---
sidebar: sidebar 
permalink: ontap-security-hardening/autonomous-ransomware-protection.html 
keywords: tr-4569, ontap hardening guide, security, ARP, fpolicy, UBA, ransomware, machine learning, volume workloads, entropy 
summary: 'La funzionalità di apprendimento automatico on-box di ONTAP rileva il ransomware in base ai workload dei volumi e all"entropia.' 
---
= Protezione autonoma dal ransomware di ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per integrare gli analytics sul comportamento degli utenti per la sicurezza del workload di storage, la protezione autonoma da ransomware di ONTAP analizza i carichi di lavoro dei volumi e l'entropia per rilevare il ransomware ed effettua una Snapshot e informa l'amministratore quando si sospetta un attacco.

Oltre al rilevamento e alla prevenzione del ransomware che utilizzano l'analisi comportamentale esterna degli utenti FPolicy (UBA) con NetApp Cloud Insights / Cloud Secure e l'ecosistema di partner NetApp FPolicy, ONTAP 9.10.1 introduce una protezione autonoma dal ransomware. La protezione autonoma dal ransomware ONTAP utilizza una funzionalità integrata di machine learning (ML) on-box che analizza l'attività del carico di lavoro dei volumi più l'entropia dei dati per rilevare automaticamente il ransomware. Esegue il monitoraggio di attività diverse da quelle di UBA, in modo da rilevare attacchi che UBA non ha.

Per informazioni più dettagliate su questa funzionalità, vedere link:../ransomware-solutions/ransomware-overview.html["Soluzioni NetApp per il ransomware"^] o link:../anti-ransomware/use-cases-restrictions-concept.html["Documentazione sulla protezione autonoma dal ransomware di ONTAP"^].
