---
sidebar: sidebar 
permalink: ontap-security-hardening/autosupport.html 
keywords: tr-4569, ontap hardening guide, security, proactively monitor, NetApp Digital Advisor, logs, context-sensitive data, configuration and status data, performance data, use https 
summary: La funzione AutoSupport di ONTAP consente di monitorare in modo proattivo lo stato del sistema. 
---
= NetApp AutoSupport
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La funzione AutoSupport di ONTAP consente di monitorare in modo proattivo lo stato di salute del sistema e di inviare automaticamente messaggi e dettagli al supporto tecnico NetApp, al team di supporto interno dell'organizzazione o a un partner di supporto. Per impostazione predefinita, i messaggi AutoSupport inviati al supporto tecnico NetApp vengono abilitati quando il sistema di archiviazione viene configurato per la prima volta. Inoltre, AutoSupport inizia a inviare messaggi al supporto tecnico NetApp 24 ore dopo l'attivazione. Questo periodo di 24 ore è configurabile. Per sfruttare la comunicazione al team di supporto interno di un'organizzazione, è necessario completare la configurazione dell'host di posta.

Solo l'amministratore del cluster può eseguire la gestione (configurazione) di AutoSupport. L'amministratore della SVM non ha accesso a AutoSupport. La funzione AutoSupport può essere disattivata. Tuttavia, NetApp consiglia di abilitarla perché AutoSupport consente di velocizzare l'identificazione e la risoluzione dei problemi in caso di problemi nel sistema storage. Per impostazione predefinita, il sistema raccoglie le informazioni AutoSupport e le memorizza localmente anche se si disattiva AutoSupport.

Per ulteriori informazioni sui messaggi AutoSupport, inclusi i contenuti nei vari messaggi e le destinazioni in cui vengono inviati diversi tipi di messaggi, consultare la link:https://activeiq.netapp.com/custom-dashboard/search["Consulente digitale NetApp"^] documentazione.

I messaggi AutoSupport contengono dati riservati, inclusi, a titolo esemplificativo, i seguenti elementi:

* File di log
* Dati sensibili al contesto relativi a sottosistemi specifici
* Dati di configurazione e stato
* Dati sulle performance


AutoSupport supporta HTTPS e SMTP per i protocolli di trasporto. A causa della natura sensibile dei messaggi AutoSupport, NetApp consiglia vivamente di utilizzare HTTPS come protocollo di trasporto predefinito per l'invio di messaggi AutoSupport al supporto NetApp.

Inoltre, è necessario utilizzare il `system node autosupport modify` comando per specificare gli obiettivi dei dati AutoSupport (ad esempio, il supporto tecnico di NetApp, le operazioni interne di un'organizzazione o i partner). Questo comando consente inoltre di specificare quali dettagli AutoSupport specifici inviare (ad esempio, dati sulle prestazioni, file di log e così via).

Per disattivare completamente AutoSupport, utilizzare il `system node autosupport modify -state disable` comando.
