---
sidebar: sidebar 
permalink: ontap-security-hardening/create-ca-signed-certificates.html 
keywords: tr-4569, ontap hardening guide, security, self-signed, digital certificates, CA-signed digital certificates, generate-csr, security certificate install 
summary: 'Creare un certificato digitale con firma CA da utilizzare per l"autenticazione del cluster o della SVM come server SSL.' 
---
= Creare un certificato digitale con firma CA
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per molte organizzazioni, il certificato digitale autofirmato per l'accesso Web a ONTAP non è conforme ai criteri di InfoSec. Nei sistemi di produzione, è NetApp consigliabile installare un certificato digitale firmato CA da utilizzare per l'autenticazione del cluster o della SVM come server SSL.

È possibile utilizzare il `security certificate generate-csr` comando per generare una richiesta di firma del certificato (CSR) e il `security certificate install` comando per installare il certificato ricevuto dalla CA.

.Fasi
. Per creare un certificato digitale firmato dalla CA dell'organizzazione, procedere come segue:
+
.. Generare una CSR.
.. Seguire la procedura dell'organizzazione per richiedere un certificato digitale utilizzando la CSR alla CA dell'organizzazione. Ad esempio, utilizzando l'interfaccia Web servizi certificati di Microsoft Active Directory, accedere a `<CA_server_name>/certsrv` e richiedere un certificato.
.. Installare il certificato digitale in ONTAP.



