---
sidebar: sidebar 
permalink: authentication-access-control/enable-webauthn-mfa-task.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key, enable, system manager 
summary: È possibile attivare WebAuthn MFA per gli utenti di System Manager. 
---
= Abilitare WebAuthn MFA per utenti o gruppi di Gestione di sistema di ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In qualità di amministratore ONTAP, è possibile abilitare WebAuthn MFA per un utente o un gruppo di Gestione di sistema aggiungendo un nuovo utente o gruppo con l'opzione MFA WebAuthn attivata o attivando l'opzione per un utente o un gruppo esistente.


NOTE: Dopo aver attivato WebAuthn MFA come secondo metodo di autenticazione per un utente o un gruppo, all'utente (o a tutti gli utenti di quel gruppo) verrà richiesto di registrare un dispositivo hardware FIDO2 al successivo accesso a System Manager. Questa registrazione viene gestita dal sistema operativo locale dell'utente e consiste generalmente nell'inserire la chiave di protezione, creare una chiave di accesso e toccare la chiave di protezione (se supportata).



== Attivare WebAuthn MFA quando si crea un nuovo utente o gruppo

È possibile creare un nuovo utente o gruppo con WebAuthn MFA attivato utilizzando Gestione di sistema o la CLI di ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. Selezionare *Cluster > Settings* (cluster > Impostazioni).
. Selezionare l'icona a forma di freccia accanto a *utenti e ruoli*.
. Selezionare *Aggiungi* in *utenti*.
. Specificare un nome utente o gruppo e selezionare un ruolo nel menu a discesa *ruolo*.
. Specificare un metodo di accesso e una password per l'utente o il gruppo.
+
WebAuthn MFA supporta i metodi di accesso "password", "dominio" o "nsswitch" per gli utenti e "dominio" o "nsswitch" per i gruppi.

. Nella colonna *MFA per HTTP*, selezionare *abilitato*.
. Selezionare *Salva*.


--
.CLI
--
. Creare un nuovo utente o gruppo con WebAuthn MFA attivato.
+
Nell'esempio seguente, WebAuthn MFA viene attivato scegliendo "publickey" per il secondo metodo di autenticazione:

+
[source, console]
----
security login create -user-or-group-name <user_or_group_name> \
                     -authentication-method domain \
                     -second-authentication-method publickey \
                     -application http \
                     -role admin
----


--
====


== Abilitare WebAuthn MFA per un utente o un gruppo esistente

È possibile attivare WebAuthn MFA per un utente o un gruppo esistente.

[role="tabbed-block"]
====
.System Manager
--
. Selezionare *Cluster > Settings* (cluster > Impostazioni).
. Selezionare l'icona a forma di freccia accanto a *utenti e ruoli*.
. Nell'elenco degli utenti e dei gruppi, selezionare il menu delle opzioni per l'utente o il gruppo che si desidera modificare.
+
WebAuthn MFA supporta i metodi di accesso "password", "dominio" o "nsswitch" per gli utenti e "dominio" o "nsswitch" per i gruppi.

. Nella colonna *MFA per HTTP* per quell'utente, selezionare *attivato*.
. Selezionare *Salva*.


--
.CLI
--
. Modificare un utente o un gruppo esistente per abilitare WebAuthn MFA per tale utente o gruppo.
+
Nell'esempio seguente, WebAuthn MFA viene attivato scegliendo "publickey" per il secondo metodo di autenticazione:

+
[source, console]
----
security login modify -user-or-group-name <user_or_group_name> \
                     -authentication-method domain \
                     -second-authentication-method publickey \
                     -application http \
                     -role admin
----


--
====


== Scopri di più

Visitare le pagine del manuale di ONTAP per i seguenti comandi:

* https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["creazione dell'accesso di sicurezza"^]
* https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["modifica dell'accesso di sicurezza"^]

