---
sidebar: sidebar 
permalink: authentication-access-control/webauthn-mfa-overview.html 
keywords: mfa, multi-factor, multifactor, authentication, authorization, webauthn, FIDO2, hardware key 
summary: A partire da ONTAP 9.16,1, è possibile attivare WebAuthn MFA per gli utenti ONTAP. 
---
= Scopri l'autenticazione a più fattori WebAuthn per gli utenti di ONTAP System Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.16.1, gli amministratori possono abilitare WebAuthn l'autenticazione a più fattori (MFA) per gli utenti che accedono a System Manager. Ciò consente l'accesso a System Manager utilizzando una chiave FIDO2 (come una YubiKey) come seconda forma di autenticazione. Per impostazione predefinita, la WebAuthn MFA è disabilitata per i nuovi ed esistenti utenti ONTAP.

[NOTE]
====
A partire da ONTAP 9.19.1, devi usare il parametro  `-rp-domains` nel comando delle impostazioni globali WebAuthn. Questo permette di limitare esplicitamente l'insieme di domini Relying Party (RP) consentiti durante l'autenticazione a più fattori WebAuthn (FIDO2) in System Manager. Se stai aggiornando a ONTAP 9.19.1 da ONTAP 9.16.1 fino a 9.18.1, vedi link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-Issues/CONTAP-597688["CONTAP-597688"] per maggiori informazioni.

====
WebAuthn MFA è supportato per utenti e gruppi che utilizzano i seguenti tipi di autenticazione per il primo metodo di autenticazione:

* Utenti: Password, dominio o nsswitch
* Gruppi: Dominio o nsswitch


Dopo aver attivato WebAuthn MFA come secondo metodo di autenticazione per un utente, all'utente viene richiesto di registrare un autenticatore hardware al momento dell'accesso a System Manager. Dopo la registrazione, la chiave privata viene memorizzata nell'autenticatore e la chiave pubblica viene memorizzata in ONTAP.

ONTAP supporta una credenziale WebAuthn per utente. Se un utente perde un autenticatore e deve sostituirlo, l'amministratore ONTAP deve eliminare la credenziale WebAuthn per l'utente in modo che l'utente possa registrare un nuovo autenticatore al successivo accesso.


NOTE: Gli utenti che hanno attivato WebAuthn MFA come secondo metodo di autenticazione devono utilizzare l'FQDN (ad esempio, "https://myontap.example.com"[]) invece dell'indirizzo IP (ad esempio, "https://192.168.100.200"[]) per accedere a System Manager. Per gli utenti con WebAuthn MFA attivato, i tentativi di accesso a System Manager utilizzando l'indirizzo IP vengono rifiutati.
