---
sidebar: sidebar 
permalink: ransomware-solutions/ransomware-snaplock-tamperproof-snapshots.html 
keywords: tr-4572, technical report, ransomware, protect, protection, netapp ransomware protection, netapp tr, ontap tr 
summary: La protezione dal ransomware di NetApp include SnapLock, che si è dimostrata altamente efficace nella salvaguardia dalle minacce ransomware. 
---
= SnapLock e snapshot a prova di manomissione per la protezione dal ransomware
:allow-uri-read: 


[role="lead"]
Un'arma vitale nell'arsenale Snap di NetApp è SnapLock, che si è dimostrato altamente efficace nel proteggere dalle minacce ransomware. Prevenendo la cancellazione non autorizzata dei dati, SnapLock fornisce un ulteriore livello di sicurezza, garantendo che i dati critici rimangano intatti e accessibili anche in caso di attacchi dannosi.



== Conformità SnapLock

SnapLock Compliance (SLC) fornisce una protezione indelebile dei tuoi dati. SLC impedisce l'eliminazione dei dati anche quando un amministratore tenta di reinizializzare l'array. A differenza di altri prodotti della concorrenza, SnapLock Compliance non è vulnerabile agli attacchi di social engineering attraverso i team di supporto di questi prodotti. I dati protetti da SnapLock Compliance Volumes sono ripristinabili fino a quando tali dati non hanno raggiunto la data di scadenza.

Per abilitare SnapLock, link:../system-admin/manage-licenses-concept.html["ONTAP uno"]è necessaria una  licenza.

.Scopri di più
* link:../snaplock/index.html["Documentazione SnapLock"]




== Snapshot a prova di manomissione

Le copie Snapshot a prova di manomissione (TPS) offrono un modo rapido e pratico per proteggere i dati da atti dannosi. A differenza di SnapLock Compliance, il TPS viene in genere utilizzato sui sistemi primari in cui l'utente può proteggere i dati per un determinato periodo di tempo e lasciato localmente per ripristini rapidi o in cui i dati non devono essere replicati dal sistema primario. TPS utilizza le tecnologie SnapLock per impedire l'eliminazione dello snapshot primario anche da parte di un amministratore ONTAP che utilizza lo stesso periodo di scadenza della conservazione SnapLock. L'eliminazione degli Snapshot viene evitata anche se il volume non è abilitato per SnapLock, sebbene gli snapshot non abbiano la stessa natura indelebile dei volumi SnapLock Compliance.

Per rendere gli snapshot a prova di manomissione, è necessaria una link:../system-admin/manage-licenses-concept.html["ONTAP uno"] licenza.

.Scopri di più
* link:../snaplock/snapshot-lock-concept.html["Bloccare una snapshot per la protezione dagli attacchi ransomware"].

