---
permalink: s3-config/create-s3-service-data-policy-task.html 
sidebar: sidebar 
keywords: create, s3, service, data, policy 
summary: È possibile creare policy di servizio per i dati S3 e i servizi di gestione. Per abilitare il traffico dati S3 su LIF, è necessaria una policy dei dati del servizio S3. 
---
= Creare la politica dei dati del servizio ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare policy di servizio per i dati S3 e i servizi di gestione. Per abilitare il traffico dati S3 su LIF, è necessaria una policy dei dati del servizio S3.

.A proposito di questa attività
Se si utilizzano LIF di dati e LIF di intercluster, è necessaria una policy sui dati di servizio S3. Non è necessario se si utilizzano le LIF del cluster per il caso di utilizzo del tiering locale.

Quando viene specificata una policy di servizio per una LIF, questa viene utilizzata per creare un ruolo predefinito, una policy di failover e un elenco di protocolli dati per la LIF.

Sebbene sia possibile configurare più protocolli per SVM e LIFF, è consigliabile che S3 sia l'unico protocollo per la fornitura di dati a oggetti.

.Fasi
. Impostare i privilegi su Advanced (avanzato):
+
`set -privilege advanced`

. Creare una policy sui dati del servizio:
+
`network interface service-policy create -vserver _svm_name_ -policy _policy_name_ -services data-core,data-s3-server`

+
Il `data-core` e. `data-s3-server` I servizi sono gli unici necessari per abilitare ONTAP S3, anche se è possibile includere altri servizi in base alle esigenze.


