---
permalink: s3-config/enable-client-access-from-s3-app-task.html 
sidebar: sidebar 
keywords: enable, client, access, s3 app 
summary: 'Affinché le applicazioni client S3 possano accedere al server ONTAP S3, l"amministratore di ONTAP S3 deve fornire le informazioni di configurazione all"utente S3.' 
---
= Abilitare l'accesso client da un'applicazione S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Affinché le applicazioni client S3 possano accedere al server ONTAP S3, l'amministratore di ONTAP S3 deve fornire le informazioni di configurazione all'utente S3.

.Prima di iniziare
L'applicazione client S3 deve essere in grado di eseguire l'autenticazione con il server ONTAP S3 utilizzando le seguenti versioni delle firme AWS:

* Signature versione 4, ONTAP 9.8 e versioni successive
* Signature versione 2, ONTAP 9.11.1 e versioni successive


ONTAP S3 non supporta altre versioni delle firme.

L'amministratore di ONTAP S3 deve aver creato gli utenti S3 e concesso loro le autorizzazioni di accesso, come singoli utenti o come membro di gruppo, nella policy del bucket o nella policy del server di storage a oggetti.

L'applicazione client S3 deve essere in grado di risolvere il nome del server ONTAP S3, il che richiede che l'amministratore di ONTAP S3 fornisca il nome del server S3 (FQDN) e gli indirizzi IP per le LIF del server S3.

.A proposito di questa attività
Per accedere a un bucket ONTAP S3, un utente dell'applicazione client S3 inserisce le informazioni fornite dall'amministratore di ONTAP S3.

A partire da ONTAP 9.9.1, il server ONTAP S3 supporta le seguenti funzionalità del client AWS:

* metadati degli oggetti definiti dall'utente
+
Un insieme di coppie chiave-valore può essere assegnato agli oggetti come metadati quando vengono creati usando PUT (o POST). Quando viene eseguita un'operazione GET/HEAD sull'oggetto, i metadati definiti dall'utente vengono restituiti insieme ai metadati di sistema.

* tagging degli oggetti
+
È possibile assegnare un insieme separato di coppie chiave-valore come tag per la classificazione degli oggetti. A differenza dei metadati, i tag vengono creati e letti con API REST indipendentemente dall'oggetto e implementati quando gli oggetti vengono creati o in qualsiasi momento.

+
[NOTE]
====
Per consentire ai client di ottenere e inserire informazioni di tagging, le azioni `GetObjectTagging`, `PutObjectTagging`, e. `DeleteObjectTagging` devono essere consentite utilizzando le policy di gruppo o bucket.

====


Per ulteriori informazioni, consultare la documentazione di AWS S3.

.Fasi
. Autenticare l'applicazione client S3 con il server ONTAP S3 immettendo il nome del server S3 e il certificato CA.
. Autenticare un utente sull'applicazione client S3 inserendo le seguenti informazioni:
+
** Nome server S3 (FQDN) e nome bucket
** la chiave di accesso e la chiave segreta dell'utente



