---
permalink: s3-config/enable-ontap-s3-access-remote-fabricpool-task.html 
sidebar: sidebar 
keywords: enable, ontap s3, access, remote, fabricpool tiering 
summary: 'Per utilizzare ONTAP S3 come Tier di capacità FabricPool remota (cloud), l"amministratore di ONTAP S3 deve fornire informazioni sulla configurazione del server S3 all"amministratore remoto del cluster ONTAP.' 
---
= Abilitare l'accesso ONTAP S3 per il tiering FabricPool remoto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per utilizzare ONTAP S3 come Tier di capacità FabricPool remota (cloud), l'amministratore di ONTAP S3 deve fornire informazioni sulla configurazione del server S3 all'amministratore remoto del cluster ONTAP.

.A proposito di questa attività
Per configurare i livelli cloud FabricPool sono necessarie le seguenti informazioni sul server S3:

* Nome server (FQDN)
* nome bucket
* Certificato CA
* tasto di accesso
* password (chiave di accesso segreta)


Inoltre, è necessaria la seguente configurazione di rete:

* Nel server DNS configurato per la SVM amministrativa deve essere presente una voce per il nome host del server ONTAP S3 remoto, compreso il nome FQDN del server S3 e gli indirizzi IP sui relativi LIF.
* Le LIF di intercluster devono essere configurate sul cluster locale, anche se non è richiesto il peering del cluster.


Consultare la documentazione di FabricPool sulla configurazione di ONTAP S3 come Tier cloud.

link:../fabricpool/index.html["Gestione dei Tier di storage mediante FabricPool"]
