---
permalink: s3-config/generate-access-keys-api.html 
sidebar: sidebar 
keywords: generate, ldap, s3, access keys, secret keys using API 
summary: 'Le chiavi per accedere ai client S3 possono essere rigenerate da S3 utenti utilizzando l"API.' 
---
= Consentire agli utenti LDAP o di dominio di generare le proprie chiavi di accesso a ONTAP S3
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.14.1, in qualità di amministratore ONTAP, è possibile creare ruoli personalizzati e concederli a gruppi locali o di dominio o a gruppi LDAP (Lightweight Directory Access Protocol), in modo che gli utenti appartenenti a tali gruppi possano generare le proprie chiavi di accesso e segrete per l'accesso client S3.

Devi eseguire alcuni passaggi di configurazione sulla macchina virtuale di storage in modo che sia possibile creare e assegnare il ruolo personalizzato all'utente che richiama l'API per la generazione della chiave di accesso.


NOTE: Se LDAP è disabilitato, puoi link:configure-access-ldap.html["configurare i servizi di directory esterni per l'accesso ONTAP S3"] per consentire agli utenti di generare chiavi di accesso.

.Prima di iniziare
Verificare quanto segue:

. È stata creata una macchina virtuale di storage abilitata per S3 contenente un server S3. Vedere link:../s3-config/create-svm-s3-task.html["Creare una SVM per S3"].
. È stato creato un bucket in quella VM per lo storage. Vedere link:../s3-config/create-bucket-task.html["Creare un bucket"].
. Il DNS è configurato sulla macchina virtuale di storage. Vedere link:../networking/configure_dns_services_auto.html["Configurare i servizi DNS"].
. Sulla VM di storage viene installato un certificato CA (root Certification Authority) autofirmato del server LDAP. Vedere link:../nfs-config/install-self-signed-root-ca-certificate-svm-task.html["Installare certificati CA radice autofirmati sull'SVM"].
. Un client LDAP è configurato con TLS attivato sulla macchina virtuale di storage. Vedere link:../nfs-config/create-ldap-client-config-task.html["Creare configurazioni client LDAP per l'accesso ONTAP NFS"].
. Associare la configurazione del client al Vserver. Vedere link:../nfs-config/enable-ldap-svms-task.html["Associare le configurazioni client LDAP con ONTAP NFS SVM"]. Ulteriori informazioni su `vserver services name-service ldap create` nella link:https://docs.netapp.com/us-en/ontap-cli//vserver-services-name-service-ldap-create.html["Riferimento al comando ONTAP"^].
. Se stai utilizzando una macchina virtuale per lo storage dei dati, crea un'interfaccia di rete di gestione (LIF) e una macchina virtuale, oltre a una policy di servizio per la LIF. Ulteriori informazioni su `network interface create` e `network interface service-policy create` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Riferimento al comando ONTAP"^].




== Configurare gli utenti per la generazione delle chiavi di accesso

.Fasi
[role="tabbed-block"]
====
.Utenti LDAP
--
. Specificare LDAP come _name service database_ della VM di archiviazione per il gruppo e la password per LDAP:
+
[source, cli]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Ulteriori informazioni su `vserver services name-service ns-switch modify` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-ns-switch-modify.html["Riferimento al comando ONTAP"^].

. Creare un ruolo personalizzato con accesso all'endpoint API REST per S3 utenti:
`security login rest-role create -vserver <vserver-name> -role <custom-role-name> -api "/api/protocols/s3/services/*/users" -access <access-type>`
In questo esempio, il `s3-role` Viene generato un ruolo per gli utenti sulla VM di storage `svm-1`, a cui vengono concessi tutti i diritti di accesso, lettura, creazione e aggiornamento.
+
[listing]
----
security login rest-role create -vserver svm-1 -role s3role -api "/api/protocols/s3/services/*/users" -access all
----
+
Ulteriori informazioni su `security login rest-role create` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-rest-role-create.html["Riferimento al comando ONTAP"^].

. Crea un gruppo di utenti LDAP con  `security login` comando e aggiungere il nuovo ruolo personalizzato per accedere all'endpoint dell'API REST dell'utente S3. Scopri di più su  `security login create` nel link:https://docs.netapp.com/us-en/ontap-cli//security-login-create.html["Riferimento al comando ONTAP"^] .
+
[source, cli]
----
security login create -user-or-group-name <ldap-group-name> -application http -authentication-method nsswitch -role <custom-role-name> -is-ns-switch-group yes
----
+
In questo esempio, il gruppo LDAP `ldap-group-1` viene creato in `svm-1`e il ruolo personalizzato `s3role` Viene aggiunto per accedere all'endpoint API, oltre ad abilitare l'accesso LDAP in modalità di associazione rapida.

+
[listing]
----
security login create -user-or-group-name ldap-group-1 -application http -authentication-method nsswitch -role s3role -is-ns-switch-group yes -second-authentication-method none -vserver svm-1 -is-ldap-fastbind yes
----
+
Per ulteriori informazioni, vedere link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["Utilizzare il fast bind LDAP per l'autenticazione nsswitch per le SVM ONTAP NFS"].

+
Ulteriori informazioni su `security login create` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["Riferimento al comando ONTAP"^].



L'aggiunta del ruolo personalizzato al gruppo LDAP consente agli utenti di quel gruppo un accesso limitato ONTAP  `/api/protocols/s3/services/{svm.uuid}/users` Endpoint. Invocando l'API, gli utenti del gruppo LDAP possono generare le proprie chiavi di accesso e segrete per accedere al client S3. Possono generare le chiavi solo per sé stessi e non per altri utenti.

--
.Utenti del dominio
--
. Crea un ruolo personalizzato con accesso all'endpoint API REST dell'utente S3:


[source, cli]
----
security login rest-role create -vserver <vserver-name> -role <custom-role-name> -api "/api/protocols/s3/services/*/users" -access <access-type>
----
In questo esempio, il  `s3-role` il ruolo viene generato per gli utenti sulla VM di archiviazione  `svm-1` , a cui sono concessi tutti i diritti di accesso, lettura, creazione e aggiornamento.

[listing]
----
security login rest-role create -vserver svm-1 -role s3role -api "/api/protocols/s3/services/*/users" -access all
----
Ulteriori informazioni su `security login rest-role create` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-rest-role-create.html["Riferimento al comando ONTAP"^].

. Crea un gruppo di utenti di dominio con  `security login` comando e aggiungere il nuovo ruolo personalizzato per accedere all'endpoint dell'API REST dell'utente S3. Scopri di più su  `security login create` nel link:https://docs.netapp.com/us-en/ontap-cli//security-login-create.html["Riferimento al comando ONTAP"^] .
+
[source, cli]
----
security login create -vserver <vserver-name> -user-or-group-name domain\<group-name> -application http -authentication-method domain -role <custom-role-name>
----
+
In questo esempio, il gruppo di dominio  `domain\group1` è creato in  `svm-1` e il ruolo personalizzato  `s3role` viene aggiunto per accedere all'endpoint API.

+
[listing]
----
security login create -user-or-group-name domain\group1 -application http -authentication-method domain -role s3role -vserver svm-1
----
+
Ulteriori informazioni su `security login create` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["Riferimento al comando ONTAP"^].



L'aggiunta del ruolo personalizzato al gruppo di dominio consente agli utenti di quel gruppo un accesso limitato ONTAP  `/api/protocols/s3/services/{svm.uuid}/users` Endpoint. Invocando l'API, gli utenti del gruppo di dominio possono generare le proprie chiavi di accesso e segrete per accedere al client S3. Possono generare le chiavi solo per sé stessi e non per altri utenti.

--
====


== Come utente S3 o LDAP, generare le proprie chiavi di accesso

A partire da ONTAP 9.14.1, è possibile generare le proprie chiavi di accesso e segrete per l'accesso ai client S3, se l'amministratore ha concesso il ruolo di generazione delle proprie chiavi. Puoi generare le chiavi solo per te utilizzando il seguente endpoint dell'API REST ONTAP.

.Crea un utente S3 e genera le chiavi
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti. Per ulteriori informazioni su questo endpoint, consultare il riferimento.  https://docs.netapp.com/us-en/ontap-automation/reference/api_reference.html#access-a-copy-of-the-ontap-rest-api-reference-documentation["Documentazione API"] .

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /api/protocolli/s3/servizi/{svm.uuid}/utenti 
|===
Per gli utenti di dominio, utilizzare il seguente formato per il nome utente S3:  `user@fqdn` , Dove  `fqdn` è il nome di dominio completamente qualificato del dominio.

.Esempio di arricciamento
[source, curl]
----
curl
--request POST \
--location "https://$FQDN_IP /api/protocols/s3/services/{svm.uuid}/users " \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
--data '{"name":"user1@example.com"}'
----
.Esempio di output JSON
[listing]
----
{
  "records": [
    {
      "access_key": "4KX07KF7ML8YNWY01JWG",
      "_links": {
        "next": {
          "href": "/api/resourcelink"
        },
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "user1@example.com",
      "secret_key": "<secret_key_value>"
    }
  ],
  "num_records": "1"
}

----
.Rigenera le chiavi per un utente S3
Se esiste già un utente S3, è possibile rigenerarne le chiavi di accesso e segrete. Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| TOPPA | /api/protocols/s3/services/{svm.uuid}/users/{name} 
|===
.Esempio di arricciamento
[source, curl]
----
curl
--request PATCH \
--location "https://$FQDN_IP /api/protocols/s3/services/{svm.uuid}/users/{name} " \
--include \
--header "Authorization: Basic $BASIC_AUTH" \
--data '{"regenerate_keys":"True"}'
----
.Esempio di output JSON
[listing]
----
{
  "records": [
    {
      "access_key": "DX12U609DMRVD8U30Z1M",
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "user1@example.com",
      "secret_key": "<secret_key_value>"
    }
  ],
  "num_records": "1"
}

----