---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: tr-4814, ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: ONTAP supporta lo storage a oggetti S3 per ambienti on-premise a partire da ONTAP 9.8. Cloud Volumes ONTAP supporta lo storage a oggetti S3 per ambienti cloud a partire da ONTAP 9.9.1. 
---
= Supporto della versione e della piattaforma ONTAP per lo storage a oggetti S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo storage a oggetti S3 è supportato su tutte le piattaforme AFF, FAS e ONTAP Select con ONTAP 9,8 e versioni successive.

Come per altri protocolli come FC, iSCSI, NFS, NVMe_of e SMB, S3 richiede l'installazione di una licenza per poter essere utilizzata in ONTAP. La licenza S3 è una licenza a costo zero, ma deve essere installata sui sistemi che eseguono l'aggiornamento a ONTAP 9,8. La licenza S3 può essere scaricata dal link:https://mysupport.netapp.com/site/systems/master-license-keys/ontaps3["Pagina chiavi di licenza master"^] sito di assistenza NetApp.

I nuovi sistemi ONTAP 9,8 e successivi dispongono della licenza S3 preinstallata.



== Cloud Volumes ONTAP

ONTAP S3 è configurato e funziona allo stesso modo in Cloud Volumes ONTAP come negli ambienti on-premise, con un'eccezione:

* Quando si creano i bucket in Cloud Volumes ONTAP, occorre seguire la procedura CLI per assicurarsi che il volume FlexGroup sottostante utilizzi solo aggregati da un singolo nodo. L'utilizzo di aggregati di nodi multipli avrà un impatto sulle performance, perché i nodi si troveranno in zone di disponibilità geograficamente separate e soggetti a problemi di latenza.


|===
| Provider di cloud | Versione di ONTAP 


| Azure | ONTAP 9.9.1 e versioni successive 


| AWS | ONTAP 9.11.0 e versioni successive 


| Google Cloud | ONTAP 9.12.1 e versioni successive 
|===


== Amazon FSX per NetApp ONTAP

Lo storage a oggetti S3 è supportato su Amazon FSX per i servizi NetApp utilizzando ONTAP 9,11 e versioni successive.



== Supporto S3 con MetroCluster

A partire da ONTAP 9.14.1, è possibile abilitare un server per lo storage a oggetti S3 su una SVM in un aggregato con mirroring nelle configurazioni IP e FC di MetroCluster.

A partire da ONTAP 9.12.1, è possibile abilitare un server di storage a oggetti S3 su una SVM in un aggregato senza mirror in una configurazione IP MetroCluster. Per ulteriori informazioni sulle limitazioni degli aggregati senza mirror nelle configurazioni MetroCluster IP, vedere link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html["Considerazioni per gli aggregati senza mirror"^].



== Anteprima pubblica S3 in ONTAP 9.7

In ONTAP 9.7, lo storage a oggetti S3 è stato introdotto come anteprima pubblica. Tale versione non era destinata agli ambienti di produzione e non sarà più aggiornata a partire da ONTAP 9.8. Solo ONTAP 9.8 e versioni successive supportano lo storage a oggetti S3 negli ambienti di produzione.

I bucket S3 creati con l'anteprima pubblica 9.7 possono essere utilizzati in ONTAP 9.8 e versioni successive, ma non possono sfruttare i miglioramenti delle funzionalità. Se si dispone di bucket creati con l'anteprima pubblica 9.7, è necessario migrare il contenuto di tali bucket in 9.8 bucket per il supporto delle funzionalità, la sicurezza e i miglioramenti delle performance.
