---
permalink: s3-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: decide, provision, new s3, storage, capacity 
summary: Prima di creare un nuovo bucket S3, è necessario decidere se posizionarlo in una SVM nuova o esistente. Questa decisione determina il tuo flusso di lavoro. 
---
= Decidere dove eseguire il provisioning della nuova capacità di storage di ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di creare un nuovo bucket S3, è necessario decidere se posizionarlo in una SVM nuova o esistente. Questa decisione determina il tuo flusso di lavoro.

.Scelte
* Se si desidera eseguire il provisioning di un bucket in un nuovo SVM o SVM non abilitato per S3, completare la procedura descritta nei seguenti argomenti.
+
link:create-svm-s3-task.html["Creare una SVM per S3"]

+
link:create-bucket-task.html["Creare un bucket per S3"]

+
Sebbene S3 possa coesistere in una SVM con NFS e SMB, è possibile scegliere di creare una nuova SVM se si verifica una delle seguenti condizioni:

+
** Si sta abilitando S3 su un cluster per la prima volta.
** Esistono SVM in un cluster in cui non si desidera attivare il supporto S3.
** Si dispone di una o più SVM abilitate per S3 in un cluster e si desidera un altro server S3 con caratteristiche di performance diverse. Dopo aver attivato S3 sulla SVM, procedere con il provisioning di un bucket.


* Se si desidera eseguire il provisioning del bucket iniziale o di un bucket aggiuntivo su una SVM abilitata S3 esistente, completare la procedura descritta nel seguente argomento.
+
link:create-bucket-task.html["Creare un bucket per S3"]


