---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: 'È necessario creare un volume SnapLock per i file o le snapshot che si desidera impostare sullo stato WORM. A partire da ONTAP 9.10.1, qualsiasi volume creato, indipendentemente dal tipo di aggregato, viene creato per impostazione predefinita come volume non SnapLock. È necessario utilizzare questa `-snaplock-type` opzione per creare esplicitamente un volume SnapLock specificando conformità o Enterprise come tipo di SnapLock. Per impostazione predefinita, il tipo di SnapLock è impostato su `non-snaplock`.' 
---
= Creare e montare volumi SnapLock in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare un volume SnapLock per i file o le snapshot che si desidera impostare sullo stato WORM. A partire da ONTAP 9.10.1, qualsiasi volume creato, indipendentemente dal tipo di aggregato, viene creato per impostazione predefinita come volume non SnapLock. È necessario utilizzare questa `-snaplock-type` opzione per creare esplicitamente un volume SnapLock specificando conformità o Enterprise come tipo di SnapLock. Per impostazione predefinita, il tipo di SnapLock è impostato su `non-snaplock`.

.Prima di iniziare
* L'aggregato SnapLock deve essere online.
* Si dovrebbe link:../system-admin/manage-license-task.html["Verificare che sia installata una licenza SnapLock"]. Se una licenza SnapLock non è installata sul nodo, è necessario link:../system-admin/install-license-task.html["installare"] farlo. Questa licenza è inclusa con link:../system-admin/manage-licenses-concept.html["ONTAP uno"]. Prima di ONTAP One, la licenza SnapLock era inclusa nel pacchetto sicurezza e conformità. Il bundle Security and Compliance non è più offerto, ma è ancora valido. Sebbene non sia attualmente necessario, i clienti esistenti possono scegliere di link:../system-admin/download-nlf-task.html["Eseguire l'aggiornamento a ONTAP One"].
* link:../snaplock/initialize-complianceclock-task.html["È necessario inizializzare il Compliance Clock sul nodo"].


.A proposito di questa attività
Con le autorizzazioni SnapLock appropriate, è possibile distruggere o rinominare un volume Enterprise in qualsiasi momento. Non è possibile distruggere un volume Compliance fino allo scadere del periodo di conservazione. Non è mai possibile rinominare un volume Compliance.

È possibile clonare i volumi SnapLock, ma non i file su un volume SnapLock. Il volume clone sarà dello stesso tipo di SnapLock del volume padre.

[NOTE]
====
I LUN non sono supportati nei volumi SnapLock. I LUN sono supportati nei volumi SnapLock solo negli scenari in cui le snapshot create su un volume non SnapLock vengono trasferite in un volume SnapLock per essere protette come parte della relazione del vault di SnapLock. I LUN non sono supportati nei volumi SnapLock in lettura/scrittura. Gli snapshot a prova di manomissione sono tuttavia supportati sia sui volumi di origine di SnapMirror che sui volumi di destinazione che contengono LUN.

====
Eseguire questa attività utilizzando Gestione di sistema di ONTAP o l'interfaccia utente di ONTAP.

[role="tabbed-block"]
====
.System Manager
--
A partire da ONTAP 9.12.1, è possibile utilizzare Gestione sistema per creare un volume SnapLock.

.Fasi
. Selezionare *Storage > Volumes* (Storage > volumi) e fare clic su *Add* (Aggiungi).
. Nella finestra *Add Volume* (Aggiungi volume), fare clic su *More Options* (altre opzioni).
. Inserire le informazioni sul nuovo volume, inclusi il nome e le dimensioni del volume.
. Selezionare *Enable SnapLock* (attiva conformità) e scegliere il tipo di SnapLock, Compliance (conformità) o Enterprise (Azienda).
. Nella sezione *Auto-commit Files*, selezionare *Modified* e inserire il tempo in cui un file deve rimanere invariato prima che venga automaticamente salvato. Il valore minimo è di 5 minuti e il valore massimo è di 10 anni.
. Nella sezione *conservazione dei dati*, selezionare il periodo di conservazione minimo e massimo.
. Selezionare il periodo di conservazione predefinito.
. Fare clic su *Save* (Salva).
. Selezionare il nuovo volume nella pagina *Volumes* per verificare le impostazioni SnapLock.


--
.CLI
--
. Creare un volume SnapLock:
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -snaplock-type <compliance|enterprise>
----
+
Ulteriori informazioni su `volume create` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Riferimento al comando ONTAP"^]. Le seguenti opzioni non sono disponibili per i volumi SnapLock: `-nvfail`, `-atime-update`, `-is-autobalance-eligible`, `-space-mgmt-try-first` E `vmalign`.

+
Il seguente comando crea un SnapLock `Compliance` volume denominato `vol1` acceso `aggr1` acceso `vs1`:

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== Montare un volume SnapLock

È possibile montare un volume SnapLock su un percorso di giunzione nello spazio dei nomi SVM per l'accesso al client NAS.

.Di cosa hai bisogno
Il volume SnapLock deve essere online.

.A proposito di questa attività
* È possibile montare un volume SnapLock solo sotto la directory principale della SVM.
* Non è possibile montare un volume normale sotto un volume SnapLock.


.Fasi
. Montare un volume SnapLock:
+
`*volume mount -vserver _SVM_name_ -volume _volume_name_ -junction-path _path_*`

+
Ulteriori informazioni su `volume mount` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-mount.html["Riferimento al comando ONTAP"^].

+
Il seguente comando consente di montare un volume SnapLock denominato `vol1` al percorso di giunzione `/sales` in `vs1` spazio dei nomi:

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

