---
permalink: snaplock/implement-privileged-delete-functionality-task.html 
sidebar: sidebar 
keywords: delete, worm, file, priveleged, delete, enterprise, mode, retention, period 
summary: È possibile utilizzare la funzione di eliminazione con privilegi per eliminare i file WORM in modalità Enterprise durante il periodo di conservazione. 
---
= Eliminare i file WORM in modalità Enterprise
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la funzione di eliminazione con privilegi per eliminare i file WORM in modalità Enterprise durante il periodo di conservazione.

.Di cosa hai bisogno
* Per eseguire questa attività, è necessario essere un amministratore di SnapLock.
* È necessario aver creato un registro di controllo di SnapLock e attivato la funzione di eliminazione con privilegi sul volume aziendale.


.A proposito di questa attività
Non è possibile utilizzare un'operazione di eliminazione con privilegi per eliminare un file WORM scaduto. È possibile utilizzare `volume file retention show` Per visualizzare il tempo di conservazione del file WORM che si desidera eliminare. Per ulteriori informazioni, vedere la pagina man del comando.

.Fase
. Eliminare un file WORM su un volume Enterprise:
+
`*volume file privileged-delete -vserver _SVM_name_ -file _file_path_*`

+
Il seguente comando elimina il file `/vol/dataVol/f1` Su SVM``SVM1``:

+
[listing]
----
SVM1::> volume file privileged-delete -file /vol/dataVol/f1
----

