---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, compliance clock, initialize, worm, retention, period, node, ntp, reset, resynchronize 
summary: Il SnapLock ComplianceClock garantisce la protezione da manomissioni che potrebbero alterare il periodo di conservazione dei file WORM. È necessario inizializzare il clock di conformità del sistema su ogni nodo che ospita un aggregato SnapLock.  
---
= Inizializza l'orologio di conformità ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock utilizza _Volume Compliance Clock_ per evitare manomissioni che potrebbero alterare il periodo di conservazione dei file WORM. È necessario prima inizializzare il _system ComplianceClock_ su ogni nodo che ospita un aggregato SnapLock.

A partire da ONTAP 9.14.1, è possibile inizializzare o reinizializzare l'orologio di conformità del sistema quando non sono presenti SnapLock volumi o non sono presenti volumi con il blocco snapshot abilitato. La possibilità di reinizializzare consente agli amministratori di sistema di reimpostare l'orologio di conformità del sistema nei casi in cui potrebbe essere stato inizializzato in modo errato o per correggere la deriva dell'orologio sul sistema. In ONTAP 9.13.1 e versioni precedenti, dopo aver inizializzato l'orologio di conformità su un nodo, non è possibile inizializzarlo nuovamente.

.Prima di iniziare
Per reinizializzare il Compliance Clock:

* Tutti i nodi nel cluster devono essere in stato integro.
* Tutti i volumi devono essere online.
* Non possono essere presenti volumi nella coda di ripristino.
* Non può essere presente alcun volume SnapLock.
* Non può essere presente alcun volume con blocco snapshot attivato.


Requisiti generali per l'inizializzazione dell'orologio di conformità:

* Per eseguire questa attività, è necessario essere un amministratore del cluster.
* link:../system-admin/install-license-task.html["La licenza SnapLock deve essere installata sul nodo"].


.A proposito di questa attività
L'ora del Compliance Clock del sistema viene ereditata dal _Volume Compliance Clock_, quest'ultimo dei quali controlla il periodo di conservazione dei file WORM sul volume. Il clock di conformità del volume viene inizializzato automaticamente quando si crea un nuovo volume SnapLock.

[NOTE]
====
L'impostazione iniziale dell'orologio di conformità del sistema si basa sull'orologio di sistema hardware corrente. Per questo motivo, è necessario verificare che l'ora e il fuso orario del sistema siano corretti prima di inizializzare l'orologio di conformità del sistema su ciascun nodo. Dopo aver inizializzato l'orologio di conformità del sistema su un nodo, non sarà possibile inizializzarlo nuovamente quando sono presenti volumi SnapLock o volumi con blocco abilitato.

====
.Fasi
È possibile utilizzare la CLI di ONTAP per inizializzare l'orologio di conformità oppure, a partire da ONTAP 9.12.1, utilizzare Gestione sistema per inizializzare l'orologio di conformità.

[role="tabbed-block"]
====
.System Manager
--
. Accedere a *Cluster > Panoramica*.
. Nella sezione *Nodi*, selezionare *Inizializza SnapLock Compliance Clock*.
. Per visualizzare la colonna *Compliance Clock* e per verificare che la Compliance Clock sia inizializzata, nella sezione *Cluster > Panoramica > Nodi*, selezionare *Mostra/Nascondi* e selezionare *SnapLock Compliance Clock*.


--
--
.CLI
. Inizializzare l'orologio di conformità del sistema:
+
`snaplock compliance-clock initialize -node _node_name_`

+
Il seguente comando inizializza il Compliance Clock del sistema su `node1`:

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
+
Ulteriori informazioni su `snaplock compliance-clock initialize` nella link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-initialize.html["Riferimento al comando ONTAP"^].

. Quando richiesto, confermare che l'orologio di sistema è corretto e che si desidera inizializzare l'orologio di conformità:
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. Ripetere questa procedura per ogni nodo che ospita un aggregato SnapLock.


--
====


== Abilitare la risincronizzazione del clock di conformità per un sistema configurato con NTP

È possibile abilitare la funzionalità di sincronizzazione dell'orologio SnapLock Compliance quando è configurato un server NTP.

.Prima di iniziare
* Questa funzione è disponibile solo al livello di privilegio avanzato.
* Per eseguire questa attività, è necessario essere un amministratore del cluster.
* link:../system-admin/install-license-task.html["La licenza SnapLock deve essere installata sul nodo"].
* Questa funzione è disponibile solo per le piattaforme Cloud Volumes ONTAP, ONTAP Select e VSIM.


.A proposito di questa attività
Quando il demone dell'orologio sicuro SnapLock rileva una differenza di orario superiore alla soglia, ONTAP utilizza l'ora di sistema per reimpostare sia l'orologio di conformità di sistema che quello del volume. Un periodo di 24 ore è impostato come soglia per la differenza di orario. L'orologio di conformità di sistema si sincronizza con l'orologio di sistema solo se la differenza di orario supera un giorno.

Il demone dell'orologio sicuro SnapLock rileva una discrepanza e cambia l'orologio di conformità sull'ora di sistema. Qualsiasi tentativo di modificare l'ora di sistema per forzare l'orologio di conformità a sincronizzarsi con l'ora di sistema fallisce, perché l'orologio di conformità si sincronizza con l'ora di sistema solo se quest'ultima è sincronizzata con l'ora NTP.

.Fasi
. Abilitare la funzionalità di sincronizzazione dell'orologio SnapLock Compliance quando è configurato un server NTP:
+
`snaplock compliance-clock ntp`

+
Il seguente comando abilita la funzionalità di sincronizzazione dell'orologio di conformità del sistema:

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
+
Ulteriori informazioni su `snaplock compliance-clock ntp modify` nella link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-modify.html["Riferimento al comando ONTAP"^].

. Quando richiesto, verificare che i server NTP configurati siano attendibili e che il canale di comunicazione sia sicuro per abilitare la funzione:
. Verificare che la funzione sia attivata:
+
`snaplock compliance-clock ntp show`

+
Il seguente comando verifica che la funzionalità di sincronizzazione dell'orologio di conformità del sistema sia abilitata:

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----
+
Ulteriori informazioni su `snaplock compliance-clock ntp show` nella link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-show.html["Riferimento al comando ONTAP"^].


