---
permalink: snaplock/move-snaplock-volume-concept.html 
sidebar: sidebar 
keywords: move, snaplock, volume, aggregate, security, role, enterprise, compliance, create, administrator, support, user, cluster, destination, command 
summary: A partire da ONTAP 9.8, è possibile spostare un volume SnapLock in un aggregato di destinazione dello stesso tipo, da Enterprise a Enterprise o Compliance a Compliance. Per spostare un volume SnapLock, è necessario assegnare il ruolo di protezione SnapLock. 
---
= Spostare un volume SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.8, è possibile spostare un volume SnapLock in un aggregato di destinazione dello stesso tipo, da Enterprise a Enterprise o Compliance a Compliance. Per spostare un volume SnapLock, è necessario assegnare il ruolo di protezione SnapLock.



== Creare un account amministratore di sicurezza SnapLock

Per eseguire lo spostamento di un volume SnapLock, è necessario disporre dei privilegi di amministratore della sicurezza di SnapLock. Questo privilegio viene concesso con il ruolo _SnapLock_, introdotto in ONTAP 9.8. Se non è stato ancora assegnato tale ruolo, è possibile chiedere all'amministratore del cluster di creare un utente di protezione SnapLock con questo ruolo di protezione SnapLock.

.Prima di iniziare
* Per eseguire questa attività, è necessario essere un amministratore del cluster.
* È necessario aver effettuato l'accesso con una connessione sicura (SSH, console o ZAPI).


.A proposito di questa attività
Il ruolo SnapLock è associato alla SVM amministrativa, a differenza del ruolo vsadmin-snaplock, associato alla SVM dei dati.

.Fase
. Creare un account amministratore SVM con il ruolo di amministratore di SnapLock:
+
`*security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_*`

+
Il seguente comando attiva l'account amministratore SVM `SnapLockAdmin` con il predefinito `snaplock` Ruolo per accedere a SVM di amministrazione `cluster1` utilizzo di una password:

+
[listing]
----
cluster1::> security login create -vserver cluster1 -user-or-group-name SnapLockAdmin -application ssh -authmethod password -role snaplock
----




== Spostare un volume SnapLock

È possibile utilizzare `volume move` Comando per spostare un volume SnapLock in un aggregato di destinazione.

.Prima di iniziare
* È necessario aver creato un registro di controllo protetto da SnapLock prima di eseguire lo spostamento del volume SnapLock.
+
link:create-audit-log-task.html["Creare un registro di controllo"].

* Se si utilizza una versione di ONTAP precedente a ONTAP 9.10.1, l'aggregato di destinazione deve essere dello stesso tipo di SnapLock del volume SnapLock che si desidera spostare, ovvero Compliance to Compliance o Enterprise to Enterprise. A partire da ONTAP 9.10.1, questa restrizione viene rimossa e un aggregato può includere volumi Compliance e Enterprise SnapLock, oltre a volumi non SnapLock.
* Devi essere un utente con il ruolo di sicurezza SnapLock.


.Fasi
. Utilizzando una connessione sicura, accedere alla LIF di gestione del cluster di ONTAP:
+
`*ssh snaplock_user@cluster_mgmt_ip*`

. Spostamento di un volume SnapLock:
+
`*volume move start -vserver _SVM_name_ -volume _SnapLock_volume_name_ -destination-aggregate _destination_aggregate_name_*`

. Controllare lo stato dell'operazione di spostamento del volume:
+
`*volume move show -volume _SnapLock_volume_name_ -vserver _SVM_name_ -fields volume,phase,vserver*`


