---
permalink: nfs-trunking/adapt-exports-overview.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, adapt, single-path 
summary: 'È possibile adattare un"esportazione NFS a percorso singolo (non trunked) esistente per utilizzare il trunking.' 
---
= Adattamento della panoramica delle esportazioni a percorso singolo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile adattare un'esportazione NFSv4,1 a percorso singolo (non trunked) esistente per utilizzare il trunking. I client con funzionalità trunking possono trarre vantaggio da prestazioni migliorate non appena il trunking viene abilitato sul server, a condizione che i prerequisiti del server e del client siano soddisfatti.

L'adattamento di un'esportazione a percorso singolo per il trunking consente di mantenere i set di dati esportati in volumi e SVM esistenti. A tale scopo, è necessario abilitare il trunking sul server NFS, aggiornare la configurazione di rete ed esportarla e rimontare la condivisione esportata sui client.

L'attivazione del trunking ha l'effetto di riavviare il server. I client VMware devono quindi rimontare i datastore esportati, mentre i client Linux devono rimontare i volumi esportati con `max_connect` opzione.
