---
permalink: nfs-trunking/prepare-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: Per sfruttare il trunking NFSv4,1, le LIF di un gruppo trunking devono risiedere sullo stesso nodo e disporre di porte home sullo stesso nodo. . 
---
= Preparare la rete per il trunking NFS ONTAP
:allow-uri-read: 


[role="lead"]
Per sfruttare il trunking NFSv4,1, le LIF di un gruppo trunking devono risiedere sullo stesso nodo e disporre di porte home sullo stesso nodo. Le LIF devono essere configurate in un gruppo di failover sullo stesso nodo.

.A proposito di questa attività
Una mappatura uno a uno di LIF e NIC consente di ottenere il massimo guadagno in termini di prestazioni, ma non è necessaria per abilitare il trunking. L'installazione di almeno due NIC può offrire vantaggi in termini di prestazioni, ma non è necessaria.

È possibile disporre di più gruppi di failover, ma il gruppo di failover per il trunking deve includere solo i file LIFS nel gruppo trunking.

È necessario regolare il gruppo di failover trunking ogni volta che si aggiungono o rimuovono connessioni (e NIC sottostanti) da un gruppo di failover.

.Prima di iniziare
* Se si desidera creare un gruppo di failover, è necessario conoscere i nomi delle porte associate alle schede NIC.
* Le porte devono essere tutte sullo stesso nodo.


.Fasi
. Verificare i nomi e lo stato delle porte di rete che si intende utilizzare:
+
`network port status`

. Creare il gruppo di failover:
+
`network interface failover-groups create -vserver _svm_name_ -failover-group _failover_group_name_ -targets _ports_list_`

+

NOTE: Non è un requisito per avere un gruppo di failover, ma è vivamente consigliato.

+
** `_svm_name_` È il nome della SVM che contiene il server NFS.
** `_ports_list_` è l'elenco delle porte che verranno aggiunte al gruppo di failover.
+
Le porte vengono aggiunte nel formato _node_name:port_number_, ad esempio, node1:e0c.

+
Questo comando crea il gruppo di failover FG3 per SVM VS1 e aggiunge tre porte:

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
Scopri di più link:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["gruppi di failover."]



. Se necessario, creare LIF per i membri del gruppo trunking:
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -home-node _node_name_ -home-port _port_name_ -address _IP_address_ -netmask _IP_address_ [-service-policy _policy_] [-auto-revert {true|false}]`

+
** `-home-node` - Il nodo da cui la LIF ritorna quando il comando di revert dell'interfaccia di rete viene eseguito sulla LIF.
+
È inoltre possibile specificare se il LIF deve ripristinare automaticamente il nodo home e la porta home con `-auto-revert` opzione.

** `-home-port` Indica la porta fisica o logica alla quale la LIF ritorna quando il comando di indirizzamento dell'interfaccia di rete viene eseguito sulla LIF.
** È possibile specificare un indirizzo IP con `-address` e. `-netmask` opzioni, non con `-subnet` opzione.
** Quando si assegnano gli indirizzi IP, potrebbe essere necessario configurare un percorso predefinito per un gateway se ci sono client o controller di dominio su una subnet IP diversa. Ulteriori informazioni su `network route create` e sulla creazione di un percorso statico all'interno di una SVM nella link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["Riferimento al comando ONTAP"^].
** `-service-policy` - La politica di servizio per la LIF. Se non viene specificato alcun criterio, viene assegnato automaticamente un criterio predefinito. Utilizzare `network interface service-policy show` per esaminare le politiche di servizio disponibili.
** `-auto-revert` - Consente di specificare se un data LIF viene automaticamente riportato al suo nodo principale in circostanze come l'avvio, modifiche allo stato del database di gestione o quando viene effettuata la connessione di rete. L'impostazione predefinita è false, ma è possibile impostarla su true in base ai criteri di gestione della rete nell'ambiente.
+
Ripetere questo passaggio per ogni LIF nel gruppo trunking.

+
Viene creato il seguente comando `lif-A` Per SVM `vs1`, sulla porta `e0c` del nodo `cluster1_01`:

+
`network interface create -vserver vs1 -lif lif-A -service-policy *???* -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
Scopri di più link:../networking/create_lifs.html["Creazione LIF."]



. Verificare che la LIF sia stata creata:
+
`network interface show`

. Verificare che l'indirizzo IP configurato sia raggiungibile:
+
[cols="25,75"]
|===
| Per verificare un... | Utilizzare... 


| Indirizzo IPv4 | `network ping` 


| Indirizzo IPv6 | `network ping6` 
|===

