---
permalink: nfs-trunking/reestablish-client-mount-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, data, shares, Linux, VMware, mounts, client 
summary: Per convertire le connessioni client non trunked in connessioni trunked, i mount esistenti sui client Linux e VMware devono essere smontati e rimontati utilizzando le informazioni sulle LIF. 
---
= Rimonta i volumi ONTAP o le condivisioni di dati per il trunking NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per convertire le connessioni client non trunked in connessioni trunked, i mount esistenti sui client Linux e VMware devono essere smontati e rimontati utilizzando le informazioni sulle LIF.

Scopri di più link:index.html#supported-clients["client supportati"].


NOTE: L'annullamento del montaggio dei client VMware provoca interruzioni per le macchine virtuali presenti nel datastore. Un'alternativa potrebbe essere creare un nuovo datastore abilitato per il trunking e utilizzare *storage vmotion* per spostare le macchine virtuali dal vecchio datastore al nuovo. Per ulteriori informazioni, consultare la documentazione VMware.

[role="tabbed-block"]
====
.Requisiti del client Linux
--
Se si utilizza ONTAP 9.16.1 o versione successiva e Red Hat Enterprise Linux versione 8,7 o successiva (per RHEL 8) o 9,2 o successiva (per RHEL 9) come client Linux, è necessario un solo punto di montaggio per il gruppo trunking. Montare i volumi esportati con questo comando, utilizzando l' `trunkdiscovery`opzione:

[source, cli]
----
mount <lif_ip>:<volume_name> </mount_path> -o trunkdiscovery,vers=4.1
----
In caso contrario, è necessario un punto di montaggio separato per ciascuna connessione nel gruppo trunking. Montare i volumi esportati con comandi simili a quelli seguenti, utilizzando l' `max_connect`opzione:

[source, cli]
----
mount <lif1_ip>:<volume_name> </mount_path1> -o vers=4.1,max_connect=16
----
[source, cli]
----
mount <lif2_ip>:<volume_name> </mount_path2> -o vers=4.1,max_connect=16
----
La versione (`vers`) il valore deve essere `4.1` o versioni successive.

Il `max_connect` il valore corrisponde al numero di connessioni nel gruppo trunking.

--
.Requisiti del client VMware
--
È necessaria un'istruzione mount che includa un indirizzo IP per ciascuna connessione nel gruppo trunking.

Montare il datastore esportato con un comando simile al seguente:

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

Il `-H` i valori devono corrispondere alle connessioni nel gruppo trunking.

--
====