---
permalink: cloud/data-sovereignty-concept.html 
sidebar: sidebar 
keywords: data sovereignty 
summary: 'La sovranità dei dati si riferisce alle leggi nazionali relative alla raccolta, all"archiviazione e alla trasmissione dei dati. Il General Data Protection Regulation (GDPR) in Europa e il Health Insurance Portability and Accountability Act (HIPAA) negli Stati Uniti sono esempi di queste leggi. La residenza dei dati si riferisce alla posizione in cui i dati sono fisicamente memorizzati e viene spesso specificata dalle leggi sulla sovranità dei dati. I dati personali degli individui sono un obiettivo primario delle normative, ma anche altri dati possono essere regolamentati.' 
---
= Sovranità dei dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sovranità dei dati si riferisce alle leggi nazionali relative alla raccolta, all'archiviazione e alla trasmissione dei dati. Il General Data Protection Regulation (GDPR) in Europa e il Health Insurance Portability and Accountability Act (HIPAA) negli Stati Uniti sono esempi di queste leggi. La residenza dei dati si riferisce alla posizione in cui i dati sono fisicamente memorizzati e viene spesso specificata dalle leggi sulla sovranità dei dati. I dati personali degli individui sono un obiettivo primario delle normative, ma anche altri dati possono essere regolamentati.

Quando si memorizzano i dati on-premise nel proprio data center, si ha il controllo completo su come e dove sono memorizzati i dati. Quando memorizzi i dati nel cloud, sei responsabile di capire come e dove sono fisicamente memorizzati i dati e sei responsabile di garantire il rispetto delle leggi sulla sovranità dei dati applicabili. Per le configurazioni di cloud ibrido, devi prestare attenzione alla posizione in cui sono memorizzati sia i Tier on-premise che i Tier cloud.

La buona notizia è che tutti i principali cloud provider sono pienamente consapevoli delle leggi e dispongono di procedure e informazioni per aiutarti a rispettare le normative. Tuttavia, è ancora importante selezionare i prodotti e le procedure appropriati per le esigenze specifiche.

In molti casi, l'archiviazione dei dati nel cloud consente di mantenere i dati entro i confini di un paese in cui la tua azienda non ha alcuna presenza fisica.

Ecco alcuni esempi delle informazioni sulla conformità fornite da NetApp e dai cloud provider:

* https://cloud.netapp.com/blog/blg-gdpr-and-hipaa-compliant-storage-systems-with-cloud-tiering["Architettura dello storage conforme a GDPR e HIPAA"]
* https://azure.microsoft.com/en-us/blog/questions-on-data-residency-and-compliance-in-azure-we-got-answers/["Domande sulla residenza dei dati e sulla conformità in Microsoft Azure"]
* https://aws.amazon.com/compliance/gdpr-center/["Centro General Data Protection Regulation (GDPR) per Amazon Web Services"]
* https://cloud.google.com/security/compliance["Centro risorse per la compliance per Google Cloud"]
* https://www.alibabacloud.com/trust-center["Alibaba Cloud Security  Compliance Center"]

