---
permalink: cloud/event-performance-monitoring-concept.html 
sidebar: sidebar 
keywords: event, performance monitoring 
summary: Quando trasferisci i carichi di lavoro on-premise nel cloud, puoi continuare a fare affidamento sul monitoraggio degli eventi di ONTAP. I messaggi EMS, il controllo nativo NAS, FPolicy e SNMP sono tutti disponibili nel cloud. 
---
= Monitoraggio di eventi e performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando trasferisci i carichi di lavoro on-premise nel cloud, puoi continuare a fare affidamento sul monitoraggio degli eventi di ONTAP. I messaggi EMS, il controllo nativo NAS, FPolicy e SNMP sono tutti disponibili nel cloud.

Se stai già utilizzando Gestione di sistema o Active IQ Unified Manager per il monitoraggio delle performance on-premise, puoi continuare a farlo nel cloud. Sia System Manager che Unified Manager forniscono report e avvisi dettagliati sullo stato, la capacità e le performance di Cloud Volumes ONTAP.

.Informazioni correlate
https://cloud.netapp.com/blog/how-to-define-an-effective-cloud-monitoring-strategy["Come definire una strategia di monitoraggio del cloud efficace"]

link:../data-protection/index.html["10 Strumenti di monitoraggio cloud che dovresti conoscere"]
