---
permalink: cloud/file-sharing-nfs-smb-concept.html 
sidebar: sidebar 
keywords: file sharing, nfs, smb 
summary: I protocolli NFS e SMBsono utilizzati per rendere condivisioni e file disponibili per le applicazioni client in rete. Cloud Volumes ONTAP consente di fornire file da un cloud pubblico utilizzando uno o entrambi questi protocolli. 
---
= Condivisione di file con NFS e SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I protocolli NFS e SMB vengono utilizzati per rendere le condivisioni e i file disponibili alle applicazioni client in rete. Cloud Volumes ONTAP consente di fornire file da un cloud pubblico utilizzando uno o entrambi questi protocolli.

Se scegli di spostare un intero workload nel cloud, Cloud Volumes ONTAP consente alla tua applicazione di lavorare con lo storage nel cloud esattamente come avviene on-premise. Non è necessario modificare l'applicazione e, se decidi di passare a un altro cloud provider, non dovrai preoccuparti del blocco del provider. Gli stessi comandi e script utilizzati per gestire i file service on-premise lavorano nel cloud.

Nel cloud, puoi scalare rapidamente le condivisioni di file, aggiungendo o rimuovendo istanze di storage e calcolo o regolando il tuo livello di servizio in base alle necessità per rispondere ai cambiamenti della domanda dei client senza incorrere in spese di capitale. Maggiore è il numero di risorse utilizzate, maggiore è il costo, ma solo quando si utilizzano le risorse.

La tecnologia NetApp SnapMirror consente di spostare e sincronizzare i dati dei file tra il sistema ONTAP on-premise e Cloud Volumes ONTAP. Puoi spostare facilmente i dati da e verso il cloud e tra i cloud provider.

.Informazioni correlate
https://docs.netapp.com/us-en/occm/task_provisioning_storage.html#creating-flexvol-volumes["BlueXP: Provisioning dello storage"]

https://docs.netapp.com/us-en/occm/task_manage_anf.html["Gestione dei volumi per Azure NetApp Files"]

https://docs.netapp.com/us-en/occm/task_manage_cvs_aws.html["Gestione di Cloud Volumes Service per AWS"]
