---
permalink: cloud/high-availability-concept.html 
sidebar: sidebar 
keywords: high availability 
summary: 'In un data center on-premise, i nodi fisici sono configurati in coppie ad alta disponibilità (ha) per la fault tolerance e le operazioni senza interruzioni. Se un nodo si guasta o se è necessario interrompere un nodo per la manutenzione ordinaria, il partner assume il controllo dello storage e continua a fornire i dati da esso.' 
---
= Alta disponibilità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In un data center on-premise, i nodi fisici sono configurati in coppie ad alta disponibilità (ha) per la fault tolerance e le operazioni senza interruzioni. Se un nodo si guasta o se è necessario interrompere un nodo per la manutenzione ordinaria, il partner assume il controllo dello storage e continua a fornire i dati da esso.

In un ambiente cloud, è possibile creare una coppia ha di istanze Cloud Volumes ONTAP per le stesse operazioni di fault tolerance e senza interruzioni di una coppia ha on-premise. Questi obiettivi di recovery sono disponibili con le coppie ha cloud:

* L'obiettivo del punto di ripristino (RPO) è di 0 secondi. I tuoi dati sono coerenti con le transazioni senza alcuna perdita di dati.
* L'obiettivo del tempo di ripristino (RTO) è di 60 secondi. In caso di interruzione, i dati devono essere disponibili in 60 secondi o meno.


Ogni cloud provider offre la propria architettura ha e opzioni di configurazione. Per Cloud Volumes Service, l'alta disponibilità è garantita nel service level agreement.

.Informazioni correlate
https://docs.netapp.com/us-en/occm/concept_ha.html["Coppie ad alta disponibilità in AWS"]

https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Coppie ad alta disponibilità in Azure"]
