---
permalink: cloud/manage-ontap-concept.html 
sidebar: sidebar 
keywords: manage, ontap, cloud 
summary: 'Che si utilizzi ONTAP nel proprio data center o nel cloud, si utilizzano le stesse interfacce per gestire lo storage. Ciò significa che sai già come gestire ONTAP nel cloud. Inoltre, NetApp BlueXP è un"interfaccia grafica moderna e facile da utilizzare per l"implementazione e l"introduzione a Cloud Volumes ONTAP. Esistono situazioni in cui è necessario eseguire una gestione avanzata di Cloud Volumes ONTAP o Cloud Volumes Service. È possibile farlo utilizzando System Manager, l"interfaccia della riga di comando (CLI) o le API REST.' 
---
= Gestire ONTAP nel cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Che si utilizzi ONTAP nel proprio data center o nel cloud, si utilizzano le stesse interfacce per gestire lo storage. Ciò significa che sai già come gestire ONTAP nel cloud. Inoltre, NetApp BlueXP è un'interfaccia grafica moderna e facile da utilizzare per l'implementazione e l'introduzione a Cloud Volumes ONTAP. Esistono situazioni in cui è necessario eseguire una gestione avanzata di Cloud Volumes ONTAP o Cloud Volumes Service. È possibile farlo utilizzando System Manager, l'interfaccia della riga di comando (CLI) o le API REST.

*Gestore di sistema* viene eseguito sul sistema Cloud Volumes ONTAP o Cloud Volumes Service, consentendo di eseguire attività di gestione.

*La CLI* di ONTAP consente di eseguire tutti i comandi amministrativi ed è una buona scelta per attività avanzate o se si è più comodi nell'utilizzo della CLI. Si effettua la connessione all'interfaccia CLI utilizzando Secure Shell (SSH).

*Le API REST di ONTAP* ti consentono di creare e gestire volumi cloud e sviluppare script e tool di provisioning. Le funzionalità di ONTAP disponibili tramite l'interfaccia utente Web sono disponibili anche tramite le API REST. In alcune situazioni, questa interfaccia programmatica è più utile, soprattutto per gli sviluppatori perché possono automatizzare i processi che coinvolgono le operazioni BlueXP.

.Informazioni correlate
https://docs.netapp.com/us-en/occm/task_connecting_to_otc.html#connecting-to-oncommand-system-manager["Connessione a Cloud Volumes ONTAP"]

https://cloud.netapp.com/blog/cloud-automation-with-cloud-volumes-ontap-rest["Automazione del cloud con Cloud Volumes ONTAP e REST"]

https://docs.netapp.com/us-en/occm/api.html["API REST BlueXP"]
