---
permalink: cloud/snaplock-worm-storage-concept.html 
sidebar: sidebar 
keywords: cloud worm storage 
summary: 'Un aspetto importante della conformità è la possibilità di garantire che alcuni dati vengano mantenuti invariati per un periodo di tempo richiesto. È possibile attivare lo storage WORM (Write Once, Read Many) su un sistema Cloud Volumes ONTAP per conservare i file in forma non modificata per un periodo di conservazione specificato. Lo storage cloud WORM è basato sulla tecnologia SnapLock, il che significa che i file WORM sono protetti a livello di file.' 
---
= Cloud WORM storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un aspetto importante della conformità è la possibilità di garantire che alcuni dati vengano mantenuti invariati per un periodo di tempo richiesto. È possibile attivare lo storage WORM (Write Once, Read Many) su un sistema Cloud Volumes ONTAP per conservare i file in forma non modificata per un periodo di conservazione specificato. Lo storage cloud WORM è basato sulla tecnologia SnapLock, il che significa che i file WORM sono protetti a livello di file.

Una volta che un file è stato impegnato nello storage WORM, non può essere modificato, anche dopo la scadenza del periodo di conservazione. Un clock a prova di manomissione determina quando è trascorso il periodo di conservazione di un file WORM.

È possibile attivare lo storage WORM su un sistema Cloud Volumes ONTAP quando si crea un nuovo ambiente di lavoro. Ciò include l'impostazione del periodo di conservazione predefinito per i file. Non è possibile attivare lo storage WORM su singoli volumi: ​WORM deve essere attivato a livello di sistema.

.Informazioni correlate
https://docs.netapp.com/us-en/occm/concept_worm.html#activating-worm-storage["Storage WORM"]

link:../snaplock/index.html["Archiviazione e conformità con la tecnologia SnapLock"]

https://cloud.netapp.com/blog/enhance-cloud-data-protection-with-worm-storage["NetApp Cloud WORM: Miglioramento della protezione dei dati con funzionalità di blocco"]
