---
permalink: cloud/storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency 
summary: Le stesse funzionalità di efficienza dello storage di ONTAP on-premise sono disponibili nel cloud. Copie Snapshot, deduplica, compressione, compaction, thin provisioning, E i cloni di dati FlexClone sono tutti disponibili nelle offerte cloud di NetApp. 
---
= Efficienza dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le stesse funzionalità di efficienza dello storage di ONTAP on-premise sono disponibili nel cloud. Copie Snapshot, deduplica, compressione, compaction, thin provisioning, E i cloni di dati FlexClone sono tutti disponibili nelle offerte cloud di NetApp.

Quando trasferisci i dati da ONTAP on-premise al cloud, l'efficienza dello storage esistente viene preservata. Sia che stiate spostando un intero set di dati o semplicemente tiering dei dati cold nel cloud, non sposterete i dati non compressi o duplicati.

.Informazioni correlate
https://cloud.netapp.com/blog/storage-efficiency-success-stories-with-cloud-volumes-ontap["Analisi delle funzionalità di Cloud Volumes ONTAP: Case study sull'efficienza dello storage"]

https://docs.netapp.com/us-en/occm/task_planning_your_config.html["Utilizzo di un profilo di utilizzo dei volumi in BlueXP per gestire l'efficienza dello storage cloud"]
