---
permalink: cloud/volume-move-concept.html 
sidebar: sidebar 
keywords: volume move 
summary: 'Utilizzando ONTAP, è possibile spostare un volume FlexVol su un Tier locale (aggregato), un nodo o entrambi diversi all"interno della stessa VM di storage per bilanciare la capacità dello storage dopo aver determinato lo squilibrio della capacità dello storage. Con Cloud Volumes ONTAP, è possibile spostare uno o più volumi in un altro sistema Cloud Volumes ONTAP o in un altro aggregato per evitare problemi di capacità. Potrebbe essere necessario eseguire questa operazione se il sistema raggiunge il limite di dischi.' 
---
= Spostamento del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzando ONTAP, è possibile spostare un volume FlexVol su un Tier locale (aggregato), un nodo o entrambi diversi all'interno della stessa VM di storage per bilanciare la capacità dello storage dopo aver determinato lo squilibrio della capacità dello storage. Con Cloud Volumes ONTAP, è possibile spostare uno o più volumi in un altro sistema Cloud Volumes ONTAP o in un altro aggregato per evitare problemi di capacità. Potrebbe essere necessario eseguire questa operazione se il sistema raggiunge il limite di dischi.

.Informazioni correlate
https://docs.netapp.com/us-en/occm/task_managing_storage.html#moving-volumes-to-another-system-to-avoid-capacity-issues["Cloud Volumes ONTAP: Spostamento dei volumi in un altro sistema per evitare problemi di capacità"]

https://docs.netapp.com/us-en/occm/task_managing_storage.html#moving-volumes-to-another-aggregate-to-avoid-capacity-issues["Cloud Volumes ONTAP: Spostamento dei volumi in un altro aggregato per evitare problemi di capacità"]
