---
permalink: flexcache/add-license-task.html 
sidebar: sidebar 
keywords: add, flexcache, license, flex cache, volume, limit, capacity, term 
summary: Se si utilizza ONTAP 9.6 o versioni precedenti, è necessario installare una licenza FlexCache, basata sulla capacità e sui termini, utilizzando Gestione sistema. 
---
= Aggiungere una licenza FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza ONTAP 9.6 o versioni precedenti, è necessario installare una licenza FlexCache, basata sulla capacità e sui termini, utilizzando Gestione sistema.

.A proposito di questa attività
La licenza FlexCache è una licenza a livello di cluster. La licenza include un limite di utilizzo autorizzato acquistato per l'utilizzo dei volumi FlexCache nel cluster. L'utilizzo dello spazio da parte dei volumi FlexCache nel cluster non deve superare la capacità del limite di utilizzo autorizzato. Per aumentare il limite di utilizzo della licenza, contattare il rappresentante commerciale.

A partire da ONTAP 9.7, la licenza basata sulla capacità non è richiesta. La licenza FlexCache viene fornita con il pacchetto ONTAP.

.Fasi
. Scaricare il file di licenza NetApp per la licenza FlexCache dal sito del supporto NetApp.
+
https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"]

. Utilizzare Gestione di sistema per caricare la licenza FlexCache nel cluster:
+
.. Fare clic sulla scheda *configurazioni* > *Cluster* > *licenze*.
.. Nella finestra *pacchetti*, fare clic su *Aggiungi*.
.. Nella finestra di dialogo *Aggiungi pacchetti di licenza*, fare clic su *Scegli file* per selezionare il file di licenza NetApp scaricato, quindi fare clic su *Aggiungi* per caricare il file nel cluster.



