---
permalink: flexcache/global-file-locking-task.html 
sidebar: sidebar 
keywords: global file locking, flexcache, relationship 
summary: È possibile attivare il blocco globale dei file sui volumi FlexCache se si desidera privilegiare la coerenza rispetto alla disponibilità. 
---
= Attiva il blocco globale dei file
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.10.1, è possibile applicare il blocco globale dei file per impedire la lettura di tutti i file memorizzati nella cache correlati.

Con il blocco globale dei file abilitato, le modifiche al volume di origine vengono sospese fino a quando tutti i volumi FlexCache non sono online. È necessario attivare il blocco globale dei file solo quando si ha il controllo sull'affidabilità delle connessioni tra la cache e l'origine a causa della sospensione e dei possibili timeout delle modifiche quando i volumi FlexCache sono offline.

.Prima di iniziare
* Il blocco globale dei file richiede che i cluster contenenti l'origine e tutte le cache associate eseguano ONTAP 9.9.1 o versione successiva. Il blocco globale dei file può essere attivato su volumi FlexCache nuovi o esistenti. Il comando può essere eseguito su un unico volume e si applica a tutti i volumi FlexCache associati.
* Per attivare il blocco globale dei file, è necessario essere nel livello di privilegio avanzato.
* Se si torna a una versione di ONTAP precedente alla 9,9.1, il blocco globale dei file deve essere prima disattivato nell'origine e nelle cache associate. Per disattivare, dal volume di origine, eseguire: `volume flexcache prepare-to-downgrade -disable-feature-set 9.10.0`
* Il processo di attivazione del blocco dei file globale dipende dal fatto che l'origine disponga di cache esistenti:
+
** <<enable-gfl-new>>
** <<enable-gfl-existing>>






== Attiva il blocco globale dei file sui nuovi volumi FlexCache

.Fasi
. Creare il volume FlexCache con `-is-global-file-locking` imposta su true:
+
`volume flexcache create volume _volume_name_ -is-global-file-locking-enabled true`

+

NOTE: Il valore predefinito di `-is-global-file-locking` è "`false`". In caso di successiva `volume flexcache create` i comandi vengono eseguiti su un volume e devono essere passati con `-is-global-file-locking enabled` impostare su "`true`".





== Attiva il blocco globale dei file sui volumi FlexCache esistenti

.Fasi
. Il blocco globale dei file deve essere impostato dal volume di origine.
. L'origine non può avere altre relazioni esistenti (ad esempio, SnapMirror). Tutte le relazioni esistenti devono essere dissociate. Tutte le cache e i volumi devono essere collegati al momento dell'esecuzione del comando. Per verificare lo stato della connessione, eseguire:
+
`volume flexcache connection-status show`

+
Lo stato di tutti i volumi elencati deve essere visualizzato come `connected.` Per ulteriori informazioni, vedere link:view-connection-status-origin-task.html["Visualizzare lo stato di una relazione FlexCache"] oppure link:synchronize-properties-origin-volume-task.html["Sincronizzare le proprietà di un volume FlexCache da un'origine"].

. Attiva il blocco globale dei file nelle cache:
+
`volume flexcache origin config show/modify -volume _volume_name_ -is-global-file-locking-enabled true`



.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^]

