---
permalink: flexcache/index.html 
sidebar: sidebar 
keywords: flexcache, volumes, faster, data, access, configure, manage, volues 
summary: 'È possibile configurare e gestire i volumi FlexCache per accelerare l"accesso ai dati.' 
---
= Panoramica sulla gestione dei volumi FlexCache con l'interfaccia CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare e gestire i volumi FlexCache per accelerare l'accesso ai dati.

Utilizzare queste procedure per configurare i volumi FlexCache se si verificano le seguenti condizioni:

* Si utilizza ONTAP 9.5 o versione successiva.
* Si desidera utilizzare l'interfaccia della riga di comando (CLI) di ONTAP, non Gestione di sistema o uno strumento di scripting automatico.
* Si desidera utilizzare le Best practice, non esplorare tutte le opzioni disponibili.
+
I dettagli sulla sintassi dei comandi sono disponibili nella guida dell'interfaccia utente e nelle pagine man di ONTAP.

* Si dispone di privilegi di amministratore del cluster, non di amministratore SVM.

