---
permalink: flexcache/sizing-concept.html 
sidebar: sidebar 
keywords: guidelines, sizing, flexcache, volume 
summary: È necessario conoscere i limiti per i volumi FlexCache prima di iniziare il provisioning dei volumi. 
---
= Linee guida per il dimensionamento di un volume FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere i limiti per i volumi FlexCache prima di iniziare il provisioning dei volumi.

Il limite di dimensione di un volume FlexVol è applicabile a un volume di origine. Le dimensioni di un volume FlexCache possono essere inferiori o uguali al volume di origine. La procedura consigliata per le dimensioni di un volume FlexCache è di almeno il 10% delle dimensioni del volume di origine.

È inoltre necessario conoscere i seguenti limiti aggiuntivi per i volumi FlexCache:

[cols="55,15,15,15"]
|===


| Limite | ONTAP 9.5-9.6 | ONTAP 9.7 | ONTAP 9.8 e versioni successive 


| Numero massimo di volumi FlexCache che è possibile creare da un volume di origine | 10 | 10 | 100 


| Numero massimo consigliato di volumi di origine per nodo | 10 | 100 | 100 


| Numero massimo consigliato di volumi FlexCache per nodo | 10 | 100 | 100 


| Numero massimo consigliato di componenti FlexGroup in un volume FlexCache per nodo | 40 | 800 | 800 


| Numero massimo di componenti per volume FlexCache per nodo | 32 | 32 | 32 
|===
.Informazioni correlate
https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilità NetApp"]
