---
permalink: flexcache/supported-unsupported-features-concept.html 
sidebar: sidebar 
keywords: supported, unsupported, features, flexcache, volumes 
summary: Le funzionalità e i protocolli supportati per i volumi di origine FlexCache e i volumi FlexCache variano. 
---
= Funzionalità supportate e non supportate per FlexCache Volumes in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9,5, è possibile configurare FlexCache Volumes. I volumi FlexVol sono supportati come volumi di origine e i volumi FlexGroup sono supportati come volumi FlexCache. A partire da ONTAP 9,7 sia i volumi FlexVol che i volumi FlexGroup sono supportati come volumi di origine. Le funzionalità e i protocolli supportati per il volume di origine e il volume FlexCache variano.


NOTE: I volumi cache e i volumi di origine possono interoperare purché entrambi siano in esecuzione su una versione supportata di ONTAP. Tenere presente che le funzionalità sono supportate solo quando sia la cache che l'origine eseguono almeno la versione ONTAP in cui è stato introdotto il supporto o una versione ONTAP successiva.



== Supporto della versione di ONTAP tra volumi FlexCache e volumi di origine

La versione ONTAP consigliata supportata tra il volume di origine e il volume della cache non è più di quattro versioni precedenti o quattro versioni successive. Ad esempio, se la cache utilizza ONTAP 9.14.1, la prima versione che l'origine può utilizzare è ONTAP 9.10.1.



== Protocolli supportati

|===


| Protocollo | Supportato sul volume di origine? | Supportato dal volume FlexCache? 


 a| 
NFSv3
 a| 
Sì
 a| 
Sì



 a| 
NFSv4
 a| 
Sì

Per accedere ai volumi della cache utilizzando il protocollo NFSv4.x, i cluster di origine e cache devono utilizzare ONTAP 9.10.1 o versione successiva. Il cluster di origine e il cluster FlexCache possono avere diverse versioni di ONTAP, ma entrambe devono essere ONTAP 9.10.1 e versioni successive. Ad esempio, l'origine può avere ONTAP 9.10.1 e la cache può avere ONTAP 9.11.1.
 a| 
Sì

Supportato a partire da ONTAP 9.10.1.

Per accedere ai volumi della cache utilizzando il protocollo NFSv4.x, i cluster di origine e cache devono utilizzare ONTAP 9.10.1 o versione successiva. Il cluster di origine e il cluster FlexCache possono avere diverse versioni di ONTAP, ma entrambe devono essere ONTAP 9.10.1 e versioni successive. Ad esempio, l'origine può avere ONTAP 9.10.1 e la cache può avere ONTAP 9.11.1.



 a| 
NFSv4.2
 a| 
Sì
 a| 
No



 a| 
PMI
 a| 
Sì
 a| 
Sì

Supportato a partire da ONTAP 9.8.

|===


== Funzionalità supportate

|===


| Funzione | Supportato sul volume di origine? | Supportato dal volume FlexCache? 


 a| 
Protezione autonoma dal ransomware
 a| 
Sì

Supportato per volumi di origine FlexVol a partire da ONTAP 9.10.1 e supportato per volumi di origine FlexGroup a partire da ONTAP 9.13.1. Vedere link:../anti-ransomware/use-cases-restrictions-concept.html#unsupported-configurations["Casi di utilizzo e considerazioni sulla protezione ransomware autonoma"].
 a| 
No



 a| 
Antivirus
 a| 
Sì

Supportato a partire da ONTAP 9,7.
 a| 
Non applicabile

Se si configura la scansione antivirus all'origine, non è necessaria nella cache. La scansione antivirus di origine rileva i file infettati da virus prima che le scritture siano confermate, indipendentemente dall'origine di scrittura. Per ulteriori informazioni sull'utilizzo della scansione antivirus con FlexCache, consultare la https://www.netapp.com/media/7336-tr4743.pdf["Report tecnico su FlexCache with ONTAP"^].



 a| 
Controllo
 a| 
Sì

Supportato a partire da ONTAP 9,7.
Puoi controllare gli eventi di accesso ai file NFS nelle relazioni FlexCache utilizzando l'audit ONTAP nativo.
Per ulteriori informazioni, vedere xref:audit-flexcache-volumes-concept.adoc[Considerazioni per il controllo dei volumi FlexCache]
 a| 
Sì

Supportato a partire da ONTAP 9,7.
Puoi controllare gli eventi di accesso ai file NFS nelle relazioni FlexCache utilizzando l'audit ONTAP nativo.
Per ulteriori informazioni, vedere xref:audit-flexcache-volumes-concept.adoc[Considerazioni per il controllo dei volumi FlexCache]



 a| 
Cloud Volumes ONTAP
 a| 
Sì

Supportato a partire da ONTAP 9.6
 a| 
Sì

Supportato a partire da ONTAP 9.6



 a| 
Compattazione
 a| 
Sì

Supportato a partire da ONTAP 9.6
 a| 
Sì

Supportato a partire da ONTAP 9.7



 a| 
Compressione
 a| 
Sì

Supportato a partire da ONTAP 9.6
 a| 
Sì

Supportato a partire da ONTAP 9.6



 a| 
Deduplica
 a| 
Sì
 a| 
Sì

La deduplica inline è supportata sui volumi FlexCache a partire da ONTAP 9.6. La deduplica tra volumi è supportata sui volumi FlexCache a partire da ONTAP 9.7.



 a| 
FabricPool
 a| 
Sì
 a| 
Sì

Supportato a partire da ONTAP 9.7



 a| 
Dr. FlexCache
 a| 
Sì
 a| 
Sì

Supportato a partire da ONTAP 9.9.1, solo con protocollo NFSv3. I volumi FlexCache devono trovarsi in SVM separate o in cluster separati.



 a| 
Volume FlexGroup
 a| 
Sì

Supportato a partire da ONTAP 9.7
 a| 
Sì



 a| 
Volume FlexVol
 a| 
Sì
 a| 
No



 a| 
FPolicy
 a| 
Sì

Supportato a partire da ONTAP 9.7
 a| 
Sì

Supportato per NFS a partire da ONTAP 9,7.
Supportato per SMB a partire da ONTAP 9.14.1.



 a| 
Configurazione di MetroCluster
 a| 
Sì

Supportato a partire da ONTAP 9.7
 a| 
Sì

Supportato a partire da ONTAP 9.7



 a| 
ODX (Microsoft Offloaded Data Transfer)
 a| 
Sì
 a| 
No



 a| 
NetApp aggregate Encryption (NAE)
 a| 
Sì

Supportato a partire da ONTAP 9.6
 a| 
Sì

Supportato a partire da ONTAP 9.6



 a| 
NetApp Volume Encryption (NVE)
 a| 
Sì

Supportato a partire da ONTAP 9.6
 a| 
Sì

Supportato a partire da ONTAP 9.6



 a| 
Bucket ONTAP S3 NAS
 a| 
Sì

Supportato a partire da ONTAP 9.12.1
 a| 
No



 a| 
QoS
 a| 
Sì
 a| 
Sì


NOTE: La QoS a livello di file non è supportata per i volumi FlexCache.



 a| 
Qtree
 a| 
Sì

A partire da ONTAP 9.6, è possibile creare e modificare qtree. È possibile accedere ai qtree creati sull'origine dalla cache.
 a| 
No



 a| 
Quote
 a| 
Sì

A partire da ONTAP 9,6, l'imposizione delle quote sui volumi di origine FlexCache è supportata per utenti, gruppi e qtree.
 a| 
No

Con la modalità FlexCache Writeound (modalità predefinita), le scritture nella cache vengono inoltrate al volume di origine. Le quote vengono applicate all'origine.


NOTE: A partire da ONTAP 9.6, la quota remota (rquota) è supportata nei volumi FlexCache.



 a| 
SMB Change Notify
 a| 
Sì
 a| 
Sì

A partire da ONTAP 9.14.1, SMB Change Notify è supportato nella cache.



 a| 
Volumi SnapLock
 a| 
No
 a| 
No



 a| 
Relazioni asincrone SnapMirror*
 a| 
Sì
 a| 
No



 a| 
 a| 
*Origini di FlexCache:

* È possibile disporre di un volume FlexCache da un FlexVol di origine
* È possibile disporre di un volume FlexCache da un FlexGroup di origine
* È possibile avere un volume FlexCache da un volume primario di origine in relazione SnapMirror.
* A partire da ONTAP 9.8, un volume secondario SnapMirror può essere un volume di origine FlexCache. Il volume secondario SnapMirror deve essere inattivo senza aggiornamenti SnapMirror attivi; in caso contrario, la creazione di FlexCache non riesce.




 a| 
Relazioni sincrone SnapMirror
 a| 
No
 a| 
No



 a| 
SnapRestore
 a| 
Sì
 a| 
No



 a| 
Snapshot
 a| 
Sì
 a| 
No



 a| 
Configurazione DR SVM
 a| 
Sì

Supportato a partire da ONTAP 9.5. La SVM primaria di una relazione DR SVM può avere il volume di origine; tuttavia, se la relazione DR SVM viene interrotta, la relazione FlexCache deve essere ricreata con un nuovo volume di origine.
 a| 
No

È possibile avere volumi FlexCache nelle SVM primarie, ma non nelle SVM secondarie. Qualsiasi volume FlexCache nella SVM primaria non viene replicato come parte della relazione di DR della SVM.



 a| 
Access Guard a livello di storage (SLAG)
 a| 
No
 a| 
No



 a| 
Thin provisioning
 a| 
Sì
 a| 
Sì

Supportato a partire da ONTAP 9.7



 a| 
Cloning di volumi
 a| 
Sì

La clonazione di un volume di origine e dei file nel volume di origine è supportata a partire da ONTAP 9.6.
 a| 
No



 a| 
Spostamento del volume
 a| 
Sì
 a| 
Sì (solo per i componenti del volume)

Lo spostamento degli elementi costitutivi del volume FlexCache è supportato con ONTAP 9,6 e versioni successive.



 a| 
Re-host del volume
 a| 
No
 a| 
No



 a| 
API vStorage per l'integrazione degli array (VAAI)
 a| 
Sì
 a| 
No

|===

NOTE: Nelle release di ONTAP 9 precedenti alla 9.5, i volumi FlexVol di origine possono fornire dati solo ai volumi FlexCache creati su sistemi che eseguono Data ONTAP 8.2.x in modalità 7. A partire da ONTAP 9.5, i volumi FlexVol di origine possono anche fornire dati ai volumi FlexCache sui sistemi ONTAP 9. Per informazioni sulla migrazione da 7-Mode FlexCache a ONTAP 9 FlexCache, vedere link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf["Rapporto tecnico NetApp 4743: FlexCache in ONTAP"^].
