---
permalink: flexcache/synchronize-properties-origin-volume-task.html 
sidebar: sidebar 
keywords: synchronizing, properties, flexcache, volume, origin 
summary: Alcune delle proprietà del volume FlexCache devono sempre essere sincronizzate con quelle del volume di origine. Se le proprietà di un volume FlexCache non vengono sincronizzate automaticamente dopo la modifica delle proprietà nel volume di origine, è possibile sincronizzare manualmente le proprietà. 
---
= Sincronizzare le proprietà di un volume FlexCache da un volume di origine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alcune delle proprietà del volume FlexCache devono sempre essere sincronizzate con quelle del volume di origine. Se le proprietà di un volume FlexCache non vengono sincronizzate automaticamente dopo la modifica delle proprietà nel volume di origine, è possibile sincronizzare manualmente le proprietà.

.A proposito di questa attività
Le seguenti proprietà di un volume FlexCache devono essere sempre sincronizzate con quelle del volume di origine:

* Stile di sicurezza (`-security-style`)
* Nome del volume (`-volume-name`)
* Dimensione massima directory (`-maxdir-size`)
* Valore minimo di lettura anticipata (`-min-readahead`)


.Fase
. Dal volume FlexCache, sincronizzare le proprietà del volume:
+
`volume flexcache sync-properties -vserver svm_name -volume flexcache_volume`

+
[listing]
----
cluster1::> volume flexcache sync-properties -vserver vs1 -volume fc1
----

