---
permalink: volumes/assign-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: assign, volume efficiency policy, volume 
summary: 'È possibile assegnare una policy di efficienza a un volume per eseguire operazioni di deduplica o compressione dei dati utilizzando il comando di modifica dell"efficienza del volume.' 
---
= Assegnare una policy di efficienza del volume a un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile assegnare una policy di efficienza a un volume per eseguire operazioni di deduplica o compressione dei dati utilizzando `volume efficiency modify` comando.

.A proposito di questa attività
Se un criterio di efficienza viene assegnato a un volume secondario SnapVault, viene preso in considerazione solo l'attributo di priorità di efficienza del volume quando si eseguono operazioni di efficienza del volume. Le pianificazioni dei processi vengono ignorate e l'operazione di deduplica viene eseguita quando vengono effettuati aggiornamenti incrementali al volume secondario SnapVault.

.Fase
. Utilizzare `volume efficiency modify` comando per assegnare un criterio a un volume.


.Esempio
Il seguente comando assegna al volume Vola la policy di efficienza del volume denominata new_policy:

`volume efficiency modify -vserver vs1 -volume VolA -policy new_policy`
