---
permalink: volumes/autoshrink-snapshot-copy-deletion-concept.html 
sidebar: sidebar 
keywords: how, autoshrink functionality, interacts with, snapshot copy, deletion, automatic 
summary: 'Poiché la funzionalità di riduzione automatica riduce le dimensioni di un volume FlexVol, può influire anche sull"eliminazione automatica delle copie Snapshot del volume.' 
---
= Funzionalità di collegamento automatico ed eliminazione della copia snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Poiché la funzionalità di riduzione automatica riduce le dimensioni di un volume FlexVol, può influire anche sull'eliminazione automatica delle copie Snapshot del volume.

La funzionalità di riduzione automatica interagisce con l'eliminazione automatica della copia Snapshot del volume nei seguenti modi:

* Se entrambi i `grow_shrink` La modalità di dimensionamento automatico e l'eliminazione automatica della copia Snapshot sono attivate, quando le dimensioni di un volume si restringono, possono attivare l'eliminazione automatica della copia Snapshot.
+
Questo perché la riserva Snapshot si basa su una percentuale delle dimensioni del volume (5% per impostazione predefinita) e tale percentuale si basa ora su un volume più piccolo. Ciò può causare la fuoriuscita delle copie Snapshot dalla riserva e l'eliminazione automatica.

* Se il `grow_shrink` La modalità di dimensionamento automatico è attivata e si elimina manualmente una copia Snapshot, che potrebbe attivare un ritiro automatico del volume.

