---
permalink: volumes/automatic-deduplication-schedule-aff-concept.html 
sidebar: sidebar 
keywords: manage, automatic, volume-level, background, deduplication, aff systems 
summary: A partire da ONTAP 9.3, la deduplica in background a livello di volume può essere gestita in modo da essere eseguita automaticamente utilizzando un criterio AutoAFF predefinito. Non è richiesta alcuna configurazione manuale delle pianificazioni. La policy automatica esegue la deduplica continua in background. 
---
= Deduplica in background a livello di volume automatica su sistemi AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9,3, è possibile configurare la deduplica in background a livello di volume in modo che venga eseguita automaticamente utilizzando un valore predefinito `auto` Policy AFF. Non è richiesta alcuna configurazione manuale delle pianificazioni. Il `auto` policy esegue la deduplica continua in background.

Il `auto` la policy viene impostata per tutti i volumi appena creati e per tutti i volumi aggiornati che non sono stati configurati manualmente per la deduplica in background. È possibile link:assign-volume-efficiency-policy-task.html["modificare il criterio"] a. `default` o qualsiasi altro criterio per disattivare la funzione.

Se un volume si sposta da un sistema non AFF a un sistema AFF, l' `auto` il criterio è attivato per impostazione predefinita nel nodo di destinazione. Se un volume si sposta da un nodo AFF a un nodo non AFF, il `auto` il criterio sul nodo di destinazione viene sostituito da `inline-only` policy per impostazione predefinita.

Su AFF, il sistema monitora tutti i volumi con `auto` policy e deprioritizza il volume che ha meno risparmi o sovrascritture frequenti. I volumi sordinati non partecipano più alla deduplica automatica in background. La registrazione delle modifiche sui volumi con priorità disattivata viene disattivata e i metadati sul volume vengono troncati.

Gli utenti possono promuovere il volume sassegnato dalla priorità per partecipare nuovamente a una deduplica automatica in background utilizzando `volume efficiency promote` comando disponibile a livello di privilegio avanzato.

Ulteriori informazioni su `volume efficiency promote` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-promote.html["Riferimento al comando ONTAP"^].
