---
permalink: volumes/change-inactive-data-threshold-task.html 
sidebar: sidebar 
keywords: storage, efficiency, temperature, change, efficient, default, threshold, inactive, compression, cold data, frequency 
summary: 'È possibile modificare la frequenza con cui ONTAP esegue una scansione dei dati a freddo modificando la soglia di freddo sui volumi utilizzando l"efficienza dello storage sensibile alla temperatura.' 
---
= Modificare la soglia di compressione dei dati inattivi del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la frequenza con cui ONTAP esegue una scansione dei dati a freddo modificando la soglia di freddo sui volumi utilizzando l'efficienza dello storage sensibile alla temperatura.

.Prima di iniziare
È necessario essere un amministratore di cluster o SVM e utilizzare il livello di privilegio avanzato CLI di ONTAP.

.A proposito di questa attività
La soglia di freddo può essere compresa tra 1 e 60 giorni. La soglia predefinita è 14 giorni.

.Fasi
. Impostare il livello di privilegio:
+
`set -privilege advanced`

. Modificare la compressione dei dati inattivi su un volume:
+
`volume efficiency inactive-data-compression modify -vserver <vserver_name> -volume <volume_name> -threshold-days <integer>`



Per ulteriori informazioni su, consulta la pagina man link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-inactive-data-compression-modify.html#description["modifica della compressione dei dati inattivi"].
