---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume, maximum, files, file 
summary: I volumi FlexVol possono contenere un numero massimo di file. È possibile modificare questo valore massimo, ma tenere presente che questo influisce sul volume. 
---
= Numero predefinito e massimo di file consentiti per i volumi FlexVol in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I volumi FlexVol hanno un numero predefinito e massimo di file che possono contenere.  Se i tuoi dati richiedono un numero elevato di file, puoi aumentare il numero di file visibili all'utente consentiti su un volume fino a un valore massimo.  Prima di procedere, è necessario comprendere i limiti e le avvertenze.

Il numero di file visibili all'utente che un volume può contenere è determinato dalla capacità di inode disponibile per il volume.  Un inode è una struttura dati che contiene informazioni sui file.

ONTAP imposta automaticamente il numero predefinito e massimo di inode disponibili per un volume appena creato come segue, in base alle dimensioni del volume.

[cols="2,2"]
|===
| Numero predefinito di inode | Numero massimo di inode 


| 1 ogni 32 KB di dimensione del volume | 1 per 4 KB di dimensione del volume 
|===
Quando la dimensione di un volume viene aumentata, manualmente da un amministratore o automaticamente tramite la funzione di ridimensionamento automatico di ONTAP, ONTAP aumenta anche (se necessario) il numero di inode disponibili in modo che ci sia almeno 1 inode ogni 32 KB di dimensione del volume, finché il volume non raggiunge circa 680 GB di dimensione.

In ONTAP 9.12.1 e versioni precedenti, la creazione di un nuovo volume o il ridimensionamento di un volume esistente di dimensioni superiori a 680 GB non determina automaticamente una capacità inode aggiuntiva.  Se hai bisogno di più file rispetto al numero predefinito per qualsiasi dimensione di volume, puoi usare `volume modify` comando per aumentare fino al massimo il numero di inode disponibili per il volume.

A partire da ONTAP 9.13.1, la creazione di un nuovo volume o il ridimensionamento di un volume esistente imposta il numero predefinito di inode disponibili su 1 inode ogni 32 KB di spazio del volume, anche se il volume è maggiore di 680 GB.  Questo rapporto persiste finché il volume non raggiunge il massimo assoluto dell'inode pari a 2.040.109.451.

È anche possibile diminuire il numero di inode disponibili.  Ciò non modifica la quantità di spazio allocata agli inode, ma riduce la quantità massima di spazio che il file inode pubblico può consumare.  Una volta allocato lo spazio per gli inode, questo non viene mai restituito al volume.  Pertanto, non è possibile ridurre il numero massimo di inode al di sotto del numero di inode attualmente assegnati.

.Ulteriori informazioni
* xref:display-file-inode-usage-task.html[Determina l'utilizzo di file e inode per un volume]
* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ_-_ONTAP_default_and_maximum_number_of_files_(inodes)["Articolo della Knowledge Base: FAQ - Numero predefinito e massimo di file (inode) ONTAP"]

