---
permalink: volumes/commands-manage-qtrees-reference.html 
sidebar: sidebar 
keywords: commands for, managing, configuring, qtrees, manage, command, configure 
summary: È possibile gestire e configurare qtree utilizzando specifici comandi ONTAP. 
---
= Comandi per la gestione e la configurazione di qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire e configurare qtree utilizzando specifici comandi ONTAP. A seconda dell'operazione da eseguire, puoi utilizzare i seguenti comandi per gestire e configurare le qtree:

|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare un qtree
 a| 
`volume qtree create`



 a| 
Visualizza un elenco filtrato di qtree
 a| 
`volume qtree show`



 a| 
Eliminare un qtree
 a| 
`volume qtree delete`


NOTE: Il comando qtree `volume qtree delete` non riesce a meno che il qtree non sia vuoto o il `-force true` viene aggiunto il flag.



 a| 
Modificare le autorizzazioni UNIX di un qtree
 a| 
`volume qtree modify -unix-permissions`



 a| 
Modificare l'impostazione degli oplock CIFS di un qtree
 a| 
`volume qtree oplocks`



 a| 
Modificare l'impostazione di sicurezza di un qtree
 a| 
`volume qtree security`



 a| 
Rinominare un qtree
 a| 
`volume qtree rename`



 a| 
Visualizzare le statistiche di un qtree
 a| 
`volume qtree statistics`



 a| 
Ripristinare le statistiche di un qtree
 a| 
`volume qtree statistics -reset`

|===
[NOTE]
====
Il `volume rehost` il comando può causare il malfunzionamento di altre operazioni amministrative simultanee destinate a quel volume.

====