---
permalink: volumes/commands-manage-flexvol-volumes-reference.html 
sidebar: sidebar 
keywords: commands for, managing, flexvol, volumes, manage 
summary: 'Sono disponibili comandi specifici per la gestione dei volumi FlexVol mediante l"interfaccia CLI di ONTAP.' 
---
= Comandi per la gestione dei volumi FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili comandi specifici per la gestione dei volumi FlexVol mediante l'interfaccia CLI di ONTAP.

[cols="2*"]
|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Porta un volume online
 a| 
`volume online`



 a| 
Modificare le dimensioni di un volume
 a| 
`volume size`



 a| 
Determinare l'aggregato associato di un volume
 a| 
`volume show`



 a| 
Determinare l'aggregato associato per tutti i volumi su una macchina virtuale di storage (SVM)
 a| 
`volume show -vserver -fields aggregate`



 a| 
Determinare il formato di un volume
 a| 
`volume show -fields block-type`



 a| 
Montare un volume su un altro volume utilizzando una giunzione
 a| 
`volume mount`



 a| 
Impostare un volume nello stato con restrizioni
 a| 
`volume restrict`



 a| 
Rinominare un volume
 a| 
`volume rename`



 a| 
Portare un volume offline
 a| 
`volume offline`

|===
Per ulteriori informazioni, consulta la pagina man relativa a ciascun comando.
