---
permalink: volumes/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands for, displaying, space, usage, information, display 
summary: 'I comandi di aggregato e volume dello storage consentono di visualizzare l"utilizzo dello spazio negli aggregati, nei volumi e nelle relative copie Snapshot.' 
---
= Comandi per la visualizzazione delle informazioni sull'utilizzo dello spazio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utilizza `storage aggregate` e. `volume` Comandi per vedere come viene utilizzato lo spazio negli aggregati, nei volumi e nelle relative copie Snapshot.

[cols="2*"]
|===
| Per visualizzare informazioni su... | Utilizzare questo comando... 


 a| 
Aggregati, inclusi i dettagli sulle percentuali di spazio utilizzate e disponibili, le dimensioni della riserva Snapshot e altre informazioni sull'utilizzo dello spazio
 a| 
`storage aggregate show` `storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Modalità di utilizzo dei dischi e dei gruppi RAID in un aggregato e nello stato RAID
 a| 
`storage aggregate show-status`



 a| 
La quantità di spazio su disco che verrebbe recuperata se si elimina una copia Snapshot specifica
 a| 
`volume snapshot compute-reclaimable` (avanzato)



 a| 
La quantità di spazio utilizzata da un volume
 a| 
`volume show -fields size,used,available,percent-used` `volume show-space`



 a| 
La quantità di spazio utilizzata da un volume nell'aggregato contenente
 a| 
`volume show-footprint`

|===