---
permalink: volumes/commands-display-quotas-reference.html 
sidebar: sidebar 
keywords: commands for, display, displaying, information about, quotas 
summary: 'È possibile utilizzare i comandi per visualizzare un report delle quote contenente le quote applicate e l"utilizzo delle risorse, visualizzare informazioni sullo stato delle quote e sugli errori o sui criteri delle quote e sulle regole delle quote.' 
---
= Comandi per la visualizzazione delle informazioni sulle quote in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i comandi per visualizzare un report delle quote contenente le quote applicate e l'utilizzo delle risorse, visualizzare informazioni sullo stato delle quote e sugli errori o sui criteri delle quote e sulle regole delle quote.

[NOTE]
====
È possibile eseguire i seguenti comandi solo sui volumi FlexVol.

====
[cols="2*"]
|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza informazioni sulle quote applicate
 a| 
`volume quota report`



 a| 
Visualizzare l'utilizzo delle risorse (spazio su disco e numero di file) delle destinazioni di quota
 a| 
`volume quota report`



 a| 
Determinare quali limiti di quota sono interessati quando è consentita la scrittura su un file
 a| 
`volume quota report` con `-path` parametro



 a| 
Visualizzare lo stato della quota, ad esempio `on`, `off`, e. `initializing`
 a| 
`volume quota show`



 a| 
Consente di visualizzare informazioni sulla registrazione dei messaggi di quota
 a| 
`volume quota show` con `-logmsg` parametro



 a| 
Visualizza gli errori che si verificano durante l'inizializzazione e il ridimensionamento delle quote
 a| 
`volume quota show` con `-instance` parametro



 a| 
Visualizza informazioni sulle policy di quota
 a| 
`volume quota policy show`



 a| 
Consente di visualizzare informazioni sulle regole delle quote
 a| 
`volume quota policy rule show`



 a| 
Visualizzare il nome del criterio di quota assegnato a una macchina virtuale di storage (SVM, precedentemente noto come Vserver)
 a| 
`vserver show` con `-instance` parametro

|===
Ulteriori informazioni su `volume quota` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["Riferimento al comando ONTAP"^].
