---
permalink: volumes/commands-activate-modify-quotas-reference.html 
sidebar: sidebar 
keywords: commands to, activate, modify, quotas, command, commands 
summary: I comandi di quota del volume consentono di modificare lo stato delle quote e di configurare la registrazione dei messaggi delle quote. 
---
= Comandi per attivare e modificare le quote in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`volume quota` i comandi consentono di modificare lo stato delle quote e di configurare la registrazione dei messaggi delle quote. A seconda delle operazioni da eseguire, è possibile utilizzare i seguenti comandi per attivare e modificare le quote:

[cols="2*"]
|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Attivare le quote (dette anche _inizializzazione_)
 a| 
`volume quota on`



 a| 
Ridimensionare le quote esistenti
 a| 
`volume quota resize`



 a| 
Disattivare le quote
 a| 
`volume quota off`



 a| 
Modificare la registrazione dei messaggi delle quote, attivare le quote, disattivare le quote o ridimensionare le quote esistenti
 a| 
`volume quota modify`

|===
Ulteriori informazioni su `volume quota` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["Riferimento al comando ONTAP"^].
