---
permalink: volumes/configure-automatic-provide-space-when-full-task.html 
sidebar: sidebar 
keywords: configure, volumes, automatically, provide, space, full, increase, size, automatic, grow, autogrow 
summary: Quando i volumi FlexVol diventano completi, ONTAP può tentare automaticamente di fornire più spazio libero al volume utilizzando uno dei diversi metodi. 
---
= Configurare i volumi in modo che forniscano automaticamente più spazio quando sono pieni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando i volumi FlexVol si esauriranno, ONTAP può utilizzare diversi metodi per tentare di fornire automaticamente più spazio libero per il volume. È possibile scegliere i metodi che ONTAP può utilizzare e in quale ordine, a seconda dei requisiti imposti dall'applicazione e dall'architettura di storage.

.A proposito di questa attività
ONTAP può fornire automaticamente più spazio libero per un volume completo utilizzando uno o entrambi i metodi seguenti:

* Aumentare le dimensioni del volume (noto come _crescita automatica_).
+
Questo metodo è utile se l'aggregato contenente il volume dispone di spazio sufficiente per supportare un volume più grande. È possibile configurare ONTAP in modo da impostare una dimensione massima per il volume. L'aumento viene attivato automaticamente in base alla quantità di dati scritti nel volume in relazione alla quantità corrente di spazio utilizzato e alle soglie impostate.

+
L'autogrow non viene attivato per supportare la creazione di snapshot. Se si tenta di creare uno snapshot e lo spazio è insufficiente, la creazione dello snapshot non riesce, anche con la funzione di crescita automatica attivata.

* Eliminazione di Snapshot, file FlexClone o LUN FlexClone.
+
Ad esempio, puoi configurare ONTAP in modo da eliminare automaticamente le snapshot non collegate a snapshot in volumi o LUN clonati, oppure puoi definire quali snapshot vuoi che ONTAP elimini per primi le snapshot più vecchie o più recenti. È inoltre possibile stabilire quando ONTAP deve iniziare a eliminare gli snapshot, ad esempio quando il volume è quasi pieno o quando la riserva di snapshot del volume è quasi piena.



Se si abilitano entrambi questi metodi, è possibile specificare il metodo che ONTAP tenta per primo quando un volume è quasi pieno. Se il primo metodo non fornisce spazio aggiuntivo sufficiente al volume, ONTAP tenta di utilizzare l'altro metodo.

Per impostazione predefinita, ONTAP tenta di aumentare prima le dimensioni del volume. Nella maggior parte dei casi, è preferibile la configurazione predefinita, perché quando uno snapshot viene eliminato, non può essere ripristinato. Tuttavia, se è necessario evitare di aumentare le dimensioni di un volume quando possibile, è possibile configurare ONTAP in modo da eliminare gli snapshot prima di aumentare le dimensioni del volume.

.Fasi
. Se si desidera che ONTAP provi ad aumentare le dimensioni del volume una volta esaurito, attivare la funzionalità di crescita automatica del volume usando il comando con `grow` la `volume autosize` modalità. Ulteriori informazioni su `volume autosize` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-autosize.html["Riferimento al comando ONTAP"^].
+
Tenere presente che quando il volume cresce, consuma più spazio libero dall'aggregato associato. Se si dipende dalla capacità del volume di crescere ogni volta che è necessario, è necessario monitorare lo spazio libero nell'aggregato associato e aggiungerne di più quando necessario.

. Abilitare l'eliminazione automatica per i tipi di oggetti necessari per eliminare snapshot, file FlexClone o LUN FlexClone al crescere del volume ONTAP.
. Se sono state attivate sia la funzionalità di crescita automatica del volume che una o più funzionalità di eliminazione automatica, selezionare il primo metodo che ONTAP deve utilizzare per fornire spazio libero a un volume utilizzando il `volume modify` comando con l' `-space-mgmt-try-first`opzione . Ulteriori informazioni su `volume modify` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["Riferimento al comando ONTAP"^].
+
Per specificare prima di tutto l'aumento delle dimensioni del volume (impostazione predefinita), utilizzare `volume_grow`. Per specificare prima di tutto l'eliminazione delle istantanee, utilizzare `snap_delete`.


