---
permalink: volumes/control-io-performance-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o performance, flexvol volumes, using storage qos, qos, performance, throttle, flexvol, policy, policy group 
summary: Puoi controllare le performance di i/o per volumi FlexVol utilizzando gruppi di policy di qualità del servizio di storage per gestire i carichi di lavoro. 
---
= Controlla e monitora le performance i/o di FlexVol volume con QoS storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile controllare le prestazioni di input/output (i/o) dei volumi FlexVol assegnando i volumi ai gruppi di policy di qualità del servizio di storage. È possibile controllare le performance di i/o per garantire che i carichi di lavoro raggiungano specifici obiettivi di performance o per ridurre il carico di lavoro che ha un impatto negativo su altri carichi di lavoro.

.A proposito di questa attività
I gruppi di policy impongono un limite massimo di throughput (ad esempio, 100 MB/s). È possibile creare un gruppo di policy senza specificare un limite massimo di throughput, il che consente di monitorare le prestazioni prima di controllare il carico di lavoro. È anche possibile specificare un limite minimo di throughput.

È inoltre possibile assegnare SVM, LUN e file ai gruppi di criteri.

Tenere presente i seguenti requisiti relativi all'assegnazione di un volume a un gruppo di criteri:

* Il volume deve essere contenuto dalla SVM a cui appartiene il gruppo di criteri.
+
Specificare la SVM quando si crea il gruppo di criteri.

* A partire da ONTAP 9.18.1, è possibile assegnare policy QoS ai volumi contenuti in SVM che dispongono di policy QoS. Quando si utilizzano policy QoS nidificate, viene applicata la policy più restrittiva.
* A partire da ONTAP 9.14.0, puoi assegnare policy ai qtree contenuti nei volumi che hanno policy QoS.


Per ulteriori informazioni sull'utilizzo di Storage QoS, consultare link:../system-admin/index.html["System Administration Reference (Guida all'amministrazione del sistema"].

.Fasi
. Utilizzare `qos policy-group create` per creare un gruppo di criteri.
. Utilizzare `volume create` o il `volume modify` con il `-qos-policy-group` parametro per assegnare un volume a un gruppo di criteri.
. Utilizzare `qos statistics` comandi per visualizzare i dati delle performance.
. Se necessario, utilizzare `qos policy-group modify` comando per regolare il limite massimo di throughput del gruppo di criteri.


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+policy-group["gruppo di policy QOS"^]
* collegamento: https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html [creazione di un gruppo di policy QOS]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["creazione del volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["modifica del volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+statistics["statistiche qos"^]

