---
permalink: volumes/convert-directory-qtree-task.html 
sidebar: sidebar 
keywords: convert, directory, qtree 
summary: Se si dispone di una directory alla radice di una FlexVol volume che si desidera convertire in un qtree, è necessario migrare i dati contenuti nella directory in un nuovo qtree con lo stesso nome. 
---
= Convertire una directory in un qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dispone di una directory alla radice di una FlexVol volume che si desidera convertire in un qtree, sarà necessario migrare i dati contenuti nella directory in un nuovo qtree con lo stesso nome, utilizzando l'applicazione client.

.A proposito di questa attività
La procedura da seguire per convertire una directory in un qtree dipende dal client utilizzato. Il seguente processo descrive le attività generali che è necessario completare.

.Prima di iniziare
Non è possibile eliminare una directory se associata a una condivisione CIFS esistente.

.Fasi
. Rinominare la directory da creare in un qtree.
. Creare un nuovo qtree con il nome della directory originale.
. Utilizzare l'applicazione client per spostare il contenuto della directory nel nuovo qtree.
. Eliminare la directory ora vuota.

