---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun 
summary: È possibile creare cloni di file e LUN presenti nei volumi FlexVol o FlexClone efficienti in termini di spazio e tempo utilizzando il comando di creazione del clone del file di volume. 
---
= Creare un file FlexClone o un LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare cloni di file e LUN presenti nei volumi FlexVol o FlexClone efficienti in termini di spazio e tempo utilizzando `volume file clone create` comando.

.Di cosa hai bisogno
* La licenza FlexClone deve essere installata sul cluster. Questa licenza è inclusa con link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP uno"].
* Se vengono utilizzati più intervalli di blocchi per la clonazione sotto-LUN o per la clonazione sotto-file, i numeri di blocco non devono sovrapporsi.
* Se si crea un file secondario o un file secondario su volumi con compressione adattiva attivata, gli intervalli di blocchi non devono essere disallineati.
+
Ciò significa che il numero del blocco iniziale di origine e il numero del blocco iniziale di destinazione devono essere allineati pari o dispari.



.A proposito di questa attività
A seconda dei privilegi assegnati dall'amministratore del cluster, un amministratore SVM può creare file FlexClone e LUN FlexClone.

È possibile specificare l'impostazione di eliminazione automatica per i file FlexClone e le LUN FlexClone quando si creano e modificano i cloni. Per impostazione predefinita, l'eliminazione automatica è disattivata.

È possibile sovrascrivere un file FlexClone o un LUN FlexClone esistente quando si crea un clone utilizzando `volume file clone create` con il `-overwrite-destination` parametro.

Quando il nodo raggiunge il carico di divisione massimo, il nodo interrompe temporaneamente l'accettazione delle richieste di creazione dei file FlexClone e dei LUN FlexClone ed emette un `EBUSY` messaggio di errore. Quando il carico suddiviso per il nodo scende al di sotto del massimo, il nodo accetta le richieste di creazione di file FlexClone e LUN FlexClone di nuovo. Prima di riprovare la richiesta di creazione, attendere che il nodo disponga della capacità necessaria per creare i cloni.

.Fasi
. Creare un file FlexClone o un LUN FlexClone utilizzando `volume file clone create` comando.
+
Nell'esempio seguente viene illustrato come creare un file FlexClone file1_clone del file padre file1_source nel volume vol1:

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
Per ulteriori informazioni sull'utilizzo di questo comando, vedere le pagine man.



.Informazioni correlate
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^]
