---
permalink: volumes/create-flexclone-task.html 
sidebar: sidebar 
keywords: create, flexclone volume 
summary: Creazione di un volume FlexClone. 
---
= Creare un volume FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un volume FlexClone per la protezione dei dati da un volume di destinazione SnapMirror o da un volume FlexVol padre che è un volume secondario SnapVault. A partire da ONTAP 9.7, è possibile creare un volume FlexClone da un volume FlexGroup. Una volta creato un volume FlexClone, non è possibile eliminare il volume padre mentre è presente il volume FlexClone.

.Di cosa hai bisogno
* La licenza FlexClone deve essere installata sul cluster.
* Il volume che si desidera clonare deve essere in linea.




== Creare un volume FlexClone di un FlexVol o FlexGroup

.Fase
. Creare un volume FlexClone:
+
`volume clone create`

+
[NOTE]
====
Durante la creazione di un volume FlexClone di lettura/scrittura dal volume padre di lettura/scrittura, non è necessario specificare la copia Snapshot di base. ONTAP crea una copia Snapshot se non si assegna un nome a una copia Snapshot specifica da utilizzare come copia Snapshot di base per il clone. È necessario specificare la copia Snapshot di base per la creazione di un volume FlexClone quando il volume padre è un volume di protezione dei dati.

====


.Esempio
* Il seguente comando crea un volume FlexClone di lettura/scrittura vol1_clone dal volume padre vol1:
+
`volume clone create -vserver vs0 -flexclone vol1_clone -type RW -parent-volume vol1`

* Il seguente comando crea un volume FlexClone di protezione dei dati vol_dp_clone dal volume d'origine dp_vol utilizzando la copia Snapshot di base snap1:
+
`volume clone create -vserver vs1 -flexclone vol_dp_clone -type DP -parent-volume dp_vol -parent-snapshot snap1`





== Creare un FlexClone di qualsiasi tipo di SnapLock

A partire da ONTAP 9.13.1, è possibile specificare uno dei tre tipi di SnapLock, `compliance`, `enterprise`, `non-snaplock`, Quando si crea un FlexClone di un volume RW. Per impostazione predefinita, viene creato un volume FlexClone con lo stesso tipo di SnapLock del volume padre. Tuttavia, è possibile eseguire l'override del valore predefinito utilizzando `snaplock-type` Durante la creazione del volume FlexClone.

Utilizzando il `non-snaplock` con il `snaplock-type` È possibile creare un volume FlexClone di tipo non SnapLock da un volume padre SnapLock per fornire un metodo più rapido per riportare i dati online quando necessario.

Scopri di più link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["SnapLock"].

.Prima di iniziare
Tenere presente le seguenti limitazioni dei volumi FlexClone quando hanno un tipo di SnapLock diverso da quello del volume padre.

* Sono supportati solo cloni di tipo RW. I cloni di tipo DP con un tipo SnapLock diverso dal volume padre non sono supportati.
* I volumi con LUN non possono essere clonati utilizzando l'opzione di tipo snaplock perché i volumi SnapLock non supportano le LUN.
* Non è possibile clonare un volume su un aggregato mirrorato di MetroCluster con un tipo di Compliance SnapLock perché i volumi di conformità SnapLock non sono supportati sugli aggregati mirrorati di MetroCluster.
* I volumi di conformità SnapLock con blocco legale non possono essere clonati con un tipo di SnapLock diverso. La conservazione a fini giudiziari è supportata solo sui volumi di conformità SnapLock.
* Il DR SVM non supporta i volumi SnapLock. Il tentativo di creare un clone SnapLock da un volume in una SVM che fa parte di una relazione DR SVM non riesce.
* Le Best practice di FabricPool consigliano che i cloni mantengano la stessa policy di tiering del padre. Tuttavia, un clone di conformità SnapLock di un volume abilitato a FabricPool non può avere lo stesso criterio di tiering del volume padre. La policy di tiering deve essere impostata su `none`. Tentativo di creare un clone di conformità SnapLock da un'origine con una policy di tiering diversa da `none` non funziona.


.Fasi
. Creare un volume FlexClone con un tipo di SnapLock: `volume clone create -vserver _svm_name_ -flexclone _flexclone_name_ -type RW [ -snaplock-type {non-snaplock|compliance|enterprise} ]`
+
Esempio:

+
[listing]
----
> volume clone create -vserver vs0 -flexclone vol1_clone -type RW -snaplock-type enterprise -parent-volume vol1
----

