---
permalink: volumes/create-flexclone-snapmirror-concept.html 
sidebar: sidebar 
keywords: considerations, creating, flexclone volume, from snapmirror, source, destination, volume, flexclone, snapmirror, future 
summary: È possibile creare un volume FlexClone dal volume di origine o di destinazione in una relazione SnapMirror esistente, ma ciò può avere un effetto su future operazioni di replica SnapMirror. 
---
= Considerazioni per la creazione di un volume FlexClone da un volume di origine o di destinazione SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un volume FlexClone dal volume di origine o di destinazione in una relazione SnapMirror di un volume esistente. Tuttavia, ciò potrebbe impedire il corretto completamento delle future operazioni di replica di SnapMirror.

La replica potrebbe non funzionare perché quando si crea il volume FlexClone, è possibile bloccare uno snapshot utilizzato da SnapMirror. In questo caso, SnapMirror interrompe la replica nel volume di destinazione fino a quando il volume FlexClone non viene distrutto o separato dal volume padre. Sono disponibili due opzioni per risolvere questo problema:

* Se si richiede temporaneamente il volume FlexClone e si riesce a contenere un'interruzione temporanea della replica SnapMirror, è possibile creare il volume FlexClone ed eliminarlo o separarlo dal relativo volume padre, se possibile.
+
La replica di SnapMirror continua normalmente quando il volume FlexClone viene cancellato o separato dal volume padre.

* Se un arresto temporaneo della replica SnapMirror non è accettabile, è possibile creare uno snapshot nel volume di origine SnapMirror e quindi utilizzare tale snapshot per creare il volume FlexClone. (Se si sta creando un volume FlexClone dal volume di destinazione, è necessario attendere che lo snapshot venga replicato nel volume di destinazione SnapMirror).
+
Questo metodo di creazione di uno snapshot nel volume di origine SnapMirror consente di creare il clone senza bloccare uno snapshot utilizzato da SnapMirror.


