---
permalink: volumes/delete-flexvol-task.html 
sidebar: sidebar 
keywords: delete, flexvol volume, flexvol, volume 
summary: 'È possibile utilizzare l"interfaccia a riga di comando di ONTAP per eliminare un FlexVol volume non più necessario.' 
---
= Eliminare un volume FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi eliminare un volume FlexVol non più necessario.

.Prima di iniziare
Nessuna applicazione deve accedere ai dati nel volume che si desidera eliminare.

[NOTE]
====
Se si elimina accidentalmente un volume, vederelink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Knowledge Base NetApp : come utilizzare la coda di ripristino del volume"^] .

====
.Fasi
. Se il volume è stato montato, smontarlo:
+
`volume unmount -vserver vserver_name -volume volume_name`

. Se il volume fa parte di una relazione SnapMirror, eliminare la relazione utilizzando `snapmirror delete` comando.
. Se il volume è online, portarlo offline:
+
`volume offline -vserver vserver_name volume_name`

. Eliminare il volume:
+
`volume delete -vserver vserver_name volume_name`





== Risultato

Il volume viene eliminato, insieme a eventuali criteri di quota e qtree associati.

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["eliminazione di snapmirror"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-unmount.html["smontare il volume"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-offline.html["volume offline"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["eliminazione dei volumi"]

