---
permalink: volumes/differences-hard-soft-threshold-quotas-concept.html 
sidebar: sidebar 
keywords: differences, hard, soft, threshold, quotas, quota, notification, prevent 
summary: Le quote fisse impediscono le operazioni, mentre le quote di soglia e soft attivano le notifiche. 
---
= Differenze tra quote rigide, morbide e di soglia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le quote rigide impediscono le operazioni mentre le quote morbide attivano le notifiche.

Le quote rigide impongono un limite massimo alle risorse di sistema; qualsiasi operazione che comporterebbe il superamento del limite fallisce. Le seguenti impostazioni creano le quote rigide:

* Parametro disk limit
* Parametro limite file


Le quote morbide inviano un messaggio di avviso quando l'utilizzo delle risorse raggiunge un determinato livello, ma non influiscono sulle operazioni di accesso ai dati, in modo da poter intraprendere le azioni appropriate prima che la quota venga superata. Le seguenti impostazioni creano quote soft:

* Soglia per il parametro Disk Limit
* Parametro Soft Disk Limit
* Parametro di limite dei file soft


Le quote Threshold e Soft Disk consentono agli amministratori di ricevere più di una notifica su una quota. In genere, gli amministratori impostano il valore Threshold for Disk Limit (soglia per limite disco) su un valore solo leggermente inferiore al limite del disco, in modo che la soglia fornisca un "avviso finale" prima che la scrittura inizi a non riuscire.
