---
permalink: volumes/disable-data-compression-volume-task.html 
sidebar: sidebar 
keywords: disable data compression 
summary: 'È possibile disattivare la compressione dei dati su un volume utilizzando il comando di modifica dell"efficienza del volume.' 
---
= Disattiva la compressione dei dati su un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile disattivare la compressione dei dati su un volume utilizzando `volume efficiency modify` comando.

.A proposito di questa attività
Se si desidera disattivare la compressione post-elaborazione, è necessario prima disattivare la compressione inline sul volume.

.Fasi
. Interrompere qualsiasi operazione di efficienza del volume attualmente attiva sul volume:
+
`volume efficiency stop`

. Disattivare la compressione dei dati:
+
`volume efficiency modify`

+
I dati compressi esistenti rimarranno compressi sul volume. Solo le nuove scritture che arrivano nel volume non vengono compresse.



.Esempi
Il seguente comando disattiva la compressione inline sul volume Vola:

`volume efficiency modify -vserver vs1 -volume VolA -inline-compression false`

Il seguente comando disattiva sia la compressione post-processo che la compressione inline sul volume Vola:

`volume efficiency modify -vserver vs1 -volume VolA -compression false -inline-compression false`
