---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data, compaction, fas systems 
summary: 'È possibile controllare la compattazione dei dati inline sui sistemi FAS con aggregati di Flash Pool (ibridi) o HDD a livello di volume o aggregato utilizzando il comando shell del nodo di abilitazione della compattazione WAFL. La compattazione dei dati è disattivata per impostazione predefinita per i sistemi FAS.' 
---
= Consentire la compaction dei dati inline per i sistemi FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile controllare la compattazione dei dati inline sui sistemi FAS con aggregati di Flash Pool (ibridi) o HDD a livello di volume o aggregato utilizzando `volume efficiency` comando della shell del cluster. La compattazione dei dati è disattivata per impostazione predefinita per i sistemi FAS.

.A proposito di questa attività
Se si abilita la compaction dei dati a livello di aggregato, la compaction dei dati viene attivata su qualsiasi nuovo volume creato con una garanzia di spazio del volume di `none` nell'aggregato. L'abilitazione della compaction dei dati su un volume su un aggregato HDD utilizza risorse CPU aggiuntive.

.Fasi
. Passare al livello di privilegio avanzato: +
`set -privilege advanced`
. Controllare lo stato di compattazione dei dati dei volumi e degli aggregati per il nodo desiderato: +
`volume efficiency show -volume _volume_name_` +
. Consentire la compaction dei dati sul volume: +
`volume efficiency modify -volume _volume_name_ -data-compaction true`
+
[NOTE]
====
Se la compattazione dei dati è impostata su `false` per un aggregato o un volume, la compattazione non riesce. L'abilitazione della compaction non compatta i dati esistenti; solo le nuove scritture nel sistema vengono compattate. Il `volume efficiency start` Command contiene ulteriori informazioni su come comprimere i dati esistenti (in ONTAP 9.1 e versioni successive). +http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^]

====
. Visualizza le statistiche di compattazione:
`volume efficiency show -volume _volume_name_`

