---
permalink: volumes/enable-storage-efficiency-visualization-concept.html 
sidebar: sidebar 
keywords: storage, efficiency, visualization, storage aggregate 
summary: 'Mostrare viste differenti dell"efficienza dello storage di tutti gli aggregati nel sistema.' 
---
= Visualizzazione dell'efficienza dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare `storage aggregate show-efficiency` comando per visualizzare le informazioni sull'efficienza dello storage di tutti gli aggregati del sistema.

Il `storage aggregate show-efficiency` command dispone di tre viste diverse che possono essere richiamate passando le opzioni dei comandi.



== Vista predefinita

La vista predefinita visualizza il rapporto complessivo per ciascuno degli aggregati.

`cluster1::> storage aggregate show-efficiency`



== Vista dettagliata

Richiamare la vista dettagliata con `-details` opzione di comando. Questa vista visualizza quanto segue:

* Rapporto di efficienza globale per ciascuno degli aggregati.
* Rapporto complessivo senza copie Snapshot.
* Suddivisione del rapporto per le seguenti tecnologie di efficienza: Deduplica dei volumi, compressione dei volumi, copie Snapshot, cloni, compattazione dei dati, e deduplica in linea aggregata.


`cluster1::> storage aggregate show-efficiency -details`



== Vista avanzata

La vista avanzata è simile alla vista dettagliata e visualizza i dettagli utilizzati sia logici che fisici.

È necessario eseguire questo comando al livello di privilegio avanzato. Passare ai privilegi avanzati utilizzando `set -privilege advanced` comando.

Il prompt dei comandi diventa `cluster::*>`.

`cluster1::> set -privilege advanced`

Richiamare la vista avanzata con `-advanced` opzione di comando.

`cluster1::*> storage aggregate show-efficiency -advanced`

Per visualizzare i rapporti per un singolo aggregato, richiamare singolarmente `-aggregate _aggregate_name_` comando. Questo comando può essere eseguito a livello di amministratore, nonché a livello di privilegi avanzati.

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`
