---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency 
summary: 'Abilitazione della compattazione dei dati inline sui sistemi FAS con aggregati Flash Pool (ibridi) o aggregati HDD a livello di volume o aggregato.' 
---
= Consentire la compaction dei dati inline per i sistemi FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
YYou può abilitare la inline data compaction sui sistemi FAS con aggregati Flash Pool (ibridi) o aggregati HDD a livello di volume utilizzando il `volume efficiency` comando shell del cluster. La data compaction è disabilitata per impostazione predefinita per i volumi creati sui sistemi FAS. Ulteriori informazioni su `volume efficiency` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+efficiency["Riferimento al comando ONTAP"^].

.A proposito di questa attività
Per attivare la compattazione dei dati inline su un volume, `-space-guarantee` l'opzione deve essere impostata su `none`. L'abilitazione della compaction dei dati su un volume su un aggregato HDD utilizza risorse CPU aggiuntive.

.Fasi
. Passare al livello di privilegio avanzato:
+
[source, cli]
----
set -privilege advanced
----
+
Ulteriori informazioni su `set` nella link:https://docs.netapp.com/us-en/ontap-cli/set.html["Riferimento al comando ONTAP"^].

. Controllare lo stato di data compaction dei volumi e degli aggregati per il nodo desiderato:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
+
Ulteriori informazioni su `volume efficiency show` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["Riferimento al comando ONTAP"^].

. Abilita la data compaction sui volumi:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
Ulteriori informazioni su `volume efficiency modify` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Riferimento al comando ONTAP"^].

+
[NOTE]
====
Se la data compaction è impostata su `false` per un aggregato o un volume, la compattazione non riesce. L'abilitazione della compaction non compatta i dati esistenti; solo le nuove scritture nel sistema vengono compattate. Il `volume efficiency start` comando contiene ulteriori informazioni su come compattare i dati esistenti. Ulteriori informazioni su `volume efficiency start` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["Riferimento al comando ONTAP"^].

====
. Visualizza le statistiche di compattazione:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

