---
permalink: volumes/enable-large-vol-file-support-task.html 
sidebar: sidebar 
keywords: create, modify, volume, large file, large volume 
summary: È possibile abilitare il supporto per volumi e file di grandi dimensioni quando si crea un nuovo volume o si può modificare un volume esistente. 
---
= Supporta volumi di grandi dimensioni e file di grandi dimensioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.12.1 P2, è possibile creare un nuovo volume o modificare un volume esistente per abilitare il supporto di dimensioni massime di un volume di 300TB TB e dimensioni massime di un file (LUN) di 128TB TB.

.Prima di iniziare
* Sul cluster viene installato ONTAP 9.12.1 P2 o versione successiva.
* Sei un amministratore di cluster o SVM.




== Creare un nuovo volume

.Fase
. Creazione di un volume con supporto file e volumi di grandi dimensioni abilitato:
+
`volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -is-large-size-enabled true`



.Esempio
Nell'esempio seguente viene creato un nuovo volume con il supporto di grandi volumi e dimensioni file abilitato.

[listing]
----
volume create -vserver vs1 -volume big_vol1 -aggregate aggr1 -is-large-size-enabled true
----


== Modificare un volume esistente

. Modificare un volume per attivare il supporto di file e volumi di grandi dimensioni:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -is-large-size-enabled true`



.Esempio
Nell'esempio seguente viene modificato un volume esistente per supportare volumi e dimensioni dei file di grandi dimensioni.

[listing]
----
volume modify -vserver vs2 -volume data_vol -aggregate aggr1 -is-large-size-enabled true
----
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Creare un volume"]
* link:https://docs.netapp.com/us-en/ontap-cli-9141/["Riferimento comando"]

