---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency 
summary: 'Abilitazione della compattazione dei dati inline sui sistemi FAS con aggregati Flash Pool (ibridi) o aggregati HDD a livello di volume o aggregato.' 
---
= Consentire la compaction dei dati inline per i sistemi FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi abilitare la inline data compaction sui sistemi FAS con aggregati Flash Pool (ibridi) o aggregati HDD a livello di volume o aggregato utilizzando il `volume efficiency` comando shell del cluster. La compattazione dei dati è disattivata per impostazione predefinita per i sistemi FAS.

.A proposito di questa attività
Se si abilita la compaction dei dati a livello di aggregato, la compaction dei dati viene attivata su qualsiasi nuovo volume creato con una garanzia di spazio del volume di `none` nell'aggregato. L'abilitazione della compaction dei dati su un volume su un aggregato HDD utilizza risorse CPU aggiuntive.

.Fasi
. Passare al livello di privilegio avanzato:
+
[source, cli]
----
set -privilege advanced
----
. Controllare lo stato di data compaction dei volumi e degli aggregati per il nodo desiderato:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
. Abilita la data compaction sui volumi:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
[NOTE]
====
Se la data compaction è impostata su `false` per un aggregato o un volume, la compattazione non riesce. L'abilitazione della compaction non compatta i dati esistenti; solo le nuove scritture nel sistema vengono compattate. Il `volume efficiency start` comando contiene ulteriori informazioni su come compattare i dati esistenti. Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/ontap-cli["Riferimento al comando ONTAP"^].

====
. Visualizza le statistiche di compattazione:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

