---
permalink: volumes/enable-logical-space-reporting-enforcement-task.html 
sidebar: sidebar 
keywords: enable, logical, space, reporting, enforcement 
summary: 'A partire da ONTAP 9.4, è possibile attivare il reporting dello spazio logico. A partire da 9.5, è possibile abilitare l"applicazione dello spazio logico, o sia il reporting che l"applicazione congiunta.' 
---
= Abilitare il reporting e l'applicazione dello spazio logico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.4, è possibile attivare il reporting dello spazio logico. A partire da 9.5, è possibile abilitare l'applicazione dello spazio logico, o sia il reporting che l'applicazione congiunta.

.A proposito di questa attività
Oltre a consentire il reporting e l'applicazione dello spazio logico a livello di singolo volume, è possibile abilitarli a livello di SVM per ogni volume che supporta tale funzionalità. Se si abilitano le funzionalità di spazio logico per l'intera SVM, è possibile disattivarle anche per singoli volumi.

A partire da ONTAP 9.8, se si attiva la creazione di report dello spazio logico su un volume di origine SnapMirror, questo viene attivato automaticamente sul volume di destinazione dopo il trasferimento.

A partire da ONTAP 9.13.1, se l'opzione di imposizione è attivata su un volume di origine SnapMirror, la destinazione riporta il consumo di spazio logico e ne rispetta l'applicazione, consentendo una migliore pianificazione della capacità.


NOTE: Se si esegue una release di ONTAP precedente a ONTAP 9.13.1, si deve comprendere che, sebbene l'impostazione di imposizione venga trasferita al volume di destinazione di SnapMirror, il volume di destinazione non supporta l'imposizione. Di conseguenza, la destinazione riporta il consumo di spazio logico, ma non rispetta la sua applicazione.

Scopri di più link:https://docs.netapp.com/us-en/ontap/volumes/logical-space-reporting-enforcement-concept.html["Supporto della release ONTAP per il reporting dello spazio logico"].

.Scelte
* Abilitare il reporting dello spazio logico per un volume:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true`

* Abilitare l'imposizione dello spazio logico per un volume:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-enforcement-logical true`

* Abilitare insieme il reporting e l'applicazione dello spazio logico per un volume:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true -is-space-enforcement-logical true`

* Abilitare il reporting o l'applicazione dello spazio logico per una nuova SVM:
+
`+vserver create -vserver _svm_name_ -rootvolume root-_volume_name_ -rootvolume-security-style unix -data-services {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`

* Abilitare il reporting o l'imposizione dello spazio logico per una SVM esistente:
+
`+vserver modify -vserver _svm_name_ {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`


