---
permalink: volumes/enable-disable-background-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, background, deduplication, aff systems 
summary: Attiva o disattiva la deduplica a livello di aggregato per i volumi o determina se la funzione è attivata. 
---
= Gestire la deduplica in background a livello aggregato sui sistemi AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La deduplica a livello di aggregato elimina i blocchi duplicati nei volumi appartenenti allo stesso aggregato. A partire da ONTAP 9.3, è possibile eseguire la deduplica a livello aggregato in background sui sistemi AFF. La funzione è attivata per impostazione predefinita per tutti i volumi appena creati e tutti i volumi aggiornati con la deduplica in background del volume attivata.

.A proposito di questa attività
L'operazione viene attivata automaticamente quando viene compilata una percentuale sufficiente del registro delle modifiche. Nessuna pianificazione o policy è associata all'operazione.

A partire da ONTAP 9.4, gli utenti di AFF possono anche eseguire lo scanner di deduplica a livello aggregato per eliminare i duplicati dei dati esistenti nei volumi dell'aggregato. È possibile utilizzare `storage aggregate efficiency cross-volume-dedupe start` con il `-scan-old-data=true` opzione per avviare lo scanner:

[listing]
----
cluster-1::> storage aggregate efficiency cross-volume-dedupe start -aggregate aggr1 -scan-old-data true
----
La scansione della deduplica può richiedere molto tempo. Potrebbe essere necessario eseguire l'operazione in ore non di punta.

[NOTE]
====
La deduplica in background a livello di aggregato viene talvolta definita deduplica in background tra volumi.

====
Ulteriori informazioni su `storage aggregate efficiency cross-volume-dedupe start` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-start.html["Riferimento al comando ONTAP"^].

.Fasi
. Gestire la deduplica in background a livello aggregato sui sistemi AFF:
+
[cols="2*"]
|===
| Se si desidera... | Utilizzare questo comando 


 a| 
Abilitare la deduplica in background a livello aggregato
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe true`



 a| 
Disattiva la deduplica in background a livello di aggregato
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe false`



 a| 
Visualizzare lo stato della deduplica di background a livello aggregato
 a| 
`aggregate efficiency cross-volume-dedupe show`

|===


Per ulteriori informazioni sui comandi descritti in questa procedura, consultare la link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].
