---
permalink: volumes/enforced-quotas-differ-configured-concept.html 
sidebar: sidebar 
keywords: why, enforced, quotas, differ, configured, quotas 
summary: Comprendere la differenza tra le quote applicate e le quote configurate in modo da poter confrontare le quote applicate visualizzate nei report delle quote con le quote configurate 
---
= Perché le quote applicate differiscono dalle quote configurate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le quote applicate differiscono dalle quote configurate perché le quote derivate vengono applicate senza essere configurate, ma le quote configurate vengono applicate solo dopo che sono state inizializzate correttamente. La comprensione di queste differenze consente di confrontare le quote applicate visualizzate nei report delle quote con quelle configurate.

Le quote applicate, visualizzate nei report delle quote, potrebbero differire dalle regole delle quote configurate per i seguenti motivi:

* Le quote derivate vengono applicate senza essere configurate come regole di quota. ONTAP crea automaticamente quote derivate in risposta alle quote predefinite.
* Le quote potrebbero non essere state reinizializzate su un volume dopo la configurazione delle regole di quota.
* È possibile che si siano verificati errori durante l'inizializzazione delle quote su un volume.

