---
permalink: volumes/examples-quota-config-concept.html 
sidebar: sidebar 
keywords: examples, quota, configuration, volume quota policy 
summary: Questi esempi aiutano a comprendere come configurare le quote e leggere i report delle quote. 
---
= Esempi di configurazione delle quote
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questi esempi aiutano a comprendere come configurare le quote e leggere i report delle quote.

.A proposito di questi esempi
Per i seguenti esempi, si supponga di avere un sistema storage che includa una SVM, `vs1`, con un volume, `vol1` .

. Per avviare la configurazione delle quote, è necessario creare una nuova policy di quota per la SVM:
+
[listing]
----
cluster1::>volume quota policy create -vserver vs1 -policy-name quota_policy_vs1_1
----
. Dato che la policy delle quote è una novità, la assegnerai alla SVM:
+
[listing]
----
cluster1::>vserver modify -vserver vs1 -quota-policy quota_policy_vs1_1
----


.Esempio 1: Quota utente predefinita
. Si decide di imporre un limite massimo di 50MB per ogni utente in `vol1`:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target "" -disk-limit 50MB -qtree ""
----
. Per attivare la nuova regola, inizializza le quote sul volume:
+
[listing]
----
cluster1::>volume quota on -vserver vs1 -volume vol1 -foreground
----
. Viene visualizzato il report quota:
+
[listing]
----
cluster1::>volume quota report
----


Il report delle quote risultante è simile al report seguente:

[listing]
----
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    49MB   50MB      37       -   *
vol1               user    root        0B      -       1       -
----
La prima riga mostra la quota utente predefinita creata, compreso il limite di dischi. Come tutte le quote predefinite, questa quota utente predefinita non visualizza informazioni sull'utilizzo di disco o file. Oltre alla quota creata, vengono visualizzate altre due quote. Esiste una quota per ogni utente che possiede file su `vol1`. Queste quote aggiuntive sono quote utente derivate automaticamente dalla quota utente predefinita. La quota utente derivata per l'utente `jsmith` ha lo stesso limite di 50MB dischi della quota utente predefinita. La quota utente derivata per l'utente root è una quota di monitoraggio (senza limiti).

Se un utente del sistema (diverso dall'utente root) tenta di eseguire un'azione che userebbe più di 50MB in `vol1` (ad esempio, la scrittura su un file da un editor), l'azione non riesce.

.Esempio 2: Quota utente esplicita che sovrascrera una quota utente predefinita
. Se è necessario fornire più spazio in volume `vol1` all'utente `jsmith`, immettere il seguente comando:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target jsmith -disk-limit 80MB -qtree ""
----
+
Si tratta di una quota utente esplicita, in quanto l'utente è esplicitamente elencato come destinazione della regola di quota.

+
Si tratta di una modifica a un limite di quota esistente, poiché modifica il limite del disco della quota utente derivata per l'utente `jsmith` sul volume. Pertanto, non è necessario reinizializzare le quote sul volume per attivare la modifica.

. Per ridimensionare le quote:
+
[listing]
----
cluster1::>volume quota resize -vserver vs1 -volume vol1 -foreground
----
+
Le quote rimangono attive durante il ridimensionamento e il processo di ridimensionamento è breve.



Il report delle quote risultante è simile al report seguente:

[listing]
----
cluster1::> volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    50MB   80MB      37       -   jsmith
vol1               user    root        0B      -       1       -
3 entries were displayed.
----
La seconda riga ora mostra un limite di disco di `80MB` e uno specificatore di quota di `jsmith` .

Pertanto, `jsmith` può utilizzare fino a 80MB GB di spazio `vol1` anche se tutti gli altri utenti sono ancora limitati a 50MB GB.

.Esempio 3: Soglie
Si supponga di voler ricevere una notifica quando gli utenti raggiungono un massimo di 5 MB dei limiti dei dischi.

. Per creare una soglia di 45MB per tutti gli utenti e una soglia di 75MB per `jsmith`, si modificano le regole di quota esistenti:
+
[listing]
----
cluster1::>volume quota policy rule modify -vserver vs1 -policy quota_policy_vs1_1 -volume vol1 -type user -target "" -qtree "" -threshold 45MB
cluster1::>volume quota policy rule modify -vserver vs1 -policy quota_policy_vs1_1 -volume vol1 -type user -target jsmith -qtree "" -threshold 75MB
----
+
Poiché le dimensioni delle regole esistenti vengono modificate, le quote vengono ridimensionate sul volume per attivare le modifiche. Attendere il completamento del processo di ridimensionamento.

. Per visualizzare il report delle quote con le soglie, aggiungere `-thresholds` al `volume quota report` comando:
+
[listing]
----
cluster1::>volume quota report -thresholds
Vserver: vs1
                                    ----Disk----  ----Files-----
Volume   Tree      Type    ID        Used  Limit   Used    Limit  Quota
                                          (Thold)                 Specifier
-------  --------  ------  -------  -----  -----  ------  ------  ---------
vol1               user    *           0B   50MB       0       -  *
                                           (45MB)
vol1               user    jsmith    59MB   80MB      55       -  jsmith
                                           (75MB)
vol1               user    root        0B      -       1       -
                                           ( -)
3 entries were displayed.
----
+
Le soglie vengono visualizzate tra parentesi nella colonna Disk Limit (limite disco).



.Esempio 4: Quote su qtree
Supponiamo di dover partizionare dello spazio per due progetti. È possibile creare due qtree, denominati `proj1` e `proj2`, per ospitare i progetti all'interno di `vol1`.

Attualmente, gli utenti possono utilizzare lo spazio di un qtree pari a quello assegnato per l'intero volume (a condizione che non superino il limite del volume utilizzando lo spazio nella directory principale o in un altro qtree). Inoltre, ciascuno dei qtree può crescere per consumare l'intero volume.

. Se si desidera garantire che nessuna delle due dimensioni di qtree superi i 20 GB, è possibile creare una quota ad albero predefinita sul volume:
+
[listing]
----
cluster1:>>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type tree -target "" -disk-limit 20GB
----
+

NOTE: Il tipo corretto è _tree_, non qtree.

. Poiché si tratta di una nuova quota, non è possibile attivarla ridimensionandola. Reinizializzare le quote sul volume:
+
[listing]
----
cluster1:>>volume quota off -vserver vs1 -volume vol1
cluster1:>>volume quota on -vserver vs1 -volume vol1 -foreground
----


[NOTE]
====
È necessario attendere circa cinque minuti prima di riattivare le quote su ciascun volume interessato, in quanto si tenta di attivarle quasi immediatamente dopo l'esecuzione di `volume quota off` il comando potrebbe causare errori. In alternativa, è possibile eseguire i comandi per reinizializzare le quote per un volume dal nodo che contiene il volume specifico.

====
Le quote non vengono applicate durante il processo di reinizializzazione, che richiede più tempo del processo di ridimensionamento.

Quando si visualizza un report quota, sono presenti diverse nuove righe. Alcune linee sono per le quote ad albero e alcune linee sono per le quote utente derivate.

Le nuove righe seguenti si riferiscono alle quote della struttura:

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
...
vol1               tree    *           0B   20GB       0       -   *
vol1     proj1     tree    1           0B   20GB       1       -   proj1
vol1     proj2     tree    2           0B   20GB       1       -   proj2
...
----
La quota ad albero predefinita creata viene visualizzata nella prima nuova riga, con un asterisco (*) nella colonna ID. In risposta alla quota tree predefinita su un volume, ONTAP crea automaticamente quote tree derivate per ogni qtree del volume. Questi sono mostrati nelle linee dove `proj1` e `proj2` appaiono nella `Tree` colonna.

Le seguenti nuove righe si riferiscono alle quote utente derivate:

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
...
vol1     proj1     user    *           0B   50MB       0       -
vol1     proj1     user    root        0B      -       1       -
vol1     proj2     user    *           0B   50MB       0       -
vol1     proj2     user    root        0B      -       1       -
...
----
Le quote utente predefinite su un volume vengono ereditate automaticamente per tutti i qtree contenuti in quel volume, se le quote sono attivate per i qtree. Quando è stata aggiunta la prima quota qtree, sono state attivate le quote sui qtree. Pertanto, sono state create quote utente predefinite derivate per ogni qtree. Questi sono indicati nelle righe in cui ID è asterisco (*).

Poiché l'utente root è il proprietario di un file, quando sono state create quote utente predefinite per ciascuno dei qtree, sono state create anche quote di rilevamento speciali per l'utente root su ciascuno dei qtree. Questi vengono visualizzati nelle righe in cui ID è root.

.Esempio 5: Quota utente su un qtree
. Hai deciso di limitare gli utenti a una minore quantità `proj1` di spazio nella qtree rispetto a quella presente nel volume complessivo.  `proj1`Pertanto, è consigliabile evitare di utilizzare oltre 10MB PB di dati nel qtree. Pertanto, si crea una quota utente predefinita per il qtree:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target "" -disk-limit 10MB -qtree proj1
----
+
Si tratta di una modifica a una quota esistente, in quanto modifica la quota utente predefinita per il qtree proj1 derivato dalla quota utente predefinita sul volume. Pertanto, è possibile attivare la modifica ridimensionando le quote. Una volta completato il processo di ridimensionamento, è possibile visualizzare il report delle quote.

+
Nel report delle quote viene visualizzata la seguente nuova riga che mostra la nuova quota utente esplicita per il qtree:

+
[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     user    *           0B   10MB       0       -   *
----
+
Tuttavia, `jsmith` all'utente non è consentito scrivere più dati nel qtree proj1 perché la quota creata per sovrascrivere la quota utente predefinita (per fornire più spazio) si trovava sul volume. Una volta aggiunta una quota utente predefinita sul `proj1` qtree, tale quota viene applicata e limita tutto lo spazio degli utenti in tale qtree, incluso `jsmith`.

. Per fornire più spazio all'utente `jsmith`, è necessario aggiungere una regola esplicita di quota utente per il qtree con un limite di 80MB dischi per ignorare la regola predefinita di quota utente per il qtree:
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target jsmith -disk-limit 80MB -qtree proj1
----
+
Poiché si tratta di una quota esplicita per la quale esiste già una quota predefinita, la modifica viene attivata ridimensionando le quote. Una volta completato il processo di ridimensionamento, viene visualizzato un report delle quote.



Nel report delle quote viene visualizzata la seguente nuova riga:

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     user    jsmith    61MB   80MB      57       -   jsmith
----
Il report finale sulle quote è simile al seguente:

[listing]
----
cluster1::>volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               tree    *           0B   20GB       0       -   *
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    70MB   80MB      65       -   jsmith
vol1     proj1     tree    1           0B   20GB       1       -   proj1
vol1     proj1     user    *           0B   10MB       0       -   *
vol1     proj1     user    root        0B      -       1       -
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj2     user    *           0B   50MB       0       -
vol1     proj2     user    root        0B      -       1       -
vol1               user    root        0B      -       3       -
vol1     proj1     user    jsmith    61MB   80MB      57       -   jsmith
11 entries were displayed.
----
L'utente `jsmith` deve rispettare i seguenti limiti di quota per scrivere su un file in `proj1`:

. La quota ad albero per il `proj1` qtree.
. Quota utente sul `proj1` qtree.
. La quota utente sul volume.

