---
permalink: volumes/flexclone-volumes-files-luns-concept.html 
sidebar: sidebar 
keywords: how , flexclone, volumes, work, flexclone files, flexClone luns 
summary: È possibile creare un volume FlexClone di un volume FlexVol che contiene un file FlexClone e un LUN FlexClone e il relativo file padre o LUN. 
---
= Come funzionano i volumi FlexClone con i file FlexClone e le LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un volume FlexClone di un volume FlexVol che contiene un file FlexClone e un LUN FlexClone e il relativo file padre o LUN.

I file FlexClone o le LUN FlexClone e i relativi file padre o LUN presenti nel volume FlexClone continuano a condividere i blocchi allo stesso modo del volume FlexVol padre. Infatti, tutte le entità FlexClone e le loro società madri condividono gli stessi blocchi di dati fisici sottostanti, riducendo al minimo l'utilizzo dello spazio su disco fisico.

Se il volume FlexClone viene diviso dal volume principale, i file FlexClone o le LUN FlexClone e i relativi file padre o LUN smettono di condividere i blocchi nel clone del volume FlexClone. In seguito, esistono come file indipendenti o LUN. Ciò significa che il clone del volume utilizza più spazio rispetto a prima dell'operazione di suddivisione.
