---
permalink: volumes/logical-space-reporting-enforcement-concept.html 
sidebar: sidebar 
keywords: logical, space, reporting, enforcement, volumes 
summary: A partire da ONTAP 9.4, è possibile consentire agli utenti di visualizzare lo spazio logico utilizzato in un volume e la quantità di spazio di storage rimanente. A partire da 9.5, è possibile limitare la quantità di spazio logico consumata dagli utenti. 
---
= Report e applicazione dello spazio logico per la panoramica dei volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.4, è possibile consentire agli utenti di visualizzare lo spazio logico utilizzato in un volume e la quantità di spazio di storage rimanente. A partire da ONTAP 9.5, è possibile limitare la quantità di spazio logico consumata dagli utenti.

Per impostazione predefinita, il reporting e l'imposizione dello spazio logico sono disattivati.

I seguenti tipi di volume supportano l'applicazione e il reporting dello spazio logico.

[cols="3*"]
|===
| Tipo di volume | Il reporting dello spazio è supportato? | L'applicazione dello spazio è supportata? 


 a| 
Volumi FlexVol
 a| 
Sì, a partire da ONTAP 9.4
 a| 
Sì, a partire da ONTAP 9.5



 a| 
Volumi di destinazione di SnapMirror
 a| 
Sì, a partire da ONTAP 9.8
 a| 
Sì, a partire da ONTAP 9.13.1



 a| 
Volumi FlexGroup
 a| 
Sì, a partire da ONTAP 9.9.1
 a| 
Sì, a partire da ONTAP 9.9.1



 a| 
Volumi FlexCache
 a| 
L'impostazione di origine viene utilizzata nella cache
 a| 
Non applicabile

|===