---
permalink: volumes/manage-aggregate-level-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, inline, deduplication, aff systems 
summary: Gestire la funzionalità di deduplica a livello di aggregato che elimina i blocchi duplicati dai volumi appartenenti allo stesso aggregato. 
---
= Gestione della deduplica inline a livello aggregato sui sistemi AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La deduplica a livello di aggregato elimina i blocchi duplicati nei volumi appartenenti allo stesso aggregato. A partire da ONTAP 9.2, è possibile eseguire la deduplica a livello aggregato inline sui sistemi AFF. La funzione è attivata per impostazione predefinita per tutti i volumi appena creati e tutti i volumi aggiornati con la deduplica inline del volume attivata.

.A proposito di questa attività
L'operazione di deduplica elimina i blocchi duplicati prima che i dati vengano scritti su disco. Solo i volumi con `space guarantee` impostare su `none` può partecipare alla deduplica inline a livello di aggregato. Questa è l'impostazione predefinita sui sistemi AFF.

[NOTE]
====
La deduplica inline a livello di aggregato viene talvolta definita deduplica inline tra volumi diversi.

====
.Fase
. Gestire la deduplica inline a livello aggregato sui sistemi AFF:
+
[cols="2*"]
|===
| Se si desidera... | Utilizzare questo comando 


 a| 
Consente la deduplica inline a livello di aggregato
 a| 
`volume efficiency modify -vserver vserver_name -volume vol_name -cross-volume-inline-dedupe true`



 a| 
Disattiva la deduplica inline a livello di aggregato
 a| 
`volume efficiency modify -vserver vserver_name -volume vol_name -cross-volume-inline-dedupe false`



 a| 
Visualizzare lo stato della deduplica inline a livello di aggregato
 a| 
`volume efficiency config -volume vol_name`

|===


.Esempi
Il seguente comando visualizza lo stato della deduplica inline a livello di aggregato:

[listing]
----

wfit-8020-03-04::> volume efficiency config -volume choke0_wfit_8020_03_0
Vserver:                                      vs0
Volume:                                       choke0_wfit_8020_03_0
Schedule:                                     -
Policy:                                       choke_VE_policy
Compression:                                  true
Inline Compression:                           true
Inline Dedupe:                                true
Data Compaction:                              true
Cross Volume Inline Deduplication:            false
----