---
permalink: volumes/methods-delete-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: methods, delete, flexclone, files, flexclone luns 
summary: È possibile utilizzare diversi metodi per eliminare i file FlexClone e le LUN FlexClone. La comprensione dei metodi disponibili consente di pianificare la gestione dei cloni. 
---
= Metodi per eliminare i file FlexClone e le LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare diversi metodi per eliminare i file FlexClone e le LUN FlexClone. La comprensione dei metodi disponibili consente di pianificare la gestione dei cloni.

Per eliminare i file FlexClone e le LUN FlexClone, è possibile utilizzare i seguenti metodi:

* È possibile configurare un volume FlexVol per eliminare automaticamente i cloni con l'opzione di eliminazione automatica attivata quando lo spazio libero in un volume FlexVol scende al di sotto di una determinata soglia.
* È possibile configurare i client per eliminare i cloni utilizzando NetApp Manageability SDK.
* È possibile utilizzare i client per eliminare i cloni utilizzando i protocolli NAS e SAN.
+
Il metodo di eliminazione più lento è attivato per impostazione predefinita perché questo metodo non utilizza NetApp Manageability SDK. Tuttavia, è possibile configurare il sistema in modo che utilizzi il metodo di eliminazione più rapida quando si eliminano i file FlexClone utilizzando `volume file clone deletion` comandi.


