---
permalink: volumes/modify-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: modify, volume, efficiency, policy 
summary: È possibile modificare una policy di efficienza dei volumi per eseguire la deduplica e la compressione dei dati per una durata diversa oppure modificare la pianificazione dei processi utilizzando il comando di modifica della policy di efficienza dei volumi. 
---
= Modificare una policy di efficienza dei volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare una policy di efficienza dei volumi per eseguire la deduplica e la compressione dei dati per una durata diversa o modificare la pianificazione dei processi utilizzando `volume efficiency policy modify` comando.

.Fase
. Utilizzare `volume efficiency policy modify` comando per modificare una policy di efficienza dei volumi.


.Esempi
Il seguente comando modifica la policy di efficienza del volume denominata policy 1 da eseguire ogni ora:

`volume efficiency policy modify -vserver vs1 -policy policy1 -schedule hourly`

Il seguente comando modifica una policy di efficienza del volume denominata pol2 in threshold 30%:

`volume efficiency policy modify -vserver vs1 -policy pol1 -type threshold -start-threshold-percent 30%`
