---
permalink: volumes/ndmp-dump-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, ndmp, works, flexclone files, flexclone luns 
summary: NDMP funziona a livello logico con file FlexClone e LUN FlexClone. Il backup di tutti i file o LUN FlexClone viene eseguito come file o LUN separati. 
---
= Funzionamento di NDMP con i file FlexClone e le LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP funziona a livello logico con file FlexClone e LUN FlexClone. Il backup di tutti i file o LUN FlexClone viene eseguito come file o LUN separati.

Quando si utilizzano i servizi NDMP per eseguire il backup di un qtree o di un volume FlexVol che contiene file FlexClone o LUN FlexClone, la condivisione dei blocchi tra entità padre e clone non viene preservata e le entità clonate vengono sottoposte a backup su nastro come file o LUN separati. Il risparmio di spazio viene perso. Pertanto, il nastro su cui si esegue il backup dovrebbe avere spazio sufficiente per memorizzare la quantità espansa di dati. Quando si esegue il ripristino, tutti i file FlexClone e le LUN FlexClone vengono ripristinati come file fisici e LUN separati. È possibile attivare la deduplica sul volume per ripristinare i vantaggi della condivisione di blocchi.

[NOTE]
====
Quando si creano file FlexClone e LUN FlexClone da una copia Snapshot esistente di un volume FlexVol, non è possibile eseguire il backup del volume su nastro fino al completamento del processo di condivisione dei blocchi, che avviene in background. Se si utilizza NDMP sul volume durante il processo di condivisione dei blocchi, il sistema visualizza un messaggio che richiede di riprovare l'operazione dopo un certo periodo di tempo. In una situazione del genere, è necessario continuare a provare l'operazione di backup su nastro in modo che abbia esito positivo al termine della condivisione dei blocchi.

====