---
permalink: volumes/obtain-qtree-junction-path-task.html 
sidebar: sidebar 
keywords: obtain, qtree, junction, path 
summary: È possibile montare un singolo qtree ottenendo il percorso di giunzione o il percorso dello spazio dei nomi del qtree. 
---
= Ottenere un percorso di giunzione qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile montare un singolo qtree ottenendo il percorso di giunzione o il percorso dello spazio dei nomi del qtree. Il percorso del qtree visualizzato dal comando CLI `qtree show -instance` è del formato `/vol/<volume_name>/<qtree_name>`. Tuttavia, questo percorso non fa riferimento al percorso di giunzione o al percorso dello spazio dei nomi del qtree.

.A proposito di questa attività
È necessario conoscere il percorso di giunzione del volume per ottenere il percorso di giunzione o il percorso dello spazio dei nomi del qtree.

.Fasi
. Utilizzare `vserver volume junction-path` per ottenere il percorso di giunzione di un volume.
+
Nell'esempio seguente viene visualizzato il percorso di giunzione del volume denominato vol1 situato sulla macchina virtuale di storage (SVM) denominata vs0:

+
[listing]
----
cluster1::> volume show -volume vol1 -vserver vs0 -fields junction-path

------- ------ -------------

vs0 vol1 /vol1
----
+
Dal suddetto output, il percorso di giunzione del volume è `/vol1`. Poiché i qtree sono sempre radicati nel volume, il percorso di giunzione o il percorso dello spazio dei nomi del qtree sarà `/vol1/qtree1`.


