---
permalink: volumes/quota-targets-types-concept.html 
sidebar: sidebar 
keywords: quotas, quota targets, quota types 
summary: 'Ogni quota ha un tipo specifico. La destinazione della quota deriva dal tipo e specifica l"utente, il gruppo o il qtree a cui vengono applicati i limiti di quota.' 
---
= Destinazioni e tipi di quota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni quota ha un tipo specifico. La destinazione della quota deriva dal tipo e specifica l'utente, il gruppo o il qtree a cui vengono applicati i limiti di quota.

Nella tabella seguente sono elencati gli obiettivi di quota, i tipi di quote a cui è associato ciascun obiettivo di quota e la modalità di rappresentazione di ciascun obiettivo di quota.

[cols="15,15,35,35"]
|===


| Destinazione della quota | Tipo di quota | Come viene rappresentato il target | Note 


 a| 
utente
 a| 
quota utente
 a| 
Nome utente UNIX UID UNIX

File o directory il cui UID corrisponde all'utente

Nome utente Windows in formato precedente a Windows 2000

SID di Windows

File o directory con un ACL di proprietà del SID dell'utente
 a| 
Le quote utente possono essere applicate a un volume o qtree specifico.



 a| 
gruppo
 a| 
quota di gruppo
 a| 
Nome del gruppo UNIX GID

Un file o una directory il cui GID corrisponde al gruppo
 a| 
Le quote di gruppo possono essere applicate a un volume o qtree specifico.


NOTE: ONTAP non applica quote di gruppo basate sugli ID Windows.



 a| 
qtree
 a| 
quota ad albero
 a| 
nome del qtree
 a| 
Le quote ad albero vengono applicate a un particolare volume e non influiscono sui qtree di altri volumi.



 a| 
`""`
 a| 
quota di preventivi utente

quota ad albero
 a| 
Virgolette doppie ("")
 a| 
Una destinazione di quota di "" indica una _quota predefinita_. Per le quote predefinite, il tipo di quota è determinato dal valore del campo tipo.

|===