---
permalink: volumes/quota-report-affect-writes-specific-file-task.html 
sidebar: sidebar 
keywords: use, quota report, determine, quotas limit, writes, specific file 
summary: Utilizzare il comando report quota volume con un percorso file specifico per determinare quali limiti di quota influiscono sulle operazioni di scrittura in un file. 
---
= Utilizzare il report delle quote per determinare il limite delle quote di scrittura in un file specifico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il comando del report quota volume con un percorso di file specifico per determinare quali limiti di quota influiscono sulle operazioni di scrittura in un file. In questo modo è possibile capire quale quota impedisce un'operazione di scrittura.

.Fasi
. Utilizzare il comando volume quota report con il parametro -path.


.Esempio di visualizzazione delle quote che influiscono su un file specifico
L'esempio seguente mostra il comando e l'output per determinare quali quote sono in vigore per le scritture nel file 1, che risiede nel qtree q1 nel volume FlexVol vol2:

[listing]
----
cluster1:> volume quota report -vserver vs0 -volume vol2 -path /vol/vol2/q1/file1
Virtual Server: vs0
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol2     q1        tree    jsmith     1MB  100MB       2   10000   q1
vol2     q1        group   eng        1MB  700MB       2   70000
vol2               group   eng        1MB  700MB       6   70000   *
vol2               user    corp\jsmith
                                      1MB   50MB       1       -   *
vol2     q1        user    corp\jsmith
                                      1MB   50MB       1       -
5 entries were displayed.
----