---
permalink: volumes/quotas-activated-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are activated, quota activation 
summary: 'Per rendere effettive le nuove quote e le modifiche alle quote esistenti. L"attivazione viene eseguita a livello di volume. Sapere come funziona l"attivazione delle quote può aiutare a gestire le quote con meno interruzioni.' 
---
= Panoramica dell'attivazione delle quote
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per rendere effettive le nuove quote e le modifiche alle quote esistenti. L'attivazione viene eseguita a livello di volume. Sapere come funziona l'attivazione delle quote può aiutare a gestire le quote con meno interruzioni.

Le quote vengono attivate tramite _inizializzazione_ (attivazione) o mediante _ridimensionamento_. La disattivazione e la riattivazione delle quote viene chiamata reinizializzazione.

La durata del processo di attivazione e il suo impatto sull'applicazione delle quote dipendono dal tipo di attivazione:

* Il processo di inizializzazione comprende due parti: A. `quota on` job e una scansione delle quote dell'intero file system del volume. La scansione inizia dopo `quota on` processo completato correttamente. La scansione delle quote può richiedere del tempo; maggiore è il numero di file presenti nel volume, maggiore sarà il tempo necessario. Fino al termine della scansione, l'attivazione della quota non viene completata e le quote non vengono applicate.
* Il processo di ridimensionamento richiede solo un `quota resize` lavoro. Il ridimensionamento richiede meno tempo rispetto all'inizializzazione di una quota perché non comporta una scansione di quota. Durante un processo di ridimensionamento, le quote continuano ad essere applicate.


Per impostazione predefinita, il `quota on` e. `quota resize` i lavori vengono eseguiti in background, consentendo di utilizzare contemporaneamente altri comandi.

Gli errori e gli avvisi del processo di attivazione vengono inviati al sistema di gestione degli eventi. Se si utilizza `-foreground` con il `volume quota on` oppure `volume quota resize` il comando non viene restituito fino al completamento del processo; ciò è utile se si esegue una reinizializzazione da uno script. Per visualizzare gli errori e gli avvisi in un secondo momento, è possibile utilizzare `volume quota show` con il `-instance` parametro.

L'attivazione della quota persiste tra gli arresti e si riavvia. Il processo di attivazione delle quote non influisce sulla disponibilità dei dati del sistema di storage.
