---
permalink: volumes/quotas-applied-root-user-concept.html 
sidebar: sidebar 
keywords: how, quotas are applied, root user 
summary: 'L"utente root (UID=0) sui client UNIX è soggetto a quote ad albero, ma non a quote utente o di gruppo. Ciò consente all"utente root di intraprendere azioni per conto di altri utenti che altrimenti sarebbero impedite da una quota.' 
---
= Modalità di applicazione delle quote all'utente root
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'utente root (UID=0) sui client UNIX è soggetto a quote ad albero, ma non a quote utente o di gruppo. Ciò consente all'utente root di intraprendere azioni per conto di altri utenti che altrimenti sarebbero impedite da una quota.

Quando root esegue un cambiamento di proprietà di file o directory o un'altra operazione (come UNIX `chown` Comando) per conto di un utente con meno privilegi, ONTAP controlla le quote in base al nuovo proprietario, ma non segnala errori o interrompe l'operazione, anche se vengono superate le restrizioni di quota rigida del nuovo proprietario. Ciò può essere utile quando un'azione amministrativa, come il ripristino dei dati persi, comporta il superamento temporaneo delle quote.

[NOTE]
====
Una volta eseguito il trasferimento di proprietà, tuttavia, un sistema client segnala un errore di spazio su disco se l'utente tenta di allocare più spazio su disco mentre la quota viene ancora superata.

====