---
permalink: volumes/quota-rules-policies-enforced-quotas-concept.html 
sidebar: sidebar 
keywords: what are, quota rules, quota policies, quotas 
summary: 'Le quote sono definite in regole di quota specifiche per i volumi FlexVol. Queste regole di quota vengono raccolte in una policy di quota di una macchina virtuale di storage (SVM) e attivate su ciascun volume della SVM.' 
---
= Quali sono le regole delle quote, le policy delle quote e le quote
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le quote sono definite in regole di quota specifiche per i volumi FlexVol. Queste regole di quota vengono raccolte in una policy di quota di una macchina virtuale di storage (SVM) e attivate su ciascun volume della SVM.

Una regola di quota è sempre specifica per un volume. Le regole di quota non hanno alcun effetto fino a quando le quote non vengono attivate sul volume definito nella regola di quota.

Un criterio di quota è un insieme di regole di quota per tutti i volumi di una SVM. Le policy di quota non sono condivise tra le SVM. Una SVM può disporre di un massimo di cinque criteri di quota, che consentono di disporre di copie di backup dei criteri di quota. Una policy di quota viene assegnata a una SVM in qualsiasi momento.

Una quota è la restrizione effettiva che ONTAP applica o il monitoraggio effettivo che ONTAP esegue. Una regola di quota determina sempre almeno una quota e potrebbe comportare molte quote derivate aggiuntive. L'elenco completo delle quote applicate è visibile solo nei report delle quote.

L'attivazione è il processo di attivazione di ONTAP per la creazione di quote applicate dall'attuale set di regole di quota nel criterio di quota assegnato. L'attivazione avviene volume per volume. La prima attivazione delle quote su un volume viene chiamata inizializzazione. Le attivazioni successive sono chiamate reinizializzazione o ridimensionamento, a seconda dell'ambito delle modifiche.

[NOTE]
====
Quando si inizializzano o si ridimensionano le quote su un volume, si attivano le regole di quota nel criterio di quota attualmente assegnato alla SVM.

====