---
permalink: volumes/quotas-concept.html 
sidebar: sidebar 
keywords: why use quotas 
summary: 'È possibile utilizzare le quote per limitare l"utilizzo delle risorse nei volumi FlexVol, fornire notifiche quando l"utilizzo delle risorse raggiunge livelli specifici o tenere traccia dell"utilizzo delle risorse.' 
---
= Perché utilizzare le quote
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare le quote per limitare l'utilizzo delle risorse nei volumi FlexVol, fornire notifiche quando l'utilizzo delle risorse raggiunge livelli specifici o tenere traccia dell'utilizzo delle risorse.

Specificare una quota per i seguenti motivi:

* Per limitare la quantità di spazio su disco o il numero di file che possono essere utilizzati da un utente o un gruppo o che possono essere contenuti da un qtree
* Per tenere traccia della quantità di spazio su disco o del numero di file utilizzati da un utente, un gruppo o un qtree, senza imporre alcun limite
* Per avvisare gli utenti quando l'utilizzo del disco o del file è elevato


Utilizza le quote predefinite, esplicite, derivate e tracciate per gestire l'utilizzo del disco nel modo più efficiente.
