---
permalink: volumes/quotas-applied-users-multiple-ids-concept.html 
sidebar: sidebar 
keywords: how, quotas are applied, users, multiple ids 
summary: Un utente può essere rappresentato da più ID. È possibile impostare una singola quota utente per tale utente specificando un elenco di ID come destinazione della quota. Un file di proprietà di uno qualsiasi di questi ID è soggetto alla limitazione della quota utente. 
---
= Modalità di applicazione delle quote agli utenti con ID multipli
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un utente può essere rappresentato da più ID. È possibile impostare una singola quota utente per tale utente specificando un elenco di ID come destinazione della quota. Un file di proprietà di uno qualsiasi di questi ID è soggetto alla limitazione della quota utente.

Si supponga che un utente disponga dell'UID UNIX 20 e dell'id Windows corp. john_smith e Engineering. Per questo utente, è possibile specificare una quota in cui la destinazione della quota è un elenco degli ID UID e Windows. Quando l'utente scrive nel sistema di storage, viene applicata la quota specificata, indipendentemente dal fatto che la scrittura abbia origine da UID 20, dall'azienda o dal tecnico.

[NOTE]
====
Le voci separate del file di quota sono considerate destinazioni separate, anche se gli ID appartengono allo stesso utente. Ad esempio, per lo stesso utente è possibile specificare una quota che limiti UID 20 a 1 GB di spazio su disco e un'altra quota che limiti corp/john_smith a 2 GB di spazio su disco, anche se entrambi gli ID rappresentano lo stesso utente. ONTAP applica le quote separatamente a UID 20 e a john smith.

In questo caso, non viene applicato alcun limite ai tecnici, anche se vengono applicati limiti agli altri ID utilizzati dallo stesso utente.

====