---
permalink: volumes/quotas-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, quotas work, with, flexclone files, flexclone luns 
summary: I limiti di quota vengono applicati alla dimensione logica totale dei file FlexClone o delle LUN FlexClone. Le operazioni di cloning non falliscono la condivisione dei blocchi anche se causa il superamento delle quote. 
---
= Come funzionano le quote con i file FlexClone e le LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I limiti di quota vengono applicati alla dimensione logica totale dei file FlexClone o delle LUN FlexClone. Le operazioni di cloning non falliscono la condivisione dei blocchi anche se causa il superamento delle quote.

Quando si crea un file FlexClone o un LUN FlexClone, le quote non riconoscono alcun risparmio di spazio. Ad esempio, se si crea un file FlexClone di un file padre di 10 GB, si utilizzano solo 10 GB di spazio fisico, ma l'utilizzo delle quote viene registrato come 20 GB (10 GB per il file padre e 10 GB per il file FlexClone).

Se la creazione di un file FlexClone o di un LUN determina il superamento della quota di gruppo o utente, l'operazione di clonazione riesce a condizione che il volume FlexVol disponga di spazio sufficiente per contenere i metadati per il clone. Tuttavia, la quota per quell'utente o gruppo viene sottoscritta in eccesso.
