---
permalink: volumes/recommended-volume-lun-config-combinations-concept.html 
sidebar: sidebar 
keywords: recommended, volume, file, lun configuration, combinations 
summary: Comprendere i vantaggi e i costi di combinazioni specifiche di FlexVol volume e configurazioni di file o LUN. 
---
= Panoramica delle combinazioni consigliate di configurazione di volume e file o LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono combinazioni specifiche di configurazioni di volume e file o LUN FlexVol che è possibile utilizzare, a seconda dei requisiti di amministrazione e dell'applicazione. Comprendere i vantaggi e i costi di queste combinazioni può aiutarti a determinare la configurazione giusta per il tuo ambiente.

Si consiglia di utilizzare le seguenti combinazioni di configurazione del volume e del LUN:

* File o LUN con spazio riservato con provisioning di volumi thick
* File o LUN non riservati in termini di spazio con provisioning di volumi thin
* File o LUN con spazio riservato con provisioning di volumi semi-spessi


È possibile utilizzare il thin provisioning SCSI sui LUN in combinazione con una qualsiasi di queste combinazioni di configurazione.



== File o LUN con spazio riservato con provisioning di volumi thick

*Benefici:*

* Tutte le operazioni di scrittura all'interno dei file con spazio riservato sono garantite; non si verificheranno errori a causa dello spazio insufficiente.
* Non esistono limitazioni all'efficienza dello storage e alle tecnologie di protezione dei dati sul volume.


*Costi e limitazioni:*

* È necessario disporre di spazio sufficiente per l'aggregato in primo piano per supportare il volume con provisioning spesso.
* Lo spazio pari al doppio delle dimensioni del LUN viene allocato dal volume al momento della creazione del LUN.




== File o LUN non riservati in termini di spazio con provisioning di volumi thin

*Benefici:*

* Non esistono limitazioni all'efficienza dello storage e alle tecnologie di protezione dei dati sul volume.
* Lo spazio viene allocato solo quando viene utilizzato.


*Costi e restrizioni:*

* Le operazioni di scrittura non sono garantite; possono fallire se il volume esaurisce lo spazio libero.
* È necessario gestire lo spazio libero nell'aggregato in modo efficace per evitare che l'aggregato esaurisca lo spazio libero.




== File o LUN con spazio riservato con provisioning di volumi semi-spessi

*Benefici:*

Meno spazio viene riservato in anticipo rispetto al provisioning di volumi spessi e viene comunque fornita una garanzia di scrittura con il massimo sforzo.

*Costi e restrizioni:*

* Con questa opzione, le operazioni di scrittura possono non riuscire.
+
È possibile ridurre questo rischio bilanciando correttamente lo spazio libero nel volume rispetto alla volatilità dei dati.

* Non puoi fare affidamento sulla conservazione di oggetti di data Protection come snapshot, file FlexClone e LUN.
* Non è possibile utilizzare le funzionalità di efficienza dello storage per la condivisione di blocchi di ONTAP che non possono essere eliminate automaticamente, tra cui deduplica, compressione e offload ODX/copia.

