---
permalink: volumes/rehost-san-task.html 
sidebar: sidebar 
keywords: rehost, san volumes 
summary: Rehosting di un volume SAN che serve dati tramite LUN mappate. 
---
= Rehosting di un volume SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il rehosting di un volume SAN che serve dati tramite LUN mappate. Dopo aver ricreato il gruppo iniziatore (igroup) nella SVM di destinazione, l'operazione di re-hosting del volume può eseguire automaticamente il remap del volume nella stessa SVM.

.A proposito di questa attività
* Il rehosting è un'operazione che interrompe.
* Se l'operazione di rehosting non riesce, potrebbe essere necessario riconfigurare i criteri del volume e le regole associate sul volume di origine.
* A partire da ONTAP 9.8, è supportato il rehosting di un volume con crittografia volume NetApp (NVE). Se si utilizza un gestore di chiavi integrato, i metadati crittografati verranno modificati durante l'operazione di rehosting. I dati dell'utente non vengono modificati.
+
Se si utilizza ONTAP 9.8 o una versione precedente, è necessario annullare la crittografia del volume prima di eseguire l'operazione di rehosting.



* Dopo l'operazione di rehosting, le seguenti policy, regole dei criteri e configurazioni del volume vengono perse dal volume di origine e devono essere riconfigurate manualmente sul volume rehosted:
+
** Policy antivirus
** Policy di efficienza dei volumi
** Policy sulla qualità del servizio (QoS)
** Policy di Snapshot
** criteri e regole di esportazione della configurazione di ns-switch e name services
** ID utente e gruppo




.Prima di iniziare
* Il volume deve essere online.
* Le operazioni di gestione dei volumi, come gli spostamenti dei volumi o delle LUN, non devono essere in esecuzione.
* Non devono essere presenti i/o attivi sui volumi o sui LUN.
* È necessario verificare che la SVM di destinazione non abbia igroup con lo stesso nome ma iniziatori diversi.
+
Se l'igroup ha lo stesso nome, è necessario rinominare l'igroup in una delle SVM (origine o destinazione).

* È necessario aver attivato `force-unmap-luns` opzione.
+
** Il valore predefinito di `force-unmap-luns` l'opzione è `false`.
** Quando si imposta, non viene visualizzato alcun messaggio di avviso o di conferma `force-unmap-luns` opzione a. `true`.




.Fasi
. Registrare le informazioni di mappatura LUN sul volume di destinazione:
+
`lun mapping show volume _volume_ vserver _source_svm_`

+
Si tratta di una procedura precauzionale per evitare la perdita di informazioni sulla mappatura LUN in caso di errore del rehost del volume.

. Elimina igroups associati al volume di destinazione.
. Eseguire nuovamente l'hosting del volume di destinazione nella SVM di destinazione:
+
`volume rehost -vserver _source_svm_ -volume _volume_name_ -destination-vserver _destination_svm_`

. Mappare i LUN del volume di destinazione agli igroup appropriati:
+
** Il re-hosting dei volumi preserva i LUN del volume di destinazione, tuttavia le LUN restano non mappate.
** Utilizzare la porta SVM di destinazione impostata durante la mappatura dei LUN.
** Se il `auto-remap-luns` l'opzione è impostata su `true`, I LUN vengono mappati automaticamente dopo il rehost.



