---
permalink: volumes/rehost-nfs-volumes-task.html 
sidebar: sidebar 
keywords: rehost, nfs, volumes 
summary: È possibile eseguire il rehosting dei volumi che servono i dati tramite il protocollo NFS. Dopo aver eseguito il rehosting dei volumi NFS, per continuare ad accedere ai dati tramite il protocollo NFS, è necessario associare il volume alla policy di esportazione della SVM di hosting e configurare manualmente i criteri e le regole associate. 
---
= Eseguire nuovamente l'hosting dei volumi NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il rehosting dei volumi che servono i dati tramite il protocollo NFS. Dopo aver eseguito il rehosting dei volumi NFS, per continuare ad accedere ai dati tramite il protocollo NFS, è necessario associare il volume alla policy di esportazione della SVM di hosting e configurare manualmente i criteri e le regole associate.

.Di cosa hai bisogno
* Il volume deve essere online.
* Le operazioni di gestione dei volumi, come gli spostamenti dei volumi o delle LUN, non devono essere in esecuzione.
* L'accesso ai dati al volume che viene reospitato deve essere interrotto.
* La configurazione ns-switch e name Services della SVM di destinazione deve essere configurata per supportare l'accesso ai dati del volume di re-hosting.
* L'ID utente e l'ID gruppo del volume devono essere disponibili nella SVM di destinazione o modificati nel volume di hosting.


.A proposito di questa attività
* Il rehosting è un'operazione che interrompe.
* Se l'operazione di rehosting non riesce, potrebbe essere necessario riconfigurare i criteri del volume e le regole associate sul volume di origine.
* Dopo l'operazione di rehosting, le seguenti policy, regole dei criteri e configurazioni del volume vengono perse dal volume di origine e devono essere riconfigurate manualmente sul volume rehosted:
+
** Policy di esportazione di volumi e qtree
** Policy antivirus
** Policy di efficienza dei volumi
** Policy sulla qualità del servizio (QoS)
** Policy di Snapshot
** Regole di quota
** criteri e regole di esportazione della configurazione di ns-switch e name services
** ID utente e gruppo




.Fasi
. Registrare le informazioni relative ai criteri di esportazione NFS per evitare di perdere informazioni sui criteri NFS in caso di errore dell'operazione di rehost del volume.
. Smontare il volume dal volume padre:
+
`volume unmount`

. Passare al livello di privilegio avanzato:
+
`set -privilege advanced`

. Eseguire nuovamente l'hosting del volume sulla SVM di destinazione:
+
`volume rehost -vserver source_svm -volume vol_name -destination-vserver destination_svm`

+
Il criterio di esportazione predefinito della SVM di destinazione viene applicato al volume rehosted.

. Creare la policy di esportazione:
+
`vserver export-policy create`

. Aggiornare il criterio di esportazione del volume reospitato in un criterio di esportazione definito dall'utente:
+
`volume modify`

. Montare il volume sotto il percorso di giunzione appropriato nella SVM di destinazione:
+
`volume mount`

. Verificare che il servizio NFS sia in esecuzione sulla SVM di destinazione.
. Riprendere l'accesso NFS al volume reospitato.
. Aggiornare le credenziali del client NFS e le configurazioni LIF per riflettere le LIF SVM di destinazione.
+
Questo perché il percorso di accesso al volume (LIF e percorso di giunzione) è stato modificato.



.Al termine
È necessario riconfigurare manualmente i criteri e le regole associate sul volume rehosted.

https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config/index.html["Configurazione NFS"]
