---
permalink: volumes/run-efficiency-operations-manual-existing-data-task.html 
sidebar: sidebar 
keywords: run, efficiency, operations, manually, existing, data 
summary: Eseguire manualmente le operazioni di efficienza sui dati esistenti nei volumi di efficienza dello storage non sensibili alla temperatura prima di abilitare la deduplica, la compressione dei dati o la data compaction. 
---
= Eseguire manualmente un'operazione di efficienza sui dati esistenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi eseguire manualmente le operazioni di efficienza sui dati presenti nei volumi di efficienza dello storage non sensibili alla temperatura prima di abilitare la deduplica, la compressione dei dati o la data compaction. Queste operazioni possono essere eseguite con versioni di ONTAP precedenti a ONTAP 9.8.

.A proposito di questa attività
Questa operazione viene eseguita utilizzando il `volume efficiency start` comando con il `-scan-old-data` parametro. L' `-compression` opzione non funziona con `-scan-old-data` sui volumi di efficienza dello storage sensibili alla temperatura. La compressione dei dati inattivi viene eseguita automaticamente sui dati preesistenti per i volumi dell'efficienza dello storage sensibili alla temperatura in ONTAP 9,8 e versioni successive.

Se si attiva solo la deduplica su un volume, la deduplica viene eseguita sui dati. Se si abilitano deduplica, compressione dei dati e compaction dei dati su un volume, la compressione dei dati viene eseguita per prima, seguita da deduplica e compaction dei dati.

Quando si esegue la compressione dei dati sui dati esistenti, per impostazione predefinita l'operazione di compressione dei dati salta i blocchi di dati condivisi dalla deduplica e i blocchi di dati che sono bloccati dagli snapshot. Se si sceglie di eseguire la compressione dei dati su blocchi condivisi, l'ottimizzazione viene disattivata e le informazioni sulle impronte digitali vengono acquisite e riutilizzate per la condivisione. È possibile modificare il comportamento predefinito della compressione dei dati durante la compressione dei dati esistenti.

È possibile eseguire un massimo di otto operazioni di deduplica, compressione dei dati o compattazione dei dati contemporaneamente per nodo. Le operazioni rimanenti vengono inserite nella coda.

[NOTE]
====
La compressione post-process non viene eseguita sulle piattaforme AFF. Viene generato un messaggio EMS per informare che questa operazione è stata ignorata.

====
Ulteriori informazioni su `volume efficiency start` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["Riferimento al comando ONTAP"^].

.Fasi
. Utilizzare `volume efficiency start -scan-old-data` comando per eseguire la deduplica, la compressione dei dati o la compattazione dei dati manualmente sui dati esistenti.
+
Il seguente comando consente di eseguire queste operazioni manualmente sui dati esistenti nel volume Vola:

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true [-compression | -dedupe | -compaction ] true`



.Informazioni correlate
* link:run-efficiency-operations-manual-task.html["Eseguire manualmente le operazioni di efficienza"]

