---
permalink: volumes/snapshot-copies-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, snapshot copies, work, flexclone files, flexclone luns 
summary: Comprendi la sinergia tra snapshot, file FlexClone e LUN FlexClone, oltre a determinate restrizioni. 
---
= Modalità di funzionamento delle snapshot con FlexClone Files e LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esiste una sinergia tra le snapshot, FlexClone Files e le LUN di FlexClone. Se si lavora con queste tecnologie, è necessario essere consapevoli di ciò che è possibile e delle relative restrizioni.

.Creazione di file e LUN FlexClone in corso
È possibile creare un file FlexClone o un LUN FlexClone da uno snapshot esistente. La copia si basa sui file padre e sulle LUN padre contenuti in una FlexVol volume.

.Eliminazione di uno snapshot
Non è possibile eliminare manualmente uno snapshot da cui sono attualmente creati file FlexClone o LUN FlexClone. Lo snapshot rimane bloccato fino al completamento del processo di condivisione dei blocchi in background. Se si tenta di eliminare uno snapshot bloccato, il sistema visualizza un messaggio che richiede di riprovare l'operazione dopo un certo periodo di tempo. In questo caso, è necessario continuare a provare nuovamente l'operazione di eliminazione. Sarà possibile eliminare lo snapshot al termine della condivisione del blocco.
