---
permalink: volumes/specify-unix-users-quotas-concept.html 
sidebar: sidebar 
keywords: specify, unix users, for quotas 
summary: È possibile specificare un utente UNIX per una quota in uno dei diversi formati. 
---
= Specificare gli utenti UNIX per le quote
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile specificare un utente UNIX per una quota in uno dei diversi formati.

I tre formati disponibili quando si specifica un utente UNIX per una quota includono:

* Il nome utente (ad esempio jsmith).
+
[NOTE]
====
Non è possibile utilizzare un nome utente UNIX per specificare una quota se tale nome include una barra rovesciata ( @) o un simbolo " ". Questo perché ONTAP considera i nomi che contengono questi caratteri come nomi Windows.

====
* L'ID utente o l'UID (ad esempio 20).
* Il percorso di un file o di una directory di proprietà dell'utente, in modo che l'UID del file corrisponda all'utente.
+
[NOTE]
====
Se si specifica un nome di file o di directory, è necessario selezionare un file o una directory che durerà fino a quando l'account utente rimane nel sistema.

Se si specifica un nome di file o directory per l'UID, ONTAP non applica una quota a tale file o directory.

====

