---
permalink: volumes/specify-windows-users-quotas-concept.html 
sidebar: sidebar 
keywords: how to, specify, windows users, for quotas 
summary: 'È possibile specificare un utente Windows per una quota utilizzando uno dei tre formati seguenti: Il nome di Windows in formato precedente a Windows 2000, il SID o un file o una directory di proprietà del SID dell"utente.' 
---
= Modalità di specifica degli utenti Windows per le quote
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile specificare un utente Windows per una quota utilizzando uno dei tre formati seguenti: Il nome di Windows in formato precedente a Windows 2000, il SID o un file o una directory di proprietà del SID dell'utente.

Per specificare un utente Windows per una quota, è possibile utilizzare uno dei seguenti formati:

* Il nome di Windows in formato precedente a Windows 2000.
* L'ID di protezione (SID), come visualizzato da Windows in forma di testo, ad esempio S-1-5-32-544.
* Il nome di un file o di una directory che ha un ACL di proprietà del SID dell'utente.
+
[NOTE]
====
Se si specifica un nome di file o di directory, è necessario selezionare un file o una directory che durerà fino a quando l'account utente rimane nel sistema.

Affinché ONTAP ottenga il SID dall'ACL, l'ACL deve essere valido.

Se il file o la directory esiste in un qtree di stile UNIX o se il sistema di storage utilizza la modalità UNIX per l'autenticazione dell'utente, ONTAP applica la quota utente all'utente il cui *UID*, non SID, corrisponde a quello del file o della directory.

Se si specifica un nome di file o directory per identificare un utente per una quota, ONTAP non applica una quota a tale file o directory.

====

