---
permalink: volumes/storage-limits-reference.html 
sidebar: sidebar 
keywords: storage limits 
summary: 'Esistono limiti per gli oggetti di storage che è necessario prendere in considerazione durante la pianificazione e la gestione dell"architettura di storage.' 
---
= Limiti di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono limiti per gli oggetti di storage che è necessario prendere in considerazione durante la pianificazione e la gestione dell'architettura di storage.

I limiti dipendono spesso dalla piattaforma. Fare riferimento a. link:https://hwu.netapp.com/["Hardware Universe"^] per conoscere i limiti della configurazione specifica.

I limiti sono elencati nelle seguenti sezioni:

* <<vollimits>>
* <<flexclone>>


I limiti di storage per Cloud Volumes ONTAP sono documentati nella link:https://docs.netapp.com/us-en/cloud-volumes-ontap/["Note di rilascio di Cloud Volumes ONTAP"^].



== Limiti di volume

[cols="4*"]
|===
| Oggetto di storage | Limite | Storage nativo | Storage array 


 a| 
*LUN array*
 a| 
Dimensione minima del volume root^1^
 a| 
N/A.
 a| 
In base al modello



 a| 
*File*
 a| 
Dimensione massima
 a| 
16 TB
 a| 
16 TB



 a| 
Massimo per volume^3^
 a| 
In base alle dimensioni del volume, fino a 2 miliardi
 a| 
In base alle dimensioni del volume, fino a 2 miliardi



 a| 
*Volumi FlexClone*
 a| 
Profondità del clone gerarchico^4^
 a| 
499
 a| 
499



 a| 
*Volumi FlexVol*
 a| 
Massimo per nodo^1^
 a| 
In base al modello
 a| 
In base al modello



 a| 
Massimo per nodo per SVM^5^
 a| 
In base al modello
 a| 
In base al modello



 a| 
Dimensione minima
 a| 
20 MB
 a| 
20 MB



 a| 
Dimensione massima^1^
 a| 
In base al modello
 a| 
In base al modello



 a| 
*Volumi FlexVol per carichi di lavoro primari*
 a| 
Massimo per nodo^2^
 a| 
In base al modello
 a| 
In base al modello



 a| 
*Volumi root FlexVol*
 a| 
Dimensione minima^1^
 a| 
In base al modello
 a| 
In base al modello



 a| 
*LUN*
 a| 
Massimo per nodo^5^
 a| 
In base al modello
 a| 
In base al modello



 a| 
Massimo per cluster^5^
 a| 
In base al modello
 a| 
In base al modello



 a| 
Massimo per volume^5^
 a| 
In base al modello
 a| 
In base al modello



 a| 
Dimensione massima
 a| 
16 TB
 a| 
16 TB



 a| 
*Qtree*
 a| 
Massimo per volume FlexVol
 a| 
4,995
 a| 
4,995



 a| 
*Copie Snapshot*
 a| 
Massimo per volume^6^
 a| 
255/1023
 a| 
255/1023



 a| 
*Volumi*
 a| 
Massimo per cluster per NAS
 a| 
12,000
 a| 
12,000



 a| 
Massimo per cluster con protocolli SAN configurati
 a| 
In base al modello
 a| 
In base al modello

|===
*Note:*

. In ONTAP 9.3 e versioni precedenti, un volume può contenere fino a 255 copie Snapshot. In ONTAP 9.4 e versioni successive, un volume può contenere fino a 1023 copie Snapshot.
. A partire da ONTAP 9,7, il numero massimo di volumi FlexVol supportati sulle piattaforme AFF con almeno 128 GB di memoria è aumentato a 2.500 volumi FlexVol per nodo.
+
Per informazioni specifiche sulla piattaforma e per informazioni aggiornate sul supporto, visitare il sito Web all'indirizzo https://hwu.netapp.com/["Hardware Universe"^].

. 2 miliardi = 2 × 10^9^.
. Profondità massima di una gerarchia nidificata di volumi FlexClone che è possibile creare da un singolo volume FlexVol.
. Questo limite si applica solo agli ambienti SAN.
+
link:../san-config/index.html["Configurazione SAN"]

. È possibile utilizzare una distribuzione a cascata di SnapMirror per aumentare questo limite.




== Limiti di file FlexClone e LUN FlexClone

[cols="3*"]
|===
| Limite | Storage nativo | Storage array 


 a| 
**Massimo per file o LUN**^1^
 a| 
32,767
 a| 
32,767



 a| 
*Massimo totale dei dati condivisi per volume FlexVol*
 a| 
640 TB
 a| 
640 TB

|===
*Nota:*

. Se si tenta di creare più di 32,767 cloni, ONTAP crea automaticamente una nuova copia fisica del file padre o del LUN.
+
Questo limite potrebbe essere inferiore per i volumi FlexVol che utilizzano la deduplica.



.Informazioni correlate
https://www.netapp.com/cloud-services/cloud-manager/documentation/["Trova le Note di rilascio relative alla tua versione di Cloud Volumes ONTAP"]
