---
permalink: volumes/tree-quotas-concept.html 
sidebar: sidebar 
keywords: how, tree, quotas, work 
summary: È possibile creare una quota con un qtree come destinazione per limitare le dimensioni del qtree di destinazione. Queste quote sono anche chiamate quote ad albero. 
---
= Panoramica sul funzionamento delle quote ad albero
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare una quota con un qtree come destinazione per limitare le dimensioni del qtree di destinazione. Queste quote sono anche denominate _quote albero_.

Quando si applica una quota a un qtree, il risultato è simile a una partizione del disco, con la differenza che è possibile modificare la dimensione massima del qtree in qualsiasi momento modificando la quota. Quando si applica una quota ad albero, ONTAP limita lo spazio su disco e il numero di file nel qtree, indipendentemente dai proprietari. Nessun utente, inclusi root e membri del gruppo BUILTIN/Administrators, può scrivere nel qtree se l'operazione di scrittura causa il superamento della quota tree.

[NOTE]
====
La dimensione della quota non garantisce una quantità specifica di spazio disponibile. La dimensione della quota può essere superiore alla quantità di spazio libero disponibile per il qtree. È possibile utilizzare `volume quota report` per determinare la quantità effettiva di spazio disponibile nel qtree.

====