---
permalink: volumes/user-ids-mixed-environment-concept.html 
sidebar: sidebar 
keywords: ontap determines, determine user ids, mixed environment 
summary: Diversi fattori determinano se ONTAP utilizza un ID UNIX o Windows quando si applicano le quote utente. 
---
= Come ONTAP determina gli ID utente in un ambiente misto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se sono presenti utenti che accedono allo storage ONTAP da client Windows e UNIX, per determinare la proprietà dei file vengono utilizzate sia la protezione Windows che quella UNIX. Diversi fattori determinano se ONTAP utilizza un ID UNIX o Windows quando si applicano le quote utente.

Se lo stile di protezione del volume qtree o FlexVol che contiene il file è solo NTFS o UNIX, lo stile di protezione determina il tipo di ID utilizzato durante l'applicazione delle quote utente. Per i qtree con lo stile di sicurezza misto, il tipo di ID utilizzato è determinato dalla presenza o meno di un ACL nel file.

La tabella seguente riassume il tipo di ID utilizzato.

[cols="3*"]
|===
| Stile di sicurezza | ACL | Nessun ACL 


 a| 
UNIX
 a| 
ID UNIX
 a| 
ID UNIX



 a| 
Misto
 a| 
ID Windows
 a| 
ID UNIX



 a| 
NTFS
 a| 
ID Windows
 a| 
ID Windows

|===