---
permalink: encryption-at-rest/change-encryption-key-volume-92-earlier-task.html 
sidebar: sidebar 
keywords: changing, encryption key, volume, volume move start, command 
summary: 'È consigliabile modificare periodicamente la chiave di crittografia di un volume. È possibile utilizzare il comando di avvio spostamento volume per modificare la chiave di crittografia. È necessario utilizzare l"avvio dello spostamento del volume in ONTAP 9.2 e versioni precedenti. Il volume spostato può risiedere sullo stesso aggregato o su un aggregato diverso.' 
---
= Modificare la chiave di crittografia per un volume con il comando di avvio spostamento volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È consigliabile modificare periodicamente la chiave di crittografia di un volume. È possibile utilizzare `volume move start` per modificare la chiave di crittografia. È necessario utilizzare `volume move start` In ONTAP 9.2 e versioni precedenti. Il volume spostato può risiedere sullo stesso aggregato o su un aggregato diverso.

.A proposito di questa attività
Non è possibile utilizzare `volume move start` Per modificare la chiave di un volume SnapLock o FlexGroup.

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster. In alternativa, puoi essere un amministratore SVM a cui l'amministratore del cluster ha delegato l'autorità. Per ulteriori informazioni, vedere link:delegate-volume-encryption-svm-administrator-task.html["delegare l'autorità per eseguire il comando di spostamento del volume"].

.Fasi
. Spostare un volume esistente e modificare la chiave di crittografia:
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -generate-destination-key true`

+
Per la sintassi completa dei comandi, vedere la pagina man del comando.

+
Il seguente comando sposta un volume esistente denominato `*vol1*` all'aggregato di destinazione `*aggr2*` e modifica la chiave di crittografia:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -generate-destination-key true
----
+
Viene creata una nuova chiave di crittografia per il volume. I dati sul volume rimangono crittografati.

. Verificare che il volume sia abilitato per la crittografia:
+
`volume show -is-encrypted true`

+
Per la sintassi completa dei comandi, vedere la pagina man del comando.

+
Il seguente comando visualizza i volumi crittografati su `cluster1`:

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----

