---
permalink: encryption-at-rest/configure-external-key-management-overview-concept.html 
sidebar: sidebar 
keywords: external key management, kmip, configure 
summary: 'È possibile utilizzare uno o più server di gestione delle chiavi esterni per proteggere le chiavi utilizzate dal cluster per accedere ai dati crittografati. Un server di gestione delle chiavi esterno è un sistema di terze parti nell"ambiente di storage che fornisce le chiavi ai nodi utilizzando il protocollo KMIP (Key Management Interoperability Protocol).' 
---
= Scopri come configurare la gestione delle chiavi esterne con ONTAP NetApp Volume Encryption
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare uno o più server di gestione delle chiavi esterni per proteggere le chiavi utilizzate dal cluster per accedere ai dati crittografati. Un server di gestione delle chiavi esterno è un sistema di terze parti presente nell'ambiente di storage che fornisce le chiavi ai nodi utilizzando il protocollo KMIP (Key Management Interoperability Protocol). Oltre a Onboard Key Manager, ONTAP supporta diversi server di gestione delle chiavi esterni.

 Beginning with ONTAP 9.10.1, you can use xref:manage-keys-azure-google-task.html[Azure Key Vault or Google Cloud Key Manager Service] to protect your NVE keys for data SVMs. Beginning with ONTAP 9.11.1, you can configure multiple external key managers in a cluster. See xref:configure-cluster-key-server-task.html[Configure clustered key servers]. Beginning with ONTAP 9.12.0, you can use link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html[AWS' KMS^] to protect your NVE keys for data SVMs. Beginning with ONTAP 9.17.1, you can use OpenStack's xref:manage-keys-barbican-task.html[Barbican KMS] to protect your NVE keys for data SVMs.