---
permalink: encryption-at-rest/create-authentication-keys-96-later-task.html 
sidebar: sidebar 
keywords: creating, authentication keys, ontap 9.6, later 
summary: È possibile utilizzare il comando create della chiave di gestione della sicurezza per creare le chiavi di autenticazione per un nodo e memorizzarle nei server KMIP configurati. 
---
= Creare chiavi di autenticazione in ONTAP 9.6 e versioni successive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `security key-manager key create` Per creare le chiavi di autenticazione per un nodo e memorizzarle nei server KMIP configurati.

.A proposito di questa attività
Se la configurazione della protezione richiede l'utilizzo di chiavi diverse per l'autenticazione dei dati e l'autenticazione FIPS 140-2, è necessario creare una chiave separata per ciascuna di esse. In caso contrario, è possibile utilizzare la stessa chiave di autenticazione per la conformità FIPS utilizzata per l'accesso ai dati.

ONTAP crea chiavi di autenticazione per tutti i nodi del cluster.

* Questo comando non è supportato quando Onboard Key Manager è attivato. Tuttavia, quando Onboard Key Manager è attivato, vengono create automaticamente due chiavi di autenticazione. I tasti possono essere visualizzati con il seguente comando:
+
[listing]
----
security key-manager key query -key-type NSE-AK
----
* Viene visualizzato un avviso se i server di gestione delle chiavi configurati memorizzano già più di 128 chiavi di autenticazione.
* È possibile utilizzare il `security key-manager key delete` comando per eliminare le chiavi non utilizzate. Il `security key-manager key delete` comando fallisce se la chiave specificata è attualmente in uso da ONTAP. (Per utilizzare questo comando è necessario avere Privileges maggiore di `admin`).
+
[NOTE]
====
In un ambiente MetroCluster, prima di eliminare una chiave, è necessario assicurarsi che la chiave non sia in uso nel cluster partner. È possibile utilizzare i seguenti comandi sul cluster partner per verificare che la chiave non sia in uso:

** `storage encryption disk show -data-key-id <key-id>`
** `storage encryption disk show -fips-key-id <key-id>`


====


.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.Fasi
. Creare le chiavi di autenticazione per i nodi del cluster:
+
[source, cli]
----
security key-manager key create -key-tag <passphrase_label> -prompt-for-key true|false
----
+
[NOTE]
====
L'impostazione `prompt-for-key=true` fa sì che il sistema richieda all'amministratore del cluster di utilizzare la passphrase durante l'autenticazione dei dischi crittografati. In caso contrario, il sistema genera automaticamente una passphrase da 32 byte. Il `security key-manager key create` comando sostituisce il `security key-manager create-key` comando. Ulteriori informazioni su `security key-manager key create` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-create.html?q=security+key-manager+key+create["Riferimento al comando ONTAP"^].

====
+
Nell'esempio seguente vengono create le chiavi di autenticazione per `cluster1`, che genera automaticamente una passphrase da 32 byte:

+
[listing]
----
cluster1::> security key-manager key create
Key ID: <id_value>
----
. Verificare che le chiavi di autenticazione siano state create:
+
[listing]
----
security key-manager key query -node node
----
+
[NOTE]
====
Il `security key-manager key query` comando sostituisce il `security key-manager query key` comando.

L'ID della chiave visualizzato nell'output è un identificatore utilizzato per fare riferimento alla chiave di autenticazione. Non si tratta della chiave di autenticazione effettiva o della chiave di crittografia dei dati.

====
+
Nell'esempio seguente viene verificata la creazione di chiavi di autenticazione per `cluster1`:

+
[listing]
----
cluster1::> security key-manager key query
       Vserver: cluster1
   Key Manager: external
          Node: node1

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node1                                 NSE-AK    yes
    Key ID: <id_value>
node1                                 NSE-AK    yes
    Key ID: <id_value>

       Vserver: cluster1
   Key Manager: external
          Node: node2

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node2                                 NSE-AK    yes
    Key ID: <id_value>
node2                                 NSE-AK    yes
    Key ID: <id_value>
----
+
Ulteriori informazioni su `security key-manager key query` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["Riferimento al comando ONTAP"^].


