---
permalink: encryption-at-rest/data-seds-inaccessible-concept.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, emergency, shred,  drive, sed,  encrypt, destroy 
summary: 'Se si desidera rendere i dati su un"unità FIPS o SED permanentemente inaccessibili, mantenendo lo spazio inutilizzato dell"unità disponibile per i nuovi dati, è possibile disinfettare il disco. Se si desidera rendere i dati inaccessibili in modo permanente e non è necessario riutilizzare il disco, è possibile distruggerli.' 
---
= Rendere i dati su un disco FIPS o panoramica SED inaccessibili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera rendere i dati su un'unità FIPS o SED permanentemente inaccessibili, mantenendo lo spazio inutilizzato dell'unità disponibile per i nuovi dati, è possibile disinfettare il disco. Se si desidera rendere i dati inaccessibili in modo permanente e non è necessario riutilizzare il disco, è possibile distruggerli.

* Pulizia dei dischi
+
Quando si disigienizza un'unità con crittografia automatica, il sistema modifica la chiave di crittografia del disco in un nuovo valore casuale, ripristina lo stato di blocco all'accensione su false e imposta l'ID della chiave su un valore predefinito, ovvero l'ID protetto del produttore 0x0 (unità SAS) o una chiave nulla (unità NVMe). In questo modo, i dati sul disco non sono accessibili e non possono essere recuperati. È possibile riutilizzare i dischi sanitizzati come dischi di riserva non azzerati.

* Distruggere il disco
+
Quando si distrugge un disco FIPS o SED, il sistema imposta la chiave di crittografia del disco su un valore casuale sconosciuto e blocca il disco in modo irreversibile. In questo modo, il disco risulta inutilizzabile in modo permanente e i dati in esso contenuti sono inaccessibili in modo permanente.



È possibile sanificare o distruggere singole unità con crittografia automatica o tutte le unità con crittografia automatica per un nodo.
