---
permalink: encryption-at-rest/data-seds-inaccessible-concept.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, emergency, shred,  drive, sed,  encrypt, destroy 
summary: 'Se si desidera rendere i dati su un"unità FIPS o SED permanentemente inaccessibili, mantenendo lo spazio inutilizzato dell"unità disponibile per i nuovi dati, è possibile disinfettare il disco. Se si desidera rendere i dati inaccessibili in modo permanente e non è necessario riutilizzare il disco, è possibile distruggerli.' 
---
= Rendere i dati su un disco FIPS o panoramica SED inaccessibili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera rendere i dati su un'unità FIPS o SED permanentemente inaccessibili, mantenendo lo spazio inutilizzato dell'unità disponibile per i nuovi dati, è possibile disinfettare il disco. Se si desidera rendere i dati inaccessibili in modo permanente e non è necessario riutilizzare il disco, è possibile distruggerli.

* Pulizia dei dischi
+
Quando si disigienizza un'unità con crittografia automatica, il sistema modifica la chiave di crittografia del disco in un nuovo valore casuale, ripristina lo stato di blocco all'accensione su false e imposta l'ID della chiave su un valore predefinito, ovvero l'ID protetto del produttore 0x0 (unità SAS) o una chiave nulla (unità NVMe). In questo modo, i dati sul disco non sono accessibili e non possono essere recuperati. È possibile riutilizzare i dischi sanitizzati come dischi di riserva non azzerati.

* Distruggere il disco
+
Quando si distrugge un disco FIPS o SED, il sistema imposta la chiave di crittografia del disco su un valore casuale sconosciuto e blocca il disco in modo irreversibile. In questo modo, il disco risulta inutilizzabile in modo permanente e i dati in esso contenuti sono inaccessibili in modo permanente.



È possibile sanificare o distruggere singole unità con crittografia automatica o tutte le unità con crittografia automatica per un nodo.



== Sanificare un disco FIPS o SED

Se si desidera rendere i dati su un'unità FIPS o SED permanentemente inaccessibili e utilizzare l'unità per i nuovi dati, è possibile utilizzare `storage encryption disk sanitize` comando per la pulizia del disco.

.Di cosa hai bisogno
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.A proposito di questa attività
Quando si disigienizza un'unità con crittografia automatica, il sistema modifica la chiave di crittografia del disco in un nuovo valore casuale, ripristina lo stato di blocco all'accensione su false e imposta l'ID della chiave su un valore predefinito, ovvero l'ID protetto del produttore 0x0 (unità SAS) o una chiave nulla (unità NVMe). In questo modo, i dati sul disco non sono accessibili e non possono essere recuperati. È possibile riutilizzare i dischi sanitizzati come dischi di riserva non azzerati.

.Fasi
. Migrare tutti i dati che devono essere conservati in un aggregato su un altro disco.
. Eliminare l'aggregato sull'unità FIPS o SED da sanificare:
+
`storage aggregate delete -aggregate _aggregate_name_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. Identificare l'ID del disco per l'unità FIPS o SED da sanificare:
+
`storage encryption disk show -fields data-key-id,fips-key-id,owner`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. Se un disco FIPS è in esecuzione in modalità di conformità FIPS, impostare nuovamente l'ID della chiave di autenticazione FIPS per il nodo sul valore MSID 0x0 predefinito:
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id 0x0`

+
È possibile utilizzare `security key-manager query` Per visualizzare gli ID chiave.

+
[listing]
----
cluster1::> storage encryption disk modify -disk 1.10.2 -fips-key-id 0x0

Info: Starting modify on 1 disk.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. Igienizzare il disco:
+
`storage encryption disk sanitize -disk _disk_id_`

+
È possibile utilizzare questo comando per sanificare solo i dischi hot spare o rotti. Per sanificare tutti i dischi, indipendentemente dal tipo, utilizzare `-force-all-state` opzione. Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Viene richiesto di inserire una frase di conferma prima di continuare. Inserire la frase esattamente come mostrato sullo schermo.

====
+
[listing]
----
cluster1::> storage encryption disk sanitize -disk 1.10.2

Warning: This operation will cryptographically sanitize 1 spare or broken self-encrypting disk on 1 node.
         To continue, enter sanitize disk: sanitize disk

Info: Starting sanitize on 1 disk.
      View the status of the operation using the
      storage encryption disk show-status command.
----




== Distruggere un disco FIPS o SED

Se si desidera rendere i dati su un'unità FIPS o SED permanentemente inaccessibili e non è necessario riutilizzarli, è possibile utilizzare `storage encryption disk destroy` comando per distruggere il disco.

.Di cosa hai bisogno
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.A proposito di questa attività
Quando si distrugge un disco FIPS o SED, il sistema imposta la chiave di crittografia del disco su un valore casuale sconosciuto e blocca l'unità in modo irreversibile. In questo modo, il disco risulta praticamente inutilizzabile e i dati in esso contenuti permanentemente inaccessibili. Tuttavia, è possibile ripristinare le impostazioni predefinite del disco utilizzando l'ID fisico sicuro (PSID) stampato sull'etichetta del disco. Per ulteriori informazioni, vedere link:return-self-encrypting-disks-keys-not-available-task.html["Restituzione di un disco FIPS o SED in caso di smarrimento delle chiavi di autenticazione"].

[NOTE]
====
Non distruggere un disco FIPS o SED a meno che non si disponga del servizio non-Returnable Disk Plus (NRD Plus). La distruzione di un disco annulla la garanzia.

====
.Fasi
. Migrare tutti i dati che devono essere conservati in un aggregato su un altro disco diverso.
. Eliminare l'aggregato sull'unità FIPS o SED da distruggere:
+
`storage aggregate delete -aggregate aggregate_name`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. Identificare l'ID del disco per l'unità FIPS o SED da distruggere:
+
`storage encryption disk show`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. Distruggere il disco:
+
`storage encryption disk destroy -disk disk_id`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Viene richiesto di inserire una frase di conferma prima di continuare. Inserire la frase esattamente come mostrato sullo schermo.

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----




== Distruzione di emergenza dei dati su un disco FIPS o SED

In caso di emergenza di sicurezza, è possibile impedire immediatamente l'accesso a un disco FIPS o SED, anche se il sistema storage o il server KMIP non sono in grado di fornire alimentazione.

.Di cosa hai bisogno
* Se si utilizza un server KMIP privo di alimentazione, il server KMIP deve essere configurato con un elemento di autenticazione facilmente distrutto (ad esempio, una smart card o un'unità USB).
* Per eseguire questa attività, è necessario essere un amministratore del cluster.


.Fase
. Eseguire la cancellazione di emergenza dei dati su un disco FIPS o SED:
+
|===


| Se... 2+| Quindi... 


 a| 
Il sistema di storage è alimentato e hai tempo per portare il sistema di storage offline senza problemi
 a| 
.. Se il sistema storage è configurato come coppia ha, disattivare il Takeover.
.. Portare tutti gli aggregati offline ed eliminarli.
.. Impostare il livello di privilegio su Advanced: +
`set -privilege advanced`
.. Se il disco è in modalità di conformità FIPS, impostare nuovamente l'ID della chiave di autenticazione FIPS per il nodo sul valore MSID predefinito: +
`storage encryption disk modify -disk * -fips-key-id 0x0`
.. Arrestare il sistema storage.
.. Avviare in modalità di manutenzione.
.. Sanificare o distruggere i dischi:
+
*** Se si desidera rendere i dati sui dischi inaccessibili e continuare a riutilizzare i dischi, disinfettare i dischi: +
`disk encrypt sanitize -all`
*** Se si desidera rendere i dati sui dischi inaccessibili e non è necessario salvarli, distruggere i dischi: +
`disk encrypt destroy disk_id1 disk_id2 …`


+
[NOTE]
====
Il `disk encrypt sanitize` e. `disk encrypt destroy` i comandi sono riservati solo alla modalità di manutenzione. Questi comandi devono essere eseguiti su ciascun nodo ha e non sono disponibili per i dischi rotti.

====
.. Ripetere questi passaggi per il nodo partner. In questo modo, il sistema di storage viene disattivato in modo permanente e tutti i dati vengono cancellati. Per utilizzare di nuovo il sistema, è necessario riconfigurarlo.




 a| 
Il sistema storage è alimentato e i dati devono essere immediatamente sottratti
 a| 
.. *Se si desidera rendere i dati sui dischi inaccessibili e continuare a riutilizzare i dischi, eseguire la pulizia dei dischi:*
.. Se il sistema storage è configurato come coppia ha, disattivare il Takeover.
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

.. Se il disco è in modalità di conformità FIPS, impostare nuovamente l'ID della chiave di autenticazione FIPS per il nodo sul valore MSID predefinito:
+
`storage encryption disk modify -disk * -fips-key-id 0x0`

.. Igienizzare il disco:
+
`storage encryption disk sanitize -disk * -force-all-states true`


 a| 
.. *Se si desidera rendere i dati sui dischi inaccessibili e non è necessario salvarli, distruggere i dischi:*
.. Se il sistema storage è configurato come coppia ha, disattivare il Takeover.
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

.. Distruggere i dischi:
`storage encryption disk destroy -disk * -force-all-states true`




 a| 
Il sistema di storage esegue una panoramica, lasciando il sistema in uno stato di disattivazione permanente con tutti i dati cancellati. Per utilizzare di nuovo il sistema, è necessario riconfigurarlo.



 a| 
L'alimentazione è disponibile per il server KMIP ma non per il sistema storage
 a| 
.. Accedere al server KMIP.
.. Distruggere tutte le chiavi associate ai dischi FIPS o ai SED che contengono i dati a cui si desidera impedire l'accesso. In questo modo si impedisce l'accesso alle chiavi di crittografia del disco da parte del sistema di storage.




 a| 
L'alimentazione del server KMIP o del sistema storage non è disponibile
 a| 
Eliminare l'elemento di autenticazione per il server KMIP (ad esempio, la smart card). In questo modo si impedisce l'accesso alle chiavi di crittografia del disco da parte del sistema di storage.

|===
+
Per la sintassi completa dei comandi, vedere le pagine man.


