---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: È possibile utilizzare il comando di eliminazione del volume per eliminare un volume crittografato. 
---
= Eliminare un volume crittografato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `volume delete` comando per eliminare un volume crittografato.

.Di cosa hai bisogno
* Per eseguire questa attività, è necessario essere un amministratore del cluster o un amministratore SVM al quale l'amministratore del cluster ha delegato l'autorità.
+
link:delegate-volume-encryption-svm-administrator-task.html["Delega dell'autorizzazione all'esecuzione del comando di spostamento del volume"]

* Il volume deve essere offline.


.Fase
. Eliminazione di un volume crittografato:
+
`volume delete -vserver SVM_name -volume volume_name`

+
Per la sintassi completa dei comandi, vedere la pagina man del comando.

+
Il seguente comando elimina un volume crittografato denominato `vol1`:

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Invio `yes` quando viene richiesto di confermare l'eliminazione.

+
Il sistema elimina la chiave di crittografia per il volume dopo 24 ore.

+
Utilizzare `volume delete` con `-force true` opzione per eliminare un volume e distruggere immediatamente la chiave di crittografia corrispondente. Questo comando richiede privilegi avanzati. Per ulteriori informazioni, consulta la pagina man.



.Al termine
È possibile utilizzare `volume recovery-queue` comando per ripristinare un volume cancellato durante il periodo di conservazione dopo l'emissione di `volume delete` comando:

`volume recovery-queue SVM_name -volume volume_name`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Come utilizzare la funzione Volume Recovery (Ripristino volume)"]
