---
permalink: encryption-at-rest/delete-key-management-database-task.html 
sidebar: sidebar 
keywords: transitioning, onboard key management, external key management 
summary: Se si desidera passare alla gestione delle chiavi integrata dalla gestione delle chiavi esterna, è necessario eliminare la configurazione di gestione delle chiavi esterne prima di poter attivare la gestione delle chiavi integrata. 
---
= Transizione alla gestione delle chiavi integrata dalla gestione esterna delle chiavi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera passare alla gestione delle chiavi integrata dalla gestione delle chiavi esterna, è necessario eliminare la configurazione di gestione delle chiavi esterne prima di poter attivare la gestione delle chiavi integrata.

.Prima di iniziare
* Per la crittografia basata su hardware, è necessario ripristinare il valore predefinito delle chiavi dati di tutti i dischi FIPS o SED.
+
link:return-seds-unprotected-mode-task.html["Ripristino di un'unità FIPS o SED in modalità non protetta"]

* È necessario eliminare tutte le connessioni di gestione delle chiavi esterne.
+
link:remove-external-key-server-93-later-task.html["Eliminazione di una connessione di gestione delle chiavi esterna"]

* Per eseguire questa attività, è necessario essere un amministratore del cluster.




== Procedura

[role="tabbed-block"]
====
.ONTAP 9.6 e versioni successive
--
. Passare al livello di privilegio avanzato:
+
`set -privilege advanced`

. Utilizzare il comando:
+
`security key-manager external disable -vserver _admin_SVM_`

+

NOTE: In un ambiente MetroCluster, è necessario ripetere il comando su entrambi i cluster per la SVM amministrativa.



--
.ONTAP 9.5 e versioni precedenti
--
Utilizzare il comando:
`security key-manager delete-kmip-config`

--
====