---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: È possibile utilizzare il comando di eliminazione del volume per eliminare un volume crittografato. 
---
= Consente di eliminare un volume crittografato in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `volume delete` comando per eliminare un volume crittografato.

.Prima di iniziare
* Per eseguire questa attività, è necessario essere un amministratore del cluster.
* Il volume deve essere offline.


.Fase
. Eliminazione di un volume crittografato:
+
`volume delete -vserver _SVM_name_ -volume _volume_name_`

+
Ulteriori informazioni su `volume delete` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["Riferimento al comando ONTAP"^].

+
Il seguente comando elimina un volume crittografato denominato `vol1`:

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Invio `yes` quando viene richiesto di confermare l'eliminazione.

+
Il sistema elimina la chiave di crittografia per il volume dopo 24 ore.

+
Utilizzare `volume delete` con l' `-force true`opzione per eliminare un volume e distruggere immediatamente la chiave di crittografia corrispondente. Questo comando richiede privilegi avanzati. Ulteriori informazioni su `volume delete` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["Riferimento al comando ONTAP"^].



.Al termine
È possibile utilizzare `volume recovery-queue` comando per ripristinare un volume cancellato durante il periodo di conservazione dopo l'emissione di `volume delete` comando:

`volume recovery-queue _SVM_name_ -volume _volume_name_`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Come utilizzare la funzione Volume Recovery (Ripristino volume)"]
