---
permalink: encryption-at-rest/destroy-nse-disks-task.html 
sidebar: sidebar 
keywords: fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, encrypt, 
summary: 'Se si desidera rendere i dati su un"unità FIPS o SED permanentemente inaccessibili e non è necessario riutilizzarli, è possibile utilizzare `storage encryption disk destroy` comando per distruggere il disco.' 
---
= Distruggere un'unità FIPS o SED in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera rendere i dati su un'unità FIPS o SED permanentemente inaccessibili e non è necessario riutilizzarli, è possibile utilizzare `storage encryption disk destroy` comando per distruggere il disco.

.A proposito di questa attività
Quando si distrugge un disco FIPS o SED, il sistema imposta la chiave di crittografia del disco su un valore casuale sconosciuto e blocca l'unità in modo irreversibile. In questo modo, il disco risulta praticamente inutilizzabile e i dati in esso contenuti permanentemente inaccessibili. Tuttavia, è possibile ripristinare le impostazioni predefinite del disco utilizzando l'ID fisico sicuro (PSID) stampato sull'etichetta del disco. Per ulteriori informazioni, vedere link:return-self-encrypting-disks-keys-not-available-task.html["Restituzione di un disco FIPS o SED in caso di smarrimento delle chiavi di autenticazione"].


NOTE: Non distruggere un disco FIPS o SED a meno che non si disponga del servizio non-Returnable Disk Plus (NRD Plus). La distruzione di un disco annulla la garanzia.

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.Fasi
. Migrare tutti i dati che devono essere conservati in un aggregato su un altro disco diverso.
. Eliminare l'aggregato sull'unità FIPS o SED da distruggere:
+
`storage aggregate delete -aggregate aggregate_name`

+
Ulteriori informazioni su `storage aggregate delete` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["Riferimento al comando ONTAP"^].

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. Identificare l'ID del disco per l'unità FIPS o SED da distruggere:
+
`storage encryption disk show`

+
Ulteriori informazioni su `storage encryption disk show` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Riferimento al comando ONTAP"^].

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
1.10.2  data <id_value>
[...]
----
. Distruggere il disco:
+
`storage encryption disk destroy -disk disk_id`

+
Ulteriori informazioni su `storage encryption disk destroy` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-destroy.html["Riferimento al comando ONTAP"^].

+
[NOTE]
====
Viene richiesto di inserire una frase di conferma prima di continuare. Inserire la frase esattamente come mostrato sullo schermo.

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----

