---
permalink: encryption-at-rest/disable-encryption-by-default-97-higher-task.html 
sidebar: sidebar 
keywords: disabling, encryption, default, ontap 9.7, later 
summary: 'A partire da ONTAP 9.7, la crittografia aggregata e del volume è attivata per impostazione predefinita se si dispone di una licenza di crittografia del volume (VE) e si utilizza un gestore di chiavi integrato o esterno. Se necessario, è possibile disattivare la crittografia per impostazione predefinita.' 
---
= Disattiva la crittografia per impostazione predefinita con ONTAP 9.7 e versioni successive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.7, la crittografia aggregata e del volume è attivata per impostazione predefinita se si dispone di una licenza di crittografia del volume (VE) e si utilizza un gestore di chiavi integrato o esterno. Se necessario, è possibile disattivare la crittografia per impostazione predefinita per l'intero cluster.

.Di cosa hai bisogno
Per eseguire questa attività, è necessario essere un amministratore del cluster o un amministratore SVM al quale l'amministratore del cluster ha delegato l'autorità.

.Fase
. Per disattivare la crittografia per impostazione predefinita per l'intero cluster in ONTAP 9.7 o versioni successive, eseguire il seguente comando:
+
`options -option-name encryption.data_at_rest_encryption.disable_by_default -option-value on`


