---
permalink: encryption-at-rest/enable-external-key-management-96-later-nve-task.html 
sidebar: sidebar 
keywords: enabling, external key management, ontap 9.6, later, nve 
summary: È possibile utilizzare uno o più server KMIP per proteggere le chiavi utilizzate dal cluster per accedere ai dati crittografati. A partire da ONTAP 9.6, è possibile utilizzare uno o più server KMIP per proteggere le chiavi utilizzate da una determinata SVM per accedere ai dati crittografati. 
---
= Abilita la gestione delle chiavi esterne per NVE in ONTAP 9.6 e versioni successive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare i server KMIP per proteggere le chiavi utilizzate dal cluster per accedere ai dati crittografati.  A partire da ONTAP 9.6, è possibile configurare un gestore di chiavi esterno separato per proteggere le chiavi utilizzate da una SVM di dati per accedere ai dati crittografati.

A partire da ONTAP 9.11.1, è possibile aggiungere fino a 3 server chiavi secondari per server chiavi primario per creare un server chiavi in cluster. Per ulteriori informazioni, vedere xref:configure-cluster-key-server-task.html[Configurare i server di chiavi esterne in cluster].

.A proposito di questa attività
È possibile connettere fino a quattro server KMIP a un cluster o SVM.  Utilizzare almeno due server per la ridondanza e il ripristino in caso di emergenza.

L'ambito della gestione esterna delle chiavi determina se i server di gestione delle chiavi proteggono tutte le SVM nel cluster o solo le SVM selezionate:

* È possibile utilizzare un _ambito del cluster_ per configurare la gestione delle chiavi esterne per tutte le SVM nel cluster. L'amministratore del cluster ha accesso a tutte le chiavi memorizzate sui server.
* A partire da ONTAP 9.6, è possibile utilizzare un _ambito SVM_ per configurare la gestione delle chiavi esterne per una SVM di dati nel cluster. Questo è il meglio per gli ambienti multi-tenant in cui ciascun tenant utilizza una SVM (o un insieme di SVM) diversa per la distribuzione dei dati. Solo l'amministratore SVM di un determinato tenant ha accesso alle chiavi del tenant.
* Per gli ambienti multi-tenant, installare una licenza per _MT_EK_MGMT_ utilizzando il seguente comando:
+
`system license add -license-code <MT_EK_MGMT license code>`

+
Ulteriori informazioni su `system license add` nella link:https://docs.netapp.com/us-en/ontap-cli/system-license-add.html["Riferimento al comando ONTAP"^].



È possibile utilizzare entrambi gli ambiti nello stesso cluster. Se i server di gestione delle chiavi sono stati configurati per una SVM, ONTAP utilizza solo questi server per proteggere le chiavi. In caso contrario, ONTAP protegge le chiavi con i server di gestione delle chiavi configurati per il cluster.

È possibile configurare la gestione delle chiavi integrata nell'ambito del cluster e la gestione delle chiavi esterne nell'ambito SVM. È possibile utilizzare `security key-manager key migrate` Comando per la migrazione delle chiavi dalla gestione delle chiavi integrata nell'ambito del cluster ai key manager esterni nell'ambito SVM.

Ulteriori informazioni su `security key-manager key migrate` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-migrate.html["Riferimento al comando ONTAP"^].

.Prima di iniziare
* I certificati del server e del client SSL KMIP devono essere stati installati.
* Per eseguire questa attività, è necessario essere un amministratore del cluster o di SVM.
* In un ambiente MetroCluster :
+
** MetroCluster deve essere completamente configurato prima di abilitare la gestione delle chiavi esterne.
** È necessario installare lo stesso certificato SSL KMIP su entrambi i cluster.
** Su entrambi i cluster deve essere configurato un gestore delle chiavi esterno.




.Fasi
. Configurare la connettività del gestore delle chiavi per il cluster:
+
`security key-manager external enable -vserver admin_SVM -key-servers host_name|IP_address:port,... -client-cert client_certificate -server-ca-cert server_CA_certificates`

+

NOTE: IL `security key-manager external enable` il comando sostituisce il `security key-manager setup` comando.  Se si esegue il comando al prompt di accesso al cluster, `_admin_SVM_` per impostazione predefinita è l'SVM di amministrazione del cluster corrente.  Puoi eseguire il `security key-manager external modify` comando per modificare la configurazione della gestione delle chiavi esterne.

+
Il seguente comando abilita la gestione esterna delle chiavi per `cluster1` con tre key server esterni. Il primo server chiavi viene specificato utilizzando il nome host e la porta, il secondo viene specificato utilizzando un indirizzo IP e la porta predefinita, mentre il terzo viene specificato utilizzando un indirizzo IPv6 e una porta:

+
[listing]
----
clusterl::> security key-manager external enable -vserver cluster1 -key-servers ks1.local:15696,10.0.0.10,[fd20:8b1e:b255:814e:32bd:f35c:832c:5a09]:1234 -client-cert AdminVserverClientCert -server-ca-certs AdminVserverServerCaCert
----
. Configurare un gestore delle chiavi e una SVM:
+
`security key-manager external enable -vserver SVM -key-servers host_name|IP_address:port,... -client-cert client_certificate -server-ca-cert server_CA_certificates`

+
[NOTE]
====
** Se si esegue il comando al prompt di accesso SVM, `SVM` per impostazione predefinita è l'SVM corrente.  Puoi eseguire il `security key-manager external modify` comando per modificare la configurazione della gestione delle chiavi esterne.
** In un ambiente MetroCluster, se si configura la gestione esterna delle chiavi per una SVM di dati, non è necessario ripetere `security key-manager external enable` sul cluster partner.


====
+
Il seguente comando abilita la gestione esterna delle chiavi per `svm1` con un server a chiave singola in ascolto sulla porta predefinita 5696:

+
[listing]
----
svm1l::> security key-manager external enable -vserver svm1 -key-servers keyserver.svm1.com -client-cert SVM1ClientCert -server-ca-certs SVM1ServerCaCert
----
. Ripetere l'ultimo passaggio per eventuali SVM aggiuntive.
+
[NOTE]
====
Inoltre, è possibile utilizzare il `security key-manager external add-servers` comando per configurare SVM aggiuntive. Il `security key-manager external add-servers` comando sostituisce il `security key-manager add` comando. Ulteriori informazioni su `security key-manager external add-servers` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-add-servers.html["Riferimento al comando ONTAP"^].

====
. Verificare che tutti i server KMIP configurati siano connessi:
+
`security key-manager external show-status -node node_name`

+
[NOTE]
====
Il `security key-manager external show-status` comando sostituisce il `security key-manager show -status` comando. Ulteriori informazioni su `security key-manager external show-status` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-show-status.html["Riferimento al comando ONTAP"^].

====
+
[listing]
----
cluster1::> security key-manager external show-status

Node  Vserver  Key Server                                     Status
----  -------  ---------------------------------------        -------------
node1
      svm1
               keyserver.svm1.com:5696                        available
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available
node2
      svm1
               keyserver.svm1.com:5696                        available
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available

8 entries were displayed.
----
. Facoltativamente, convertire volumi di testo normale in volumi crittografati.
+
`volume encryption conversion start`

+
Prima di convertire i volumi, è necessario configurare completamente un gestore di chiavi esterno.



.Informazioni correlate
* xref:configure-cluster-key-server-task.html[Configurare i server di chiavi esterne in cluster]
* link:https://docs.netapp.com/us-en/ontap-cli/system-license-add.html["aggiunta licenza di sistema"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-migrate.html["migrazione delle chiavi del gestore delle chiavi di sicurezza"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-add-servers.html["server aggiuntivi esterni del gestore delle chiavi di sicurezza"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-show-status.html["gestore chiavi di sicurezza esterno mostra stato"^]

