---
permalink: encryption-at-rest/install-license-task.html 
sidebar: sidebar 
keywords: install, license, VE license, NVE, encryption, encrypt data 
summary: Una licenza VE consente di utilizzare la funzione su tutti i nodi del cluster. È necessario installare la licenza prima di poter crittografare i dati con NVE. 
---
= Installare la licenza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una licenza VE consente di utilizzare la funzione su tutti i nodi del cluster. È necessario installare la licenza prima di poter crittografare i dati con NVE.

.Di cosa hai bisogno
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.A proposito di questa attività
Dovresti aver ricevuto il codice di licenza VE dal tuo commerciale.

.Fasi
. Installare la licenza VE per un nodo:
+
`system license add -license-code license_key`

+
Il comando seguente installa la licenza con la chiave `AAAAAAAAAAAAAAAAAAAAAAAAAAAA`.

+
[listing]
----
cluster1::> system license add -license-code AAAAAAAAAAAAAAAAAAAAAAAAAAAA
----
. Verificare che la licenza sia installata visualizzando tutte le licenze sul cluster:
+
`system license show`

+
Per la sintassi completa dei comandi, vedere la pagina man del comando.

+
Il seguente comando visualizza tutte le licenze su `cluster1`:

+
[listing]
----
cluster1::> system license show
----
+
Il nome del pacchetto di licenza VE è "`VE`".


