---
permalink: encryption-at-rest/install-ssl-certificates-task.html 
sidebar: sidebar 
keywords: install, ssl, certificates, cluster 
summary: 'Il cluster e il server KMIP utilizzano i certificati SSL KMIP per verificare l"identità reciproca e stabilire una connessione SSL. Prima di configurare la connessione SSL con il server KMIP, è necessario installare i certificati SSL del client KMIP per il cluster e il certificato pubblico SSL per l"autorità di certificazione principale (CA) del server KMIP.' 
---
= Installare i certificati SSL sul cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il cluster e il server KMIP utilizzano i certificati SSL KMIP per verificare l'identità reciproca e stabilire una connessione SSL. Prima di configurare la connessione SSL con il server KMIP, è necessario installare i certificati SSL del client KMIP per il cluster e il certificato pubblico SSL per l'autorità di certificazione principale (CA) del server KMIP.

.A proposito di questa attività
In una coppia ha, entrambi i nodi devono utilizzare gli stessi certificati SSL KMIP pubblici e privati. Se si collegano più coppie ha allo stesso server KMIP, tutti i nodi delle coppie ha devono utilizzare gli stessi certificati SSL KMIP pubblici e privati.

.Prima di iniziare
* L'ora deve essere sincronizzata sul server che crea i certificati, sul server KMIP e sul cluster.
* È necessario avere ottenuto il certificato del client KMIP SSL pubblico per il cluster.
* È necessario aver ottenuto la chiave privata associata al certificato del client SSL KMIP per il cluster.
+
Il certificato del client SSL KMIP non deve essere protetto da password.

* È necessario aver ottenuto il certificato pubblico SSL per l'autorità di certificazione principale (CA) del server KMIP.
* In un ambiente MetroCluster, è necessario installare il certificato SSL KMIP su entrambi i cluster.



NOTE: È possibile installare i certificati client e server sul server KMIP prima o dopo l'installazione dei certificati sul cluster.

.Fasi
. Installare i certificati del client KMIP SSL per il cluster:
+
`security certificate install -vserver admin_svm_name -type client`

+
Viene richiesto di immettere i certificati SSL KMIP pubblici e privati.

+
`cluster1::> security certificate install -vserver cluster1 -type client`

. Installare il certificato pubblico SSL per l'autorità di certificazione principale (CA) del server KMIP:
+
`security certificate install -vserver admin_svm_name -type server-ca`

+
`cluster1::> security certificate install -vserver cluster1 -type server-ca`


