---
permalink: encryption-at-rest/purge-data-encrypted-volume-without-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume, encryption, snapmirror 
summary: A partire da ONTAP 9.4, è possibile utilizzare Secure-purge per eseguire lo scrubbing dei dati senza interruzioni su volumi abilitati per NVE. 
---
= Pulisci i dati da un volume ONTAP crittografato senza una relazione SnapMirror
:allow-uri-read: 


[role="lead"]
A partire da ONTAP 9.4, è possibile utilizzare la funzione Secure-purge per i dati "`scrub`" senza interruzioni su volumi abilitati per NVE.

.A proposito di questa attività
Il completamento dell'eliminazione sicura può richiedere da diversi minuti a molte ore, a seconda della quantità di dati contenuti nei file cancellati. È possibile utilizzare `volume encryption secure-purge show` per visualizzare lo stato dell'operazione. È possibile utilizzare `volume encryption secure-purge abort` per terminare l'operazione.


NOTE: Per eseguire un'eliminazione sicura su un host SAN, è necessario eliminare l'intero LUN contenente i file da eliminare oppure è necessario essere in grado di perforare i LUN per i blocchi che appartengono ai file che si desidera eliminare. Se non è possibile eliminare il LUN o se il sistema operativo host non supporta i fori di punzonatura nel LUN, non è possibile eseguire un'eliminazione sicura.

.Prima di iniziare
* Per eseguire questa attività, è necessario essere un amministratore del cluster.
* Per questa attività sono richiesti privilegi avanzati.


.Fasi
. Eliminare i file o il LUN che si desidera eliminare in modo sicuro.
+
** Su un client NAS, eliminare i file che si desidera eliminare in modo sicuro.
** Su un host SAN, eliminare il LUN che si desidera eliminare in modo sicuro o perforare i fori nel LUN per i blocchi che appartengono ai file che si desidera eliminare.


. Sul sistema storage, passare al livello di privilegio avanzato:
+
`set -privilege advanced`

. Se i file che si desidera eliminare in modo sicuro si trovano in snapshot, eliminare le snapshot:
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. Eliminare in modo sicuro i file cancellati:
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_`

+
Il seguente comando elimina in modo sicuro i file cancellati su `vol1` Su SVM``vs1``:

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. Verificare lo stato dell'operazione di eliminazione sicura:
+
`volume encryption secure-purge show`


