---
permalink: encryption-at-rest/replace-self-encrypting-disk-task.html 
sidebar: sidebar 
keywords: replacing, fips drive, sed 
summary: 'È possibile sostituire un"unità FIPS o SED nello stesso modo in cui si sostituisce un disco normale. Assicurarsi di assegnare nuove chiavi di autenticazione dei dati all"unità sostitutiva. Per un"unità FIPS, potrebbe essere necessario assegnare una nuova chiave di autenticazione FIPS 140-2.' 
---
= Sostituire un'unità FIPS o SED in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire un'unità FIPS o SED nello stesso modo in cui si sostituisce un disco normale. Assicurarsi di assegnare nuove chiavi di autenticazione dei dati all'unità sostitutiva. Per un'unità FIPS, potrebbe essere necessario assegnare una nuova chiave di autenticazione FIPS 140-2.


NOTE: Se è in uso una coppia ha link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html["Crittografia dei dischi SAS o NVMe (SED, NSE, FIPS)"], è necessario seguire le istruzioni riportate nell'argomento link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["Ripristino di un'unità FIPS o SED in modalità non protetta"] Per tutti i dischi all'interno della coppia ha prima dell'inizializzazione del sistema (opzioni di avvio 4 o 9). Il mancato rispetto di questa procedura potrebbe causare la perdita di dati in futuro se i dischi vengono riutilizzati.

.Prima di iniziare
* È necessario conoscere l'ID della chiave di autenticazione utilizzata dal disco.
* Per eseguire questa attività, è necessario essere un amministratore del cluster.


.Fasi
. Assicurarsi che il disco sia stato contrassegnato come guasto:
+
`storage disk show -broken`

+
Ulteriori informazioni su `storage disk show` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["Riferimento al comando ONTAP"^].

+
[listing]
----
cluster1::> storage disk show -broken
Original Owner: cluster1-01
  Checksum Compatibility: block
                                                                 Usable Physical
    Disk   Outage Reason HA Shelf Bay Chan   Pool  Type    RPM     Size     Size
    ------ ---- ------------ ---- --- ---- ------ -----  -----  -------  -------
    0.0.0  admin  failed  0b    1   0    A  Pool0  FCAL  10000  132.8GB  133.9GB
    0.0.7  admin  removed 0b    2   6    A  Pool1  FCAL  10000  132.8GB  134.2GB
[...]
----
. Rimuovere il disco guasto e sostituirlo con un nuovo disco FIPS o SED, seguendo le istruzioni nella guida hardware del modello di shelf di dischi in uso.
. Assegnare la proprietà del disco appena sostituito:
+
`storage disk assign -disk disk_name -owner node`

+
Ulteriori informazioni su `storage disk assign` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["Riferimento al comando ONTAP"^].

+
[listing]
----
cluster1::> storage disk assign -disk 2.1.1 -owner cluster1-01
----
. Verificare che il nuovo disco sia stato assegnato:
+
`storage encryption disk show`

+
Ulteriori informazioni su `storage encryption disk show` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Riferimento al comando ONTAP"^].

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.0  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
1.10.1  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
2.1.1   open 0x0
[...]
----
. Assegnare le chiavi di autenticazione dei dati all'unità FIPS o SED.
+
link:assign-authentication-keys-seds-external-task.html["Assegnazione di una chiave di autenticazione dei dati a un disco FIPS o SED (gestione esterna delle chiavi)"]

. Se necessario, assegnare una chiave di autenticazione FIPS 140-2 all'unità FIPS.
+
link:assign-fips-140-2-authentication-key-task.html["Assegnazione di una chiave di autenticazione FIPS 140-2 a un disco FIPS"]


