---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: A volte, potrebbe essere necessario ripristinare una chiave di crittografia integrata per la gestione delle chiavi. Una volta verificato che è necessario ripristinare una chiave, è possibile impostare Onboard Key Manager per ripristinarla. 
---
= Ripristina le chiavi di crittografia della gestione delle chiavi integrate in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procedura che segui per ripristinare le chiavi di crittografia della gestione delle chiavi integrate varia in base alla tua versione di ONTAP.

.Prima di iniziare
* Se si utilizza NSE con un server KMIP (Key Management) esterno, è necessario eliminare il database del gestore delle chiavi esterno. Per ulteriori informazioni, vedere link:delete-key-management-database-task.html["transizione alla gestione delle chiavi integrata dalla gestione delle chiavi esterna"]
* Per eseguire questa attività, è necessario essere un amministratore del cluster.



NOTE: Se stai utilizzando NSE su un sistema con un modulo Flash cache, dovresti abilitare anche NVE o NAE. NSe non crittografa i dati che risiedono nel modulo Flash cache.



== ONTAP 9.6 e versioni successive


IMPORTANT: Se si esegue ONTAP 9,8 o versione successiva e il volume root è crittografato, seguire la procedura descritta in <<ontap-9-8>>.

. Verificare che la chiave debba essere ripristinata: +
`security key-manager key query -node _node_`
+
Ulteriori informazioni su `security key-manager key query` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["Riferimento al comando ONTAP"^].

. Ripristinare la chiave: +
`security key-manager onboard sync`
+
Il seguente comando ONTAP 9.6 sincronizza le chiavi nella gerarchia di chiavi integrate:

+
[listing]
----
cluster1::> security key-manager onboard sync

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
----
+
Ulteriori informazioni su `security key-manager onboard sync` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-sync.html["Riferimento al comando ONTAP"^].

. Al prompt della passphrase, inserire la passphrase di gestione della chiave integrata per il cluster.




== ONTAP 9,8 o versione successiva con volume root crittografato

Se si utilizza ONTAP 9.8 e versioni successive e il volume root è crittografato, è necessario impostare una passphrase di ripristino per la gestione delle chiavi integrata nel menu di avvio. Questo processo è necessario anche se si esegue una sostituzione dei supporti di avvio.

. Avviare il nodo dal menu di boot e selezionare l'opzione `(10) Set onboard key management recovery secrets`.
. Invio `y` per utilizzare questa opzione.
. Quando richiesto, inserire la passphrase di gestione della chiave integrata per il cluster.
. Quando richiesto, inserire i dati della chiave di backup.
+
Il nodo torna al menu di boot.

. Dal menu di avvio, selezionare opzione `(1) Normal Boot`.




== ONTAP 9.5 e versioni precedenti

. Verificare che la chiave debba essere ripristinata: +
`security key-manager key show`
. Se si utilizza ONTAP 9.8 e versioni successive e il volume root è crittografato, attenersi alla seguente procedura:
+
Se si utilizza ONTAP 9.6 o 9.7, o se si utilizza ONTAP 9.8 o versione successiva e il volume root non è crittografato, ignorare questo passaggio.

. Ripristinare la chiave: +
`security key-manager setup -node _node_`
+
Ulteriori informazioni su `security key-manager setup` nella link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-setup.html["Riferimento al comando ONTAP"^].

. Al prompt della passphrase, inserire la passphrase di gestione della chiave integrata per il cluster.

