---
permalink: encryption-at-rest/sanitize-fips-drive-sed-task.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, inaccessible, psid, physical secure ID, nrd plus, encrypt 
summary: 'Se si desidera rendere i dati su un"unità FIPS o SED permanentemente inaccessibili e utilizzare l"unità per i nuovi dati, è possibile utilizzare `storage encryption disk sanitize` comando per la pulizia del disco.' 
---
= Bonifica di un'unità FIPS o SED in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera rendere i dati su un'unità FIPS o SED permanentemente inaccessibili e utilizzare l'unità per i nuovi dati, è possibile utilizzare `storage encryption disk sanitize` comando per la pulizia del disco.

.A proposito di questa attività
Quando si disigienizza un'unità con crittografia automatica, il sistema modifica la chiave di crittografia del disco in un nuovo valore casuale, ripristina lo stato di blocco all'accensione su false e imposta l'ID della chiave su un valore predefinito, ovvero l'ID protetto del produttore 0x0 (unità SAS) o una chiave nulla (unità NVMe). In questo modo, i dati sul disco non sono accessibili e non possono essere recuperati. È possibile riutilizzare i dischi sanitizzati come dischi di riserva non azzerati.

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.Fasi
. Migrare tutti i dati che devono essere conservati in un aggregato su un altro disco.
. Eliminare l'aggregato sull'unità FIPS o SED da sanificare:
+
`storage aggregate delete -aggregate _aggregate_name_`

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
+
Ulteriori informazioni su `storage aggregate delete` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["Riferimento al comando ONTAP"^].

. Identificare l'ID del disco per l'unità FIPS o SED da sanificare:
+
`storage encryption disk show -fields data-key-id,fips-key-id,owner`

+
Ulteriori informazioni su `storage encryption disk show` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Riferimento al comando ONTAP"^].

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
1.10.2  data <id_value>
[...]
----
. Se un disco FIPS è in esecuzione in modalità di conformità FIPS, impostare nuovamente l'ID della chiave di autenticazione FIPS per il nodo sul valore MSID 0x0 predefinito:
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id 0x0`

+
È possibile utilizzare `security key-manager query` Per visualizzare gli ID chiave.

+
[listing]
----
cluster1::> storage encryption disk modify -disk 1.10.2 -fips-key-id 0x0

Info: Starting modify on 1 disk.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. Igienizzare il disco:
+
`storage encryption disk sanitize -disk _disk_id_`

+
È possibile utilizzare questo comando per sanificare solo i dischi hot spare o rotti. Per bonificare tutti i dischi, indipendentemente dal tipo, utilizzare `-force-all-state` l'opzione. Ulteriori informazioni su `storage encryption disk sanitize` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["Riferimento al comando ONTAP"^].

+

NOTE: ONTAP richiede di inserire una frase di conferma prima di continuare. Inserire la frase esattamente come mostrato sullo schermo.

+
[listing]
----
cluster1::> storage encryption disk sanitize -disk 1.10.2

Warning: This operation will cryptographically sanitize 1 spare or broken self-encrypting disk on 1 node.
         To continue, enter sanitize disk: sanitize disk

Info: Starting sanitize on 1 disk.
      View the status of the operation using the
      storage encryption disk show-status command.
----
. Annullare l'esecuzione di un errore sul disco crittografato:
`storage disk unfail -spare true -disk _disk_id_`
. Verificare se il disco dispone di un proprietario:
`storage disk show -disk _disk_id_`
 +
 Se il disco non dispone di un proprietario, assegnarne uno.
`storage disk assign -owner node -disk _disk_id_`
. Immettere il nodeshell per il nodo proprietario dei dischi che si desidera disinfettare:
+
`system node run -node _node_name_`

+
Eseguire `disk sanitize release` comando.

. Uscire dalla nodeshell. Annulla errore del disco:
`storage disk unfail -spare true -disk _disk_id_`
. Verificare che il disco sia ora uno spare e pronto per essere riutilizzato in un aggregato:
`storage disk show -disk _disk_id_`


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["assegnazione del disco di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["mostra disco di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-unfail.html["disco di archiviazione non guasto"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["modifica del disco di crittografia di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["crittografia di archiviazione, sanificazione del disco"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["archiviazione crittografia disco mostra-stato"^]

