---
permalink: encryption-at-rest/transition-external-key-from-onboard-key-task.html 
sidebar: sidebar 
keywords: transitioning, external key management, onboard key management 
summary: Se si desidera passare alla gestione esterna delle chiavi dalla gestione integrata delle chiavi, è necessario eliminare la configurazione di gestione integrata delle chiavi prima di attivare la gestione esterna delle chiavi. 
---
= Transizione alla gestione esterna delle chiavi dalla gestione integrata delle chiavi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera passare alla gestione esterna delle chiavi dalla gestione integrata delle chiavi, è necessario eliminare la configurazione di gestione integrata delle chiavi prima di attivare la gestione esterna delle chiavi.

.Di cosa hai bisogno
* Per la crittografia basata su hardware, è necessario ripristinare il valore predefinito delle chiavi dati di tutti i dischi FIPS o SED.
+
link:return-seds-unprotected-mode-task.html["Ripristino di un'unità FIPS o SED in modalità non protetta"]

* Per la crittografia basata su software, è necessario annullare la crittografia di tutti i volumi.
+
link:unencrypt-volume-data-task.html["Annullamento della crittografia dei dati del volume"]

* Per eseguire questa attività, è necessario essere un amministratore del cluster.


.Fase
. Eliminare la configurazione di gestione delle chiavi integrata per un cluster:
+
[cols="35,65"]
|===


| Per questa versione di ONTAP... | Utilizzare questo comando... 


 a| 
ONTAP 9.6 e versioni successive
 a| 
`security key-manager onboard disable -vserver SVM`



 a| 
ONTAP 9.5 e versioni precedenti
 a| 
`security key-manager delete-key-database`

|===


Per la sintassi completa dei comandi, vedere link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Pagine di manuale di ONTAP"].
