---
permalink: encryption-at-rest/unencrypt-volume-data-task.html 
sidebar: sidebar 
keywords: unencrypting, volume, data 
summary: È possibile utilizzare il comando di avvio spostamento volume per spostare e rimuovere la crittografia dei dati del volume. 
---
= Annullare la crittografia dei dati del volume in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `volume move start` comando per spostare e rimuovere la crittografia dei dati del volume.

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster. In alternativa, puoi essere un amministratore SVM a cui l'amministratore del cluster ha delegato l'autorità. Per ulteriori informazioni, vedere link:delegate-volume-encryption-svm-administrator-task.html["Delegare l'autorità per eseguire il comando di spostamento del volume"].

.Fasi
. Spostare un volume crittografato esistente e annullare la crittografia dei dati sul volume:
+
`volume move start -vserver _SVM_name_ -volume volume_name -destination-aggregate _aggregate_name_ -encrypt-destination false`

+
Ulteriori informazioni su `volume move start` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-move-start.html["Riferimento al comando ONTAP"^].

+
Il seguente comando sposta un volume esistente denominato `vol1` all'aggregato di destinazione `aggr3` e annulla la crittografia dei dati sul volume:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3 -encrypt-destination false
----
+
Il sistema elimina la chiave di crittografia per il volume. I dati del volume non sono crittografati.

. Verificare che il volume sia disattivato per la crittografia:
+
`volume show -encryption`

+
Ulteriori informazioni su `volume show` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Riferimento al comando ONTAP"^].

+
Il seguente comando indica se i volumi sono accesi `cluster1` sono crittografati:

+
[listing]
----
cluster1::> volume show -encryption

Vserver  Volume   Aggregate   State    Encryption State
-------  ------   ---------   -----    ----------------
vs1      vol1     aggr1       online   none
----

