---
permalink: s3-multiprotocol/create-nas-bucket-task.html 
sidebar: sidebar 
keywords: s3, svm, bucket, object, server, versioning, protocol, filesystems, nas, directories 
summary: Un bucket S3 NAS è una mappatura tra un nome di bucket S3 e un percorso NAS. 
---
= Creare un bucket S3 NAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un bucket S3 NAS è una mappatura tra un nome di bucket S3 e un percorso NAS. I bucket NAS S3 consentono di fornire l'accesso S3 a qualsiasi parte di uno spazio dei nomi SVM con volumi e struttura di directory esistenti.

.Prima di iniziare
* Un server a oggetti S3 è configurato in una SVM contenente dati NAS.
* I dati NAS sono conformi a. link:nas-data-requirements-client-access-reference.html["Requisiti per l'accesso al client S3"].


.A proposito di questa attività
È possibile configurare i bucket S3 NAS per specificare qualsiasi set di file e directory all'interno della directory root di SVM.

È inoltre possibile impostare policy bucket che consentono o non consentono l'accesso ai dati NAS in base a qualsiasi combinazione di questi parametri:

* File e directory
* Autorizzazioni utente e gruppo
* Operazioni S3


Ad esempio, potrebbero essere necessarie policy di bucket separate che concedano l'accesso ai dati di sola lettura a un gruppo di utenti di grandi dimensioni e un'altra che consenta a un gruppo limitato di eseguire operazioni su un sottoinsieme di tali dati.

Poiché i "bucket" S3 NAS sono mappature e non bucket S3, le seguenti proprietà dei bucket S3 standard non si applicano ai bucket S3 NAS.

* *Aggr-list/aggr-list-moltiplicer/storage-service-level/volume/size/exclude-aggr-list/qos-policy-group* + Nessun volume o qtree viene creato durante la configurazione dei bucket S3 NAS.
* *Ruolo \ è -protetto \ è -protetto-su-ONTAP \ è -protetto-su-cloud* + i bucket NAS S3 non sono protetti o con mirroring utilizzando SnapMirror S3, ma useranno invece la normale protezione SnapMirror disponibile con granularità del volume.
* *Versioning-state* + i volumi NAS di solito dispongono di tecnologia snapshot per salvare versioni diverse. Tuttavia, la versione non è attualmente disponibile nei bucket S3 NAS.
* I comandi del volume consentono di accedere alle statistiche utilizzate in modo logico/object-count* + equivalenti per i volumi NAS.
* *Oggetti multiparte* + a partire da ONTAP 9.16.1, gli oggetti multiparte sono supportati nei bucket NAS S3 quando link:../flexgroup/enable-adv-capacity-flexgroup-task.html["bilanciamento avanzato della capacità"] è abilitato sul volume FlexGroup sottostante. Il bilanciamento avanzato della capacità può essere abilitato solo sui volumi FlexGroup. Non può essere abilitato sui FlexVol.


[role="tabbed-block"]
====
.System Manager
--
Aggiungere un nuovo bucket S3 NAS su una VM di storage abilitata per NAS.

. Fare clic su *Storage > Bucket*, quindi su *Add* (Aggiungi).
. Inserire un nome per il bucket S3 NAS e selezionare la VM di storage, non inserire una dimensione, quindi fare clic su *altre opzioni*.
. Immettere un nome di percorso valido o fare clic su Browse (Sfoglia) per effettuare una selezione da un elenco di nomi di percorso validi. + quando si immette un nome di percorso valido, le opzioni non rilevanti per la configurazione S3 NAS vengono nascoste.
. Se gli utenti S3 sono già stati mappati agli utenti NAS e sono stati creati dei gruppi, è possibile configurarne le autorizzazioni, quindi fare clic su *Save* (Salva). + prima di configurare le autorizzazioni in questa fase, è necessario aver già mappato gli utenti S3 agli utenti NAS.


Altrimenti, fare clic su *Save* (Salva) per completare la configurazione del bucket S3 NAS.

--
.CLI
--
Creare un bucket S3 NAS in una SVM contenente i filesystem NAS. +
`vserver object-store-server bucket create -vserver _svm_name_ -bucket _bucket_name_ -type nas -nas-path _junction_path_ [-comment _text_]`

Esempio: +
`cluster1::> vserver object-store-server bucket create -bucket testbucket -type nas -path /vol1`

--
====