---
permalink: s3-multiprotocol/nas-data-requirements-client-access-reference.html 
sidebar: sidebar 
keywords: s3, mapping, directory, access, configuration, object, nas, bucket 
summary: 'È importante comprendere che la mappatura di file e directory NAS per l"accesso S3 altera alcuni comportamenti NAS standard.' 
---
= Scopri i requisiti dei dati NAS per l'accesso client ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È importante comprendere che ci sono alcune incompatibilità intrinseche quando si mappano file e directory NAS per l'accesso S3. Potrebbe essere necessario regolare le gerarchie dei file NAS prima di servirle utilizzando i bucket S3 NAS.

Un bucket S3 NAS fornisce l'accesso S3 a una directory NAS mappando tale directory utilizzando la sintassi del bucket S3 e i file nell'albero delle directory vengono visualizzati come oggetti. I nomi degli oggetti sono i percorsi delimitati dalla barra dei file relativi alla directory specificata nella configurazione del bucket S3.

Questa mappatura impone alcuni requisiti quando i file e le directory vengono serviti utilizzando i bucket NAS S3:

* I nomi S3 sono limitati a 1024 byte, pertanto i file con percorsi più lunghi non sono accessibili utilizzando S3.
* I nomi di file e directory sono limitati a 255 caratteri, pertanto il nome di un oggetto non può contenere più di 255 caratteri consecutivi non slash (‘/’)
* Un nome percorso SMB delimitato da caratteri backslash (‘’) viene visualizzato in s3 come nome di oggetto contenente caratteri‘/’ (barra rovesciata).
* Alcune coppie di nomi di oggetti S3 legali non possono coesistere nell'albero di directory NAS mappato. Ad esempio, i nomi degli oggetti S3 legali "part1/part2" e "part1/part2/part3" corrispondono a file che non possono esistere contemporaneamente nell'albero delle directory NAS, in quanto "part1/part2" è un file nel nome e una directory nell'altro.
+
** Se "part1/part2" è un file esistente, la creazione S3 di "part1/part2/part3" non riesce.
** Se "part1/part2/part3" è un file esistente, la creazione o l'eliminazione S3 di "part1/part2" non avrà esito positivo.
** La creazione di un oggetto S3 che corrisponde al nome di un oggetto esistente sostituisce l'oggetto pre-esistente (nei bucket senza versione), che contiene in NAS ma richiede una corrispondenza esatta. Gli esempi precedenti non causeranno la rimozione dell'oggetto esistente perché, mentre i nomi si scontrano, non corrispondono.




Sebbene un archivio di oggetti sia progettato per supportare un numero molto elevato di nomi arbitrari, una struttura di directory NAS può riscontrare problemi di performance se un numero molto elevato di nomi viene inserito in una directory. In particolare, i nomi che non contengono caratteri slash (‘/’) verranno tutti inseriti nella directory principale della mappatura NAS. Le applicazioni che utilizzano in modo esteso nomi non compatibili con NAS potrebbero essere ospitate meglio su un bucket di archivio di oggetti effettivo piuttosto che su una mappatura NAS.
