---
permalink: ndmp/index.html 
sidebar: sidebar 
keywords: decide, ndmp, configuration, network, data, management, protocol, backup, back up 
summary: 'È possibile configurare rapidamente un cluster ONTAP 9 in modo che utilizzi il protocollo di gestione dei dati di rete (NDMP) per eseguire il backup dei dati direttamente su nastro utilizzando un"applicazione di backup di terze parti.' 
---
= Panoramica della configurazione NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare rapidamente un cluster ONTAP 9 in modo che utilizzi il protocollo di gestione dei dati di rete (NDMP) per eseguire il backup dei dati direttamente su nastro utilizzando un'applicazione di backup di terze parti.

Se l'applicazione di backup supporta Cluster Aware Backup (CAB), è possibile configurare NDMP come _SVM-scoped_ o _node-scoped_:

* SVM-scope a livello di cluster (admin SVM) consente di eseguire il backup di tutti i volumi ospitati su diversi nodi del cluster. Se possibile, si consiglia di utilizzare NDMP con ambito SVM.
* NDMP con ambito nodo consente di eseguire il backup di tutti i volumi ospitati su quel nodo.


Se l'applicazione di backup non supporta CAB, è necessario utilizzare NDMP con ambito nodo.

Gli NDMP con ambito SVM e nodo si escludono a vicenda e non possono essere configurati sullo stesso cluster.


NOTE: NDMP con ambito del nodo è obsoleto in ONTAP 9.

Scopri di più link:https://docs.netapp.com/us-en/ontap/tape-backup/cluster-aware-backup-extension-concept.html["Backup cluster-aware (CAB)"].

Prima di configurare NDMP, verificare quanto segue:

* Si dispone di un'applicazione di backup di terze parti (chiamata anche Data Management Application o DMA).
* Sei un amministratore del cluster.
* Sono installati i dispositivi a nastro e un server multimediale opzionale.
* I dispositivi a nastro sono collegati al cluster tramite uno switch Fibre Channel (FC) e non direttamente.
* Almeno un dispositivo a nastro ha un numero di unità logica (LUN) pari a 0.

