---
permalink: consistency-groups/clone-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, clone 
summary: A partire da ONTAP 9.12.1, puoi clonare un gruppo di coerenza per creare una copia della configurazione e dei volumi del gruppo di coerenza. 
---
= Clonare un gruppo di coerenza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.12.1, è possibile clonare un gruppo di coerenza per creare una copia di un gruppo di coerenza e del relativo contenuto. La clonazione di un gruppo di coerenza crea una copia della configurazione del gruppo di coerenza, dei relativi metadati come il tipo di applicazione e di tutti i volumi e i relativi contenuti come file, directory, LUN o spazi dei nomi NVMe.

.A proposito di questa attività
Durante la clonazione di un gruppo di coerenza, è possibile clonarlo con la configurazione corrente, ma con il contenuto del volume così come sono o in base a un gruppo di coerenza esistente Snapshot.

La clonazione di un gruppo di coerenza è supportata solo per l'intero gruppo di coerenza. Non è possibile clonare un singolo gruppo di coerenza figlio in una relazione gerarchica: È possibile clonare solo la configurazione completa del gruppo di coerenza.

Quando si clonano gruppi di coerenza, i seguenti componenti non vengono clonati:

* IGroups
* Mappe LUN
* Sottosistemi NVMe
* Mappe dei sottosistemi dello spazio dei nomi NVMe


.Prima di iniziare
* Quando si clonano gruppi di coerenza, ONTAP non crea condivisioni SMB per i volumi clonati se non viene specificato un nome di condivisione. * I gruppi di coerenza clonati non vengono montati se non viene specificato un percorso di giunzione.
* Se si tenta di clonare un gruppo di coerenza basato su un'istantanea che non riflette i volumi costituenti correnti del gruppo di coerenza, l'operazione non verrà eseguita correttamente.
* Dopo aver clonato un gruppo di coerenza, è necessario eseguire l'operazione di mappatura appropriata.
+
Fare riferimento a. xref:../task_san_map_igroups_to_multiple_luns.html[Mappare igroups a più LUN] oppure xref:../san-admin/map-nvme-namespace-subsystem-task.html[Mappare uno spazio dei nomi NVMe in un sottosistema] per ulteriori informazioni.

* La clonazione di un gruppo di coerenza non è supportata per un gruppo di coerenza in una relazione di Business Continuity SnapMirror o con qualsiasi volume DP associato.


[role="tabbed-block"]
====
.System Manager
--
.Fasi
. Selezionare *Storage > Consistency groups*.
. Selezionare il gruppo di coerenza che si desidera clonare dal menu *Consistency Group*.
. Nella parte superiore destra della pagina panoramica del gruppo di coerenza, selezionare *Clone*.
. Immettere un nome per il nuovo gruppo di coerenza clonato o accettare il nome predefinito.
+
.. Scegliere se si desidera attivare link:../concepts/thin-provisioning-concept.html["*Thin Provisioning*"^].
.. Scegliere *Split Clone* se si desidera separare il gruppo di coerenza dall'origine e allocare ulteriore spazio su disco per il gruppo di coerenza clonato.


. Per clonare il gruppo di coerenza nello stato corrente, scegliere *Aggiungi una nuova copia Snapshot*.
+
Per clonare il gruppo di coerenza in base a uno snapshot, scegliere *Usa una copia Snapshot esistente*. Selezionando questa opzione si apre un nuovo sottomenu. Scegliere l'istantanea che si desidera utilizzare come base per l'operazione di clonazione.

. Selezionare *Clone*.
. Tornare al menu *Consistency Group* per confermare che il gruppo di coerenza è stato clonato.


--
.CLI
--
A partire da ONTAP 9.14.1, è possibile clonare un gruppo di coerenza utilizzando la CLI.

.Clonare un gruppo di coerenza
. Il `consistency-group clone create` command clona il gruppo di coerenza al suo stato corrente point-in-time. Per basare l'operazione di cloning su uno Snapshot, includere il `-source-snapshot` parametro.
+
`consistency-group clone create -vserver _svm_name_ -consistency-group _clone_name_ -source-consistency-group _consistency_group_name_ [-source-snapshot _snapshot_name_]`



--
====
.Passi successivi
* xref:../task_san_map_igroups_to_multiple_luns.html[Mappare igroups a più LUN]
* xref:../san-admin/map-nvme-namespace-subsystem-task.html[Mappare uno spazio dei nomi NVMe in un sottosistema]

