---
permalink: consistency-groups/configure-hierarchy-task.html 
sidebar: sidebar 
keywords: consistency groups, application protection, parent, child, hierarchy 
summary: Creare un gruppo di coerenza gerarchico per la gestione dei carichi di lavoro delle applicazioni di grandi dimensioni e la protezione dei dati. 
---
= Configurare un gruppo di coerenza gerarchico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I gruppi di coerenza gerarchica consentono di gestire grandi carichi di lavoro su più volumi, creando un gruppo di coerenza padre che funge da ombrello per i gruppi di coerenza figlio.

I gruppi di coerenza gerarchica hanno un padre che può includere fino a cinque singoli gruppi di coerenza. I gruppi di coerenza gerarchici possono supportare diverse policy di snapshot locali tra gruppi di coerenza o singoli volumi. Se si utilizza un criterio di protezione remota, questo verrà applicato all'intero gruppo di coerenza gerarchico (principale e figlio).

A partire da ONTAP 9.13.1, è possibile xref:modify-geometry-task.html[modificare la geometria dei gruppi di coerenza] e. xref:modify-task.html[spostare i volumi tra i gruppi di coerenza figlio].

Per i limiti degli oggetti sui gruppi di coerenza, vedere xref:limits.html[Limiti degli oggetti per i gruppi di coerenza].



== Creare un gruppo di coerenza gerarchica con nuove LUN o volumi

Quando si crea un gruppo di coerenza gerarchica, è possibile compilarlo con nuove LUN. A partire da ONTAP 9.13.1, puoi anche utilizzare nuovi namespace NVMe e volumi NAS.

[role="tabbed-block"]
====
.System Manager
--
.Fasi
. Selezionare *Storage > Consistency groups*.
. Selezionare *+Aggiungi*, quindi selezionare il protocollo per l'oggetto di storage.
+
In ONTAP dalla versione 9.10.1 alla 9.12.1, l'unica opzione per un nuovo oggetto di storage è **l'utilizzo di nuove LUN**. A partire da ONTAP 9.13.1, System Manager supporta la creazione di gruppi di coerenza con nuovi namespace NVMe e nuovi volumi NAS.

. Assegnare un nome al gruppo di coerenza. Indicare il numero di volumi o LUN e la capacità per volume o LUN.
+
.. **Tipo di applicazione**: Se si utilizza ONTAP 9.12.1 o versione successiva, selezionare un tipo di applicazione. Se non viene selezionato alcun valore, al gruppo di coerenza viene assegnato il tipo **Altro** per impostazione predefinita. Scopri di più sulla coerenza dei tag in xref:modify-tags-task.html[Tag di applicazioni e componenti]. Se si prevede di utilizzare una policy di protezione remota, è necessario scegliere *Altro*.


. Selezionare il sistema operativo host e il formato LUN. Inserire le informazioni dell'iniziatore host.
+
.. Per **nuovi LUN**: Selezionare il sistema operativo host e il formato LUN. Inserire le informazioni dell'iniziatore host.
.. Per **nuovi volumi NAS**: Scegliere l'opzione di esportazione appropriata (NFS o SMB/CIFS) in base alla configurazione NAS della SVM.
.. Per **nuovi spazi dei nomi NVMe**: Selezionare il sistema operativo host e il sottosistema NVMe.


. Per aggiungere un gruppo di coerenza figlio, selezionare *altre opzioni*, quindi *+Aggiungi gruppo di coerenza figlio*.
. Selezionare il livello di performance, il numero di LUN o volumi e la capacità per LUN o volume. Indicare le configurazioni di esportazione appropriate o le informazioni del sistema operativo in base al protocollo in uso.
. Facoltativamente, selezionare un criterio di snapshot locale e impostare le autorizzazioni di accesso.
. Ripetere la procedura per un massimo di cinque gruppi di coerenza figlio.
. Selezionare *Salva*.
. Verificare che il gruppo di coerenza sia stato creato tornando al menu principale del gruppo di coerenza in cui verrà visualizzato una volta completato il lavoro ONTAP. Se si imposta un criterio di protezione, controllare il criterio appropriato, remoto o locale, che dovrebbe visualizzare uno schermo verde con un segno di spunta.


--
.CLI
--
.Prima di iniziare
* Per eseguire questa attività, è necessario essere al livello di privilegi di amministratore.
* In ONTAP 9.14.1, per eseguire questa attività devi essere un amministratore del cluster o della SVM. A partire da ONTAP 9.15.1, qualsiasi utente al livello di privilegi admin può eseguire questa attività.


Quando si crea un gruppo di coerenza gerarchica nella CLI con nuovi volumi, è necessario creare ciascun gruppo di coerenza figlio singolarmente.

.Fase
. Creare il nuovo gruppo di coerenza utilizzando `consistency-group create` comando.
+
`consistency-group create -vserver <SVM_name> -consistency-group <consistency_group_name> -parent-consistency-group <parent_consistency_group_name> -volume-prefix <volume_prefix> -volume-count <number_of_volumes> -size <size>`

. Quando richiesto dalla CLI, confermare che si desidera creare il nuovo gruppo di coerenza principale. Immettere `y`.
. Se lo si desidera, ripetere il passaggio 1 per creare altri gruppi di coerenza figlio.


--
====


== Creare un gruppo di coerenza gerarchica con i volumi esistenti

È possibile organizzare i volumi esistenti in un gruppo di coerenza gerarchico.

[role="tabbed-block"]
====
.System Manager
--
.Fasi
. Selezionare *Storage > Consistency groups*.
. Selezionare *+Aggiungi*, quindi *utilizzando volumi esistenti*.
. Selezionare la VM di storage.
. Selezionare i volumi esistenti da includere. Saranno disponibili per la selezione solo i volumi che non fanno già parte di un gruppo di coerenza.
. Per aggiungere un gruppo di coerenza figlio, selezionare *+Aggiungi gruppo di coerenza figlio*. Creare i gruppi di coerenza necessari, che verranno nominati automaticamente.
+
.. **Tipo di componente**: Se si utilizza ONTAP 9.12.1 o versione successiva, selezionare un tipo di componente "dati", "registri" o "Altro". Se non viene selezionato alcun valore, al gruppo di coerenza viene assegnato il tipo **Altro** per impostazione predefinita. Scopri di più sulla coerenza dei tag in xref:modify-tags-task.html[Tag di applicazioni e componenti]. Se si intende utilizzare una policy di protezione remota, è necessario utilizzare *Altro*.


. Assegnare i volumi esistenti a ciascun gruppo di coerenza.
. In alternativa, selezionare un criterio snapshot locale.
. Ripetere la procedura per un massimo di cinque gruppi di coerenza figlio.
. Selezionare *Salva*.
. Verificare che il gruppo di coerenza sia stato creato tornando al menu principale del gruppo di coerenza in cui verrà visualizzato una volta completato il lavoro ONTAP. Se è stata scelta una policy di protezione, confermarla selezionando il gruppo di coerenza dal menu; sotto il tipo di policy appropriato, viene visualizzato uno shield verde con un segno di spunta all'interno di essa.


--
.CLI
--
A partire da ONTAP 9.14.1, è possibile creare un gruppo di coerenza gerarchica utilizzando la CLI.

.Prima di iniziare
* Per eseguire questa attività, è necessario essere al livello di privilegi di amministratore.
* In ONTAP 9.14.1, per eseguire questa attività devi essere un amministratore del cluster o della SVM. A partire da ONTAP 9.15.1, qualsiasi utente al livello di privilegi admin può eseguire questa attività.


.Fasi
. Provisioning di un nuovo gruppo di coerenza di origine e assegnazione dei volumi a un nuovo gruppo di coerenza child:
+
`consistency-group create -vserver <svm_name> -consistency-group <child_consistency_group_name> -parent-consistency-group <parent_consistency_group_name> -volumes <volume_names>`

. Invio `y` per confermare la creazione di un nuovo gruppo di coerenza principale e secondario.


--
====
.Passi successivi
* xref:xref:modify-geometry-task.html[Modificare la geometria di un gruppo di coerenza]
* xref:modify-task.html[Modificare un gruppo di coerenza]
* xref:protect-task.html[Proteggere un gruppo di coerenza]

