---
sidebar: sidebar 
permalink: concept-svm-admin-dashboard-sm.html 
keywords: netapp, system manager, ontap, administration, overview, svm, storage vm, volume, vserver, dashboard, administrator, tenant, multi-tenancy, protocol, network interface, performance, learn 
summary: 'Gli amministratori SVM possono monitorare e gestire i propri SVM utilizzando una dashboard dedicata di System Manager. Ciò risulta particolarmente utile in un ambiente ONTAP multi-tenant, dove l"amministratore del cluster può fornire una dashboard SVM per ciascun tenant.' 
---
= Scopri la dashboard dell'amministratore SVM di ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP 9.19.1, gli amministratori SVM possono monitorare e gestire i propri SVM utilizzando una dashboard dedicata di System Manager e la pagina Storage > Volumi. Ciò è particolarmente utile in un ambiente ONTAP multi-tenant, dove l'amministratore del cluster può fornire una dashboard SVM per ciascun tenant.

L'amministratore del cluster fornisce le credenziali di accesso agli amministratori SVM. Gli amministratori SVM possono visualizzare dettagli e prestazioni nella dashboard SVM e nella pagina *Storage > Volumi*. La dashboard mostra i protocolli SVM, le interfacce di rete, i dettagli e le metriche sulle prestazioni. La pagina Volumi fornisce informazioni sui volumi SVM e, se consentito dall'amministratore del cluster, la possibilità per l'amministratore SVM di aggiungere nuovi volumi.

.Cosa succede dopo
link:task-assign-svm-admin-access-sm.html["Assegnare l'accesso di amministratore SVM con ONTAP System Manager"]
