---
sidebar: sidebar 
permalink: concept_nas_provision_overview.html 
keywords: netapp, ontap, provisioning, nas, overview, provision NAS storage, manage NAS services, NAS file service, Linux client, Windows client, NAS multiprotocol, name service, name service switch, NFS, SMB, DNS, LDAP, NIS, Kerberos security, export, share, qtree, name mapping, NAS data service 
summary: ONTAP consente di fornire i dati ai client Linux e Windows in modo semplice, sicuro ed efficiente. 
---
= Panoramica sulla gestione NAS con System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gli argomenti di questa sezione mostrano come configurare e gestire gli ambienti NAS con Gestione di sistema in ONTAP 9.7 e versioni successive.

Se si utilizza Gestione di sistema classico (disponibile solo in ONTAP 9.7 e versioni precedenti), consultare i seguenti argomenti:

* https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config/index.html["Panoramica della configurazione di NFS"^]
* https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/index.html["Panoramica della configurazione SMB"^]


System Manager supporta i flussi di lavoro per:

* Configurazione iniziale dei cluster che si intende utilizzare per i file service NAS.
* Provisioning di volumi aggiuntivo per esigenze di storage in continua evoluzione.
* Configurazione e manutenzione per strutture di sicurezza e autenticazione standard di settore.


Con System Manager, è possibile gestire i servizi NAS a livello di componente:

* Protocolli: NFS, SMB o entrambi (multiprotocollo NAS)
* Name service - DNS, LDAP e NIS
* Switch name service
* Kerberos e TLS
* Esportazioni e condivisioni
* Qtree
* Mappatura dei nomi di utenti e gruppi

