---
sidebar: sidebar 
permalink: concept_key_ontap.html 
keywords: netapp, ontap, cluster, node, local tier, cloud tier, aggregate, SVM, storage VM, service level, volume, qtree, LUN, automatic aggregate selection, tier selection, vserver, ONTAP concepts, terms, Snapshot copy, data protection, mirroring, HA pair, storage efficiency, compression, deduplication, compaction, multifactor authentication, client, LUN, NVMe, quiesce, quiescing, pause, namespace, flash storage 
summary: Una rapida introduzione a ONTAP e alcune modifiche alla terminologia per i clienti attuali 
---
= Concetti chiave
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp ONTAP è il software per la gestione dei dati comprovato di NetApp. Puoi eseguire ONTAP nel tuo data center su hardware progettato da NetApp, sul tuo hardware commodity o in uno dei principali cloud pubblici.



== Informazioni su System Manager

System Manager (in precedenza Gestore di sistema di OnCommand) è un prodotto semplice e versatile che consente di configurare e gestire facilmente i cluster ONTAP. System Manager semplifica le attività di storage comuni, come la creazione di volumi, LUN, qtree, condivisioni ed esportazioni, che consente di risparmiare tempo e prevenire gli errori.

A partire da ONTAP 9.7, un Gestore di sistema completamente riprogettato semplifica la gestione di ONTAP con un'interfaccia utente grafica intuitiva che offre:

* Configurazione semplice e veloce
+
Flussi di lavoro semplificati per la configurazione e la gestione ONTAP delle attività comuni.

* Impostazioni predefinite smart
+
Consente di creare configurazioni Best practice basate su implementazioni comprovate.

* Ampie funzionalità amministrative
+
Configura ed esegui facilmente il provisioning dello storage per la condivisione di file, i carichi di lavoro delle applicazioni e dei database.

* Gestione integrata System Manager viene fornito in bundle con la piattaforma ONTAP 9, eliminando la necessità di un'installazione separata. Una nuova dashboard che mostra lo stato e le performance principali del cluster su un'unica schermata.


System Manager ti offre una chiara visione dello stato del tuo cluster e ti guida sui modi migliori per raggiungere i tuoi obiettivi di storage.

Se hai familiarità con una versione precedente di ONTAP, ti sentirai come a casa. In System Manager sono state apportate alcune modifiche alla terminologia di cui si dovrebbe essere a conoscenza.

* *Tier locale* – un set di dischi fisici a stato solido o dischi rigidi su cui memorizzare i dati. Potresti conoscere questi come aggregati. Infatti, se si utilizza l'interfaccia CLI di ONTAP, si vedrà comunque il termine _aggregate_ utilizzato per rappresentare un Tier locale.
* *Tier cloud* – storage nel cloud utilizzato da ONTAP quando si desidera avere alcuni dati off-premise per uno dei diversi motivi. Se stai pensando alla parte cloud di un FabricPool, l'hai già capito. E se utilizzi un sistema StorageGRID, il tuo cloud potrebbe non essere off-premise. (Un'esperienza on-premise simile al cloud si chiama _cloud privato_).
* *Storage VM* – una macchina virtuale in esecuzione in ONTAP che fornisce servizi di storage e dati ai client. Potresti sapere che si tratta di un _SVM_ o di un _vserver_.
* *Interfaccia di rete* - Indirizzo e proprietà assegnati a una porta di rete fisica. Questo potrebbe essere un'interfaccia logica (LIF)_.
* *Pause* - azione che interrompe le operazioni. Prima di ONTAP 9.8, in altre versioni di Gestore di sistema potrebbe essere stato fatto riferimento a _quiesce_.


Se sei un nuovo utente di ONTAP, ecco alcuni altri concetti che ti consentiranno di accelerare il processo.

* *Cluster* – questo è il quadro generale. Un cluster è costituito da uno o più nodi. Si pensi ai nodi come ai computer specializzati nella gestione dei dati e nello storage. È possibile aggiungere nodi al cluster man mano che le esigenze crescono o sostituire nodi più piccoli con nodi più grandi. Il tutto senza interrompere l'accesso ai tuoi dati, naturalmente.
* *Copie Snapshot*: Copie istantanee dei dati che è possibile utilizzare per annullare un errore, spostare o eseguire il backup sul cloud, eseguire il mirroring su un altro cluster o persino copiare su nastro. Senza interruzioni per i tuoi clienti. E chi può permettersi il downtime?
* *Protezione dei dati* - le funzionalità di protezione utilizzate dipendono da ciò che occorre proteggere e da quanto tempo è possibile attendere per il ripristino in caso di problemi. ONTAP offre mirroring sincrono e asincrono e molto altro ancora.
* *Coppia ha* – parlando di evitare il downtime, la coppia ad alta disponibilità è l'unità di base di un cluster ONTAP. È costituito da due nodi partner che possono assumere il controllo reciproco. Supponiamo di voler eseguire l'aggiornamento all'ultima versione di ONTAP per ottenere una nuova eccezionale funzionalità di gestione dei dati. È sufficiente che il partner prenda il controllo del carico del client di un nodo, aggiorni tale client e restituisci il carico. Ripetere l'operazione per il nodo partner e l'aggiornamento è stato eseguito senza alcuna interruzione.
* *Efficienza dello storage*: I dischi costano denaro (denaro reale!), ma l'efficienza dello storage consente di memorizzare più dati in meno spazio. E questo consente di risparmiare denaro reale e di diventare un eroe dei dati. È possibile utilizzare una o tutte le funzioni di compressione, deduplica e compattazione di ONTAP. Siamo sicuri che conosci già la compressione. La deduplica identifica più copie degli stessi dati e sostituisce i duplicati con puntatori a una singola copia. La compattazione inserisce più file di piccole dimensioni in un singolo blocco di storage, riempiendo ciò che altrimenti verrebbe sprecato spazio.
* *Sicurezza* – la sicurezza è parte integrante del software di gestione dei dati ONTAP. ONTAP ti aiuta in molti modi, ad esempio utilizzando l'autenticazione a più fattori per gli amministratori, crittografando i dati su disco e in volo e utilizzando strumenti antivirus per proteggere i file Windows.
* *Volumi* – sono esattamente ciò che pensi siano i volumi. Sono container per memorizzare i file. È possibile esportare volumi in client Linux, condividere volumi con client Windows o eseguire entrambe le operazioni contemporaneamente con gli stessi file.
* *LUN* – l'unità di base DELLA SAN. Si tratta di Fibre Channel e iSCSI. In un ambiente SAN, ONTAP fornisce dischi virtuali ai client anziché ai file. Gli amministratori di database spesso desiderano dischi virtuali che possono gestire a un livello basso o applicare un file system specializzato. Molti sistemi ONTAP, ma non tutti, possono fornire dati ai client SAN.
* *NVMe namespace* – il futuro dello storage flash. Il protocollo NVMe è ottimizzato per lo storage basato su SSD ed è molto veloce. NVMe è un aspetto della SAN, ma l'unità di storage di base è denominata _namespace_ invece di un LUN.


Per ulteriori informazioni su ONTAP, fare riferimento alla ONTAP link:./concepts/index.html["panoramica dei concetti"].



== Video dei casi d'utilizzo di System Manager

video::PrpfVnN3dyk[youtube,width=848,height=480]