---
sidebar: sidebar 
permalink: metrocluster-setup-l3-task.html 
keywords: metrocluster, layer 3, edit, gateway, netmask, net mask, configuration, configure 
summary: 'A partire da ONTAP 9.10.1, è possibile modificare l"indirizzo IP, la maschera e il gateway di un"interfaccia IP MetroCluster.' 
---
= Modificare l'indirizzo, la netmask e il gateway in un IP MetroCluster
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
A partire da ONTAP 9.10.1, è possibile modificare le seguenti proprietà di un'interfaccia IP MetroCluster: Indirizzo IP, maschera e gateway. È possibile utilizzare qualsiasi combinazione di parametri per l'aggiornamento.

Potrebbe essere necessario aggiornare queste proprietà, ad esempio, se viene rilevato un indirizzo IP duplicato o se un gateway deve essere modificato in caso di rete di livello 3 a causa di modifiche alla configurazione del router. È possibile modificare solo un'interfaccia alla volta. L'interfaccia verrà rallentata fino a quando le altre interfacce non saranno aggiornate e le connessioni non verranno ristabilita.


NOTE: È necessario apportare le modifiche a ciascuna porta. Analogamente, anche gli switch di rete devono aggiornare la configurazione. Ad esempio, se il gateway viene aggiornato, idealmente viene modificato su entrambi i nodi di una coppia ha, poiché sono identici. Inoltre, anche lo switch connesso a tali nodi deve aggiornare il gateway.

.Fase
Aggiornare l'indirizzo IP, la netmask e il gateway per ogni nodo e interfaccia.
