---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-automation,
    ontap-cli-9141
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti ONTAP
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - title: Integrazione di System Manager con BlueXP
    url: "/sysmgr-integration-bluexp-concept.html"
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: authentication-access-control
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: Pagine di manuale di ONTAP
    url: "/concepts/manual-pages.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: Tutta la documentazione del prodotto ONTAP
