---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  search: ontap, ontap-metrocluster, ontap-fli, ontap-automation, ontap-cli
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti ONTAP
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: authentication-access-control
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: Pagine di manuale di ONTAP
    url: "/concepts/manual-pages.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
