---
sidebar: sidebar 
permalink: sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: A partire da ONTAP 9.12.1, System Manager è completamente integrato con BlueXP. Con BlueXP, puoi gestire la tua infrastruttura multicloud ibrida da un singolo piano di controllo mantenendo la familiare dashboard di System Manager. 
---
= Integrazione di System Manager con BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP 9.12.1, System Manager è completamente integrato con BlueXP. Con BlueXP, puoi gestire la tua infrastruttura multicloud ibrida da un singolo piano di controllo mantenendo la familiare dashboard di System Manager.

BlueXP consente di creare e amministrare lo storage cloud (ad esempio, Cloud Volumes ONTAP), utilizzare i servizi dati di NetApp (ad esempio, backup cloud) e controllare molti dispositivi storage on-premise e edge.

Per utilizzare System Manager in BlueXP, attenersi alla seguente procedura:

.Fasi
. Aprire un browser Web e inserire l'indirizzo IP dell'interfaccia di rete per la gestione del cluster.
+
Se il cluster dispone della connettività a BlueXP, viene visualizzato un prompt di accesso.

. Fare clic su *Continue to BlueXP* (continua con BlueXP*) per seguire il link a BlueXP.
+

NOTE: Se le impostazioni del sistema hanno bloccato le reti esterne, non sarà possibile accedere a BlueXP.  Per accedere a System Manager utilizzando BlueXP, devi assicurarti che il sistema possa accedere all'indirizzo "`cloudmanager.cloud.netapp.com`"".  In caso contrario, quando richiesto, è possibile scegliere di utilizzare la versione di Gestione sistema installata con il sistema ONTAP.

. Nella pagina di accesso a BlueXP, selezionare *Accedi con le credenziali del sito di supporto NetApp* e immettere le credenziali.
+
Se hai già utilizzato BlueXP e disponi di un account di accesso utilizzando un'e-mail e una password, dovrai continuare a utilizzare l'opzione di accesso.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["Scopri di più sull'accesso a BlueXP"^].

. Se richiesto, immettere un nome per il nuovo account BlueXP.
+
Nella maggior parte dei casi, BlueXP crea automaticamente un account in base ai dati del cluster.

. Immettere le credenziali di amministratore del cluster per il cluster.


.Risultato
System Manager viene visualizzato ed è ora possibile gestire il cluster da BlueXP.



== Scopri i tuoi cluster direttamente da BlueXP

BlueXP offre due modi per rilevare e gestire i cluster:

* Rilevamento diretto per la gestione tramite System Manager
+
Si tratta della stessa opzione di rilevamento descritta nella sezione precedente con cui si segue il reindirizzamento.

* Rilevamento attraverso un connettore
+
Il connettore è un software installato nel tuo ambiente che ti consente di accedere alle funzioni di gestione tramite System Manager e ai servizi cloud BlueXP che offrono funzionalità come replica dei dati, backup e recovery, classificazione dei dati, tiering dei dati e molto altro ancora.



Accedere alla https://docs.netapp.com/us-en/cloud-manager-family/index.html["Documentazione BlueXP"^] per ulteriori informazioni su queste opzioni di rilevamento e gestione.



== Scopri di più su BlueXP

* https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["Panoramica di BlueXP"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["Gestisci i tuoi sistemi NetApp AFF e FAS tramite BlueXP"^]

