---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, data infrastructure insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: Con Data Infrastructure Insights puoi monitorare, risolvere i problemi e ottimizzare tutte le tue risorse, inclusi i tuoi cloud pubblici e i tuoi data center privati. 
---
= Monitora le prestazioni del cluster con ONTAP Data Infrastructure Insights
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Infrastructure Insights è uno strumento di monitoraggio che offre visibilità sull'intera infrastruttura. Con Data Infrastructure Insights, puoi monitorare, risolvere i problemi e ottimizzare tutte le tue risorse, inclusi i cloud pubblici e i data center privati.



== Data Infrastructure Insights è disponibile in due edizioni

Data Infrastructure Insights Basic Edition è progettato specificamente per monitorare e ottimizzare le risorse NetApp Data Fabric. Fornisce analisi avanzate per le connessioni tra tutte le risorse NetApp, tra cui HCI e All Flash FAS (AFF) all'interno dell'ambiente, gratuitamente.

Data Infrastructure Insights Standard Edition si concentra non solo sui componenti infrastrutturali abilitati da NetApp Data Fabric, ma anche sugli ambienti multi-vendor e multi-cloud. Grazie alle sue funzionalità avanzate, puoi accedere al supporto di oltre 100 servizi e risorse.

Nel mondo odierno, con risorse in gioco dai data center on-premise a più cloud pubblici, è fondamentale avere un quadro completo dell'applicazione stessa al disco back-end dello storage array. Il supporto aggiuntivo per il monitoraggio delle applicazioni (come Kafka, MongoDB e Nginx) fornisce le informazioni e le conoscenze necessarie per operare al livello di utilizzo ottimale e con il buffer di rischio perfetto.

Entrambe le edizioni (di base e standard) possono integrarsi con NetApp Active IQ Unified Manager. I clienti che utilizzano Active IQ Unified Manager possono visualizzare le informazioni di join all'interno dell'interfaccia utente di Data Infrastructure Insights. Le notifiche pubblicate su Active IQ Unified Manager non vengono ignorate e possono essere correlate agli eventi in Data Infrastructure Insights. In altre parole, otterrai il meglio di entrambi i mondi.



== Monitorare, risolvere i problemi e ottimizzare tutte le risorse

Data Infrastructure Insights ti aiuta a ridurre significativamente i tempi di risoluzione dei problemi e a impedire che abbiano un impatto sugli utenti finali. Inoltre, ti aiuta a ridurre i costi dell'infrastruttura cloud. La tua esposizione alle minacce interne è ridotta proteggendo i tuoi dati con informazioni pratiche.

Data Infrastructure Insights ti offre visibilità sull'intera infrastruttura ibrida in un unico posto: dal cloud pubblico al data center. Puoi creare istantaneamente dashboard pertinenti che possono essere personalizzati in base alle tue esigenze specifiche. È inoltre possibile creare avvisi mirati e condizionali specifici e pertinenti alle esigenze dell'organizzazione.

Il rilevamento avanzato delle anomalie consente di risolvere in modo proattivo i problemi prima che si verifichino. È possibile visualizzare automaticamente i conflitti e il degrado delle risorse per ripristinare rapidamente i carichi di lavoro interessati. Il troubleshooting viene eseguito più rapidamente grazie alla gerarchia di relazioni creata automaticamente tra i diversi componenti dello stack.

Puoi identificare le risorse inutilizzate o abbandonate nel tuo ambiente, che ti aiuta a scoprire le opportunità di dimensionare correttamente l'infrastruttura e ottimizzare l'intera spesa.

Data Infrastructure Insights visualizza la topologia del sistema per comprendere l'architettura di Kubernetes. È possibile monitorare lo stato dei cluster Kubernetes, inclusi i nodi in difficoltà, e ingrandire quando si verifica un problema.

Data Infrastructure Insights ti aiuta a proteggere i dati aziendali dall'uso improprio da parte di utenti malintenzionati o compromessi tramite apprendimento automatico avanzato e rilevamento delle anomalie che forniscono informazioni fruibili sulle minacce interne.

Data Infrastructure Insights ti aiuta a visualizzare le metriche di Kubernetes in modo da comprendere appieno le relazioni tra pod, nodi e cluster. È possibile valutare lo stato di salute di un cluster o di un pod di lavoro, nonché il carico attualmente in elaborazione, consentendo di assumere il controllo del cluster K8S e di controllare sia lo stato di salute che il costo dell'implementazione.

.Link correlati
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html["Inizia con Data Infrastructure Insights"^]

