---
sidebar: sidebar 
permalink: task_nas_flexcache.html 
keywords: flexcache, flexcache volume, offload traffic, work load, workload, access speed 
summary: 'È possibile utilizzare i volumi FlexCache per accelerare l"accesso ai dati o per trasferire il traffico dai volumi ad accesso elevato. I volumi FlexCache sono ideali per i carichi di lavoro ad alta intensità di lettura, in particolare quando i client devono accedere ripetutamente agli stessi dati.' 
---
= Migliora le performance per più client con FlexCache
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare i volumi FlexCache per accelerare l'accesso ai dati o per trasferire il traffico dai volumi ad accesso elevato. I volumi FlexCache sono ideali per i carichi di lavoro ad alta intensità di lettura, in particolare quando i client devono accedere ripetutamente agli stessi dati.

Gli argomenti di questa sezione illustrano come gestire i volumi FlexCache con Gestione sistema in ONTAP 9.7 e versioni successive.se si utilizza Gestione sistema classico (disponibile solo in ONTAP 9.7 e versioni precedenti), consultare questo argomento:

* https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_flexcache_volumes.html["Creare volumi FlexCache"^]


Il volume FlexCache può trovarsi sullo stesso cluster di o su un cluster diverso da quello del volume remoto. Se il volume remoto si trova su un cluster diverso, è necessario aver già fatto il peering dei cluster e delle VM di storage.


NOTE: Se è in uso una coppia ha link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html["Crittografia dei dischi SAS o NVMe (SED, NSE, FIPS)"], è necessario seguire le istruzioni riportate nell'argomento link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["Ripristino di un'unità FIPS o SED in modalità non protetta"] Per tutti i dischi all'interno della coppia ha prima dell'inizializzazione del sistema (opzioni di avvio 4 o 9). Il mancato rispetto di questa procedura potrebbe causare la perdita di dati in futuro se i dischi vengono riutilizzati.

.Fasi
. Selezionare *Storage > Volumes* (Storage > volumi).
. Selezionare *Aggiungi*.
. Selezionare *altre opzioni*, quindi selezionare *Aggiungi come cache per un volume remoto*.
+
.. Se si utilizza ONTAP 9.8 o versione successiva e si desidera disattivare la qualità del servizio o scegliere un criterio di qualità del servizio personalizzato, fare clic su *altre opzioni*, quindi in *archiviazione e ottimizzazione* selezionare *livello di servizio delle prestazioni*.




Per qualsiasi nuova richiesta di dati, il volume FlexCache richiede i dati dal volume remoto e li memorizza. Tutte le successive richieste di lettura dei dati vengono quindi inviate direttamente dal volume FlexCache.



== Video



=== In che modo FlexCache può ridurre la latenza WAN e i tempi di lettura dei dati globali

video::rbbH0l74RWc[youtube,width=848,height=480]


=== Scopri i vantaggi in termini di performance di ONTAP FlexCache!

video::bWi1-8Ydkpg[youtube,width=848,height=480]