---
sidebar: sidebar 
permalink: task_nas_file_system_analytics_view.html 
keywords: explorer, file system analytics, inactive data, capacity analytics, active data, historical data 
summary: 'Dopo aver attivato l"analisi del file system, la schermata Explorer consente di visualizzare l"analisi della capacità, impostare periodi di dati inattivi ed esplorare altri dati relativi ai file system.' 
---
= Visualizzare l'attività del file system in ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver attivato file System Analytics (FSA), è possibile visualizzare il contenuto della directory principale di un volume selezionato, ordinato in base allo spazio utilizzato in ogni sottostruttura.

Selezionare qualsiasi oggetto del file system per esplorare il file system e visualizzare informazioni dettagliate su ciascun oggetto in una directory. Le informazioni sulle directory possono anche essere visualizzate graficamente. Nel tempo, vengono visualizzati i dati storici per ogni sottostruttura. Lo spazio utilizzato non viene ordinato se sono presenti più di 3000 directory.



== Esplora risorse

La schermata file System Analytics *Explorer* è composta da tre aree:

* Visualizzazione ad albero di directory e sottodirectory; elenco espandibile con nome, dimensione, cronologia delle modifiche e cronologia degli accessi.
* File; mostra nome, dimensione e tempo di accesso per l'oggetto selezionato nell'elenco di directory.
* Confronto dei dati attivi e inattivi per l'oggetto selezionato nell'elenco delle directory.
+
A partire da ONTAP 9.9.1, è possibile personalizzare l'intervallo da segnalare. Il valore predefinito è di un anno. In base a queste personalizzazioni, è possibile intraprendere azioni correttive, come lo spostamento di volumi e la modifica della policy di tiering.



L'ora di accesso viene visualizzata per impostazione predefinita. Tuttavia, se l'impostazione predefinita del volume è stata modificata dall'interfaccia CLI (impostando il `-atime-update` opzione a. `false` con `volume modify` comando), quindi viene visualizzata solo l'ora dell'ultima modifica. Ad esempio:

* La vista ad albero non visualizza la *cronologia di accesso*.
* La vista file viene modificata.
* La vista dati attiva/inattiva si basa sull'ora modificata (`mtime`).


Utilizzando queste schermate, è possibile esaminare quanto segue:

* Le posizioni del file system occupano la maggior parte dello spazio
* Informazioni dettagliate su un albero di directory, incluso il numero di file e sottodirectory all'interno di directory e sottodirectory
* Posizioni del file system che contengono dati vecchi (ad esempio, scratch, temp o log tree)


Tenere a mente i seguenti punti quando si interpreta l'output FSA:

* FSA mostra dove e quando i tuoi dati sono in uso, non la quantità di dati che vengono elaborati. Ad esempio, un elevato consumo di spazio da parte dei file recentemente utilizzati o modificati non indica necessariamente elevati carichi di elaborazione del sistema.
* Il modo in cui la scheda *Volume Explorer* calcola il consumo di spazio per FSA potrebbe differire da altri strumenti. In particolare, potrebbero esserci differenze significative rispetto al consumo riportato in *Volume Overview* se il volume dispone delle funzionalità di efficienza dello storage abilitate. Questo perché la scheda *Volume Explorer* non include i risparmi in termini di efficienza.
* A causa delle limitazioni di spazio nella visualizzazione della directory, non è possibile visualizzare una profondità della directory superiore a 8 livelli nella _visualizzazione elenco_. Per visualizzare le directory più profonde di 8 livelli, passare a _Graphical View_, individuare la directory desiderata, quindi tornare a _List View_. In questo modo si otterrà ulteriore spazio sullo schermo.


.Fasi
. Visualizzare il contenuto della directory principale di un volume selezionato:
+
[cols="2"]
|===
| In ONTAP 9.8 e 9.9.1 | A partire da ONTAP 9.10.1 


| Fare clic su *Storage > Volumes* (archiviazione > volumi), selezionare il volume desiderato, quindi fare clic su *Explorer*. | Selezionare *Storage > Volumes* (archiviazione > volumi), quindi selezionare il volume desiderato. Dal menu dei singoli volumi, selezionare *file System > Explorer*. 
|===


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["modifica del volume"^]

