---
sidebar: sidebar 
permalink: task-svm-admin-dashboard-sm.html 
keywords: netapp, system manager, ontap, administration, svm, storage vm, volume, vserver, dashboard, administrator, tenant, multi-tenancy, protocol, network interface, performance 
summary: 'Gli amministratori del cluster possono fornire agli amministratori SVM l"accesso per monitorare e gestire gli SVM. Gli amministratori SVM possono monitorare e gestire gli SVM tramite la dashboard di amministrazione SVM in ONTAP System Manager.' 
---
= Gestisci e monitora le SVM ONTAP con System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP 9.19.1, gli amministratori SVM possono monitorare e gestire i propri SVM utilizzando una dashboard dedicata di System Manager.

.Prima di iniziare
L'amministratore del cluster deve fornirti:

* Indirizzo IP di gestione per SVM
* Credenziali (nome utente e password) per la dashboard di System Manager della SVM (l'utente vsadmin deve essere sbloccato)
* Facoltativamente, autorizzazioni per aggiungere volumi sull'SVM


.Fasi
. Inserisci l'indirizzo IP di gestione dell'SVM in un browser.
. Inserisci il tuo nome utente e la password per l'amministratore SVM (vsadmin).
. Seleziona *Sign in*.
+
La dashboard di ONTAP System Manager si apre.

. È possibile visualizzare le seguenti informazioni sulla SVM:
+
[cols="1,2"]
|===
| Informazioni sull'SVM | Descrizione 


| Protocolli | I protocolli abilitati sulla SVM. 


| Dettagli | Informazioni NIS e LDAP, lingua e periodo di conservazione dopo l'eliminazione di un volume. 


| Performance | Statistiche sulle prestazioni di latenza, IOPS e throughput per ora, giorno, settimana, mese o anno per il protocollo selezionato. 
|===
. Facoltativamente, è possibile scaricare i dati in un file CSV (valori separati da virgola) per ulteriori analisi.
. Selezionare *Storage > Volumes* (Storage > volumi).
+
Si apre la pagina della dashboard dei volumi.

+
L'amministratore del cluster può concederti l'autorizzazione ad aggiungere volumi all'SVM. Se questa autorizzazione non viene concessa, la selezione del pulsante *Aggiungi* non andrà a buon fine e verrà visualizzato un messaggio di errore.



.Informazioni correlate
* link:concepts/cluster-svm-administrators-concept.html["Amministrazione di cluster e SVM"]
* link:task_cp_dashboard_tour.html#performance["Scopri la gestione dei cluster nelle dashboard di ONTAP System Manager (sezione Prestazioni)"]
* link:volumes/manage-volumes-task.html["Gestire i volumi ONTAP con System Manager"]

