---
sidebar: sidebar 
permalink: task_san_configure_protection_for_business_continuity.html 
keywords: netapp, ontap, System Manager, LUNs, source cluster, protect, protection, storage VM, volume, volumes, source, destination, cluster, IOPS activity 
summary: 'La configurazione della protezione per la business continuity implica la selezione delle LUN nel cluster di origine ONTAP e l"aggiunta a un gruppo di coerenza. Aprire System Manager da un browser del cluster di origine per iniziare a configurare la protezione per la business continuity.' 
---
= Configurare la protezione per la business continuity
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
La configurazione della protezione per la business continuity implica la selezione delle LUN nel cluster di origine ONTAP e l'aggiunta a un gruppo di coerenza. Aprire System Manager da un browser del cluster di origine per iniziare a configurare la protezione per la business continuity.

Questo flusso di lavoro è progettato per ONTAP 9.8 e 9.9. A partire da ONTAP 9.10.1, si consiglia di iniziare creando un gruppo di coerenza e quindi di utilizzare SM-BC come protezione remota.



== A proposito di questa attività

* I LUN devono risiedere sulla stessa VM di storage.
* Le LUN possono risiedere su volumi diversi.
* Il cluster di origine e di destinazione non può essere lo stesso.
* L'IPSpace predefinito è richiesto da SM-BC per le relazioni peer del cluster. IPSpace personalizzato non supportato.


.Fasi
. Scegli i LUN che desideri proteggere e aggiungili a un gruppo di protezione: *Protezione > Panoramica > Proteggi per la business continuity > Proteggi LUN*.
. Selezionare una o più LUN da proteggere sul cluster di origine.
. Selezionare il cluster di destinazione e SVM.
. Per impostazione predefinita, l'opzione *Inizializza relazione* è selezionata. Fare clic su *Save* (Salva) per iniziare la protezione.
. Accedere a *Dashboard > Performance* per verificare l'attività IOPS per le LUN.
. Nel cluster di destinazione, utilizzare System Manager per verificare che la protezione per la relazione di business continuity sia sincronizzata: *Protezione > relazioni*.

