---
sidebar: sidebar 
permalink: task_admin_monitor_capacity_in_sm.html 
keywords: used storage, digital advisor, local tier capacity, aggregate capacity, add capacity, used capacity, available, total capacity, inactive data, overprovision, overflows, snapshot copy reserves, reserves, clone, maximum capacity limit, storage VM, allocate 
summary: Con System Manager, è possibile monitorare la quantità di capacità di storage utilizzata e la quantità ancora disponibile per un cluster, un Tier locale o una VM di storage. 
---
= Monitorare cluster, Tier e capacità SVM in ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con System Manager, è possibile monitorare la quantità di capacità di storage utilizzata e la quantità ancora disponibile per un cluster, un Tier locale o una VM di storage.

Con ogni versione di ONTAP, System Manager fornisce informazioni di monitoraggio della capacità più affidabili:

* A partire da ONTAP 9.10.1, System Manager consente di visualizzare i dati storici sulla capacità del cluster e le proiezioni sulla capacità utilizzata o disponibile in futuro. È inoltre possibile monitorare la capacità dei volumi e dei Tier locali.
* A partire da ONTAP 9.12.1, System Manager visualizza la quantità di capacità impegnata per un Tier locale.
* A partire da ONTAP 9.13.1, è possibile attivare un limite massimo di capacità per una VM di storage e impostare una soglia per attivare avvisi quando lo storage utilizzato raggiunge una determinata percentuale della capacità massima.



NOTE: Le misurazioni della capacità utilizzata vengono visualizzate in modo diverso a seconda della versione di ONTAP in uso. Ulteriori informazioni in link:./concepts/capacity-measurements-in-sm-concept.html["Misurazioni della capacità in System Manager"].



== Visualizzare la capacità di un cluster

È possibile visualizzare le misurazioni della capacità di un cluster nella dashboard di System Manager.

.Prima di iniziare
Per visualizzare i dati relativi alla capacità nel cloud, è necessario disporre di un account con Digital Advisor ed essere connessi.

.Fasi
. In System Manager, fare clic su *Dashboard*.
. Nella sezione *capacità*, è possibile visualizzare quanto segue:
+
--
** Capacità totale utilizzata del cluster
** Capacità totale disponibile del cluster
** Percentuali di capacità utilizzata e disponibile.
** Rapporto di riduzione dei dati.
** Quantità di capacità utilizzata nel cloud.
** Cronologia dell'utilizzo della capacità.
** Proiezione dell'utilizzo della capacità


--
+

NOTE: In System Manager, le rappresentazioni della capacità non tengono conto delle capacità del Tier storage root (aggregato).

. Fare clic sul grafico per visualizzare ulteriori dettagli sulla capacità del cluster.
+
Le misurazioni della capacità vengono visualizzate in due diagrammi a barre:

+
--
** Il grafico in alto mostra la capacità fisica: La dimensione dello spazio fisico utilizzato, riservato e disponibile.
** Il grafico in basso mostra la capacità logica: Le dimensioni dei dati dei client, gli snapshot e i cloni e lo spazio logico totale utilizzato.


--
+
Sotto i grafici a barre sono riportate le misurazioni per la riduzione dei dati:

+
--
** Rapporto di riduzione dei dati solo per i dati client (snapshot e cloni non sono inclusi).
** Rapporto complessivo di riduzione dei dati.


--


Per ulteriori informazioni, vedere link:./concepts/capacity-measurements-in-sm-concept.html["Misurazioni della capacità in System Manager"].



== Visualizzare la capacità di un Tier locale

È possibile visualizzare i dettagli sulla capacità dei Tier locali. A partire da ONTAP 9.12.1, la vista *capacità* include anche la quantità di capacità impegnata per un Tier locale, consentendo di determinare se è necessario aggiungere capacità al Tier locale per soddisfare la capacità impegnata ed evitare di esaurire lo spazio libero.

.Fasi
. Fare clic su *Storage > Tier*.
. Selezionare il nome del Tier locale.
. Nella pagina *Panoramica*, nella sezione *capacità*, la capacità viene visualizzata in un grafico a barre con tre misurazioni:
+
** Capacità utilizzata e riservata
** Capacità disponibile
** Capacità impegnata (a partire da ONTAP 9.12.1)


. Fare clic sul grafico per visualizzare i dettagli sulla capacità del Tier locale.
+
Le misurazioni della capacità vengono visualizzate in due diagrammi a barre:

+
--
** Il grafico a barre superiore visualizza la capacità fisica: La dimensione dello spazio fisico utilizzato, riservato e disponibile.
** Il grafico a barre inferiore visualizza la capacità logica: La dimensione dei dati del client, gli snapshot e i cloni e il totale dello spazio logico utilizzato.


--
+
Sotto i grafici a barre sono riportati i rapporti di misurazione per la riduzione dei dati:

+
--
** Rapporto di riduzione dei dati solo per i dati client (snapshot e cloni non sono inclusi).
** Rapporto complessivo di riduzione dei dati.


--


Per ulteriori informazioni, vedere link:./concepts/capacity-measurements-in-sm-concept.html["Misurazioni della capacità in System Manager"].

.Azioni facoltative
* Se la capacità impegnata è superiore alla capacità del Tier locale, è possibile aggiungere capacità al Tier locale prima che esaurisca lo spazio libero. Vedere link:./disks-aggregates/add-disks-local-tier-aggr-task.html["Aggiunta di capacità a un Tier locale (aggiunta di dischi a un aggregato)"].
* È inoltre possibile visualizzare lo storage utilizzato da volumi specifici nel Tier locale selezionando la scheda *Volumes*.




== Visualizzare la capacità dei volumi in una VM di storage

È possibile visualizzare la quantità di storage utilizzata dai volumi in una VM di storage e la quantità di capacità ancora disponibile. La misurazione totale dello storage utilizzato e disponibile viene chiamata "capacità su più volumi".

.Fasi
. Selezionare *Storage* > *Storage VM*.
. Fare clic sul nome della VM di storage.
. Scorrere fino alla sezione *capacità*, che mostra un grafico a barre con le seguenti misurazioni:
+
--
** *Fisico utilizzato*: Somma dello storage fisico utilizzato in tutti i volumi di questa VM di storage.
** *Disponibile*: Somma della capacità disponibile in tutti i volumi di questa VM di storage.
** *Logica utilizzata*: Somma dello storage logico utilizzato in tutti i volumi di questa VM di storage.


--


Per ulteriori informazioni sulle misurazioni, vedere link:./concepts/capacity-measurements-in-sm-concept.html["Misurazioni della capacità in System Manager"].



== Visualizzare il limite massimo di capacità di una VM di storage

A partire da ONTAP 9.13.1, è possibile visualizzare il limite massimo di capacità di una VM di storage.

.Prima di iniziare
È necessario link:manage-max-cap-limit-svm-in-sm-task.html["Abilitare il limite massimo di capacità di una VM di storage"] prima di visualizzarlo.

.Fasi
. Selezionare *Storage* > *Storage VM*.
+
È possibile visualizzare le misurazioni della capacità massima in due modi:

+
--
** Nella riga relativa alla VM di storage, visualizzare la colonna *capacità massima* che contiene un grafico a barre che mostra la capacità utilizzata, la capacità disponibile e la capacità massima.
** Fare clic sul nome della VM di storage. Nella scheda *Panoramica*, scorrere per visualizzare i valori di soglia di avviso relativi alla capacità massima, alla capacità allocata e alla capacità nella colonna di sinistra.


--


.Informazioni correlate
* link:manage-max-cap-limit-svm-in-sm-task.html#edit-max-cap-limit-svm["Modificare il limite massimo di capacità di una VM di storage"]
* link:./concepts/capacity-measurements-in-sm-concept.html["Misurazioni della capacità in System Manager"]

