---
permalink: element-replication/enable-snapmirror-cluster-task.html 
sidebar: sidebar 
keywords: enable, snapmirror, element, cluster 
summary: 'È necessario attivare SnapMirror sul cluster di elementi prima di poter creare una relazione di replica. È possibile eseguire questa attività solo nell"interfaccia utente Web del software Element.' 
---
= Attivare SnapMirror sul cluster di elementi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario attivare SnapMirror sul cluster di elementi prima di poter creare una relazione di replica. È possibile eseguire questa attività solo nell'interfaccia utente Web del software Element.

.Prima di iniziare
* Il cluster di elementi deve eseguire il software NetApp Element versione 10.1 o successiva.
* SnapMirror può essere abilitato solo per i cluster di elementi utilizzati con i volumi NetApp ONTAP.


.A proposito di questa attività
Il sistema Element viene fornito con SnapMirror disattivato per impostazione predefinita. SnapMirror non viene attivato automaticamente come parte di una nuova installazione o di un aggiornamento.

[NOTE]
====
Una volta attivato, SnapMirror non può essere disattivato. È possibile disattivare la funzione SnapMirror e ripristinare le impostazioni predefinite solo ripristinando l'immagine predefinita del cluster.

====
.Fasi
. Fare clic su *Clusters* > *Impostazioni*.
. Individuare le impostazioni specifiche del cluster per SnapMirror.
. Fare clic su *Enable SnapMirror* (attiva SnapMirror

