---
permalink: element-replication/initialize-replication-relationship-task.html 
sidebar: sidebar 
keywords: initialize, replication, relationship 
summary: 'Per tutti i tipi di relazione, l"inizializzazione esegue un trasferimento di riferimento: Esegue una copia Snapshot del volume di origine, quindi trasferisce la copia e tutti i blocchi di dati a cui fa riferimento al volume di destinazione.' 
---
= Inizializzare una relazione di replica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per tutti i tipi di relazione, l'inizializzazione esegue un _trasferimento baseline_: Esegue una copia Snapshot del volume di origine, quindi trasferisce la copia e tutti i blocchi di dati a cui fa riferimento al volume di destinazione.

.Prima di iniziare
* Il nodo Element contenente il volume da replicare deve essere stato reso accessibile a ONTAP.
* Il volume Element deve essere stato abilitato per la replica di SnapMirror.
* Se si utilizza il tipo di policy "`mirror-vault`", è necessario configurare un'etichetta SnapMirror per la replica delle copie Snapshot degli elementi.


.A proposito di questa attività
Specificare il percorso di origine dell'elemento nel modulo `_hostip:_/lun/_name_`, dove "`lun`" è la stringa effettiva "`lun`" e. `_name_` È il nome del volume Element.

L'inizializzazione può richiedere molto tempo. Si consiglia di eseguire il trasferimento di riferimento in ore non di punta.

[NOTE]
====
Se l'inizializzazione di una relazione da un'origine ONTAP a una destinazione dell'elemento non riesce per qualsiasi motivo, continuerà a fallire anche dopo aver corretto il problema (ad esempio, un nome LUN non valido). La soluzione è la seguente:

. Eliminare la relazione.
. Eliminare il volume di destinazione dell'elemento.
. Creare un nuovo volume di destinazione elemento.
. Creare e inizializzare una nuova relazione dall'origine ONTAP al volume di destinazione dell'elemento.


====
.Fase
. Inizializzare una relazione di replica:
+
`snapmirror initialize -source-path _hostip:_/lun/_name_ -destination-path _SVM:volume|cluster://SVM/volume_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio riportato di seguito viene inizializzata la relazione tra il volume di origine `0005` All'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

