---
permalink: element-replication/make-destination-volume-writeable-task.html 
sidebar: sidebar 
keywords: make, destination, volume, write 
summary: È necessario rendere il volume di destinazione scrivibile prima di poter inviare i dati dal volume ai client. È possibile utilizzare il comando quiesce di snapmirror per interrompere i trasferimenti pianificati verso la destinazione, il comando di interruzione di snapmirror per interrompere i trasferimenti in corso e il comando di interruzione di snapmirror per rendere la destinazione scrivibile. 
---
= Rendere il volume di destinazione scrivibile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando Disaster disattiva il sito primario per una relazione di disaster recovery SnapMirror, è possibile fornire i dati dal volume di destinazione con interruzioni minime. È possibile riattivare il volume di origine quando il servizio viene ripristinato nel sito primario.

È necessario rendere il volume di destinazione scrivibile prima di poter inviare i dati dal volume ai client. È possibile utilizzare `snapmirror quiesce` per arrestare i trasferimenti pianificati verso la destinazione, il `snapmirror abort` per interrompere i trasferimenti in corso e il `snapmirror break` per rendere la destinazione scrivibile.

.A proposito di questa attività
È necessario specificare il percorso di origine dell'elemento nel formato `<hostip:>/lun/<name>`, dove "`lun'" è la stringa effettiva "`lun'" ed `name` è il nome del volume dell'elemento.

.Fasi
. Interrompere i trasferimenti pianificati verso la destinazione:
+
`snapmirror quiesce -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente vengono interrompiti i trasferimenti pianificati tra il volume di origine `0005` All'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Interrompere i trasferimenti in corso verso la destinazione:
+
`snapmirror abort -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente vengono interrompiti i trasferimenti in corso tra il volume di origine `0005` All'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Interrompere la relazione di disaster recovery di SnapMirror:
+
`snapmirror break -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene spezzata la relazione tra il volume di origine `0005` All'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` acceso `svm_backup` e il volume di destinazione `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

