---
permalink: element-replication/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate. original, source, volume 
summary: È possibile ristabilire la relazione di protezione dei dati originale tra i volumi di origine e di destinazione quando non è più necessario fornire dati dalla destinazione. 
---
= Riattivare il volume di origine originale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ristabilire la relazione di protezione dei dati originale tra i volumi di origine e di destinazione quando non è più necessario fornire dati dalla destinazione.

.A proposito di questa attività
La procedura riportata di seguito presuppone che la linea di base nel volume di origine originale sia intatta. Se la linea di base non è intatta, è necessario creare e inizializzare la relazione tra il volume da cui si stanno fornendo i dati e il volume di origine originale prima di eseguire la procedura.

Specificare il percorso di origine dell'elemento nel modulo `_hostip:_/lun/_name_`, dove "`lun`" è la stringa effettiva "`lun`" e. `name` È il nome del volume Element.

A partire da ONTAP 9.4, le copie Snapshot di un LUN create durante la distribuzione dei dati dalla destinazione ONTAP vengono replicate automaticamente quando l'origine dell'elemento viene riattivata.

Le regole di replica sono le seguenti:

* Sono supportati solo i LUN iSCSI.
* Non è possibile replicare più di un LUN da un volume ONTAP a un volume Element.
* Non è possibile replicare un LUN da un volume ONTAP a più volumi di elementi.


.Fasi
. Eliminare la relazione di protezione dei dati originale:
+
`snapmirror delete -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip:_/lun/_name_ -policy _policy_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene eliminata la relazione tra il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11 e al volume da cui si stanno servendo i dati, `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----
. Invertire la relazione di protezione dei dati originale:
+
`snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip:_/lun/_name_ -policy _policy_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Sebbene la risincronizzazione non richieda un trasferimento di riferimento, può richiedere molto tempo. È possibile eseguire la risincronizzazione in ore non di punta.

+
Nell'esempio seguente viene invertita la relazione tra il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11 e al volume da cui si stanno servendo i dati, `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Aggiornare la relazione inversa:
+
`snapmirror update -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip:_/lun/_name_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Il comando non riesce se non esiste una copia Snapshot comune sull'origine e sulla destinazione. Utilizzare `snapmirror initialize` per reinizializzare la relazione.

====
+
Nell'esempio riportato di seguito viene aggiornata la relazione tra il volume da cui si stanno fornendo i dati, `volA_dst` acceso `svm_backup`e il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Arrestare i trasferimenti pianificati per la relazione invertita:
+
`snapmirror quiesce -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip:_/lun/_name_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente vengono interrompiti i trasferimenti pianificati tra il volume da cui si stanno fornendo i dati, `volA_dst` acceso `svm_backup`e il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Arrestare i trasferimenti in corso per la relazione invertita:
+
`snapmirror abort -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip:_/lun/_name_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente interrompe i trasferimenti in corso tra il volume da cui si stanno servendo i dati, `volA_dst` acceso `svm_backup`e il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Interrompere la relazione inversa:
+
`snapmirror break -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip:_/lun/_name_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene spezzata la relazione tra il volume da cui si stanno fornendo i dati, `volA_dst` acceso `svm_backup`e il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Eliminare la relazione di protezione dei dati invertita:
+
`snapmirror delete -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip_:/lun/_name_ -policy _policy_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene eliminata la relazione inversa tra il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11 e al volume da cui si stanno servendo i dati, `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Ristabilire la relazione di protezione dei dati originale:
+
`snapmirror resync -source-path _hostip_:/lun/_name_ -destination-path _SVM:volume|cluster://SVM/volume_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene ristabilita la relazione tra il volume di origine originale, `0005` All'indirizzo IP 10.0.0.11 e al volume di destinazione originale, `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----


.Al termine
Utilizzare `snapmirror show` Per verificare che sia stata creata la relazione SnapMirror. Per la sintassi completa dei comandi, vedere la pagina man.
