---
permalink: element-replication/update-replication-relationship-manually-task.html 
sidebar: sidebar 
keywords: update, replication, relationship, manually 
summary: Potrebbe essere necessario aggiornare manualmente una relazione di replica se un aggiornamento non riesce a causa di un errore di rete. 
---
= Aggiornare manualmente una relazione di replica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario aggiornare manualmente una relazione di replica se un aggiornamento non riesce a causa di un errore di rete.

.A proposito di questa attività
È necessario specificare il percorso di origine dell'elemento nel formato `<hostip:>/lun/<name>`, dove "`lun'" è la stringa effettiva "`lun'" ed `name` è il nome del volume dell'elemento.

.Fasi
. Aggiornare manualmente una relazione di replica:
+
`snapmirror update -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Il comando non riesce se non esiste una copia Snapshot comune sull'origine e sulla destinazione. Utilizzare `snapmirror initialize` per reinizializzare la relazione.

====
+
Nell'esempio seguente viene aggiornata la relazione tra il volume di origine `0005` All'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror update -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

