---
permalink: tape-backup/assign-tape-aliases-task.html 
sidebar: sidebar 
keywords: assign, tape, aliases, device, identification, drive, medium, changer, logical, names, backup 
summary: 'Per una facile identificazione del dispositivo, è possibile assegnare alias del nastro a un"unità a nastro o a un caricatore di supporti. Gli alias forniscono una corrispondenza tra i nomi logici dei dispositivi di backup e un nome assegnato in modo permanente all"unità a nastro o al caricatore di supporti.' 
---
= Assegnare alias nastro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per una facile identificazione del dispositivo, è possibile assegnare alias del nastro a un'unità a nastro o a un caricatore di supporti. Gli alias forniscono una corrispondenza tra i nomi logici dei dispositivi di backup e un nome assegnato in modo permanente all'unità a nastro o al caricatore di supporti.

.Fasi
. Assegnare un alias a un'unità a nastro o a un caricatore di supporti utilizzando `storage tape alias set` comando.
+
Per ulteriori informazioni su questo comando, vedere le pagine man.

+
È possibile visualizzare le informazioni sul numero di serie (SN) delle unità a nastro utilizzando `system node hardware tape drive show` e informazioni sulle librerie di nastri utilizzando `system node hardware tape library show` comandi.

+
Il seguente comando imposta un nome alias su un'unità a nastro con numero di serie SN[123456]L4 collegato al nodo, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name st3 -mapping SN[123456]L4
----
+
Il seguente comando imposta un nome alias su un media changer con numero di serie SN[65432] collegato al nodo, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name mc1 -mapping SN[65432]
----


.Informazioni correlate
xref:assign-tape-aliases-concept.adoc[Che cos'è l'aliasing su nastro]

xref:remove-tape-aliases-task.adoc[Rimozione degli alias del nastro]
