---
permalink: tape-backup/availability-volumes-tapes-backup-restore-lif-reference.html 
sidebar: sidebar 
keywords: lif, availability, volumes, tape, devices, backup, restore, types, cab, extension, application 
summary: 'È possibile configurare un"applicazione di backup per stabilire una connessione di controllo NDMP su qualsiasi tipo di LIF in un cluster. Nella modalità NDMP con ambito SVM (Storage Virtual Machine), è possibile determinare la disponibilità di volumi e dispositivi a nastro per le operazioni di backup e ripristino in base a questi tipi di LIF e allo stato dell"estensione CAB.' 
---
= Disponibilità di volumi e dispositivi a nastro per il backup e il ripristino su diversi tipi di LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare un'applicazione di backup per stabilire una connessione di controllo NDMP su qualsiasi tipo di LIF in un cluster. Nella modalità NDMP con ambito SVM (Storage Virtual Machine), è possibile determinare la disponibilità di volumi e dispositivi a nastro per le operazioni di backup e ripristino in base a questi tipi di LIF e allo stato dell'estensione CAB.

Le seguenti tabelle mostrano la disponibilità di volumi e dispositivi a nastro per i tipi LIF di connessione di controllo NDMP e lo stato dell'estensione CAB:



== Disponibilità di volumi e dispositivi a nastro quando L'estensione CAB non è supportata dall'applicazione di backup

|===
| Tipo LIF connessione di controllo NDMP | Volumi disponibili per il backup o il ripristino | Dispositivi a nastro disponibili per il backup o il ripristino 


 a| 
LIF di gestione dei nodi
 a| 
Tutti i volumi ospitati da un nodo
 a| 
Dispositivi a nastro collegati al nodo che ospita la LIF di gestione dei nodi



 a| 
LIF dati
 a| 
Solo i volumi che appartengono alla SVM ospitati da un nodo che ospita la LIF dei dati
 a| 
Nessuno



 a| 
LIF gestione cluster
 a| 
Tutti i volumi ospitati da un nodo che ospita la LIF di gestione del cluster
 a| 
Nessuno



 a| 
LIF intercluster
 a| 
Tutti i volumi ospitati da un nodo che ospita la LIF dell'intercluster
 a| 
Dispositivi a nastro collegati al nodo che ospita la LIF dell'intercluster

|===


== Disponibilità di volumi e dispositivi a nastro quando L'estensione CAB è supportata dall'applicazione di backup

|===
| Tipo LIF connessione di controllo NDMP | Volumi disponibili per il backup o il ripristino | Dispositivi a nastro disponibili per il backup o il ripristino 


 a| 
LIF di gestione dei nodi
 a| 
Tutti i volumi ospitati da un nodo
 a| 
Dispositivi a nastro collegati al nodo che ospita la LIF di gestione dei nodi



 a| 
LIF dati
 a| 
Tutti i volumi che appartengono alla SVM che ospita la LIF dei dati
 a| 
Nessuno



 a| 
LIF gestione cluster
 a| 
Tutti i volumi nel cluster
 a| 
Tutti i dispositivi a nastro nel cluster



 a| 
LIF intercluster
 a| 
Tutti i volumi nel cluster
 a| 
Tutti i dispositivi a nastro nel cluster

|===