---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: 'Sono disponibili comandi per visualizzare le informazioni relative alle unità a nastro e ai media changer in un cluster, portare un"unità a nastro online e portarla fuori linea, modificare la posizione della cartuccia dell"unità a nastro, impostare e cancellare il nome alias dell"unità a nastro e reimpostare un"unità a nastro. È inoltre possibile visualizzare e ripristinare le statistiche del disco a nastro.' 
---
= Comandi ONTAP per la gestione di unità nastro, cambia-supporti e operazioni di unità nastro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili comandi per visualizzare le informazioni relative alle unità a nastro e ai media changer in un cluster, portare un'unità a nastro online e portarla fuori linea, modificare la posizione della cartuccia dell'unità a nastro, impostare e cancellare il nome alias dell'unità a nastro e reimpostare un'unità a nastro. È inoltre possibile visualizzare e ripristinare le statistiche del disco a nastro.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Portare online un'unità a nastro
 a| 
`storage tape online`



 a| 
Cancellare un nome alias per l'unità a nastro o il caricatore di supporti
 a| 
`storage tape alias clear`



 a| 
Attivare o disattivare un'operazione di traccia su nastro per un'unità a nastro
 a| 
`storage tape trace`



 a| 
Modificare la posizione della cartuccia del disco a nastro
 a| 
`storage tape position`



 a| 
Ripristinare un'unità a nastro
 a| 
`storage tape reset`

[NOTE]
====
Questo comando è disponibile solo a livello di privilegi avanzati.

====


 a| 
Impostare un nome alias per l'unità a nastro o il caricatore di supporti
 a| 
`storage tape alias set`



 a| 
Portare un'unità a nastro offline
 a| 
`storage tape offline`



 a| 
Visualizza informazioni su tutte le unità a nastro e i media changer
 a| 
`storage tape show`



 a| 
Visualizzare le informazioni sulle unità a nastro collegate al cluster
 a| 
* `storage tape show-tape-drive`
* `system node hardware tape drive show`




 a| 
Consente di visualizzare informazioni sui media changer collegati al cluster
 a| 
`storage tape show-media-changer`



 a| 
Visualizzare le informazioni sugli errori relativi alle unità a nastro collegate al cluster
 a| 
`storage tape show-errors`



 a| 
Visualizza tutte le unità a nastro qualificate e supportate da ONTAP collegate a ciascun nodo del cluster
 a| 
`storage tape show-supported-status`



 a| 
Visualizzare gli alias di tutte le unità a nastro e i media changer collegati a ciascun nodo del cluster
 a| 
`storage tape alias show`



 a| 
Azzerare le statistiche di lettura di un'unità a nastro
 a| 
`storage stats tape zero` `tape_name`

Devi usare questo comando al nodeshell.



 a| 
Visualizza le unità a nastro supportate da ONTAP
 a| 
`storage show tape supported [-v]`

Devi usare questo comando al nodeshell. È possibile utilizzare `-v` per visualizzare ulteriori dettagli su ciascuna unità a nastro.



 a| 
Visualizzare le statistiche dei dispositivi a nastro per comprendere le prestazioni dei nastri e verificare il modello di utilizzo
 a| 
`storage stats tape` `tape_name`

Devi usare questo comando al nodeshell.

|===
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+tape["nastro di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-show.html["spettacolo di nastri di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-show-supported-status.html["nastro di archiviazione mostra-stato-supportato"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-show-tape-drive.html["nastro di archiviazione mostra-unità-nastro"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-clear.html["alias nastro di archiviazione chiaro"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-set.html["set di alias del nastro di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-show.html["alias del nastro di archiviazione mostra"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-trace.html["traccia del nastro di archiviazione"^]

