---
permalink: tape-backup/commands-manage-node-scoped-ndmp-reference.html 
sidebar: sidebar 
keywords: command, manage, node, scoped, ndmp, mode 
summary: È possibile utilizzare i comandi ndmp dei servizi di sistema per gestire NDMP a livello di nodo. Alcuni di questi comandi sono deprecati e verranno rimossi in una release futura. 
---
= Comandi per la gestione della modalità NDMP con ambito nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `system services ndmp` Comandi per gestire NDMP a livello di nodo. Alcuni di questi comandi sono deprecati e verranno rimossi in una release futura.

È possibile utilizzare i seguenti comandi NDMP solo a livello di privilegi avanzati:

* `system services ndmp service terminate`
* `system services ndmp service start`
* `system services ndmp service stop`
* `system services ndmp log start`
* `system services ndmp log stop`


|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Abilitare il servizio NDMP
 a| 
`system services ndmp on`*



 a| 
Disattiva servizio NDMP
 a| 
`system services ndmp off`*



 a| 
Visualizzare la configurazione NDMP
 a| 
`system services ndmp show`*



 a| 
Modificare la configurazione NDMP
 a| 
`system services ndmp modify`*



 a| 
Visualizza la versione NDMP predefinita
 a| 
`system services ndmp version`*



 a| 
Visualizzare la configurazione del servizio NDMP
 a| 
`system services ndmp service show`



 a| 
Modificare la configurazione del servizio NDMP
 a| 
`system services ndmp service modify`



 a| 
Visualizza tutte le sessioni NDMP
 a| 
`system services ndmp status`



 a| 
Visualizza informazioni dettagliate su tutte le sessioni NDMP
 a| 
`system services ndmp probe`



 a| 
Terminare la sessione NDMP specificata
 a| 
`system services ndmp kill`



 a| 
Terminare tutte le sessioni NDMP
 a| 
`system services ndmp kill-all`



 a| 
Modificare la password NDMP
 a| 
`system services ndmp password`*



 a| 
Attiva la modalità NDMP con ambito nodo
 a| 
`system services ndmp node-scope-mode on`*



 a| 
Disattiva la modalità NDMP con ambito nodo
 a| 
`system services ndmp node-scope-mode off`*



 a| 
Visualizza lo stato della modalità NDMP con ambito nodo
 a| 
`system services ndmp node-scope-mode status`*



 a| 
Terminare con forza tutte le sessioni NDMP
 a| 
`system services ndmp service terminate`



 a| 
Avviare il daemon del servizio NDMP
 a| 
`system services ndmp service start`



 a| 
Arrestare il daemon del servizio NDMP
 a| 
`system services ndmp service stop`



 a| 
Avviare la registrazione per la sessione NDMP specificata
 a| 
`system services ndmp log start`*



 a| 
Interrompere la registrazione per la sessione NDMP specificata
 a| 
`system services ndmp log stop`*

|===
* Questi comandi sono deprecati e verranno rimossi in una release futura.


Per ulteriori informazioni su questi comandi, consultare le pagine man del `system services ndmp` comandi.
