---
permalink: tape-backup/commands-verify-library-connections-reference.html 
sidebar: sidebar 
keywords: commands, verify, tape, library, connections, storage, system 
summary: È possibile visualizzare informazioni sul percorso di connessione tra un sistema di storage e una configurazione della libreria di nastri collegata al sistema di storage. È possibile utilizzare queste informazioni per verificare il percorso di connessione alla configurazione della libreria di nastri o per la risoluzione dei problemi relativi ai percorsi di connessione. 
---
= Comandi per la verifica delle connessioni della libreria di nastri in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sul percorso di connessione tra un sistema di storage e una configurazione della libreria di nastri collegata al sistema di storage. È possibile utilizzare queste informazioni per verificare il percorso di connessione alla configurazione della libreria di nastri o per la risoluzione dei problemi relativi ai percorsi di connessione.

È possibile visualizzare i seguenti dettagli della libreria di nastri per verificare le connessioni della libreria di nastri dopo l'aggiunta o la creazione di una nuova libreria di nastri o dopo il ripristino di un percorso guasto in un accesso a percorso singolo o multipath a una libreria di nastri. È inoltre possibile utilizzare queste informazioni durante la risoluzione di errori relativi al percorso o in caso di errore nell'accesso a una libreria di nastri.

* Nodo a cui è collegata la libreria di nastri
* ID dispositivo
* Percorso NDMP
* Nome della libreria di nastri
* Porta di destinazione e ID porta iniziatore
* Accesso a percorso singolo o multipath a una libreria di nastri per ogni porta di destinazione o FC Initiator
* Dettagli sull'integrità dei dati relativi al percorso, ad esempio "`Path Errors`" e "`Path Qual`"
* Gruppi LUN e conteggi LUN


|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Consente di visualizzare informazioni su una libreria di nastri in un cluster
 a| 
`system node hardware tape library show`



 a| 
Visualizzare le informazioni sul percorso di una libreria di nastri
 a| 
`storage tape library path show`



 a| 
Visualizzare le informazioni sul percorso di una libreria di nastri per ogni porta di iniziatore
 a| 
`storage tape library path show-by-initiator`



 a| 
Visualizzare le informazioni di connettività tra una libreria di nastri di storage e il cluster
 a| 
`storage tape library config show`

|===
Ulteriori informazioni su `storage tape library` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+tape+library["Riferimento al comando ONTAP"^].
