---
permalink: tape-backup/commands-manage-svm-scoped-ndmp-reference.html 
sidebar: sidebar 
keywords: commands, manage, svm, scoped, ndmp, mode, vserver, storage, virtual, machine 
summary: 'È possibile utilizzare i comandi ndmp dei servizi vserver per gestire NDMP su ciascuna macchina virtuale di storage (SVM, precedentemente nota come Vserver).' 
---
= Comandi per la gestione della modalità NDMP con ambito SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `vserver services ndmp` Comandi per la gestione di NDMP su ciascuna macchina virtuale di storage (SVM, in precedenza noto come Vserver).

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Abilitare il servizio NDMP
 a| 
`vserver services ndmp on`

[NOTE]
====
Il servizio NDMP deve essere sempre attivato su tutti i nodi di un cluster. È possibile attivare il servizio NDMP su un nodo utilizzando `system services ndmp on` comando. Per impostazione predefinita, il servizio NDMP è sempre attivato su un nodo.

====


 a| 
Disattiva servizio NDMP
 a| 
`vserver services ndmp off`



 a| 
Visualizzare la configurazione NDMP
 a| 
`vserver services ndmp show`



 a| 
Modificare la configurazione NDMP
 a| 
`vserver services ndmp modify`



 a| 
Visualizza la versione NDMP predefinita
 a| 
`vserver services ndmp version`



 a| 
Visualizza tutte le sessioni NDMP
 a| 
`vserver services ndmp status`



 a| 
Visualizza informazioni dettagliate su tutte le sessioni NDMP
 a| 
`vserver services ndmp probe`



 a| 
Terminare una sessione NDMP specificata
 a| 
`vserver services ndmp kill`



 a| 
Terminare tutte le sessioni NDMP
 a| 
`vserver services ndmp kill-all`



 a| 
Generare la password NDMP
 a| 
`vserver services ndmp generate-password`



 a| 
Visualizza lo stato dell'interno NDMP
 a| 
`vserver services ndmp extensions show`

Questo comando è disponibile a livello di privilegio avanzato.



 a| 
Modifica (attiva o disattiva) lo stato dell'interno NDMP
 a| 
`vserver services ndmp extensions modify`

Questo comando è disponibile a livello di privilegio avanzato.



 a| 
Avviare la registrazione per la sessione NDMP specificata
 a| 
`vserver services ndmp log start`

Questo comando è disponibile a livello di privilegio avanzato.



 a| 
Interrompere la registrazione per la sessione NDMP specificata
 a| 
`vserver services ndmp log stop`

Questo comando è disponibile a livello di privilegio avanzato.

|===
Per ulteriori informazioni su questi comandi, consultare le pagine man del `vserver services ndmp` comandi.
