---
permalink: tape-backup/dump-volume-move-concept.html 
sidebar: sidebar 
keywords: dump, works, volume, move, tape, backup, restore, storage, system 
summary: Le operazioni di backup e ripristino su nastro e lo spostamento del volume possono essere eseguite in parallelo fino al tentativo di cutover finale da parte del sistema di storage. Al termine di questa fase, non sono consentite nuove operazioni di backup e ripristino del nastro sul volume che viene spostato. Tuttavia, le operazioni correnti continuano a essere eseguite fino al completamento. 
---
= Come funziona il dump con lo spostamento del volume ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le operazioni di backup e ripristino su nastro e lo spostamento del volume possono essere eseguite in parallelo fino al tentativo di cutover finale da parte del sistema di storage. Al termine di questa fase, non sono consentite nuove operazioni di backup e ripristino del nastro sul volume che viene spostato. Tuttavia, le operazioni correnti continuano a essere eseguite fino al completamento.

La seguente tabella descrive il comportamento delle operazioni di backup e ripristino su nastro dopo l'operazione di spostamento del volume:

|===
| Se si eseguono operazioni di backup e ripristino su nastro in... | Quindi... 


 a| 
Modalità NDMP con ambito SVM (Storage Virtual Machine) quando L'estensione CAB è supportata dall'applicazione di backup
 a| 
È possibile continuare a eseguire operazioni di backup e ripristino su nastro incrementali su volumi di sola lettura/scrittura senza riconfigurare i criteri di backup.



 a| 
Modalità NDMP SVM-scoped quando l'estensione CAB non è supportata dall'applicazione di backup
 a| 
È possibile continuare a eseguire operazioni di backup e ripristino su nastro incrementali su volumi di sola lettura/scrittura se si esegue la migrazione della LIF configurata nel criterio di backup nel nodo che ospita l'aggregato di destinazione. In caso contrario, dopo lo spostamento del volume, è necessario eseguire un backup di riferimento prima di eseguire l'operazione di backup incrementale.

|===
[NOTE]
====
Quando si verifica uno spostamento del volume, se il volume appartenente a un SVM diverso sul nodo di destinazione ha lo stesso nome del volume spostato, non è possibile eseguire operazioni di backup incrementali del volume spostato.

====