---
permalink: tape-backup/dump-snapmirror-single-file-lun-restore-concept.html 
sidebar: sidebar 
keywords: dump, works, snapmirror, single, file, lun, restore, operation 
summary: 'Prima di eseguire operazioni di dump backup o ripristino su un volume su cui viene ripristinato un singolo file o LUN utilizzando la tecnologia SnapMirror, è necessario comprendere il funzionamento delle operazioni di dump con un"operazione di ripristino di un singolo file o LUN.' 
---
= Come funziona il dump con il ripristino di un singolo file o LUN SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire operazioni di dump backup o ripristino su un volume su cui viene ripristinato un singolo file o LUN utilizzando la tecnologia SnapMirror, è necessario comprendere il funzionamento delle operazioni di dump con un'operazione di ripristino di un singolo file o LUN.

Durante un'operazione di ripristino di un singolo file o LUN SnapMirror, l'i/o del client viene limitato al file o al LUN da ripristinare. Al termine dell'operazione di ripristino di un singolo file o LUN, la restrizione i/o sul file o sul LUN viene rimossa. Se viene eseguito un backup dump su un volume in cui viene ripristinato un singolo file o LUN, il file o LUN con restrizione i/o del client non viene incluso nel backup dump. In una successiva operazione di backup, il backup di questo file o LUN viene eseguito su nastro dopo la rimozione della restrizione i/O.

Non è possibile eseguire contemporaneamente un ripristino dump e un'operazione di ripristino di un singolo file o LUN SnapMirror sullo stesso volume.
