---
permalink: tape-backup/dump-storage-failover-arl-operations-concept.html 
sidebar: sidebar 
keywords: dump, workd, storage, failover, arl, operations, override, aggregate, relocation, takeover, giveback, cab, extension 
summary: 'Prima di eseguire operazioni di dump backup o ripristino, è necessario comprendere il funzionamento di queste operazioni con operazioni di failover dello storage (takeover e giveback) o di trasferimento aggregato (ARL). L"opzione -override-vetoes determina il comportamento del motore di dump durante un failover dello storage o un"operazione ARL.' 
---
= Come funziona il dump con il failover dello storage e le operazioni ARL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire operazioni di dump backup o ripristino, è necessario comprendere il funzionamento di queste operazioni con operazioni di failover dello storage (takeover e giveback) o di trasferimento aggregato (ARL). Il `-override-vetoes` L'opzione determina il comportamento del motore di dump durante un failover dello storage o un'operazione ARL.

Quando è in esecuzione un'operazione di dump backup o ripristino e il `-override-vetoes` l'opzione è impostata su `false`, Un failover dello storage avviato dall'utente o un'operazione ARL viene interrotta. Tuttavia, se il `–override-vetoes` l'opzione è impostata su `true`, Quindi, il failover dello storage o l'operazione ARL viene proseguita e l'operazione di backup o ripristino del dump viene interrotta. Quando un'operazione ARL o di failover dello storage viene avviata automaticamente dal sistema storage, un'operazione di backup o ripristino dump attivo viene sempre interrotta. Non è possibile riavviare le operazioni di backup e ripristino dump anche dopo il completamento delle operazioni ARL o di failover dello storage.



== Operazioni di dump quando è supportata l'estensione DELLA CABINA

Se l'applicazione di backup supporta l'estensione CAB, è possibile continuare a eseguire operazioni di backup e ripristino incrementali senza riconfigurare le policy di backup dopo un failover dello storage o un'operazione ARL.



== Operazioni di dump quando l'estensione DELLA CABINA non è supportata

Se l'applicazione di backup non supporta l'estensione CAB, è possibile continuare a eseguire operazioni di backup e ripristino del dump incrementale se si esegue la migrazione della LIF configurata nel criterio di backup nel nodo che ospita l'aggregato di destinazione. In caso contrario, dopo il failover dello storage e l'operazione ARL, è necessario eseguire un backup di riferimento prima di eseguire l'operazione di backup incrementale.

[NOTE]
====
Per le operazioni di failover dello storage, la LIF configurata nel criterio di backup deve essere migrata al nodo partner.

====
.Informazioni correlate
https://docs.netapp.com/us-en/ontap/high-availability/index.html["Alta disponibilità"]
