---
permalink: tape-backup/dump-restore-event-log-message-format-concept.html 
sidebar: sidebar 
keywords: event, dump, restore, log, message, 
summary: Per ogni evento di dump e ripristino, viene scritto un messaggio nel file di log di backup. 
---
= Formato del messaggio del registro eventi di dump e ripristino ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ogni evento di dump e ripristino, viene scritto un messaggio nel file di log di backup.

Il formato del messaggio di dump e ripristino del registro eventi è il seguente:

`_type timestamp identifier event (event_info)_`

Il seguente elenco descrive i campi nel formato dei messaggi del registro eventi:

* Ogni messaggio di registro inizia con uno degli indicatori di tipo descritti nella tabella seguente:
+
|===
| Tipo | Descrizione 


 a| 
log (registro)
 a| 
Registrazione dell'evento



 a| 
dmp
 a| 
Evento dump



 a| 
rst
 a| 
Evento di ripristino

|===
* `timestamp` mostra la data e l'ora dell'evento.
* Il `identifier` Il campo per un evento dump include il percorso dump e l'ID univoco per il dump. Il `identifier` il campo di un evento di ripristino utilizza solo il nome del percorso di destinazione di ripristino come identificatore univoco. I messaggi di evento correlati alla registrazione non includono un `identifier` campo.




== Scopri di più sugli eventi di registrazione ONTAP

Il campo evento di un messaggio che inizia con un registro specifica l'inizio di una registrazione o la fine di una registrazione.

Contiene uno degli eventi mostrati nella tabella seguente:

|===
| Evento | Descrizione 


 a| 
Start_Logging
 a| 
Indica l'inizio della registrazione o che la registrazione è stata riattivata dopo essere stata disattivata.



 a| 
Stop_Logging
 a| 
Indica che la registrazione è stata disattivata.

|===


== Scopri di più sugli eventi di dump ONTAP

Il campo dell'evento per un evento dump contiene un tipo di evento seguito da informazioni specifiche dell'evento tra parentesi.

La seguente tabella descrive gli eventi, le relative descrizioni e le relative informazioni che potrebbero essere registrate per un'operazione di dump:

|===
| Evento | Descrizione | Informazioni sull'evento 


 a| 
Inizio
 a| 
Viene avviato il dump NDMP
 a| 
Livello di dump e tipo di dump



 a| 
Fine
 a| 
Dump completati correttamente
 a| 
Quantità di dati elaborati



 a| 
Interrompere
 a| 
L'operazione viene annullata
 a| 
Quantità di dati elaborati



 a| 
Opzioni
 a| 
Vengono elencate le opzioni specificate
 a| 
Tutte le opzioni e i relativi valori, incluse le opzioni NDMP



 a| 
TAPE_Open
 a| 
Il nastro è aperto per la lettura/scrittura
 a| 
Il nome del nuovo dispositivo a nastro



 a| 
Tape_close
 a| 
Il nastro è chiuso per la lettura/scrittura
 a| 
Il nome del dispositivo a nastro



 a| 
Cambiamento di fase
 a| 
Un dump sta entrando in una nuova fase di elaborazione
 a| 
Il nome della nuova fase



 a| 
Errore
 a| 
Si è verificato un evento imprevisto in un dump
 a| 
Messaggio di errore



 a| 
Snapshot
 a| 
Viene creata o posizionata un'istantanea
 a| 
Il nome e l'ora dell'istantanea



 a| 
Base_dump
 a| 
È stata individuata una voce di dump di base nel metafile interno
 a| 
Il livello e il tempo del dump di base (solo per i dump incrementali)

|===


== Scopri di più sugli eventi di ripristino ONTAP

Il campo evento per un evento di ripristino contiene un tipo di evento seguito da informazioni specifiche dell'evento tra parentesi.

La seguente tabella fornisce informazioni sugli eventi, le relative descrizioni e le relative informazioni che è possibile registrare per un'operazione di ripristino:

|===
| Evento | Descrizione | Informazioni sull'evento 


 a| 
Inizio
 a| 
Ripristino NDMP avviato
 a| 
Livello di ripristino e tipo di ripristino



 a| 
Fine
 a| 
Ripristini completati correttamente
 a| 
Numero di file e quantità di dati elaborati



 a| 
Interrompere
 a| 
L'operazione viene annullata
 a| 
Numero di file e quantità di dati elaborati



 a| 
Opzioni
 a| 
Vengono elencate le opzioni specificate
 a| 
Tutte le opzioni e i relativi valori, incluse le opzioni NDMP



 a| 
TAPE_Open
 a| 
Il nastro è aperto per la lettura/scrittura
 a| 
Il nome del nuovo dispositivo a nastro



 a| 
Tape_close
 a| 
Il nastro è chiuso per la lettura/scrittura
 a| 
Il nome del dispositivo a nastro



 a| 
Cambiamento di fase
 a| 
Il ripristino sta entrando in una nuova fase di elaborazione
 a| 
Il nome della nuova fase



 a| 
Errore
 a| 
Il ripristino rileva un evento imprevisto
 a| 
Messaggio di errore

|===