---
permalink: tape-backup/dump-backup-concept.html 
sidebar: sidebar 
keywords: dump, backup, qtree, file, system, data 
summary: Un backup dump scrive i dati del file system da disco a nastro utilizzando un processo predefinito. È possibile eseguire il backup di un volume, di un qtree o di un sottostruttura che non è né un intero volume né un intero qtree. 
---
= Come funziona un backup dump con ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un backup dump scrive i dati del file system da disco a nastro utilizzando un processo predefinito. È possibile eseguire il backup di un volume, di un qtree o di un sottostruttura che non è né un intero volume né un intero qtree.

La seguente tabella descrive il processo utilizzato da ONTAP per eseguire il backup dell'oggetto indicato dal percorso di dump:

[cols="1,4"]
|===
| Fase | Azione 


 a| 
1
 a| 
Per un volume inferiore a quello completo o per i backup qtree completi, ONTAP attraversa le directory per identificare i file di cui eseguire il backup. Se si esegue il backup di un intero volume o qtree, ONTAP combina questa fase con la fase 2.



 a| 
2
 a| 
Per un backup completo di un volume o di un qtree completo, ONTAP identifica le directory nei volumi o qtree di cui eseguire il backup.



 a| 
3
 a| 
ONTAP scrive le directory su nastro.



 a| 
4
 a| 
ONTAP scrive i file su nastro.



 a| 
5
 a| 
ONTAP scrive le informazioni dell'ACL (se applicabili) su nastro.

|===
Il backup di dump utilizza uno snapshot dei dati per il backup. Pertanto, non è necessario portare il volume offline prima di iniziare il backup.

Il backup dump nomina ogni istantanea che crea come, dove `n` è un intero che `snapshot_for_backup.n` inizia da 0. Ogni volta che il backup dump crea uno snapshot, incrementa il numero intero di 1. Il valore intero viene reimpostato su 0 dopo il riavvio del sistema di storage. Al termine dell'operazione di backup, il motore di scarico elimina questa istantanea.

Quando ONTAP esegue più backup di dump contemporaneamente, il motore di dump crea più snapshot. Ad esempio, se ONTAP esegue due backup di dump contemporaneamente, nei volumi da cui viene eseguito il backup dei dati sono presenti i seguenti snapshot: `snapshot_for_backup.0` E `snapshot_for_backup.1`.

[NOTE]
====
Quando si esegue il backup da un'istantanea, il motore di scarico non crea un'istantanea aggiuntiva.

====


== Tipi di dati di cui il motore di dump esegue il backup

Il motore di dump consente di eseguire il backup dei dati su nastro per proteggersi da disastri o interruzioni del controller. Oltre al backup di oggetti dati come file, directory, qtree o interi volumi, il motore di dump può eseguire il backup di molti tipi di informazioni su ciascun file. Conoscere i tipi di dati di cui il motore di dump può eseguire il backup e le restrizioni da prendere in considerazione può aiutarti a pianificare il tuo approccio al disaster recovery.

Oltre a eseguire il backup dei dati nei file, il motore di dump può eseguire il backup delle seguenti informazioni relative a ciascun file, a seconda dei casi:

* UNIX GID, Owner UID e permessi del file
* Tempi di accesso, creazione e modifica UNIX
* Tipo di file
* Dimensione del file
* Nome DOS, attributi DOS e tempo di creazione
* Elenchi di controllo degli accessi (ACL) con 1,024 voci di controllo degli accessi (ACE)
* Informazioni sul qtree
* Percorsi di giunzione


I percorsi di giunzione vengono sottoposti a backup come collegamenti simbolici.

* LUN e LUN
+
È possibile eseguire il backup di un intero oggetto LUN; tuttavia, non è possibile eseguire il backup di un singolo file all'interno dell'oggetto LUN. Allo stesso modo, è possibile ripristinare un intero oggetto LUN ma non un singolo file all'interno del LUN.

+
[NOTE]
====
Il motore di dump esegue il backup dei cloni LUN come LUN indipendenti.

====
* File allineati alle macchine virtuali
+
Il backup dei file allineati alle macchine virtuali non è supportato nelle versioni precedenti a Data ONTAP 8.1.2.



[NOTE]
====
Quando un clone del LUN con snapshot viene passato da Data ONTAP in 7-Mode a ONTAP, diventa un LUN non coerente. Il motore di dump non esegue il backup di LUN incoerenti.

====
Quando si ripristinano i dati su un volume, l'i/o client viene limitato alle LUN da ripristinare. La restrizione LUN viene rimossa solo al termine dell'operazione di dump restore. Allo stesso modo, durante un'operazione di ripristino di un singolo file o LUN SnapMirror, l'i/o del client viene limitato sia ai file che ai LUN ripristinati. Questa restrizione viene rimossa solo al termine dell'operazione di ripristino del singolo file o del LUN. Se viene eseguito un backup dump su un volume su cui viene eseguita un'operazione di ripristino dump o un singolo file o LUN di SnapMirror, i file o le LUN con restrizione i/o del client non vengono inclusi nel backup. Questi file o LUN vengono inclusi in una successiva operazione di backup se la restrizione i/o del client viene rimossa.

[NOTE]
====
Un LUN eseguito su Data ONTAP 8.3 di cui è stato eseguito il backup su nastro può essere ripristinato solo alla versione 8.3 e successive e non a una release precedente. Se il LUN viene ripristinato a una release precedente, il LUN viene ripristinato come file.

====
Quando si esegue il backup di un volume secondario SnapVault o di una destinazione SnapMirror su nastro, viene eseguito il backup solo dei dati sul volume. Non viene eseguito il backup dei metadati associati. Pertanto, quando si tenta di ripristinare il volume, vengono ripristinati solo i dati di tale volume. Le informazioni sulle relazioni di SnapMirror del volume non sono disponibili nel backup e pertanto non vengono ripristinate.

Se si esegue il dump di un file che dispone solo delle autorizzazioni di Windows NT e lo si ripristina in un qtree o volume UNIX, il file ottiene le autorizzazioni UNIX predefinite per quel qtree o volume.

Se si esegue il dump di un file che dispone solo di autorizzazioni UNIX e lo si ripristina in un qtree o volume di stile NTFS, il file ottiene le autorizzazioni Windows predefinite per quel qtree o volume.

Altri dump e ripristini mantengono le autorizzazioni.

È possibile eseguire il backup dei file allineati alle macchine virtuali e di `vm-align-sector` opzione. Per ulteriori informazioni sui file allineati alle macchine virtuali, vedere link:../volumes/index.html["Gestione dello storage logico"].
