---
permalink: tape-backup/dump-restore-event-log-message-format-concept.html 
sidebar: sidebar 
keywords: event, dump, restore, log, message, 
summary: Per ogni evento di dump e ripristino, viene scritto un messaggio nel file di log di backup. 
---
= Panoramica del formato dei messaggi del registro eventi di dump e ripristino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ogni evento di dump e ripristino, viene scritto un messaggio nel file di log di backup.

Il formato del messaggio di dump e ripristino del registro eventi è il seguente:

`_type timestamp identifier event (event_info)_`

Il seguente elenco descrive i campi nel formato dei messaggi del registro eventi:

* Ogni messaggio di registro inizia con uno degli indicatori di tipo descritti nella tabella seguente:
+
|===
| Tipo | Descrizione 


 a| 
log (registro)
 a| 
Registrazione dell'evento



 a| 
dmp
 a| 
Evento dump



 a| 
rst
 a| 
Evento di ripristino

|===
* `timestamp` mostra la data e l'ora dell'evento.
* Il `identifier` Il campo per un evento dump include il percorso dump e l'ID univoco per il dump. Il `identifier` il campo di un evento di ripristino utilizza solo il nome del percorso di destinazione di ripristino come identificatore univoco. I messaggi di evento correlati alla registrazione non includono un `identifier` campo.

