---
permalink: tape-backup/generate-ndmp-password-users-task.html 
sidebar: sidebar 
keywords: generate, ndmp, specific, password, user, svm, storage, virtual, machine, login 
summary: 'Nella modalità NDMP con ambito SVM (Storage Virtual Machine), è necessario generare una password per un ID utente specifico. La password generata si basa sulla password di accesso effettiva per l"utente NDMP. Se la password di accesso effettiva viene modificata, è necessario generare nuovamente la password specifica di NDMP.' 
---
= Genera una password specifica NDMP per gli utenti ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nella modalità NDMP con ambito SVM (Storage Virtual Machine), è necessario generare una password per un ID utente specifico. La password generata si basa sulla password di accesso effettiva per l'utente NDMP. Se la password di accesso effettiva viene modificata, è necessario generare nuovamente la password specifica di NDMP.

.Fasi
. Utilizzare `vserver services ndmp generate-password` Per generare una password specifica per NDMP.
+
È possibile utilizzare questa password in qualsiasi operazione NDMP corrente o futura che richieda l'immissione della password.

+
[NOTE]
====
Dal contesto della macchina virtuale di storage (SVM, precedentemente noto come Vserver), è possibile generare password NDMP per gli utenti che appartengono solo a tale SVM.

====
+
Nell'esempio seguente viene illustrato come generare una password specifica per NDMP per un ID utente user1:

+
[listing]
----

cluster1::vserver services ndmp> generate-password -vserver vs1 -user user1

Vserver: vs1
User: user1
Password: jWZiNt57huPOoD8d
----
. Se si modifica la password con il normale account del sistema di storage, ripetere questa procedura per ottenere la nuova password specifica di NDMP.

