---
permalink: tape-backup/index.html 
sidebar: sidebar 
keywords: tape, backup, flexvol, volumes, overview, ndmp, network, data, management, protocol, sump, smtape 
summary: ONTAP supporta il backup e il ripristino su nastro attraverso il protocollo di gestione dei dati di rete. 
---
= Panoramica del backup su nastro dei volumi FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporta il backup e il ripristino su nastro attraverso il protocollo di gestione dei dati di rete (NDMP). NDMP consente di eseguire il backup dei dati nei sistemi storage direttamente su nastro, con un utilizzo efficiente della larghezza di banda della rete. ONTAP supporta motori di dump e SMTape per il backup su nastro.

È possibile eseguire un dump o un backup o ripristino SMTape utilizzando applicazioni di backup conformi a NDMP. È supportata solo la versione 4 di NDMP.



== Backup su nastro con dump

Dump è un backup basato su copia Snapshot in cui viene eseguito il backup dei dati del file system su nastro. Il motore di dump ONTAP esegue il backup su nastro di file, directory e le informazioni dell'elenco di controllo di accesso (ACL) applicabili. È possibile eseguire il backup di un intero volume, di un intero qtree o di un sottoalbero che non sia un intero volume o un intero qtree. Dump supporta backup baseline, differenziali e incrementali.



== Backup su nastro con SMTape

SMTape è una soluzione di disaster recovery basata su copia Snapshot di ONTAP che esegue il backup di blocchi di dati su nastro. È possibile utilizzare SMTape per eseguire backup dei volumi su nastri. Tuttavia, non è possibile eseguire un backup a livello di qtree o sottostruttura. SMTape supporta backup baseline, differenziali e incrementali.

A partire da ONTAP 9.13.1, il backup su nastro con SMTape supporta xref:../smbc/index.html[Continuità aziendale di SnapMirror].
