---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: 'È possibile gestire NDMP per SVM utilizzando le opzioni e i comandi NDMP. È possibile modificare le opzioni NDMP utilizzando il comando di modifica ndmp dei servizi vserver. Nella modalità NDMP con ambito SVM, l"autenticazione dell"utente è integrata con il meccanismo di controllo degli accessi basato sui ruoli.' 
---
= Gestire la modalità NDMP con ambito SVM per la panoramica dei volumi FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire NDMP per SVM utilizzando le opzioni e i comandi NDMP. È possibile modificare le opzioni NDMP utilizzando `vserver services ndmp modify` comando. Nella modalità NDMP con ambito SVM, l'autenticazione dell'utente è integrata con il meccanismo di controllo degli accessi basato sui ruoli.

È possibile aggiungere NDMP nell'elenco dei protocolli consentiti o non consentiti utilizzando `vserver modify` comando. Per impostazione predefinita, NDMP si trova nell'elenco dei protocolli consentiti. Se NDMP viene aggiunto all'elenco dei protocolli non consentiti, non è possibile stabilire sessioni NDMP.

È possibile controllare il tipo di LIF su cui viene stabilita una connessione dati NDMP utilizzando `-preferred-interface-role` opzione. Durante una connessione dati NDMP, NDMP sceglie un indirizzo IP appartenente al tipo LIF specificato da questa opzione. Se gli indirizzi IP non appartengono a nessuno di questi tipi LIF, non è possibile stabilire la connessione dati NDMP. Per ulteriori informazioni su `-preferred-interface-role` vedere le pagine man.

Per ulteriori informazioni su `vserver services ndmp modify` vedere le pagine man.

.Informazioni correlate
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Comandi per la gestione della modalità NDMP con ambito SVM]

xref:cluster-aware-backup-extension-concept.adoc[Qual è la funzione di Cluster Aware Backup Extension]

xref:svm-scoped-ndmp-mode-concept.adoc[Qual è la modalità NDMP con ambito SVM]

link:../system-admin/index.html["Amministrazione del sistema"]
