---
permalink: tape-backup/manage-node-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, node, scope, ndmp, mode, flexvol, volume, command, option, backup, restore 
summary: È possibile gestire NDMP a livello di nodo utilizzando le opzioni e i comandi NDMP. È possibile modificare le opzioni NDMP utilizzando il comando Options. Per accedere a un sistema di storage ed eseguire operazioni di backup e ripristino su nastro, è necessario utilizzare credenziali specifiche di NDMP. 
---
= Scopri come gestire la modalità NDMP con ambito nodo ONTAP per i volumi FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire NDMP a livello di nodo utilizzando le opzioni e i comandi NDMP. È possibile modificare le opzioni NDMP utilizzando `options` comando. Per accedere a un sistema di storage ed eseguire operazioni di backup e ripristino su nastro, è necessario utilizzare credenziali specifiche di NDMP.

Ulteriori informazioni su `options` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=options["Riferimento al comando ONTAP"^].



== Comandi per la gestione della modalità NDMP con ambito nodo ONTAP

È possibile utilizzare `system services ndmp` Comandi per gestire NDMP a livello di nodo. Alcuni di questi comandi sono deprecati e verranno rimossi in una release futura.

È possibile utilizzare i seguenti comandi NDMP solo a livello di privilegi avanzati:

* `system services ndmp service terminate`
* `system services ndmp service start`
* `system services ndmp service stop`
* `system services ndmp log start`
* `system services ndmp log stop`


|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Abilitare il servizio NDMP
 a| 
`system services ndmp on`*



 a| 
Disattiva servizio NDMP
 a| 
`system services ndmp off`*



 a| 
Visualizzare la configurazione NDMP
 a| 
`system services ndmp show`*



 a| 
Modificare la configurazione NDMP
 a| 
`system services ndmp modify`*



 a| 
Visualizza la versione NDMP predefinita
 a| 
`system services ndmp version`*



 a| 
Visualizzare la configurazione del servizio NDMP
 a| 
`system services ndmp service show`



 a| 
Modificare la configurazione del servizio NDMP
 a| 
`system services ndmp service modify`



 a| 
Visualizza tutte le sessioni NDMP
 a| 
`system services ndmp status`



 a| 
Visualizza informazioni dettagliate su tutte le sessioni NDMP
 a| 
`system services ndmp probe`



 a| 
Terminare la sessione NDMP specificata
 a| 
`system services ndmp kill`



 a| 
Terminare tutte le sessioni NDMP
 a| 
`system services ndmp kill-all`



 a| 
Modificare la password NDMP
 a| 
`system services ndmp password`*



 a| 
Attiva la modalità NDMP con ambito nodo
 a| 
`system services ndmp node-scope-mode on`*



 a| 
Disattiva la modalità NDMP con ambito nodo
 a| 
`system services ndmp node-scope-mode off`*



 a| 
Visualizza lo stato della modalità NDMP con ambito nodo
 a| 
`system services ndmp node-scope-mode status`*



 a| 
Terminare con forza tutte le sessioni NDMP
 a| 
`system services ndmp service terminate`



 a| 
Avviare il daemon del servizio NDMP
 a| 
`system services ndmp service start`



 a| 
Arrestare il daemon del servizio NDMP
 a| 
`system services ndmp service stop`



 a| 
Avviare la registrazione per la sessione NDMP specificata
 a| 
`system services ndmp log start`*



 a| 
Interrompere la registrazione per la sessione NDMP specificata
 a| 
`system services ndmp log stop`*

|===
* Questi comandi sono deprecati e verranno rimossi in una release futura.


Ulteriori informazioni su `system services ndmp` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+ndmp["Riferimento al comando ONTAP"^].



== Autenticazione dell'utente in una modalità NDMP con ambito nodo

Nella modalità NDMP con ambito nodo, è necessario utilizzare credenziali specifiche NDMP per accedere a un sistema di storage per eseguire operazioni di backup e ripristino su nastro.

L'ID utente predefinito è "`root`". Prima di utilizzare NDMP su un nodo, è necessario assicurarsi di modificare la password NDMP predefinita associata all'utente NDMP. È inoltre possibile modificare l'ID utente NDMP predefinito.

.Informazioni correlate
xref:commands-manage-node-scoped-ndmp-reference.adoc[Comandi per la gestione della modalità NDMP con ambito nodo]

xref:node-scoped-ndmp-mode-concept.adoc[Qual è la modalità NDMP con ambito nodo]
