---
permalink: tape-backup/ndmp-backup-policy-affected-adb-concept.html 
sidebar: sidebar 
keywords: ndmp, backup, policy, adb, aggregate, balancer, analysis, user, statistics, usage, percentage 
summary: 'Quando il bilanciamento automatico dei dati (ADB) è attivato, il bilanciamento analizza le statistiche di utilizzo degli aggregati per identificare l"aggregato che ha superato la percentuale di utilizzo ad alta soglia configurata.' 
---
= Come viene influenzata una policy di backup ONTAP NDMP durante ADB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando il bilanciamento automatico dei dati (ADB) è attivato, il bilanciamento analizza le statistiche di utilizzo degli aggregati per identificare l'aggregato che ha superato la percentuale di utilizzo ad alta soglia configurata.

Dopo aver identificato l'aggregato che ha superato la soglia, il bilanciamento identifica un volume che può essere spostato in aggregati che risiedono in un altro nodo del cluster e tenta di spostare tale volume. Questa situazione influisce sul criterio di backup configurato per questo volume perché se l'applicazione di gestione dei dati (DMA) non è a conoscenza DEL CAB, l'utente deve riconfigurare il criterio di backup ed eseguire l'operazione di backup di riferimento.

[NOTE]
====
Se il DMA è in GRADO di riconoscere IL CAB e il criterio di backup è stato configurato utilizzando un'interfaccia specifica, ADB non viene interessato.

====