---
permalink: tape-backup/node-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: node, scope, ndmp, mode, tape, backup, resotre, operations, upgrade, data 
summary: 'Nella modalità NDMP con ambito nodo, è possibile eseguire operazioni di backup e ripristino su nastro a livello di nodo. La modalità operativa NDMP utilizzata in Data ONTAP 8.2 continuerà a essere mantenuta dopo l"aggiornamento dalla versione 8.2 alla 8.3.' 
---
= Qual è la modalità NDMP con ambito nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nella modalità NDMP con ambito nodo, è possibile eseguire operazioni di backup e ripristino su nastro a livello di nodo. La modalità operativa NDMP utilizzata in Data ONTAP 8.2 continuerà a essere mantenuta dopo l'aggiornamento dalla versione 8.2 alla 8.3.

Nella modalità NDMP con ambito nodo, è possibile eseguire operazioni di backup e ripristino su nastro su un nodo proprietario del volume. Per eseguire queste operazioni, è necessario stabilire connessioni di controllo NDMP su un LIF ospitato sul nodo proprietario dei dispositivi a nastro o volume.

[NOTE]
====
Questa modalità è obsoleta e verrà rimossa in una release futura.

====
.Informazioni correlate
xref:manage-node-scoped-ndmp-mode-concept.adoc[Gestione della modalità NDMP con ambito nodo per volumi FlexVol]
