---
permalink: tape-backup/options-ndmpcopy-command-reference.html 
sidebar: sidebar 
keywords: ndmpcopy, command, tranfer, data, nodeshell 
summary: È necessario conoscere le opzioni disponibili per il comando ndmpcopy per il trasferimento dei dati. 
---
= Opzioni per il comando ndmpcopy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere le opzioni disponibili per `ndmpcopy` comando nodeshell per trasferire correttamente i dati.

La seguente tabella elenca le opzioni disponibili. Per ulteriori informazioni, consultare `ndmpcopy` pagine man disponibili attraverso il nodeshell.

|===
| Opzione | Descrizione 


 a| 
`-sa` `username`:[`password`]
 a| 
Questa opzione consente di impostare il nome utente e la password per l'autenticazione di origine per la connessione al sistema di storage di origine. Si tratta di un'opzione obbligatoria.

Per un utente senza privilegi di amministratore, è necessario specificare la password specifica NDMP generata dal sistema dell'utente. La password generata dal sistema è obbligatoria per gli utenti admin e non admin.



 a| 
`-da` `username`:[`password`]
 a| 
Questa opzione consente di impostare il nome utente e la password di autenticazione di destinazione per la connessione al sistema di storage di destinazione. Si tratta di un'opzione obbligatoria.



 a| 
`-st` {`md5`|`text`}
 a| 
Questa opzione consente di impostare il tipo di autenticazione di origine da utilizzare durante la connessione al sistema di storage di origine. Si tratta di un'opzione obbligatoria, pertanto l'utente deve fornire `text` oppure `md5` opzione.



 a| 
`-dt` {`md5`|`text`}
 a| 
Questa opzione consente di impostare il tipo di autenticazione di destinazione da utilizzare durante la connessione al sistema di storage di destinazione.



 a| 
`-l`
 a| 
Questa opzione imposta il livello di dump utilizzato per il trasferimento sul valore specificato di level.Valid Values are `0`, `1`, a. `9`, dove `0` indica un trasferimento completo e. `1` a. `9` specifica un trasferimento incrementale. L'impostazione predefinita è `0`.



 a| 
`-d`
 a| 
Questa opzione consente la generazione di messaggi di log di debug ndmpcopy. I file di log di debug ndmpcopy si trovano in `/mroot/etc/log` volume root. I nomi dei file di log di debug ndmpcopy si trovano in `ndmpcopy.yyyymmdd` formato.



 a| 
`-f`
 a| 
Questa opzione attiva la modalità forzata. Questa modalità consente di sovrascrivere i file di sistema in `/etc` Nella directory principale del volume 7-Mode.



 a| 
`-h`
 a| 
Questa opzione consente di stampare il messaggio della guida.



 a| 
`-p`
 a| 
Questa opzione richiede di inserire la password per l'autorizzazione di origine e destinazione. Questa password sovrascrive la password specificata per `-sa` e. `-da` opzioni.

[NOTE]
====
È possibile utilizzare questa opzione solo quando il comando è in esecuzione in una console interattiva.

====


 a| 
`-exclude`
 a| 
Questa opzione esclude i file o le directory specificati dal percorso specificato per il trasferimento dei dati. Il valore può essere un elenco separato da virgole di nomi di directory o file come `*.pst` oppure `*.txt`.

|===