---
permalink: tape-backup/remove-tape-aliases-task.html 
sidebar: sidebar 
keywords: remove, tape, aliases, clear, command, drive, medium, changer 
summary: 'È possibile rimuovere gli alias utilizzando il comando di cancellazione alias del nastro di storage quando gli alias persistenti non sono più necessari per un"unità a nastro o un caricatore di supporti.' 
---
= Rimuovere gli alias del nastro da un'unità nastro o da un cambia-supporto per il backup su nastro ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere gli alias utilizzando `storage tape alias clear` comando quando gli alias persistenti non sono più necessari per un'unità a nastro o un dispositivo di sostituzione del supporto.

.Fasi
. Rimuovere un alias da un'unità a nastro o da un caricatore di supporti utilizzando `storage tape alias clear` comando.
+
Ulteriori informazioni su `storage tape alias clear` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-clear.html["Riferimento al comando ONTAP"^].

+
Il seguente comando rimuove gli alias di tutte le unità a nastro specificando l'ambito dell'operazione di cancellazione alias in `tape`:

+
[listing]
----
cluster-01::>storage tape alias clear -node cluster-01 -clear-scope tape
----


.Al termine
Se si esegue un'operazione di backup o ripristino su nastro utilizzando NDMP, dopo aver rimosso un alias da un'unità a nastro o da un caricatore di supporti, è necessario assegnare un nuovo nome alias all'unità a nastro o al caricatore di supporti per continuare l'accesso al dispositivo a nastro.

.Informazioni correlate
* xref:assign-tape-aliases-concept.adoc[Che cos'è l'aliasing su nastro]
* xref:assign-tape-aliases-task.adoc[Assegnazione degli alias del nastro]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-clear.html["alias nastro di archiviazione chiaro"^]

