---
permalink: tape-backup/restore-7-mode-clustered-ontap-concept.html 
sidebar: sidebar 
keywords: tape, backup, restore, support, data, 7 mode, storage, system 
summary: È possibile ripristinare i dati di cui è stato eseguito il backup da un sistema storage in 7-Mode o in esecuzione su ONTAP in un sistema storage in 7-Mode o in esecuzione su ONTAP. 
---
= Supporto di backup e ripristino su nastro tra Data ONTAP in 7-Mode e ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare i dati di cui è stato eseguito il backup da un sistema storage in 7-Mode o in esecuzione su ONTAP in un sistema storage in 7-Mode o in esecuzione su ONTAP.

Le seguenti operazioni di backup e ripristino su nastro sono supportate tra Data ONTAP in 7-Mode e ONTAP:

* Backup di un volume 7-Mode su un'unità a nastro collegata a un sistema storage che esegue ONTAP
* Backup di un volume ONTAP su un'unità a nastro collegata a un sistema 7-Mode
* Ripristino dei dati di backup di un volume 7-Mode da un'unità a nastro collegata a un sistema storage che esegue ONTAP
* Ripristino dei dati di backup di un volume ONTAP da un'unità a nastro collegata a un sistema 7-Mode
* Ripristino di un volume 7-Mode su un volume ONTAP
+
[NOTE]
====
....
-   A 7-Mode LUN is restored as a LUN on an ONTAP volume.
-   You should retain the ONTAP LUN identifiers when restoring a 7-Mode LUN to an existing ONTAP LUN.
....
====
* Ripristino di un volume ONTAP su un volume 7-Mode
+
[NOTE]
====
Un LUN ONTAP viene ripristinato come file normale su un volume 7-Mode.

====

