---
permalink: tape-backup/scalability-limits-ndmp-sessions-reference.html 
sidebar: sidebar 
keywords: scalability, limits, ndmp, sessions, memory, capacities, maximum 
summary: È necessario conoscere il numero massimo di sessioni NDMP che è possibile stabilire simultaneamente su sistemi storage con capacità di memoria di sistema diverse. Questo numero massimo dipende dalla memoria di sistema di un sistema di storage. 
---
= Limiti di scalabilità per le sessioni NDMP in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere il numero massimo di sessioni NDMP che è possibile stabilire simultaneamente su sistemi storage con capacità di memoria di sistema diverse. Questo numero massimo dipende dalla memoria di sistema di un sistema di storage.

I limiti indicati nella seguente tabella si riferiscono al server NDMP. I limiti indicati nella sezione "`Slimiti di calabilità per le sessioni di backup e ripristino dump`" si riferiscono alla sessione di dump e ripristino.

xref:scalability-limits-dump-backup-restore-sessions-concept.adoc[Limiti di scalabilità per sessioni di dump backup e ripristino]

|===
| Memoria di sistema di un sistema storage | Numero massimo di sessioni NDMP 


 a| 
Meno di 16 GB
 a| 
8



 a| 
Superiore o uguale a 16 GB ma inferiore a 24 GB
 a| 
20



 a| 
Maggiore o uguale a 24 GB
 a| 
36

|===
È possibile ottenere la memoria di sistema del proprio sistema di archiviazione utilizzando il `sysconfig -a` comando (disponibile tramite la nodeshell). Ulteriori informazioni su `sysconfig -a` nella link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["Riferimento al comando ONTAP"^].
