---
permalink: tape-backup/smtape-capabilities-concept.html 
sidebar: sidebar 
keywords: smtap, capabilities, snapshot, copy, preservation, deduplication, compression, restored, volume, backup, restore 
summary: Le funzionalità SMTape, come backup di copie Snapshot, backup incrementali e differenziali, conservazione delle funzionalità di deduplica e compressione sui volumi ripristinati e seeding dei nastri, consentono di ottimizzare le operazioni di backup e ripristino dei nastri. 
---
= Funzionalità SMTape
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le funzionalità SMTape, come backup di copie Snapshot, backup incrementali e differenziali, conservazione delle funzionalità di deduplica e compressione sui volumi ripristinati e seeding dei nastri, consentono di ottimizzare le operazioni di backup e ripristino dei nastri.

SMTape offre le seguenti funzionalità:

* Offre una soluzione di disaster recovery
* Consente backup incrementali e differenziali
* Esegue il backup delle copie Snapshot
* Consente il backup e il ripristino dei volumi deduplicati e preserva la deduplica sui volumi ripristinati
* Esegue il backup dei volumi compressi e mantiene la compressione sui volumi ripristinati
* Consente il seeding dei nastri


SMTape supporta il fattore di blocco in multipli di 4 KB, nell'intervallo da 4 KB a 256 KB.

[NOTE]
====
È possibile ripristinare i dati su volumi creati solo in due release principali consecutive di ONTAP.

====