---
permalink: tape-backup/smtape-storage-failover-arl-concept.html 
sidebar: sidebar 
keywords: smtape, storage, failover, arl, operation, aggregate, relocation 
summary: 'Prima di eseguire operazioni di backup o ripristino SMTape, è necessario comprendere il funzionamento di queste operazioni con operazioni di failover dello storage (takeover e giveback) o di riposizionamento degli aggregati (ARL). L"opzione -override-vetoes determina il comportamento del motore SMTape durante un failover dello storage o un"operazione ARL.' 
---
= Come funziona SMTape con il failover dell'archiviazione ONTAP e le operazioni ARL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire operazioni di backup o ripristino SMTape, è necessario comprendere il funzionamento di queste operazioni con operazioni di failover dello storage (takeover e giveback) o di riposizionamento degli aggregati (ARL). Il `-override-vetoes` L'opzione determina il comportamento del motore SMTape durante un'operazione ARL o di failover dello storage.

Quando è in esecuzione un'operazione di backup o ripristino SMTape e il `-override-vetoes` l'opzione è impostata su `false`, Un failover dello storage avviato dall'utente o un'operazione ARL viene interrotta e l'operazione di backup o ripristino viene completata. Se l'applicazione di backup supporta l'estensione CAB, è possibile continuare a eseguire operazioni di backup e ripristino SMTape incrementali senza riconfigurare i criteri di backup. Tuttavia, se il `–override-vetoes` l'opzione è impostata su `true`, Quindi il failover dello storage o l'operazione ARL viene proseguita e l'operazione di backup o ripristino SMTape viene interrotta.

.Informazioni correlate
link:../networking/networking_reference.html["Gestione della rete"]

link:../high-availability/index.html["Alta disponibilità"]
