---
permalink: tape-backup/smtape-volume-move-concept.html 
sidebar: sidebar 
keywords: smtape, backup, operation, volume, move, cutover, phase 
summary: Le operazioni di backup SMTape e le operazioni di spostamento del volume possono essere eseguite in parallelo fino a quando il sistema storage non tenta la fase di cutover finale. Dopo questa fase, non è possibile eseguire nuove operazioni di backup SMTape sul volume che viene spostato. Tuttavia, le operazioni correnti continuano a essere eseguite fino al completamento. 
---
= Funzionamento di SMTape con lo spostamento del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le operazioni di backup SMTape e le operazioni di spostamento del volume possono essere eseguite in parallelo fino a quando il sistema storage non tenta la fase di cutover finale. Dopo questa fase, non è possibile eseguire nuove operazioni di backup SMTape sul volume che viene spostato. Tuttavia, le operazioni correnti continuano a essere eseguite fino al completamento.

Prima di avviare la fase di cutover di un volume, l'operazione di spostamento del volume verifica la presenza di operazioni di backup SMTape attive sullo stesso volume. Se sono presenti operazioni di backup SMTape attive, l'operazione di spostamento del volume passa a uno stato di cutover rinviato e consente il completamento delle operazioni di backup SMTape. Una volta completate queste operazioni di backup, è necessario riavviare manualmente l'operazione di spostamento del volume.

Se l'applicazione di backup supporta l'estensione CAB, è possibile continuare a eseguire operazioni di backup e ripristino su nastro incrementali su volumi di sola lettura/scrittura senza riconfigurare i criteri di backup.

Le operazioni di ripristino di base e di spostamento del volume non possono essere eseguite contemporaneamente; tuttavia, il ripristino incrementale può essere eseguito in parallelo con le operazioni di spostamento del volume, con un comportamento simile a quello delle operazioni di backup SMTape durante le operazioni di spostamento del volume.

.Informazioni correlate
link:../concepts/index.html["Concetti di ONTAP"]
