---
permalink: tape-backup/supported-number-simultaneous-tape-devices-concept.html 
sidebar: sidebar 
keywords: supported, number, simultaneoud, tape, devices, fibre, channel, scsi, sas, attachments, router, devices 
summary: 'ONTAP supporta un massimo di 64 connessioni simultanee a unità a nastro, 16 media changer e 16 dispositivi bridge o router per ciascun sistema storage (per nodo) in qualsiasi combinazione di collegamenti Fibre Channel, SCSI o SAS.' 
---
= Numero supportato di dispositivi a nastro ONTAP simultanei
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporta un massimo di 64 connessioni simultanee a unità a nastro, 16 media changer e 16 dispositivi bridge o router per ciascun sistema storage (per nodo) in qualsiasi combinazione di collegamenti Fibre Channel, SCSI o SAS.

I dischi a nastro o i media changer possono essere dispositivi in librerie di nastri fisiche o virtuali o dispositivi standalone.

[NOTE]
====
Sebbene un sistema storage sia in grado di rilevare 64 connessioni a unità a nastro, il numero massimo di sessioni di backup e ripristino che possono essere eseguite contemporaneamente dipende dai limiti di scalabilità del motore di backup.

====
.Informazioni correlate
xref:scalability-limits-dump-backup-restore-sessions-concept.adoc[Limiti di scalabilità per sessioni di dump backup e ripristino]
