---
permalink: tape-backup/supported-ndmp-authentication-methods-concept.html 
sidebar: sidebar 
keywords: ndmp, authentication, method, requests, plaintext, challenge 
summary: 'È possibile specificare un metodo di autenticazione per consentire le richieste di connessione NDMP. ONTAP supporta due metodi per autenticare l"accesso NDMP a un sistema storage: Testo normale e sfida.' 
---
= Metodi di autenticazione NDMP supportati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile specificare un metodo di autenticazione per consentire le richieste di connessione NDMP. ONTAP supporta due metodi per autenticare l'accesso NDMP a un sistema storage: Testo normale e sfida.

Nella modalità NDMP con ambito nodo, sia challenge che plaintext sono attivati per impostazione predefinita. Tuttavia, non è possibile disattivare la sfida. È possibile attivare e disattivare il testo non crittografato. Nel metodo di autenticazione non crittografato, la password di accesso viene trasmessa come testo non crittografato.

Nella modalità NDMP con ambito SVM (Storage Virtual Machine), per impostazione predefinita il metodo di autenticazione è un problema. A differenza della modalità NDMP con ambito di nodo, in questa modalità è possibile attivare e disattivare sia i metodi di autenticazione a testo normale che quelli di verifica.

.Informazioni correlate
xref:user-authentication-node-scoped-ndmp-mode-concept.adoc[Autenticazione dell'utente in una modalità NDMP con ambito nodo]

xref:user-authentication-svm-scoped-ndmp-mode-concept.adoc[Autenticazione dell'utente in modalità NDMP con ambito SVM]
