---
permalink: tape-backup/tape-device-name-format-concept.html 
sidebar: sidebar 
keywords: tape, device, name, format, rewind, type, alias, compression 
summary: 'A ciascuna periferica a nastro è associato un nome che viene visualizzato in un formato definito. Il formato include informazioni sul tipo di dispositivo, sul tipo di riavvolgimento, sull"alias e sul tipo di compressione.' 
---
= Formato del nome di un dispositivo a nastro ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A ciascuna periferica a nastro è associato un nome che viene visualizzato in un formato definito. Il formato include informazioni sul tipo di dispositivo, sul tipo di riavvolgimento, sull'alias e sul tipo di compressione.

Il formato del nome di un dispositivo a nastro è il seguente:

`rewind_type` `st` `alias_number` `compression_type`

`rewind_type` è il tipo di riavvolgimento.

Il seguente elenco descrive i diversi valori del tipo di riavvolgimento:

* *r*
+
ONTAP riavvolge il nastro al termine della scrittura del file.

* *nr*
+
ONTAP non riavvolge il nastro al termine della scrittura del file. È necessario utilizzare questo tipo di riavvolgimento quando si desidera scrivere più file su nastro sullo stesso nastro.

* *ur*
+
Questo è il tipo di riavvolgimento di scaricamento/ricarica. Quando si utilizza questo tipo di riavvolgimento, la libreria di nastri scarica il nastro quando raggiunge la fine di un file di nastro, quindi carica il nastro successivo, se presente.

+
È necessario utilizzare questo tipo di riavvolgimento solo nei seguenti casi:

+
** L'unità a nastro associata a questo dispositivo si trova in una libreria di nastri o in un caricatore di supporti che si trova in modalità di libreria.
** L'unità a nastro associata a questo dispositivo è collegata a un sistema di storage.
** Nella sequenza di nastri della libreria definita per questa unità a nastro sono disponibili nastri sufficienti per l'operazione che si sta eseguendo.




[NOTE]
====
Se si registra un nastro utilizzando un dispositivo senza riavvolgimento, è necessario riavvolgere il nastro prima di leggerlo.

====
`st` è la designazione standard per un'unità a nastro.

`alias_number` È l'alias assegnato da ONTAP all'unità a nastro. Quando ONTAP rileva una nuova unità a nastro, ONTAP assegna un alias all'unità a nastro.

`compression_type` è un codice specifico del disco per la densità dei dati sul nastro e il tipo di compressione.

L'elenco seguente descrive i vari valori per `compression_type`:

* *a*
+
Compressione massima

* *h*
+
Compressione elevata

* *m*
+
Compressione media

* *l*
+
Compressione bassa



.Esempi
`nrst0a` specifica un dispositivo no-rewind sull'unità a nastro 0 utilizzando la compressione più elevata.

.Esempio di un elenco di dispositivi a nastro
L'esempio seguente mostra i dispositivi a nastro associati a HP Ultrium 2-SCSI:

[listing]
----

           Tape drive (fc202_6:2.126L1)  HP      Ultrium 2-SCSI
    rst0l  -  rewind device,        format is: HP (200GB)
    nrst0l -  no rewind device,     format is: HP (200GB)
    urst0l -  unload/reload device, format is: HP (200GB)
    rst0m  -  rewind device,        format is: HP (200GB)
    nrst0m -  no rewind device,     format is: HP (200GB)
    urst0m -  unload/reload device, format is: HP (200GB)
    rst0h  -  rewind device,        format is: HP (200GB)
    nrst0h -  no rewind device,     format is: HP (200GB)
    urst0h -  unload/reload device, format is: HP (200GB)
    rst0a  -  rewind device,        format is: HP (400GB w/comp)
    nrst0a -  no rewind device,     format is: HP (400GB w/comp)
    urst0a -  unload/reload device, format is: HP (400GB w/comp)
----
L'elenco seguente descrive le abbreviazioni dell'esempio precedente:

* GB--Gigabyte; questa è la capacità del nastro.
* w/comp--con compressione; indica la capacità del nastro con compressione.

