---
permalink: tape-backup/tape-devices-concept.html 
sidebar: sidebar 
keywords: tape, device, representation, combination, rewind, type, compression, capability, drive 
summary: 'Un dispositivo a nastro è una rappresentazione di un"unità a nastro. Si tratta di una combinazione specifica di tipo di rewind e funzionalità di compressione di un"unità a nastro.' 
---
= Panoramica dei dispositivi a nastro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un dispositivo a nastro è una rappresentazione di un'unità a nastro. Si tratta di una combinazione specifica di tipo di rewind e funzionalità di compressione di un'unità a nastro.

Viene creato un dispositivo a nastro per ogni combinazione di tipo di rewind e funzionalità di compressione. Pertanto, un'unità a nastro o una libreria a nastro possono essere associati a diversi dispositivi a nastro. È necessario specificare un dispositivo a nastro per spostare, scrivere o leggere i nastri.

Quando si installa un'unità a nastro o una libreria di nastri su un sistema di storage, ONTAP crea dispositivi a nastro associati all'unità a nastro o alla libreria di nastri.

ONTAP rileva le unità a nastro e le librerie a nastro e assegna loro numeri logici e dispositivi a nastro. ONTAP rileva le librerie e le unità a nastro Fibre Channel, SAS e SCSI parallele quando sono collegate alle porte di interfaccia. ONTAP rileva questi dischi quando le interfacce sono attivate.
