---
permalink: tape-backup/types-data-dump-engine-restores-concept.html 
sidebar: sidebar 
keywords: types, data, dump, engine, restores, disaster, controller, disruption, file, attribute 
summary: 'Quando si verifica un"interruzione del controller o di un"emergenza, il motore di dump offre diversi metodi per ripristinare tutti i dati di cui è stato eseguito il backup, dai singoli file agli attributi dei file, alle intere directory. Conoscere i tipi di dati ripristinati dal motore di dump e quando utilizzare il metodo di recovery può contribuire a ridurre al minimo i tempi di inattività.' 
---
= Tipi di dati ripristinati dal motore di dump
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si verifica un'interruzione del controller o di un'emergenza, il motore di dump offre diversi metodi per ripristinare tutti i dati di cui è stato eseguito il backup, dai singoli file agli attributi dei file, alle intere directory. Conoscere i tipi di dati ripristinati dal motore di dump e quando utilizzare il metodo di recovery può contribuire a ridurre al minimo i tempi di inattività.

È possibile ripristinare i dati in una LUN mappata online. Tuttavia, le applicazioni host non possono accedere a questo LUN fino al completamento dell'operazione di ripristino. Una volta completata l'operazione di ripristino, la cache host dei dati LUN deve essere svuotata per garantire la coerenza con i dati ripristinati.

Il motore di dump può recuperare i seguenti dati:

* Contenuto di file e directory
* Permessi di file UNIX
* ACL
+
Se si ripristina un file che dispone solo delle autorizzazioni di file UNIX su un qtree o volume NTFS, il file non dispone di ACL Windows NT. Il sistema di storage utilizza solo le autorizzazioni di file UNIX per questo file fino a quando non viene creato un ACL di Windows NT.

+
[NOTE]
====
Se si ripristinano gli ACL di cui è stato eseguito il backup dai sistemi storage che eseguono Data ONTAP 8.2 ai sistemi storage che eseguono Data ONTAP 8.1.x e versioni precedenti con un limite ACE inferiore a 1,024, viene ripristinato un ACL predefinito.

====
* Informazioni sul qtree
+
Le informazioni qtree vengono utilizzate solo se un qtree viene ripristinato nella directory principale di un volume. Le informazioni qtree non vengono utilizzate se un qtree viene ripristinato in una directory inferiore, ad esempio `/vs1/vol1/subdir/lowerdir`e cessa di essere un qtree.

* Tutti gli altri attributi di file e directory
* Flussi Windows NT
* LUN
+
** Un LUN deve essere ripristinato a livello di volume o qtree per rimanere come LUN.
+
Se viene ripristinato in una directory, viene ripristinato come file perché non contiene metadati validi.

** Un LUN 7-Mode viene ripristinato come LUN su un volume ONTAP.


* È possibile ripristinare un volume 7-Mode su un volume ONTAP.
* I file allineati alle macchine virtuali ripristinati in un volume di destinazione ereditano le proprietà di allineamento delle macchine virtuali del volume di destinazione.
* Il volume di destinazione per un'operazione di ripristino potrebbe avere file con blocchi obbligatori o di avviso.
+
Durante l'esecuzione dell'operazione di ripristino su un volume di destinazione di questo tipo, il motore di dump ignora questi blocchi.


