---
permalink: tape-backup/workflow-task.html 
sidebar: sidebar 
keywords: perform, tape, backup, restore, flexvol, volume, ndmp, backup, application 
summary: 'È possibile eseguire operazioni di backup e ripristino su nastro utilizzando un"applicazione di backup abilitata per NDMP.' 
---
= Flusso di lavoro di backup e ripristino su nastro in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire operazioni di backup e ripristino su nastro utilizzando un'applicazione di backup abilitata per NDMP.

.A proposito di questa attività
Il flusso di lavoro di backup e ripristino su nastro offre una panoramica delle attività coinvolte nell'esecuzione delle operazioni di backup e ripristino su nastro. Per informazioni dettagliate sull'esecuzione di un'operazione di backup e ripristino, consultare la documentazione dell'applicazione di backup.

.Fasi
. Configurare una libreria di nastri scegliendo una topologia a nastro supportata da NDMP.
. Abilitare i servizi NDMP sul sistema storage.
+
È possibile attivare i servizi NDMP a livello di nodo o di SVM (Storage Virtual Machine). Questo dipende dalla modalità NDMP in cui si sceglie di eseguire l'operazione di backup e ripristino su nastro.

. Utilizza le opzioni NDMP per gestire NDMP sul tuo sistema storage.
+
È possibile utilizzare le opzioni NDMP a livello di nodo o SVM. Questo dipende dalla modalità NDMP in cui si sceglie di eseguire l'operazione di backup e ripristino su nastro.

+
Puoi modificare le opzioni NDMP a livello di nodo utilizzando il `system services ndmp modify` comando e a livello SVM utilizzando il comando `vserver services ndmp modify`. Ulteriori informazioni su `system services ndmp modify`and `vserver services ndmp modify` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=services+ndmp+modify["Riferimento al comando ONTAP"^].

. Eseguire un'operazione di backup o ripristino su nastro utilizzando un'applicazione di backup abilitata per NDMP.
+
ONTAP supporta motori di dump e SMTape per backup e ripristino su nastro.

+
Per ulteriori informazioni sull'utilizzo dell'applicazione di backup (denominata anche _applicazioni di gestione dei dati_ o _DMA_) per eseguire operazioni di backup o ripristino, consultare la documentazione dell'applicazione di backup.



.Informazioni correlate
xref:common-ndmp-topologies-reference.adoc[Topologie comuni di backup su nastro NDMP]

xref:data-backup-dump-concept.adoc[Comprendere il motore di dump per i volumi FlexVol]
