---
sidebar: sidebar 
permalink: software_setup/configure-protocols.html 
keywords: install, installing, cluster, set up, setup, configure, disk, data ports, guided setup, local tiers, aggregate, vserver, volume, configuring ONTAP on a new cluster, configuring a new cluster, assign a node-management IP address, node, DNS server, host name, hostname, NTP server, synchronize time, create a local tier, configure protocol, SSD, provision storage, add LUN, add volume, add namespace, volume, vserver, configure ONTAP on a new cluster, configuration 
summary: System Manager offre un workflow semplice e semplice per la configurazione del cluster e dello storage. 
---
= Configurare i protocolli sul cluster ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A seconda delle licenze attivate sul cluster, è possibile attivare i protocolli desiderati sul cluster. Si creano quindi interfacce di rete che consentono di accedere allo storage.

.A proposito di questa attività
Questa procedura si applica ai sistemi FAS, AFF e ASA. Se hai un sistema ASA r2 (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30, ASA A20 o ASA C30), segui link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["questi passaggi"^] per utilizzare System Manger per configurare un cluster ONTAP. I sistemi ASA R2 forniscono un'esperienza ONTAP semplificata, specifica per i clienti solo SAN.

.Fase
. Selezionare *Dashboard*, quindi fare clic su *Configura protocolli*.
+
** Per attivare i protocolli NAS, selezionare *NFS* o *SMB*.
** Per attivare i protocolli SAN, selezionare *iSCSI* o *FC*.
** Per attivare i protocolli NVMe, selezionare *NVMe*.



