---
permalink: software_setup/task_decide_where_to_send_important_event_notifications.html 
sidebar: sidebar 
keywords: ontap, software, setup, decide, where, send, important, event, notifications 
summary: Prima di configurare le notifiche di eventi EMS importanti, è necessario decidere se inviare le notifiche a un indirizzo e-mail, a un server syslog o a un host traphost SNMP. 
---
= Decidere dove inviare notifiche di eventi importanti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di configurare le notifiche di eventi EMS importanti, è necessario decidere se inviare le notifiche a un indirizzo e-mail, a un server syslog o a un host traphost SNMP.

Se l'ambiente in uso contiene già un server syslog per l'aggregazione degli eventi registrati da altri sistemi, come server e applicazioni, è più semplice utilizzare tale server syslog anche per le notifiche di eventi importanti provenienti dai sistemi storage.

Se l'ambiente non contiene già un server syslog, è più semplice utilizzare l'e-mail per le notifiche di eventi importanti.

Se si inoltrano già notifiche di eventi a un host trapSNMP, potrebbe essere necessario monitorare tale host per rilevare eventi importanti.

* Impostare EMS per l'invio delle notifiche degli eventi.
+
[cols="2*"]
|===
| Se vuoi... | Fare riferimento a... 


 a| 
EMS per inviare notifiche di eventi importanti a un indirizzo e-mail
 a| 
xref:task_configure_important_ems_events_to_send_email_notifications.html[Configurazione di eventi EMS importanti per l'invio di notifiche e-mail]



 a| 
EMS per inoltrare notifiche di eventi importanti a un server syslog
 a| 
xref:task_configure_important_ems_events_to_forward_notifications_to_a_syslog_server.html[Configurazione di eventi EMS importanti per inoltrare le notifiche a un server syslog]



 a| 
Se si desidera che EMS inoltri le notifiche degli eventi a un host trapSNMP
 a| 
xref:task_configure_snmp_traphosts_to_receive_event_notifications.html[Configurazione di SNMP traphosts per la ricezione di notifiche di eventi]

|===

