---
permalink: software_setup/task_synchronize_the_system_time_across_the_cluster.html 
sidebar: sidebar 
keywords: ontap, software, setup, synchronize, system, time, across, cluster 
summary: 'La sincronizzazione dell"ora garantisce che ogni nodo del cluster abbia lo stesso tempo e previene gli errori CIFS e Kerberos.' 
---
= Sincronizzare l'ora di sistema nel cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sincronizzazione dell'ora garantisce che ogni nodo del cluster abbia lo stesso tempo e previene gli errori CIFS e Kerberos.

È necessario configurare un server NTP (Network Time Protocol) presso la propria sede. A partire da ONTAP 9.5, è possibile configurare il server NTP con autenticazione simmetrica. Per ulteriori informazioni, consultare la documentazione di link:../system-admin/manage-cluster-time-concept.html["gestione del tempo del cluster (solo amministratori del cluster)"].

È possibile sincronizzare l'ora nel cluster associando il cluster a uno o più server NTP.

. Verificare che l'ora e il fuso orario del sistema siano impostati correttamente per ciascun nodo.
+
Tutti i nodi del cluster devono essere impostati sullo stesso fuso orario.

+
.. Utilizzare il comando cluster date show per visualizzare la data, l'ora e il fuso orario correnti per ciascun nodo.
+
[listing]
----
cluster1::> cluster date show
Node         Date                Time zone
------------ ------------------- -----------------
cluster1-01  01/06/2015 09:35:15 America/New_York
cluster1-02  01/06/2015 09:35:15 America/New_York
cluster1-03  01/06/2015 09:35:15 America/New_York
cluster1-04  01/06/2015 09:35:15 America/New_York
4 entries were displayed.
----
.. Utilizzare il comando cluster date modify per modificare la data o il fuso orario di tutti i nodi.
+
In questo esempio, il fuso orario del cluster viene modificato in GMT:

+
[listing]
----
cluster1::> cluster date modify -timezone GMT
----


. Utilizzare il comando cluster Time-service ntp server create per associare il cluster al server NTP.
+
** Per configurare il server NTP senza autenticazione simmetrica, immettere il seguente comando: `cluster time-service ntp server create -server server_name`
** Per configurare il server NTP con autenticazione simmetrica, immettere il seguente comando: `cluster time-service ntp server create -server server_ip_address -key-id key_id`
+

NOTE: L'autenticazione simmetrica è disponibile a partire da ONTAP 9.5. Non è disponibile in ONTAP 9.4 o versioni precedenti.

+
Questo esempio presuppone che il DNS sia stato configurato per il cluster. Se il DNS non è stato configurato, specificare l'indirizzo IP del server NTP:

+
[listing]
----
cluster1::> cluster time-service ntp server create -server ntp1.example.com
----


. Verificare che il cluster sia associato a un server NTP: `cluster time-service ntp server show`
+
[listing]
----
cluster1::> cluster time-service ntp server show
Server               Version
-------------------- -----------
ntp1.example.com     auto
----


.Informazioni correlate
link:../system-admin/index.html["Amministrazione del sistema"]
