---
permalink: asa/support-limitations.html 
sidebar: sidebar 
keywords: all san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: Utilizzare le seguenti procedure per configurare un array All SAN utilizzando System Manager. 
---
= Tutti i limiti di configurazione E supporto DEGLI array SAN
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
I limiti di configurazione e il supporto di ASA variano in base alla versione di ONTAP. I dettagli più aggiornati sui limiti di configurazione supportati sono disponibili in link:https://hwu.netapp.com/["NetApp Hardware Universe"^].

Il supporto ASA per i protocolli SAN e i nodi per cluster è il seguente:

[cols="3*"]
|===


| Inizio con ONTAP... | Supporto del protocollo | Numero massimo di nodi per cluster 


| 9.12.1  a| 
* NVMe
+
** Configurazioni MetroCluster IP a 4 nodi
** Configurazioni IP non MetroCluster


* FC
* ISCSI

| 12 


| 9.9.1  a| 
* NVMe
+
** Configurazioni IP non MetroCluster


* FC
* ISCSI

 a| 
* 12 nodi per configurazioni IP non MetroCluser
* 8 nodi per le configurazioni IP MetroCluster




| 9.7  a| 
* FC
* ISCSI

| 4 
|===


== Supporto per porte persistenti

A partire da ONTAP 9.8, le porte persistenti sono attivate per impostazione predefinita su tutti GLI array SAN (ASA) configurati per l'utilizzo del protocollo FC. Le porte persistenti sono disponibili solo per FC e richiedono l'appartenenza alla zona identificata dal World Wide Port Name (WWPN).

Le porte persistenti riducono l'impatto dei takeover creando una LIF shadow sulla porta fisica corrispondente del partner ha. Quando un nodo viene sostituito, la LIF shadow sul nodo partner assume l'identità della LIF originale, inclusa la WWPNe. Prima che lo stato del percorso verso il nodo preso in consegna venga modificato in difettoso, la LIF shadow viene visualizzata come percorso attivo/ottimizzato verso lo stack MPIO host e l'i/o viene spostato. In questo modo si riducono le interruzioni di i/o perché l'host rileva sempre lo stesso numero di percorsi verso la destinazione, anche durante le operazioni di failover dello storage.

Per le porte persistenti, le seguenti caratteristiche della porta FCP devono essere identiche all'interno della coppia ha:

* Numero di porte FCP
* Nomi delle porte FCP
* Velocità delle porte FCP
* Zoning basato su WWPN FCP LIF


Se una di queste caratteristiche non è identica all'interno della coppia ha, viene generato il seguente messaggio EMS:

`EMS : scsiblade.lif.persistent.ports.fcp.init.error`

Per ulteriori informazioni sulle porte persistenti, vedere link:http://www.netapp.com/us/media/tr-4080.pdf["Report tecnico di NetApp 4080: Best practice per SAN ONTAP 9 scalabile"^].
