---
sidebar: sidebar 
permalink: high-availability/ha_automatic_takeover_commands_overview.html 
keywords: ontap, high, availability, ha, pair, automatic, takeover, commands, system, events, result, enable, email, notification, capability, disabled 
summary: Il Takeover automatico è attivato per impostazione predefinita su tutte le piattaforme NetApp FAS, AFF e ASA supportate. 
---
= Comandi di acquisizione automatica ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il Takeover automatico è attivato per impostazione predefinita su tutte le piattaforme NetApp FAS, AFF e ASA supportate. Potrebbe essere necessario modificare il comportamento e il controllo predefiniti quando si verificano ripristini automatici quando il nodo partner si riavvia, esegue una panoramica o si arresta.

|===


| Se si desidera che l'acquisizione avvenga automaticamente quando il nodo partner... | Utilizzare questo comando... 


| Si riavvia o si arresta | `storage failover modify ‑node nodename ‑onreboot true` 


| Panoramica | `storage failover modify ‑node nodename ‑onpanic true` 
|===


== Attivare la notifica via email se la funzionalità di Takeover è disattivata

Per ricevere una notifica rapida in caso di disattivazione della funzionalità di Takeover, configurare il sistema in modo da abilitare la notifica automatica via email per i messaggi EMS "`Takeover impossible`":

* `ha.takeoverImpVersion`
* `ha.takeoverImpLowMem`
* `ha.takeoverImpDegraded`
* `ha.takeoverImpUnsync`
* `ha.takeoverImpIC`
* `ha.takeoverImpHotShelf`
* `ha.takeoverImpNotDef`


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["modifica del failover di archiviazione"^]

