---
permalink: nas-audit/basic-auditing-concept.html 
sidebar: sidebar 
keywords: basic audit concepts 
summary: Per comprendere il controllo in ONTAP, è necessario conoscere alcuni concetti di base relativi al controllo. 
---
= Scoprite i concetti fondamentali di controllo di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per comprendere il controllo in ONTAP, è necessario conoscere alcuni concetti di base relativi al controllo.

* *File di staging*
+
I file binari intermedi sui singoli nodi in cui vengono memorizzati i record di audit prima del consolidamento e della conversione. I file di staging sono contenuti nei volumi di staging.

* *Volume di staging*
+
Un volume dedicato creato da ONTAP per memorizzare i file di staging. Esiste un volume di staging per aggregato. I volumi di staging sono condivisi da tutte le SVM (Storage Virtual Machine) abilitate all'audit per memorizzare i record di audit dell'accesso ai dati per i volumi di dati in quel particolare aggregato. I record di audit di ogni SVM sono memorizzati in una directory separata all'interno del volume di staging.

+
Gli amministratori dei cluster possono visualizzare informazioni sui volumi di staging, ma la maggior parte delle altre operazioni sui volumi non è consentita. Solo ONTAP può creare volumi di staging. ONTAP assegna automaticamente un nome ai volumi di staging. Tutti i nomi dei volumi di staging iniziano con `MDV_aud_` Seguito dall'UUID dell'aggregato contenente il volume di staging (ad esempio: `MDV_aud_1d0131843d4811e296fc123478563412`.)

* *Volumi di sistema*
+
Volume FlexVol contenente metadati speciali, ad esempio metadati per i log di audit dei servizi file. La SVM amministrativa possiede i volumi di sistema, visibili all'interno del cluster. I volumi di staging sono un tipo di volume di sistema.

* *Attività di consolidamento*
+
Un'attività che viene creata quando viene attivato il controllo. Questa attività a esecuzione prolungata su ogni SVM prende i record di audit dai file di staging attraverso i nodi membri della SVM. Questa attività unisce i record di audit in ordine cronologico ordinato, quindi li converte in un formato di registro eventi leggibile dall'utente specificato nella configurazione di controllo, ovvero IL formato DI file EVTX o XML. I registri eventi convertiti vengono memorizzati nella directory del registro eventi di controllo specificata nella configurazione di controllo SVM.


