---
permalink: nas-audit/commands-modify-auditing-config-reference.html 
sidebar: sidebar 
keywords: commands, modify, audit, configurations 
summary: 'Se si desidera modificare un"impostazione di controllo, è possibile modificare la configurazione corrente in qualsiasi momento, tra cui la modifica della destinazione del percorso di log e del formato di log, la modifica delle categorie di eventi da controllare, la modalità di salvataggio automatico dei file di log e il numero massimo di file di log da salvare.' 
---
= Comandi ONTAP per la modifica delle configurazioni di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera modificare un'impostazione di controllo, è possibile modificare la configurazione corrente in qualsiasi momento, tra cui la modifica della destinazione del percorso di log e del formato di log, la modifica delle categorie di eventi da controllare, la modalità di salvataggio automatico dei file di log e il numero massimo di file di log da salvare.

[cols=""30"]
|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Modificare il percorso di destinazione del log
 a| 
`vserver audit modify` con `-destination` parametro



 a| 
Modificare la categoria di eventi da controllare
 a| 
`vserver audit modify` con `-events` parametro


NOTE: Per controllare gli eventi di staging dei criteri di accesso centrale, è necessario attivare l'opzione del server SMB DAC (Dynamic Access Control) sulla macchina virtuale di storage (SVM).



 a| 
Modificare il formato del registro
 a| 
`vserver audit modify` con `-format` parametro



 a| 
Attivazione dei salvataggi automatici in base alle dimensioni interne del file di log
 a| 
`vserver audit modify` con `-rotate-size` parametro



 a| 
Attivazione dei salvataggi automatici in base a un intervallo di tempo
 a| 
`vserver audit modify` con `-rotate-schedule-month`, `-rotate-schedule-dayofweek`, `-rotate-schedule-day`, `-rotate-schedule-hour`, e. `-rotate-schedule-minute` parametri



 a| 
Specifica del numero massimo di file di log salvati
 a| 
`vserver audit modify` con `-rotate-limit` parametro

|===