---
permalink: nas-audit/configure-file-folder-audit-policies-concept.html 
sidebar: sidebar 
keywords: configure, file, folder, audit policies 
summary: 'L"implementazione del controllo sugli eventi di accesso a file e cartelle è un processo in due fasi. Innanzitutto, è necessario creare e abilitare una configurazione di controllo sulle macchine virtuali di storage (SVM). In secondo luogo, è necessario configurare i criteri di controllo nei file e nelle cartelle che si desidera monitorare. È possibile configurare criteri di controllo per monitorare i tentativi di accesso riusciti e non riusciti.' 
---
= Configurare i criteri di controllo di file e cartelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'implementazione del controllo sugli eventi di accesso a file e cartelle è un processo in due fasi. Innanzitutto, è necessario creare e abilitare una configurazione di controllo sulle macchine virtuali di storage (SVM). In secondo luogo, è necessario configurare i criteri di controllo nei file e nelle cartelle che si desidera monitorare. È possibile configurare criteri di controllo per monitorare i tentativi di accesso riusciti e non riusciti.

È possibile configurare policy di audit SMB e NFS. Le policy di audit SMB e NFS hanno requisiti di configurazione e funzionalità di audit differenti.

Se sono configurati i criteri di audit appropriati, ONTAP monitora gli eventi di accesso SMB e NFS come specificato nelle policy di audit solo se i server SMB o NFS sono in esecuzione.
