---
permalink: nas-audit/create-fpolicy-scope-task.html 
sidebar: sidebar 
keywords: create, fpolicy scope 
summary: 'Dopo aver creato il criterio FPolicy, è necessario creare un ambito FPolicy. Quando si crea l"ambito, si associa l"ambito a un criterio FPolicy. Un ambito definisce i limiti ai quali si applica la policy FPolicy. Gli ambiti possono includere o escludere file in base a condivisioni, policy di esportazione, volumi ed estensioni di file.' 
---
= Creare l'ambito FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver creato il criterio FPolicy, è necessario creare un ambito FPolicy. Quando si crea l'ambito, si associa l'ambito a un criterio FPolicy. Un ambito definisce i limiti ai quali si applica la policy FPolicy. Gli ambiti possono includere o escludere file in base a condivisioni, policy di esportazione, volumi ed estensioni di file.

.Di cosa hai bisogno
Il foglio di lavoro FPolicy Scope deve essere completato. Il criterio FPolicy deve esistere con un motore esterno associato (se il criterio è configurato per l'utilizzo di server FPolicy esterni) e deve avere almeno un evento FPolicy associato.

.Fasi
. Creare l'ambito FPolicy utilizzando `vserver fpolicy policy scope create` comando.
+
`vserver fpolicy policy scope create -vserver-name vs1.example.com -policy-name policy1 -volumes-to-include datavol1,datavol2`

. Verificare la configurazione dell'ambito FPolicy utilizzando `vserver fpolicy policy scope show` comando.
+
`vserver fpolicy policy scope show -vserver vs1.example.com -instance`

+
[listing]
----

                   Vserver: vs1.example.com
                    Policy: policy1
         Shares to Include: -
         Shares to Exclude: -
        Volumes to Include: datavol1, datavol2
        Volumes to Exclude: -
Export Policies to Include: -
Export Policies to Exclude: -
File Extensions to Include: -
File Extensions to Exclude: -
----

