---
permalink: nas-audit/create-fpolicy-policy-task.html 
sidebar: sidebar 
keywords: create, fpolicy, policy 
summary: 'Quando si crea il criterio FPolicy, si associa un motore esterno e uno o più eventi al criterio. Il criterio specifica inoltre se è richiesto lo screening obbligatorio, se i server FPolicy dispongono di un accesso privilegiato ai dati sulla macchina virtuale di storage (SVM) e se è attivata la funzione pass-through-Read per i file offline.' 
---
= Creare policy ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si crea il criterio FPolicy, si associa un motore esterno e uno o più eventi al criterio. Il criterio specifica inoltre se è richiesto lo screening obbligatorio, se i server FPolicy dispongono di un accesso privilegiato ai dati sulla macchina virtuale di storage (SVM) e se è attivata la funzione pass-through-Read per i file offline.

.Prima di iniziare
* Il foglio di lavoro della policy FPolicy deve essere completato.
* Se si prevede di configurare il criterio per l'utilizzo dei server FPolicy, il motore esterno deve esistere.
* Deve esistere almeno un evento FPolicy che si prevede di associare al criterio FPolicy.
* Se si desidera configurare l'accesso privilegiato ai dati, è necessario che un server SMB esista sulla SVM.
* Per configurare un archivio persistente per un criterio, il tipo di motore deve essere *asincrono* e il criterio deve essere *non obbligatorio*.
+
Per ulteriori informazioni, vedere link:create-persistent-stores.html["Creare archivi persistenti"].



.Fasi
. Creare la policy FPolicy:
+
`vserver fpolicy policy create -vserver <vserver_name> -policy-name <policy_name> -engine <engine_name> -events <event_name>[,event_name2,...] [-persistent-store <PS_name>] [-is-mandatory {true|false}] [-allow-privileged-access {yes|no}] [-privileged-user-name <domain\\user_name>] [-is-passthrough-read-enabled {true|false}]`

+
** Puoi aggiungere uno o più eventi separati da virgole alla policy FPolicy.
** Per impostazione predefinita, lo screening obbligatorio è attivato.
** Se si desidera consentire l'accesso con privilegi impostando `-allow-privileged-access` parametro a. `yes`, è inoltre necessario configurare un nome utente con privilegi per l'accesso con privilegi.
** Se si desidera configurare pass-through-Read impostando `-is-passthrough-read-enabled` parametro a. `true`, è inoltre necessario configurare l'accesso privilegiato ai dati.
+
Il seguente comando crea una policy denominata `policy1` che ha l'evento denominato `event1` e il motore esterno denominato `engine1` associato ad essa. Questa policy utilizza i valori predefiniti nella configurazione della policy:
`vserver fpolicy policy create -vserver vs1.example.com -policy-name policy1 -events event1 -engine engine1`

+
Il seguente comando crea una policy denominata  `policy2` che ha l'evento denominato  `event2` e il motore esterno denominato  `engine2` associato ad essa. Questa policy è configurata per usare l'accesso privilegiato con il nome utente specificato. La modalità passthrough-read è abilitata:

+
`vserver fpolicy policy create -vserver vs1.example.com -policy-name policy2 -events event2 -engine engine2 -allow-privileged-access yes -privileged-user-name example\archive_acct -is-passthrough-read-enabled true`

+
Il seguente comando crea una policy denominata  `native1` che ha l'evento denominato  `event3` associato a essa. Questa policy usa il motore nativo e usa i valori predefiniti nella configurazione della policy:

+
`vserver fpolicy policy create -vserver vs1.example.com -policy-name native1 -events event3 -engine native`



. Verificare la configurazione del criterio FPolicy utilizzando `vserver fpolicy policy show` comando.
+
Il seguente comando visualizza le informazioni relative ai tre criteri FPolicy configurati, incluse le seguenti informazioni:

+
** SVM associato al criterio
** Il motore esterno associato alla policy
** Gli eventi associati al criterio
** Se è richiesto lo screening obbligatorio
** Se è richiesto l'accesso con privilegi
`vserver fpolicy policy show`


+
[listing]
----

   Vserver       Policy     Events    Engine    Is Mandatory  Privileged
                 Name                                         Access
--------------   ---------  --------- --------- ------------  -----------
vs1.example.com  policy1    event1    engine1   true          no
vs1.example.com  policy2    event2    engine2   true          yes
vs1.example.com  native1    event3    native    true          no
----

