---
permalink: nas-audit/create-fpolicy-event-task.html 
sidebar: sidebar 
keywords: creating, fpolicy event 
summary: 'Durante la creazione di una configurazione dei criteri FPolicy, è necessario creare un evento FPolicy. L"evento viene associato alla policy FPolicy al momento della sua creazione. Un evento definisce il protocollo da monitorare e gli eventi di accesso al file da monitorare e filtrare.' 
---
= Creare l'evento FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la creazione di una configurazione dei criteri FPolicy, è necessario creare un evento FPolicy. L'evento viene associato alla policy FPolicy al momento della sua creazione. Un evento definisce il protocollo da monitorare e gli eventi di accesso al file da monitorare e filtrare.

.Prima di iniziare
È necessario completare l'evento FPolicy link:../nas-audit/fpolicy-event-config-worksheet-reference.html["foglio di lavoro"].



== Creare l'evento FPolicy

. Creare l'evento FPolicy utilizzando `vserver fpolicy policy event create` comando.
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -file-operations open,close,read,write`

. Verificare la configurazione dell'evento FPolicy utilizzando `vserver fpolicy policy event show` comando.
+
`vserver fpolicy policy event show -vserver vs1.example.com`

+
[listing]
----

                  Event               File                    Is Volume
Vserver           Name      Protocols Operations    Filters   Operation
---------------   --------- --------- ------------- --------- ------------
vs1.example.com   event1    cifs      open, close,  -         false
                                      read, write
----




== Creare gli eventi di accesso negato FPolicy

A partire da ONTAP 9.13.1, gli utenti possono ricevere notifiche per operazioni di file non riuscite a causa della mancanza di autorizzazioni. Queste notifiche sono preziose per la sicurezza, la protezione ransomware e la governance.

. Creare l'evento FPolicy utilizzando `vserver fpolicy policy event create` comando.
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -monitor-fileop-failure true -file-operations open`


