---
permalink: nas-audit/create-security-traces-concept.html 
sidebar: sidebar 
keywords: considerations, create, security traces 
summary: 'Quando si creano tracce di sicurezza sulle macchine virtuali di storage (SVM), è necessario tenere a mente diverse considerazioni. Ad esempio, è necessario conoscere i protocolli che è possibile creare una traccia, gli stili di protezione supportati e il numero massimo di tracce attive.' 
---
= Considerazioni per la creazione di tracce di protezione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si creano tracce di sicurezza sulle macchine virtuali di storage (SVM), è necessario tenere a mente diverse considerazioni. Ad esempio, è necessario conoscere i protocolli che è possibile creare una traccia, gli stili di protezione supportati e il numero massimo di tracce attive.

* È possibile creare tracce di sicurezza solo sulle SVM.
* Ogni voce di filtro di traccia di protezione è specifica per SVM.
+
Specificare la SVM su cui si desidera eseguire la traccia.

* È possibile aggiungere filtri di tracciamento delle autorizzazioni per le richieste SMB e NFS.
* È necessario configurare il server SMB o NFS sulla SVM su cui si desidera creare i filtri di traccia.
* È possibile creare tracce di sicurezza per file e cartelle che risiedono su NTFS, UNIX e volumi e qtree misti di sicurezza.
* È possibile aggiungere un massimo di 10 filtri di tracciamento delle autorizzazioni per SVM.
* Quando si crea o si modifica un filtro, è necessario specificare un numero di indice del filtro.
+
I filtri vengono considerati in ordine del numero di indice. I criteri di un filtro con un numero di indice superiore vengono considerati prima dei criteri con un numero di indice inferiore. Se la richiesta tracciata corrisponde ai criteri in più filtri abilitati, viene attivato solo il filtro con il numero di indice più alto.

* Dopo aver creato e attivato un filtro di traccia di protezione, è necessario eseguire alcune richieste di file o cartelle su un sistema client per generare attività che il filtro di traccia può acquisire e accedere al registro dei risultati di traccia.
* È necessario aggiungere filtri di tracciamento delle autorizzazioni solo per la verifica dell'accesso al file o per la risoluzione dei problemi.
+
L'aggiunta di filtri di tracciamento delle autorizzazioni ha un effetto minore sulle prestazioni del controller.

+
Una volta completata l'attività di verifica o risoluzione dei problemi, è necessario disattivare o rimuovere tutti i filtri di tracciamento delle autorizzazioni. Inoltre, i criteri di filtraggio selezionati devono essere il più specifici possibile, in modo che ONTAP non invii un numero elevato di risultati di traccia al registro.


