---
permalink: nas-audit/display-audit-policies-windows-security-tab-task.html 
sidebar: sidebar 
keywords: display, information, audit policies, windows security tab 
summary: 'È possibile visualizzare informazioni sui criteri di controllo applicati a file e directory utilizzando la scheda Security (protezione) della finestra Windows Properties (Proprietà di Windows). Si tratta dello stesso metodo utilizzato per i dati residenti su un server Windows, che consente ai clienti di utilizzare la stessa interfaccia GUI a cui sono abituati.' 
---
= Visualizzare le informazioni sui criteri di controllo utilizzando la scheda protezione di Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sui criteri di controllo applicati a file e directory utilizzando la scheda Security (protezione) della finestra Windows Properties (Proprietà di Windows). Si tratta dello stesso metodo utilizzato per i dati residenti su un server Windows, che consente ai clienti di utilizzare la stessa interfaccia GUI a cui sono abituati.

.A proposito di questa attività
La visualizzazione delle informazioni sui criteri di controllo applicati a file e directory consente di verificare che siano impostati gli elenchi di controllo di accesso di sistema (SACL) appropriati su file e cartelle specificati.

Per visualizzare informazioni sui SACL applicati a file e cartelle NTFS, completare la seguente procedura su un host Windows.

.Fasi
. Dal menu *Strumenti* di Esplora risorse, selezionare *Connetti unità di rete*.
. Completare la finestra di dialogo *Map Network Drive* (Connetti unità di rete):
+
.. Selezionare una lettera *Drive*.
.. Nella casella *Folder* (cartella), digitare l'indirizzo IP o il nome del server SMB della macchina virtuale di storage (SVM) contenente la condivisione che contiene sia i dati che si desidera controllare che il nome della condivisione.
+
Se il nome del server SMB è "`SMB_SERVER`" e la condivisione è denominata "`share1`", immettere `\\SMB_SERVER\share1`.

+
[NOTE]
====
È possibile specificare l'indirizzo IP dell'interfaccia dati per il server SMB invece del nome del server SMB.

====
.. Fare clic su *fine*.


+
Il disco selezionato viene montato e pronto con la finestra Esplora risorse che visualizza i file e le cartelle contenuti nella condivisione.

. Selezionare il file o la directory per cui vengono visualizzate le informazioni di controllo.
. Fare clic con il pulsante destro del mouse sul file o sulla directory e selezionare *Proprietà*.
. Selezionare la scheda *sicurezza*.
. Fare clic su *Avanzate*.
. Selezionare la scheda *Auditing*.
. Fare clic su *continua*.
+
Viene visualizzata la finestra Auditing. Nella casella *voci di controllo* viene visualizzato un riepilogo degli utenti e dei gruppi a cui sono stati applicati SACL.

. Nella casella *voci di controllo* selezionare l'utente o il gruppo di cui si desidera visualizzare le voci SACL.
. Fare clic su *Edit* (Modifica).
+
Viene visualizzata la finestra voce di controllo per <object>.

. Nella casella *Access*, visualizzare i SACL correnti applicati all'oggetto selezionato.
. Fare clic su *Annulla* per chiudere la casella *voce di controllo per <object>*.
. Fare clic su *Annulla* per chiudere la casella *controllo*.

