---
permalink: nas-audit/display-security-trace-results-task.html 
sidebar: sidebar 
keywords: display, security trace results 
summary: 'È possibile visualizzare i risultati della traccia di protezione generati per le operazioni dei file che corrispondono ai filtri di traccia di protezione. È possibile utilizzare i risultati per convalidare la configurazione di sicurezza per l"accesso ai file o per risolvere i problemi di accesso ai file SMB e NFS.' 
---
= Visualizza i risultati della traccia di protezione in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare i risultati della traccia di protezione generati per le operazioni dei file che corrispondono ai filtri di traccia di protezione. È possibile utilizzare i risultati per convalidare la configurazione di sicurezza per l'accesso ai file o per risolvere i problemi di accesso ai file SMB e NFS.

.Prima di iniziare
Per generare i risultati della traccia di protezione, è necessario che esista un filtro di traccia di protezione abilitato e che siano state eseguite operazioni da un client SMB o NFS che corrisponda al filtro di traccia di protezione.

.A proposito di questa attività
È possibile visualizzare un riepilogo di tutti i risultati della traccia di protezione oppure personalizzare le informazioni visualizzate nell'output specificando parametri opzionali. Ciò può essere utile quando i risultati della traccia di protezione contengono un gran numero di record.

Se non si specifica alcun parametro opzionale, viene visualizzato quanto segue:

* Nome SVM (Storage Virtual Machine)
* Nome del nodo
* Numero di indice della traccia di sicurezza
* Stile di sicurezza
* Percorso
* Motivo
* Nome utente
+
Il nome utente viene visualizzato in base alla configurazione del filtro di traccia:

+
[cols="40,60"]
|===


| Se il filtro è configurato... | Quindi... 


 a| 
Con un nome utente UNIX
 a| 
Il risultato della traccia di protezione visualizza il nome utente UNIX.



 a| 
Con un nome utente Windows
 a| 
Il risultato della traccia di protezione visualizza il nome utente di Windows.



 a| 
Senza nome utente
 a| 
Il risultato della traccia di protezione visualizza il nome utente di Windows.

|===


È possibile personalizzare l'output utilizzando parametri opzionali. Alcuni dei parametri facoltativi che è possibile utilizzare per limitare i risultati restituiti nell'output del comando includono:

[cols="35,65"]
|===


| Parametro facoltativo | Descrizione 


 a| 
`-fields` `field_name`, ...
 a| 
Visualizza l'output nei campi scelti. È possibile utilizzare questo parametro da solo o in combinazione con altri parametri opzionali.



 a| 
`-instance`
 a| 
Visualizza informazioni dettagliate sugli eventi di analisi della sicurezza. Utilizzare questo parametro con altri parametri opzionali per visualizzare informazioni dettagliate sui risultati specifici del filtro.



 a| 
`-node` `node_name`
 a| 
Visualizza solo informazioni sugli eventi nel nodo specificato.



 a| 
`-vserver` `vserver_name`
 a| 
Visualizza solo le informazioni sugli eventi sulla SVM specificata.



 a| 
`-index` `integer`
 a| 
Visualizza le informazioni sugli eventi che si sono verificati come risultato del filtro corrispondente al numero di indice specificato.



 a| 
`-client-ip` `IP_address`
 a| 
Visualizza informazioni sugli eventi che si sono verificati in seguito all'accesso al file dall'indirizzo IP del client specificato.



 a| 
`-path` `path`
 a| 
Visualizza le informazioni sugli eventi che si sono verificati in seguito all'accesso al file al percorso specificato.



 a| 
`-user-name` `user_name`
 a| 
Visualizza informazioni sugli eventi che si sono verificati in seguito all'accesso al file da parte dell'utente Windows o UNIX specificato.



 a| 
`-security-style` `security_style`
 a| 
Visualizza informazioni sugli eventi che si sono verificati nei file system con lo stile di sicurezza specificato.

|===
Per ulteriori informazioni sugli altri parametri opzionali, vedere link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].

.Fase
. Visualizzare i risultati del filtro di traccia di protezione utilizzando `vserver security trace trace-result show` comando.
+
`vserver security trace trace-result show -user-name domain\user`

+
[listing]
----
Vserver: vs1

Node     Index   Filter Details         Reason
-------- ------- ---------------------  -----------------------------
node1    3       User:domain\user       Access denied by explicit ACE
                 Security Style:mixed
                 Path:/dir1/dir2/

node1    5       User:domain\user       Access denied by explicit ACE
                 Security Style:unix
                 Path:/dir1/
----

