---
permalink: nas-audit/enable-audit-svm-task.html 
sidebar: sidebar 
keywords: enable, audit, svm 
summary: 'Una volta completata la configurazione del controllo, è necessario attivare il controllo sulla macchina virtuale dello storage (SVM).' 
---
= Abilitare il controllo su SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una volta completata l'impostazione della configurazione di controllo, è necessario attivare il controllo sulla macchina virtuale di storage (SVM).

.Di cosa hai bisogno
La configurazione dell'audit SVM deve già esistere.

.A proposito di questa attività
Quando una configurazione di eliminazione dell'ID di disaster recovery SVM viene avviata per la prima volta (dopo il completamento dell'inizializzazione di SnapMirror) e la SVM dispone di una configurazione di controllo, ONTAP disattiva automaticamente la configurazione di controllo. Il controllo viene disattivato sulla SVM di sola lettura per impedire il riempimento dei volumi di staging. È possibile attivare il controllo solo dopo che la relazione SnapMirror è stata interrotta e la SVM è in lettura/scrittura.

.Fase
. Abilitare il controllo su SVM:
+
`vserver audit enable -vserver vserver_name`

+
`vserver audit enable -vserver vs1`


