---
permalink: nas-audit/fpolicy-external-engine-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, external engine, configuration, worksheet 
summary: È possibile utilizzare questo foglio di lavoro per registrare i valori necessari durante il processo di configurazione del motore esterno FPolicy. Se è richiesto un valore di parametro, è necessario determinare quale valore utilizzare per tali parametri prima di configurare il motore esterno. 
---
= Completare il foglio di lavoro di configurazione del motore esterno FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare questo foglio di lavoro per registrare i valori necessari durante il processo di configurazione del motore esterno FPolicy. Se è richiesto un valore di parametro, è necessario determinare quale valore utilizzare per tali parametri prima di configurare il motore esterno.



== Informazioni per una configurazione di base del motore esterno

Registrare se si desidera includere ogni impostazione di parametro nella configurazione esterna del motore e quindi registrare il valore dei parametri che si desidera includere.

[cols="40,20,20,20"]
|===


| Tipo di informazione | Obbligatorio | Includi | I tuoi valori 


 a| 
Nome SVM (Storage Virtual Machine)
 a| 
Sì
 a| 
Sì
 a| 



 a| 
Nome del motore
 a| 
Sì
 a| 
Sì
 a| 



 a| 
Server FPolicy primari
 a| 
Sì
 a| 
Sì
 a| 



 a| 
Numero di porta
 a| 
Sì
 a| 
Sì
 a| 



 a| 
Server FPolicy secondari
 a| 
No
 a| 
 a| 



 a| 
Tipo di motore esterno
 a| 
No
 a| 
 a| 



 a| 
Opzione SSL per la comunicazione con il server FPolicy esterno
 a| 
Sì
 a| 
Sì
 a| 



 a| 
FQDN certificato o nome comune personalizzato
 a| 
No
 a| 
 a| 



 a| 
Numero di serie del certificato
 a| 
No
 a| 
 a| 



 a| 
Autorità di certificazione
 a| 
No
 a| 
 a| 

|===


== Informazioni sui parametri esterni avanzati del motore

Per configurare un motore esterno con parametri avanzati, è necessario immettere il comando di configurazione in modalità avanzata con privilegi.

[cols="40,20,20,20"]
|===


| Tipo di informazione | Obbligatorio | Includi | I tuoi valori 


 a| 
Timeout per l'annullamento di una richiesta
 a| 
No
 a| 
 a| 



 a| 
Timeout per l'interruzione di una richiesta
 a| 
No
 a| 
 a| 



 a| 
Intervallo per l'invio delle richieste di stato
 a| 
No
 a| 
 a| 



 a| 
Numero massimo di richieste in sospeso sul server FPolicy
 a| 
No
 a| 
 a| 



 a| 
Timeout per la disconnessione di un server FPolicy che non risponde
 a| 
No
 a| 
 a| 



 a| 
Intervallo per l'invio di messaggi keep-alive al server FPolicy
 a| 
No
 a| 
 a| 



 a| 
Numero massimo di tentativi di riconnessione
 a| 
No
 a| 
 a| 



 a| 
Dimensione buffer di ricezione
 a| 
No
 a| 
 a| 



 a| 
Dimensione buffer di invio
 a| 
No
 a| 
 a| 



 a| 
Timeout per l'eliminazione di un ID sessione durante la riconnessione
 a| 
No
 a| 
 a| 

|===