---
permalink: nas-audit/super-user-credentials-privileged-access-concept.html 
sidebar: sidebar 
keywords: grant, super user, credentials, privileged data access 
summary: 'ONTAP utilizza la combinazione dell"indirizzo IP e della credenziale utente configurata nella configurazione FPolicy per assegnare credenziali super utente al server FPolicy.' 
---
= Cosa significa concedere credenziali super utente per l'accesso privilegiato ai dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utilizza la combinazione dell'indirizzo IP e della credenziale utente configurata nella configurazione FPolicy per assegnare credenziali super utente al server FPolicy.

Quando il server FPolicy accede ai dati, lo stato di Super User concede i seguenti privilegi:

* Evitare controlli delle autorizzazioni
+
L'utente evita di controllare i file e l'accesso alla directory.

* Speciali privilegi di blocco
+
ONTAP consente l'accesso in lettura, scrittura o modifica a qualsiasi file, indipendentemente dai blocchi esistenti. Se il server FPolicy utilizza blocchi di intervallo di byte sul file, si ottiene la rimozione immediata dei blocchi esistenti sul file.

* Ignorare eventuali controlli FPolicy
+
Access non genera alcuna notifica FPolicy.


