---
permalink: nas-audit/supported-file-operation-filter-fpolicy-smb-concept.html 
sidebar: sidebar 
keywords: list, supported file operation, filter combinations, fpolicy, monitor, smb 
summary: 'Quando si configura l"evento FPolicy, è necessario tenere presente che solo alcune combinazioni di operazioni e filtri dei file sono supportate per il monitoraggio delle operazioni di accesso ai file SMB.' 
---
= Operazioni sui file supportate e combinazioni di filtri Monitor ONTAP FPolicy per SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura l'evento FPolicy, è necessario tenere presente che solo alcune combinazioni di operazioni e filtri dei file sono supportate per il monitoraggio delle operazioni di accesso ai file SMB.

L'elenco delle operazioni di file supportate e delle combinazioni di filtri per il monitoraggio FPolicy degli eventi di accesso ai file SMB è riportato nella seguente tabella:

[cols="30,70"]
|===


| Operazioni di file supportate | Filtri supportati 


 a| 
chiudere
 a| 
monitor-ads, offline-bit, close-with-modification, close-without-modification, close-with-read, escludi-directory



 a| 
creare
 a| 
monitor-ads, offline-bit



 a| 
crea_dir
 a| 
Attualmente non è supportato alcun filtro per questa operazione di file.



 a| 
eliminare
 a| 
monitor-ads, offline-bit



 a| 
dir_delete
 a| 
Attualmente non è supportato alcun filtro per questa operazione di file.



 a| 
getattr
 a| 
offline-bit, exclude-dir



 a| 
aprire
 a| 
monitor-ads, offline-bit, open-with-delete-intent, open-with-write-intent, exclude-dir



 a| 
leggi
 a| 
monitor-ads, offline-bit, first-read



 a| 
di scrittura
 a| 
monitor-ads, offline-bit, first-write, write-with-size-change



 a| 
rinominare
 a| 
monitor-ads, offline-bit



 a| 
rinomina_dir
 a| 
Attualmente non è supportato alcun filtro per questa operazione di file.



 a| 
setattr
 a| 
monitor-ads, offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_with_creation_time_change, setattr_with_size_change, setattr_with_allocation_size_change, exclude_directory

|===
A partire da ONTAP 9.13.1, gli utenti possono ricevere notifiche per operazioni di file non riuscite a causa della mancanza di autorizzazioni. L'elenco delle combinazioni di filtri e operazioni di accesso negato supportate per il monitoraggio FPolicy degli eventi di accesso ai file SMB è riportato nella seguente tabella:

[cols="30,70"]
|===


| Operazione di accesso supportato con accesso negato | Filtri supportati 


 a| 
aprire
 a| 
NA

|===