---
permalink: nas-audit/synchronous-asynchronous-notifications-concept.html 
sidebar: sidebar 
keywords: synchronous, asynchronous, notifications 
summary: 'FPolicy invia notifiche ai server FPolicy esterni tramite l"interfaccia FPolicy. Le notifiche vengono inviate in modalità sincrona o asincrona. La modalità di notifica determina le operazioni di ONTAP dopo l"invio di notifiche ai server FPolicy.' 
---
= Quali sono le notifiche sincrone e asincrone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy invia notifiche ai server FPolicy esterni tramite l'interfaccia FPolicy. Le notifiche vengono inviate in modalità sincrona o asincrona. La modalità di notifica determina le operazioni di ONTAP dopo l'invio di notifiche ai server FPolicy.

* *Notifiche asincrone*
+
Con le notifiche asincrone, il nodo non attende una risposta dal server FPolicy, che migliora il throughput complessivo del sistema. Questo tipo di notifica è adatto alle applicazioni in cui il server FPolicy non richiede che venga intrapresa alcuna azione in seguito alla valutazione della notifica. Ad esempio, le notifiche asincrone vengono utilizzate quando l'amministratore della macchina virtuale di storage (SVM) desidera monitorare e controllare l'attività di accesso ai file.

+
Se un server FPolicy che opera in modalità asincrona subisce un'interruzione di rete, le notifiche FPolicy generate durante l'interruzione vengono memorizzate nel nodo di storage. Quando il server FPolicy torna in linea, viene avvisato delle notifiche memorizzate e può recuperarle dal nodo di storage. Il periodo di tempo in cui le notifiche possono essere memorizzate durante un'interruzione è configurabile fino a 10 minuti.

+
A partire da ONTAP 9.14.1, FPolicy consente di configurare un archivio persistente per acquisire eventi di accesso ai file per policy asincrone non obbligatorie nella SVM. Gli archivi persistenti possono aiutare a separare l'elaborazione i/o dei client dall'elaborazione delle notifiche FPolicy per ridurre la latenza dei client. Le configurazioni obbligatorie sincrone (obbligatorie o non obbligatorie) e asincrone non sono supportate.



A partire da ONTAP 9.14.1, FPolicy consente di configurare un archivio persistente per acquisire eventi di accesso ai file per policy asincrone non obbligatorie nella SVM. Gli archivi persistenti possono aiutare a separare l'elaborazione i/o dei client dall'elaborazione delle notifiche FPolicy per ridurre la latenza dei client. Le configurazioni obbligatorie sincrone e asincrone non sono supportate.

* *Notifiche sincrona*
+
Se configurato per l'esecuzione in modalità sincrona, il server FPolicy deve riconoscere ogni notifica prima che l'operazione del client possa continuare. Questo tipo di notifica viene utilizzato quando è richiesta un'azione in base ai risultati della valutazione della notifica. Ad esempio, le notifiche sincrone vengono utilizzate quando l'amministratore SVM desidera consentire o negare le richieste in base ai criteri specificati sul server FPolicy esterno.





== Applicazioni sincrone e asincrone

Esistono molti possibili utilizzi per le applicazioni FPolicy, sia asincrone che sincrona.

Le applicazioni asincrone sono quelle in cui il server FPolicy esterno non altera l'accesso a file o directory o non modifica i dati sulla macchina virtuale di storage (SVM). Ad esempio:

* Accesso al file e registrazione dell'audit
* Gestione delle risorse dello storage


Le applicazioni sincrone sono quelle in cui l'accesso ai dati viene alterato o i dati vengono modificati dal server FPolicy esterno. Ad esempio:

* Gestione delle quote
* Blocco dell'accesso al file
* Archiviazione dei file e gestione dello storage gerarchico
* Servizi di crittografia e decrittografia
* Servizi di compressione e decompressione

