---
permalink: nas-audit/troubleshoot-auditing-staging-volume-concept.html 
sidebar: sidebar 
keywords: troubleshoot, audit, stage, volume space, issues 
summary: 'Possono verificarsi problemi quando lo spazio disponibile sui volumi di staging o sul volume contenente i registri degli eventi di audit è insufficiente. Se lo spazio è insufficiente, non è possibile creare nuovi record di audit, impedendo ai client di accedere ai dati e impedendo l"esecuzione delle richieste di accesso. Dovresti sapere come risolvere questi problemi di spazio del volume.' 
---
= Risolvere i problemi di auditing e di gestione dello spazio dei volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Possono verificarsi problemi quando lo spazio disponibile sui volumi di staging o sul volume contenente i registri degli eventi di audit è insufficiente. Se lo spazio è insufficiente, non è possibile creare nuovi record di audit, impedendo ai client di accedere ai dati e impedendo l'esecuzione delle richieste di accesso. Dovresti sapere come risolvere questi problemi di spazio del volume.



== Risolvere i problemi di spazio relativi ai volumi del registro eventi

Se i volumi contenenti file di log degli eventi esauriranno lo spazio, il controllo non potrà convertire i record di log in file di log. Ciò comporta errori di accesso al client. È necessario sapere come risolvere i problemi di spazio relativi ai volumi del registro eventi.

* Gli amministratori di Storage Virtual Machine (SVM) e del cluster possono determinare se lo spazio dei volumi è insufficiente visualizzando informazioni sull'utilizzo e sulla configurazione di volumi e aggregati.
* Se lo spazio disponibile nei volumi contenenti registri eventi è insufficiente, gli amministratori di SVM e cluster possono risolvere i problemi di spazio rimuovendo alcuni file di registro eventi o aumentando le dimensioni del volume.
+
[NOTE]
====
Se l'aggregato che contiene il volume del registro eventi è pieno, è necessario aumentare le dimensioni dell'aggregato prima di poter aumentare le dimensioni del volume. Solo un amministratore del cluster può aumentare le dimensioni di un aggregato.

====
* Il percorso di destinazione dei file di registro eventi può essere modificato in una directory di un altro volume modificando la configurazione di controllo.
+
[NOTE]
====
L'accesso ai dati viene negato nei seguenti casi:

** La directory di destinazione viene eliminata.
** Il limite di file su un volume, che ospita la directory di destinazione, raggiunge il livello massimo.


====


Scopri di più su:

* link:../volumes/index.html["Come visualizzare informazioni sui volumi e aumentare le dimensioni del volume"].
* link:../disks-aggregates/index.html["Come visualizzare informazioni sugli aggregati e sulla gestione degli aggregati"].




== Risolvere i problemi di spazio relativi ai volumi di staging

Se uno dei volumi contenenti file di staging per la macchina virtuale di storage (SVM) esaurisce lo spazio, il controllo non può scrivere record di log nei file di staging. Ciò comporta errori di accesso al client. Per risolvere questo problema, è necessario determinare se uno dei volumi di staging utilizzati nella SVM è pieno visualizzando le informazioni sull'utilizzo del volume.

Se il volume contenente i file di registro eventi consolidati dispone di spazio sufficiente ma si verificano ancora errori di accesso del client a causa di spazio insufficiente, i volumi di staging potrebbero essere fuori spazio. L'amministratore di SVM deve contattare l'utente per determinare se i volumi di staging che contengono file di staging per SVM hanno spazio insufficiente. Il sottosistema di controllo genera un evento EMS se non è possibile generare eventi di controllo a causa dello spazio insufficiente in un volume di staging. Viene visualizzato il seguente messaggio: `No space left on device`. Solo gli amministratori SVM possono visualizzare informazioni sui volumi di staging.

Tutti i nomi dei volumi di staging iniziano con `MDV_aud_` Seguito dall'UUID dell'aggregato contenente il volume di staging. L'esempio seguente mostra quattro volumi di sistema sulla SVM amministrativa, creati automaticamente quando è stata creata una configurazione di controllo dei file service per una SVM di dati nel cluster:

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          5GB     4.75GB    5%
4 entries were displayed.
----
Se lo spazio disponibile nei volumi di staging è insufficiente, è possibile risolvere i problemi di spazio aumentando le dimensioni del volume.

[NOTE]
====
Se l'aggregato che contiene il volume di staging è pieno, è necessario aumentare le dimensioni dell'aggregato prima di poter aumentare le dimensioni del volume. Solo gli amministratori di SVM possono aumentare le dimensioni di un aggregato.

====
Se uno o più aggregati hanno uno spazio disponibile inferiore a 5GB GB, la creazione dell'audit della SVM non riesce. Quando la creazione dell'audit SVM non riesce, i volumi di staging creati vengono cancellati.
