---
permalink: nas-audit/troubleshoot-auditing-staging-volume-concept.html 
sidebar: sidebar 
keywords: troubleshoot, audit, stage, volume space, issues 
summary: 'Possono verificarsi problemi in caso di spazio insufficiente sui volumi di staging o sul volume contenente i log degli eventi di audit. Se lo spazio è insufficiente, non è possibile creare nuovi record di audit. Quando la garanzia di audit è abilitata, questo può impedire ai client di accedere ai dati e causare l"errore delle richieste di accesso. Dovresti sapere come risolvere questi problemi di spazio sui volumi.' 
---
= Risolvere i problemi di auditing e staging dello spazio dei volumi di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Possono verificarsi problemi in caso di spazio insufficiente sui volumi di staging o sul volume contenente i log degli eventi di audit. Se lo spazio è insufficiente, non è possibile creare nuovi record di audit. Quando la garanzia di audit è abilitata, questo può impedire ai client di accedere ai dati e causare l'errore delle richieste di accesso. Dovresti sapere come risolvere questi problemi di spazio sui volumi.

[NOTE]
====
Questo comportamento si applica quando la garanzia di audit è abilitata. Per ulteriori informazioni, vedere link:../nas-audit/auditing-process-concept.html["Auditing garantito"].

====


[[troubleshoot-space-issues-related-to-the-event-log-volumes]]
== Risolvere i problemi di spazio relativi ai volumi del registro eventi

Se lo spazio sui volumi contenenti i file di registro eventi si esaurisce, il controllo non può convertire i record di registro in file di registro. Quando la garanzia di controllo è abilitata, questo causa errori di accesso da parte dei client. Devi sapere come risolvere i problemi di spazio relativi ai volumi di registro eventi.

* Gli amministratori di Storage Virtual Machine (SVM) e del cluster possono determinare se lo spazio dei volumi è insufficiente visualizzando informazioni sull'utilizzo e sulla configurazione di volumi e aggregati.
* Se lo spazio disponibile nei volumi contenenti registri eventi è insufficiente, gli amministratori di SVM e cluster possono risolvere i problemi di spazio rimuovendo alcuni file di registro eventi o aumentando le dimensioni del volume.
+
[NOTE]
====
Se l'aggregato che contiene il volume del registro eventi è pieno, è necessario aumentare le dimensioni dell'aggregato prima di poter aumentare le dimensioni del volume. Solo un amministratore del cluster può aumentare le dimensioni di un aggregato.

====
* Il percorso di destinazione dei file di registro eventi può essere modificato in una directory di un altro volume modificando la configurazione di controllo.
+
[NOTE]
====
L'accesso ai dati viene negato nei seguenti casi:

** La directory di destinazione viene eliminata.
** Il limite di file su un volume, che ospita la directory di destinazione, raggiunge il livello massimo.


====


Scopri di più su:

* link:../volumes/index.html["Come visualizzare informazioni sui volumi e aumentare le dimensioni del volume"].
* link:../disks-aggregates/index.html["Come visualizzare informazioni sugli aggregati e sulla gestione degli aggregati"].




[[troubleshoot-space-issues-related-to-the-staging-volumes]]
== Risolvere i problemi di spazio relativi ai volumi di staging

Se uno qualsiasi dei volumi contenenti i file di staging per la tua storage virtual machine (SVM) esaurisce lo spazio, il controllo non può scrivere i record di log nei file di staging. Quando la garanzia di controllo è abilitata, questo causa errori di accesso da parte dei client. Per risolvere questo problema, devi verificare se uno qualsiasi dei volumi di staging utilizzati nella SVM è pieno visualizzando le informazioni sull'utilizzo dei volumi.

Se il volume contenente i file di registro eventi consolidati dispone di spazio sufficiente ma si verificano ancora errori di accesso del client a causa di spazio insufficiente, i volumi di staging potrebbero essere fuori spazio. L'amministratore di SVM deve contattare l'utente per determinare se i volumi di staging che contengono file di staging per SVM hanno spazio insufficiente. Il sottosistema di controllo genera un evento EMS se non è possibile generare eventi di controllo a causa dello spazio insufficiente in un volume di staging. Viene visualizzato il seguente messaggio: `No space left on device`. Solo gli amministratori SVM possono visualizzare informazioni sui volumi di staging.

Tutti i nomi dei volumi di staging iniziano con `MDV_aud_` Seguito dall'UUID dell'aggregato contenente il volume di staging. L'esempio seguente mostra quattro volumi di sistema sulla SVM amministrativa, creati automaticamente quando è stata creata una configurazione di controllo dei file service per una SVM di dati nel cluster:

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          5GB     4.75GB    5%
4 entries were displayed.
----
Se lo spazio disponibile nei volumi di staging è insufficiente, è possibile risolvere i problemi di spazio aumentando le dimensioni del volume.

[NOTE]
====
Se l'aggregato che contiene il volume di staging è pieno, è necessario aumentare le dimensioni dell'aggregato prima di poter aumentare le dimensioni del volume. Solo gli amministratori di SVM possono aumentare le dimensioni di un aggregato.

====
Se uno o più aggregati hanno uno spazio disponibile inferiore a 2GB GB (in ONTAP 9.14.1 e versioni precedenti) o 5GB GB (a partire da ONTAP 9.15.1), la creazione del controllo SVM non riesce. Quando la creazione dell'audit SVM non riesce, i volumi di staging creati vengono cancellati.
