---
permalink: nas-audit/two-parts-fpolicy-solution-concept.html 
sidebar: sidebar 
keywords: two parts, fpolicy, solution 
summary: Una soluzione FPolicy è composta da due parti. Il framework FPolicy di ONTAP gestisce le attività sul cluster e invia notifiche ai server FPolicy esterni. I server FPolicy esterni elaborano le notifiche inviate da ONTAP FPolicy. 
---
= Scopri le soluzioni ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy è un framework di notifica dell'accesso ai file utilizzato per monitorare e gestire gli eventi di accesso ai file sulle macchine virtuali di storage (SVM) attraverso le soluzioni dei partner. Le soluzioni dei partner ti aiutano a risolvere diversi casi di utilizzo, ad esempio governance e conformità dei dati, protezione ransomware e mobilità dei dati.

Le soluzioni dei partner includono soluzioni di terze parti supportate da NetApp e prodotti NetApp workload Security e Cloud Data Sense.

Una soluzione FPolicy è composta da due parti. Il framework FPolicy di ONTAP gestisce le attività sul cluster e invia notifiche all'applicazione partner (alias server FPolicy esterni). I server FPolicy esterni elaborano le notifiche inviate da ONTAP FPolicy per soddisfare i casi di utilizzo dei clienti.

Il framework ONTAP crea e gestisce la configurazione di FPolicy, monitora gli eventi dei file e invia notifiche ai server FPolicy esterni. ONTAP FPolicy fornisce l'infrastruttura che consente la comunicazione tra server FPolicy esterni e nodi SVM (Storage Virtual Machine).

Il framework FPolicy si connette ai server FPolicy esterni e invia notifiche per determinati eventi del file system ai server FPolicy quando questi eventi si verificano in seguito all'accesso del client. I server FPolicy esterni elaborano le notifiche e inviano le risposte al nodo. Ciò che accade in seguito all'elaborazione delle notifiche dipende dall'applicazione e dal fatto che la comunicazione tra il nodo e i server esterni sia asincrona o sincrona.
