---
permalink: nas-audit/view-audit-event-logs-concept.html 
sidebar: sidebar 
keywords: view, audit event logs 
summary: È possibile utilizzare i registri degli eventi di audit per determinare se si dispone di una protezione dei file adeguata e se si sono verificati tentativi di accesso a file e cartelle non corretti. È possibile visualizzare ed elaborare i log degli eventi di audit salvati nei formati DI file EVTX o XML. 
---
= Visualizzare i registri degli eventi di audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i registri degli eventi di audit per determinare se si dispone di una protezione dei file adeguata e se si sono verificati tentativi di accesso a file e cartelle non corretti. È possibile visualizzare ed elaborare i registri degli eventi di audit salvati in `EVTX` oppure `XML` formati di file.

* `EVTX` formato del file
+
È possibile aprire il file convertito `EVTX` Controllare i log degli eventi come file salvati utilizzando Microsoft Event Viewer.

+
È possibile utilizzare due opzioni per la visualizzazione dei registri eventi mediante il Visualizzatore eventi:

+
** Vista generale
+
Le informazioni comuni a tutti gli eventi vengono visualizzate per il record dell'evento. In questa versione di ONTAP, i dati specifici dell'evento per il record dell'evento non vengono visualizzati. È possibile utilizzare la vista dettagliata per visualizzare i dati specifici dell'evento.

** Vista dettagliata
+
Sono disponibili una vista intuitiva e una vista XML. La visualizzazione semplice e la visualizzazione XML visualizzano sia le informazioni comuni a tutti gli eventi che i dati specifici dell'evento per il record dell'evento.



* `XML` formato del file
+
È possibile visualizzare ed elaborare `XML` registri degli eventi di audit su applicazioni di terze parti che supportano `XML` formato del file. È possibile utilizzare gli strumenti di visualizzazione XML per visualizzare i registri di controllo, a condizione che si disponga dello schema XML e delle informazioni sulle definizioni dei campi XML. Per ulteriori informazioni sullo schema e sulle definizioni XML, vedere https://library.netapp.com/ecm/ecm_get_file/ECMLP2875022["Riferimento allo schema di controllo ONTAP"].





== Visualizzazione dei registri di controllo attivi mediante Event Viewer

Se il processo di consolidamento dell'audit è in esecuzione sul cluster, il processo di consolidamento aggiunge nuovi record al file di log dell'audit attivo per le macchine virtuali dello storage abilitate all'audit (SVM). È possibile accedere a questo registro di controllo attivo e aprirlo tramite una condivisione SMB in Microsoft Event Viewer.

Oltre a visualizzare i record di audit esistenti, Event Viewer offre un'opzione di refresh che consente di aggiornare il contenuto nella finestra della console. La possibilità di visualizzare i nuovi registri aggiunti nel Visualizzatore eventi dipende dall'attivazione o meno degli oplock nella condivisione utilizzata per accedere al registro di controllo attivo.

[cols="30,70"]
|===


| Impostazione degli oplock sulla condivisione | Comportamento 


 a| 
Attivato
 a| 
Event Viewer apre il registro contenente gli eventi scritti fino a quel momento. L'operazione di refresh non aggiorna il log con nuovi eventi aggiunti dal processo di consolidamento.



 a| 
Disattivato
 a| 
Event Viewer apre il registro contenente gli eventi scritti fino a quel momento. L'operazione di refresh aggiorna il log con nuovi eventi aggiunti dal processo di consolidamento.

|===
[NOTE]
====
Queste informazioni sono valide solo per `EVTX` registri eventi. `XML` I registri degli eventi possono essere visualizzati tramite SMB in un browser o NFS utilizzando qualsiasi editor o visualizzatore XML.

====