---
permalink: san-config/configure-fc-adapters-initiator-mode-task.html 
sidebar: sidebar 
keywords: configure, fc adapters, initiator mode 
summary: 'È possibile configurare singole porte FC di adattatori integrati e alcune schede FC per la modalità Initiator. La modalità Initiator viene utilizzata per collegare le porte a unità a nastro, librerie a nastro o storage di terze parti con la virtualizzazione FlexArray o l"importazione di LUN esterne (FLI).' 
---
= Configurare gli adattatori FC per la modalità Initiator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare singole porte FC di adattatori integrati e alcune schede FC per la modalità Initiator. La modalità Initiator viene utilizzata per collegare le porte a unità a nastro, librerie a nastro o storage di terze parti con la virtualizzazione FlexArray o l'importazione di LUN esterne (FLI).

.Di cosa hai bisogno
* Le LIF della scheda di rete devono essere rimosse da tutti i set di porte di cui sono membri.
* Tutti i LIF di ogni macchina virtuale di storage (SVM) che utilizza la porta fisica da modificare devono essere migrati o distrutti prima di cambiare la personalità della porta fisica da destinazione a iniziatore.


.A proposito di questa attività
Ogni porta FC integrata può essere configurata singolarmente come iniziatore o destinazione. Le porte di alcuni adattatori FC possono anche essere configurate singolarmente come una porta di destinazione o una porta initiator, proprio come le porte FC integrate. In è disponibile un elenco di adattatori che è possibile configurare per la modalità di destinazione https://hwu.netapp.com["NetApp Hardware Universe"^].

[NOTE]
====
NVMe/FC supporta la modalità Initiator.

====
.Fasi
. Rimuovere tutti i file LIF dalla scheda:
+
`network interface delete -vserver _SVM_name_ -lif _lif_name_,_lif_name_`

. Porta l'adattatore offline:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down`

+
Se l'adattatore non viene scollegato, è anche possibile rimuovere il cavo dalla porta dell'adattatore appropriata sul sistema.

. Cambiare la scheda di rete da destinazione a iniziatore:
+
`system hardware unified-connect modify -t initiator _adapter_port_`

. Riavviare il nodo che ospita l'adattatore modificato.
. Verificare che le porte FC siano configurate nello stato corretto per la configurazione:
+
`system hardware unified-connect show`

. Riportare l'adattatore online:
+
`node run -node _node_name_ storage enable adapter _adapter_port_`


