---
permalink: san-config/configure-fc-adapters-target-mode-task.html 
sidebar: sidebar 
keywords: configure, fc, adapters, target mode 
summary: È possibile configurare singole porte FC di adattatori integrati e alcune schede adattatore FC per la modalità di destinazione. La modalità di destinazione viene utilizzata per collegare le porte agli iniziatori FC. 
---
= Configurare gli adattatori FC per la modalità di destinazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare singole porte FC di adattatori integrati e alcune schede adattatore FC per la modalità di destinazione. La modalità di destinazione viene utilizzata per collegare le porte agli iniziatori FC.

.A proposito di questa attività
Ogni porta FC integrata può essere configurata singolarmente come iniziatore o destinazione. Le porte di alcuni adattatori FC possono anche essere configurate singolarmente come una porta di destinazione o una porta initiator, proprio come le porte FC integrate. In è disponibile un elenco di adattatori che è possibile configurare per la modalità di destinazione link:https://hwu.netapp.com["NetApp Hardware Universe"^].

La stessa procedura viene utilizzata per la configurazione degli adattatori FC per il protocollo FC e il protocollo FC-NVMe. Tuttavia, solo alcuni adattatori FC supportano FC-NVMe. Vedere link:https://hwu.netapp.com["NetApp Hardware Universe"^] Per un elenco di adattatori che supportano il protocollo FC-NVMe.

.Fasi
. Portare l'adattatore offline:
+
`node run -node _node_name_ storage disable adapter _adapter_name_`

+
Se l'adattatore non viene scollegato, è anche possibile rimuovere il cavo dalla porta dell'adattatore appropriata sul sistema.

. Cambiare la scheda di rete da iniziatore a destinazione:
+
`system node hardware unified-connect modify -t target -node _node_name_ adapter _adapter_name_`

. Riavviare il nodo che ospita l'adattatore modificato.
. Verificare che la porta di destinazione abbia la configurazione corretta:
+
`network fcp adapter show -node _node_name_`

. Porta online il tuo adattatore:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -state up`


