---
permalink: san-config/configure-fc-adapters-initiator-target.html 
sidebar: sidebar 
keywords: configure, fc adapters, initiator mode, target mode, FC-NVMe, FC adapter speed 
summary: Gli adattatori FC integrati e alcune schede adattatore FC possono essere configurati come iniziatori o porte di destinazione. Gli altri adattatori di espansione FC sono configurati come iniziatori o target in fabbrica e non possono essere modificati. 
---
= Configurare gli adattatori FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli adattatori FC integrati e alcune schede adattatore FC possono essere configurati singolarmente come iniziatori o porte di destinazione. Gli altri adattatori di espansione FC sono configurati come iniziatori o target in fabbrica e non possono essere modificati. Sono disponibili anche porte FC aggiuntive tramite le schede UTA2 supportate configurate con adattatori FC SFP+.

È possibile utilizzare le porte Initiator per il collegamento diretto agli shelf di dischi back-end e agli array di storage di altri produttori. Le porte di destinazione possono essere utilizzate per collegare solo switch FC.

Il numero di porte integrate e le porte CNA/UTA2 configurate per FC varia a seconda del modello del controller. Anche gli adattatori di espansione target supportati variano a seconda del modello di controller. Consulta link:https://hwu.netapp.com["NetApp Hardware Universe"^] per un elenco completo delle porte FC integrate e degli adattatori di espansione di destinazione supportati per il tuo modello di controller.



== Configurare gli adattatori FC per la modalità Initiator

La modalità Initiator viene utilizzata per collegare le porte a unità a nastro, librerie a nastro o storage di terze parti con la virtualizzazione FlexArray o l'importazione di LUN esterne (FLI).

.Prima di iniziare
* Le LIF della scheda di rete devono essere rimosse da tutti i set di porte di cui sono membri.
* Tutti i LIF di ogni macchina virtuale di storage (SVM) che utilizza la porta fisica da modificare devono essere migrati o distrutti prima di cambiare la personalità della porta fisica da destinazione a iniziatore.


[NOTE]
====
NVMe/FC supporta la modalità Initiator.

====
.Fasi
. Rimuovere tutti i file LIF dalla scheda:
+
[source, cli]
----
network interface delete -vserver _SVM_name_ -lif _lif_name_,_lif_name_
----
. Porta l'adattatore offline:
+
[source, cli]
----
network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down
----
+
Se l'adattatore non viene scollegato, è anche possibile rimuovere il cavo dalla porta dell'adattatore appropriata sul sistema.

. Cambiare la scheda di rete da destinazione a iniziatore:
+
[source, cli]
----
system hardware unified-connect modify -t initiator _adapter_port_
----
. Riavviare il nodo che ospita l'adattatore modificato.
. Verificare che le porte FC siano configurate nello stato corretto per la configurazione:
+
[source, cli]
----
system hardware unified-connect show
----
. Riportare l'adattatore online:
+
[source, cli]
----
node run -node _node_name_ storage enable adapter _adapter_port_
----




== Configurare gli adattatori FC per la modalità di destinazione

La modalità di destinazione viene utilizzata per collegare le porte agli iniziatori FC.

Vengono eseguite le stesse operazioni per configurare gli adattatori FC per il protocollo FC e il protocollo FC-NVMe. Tuttavia, solo alcuni adattatori FC supportano FC-NVMe. Consulta la link:https://hwu.netapp.com["NetApp Hardware Universe"^] per un elenco di adattatori che supportano il protocollo FC-NVMe.

.Fasi
. Portare l'adattatore offline:
+
[source, cli]
----
node run -node _node_name_ storage disable adapter _adapter_name_
----
+
Se l'adattatore non viene scollegato, è anche possibile rimuovere il cavo dalla porta dell'adattatore appropriata sul sistema.

. Cambiare la scheda di rete da iniziatore a destinazione:
+
[source, cli]
----
system node hardware unified-connect modify -t target -node _node_name_ adapter _adapter_name_
----
. Riavviare il nodo che ospita l'adattatore modificato.
. Verificare che la porta di destinazione abbia la configurazione corretta:
+
[source, cli]
----
network fcp adapter show -node _node_name_
----
. Porta online il tuo adattatore:
+
[source, cli]
----
network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -state up
----




== Configurare la velocità della scheda FC

È necessario configurare la velocità della porta di destinazione della scheda di rete in modo che corrisponda alla velocità del dispositivo a cui si connette, anziché utilizzare la negoziazione automatica. Una porta impostata per la negoziazione automatica può richiedere più tempo per riconnettersi dopo un takeover/giveback o un'altra interruzione.

.A proposito di questa attività
Poiché questa attività comprende tutte le macchine virtuali di storage (SVM) e tutte le LIF in un cluster, è necessario utilizzare `-home-port` e. `-home-lif` parametri per limitare l'ambito di questa operazione. Se non si utilizzano questi parametri, l'operazione si applica a tutte le LIF del cluster, cosa che potrebbe non essere auspicabile.

.Prima di iniziare
Tutte le LIF che utilizzano questo adattatore come porta home devono essere offline.

.Fasi
. Porta tutti i LIF su questo adattatore offline:
+
[source, cli]
----
network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin down
----
. Portare l'adattatore offline:
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -state down
----
+
Se l'adattatore non viene scollegato, è anche possibile rimuovere il cavo dalla porta dell'adattatore appropriata sul sistema.

. Determinare la velocità massima per l'adattatore porta:
+
[source, cli]
----
fcp adapter show -instance
----
+
Non è possibile modificare la velocità della scheda oltre la velocità massima.

. Modificare la velocità dell'adattatore:
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -speed 16
----
. Portare l'adattatore online:
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -state up
----
. Portare online tutti i file LIF della scheda di rete:
+
[source, cli]
----
network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin up
----

