---
permalink: san-config/determine-supported-hosts-fc-nvme-config-task.html 
sidebar: sidebar 
keywords: determine, number, supported hosts, per cluster, fc, fc-nvme, configurations 
summary: Il numero massimo di host SAN che possono essere connessi a un cluster varia notevolmente in base alla combinazione specifica di più attributi del cluster, ad esempio il numero di host connessi a ciascun nodo del cluster, gli iniziatori per host, le sessioni per host e i nodi nel cluster. 
---
= Determinare il numero di host supportati per cluster nelle configurazioni FC e FC-NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il numero massimo di host SAN che possono essere connessi a un cluster varia notevolmente in base alla combinazione specifica di più attributi del cluster, ad esempio il numero di host connessi a ciascun nodo del cluster, gli iniziatori per host, le sessioni per host e i nodi nel cluster.

.A proposito di questa attività
Per le configurazioni FC e FC-NVMe, è necessario utilizzare il numero di ITN (Initiator-Target Nexuses) nel sistema per determinare se è possibile aggiungere altri host al cluster.

Un ITN rappresenta un percorso dall'iniziatore dell'host alla destinazione del sistema di storage. Il numero massimo di ITN per nodo nelle configurazioni FC e FC-NVMe è 2,048. Se si è al di sotto del numero massimo di ITN, è possibile continuare ad aggiungere host al cluster.

Per determinare il numero di ITN utilizzati nel cluster, attenersi alla seguente procedura per ciascun nodo del cluster.

.Fasi
. Identificare tutte le LIF su un nodo specifico.
. Eseguire il seguente comando per ogni LIF sul nodo:
+
`fcp initiator show -fields wwpn, lif`

+
Il numero di voci visualizzate nella parte inferiore dell'output del comando rappresenta il numero di ITN per la LIF.

. Registrare il numero di ITN visualizzati per ciascun LIF.
. Aggiungere il numero di ITN per ogni LIF su ogni nodo del cluster.
+
Questo totale rappresenta il numero di ITN nel cluster.


