---
permalink: san-config/fc-switch-config-limits-reference.html 
sidebar: sidebar 
keywords: fc, switch, configuration, limits 
summary: Gli switch Fibre Channel hanno limiti di configurazione massimi, incluso il numero di accessi supportati per porta, gruppo di porte, blade e switch. I vendor di switch documentano i propri limiti supportati. 
---
= Limiti di configurazione per gli switch FC utilizzati con i sistemi ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli switch Fibre Channel hanno limiti di configurazione massimi, incluso il numero di accessi supportati per porta, gruppo di porte, blade e switch. I vendor di switch documentano i propri limiti supportati.

Ogni interfaccia logica FC (LIF) accede a una porta dello switch FC. Il numero totale di accessi da una singola destinazione sul nodo equivale al numero di LIF più un accesso per la porta fisica sottostante. Non superare i limiti di configurazione del vendor dello switch per gli accessi o altri valori di configurazione. Ciò vale anche per gli iniziatori utilizzati sul lato host in ambienti virtualizzati con NPIV attivato. Non superare i limiti di configurazione del vendor dello switch per gli accessi per la destinazione o per gli iniziatori utilizzati nella soluzione.



== Limiti dello switch Brocade

I limiti di configurazione per gli switch Brocade sono indicati nelle _linee guida sulla scalabilità Brocade_.



== Limiti degli switch Cisco Systems

I limiti di configurazione per gli switch Cisco sono disponibili in http://www.cisco.com/en/US/products/ps5989/products_installation_and_configuration_guides_list.html["Limiti di configurazione Cisco"^] Guida alla versione del software dello switch Cisco in uso.
