---
permalink: san-config/fc-switch-config-best-practices-concept.html 
sidebar: sidebar 
keywords: fc, switch, configuration, best, practices 
summary: Per ottenere prestazioni ottimali, è necessario prendere in considerazione alcune Best practice durante la configurazione dello switch FC. 
---
= Best practice per la configurazione dello switch FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ottenere prestazioni ottimali, è necessario prendere in considerazione alcune Best practice durante la configurazione dello switch FC.

Un'impostazione della velocità di collegamento fissa è la procedura migliore per le configurazioni degli switch FC, in particolare per i fabric di grandi dimensioni, in quanto offre le migliori prestazioni per le ricostruzioni del fabric e può risparmiare significativamente tempo. Sebbene la negoziazione automatica offra la massima flessibilità, la configurazione dello switch FC non sempre funziona come previsto e aggiunge tempo alla sequenza generale di fabric-build.

Tutti gli switch collegati al fabric devono supportare la virtualizzazione NPIV (N_Port ID Virtualization) e attivare NPIV. ONTAP utilizza NPIV per presentare i target FC a un fabric.

Per ulteriori informazioni sugli ambienti supportati, vedere https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].

Per informazioni sulle Best practice FC e iSCSI, vedere http://www.netapp.com/us/media/tr-4080.pdf["Best practice per SAN scalabili - ONTAP 9"].
