---
permalink: san-config/fc-target-port-config-recommendations-concept.html 
sidebar: sidebar 
keywords: fc, target, port, configuration, recommendations 
summary: Per ottenere le migliori prestazioni e la massima disponibilità, è necessario utilizzare la configurazione della porta di destinazione FC consigliata. 
---
= Consigli per la configurazione della porta di destinazione FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ottenere le migliori prestazioni e la massima disponibilità, è necessario utilizzare la configurazione della porta di destinazione FC consigliata.

La seguente tabella mostra l'ordine di utilizzo delle porte preferito per le porte di destinazione FC e FC-NVMe integrate. Per gli adattatori di espansione, le porte FC devono essere distribuite in modo che non utilizzino lo stesso ASIC per la connettività. L'ordine degli slot preferiti è riportato nella https://hwu.netapp.com["NetApp Hardware Universe"^] Per la versione del software ONTAP utilizzata dal controller.

FC-NVMe è supportato sui seguenti modelli:

* AFF A300
+
[NOTE]
====
Le porte integrate AFF A300 non supportano FC-NVMe.

====
* AFF A700
* AFF A700
* AFF A800


[NOTE]
====
I sistemi FAS2520 non hanno porte FC integrate e non supportano adattatori aggiuntivi.

====
[cols="3*"]
|===
| Controller | Coppie di porte con ASIC condiviso | Numero di porte di destinazione: Porte preferite 


 a| 
FAS9000, AFF A700, AFF A700 e AFF A800
 a| 
Nessuno
 a| 
Tutte le porte dati si trovano sugli adattatori di espansione. Vedere https://hwu.netapp.com["NetApp Hardware Universe"^] per ulteriori informazioni.



 a| 
8080, 8060 e 8040
 a| 
0e+0f

0g+0h
 a| 
1: 0e

2: 0e, 0g

3: 0e, 0g, 0h

4: 0e, 0g, 0f, 0h



 a| 
FAS8200 e AFF A300
 a| 
0g+0h
 a| 
1: 0 g.

2: 0 g, 0 ore



 a| 
8020
 a| 
0c+0d
 a| 
1: 0c

2: 0c, 0d



 a| 
62xx
 a| 
0a+0b

0c+0d
 a| 
1: 0a

2: 0a, 0c

3: 0a, 0c, 0b

4: 0a, 0c, 0b, 0d



 a| 
32xx
 a| 
0c+0d
 a| 
1: 0c

2: 0c, 0d



 a| 
FAS2554, FAS2552, FAS2600, FAS2720, FAS2750, AFF A200 e AFF A220
 a| 
0c+0d

0e+0f
 a| 
1: 0c

2: 0c, 0e

3: 0c, 0e, 0d

4: 0c, 0e, 0d, 0f

|===