---
permalink: san-config/fc-target-port-supported-speeds-reference.html 
sidebar: sidebar 
keywords: fc, target, port, supported, speeds 
summary: Le porte di destinazione FC possono essere configurate per funzionare a velocità diverse. Impostare la velocità della porta di destinazione in modo che corrisponda alla velocità del dispositivo a cui si connette. Tutte le porte di destinazione utilizzate da un determinato host devono essere impostate alla stessa velocità. 
---
= Velocità supportate dalla porta di destinazione FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le porte di destinazione FC possono essere configurate per funzionare a velocità diverse. Impostare la velocità della porta di destinazione in modo che corrisponda alla velocità del dispositivo a cui si connette. Tutte le porte di destinazione utilizzate da un determinato host devono essere impostate alla stessa velocità.

Le porte di destinazione FC possono essere utilizzate per le configurazioni FC-NVMe esattamente come per le configurazioni FC.

È necessario impostare la velocità della porta di destinazione in modo che corrisponda alla velocità del dispositivo a cui si connette invece di utilizzare la negoziazione automatica. Una porta impostata per la negoziazione automatica può richiedere più tempo per riconnettersi dopo un takeover/giveback o un'altra interruzione.

È possibile configurare le porte integrate e gli adattatori di espansione in modo che funzionino alle seguenti velocità. Ogni porta del controller e dell'adattatore di espansione può essere configurata singolarmente per diverse velocità in base alle esigenze.

[cols="4*"]
|===
| Porte da 4 GB | Porte da 8 GB | Porte da 16 GB | Porte da 32 GB 


 a| 
* 4 GB
* 2 GB
* 1 GB

 a| 
* 8 GB
* 4 GB
* 2 GB

 a| 
* 16 GB
* 8 GB
* 4 GB

 a| 
* 32 GB
* 16 GB
* 8 GB


|===
[NOTE]
====
Le porte UTA2 possono utilizzare un adattatore SFP+ da 8 GB per supportare velocità da 8, 4 e 2 GB, se necessario.

====