---
permalink: san-config/fcoe-supported-hop-count-reference.html 
sidebar: sidebar 
keywords: fcoe, supported, hop, count 
summary: 'Il numero massimo di hop Fibre Channel over Ethernet (FCoE) supportati tra un host e un sistema storage dipende dal fornitore dello switch e dal supporto del sistema storage per le configurazioni FCoE.' 
---
= Numero di hop supportati da FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il numero massimo di hop Fibre Channel over Ethernet (FCoE) supportati tra un host e un sistema storage dipende dal fornitore dello switch e dal supporto del sistema storage per le configurazioni FCoE.

Il numero di hop viene definito come il numero di switch nel percorso tra l'iniziatore (host) e la destinazione (sistema di storage). La documentazione di Cisco Systems fa anche riferimento a questo valore come _diametro del fabric SAN_.

Per FCoE, è possibile collegare gli switch FCoE agli switch FC.

Per le connessioni FCoE end-to-end, gli switch FCoE devono eseguire una versione del firmware che supporti i collegamenti Ethernet tra switch (ISL).

La tabella seguente elenca i conteggi massimi di hop supportati:

[cols="2*"]
|===
| Cambiare fornitore | Numero di hop supportato 


 a| 
Brocade
 a| 
7 per FC

5 per FCoE



 a| 
Cisco
 a| 
7

Fino a 3 switch possono essere switch FCoE.

|===