---
permalink: san-config/fibre-channel-fcoe-zoning-concept.html 
sidebar: sidebar 
keywords: fibre, channel, fcoe zoning 
summary: 'Una zona FC, FC-NVMe o FCoE è un raggruppamento logico di una o più porte all"interno di un fabric. Affinché i dispositivi possano vederti, connettersi, creare sessioni e comunicare tra loro, entrambe le porte devono avere un"appartenenza di zona comune. Si consiglia di utilizzare lo zoning Single Initiator.' 
---
= Panoramica dello zoning FCoE e Fibre Channel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una zona FC, FC-NVMe o FCoE è un raggruppamento logico di una o più porte all'interno di un fabric. Affinché i dispositivi possano vederti, connettersi, creare sessioni e comunicare tra loro, entrambe le porte devono avere un'appartenenza di zona comune. Si consiglia di utilizzare lo zoning Single Initiator.



== Motivi per lo zoning

* Lo zoning riduce o elimina _crosstalk_ tra gli HBA iniziatori.
+
Ciò si verifica anche in ambienti di piccole dimensioni ed è uno degli argomenti migliori per l'implementazione dello zoning. I sottoinsiemi di fabric logici creati con lo zoning eliminano i problemi di crosstalk.

* Lo zoning riduce il numero di percorsi disponibili per una determinata porta FC, FC-NVMe o FCoE e riduce il numero di percorsi tra un host e una particolare LUN visibili.
+
Ad esempio, alcune soluzioni di multipathing del sistema operativo host hanno un limite al numero di percorsi che possono gestire. Lo zoning può ridurre il numero di percorsi che un driver multipathing del sistema operativo vede. Se un host non dispone di una soluzione multipathing installata, è necessario verificare che sia visibile un solo percorso a un LUN utilizzando lo zoning nel fabric o una combinazione di mappatura LUN selettiva (SLM) e portset in SVM.

* Lo zoning aumenta la sicurezza limitando l'accesso e la connettività agli end-point che condividono una zona comune.
+
Le porte che non hanno zone in comune non possono comunicare tra loro.

* Lo zoning migliora l'affidabilità DELLA SAN isolando i problemi che si verificano e aiuta a ridurre i tempi di risoluzione dei problemi limitando lo spazio dei problemi.




== Consigli per lo zoning

* È necessario implementare lo zoning in qualsiasi momento, se quattro o più host sono connessi a una SAN o se SLM non è implementato sui nodi di una SAN.
* Sebbene sia possibile utilizzare lo zoning dei nomi dei nodi in tutto il mondo con alcuni fornitori di switch, è necessario utilizzare lo zoning dei nomi delle porte in tutto il mondo per definire correttamente una porta specifica e utilizzare NPIV in modo efficace.
* È necessario limitare le dimensioni della zona mantenendo la gestibilità.
+
È possibile sovrapporre più zone per limitare le dimensioni. Idealmente, viene definita una zona per ciascun host o cluster di host.

* Utilizzare lo zoning a singolo iniziatore per eliminare il crosstalk tra gli HBA iniziatori.

