---
permalink: san-config/host-support-multipathing-concept.html 
sidebar: sidebar 
keywords: host, support, multipathing 
summary: 'ONTAP utilizza sempre ALUA (Asymmetric Logical Unit Access) per i percorsi FC e iSCSI. Assicurarsi di utilizzare configurazioni host che supportino ALUA per i protocolli FC e iSCSI.' 
---
= Supporto ONTAP per multipathing di host SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utilizza il software ALUA (Asymmetric Logical Unit Access) per il multipathing con gli host FC e iSCSI.

A partire da ONTAP 9,5, il failover/giveback della coppia ha (Multipath High Availability) è supportato per gli host NVMe utilizzando l'accesso asincrono al namespace (ANA). In ONTAP 9,4, NVMe supporta solo un percorso dall'host alla destinazione, pertanto l'host dell'applicazione deve gestire il failover del percorso al partner ha.

Per informazioni su quali configurazioni host specifiche supportano ALUA o ANA, consultare https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^] e. https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configurazione host SAN ONTAP"] per il sistema operativo host.

Il software di multipathing, noto anche come MPIO (multipath I/O), è consigliato nelle configurazioni HA. Il software di multipathing è necessario sull'host SAN per consentire l'accesso a una LUN o a uno spazio dei nomi NVMe tramite più percorsi. Presenta al sistema operativo un singolo disco per tutti i percorsi verso una LUN o uno spazio dei nomi NVMe. Senza di esso, il sistema operativo potrebbe trattare ciascun percorso come un disco separato, con conseguente danneggiamento dei dati.

La soluzione è considerata avere più percorsi se si dispone di uno dei seguenti elementi:

* Una singola porta iniziatore nell'host che si collega a più LIF SAN nella SVM
* Più porte initiator collegate a una singola LIF SAN nella SVM
* Più porte initiator collegate a più LIF SAN nella SVM


È consigliabile utilizzare Selective LUN Map, FC switch zoning o portsets per limitare i percorsi utilizzati per accedere a LUN e namespace.

.Informazioni correlate
Scopri di più su link:../san-admin/multipath-automatic-lif-failover-support.html["Configurazioni SAN multipath supportate da ONTAP"].



== Numero consigliato di percorsi da host a nodi nel cluster

Non superare più di otto percorsi dall'host a ciascun nodo del cluster. Non superare il numero totale di percorsi supportati per il sistema operativo host e il multipathing utilizzato sull'host.

Se nel cluster sono presenti quattro o più nodi o più di quattro porte di destinazione utilizzate dalle SVM in uno dei nodi, È possibile utilizzare i seguenti metodi per limitare il numero di percorsi che è possibile utilizzare per accedere alle LUN sui nodi in modo da non superare il numero massimo consigliato di otto percorsi.

* link:selective-lun-map-concept.html["Mappa LUN selettiva (SLM)"]
+
SLM riduce il numero di percorsi dall'host alla LUN ai soli percorsi presenti sul nodo proprietario della LUN e sul nodo partner HA del proprietario. SLM è abilitato per impostazione predefinita. È necessario disporre di almeno due percorsi per ogni LUN che si connettono a ciascun nodo di reporting tramite SLM utilizzato dalla storage virtual machine (SVM) nel cluster. Ciò elimina i singoli punti di guasto e consente al sistema di sopravvivere a eventuali guasti dei componenti.

* link:../san-admin/limit-lun-access-portsets-igroups-concept.html["Portset"]
+
I portset possono essere utilizzati con SLM per limitare ulteriormente l'accesso di determinate destinazioni a determinati iniziatori. Quando si utilizza SLM con i portset, i LUN saranno accessibili sull'insieme di LIF nel portset sul nodo che possiede il LUN e sul partner ha di quel nodo.

* Mappature del gruppo initiator (igroup) dal tuo host
+
È possibile definire gli igroup e mapparli alle LUN per controllare quali initiator hanno accesso alle LUN.

* link:../san-config/fc-fcoe-recommended-zoning-configuration.html["Zoning dello switch FC"]
+
È necessario creare una configurazione dello zoning se l'host non dispone di una soluzione di multipath I/O installata, se quattro o più host sono connessi alla SAN o se SLM non è implementato sui nodi del cluster.


