---
permalink: san-config/index.html 
sidebar: sidebar 
keywords: san, configure, configuration, fc, iscsi, nvme, host, fcoe, topology, topologies, connect, connecting, limits 
summary: Topologie FC-NVMe, FC, iSCSI e FCoE supportate per la connessione dei computer host ai nodi e limiti supportati per i componenti SAN. 
---
= Panoramica della configurazione SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una rete SAN è costituita da una soluzione storage connessa agli host tramite un protocollo di trasporto SAN come iSCSI o FC. È possibile configurare la RETE SAN in modo che la soluzione di storage si colleghi agli host tramite uno o più switch.  Se si utilizza iSCSI, è anche possibile configurare la SAN in modo che la soluzione di storage si colleghi direttamente all'host senza utilizzare uno switch.

In una SAN, più host, utilizzando sistemi operativi diversi, come Windows, Linux o UNIX, possono accedere alla soluzione di storage contemporaneamente.  È possibile utilizzare link:../san-admin/selective-lun-map-concept.html["Mappatura selettiva delle LUN"] e. link:../san-admin/create-port-sets-binding-igroups-task.html["portset"] per limitare l'accesso ai dati tra gli host e lo storage.

Per iSCSI, la topologia di rete tra la soluzione di storage e gli host viene definita rete.  Per FC, FC/NVMe e FCoE la topologia della rete tra la soluzione di storage e gli host è indicata come fabric. Per creare la ridondanza, che protegge dai rischi di perdita dell'accesso ai dati, è necessario impostare la SAN con coppie ha in una configurazione multi-network o multi-fabric.  Le configurazioni che utilizzano nodi singoli o reti/fabric singoli non sono completamente ridondanti, quindi non sono consigliate.

Una volta configurato il SAN, è possibile link:../san-admin/provision-storage.html["Provisioning dello storage per iSCSI o FC"]oppure è possibile link:../san-admin/create-nvme-namespace-subsystem-task.html["Eseguire il provisioning dello storage per FC/NVMe"].  Quindi, è possibile connettersi agli host per iniziare la manutenzione dei dati.

Il supporto del protocollo SAN varia in base alla versione di ONTAP in uso, alla piattaforma e alla configurazione in uso. Per ulteriori informazioni sulla configurazione specifica, consultare la link:https://imt.netapp.com/matrix/["Tool di matrice di interoperabilità NetApp"].

.Informazioni correlate
* link:../san-admin/index.html["Panoramica dell'amministrazione SAN"]
* link:../nvme/support-limitations.html["Configurazione, supporto e limitazioni NVMe"]

