---
permalink: san-config/iscsi-config-concept.html 
sidebar: sidebar 
keywords: considerations, iscsi, configurations 
summary: Quando si configura la configurazione iSCSI, è necessario prendere in considerazione diversi aspetti. 
---
= Considerazioni per la panoramica delle configurazioni iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura la configurazione iSCSI, è necessario prendere in considerazione diversi aspetti.

* È possibile configurare la configurazione iSCSI con nodi singoli o con coppie ha.
+
La connessione diretta o l'utilizzo di switch Ethernet sono supportati per la connettività. È necessario creare LIF per entrambi i tipi di connettività

* È necessario configurare una LIF di gestione per ogni macchina virtuale di storage (SVM) che supporti LA SAN.
* La mappatura LUN selettiva (SLM) limita i percorsi utilizzati per accedere alle LUN di proprietà di una coppia ha.
+
Questo è il comportamento predefinito per i LUN creati con le release di ONTAP.

* Le coppie HA sono definite come nodi di reporting per i percorsi Active/Optimized e Active/UnOptimized che verranno utilizzati dall'host per accedere alle LUN tramite ALUA.
* È consigliabile che tutte le SVM nelle configurazioni ISCSI dispongano di almeno due LIF per nodo in reti Ethernet separate per ridondanza e MPIO su percorsi multipli.
* È necessario creare uno o più percorsi iSCSI da ciascun nodo di una coppia ha, utilizzando le interfacce logiche (LIF) per consentire l'accesso alle LUN servite dalla coppia ha.
+
In caso di guasto di un nodo, i file LIF non migrano né assumono gli indirizzi IP del nodo partner guasto. Il software MPIO, che utilizza ALUA sull'host, è invece responsabile della selezione dei percorsi appropriati per l'accesso LUN tramite LIF.

* Le VLAN offrono vantaggi specifici, come una maggiore sicurezza e una maggiore affidabilità di rete che è possibile sfruttare in iSCSI.

