---
permalink: san-config/supported-fc-ports-concept.html 
sidebar: sidebar 
keywords: supported, fc, ports 
summary: Il numero di porte FC integrate e di porte CNA/UTA2 configurate per FC varia in base al modello del controller. Le porte FC sono disponibili anche tramite adattatori di espansione FC target supportati o schede UTA2 aggiuntive configurate con adattatori FC SFP+. 
---
= Porte FC supportate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il numero di porte FC integrate e di porte CNA/UTA2 configurate per FC varia in base al modello del controller. Le porte FC sono disponibili anche tramite adattatori di espansione FC target supportati o schede UTA2 aggiuntive configurate con adattatori FC SFP+.



== Porte FC, UTA e UTA2 integrate

* Le porte onboard possono essere configurate singolarmente come porte FC di destinazione o iniziatore.
* Il numero di porte FC integrate varia a seconda del modello di controller.
+
Il https://hwu.netapp.com["NetApp Hardware Universe"^] Contiene un elenco completo delle porte FC integrate su ciascun modello di controller.

* Le porte FC sono disponibili solo sui sistemi FAS2240 tramite l'adattatore di espansione X1150A-R6.
+
I sistemi FAS2220 e FAS2520 non supportano FC.





== Porte FC dell'adattatore di espansione di destinazione

* Gli adattatori di espansione di destinazione disponibili variano a seconda del modello di controller.
+
Il https://hwu.netapp.com["NetApp Hardware Universe"^] contiene un elenco completo degli adattatori di espansione di destinazione per ciascun modello di controller.

* Le porte di alcuni adattatori di espansione FC sono configurate in fabbrica come iniziatori o destinazioni e non possono essere modificate.
+
Altre porte possono essere configurate singolarmente come porte FC di destinazione o inizializzatore, proprio come le porte FC integrate. Un elenco completo è disponibile in https://hwu.netapp.com["NetApp Hardware Universe"^].


