---
permalink: upgrade/choose-target-version.html 
sidebar: sidebar 
keywords: upgrade, ontap, choose target release, target release 
summary: Scegli la release di upgrade ONTAP di destinazione in base ai consigli NetApp, alle esigenze di determinate funzionalità o alla versione minima consigliata per le performance. 
---
= Scegliere una versione ONTAP di destinazione consigliata da NetApp per un aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzando Upgrade Advisor per generare un piano di upgrade per il cluster, è prevista una release ONTAP di destinazione consigliata per l'aggiornamento.  Il consiglio fornito da Upgrade Advisor si basa sulla configurazione corrente e sulla versione ONTAP corrente.

Se non si utilizza Upgrade Advisor per pianificare l'aggiornamento, è necessario scegliere la versione ONTAP di destinazione per l'aggiornamento in base ai consigli NetApp o la versione minima necessaria per soddisfare le esigenze di prestazioni del .

* Aggiornamento all'ultima versione disponibile (consigliato)
+
NetApp consiglia di aggiornare il software ONTAP all'ultima versione della patch dell'ultima versione numerata di ONTAP.  Se ciò non è possibile perché l'ultima release numerata non è supportata dai sistemi storage nel cluster, è necessario eseguire l'aggiornamento all'ultima release numerata supportata.

* Versione minima consigliata
+
Per limitare l'upgrade alla release minima consigliata per il cluster, consulta la sezione link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["Release ONTAP minime consigliate"^] Per determinare la versione di ONTAP a cui eseguire l'aggiornamento.


