---
permalink: upgrade/concept_upgrade_methods.html 
sidebar: sidebar 
keywords: upgrade, methods, andu, ndu, automated, automatic, system manager, cli, nondisruptive, disruptive 
summary: 'Il metodo utilizzato per l"aggiornamento dipende dalla configurazione. Se disponibile, l"aggiornamento automatico senza interruzioni (ANDU) con System Manager è il metodo preferito.' 
---
= Metodi di aggiornamento del software ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi eseguire un aggiornamento automatico del software ONTAP utilizzando Gestione sistema. In alternativa, è possibile eseguire un aggiornamento automatico o manuale utilizzando l'interfaccia a riga di comando (CLI) di ONTAP. Il metodo utilizzato per aggiornare ONTAP dipende dalla configurazione, dalla versione corrente di ONTAP e dal numero di nodi nel cluster. NetApp consiglia di utilizzare System Manager per eseguire aggiornamenti automatici, a meno che la configurazione non richieda un approccio diverso. Ad esempio, se disponi di una configurazione MetroCluster con 4 nodi in cui è in esecuzione ONTAP 9,3 o versione successiva, dovresti utilizzare System Manager per eseguire un upgrade automatico (talvolta indicato come upgrade automatico senza interruzioni o ANDU). Se disponi di una configurazione MetroCluster con 8 nodi in esecuzione su ONTAP 9,2 o versione precedente, devi utilizzare la CLI per eseguire un aggiornamento manuale.

È possibile eseguire un aggiornamento utilizzando il processo di aggiornamento in sequenza o il processo di aggiornamento in batch. Entrambi sono senza interruzioni.

.Rolling upgrade di ONTAP
Durante il processo di aggiornamento continuo, un nodo viene portato offline e aggiornato mentre il partner assume il controllo dello storage. Quando l'aggiornamento del nodo è completo, il nodo partner restituisce il controllo al nodo proprietario originale e il processo viene ripetuto sul nodo partner. Ogni coppia ha aggiuntiva viene aggiornata in sequenza fino a quando tutte le coppie ha non eseguono la release di destinazione. L'Rolling upgrade è l'impostazione predefinita per i cluster con meno di 8 nodi.

.Aggiornamenti batch ONTAP
Nel processo di batch upgrade, il cluster viene diviso in diversi batch, ciascuno dei quali contiene più coppie ha. Nel primo batch, viene eseguito l'upgrade di un nodo di ciascuna coppia ha, seguito dai relativi partner ha. Il processo viene quindi ripetuto in sequenza per i batch rimanenti. Il processo di aggiornamento in batch è l'impostazione predefinita per i cluster di 8 o più nodi.

Per gli upgrade automatici, ONTAP installa automaticamente l'immagine ONTAP di destinazione su ciascun nodo, convalida i componenti del cluster per garantire l'upgrade senza interruzioni del cluster, quindi esegue un batch o un Rolling upgrade in background in base al numero di nodi. Per gli aggiornamenti manuali, l'amministratore conferma manualmente che ogni nodo del cluster è pronto per l'aggiornamento, quindi esegue i passaggi necessari per eseguire un Rolling upgrade.



== Metodi di aggiornamento ONTAP consigliati in base alla configurazione

I metodi di aggiornamento supportati dalla configurazione in uso sono elencati in ordine di utilizzo consigliato.

[cols="4"]
|===
| Configurazione | Versione di ONTAP | Numero di nodi | Metodo di aggiornamento consigliato 


| Standard | 9.0 o versione successiva | 2 o più  a| 
* xref:task_upgrade_andu_sm.html[Automazione senza interruzioni con System Manager]
* xref:task_upgrade_andu_cli.html[Automazione senza interruzioni con CLI]




| Standard | 9.0 o versione successiva | Singola | xref:task_upgrade_disruptive_automated_cli.html[Interruzione automatizzata] 


| MetroCluster | 9.3 o versione successiva | 8  a| 
* xref:task_upgrade_andu_cli.html[Automazione senza interruzioni con CLI]
* xref:task_updating_a_four_or_eight_node_mcc.html[Manuale senza interruzioni per MetroCluster a 4 o 8 nodi utilizzando la CLI]




| MetroCluster | 9.3 o versione successiva | 2,4  a| 
* xref:task_upgrade_andu_sm.html[Automazione senza interruzioni con System Manager]
* xref:task_upgrade_andu_cli.html[Automazione senza interruzioni con CLI]




| MetroCluster | 9.2 o versioni precedenti | 4, 8 | xref:task_updating_a_four_or_eight_node_mcc.html[Manuale senza interruzioni per MetroCluster a 4 o 8 nodi utilizzando la CLI] 


| MetroCluster | 9.2 o versioni precedenti | 2 | xref:task_updating_a_two_node_metrocluster_configuration_in_ontap_9_2_and_earlier.html[Manuale senza interruzioni per MetroCluster a 2 nodi utilizzando la CLI] 
|===
L'utilizzo di System Manager è il metodo di aggiornamento consigliato per tutti gli aggiornamenti delle patch, indipendentemente dalla configurazione.


NOTE: R xref:task_updating_an_ontap_cluster_disruptively.html[aggiornamento manuale con interruzioni delle attività] può essere eseguita su qualsiasi configurazione.  Tuttavia, non si consiglia di eseguire un aggiornamento senza interruzioni, a meno che non sia possibile disattivare il cluster per tutta la durata dell'aggiornamento. Se si opera in un ambiente SAN, è necessario essere pronti a chiudere o sospendere tutti i client SAN prima di eseguire un aggiornamento disgregativo. Gli aggiornamenti disruptive vengono eseguiti utilizzando l'interfaccia utente di ONTAP.
