---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: Un cluster ONTAP a versione mista è costituito da nodi che eseguono due release principali di ONTAP diverse, come ONTAP 9.8 e 9.12.1. I cluster ONTAP con versione mista sono supportati solo in scenari specifici. 
---
= Verificare la compatibilità delle versioni di ONTAP per i cluster di versioni miste
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In un cluster ONTAP versione mista, i nodi eseguono due diverse versioni principali di ONTAP per un breve periodo di tempo. Ad esempio, un cluster con nodi che eseguono ONTAP 9,8 e 9.12.1 o ONTAP 9.9.1 e 9.13.1 è una versione mista. I cluster con nodi che eseguono livelli di patch diversi all'interno della stessa versione, come ONTAP 9,9.1P1 e 9,9.1P5, non sono cluster di versioni miste.


NOTE: I cluster di versioni miste non sono supportati per Cloud Volumes ONTAP.

NetApp supporta cluster ONTAP a versione mista per periodi di tempo limitati e in scenari specifici.

Di seguito sono riportati gli scenari più comuni in cui un cluster ONTAP sarà in uno stato di versione mista:

* Aggiornamenti del software ONTAP in cluster di grandi dimensioni
+
L'upgrade di tutti i nodi di un cluster di grandi dimensioni può richiedere diversi giorni o settimane. Il cluster entra e rimane in uno stato misto di versione fino all'upgrade di tutti i nodi.

* Gli aggiornamenti del software ONTAP sono necessari quando si prevede di aggiungere nuovi nodi a un cluster
+
È possibile aggiungere nuovi nodi al cluster per espanderne la capacità oppure aggiungere nuovi nodi durante il processo di sostituzione completa dei controller. In entrambi i casi, potrebbe essere necessario immettere uno stato di versione mista per consentire la migrazione dei dati dai controller esistenti ai nuovi nodi nel nuovo sistema.



Per un funzionamento ottimale del cluster, il tempo in cui il cluster si trova in uno stato di versione mista deve essere il più breve possibile. Il periodo di tempo massimo per cui un cluster è idoneo per il supporto in uno stato misto dipende dalla versione più bassa di ONTAP nel cluster.

[cols="2"]
|===
| Se la versione più bassa di ONTAP in esecuzione nel cluster di versioni miste è... | Quindi è possibile rimanere in uno stato di versione mista per un massimo di... 


| ONTAP 9.8 o versione successiva | 90 giorni 


| ONTAP 9.7 o versioni precedenti | 7 giorni 
|===
Mentre il cluster si trova in uno stato di versione mista, non inserire alcun comando che alteri l'operazione o la configurazione del cluster, ad eccezione di quelli richiesti per il processo di aggiornamento o di migrazione dei dati. Ad esempio, attività come la migrazione LIF (ma non solo), operazioni pianificate di failover dello storage o la creazione o l'eliminazione di oggetti su larga scala non devono essere eseguite fino al completamento dell'upgrade e della migrazione dei dati.



== Cluster di versioni miste supportati per gli aggiornamenti software ONTAP

È possibile immettere uno stato di versione mista con qualsiasi versione di ONTAP supportata per un aggiornamento diretto dalla versione corrente più bassa. Ad esempio, se si esegue ONTAP 9.11.1, è possibile immettere uno stato di versione misto con i nodi che eseguono ONTAP 9.15.1. Non è possibile immettere uno stato di versione misto con i nodi che eseguono ONTAP 9.11.1 e ONTAP 9.16.1. ONTAP 9.16.1 non è supportato per l'aggiornamento diretto da ONTAP 9.11.1.


NOTE: Le versioni delle patch (P) ONTAP non hanno alcun impatto sulla compatibilità con i cluster a versione mista. Ad esempio, se si utilizza ONTAP 9.11.1P6, la versione ONTAP corrente per la compatibilità con i cluster a versione mista è ONTAP 9.11.1. Oppure, se si utilizza ONTAP 9.12.1 e si desidera eseguire l'aggiornamento a ONTAP 9.15.1P2, la versione ONTAP di destinazione per la compatibilità con i cluster a versione mista è ONTAP 9.15.1.

Per eseguire l'aggiornamento a una versione di ONTAP non supportata per un aggiornamento diretto dalla versione corrente, è necessario eseguire un aggiornamento a più fasi. In un aggiornamento a più fasi, è necessario prima immettere uno stato di versione mista con la versione più alta supportata per un aggiornamento diretto dalla versione corrente. L'aggiornamento viene completato, quindi viene eseguito un aggiornamento separato alla versione di destinazione. Ad esempio, se la release corrente più bassa è ONTAP 9.10.1 e si desidera eseguire l'aggiornamento a ONTAP 9.16.1, è necessario immettere uno stato di versione mista per aggiornare tutti i nodi a ONTAP 9.14.1; quindi eseguire un aggiornamento separato da ONTAP 9.14.1 a ONTAP 9.16.1. Ulteriori informazioni su link:concept_upgrade_paths.html#types-of-upgrade-paths["aggiornamenti multi-fase"] e link:concept_upgrade_paths.html#supported-upgrade-paths["percorsi di aggiornamento supportati"].

Un cluster di versioni miste può contenere solo due release principali di ONTAP. Ad esempio, puoi avere un cluster in versione mista con nodi che eseguono ONTAP 9.13.1 e 9.15.1 o con nodi che eseguono ONTAP 9.13.1 e 9.16.1. Non puoi avere un cluster in versione mista con nodi che eseguono ONTAP 9.13.1, 9.15.1 e 9.16.1.

[cols="25,25,50"]
|===
| Se la versione corrente di ONTAP è… | E la tua release ONTAP di destinazione è… | Lo stato della versione mista per l'aggiornamento è... 


| 9.16.1 | 9.17.1 | Supportato 


.2+| 9.15.1 | 9.17.1 | Supportato 


| 9.16.1 | Supportato 


.3+| 9.14.1 | 9.17.1 | Supportato 


| 9.16.1 | Supportato 


| 9.15.1 | Supportato 


.4+| 9.13.1 | 9.17.1 | Supportato 


| 9.16.1 | Supportato 


| 9.15.1 | Supportato 


| 9.14.1 | Supportato 


.5+| 9.12.1 | 9.17.1 | Non supportato 


| 9.16.1 | Supportato 


| 9.15.1 | Supportato 


| 9.14.1 | Supportato 


| 9.13.1 | Supportato 


.6+| 9.11.1 | 9.17.1 | Non supportato 


| 9.16.1  a| 
Non supportato



| 9.15.1 | Supportato 


| 9.14.1 | Supportato 


| 9.13.1 | Supportato 


| 9.12.1 | Supportato 


.7+| 9.10.1 | 9.17.1 | Non supportato 


| 9.16.1  a| 
Non supportato



| 9.15.1  a| 
Non supportato



| 9.14.1 | Supportato 


| 9.13.1 | Supportato 


| 9.12.1 | Supportato 


| 9.11.1 | Supportato 


.8+| 9.9.1 | 9.17.1 | Non supportato 


| 9.16.1  a| 
Non supportato



| 9.15.1  a| 
Non supportato



| 9.14.1  a| 
Non supportato



| 9.13.1 | Supportato 


| 9.12.1 | Supportato 


| 9.11.1 | Supportato 


| 9.10.1 | Supportato 


.9+| 9.8 | 9.17.1 | Non supportato 


| 9.16.1  a| 
Non supportato



| 9.15.1  a| 
Non supportato



| 9.14.1  a| 
Non supportato



| 9.13.1  a| 
Non supportato



| 9.12.1 | Supportato 


| 9.11.1 | Supportato 


| 9.10.1  a| 
Supportato



| 9.9.1 | Supportato 
|===


== Aggiunta di nuovi nodi a un cluster ONTAP

Se si prevede di aggiungere nuovi nodi al cluster e tali nodi richiedono una versione minima di ONTAP successiva alla versione attualmente in esecuzione nel cluster, è necessario eseguire eventuali aggiornamenti software supportati sui nodi esistenti nel cluster prima di aggiungere i nuovi nodi. Idealmente, si dovrebbe aggiornare tutti i nodi esistenti alla versione minima di ONTAP richiesta dai nodi che si intende aggiungere al cluster. Tuttavia, se questo non è possibile perché alcuni dei nodi esistenti non supportano la versione successiva di ONTAP, sarà necessario immettere uno stato di versione mista per un periodo di tempo limitato come parte del processo di aggiornamento.

.Fasi
. link:concept_upgrade_methods.html["Eseguire l'upgrade"] i nodi che non supportano la versione ONTAP minima richiesta dai nuovi controller alla versione ONTAP più alta da loro supportata.
+
Ad esempio, se si dispone di un FAS8080 con ONTAP 9.5 e si sta aggiungendo una nuova piattaforma C-Series con ONTAP 9.12.1, è necessario aggiornare il FAS8080 a ONTAP 9.8 (che è la versione ONTAP più recente supportata).

. link:../system-admin/add-nodes-cluster-concept.html["Aggiungere i nuovi nodi al cluster"^].
. link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Migrare i dati"^] dai nodi rimossi dal cluster ai nuovi nodi aggiunti.
. link:../system-admin/remove-nodes-cluster-concept.html["Rimuovere i nodi non supportati dal cluster"^].
. link:concept_upgrade_methods.html["Eseguire l'upgrade"] il cluster alla stessa versione ONTAP e livello di patch in esecuzione sui nuovi nodi o al link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["ultima versione di patch consigliata"^] per la versione ONTAP in esecuzione sui nuovi nodi.
. Verificare che tutti i nodi eseguano la stessa versione ONTAP .
+
.. Mostra la versione ONTAP in esecuzione sul cluster:
+
[source, cli]
----
version
----
.. Mostra la versione ONTAP in esecuzione su ciascun nodo del cluster:
+
[source, cli]
----
version *
----


+
Se c'è una differenza tra la versione ONTAP riportata nell'output per il `version *` (gruppo) e `version` (singoli nodi) comandi, aggiorna tutti i nodi alla stessa versione ONTAP e patch eseguendo un link:concept_upgrade_methods.html["aggiornamento dell'immagine del cluster"].



Per ulteriori informazioni sulla migrazione dei dati, consulta:

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Creare un aggregato e spostare i volumi nei nuovi nodi"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["Impostazione di nuove connessioni iSCSI per gli spostamenti dei volumi SAN"^]
* link:../encryption-at-rest/encrypt-existing-volume-task.html["Spostamento di volumi con crittografia"^]

