---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, requirements, metrocluster, configuration, mcc, general, normal, operations, switchover 
summary: Prima di aggiornare il software ONTAP su una configurazione MetroCluster, i cluster devono soddisfare determinati requisiti. 
---
= Verificare i requisiti di aggiornamento di ONTAP per le configurazioni MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare il software ONTAP su una configurazione MetroCluster, i cluster devono soddisfare determinati requisiti.

* Entrambi i cluster devono eseguire la stessa versione di ONTAP.
+
È possibile verificare la versione di ONTAP utilizzando il comando version.

* Se si sta eseguendo un aggiornamento ONTAP importante, la configurazione MetroCluster deve essere in modalità normale.
* Se si sta eseguendo un aggiornamento di patch ONTAP, la configurazione MetroCluster può essere in modalità normale o di switchover.
* Per tutte le configurazioni, ad eccezione dei cluster a due nodi, è possibile aggiornare entrambi i cluster senza interruzioni allo stesso tempo.
+
Per un upgrade senza interruzioni in cluster a due nodi, i cluster devono essere aggiornati un nodo alla volta.

* Gli aggregati in entrambi i cluster non devono trovarsi nello stato RAID di risyncing.
+
Durante la riparazione MetroCluster , gli aggregati speculari vengono risincronizzati.  È possibile verificare se la configurazione MetroCluster è in questo stato utilizzando `storage aggregate plex show -in-progress true` comando.  Se sono presenti aggregati in fase di sincronizzazione, non eseguire un aggiornamento finché la risincronizzazione non sarà completata.

+
Scopri di più su  `storage aggregate plex show` nel link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-plex-show.html["Riferimento al comando ONTAP"^] .

* Le operazioni di switchover negoziate non avranno esito positivo durante l'aggiornamento.
+
Per evitare problemi con le operazioni di upgrade o revert, non tentare uno switchover non pianificato durante un'operazione di upgrade o revert, a meno che tutti i nodi su entrambi i cluster non eseguano la stessa versione di ONTAP.





== Requisiti di configurazione per il normale funzionamento dell'MetroCluster

* I LIF SVM di origine devono essere attivi e posizionati sui nodi domestici.
+
Non è necessario che le LIF dei dati per le SVM di destinazione siano attive o che si trovino sui propri nodi domestici.

* Tutti gli aggregati del sito locale devono essere online.
* Tutti i volumi root e di dati di proprietà delle SVM del cluster locale devono essere online.




== Requisiti di configurazione per lo switchover di MetroCluster

* Tutti i LIF devono essere attivi e posizionati sui propri nodi domestici.
* Tutti gli aggregati devono essere online, ad eccezione degli aggregati root del sito DR.
+
Gli aggregati root del sito DR sono offline durante alcune fasi di switchover.

* Tutti i volumi devono essere online.


.Informazioni correlate
link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html["Verifica dello stato di rete e storage per le configurazioni MetroCluster"]
