---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: Un cluster ONTAP a versione mista è costituito da nodi che eseguono due release principali di ONTAP diverse, come ONTAP 9.8 e 9.12.1. I cluster ONTAP a versione mista sono supportati da NetApp solo in scenari specifici. 
---
= Cluster ONTAP a versione mista
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un cluster ONTAP a versione mista è costituito da nodi che eseguono due diverse release principali di ONTAP per un periodo di tempo limitato.  Ad esempio, se un cluster è costituito da nodi che eseguono ONTAP 9.8 e 9.12.1, si tratta di un cluster a versione mista.  Analogamente, un cluster in cui i nodi eseguono ONTAP 9.9.1 e 9.13.1 sarebbe un cluster a versione mista.  NetApp supporta cluster ONTAP a versione mista per periodi di tempo limitati e in scenari specifici.

Di seguito sono riportati gli scenari più comuni in cui un cluster ONTAP si trova in uno stato di versione mista:

* Aggiornamenti del software ONTAP in cluster di grandi dimensioni
* Gli aggiornamenti del software ONTAP sono necessari quando si prevede di aggiungere nuovi nodi a un cluster


Le informazioni si applicano alle versioni di ONTAP che supportano i sistemi con piattaforme NetApp, come AFF A-Series e C-Series, ASA, FAS e C-Series. Le informazioni non sono valide per le versioni cloud di ONTAP (9.x.0), ad esempio 9.12.0.



== Requisiti per i cluster ONTAP a versione mista

Se il cluster deve entrare in uno stato di versione ONTAP misto, è necessario essere a conoscenza di requisiti e restrizioni importanti.

* In un cluster non possono essere presenti più di due versioni principali di ONTAP diverse per volta. I cluster con nodi in esecuzione con diversi livelli di patch P o D della stessa release di ONTAP, come ONTAP 9.9.1P1 e 9.9.1P5, non sono considerati cluster ONTAP con versione mista.
* Mentre il cluster si trova in uno stato di versione mista, non inserire alcun comando che alteri l'operazione o la configurazione del cluster, ad eccezione di quelli richiesti per il processo di aggiornamento o di migrazione dei dati.  Ad esempio, attività come (ma non solo) migrazione LIF, operazioni di failover dello storage pianificate o creazione o distruzione di oggetti su larga scala non devono essere eseguite fino al completamento dell'aggiornamento e della migrazione dei dati.
* Per un funzionamento ottimale del cluster, il tempo in cui il cluster si trova in uno stato di versione mista deve essere il più breve possibile.  La durata massima di permanenza di un cluster in uno stato di versione mista dipende dalla versione ONTAP più bassa del cluster.
+
[cols="2*"]
|===
| Se la versione più bassa di ONTAP in esecuzione nel cluster di versioni miste è: | Quindi, è possibile rimanere in uno stato di versione misto per un massimo di 


| ONTAP 9.8 o superiore | 90 giorni 


| ONTAP 9.7 o versione precedente | 7 giorni 
|===
* A partire da ONTAP 9.8, un cluster ONTAP con versione mista può includere un massimo di 4 release principali. Ad esempio, un cluster ONTAP con versione mista potrebbe avere nodi che eseguono ONTAP 9.8 e 9.12.1 o nodi che eseguono ONTAP 9.9.1 e 9.13.1. Un cluster ONTAP con versione mista con nodi che eseguono ONTAP 9.8 e 9.13.1 non sarebbe supportato, perché questo cluster con versione mista si estende su 5 release principali.




== Aggiornamento della versione ONTAP di un cluster di grandi dimensioni

Uno scenario per l'accesso a uno stato di cluster con versione mista prevede l'aggiornamento della versione ONTAP di un cluster con più nodi per sfruttare le funzionalità disponibili nelle versioni successive di ONTAP 9. Quando è necessario aggiornare la versione ONTAP di un cluster più grande, si inserisce uno stato del cluster a versione mista per un periodo di tempo durante l'aggiornamento di ciascun nodo del cluster.



== Aggiunta di nuovi nodi al cluster

Un altro scenario per l'inserimento di uno stato di cluster con versione mista prevede l'aggiunta di nuovi nodi al cluster. È possibile aggiungere nuovi nodi al cluster per espanderne la capacità oppure aggiungere nuovi nodi durante il processo di sostituzione completa dei controller. In entrambi i casi, è necessario abilitare la migrazione dei dati dai controller esistenti ai nuovi nodi nel nuovo sistema.

Se si prevede di aggiungere nuovi nodi al cluster e tali nodi richiedono una versione minima di ONTAP successiva alla versione attualmente in esecuzione nel cluster, è necessario eseguire gli aggiornamenti software supportati sui nodi esistenti nel cluster prima di aggiungere i nuovi nodi.

Idealmente, si dovrebbe aggiornare tutti i nodi esistenti alla versione minima di ONTAP richiesta dai nodi che si intende aggiungere al cluster. Tuttavia, se ciò non è possibile perché alcuni dei nodi esistenti non supportano la versione successiva di ONTAP, sarà necessario inserire uno stato di versione mista per un periodo di tempo limitato come parte del processo di aggiornamento. Se si dispone di nodi che non supportano la versione minima di ONTAP richiesta dai nuovi controller, attenersi alla seguente procedura:

. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["Eseguire l'upgrade"] Tutti i nodi del cluster che supportano la versione minima di ONTAP richiesta dai nuovi controller.
. Aggiungere i nuovi nodi al cluster.
+
Utilizzare il cluster di comandi ONTAP `add-node -allow-mixed-version-join` al livello di privilegio avanzato per unirsi ai nuovi nodi.

. Migrare i dati da qualsiasi nodo che non può essere aggiornato a un nodo che esegue la versione ONTAP superiore.
. link:https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html["Rimuovere i nodi non supportati dal cluster"^].
+
Utilizzare il cluster di comandi ONTAP `remove-node -skip-last-low-version-node-check` per rimuovere questi nodi. (In ONTAP 9.3 e versioni precedenti, utilizzare `cluster unjoin -skip-last-low-version-node-check` comando.)



Per ulteriori informazioni sulla migrazione dei dati, consulta:

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Creare un aggregato e spostare i volumi nei nuovi nodi"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["Impostazione di nuove connessioni iSCSI per gli spostamenti dei volumi SAN"^]
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["Spostamento di volumi con crittografia"^]

