---
permalink: upgrade/concept_when_you_need_to_update_the_disk_qualification_package.html 
sidebar: sidebar 
keywords: upgrade, ontap, dqp, disk, qualification, package 
summary: 'Dopo l"aggiornamento di ONTAP, l"aggiunta di un nuovo tipo o dimensione di unità o l"aggiornamento del firmware del disco, è necessario aggiornare anche il pacchetto di qualifica del disco ONTAP (DQP).' 
---
= Aggiornare il pacchetto di Disk Qualification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver aggiornato il software ONTAP, è necessario scaricare e installare il pacchetto di qualifica dei dischi ONTAP (DQP).  Il DQP non viene aggiornato come parte di un aggiornamento del ONTAP.

Il DQP contiene i parametri appropriati per l'interazione ONTAP con tutte le unità appena qualificate. Se la versione del DQP in uso non contiene informazioni relative a un'unità appena qualificata, ONTAP non disporrà delle informazioni necessarie per configurare correttamente l'unità.

È consigliabile aggiornare il DQP ogni trimestre.  È inoltre necessario aggiornare il DQP per i seguenti motivi:

* Quando Aggiungi un nuovo tipo di disco o una nuova dimensione a un nodo del cluster
+
Ad esempio, se si dispone già di dischi da 1 TB e si aggiungono dischi da 2 TB, è necessario verificare la disponibilità dell'aggiornamento DQP più recente.

* Ogni volta che si aggiorna il firmware del disco
* Ogni volta che sono disponibili firmware del disco o file DQP più recenti


.Informazioni correlate
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["Download NetApp: Pacchetto di qualificazione dei dischi"^]
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Download NetApp: Firmware del disco"]

