---
permalink: upgrade/considerations-authenticate-ssh-public-key-fips-concept.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, ssl, fips mode, host key algorithm 
summary: 'Se la modalità SSL FIPS è attivata su un cluster in cui gli account amministratore autenticano con una chiave pubblica SSH, è necessario assicurarsi che l"algoritmo della chiave host sia supportato sulla release di destinazione prima di aggiornare ONTAP.' 
---
= Verificare il supporto dell'algoritmo della chiave host SSH prima dell'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la modalità SSL FIPS è attivata su un cluster in cui gli account amministratore autenticano con una chiave pubblica SSH, è necessario assicurarsi che l'algoritmo della chiave host sia supportato sulla release di destinazione prima di aggiornare ONTAP.

La seguente tabella indica gli algoritmi del tipo di chiave host supportati per le connessioni SSH ONTAP. Questi tipi di chiave non si applicano alla configurazione dell'autenticazione pubblica SSH.

[cols="30,30,30"]
|===


| Release di ONTAP | Tipi di chiave supportati in modalità FIPS | Tipi di chiave supportati in modalità non FIPS 


 a| 
9.11.1 e versioni successive
 a| 
ecdsa-sha2-nistp256
 a| 
ecdsa-sha2-nistp256 + rsa-sha2-512 + rsa-sha2-256 + ssh-ed25519 + ssh-dss + ssh-rsa



 a| 
9.10.1 e versioni precedenti
 a| 
ecdsa-sha2-nistp256 + ssh-ed25519
 a| 
ecdsa-sha2-nistp256 + ssh-ed25519 + ssh-dss + ssh-rsa

|===

NOTE: il supporto per l'algoritmo della chiave host ssh-ed25519 è stato rimosso nel 9.11.1

Per ulteriori informazioni, vedere link:../networking/configure_network_security_using_federal_information_processing_standards_@fips@.html["Configurare la sicurezza di rete utilizzando FIPS"].

Gli account a chiave pubblica SSH esistenti senza gli algoritmi a chiave supportati devono essere riconfigurati con un tipo di chiave supportato prima di abilitare l'aggiornamento, altrimenti l'autenticazione dell'amministratore non avrà esito positivo.

link:../authentication/enable-ssh-public-key-accounts-task.html["Scopri di più sull'abilitazione degli account a chiave pubblica SSH."]
