---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, upgrade health checker, advisor, digital advisor, active iq, create an upgrade plan 
summary: È possibile utilizzare Upgrade Advisor in Active IQ Digital Advisor o Upgrade Health Checker per generare automaticamente un report di aggiornamento specifico per il proprio ambiente e la configurazione del cluster. 
---
= Preparati per un upgrade di ONTAP con Upgrade Advisor o Upgrade Health Checker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Upgrade Advisor in Active IQ Digital Advisor o Upgrade Health Checker per generare automaticamente un report di upgrade specifico per il proprio ambiente e la configurazione del cluster. Entrambi gli strumenti forniscono intelligence che aiuta a pianificare l'upgrade, identificare blocker e avvisi e ridurre al minimo incertezza e rischio.



[[prepare-to-upgrade-with-upgrade-advisor]]
== Prepararsi per l'aggiornamento con Upgrade Advisor

Upgrade Advisor identifica i problemi nel tuo ambiente che possono essere risolti aggiornando a una versione più recente di ONTAP e fornisce un report dei problemi di cui potresti dover essere a conoscenza nella versione di ONTAP a cui stai effettuando l'upgrade. Upgrade Advisor fornisce anche un percorso di upgrade consigliato e genera un piano di upgrade specifico per la configurazione del tuo cluster.

Upgrade Advisor è particolarmente adatto agli utenti con un ambiente più piccolo che preferiscono un'esperienza basata sul cloud e incentrata sull'interfaccia utente.

.Prima di iniziare
* Per utilizzare Upgrade Advisor è necessario un contratto attivo link:https://www.netapp.com/netapp-services/["Servizi di supporto con intelligenza artificiale abilitata SupportEdge"^] per link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Consulente digitale"^].
* AutoSupport deve essere abilitato affinché Upgrade Advisor possa accedere automaticamente ai log di AutoSupport necessari per generare un piano di upgrade. Se non hai abilitato AutoSupport, puoi https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["Caricare manualmente i file AutoSupport"^].


.Fasi
. https://aiq.netapp.com/["Avviare il programma di consulenza digitale Active IQ"^]
. In Digital Advisor link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["visualizza tutti i rischi associati al cluster ed esegui manualmente azioni correttive"^].
+
I rischi inclusi nelle categorie *Modifica configurazione SW*, *Modifica configurazione HW* e *Sostituzione HW* devono essere risolti prima di eseguire un aggiornamento ONTAP.

. Esaminare il percorso di aggiornamento consigliato e. link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["genera il tuo piano di upgrade"^].


.Quali sono le prossime novità?
* Esaminate le link:../release-notes/index.html["Note di rilascio di ONTAP"] informazioni sulle modifiche introdotte nella versione di ONTAP che Upgrade Advisor consiglia come destinazione per l'aggiornamento. Dopo averlo fatto, aggiornate il cluster seguendo il piano generato da Upgrade Advisor.
* link:reboot-sp-bmc.html["Riavviare SP o BMC"] prima dell'inizio dell'aggiornamento.




[[prepare-to-upgrade-with-upgrade-health-checker]]
== Preparati per l'upgrade con Upgrade Health Checker

Upgrade Health Checker è uno strumento on-site adatto agli utenti con ambienti di grandi dimensioni o complessi, accesso limitato a Internet o framework di automazione e orchestrazione esistenti. Un contratto SupportEdge non è richiesto per utilizzare Upgrade Health Checker.

.Prima di iniziare
È necessario link:https://docs.netapp.com/us-en/upgrade-health-checker/set-up-upgrade-health-checker.html["scarica e configura Upgrade Health Checker"^] prima di poterlo utilizzare per generare un piano di upgrade.

.Fasi
. link:https://docs.netapp.com/us-en/upgrade-health-checker/generate-report-upgrade-health-checker.html["Genera un piano di upgrade con Upgrade Health Checker"^].


.Quali sono le prossime novità?
* Consulta le link:../release-notes/index.html["Note di rilascio di ONTAP"] per informazioni sulle modifiche introdotte nella versione di ONTAP che Upgrade Health Checker consiglia come destinazione di upgrade. Dopo averlo fatto, esegui l'upgrade del cluster seguendo il piano generato da Upgrade Health Checker.
* link:reboot-sp-bmc.html["Riavviare SP o BMC"] prima dell'inizio dell'aggiornamento.

