---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, active iq, create an upgrade plan, estimate upgrade, 
summary: 'Il servizio Upgrade Advisor di Active IQ Digital Advisor fornisce informazioni utili per pianificare l"upgrade e ridurre al minimo incertezza e rischi.' 
---
= Creare un piano di aggiornamento ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È consigliabile creare un piano di aggiornamento. Se si dispone di un'opzione attiva link:https://www.netapp.com/us/services/support-edge.aspx["Servizi SupportEdge"^] contratto per link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Consulente digitale Active IQ"^], È possibile utilizzare Upgrade Advisor per generare un piano di aggiornamento. In caso contrario, è necessario creare un piano personalizzato.



== Pianifica l'upgrade con Upgrade Advisor

Il servizio Upgrade Advisor di Active IQ Digital Advisor fornisce informazioni utili per pianificare l'upgrade e ridurre al minimo incertezza e rischi.

Active IQ identifica i problemi dell'ambiente che possono essere risolti eseguendo l'aggiornamento a una versione più recente di ONTAP. Il servizio preparazione aggiornamento ti aiuta a pianificare un aggiornamento corretto e fornisce un report dei problemi che potresti dover essere a conoscenza della versione di ONTAP a cui stai eseguendo l'aggiornamento.

.Fasi
. https://aiq.netapp.com/["Avviare Active IQ"^]
. A Active IQ link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["visualizza tutti i rischi associati al cluster ed esegui manualmente azioni correttive"^].
+
I rischi inclusi nelle categorie *Modifica configurazione SW*, *Modifica configurazione HW* e *Sostituzione HW* devono essere risolti prima di eseguire un aggiornamento ONTAP.

. Esaminare il percorso di aggiornamento consigliato e. link:https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html["genera il tuo piano di upgrade"^].




== Quanto tempo richiede un aggiornamento di ONTAP?

Dovresti pianificare per almeno 30 minuti di completamento dei passaggi preparatori per un upgrade di ONTAP, 60 minuti per eseguire l'upgrade di ciascuna coppia ha e almeno 30 minuti per completare i passaggi successivi all'upgrade.


NOTE: Se si utilizza NetApp Encryption con un server di gestione delle chiavi esterno e il protocollo KMIP (Key Management Interoperability Protocol), l'aggiornamento di ciascuna coppia ha dovrebbe essere superiore a un'ora.

Queste linee guida sulla durata dell'aggiornamento si basano su configurazioni e carichi di lavoro tipici. È possibile utilizzare queste linee guida per stimare il tempo necessario per eseguire un aggiornamento senza interruzioni nel proprio ambiente. La durata effettiva del processo di upgrade dipende dal singolo ambiente e dal numero di nodi.
