---
permalink: upgrade/download-software-image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, upgrade 
summary: Prima di aggiornare ONTAP, è necessario scaricare il software ONTAP dal sito di supporto NetApp. 
---
= Scaricare l'immagine del software ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare ONTAP, è necessario scaricare l'immagine del software ONTAP di destinazione dal sito di supporto NetApp. A seconda della versione di ONTAP, è possibile scaricare il software ONTAP su un server HTTPS, HTTP o FTP sulla rete o in una cartella locale.

[cols="2"]
|===
| Se si esegue... | È possibile scaricare l'immagine in questa posizione... 


| ONTAP 9.6 e versioni successive  a| 
* Sul sistema locale deve essere installato un server HTTPS e il certificato CA del server.
* Una cartella locale
* Un server HTTP o FTP




| ONTAP 9.4 e versioni successive  a| 
* Una cartella locale
* Un server HTTP o FTP




| ONTAP 9.0 e versioni successive | Un server HTTP o FTP 
|===
.A proposito di questa attività
* Se stai eseguendo un upgrade automatizzato e senza interruzioni utilizzando un link:concept_upgrade_paths.html#types-of-upgrade-paths["percorso di upgrade diretto multi-hop"], È necessario scaricare il pacchetto software sia per la versione ONTAP intermedia che per la versione ONTAP di destinazione richiesta per l'aggiornamento.  Ad esempio, se si esegue l'aggiornamento da ONTAP 9,8 a ONTAP 9.13.1, è necessario scaricare i pacchetti software sia per ONTAP 9.12.1 che per ONTAP 9.13.1.  Vedere link:concept_upgrade_paths.html#supported-upgrade-paths["percorsi di aggiornamento supportati"] per determinare se il percorso di aggiornamento richiede il download di un pacchetto software intermedio.
* Se si esegue l'aggiornamento di un sistema con crittografia dei volumi NetApp a ONTAP 9.5 o versione successiva, è necessario scaricare l'immagine del software ONTAP per i paesi senza restrizioni, che include crittografia dei volumi NetApp.
+
Se si utilizza l'immagine del software ONTAP per i paesi con restrizioni per aggiornare un sistema con crittografia dei volumi NetApp, il sistema esegue una panoramica e si perde l'accesso ai volumi.

* Non è necessario scaricare un pacchetto software separato per il firmware. L'aggiornamento del firmware per il cluster è incluso nel pacchetto di aggiornamento software ONTAP e viene copiato nel dispositivo di boot di ogni nodo. Il nuovo firmware viene quindi installato come parte del processo di aggiornamento.


.Fasi
. Individuare il software ONTAP di destinazione in link:https://mysupport.netapp.com/site/products/all/details/ontap9/downloads-tab["Download di software"] Area del NetApp Support Site.
+
Per un aggiornamento ONTAP Select, selezionare *aggiornamento nodo ONTAP Select*.

. Copiare l'immagine software (ad esempio, 97_q_image.tgz) nella posizione appropriata.
+
A seconda della versione di ONTAP, la posizione sarà una directory di un server HTTP, HTTPS o FTP da cui l'immagine verrà servita al sistema locale o a una cartella locale del sistema di storage.


