---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: 'L"aggiornamento ONTAP consente di sfruttare le funzioni nuove e migliorate. Prima di iniziare, attenersi alla procedura consigliata per la preparazione dell"aggiornamento.' 
---
= Ulteriori informazioni sull'aggiornamento di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando aggiorni il software ONTAP, puoi sfruttare le nuove e migliorate funzionalità di ONTAP che possono aiutarti a ridurre i costi, accelerare i carichi di lavoro critici, migliorare la sicurezza ed espandere l'ambito di protezione dei dati disponibile per la tua organizzazione.

Un upgrade principale di ONTAP consiste nel passaggio da una release di ONTAP con numerazione inferiore a una release di ONTAP con numerazione superiore. Un esempio potrebbe essere un upgrade del cluster da ONTAP 9.14.1 a ONTAP 9.18.1. Un upgrade minore (o patch) consiste nel passaggio da una versione di ONTAP a una versione di ONTAP superiore all'interno della stessa release numerata. Un esempio potrebbe essere un upgrade del cluster da ONTAP 9.17.1P1 a 9.17.1P4.

Per iniziare, puoi utilizzare uno dei seguenti metodi per preparare l'upgrade.

* Upgrade Advisor
+
Se hai un contratto attivo SupportEdge per Active IQ Digital Advisor (noto anche come Digital Advisor), dovresti link:create-upgrade-plan.html["Prepararsi per l'aggiornamento con Upgrade Advisor"]. Upgrade Advisor fornisce informazioni che ti aiutano a ridurre al minimo l'incertezza e il rischio valutando il tuo cluster e creando un piano di upgrade specifico per la tua configurazione.

+
Upgrade Advisor è adatto agli utenti con ambienti più piccoli che preferiscono un'esperienza basata sul cloud e incentrata sull'interfaccia utente.

+
Scopri di più su link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Upgrade Advisor"^].

* Upgrade Health Checker
+
Puoi anche link:create-upgrade-plan.html["preparati per l'upgrade con Upgrade Health Checker"]. Upgrade Health Checker è uno strumento di consulenza per gli upgrade che esegue controlli completi in loco per identificare blocchi e avvisi di upgrade. Un contratto SupportEdge non è richiesto per utilizzare Upgrade Health Checker.

+
Upgrade Health Checker è adatto agli utenti che dispongono di un ambiente ampio o complesso, accesso limitato a Internet o un framework di automazione e orchestrazione esistente.

+
Scopri di più su link:https://docs.netapp.com/us-en/upgrade-health-checker/learn-about-upgrade-health-checker.html["Upgrade Health Checker"^].

* Preparazione manuale
+
Se non si utilizza Upgrade Advisor o lo strumento Upgrade Health Checker, è necessario link:prepare.html["prepararsi per l'upgrade manuale"]. La preparazione manuale richiede il completamento di più attività per verificare eventuali problemi noti o blocchi e garantire che il cluster soddisfi i requisiti necessari per l'upgrade.

+
Scopri di più su link:prepare.html["preparazione dell'upgrade manuale"^].



Dopo aver preparato l'aggiornamento, si consiglia di eseguire gli aggiornamenti utilizzando link:task_upgrade_andu_sm.html["Upgrade automatizzato senza interruzioni (ANDU) da System Manager"]. ANDU sfrutta la tecnologia di failover ad alta disponibilità (ha) di ONTAP per garantire che i cluster continuino a fornire i dati senza interruzioni durante l'upgrade.


NOTE: A partire da ONTAP 9.12.1, System Manager è completamente integrato con NetApp Console.  Se la Console è configurata sul tuo sistema, puoi effettuare l'aggiornamento tramite la pagina Sistemi.

Se desideri assistenza per l'aggiornamento del software ONTAP, i servizi di assistenza professionale NetApp offrono una link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["Servizio di upgrade gestito"^]. Se siete interessati a utilizzare questo servizio, contattate il vostro rappresentante commerciale NetApp o. link:https://www.netapp.com/forms/sales-contact/["Inviare il modulo per la richiesta di informazioni sulle vendite NetApp"^]. Il Servizio di aggiornamento gestito e altri tipi di supporto per l'aggiornamento sono disponibili per i clienti con link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["Servizi SupportEdge Expert"^] senza costi aggiuntivi.

.Informazioni correlate
* link:concept_upgrade_paths.html["Percorsi di upgrade supportati"]

