---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade, ontap 
summary: Procedure di aggiornamento di ONTAP 
---
= Panoramica di Upgrade ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Il link:concept_upgrade_methods.html["metodo utilizzato per l'aggiornamento"] Il software ONTAP dipende dalla configurazione. Se è supportato dalla configurazione, è necessario eseguire un aggiornamento automatico senza interruzioni utilizzando System Manager.

È possibile utilizzare queste procedure per aggiornare on-premise ONTAP e ONTAP Select. Per ulteriori informazioni su ONTAP Select, consultare la procedura generale di link:https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html#general-procedure["Aggiornamento dei nodi ONTAP Select"]. Per informazioni sull'aggiornamento di ONTAP nel cloud, vedere https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html["Aggiornamento del software Cloud Volumes ONTAP"^].

Se si dispone di un'opzione attiva link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge"] contratto per link:https://aiq.netapp.com/["Consulente digitale Active IQ"], Prima di iniziare l'aggiornamento, è necessario avviare preparazione aggiornamento in Consulente digitale Active IQ per pianificare l'aggiornamento.

Le procedure descritte in questa sezione guidano l'utente attraverso i passaggi da eseguire prima e dopo l'aggiornamento, incluse le risorse da leggere e i necessari controlli pre e post-aggiornamento da eseguire.
