---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary 
summary: La preparazione per un aggiornamento di ONTAP consente di identificare e ridurre i rischi o i blocchi legati agli aggiornamenti e tiene conto di considerazioni speciali applicabili alla configurazione in uso. 
---
= Prepararsi per un aggiornamento del software ONTAP senza Consulenza aggiornamenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La preparazione corretta per un aggiornamento software ONTAP consente di identificare e ridurre i potenziali rischi o blocchi di aggiornamento prima di iniziare il processo di aggiornamento. Durante la preparazione dell'aggiornamento, è inoltre possibile identificare eventuali considerazioni speciali che potrebbero essere necessarie prima di eseguire l'aggiornamento. Ad esempio, se la modalità SSL FIPS è attivata sul cluster e gli account amministratore utilizzano chiavi pubbliche SSH per l'autenticazione, è necessario verificare che l'algoritmo della chiave host sia supportato nella versione ONTAP di destinazione.

Se si dispone di un contratto SupportEdge attivo per link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Consulente digitale"^], link:create-upgrade-plan.html["Pianificate l'aggiornamento con Upgrade Advisor"]. Se non si dispone dell'accesso a Active IQ Digital Advisor (noto anche come Digital Advisor), è necessario effettuare le seguenti operazioni per prepararsi a un aggiornamento di ONTAP.

. link:choose-target-version.html["Scegli la tua versione ONTAP di destinazione"].
. Consultare le sezioni _attenzione all'aggiornamento_ e _problemi noti e limitazioni_ nella link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"]per la versione di destinazione.
+
_Attenzione aggiornamento_ descrivono i potenziali problemi di cui si dovrebbe essere a conoscenza prima dell'aggiornamento. _Problemi noti e limitazioni_ descrivono comportamenti del sistema potenzialmente imprevisti che potrebbero verificarsi dopo l'aggiornamento.

+
Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.

. link:confirm-configuration.html["Verificare il supporto ONTAP per la configurazione hardware"].
+
La piattaforma hardware, gli switch per la gestione del cluster e gli switch IP MetroCluster devono supportare la release di destinazione.  Se il cluster è configurato per SAN, la configurazione SAN deve essere completamente supportata.

. link:task_check_for_common_configuration_errors_using_config_advisor.html["Utilizzare Active IQ Config Advisor per verificare che non siano presenti errori di configurazione comuni."]
. Esaminare il ONTAP supportato link:concept_upgrade_paths.html#supported-upgrade-paths["percorsi di aggiornamento"] per determinare se è possibile eseguire un aggiornamento diretto o se è necessario completare l'aggiornamento in fasi.
. link:task_verifying_the_lif_failover_configuration.html["Verifica della configurazione di failover della LIF"].
+
Prima di eseguire un aggiornamento, è necessario verificare che i criteri di failover del cluster e i gruppi di failover siano configurati correttamente.

. link:concept_verify_svm_routing.html["Verificare la configurazione del routing SVM"].
. link:special-considerations.html["Verificare le considerazioni speciali"] per il tuo cluster.
+
Se nel cluster esistono determinate configurazioni, è necessario intraprendere azioni specifiche prima di iniziare un aggiornamento software di ONTAP.

. link:reboot-sp-bmc.html["Riavviare SP o BMC"].

