---
sidebar: sidebar 
permalink: upgrade/resume-upgrade-after-andu-error.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 'Se un aggiornamento automatico del software ONTAP si interrompe a causa di un errore, è necessario risolvere l"errore e continuare l"aggiornamento.' 
---
= Riprendere l'aggiornamento del software ONTAP dopo un errore nel processo di aggiornamento automatico
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se un aggiornamento automatico del software ONTAP si interrompe a causa di un errore, è necessario risolvere l'errore e continuare l'aggiornamento.  Una volta risolto l'errore, è possibile scegliere di continuare il processo di aggiornamento automatico o di completare manualmente il processo di aggiornamento. Se si sceglie di continuare l'aggiornamento automatico, non eseguire manualmente alcuna procedura di aggiornamento.

.Fasi
[role="tabbed-block"]
====
.System Manager
--
. A seconda della versione di ONTAP in esecuzione, eseguire una delle seguenti operazioni:
+
|===


| Se si esegue... | Quindi... 


 a| 
ONTAP 9.8 o versione successiva
 a| 
Fare clic su *Cluster* > *Overview*



 a| 
ONTAP 9,7, 9,6 o 9,5
 a| 
Fare clic su *Configuration* > *Cluster* > *Update*.



 a| 
ONTAP 9.4 o versioni precedenti
 a| 
** Fare clic su *Configuration* > *Cluster Update*.
** Nell'angolo destro del riquadro *Panoramica*, fare clic sui tre punti verticali blu e selezionare *aggiornamento ONTAP*.


|===
. Continuare l'aggiornamento automatico o annullarlo e continuare manualmente.
+
|===


| Se si desidera... | Quindi... 


 a| 
Riprendere l'aggiornamento automatico
 a| 
Fare clic su *Riprendi*.



 a| 
Annullare l'aggiornamento automatico e continuare manualmente
 a| 
Fare clic su *Annulla*.

|===


--
.CLI
--
. Visualizzare l'errore di aggiornamento:
+
[source, cli]
----
cluster image show-update-progress
----
. Risolvere l'errore.
. Riprendere l'aggiornamento:
+
|===


| Se si desidera... | Immettere il seguente comando... 


 a| 
Riprendere l'aggiornamento automatico
 a| 
[source, cli]
----
cluster image resume-update
----


 a| 
Annullare l'aggiornamento automatico e continuare manualmente
 a| 
[source, cli]
----
cluster image cancel-update
----
|===


--
====
.Al termine
link:task_what_to_do_after_upgrade.html["Eseguire i controlli post-aggiornamento"].
