---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: 'Se sul cluster è configurata una relazione a cascata SnapMirror , potrebbe essere necessario disabilitare gli snapshot di conservazione a lungo termine prima di eseguire l"aggiornamento' 
---
= Disattiva gli snapshot di conservazione a lungo termine prima dell'aggiornamento di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In una relazione di volumi a cascata, gli snapshot di conservazione a lungo termine sono supportati solo sul volume di destinazione SnapMirror finale della cascata in tutte le versioni di ONTAP 9. L'abilitazione di snapshot di conservazione a lungo termine su qualsiasi volume intermedio nella cascata comporta la perdita di backup e snapshot.

Scopri di più sulink:../data-protection/long-term-retention-snapshots-concept.html["snapshot di conservazione a lungo termine"] .

Se si dispone di una configurazione non supportata in cui gli snapshot di conservazione a lungo termine sono stati abilitati su un volume intermedio di una cascata, contattare l'assistenza tecnica e fare riferimento al collegamento: https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_ (long-term retention)_snapshots_enabled_is_not_supported[NetApp Knowledge Base: La cascata di un volume con snapshot di conservazione a lungo termine (LTR) abilitati non è supportata^] per assistenza.

Le seguenti versioni ONTAP non consentono di abilitare snapshot di conservazione a lungo termine su alcun volume in una cascata, ad eccezione del volume di destinazione SnapMirror finale.

* 9.15.1 e versioni successive
* 9.14.1P2 e P4 fino a P14
* 9.13.1P9 attraverso P17
* 9.12.1 P12 attraverso P19
* 9.11.1P15 attraverso P20
* 9.10.1P18 attraverso P20
* 9.9.1P20


Prima di eseguire l'aggiornamento da una versione ONTAP che consente di abilitare snapshot di conservazione a lungo termine sui volumi intermedi di una cascata a una versione ONTAP che lo blocca, è necessario disabilitare gli snapshot di conservazione a lungo termine per evitare backup e snapshot persi.

È necessario intervenire nei seguenti scenari:

* Gli snapshot di conservazione a lungo termine vengono configurati sul volume "B" in una cascata SnapMirror "A > B > C" o su un altro volume di destinazione SnapMirror intermedio nella cascata più grande.
* gli snapshot di conservazione a lungo termine sono definiti da una pianificazione applicata a una regola di policy SnapMirror . Questa regola non replica gli snapshot dal volume di origine, ma li crea direttamente sul volume di destinazione.
+

NOTE: Per ulteriori informazioni sulle pianificazioni e sulle policy SnapMirror , vederelink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["NetApp Knowledge Base: come funziona il parametro "schedule" in una regola di policy ONTAP 9 SnapMirror ?"^] .



.Fasi
. Rimuovere la regola di conservazione a lungo termine dalla policy SnapMirror sul volume centrale della cascata:
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
Scopri di più su  `snapmirror policy remove-rule` nel link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["Riferimento al comando ONTAP"^] .

. Aggiungere nuovamente la regola per l'etichetta SnapMirror senza la pianificazione di conservazione a lungo termine:
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: La rimozione degli snapshot di conservazione a lungo termine dalle regole dei criteri di SnapMirror significa che SnapMirror estrarrà gli snapshot con l'etichetta specificata dal volume di origine. Potrebbe anche essere necessario aggiungere o modificare una pianificazione nella policy di snapshot del volume di origine per creare snapshot correttamente etichettati.

+
Ulteriori informazioni su `snapmirror policy add-rule` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Riferimento al comando ONTAP"^].

. Se necessario, modificare (o creare) una pianificazione nel policy di snapshot del volume di origine per consentire la creazione di snapshot con un'etichetta SnapMirror:
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: gli snapshot di conservazione a lungo termine possono comunque essere abilitati sul volume di destinazione SnapMirror finale all'interno di una configurazione a cascata SnapMirror .
