---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: 'Se nel cluster disponi di una relazione di cascata SnapMirror configurata, potrebbe essere necessario disattivare le snapshot di conservazione a lungo termine (LTR) prima dell"upgrade' 
---
= Disattiva gli snapshot di conservazione a lungo termine prima dell'aggiornamento di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In una relazione di volumi a cascata, gli snapshot con conservazione a lungo termine (LTR) sono supportati solo sul volume di destinazione SnapMirror finale della cascata in tutte le versioni di ONTAP 9.  L'abilitazione degli snapshot LTR su qualsiasi volume intermedio nella cascata comporta la perdita di backup e snapshot.

Scopri di più sulink:../data-protection/long-term-retention-snapshots-concept.html["snapshot di conservazione a lungo termine"] .

Se si dispone di una configurazione non supportata in cui gli snapshot LTR sono stati abilitati su qualsiasi volume intermedio di una cascata, contattare il supporto tecnico e fare riferimento allink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_(LTR)_snapshots_enabled_is_not_supported["Knowledge Base NetApp : la sovrapposizione di un volume con snapshot LTR (Long-Term Retention) abilitati non è supportata"^] per assistenza.

Le seguenti versioni ONTAP non consentono di abilitare gli snapshot LTR su alcun volume in una cascata, ad eccezione del volume di destinazione SnapMirror finale.

* 9.15.1 e versioni successive
* 9.14.1P2 e P4 fino a P14
* 9.13.1P9 attraverso P17
* 9.12.1 P12 attraverso P19
* 9.11.1P15 attraverso P20
* 9.10.1P18 attraverso P20
* 9.9.1P20


Prima di eseguire l'aggiornamento da una versione ONTAP che consente di abilitare gli snapshot LTR sui volumi intermedi di una cascata a una versione ONTAP che li blocca, è necessario disabilitare gli snapshot LTR per evitare backup e snapshot persi.

È necessario intervenire nei seguenti scenari:

* Gli snapshot LTR (Long-Term Retention) sono configurati sul volume "B" in una cascata SnapMirror "A > B > C" o su un altro volume di destinazione SnapMirror medio nella tua cascata più grande.
* Gli snapshot LTR sono definiti da una pianificazione applicata a una regola di policy SnapMirror. Questa regola non replica gli snapshot dal volume di origine, ma li crea direttamente sul volume di destinazione.
+

NOTE: Per ulteriori informazioni sulle pianificazioni e sulle policy SnapMirror , vederelink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["NetApp Knowledge Base: come funziona il parametro "schedule" in una regola di policy ONTAP 9 SnapMirror ?"^] .



.Fasi
. Rimuovere la regola LTR dalla policy SnapMirror sul volume intermedio della cascata:
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
Scopri di più su  `snapmirror policy remove-rule` nel link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["Riferimento al comando ONTAP"^] .

. Aggiungere di nuovo la regola per l'etichetta SnapMirror senza la pianificazione LTR:
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: La rimozione degli snapshot LTR dalle regole di policy di SnapMirror implica che SnapMirror estrarrà gli snapshot con l'etichetta specificata dal volume di origine. Potrebbe inoltre essere necessario aggiungere o modificare una pianificazione nel criterio snapshot del volume di origine per creare snapshot con etichetta corretta.

+
Ulteriori informazioni su `snapmirror policy add-rule` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Riferimento al comando ONTAP"^].

. Se necessario, modificare (o creare) una pianificazione nel policy di snapshot del volume di origine per consentire la creazione di snapshot con un'etichetta SnapMirror:
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: Gli snapshot LTR possono ancora essere abilitati sul volume di destinazione SnapMirror finale all'interno di una configurazione a cascata SnapMirror.
