---
permalink: upgrade/task_reviewing_pre_update_resources.html 
sidebar: sidebar 
keywords: ontap, upgrade, resources, review, before 
summary: Prima di aggiornare il software ONTAP, è necessario esaminare le risorse per comprendere i problemi da risolvere, comprendere il nuovo comportamento del sistema nella release di destinazione e confermare il supporto hardware. 
---
= Risorse da leggere prima dell'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se non si utilizza link:https://aiq.netapp.com/["Active IQ"^] Upgrade Advisor, prima di aggiornare il software ONTAP, è necessario rivedere alcune risorse NetApp. Queste risorse consentono di comprendere i problemi da risolvere, il nuovo comportamento del sistema nella release di destinazione e confermare il supporto hardware.

. Consultare le _Note di rilascio_ per la release di destinazione.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"]

+
La sezione "`attenzione importante`" descrive i potenziali problemi che è necessario conoscere prima di eseguire l'aggiornamento alla nuova release. Le sezioni "`funzioni nuove e modificate`" e "`problemi e limitazioni noti`" descrivono il nuovo comportamento del sistema dopo l'aggiornamento alla nuova release.

. Verificare che la piattaforma hardware, il cluster e gli switch di gestione siano supportati nella release di destinazione.
+
È possibile eseguire l'aggiornamento in uno stato transitorio, ma in ultima analisi le versioni del software NX-OS (switch di rete cluster), IOS (switch di rete di gestione) e del file di configurazione di riferimento (RCF) devono essere compatibili con la versione di ONTAP alla quale si esegue l'aggiornamento.

+
https://hwu.netapp.com["NetApp Hardware Universe"^]

. Verificare che gli switch IP MetroCluster siano supportati nella versione di destinazione.
+
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]

. Se il cluster e gli switch di gestione non dispongono delle versioni software minime per la release ONTAP di destinazione, eseguire l'aggiornamento alle versioni software supportate.
+
** https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Download NetApp: Switch cluster Broadcom"^]
** https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Download NetApp: Switch Ethernet Cisco"^]
** https://mysupport.netapp.com/site/info/netapp-cluster-switch["Download NetApp: Switch cluster NetApp"^]


. Se il cluster è configurato per LA SAN, verificare che la configurazione DELLA SAN sia completamente supportata.
+
Tutti i componenti SAN, inclusi la versione del software ONTAP di destinazione, il sistema operativo host e le patch, il software delle utility host richiesto, il software di multipathing, i driver e il firmware dell'adattatore, devono essere supportati.

+
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]

. Se si sta passando dalla modalità 7 utilizzando lo strumento di transizione 7-Mode, verificare che lo strumento supporti la transizione alla versione di ONTAP alla quale si sta eseguendo l'aggiornamento.
+
Tutti i progetti nello strumento devono essere in stato completato o interrotto prima di aggiornare lo strumento di transizione 7-Mode che supporta la versione di ONTAP alla quale si sta eseguendo l'aggiornamento.

+
link:https://docs.netapp.com/us-en/ontap-7mode-transition/install-admin/index.html["Installazione e amministrazione dello strumento di transizione 7-Mode"]


