---
permalink: upgrade/task_what_to_do_after_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade, how, post-checks 
summary: Dopo aver aggiornato il software ONTAP, è necessario eseguire diverse attività per verificare la preparazione del cluster. 
---
= Cosa fare dopo un aggiornamento di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo l'aggiornamento di ONTAP, è necessario eseguire diverse attività per verificare la disponibilità del cluster.

. link:task_verify_cluster_after_upgrade.html["Verificare il cluster"].
+
Dopo l'upgrade di ONTAP, dovresti verificare la versione del cluster, la salute del cluster e la salute dello storage. Se si utilizza una configurazione MetroCluster FC, è inoltre necessario verificare che il cluster sia abilitato per lo switchover automatico non pianificato.

. link:task_enabling_and_reverting_lifs_to_home_ports_post_upgrade.html["Verifica che tutte le LIF siano sulle porte home"].
+
Durante un riavvio, alcune LIF potrebbero essere state migrate alle porte di failover assegnate. Dopo l'aggiornamento di un cluster, è necessario abilitare e ripristinare le LIF che non si trovano sulle porte domestiche.

. Verificare link:concept_special_configurations_post_checks.html["considerazioni particolari"] specifico per il tuo cluster.
+
Se nel cluster sono presenti determinate configurazioni, potrebbe essere necessario eseguire ulteriori passaggi dopo l'aggiornamento.

. link:concept_when_you_need_to_update_the_disk_qualification_package.html["Aggiornamento del Disk Qualification Package (DQP)"].
+
Il DQP non viene aggiornato come parte di un aggiornamento del ONTAP.


