---
sidebar: sidebar 
permalink: upgrade/task_upgrade_disruptive_automated_cli.html 
keywords: netapp, ontap, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: È possibile aggiornare senza interruzioni la versione di ONTAP nel cluster. 
---
= Upgrade automatizzato dei ONTAP con interruzioni (solo cluster a nodo singolo)
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
A partire da ONTAP 9,2, puoi utilizzare l'interfaccia a riga di comando di ONTAP per eseguire un update automatico di un cluster a nodo singolo. Poiché i cluster a nodo singolo non hanno ridondanza, gli aggiornamenti sono sempre di tipo disgregativo. Non è possibile eseguire upgrade con interruzioni usando System Manager.

* È necessario soddisfare i requisiti di preparazione dell'upgrade.
+
.. Eliminare il pacchetto software ONTAP precedente: `cluster image package delete -version previous_package_version`
.. Scarica il pacchetto software ONTAP di destinazione: `cluster image package get -url location`
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
.. Verificare che il pacchetto software sia disponibile nel repository dei pacchetti del cluster: `cluster image package show-repository`
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              M/DD/YYYY 10:32:15
----
.. Verificare che il cluster sia pronto per l'aggiornamento: `cluster image validate -version package_version_number`
+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
.. Monitorare l'avanzamento della convalida: `cluster image show-update-progress`
.. Completare tutte le azioni richieste identificate dalla convalida.
.. Facoltativamente, generare una stima dell'aggiornamento del software: `cluster image update -version package_version_number -estimate-only`
+
La stima dell'aggiornamento software visualizza i dettagli relativi a ciascun componente da aggiornare e la durata stimata dell'aggiornamento.

.. Eseguire l'aggiornamento del software: `cluster image update -version package_version_number`
+

NOTE: Se si verifica un problema, l'aggiornamento viene messo in pausa e richiede di intraprendere un'azione correttiva. È possibile utilizzare il comando show-update-progress dell'immagine del cluster per visualizzare i dettagli relativi a eventuali problemi e allo stato di avanzamento dell'aggiornamento. Dopo aver corretto il problema, è possibile riprendere l'aggiornamento utilizzando il comando resume-update dell'immagine del cluster.

.. Visualizzare l'avanzamento dell'aggiornamento del cluster: `cluster image show-update-progress`
+
Il nodo viene riavviato come parte dell'aggiornamento e non è possibile accedervi durante il riavvio.

.. Attivare una notifica: `autosupport invoke -node * -type all -message "Finishing_Upgrade"`
+
Se il cluster non è configurato per l'invio di messaggi, una copia della notifica viene salvata localmente.




