---
permalink: upgrade/task_plan_without_upgrade_advisor.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade, manually, manual 
summary: 'Per pianificare l"upgrade, è consigliabile utilizzare preparazione aggiornamento in Active IQ. Se non si dispone di un contratto SupportEdge attivo per Active IQ, è necessario eseguire i controlli di pre-aggiornamento necessari e creare un piano di aggiornamento personalizzato.' 
---
= Pianifica l'upgrade senza Upgrade Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È consigliabile utilizzare Upgrade Advisor in link:https://aiq.netapp.com/["Active IQ"^] per pianificare l'aggiornamento. Se non si dispone di un'opzione attiva link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge"] Contratto per Active IQ, devi eseguire i necessari controlli di pre-upgrade e creare il tuo piano di upgrade.



== Quanto tempo richiede l'aggiornamento?

È necessario pianificare almeno 30 minuti per completare le fasi preparatorie, 60 minuti per aggiornare ogni coppia ha e almeno 30 minuti per completare le fasi successive all'aggiornamento.


NOTE: Se si utilizza NetApp Encryption con un server di gestione delle chiavi esterno e il protocollo KMIP (Key Management Interoperability Protocol), l'aggiornamento di ciascuna coppia ha dovrebbe essere superiore a un'ora.

Le nostre linee guida sulla durata dell'upgrade si basano su configurazioni e carichi di lavoro tipici. È possibile utilizzare queste linee guida per stimare il tempo necessario per eseguire un aggiornamento senza interruzioni nel proprio ambiente. Tuttavia, la durata effettiva del processo di aggiornamento dipende dal singolo ambiente e dal numero di nodi.
