---
permalink: upgrade/task-change-svm-42v-xattrs-option.html 
sidebar: sidebar 
keywords: ontap, upgrade, svm, xattr, nfsv4.2 
summary: 'Prima di aggiornare ONTAP 9.12,1 e versioni successive, assicurarsi di fornire un valore esplicito per un"opzione di attributi estesi NFSv4,2 per evitare errori di risposta NFS.' 
---
= Assegnare un valore esplicito all'opzione v4,2-xattrs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dispone di un client NFSv4,2, prima di eseguire l'aggiornamento da determinate release e patch di ONTAP 9.12,1 e versioni successive è necessario fornire un valore esplicito per l'opzione attributi estesi NFSv4,2 per evitare errori di risposta NFS dopo l'aggiornamento.

Se all' `v4.2-xattrs`opzione non viene mai assegnato esplicitamente un valore prima dell'aggiornamento di ONTAP alle versioni interessate, i client NFSv4,2 non vengono informati della modifica dell'opzione attributi estesi del server. Ciò causa errori di risposta NFS a chiamate specifiche `xattrs` a causa di una mancata corrispondenza tra client e server.

.Prima di iniziare
È necessario assegnare un valore esplicito per l'opzione NFSv4,2 attributi estesi se è vero quanto segue:

* Stai utilizzando NFSv4,2 con una SVM creata utilizzando ONTAP 9.11,1 o una versione precedente
* Si sta eseguendo l'aggiornamento di ONTAP da una delle seguenti release e patch interessate:
+
** Da 9.12.1RC1 a 9.12.1P11
** Da 9.13.1RC1 a 9.13.1P8
** Da 9.14.1RC1 a 9.14.1P1




.A proposito di questa attività
È necessario eseguire ONTAP 9.12,1 o versioni successive per impostare il valore utilizzando il comando descritto in questa procedura.

Se `v4.2-xattrs` è già impostato su `enabled`, deve essere impostato esplicitamente su `enabled` per evitare interruzioni future. Se si imposta `v4.2-xattrs` su disattivato, i client NFSv4,2 possono ricevere risposte "argomento non valido" finché non vengono rimontati o l' `v4.2-xattrs`opzione è impostata su `enabled`.

.Fasi
* Assegnare un valore esplicito all' `v4.2-xattrs`opzione:
+
[source, cli]
----
nfs modify -v4.2-xattrs <enabled/disabled> -vserver <vserver_name>
----


.Informazioni correlate
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-Issues/CONTAP-120160["Il campo NFS v4,2-xattrs viene capovolto dopo gli aggiornamenti"^]
