---
permalink: upgrade/task_preparing_to_upgrade_nodes_using_netapp_storage_encryption_with_external_key_management_servers.html 
sidebar: sidebar 
keywords: ontap, upgrade, prepare, preparing, nodes, netapp, storage, encryption, nse, external, key management, servers 
summary: 'Se si utilizza la crittografia dello storage NetApp su ONTAP 9.2 o versione precedente e si esegue l"aggiornamento a ONTAP 9.3 o versione successiva, è necessario utilizzare l"interfaccia della riga di comando per eliminare eventuali connessioni server di gestione delle chiavi esterne esistenti prima di eseguire l"aggiornamento.' 
---
= Eliminare le connessioni esistenti al server di gestione delle chiavi esterno prima di eseguire l'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza NetApp Storage Encryption (NSE) su ONTAP 9.2 o versione precedente e si esegue l'aggiornamento a ONTAP 9.3 o versione successiva, è necessario utilizzare l'interfaccia a riga di comando (CLI) per eliminare eventuali connessioni server KMIP (External Key Management) esistenti prima di eseguire l'aggiornamento.

. Verificare che le unità NSE siano sbloccate, aperte e impostate sull'ID protetto predefinito 0x0:
+
`storage encryption disk show -disk*`

. Accedere alla modalità avanzata dei privilegi:
+
`set -privilege advanced`

. Utilizzare l'ID protetto predefinito 0x0 per assegnare la chiave FIPS ai dischi con crittografia automatica (SED): `storage encryption disk modify -fips-key-id 0x0 -disk *`
. Verificare che l'assegnazione della chiave FIPS a tutti i dischi sia completata: `storage encryption disk show-status`
. Verificare che la *mode* per tutti i dischi sia impostata su data: `storage encryption disk show`
. Visualizzare i server KMIP configurati: `security key-manager show`
. Eliminare i server KMIP configurati: `security key-manager delete -address kmip_ip_address`
. Eliminare la configurazione del gestore delle chiavi esterno:``security key-manager delete-kmip-config``
+

NOTE: Questa fase non rimuove i certificati NSE.



Una volta completato l'aggiornamento, è necessario riconfigurare le connessioni del server KMIP.

.Informazioni correlate
xref:task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.adoc[Riconfigurazione delle connessioni del server KMIP dopo l'aggiornamento a ONTAP 9.3 o versione successiva]
