---
sidebar: sidebar 
permalink: upgrade/task_upgrade_disruptive_automated_cli.html 
keywords: netapp, ontap, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 'A partire da ONTAP 9,2, puoi utilizzare l"interfaccia a riga di comando di ONTAP per eseguire un update automatico di un cluster a nodo singolo. I cluster a nodo singolo non dispongono di ridondanza, pertanto gli upgrade causano interruzioni.' 
---
= Upgrade automatizzato dei ONTAP con interruzioni (solo cluster a nodo singolo)
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP 9,2, puoi utilizzare l'interfaccia a riga di comando di ONTAP per eseguire un update automatico di un cluster a nodo singolo. Poiché i cluster a nodo singolo non hanno ridondanza, gli aggiornamenti sono sempre di tipo disgregativo. Non è possibile eseguire upgrade con interruzioni usando System Manager.

* È necessario avere soddisfatto l'aggiornamento link:prepare.html["preparazione"] requisiti.


.Fasi
. Eliminare il pacchetto software ONTAP precedente:
+
[source, cli]
----
cluster image package delete -version previous_package_version
----
. Scarica il pacchetto software ONTAP di destinazione:
+
[source, cli]
----
cluster image package get -url location
----
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
. Verificare che il pacchetto software sia disponibile nel repository dei pacchetti del cluster:
+
[source, cli]
----
cluster image package show-repository
----
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              M/DD/YYYY 10:32:15
----
. Verificare che il cluster sia pronto per l'aggiornamento:
+
[source, cli]
----
cluster image validate -version package_version_number
----
+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
. Monitorare l'avanzamento della convalida:
+
[source, cli]
----
cluster image show-update-progress
----
. Completare tutte le azioni richieste identificate dalla convalida.
. Facoltativamente, generare una stima dell'aggiornamento del software:
+
[source, cli]
----
cluster image update -version package_version_number -estimate-only
----
+
La stima dell'aggiornamento software visualizza i dettagli relativi a ciascun componente da aggiornare e la durata stimata dell'aggiornamento.

. Eseguire l'aggiornamento del software:
+
[source, cli]
----
cluster image update -version package_version_number
----
+

NOTE: Se si verifica un problema, l'aggiornamento viene messo in pausa e richiede di intraprendere un'azione correttiva. È possibile utilizzare il comando show-update-progress dell'immagine del cluster per visualizzare i dettagli relativi a eventuali problemi e allo stato di avanzamento dell'aggiornamento. Dopo aver corretto il problema, è possibile riprendere l'aggiornamento utilizzando il comando resume-update dell'immagine del cluster.

. Visualizzare l'avanzamento dell'aggiornamento del cluster:
+
[source, cli]
----
cluster image show-update-progress
----
+
Il nodo viene riavviato come parte dell'aggiornamento e non è possibile accedervi durante il riavvio.

. Attivare una notifica:
+
[source, cli]
----
autosupport invoke -node * -type all -message "Finishing_Upgrade"
----
+
Se il cluster non è configurato per l'invio di messaggi, una copia della notifica viene salvata localmente.


