---
permalink: performance-admin/active-iq-digital-advisor-view-performance-concept.html 
sidebar: sidebar 
keywords: use, active iq, digital advisor, view, system, performance 
summary: Per qualsiasi sistema ONTAP che invia la telemetria AutoSupport a NetApp, è possibile visualizzare dati completi sulle performance e sulla capacità. Digital Advisor mostra le prestazioni del sistema per un periodo più lungo di quello che è possibile vedere in System Manager. 
---
= Utilizzare Digital Advisor per visualizzare le prestazioni del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per qualsiasi sistema ONTAP che invia la telemetria AutoSupport a NetApp, è possibile visualizzare dati completi sulle performance e sulla capacità. Digital Advisor mostra le prestazioni del sistema per un periodo più lungo di quello che è possibile vedere in System Manager.

È possibile visualizzare grafici relativi a utilizzo della CPU, latenza, IOPS, IOPS in base al protocollo e throughput di rete. È inoltre possibile scaricare questi dati in formato .csv per l'analisi in altri strumenti.

Oltre a questi dati sulle performance, Digital Advisor può mostrare l'efficienza dello storage per carico di lavoro e confrontare l'efficienza con quella prevista per quel tipo di carico di lavoro. È possibile visualizzare le tendenze della capacità e visualizzare una stima della quantità di storage aggiuntivo che potrebbe essere necessaria per aggiungere in un determinato intervallo di tempo.

[NOTE]
====
* L'efficienza dello storage è disponibile a livello di cliente, cluster e nodo sul lato sinistro del dashboard principale.
* Le performance sono disponibili a livello di cluster e nodo sul lato sinistro del dashboard principale.


====
.Informazioni correlate
* https://docs.netapp.com/us-en/active-iq/["Documentazione di Digital Advisor"]
* https://www.youtube.com/playlist?list=PLdXI3bZJEw7kWBxqwLYBchpMW4k9Z6Vum["Playlist video di Digital Advisor"]
* https://aiq.netapp.com/["Portale Web di Digital Advisor"]

