---
permalink: performance-admin/adaptive-policy-template-task.html 
sidebar: sidebar 
keywords: qos, throughput floor, throughput ceiling, adaptive policy group template 
summary: Applica un volume di throughput e un soffitto a livello di SVM utilizzando un modello di gruppo di policy adattivo. 
---
= Impostare un modello di gruppo di criteri adattativi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.13.1, è possibile applicare i livelli e i limiti di throughput a livello di SVM utilizzando un modello di gruppo di policy adattivo.

.A proposito di questa attività
* Il modello di gruppo di criteri adattivi è un criterio predefinito `apg1`. Il criterio può essere modificato in qualsiasi momento. Può essere impostato solo con l'API REST CLI o ONTAP e può essere applicato solo alle SVM esistenti.
* Il modello di gruppo di policy adattive influisce solo sui volumi creati o migrati sulla SVM dopo aver impostato il criterio. I volumi esistenti sulla SVM mantengono lo stato esistente.
+
Se si disattiva il modello di gruppo di criteri adattivi, i volumi su SVM conservano i criteri esistenti. Solo i volumi successivamente creati o migrati sulla SVM saranno influenzati dalla disabilitazione.

* Non è possibile impostare un modello di gruppo di criteri adattativi su una SVM con un gruppo di criteri QoS.
* I modelli di gruppi di policy adattivi sono progettati per le piattaforme AFF. È possibile impostare un modello di gruppo di policy adattivo su altre piattaforme, ma il criterio potrebbe non applicare un throughput minimo. In modo simile, puoi aggiungere un modello di gruppo di policy adattivo a una SVM di un aggregato FabricPool o di un aggregato senza supportare un throughput minimo, ma non verrà applicato il limite minimo di throughput.
* Se la SVM si trova in una configurazione MetroCluster o in una relazione SnapMirror, il modello di gruppo di criteri adattativi verrà applicato alla SVM mirrorata.


.Fasi
. Modificare la SVM per applicare il modello di gruppo di criteri adattativi:
`vserver modify -qos-adaptive-policy-group-template apg1`
. Verificare che il criterio sia stato impostato:
`vserver show -fields qos-adaptive-policy-group`

