---
permalink: performance-admin/check-nfs-tcp-read-write-size-task.html 
sidebar: sidebar 
keywords: check, nfs, tcp, maximum, transfer, size 
summary: Per NFS, è possibile verificare se le dimensioni massime di trasferimento TCP per le operazioni di lettura e scrittura potrebbero causare problemi di performance. Se pensi che le dimensioni rallentino le performance, puoi aumentarle. 
---
= Controllare le dimensioni massime di trasferimento TCP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per NFS, è possibile verificare se le dimensioni massime di trasferimento TCP per le operazioni di lettura e scrittura potrebbero causare problemi di performance. Se pensi che le dimensioni rallentino le performance, puoi aumentarle.

.Prima di iniziare
* Per eseguire questa attività, è necessario disporre dei privilegi di amministratore del cluster.
* Per questa attività, è necessario utilizzare i comandi avanzati del livello di privilegio.


.Fasi
. Passare al livello di privilegio avanzato:
+
`set -privilege advanced`

. Verificare le dimensioni massime di trasferimento TCP:
+
`vserver nfs show -vserver _vserver_name_ -instance`

. Se la dimensione massima di trasferimento TCP è troppo piccola, aumentarne la dimensione:
+
`vserver nfs modify -vserver _vserver_name_ -tcp-max-xfer-size _integer_`

. Tornare al livello di privilegi amministrativi:
+
`set -privilege admin`



.Esempio
Nell'esempio seguente viene modificata la dimensione massima di trasferimento TCP di `SVM1` a 1048576:

[listing]
----
cluster1::*> vserver nfs modify -vserver SVM1 -tcp-max-xfer-size 1048576
----