---
permalink: performance-admin/check-network-settings-task.html 
sidebar: sidebar 
keywords: check, mtu, network, setting, storage, system 
summary: 'È possibile modificare le impostazioni di rete sul sistema di storage se non corrispondono a quelle del client o di altri endpoint di rete. Mentre l"impostazione MTU della rete di gestione è impostata su 1500, la dimensione MTU della rete dati deve essere 9000.' 
---
= Controllare le impostazioni di rete MTU sul sistema di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di rete sul sistema di storage se non corrispondono a quelle del client o di altri endpoint di rete. Mentre l'impostazione MTU della rete di gestione è impostata su 1500, la dimensione MTU della rete dati deve essere 9000.



== A proposito di questa attività

Tutte le porte all'interno di un dominio di broadcast hanno le stesse dimensioni MTU, ad eccezione del traffico di gestione della porta e0M. Se la porta fa parte di un dominio di broadcast, utilizzare `broadcast-domain modify` Per modificare la MTU per tutte le porte all'interno del dominio di trasmissione modificato.

Si noti che i dispositivi di rete intermedi, come NIC e switch dati, possono essere impostati su dimensioni MTU più elevate rispetto agli endpoint di rete. Per ulteriori informazioni, vedere link:../performance-admin/check-network-settings-data-switches-task.html["Controllare le impostazioni di rete sugli switch dati"].

.Fasi
. Verificare l'impostazione della porta MTU sul sistema di storage:
+
`network port show -instance`

+
Ulteriori informazioni su `network port show` nella link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Riferimento al comando ONTAP"^].

. Modificare l'MTU sul dominio di trasmissione utilizzato dalle porte:
+
`network port broadcast-domain modify -ipspace _ipspace_ -broadcast-domain _broadcast_domain_ -mtu _new _mtu_`



.Esempio
Nell'esempio seguente viene modificata l'impostazione della porta MTU su 9000:

[listing]
----
network port broadcast-domain modify -ipspace Cluster -broadcast-domain Cluster -mtu 9000
----