---
permalink: performance-admin/check-network-settings-data-switches-task.html 
sidebar: sidebar 
keywords: check, network, settings, data, switches, mtu 
summary: 'Sebbene sia necessario mantenere le stesse impostazioni MTU su client, server e sistemi di storage (ovvero endpoint di rete), i dispositivi di rete intermedi come NIC e switch devono essere impostati sui valori MTU massimi per garantire che le performance non vengano compromesse.' 
---
= Controllare le impostazioni di rete ONTAP sugli switch dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sebbene sia necessario mantenere le stesse impostazioni MTU su client, server e sistemi di storage (ovvero endpoint di rete), i dispositivi di rete intermedi come NIC e switch devono essere impostati sui valori MTU massimi per garantire che le performance non vengano compromesse.

Per ottenere prestazioni ottimali, tutti i componenti della rete devono essere in grado di inoltrare frame jumbo (9000 byte IP, 9022 byte Ethernet inclusa). Gli switch dati devono essere impostati su almeno 9022 byte, ma con la maggior parte degli switch è possibile impostare un valore tipico di 9216.

.Fasi
. Per i commutatori di dati, verificare che la dimensione MTU sia impostata su 9022 o superiore.


Per ulteriori informazioni, consultare la documentazione del fornitore dello switch.
