---
permalink: performance-admin/check-iscsi-tcp-read-write-size-task.html 
sidebar: sidebar 
keywords: check, iscsi, tcp, read, write, size 
summary: 'Per iSCSI, è possibile controllare le dimensioni di lettura o scrittura del TCP per determinare se l"impostazione delle dimensioni sta creando un problema di prestazioni. Se le dimensioni sono la causa di un problema, è possibile correggerlo.' 
---
= Controllare la dimensione di lettura/scrittura TCP iSCSI ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per iSCSI, è possibile controllare le dimensioni di lettura/scrittura TCP per determinare se l'impostazione delle dimensioni sta creando un problema di prestazioni. Se le dimensioni sono la causa di un problema, è possibile correggerlo.

.Prima di iniziare
Per questa attività sono necessari comandi avanzati del livello di privilegio.

.Fasi
. Passare al livello di privilegio avanzato:
+
`set -privilege advanced`

. Verificare l'impostazione delle dimensioni della finestra TCP:
+
`vserver iscsi show -vserv,er _vserver_name_ -instance`

. Modificare l'impostazione delle dimensioni della finestra TCP:
+
`vserver iscsi modify -vserver _vserver_name_ -tcp-window-size _integer_`

. Tornare al privilegio amministrativo:
+
`set -privilege admin`



.Esempio
Nell'esempio seguente viene modificata la dimensione della finestra TCP di `SVM1` fino a 131,400 byte:

[listing]
----
cluster1::*> vserver iscsi modify -vserver vs1 -tcp-window-size 131400
----