---
permalink: performance-admin/configure-initial-unified-manager-settings-task.html 
sidebar: sidebar 
keywords: configure, initial, active iq unified manager, settings 
summary: 'La finestra di dialogo Configurazione iniziale di Active IQ Unified Manager viene visualizzata quando si accede per la prima volta all"interfaccia utente Web, che consente di configurare alcune impostazioni iniziali e aggiungere cluster.' 
---
= Configurare le impostazioni iniziali di ONTAP Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Configurazione iniziale di Active IQ Unified Manager viene visualizzata quando si accede per la prima volta all'interfaccia utente Web, che consente di configurare alcune impostazioni iniziali e aggiungere cluster.

.Fasi
. Accettare l'impostazione predefinita AutoSupport Enabled (attivato).
. Immettere i dettagli del server NTP, l'indirizzo e-mail dell'utente di manutenzione, il nome host del server SMTP e le opzioni SMTP aggiuntive, quindi fare clic su *Salva*.


.Al termine
Una volta completata la configurazione iniziale, viene visualizzata la pagina origini dati cluster, in cui è possibile aggiungere i dettagli del cluster.
