---
permalink: performance-admin/enable-disable-throughput-floors-v2-task.html 
sidebar: sidebar 
keywords: enable, disable, throughput, floors v2 
summary: 'È possibile attivare o disattivare il throughput floors v2 su AFF. L"impostazione predefinita è Enabled (attivato). Con FLOors v2 abilitato, è possibile soddisfare i piani di throughput quando i controller vengono utilizzati in modo pesante a scapito di una maggiore latenza su altri carichi di lavoro. Floors v2 si applica sia a QoS che a QoS adattivo.' 
---
= Attiva o disattiva i piani di throughput v2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare o disattivare il throughput floors v2 su AFF. L'impostazione predefinita è Enabled (attivato). Con FLOors v2 abilitato, è possibile soddisfare i piani di throughput quando i controller vengono utilizzati in modo pesante a scapito di una maggiore latenza su altri carichi di lavoro. Floors v2 si applica sia a QoS che a QoS adattivo.

.Fasi
. Passare al livello di privilegio avanzato:
+
`set -privilege advanced`

. Immettere uno dei seguenti comandi:
+
|===
| Se si desidera... | Utilizzare questo comando: 


 a| 
Disattiva piani v2
 a| 
`qos settings throughput-floors-v2 -enable false`



 a| 
Abilitare i piani v2
 a| 
`qos settings throughput-floors-v2 -enable true`

|===
+
[NOTE]
====
Per disattivare il throughput floors v2 in un cluster MetroCluster, è necessario eseguire

`qos settings throughput-floors-v2 -enable false`

comando sui cluster di origine e di destinazione.

====
+
[listing]
----
cluster1::*> qos settings throughput-floors-v2 -enable false
----

