---
permalink: performance-admin/identify-most-active-instance-task.html 
sidebar: sidebar 
keywords: identify, high-traffic, clients files 
summary: 'È possibile utilizzare la tecnologia ONTAP Active Objects per identificare client o file responsabili di una quantità sproporzionata di traffico cluster. Una volta identificati questi file o client "top", puoi ribilanciare i carichi di lavoro del cluster o intraprendere altre azioni per risolvere il problema.' 
---
= Identificare i client o i file ad alto traffico in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la tecnologia ONTAP Active Objects per identificare client o file responsabili di una quantità sproporzionata di traffico cluster. Una volta identificati questi file o client "top", è possibile ribilanciare i carichi di lavoro del cluster o intraprendere altre azioni per risolvere il problema.

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.Fasi
. Visualizzare i principali client che accedono al cluster:
+
`statistics top client show -node _node_name_ -sort-key _sort_column_ -interval _seconds_between_updates_ -iterations _iterations_ -max _number_of_instances_`

+
Ulteriori informazioni su `statistics top client show` nella link:https://docs.netapp.com/us-en/ontap-cli/statistics-top-client-show.html["Riferimento al comando ONTAP"^].

+
Il seguente comando visualizza i principali client che accedono `cluster1`:

+
[listing]
----
cluster1::> statistics top client show

cluster1 : 3/23/2016 17:59:10


                                               *Total
        Client Vserver           Node Protocol    Ops
-------------- ------- -------------- -------- ------
172.17.180.170     vs4 siderop1-vsim4      nfs    668
172.17.180.169     vs3 siderop1-vsim3      nfs    337
172.17.180.171     vs3 siderop1-vsim3      nfs    142
172.17.180.170     vs3 siderop1-vsim3      nfs    137
172.17.180.123     vs3 siderop1-vsim3      nfs    137
172.17.180.171     vs4 siderop1-vsim4      nfs     95
172.17.180.169     vs4 siderop1-vsim4      nfs     92
172.17.180.123     vs4 siderop1-vsim4      nfs     92
172.17.180.153     vs3 siderop1-vsim3      nfs      0
----
. Visualizzare i file principali a cui si accede dal cluster:
+
`statistics top file show -node _node_name_ -sort-key _sort_column_ -interval _seconds_between_updates_ -iterations _iterations_ -max _number_of_instances_`

+
Ulteriori informazioni su `statistics top file show` nella link:https://docs.netapp.com/us-en/ontap-cli/statistics-top-file-show.html["Riferimento al comando ONTAP"^].

+
Il seguente comando visualizza i file principali a cui si accede `cluster1`:

+
[listing]
----
cluster1::> statistics top file show

cluster1 : 3/23/2016 17:59:10

					              *Total
                    File Volume Vserver          Node    Ops
------------------------ ------ ------- -------------- ------
/vol/vol1/vm170-read.dat   vol1     vs4 siderop1-vsim4     22
/vol/vol1/vm69-write.dat   vol1     vs3 siderop1-vsim3      6
     /vol/vol2/vm171.dat   vol2     vs3 siderop1-vsim3      2
     /vol/vol2/vm169.dat   vol2     vs3 siderop1-vsim3      2
      /vol/vol2/p123.dat   vol2     vs4 siderop1-vsim4      2
      /vol/vol2/p123.dat   vol2     vs3 siderop1-vsim3      2
     /vol/vol1/vm171.dat   vol1     vs4 siderop1-vsim4      2
     /vol/vol1/vm169.dat   vol1     vs4 siderop1-vsim4      2
     /vol/vol1/vm169.dat   vol1     vs4 siderop1-vsim3      2
      /vol/vol1/p123.dat   vol1     vs4 siderop1-vsim4      2
----

