---
permalink: performance-admin/policy-group-assignment-restrictions.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: 'È possibile utilizzare un gruppo di criteri QoS adattivi per scalare automaticamente un limite di throughput o le dimensioni da pavimento a volume, mantenendo il rapporto tra IOPS e TB|GB al variare delle dimensioni del volume. Si tratta di un vantaggio significativo quando si gestiscono centinaia o migliaia di carichi di lavoro in un"implementazione di grandi dimensioni.' 
---
= Restrizioni all'assegnazione del gruppo di policy QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.18.1, è possibile utilizzare criteri QoS nidificati, che consentono di assegnare gruppi di criteri sia all'oggetto contenitore, ad esempio una SVM, sia al suo oggetto figlio, ad esempio un volume.  In un ambiente multi-tenant, i criteri QoS annidati consentono agli amministratori di suddividere i limiti QoS sulle SVM tra i volumi e i qtree all'interno della SVM e di fornire la possibilità di bilanciare le risorse di archiviazione tra gli ambienti di elaborazione, consentendo al contempo la definizione delle priorità dei carichi di lavoro critici per la missione.

I criteri QoS annidati sono supportati per le seguenti coppie di oggetti:

* SVM e volumi FlexVol o FlexGroup contenuti nell'SVM.
* Volumi FlexVol o FlexGroup e qtree all'interno dei volumi.


Per le policy QoS nidificate, viene utilizzata la policy applicabile più restrittiva.

Nella tabella seguente sono elencate le restrizioni.

|===
| Se si assegna... | Quindi non è possibile assegnare a un gruppo di policy... 


 a| 
SVM a un gruppo di criteri
 a| 
Tutti gli oggetti di archiviazione contenuti nell'SVM.


NOTE: Se si esegue ONTAP 9.18.1, i volumi FlexVol e FlexGroup contenuti nelle SVM _possono_ essere assegnati a un gruppo di policy.



 a| 
Su un gruppo di criteri
 a| 
L'SVM contenente il volume o eventuali LUN figlio.


NOTE: Se si esegue ONTAP 9.18.1 e versioni successive, l'SVM contenente il volume _può_ essere assegnato a un gruppo di policy.  Inoltre, è possibile assegnare qtree nei volumi FlexVol o FlexGroup .



 a| 
LUN a un gruppo di criteri
 a| 
Il volume o SVM contenente i LUN



 a| 
Su un gruppo di criteri
 a| 
Il volume o SVM contenente il file

|===