---
permalink: performance-admin/set-throughput-floor-qos-task.html 
sidebar: sidebar 
keywords: setting, throughput, floor, qos 
summary: 'È possibile utilizzare il campo min-throughput per un gruppo di policy per definire un piano di throughput per i carichi di lavoro a oggetti storage (QoS min). È possibile applicare il gruppo di criteri quando si crea o si modifica l"oggetto di storage. A partire da ONTAP 9.8, è possibile specificare il volume di throughput in IOPS o Mbps o IOPS e Mbps.' 
---
= Impostare un piano di throughput con QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `min-throughput` Campo per un gruppo di policy per definire un piano di throughput per i carichi di lavoro degli oggetti storage (QoS min). È possibile applicare il gruppo di criteri quando si crea o si modifica l'oggetto di storage. A partire da ONTAP 9.8, è possibile specificare il volume di throughput in IOPS o Mbps o IOPS e Mbps.

.Prima di iniziare
* È necessario eseguire ONTAP 9.2 o versione successiva. I piani di throughput sono disponibili a partire da ONTAP 9.2.
* Per creare un gruppo di criteri, è necessario essere un amministratore del cluster.
* A partire da ONTAP 9.13.1, è possibile applicare i piani di throughput a livello di SVM utilizzando un xref:adaptive-policy-template-task.html[modello di gruppo di policy adattive]. Non è possibile impostare un modello di gruppo di criteri adattativi su una SVM con un gruppo di criteri QoS.


.A proposito di questa attività
* A partire da ONTAP 9.4, è possibile utilizzare un gruppo di policy di qualità del servizio _non-shared_ per specificare che il piano di throughput definito deve essere applicato a ogni singolo carico di lavoro membro. Questa è l'unica condizione in cui un gruppo di policy per un piano di throughput può essere applicato a più carichi di lavoro.
+
Impostare `-is-shared=false` per `qos policy-group create` per specificare un gruppo di criteri non condiviso.

* Il throughput di un carico di lavoro potrebbe scendere al di sotto del piano specificato se la capacità delle performance (spazio di crescita) del nodo o dell'aggregato è insufficiente.
* Un oggetto storage soggetto a un limite di QoS deve essere contenuto dalla SVM a cui appartiene il gruppo di criteri. Più gruppi di criteri possono appartenere alla stessa SVM.
* È consigliabile applicare un gruppo di criteri allo stesso tipo di oggetti di storage.
* Un gruppo di criteri che definisce un piano di throughput non può essere applicato a una SVM.


.Fasi
. Verificare che la capacità delle performance sul nodo o sull'aggregato sia adeguata, come descritto in permalink :identify-residue-performance-Capacity-task.html[Identifying residue performance Capacity].
. Creare un gruppo di criteri:
+
`qos policy-group create -policy group _policy_group_ -vserver _SVM_ -min-throughput _qos_target_ -is-shared true|false`

+
Per una sintassi completa dei comandi, consulta la pagina man della tua release ONTAP. È possibile utilizzare `qos policy-group modify` comando per regolare i piani di throughput.

+
Il comando seguente crea il gruppo di criteri condivisi `pg-vs2` Con un throughput minimo di 1,000 IOPS:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs2 -vserver vs2 -min-throughput 1000iops -is-shared true
----
+
Il comando seguente crea il gruppo di criteri non condivisi `pg-vs4` senza un limite di throughput:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs4 -vserver vs4 -is-shared false
----
. Applicare un gruppo di criteri a un volume o a un LUN:
+
`_storage_object_ create -vserver _SVM_ -qos-policy-group _policy_group_`

+
Per la sintassi completa dei comandi, vedere le pagine man. È possibile utilizzare `_storage_object_modify` per applicare un gruppo di criteri diverso all'oggetto di storage.

+
Il seguente comando applica il gruppo di criteri `pg-app2` al volume `app2`:

+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app2 -aggregate aggr1 -qos-policy-group pg-app2
----
. Monitorare le performance dei gruppi di policy:
+
`qos statistics performance show`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Monitorare le performance dal cluster. Non utilizzare uno strumento sull'host per monitorare le prestazioni.

====
+
Il seguente comando mostra le prestazioni del gruppo di criteri:

+
[listing]
----
cluster1::> qos statistics performance show
Policy Group           IOPS      Throughput   Latency
-------------------- -------- --------------- ----------
-total-                 12316       47.76MB/s  1264.00us
pg_app2                  7216       28.19MB/s   420.00us
_System-Best-Effort        62       13.36KB/s     4.13ms
_System-Background         30           0KB/s        0ms
----
. Monitorare le performance dei carichi di lavoro:
+
`qos statistics workload performance show`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Monitorare le performance dal cluster. Non utilizzare uno strumento sull'host per monitorare le prestazioni.

====
+
Il seguente comando mostra le performance del carico di lavoro:

+
[listing]
----
cluster1::> qos statistics workload performance show
Workload          ID     IOPS      Throughput    Latency
--------------- ------ -------- ---------------- ----------
-total-              -    12320        47.84MB/s  1215.00us
app2-wid7967      7967     7219        28.20MB/s   319.00us
vs1-wid12279     12279     5026        19.63MB/s     2.52ms
_USERSPACE_APPS     14       55        10.92KB/s   236.00us
_Scan_Backgro..   5688       20            0KB/s        0ms
----
+
[NOTE]
====
È possibile utilizzare `qos statistics workload latency show` Comando per visualizzare statistiche dettagliate sulla latenza per i carichi di lavoro QoS.

====

