---
permalink: performance-admin/specify-clusters-monitor-task.html 
sidebar: sidebar 
keywords: specify, clusters, monitored 
summary: È necessario aggiungere un cluster a un server Active IQ Unified Manager per monitorare il cluster, visualizzare lo stato di rilevamento del cluster e monitorarne le prestazioni. 
---
= Specificare i cluster da monitorare
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario aggiungere un cluster a un server Active IQ Unified Manager per monitorare il cluster, visualizzare lo stato di rilevamento del cluster e monitorarne le prestazioni.

.Di cosa hai bisogno
* È necessario disporre delle seguenti informazioni:
+
** Nome host o indirizzo IP di gestione del cluster
+
Il nome host è il nome di dominio completo (FQDN, Fully Qualified Domain Name) o il nome breve utilizzato da Unified Manager per connettersi al cluster. Questo nome host deve essere risolto nell'indirizzo IP di gestione del cluster.

+
L'indirizzo IP di gestione del cluster deve essere la LIF di gestione del cluster della SVM (Administrative Storage Virtual Machine). Se si utilizza una LIF di gestione dei nodi, l'operazione non riesce.

** Nome utente e password dell'amministratore di ONTAP
** Tipo di protocollo (HTTP o HTTPS) che è possibile configurare sul cluster e numero di porta del cluster


* È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.
* L'amministratore di ONTAP deve disporre dei ruoli di amministratore di ONTAPI e SSH.
* L'FQDN di Unified Manager deve essere in grado di eseguire il ping di ONTAP.
+
Per verificarlo, utilizzare il comando ONTAP `ping -node _node_name_ -destination _Unified_Manager_FQDN_`.



.A proposito di questa attività
Per una configurazione MetroCluster, è necessario aggiungere i cluster locali e remoti e i cluster devono essere configurati correttamente.

.Fasi
. Fare clic su *Configurazione* > *origini dati cluster*.
. Dalla pagina Clusters, fare clic su *Add* (Aggiungi).
. Nella finestra di dialogo *Aggiungi cluster*, specificare i valori richiesti, ad esempio il nome host o l'indirizzo IP (IPv4 o IPv6) del cluster, il nome utente, la password, il protocollo di comunicazione e il numero di porta.
+
Per impostazione predefinita, il protocollo HTTPS è selezionato.

+
È possibile modificare l'indirizzo IP di gestione del cluster da IPv6 a IPv4 o da IPv4 a IPv6. Il nuovo indirizzo IP viene visualizzato nella griglia del cluster e nella pagina di configurazione del cluster al termine del successivo ciclo di monitoraggio.

. Fare clic su *Aggiungi*.
. Se si seleziona HTTPS, attenersi alla seguente procedura:
+
.. Nella finestra di dialogo *Authorize host* (autorizza host), fare clic su *View Certificate* (Visualizza certificato) per visualizzare le informazioni sul certificato del cluster.
.. Fare clic su *Sì*.
+
Unified Manager controlla il certificato solo quando il cluster viene aggiunto inizialmente, ma non lo controlla per ogni chiamata API a ONTAP.

+
Se il certificato è scaduto, non è possibile aggiungere il cluster. È necessario rinnovare il certificato SSL e aggiungere il cluster.



. *Opzionale*: Visualizzazione dello stato di rilevamento del cluster:
+
.. Esaminare lo stato di rilevamento del cluster dalla pagina *Cluster Setup*.


+
Il cluster viene aggiunto al database di Unified Manager dopo l'intervallo di monitoraggio predefinito di circa 15 minuti.


