---
permalink: performance-admin/verify-environment-supported-task.html 
sidebar: sidebar 
keywords: verify, vmware, environment, supported 
summary: 'Per installare correttamente Active IQ Unified Manager, è necessario verificare che l"ambiente VMware soddisfi i requisiti necessari.' 
---
= Verificare che l'ambiente VMware sia supportato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per una corretta installazione di Active IQ Unified Manager, è necessario verificare che l'ambiente VMware soddisfi i requisiti necessari.

.Fasi
. Verificare che l'infrastruttura VMware soddisfi i requisiti di dimensionamento per l'installazione di Unified Manager.
. Accedere alla https://mysupport.netapp.com/matrix["Matrice di interoperabilità"] per verificare di disporre di una combinazione supportata dei seguenti componenti:
+
** Versione di ONTAP
** Versione del sistema operativo ESXi
** Versione di VMware vCenter Server
** Versione di VMware Tools
** Tipo e versione del browser


+
[NOTE]
====
Il http://mysupport.netapp.com/matrix["Matrice di interoperabilità"] Elenca le configurazioni supportate per Unified Manager.

====
. Fare clic sul nome della configurazione selezionata.
+
I dettagli della configurazione vengono visualizzati nella finestra Dettagli configurazione.

. Esaminare le informazioni nelle seguenti schede:
+
** Note
+
Elenca avvisi e informazioni importanti specifici della configurazione.

** Policy e linee guida
+
Fornisce linee guida generali per tutte le configurazioni.




