---
permalink: performance-admin/worksheet-reference.html 
sidebar: sidebar 
keywords: active iq unified manager, worksheet 
summary: 'Prima di installare, configurare e connettere Active IQ Unified Manager, è necessario disporre di informazioni specifiche sull"ambiente in uso. È possibile registrare le informazioni nel foglio di lavoro.' 
---
= Foglio di lavoro Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare, configurare e connettere Active IQ Unified Manager, è necessario disporre di informazioni specifiche sull'ambiente in uso. È possibile registrare le informazioni nel foglio di lavoro.



== Informazioni sull'installazione di Unified Manager

|===


| Macchina virtuale su cui viene implementato il software | Il tuo valore 


 a| 
Indirizzo IP del server ESXi
 a| 



 a| 
Nome di dominio completo dell'host
 a| 



 a| 
Host IP address (Indirizzo IP host)
 a| 



 a| 
Maschera di rete
 a| 



 a| 
Indirizzo IP del gateway
 a| 



 a| 
Indirizzo DNS primario
 a| 



 a| 
Indirizzo DNS secondario
 a| 



 a| 
Cerca domini
 a| 



 a| 
Nome utente manutenzione
 a| 



 a| 
Password utente per la manutenzione
 a| 

|===


== Informazioni sulla configurazione di Unified Manager

|===


| Impostazione | Il tuo valore 


 a| 
Indirizzo e-mail utente manutenzione
 a| 



 a| 
Server NTP
 a| 



 a| 
Nome host o indirizzo IP del server SMTP
 a| 



 a| 
Nome utente SMTP
 a| 



 a| 
Password SMTP
 a| 



 a| 
Porta predefinita SMTP
 a| 
25 (valore predefinito)



 a| 
E-mail da cui vengono inviate le notifiche di avviso
 a| 



 a| 
Nome distinto bind LDAP
 a| 



 a| 
Password bind LDAP
 a| 



 a| 
Nome dell'amministratore di Active Directory
 a| 



 a| 
Password di Active Directory
 a| 



 a| 
Nome distinto della base del server di autenticazione
 a| 



 a| 
Nome host o indirizzo IP del server di autenticazione
 a| 

|===


== Informazioni sul cluster

Acquisire le seguenti informazioni per ciascun cluster in Unified Manager.

|===


| Cluster 1 di N. | Il tuo valore 


 a| 
Nome host o indirizzo IP di gestione del cluster
 a| 



 a| 
Nome utente amministratore di ONTAP


NOTE: All'amministratore deve essere stato assegnato il ruolo "admin".
 a| 



 a| 
Password dell'amministratore di ONTAP
 a| 



 a| 
Protocollo (HTTP o HTTPS)
 a| 

|===
.Informazioni correlate
link:../authentication/index.html["Autenticazione amministratore e RBAC"]
