---
permalink: peering/additional-information-reference.html 
sidebar: sidebar 
keywords: SnapMirror, ONTAP CLI, System Manager, diaster prep, recover 
summary: 'Per ulteriori informazioni sulle attività correlate al peering di cluster e SVM, consulta l"ampia raccolta di documentazione di NetApp.' 
---
= Dove trovare ulteriori informazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle attività correlate al peering di cluster e SVM, consulta l'ampia raccolta di documentazione di NetApp.

* link:../concepts/index.html["Concetti di ONTAP"]
+
Descrive i concetti che informano il software di gestione dei dati ONTAP, inclusa la protezione e il trasferimento dei dati.

* link:../data-protection/index.html["Protezione dei dati"]
+
Viene descritto come utilizzare l'interfaccia utente di ONTAP per eseguire la replica di SnapMirror.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-prep/index.html["Preparazione al disaster recovery dei volumi"]
+
Viene descritto come utilizzare System Manager per configurare rapidamente un volume di destinazione per il disaster recovery.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-prep/index.html["Preparazione al disaster recovery dei volumi"]
+
Viene descritto come utilizzare System Manager per ripristinare rapidamente un volume di destinazione dopo un disastro.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-backup-snapvault/index.html["Backup del volume con SnapVault"]
+
Viene descritto come utilizzare Gestione sistema per configurare rapidamente una relazione SnapVault tra i volumi.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-restore-snapvault/index.html["Gestione del ripristino dei volumi con SnapVault"]
+
Viene descritto come utilizzare Gestione sistema per ripristinare rapidamente i file da un volume di destinazione in una relazione SnapVault.

* link:../snaplock/index.html["Archiviazione e conformità con la tecnologia SnapLock"]
+
Viene descritto come replicare i file WORM in un volume SnapLock.


