---
permalink: peering/configure-intercluster-lifs-share-data-ports-task.html 
sidebar: sidebar 
keywords: configure, intercluster, lifs, shared, data, ports 
summary: È possibile configurare le LIF di intercluster sulle porte condivise con la rete dati. In questo modo si riduce il numero di porte necessarie per la rete tra cluster. 
---
= Configurare le LIF tra cluster su porte dati condivise
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare le LIF di intercluster sulle porte condivise con la rete dati. In questo modo si riduce il numero di porte necessarie per la rete tra cluster.

.Fasi
. Elencare le porte nel cluster:
+
`network port show`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente mostra le porte di rete in `cluster01`:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. Creazione di LIF intercluster da una SVM di amministrazione (IPSpace predefinito) o da una SVM di sistema (IPSpace personalizzato):
+
|===
| Opzione | Descrizione 


 a| 
*In ONTAP 9.6 e versioni successive:*
 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_ -home-port port -address _port_IP_ -netmask _netmask_`



 a| 
*In ONTAP 9.5 e versioni precedenti:*
 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -role intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`

|===
+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente vengono create le LIF tra cluster `cluster01_icl01` e. `cluster01_icl02`:

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. Verificare che le LIF dell'intercluster siano state create:
+
|===
| Opzione | Descrizione 


 a| 
*In ONTAP 9.6 e versioni successive:*
 a| 
`network interface show -service-policy default-intercluster`



 a| 
*In ONTAP 9.5 e versioni precedenti:*
 a| 
`network interface show -role intercluster`

|===
+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. Verificare che le LIF dell'intercluster siano ridondanti:
+
|===
| Opzione | Descrizione 


 a| 
*In ONTAP 9.6 e versioni successive:*
 a| 
`network interface show –service-policy default-intercluster -failover`



 a| 
*In ONTAP 9.5 e versioni precedenti:*
 a| 
`network interface show -role intercluster -failover`

|===
+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente mostra che le LIF dell'intercluster `cluster01_icl01` e. `cluster01_icl02` su `e0c` viene eseguito il failover della porta su `e0d` porta.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

