---
permalink: peering/peering-basics-concept.html 
sidebar: sidebar 
keywords: peer, basics 
summary: 'I cluster e le SVM nelle relazioni tra pari comunicano sulla rete intercluster utilizzando le interfacce logiche intercluster (LIFF). Una LIF intercluster è una LIF che supporta il servizio di interfaccia di rete "intercluster-core" e viene generalmente creata utilizzando la policy di servizio dell"interfaccia di rete "default-intercluster". È necessario creare LIF intercluster su ogni nodo dei cluster sottoposti a peering.' 
---
= Nozioni di base sul peering
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare _relazioni peer_ tra cluster di origine e di destinazione e tra SVM di origine e di destinazione prima di poter replicare le copie Snapshot utilizzando SnapMirror. Una relazione peer definisce le connessioni di rete che consentono a cluster e SVM di scambiare dati in modo sicuro.

I cluster e le SVM nelle relazioni tra pari comunicano sulla rete intercluster utilizzando _LIF (Intercluster Logical Interface)_. Una LIF intercluster è una LIF che supporta il servizio di interfaccia di rete "intercluster-core" e viene generalmente creata utilizzando la policy del servizio di interfaccia di rete "intercluster predefinito". È necessario creare LIF intercluster su ogni nodo dei cluster sottoposti a peering.

Le LIF di intercluster utilizzano i percorsi che appartengono alla SVM di sistema a cui sono assegnate. ONTAP crea automaticamente una SVM di sistema per le comunicazioni a livello di cluster all'interno di un IPSpace.

Sono supportate entrambe le topologie fan-out e cascata. In una topologia a cascata, è necessario creare solo reti di intercluster tra i cluster primario e secondario e tra i cluster secondario e terziario. Non è necessario creare una rete di intercluster tra il cluster primario e il cluster terzo.

[NOTE]
====
È possibile (ma non consigliabile) che un amministratore rimuova il servizio intercluster-core dalla policy di servizio intercluster predefinita. In questo caso, i LIF creati utilizzando "intercluster predefinito" non saranno effettivamente LIF intercluster. Per confermare che la policy di servizio dell'intercluster predefinito contiene il servizio intercluster-core, utilizzare il seguente comando:

`network interface service-policy show -policy default-intercluster`

====