---
permalink: san-admin/address-issues-when-luns-go-offline-concept.html 
sidebar: sidebar 
keywords: ways, address, issues, when, luns, go, offline 
summary: 'Quando non è disponibile spazio per le scritture, le LUN passano offline per preservare l"integrità dei dati. Le LUN possono esaurire lo spazio e andare offline per diversi motivi, oltre a diversi modi per risolvere il problema.' 
---
= Modi per risolvere i problemi quando i LUN passano offline
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando non è disponibile spazio per le scritture, le LUN passano offline per preservare l'integrità dei dati. Le LUN possono esaurire lo spazio e andare offline per diversi motivi, oltre a diversi modi per risolvere il problema.

[cols="2*"]
|===
| Se... | È possibile... 


 a| 
Aggregato pieno
 a| 
* Aggiungere altri dischi.
* Utilizzare `volume modify` comando per ridurre un volume con spazio disponibile.
* Se si dispone di volumi con garanzia di spazio che dispongono di spazio disponibile, impostare la garanzia di spazio del volume su `none` con `volume modify` comando.




 a| 
Il volume è pieno ma c'è spazio disponibile nell'aggregato contenente
 a| 
* Per i volumi di garanzia dello spazio, utilizzare `volume modify` per aumentare le dimensioni del volume.
* Per i volumi con thin provisioning, utilizzare `volume modify` per aumentare le dimensioni massime del volume.
+
Se la crescita automatica del volume non è attivata, utilizzare `volume modify -autogrow-mode` per attivarlo.

* Eliminare manualmente le copie Snapshot con `volume snapshot delete` oppure utilizzare il comando `volume snapshot autodelete modify` Comando per eliminare automaticamente le copie Snapshot.


|===
.Informazioni correlate
link:../disks-aggregates/index.html["Gestione di dischi e aggregati"]

link:../volumes/index.html["Gestione dello storage logico"]
