---
permalink: san-admin/backup-lun-host-backup-system-task.html 
sidebar: sidebar 
keywords: back up, lun, through, host, backup, system 
summary: È possibile utilizzare un LUN clonato da uno snapshot come dati di origine per il sistema di backup host. 
---
= Utilizzare un sistema di backup host per proteggere un LUN sul sistema di storage ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare un LUN clonato da uno snapshot come dati di origine per il sistema di backup host.

.Prima di iniziare
Un LUN di produzione deve esistere ed essere mappato a un igroup che includa il nome del nodo WWPN o Initiator del server applicazioni. Anche il LUN deve essere formattato e accessibile all'host

.Fasi
. Salvare su disco il contenuto dei buffer del file system host.
+
È possibile utilizzare il comando fornito dal sistema operativo host oppure SnapDrive per Windows o SnapDrive per UNIX. Puoi anche scegliere di includere questo passo nello script di pre-elaborazione del backup SAN.

. Creare una snapshot della LUN di produzione.
+
[source, cli]
----
volume snapshot create -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot> -comment <comment> -foreground false
----
. Creare un clone della LUN di produzione.
+
[source, cli]
----
volume file clone create -vserver <SMV_name> -volume <volume> -source-path <path> -snapshot-name <snapshot> -destination-path <destination_path>
----
. Creare un igroup che includa il WWPN del server di backup.
+
[source, cli]
----
lun igroup create -vserver <SVM_name> -igroup <igroup> -protocol <protocol> -ostype <os_type> -initiator <initiator>
----
. Associare il clone LUN creato al passaggio 3 all'host di backup.
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup>
----
+
È possibile scegliere di inserire questo passo nello script di post-elaborazione dell'applicazione DI backup SAN.

. Individuare il nuovo LUN dall'host e rendere il file system disponibile all'host.
+
È possibile scegliere di inserire questo passo nello script di post-elaborazione dell'applicazione DI backup SAN.

. Eseguire il backup dei dati nel clone LUN dall'host di backup su nastro utilizzando l'applicazione DI backup SAN.
. Portare il clone LUN offline.
+
[source, cli]
----
lun modify -vserver <SVM_name> -path <path> -state offline
----
. Rimuovere il clone del LUN.
+
[source, cli]
----
lun delete -vserver <SVM_name> -volume <volume> -lun <lun_name>
----
. Rimuovere l'istantanea.
+
[source, cli]
----
volume snapshot delete -vserver <SVM_name> -volume <volume> -snapshot <snapshot>
----

