---
permalink: san-admin/change-cna-uta2-optical-modules-task.html 
sidebar: sidebar 
keywords: change, cna/uta2, target, adapter, optical, modules 
summary: 'È necessario modificare i moduli ottici sull"adattatore di destinazione unificato (CNA/UTA2) per supportare la modalità di personalità selezionata per l"adattatore.' 
---
= Sostituire i moduli ottici dell'adattatore target CNA/UTA2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario modificare i moduli ottici sull'adattatore di destinazione unificato (CNA/UTA2) per supportare la modalità di personalità selezionata per l'adattatore.

.Fasi
. Verificare l'SFP+ corrente utilizzato nella scheda. Quindi, sostituire il modulo SFP+ corrente con il modulo SFP+ appropriato per il linguaggio preferito (FC o CNA).
. Rimuovere i moduli ottici correnti dall'adattatore X1143A-R6.
. Inserire i moduli corretti per l'ottica della modalità Personality (FC o CNA) preferita.
. Verificare di avere installato il modulo SFP+ corretto:
+
`network fcp adapter show -instance -node -adapter`

+
I moduli SFP+ supportati e i cavi in rame (Twinax) di marchio Cisco sono elencati nel _Hardware Universe_.



.Informazioni correlate
https://hwu.netapp.com["NetApp Hardware Universe"^]
