---
permalink: san-admin/chap-authentication-concept.html 
sidebar: sidebar 
keywords: what, chap, authentication, challenge handshake authentication protocol 
summary: 'Il protocollo CHAP (Challenge Handshake Authentication Protocol) consente la comunicazione autenticata tra gli iniziatori iSCSI e le destinazioni. Quando si utilizza l"autenticazione CHAP, si definiscono i nomi utente e le password CHAP sia sull"iniziatore che sul sistema di storage.' 
---
= Che cos'è l'autenticazione CHAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il protocollo CHAP (Challenge Handshake Authentication Protocol) consente la comunicazione autenticata tra gli iniziatori iSCSI e le destinazioni. Quando si utilizza l'autenticazione CHAP, si definiscono i nomi utente e le password CHAP sia sull'iniziatore che sul sistema di storage.

Durante la fase iniziale di una sessione iSCSI, l'iniziatore invia una richiesta di accesso al sistema di storage per iniziare la sessione. La richiesta di accesso include il nome utente CHAP dell'iniziatore e l'algoritmo CHAP. Il sistema storage risponde con una sfida CHAP. L'iniziatore fornisce una risposta CHAP. Il sistema storage verifica la risposta e autentica l'iniziatore. La password CHAP viene utilizzata per calcolare la risposta.

[cols="20,30,30,20"]
|===


| Autenticazione | In uscita | In entrata | Incontro? 


| Unidirezionale | Nome utente e password dell'iniziatore host | Nome utente e password di archiviazione | Deve corrispondere 


| Bidirezionale | Nome utente e password dell'iniziatore host | Nome utente e password di archiviazione | Deve corrispondere 


| Bidirezionale | Nome utente e password di archiviazione | Nome utente e password dell'iniziatore host | Deve corrispondere 
|===
[]
====
Il nome utente e la password in uscita per l'iniziatore host devono essere diversi dal nome utente e dalla password in uscita per il sistema di archiviazione.

====


== Linee guida per l'utilizzo dell'autenticazione CHAP

Quando si utilizza l'autenticazione CHAP, seguire alcune linee guida.

* Se si definiscono un nome utente e una password in entrata nel sistema di storage, è necessario utilizzare lo stesso nome utente e password per le impostazioni CHAP in uscita sull'iniziatore. Se si definiscono anche un nome utente e una password in uscita sul sistema di storage per abilitare l'autenticazione bidirezionale, è necessario utilizzare lo stesso nome utente e la stessa password per le impostazioni CHAP in entrata sull'iniziatore.
* Non è possibile utilizzare lo stesso nome utente e password per le impostazioni in entrata e in uscita sul sistema di storage.
* I nomi utente CHAP possono essere da 1 a 128 byte.
+
Non è consentito un nome utente nullo.

* Le password CHAP (segreto) possono essere da 1 a 512 byte.
+
Le password possono essere valori esadecimali o stringhe. Per i valori esadecimali, inserire il valore con il prefisso "`0x`" o "`0X`". Non è consentita una password nulla.



[NOTE]
====
ONTAP consente l'utilizzo di caratteri speciali, lettere non inglesi, numeri e spazi per le password CHAP (segreti). Tuttavia, questo è soggetto a restrizioni per l'host. Se uno di questi non è consentito dal tuo host specifico, non può essere utilizzato.

Ad esempio, l'iniziatore software iSCSI Microsoft richiede che le password CHAP di destinazione e di iniziatore siano almeno 12 byte se non viene utilizzata la crittografia IPsec. La lunghezza massima della password è di 16 byte, indipendentemente dall'utilizzo o meno di IPSec.

Per ulteriori restrizioni, consultare la documentazione dell'iniziatore.

====