---
permalink: san-admin/configure-ports-task.html 
sidebar: sidebar 
keywords: configure, ports 
summary: 'Per configurare l"adattatore di destinazione unificato (X1143A-R6), è necessario configurare le due porte adiacenti sullo stesso chip nella stessa modalità personality.' 
---
= Configurare le porte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per configurare l'adattatore di destinazione unificato (X1143A-R6), è necessario configurare le due porte adiacenti sullo stesso chip nella stessa modalità personality.

.Fasi
. Configurare le porte in base alle necessità per Fibre Channel (FC) o Converged Network Adapter (CNA) utilizzando `system node hardware unified-connect modify` comando.
. Collegare i cavi appropriati per FC o Ethernet da 10 GB.
. Verificare di avere installato il modulo SFP+ corretto:
+
`network fcp adapter show -instance -node -adapter`

+
Per CNA, è necessario utilizzare un SFP Ethernet da 10 GB. Per FC, è necessario utilizzare un SFP da 8 GB o un SFP da 16 GB, in base al fabric FC a cui è collegato.

+
Ulteriori informazioni su `network fcp adapter show` nella link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["Riferimento al comando ONTAP"^].


