---
permalink: san-admin/configure-nvme-lif-task.html 
sidebar: sidebar 
keywords: configure, nvme, lif 
summary: Quando si configurano le LIF NVMe, è necessario soddisfare alcuni requisiti. 
---
= Configurare una LIF NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configurano le LIF NVMe, è necessario soddisfare alcuni requisiti.

.Di cosa hai bisogno
NVMe deve essere supportato dall'adattatore FC su cui si crea la LIF. Gli adattatori supportati sono elencati in _Hardware Universe_.

https://hwu.netapp.com["NetApp Hardware Universe"^]

.A proposito di questa attività
Quando si crea una LIF NVMe si applicano le seguenti regole:

* NVMe può essere l'unico protocollo dati sulle LIF dei dati.
* È necessario configurare una LIF di gestione per ogni SVM che supporta LA SAN.
* Per ONTAP 9.5 e versioni successive:
+
** È possibile configurare solo due LIF NVMe per nodo su un massimo di quattro nodi.
** È necessario configurare una LIF NVMe sul nodo contenente lo spazio dei nomi e sul partner ha del nodo.


* Solo per ONTAP 9.4:
+
** Le LIF e gli spazi dei nomi NVMe devono essere ospitati sullo stesso nodo.
** È possibile configurare un solo LIF dati NVMe per SVM.




.Fasi
. Crea la LIF:
+
`network interface create -vserver _SVM_name_ -lif _LIF_name_ -role _LIF_role_ -data-protocol fc-nvme -home-node _home_node_ -home-port`

+
`_home_port_`

. Verificare che la LIF sia stata creata:
+
`network interface show -vserver _SVM_name_`


