---
permalink: san-admin/configure-network-best-performance-task.html 
sidebar: sidebar 
keywords: configure, your, network, best, performance 
summary: Le reti Ethernet variano notevolmente in termini di performance. È possibile massimizzare le prestazioni della rete utilizzata per iSCSI selezionando valori di configurazione specifici. 
---
= Configura la tua rete per ottenere le migliori performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le reti Ethernet variano notevolmente in termini di performance. È possibile massimizzare le prestazioni della rete utilizzata per iSCSI selezionando valori di configurazione specifici.

.Fasi
. Collegare le porte host e storage alla stessa rete.
+
Si consiglia di collegarsi agli stessi switch. Il routing non deve mai essere utilizzato.

. Selezionare le porte più veloci disponibili e dedicarle a iSCSI.
+
Le porte da 10 GbE sono le migliori. Le porte 1 GbE sono il minimo.

. Disattiva il controllo di flusso Ethernet per tutte le porte.
+
Dovrebbe essere visualizzato link:../networking/index.html["Gestione della rete"] Per utilizzare la CLI per configurare il controllo di flusso della porta Ethernet.

. Abilitare i frame jumbo (in genere MTU di 9000).
+
Tutti i dispositivi nel percorso dati, inclusi iniziatori, destinazioni e switch, devono supportare i frame jumbo. In caso contrario, l'abilitazione dei frame jumbo riduce notevolmente le performance di rete.


