---
permalink: san-admin/configure-nvme-lif-task.html 
sidebar: sidebar 
keywords: configure, nvme, lif 
summary: Quando si configurano le LIF NVMe, è necessario soddisfare alcuni requisiti. 
---
= Configura una LIF NVMe in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configurano le LIF NVMe, è necessario soddisfare alcuni requisiti.

.Prima di iniziare
NVMe deve essere supportato dall'adattatore FC su cui si crea la LIF. Gli adattatori supportati sono elencati nella https://hwu.netapp.com["Hardware Universe"^].

.A proposito di questa attività
A partire da ONTAP 9.12.1 e versioni successive, puoi configurare due LIF NVMe per nodo su un massimo di 12 nodi. In ONTAP 9.11.1 e versioni precedenti, è possibile configurare due LIF NVMe per nodo su un massimo di due nodi.

Quando si crea una LIF NVMe si applicano le seguenti regole:

* NVMe può essere l'unico protocollo dati sulle LIF dei dati.
* È necessario configurare una LIF di gestione per ogni SVM che supporta LA SAN.
* Per ONTAP 9,5 e versioni successive, devi configurare una LIF NVMe sul nodo che contiene il namespace e sul partner ha del nodo.
* Solo per ONTAP 9.4:
+
** Le LIF e gli spazi dei nomi NVMe devono essere ospitati sullo stesso nodo.
** È possibile configurare un solo LIF dati NVMe per SVM.




.Fasi
. Crea la LIF:
+
[source, cli]
----
network interface create -vserver <SVM_name> -lif <LIF_name> -role <LIF_role> -data-protocol {fc-nvme|nvme-tcp} -home-node <home_node> -home-port <home_port>
----
+

NOTE: NVME/TCP è disponibile a partire da ONTAP 9.10.1 e versioni successive.

. Verificare che la LIF sia stata creata:
+
[source, cli]
----
network interface show -vserver <SVM_name>
----


Dopo la creazione, le LIF NVMe/TCP sono in attesa del rilevamento sulla porta 8009.

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["interfaccia di rete"^]

