---
permalink: san-admin/configure-fc-adapters-task.html 
sidebar: sidebar 
keywords: configure, fc, adapters, target, initiator, mode 
summary: Ogni porta FC integrata può essere configurata singolarmente come iniziatore o destinazione. Le porte di alcuni adattatori FC possono anche essere configurate singolarmente come una porta di destinazione o una porta initiator, proprio come le porte FC integrate. 
---
= Configurare gli adattatori FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni porta FC integrata può essere configurata singolarmente come iniziatore o destinazione. Le porte di alcuni adattatori FC possono anche essere configurate singolarmente come una porta di destinazione o una porta initiator, proprio come le porte FC integrate. In è disponibile un elenco di adattatori che è possibile configurare per la modalità di destinazione link:https://hwu.netapp.com["NetApp Hardware Universe"^].

La modalità target viene utilizzata per connettere le porte agli iniziatori FC. La modalità iniziatore viene utilizzata per connettere le porte a unità nastro, librerie nastro o sistemi di archiviazione di terze parti con importazione di LUN esterne (FLI).

La stessa procedura viene utilizzata per la configurazione degli adattatori FC per il protocollo FC e il protocollo FC-NVMe. Tuttavia, solo alcuni adattatori FC supportano FC-NVMe. Vedere link:https://hwu.netapp.com["NetApp Hardware Universe"^] Per un elenco di adattatori che supportano il protocollo FC-NVMe.



== Configurare gli adattatori FC per la modalità di destinazione

.Fasi
. Portare l'adattatore offline:
+
`node run -node _node_name_ storage disable adapter _adapter_name_`

+
Se l'adattatore non viene scollegato, è anche possibile rimuovere il cavo dalla porta dell'adattatore appropriata sul sistema.

. Cambiare la scheda di rete da iniziatore a destinazione:
+
`system hardware unified-connect modify -t target -node _node_name_ adapter _adapter_name_`

. Riavviare il nodo che ospita l'adattatore modificato.
. Verificare che la porta di destinazione abbia la configurazione corretta:
+
`network fcp adapter show -node _node_name_`

+
Ulteriori informazioni su `network fcp adapter show` nella link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["Riferimento al comando ONTAP"^].

. Porta online il tuo adattatore:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -state up`





== Configurare gli adattatori FC per la modalità Initiator

.Prima di iniziare
* Le LIF della scheda di rete devono essere rimosse da tutti i set di porte di cui sono membri.
* Tutti i LIF di ogni macchina virtuale di storage (SVM) che utilizza la porta fisica da modificare devono essere migrati o distrutti prima di cambiare la personalità della porta fisica da destinazione a iniziatore.


[NOTE]
====
NVMe/FC supporta la modalità Initiator.

====
.Fasi
. Rimuovere tutti i file LIF dalla scheda:
+
`network interface delete -vserver _SVM_name_ -lif _LIF_name,LIF_name_`

+
Ulteriori informazioni su `network interface delete` nella link:https://docs.netapp.com/us-en/ontap-cli/network-interface-delete.html["Riferimento al comando ONTAP"^].

. Porta l'adattatore offline:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down`

+
Se l'adattatore non viene scollegato, è anche possibile rimuovere il cavo dalla porta dell'adattatore appropriata sul sistema.

. Cambiare la scheda di rete da destinazione a iniziatore:
+
`system hardware unified-connect modify -t initiator _adapter_port_`

. Riavviare il nodo che ospita l'adattatore modificato.
. Verificare che le porte FC siano configurate nello stato corretto per la configurazione:
+
`system hardware unified-connect show`

. Riportare l'adattatore online:
+
`node run -node _node_name_ storage enable adapter _adapter_port_`


