---
permalink: san-admin/control-monitor-io-performance-luns-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o, performance, luns, using, storage qos 
summary: 'È possibile controllare le prestazioni di input/output (i/o) alle LUN assegnando LUN ai gruppi di criteri Storage QoS. È possibile controllare le performance di i/o per garantire che i carichi di lavoro raggiungano specifici obiettivi di performance o per ridurre il carico di lavoro che ha un impatto negativo su altri carichi di lavoro.' 
---
= Controllo e monitoraggio delle performance i/o per le LUN utilizzando la QoS dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile controllare le prestazioni di input/output (i/o) alle LUN assegnando LUN ai gruppi di criteri Storage QoS. È possibile controllare le performance di i/o per garantire che i carichi di lavoro raggiungano specifici obiettivi di performance o per ridurre il carico di lavoro che ha un impatto negativo su altri carichi di lavoro.

.A proposito di questa attività
I gruppi di policy applicano un limite massimo di throughput (ad esempio, 100 MB/s). È possibile creare un gruppo di criteri senza specificare un throughput massimo, che consente di monitorare le performance prima di controllare il carico di lavoro.

È inoltre possibile assegnare le macchine virtuali di storage (SVM) con volumi FlexVol e LUN ai gruppi di policy.

Tenere presente i seguenti requisiti relativi all'assegnazione di un LUN a un gruppo di criteri:

* Il LUN deve essere contenuto dalla SVM a cui appartiene il gruppo di criteri.
+
Specificare la SVM quando si crea il gruppo di criteri.

* Se si assegna un LUN a un gruppo di criteri, non è possibile assegnare il volume o la SVM contenente i LUN a un gruppo di criteri.


Per ulteriori informazioni sull'utilizzo di Storage QoS, consultare link:../system-admin/index.html["Riferimento per l'amministrazione del sistema"].

.Fasi
. Utilizzare `qos policy-group create` per creare un gruppo di criteri.
. Utilizzare `lun create` o il `lun modify` con il `-qos-policy-group` Parametro per assegnare un LUN a un gruppo di criteri.
. Utilizzare `qos statistics` comandi per visualizzare i dati delle performance.
. Se necessario, utilizzare `qos policy-group modify` comando per regolare il limite massimo di throughput del gruppo di criteri.

