---
permalink: san-admin/copy-luns-concept.html 
sidebar: sidebar 
keywords: considerations, copying, luns, before 
summary: Prima di copiare un LUN, è necessario essere a conoscenza di alcuni elementi. 
---
= Cosa fare prima di copiare le LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di copiare un LUN, è necessario essere a conoscenza di alcuni elementi.

Gli amministratori dei cluster possono copiare un LUN tra le macchine virtuali di storage (SVM) all'interno del cluster utilizzando `lun copy` comando. Gli amministratori dei cluster devono stabilire la relazione di peering della macchina virtuale di storage (SVM) utilizzando `vserver peer create` Prima di eseguire un'operazione di copia del LUN tra SVM. Lo spazio nel volume di origine deve essere sufficiente per un clone del SIS.

I LUN delle snapshot possono essere utilizzati come LUN di origine per il `lun copy` comando. Quando si copia un LUN mediante il `lun copy` comando, la copia LUN è immediatamente disponibile per l'accesso in lettura e scrittura. Il LUN di origine rimane invariato grazie alla creazione di una copia del LUN. Sia il LUN di origine che la copia del LUN esistono come LUN univoci con numeri di serie LUN diversi. Le modifiche apportate al LUN di origine non si riflettono nella copia del LUN e le modifiche apportate alla copia del LUN non si riflettono nel LUN di origine. La mappatura LUN del LUN di origine non viene copiata nel nuovo LUN; la copia del LUN deve essere mappata.

La data Protection tramite snapshot si verifica a livello di volume. Pertanto, se si copia un LUN in un volume diverso dal volume del LUN di origine, il LUN di destinazione rientra nello schema di protezione dei dati del volume di destinazione. Se non sono stati creati snapshot per il volume di destinazione, non vengono create snapshot della copia LUN.

La copia delle LUN è un'operazione senza interruzioni.

Non è possibile copiare i seguenti tipi di LUN:

* LUN creata da un file
* LUN in stato NVFAIL
* Un LUN che si trova in una relazione di condivisione del carico
* Un LUN di classe protocollo-endpoint


Ulteriori informazioni su `lun copy` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=lun+copy["Riferimento al comando ONTAP"^].
