---
permalink: san-admin/data-protection-methods-reference.html 
sidebar: sidebar 
keywords: data, protection, methods, san, environments, snapmirror business continuity, smbc, snapshot copy, mirror, update, flexclone luns, license required, snapvault, backups, snapdrive, windows, unix 
summary: È possibile proteggere i dati creando copie di questi in modo che siano disponibili per il ripristino in caso di eliminazione accidentale, crash delle applicazioni, danneggiamento dei dati o disastro. A seconda delle esigenze di backup e protezione dei dati, ONTAP offre una vasta gamma di metodi che consentono di proteggere i dati. 
---
= Scopri i metodi di protezione dei dati ONTAP per gli ambienti SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile proteggere i dati creando copie di questi in modo che siano disponibili per il ripristino in caso di eliminazione accidentale, crash delle applicazioni, danneggiamento dei dati o disastro. A seconda delle esigenze di backup e protezione dei dati, ONTAP offre una vasta gamma di metodi che consentono di proteggere i dati.



== Sincronizzazione attiva di SnapMirror

A partire dalla disponibilità generale in ONTAP 9.9.1, fornisce l'obiettivo di tempo di ripristino zero (RTO zero) o il failover trasparente delle applicazioni (TAF) per consentire il failover automatico delle applicazioni business-critical negli ambienti SAN. SnapMirror Active Sync richiede l'installazione di ONTAP Mediator 1,2 in una configurazione con due cluster AFF o due cluster ASA (All-Flash SAN Array).

link:../snapmirror-active-sync/index.html["Sincronizzazione attiva di SnapMirror"^]



== Snapshot

Creazione, pianificazione e gestione manuale o automatica di backup multipli delle LUN grazie alle snapshot che utilizzano una quantità minima di spazio aggiuntivo sui volumi e che non comportano costi relativi alle performance. In caso di modifica o eliminazione accidentale dei dati del LUN, è possibile ripristinarli in maniera semplice e rapida da uno degli snapshot più recenti.



== LUN FlexClone (richiesta licenza FlexClone)

Fornisce copie scrivibili point-in-time di un'altra LUN in un volume attivo o in uno snapshot. Un clone e il suo padre possono essere modificati indipendentemente senza influire l'uno sull'altro.



== SnapRestore (licenza richiesta)

Permette di eseguire un recovery di dati veloce, efficiente in termini di spazio e su richiesta dalle snapshot su un intero volume. È possibile utilizzare SnapRestore per ripristinare un LUN a uno stato precedentemente conservato senza riavviare il sistema di storage.



== Copie mirrorate per la protezione dei dati (licenza SnapMirror richiesta)

Fornisce disaster recovery asincrono permettendoti di creare periodicamente snapshot di dati sul tuo volume, copiare tali snapshot su una rete locale o WAN in un volume partner, generalmente su un altro cluster e conservare tali snapshot. La copia mirror sul volume partner offre una rapida disponibilità e ripristino dei dati dal momento dell'ultimo snapshot, nel caso in cui i dati sul volume di origine siano corrotti o persi.



== Backup SnapVault (licenza SnapMirror richiesta)

Offre storage efficiente e conservazione a lungo termine dei backup. Le relazioni di SnapVault consentono di eseguire il backup di Snapshot selezionate di volumi su un volume di destinazione e di conservare i backup.

Se si eseguono backup su nastro e operazioni di archiviazione, è possibile eseguirli sui dati di cui è già stato eseguito il backup sul volume secondario SnapVault.



== SnapDrive per Windows o UNIX (licenza SnapDrive richiesta)

Configura l'accesso ai LUN, gestisce i LUN e gestisce le snapshot del sistema storage direttamente da host Windows o UNIX.



== Backup e ripristino su nastro nativo

Il supporto per la maggior parte delle unità a nastro esistenti è incluso in ONTAP, oltre a un metodo per i vendor di nastri per aggiungere dinamicamente il supporto per i nuovi dispositivi. ONTAP supporta anche il protocollo RMT (Remote Magnetic Tape), che consente il backup e il ripristino su qualsiasi sistema compatibile.

.Informazioni correlate
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30050["Documentazione NetApp: SnapDrive per UNIX"^] http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["Documentazione NetApp: SnapDrive per Windows (release correnti)"^] link:../tape-backup/index.html["Protezione dei dati mediante backup su nastro"]
