---
permalink: san-admin/define-authentication-method-initiator-task.html 
sidebar: sidebar 
keywords: define, security, policy, method, initiator 
summary: 'È possibile definire un elenco di iniziatori e i relativi metodi di autenticazione. È inoltre possibile modificare il metodo di autenticazione predefinito applicabile agli iniziatori che non dispongono di un metodo di autenticazione definito dall"utente.' 
---
= Definire un metodo di policy di sicurezza per un iniziatore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile definire un elenco di iniziatori e i relativi metodi di autenticazione. È inoltre possibile modificare il metodo di autenticazione predefinito applicabile agli iniziatori che non dispongono di un metodo di autenticazione definito dall'utente.

.A proposito di questa attività
È possibile generare password univoche utilizzando gli algoritmi dei criteri di protezione del prodotto oppure specificare manualmente le password che si desidera utilizzare.

[NOTE]
====
Non tutti gli iniziatori supportano password CHAP segrete esadecimali.

====
.Fasi
. Utilizzare `vserver iscsi security create` per creare un metodo di policy di sicurezza per un iniziatore.
+
`vserver iscsi security create -vserver vs2 -initiator iqn.1991-05.com.microsoft:host1 -auth-type CHAP -user-name bob1 -outbound-user-name bob2`

. Seguire i comandi sullo schermo per aggiungere le password.
+
Crea un metodo di policy di sicurezza per Initiator iqn.1991-05.com.microsoft:host1 con nomi utente e password CHAP in entrata e in uscita.



.Informazioni correlate
* xref:iscsi-authentication-concept.adoc[Come funziona l'autenticazione iSCSI]
* xref:chap-authentication-concept.adoc[Autenticazione CHAP]

