---
permalink: san-admin/delete-iscsi-service-svm-task.html 
sidebar: sidebar 
keywords: delete, iscsi, service, svm 
summary: 'È possibile eliminare un servizio iSCSI per una macchina virtuale di storage (SVM) se non è più necessario.' 
---
= Eliminare un servizio iSCSI per una SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare un servizio iSCSI per una macchina virtuale di storage (SVM) se non è più necessario.

.Di cosa hai bisogno
Lo stato di amministrazione del servizio iSCSI deve essere "proprio `d`" prima di poter eliminare un servizio iSCSI. È possibile spostare lo stato di amministrazione in basso con il `vserver iscsi modify` comando.

.Fasi
. Utilizzare `vserver iscsi modify` Per arrestare l'i/o al LUN.
+
`vserver iscsi modify -vserver vs1 -status-admin down`

. Utilizzare `vserver iscsi delete` Comando per rimuovere il servizio iscsi dalla SVM.
+
`vserver iscsi delete -vserver vs_1`

. Utilizzare `vserver iscsi show command` Per verificare che il servizio iSCSI sia stato eliminato da SVM.
+
`vserver iscsi show -vserver vs1`


