---
permalink: san-admin/enable-space-allocation-scsi-thin-provisioned-luns-task.html 
sidebar: sidebar 
keywords: enable, space, allocation, scsi, thinly, provisioned luns 
summary: 'Se si imposta l"opzione di allocazione dello spazio su abilitato, ONTAP notifica all"host quando il volume ha esaurito lo spazio e il LUN nel volume non può accettare le scritture. Questa opzione consente inoltre a ONTAP di recuperare automaticamente lo spazio quando l"host elimina i dati.' 
---
= Abilitare l'allocazione dello spazio per LUN con thin provisioning SCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si imposta `space-allocation` opzione a. `enabled`, ONTAP notifica all'host quando il volume ha esaurito lo spazio e il LUN nel volume non può accettare le scritture. Questa opzione consente inoltre a ONTAP di recuperare automaticamente lo spazio quando l'host elimina i dati.

.A proposito di questa attività
Il `space-allocation` l'opzione è impostata su `disabled` Per impostazione predefinita, è necessario impostare il LUN offline per attivare l'allocazione dello spazio. Dopo aver attivato l'allocazione dello spazio, è necessario eseguire il rilevamento sull'host prima che l'host riconosca che l'allocazione dello spazio è stata attivata.

.Fasi
. Portare il LUN offline.
+
`lun modify -vserver vserver_name -volume volume_name -lun lun_name -state offline`

. Impostare `-space-allocation` parametro a. `enabled`:
+
`lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -space-allocation enabled`

. Verificare che l'allocazione dello spazio sia attivata:
+
`lun show -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -fields space-allocation`

. Portare il LUN online:
+
`lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -state online`

. Sull'host, eseguire nuovamente la scansione di tutti i dischi per assicurarsi che la modifica apportata a `-space-allocation` l'opzione è stata rilevata correttamente.

