---
permalink: san-admin/enable-space-allocation.html 
sidebar: sidebar 
keywords: enable, space allocation, space reclamation, unmap, lun, hole punching, namespace, nvme, san 
summary: 'Abilitare l"allocazione dello spazio per consentire all"host e al sistema di storage di cooperare nella gestione dello spazio.' 
---
= Attivare l'allocazione dello spazio ONTAP per i protocolli SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'allocazione dello spazio ONTAP aiuta a impedire che le LUN o i namespace NVMe vengano portati offline se esauriscono lo spazio e consente agli host SAN di recuperare spazio.

Il supporto ONTAP per l'allocazione dello spazio si basa sul protocollo SAN e sulla versione di ONTAP in uso. A partire da ONTAP 9.16,1, l'allocazione dello spazio è abilitata per impostazione predefinita per i protocolli iSCSI, FC e NVMe per tutti i LUN e i namespace appena creati.

[cols="2,2,4a"]
|===
| Versione di ONTAP | Protocolli | L'allocazione dello spazio è... 


| 9.16.1 o versione successiva  a| 
* ISCSI
* FC
* NVMe

 a| 
Abilitata per impostazione predefinita per LUN e namespace appena creati



.2+| 9.15.1  a| 
* ISCSI
* FC

 a| 
Attivata per impostazione predefinita per i LUN appena creati



| NVMe | Non supportato 


.2+| 9.14.1 e precedenti  a| 
* ISCSI
* FC

 a| 
Disattivata per impostazione predefinita per i LUN appena creati



| NVMe | Non supportato 
|===
Quando l'allocazione dello spazio è attivata:

* Se uno spazio LUN o namespace esaurisce, ONTAP comunica all'host che non è disponibile spazio libero per le operazioni di scrittura. Di conseguenza, LUN o namespace rimangono online e le operazioni di lettura continuano a essere gestite. A seconda della configurazione dell'host, l'host ritenta le operazioni di scrittura fino a quando non riesce o il filesystem host non viene messo offline. Le operazioni di scrittura riprendono quando ulteriore spazio libero diventa disponibile per LUN o namespace.
+
Se l'allocazione dello spazio non è abilitata, quando una LUN o uno spazio dei nomi esaurisce lo spazio, tutte le operazioni i/o non riescono e la LUN o lo spazio dei nomi vengono portati offline; il problema di spazio deve essere risolto per riprendere le normali operazioni. Potrebbe essere necessario eseguire nuovamente la scansione dei dispositivi LUN sull'host per ripristinare i percorsi e i dispositivi a uno stato operativo.

* Un host può eseguire operazioni SCSI o NVME `UNMAP` (talvolta chiamate `TRIM`). Le operazioni di ANNULLAMENTO DELLA MAPPATURA consentono a un host di identificare blocchi di dati non più necessari perché non contengono più dati validi. L'identificazione avviene normalmente dopo l'eliminazione del file. Il sistema storage può quindi disallocare tali blocchi di dati in modo che lo spazio possa essere consumato altrove. Questa dislocazione migliora notevolmente l'efficienza complessiva dello storage, in particolare con file system con un elevato turnover dei dati.


.Prima di iniziare
L'abilitazione dell'allocazione dello spazio richiede una configurazione host in grado di gestire correttamente gli errori di allocazione dello spazio quando non è possibile completare una scrittura. Sfruttare SCSI o NVME `UNMAP` richiede una configurazione in grado di utilizzare il provisioning di blocchi logici, come definito nello standard SCSI SBC-3.

I seguenti host attualmente supportano il thin provisioning quando si attiva l'allocazione dello spazio:

* Citrix XenServer 6.5 e versioni successive
* VMware ESXi 5,0 e versioni successive
* Kernel Oracle Linux 6,2 UEK e versioni successive
* Red Hat Enterprise Linux 6.2 e versioni successive
* SUSE Linux Enterprise Server 11 e versioni successive
* Solaris 11,1 e versioni successive
* Windows


.A proposito di questa attività
Quando si aggiorna il cluster a ONTAP 9.15,1 o versioni successive, l'impostazione dell'allocazione dello spazio per tutte le LUN create prima dell'upgrade del software rimane invariata dopo l'upgrade, indipendentemente dal tipo di host. Ad esempio, se in ONTAP 9.13.1 è stato creato un LUN per un host VMware con allocazione dello spazio disattivata, l'allocazione dello spazio su tale LUN rimane disattivata dopo l'aggiornamento a ONTAP 9.15.1.

.Fasi
. Attiva allocazione spazio:
+
[source, cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation enabled
----
. Verificare che l'allocazione dello spazio sia attivata:
+
[source, cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----
. Verificare che l'allocazione dello spazio sia attivata sul sistema operativo host.
+

NOTE: Alcune configurazioni host, incluse alcune versioni di VMware ESXi, sono in grado di riconoscere automaticamente la modifica delle impostazioni e non richiedono l'intervento dell'utente. Altre configurazioni potrebbero richiedere una nuova scansione della periferica. Alcuni filesystem e gestori di volumi potrebbero richiedere impostazioni specifiche aggiuntive per abilitare il recupero dello spazio utilizzando `SCSI UNMAP`. Potrebbe essere necessario rimontare i file system o riavviare completamente il sistema operativo. Consultare la documentazione relativa all'host specifico.





== Configurazione host per host VMware ESXi 8.x e host NVMe successivi

Se si dispone di un host VMware che esegue ESXi 8.x o versione successiva con il protocollo NVMe, dopo aver attivato l'allocazione dello spazio in ONTAP, è necessario eseguire i seguenti passaggi sugli host.

.Fasi
. Sull'host ESXi, verificare che il DSM sia disattivato:
+
`esxcfg-advcfg -g /SCSi/NVmeUseDsmTp4040`

+
Il valore previsto è 0.

. Abilitare il DSM NVMe:
+
`esxcfg-advcfg -s 1 /Scsi/NvmeUseDsmTp4040`

. Verificare che il DSM sia abilitato:
+
`esxcfg-advcfg -g /SCSi/NVmeUseDsmTp4040`

+
Il valore previsto è 1.



.Link correlati
Ulteriori informazioni su link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Configurazione host NVMe-of per ESXi 8.x con ONTAP"^].
