---
permalink: san-admin/examine-configured-used-space-lun-task.html 
sidebar: sidebar 
keywords: examine, configured, used, space, lun 
summary: Conoscere lo spazio configurato e lo spazio effettivo utilizzato per le LUN può aiutare a determinare la quantità di spazio che può essere recuperato durante la rigenerazione dello spazio, la quantità di spazio riservato contenente dati e la dimensione totale configurata rispetto alla dimensione effettiva utilizzata per una LUN. 
---
= Esaminare lo spazio configurato e utilizzato di un LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conoscere lo spazio configurato e lo spazio effettivo utilizzato per le LUN può aiutare a determinare la quantità di spazio che può essere recuperato durante la rigenerazione dello spazio, la quantità di spazio riservato contenente dati e la dimensione totale configurata rispetto alla dimensione effettiva utilizzata per una LUN.

.Fase
. Visualizzare lo spazio configurato rispetto allo spazio effettivo utilizzato per un LUN:
+
`lun show`

+
L'esempio seguente mostra lo spazio configurato rispetto allo spazio effettivo utilizzato dalle LUN nella SVM (Storage Virtual Machine) vs3:

+
`lun show -vserver vs3 -fields path, size, size-used, space-reserve`

+
[listing]
----
vserver path                    size    space-reserve size-used
------- -----------------       ------- ------------- ---------
vs3     /vol/vol0/lun1          50.01GB disabled      25.00GB
vs3     /vol/vol0/lun1_backup   50.01GB disabled      32.15GB
vs3     /vol/vol0/lun2          75.00GB disabled      0B
vs3     /vol/volspace/lun0      5.00GB  enabled       4.50GB
4 entries were displayed.
----
+
Ulteriori informazioni su `lun show` nella link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html["Riferimento al comando ONTAP"^].


