---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: 'Una LUN FlexClone è una copia scrivibile point-in-time di un altro LUN in un volume attivo o in uno snapshot. Il clone e il suo padre possono essere modificati indipendentemente senza influire l"uno sull"altro.' 
---
= Utilizza le LUN FlexClone per proteggere la tua panoramica dei dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una LUN FlexClone è una copia scrivibile point-in-time di un altro LUN in un volume attivo o in uno snapshot. Il clone e il suo padre possono essere modificati indipendentemente senza influire l'uno sull'altro.

Un LUN FlexClone condivide inizialmente lo spazio con il LUN di origine. Per impostazione predefinita, il LUN FlexClone eredita l'attributo spazio-riservato del LUN padre. Ad esempio, se il LUN principale non è riservato allo spazio, anche il LUN FlexClone non è riservato per impostazione predefinita. Tuttavia, è possibile creare un LUN FlexClone non riservato allo spazio da un LUN padre che è riservato allo spazio.

Quando si clona una LUN, la condivisione dei blocchi avviene in background e non è possibile creare uno snapshot di un volume fino al termine della condivisione del blocco.

È necessario configurare il volume per attivare la funzione di eliminazione automatica del LUN FlexClone con `volume snapshot autodelete modify` comando. In caso contrario, se si desidera eliminare automaticamente i LUN FlexClone ma il volume non è configurato per l'eliminazione automatica di FlexClone, non viene eliminata alcuna LUN FlexClone.

Quando si crea un LUN FlexClone, la funzione di eliminazione automatica del LUN FlexClone viene disattivata per impostazione predefinita. È necessario abilitarlo manualmente su ogni LUN FlexClone prima che il LUN FlexClone possa essere cancellato automaticamente. Se si utilizza il provisioning di volumi semi-spessi e si desidera la garanzia di scrittura "`Best effort`" fornita da questa opzione, è necessario rendere disponibili _tutti_ i LUN FlexClone per l'eliminazione automatica.

[NOTE]
====
Quando si crea una LUN FlexClone da uno snapshot, la LUN viene automaticamente divisa dalla snapshot utilizzando un processo in background efficiente in termini di spazio, in modo che la LUN non continui a dipendere dalla snapshot o a consumare spazio aggiuntivo. Se la suddivisione in background non è stata completata e lo snapshot viene eliminato automaticamente, tale LUN FlexClone viene eliminato anche se è stata disattivata la funzione di eliminazione automatica FlexClone per tale LUN FlexClone. Una volta completata la suddivisione in background, il LUN FlexClone non viene eliminato anche se lo snapshot viene eliminato.

====
.Informazioni correlate
link:../volumes/index.html["Gestione dello storage logico"]
