---
permalink: san-admin/get-details-iscsi-session-error-recoveries-task.html 
sidebar: sidebar 
keywords: get, more, details, iscsi, session, error, recoveries 
summary: 'L"aumento del livello di ripristino degli errori di sessione iSCSI consente di ricevere informazioni più dettagliate sui ripristini degli errori iSCSI. L"utilizzo di un livello di ripristino degli errori superiore potrebbe causare una riduzione minore delle prestazioni della sessione iSCSI.' 
---
= Per ulteriori informazioni, consultare la sezione relativa ai ripristini degli errori della sessione iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'aumento del livello di ripristino degli errori di sessione iSCSI consente di ricevere informazioni più dettagliate sui ripristini degli errori iSCSI. L'utilizzo di un livello di ripristino degli errori superiore potrebbe causare una riduzione minore delle prestazioni della sessione iSCSI.

.A proposito di questa attività
Per impostazione predefinita, ONTAP è configurato per utilizzare il livello di ripristino degli errori 0 per le sessioni iSCSI. Se si utilizza un iniziatore qualificato per il livello di ripristino degli errori 1 o 2, è possibile scegliere di aumentare il livello di ripristino degli errori. Il livello di ripristino degli errori di sessione modificato influisce solo sulle sessioni appena create e non sulle sessioni esistenti.

A partire da ONTAP 9.4, la `max-error-recovery-level` l'opzione non è supportata in `iscsi show` e. `iscsi modify` comandi.

.Fasi
. Accedere alla modalità avanzata:
+
`set -privilege advanced`

. Verificare l'impostazione corrente utilizzando `iscsi show` comando.
+
`iscsi show -vserver vs3 -fields max-error-recovery-level`

+
[listing]
----
vserver max-error-recovery-level
------- ------------------------
vs3     0
----
. Modificare il livello di ripristino degli errori utilizzando `iscsi modify` comando.
+
`iscsi modify -vserver vs3 -max-error-recovery-level 2`


