---
permalink: san-admin/host-support-scsi-thin-provisioning-reference.html 
sidebar: sidebar 
keywords: ontap 9.2, host, support, scsi, thin, provisioning 
summary: 'Per sfruttare i vantaggi del thin provisioning SCSI, è necessario che sia supportato dall"host. Il thin provisioning SCSI utilizza la funzione Logical Block Provisioning, come definito nello standard SCSI SBC-3. Solo gli host che supportano questo standard possono utilizzare il thin provisioning SCSI in ONTAP.' 
---
= Supporto host per il thin provisioning SCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sfruttare i vantaggi del thin provisioning SCSI, è necessario che sia supportato dall'host. Il thin provisioning SCSI utilizza la funzione Logical Block Provisioning, come definito nello standard SCSI SBC-3. Solo gli host che supportano questo standard possono utilizzare il thin provisioning SCSI in ONTAP.

I seguenti host attualmente supportano il thin provisioning SCSI quando si attiva l'allocazione dello spazio:

* Citrix XenServer 6,5 e versioni successive
* ESXi 5,0 e versioni successive
* Kernel Oracle Linux 6,2 UEK o versione successiva
* RHEL 6,2 e versioni successive
* SLES11 e versioni successive
* Solaris 11,1 e versioni successive
* Windows


Quando si attiva la funzionalità di allocazione dello spazio in ONTAP, vengono attivate le seguenti funzionalità di thin provisioning SCSI:

* Annullamento della mappatura e creazione di report sull'utilizzo dello spazio per la bonifica dello spazio
* Segnalazione degli errori di esaurimento delle risorse

