---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: In un ambiente con thin provisioning, la gestione dello spazio lato host completa il processo di gestione dello spazio dal sistema storage liberato nel file system host. 
---
= Gestione dello spazio lato host SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In un ambiente con thin provisioning, la gestione dello spazio lato host completa il processo di gestione dello spazio dal sistema storage liberato nel file system host.

Un file system host contiene metadati per tenere traccia di quali blocchi sono disponibili per memorizzare nuovi dati e quali blocchi contengono dati validi che non devono essere sovrascritti. Questi metadati vengono memorizzati all'interno del LUN. Quando un file viene cancellato nel file system host, i metadati del file system vengono aggiornati per contrassegnare i blocchi del file come spazio libero. Lo spazio libero totale del file system viene quindi ricalcolato per includere i blocchi appena liberati. Nel sistema di storage, questi aggiornamenti dei metadati non appaiono diversi da qualsiasi altra scrittura eseguita dall'host. Pertanto, il sistema di storage non è a conoscenza di eventuali eliminazioni.

In questo modo si crea una discrepanza tra la quantità di spazio libero indicata dall'host e la quantità di spazio libero indicata dal sistema di storage sottostante. Ad esempio, si supponga di disporre di un LUN da 200 GB appena fornito assegnato all'host dal sistema storage. Sia l'host che il sistema di storage riportano 200 GB di spazio libero. L'host scrive quindi 100 GB di dati. A questo punto, sia l'host che il sistema di storage riportano 100 GB di spazio utilizzato e 100 GB di spazio inutilizzato.

Quindi, si eliminano 50 GB di dati dall'host. A questo punto, l'host segnalerà 50 GB di spazio utilizzato e 150 GB di spazio inutilizzato. Tuttavia, il sistema di storage riporta 100 GB di spazio utilizzato e 100 GB di spazio inutilizzato.

La gestione dello spazio sul lato host utilizza diversi metodi per riconciliare la differenza di spazio tra l'host e il sistema di storage.



== Gestione semplificata degli host con SnapCenter

È possibile utilizzare il software SnapCenter per semplificare alcune delle attività di gestione e protezione dei dati associate allo storage iSCSI e FC. SnapCenter è un pacchetto di gestione opzionale per host Windows e UNIX.

È possibile utilizzare il software SnapCenter per creare facilmente dischi virtuali da pool di storage che possono essere distribuiti tra diversi sistemi storage e per automatizzare le attività di provisioning dello storage e semplificare il processo di creazione di copie Snapshot e cloni da copie Snapshot coerenti con i dati host.

Per ulteriori informazioni su, consultare la documentazione dei prodotti NetApp https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"].

.Link correlati
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["Abilitare l'allocazione dello spazio per LUN con thin provisioning SCSI"]
