---
permalink: san-admin/igroups-concept.html 
sidebar: sidebar 
keywords: understand, igroups 
summary: 'i gruppi di iniziatori (igroups) sono tabelle di nomi di host WWPN del protocollo FC o di nodi host iSCSI. È possibile definire igroups e mapparli alle LUN per controllare quali iniziatori hanno accesso alle LUN.' 
---
= A proposito di igroups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
i gruppi di iniziatori (igroups) sono tabelle di nomi di host WWPN del protocollo FC o di nodi host iSCSI. È possibile definire igroups e mapparli alle LUN per controllare quali iniziatori hanno accesso alle LUN.

In genere, si desidera che tutte le porte iniziatore dell'host o gli iniziatori software abbiano accesso a un LUN. Se si utilizza un software multipathing o si dispone di host in cluster, ogni porta iniziatore o iniziatore software di ciascun host in cluster necessita di percorsi ridondanti verso la stessa LUN.

È possibile creare igroups che specifichino quali iniziatori hanno accesso alle LUN prima o dopo la creazione delle LUN, ma è necessario creare igroups prima di poter mappare una LUN a un igroup.

I gruppi iniziatori possono avere più iniziatori e più igroups possono avere lo stesso iniziatore. Tuttavia, non è possibile mappare un LUN a più igroups con lo stesso iniziatore. Un iniziatore non può essere un membro di igroups di diversi ostype.
