---
permalink: san-admin/iscsi-endpoint-isolation-concept.html 
sidebar: sidebar 
keywords: iscsi, endpoint, isolation, add, remove, initiator, address, range 
summary: A partire da ONTAP 9.1, i comandi di sicurezza iSCSI esistenti sono stati migliorati per accettare un intervallo di indirizzi IP o più indirizzi IP. 
---
= Isolamento degli endpoint iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I comandi di protezione iSCSI esistenti possono accettare un intervallo di indirizzi IP o più indirizzi IP.

Tutti gli iniziatori iSCSI devono fornire indirizzi IP di origine quando si stabilisce una sessione o una connessione con una destinazione. Questa nuova funzionalità impedisce a un iniziatore di accedere al cluster se l'indirizzo IP di origine non è supportato o è sconosciuto, fornendo uno schema di identificazione univoco. Qualsiasi iniziatore che ha origine da un indirizzo IP non supportato o sconosciuto avrà il proprio login rifiutato nel layer di sessione iSCSI, impedendo all'iniziatore di accedere a qualsiasi LUN o volume all'interno del cluster.

Implementare questa nuova funzionalità con due nuovi comandi per gestire le voci preesistenti.



== Aggiungere l'intervallo di indirizzi dell'iniziatore

Migliorare la gestione della sicurezza di iSCSI Initiator aggiungendo un intervallo di indirizzi IP o più indirizzi IP con `vserver iscsi security add-initiator-address-range` comando.

`cluster1::> vserver iscsi security add-initiator-address-range`



== Rimuovere l'intervallo di indirizzi dell'iniziatore

Rimuovere un intervallo di indirizzi IP o più indirizzi IP con `vserver iscsi security remove-initiator-address-range` comando.

`cluster1::> vserver iscsi security remove-initiator-address-range`
