---
permalink: san-admin/learn-about-asa.html 
sidebar: sidebar 
keywords: all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 'Gli array SAN all-flash NetApp (ASA) sono disponibili a partire da ONTAP 9,7.  Gli ASA sono soluzioni solo SAN all-flash basate su piattaforme NetApp AFF comprovate.' 
---
= Ulteriori informazioni sulle configurazioni degli array SAN all-flash
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Gli array SAN all-flash NetApp (ASA) sono disponibili a partire da ONTAP 9,7.  Gli ASA sono soluzioni solo SAN all-flash basate su piattaforme NetApp AFF comprovate.

Le piattaforme ASA includono quanto segue:

* ASA A150
* ASA A250
* ASA A400
* ASA A800
* ASA A900
* ASA C250
* ASA C400
* ASA C800



NOTE: A partire da ONTAP 9.16.0, un'esperienza ONTAP semplificata specifica per i clienti solo SAN è disponibile sui sistemi ASA R2 (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30 o ASA A20). Se si dispone di un sistema ASA R2, consultare la link:https://docs.netapp.com/us-en/asa-r2/index.html["Documentazione del sistema ASA R2"^].

Le piattaforme ASA utilizzano Active-Active simmetrico per il multipathing. Tutti i percorsi sono attivi/ottimizzati, quindi in caso di failover dello storage, l'host non deve attendere che la transizione ALUA dei percorsi di failover riprenda l'i/O. In questo modo si riduce il tempo di failover.



== Configurare un ASA

Gli All-Flash SAN Array (ASA) seguono la stessa procedura di configurazione dei sistemi non ASA.

System Manager guida l'utente attraverso le procedure necessarie per inizializzare il cluster, creare un Tier locale, configurare i protocolli e eseguire il provisioning dello storage per ASA.

xref:../software_setup/concept_decide_whether_to_use_ontap_cli.html[Inizia subito a configurare il cluster di ONTAP].



== Impostazioni e utility dell'host ASA

Le impostazioni dell'host per la configurazione degli array SAN all-flash (ASA) sono identiche a quelle di tutti gli altri host SAN.

È possibile scaricare link:https://mysupport.netapp.com/NOW/cgi-bin/software["Software NetApp host Utilities"^] per gli host specifici dal sito di supporto.



== Metodi per identificare un sistema ASA

È possibile identificare un sistema ASA utilizzando Gestione di sistema o l'interfaccia a riga di comando (CLI) di ONTAP.

* *Dalla dashboard di System Manager*: Fare clic su *Cluster > Overview* e selezionare il nodo di sistema.
+
La *PERSONALITÀ* viene visualizzata come *All-Flash SAN Array*.

* *Dalla CLI*: Immettere il `san config show` comando.
+
Il valore dell'array SAN all-flash restituisce il valore vero per i sistemi ASA.

+
Ulteriori informazioni su `san config show` nella link:https://docs.netapp.com/us-en/ontap-cli/san-config-show.html["Riferimento al comando ONTAP"^].



.Informazioni correlate
* link:https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf["Report tecnico 4968: Integrità e disponibilità dei dati degli array NetApp All-SAN"^]
* link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080pdf.pdf["Report tecnico NetApp 4080: Best practice per le SAN moderne"^]

