---
permalink: san-admin/lif-movement-concept.html 
sidebar: sidebar 
keywords: considerations, san, lif, movement 
summary: È necessario eseguire uno spostamento LIF solo se si modifica il contenuto del cluster, ad esempio aggiungendo nodi al cluster o eliminando nodi dal cluster. Se si esegue un movimento LIF, non è necessario ridefinire la zona del fabric FC o creare nuove sessioni iSCSI tra gli host collegati del cluster e la nuova interfaccia di destinazione. 
---
= Cosa fare prima di spostare UNA SAN LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario eseguire uno spostamento LIF solo se si modifica il contenuto del cluster, ad esempio aggiungendo nodi al cluster o eliminando nodi dal cluster. Se si esegue un movimento LIF, non è necessario ridefinire la zona del fabric FC o creare nuove sessioni iSCSI tra gli host collegati del cluster e la nuova interfaccia di destinazione.

Non è possibile spostare UN LIF SAN utilizzando `network interface move` comando. Lo spostamento DELLA SAN LIF deve essere eseguito portando la LIF offline, spostando la LIF su un nodo o una porta home differente e quindi riportandola online nella nuova posizione. ALUA (Asymmetric Logical Unit Access) offre percorsi ridondanti e selezione automatica del percorso come parte di qualsiasi soluzione SAN ONTAP. Pertanto, non si verifica alcuna interruzione i/o quando la LIF viene portata offline per il movimento. L'host semplicemente riprova e sposta i/o in un altro LIF.

Grazie al movimento LIF, puoi effettuare le seguenti operazioni senza interruzioni:

* Sostituire una coppia ha di un cluster con una coppia ha aggiornata in modo trasparente per gli host che accedono ai dati LUN
* Aggiornare una scheda di interfaccia di destinazione
* Spostare le risorse di una macchina virtuale di storage (SVM) da un set di nodi in un cluster a un altro set di nodi nel cluster

