---
permalink: san-admin/lun-san-environments-concept.html 
sidebar: sidebar 
keywords: lun, guidelines, assigning, assign, ids, mapping, map, igroups 
summary: Prima di iniziare a configurare le LUN sul cluster, è necessario rivedere le linee guida del LUN. 
---
= Cosa fare prima di creare un LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Perché le dimensioni effettive del LUN variano leggermente

Per quanto riguarda le dimensioni dei LUN, è necessario conoscere quanto segue.

* Quando si crea un LUN , le dimensioni effettive del LUN potrebbero variare leggermente in base al tipo di sistema operativo del LUN. Il tipo di sistema operativo LUN non può essere modificato dopo la creazione del LUN.
* Se si crea un LUN con le dimensioni massime del LUN, tenere presente che le dimensioni effettive del LUN potrebbero essere leggermente inferiori. ONTAP arrotonda il limite per essere leggermente inferiore.
* I metadati per ogni LUN richiedono circa 64 KB di spazio nell'aggregato contenente. Quando si crea un LUN, è necessario assicurarsi che l'aggregato contenente disponga di spazio sufficiente per i metadati del LUN. Se l'aggregato non contiene spazio sufficiente per i metadati del LUN, alcuni host potrebbero non essere in grado di accedere al LUN.




== Linee guida per l'assegnazione degli ID LUN

In genere, l'ID LUN predefinito inizia con 0 e viene assegnato in incrementi di 1 per ogni LUN mappato aggiuntivo. L'host associa l'ID LUN alla posizione e al nome del percorso del LUN. L'intervallo di numeri ID LUN validi dipende dall'host. Per informazioni dettagliate, consultare la documentazione fornita con le utility host.



== Linee guida per la mappatura delle LUN in igroups

* È possibile mappare un LUN solo una volta su un igroup.
* Come Best practice, è necessario mappare un LUN a un solo iniziatore specifico attraverso l'igroup.
* È possibile aggiungere un singolo iniziatore a più igroups, ma l'iniziatore può essere mappato a un solo LUN.
* Non è possibile utilizzare lo stesso ID LUN per due LUN mappati allo stesso igroup.
* È necessario utilizzare lo stesso tipo di protocollo per igroups e set di porte.

