---
permalink: san-admin/manage-systems-fc-adapters-concept.html 
sidebar: sidebar 
keywords: manage, systems, fc, adapters 
summary: 'Sono disponibili comandi per gestire gli adattatori FC integrati e le schede adattatore FC. Questi comandi possono essere utilizzati per configurare la modalità dell"adattatore, visualizzare le informazioni sull"adattatore e modificare la velocità.' 
---
= Gestire i sistemi con adattatori FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili comandi per gestire gli adattatori FC integrati e le schede adattatore FC. Questi comandi possono essere utilizzati per configurare la modalità dell'adattatore, visualizzare le informazioni sull'adattatore e modificare la velocità.

La maggior parte dei sistemi di storage dispone di adattatori FC integrati che possono essere configurati come iniziatori o destinazioni.  È anche possibile utilizzare schede adattatrici FC configurate come iniziatori o destinazioni.  Gli iniziatori si collegano agli scaffali dei dischi back-end e, possibilmente, ad array di archiviazione esterni.  I target si connettono solo agli switch FC.  Sia le porte HBA di destinazione FC che la velocità della porta dello switch devono essere impostate sullo stesso valore e non devono essere impostate su automatico.

.Informazioni correlate
link:../san-config/index.html["Configurazione SAN"]
