---
permalink: san-admin/map-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: map, nvme, namespace, subsystem 
summary: Quando si utilizza NVMe, è necessario mappare uno spazio dei nomi a un sottosistema. 
---
= Mappare uno spazio dei nomi NVMe in un sottosistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'associazione di un namespace NVMe a un sottosistema consente l'accesso ai dati dall'host.  È possibile mappare un namespace NVMe a un sottosistema quando si esegue il provisioning dello storage oppure è possibile farlo dopo che è stato eseguito il provisioning dello storage.

A partire da ONTAP 9.17.1, se si utilizza una configurazione ActiveSync SnapMirror , è possibile aggiungere una SVM a un host come server virtuale prossimale durante l'aggiunta dell'host a un sottosistema NVMe. I percorsi ottimizzati per un namespace in un sottosistema NVMe vengono pubblicati su un host solo dalla SVM configurata come server virtuale prossimale.

A partire da ONTAP 9.14.1, è possibile assegnare priorità all'allocazione delle risorse per host specifici. Per impostazione predefinita, quando un host viene aggiunto al sottosistema NVMe, viene assegnata una priorità regolare. È possibile utilizzare l'interfaccia a riga di comando (CLI) di ONTAP per modificare manualmente la priorità predefinita da normale ad alta.  Agli host assegnati una priorità alta viene assegnato un numero maggiore di code i/o e profondità di coda.


NOTE: Se si desidera assegnare una priorità elevata a un host aggiunto a un sottosistema in ONTAP 9.13.1 o versioni precedenti, è possibile farlo xref:../nvme/change-host-priority-nvme-task.html[modificare la priorità dell'host].

.Prima di iniziare
Lo spazio dei nomi e il sottosistema devono essere già creati. Per creare uno spazio dei nomi e un sottosistema, vedere link:create-nvme-namespace-subsystem-task.html["Eseguire il provisioning dello storage NVMe"].



== Mappa uno spazio dei nomi NVMe

.Fasi
. Ottenere l'NQN dall'host.
. Aggiungere l'NQN host al sottosistema:
+
[source, cli]
----
vserver nvme subsystem host add -vserver <SVM_name> -subsystem <subsystem_name> -host-nqn <Host_NQN_:subsystem._subsystem_name>
----
+
Se si desidera modificare la priorità predefinita dell'host da normale ad alta, utilizzare l' `-priority high`opzione . Questa opzione è disponibile a partire da ONTAP 9.14.1. Ulteriori informazioni su `vserver nvme subsystem host add` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-add.html["Riferimento al comando ONTAP"^].

+
Se si desidera aggiungere un SVM come  `proximal-vserver` a un host durante l'aggiunta dell'host a un sottosistema NVMe in una configurazione di sincronizzazione attiva SnapMirror , è possibile utilizzare  `-proximal-vservers` Opzione. Questa opzione è disponibile a partire da ONTAP 9.17.1. È possibile aggiungere l'SVM di origine o di destinazione, o entrambe. L'SVM in cui si esegue questo comando è quella predefinita.

. Mappare lo spazio dei nomi nel sottosistema:
+
[source, cli]
----
vserver nvme subsystem map add -vserver <SVM_name> -subsystem <subsystem_name> -path <path>
----
+
Uno spazio dei nomi può essere mappato solo a un singolo sottosistema. Ulteriori informazioni su `vserver nvme subsystem map add` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-map-add.html["Riferimento al comando ONTAP"^].

. Verificare che lo spazio dei nomi sia mappato al sottosistema:
+
[source, cli]
----
vserver nvme namespace show -vserver <SVM_name> -instance
----
+
Il sottosistema deve essere elencato come `Attached subsystem` . Ulteriori informazioni su `vserver nvme namespace show` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-namespace-show.html["Riferimento al comando ONTAP"^].


