---
permalink: san-admin/microsoft-offloaded-data-transfer-odx-concept.html 
sidebar: sidebar 
keywords: microsoft, offloaded, data, transfer, odx 
summary: 'Microsoft Offloaded Data Transfer (ODX), noto anche come offload delle copie, consente il trasferimento diretto dei dati all"interno di un dispositivo di storage o tra dispositivi di storage compatibili senza trasferire i dati attraverso il computer host.' 
---
= Panoramica di Microsoft Offloaded Data Transfer (ODX)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft Offloaded Data Transfer (ODX), noto anche come _copy offload_, consente il trasferimento diretto dei dati all'interno di un dispositivo di storage o tra dispositivi di storage compatibili senza trasferire i dati attraverso il computer host.

ONTAP supporta ODX per i protocolli SMB e SAN.

Nei trasferimenti di file non ODX, i dati vengono letti dall'origine e trasferiti attraverso la rete all'host. L'host trasferisce i dati di nuovo sulla rete alla destinazione. Nel trasferimento di file ODX, i dati vengono copiati direttamente dall'origine alla destinazione senza passare attraverso l'host.

Poiché le copie ODX offloaded vengono eseguite direttamente tra l'origine e la destinazione, si ottengono benefici significativi in termini di performance, tra cui tempi di copia più rapidi, utilizzo ridotto di CPU e memoria sul client e utilizzo ridotto della larghezza di banda i/o di rete.

Per gli ambienti SAN, ODX è disponibile solo quando è supportato sia dall'host che dal sistema storage. I computer client che supportano ODX e che hanno ODX abilitato automaticamente e in modo trasparente utilizzano il trasferimento di file offload durante lo spostamento o la copia dei file. ODX viene utilizzato indipendentemente dal fatto che si trascinino i file tramite Esplora risorse o si utilizzino comandi di copia dei file dalla riga di comando o che un'applicazione client avvii richieste di copia dei file.
