---
permalink: san-admin/move-san-lifs-task.html 
sidebar: sidebar 
keywords: move, san, lifs 
summary: Se un nodo deve essere messo offline, è possibile spostare un SAN LIF per preservarne le informazioni di configurazione, come il suo WWPN, ed evitare di riconfigurare la switch fabric. 
---
= Spostare un ONTAP SAN LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se un nodo deve essere messo offline, è possibile spostare una LIF SAN per preservarne le informazioni di configurazione, come il suo WWPN. Lo spostamento di una LIF non richiede la riconfigurazione della fabric FC né la creazione di nuove sessioni iSCSI tra gli host del cluster e l'interfaccia di destinazione. È possibile spostare le LIF SAN su qualsiasi nodo del cluster, ma non tra storage virtual machine (SVM).

È possibile spostare un LIF per eseguire le seguenti operazioni senza interrompere il funzionamento:

* Sostituire una coppia HA di un cluster con una coppia HA aggiornata in modo trasparente per gli host che accedono ai dati LUN o namespace
* Aggiornare una scheda di interfaccia di destinazione
* Spostare le risorse di una macchina virtuale di storage (SVM) da un set di nodi in un cluster a un altro set di nodi nel cluster


Non è possibile spostare un SAN LIF utilizzando il  `network interface move` comando. Per spostare un SAN LIF, è necessario metterlo offline, spostarlo su un nuovo nodo o porta home, e quindi riportarlo online. Poiché un SAN LIF deve essere messo offline prima di essere spostato, il traffico host deve fare affidamento sul software di multipathing host per fornire un accesso senza interruzioni al LUN, in modo che non vi siano interruzioni di I/O.

.Prima di iniziare
Se la LIF è membro di un set di porte, la LIF deve essere stata rimossa dalla porta impostata prima di poter spostare la LIF in un nodo diverso.

.A proposito di questa attività
Il nodo di destinazione e la porta fisica di un LIF che si desidera spostare devono trovarsi sullo stesso fabric FC o sulla stessa rete Ethernet. Se si sposta un LIF in un fabric diverso che non è stato correttamente zonato o si sposta un LIF in una rete Ethernet che non dispone di connettività tra iSCSI Initiator e destinazione, il LUN non sarà accessibile quando viene riportato online.

.Fasi
. Visualizzare lo stato amministrativo e operativo della LIF:
+
[source, cli]
----
network interface show -vserver <SVM_name>
----
+
Ulteriori informazioni su `network interface show` nella link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Riferimento al comando ONTAP"^].

. Modificare lo stato del LIF in `down` (offline):
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin down
----
+
Ulteriori informazioni su `network interface modify` nella link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["Riferimento al comando ONTAP"^].

. Assegnare alla LIF un nuovo nodo e una nuova porta:
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -home-node <node_name> -home-port <port_name>
----
. Modificare lo stato del LIF in `up` (online):
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin up
----
. Verificare le modifiche:
+
[source, cli]
----
network interface show -vserver <SVM_name>
----

