---
permalink: san-admin/nvme-copy-offload.html 
sidebar: sidebar 
keywords: configure, ports 
summary: 'La funzione di offload della copia NVMe consente a un host NVMe di trasferire le operazioni di copia dalla propria CPU alla CPU del controller di archiviazione ONTAP . L"host può copiare i dati da uno spazio dei nomi NVMe a un altro, riservando le risorse della CPU per i carichi di lavoro delle applicazioni.' 
---
= Scopri di più sullo scaricamento della copia NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funzione di offload della copia NVMe consente a un host NVMe di trasferire le operazioni di copia dalla propria CPU alla CPU del controller di archiviazione ONTAP . L'host può copiare i dati da uno spazio dei nomi NVMe a un altro, riservando le risorse della CPU per i carichi di lavoro delle applicazioni.

Supponiamo, ad esempio, di dover ribilanciare i carichi di lavoro di archiviazione per migliorare la distribuzione delle prestazioni.  Ciò richiede la migrazione di dieci macchine virtuali (VM) contenenti 45 namespace NVMe con una dimensione media di 500 GB ciascuna.  Ciò significa che è necessario copiare circa 22,5 TB di dati.  Invece di utilizzare la propria CPU per la migrazione dei dati, l'host può utilizzare l'offload della copia NVMe per evitare di ridurre le risorse della CPU per i carichi di lavoro delle applicazioni durante la copia dei dati.



== Supporto e limitazioni dell'offload della copia NVMe

L'offload della copia NVMe è supportato a partire da ONTAP 9.18.1.  ONTAP non può avviare l'offload della copia NVMe; deve essere supportato e avviato dall'host.

Le seguenti limitazioni si applicano alle operazioni di copia offload NVMe con ONTAP:

* La dimensione massima supportata per l'operazione di copia è 16 MB.
* I dati possono essere migrati solo tra namespace NVMe all'interno dello stesso sottosistema.
* I dati possono essere migrati solo tra nodi nella stessa coppia HA.

