---
permalink: san-admin/remove-lif-from-portset-task.html 
sidebar: sidebar 
keywords: remove, san, lif, port, set 
summary: Se la LIF che si desidera eliminare o spostare si trova in un set di porte, è necessario rimuovere la LIF dal set di porte prima di poter eliminare o spostare la LIF. 
---
= Rimuovere una LIF SAN da un set di porte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la LIF che si desidera eliminare o spostare si trova in un set di porte, è necessario rimuovere la LIF dal set di porte prima di poter eliminare o spostare la LIF.

.A proposito di questa attività
È necessario eseguire il passaggio 1 della procedura seguente solo se una porta LIF è impostata. Non è possibile rimuovere l'ultimo LIF in un set di porte se il set di porte è associato a un gruppo di iniziatori. In caso contrario, è possibile iniziare con la fase 2 se sono presenti più LIF nella porta impostata.

.Fasi
. Se nella porta impostata è presente un solo LIF, utilizzare `lun igroup unbind` comando per disassociare il set di porte dal gruppo di iniziatori.
+
[NOTE]
====
Quando si dislega un gruppo di iniziatori da un set di porte, tutti gli iniziatori del gruppo di iniziatori hanno accesso a tutte le LUN di destinazione mappate al gruppo di iniziatori su tutte le interfacce di rete.

====
+
`cluster1::>lun igroup unbind -vserver vs1 -igroup ig1`

+
Ulteriori informazioni su `lun igroup unbind` nella link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-unbind.html["Riferimento al comando ONTAP"^].

. Utilizzare `lun portset remove` Comando per rimuovere LIF dal set di porte.
+
`cluster1::> port set remove -vserver vs1 -portset ps1 -port-name lif1`

+
Ulteriori informazioni su `lun portset remove` nella link:https://docs.netapp.com/us-en/ontap-cli/lun-portset-remove.html["Riferimento al comando ONTAP"^].


