---
permalink: san-admin/resolve-iscsi-error-messages-reference.html 
sidebar: sidebar 
keywords: resolve, iscsi, error messages, storage system 
summary: Esistono diversi messaggi di errore comuni relativi a iSCSI che è possibile visualizzare con il comando show del registro eventi. Devi sapere cosa significano questi messaggi e cosa puoi fare per risolvere i problemi che identificano. 
---
= Risoluzione dei messaggi di errore iSCSI sul sistema di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili diversi messaggi di errore comuni relativi a iSCSI che è possibile visualizzare con `event log show` comando. Devi sapere cosa significano questi messaggi e cosa puoi fare per risolvere i problemi che identificano.

La seguente tabella contiene i messaggi di errore più comuni e le istruzioni per risolverli:

[cols="3*"]
|===
| Messaggio | Spiegazione | Cosa fare 


 a| 
`ISCSI: network interface identifier disabled for use; incoming connection discarded`
 a| 
Il servizio iSCSI non è abilitato sull'interfaccia.
 a| 
È possibile utilizzare `iscsi interface enable` Per attivare il servizio iSCSI sull'interfaccia. Ad esempio:

`iscsi interface enable -vserver vs1 -lif lif1`



 a| 
`ISCSI: Authentication failed for initiator nodename`
 a| 
CHAP non è configurato correttamente per l'iniziatore specificato.
 a| 
Controllare le impostazioni CHAP; non è possibile utilizzare lo stesso nome utente e password per le impostazioni in entrata e in uscita sul sistema di storage:

* Le credenziali in entrata nel sistema di storage devono corrispondere alle credenziali in uscita sull'iniziatore.
* Le credenziali in uscita sul sistema di storage devono corrispondere alle credenziali in entrata sull'iniziatore.


|===