---
permalink: san-admin/restore-all-luns-volume-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, all, luns in a volume, from, snapshot copy 
summary: È possibile utilizzare il comando di ripristino dello snapshot di un volume per ripristinare tutte le LUN di un volume specifico da uno snapshot. 
---
= Ripristino di tutte le LUN di un volume da una snapshot ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il `volume snapshot restore` comando per ripristinare da uno snapshot tutti i LUN di un volume specifico.

.Fasi
. Interrompere tutti gli accessi host alle LUN dall'host.
+
L'utilizzo di SnapRestore senza interrompere tutti gli accessi host alle LUN nel volume può causare la corruzione dei dati e gli errori di sistema.

. Smontare i LUN su tale host in modo che l'host non possa accedere ai LUN.
. Dismappare le LUN:
+
[source, cli]
----
lun mapping delete -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Determinare lo snapshot in cui si desidera ripristinare il volume:
+
[source, cli]
----
volume snapshot show -vserver <SVM_name> -volume <volume_name>

----
. Impostare i privilegi su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
. Ripristinare i dati:
+
[source, cli]
----
volume snapshot restore -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot_name>
----
. Seguire le istruzioni visualizzate.
. Rimappare le LUN:
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Verificare che i LUN siano online:
+
[source, cli]
----
lun show -vserver <SVM_name> -path <lun_path> -fields state
----
. Se le LUN non sono online, portarle online:
+
[source, cli]
----
lun modify -vserver <SVM_name> -path <lun_path> -state online
----
. Impostare i privilegi su admin:
+
[source, cli]
----
set -privilege admin
----
. Dall'host, rimontare i LUN.
. Dall'host, riavviare l'accesso ai LUN.

