---
permalink: san-admin/san-host-provisioning-concept.html 
sidebar: sidebar 
keywords: understand, san host, provisioning 
summary: 'Negli ambienti SAN, i sistemi storage sono destinazioni che dispongono di dispositivi di destinazione dello storage. Per iSCSI e FC, i dispositivi di destinazione dello storage sono denominati LUN (unità logiche). Per NVMe (non-volatile Memory Express) su Fibre Channel, i dispositivi di destinazione dello storage vengono definiti namespace.' 
---
= Provisioning SAN con iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Negli ambienti SAN, i sistemi storage sono destinazioni che dispongono di dispositivi di destinazione dello storage. Per iSCSI e FC, i dispositivi di destinazione dello storage sono denominati LUN (unità logiche). Per NVMe (non-volatile Memory Express) su Fibre Channel, i dispositivi di destinazione dello storage vengono definiti namespace.

È possibile configurare lo storage creando LUN per iSCSI e FC o spazi dei nomi per NVMe. Gli host accedono quindi ai LUN o agli spazi dei nomi utilizzando le reti con protocollo iSCSI (Internet Small computer Systems Interface) o FC (Fibre Channel).

Per connettersi alle reti iSCSI, gli host possono utilizzare schede di rete Ethernet (NIC) standard, schede TOE (TCP offload Engine) con iniziatori software, adattatori di rete convergenti (CNA) o HBA (host bus adapter) iSCSI dedicati.

Per connettersi alle reti FC, gli host richiedono HBA o CNA FC.

I protocolli FC supportati includono:

* FC
* FCoE
* NVMe




== Nomi e connessioni di rete del nodo di destinazione iSCSI

I nodi di destinazione iSCSI possono connettersi alla rete in diversi modi:

* Interfacce su Ethernet che utilizzano software integrato in ONTAP.
* Su più interfacce di sistema, con un'interfaccia utilizzata per iSCSI che può anche trasmettere il traffico per altri protocolli, come SMB e NFS.
* Utilizzando un adattatore di destinazione unificato (UTA) o un adattatore di rete convergente (CNA).


Ogni nodo iSCSI deve avere un nome di nodo.

I due formati, o designatori di tipo, per i nomi dei nodi iSCSI sono _iqn_ e _eui_. La destinazione iSCSI SVM utilizza sempre il designatore di tipo iqn. L'iniziatore può utilizzare il designatore di tipo iqn o eui.



== Nome del nodo del sistema di storage

Ogni SVM che esegue iSCSI ha un nome di nodo predefinito basato su un nome di dominio inverso e un numero di codifica univoco.

Il nome del nodo viene visualizzato nel seguente formato:

iqn.1992-08.com.netapp:sn.`_unique-encoding-number_`

L'esempio seguente mostra il nome del nodo predefinito per un sistema di storage con un numero di codifica univoco:

iqn.1992-08.com.netapp:sn.812921059e6c11e097b3123478563412:vs.6



== Porta TCP per iSCSI

Il protocollo iSCSI è configurato in ONTAP per utilizzare la porta TCP numero 3260.

ONTAP non supporta la modifica del numero di porta per iSCSI. La porta numero 3260 è registrata come parte della specifica iSCSI e non può essere utilizzata da altre applicazioni o servizi.

.Informazioni correlate
https://docs.netapp.com/us-en/ontap-sanhost/["Documentazione NetApp: Configurazione host SAN ONTAP"]
