---
permalink: san-admin/san-provisioning-nvme-concept.html 
sidebar: sidebar 
keywords: san, provisioning, nvme 
summary: A partire da ONTAP 9.4, NVMe/FC è supportato in ambiente SAN. NVMe/FC consente agli amministratori dello storage di eseguire il provisioning degli spazi dei nomi e dei sottosistemi e di mappare gli spazi dei nomi ai sottosistemi, in modo simile al modo in cui i LUN vengono forniti e mappati a igroups per FC e iSCSI. 
---
= Provisioning SAN con NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.4, NVMe/FC è supportato in ambiente SAN. NVMe/FC consente agli amministratori dello storage di eseguire il provisioning degli spazi dei nomi e dei sottosistemi e di mappare gli spazi dei nomi ai sottosistemi, in modo simile al modo in cui i LUN vengono forniti e mappati a igroups per FC e iSCSI.

Uno spazio dei nomi NVMe è una quantità di memoria non volatile che può essere formattata in blocchi logici. Gli spazi dei nomi sono l'equivalente dei LUN per i protocolli FC e iSCSI e un sottosistema NVMe è analogo a un igroup. Un sottosistema NVMe può essere associato agli iniziatori in modo che gli iniziatori associati possano accedere agli spazi dei nomi all'interno del sottosistema.

[NOTE]
====
Sebbene funzioni analoghe, gli spazi dei nomi NVMe non supportano tutte le funzionalità supportate dalle LUN.

====
A partire da ONTAP 9.5, è necessaria una licenza per supportare l'accesso ai dati rivolti all'host con NVMe. Se NVMe è attivato in ONTAP 9.4, viene concesso un periodo di valutazione di 90 giorni per l'acquisizione della licenza dopo l'aggiornamento a ONTAP 9.5. Se lo hai fatto link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP uno"], Sono incluse le licenze NVMe. È possibile attivare la licenza utilizzando il seguente comando:

`system license add -license-code _NVMe_license_key_`

.Informazioni correlate
http://www.netapp.com/us/media/tr-4684.pdf["Report tecnico di NetApp 4684: Implementazione e configurazione di SAN moderne con NVMe/FC"]
