---
permalink: san-admin/supported-port-config-x1143a-r6-adapter-concept.html 
sidebar: sidebar 
keywords: supported, port, configurations, x1143a-r6 adapters 
summary: 'La modalità di destinazione FC è la configurazione predefinita per le porte dell"adattatore X1143A-R6. Tuttavia, le porte di questo adattatore possono essere configurate come porte Ethernet da 10 GB e FCoE o come porte FC da 16 GB.' 
---
= Configurazioni delle porte supportate per gli adattatori X1143A-R6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La modalità di destinazione FC è la configurazione predefinita per le porte dell'adattatore X1143A-R6. Tuttavia, le porte di questo adattatore possono essere configurate come porte Ethernet da 10 GB e FCoE o come porte FC da 16 GB.

Se configurati per Ethernet e FCoE, gli adattatori X1143A-R6 supportano il traffico di destinazione simultaneo di NIC e FCoE sulla stessa porta 10-GBE. Se configurata per FC, ciascuna coppia di due porte che condivide lo stesso ASIC può essere configurata singolarmente per la destinazione FC o la modalità iniziatore FC. Ciò significa che un singolo adattatore X1143A-R6 può supportare la modalità di destinazione FC su una coppia a due porte e la modalità iniziatore FC su un'altra coppia a due porte.

.Informazioni correlate
https://hwu.netapp.com["NetApp Hardware Universe"^]

link:../san-config/index.html["Configurazione SAN"]
