---
permalink: san-admin/transition-config-concept.html 
sidebar: sidebar 
keywords: transitioning, san, configurations, capabilities, restrictions, transitioned, luns 
summary: 'In un ambiente SAN, è necessario un"interruzione del servizio durante la transizione di un volume 7-Mode a ONTAP. Per completare la transizione, è necessario spegnere gli host. Dopo la transizione, è necessario aggiornare le configurazioni host prima di poter iniziare a fornire i dati in ONTAP.' 
---
= Funzionalità e limitazioni delle LUN in transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In un ambiente SAN, è necessario un'interruzione del servizio durante la transizione di un volume 7-Mode a ONTAP. Per completare la transizione, è necessario spegnere gli host. Dopo la transizione, è necessario aggiornare le configurazioni host prima di poter iniziare a fornire i dati in ONTAP

È necessario pianificare una finestra di manutenzione durante la quale è possibile arrestare gli host e completare la transizione.

I LUN che sono stati trasferiti da Data ONTAP in 7-Mode a ONTAP presentano alcune funzionalità e restrizioni che influiscono sul modo in cui è possibile gestire i LUN.

Con i LUN in transizione è possibile effettuare le seguenti operazioni:

* Visualizzare il LUN utilizzando `lun show` comando
* Visualizzare l'inventario delle LUN in transizione dal volume 7-Mode utilizzando `transition 7-mode show` comando
* Ripristina un volume da uno snapshot 7-Mode
+
Il ripristino del volume trasferisce tutti i LUN acquisiti nello snapshot

* Ripristina una singola LUN da uno snapshot 7-Mode utilizzando il `snapshot restore-file` comando
* Crea un clone di una LUN in una snapshot 7-Mode
* Ripristina una serie di blocchi da una LUN acquisita in una snapshot 7-Mode
* Creare un FlexClone del volume utilizzando un'istantanea 7-Mode


Non è possibile eseguire le seguenti operazioni con LUN in transizione:

* Accesso ai cloni delle LUN con backup degli snapshot acquisiti nel volume


.Informazioni correlate
link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Transizione basata sulla copia"]
