---
permalink: san-admin/troubleshoot-iscsi-luns-not-visible-reference.html 
sidebar: sidebar 
keywords: troubleshoot, iscsi luns, not visible, host 
summary: 'I LUN iSCSI vengono visualizzati come dischi locali per l"host. Se i LUN del sistema di storage non sono disponibili come dischi sull"host, verificare le impostazioni di configurazione.' 
---
= Eseguire il troubleshooting dei LUN iSCSI non visibili sull'host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I LUN iSCSI vengono visualizzati come dischi locali per l'host. Se i LUN del sistema di storage non sono disponibili come dischi sull'host, verificare le impostazioni di configurazione.

[cols="1, 3"]
|===
| Impostazione di configurazione | Cosa fare 


 a| 
Cablaggio
 a| 
Verificare che i cavi tra l'host e il sistema di storage siano collegati correttamente.



 a| 
Connettività di rete
 a| 
Verificare che vi sia una connettività TCP/IP tra l'host e il sistema di storage.

* Dalla riga di comando del sistema storage, eseguire il ping delle interfacce host utilizzate per iSCSI:
+
`ping –node _node_name_ -destination _host_ip_address_for_iSCSI_`

* Dalla riga di comando dell'host, eseguire il ping delle interfacce del sistema di storage utilizzate per iSCSI:
+
`ping –node _node_name_ -destination _host_ip_address_for_iSCSI_`





 a| 
Requisiti di sistema
 a| 
Verificare che i componenti della configurazione siano qualificati. Inoltre, verificare di disporre del livello corretto del service pack del sistema operativo host (OS), della versione initiator, della versione di ONTAP e di altri requisiti di sistema. La matrice di interoperabilità contiene i requisiti di sistema più aggiornati.



 a| 
Frame jumbo
 a| 
Se si utilizzano frame jumbo nella configurazione, verificare che i frame jumbo siano attivati su tutti i dispositivi nel percorso di rete: La NIC Ethernet host, il sistema di storage e gli switch.



 a| 
Stato del servizio iSCSI
 a| 
Verificare che il servizio iSCSI sia concesso in licenza e avviato sul sistema storage.



 a| 
Accesso initiator
 a| 
Verificare che l'iniziatore sia connesso al sistema di storage. Se il `iscsi initiator show` l'output del comando indica che non sono stati registrati iniziatori. controllare la configurazione dell'iniziatore sull'host. Verificare inoltre che il sistema di storage sia configurato come destinazione dell'iniziatore.



 a| 
Nomi dei nodi iSCSI (IQN)
 a| 
Verificare di utilizzare i nomi dei nodi iniziatori corretti nella configurazione igroup. Sull'host, è possibile utilizzare i comandi e gli strumenti di initiator per visualizzare il nome del nodo di initiator. I nomi dei nodi iniziatori configurati nell'igroup e sull'host devono corrispondere.



 a| 
Mappature LUN
 a| 
Verificare che i LUN siano mappati a un igroup. Nella console del sistema di storage, è possibile utilizzare uno dei seguenti comandi:

* `lun mapping show` Visualizza tutti i LUN e gli igroups a cui sono associati.
* `lun mapping show -igroup` Visualizza i LUN mappati a un igroup specifico.




 a| 
Le LIF iSCSI sono abilitate
 a| 
Verificare che le interfacce logiche iSCSI siano attivate.

|===
.Informazioni correlate
https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^]
