---
permalink: san-admin/view-adapter-settings-capabilities-task.html 
sidebar: sidebar 
keywords: view, adapter, settings, display, information, x1143a-r6 
summary: È possibile utilizzare comandi specifici per visualizzare informazioni sugli adattatori FC/UTA. 
---
= Visualizzare le impostazioni dell'adattatore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare comandi specifici per visualizzare informazioni sugli adattatori FC/UTA.



== Adattatore di destinazione FC

.Fase
. Utilizzare `network fcp adapter show` comando per visualizzare le informazioni sull'adattatore: `network fcp adapter show -instance -node node1 -adapter 0a`
+
L'output visualizza le informazioni di configurazione del sistema e le informazioni sull'adattatore per ogni slot utilizzato.

+
Ulteriori informazioni su `network fcp adapter show` nella link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["Riferimento al comando ONTAP"^].





== Unified Target Adapter (UTA) X1143A-R6

.Fasi
. Avviare il controller senza i cavi collegati.
. Eseguire `system hardware unified-connect show` per visualizzare la configurazione delle porte e i moduli.
. Visualizzare le informazioni sulla porta prima di configurare il CNA e le porte.

