---
permalink: smb-config/configure-time-services-task.html 
sidebar: sidebar 
keywords: creating, create, smb, server, active, domain, controller, ensure, cluster, time, match, configure time services 
summary: Prima di creare un server SMB in un controller di dominio attivo, è necessario assicurarsi che il tempo del cluster e quello dei controller di dominio del dominio a cui il server SMB appartiene corrispondano entro cinque minuti. 
---
= Configurare i servizi ONTAP Time per i server SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di creare un server SMB in un controller di dominio attivo, è necessario assicurarsi che il tempo del cluster e quello dei controller di dominio del dominio a cui il server SMB appartiene corrispondano entro cinque minuti.

.A proposito di questa attività
È necessario configurare i servizi NTP del cluster in modo che utilizzino per la sincronizzazione gli stessi server NTP utilizzati dal dominio Active Directory.

A partire da ONTAP 9.5, è possibile configurare il server NTP con autenticazione simmetrica.

.Fasi
. Configurare i servizi di gestione del tempo utilizzando `cluster time-service ntp server create` comando.
+
** Per configurare i servizi temporali senza autenticazione simmetrica, immettere il seguente comando: `cluster time-service ntp server create -server server_ip_address`
** Per configurare i servizi temporali con autenticazione simmetrica, immettere il seguente comando: `cluster time-service ntp server create -server server_ip_address -key-id key_id`
`cluster time-service ntp server create -server 10.10.10.1` `cluster time-service ntp server create -server 10.10.10.2`


. Verificare che i servizi di orario siano impostati correttamente utilizzando `cluster time-service ntp server show` comando.
+
`cluster time-service ntp server show`

+
[listing]
----

Server                         Version
------------------------------ -------
10.10.10.1                     auto
10.10.10.2                     auto
----


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+time-service+ntp["cluster time-service ntp"^]

