---
permalink: smb-config/create-local-groups-task.html 
sidebar: sidebar 
keywords: create, local, group, authorize, authorizing, access, data, associate, svm, smb, connection, assign, privilege, define, right, capabilities, capability, member, create local groups 
summary: 'È possibile creare gruppi locali che possono essere utilizzati per autorizzare l"accesso ai dati associati alla SVM tramite una connessione SMB. È inoltre possibile assegnare privilegi che definiscono i diritti o le funzionalità di un membro del gruppo.' 
---
= Creare gruppi locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare gruppi locali che possono essere utilizzati per autorizzare l'accesso ai dati associati alla SVM tramite una connessione SMB. È inoltre possibile assegnare privilegi che definiscono i diritti o le funzionalità di un membro del gruppo.

.A proposito di questa attività
La funzionalità del gruppo locale viene attivata per impostazione predefinita quando viene creata la SVM.

Quando si crea un gruppo locale, è necessario specificare un nome per il gruppo e la SVM a cui associare il gruppo. È possibile specificare un nome di gruppo con o senza il nome di dominio locale ed è possibile specificare una descrizione per il gruppo locale. Non è possibile aggiungere un gruppo locale a un altro gruppo locale.

Il `vserver cifs users-and-groups local-group` le pagine man contengono dettagli sui parametri opzionali e sui requisiti di denominazione.

.Fasi
. Creare il gruppo locale: `vserver cifs users-and-groups local-group create -vserver vserver_name -group-name group_name`
+
Potrebbe essere utile il seguente parametro opzionale:

+
** `-description`
+
Una descrizione per il gruppo locale.



. Verificare che il gruppo sia stato creato correttamente: `vserver cifs users-and-groups local-group show -vserver vserver_name`


.Esempio
Nell'esempio seguente viene creato un gruppo locale "`SMB_SERVER01` engineering" associato a SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group create -vserver vs1.example.com -group-name SMB_SERVER01\engineering

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1.example.com
Vserver          Group Name                   Description
---------------- ---------------------------- ----------------------------
vs1.example.com  BUILTIN\Administrators       Built-in Administrators group
vs1.example.com  BUILTIN\Backup Operators     Backup Operators group
vs1.example.com  BUILTIN\Power Users          Restricted administrative privileges
vs1.example.com  BUILTIN\Users                All users
vs1.example.com  SMB_SERVER01\engineering
vs1.example.com  SMB_SERVER01\sales
----
.Al termine
È necessario aggiungere membri al nuovo gruppo.
