---
permalink: smb-config/create-keytab-files-authentication-concept.html 
sidebar: sidebar 
keywords: begin, ontap, support, svm, authentication, active, directory, ad, server, keytab, file, administrator, generate, uniform, resource, identifier, uri, supplied, supply, vserver, cifs, command, kerberos, create keytab files for smb authentication 
summary: 'A partire da ONTAP 9.7, ONTAP supporta l"autenticazione SVM con server Active Directory (ad) utilizzando file keytab. Gli amministratori AD generano un file keytab e lo rendono disponibile agli amministratori ONTAP come URI (Uniform Resource Identifier), che viene fornito quando i comandi cifs vserver richiedono l"autenticazione Kerberos con il dominio ad.' 
---
= Creare file keytab per l'autenticazione SMB di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.7, ONTAP supporta l'autenticazione SVM con server Active Directory (ad) utilizzando file keytab. Gli amministratori DEGLI ANNUNCI generano un file keytab e lo rendono disponibile agli amministratori di ONTAP come URI (Uniform Resource Identifier), che viene fornito quando `vserver cifs` I comandi richiedono l'autenticazione Kerberos con il dominio ad.

Gli amministratori DEGLI ANNUNCI possono creare i file keytab utilizzando Windows Server standard `ktpass` comando. Il comando deve essere eseguito sul dominio primario in cui è richiesta l'autenticazione. Il `ktpass` il comando può essere utilizzato per generare i file keytab solo per gli utenti del dominio primario; le chiavi generate utilizzando gli utenti del dominio trusted non sono supportate.

I file keytab vengono generati per specifici utenti amministratori di ONTAP. Se la password dell'utente amministratore non viene modificata, le chiavi generate per il tipo di crittografia e il dominio specifico non verranno modificate. Pertanto, è necessario un nuovo file keytab ogni volta che viene modificata la password dell'utente amministratore.

Sono supportati i seguenti tipi di crittografia:

* AES256-SHA1
* DES-CBC-MD5
+
[NOTE]
====
ONTAP non supporta il tipo di crittografia DES-CBC-CRC.

====
* RC4-HMAC


AES256 è il tipo di crittografia più elevato e deve essere utilizzato se abilitato sul sistema ONTAP.

I file keytab possono essere generati specificando la password admin o utilizzando una password generata casualmente. Tuttavia, in qualsiasi momento è possibile utilizzare una sola opzione di password, poiché sul server ad è necessaria una chiave privata specifica per l'utente amministratore per decifrare le chiavi all'interno del file keytab. Qualsiasi modifica della chiave privata per un amministratore specifico invaliderà il file keytab.
