---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile utilizzare i comandi CLI di ONTAP 9 per configurare l"accesso del client SMB ai file contenuti in un nuovo volume o qtree in una SVM nuova o esistente.' 
---
= Panoramica della configurazione SMB con la CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i comandi CLI di ONTAP 9 per configurare l'accesso del client SMB ai file contenuti in un nuovo volume o qtree in una SVM nuova o esistente.

[NOTE]
====
_SMB_ (Server message Block) si riferisce ai dialetti moderni del protocollo CIFS (Common Internet file System). L'interfaccia della riga di comando (CLI) di ONTAP e i tool di gestione di OnCommand sono ancora visibili in _CIFS_.

====
Attenersi alle seguenti procedure se si desidera configurare l'accesso SMB a un volume o a un qtree nel modo seguente:

* Si desidera utilizzare SMB versione 2 o successiva.
* Si desidera servire solo client SMB, non client NFS (non una configurazione multiprotocollo).
* Per proteggere il nuovo volume verranno utilizzate le autorizzazioni NTFS.
* Si dispone di privilegi di amministratore del cluster, non di amministratore SVM.
+
Per creare SVM e LIFF sono necessari i privilegi di amministratore del cluster. I privilegi di amministratore di SVM sono sufficienti per altre attività di configurazione SMB.

* Si desidera utilizzare la CLI, non System Manager o uno strumento di scripting automatico.
+
Per utilizzare System Manager per configurare l'accesso multiprotocollo NAS, vedere link:../task_nas_provision_nfs_and_smb.html["Provisioning dello storage NAS per Windows e Linux utilizzando sia NFS che SMB"].

* Si desidera utilizzare le Best practice, non esplorare tutte le opzioni disponibili.
+
Per ulteriori informazioni sui comandi descritti in questa procedura, consultare la link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].



Per ulteriori informazioni sulla gamma di funzionalità del protocollo SMB ONTAP, consultare link:../smb-admin/index.html["Panoramica di riferimento SMB"].



== Altri modi per farlo in ONTAP

|===


| Per eseguire queste attività con... | Fare riferimento a... 


| System Manager riprogettato (disponibile con ONTAP 9.7 e versioni successive) | link:../task_nas_provision_windows_smb.html["Provisioning dello storage NAS per i server Windows utilizzando SMB"] 


| System Manager Classic (disponibile con ONTAP 9.7 e versioni precedenti) | link:https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html["Panoramica della configurazione SMB"^] 
|===