---
permalink: smb-config/map-dns-server-task.html 
sidebar: sidebar 
keywords: site, dns, server, entry, point, smb, name, netbios, alias, ip, address, lif, windows, map the smb server on the dns server 
summary: 'Il server DNS del sito deve avere una voce che punta il nome del server SMB e qualsiasi alias NetBIOS all"indirizzo IP del LIF dei dati, in modo che gli utenti Windows possano mappare un disco al nome del server SMB.' 
---
= Mappare i server SMB ONTAP sul server DNS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il server DNS del sito deve avere una voce che punta il nome del server SMB e qualsiasi alias NetBIOS all'indirizzo IP del LIF dei dati, in modo che gli utenti Windows possano mappare un disco al nome del server SMB.

.Prima di iniziare
È necessario disporre dell'accesso amministrativo al server DNS del sito. Se non si dispone dell'accesso amministrativo, è necessario chiedere all'amministratore DNS di eseguire questa attività.

.A proposito di questa attività
Se si utilizzano alias NetBIOS per il nome del server SMB, si consiglia di creare punti di ingresso del server DNS per ciascun alias.

.Fasi
. Accedere al server DNS.
. Creare voci di ricerca in avanti (A - record di indirizzo) e indietro (PTR - record puntatore) per mappare il nome del server SMB all'indirizzo IP dei dati LIF.
. Se si utilizzano alias NetBIOS, creare una voce di ricerca Alias Canonical name (CNAME resource record) per mappare ciascun alias all'indirizzo IP dei dati LIF del server SMB.


.Risultati
Una volta propagata la mappatura in rete, gli utenti di Windows possono mappare un disco al nome del server SMB o ai relativi alias NetBIOS.
