---
permalink: smb-config/verify-client-access-task.html 
sidebar: sidebar 
keywords: verify, configure, smb, correct, access, writing, write, data, share, server, name, netbios, alias, verify smb client access 
summary: 'Verificare di aver configurato SMB correttamente accedendo e scrivendo i dati nella condivisione. Verificare l"accesso utilizzando il nome del server SMB e gli alias NetBIOS.' 
---
= Verificare l'accesso al client SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verificare di aver configurato SMB correttamente accedendo e scrivendo i dati nella condivisione. Verificare l'accesso utilizzando il nome del server SMB e gli alias NetBIOS.

.Fasi
. Accedere a un client Windows.
. Verificare l'accesso utilizzando il nome del server SMB:
+
.. In Esplora risorse, mappare un disco alla condivisione nel seguente formato: `\⁠\\SMB_Server_Name\Share_Name`
+
Se la mappatura non riesce, è possibile che la mappatura DNS non sia ancora propagata in tutta la rete. È necessario verificare l'accesso utilizzando il nome del server SMB in un secondo momento.

+
Se il server SMB è denominato vs1.example.com e la condivisione è denominata SHARE1, immettere quanto segue: `\⁠\vs0.example.com\SHARE1`

.. Sul disco appena creato, creare un file di prova, quindi eliminare il file.


+
L'accesso in scrittura alla condivisione è stato verificato utilizzando il nome del server SMB.

. Ripetere il passaggio 2 per tutti gli alias NetBIOS.

