---
permalink: smb-config/verify-user-access-task.html 
sidebar: sidebar 
keywords: test, user, configure, access, smb, share, file, contain, verify user access 
summary: È necessario verificare che gli utenti configurati possano accedere alla condivisione SMB e ai file in essa contenuti. 
---
= Verificare l'accesso alla condivisione degli utenti SMB in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario verificare che gli utenti configurati possano accedere alla condivisione SMB e ai file in essa contenuti.

.Fasi
. Su un client Windows, accedere come uno degli utenti che ora ha accesso alla condivisione.
. Dal menu *Strumenti* di Esplora risorse, selezionare *Connetti unità di rete*.
. Completare la casella *Map Network Drive* (Connetti unità di rete):
+
.. Selezionare una lettera *Drive*.
.. Nella casella *Folder* (cartella), digitare il nome della condivisione che verrà fornito agli utenti.
+
Se il nome del server SMB è SMB_SERVER01 e la condivisione è denominata "`SHARE1`", immettere `\\SMB_SERVER01\share1`.

.. Fare clic su *fine*.


+
Il disco selezionato viene montato e pronto con la finestra Esplora risorse che visualizza i file e le cartelle contenuti nella condivisione.

. Creare un file di test, verificare che esista, scriverne del testo e rimuovere il file di test.

