---
permalink: smb-config/verify-enabled-versions-task.html 
sidebar: sidebar 
keywords: ontap, release, smb, version, enable, default, connection, client, domain, controller, controller, verify, support, functionality, environment, verify enabled smb versions, can smb1 be enabled in ontap 9 
summary: In ONTAP 9,0 e versioni successive, SMB 2,0 è attivato per impostazione predefinita.  SMB 1,0 è abilitato per impostazione predefinita in base alla versione di ONTAP in uso 
---
= Verificare le versioni di SMB ONTAP abilitate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La release di ONTAP 9 determina quali versioni SMB sono abilitate per impostazione predefinita per le connessioni con client e controller di dominio. Verificare che il server SMB supporti i client e le funzionalità richieste nell'ambiente.

.A proposito di questa attività
Per le connessioni con client e controller di dominio, è necessario attivare SMB 2.0 e versioni successive, se possibile. Per motivi di sicurezza, è consigliabile evitare di utilizzare SMB 1.0 e disattivarlo se si è verificato che non è richiesto nell'ambiente in uso.

A partire da ONTAP 9.3, viene disattivato per impostazione predefinita sui nuovi SVM.

[NOTE]
====
Se `-smb1-enabled-for-dc-connections` è impostato su `false` mentre `-smb1-enabled` è impostato su `true`, ONTAP nega le connessioni SMB 1.0 come client, ma continua ad accettare connessioni SMB 1.0 in entrata come server.

====
link:../smb-admin/index.html["Gestione delle PMI"] Contiene dettagli sulle versioni e sulle funzionalità SMB supportate.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
. Verificare quali versioni SMB sono abilitate:
+
[source, cli]
----
vserver cifs options show
----
+
È possibile scorrere l'elenco per visualizzare le versioni SMB abilitate per le connessioni client e, se si configura un server SMB in un dominio ad, per le connessioni di dominio ad.

. Attivare o disattivare il protocollo SMB per le connessioni client secondo necessità:
+
** Per attivare una versione SMB:
+
[source, cli]
----
vserver cifs options modify -vserver <vserver_name> -<smb_version> true
----
+
Valori possibili per `smb_version`:

+
*** `-smb1-enabled`
*** `-smb2-enabled`
*** `-smb3-enabled`
*** `-smb31-enabled`
+
Questo comando abilita SMB 3,1 in SVM vs1.example.com:
`cluster1::*> vserver cifs options modify -vserver vs1.example.com -smb31-enabled true`



** Per disattivare una versione SMB:
+
[source, cli]
----
vserver cifs options modify -vserver <vserver_name> -<smb_version> false
----


. Se il server SMB si trova in un dominio Active Directory, attivare o disattivare il protocollo SMB per le connessioni DC come richiesto:
+
** Per attivare una versione SMB:
+
[source, cli]
----
vserver cifs security modify -vserver <vserver_name> -smb2-enabled-for-dc-connections true
----
** Per disattivare una versione SMB:
+
[source, cli]
----
vserver cifs security modify -vserver <vserver_name> -smb2-enabled-for-dc-connections false
----


. Tornare al livello di privilegio admin:
+
[source, cli]
----
set -privilege admin
----

