---
permalink: smb-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: create, smb, volume, qtree, exist, configuration, svm, decision, workflow, decide where to provision new SMB storage capacity 
summary: Prima di creare un nuovo volume o qtree SMB, è necessario decidere se posizionarlo in una SVM nuova o esistente e la quantità di configurazione richiesta da SVM. Questa decisione determina il tuo flusso di lavoro. 
---
= Decidere dove eseguire il provisioning della nuova capacità di storage per PMI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di creare un nuovo volume o qtree SMB, è necessario decidere se posizionarlo in una SVM nuova o esistente e la quantità di configurazione richiesta da SVM. Questa decisione determina il tuo flusso di lavoro.

.Scelte
* Se si desidera eseguire il provisioning di un volume o qtree su una nuova SVM o su una SVM esistente che ha SMB abilitato ma non configurato, completare la procedura descritta in "`Configurazione dell'accesso SMB a una SVM`" e "`aggiunta di capacità di storage a una SVM abilitata per SMB`".
+
xref:configure-access-svm-task.adoc[Configurazione dell'accesso SMB a una SVM]

+
xref:configure-client-access-shared-storage-concept.adoc[Configurazione dell'accesso del client SMB allo storage condiviso]

+
È possibile scegliere di creare una nuova SVM se si verifica una delle seguenti condizioni:

+
** Si sta abilitando SMB su un cluster per la prima volta.
** Esistono SVM in un cluster in cui non si desidera abilitare il supporto SMB.
** Si dispone di una o più SVM abilitate per SMB in un cluster e si desidera una delle seguenti connessioni:
+
*** A una foresta o a un gruppo di lavoro Active Directory diverso.
*** A un server SMB in uno spazio dei nomi isolato (scenario multi-tenancy). È inoltre necessario scegliere questa opzione per eseguire il provisioning dello storage su una SVM esistente con SMB abilitato ma non configurato. Questo potrebbe verificarsi se è stata creata la SVM per l'accesso SAN o se non sono stati attivati protocolli al momento della creazione della SVM.




+
Dopo aver attivato SMB su SVM, procedere al provisioning di un volume o qtree.

* Se si desidera eseguire il provisioning di un volume o qtree su una SVM esistente completamente configurata per l'accesso SMB, completare la procedura descritta in "`aggiunta di capacità di storage a una SVM abilitata per SMB`".
+
xref:configure-client-access-shared-storage-concept.adoc[Configurazione dell'accesso del client SMB allo storage condiviso]


