---
permalink: disks-aggregates/add-local-tier-overview-task.html 
sidebar: sidebar 
keywords: local tier, aggregate, add, create 
summary: 'Per aggiungere un Tier locale (creare un aggregato), si segue un workflow specifico.' 
---
= Aggiunta di un Tier locale (creazione di un aggregato)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aggiungere un Tier locale (creare un aggregato), si segue un workflow specifico.

Si determina il numero di dischi o partizioni di dischi necessari per il Tier locale e si decide quale metodo utilizzare per creare il Tier locale. È possibile aggiungere automaticamente i Tier locali consentendo a ONTAP di assegnare la configurazione oppure specificarla manualmente.

* link:aggregate-creation-workflow-concept.html["Workflow per aggiungere un Tier locale (aggregato)"]
* link:determine-number-disks-partitions-concept.html["Determinare il numero di dischi o partizioni richiesto per un Tier locale (aggregato)"]
* link:decide-aggregate-creation-method-concept.html["Decidere quale metodo di creazione del Tier locale (aggregato) utilizzare"]
* link:create-aggregates-auto-provision-task.html["Aggiungere automaticamente i Tier locali (aggregati)"]
* link:create-aggregates-manual-task.html["Aggiungere manualmente i Tier locali (aggregati)"]

