---
permalink: disks-aggregates/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, manage, aggregates 
summary: Il comando storage aggregate consente di gestire gli aggregati. 
---
= Comandi per la gestione degli aggregati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utilizza `storage aggregate` comando per gestire gli aggregati.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza le dimensioni della cache per tutti gli aggregati di Flash Pool
 a| 
`storage aggregate show -fields hybrid-cache-size-total -hybrid-cache-size-total >0`



 a| 
Visualizza le informazioni e lo stato del disco per un aggregato
 a| 
`storage aggregate show-status`



 a| 
Visualizza dischi spare per nodo
 a| 
`storage aggregate show-spare-disks`



 a| 
Visualizzare gli aggregati root nel cluster
 a| 
`storage aggregate show -has-mroot true`



 a| 
Visualizza le informazioni di base e lo stato degli aggregati
 a| 
`storage aggregate show`



 a| 
Visualizza il tipo di storage utilizzato in un aggregato
 a| 
`storage aggregate show -fields storage-type`



 a| 
Porta online un aggregato
 a| 
`storage aggregate online`



 a| 
Eliminare un aggregato
 a| 
`storage aggregate delete`



 a| 
Mettere un aggregato nello stato limitato
 a| 
`storage aggregate restrict`



 a| 
Rinominare un aggregato
 a| 
`storage aggregate rename`



 a| 
Portare un aggregato offline
 a| 
`storage aggregate offline`



 a| 
Modificare il tipo di RAID per un aggregato
 a| 
`storage aggregate modify -raidtype`

|===
.Informazioni correlate
* link:http://docs.netapp.com/us-en/ontap-cli["Riferimento comandi ONTAP 9"^]

