---
permalink: disks-aggregates/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands, display, space usage, information 
summary: 'Utilizza i comandi dell"aggregato di storage e del volume per verificare l"utilizzo dello spazio negli aggregati e nei volumi e nei relativi snapshot.' 
---
= Comandi per la visualizzazione delle informazioni sull'utilizzo dello spazio
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi utilizzare i `storage aggregate` comandi e `volume` per verificare l'utilizzo dello spazio negli aggregati e nei volumi e nei relativi snapshot.

|===


| Per visualizzare informazioni su... | Utilizzare questo comando... 


 a| 
Aggregati, inclusi i dettagli sulle percentuali di spazio utilizzate e disponibili, le dimensioni della riserva di snapshot e altre informazioni sull'utilizzo dello spazio
 a| 
`storage aggregate show`
`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Modalità di utilizzo dei dischi e dei gruppi RAID in un aggregato e nello stato RAID
 a| 
`storage aggregate show-status`



 a| 
La quantità di spazio su disco che sarebbe stata recuperata se fosse stato eliminato uno snapshot specifico
 a| 
`volume snapshot compute-reclaimable`



 a| 
La quantità di spazio utilizzata da un volume
 a| 
`volume show -fields size,used,available,percent-used`
`volume show-space`



 a| 
La quantità di spazio utilizzata da un volume nell'aggregato contenente
 a| 
`volume show-footprint`

|===
.Informazioni correlate
* link:../concepts/manual-pages.html["Riferimento al comando ONTAP"]

