---
permalink: disks-aggregates/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands, display, space usage, information 
summary: 'Utilizza i comandi dell"aggregato di storage e del volume per verificare l"utilizzo dello spazio nei Tier e nei volumi locali e nei relativi snapshot.' 
---
= Comandi ONTAP per la visualizzazione delle informazioni sull'utilizzo dello spazio
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi utilizzare i `storage aggregate` comandi e `volume` per vedere come viene utilizzato lo spazio nei tuoi Tier e volumi locali e nei loro snapshot.


NOTE: Prima di ONTAP 9,7, System Manager utilizza il termine _aggregate_ per descrivere un _livello locale_. A prescindere dalla versione di ONTAP, la CLI di ONTAP utilizza il termine _aggregate_. Per ulteriori informazioni sui livelli locali, vedere link:../disks-aggregates/index.html["Dischi e Tier locali"].

|===


| Per visualizzare informazioni su... | Utilizzare questo comando... 


 a| 
Livello locale, inclusi i dettagli sulle percentuali di spazio utilizzate e disponibili, le dimensioni della riserva di snapshot e altre informazioni sull'utilizzo dello spazio
 a| 
`storage aggregate show`

`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Modalità di utilizzo dei dischi e dei gruppi RAID in un livello locale e stato RAID
 a| 
`storage aggregate show-status`



 a| 
La quantità di spazio su disco che sarebbe stata recuperata se fosse stato eliminato uno snapshot specifico
 a| 
`volume snapshot compute-reclaimable`



 a| 
La quantità di spazio utilizzata da un volume
 a| 
`volume show -fields size,used,available,percent-used`

`volume show-space`



 a| 
La quantità di spazio utilizzata da un volume nel livello locale contenente
 a| 
`volume show-footprint`

|===
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show.html["presentazione dell'aggregato di storage"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["spazio espositivo aggregato di stoccaggio"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["mostra stato aggregato di archiviazione"^]

