---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: È possibile utilizzare i comandi di storage disk e storage aggregate per gestire i dischi. 
---
= Comandi per la gestione dei dischi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `storage disk` e. `storage aggregate` comandi per gestire i dischi.

|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza un elenco di dischi di riserva, inclusi i dischi partizionati, per proprietario
 a| 
`storage aggregate show-spare-disks`



 a| 
Visualizza il tipo di RAID del disco, l'utilizzo corrente e il gruppo RAID per aggregato
 a| 
`storage aggregate show-status`



 a| 
Visualizzare il tipo di RAID, l'utilizzo corrente, l'aggregato e il gruppo RAID, inclusi i ricambi, per i dischi fisici
 a| 
`storage disk show -raid`



 a| 
Visualizza un elenco di dischi guasti
 a| 
`storage disk show -broken`



 a| 
Visualizzare il nome del disco pre-cluster (nodescope) per un disco
 a| 
`storage disk show -primary-paths` (avanzato)



 a| 
Accendere il LED di un disco o di uno shelf specifico
 a| 
`storage disk set-led`



 a| 
Visualizza il tipo di checksum per un disco specifico
 a| 
`storage disk show -fields checksum-compatibility`



 a| 
Visualizza il tipo di checksum per tutti i dischi spare
 a| 
`storage disk show -fields checksum-compatibility -container-type spare`



 a| 
Visualizzazione delle informazioni sulla connettività e sul posizionamento dei dischi
 a| 
`storage disk show -fields disk,primary-port,secondary-name,secondary-port,shelf,bay`



 a| 
Visualizzare i nomi dei dischi pre-cluster per dischi specifici
 a| 
`storage disk show -disk diskname -fields diskpathnames`



 a| 
Visualizzare l'elenco dei dischi nel centro di manutenzione
 a| 
`storage disk show -maintenance`



 a| 
Mostra la durata dell'unità SSD
 a| 
`storage disk show -ssd-wear`



 a| 
Dispartizione di un disco condiviso
 a| 
`storage disk unpartition` (disponibile a livello diagnostico)



 a| 
Azzerare tutti i dischi non azzerati
 a| 
`storage disk zerospares`



 a| 
Interrompere un processo di sanificazione in corso su uno o più dischi specificati
 a| 
`system node run -node nodename -command disk sanitize`



 a| 
Visualizzare le informazioni sul disco di crittografia dello storage
 a| 
`storage encryption disk show`



 a| 
Recuperare le chiavi di autenticazione da tutti i server di gestione delle chiavi collegati
 a| 
`security key-manager restore`

|===
.Informazioni correlate
* link:http://docs.netapp.com/us-en/ontap-cli["Riferimento comandi ONTAP 9"^]

