---
permalink: disks-aggregates/convert-raid-tec-dp-task.html 
sidebar: sidebar 
keywords: convert, raid-tec, raid-dp, raid policy 
summary: Se riduca le dimensioni del tuo Tier locale e non hai più bisogno di tripla parità, puoi convertire la tua policy RAID da RAID-TEC a RAID-DP e ridurre il numero di dischi necessari per la parità RAID. 
---
= Converti da RAID-TEC a RAID-DP in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se riduca le dimensioni del tuo Tier locale e non hai più bisogno di tripla parità, puoi convertire la tua policy RAID da RAID-TEC a RAID-DP e ridurre il numero di dischi necessari per la parità RAID.


NOTE: Prima di ONTAP 9,7, System Manager utilizza il termine _aggregate_ per descrivere un _livello locale_. A prescindere dalla versione di ONTAP, la CLI di ONTAP utilizza il termine _aggregate_. Per ulteriori informazioni sui livelli locali, vedere link:../disks-aggregates/index.html["Dischi e Tier locali"].

.Prima di iniziare
La dimensione massima del gruppo RAID per RAID-TEC è superiore alla dimensione massima del gruppo RAID per RAID-DP. Se la dimensione massima del gruppo RAID-TEC non rientra nei limiti RAID-DP, non è possibile eseguire la conversione in RAID-DP.

.A proposito di questa attività
Per comprendere le implicazioni della conversione tra i tipi RAID, fare riferimento alla https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameters["parametri"^] per il `storage aggregate modify` comando.

.Fasi
. Verificare che il livello locale sia online e abbia un minimo di sei dischi:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Convertire il Tier locale da RAID-TEC a RAID-DP:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_dp`

. Verificare che la policy RAID del Tier locale sia RAID-DP:
+
`storage aggregate show _aggregate_name_`


