---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: 'Se si desidera una protezione aggiuntiva della tripla parità, è possibile convertire da RAID-DP a RAID-TEC. RAID-TEC è consigliato se le dimensioni dei dischi utilizzati nell"aggregato sono superiori a 4 TIB.' 
---
= Conversione da RAID-DP a RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera una protezione aggiuntiva della tripla parità, è possibile convertire da RAID-DP a RAID-TEC. RAID-TEC è consigliato se le dimensioni dei dischi utilizzati nel Tier locale (aggregato) sono superiori a 4 TIB.

.Prima di iniziare
Il Tier locale (aggregato) da convertire deve avere un minimo di sette dischi.

.A proposito di questa attività
* I Tier locali dei dischi rigidi possono essere convertiti da RAID-DP a RAID-TEC. Sono inclusi i Tier HDD nei Tier locali di Flash Pool.
* Scopri di più su `storage aggregate modify` in link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameter["Riferimento al comando ONTAP"^]


.Fasi
. Verificare che l'aggregato sia online e disponga di almeno sei dischi:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Convertire l'aggregato da RAID-DP a RAID-TEC:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. Verificare che il criterio RAID aggregato sia RAID-TEC:
+
`storage aggregate show _aggregate_name_`


