---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: Se si desidera una protezione aggiuntiva della tripla parità, è possibile convertire da RAID-DP a RAID-TEC. RAID-TEC è consigliato se le dimensioni dei dischi utilizzati nel livello locale sono superiori a 4 TiB. 
---
= Conversione da RAID-DP ONTAP a RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera una protezione aggiuntiva della tripla parità, è possibile convertire da RAID-DP a RAID-TEC. RAID-TEC è consigliato se le dimensioni dei dischi utilizzati nel livello locale sono superiori a 4 TiB.


NOTE: Prima di ONTAP 9,7, System Manager utilizza il termine _aggregate_ per descrivere un _livello locale_. A prescindere dalla versione di ONTAP, la CLI di ONTAP utilizza il termine _aggregate_. Per ulteriori informazioni sui livelli locali, vedere link:../disks-aggregates/index.html["Dischi e Tier locali"].

.Prima di iniziare
Il livello locale da convertire deve avere almeno sette dischi.

.A proposito di questa attività
* I Tier locali dei dischi rigidi possono essere convertiti da RAID-DP a RAID-TEC. Sono inclusi i Tier HDD nei Tier locali di Flash Pool.
* Scopri di più su `storage aggregate modify` in link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameter["Riferimento al comando ONTAP"^]


.Fasi
. Verificare che il livello locale sia online e abbia un minimo di sei dischi:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Convertire il Tier locale da RAID-DP a RAID-TEC:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. Verificare che il criterio RAID del livello locale sia RAID-TEC:
+
`storage aggregate show _aggregate_name_`


