---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: Anche se ONTAP fornisce consigli sulle Best-practice per la creazione automatica di Tier locali, devi determinare se le configurazioni consigliate sono supportate nel tuo ambiente. In caso contrario, è necessario prendere decisioni in merito alla policy RAID e alla configurazione del disco, quindi creare manualmente i Tier locali. 
---
= Decidere quale metodo utilizzare per creare i livelli locali di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anche se ONTAP offre consigli sulle Best-practice per l'aggiunta automatica di Tier locali, devi determinare se le configurazioni consigliate sono supportate nel tuo ambiente. In caso contrario, è necessario prendere decisioni in merito alla policy RAID e alla configurazione del disco, quindi creare manualmente i Tier locali.

Quando viene creato automaticamente un Tier locale, ONTAP analizza i dischi spare disponibili nel cluster e genera un consiglio su come utilizzare i dischi spare per aggiungere Tier locali in base alle Best practice. ONTAP visualizza le configurazioni consigliate. È possibile accettare i consigli o aggiungere manualmente i Tier locali.


NOTE: Prima di ONTAP 9,7, System Manager utilizza il termine _aggregate_ per descrivere un _livello locale_. A prescindere dalla versione di ONTAP, la CLI di ONTAP utilizza il termine _aggregate_. Per ulteriori informazioni sui livelli locali, vedere link:../disks-aggregates/index.html["Dischi e Tier locali"].



== Prima di poter accettare le raccomandazioni ONTAP

In presenza di una delle seguenti condizioni di disco, è necessario affrontarle prima di accettare le raccomandazioni di ONTAP:

* Dischi mancanti
* Fluttuazione nei numeri dei dischi spare
* Dischi non assegnati
* Parti di ricambio non azzerate
* Dischi sottoposti a test di manutenzione




== Quando è necessario utilizzare il metodo manuale

In molti casi, il layout consigliato del Tier locale sarà ottimale per il tuo ambiente. Tuttavia, se l'ambiente include le seguenti configurazioni, è necessario creare il livello locale utilizzando il metodo manuale.


NOTE: A partire da ONTAP 9.11.1, è possibile aggiungere manualmente i Tier locali con Gestore di sistema.

* Tier locali che utilizzano array LUN di terze parti
* Dischi virtuali con Cloud Volumes ONTAP o ONTAP Select
* Sistema MetroCluster
* SyncMirror
* Dischi MSATA
* Tier di Flash Pool
* Al nodo sono collegati diversi tipi o dimensioni di dischi




== Selezionare il metodo per creare livelli locali

Scegliere il metodo da utilizzare:

* link:create-aggregates-auto-provision-task.html["Aggiungere (creare) livelli locali automaticamente"]
* link:create-aggregates-manual-task.html["Aggiungere (creare) i livelli locali manualmente"]


.Informazioni correlate
* https://docs.netapp.com/us-en/ontap-cli["Riferimento al comando ONTAP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-auto-provision.html["provisioning automatico dell'aggregato di archiviazione"^]

