---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: 'Sebbene ONTAP fornisca consigli sulle Best practice per la creazione automatica di Tier (aggregati) locali (con provisioning automatico), è necessario determinare se le configurazioni consigliate sono supportate nel proprio ambiente. In caso contrario, è necessario prendere decisioni in merito alla policy RAID e alla configurazione del disco, quindi creare manualmente i Tier locali.' 
---
= Decidere quale metodo utilizzare per creare Tier locali (aggregati)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sebbene ONTAP fornisca consigli sulle Best practice per l'aggiunta automatica di Tier locali (creazione di aggregati con provisioning automatico), è necessario determinare se le configurazioni consigliate sono supportate nel proprio ambiente. In caso contrario, è necessario prendere decisioni in merito alla policy RAID e alla configurazione del disco, quindi creare manualmente i Tier locali.

Quando viene creato automaticamente un Tier locale, ONTAP analizza i dischi spare disponibili nel cluster e genera un consiglio su come utilizzare i dischi spare per aggiungere Tier locali in base alle Best practice. ONTAP visualizza le configurazioni consigliate. È possibile accettare i consigli o aggiungere manualmente i Tier locali.



== Prima di poter accettare le raccomandazioni ONTAP

In presenza di una delle seguenti condizioni di disco, è necessario affrontarle prima di accettare le raccomandazioni di ONTAP:

* Dischi mancanti
* Fluttuazione nei numeri dei dischi spare
* Dischi non assegnati
* Parti di ricambio non azzerate
* Dischi sottoposti a test di manutenzione


Il `storage aggregate auto-provision` la pagina man contiene ulteriori informazioni su questi requisiti.



== Quando è necessario utilizzare il metodo manuale

In molti casi, il layout consigliato del Tier locale sarà ottimale per il tuo ambiente. Tuttavia, se nel cluster è in esecuzione ONTAP 9.1 o versioni precedenti o se l'ambiente include le seguenti configurazioni, è necessario creare il Tier locale utilizzando il metodo manuale.


NOTE: A partire da ONTAP 9.11.1, è possibile aggiungere manualmente i Tier locali con Gestore di sistema.

* Aggregati che utilizzano LUN di array di terze parti
* Dischi virtuali con Cloud Volumes ONTAP o ONTAP Select
* Sistema MetroCluster
* SyncMirror
* Dischi MSATA
* Tier FlashPool (aggregati)
* Al nodo sono collegati diversi tipi o dimensioni di dischi




== Selezionare il metodo per creare Tier locali (aggregati)

Scegliere il metodo da utilizzare:

* link:create-aggregates-auto-provision-task.html["Aggiungere (creare) livelli locali (aggregati) automaticamente"]
* link:create-aggregates-manual-task.html["Aggiungere (creare) Tier locali (aggregati) manualmente"]


.Informazioni correlate
* link:http://docs.netapp.com/us-en/ontap-cli["Riferimento comandi ONTAP 9"^]

