---
permalink: disks-aggregates/default-raid-policies-aggregates-concept.html 
sidebar: sidebar 
keywords: raid-dp, raid-tec, default raid policies, raid policy, aggregate, local tier 
summary: 'RAID-DP o RAID-TEC è il criterio RAID predefinito per tutti i nuovi Tier locali (aggregati). Il criterio RAID determina la protezione di parità in caso di guasto del disco.' 
---
= Policy RAID predefinite per Tier locali (aggregati)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RAID-DP o RAID-TEC è il criterio RAID predefinito per tutti i nuovi Tier locali (aggregati). Il criterio RAID determina la protezione di parità in caso di guasto del disco.

RAID-DP offre una protezione a doppia parità in caso di guasto di un disco singolo o doppio. RAID-DP è il criterio RAID predefinito per i seguenti tipi di Tier locale (aggregato):

* Tier locali All Flash
* Tier locali di Flash Pool
* Tier locali dei dischi rigidi (HDD) dalle performance elevate


È disponibile una nuova policy RAID denominata RAID-TEC. RAID-TEC è supportato su tutti i tipi di dischi e su tutte le piattaforme, incluso AFF. I Tier locali che contengono dischi più grandi hanno una maggiore possibilità di guasti simultanei dei dischi. RAID-TEC aiuta a mitigare questo rischio fornendo una protezione a tripla parità in modo che i dati possano sopravvivere fino a tre guasti simultanei del disco. RAID-TEC è il criterio RAID predefinito per i Tier locali di capacità dei dischi rigidi con dischi di 6 TB o superiori.

Ogni tipo di policy RAID richiede un numero minimo di dischi:

* RAID-DP: Minimo 5 dischi
* RAID-TEC: Minimo 7 dischi

