---
permalink: disks-aggregates/delete-local-tier-task.html 
sidebar: sidebar 
keywords: delete, local tier, aggregate, remove 
summary: È possibile eliminare un livello locale se non sono presenti volumi nel livello locale. 
---
= Eliminare un livello locale ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare un livello locale se non sono presenti volumi nel livello locale.


NOTE: Prima di ONTAP 9,7, System Manager utilizza il termine _aggregate_ per descrivere un _livello locale_. A prescindere dalla versione di ONTAP, la CLI di ONTAP utilizza il termine _aggregate_. Per ulteriori informazioni sui livelli locali, vedere link:../disks-aggregates/index.html["Dischi e Tier locali"].

Il `storage aggregate delete` comando elimina un livello locale di archiviazione. Il comando non riesce se sono presenti volumi nel Tier locale. Se al livello locale è associato un archivio di oggetti, oltre a eliminare il locale, il comando elimina anche gli oggetti nell'archivio di oggetti. Non vengono apportate modifiche alla configurazione dell'archivio di oggetti come parte di questo comando.

Nell'esempio seguente viene eliminato un livello locale denominato "`aggr1'":

....
> storage aggregate delete -aggregate aggr1
....
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["eliminazione aggregato di archiviazione"^]

