---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control, volume, space usage, aggregate, local tier 
summary: 'Puoi determinare quali volumi FlexVol stanno utilizzando la maggior parte dello spazio in un Tier locale e in particolare quali funzionalità all"interno del volume.' 
---
= Determinare e controllare l'utilizzo dello spazio di un volume in un Tier locale ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi determinare quali volumi FlexVol stanno utilizzando la maggior parte dello spazio in un Tier locale e in particolare quali funzionalità all'interno del volume.

Il `volume show-footprint` comando fornisce informazioni sull'ingombro di un volume o sull'utilizzo dello spazio all'interno del livello locale che lo contiene.


NOTE: Prima di ONTAP 9,7, System Manager utilizza il termine _aggregate_ per descrivere un _livello locale_. A prescindere dalla versione di ONTAP, la CLI di ONTAP utilizza il termine _aggregate_. Per ulteriori informazioni sui livelli locali, vedere link:../disks-aggregates/index.html["Dischi e Tier locali"].

 `volume show-footprint`Il comando visualizza dettagli sull'utilizzo dello spazio di ogni volume in un Tier locale, inclusi i volumi offline. Questo comando colma la distanza tra l'output dei `volume show-space` comandi e. `aggregate show-space` Tutte le percentuali vengono calcolate come percentuale delle dimensioni del livello locale.

Nell'esempio riportato di seguito viene illustrato il `volume show-footprint` output di comando per un volume chiamato testvol:

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
La seguente tabella illustra alcune delle righe principali dell'output di `volume show-footprint` e cosa si può fare per cercare di ridurre l'utilizzo dello spazio in base a tale funzione:

|===


| Nome riga/funzione | Descrizione/contenuto della riga | Alcuni modi per diminuire 


 a| 
`Volume Data Footprint`
 a| 
La quantità totale di spazio utilizzata nel livello locale contenente dai dati di un volume nel file system attivo e lo spazio utilizzato dagli snapshot del volume. Questa riga non include lo spazio riservato.
 a| 
* Eliminazione dei dati dal volume.
* Eliminazione delle istantanee dal volume.




 a| 
`Volume Guarantee`
 a| 
La quantità di spazio riservata dal volume nel Tier locale per le scritture future. La quantità di spazio riservato dipende dal tipo di garanzia del volume.
 a| 
Modifica del tipo di garanzia per il volume in `none`.



 a| 
`Flexible Volume Metadata`
 a| 
La quantità totale di spazio utilizzata nel livello locale dai file di metadati del volume.
 a| 
Nessun metodo diretto di controllo.



 a| 
`Delayed Frees`
 a| 
Blocchi utilizzati da ONTAP per le performance e che non possono essere immediatamente liberati. Per le destinazioni SnapMirror, questa riga ha un valore di `0` e non vengono visualizzati.
 a| 
Nessun metodo diretto di controllo.



 a| 
`File Operation Metadata`
 a| 
La quantità totale di spazio riservato ai metadati delle operazioni del file.
 a| 
Nessun metodo diretto di controllo.



 a| 
`Total Footprint`
 a| 
La quantità totale di spazio utilizzata dal volume nel Tier locale. È la somma di tutte le righe.
 a| 
Uno dei metodi utilizzati per ridurre lo spazio utilizzato da un volume.

|===
.Informazioni correlate
https://www.netapp.com/pdf.html?item=/media/19670-tr-3483.pdf["Report tecnico di NetApp 3483: Thin provisioning in un ambiente NetApp SAN o IP SAN Enterprise"^]
