---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 'È possibile visualizzare la quantità di spazio utilizzata da tutti i volumi in uno o più Tier locali (aggregati) in modo da poter intraprendere azioni per liberare più spazio.' 
---
= Determinare l'utilizzo dello spazio in un Tier locale (aggregato)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare la quantità di spazio utilizzata da tutti i volumi in uno o più Tier locali (aggregati) in modo da poter intraprendere azioni per liberare più spazio.

WAFL riserva il 10% dello spazio totale su disco per le performance e i metadati a livello aggregato. Lo spazio utilizzato per mantenere i volumi nell'aggregato esce dalla WAFL Reserve e non può essere modificato.


NOTE: A partire da ONTAP 9.12.1 e versioni successive, la riserva WAFL per gli aggregati superiori a 30TB si riduce dal 10% al 5% per le piattaforme AFF e FAS500f.  A partire dal sistema ONTAP 9.14.1, questa stessa riduzione si applica agli aggregati su tutte le piattaforme FAS, producendo il 5% di spazio utilizzabile in più negli aggregati.

È possibile visualizzare l'utilizzo dello spazio da parte di tutti i volumi in uno o più aggregati con `aggregate show-space` comando. In questo modo, è possibile individuare i volumi che consumano più spazio nei relativi aggregati di contenimento, in modo da poter intraprendere azioni per liberare più spazio.

Lo spazio utilizzato in un aggregato è direttamente influenzato dallo spazio utilizzato nei volumi FlexVol in esso contenuti. Le misure adottate per aumentare lo spazio in un volume influiscono anche sullo spazio nell'aggregato.

Le seguenti righe sono incluse in `aggregate show-space` output del comando:

* *Volume Footprint*
+
Il totale di tutte le impronte di volume all'interno dell'aggregato. Include tutto lo spazio utilizzato o riservato da tutti i dati e i metadati di tutti i volumi nell'aggregato contenente.

* *Metadati aggregati*
+
I metadati totali del file system richiesti dall'aggregato, come ad esempio bitmap di allocazione e file inode.

* *Snapshot Reserve*
+
La quantità di spazio riservato per le copie Snapshot aggregate, in base alle dimensioni del volume. Viene considerato spazio utilizzato e non è disponibile per il volume o l'aggregazione di dati o metadati.

* *Snapshot Reserve inutilizzabile*
+
La quantità di spazio allocato originariamente per la riserva Snapshot aggregata che non è disponibile per le copie Snapshot aggregate perché viene utilizzata dai volumi associati all'aggregato. Può verificarsi solo per gli aggregati con una riserva Snapshot aggregata diversa da zero.

* *Totale utilizzato*
+
La somma di tutto lo spazio utilizzato o riservato nell'aggregato in base a volumi, metadati o copie Snapshot.

* *Totale fisico utilizzato*
+
La quantità di spazio utilizzata per i dati ora (anziché essere riservata per uso futuro). Include lo spazio utilizzato dalle copie Snapshot aggregate.



Nell'esempio riportato di seguito viene illustrato il `aggregate show-space` Output di comando per un aggregato la cui riserva Snapshot è del 5%. Se la riserva Snapshot era 0, la riga non veniva visualizzata.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.Informazioni correlate
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Articolo della Knowledge base: Utilizzo dello spazio"]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Liberate fino al 5% della vostra capacità di storage eseguendo l'upgrade a ONTAP 9.12.1"]

