---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: Puoi visualizzare la quantità di spazio utilizzata da tutti i volumi in uno o più Tier locali in modo da poter intraprendere azioni per liberare più spazio. 
---
= Determinare l'utilizzo dello spazio in un livello locale ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi visualizzare la quantità di spazio utilizzata da tutti i volumi in uno o più Tier locali in modo da poter intraprendere azioni per liberare più spazio.


NOTE: Prima di ONTAP 9,7, System Manager utilizza il termine _aggregate_ per descrivere un _livello locale_. A prescindere dalla versione di ONTAP, la CLI di ONTAP utilizza il termine _aggregate_. Per ulteriori informazioni sui livelli locali, vedere link:../disks-aggregates/index.html["Dischi e Tier locali"].

WAFL riserva una percentuale dello spazio su disco totale per performance e metadati a livello di Tier locale. Lo spazio utilizzato per mantenere i volumi nel livello locale esce dalla riserva WAFL e non può essere modificato.

Nei Tier locali di dimensioni inferiori a 30 TB, WAFL riserva il 10% dello spazio su disco totale per prestazioni e metadati a livello di Tier locale.

A partire dall'ONTAP 9.12.1, nei Tier locali di almeno 30 TB, la quantità di spazio su disco riservato per i metadati e le prestazioni a livello di Tier locale è ridotta, con un conseguente 5% di spazio utilizzabile in più nei Tier locali. La disponibilità di questi risparmi di spazio varia in base alla piattaforma e alla versione di ONTAP.

[cols="30,30,40"]
|===
| Spazio su disco riservato da ONTAP nei Tier locali 30 TB o superiori | Si applica alle piattaforme | Nelle versioni ONTAP 


| 5% | Tutte le piattaforme AFF e FAS | ONTAP 9.14.1 e versioni successive 


| 5% | Piattaforme AFF e piattaforme FAS500f | ONTAP 9.12.1 e versioni successive 


| 10% | Tutte le piattaforme | ONTAP 9.11.1 e versioni successive 
|===
Con il comando puoi visualizzare l'utilizzo dello spazio per tutti i volumi in uno o più Tier locali `aggregate show-space`. In questo modo è possibile individuare i volumi che consumano maggiormente spazio nei Tier locali contenenti, in modo da intraprendere azioni per liberare più spazio.

Lo spazio utilizzato in un livello locale è direttamente influenzato dallo spazio utilizzato nei volumi FlexVol in esso contenuti. Le misure adottate per aumentare lo spazio in un volume influiscono anche sullo spazio nel livello locale.


NOTE: A partire da ONTAP 9.15.1, sono disponibili due nuovi contatori di metadati. Oltre alle modifiche apportate a diversi contatori esistenti, è possibile ottenere una visualizzazione più chiara della quantità di dati utente allocati. Per ulteriori informazioni, vedere link:../volumes/determine-space-usage-volume-aggregate-concept.html["Determina l'utilizzo dello spazio in un volume o Tier locale"] .

Le seguenti righe sono incluse in `aggregate show-space` output del comando:

* *Volume Footprint*
+
Il totale di tutti gli ingombri del volume all'interno del livello locale. Include tutto lo spazio utilizzato o riservato da tutti i dati e i metadati di tutti i volumi nel Tier locale contenente.

* *Metadati aggregati*
+
I metadati totali del file system richiesti dal livello locale, come bitmap di allocazione e file inode.

* *Snapshot Reserve*
+
La quantità di spazio riservata agli snapshot del Tier locale, in base alle dimensioni del volume. Viene considerato spazio utilizzato e non è disponibile per dati o metadati relativi a volumi o Tier locali.

* *Snapshot Reserve inutilizzabile*
+
La quantità di spazio allocato originariamente per la riserva di snapshot del Tier locale che non è disponibile per gli snapshot del Tier locale perché viene utilizzata dai volumi associati al Tier locale. Può verificarsi solo per i Tier locali con una riserva di snapshot di Tier locale diversa da zero.

* *Totale utilizzato*
+
La somma di tutto lo spazio utilizzato o riservato nel Tier locale da volumi, metadati o snapshot.

* *Totale fisico utilizzato*
+
La quantità di spazio utilizzata per i dati ora (anziché essere riservata per uso futuro). Include lo spazio utilizzato dalle snapshot del Tier locale.



Nell'esempio seguente viene mostrato l' `aggregate show-space`output del comando per un livello locale la cui riserva di snapshot è 5%. Se la riserva istantanea era 0, la riga non viene visualizzata.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.Informazioni correlate
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Articolo della Knowledge base: Utilizzo dello spazio"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Liberate fino al 5% della vostra capacità di storage eseguendo l'upgrade a ONTAP 9.12.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["spazio espositivo aggregato di stoccaggio"^]

