---
permalink: disks-aggregates/flash-pool-aggregate-caching-policies-concept.html 
sidebar: sidebar 
keywords: cache, flash pool, policy, local tier, aggregate 
summary: 'Le policy di caching vengono applicate ai volumi che risiedono nei Tier locali di Flash Pool (aggregati). Prima di modificarle, è necessario comprendere il funzionamento delle policy di caching.' 
---
= Policy di caching del Tier locale (aggregato) di Flash Pool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le policy di caching per i volumi in un Tier locale (aggregato) di Flash Pool consentono di implementare la Flash come cache dalle performance elevate per il set di dati di lavoro, utilizzando al contempo HDD a basso costo per i dati ad accesso meno frequente. Se si fornisce la cache a due o più Tier locali di Flash Pool, è necessario utilizzare la partizione SSD di Flash Pool per condividere gli SSD tra i Tier locali di Flash Pool.

I criteri di caching vengono applicati ai volumi che risiedono nei Tier locali di Flash Pool. Prima di modificarle, è necessario comprendere il funzionamento delle policy di caching.

Nella maggior parte dei casi, il criterio di caching predefinito "`auto`" è il miglior criterio di caching da utilizzare. La policy di caching deve essere modificata solo se una policy diversa offre performance migliori per il carico di lavoro. La configurazione di una policy di caching errata può degradare notevolmente le performance dei volumi; il degrado delle performance potrebbe aumentare gradualmente nel tempo.

Le policy di caching combinano una policy di caching in lettura e una policy di caching in scrittura. Il nome del criterio concatena i nomi del criterio di caching in lettura e del criterio di caching in scrittura, separati da un trattino. Se non è presente un trattino nel nome del criterio, il criterio di caching in scrittura è "`none`", ad eccezione del criterio "`auto`".

Le policy di caching in lettura ottimizzano le performance di lettura future inserendo una copia dei dati nella cache oltre ai dati memorizzati sugli HDD. Per le policy di caching in lettura che inseriscono i dati nella cache per le operazioni di scrittura, la cache funziona come una cache _write-through_.

I dati inseriti nella cache utilizzando il criterio di caching in scrittura esistono solo nella cache; non è presente alcuna copia negli HDD. La cache di Flash Pool è protetta da RAID. L'attivazione del caching in scrittura rende immediatamente disponibili i dati delle operazioni di scrittura per le letture dalla cache, mentre rinviando la scrittura dei dati sugli HDD fino a quando non esaurisce la cache.

Se si sposta un volume da un livello locale di Flash Pool a un livello locale a livello singolo, il criterio di caching viene perso; se successivamente lo si sposta di nuovo su un livello locale di Flash Pool, viene assegnato il criterio di caching predefinito "`auto`". Se si sposta un volume tra due livelli locali di Flash Pool, il criterio di caching viene mantenuto.



== Modificare un criterio di caching

È possibile utilizzare la CLI per modificare il criterio di caching per un volume che risiede su un livello locale di Flash Pool utilizzando `-caching-policy` con il `volume create` comando.

Quando si crea un volume su un Tier locale di Flash Pool, per impostazione predefinita, al volume viene assegnato il criterio di caching "`auto`".
