---
permalink: disks-aggregates/modify-caching-policies-flash-pool-aggregates-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: È necessario modificare il criterio di caching di un volume solo se si prevede che un diverso criterio di caching fornisca prestazioni migliori. Puoi modificare la policy di caching di un volume su un Tier locale di Flash Pool. 
---
= Modifica delle policy di caching dei Tier locali Flash Pool di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario modificare il criterio di caching di un volume solo se si prevede che un diverso criterio di caching fornisca prestazioni migliori. Puoi modificare la policy di caching di un volume su un Tier locale di Flash Pool.

.Prima di iniziare
È necessario determinare se si desidera modificare il criterio di caching.

.A proposito di questa attività
Nella maggior parte dei casi, il criterio di memorizzazione nella cache predefinito di `auto` è il miglior criterio di memorizzazione nella cache che è possibile utilizzare. La policy di caching deve essere modificata solo se una policy diversa offre performance migliori per il carico di lavoro. La configurazione di una policy di caching errata può degradare notevolmente le performance dei volumi; il degrado delle performance potrebbe aumentare gradualmente nel tempo. Prestare attenzione quando si modificano i criteri di caching. Se si verificano problemi di prestazioni con un volume per il quale il criterio di memorizzazione nella cache è stato modificato, è necessario riportare il criterio di memorizzazione nella cache a `auto`.

.Fase
. Utilizzare la CLI per modificare il criterio di caching del volume:
+
`volume modify -volume _volume_name_ -caching-policy _policy_name_`



.Esempio
Nell'esempio seguente viene modificato il criterio di memorizzazione nella cache di un volume denominato `vol2` nel criterio `none`:

`volume modify -volume vol2 -caching-policy none`
