---
permalink: disks-aggregates/raid-protection-levels-disks-concept.html 
sidebar: sidebar 
keywords: raid, protection, level, spare, disk, failure, parity, local tier, aggregate 
summary: ONTAP supporta tre livelli di protezione RAID per i Tier locali. Il livello di protezione RAID determina il numero di dischi di parità disponibili per il ripristino dei dati in caso di guasti al disco. 
---
= Livelli di protezione RAID ONTAP per i dischi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporta tre livelli di protezione RAID per i Tier locali. Il livello di protezione RAID determina il numero di dischi di parità disponibili per il ripristino dei dati in caso di guasti al disco.

Con la protezione RAID, se si verifica un guasto al disco dati in un gruppo RAID, ONTAP può sostituire il disco guasto con un disco spare e utilizzare i dati di parità per ricostruire i dati del disco guasto.

* *RAID4*
+
Con la protezione RAID4, ONTAP può utilizzare un disco spare per sostituire e ricostruire i dati da un disco guasto all'interno del gruppo RAID.

* *RAID-DP*
+
Con la protezione RAID-DP, ONTAP può utilizzare fino a due dischi di riserva per sostituire e ricostruire i dati da un massimo di due dischi guasti contemporaneamente all'interno del gruppo RAID.

* *RAID-TEC*
+
Con la protezione RAID-TEC, ONTAP può utilizzare fino a tre dischi di riserva per sostituire e ricostruire i dati da un massimo di tre dischi guasti contemporaneamente all'interno del gruppo RAID.


