---
permalink: disks-aggregates/remove-failed-disk-task.html 
sidebar: sidebar 
keywords: remove, fail, disk 
summary: Un disco completamente guasto non è più considerato da ONTAP come un disco utilizzabile ed è possibile scollegarlo immediatamente dallo shelf. Tuttavia, si consiglia di lasciare un disco parzialmente guasto collegato abbastanza a lungo per il completamento del processo di ripristino RAID rapido. 
---
= Rimuovere un disco ONTAP guasto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un disco completamente guasto non viene più conteggiato da ONTAP come disco utilizzabile ed è possibile scollegare immediatamente il disco dallo shelf. Tuttavia, si consiglia di lasciare un disco parzialmente guasto collegato abbastanza a lungo per il completamento del processo di ripristino RAID rapido.

.A proposito di questa attività
Se si rimuove un disco perché si è verificato un errore o perché genera messaggi di errore eccessivi, non utilizzare nuovamente il disco in questo o in qualsiasi altro sistema di storage.

.Fasi
. Utilizzare l'interfaccia CLI per individuare l'ID del disco guasto:
+
`storage disk show -broken`

+
Se il disco non compare nell'elenco dei dischi guasti, potrebbe essersi verificato un errore parziale, con un ripristino RAID rapido in corso. In questo caso, prima di rimuovere il disco, è necessario attendere che il disco sia presente nell'elenco dei dischi guasti (il che significa che il processo di ripristino RAID rapido è completo).

. Determinare la posizione fisica del disco che si desidera rimuovere:
+
`storage disk set-led -action on -disk _disk_name_ 2`

+
Il LED di errore sulla parte anteriore del disco è acceso.

. Rimuovere il disco dallo shelf seguendo le istruzioni riportate nella guida hardware del modello di shelf.

