---
permalink: disks-aggregates/sanitization-interrupted-concept.html 
sidebar: sidebar 
keywords: disks, interrupted disk sanitization, power outage, disk sanitization, power failure 
summary: 'Se la sanificazione del disco viene interrotta da un intervento dell"utente o da un evento imprevisto, ad esempio un"interruzione dell"alimentazione, ONTAP esegue un"azione per riportare i dischi sottoposti a sanitizzazione a uno stato noto, ma è necessario eseguire un"azione prima che il processo di sanitizzazione possa terminare.' 
---
= Cosa succede se la pulizia del disco viene interrotta
:allow-uri-read: 


[role="lead"]
Se la sanificazione del disco viene interrotta da un intervento dell'utente o da un evento imprevisto, ad esempio un'interruzione dell'alimentazione, ONTAP esegue un'azione per riportare i dischi sottoposti a sanitizzazione a uno stato noto, ma è necessario eseguire un'azione prima che il processo di sanitizzazione possa terminare.

La sanificazione dei dischi è un'operazione a esecuzione prolungata. Se il processo di sanificazione viene interrotto da un'interruzione dell'alimentazione, dal panico del sistema o da un intervento manuale, il processo di sanificazione deve essere ripetuto dall'inizio. Il disco non è stato progettato come sanitizzato.

Se la fase di formattazione della disinfezione del disco viene interrotta, ONTAP deve ripristinare i dischi danneggiati dall'interruzione. Dopo un riavvio del sistema e una volta ogni ora, ONTAP verifica la presenza di eventuali dischi di destinazione per la sanificazione che non hanno completato la fase di formattazione della relativa sanificazione. Se vengono rilevati dischi di questo tipo, ONTAP li ripristina. Il metodo di ripristino dipende dal tipo di disco. Una volta ripristinato un disco, è possibile rieseguire il processo di pulizia su tale disco; per gli HDD, è possibile utilizzare `-s` opzione per specificare che la fase di formattazione non viene ripetuta.
