---
permalink: disks-aggregates/sanitization-not-performed-concept.html 
sidebar: sidebar 
keywords: disks, disk sanitization, unsupported disk sanitization, disk sanitization process 
summary: La pulizia dei dischi non è supportata per tutti i tipi di dischi. Inoltre, in alcuni casi non è possibile eseguire la sanificazione del disco. 
---
= Quando non è possibile eseguire la sanificazione del disco
:allow-uri-read: 


[role="lead"]
La pulizia dei dischi non è supportata per tutti i tipi di dischi. Inoltre, in alcuni casi non è possibile eseguire la sanificazione del disco.

* Non è supportato su tutti i codici prodotto SSD.
+
Per informazioni sui codici prodotto SSD che supportano la disinfezione dei dischi, consultare https://hwu.netapp.com/["Hardware Universe"^].

* Non è supportato in modalità Takeover per i sistemi in una coppia ha.
* Non può essere eseguito su dischi che si sono guastati a causa di problemi di leggibilità o di scrivibilità.
* Non esegue la relativa fase di formattazione sui dischi ATA.
* Se si utilizza il modello random, non è possibile eseguirlo su più di 100 dischi alla volta.
* Non è supportato sui LUN degli array.
* Se si disigienizzano entrambi i dischi SES nello stesso shelf ESH contemporaneamente, vengono visualizzati errori sulla console relativi all'accesso a tale shelf e gli avvisi sullo shelf non vengono segnalati per la durata della sanitizzazione.
+
Tuttavia, l'accesso ai dati a tale shelf non viene interrotto.


