---
permalink: disks-aggregates/sanitization-tips-concept.html 
sidebar: sidebar 
keywords: disk, disk sanitization, local tier, aggregate, sensitive data, sanitize 
summary: 'Se si creano o eseguono il backup di Tier locali (aggregati) per contenere dati che potrebbero dover essere sanificati, seguire alcune semplici linee guida ridurrà il tempo necessario per la sanificazione dei dati.' 
---
= Suggerimenti per la creazione e il backup di Tier locali (aggregati) contenenti dati da sanificare
:allow-uri-read: 


[role="lead"]
Se si creano o eseguono il backup di Tier locali (aggregati) per contenere dati che potrebbero dover essere sanificati, seguire alcune semplici linee guida ridurrà il tempo necessario per la sanificazione dei dati.

* Assicurati che i livelli locali contenenti dati sensibili non siano più grandi di quanto sia necessario.
+
Se sono più grandi del necessario, la sanitizzazione richiede più tempo, spazio su disco e larghezza di banda.

* Quando si esegue il backup dei Tier locali contenenti dati sensibili, evitare di eseguirne il backup su Tier locale che contenga anche grandi quantità di dati non sensibili.
+
In questo modo si riducono le risorse necessarie per spostare i dati non sensibili prima di procedere alla pulizia dei dati sensibili.


