---
permalink: disks-aggregates/sanitize-disk-maintenance-mode-task.html 
sidebar: sidebar 
keywords: sanitize, disk, maintenance mode, nodeshell, node shell, sanitization 
summary: A partire da ONTAP 9.6, è possibile eseguire la pulizia del disco in modalità di manutenzione. In questo modo è possibile rimuovere i dati da un disco o da un set di dischi su sistemi dismessi o non funzionanti, in modo che i dati non possano essere recuperati. 
---
= Bonifica di un disco ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sanificazione di un disco consente di rimuovere i dati da un disco o da un set di dischi su sistemi decommissionati o inutilizzabili, in modo che i dati non possano mai essere ripristinati.

Sono disponibili due metodi per la sanificazione dei dischi mediante l'interfaccia CLI:

.Disinfettare un disco con &#8220;modalità di manutenzione&#8221; comandi
[%collapsible]
====
A partire da ONTAP 9.6, è possibile eseguire la pulizia del disco in modalità di manutenzione.

.Prima di iniziare
* I dischi non possono essere dischi con crittografia automatica (SED).
+
È necessario utilizzare `storage encryption disk sanitize` Comando per sanificare un SED.

+
link:../encryption-at-rest/index.html["Crittografia dei dati inattivi"]

+
Ulteriori informazioni su `storage encryption disk sanitize` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["Riferimento al comando ONTAP"^].



.Fasi
. Avviare in modalità di manutenzione.
+
.. Uscire dalla shell corrente immettendo `halt`.
+
Viene visualizzato il prompt DEL CARICATORE.

.. Accedere alla modalità di manutenzione immettendo `boot_ontap maint`.
+
Una volta visualizzate alcune informazioni, viene visualizzato il prompt della modalità di manutenzione.



. Se i dischi da sanificare sono partizionati, dispartizionare ciascun disco:
+

NOTE: Il comando per departizionare un disco è disponibile solo a livello di diagnosi e deve essere eseguito solo sotto la supervisione del supporto NetApp . Si consiglia vivamente di contattare l'assistenza NetApp prima di procedere. Puoi anche fare riferimento alink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["Knowledge Base NetApp : come departizionare un'unità di riserva in ONTAP"^]

+
`disk unpartition <disk_name>`

. Igienizzare i dischi specificati:
+
`disk sanitize start [-p <pattern1>|-r [-p <pattern2>|-r [-p <pattern3>|-r]]] [-c <cycle_count>] <disk_list>`

+

NOTE: Non spegnere il nodo, interrompere la connettività dello storage o rimuovere i dischi di destinazione durante la pulizia. Se la pulizia viene interrotta durante la fase di formattazione, la fase di formattazione deve essere riavviata e completata prima che i dischi siano stati sanitizzati e pronti per essere restituiti al pool di riserva. Se è necessario interrompere il processo di sanificazione, è possibile farlo utilizzando `disk sanitize abort` comando. Se i dischi specificati sono sottoposti alla fase di formattazione della disinfezione, l'interruzione non avviene fino al completamento della fase.

+
 `-p` `<pattern1>` `-p` `<pattern2>` `-p` `<pattern3>` specifica un ciclo da uno a tre modelli di sovrascrittura di byte esadecimali definiti dall'utente che possono essere applicati in successione ai dischi da bonificare. Il modello predefinito è tre passaggi, utilizzando 0x55 per il primo passaggio, 0xaa per il secondo passaggio e 0x3c per il terzo passaggio.

+
`-r` sostituisce una sovrascrittura ripetuta con una sovrascrittura casuale per uno o tutti i passaggi.

+
`-c` `<cycle_count>` specifica il numero di volte in cui vengono applicati i modelli di sovrascrittura specificati. Il valore predefinito è un ciclo. Il valore massimo è di sette cicli.

+
`<disk_list>` Specifica un elenco separato da spazi degli ID dei dischi di riserva da bonificare.

. Se lo si desidera, controllare lo stato del processo di pulizia del disco:
+
`disk sanitize status [<disk_list>]`

. Una volta completato il processo di sanificazione, riportare i dischi allo stato spare per ciascun disco:
+
`disk sanitize release <disk_name>`

. Uscire dalla modalità di manutenzione.


====
.Sanificazione di un disco con i comandi 8220; nodeshel 8221; (tutte le release di ONTAP 9)
[%collapsible]
====
Una volta abilitata la funzione di disk sanitization utilizzando i comandi nodeshell su un nodo, non è possibile disattivarla.

.Prima di iniziare
* I dischi devono essere dischi spare; devono essere di proprietà di un nodo, ma non utilizzati in un Tier locale.
+
Se i dischi sono partizionati, nessuna partizione può essere utilizzata in un livello locale.

* I dischi non possono essere dischi con crittografia automatica (SED).
+
È necessario utilizzare `storage encryption disk sanitize` Comando per sanificare un SED.

+
link:../encryption-at-rest/index.html["Crittografia dei dati inattivi"]

* I dischi non possono far parte di un pool di storage.


.Fasi
. Se i dischi da sanificare sono partizionati, dispartizionare ciascun disco:
+
--

NOTE: Il comando per departizionare un disco è disponibile solo a livello di diagnosi e deve essere eseguito solo sotto la supervisione del supporto NetApp . **Si consiglia vivamente di contattare l'assistenza NetApp prima di procedere.** Puoi anche fare riferimento alink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["Knowledge Base NetApp : come departizionare un'unità di riserva in ONTAP"^] .

--
+
`disk unpartition <disk_name>`

. Immettere il nodeshell per il nodo proprietario dei dischi che si desidera disinfettare:
+
`system node run -node <node_name>`

. Abilitare la sanificazione del disco:
+
`options licensed_feature.disk_sanitization.enable on`

+
Viene richiesto di confermare il comando perché è irreversibile.

. Passa al livello avanzato di privilegi più avanzato:
+
`priv set advanced`

. Igienizzare i dischi specificati:
+
`disk sanitize start [-p <pattern1>|-r [-p <pattern2>|-r [-p <pattern3>|-r]]] [-c <cycle_count>] <disk_list>`

+

NOTE: Non spegnere il nodo, interrompere la connettività dello storage o rimuovere i dischi di destinazione durante la pulizia. Se la pulizia viene interrotta durante la fase di formattazione, la fase di formattazione deve essere riavviata e completata prima che i dischi siano stati sanitizzati e pronti per essere restituiti al pool di riserva. Se è necessario interrompere il processo di sanificazione, è possibile farlo utilizzando il comando disk sanitize abortor. Se i dischi specificati sono sottoposti alla fase di formattazione della disinfezione, l'interruzione non avviene fino al completamento della fase.

+
`-p <pattern1> -p <pattern2> -p <pattern3>` specifica un ciclo da uno a tre modelli di sovrascrittura di byte esadecimali definiti dall'utente che possono essere applicati in successione ai dischi da bonificare. Il modello predefinito è tre passaggi, utilizzando 0x55 per il primo passaggio, 0xaa per il secondo passaggio e 0x3c per il terzo passaggio.

+
`-r` sostituisce una sovrascrittura ripetuta con una sovrascrittura casuale per uno o tutti i passaggi.

+
`-c <cycle_count>` specifica il numero di volte in cui vengono applicati i modelli di sovrascrittura specificati.

+
Il valore predefinito è un ciclo. Il valore massimo è di sette cicli.

+
`<disk_list>` Specifica un elenco separato da spazi degli ID dei dischi di riserva da bonificare.

. Se si desidera controllare lo stato del processo di pulizia del disco:
+
`disk sanitize status [<disk_list>]`

. Una volta completato il processo di sanificazione, riportare i dischi allo stato spare:
+
`disk sanitize release <disk_name>`

. Torna al livello di privilegio admin nodeshell:
+
`priv set admin`

. Tornare all'interfaccia utente di ONTAP:
+
`exit`

. Determinare se tutti i dischi sono stati riportati allo stato spare:
+
`storage aggregate show-spare-disks`

+
[cols="1,2"]
|===


| Se... | Quindi... 


| Tutti i dischi sanitizzati sono elencati come spare | Hai finito. I dischi sono stati sanitizzati e in stato spare. 


| Alcuni dischi sanitizzati non sono elencati come dischi di riserva  a| 
Attenersi alla seguente procedura:

.. Accedere alla modalità avanzata dei privilegi:
+
`set -privilege advanced`

.. Assegnare i dischi sanitizzati non assegnati al nodo appropriato per ciascun disco:
+
`storage disk assign -disk <disk_name> -owner <node_name>`

.. Riportare i dischi allo stato spare per ciascun disco:
+
`storage disk unfail -disk <disk_name> -s -q`

.. Tornare alla modalità amministrativa:
+
`set -privilege admin`



|===
+
Ulteriori informazioni su `storage aggregate show-spare-disks` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-spare-disks.html["Riferimento al comando ONTAP"^].



====
.Risultato
I dischi specificati vengono sanitizzati e designati come hot spare. I numeri di serie dei dischi sanitizzati vengono scritti in `/etc/log/sanitized_disks`.

I registri di sanificazione dei dischi specificati, che mostrano il completamento di ciascun disco, vengono scritti in `/mroot/etc/log/sanitization.log`.

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["presentazione dell'aggregato di storage"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["assegnazione del disco di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-unfail.html["disco di archiviazione non guasto"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["crittografia di archiviazione, sanificazione del disco"^]

