---
permalink: flexgroup/convert-flexvol-volume-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, flexgroup, conversion, flex vol, flex group, transitioned, 
summary: A partire da ONTAP 9.7, è possibile eseguire una conversione in-place di un volume FlexVol in un volume FlexGroup senza richiedere una copia dei dati o ulteriore spazio su disco. 
---
= Converti ONTAP FlexVol Volumes in ONTAP FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.7, è possibile eseguire una conversione in-place di un volume FlexVol in un volume FlexGroup senza richiedere una copia dei dati o ulteriore spazio su disco.

.Prima di iniziare
* I volumi oggetto della transizione possono essere convertiti in volumi FlexGroup a partire da ONTAP 9,8.
* Il volume FlexVol in fase di conversione deve essere online.
* Le operazioni e le configurazioni sul volume FlexVol devono essere compatibili con il processo di conversione.
+
Verificare le seguenti condizioni che possono impedire la conversione:

+
** Un volume FlexVol è stato spostato da 7-Mode utilizzando 7MTT (ONTAP 9,7).
+
I volumi trasferiti possono essere convertiti a partire da ONTAP 9,8.

** Sul volume è abilitato qualcosa che non è ancora supportato dal volume FlexGroup, ad esempio SAN LUN, Windows NFS, SMB1, denominazione/eliminazione automatica degli snapshot, set vmalign, SnapLock con versioni precedenti a ONTAP 9.11.1 (SnapLock è supportato a partire da ONTAP 9.11.1), SLO dello spazio o imposizione/reporting dello spazio logico. Per ulteriori informazioni, vedere link:supported-unsupported-config-concept.html["Configurazioni supportate e non supportate per i volumi FlexGroup"].
** La SVM sul quale si trova il volume FlexVol da convertire è al momento utilizzata per il disaster recovery della SVM.
** Sono presenti i volumi FlexClone di NetApp, mentre il volume FlexVol è il volume principale. Il volume convertito non può essere un volume principale o un clone.
** Il volume è un volume di origine NetApp FlexCache.
** Per ONTAP 9,7 e versioni precedenti, gli snapshot NetApp non devono superare i 255. Per ONTAP 9,8 e versioni successive, sono supportati gli snapshot 1023.
** Le efficienze dello storage sono abilitate. Questi devono essere disattivati e possono essere riattivati dopo la conversione.
** Il volume è l'origine di una relazione di SnapMirror e la destinazione non è stata ancora convertita.
** Il volume fa parte di una relazione di SnapMirror attiva (non inattiva).
** Le quote sono attivate. Questi devono essere disattivati e possono essere riattivati dopo la conversione.
** I nomi dei volumi sono più lunghi di 197 caratteri.
** Il volume è associato a un'applicazione.
+
Applicabile solo a ONTAP 9,7. Il limite viene rimosso in ONTAP 9,8.

** I processi ONTAP sono in esecuzione, come il mirroring, i lavori, wafliron, il backup NDMP, e conversione inode in corso.
** Il volume è un volume root di SVM.
** Il volume è troppo pieno.
+
Se esiste una di queste incompatibilità, viene generato un messaggio di errore se il volume FlexVol e la conversione del volume viene interrotta. È possibile intraprendere azioni correttive e riprovare la conversione.



* Se un volume FlexVol raggiunge attualmente una capacità massima del 80% o superiore, prendi in considerazione la possibilità di copiare i dati in un volume FlexGroup appena creato invece di eseguire una conversione in-place. Anche se i volumi dei membri FlexGroup si ribilanciano naturalmente nel tempo, la conversione di un volume FlexVol a elevata capacità in un volume FlexGroup potrebbe creare performance o bilanciare problemi che non verranno rapidamente ribilanciati tra i volumi dei membri.
+
[NOTE]
====
La conversione di un volume FlexGroup molto grande determina un componente membro del volume FlexGroup molto completo, che può creare problemi di performance. Per ulteriori informazioni, vedere la sezione "quando non creare un volume FlexGroup" nel TR link:https://www.netapp.com/media/12385-tr4571.pdf["FlexGroup Volumes - Guida alle Best practice e all'implementazione"].

====


.Fasi
. Verificare che il volume FlexVol sia online: `volume show -fields vol_name volume-style-extended,state`
+
[listing]
----
cluster-1::> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexvol
----
. Verificare se il volume FlexVol può essere convertito senza problemi:
+
.. Accedere alla modalità privilegi avanzata: `set -privilege advanced`
.. Verificare il processo di conversione: `volume conversion start -vserver vs1 -volume flexvol -check-only true`
+
Correggere tutti gli errori prima di convertire il volume.

+
[NOTE]
====
Non è possibile convertire di nuovo un volume FlexGroup in un volume FlexVol.

====


. Avviare la conversione: `volume conversion start -vserver svm_name -volume vol_name`
+
[listing]
----
cluster-1::*> volume conversion start -vserver vs0 -volume my_volume

Warning: Converting flexible volume "my_volume" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion Snapshot copies cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. Verificare che la conversione sia riuscita: `volume show vol_name -fields volume-style-extended,state`
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexgroup
----


.Risultati
Il volume FlexVol viene convertito in un volume FlexGroup a singolo membro.

.Al termine
È possibile espandere il volume FlexGroup, in base alle esigenze.
