---
permalink: flexgroup/convert-flexvol-concept.html 
sidebar: sidebar 
keywords: consider, convert, flexvol, volume, flexgroup, autobalance, give back, giveback, revert, split, space limit, limit 
summary: Prima di decidere di convertire i volumi FlexVol in volumi FlexGroup, è necessario conoscere le funzionalità e le operazioni supportate. 
---
= Panoramica sulla conversione dei volumi FlexVol in volumi FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera espandere un volume FlexVol oltre il limite di spazio, è possibile convertire il volume FlexVol in un volume FlexGroup. A partire da ONTAP 9.7, è possibile convertire volumi FlexVol o FlexVol standalone in relazione a SnapMirror in volumi FlexGroup.



== Considerazioni per la conversione di volumi FlexVol in volumi FlexGroup

Prima di decidere di convertire i volumi FlexVol in volumi FlexGroup, è necessario conoscere le funzionalità e le operazioni supportate.

A partire da ONTAP 9.13.1, la protezione ransomware autonoma può rimanere attivata durante le conversioni. Se la protezione è attiva, il FlexVol originale diventerà il costituente root di FlexGroup dopo la conversione. Se la protezione non è attiva, durante la conversione viene creato un nuovo FlexGroup e il FlexVol originale assume il ruolo di costituente root.



== Operazioni non supportate durante la conversione

Le seguenti operazioni non sono consentite quando è in corso la conversione del volume:

* Spostamento del volume
* Autobalance dell'aggregato
* Ricollocazione di aggregati
* Takeover e giveback pianificati in una configurazione ad alta disponibilità
* Giveback manuale e automatico in una configurazione ad alta disponibilità
* Upgrade e revert del cluster
* Divisione del volume FlexClone
* Re-host del volume
* Modifica e dimensionamento automatico del volume
* Rinominare il volume
* Allegare un archivio di oggetti a un aggregato
* Switchover negoziato nella configurazione MetroCluster
* Operazioni di SnapMirror
* Ripristino da una copia Snapshot
* Operazioni di quota
* Operazioni di efficienza dello storage


È possibile eseguire queste operazioni sul volume FlexGroup dopo la conversione.



== Configurazioni non supportate con volumi FlexGroup

* Volume offline o limitato
* Volume root SVM
* SAN
* SMB 1.0
* Spazi dei nomi NVMe
* Servizio di copia shadow del volume remoto (VSS)

