---
permalink: flexgroup/create-snapvault-relationship-task.html 
sidebar: sidebar 
keywords: create, snapvault, relationship, flexgroup, volumes 
summary: È possibile configurare una relazione SnapVault e assegnare un criterio SnapVault alla relazione per creare un backup SnapVault. 
---
= Crea relazioni SnapVault per ONTAP FlexGroup Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare una relazione SnapVault e assegnare un criterio SnapVault alla relazione per creare un backup SnapVault.

.Prima di iniziare
È necessario conoscere le considerazioni per la creazione di una relazione SnapVault per i volumi FlexGroup.

.Fasi
. Creare un tipo di volume FlexGroup di destinazione `DP` Con lo stesso numero di componenti del volume FlexGroup di origine:
+
.. Dal cluster di origine, determinare il numero di componenti nel volume FlexGroup di origine: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume src* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       src          -            online     RW         400TB   172.86GB  56%
vss       src__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       src__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       src__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       src__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       src__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       src__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       src__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. Dal cluster di destinazione, creare un tipo di volume FlexGroup di destinazione `DP` Con lo stesso numero di componenti del volume FlexGroup di origine.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dst

Warning: The FlexGroup volume "dst" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. Dal cluster di destinazione, verificare il numero di componenti nel volume FlexGroup di destinazione: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dst* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dst          -            online     RW         400TB   172.86GB  56%
vsd       dst__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dst__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dst__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dst__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dst__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dst__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dst__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. Creare una pianificazione del processo: `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
Per `-month`, `-dayofweek`, e. `-hour`, è possibile specificare `all` per eseguire il processo ogni mese, giorno della settimana e ora, rispettivamente.

+
Nell'esempio seguente viene creata una pianificazione del processo denominata `my_weekly` Il sabato alle 3:00:

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Creare un criterio SnapVault, quindi definire una regola per il criterio SnapVault:
+
.. Creare una policy personalizzata di tipo `vault` Per la relazione SnapVault: `snapmirror policy create -vserver svm_name -policy policy_name -type vault`
.. Definire una regola per il criterio SnapVault che determina quali snapshot vengono trasferite durante le operazioni di inizializzazione e aggiornamento: `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
Se non si crea un criterio personalizzato, è necessario specificare `XDPDefault` Policy per le relazioni SnapVault.

. Creare una relazione SnapVault: `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy XDPDefault`
+
In ONTAP 9.4 e versioni precedenti, se il criterio non è specificato con `snapmirror create` il comando `MirrorAllSnapshots` il criterio viene utilizzato per impostazione predefinita. In ONTAP 9.5, se il criterio non è specificato con `snapmirror create` il comando `MirrorAndVault` il criterio viene utilizzato per impostazione predefinita.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy XDPDefault
----
+
Ulteriori informazioni su `snapmirror create` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["Riferimento al comando ONTAP"^].

. Dal cluster di destinazione, inizializzare la relazione SnapVault eseguendo un trasferimento di riferimento: `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dst
Operation is queued: snapmirror initialize of destination "vsd:dst".
----


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["creazione di snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["inizializzazione di snapmirror"^]

