---
permalink: flexgroup/create-snapmirror-cascade-fanout-reference.html 
sidebar: sidebar 
keywords: consider, create, snapmirror, cascade, fanout, relationship, flexgroup 
summary: Durante la creazione delle relazioni di fanout e cascata di SnapMirror per i volumi FlexGroup, è necessario tenere presenti considerazioni e limitazioni relative al supporto. 
---
= Considerazioni per la creazione di relazioni a cascata e fan-out di SnapMirror per FlexGroups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la creazione delle relazioni di fanout e cascata di SnapMirror per i volumi FlexGroup, è necessario tenere presenti considerazioni e limitazioni relative al supporto.



== Considerazioni per la creazione di relazioni a cascata

* Ciascuna relazione può essere una relazione tra cluster o tra cluster.
* Tutti i tipi di policy asincrone, inclusi async-mirror, mirror-vault e vault, sono supportati per entrambe le relazioni.
* Sono supportati solo i criteri di mirroring asincrono "MirrorAllSnapshot" e non "MirrorLatest".
* Sono supportati aggiornamenti simultanei delle relazioni XDP a cascata.
* Supporta la rimozione Da A a B e da B a C e la risincronizzazione Da A a C o la risincronizzazione da C a A.
* I volumi FlexGroup a e B supportano anche il fanout quando tutti i nodi eseguono ONTAP 9.9.1 o versione successiva.
* Sono supportate le operazioni di ripristino da volumi FlexGroup B o C.
* I trasferimenti sulle relazioni FlexGroup non sono supportati mentre la destinazione è l'origine di una relazione di ripristino.
* La destinazione di un ripristino FlexGroup non può essere la destinazione di altre relazioni FlexGroup.
* Le operazioni di ripristino dei file FlexGroup hanno le stesse restrizioni delle normali operazioni di ripristino di FlexGroup.
* Tutti i nodi del cluster in cui risiedono i volumi FlexGroup B e C devono eseguire ONTAP 9.9.1 o versione successiva.
* Sono supportate tutte le funzionalità di espansione e espansione automatica.
* In una configurazione a cascata, ad esempio Da A a B a C, se Da A a B e da B a C hanno diversi numeri di relazioni SnapMirror costitutive, un'operazione di interruzione dall'origine non è supportata per la relazione SnapMirror da B a C.
* System Manager non supporta le relazioni a cascata in ONTAP 9.9.1.
* Quando si converte un insieme Di relazioni FlexVol Da A a B in C in una relazione FlexGroup, è necessario convertire prima il nodo B in C Hop.
* Tutte le configurazioni a cascata di FlexGroup per le relazioni con i tipi di policy supportati da REST sono supportate anche dalle API REST nelle configurazioni FlexGroup a cascata.
* Come per le relazioni FlexVol, il collegamento a cascata FlexGroup non è supportato da `snapmirror protect` comando.




== Considerazioni per la creazione di relazioni fanout

* Sono supportate due o più relazioni FlexGroup fanout, ad esempio Da A a B, Da A a C, con un massimo di 8 segmenti fanout.
* Ogni relazione può essere intercluster o intracluster.
* Sono supportati aggiornamenti simultanei per le due relazioni.
* Sono supportate tutte le funzionalità di espansione e espansione automatica.
* Se i rami fanout della relazione hanno diversi numeri di relazioni SnapMirror costitutive, un'operazione di interruzione dall'origine non è supportata per le relazioni A-B e A-C.
* Tutti i nodi del cluster in cui risiedono i FlexGroup di origine e di destinazione devono eseguire ONTAP 9.9.1 o versione successiva.
* Tutti i tipi di policy asincrone attualmente supportati per FlexGroup SnapMirror sono supportati nelle relazioni fanout.
* È possibile eseguire operazioni di ripristino da FlexGroups B a C.
* Tutte le configurazioni fanout con i tipi di policy supportati da REST sono supportate anche per le API REST nelle configurazioni fanout FlexGroup.

