---
permalink: flexgroup/create-qtrees-task.html 
sidebar: sidebar 
keywords: create, qtrees, flexgroup, volume, flex group, segment, smb oplock, 
summary: Puoi creare qtree con volumi FlexGroup che consentono di dividere i volumi FlexGroup in segmenti più piccoli e gestiti singolarmente. 
---
= Creare qtree con volumi FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.3, è possibile creare qtree con volumi FlexGroup. I qtree consentono di suddividere i volumi FlexGroup in segmenti più piccoli che è possibile gestire singolarmente.

.A proposito di questa attività
* Se il volume FlexGroup di origine ha qtree in una relazione SnapMirror, il cluster di destinazione deve eseguire ONTAP 9.3 o versione successiva (una versione del software ONTAP che supporta qtree).
* A partire da ONTAP 9.5, le statistiche qtree sono supportate per i volumi FlexGroup.


.Fasi
. Creare un qtree nel volume FlexGroup:
+
[source, cli]
----
volume qtree create -vserver <vserver_name> -volume <volume_name> -qtree <qtree_name>
----
+
È possibile specificare lo stile di protezione, gli oplock SMB, le autorizzazioni UNIX e i criteri di esportazione per qtree.

+
[listing]
----
cluster1::> volume qtree create -vserver vs0 -volume fg1 -qtree qtree1 -security-style mixed
----


.Informazioni correlate
link:../volumes/index.html["Gestione dello storage logico"]
