---
permalink: flexgroup/create-qtrees-task.html 
sidebar: sidebar 
keywords: create, qtrees, flexgroup, volume, flex group, segment, smb oplock, 
summary: A partire da ONTAP 9.3, è possibile creare qtree con volumi FlexGroup. I qtree consentono di suddividere i volumi FlexGroup in segmenti più piccoli che è possibile gestire singolarmente. 
---
= Creare qtree con volumi FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.3, è possibile creare qtree con volumi FlexGroup. I qtree consentono di suddividere i volumi FlexGroup in segmenti più piccoli che è possibile gestire singolarmente.

.A proposito di questa attività
* Se si desidera ripristinare ONTAP 9.2 o versioni precedenti e se sono stati creati uno o più qtree nel volume FlexGroup o modificati gli attributi (stile di protezione e oplock SMB) del qtree predefinito, È necessario eliminare tutti i qtree non predefiniti e disattivare la funzionalità qtree su ciascun volume FlexGroup prima di tornare a ONTAP 9.2 o versione precedente.
+
link:../revert/task_disabling_qtrees_in_flexgroup_volumes_before_reverting.html["Disattivare la funzionalità qtree nei volumi FlexGroup prima di eseguire il ripristino"].

* Se il volume FlexGroup di origine ha qtree in una relazione SnapMirror, il cluster di destinazione deve eseguire ONTAP 9.3 o versione successiva (una versione del software ONTAP che supporta qtree).
* A partire da ONTAP 9.5, le statistiche qtree sono supportate per i volumi FlexGroup.


.Fasi
. Creare un qtree nel volume FlexGroup: `volume qtree create -vserver vserver_name -volume volume_name -qtree qtree name`
+
È possibile specificare lo stile di protezione, gli oplock SMB, le autorizzazioni UNIX e i criteri di esportazione per qtree.

+
[listing]
----
cluster1::> volume qtree create -vserver vs0 -volume fg1 -qtree qtree1 -security-style mixed
----


.Informazioni correlate
link:../volumes/index.html["Gestione dello storage logico"]
