---
permalink: flexgroup/expand-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: expand, flexgroup, volume, snapmirror, relationship, snap mirror, flex group, manual, automatic, automatically, disaster 
summary: A partire da ONTAP 9.3, è possibile espandere il volume FlexGroup di origine e il volume FlexGroup di destinazione che si trovano in una relazione SnapMirror aggiungendo nuovi componenti ai volumi. È possibile espandere i volumi di destinazione manualmente o automaticamente. 
---
= Espandere i volumi ONTAP FlexGroup in una relazione di SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.3, è possibile espandere il volume FlexGroup di origine e il volume FlexGroup di destinazione che si trovano in una relazione SnapMirror aggiungendo nuovi componenti ai volumi. È possibile espandere i volumi di destinazione manualmente o automaticamente.

.A proposito di questa attività
* Dopo l'espansione, il numero di componenti nel volume FlexGroup di origine e nel volume FlexGroup di destinazione di una relazione SnapMirror deve corrispondere.
+
Se il numero di componenti nei volumi non corrisponde, i trasferimenti SnapMirror non vengono effettuati.

* Non eseguire alcuna operazione SnapMirror quando il processo di espansione è in corso.
* Se si verifica un disastro prima del completamento del processo di espansione, è necessario interrompere la relazione SnapMirror e attendere che l'operazione abbia esito positivo.
+
[NOTE]
====
Quando il processo di espansione è in corso solo in caso di disastro, si consiglia di interrompere la relazione di SnapMirror. In caso di disastro, il completamento dell'operazione di interruzione può richiedere del tempo. Prima di eseguire un'operazione di risincronizzazione, attendere il completamento dell'operazione di interruzione. Se l'operazione di interruzione non riesce, riprovare l'operazione di interruzione. Se l'operazione di interruzione non riesce, alcuni dei nuovi componenti potrebbero rimanere nel volume FlexGroup di destinazione dopo l'operazione di interruzione. Si consiglia di eliminare questi elementi costitutivi manualmente prima di procedere ulteriormente.

====

