---
permalink: flexgroup/fabricpool-aggregates-existing-volumes-task.html 
sidebar: sidebar 
keywords: aggregate, fabricpool, flexgroup, volume 
summary: A partire da ONTAP 9.5, FabricPool è supportato per FlexGroup Volumes. Se si desidera utilizzare gli aggregati in FabricPool per i volumi FlexGroup esistenti, è possibile convertire gli aggregati in cui risiede il volume FlexGroup in aggregati in FabricPool o migrare i componenti del volume FlexGroup in aggregati in FabricPool. 
---
= Utilizza gli aggregati in FabricPool per i volumi FlexGroup esistenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.5, FabricPool è supportato per FlexGroup Volumes. Se si desidera utilizzare gli aggregati in FabricPool per i volumi FlexGroup esistenti, è possibile convertire gli aggregati in cui risiede il volume FlexGroup in aggregati in FabricPool o migrare i componenti del volume FlexGroup in aggregati in FabricPool.

.Di cosa hai bisogno
* Il volume FlexGroup deve avere la garanzia di spazio impostata su `none`.
* Se si desidera convertire gli aggregati in cui risiede il volume FlexGroup in aggregati in FabricPool, gli aggregati devono utilizzare tutti i dischi SSD.


.A proposito di questa attività
Se un volume FlexGroup esistente risiede in aggregati non SSD, è necessario migrare i componenti del volume FlexGroup in aggregati in FabricPool.

.Scelte
* Per convertire gli aggregati in cui risiede il volume FlexGroup in aggregati in FabricPool, attenersi alla seguente procedura:
+
.. Impostare il criterio di tiering sul volume FlexGroup esistente: `volume modify -volume flexgroup_name -tiering-policy [auto|snapshot|none|backup]`
+
[listing]
----
cluster-2::> volume modify -volume fg1 -tiering-policy auto
----
.. Identificare gli aggregati su cui risiede il volume FlexGroup: `volume show -volume flexgroup_name -fields aggr-list`
+
[listing]
----
cluster-2::> volume show -volume fg1 -fields aggr-list
vserver volume aggr-list
------- ------ -----------
vs1     fg1    aggr1,aggr3
----
.. Allegare un archivio di oggetti a ciascun aggregato elencato nell'elenco aggregato: `storage aggregate object-store attach -aggregate aggregate name -name object-store-name -allow-flexgroup true`
+
È necessario associare tutti gli aggregati a un archivio di oggetti.



+
[listing]
----
cluster-2::> storage aggregate object-store attach -aggregate aggr1 -object-store-name Amazon01B1
----
* Per migrare i componenti del volume FlexGroup negli aggregati in FabricPool, attenersi alla seguente procedura:
+
.. Impostare il criterio di tiering sul volume FlexGroup esistente: `volume modify -volume flexgroup_name -tiering-policy [auto|snapshot|none|backup]`
+
[listing]
----
cluster-2::> volume modify -volume fg1 -tiering-policy auto
----
.. Spostare ciascun componente del volume FlexGroup in un aggregato in FabricPool nello stesso cluster: `volume move start -volume constituent-volume -destination-aggregate FabricPool_aggregate -allow-mixed-aggr-types true`
+
È necessario spostare tutti i componenti del volume FlexGroup negli aggregati in FabricPool (nel caso in cui i componenti del volume FlexGroup si trovino su tipi di aggregati misti) e assicurarsi che tutti i componenti siano bilanciati tra i nodi del cluster.

+
[listing]
----
cluster-2::> volume move start -volume fg1_001 -destination-aggregate FP_aggr1 -allow-mixed-aggr-types true
----




.Informazioni correlate
link:../disks-aggregates/index.html["Gestione di dischi e aggregati"]
