---
permalink: flexgroup/monitor-space-usage-task.html 
sidebar: sidebar 
keywords: monitor, space, flexgroup, volume, flex group, size, sizing, shrink 
summary: È possibile visualizzare un volume FlexGroup e i relativi componenti e monitorare lo spazio utilizzato dal volume FlexGroup. 
---
= Monitorare l'utilizzo dello spazio di un volume ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare un volume FlexGroup e i relativi componenti e monitorare lo spazio utilizzato dal volume FlexGroup.

.A proposito di questa attività
A partire da ONTAP 9.6, è supportato il dimensionamento elastico. ONTAP aumenta automaticamente un componente di un volume FlexGroup se lo spazio è esaurito, riducendo di una quantità equivalente qualsiasi altro componente del volume FlexGroup che dispone di spazio libero. Il dimensionamento elastico evita gli errori di spazio insufficiente generati a causa dello spazio insufficiente di uno o più volumi costituenti FlexGroup.

[NOTE]
====
A partire da ONTAP 9.9.1, è disponibile anche il reporting e l'imposizione dello spazio logico per i volumi FlexGroup. Per ulteriori informazioni, vedere link:../volumes/logical-space-reporting-enforcement-concept.html["Creazione di report e applicazione dello spazio logico per i volumi"].

====
.Fase
. Visualizzare lo spazio utilizzato dal volume FlexGroup e dai suoi componenti: `volume show -vserver vserver_name -volume-style-extended [flexgroup | flexgroup-constituent]`
+
[listing]
----
cluster-2::> volume show -vserver vs1 -volume-style-extended flexgroup
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs1       fg1          -            online     RW        500GB    207.5GB   56%
----
+
[listing]
----
ccluster-2::> volume show -vserver vs1 -volume-style-extended flexgroup-constituent
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs1       fg1__0001    aggr3        online     RW      31.25GB    12.97GB   56%
vs1       fg1__0002    aggr1        online     RW      31.25GB    12.98GB   56%
vs1       fg1__0003    aggr1        online     RW      31.25GB    13.00GB   56%
vs1       fg1__0004    aggr3        online     RW      31.25GB    12.88GB   56%
vs1       fg1__0005    aggr1        online     RW      31.25GB    13.00GB   56%
vs1       fg1__0006    aggr3        online     RW      31.25GB    12.97GB   56%
vs1       fg1__0007    aggr1        online     RW      31.25GB    13.01GB   56%
vs1       fg1__0008    aggr1        online     RW      31.25GB    13.01GB   56%
vs1       fg1__0009    aggr3        online     RW      31.25GB    12.88GB   56%
vs1       fg1__0010    aggr1        online     RW      31.25GB    13.01GB   56%
vs1       fg1__0011    aggr3        online     RW      31.25GB    12.97GB   56%
vs1       fg1__0012    aggr1        online     RW      31.25GB    13.01GB   56%
vs1       fg1__0013    aggr3        online     RW      31.25GB    12.95GB   56%
vs1       fg1__0014    aggr3        online     RW      31.25GB    12.97GB   56%
vs1       fg1__0015    aggr3        online     RW      31.25GB    12.88GB   56%
vs1       fg1__0016    aggr1        online     RW      31.25GB    13.01GB   56%
16 entries were displayed.
----
+
È possibile utilizzare lo spazio disponibile e lo spazio percentuale utilizzati per monitorare l'utilizzo dello spazio del volume FlexGroup.


