---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: Quando crei un volume FlexGroup, puoi scegliere di fare in modo che ONTAP esegua il provisioning del volume FlexGroup selezionando automaticamente gli aggregati. Gli aggregati vengono selezionati in base alle Best practice per ottenere performance ottimali. 
---
= Esegui automaticamente il provisioning di un volume ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando crei un volume FlexGroup, puoi scegliere di fare in modo che ONTAP esegua il provisioning automatico del volume FlexGroup selezionando gli aggregati. La selezione degli aggregati viene effettuata in base alle Best practice, che consentono di ottenere capacità e performance ottimali.

.Prima di iniziare
Ogni nodo del cluster deve avere almeno un aggregato.

[NOTE]
====
Per creare un volume FlexGroup per FabricPool in ONTAP 9.5, ciascun nodo deve disporre di almeno un aggregato FabricPool.

====
.A proposito di questa attività
ONTAP seleziona due aggregati con la maggiore quantità di spazio utilizzabile su ciascun nodo per creare il volume FlexGroup. Se non sono disponibili due aggregati, ONTAP seleziona un aggregato per nodo per creare il volume FlexGroup.

A partire da ONTAP 9.15.1, quando si esegue il provisioning automatico di un volume FlexGroup, ONTAP utilizza il posizionamento bilanciato (BP, Balanced Placement) per scegliere gli aggregati e il layout dei componenti FlexGroup. Un aspetto della BP è il modo in cui limita l'overprovisioning degli aggregati quando si crea "nessuno" volumi FlexGroup garantiti. Le dimensioni del volume FlexGroup complessivo sono limitate dalla quantità di spazio libero sugli aggregati, anche se il limite è maggiore di quello riservato ai volumi FlexGroup garantiti. Quando crei un volume FlexGroup utilizzando le API REST o `auto-provision-as` con l'interfaccia a riga di comando di ONTAP, il provisioning potrebbe avere esito negativo a causa di uno spazio insufficiente a causa di questo limite. È possibile evitare questo problema creando volumi FlexGroup più piccoli o link:create-task.html["Creazione di un volume FlexGroup e selezione manuale degli aggregati"] utilizzando il `aggr-list` parametro.

.Fasi
. Provisioning del volume FlexGroup:
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true]`

+
A partire da ONTAP 9.5, è possibile creare volumi FlexGroup per FabricPool. Per eseguire il provisioning automatico di un volume FlexGroup su FabricPool, è necessario impostare `-support-tiering` parametro a. `true`. La garanzia del volume deve essere sempre impostata su `none` Per FabricPool. È inoltre possibile specificare il criterio di tiering e il periodo minimo di raffreddamento del tiering per il volume FlexGroup.

+
link:../disks-aggregates/index.html["Gestione di dischi e aggregati"]

+
Puoi specificare un limite massimo di throughput (qualità del servizio massima) per i volumi FlexGroup. Questo limita le risorse di performance che il volume FlexGroup può utilizzare. A partire da ONTAP 9.4, è possibile specificare i livelli di throughput (QoS min) e la QoS adattiva per i volumi FlexGroup.

+
link:../performance-admin/index.html["Gestione delle performance"]

+
È possibile impostare il `-encrypt` parametro su `true` se si desidera attivare la crittografia sul volume FlexGroup. Per creare un volume crittografato, è necessario aver installato la licenza per la crittografia del volume e il gestore delle chiavi.

+

NOTE: Al momento della creazione, è necessario attivare la crittografia sui volumi FlexGroup. Non è possibile attivare la crittografia sui volumi FlexGroup esistenti.

+
link:../encryption-at-rest/index.html["Crittografia dei dati inattivi"]

+
Il `size` Parametro specifica le dimensioni del volume FlexGroup in KB, MB, GB, TB o PB.

+
L'esempio seguente mostra come eseguire il provisioning di un volume FlexGroup di dimensioni 400 TB:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Nell'esempio seguente viene illustrato come creare un gruppo di criteri QoS per il limite di throughput e come applicarlo a un volume FlexGroup:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
L'esempio seguente mostra come eseguire il provisioning di un volume FlexGroup di 400 TB su aggregati in FabricPool in ONTAP 9.5:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Il volume FlexGroup viene creato con otto componenti su ciascun nodo del cluster. I componenti sono distribuiti in modo uguale tra i due aggregati più grandi su ciascun nodo.

+
Per impostazione predefinita, il volume FlexGroup viene creato con `volume` Impostazione della garanzia di spazio eccetto per i sistemi AFF. Per i sistemi AFF, per impostazione predefinita il volume FlexGroup viene creato con `none` garanzia di spazio.

. Montare il volume FlexGroup con un percorso di giunzione:
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.Al termine
È necessario montare il volume FlexGroup dal client.

Se si utilizza ONTAP 9.6 o versioni precedenti e la macchina virtuale di storage (SVM) ha configurato NFSv3 e NFSv4, il montaggio del volume FlexGroup dal client potrebbe non riuscire. In questi casi, è necessario specificare esplicitamente la versione di NFS quando si monta il volume FlexGroup dal client.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----