---
permalink: flexgroup/restore-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, flexgroup, volume, snapvault, backup 
summary: 'È possibile eseguire un"operazione di ripristino completo dei volumi FlexGroup da una copia Snapshot nel volume secondario SnapVault. È possibile ripristinare il volume FlexGroup sul volume di origine originale o su un nuovo volume FlexGroup.' 
---
= Ripristinare un volume FlexGroup da un backup SnapVault
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire un'operazione di ripristino completo dei volumi FlexGroup da una copia Snapshot nel volume secondario SnapVault. È possibile ripristinare il volume FlexGroup sul volume di origine originale o su un nuovo volume FlexGroup.

.Prima di iniziare
È necessario tenere presente alcune considerazioni quando si esegue il ripristino dai backup di SnapVault per i volumi FlexGroup.

* Solo il ripristino baseline è supportato con copie Snapshot parziali da un backup SnapVault. Il numero di componenti nel volume di destinazione deve corrispondere al numero di componenti nel volume di origine quando è stata eseguita la copia Snapshot.
* Se un'operazione di ripristino non riesce, non sono consentite altre operazioni fino al completamento dell'operazione di ripristino. È possibile riprovare l'operazione di ripristino o eseguirlo con `cleanup` parametro.
* Un volume FlexGroup può essere il volume di origine di una sola relazione di backup o di ripristino. Un volume FlexGroup non può essere l'origine di due relazioni SnapVault, due relazioni di ripristino o una relazione SnapVault e una relazione di ripristino.
* Le operazioni di backup e ripristino di SnapVault non possono essere eseguite in parallelo. Quando è in corso un'operazione di ripristino di base o un'operazione di ripristino incrementale, è necessario interrompere le operazioni di backup.
* È necessario interrompere un'operazione di ripristino di una copia Snapshot parziale dal volume FlexGroup di destinazione. Non è possibile interrompere l'operazione di ripristino di una copia Snapshot parziale dal volume di origine.
* Se si interrompe un'operazione di ripristino, è necessario riavviare l'operazione di ripristino con la stessa copia Snapshot utilizzata per l'operazione di ripristino precedente.


.A proposito di questa attività
Tutte le regole di quota attive sul volume FlexGroup di destinazione vengono disattivate prima di eseguire il ripristino.

È possibile utilizzare `volume quota modify` comando per riattivare le regole di quota al termine dell'operazione di ripristino.

.Fasi
. Ripristinare il volume FlexGroup: `snapmirror restore -source-path _src_svm:src_flexgroup_ -destination-path _dest_svm:dest_flexgroup_ -snapshot _snapshot_name_`
`snapshot_name` È la copia Snapshot che deve essere ripristinata dal volume di origine al volume di destinazione. Se la copia Snapshot non viene specificata, il volume di destinazione viene ripristinato dall'ultima copia Snapshot.
+
[listing]
----
vserverA::> snapmirror restore -source-path vserverB:dstFG -destination-path vserverA:newFG -snapshot daily.2016-07-15_0010
Warning: This is a disruptive operation and the volume vserverA:newFG will be read-only until the operation completes
Do you want to continue? {y|n}: y
----

