---
permalink: flexgroup/snapvault-backup-concept.html 
sidebar: sidebar 
keywords: consider, create, snapvault, backup, relation, unified, data, protection, flexgroup, volume 
summary: È necessario conoscere le considerazioni per la creazione di una relazione di backup SnapVault e di una relazione unificata di protezione dei dati per i volumi FlexGroup. 
---
= Considerazioni per la creazione di una relazione di backup SnapVault e di una relazione di protezione dati unificata per i volumi FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere le considerazioni per la creazione di una relazione di backup SnapVault e di una relazione unificata di protezione dei dati per i volumi FlexGroup.

* Puoi risincronizzare una relazione di backup di SnapVault e una relazione di protezione dei dati unificata, sfruttando `-preserve` un'opzione che ti consente di conservare gli snapshot sul volume di destinazione più recenti rispetto all'ultimo snapshot comune.
* La conservazione a lungo termine non è supportata con i volumi FlexGroup.
+
La conservazione a lungo termine consente di creare snapshot direttamente sul volume di destinazione, senza dover memorizzare gli snapshot sul volume di origine.

* Il `snapshot` comando `expiry-time` L'opzione non è supportata per i volumi FlexGroup.
* L'efficienza dello storage non può essere configurata sul volume FlexGroup di destinazione di una relazione di backup SnapVault e di una relazione unificata di protezione dei dati.
* Non puoi rinominare le snapshot di una relazione di backup di SnapVault e di una relazione di data Protection unificata per FlexGroup Volumes.
* Un volume FlexGroup può essere il volume di origine di una sola relazione di backup o di ripristino.
+
Un volume FlexGroup non può essere l'origine di due relazioni SnapVault, due relazioni di ripristino o una relazione di backup SnapVault e una relazione di ripristino.

* Se si elimina uno snapshot sul volume FlexGroup di origine e si crea nuovamente uno snapshot con lo stesso nome, il successivo trasferimento di aggiornamento al volume FlexGroup di destinazione non riesce se il volume di destinazione ha uno snapshot dello stesso nome.
+
Questo perché gli snapshot non possono essere rinominati per i volumi FlexGroup.


