---
permalink: flexgroup/supported-unsupported-config-concept.html 
sidebar: sidebar 
keywords: support, unsupported, configuration, flexgroup, volumes 
summary: È necessario conoscere le funzionalità di ONTAP supportate e non supportate da FlexGroup Volumes in ONTAP 9. 
---
= Configurazioni supportate e non supportate per i volumi FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere le funzionalità di ONTAP supportate e non supportate da FlexGroup Volumes in ONTAP 9.



== Funzioni supportate a partire da ONTAP 9.16.1

* xref:enable-adv-capacity-flexgroup-task.html[Bilanciamento avanzato della capacità]




== Funzioni supportate a partire da ONTAP 9.15.1

* xref:provision-automatically-task.html[Miglioramenti del provisioning automatico]




== Funzioni supportate a partire da ONTAP 9.14.1

* Tagging degli Snapshot: Supporto per la creazione, la modifica e l'eliminazione di tag degli snapshot (etichette e commenti di SnapMirror) per gli snapshot su volumi FlexGroup tramite il `volume snapshot` comando.




== Funzionalità supportate a partire da ONTAP 9.13.1

* xref:../anti-ransomware/index.html[Protezione ransomware autonoma (ARP)] Per i volumi FlexGroup, incluse le seguenti funzionalità supportate:
+
** Operazioni di espansione di FlexGroup: Un nuovo volume membro eredita gli attributi di protezione autonoma da ransomware.
** Conversioni da FlexVol a FlexGroup: È possibile convertire FlexVol con protezione ransomware autonoma attiva.
** Ribilanciamento dei FlexGroup: La protezione autonoma dai ransomware è supportata durante operazioni di ribilanciamento senza interruzioni e con interruzioni.


* Pianificazione di una singola operazione di ribilanciamento FlexGroup.
* xref:create-snapmirror-cascade-fanout-reference.html[Fanout SnapMirror] Relazioni con SVM DR su volumi FlexGroup. Supporta fan-out fino a otto siti.




== Funzionalità supportate a partire da ONTAP 9.12.1

* xref:manage-flexgroup-rebalance-task.html[Ribilanciamento FlexGroup]
* SnapLock per SnapVault
* FabricPool, FlexGroup e SVM DR funzionano in collaborazione. (Nelle release precedenti a ONTAP 9.12.1, due di queste funzionalità funzionavano insieme, ma non tutte e tre insieme).
* xref:../volumes/enable-large-vol-file-support-task.html[Supporto di grandi volumi] Consente di aumentare le dimensioni dei membri del volume FlexGroup da un massimo di 100TB a un massimo di 300TB.




== Funzionalità supportate a partire da ONTAP 9.11.1

* xref:../snaplock/index.html[Volumi SnapLock]
+
SnapLock non supporta le seguenti funzionalità con FlexGroup Volumes:

+
** Conservazione a fini giudiziari
** Conservazione basata sugli eventi
** SnapLock per SnapVault




SnapLock viene configurato a livello di FlexGroup. Non è possibile configurare SnapLock a livello di volume membro.

* xref:manage-client-async-dir-delete-task.adoc[Eliminazione asincrona della directory del client]




== Funzionalità supportate a partire da ONTAP 9.10.1

* xref:convert-flexvol-svm-dr-relationship-task.adoc[Converti un FlexVol volume in un volume FlexGroup all'interno di una relazione di disaster recovery di SVM]
* xref:../volumes/create-flexclone-task.adoc[Supporto FlexClone DR SVM per volumi FlexGroup]




== Funzionalità supportate a partire da ONTAP 9.9.1

* xref:create-svm-disaster-recovery-relationship-task.html[Disaster recovery SVM]
+
Il cloning di un volume FlexGroup che fa parte di una relazione di disaster recovery della SVM non è supportato.

* Relazioni di fanout di SnapMirror di 2 o più (Da A a B, Da A a C), con un massimo di 8 segmenti di fanout.
+
xref:create-snapmirror-cascade-fanout-reference.adoc[Considerazioni per la creazione di relazioni a cascata e fan-out di SnapMirror per FlexGroups]

* Relazioni a cascata di SnapMirror fino a due livelli (Da A a B a C)
+
xref:create-snapmirror-cascade-fanout-reference.adoc[Considerazioni per la creazione di relazioni a cascata e fan-out di SnapMirror per FlexGroups]





== Funzionalità supportate a partire da ONTAP 9.8

* Ripristino di un singolo file da un vault di FlexGroup SnapMirror o da una destinazione UDP
+
** Il ripristino può essere eseguito da un volume FlexGroup di qualsiasi geometria a un volume FlexGroup di qualsiasi geometria
** È supportato un solo file per operazione di ripristino


* Conversione dei volumi passati dai sistemi 7-Mode a FlexGroup Volumes
+
Per ulteriori informazioni, consultare l'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_To_Convert_a_Transitioned_FlexVol_to_FlexGroup["Come convertire un FlexVol in transizione in FlexGroup"].

* NFSv4.2
* xref:fast-directory-delete-asynchronous-task.html[Eliminazione asincrona di file e directory]
* xref:../concept_nas_file_system_analytics_overview.html[File System Analytics (FSA)]
* FlexGroup come datastore VMware vSphere
* Supporto aggiuntivo per backup e ripristino su nastro con NDMP, incluse le seguenti funzionalità:
+
** NDMP Restartable Backup Extension (RBE) e Snapshot Management Extension (SSME)
** Le variabili di ambiente ESCLUDONO e MULTI_SUBTREE_NAMES supportano i backup FlexGroup
** Introduzione della variabile di ambiente IGNORE_CTIME_MTIME per i backup FlexGroup
** Il ripristino di singoli file in un FlexGroup utilizzando il messaggio NDMP_SNAP_RECOVER, che fa parte dell'estensione 0x2050, le sessioni di dump e ripristino vengono interrotte durante un aggiornamento o un revert.






== Funzionalità supportate a partire da ONTAP 9.7

* xref:../volumes/flexclone-efficient-copies-concept.html[Volume FlexClone]
* NFSv4 e NFSv4.1
* PNFS
* xref:../ndmp/index.html[Backup e ripristino su nastro utilizzando NDMP]
+
Per il supporto NDMP sui volumi FlexGroup, è necessario conoscere i seguenti punti:

+
** Il messaggio NDMP_SNAP_RECOVER nella classe di estensione 0x2050 può essere utilizzato solo per il ripristino di un intero volume FlexGroup.
+
I singoli file in un volume FlexGroup non possono essere ripristinati.

** NDMP retardable backup Extension (RBE) non è supportato per i volumi FlexGroup.
** Le variabili di ambiente ESCLUDI e MULTI_SUBTREE_NAMES non sono supportate per i volumi FlexGroup.
** Il `ndmpcopy` Il comando è supportato per il trasferimento dei dati tra volumi FlexVol e FlexGroup.
+
Se si ripristina Data ONTAP 9.7 a una versione precedente, le informazioni di trasferimento incrementale dei trasferimenti precedenti non vengono conservate e, di conseguenza, è necessario eseguire una copia di riferimento dopo il ripristino.



* API vStorage VMware per l'integrazione degli array (VAAI)
* Conversione di un volume FlexVol in un volume FlexGroup
* Volumi FlexGroup come volumi di origine FlexCache




== Funzionalità supportate a partire da ONTAP 9.6

* Condivisioni SMB sempre disponibili
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Configurazioni MetroCluster"^]
* Ridenominazione di un volume FlexGroup (`volume rename` comando)
* Riduzione o riduzione delle dimensioni di un volume FlexGroup (`volume size` comando)
* Dimensionamento elastico
* Crittografia aggregata NetApp (NAE)
* Cloud Volumes ONTAP




== Funzionalità supportate a partire da ONTAP 9.5

* Offload delle copie ODX
* Access Guard a livello di storage
* Miglioramenti alle notifiche di modifica per le condivisioni SMB
+
Le notifiche di modifica vengono inviate per le modifiche apportate alla directory principale in cui si trova `changenotify` la proprietà viene impostata e per le modifiche a tutte le sottodirectory della directory principale.

* FabricPool
* Applicazione delle quote
* Statistiche qtree
* QoS adattiva per i file nei volumi FlexGroup
* FlexCache (solo cache; FlexGroup come origine supportato in ONTAP 9.7)




== Funzionalità supportate a partire da ONTAP 9.4

* FPolicy
* Controllo dei file
* Throughput floor (QoS min) e QoS adattiva per volumi FlexGroup
* Limite di throughput (QoS max) e piano di throughput (QoS min) per i file nei volumi FlexGroup
+
Si utilizza `volume file modify` Comando per gestire il gruppo di policy QoS associato a un file.

* Limiti di SnapMirror rilassati
* SMB 3.x multicanale




== Funzioni supportate in ONTAP 9,3 e versioni precedenti

* Configurazione antivirus
* Notifiche di modifica per le condivisioni SMB
+
Le notifiche vengono inviate solo per le modifiche apportate alla directory principale in cui si trova `changenotify` proprietà impostata. Le notifiche di modifica non vengono inviate per le modifiche apportate alle sottodirectory nella directory principale.

* Qtree
* Limite di throughput (QoS max)
* Espandere il volume FlexGroup di origine e il volume FlexGroup di destinazione in una relazione SnapMirror
* Backup e ripristino di SnapVault
* Relazioni unificate per la data Protection
* Opzione di crescita automatica e opzione di riduzione automatica
* Conteggio inode conteggiato per l'acquisizione
* Crittografia dei volumi
* Deduplica aggregata inline (deduplica tra volumi)
* xref:../encryption-at-rest/encrypt-volumes-concept.html[Crittografia dei volumi NetApp (NVE)]
* Tecnologia SnapMirror
* Snapshot
* Consulente digitale
* Compressione adattiva inline
* Deduplica inline
* Compaction dei dati inline
* AFF
* Creazione di report sulle quote
* Tecnologia Snapshot di NetApp
* Software SnapRestore (livello FlexGroup)
* Aggregati ibridi
* Spostamento del volume del componente o del membro
* Deduplica post-elaborazione
* Tecnologia NetApp RAID-TEC
* Punto di coerenza per aggregato
* Condivisione di FlexGroup con il volume FlexVol nella stessa SVM




== Configurazioni del volume FlexGroup non supportate in ONTAP 9

|===


| Protocolli non supportati | Funzionalità di protezione dei dati non supportate | Altre funzioni ONTAP non supportate 


 a| 
* xref:../nfs-admin/enable-disable-pnfs-task.html[PNFS] (ONTAP 9.6 e precedenti)
* SMB 1.0
* xref:../smb-hyper-v-sql/witness-protocol-transparent-failover-concept.html[Failover trasparente SMB] (ONTAP 9.5 e precedenti)
* xref:../volumes/san-volumes-concept.html[SAN]

 a| 
* xref:../snaplock/index.html[Volumi SnapLock] (ONTAP 9.10,1 e versioni precedenti)
* xref:../tape-backup/smtape-engine-concept.html[SMTape]
* xref:../data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html[SnapMirror sincrono]
* Disaster recovery SVM con volumi FlexGroup contenenti FabricPools (ONTAP 9.11.1 e versioni precedenti)

 a| 
* xref:../smb-hyper-v-sql/share-based-backups-remote-vss-concept.html[Servizio di copia shadow del volume remoto (VSS)]
* xref:../svm-migrate/index.html[Mobilità dei dati SVM]


|===