---
permalink: flexcache-writeback/flexcache-write-back-interoperability.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, interoperability, client, technical report, netapp tr, ontap tr 
summary: 'Comprendere queste considerazioni sull"interoperabilità durante la distribuzione di FlexCache in modalità write-back' 
---
= Interoperabilità di writeback di FlexCache
:allow-uri-read: 


[role="lead"]
Comprendere queste considerazioni sull'interoperabilità durante la distribuzione di FlexCache in modalità write-back.



== Versione di ONTAP

Per utilizzare la modalità operativa write-back, sia la cache che l'origine *devono* eseguire ONTAP 9.15.1 o versioni successive.


NOTE: I cluster in cui non è necessaria una cache abilitata alla riscrittura possono eseguire versioni precedenti di ONTAP, ma tale cluster può operare solo in modalità write-around.

È possibile disporre di una combinazione di versioni di ONTAP nel proprio ambiente.

[cols="1*,1*,1*"]
|===
| Cluster | Versione di ONTAP | Write-back supportato? 


| *Origine* | ONTAP 9.15.1 | N/A † 


| *Cluster 1* | ONTAP 9.15.1 | Sì 


| *Cluster 2* | ONTAP 9.14.1 | No 
|===
[cols="1*,1*,1*"]
|===
| Cluster | Versione di ONTAP | Write-back supportato? 


| *Origine* | ONTAP 9.14.1 | N/A † 


| *Cluster 1* | ONTAP 9.15.1 | No 


| *Cluster 2* | ONTAP 9.15.1 | No 
|===
† _Origins non sono una cache, quindi né il supporto write-back né quello write-around sono applicabili._


NOTE: In <<example2-table>>, nessuno dei due cluster può abilitare la modalità write-back perché l'origine non esegue ONTAP 9.15.1 o versioni successive, il che è un requisito rigoroso.



== Interoperabilità dei client

Qualsiasi client generalmente supportato da ONTAP può accedere a un volume FlexCache indipendentemente dal fatto che stia operando in modalità write-around o write-back. Per un elenco aggiornato dei client supportati, fare riferimento al manuale NetApp's https://imt.netapp.com/matrix/#welcome["matrice di interoperabilità"^].

Anche se la versione client non ha importanza specifica, il client deve essere abbastanza nuovo da supportare NFSv3, NFSv4,0, NFSv4,1, SMB2.x o SMB3.x SMB1 e NFSv2 sono protocolli obsoleti e non sono supportati.



== Write-back e write-around

Come illustrato in <<example1-table>>, FlexCache che opera in modalità write-back può coesistere con le cache che operano in modalità write-around. Si consiglia di confrontare la memoria write-around e quella write-back con il proprio carico di lavoro specifico.


TIP: Se le performance per un carico di lavoro sono le stesse tra write-back e write-around, utilizza la funzionalità write-around.



== Interoperabilità delle funzionalità di ONTAP

Per l'elenco più aggiornato di interoperabilità delle funzioni FlexCache, fare riferimento a link:../flexcache/supported-unsupported-features-concept.html["Funzionalità supportate e non supportate per FlexCache Volumes"].
