---
permalink: flexcache-writeback/flexcache-write-back-prerequisites.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, prerequisites, technical report, netapp tr, ontap tr 
summary: Prima di distribuire FlexCache in modalità write-back, accertarsi di aver soddisfatto i requisiti di software, licenza e configurazione del sistema. 
---
= Prerequisiti per la riscrittura di ONTAP FlexCache
:allow-uri-read: 


[role="lead"]
Prima di implementare FlexCache in modalità write-back, verificare di aver soddisfatto i requisiti relativi a prestazioni, software, licenze e configurazione del sistema.



== CPU e memoria

Si consiglia vivamente che ciascun nodo del cluster di origine disponga di almeno 128 GB di RAM e 20 CPU per assorbire i messaggi di write-back avviati dalle cache abilitate per la write-back. Equivalente a A400 o superiore. Se il cluster di origine funge da origine per più FlexCaches abilitati per la riscrittura, richiederà più CPU e RAM.


CAUTION: L'utilizzo di un'origine non sufficientemente dimensionata per il tuo carico di lavoro può avere un impatto profondo sulle performance della cache abilitata per la riscrittura o dell'origine.



== Versione di ONTAP

* L'origine *_must_* esegue ONTAP 9.15.1 o versione successiva.
* Qualsiasi cluster di caching che deve funzionare in modalità write-back *_deve_* eseguire ONTAP 9.15.1 o versioni successive.
* Qualsiasi cluster di caching che non ha bisogno di operare in modalità write-back può eseguire qualsiasi versione di ONTAP generalmente supportata.




== Licensing

FlexCache, compresa la modalità operativa di riscrittura, è inclusa nell'acquisto di ONTAP. Non è richiesta alcuna licenza aggiuntiva.



== Peering

* I cluster di origine e cache devono essere link:../flexcache-writeback/flexcache-writeback-enable-task.html["cluster peered"]
* Le macchine virtuali dei server (SVM) sull'origine e sul cluster di cache devono essere link:../flexcache-writeback/flexcache-writeback-enable-task.html["svm peered"] dotate dell'opzione FlexCache.



NOTE: Non è necessario collegare un cluster di cache a un altro cluster di cache. Inoltre, non è necessario peer di una SVM cache in un'altra SVM cache.
