---
sidebar: sidebar 
permalink: smbc/smbc_install_confirm_ontap_cluster.html 
keywords: SM-BC, SMBC, ONTAP, cluster, configure, peering, volume, SVM, SAN, LIFs, map, igroup, discover 
summary: Assicurarsi che i cluster di origine e di destinazione siano configurati correttamente. 
---
= Installare il servizio di supporto ONTAP e confermare la configurazione del cluster ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Assicurarsi che i cluster di origine e di destinazione siano configurati correttamente.

.A proposito di questa attività
Procedere con ciascuna delle seguenti operazioni. Per ogni fase, è necessario confermare che la configurazione specifica è stata eseguita. Utilizza il link incluso dopo ogni passaggio per ottenere ulteriori informazioni in base alle necessità.

.Fasi
. Installare il servizio ONTAP Mediator prima di assicurarsi che i cluster di origine e di destinazione siano configurati correttamente.
+
xref:../mediator/index.html[Servizio mediatore ONTAP]

. Verificare che esista una relazione di peering del cluster tra i cluster.
+

NOTE: L'IPSpace predefinito è richiesto da SM-BC per le relazioni peer del cluster. IPSpace personalizzato non supportato.

+
xref:../task_dp_prepare_mirror.html[Configurare le relazioni peer]

. Verificare che le VM di storage siano create su ciascun cluster.
+
xref:../smb-config/create-svms-data-access-task.html[Creazione di una SVM]

. Verificare l'esistenza di una relazione peer tra le VM di storage su ciascun cluster.
+
xref:../peering/create-intercluster-svm-peer-relationship-93-later-task.html[Creazione di una relazione di peering SVM]

. Verificare che i volumi esistano per le LUN.
+
xref:../smb-config/create-volume-task.html[Creazione di un volume]

. Verificare che sia stata creata almeno una LIF SAN su ciascun nodo del cluster.
+
link:../san-admin/lifs-cluster-concept.html["Considerazioni per le LIF in un ambiente SAN cluster"]

+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-4B666C44-694A-48A3-B0A9-517FA7FD2502.html?cp=13_6_4_0["Creazione di una LIF"^]

. Verificare che i LUN necessari siano creati e mappati a igroup, che viene utilizzato per mappare i LUN all'iniziatore sull'host dell'applicazione.
+
xref:../san-admin/create-luns-mapping-igroups-task.html[Creare LUN e mappare igroups]

. Eseguire nuovamente la scansione dell'host dell'applicazione per rilevare eventuali nuove LUN.

