---
sidebar: sidebar 
permalink: smbc/smbc_admin_monitoring.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, SM-BC status 
summary: Esistono diversi componenti e operazioni SM-BC che è possibile monitorare. 
---
= Monitorare le operazioni di Business Continuity di SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile monitorare le seguenti operazioni di Business Continuity SnapMirror (SM-BC) per garantire lo stato di salute della configurazione SM-BC:

* Mediatore ONTAP
* Operazioni di failover pianificate
* Operazioni di failover automatiche non pianificate
* Disponibilità SM-BC




== Mediatore ONTAP

Durante le normali operazioni, lo stato del mediatore ONTAP deve essere connesso. Se si trova in qualsiasi altro stato, potrebbe essere presente una condizione di errore. È possibile rivedere link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["Messaggi EMS (Event Management System)"^] per determinare l'errore e le azioni correttive appropriate.



== Operazioni di failover pianificate

È possibile monitorare lo stato e l'avanzamento di un'operazione di failover pianificata utilizzando `snapmirror failover show` comando. Ad esempio:

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
Una volta completata l'operazione di failover, è possibile monitorare lo stato di protezione di Synchronous SnapMirror dal nuovo cluster di destinazione. Ad esempio:

....
ClusterA::> snapmirror show
....
Fare riferimento a. link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["Riferimento EMS"^] per informazioni sui messaggi di evento e sulle azioni correttive.



== Operazioni di failover automatiche non pianificate

Durante un failover automatico non pianificato, è possibile monitorare lo stato dell'operazione utilizzando `snapmirror failover show` comando.

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
Fare riferimento a. link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["Riferimento EMS"^] per informazioni sui messaggi di evento e sulle azioni correttive.



== Disponibilità SM-BC

È possibile verificare la disponibilità della relazione SM-BC utilizzando una serie di comandi, sul cluster primario, sul cluster secondario o su entrambi.

I comandi utilizzati includono `snapmirror mediator show` sul cluster primario e secondario per controllare lo stato di connessione e quorum, il `snapmirror show` e il `volume show` comando. Ad esempio:

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored InSync  -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored InSync    -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....