---
sidebar: sidebar 
permalink: smbc/smbc_admin_performing_a_planned_failover.html 
keywords: SM-BC, SMBC, testing failover, planned failover, maintenance, Mediator, quorum 
summary: È possibile eseguire un failover pianificato per verificare la configurazione del disaster recovery o per eseguire la manutenzione sul cluster primario. 
---
= Eseguire un failover pianificato
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In un failover pianificato, è possibile cambiare i ruoli dei cluster primario e secondario, in modo che il cluster secondario prenda il controllo dal cluster primario. Durante un failover, il cluster secondario elabora le richieste di input e output in locale senza interrompere le operazioni del client.

È possibile eseguire un failover pianificato per verificare lo stato della configurazione di disaster recovery o per eseguire la manutenzione sul cluster primario.

.A proposito di questa attività
L'amministratore del cluster secondario avvia un failover pianificato. L'operazione richiede la commutazione dei ruoli primario e secondario in modo che il cluster secondario prenda il posto del primario. Il nuovo cluster primario può quindi iniziare a elaborare le richieste di input e output localmente senza interrompere le operazioni del client.

.Prima di iniziare
* La relazione SM-BC deve essere sincronizzata.
* Non è possibile avviare un failover pianificato quando è in corso un'operazione senza interruzioni. Le operazioni senza interruzioni includono spostamenti di volumi, trasferimenti di aggregazioni e failover dello storage.
* Il mediatore ONTAP deve essere configurato, connesso e in quorum.


.Fasi
È possibile eseguire un failover pianificato utilizzando l'interfaccia utente di ONTAP o Gestione di sistema.

[role="tabbed-block"]
====
.CLI ONTAP
--
. Dal cluster di destinazione, avviare l'operazione di failover:
+
`destination::>snapmirror failover start -destination-path   vs1_dst:/cg/cg_dst`

. Monitorare l'avanzamento del failover:
+
`destination::>snapmirror failover show`

. Una volta completata l'operazione di failover, è possibile monitorare lo stato della relazione di protezione di Synchronous SnapMirror dalla destinazione:
+
`destination::>snapmirror show`



--
.System Manager
--
. In System Manager, selezionare **protezione > Panoramica > Relazioni**.
. Identificare la relazione SM-BC che si desidera eseguire il failover. Accanto al nome, selezionare `...` Accanto al nome della relazione, quindi selezionare **failover**.
. Per monitorare lo stato del failover, utilizzare `snapmirror failover show` Nella CLI di ONTAP.


--
====