---
sidebar: sidebar 
permalink: smbc/smbc_plan_ontap_access_options.html 
keywords: SM-BC, SMBC, access options, CLI, command line interface, System Manager, REST API 
summary: 'Sono disponibili diverse opzioni di accesso per la configurazione dei nodi ONTAP che partecipano a un"implementazione SM- BC.' 
---
= Opzioni di accesso a ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sono disponibili diverse opzioni di accesso per la configurazione dei nodi ONTAP che partecipano a un'implementazione SM- BC. È necessario selezionare l'opzione che meglio corrisponde al proprio ambiente e agli obiettivi di implementazione specifici.


NOTE: In tutti i casi, è necessario accedere utilizzando l'account amministratore con una password valida.

Interfaccia della riga di comando:: L'interfaccia della riga di comando basata su testo è disponibile attraverso la shell di gestione di ONTAP. È possibile accedere alla CLI utilizzando la shell sicura (SSH).
System Manager:: È possibile connettersi a System Manager utilizzando un moderno browser Web. L'interfaccia grafica web fornisce un'interfaccia intuitiva e facile da usare per accedere alla funzionalità di Business Continuity di SnapMirror. Per ulteriori informazioni sull'utilizzo di System Manager, vedere https://docs.netapp.com/us-en/ontap/["Documentazione di System Manager"^].
API REST:: L'API REST di ONTAP esposta ai client esterni offre un'altra opzione durante la connessione a ONTAP. È possibile accedere all'API utilizzando qualsiasi linguaggio di programmazione mainstream o tool che supporti i servizi Web REST. Le scelte più popolari includono:
+
--
* Python (inclusa la libreria client Python di ONTAP)
* Java
* Arricciatura


--


L'utilizzo di un linguaggio di programmazione o scripting offre l'opportunità di automatizzare l'implementazione e la gestione di un'implementazione di Business Continuity SnapMirror. Per ulteriori informazioni, consultare la pagina della documentazione online di ONTAP nel sistema di storage ONTAP.
