---
sidebar: sidebar 
permalink: smbc/smbc_plan_prerequisites.html 
keywords: SM-BC, SMBC, prerequisites, planning, software, hardware, licensing, protocols, network, snapmirror active sync 
summary: 'Per la pianificazione dell"implementazione di una soluzione di Business Continuity SnapMirror, è necessario prendere in considerazione diversi prerequisiti.' 
---
= Prerequisiti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la pianificazione dell'implementazione di SnapMirror Business Continuity, assicurarsi di aver soddisfatto i diversi requisiti di configurazione hardware, software e di sistema.



== Hardware

* Sono supportati solo cluster ha a due nodi
* Entrambi i cluster devono essere AFF (incluso AFF C-Series) o ASA (senza combinazione)




== Software

* ONTAP 9.8 o versione successiva
* Mediatore ONTAP 1.2 o versione successiva
* Un server Linux o una macchina virtuale per il mediatore ONTAP che esegue una delle seguenti operazioni:


[cols="30,70"]
|===


| Versione del mediatore ONTAP | Versioni Linux supportate 


 a| 
1.6
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 e 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 8.1
* CentOS: 7.6, 7.7, 7.8


|===


== Licensing

* La licenza SnapMirror Synchronous (SM-S) deve essere applicata a entrambi i cluster
* La licenza SnapMirror deve essere applicata su entrambi i cluster
+

NOTE: Se i sistemi storage ONTAP sono stati acquistati prima di giugno 2019, vedere link:https://mysupport.netapp.com/site/systems/master-license-keys["Chiavi di licenza master NetApp ONTAP"^] Per ottenere la licenza SM-S richiesta.





== Ambiente di rete

* Il tempo di round trip (RTT) di latenza tra cluster deve essere inferiore a 10 millisecondi.
* Le prenotazioni persistenti SCSI-3 sono **non** supportate con SM-BC .




== Protocolli supportati

* Sono supportati solo i protocolli SAN (non NFS/SMB).
* Sono supportati solo i protocolli Fibre Channel e iSCSI.
* L'IPSpace predefinito è richiesto da SM-BC per le relazioni peer del cluster. IPSpace personalizzato non supportato.




== Sicurezza NTFS

Lo stile di sicurezza NTFS *non* è supportato sui volumi SM-BC.



== Mediatore ONTAP

* Il provisioning del mediatore ONTAP viene eseguito esternamente e collegato a ONTAP per il failover trasparente delle applicazioni.
* Per essere pienamente funzionale e per abilitare il failover automatico non pianificato, il mediatore ONTAP esterno deve essere fornito e configurato con cluster ONTAP.
* Il supporto ONTAP deve essere installato in un terzo dominio di errore, separato dai due cluster ONTAP.
* Quando si installa il mediatore ONTAP, è necessario sostituire il certificato autofirmato con un certificato valido firmato da una CA mainstream affidabile.
* Per ulteriori informazioni sul mediatore ONTAP, vedere link:../mediator/index.html["Preparare l'installazione del servizio ONTAP Mediator"].




== Volumi di destinazione in lettura/scrittura

* Le relazioni SM-BC non sono supportate sui volumi di destinazione in lettura/scrittura. Prima di poter utilizzare un volume di lettura/scrittura, è necessario convertirlo in un volume DP creando una relazione SnapMirror a livello di volume ed eliminando la relazione. Per ulteriori informazioni, vedere link:smbc_admin_converting_existing_relationships_to_smbc.html["Conversione delle relazioni esistenti in relazioni SM-BC"]




== Grandi LUN e grandi volumi

Il supporto per LUN di grandi dimensioni e grandi volumi (superiori a 100 TB) dipende dalla versione di ONTAP in uso e dalla piattaforma.

[role="tabbed-block"]
====
.ONTAP 9.12.1P2 e versioni successive
--
* Per ONTAP 9.12.1 P2 e versioni successive, SMBC supporta LUN di grandi dimensioni e volumi superiori a 100 TB su ASA e AFF (inclusa la serie C).



NOTE: Per ONTAP versione 9.12.1P2 e successive, è necessario assicurarsi che i cluster primario e secondario siano tutti gli array SAN o tutti gli array flash e che entrambi abbiano installato ONTAP 9.12.1 P2 o versione successiva. Se il cluster secondario esegue una versione precedente a ONTAP 9.12.1P2 o se il tipo di array non è lo stesso del cluster primario, la relazione sincrona può uscire dalla sincronizzazione se il volume primario supera i 100 TB.

--
.ONTAP 9.8 - 9.12.1P1
--
* Per le versioni ONTAP comprese tra ONTAP 9.8 e 9.12.1 P1 (incluse), le LUN di grandi dimensioni e i grandi volumi superiori a 100 TB sono supportati solo su tutti gli array SAN.



NOTE: Per le versioni di ONTAP comprese tra ONTAP 9.8 e 9.12.1 P2, è necessario assicurarsi che i cluster primario e secondario siano tutti array SAN e che entrambi abbiano installato ONTAP 9.8 o versione successiva. Se il cluster secondario esegue una versione precedente a ONTAP 9.8 o se non si tratta di un array All SAN, la relazione sincrona può uscire dalla sincronizzazione se il volume primario supera i 100 TB.

--
====


== Ulteriori informazioni

* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../mediator/mediator-overview-concept.html["Panoramica del mediatore ONTAP"^]

