---
sidebar: sidebar 
permalink: smbc/smbc_install_confirm_ontap_cluster.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP Mediator, initialize, snapmirror active sync 
summary: 'SM-BC richiede l"installazione e l"inizializzazione del mediatore ONTAP e la garanzia di un peering corretto del cluster.' 
---
= Configurare il mediatore ONTAP e i cluster per la business continuity SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Business Continuity (SM-BC) utilizza cluster peered per garantire la disponibilità dei dati in caso di failover. Il mediatore ONTAP è una risorsa chiave che garantisce la business continuity, monitorando lo stato di salute di ogni cluster. Per configurare SM-BC, è necessario prima installare il mediatore ONTAP e assicurarsi che i cluster primari e secondari siano configurati correttamente.

Una volta installato il mediatore ONTAP e configurato i cluster, è necessario <<initialize-the-ontap-mediator>> Il mediatore ONTAP da utilizzare con SM-BC. Devi quindi xref:../task_san_configure_protection_for_business_continuity.html[Creare, inizializzare e mappare il gruppo di coerenza per SM-BC]



== Mediatore ONTAP

Il mediatore ONTAP stabilisce un quorum per i cluster ONTAP in una relazione SM-BC. Coordina il failover automatico quando viene rilevato un guasto, determinando quale cluster agisce come principale e garantendo che i dati vengano serviti da e verso la destinazione corretta.

.Prerequisiti per il mediatore ONTAP
* Il mediatore ONTAP include un proprio set di prerequisiti. È necessario soddisfare questi prerequisiti prima di installare il mediatore.
+
Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Preparare l'installazione del servizio ONTAP Mediator"^].

* Per impostazione predefinita, il supporto ONTAP fornisce il servizio tramite la porta TCP 31784. Assicurarsi che la porta 31784 sia aperta e disponibile tra i cluster ONTAP e il mediatore.




== Installare il mediatore ONTAP e confermare la configurazione del cluster

Procedere con ciascuna delle seguenti operazioni. Per ogni fase, è necessario confermare che la configurazione specifica è stata eseguita. Utilizza il link incluso dopo ogni passaggio per ottenere ulteriori informazioni in base alle necessità.

.Fasi
. Installare il servizio ONTAP Mediator prima di assicurarsi che i cluster di origine e di destinazione siano configurati correttamente.
+
xref:../mediator/index.html[Preparazione all'installazione o all'aggiornamento del servizio ONTAP Mediator]

. Verificare che esista una relazione di peering del cluster tra i cluster.
+

NOTE: L'IPSpace predefinito è richiesto da SM-BC per le relazioni peer del cluster. Un IPSpace personalizzato non è supportato.

+
xref:../task_dp_prepare_mirror.html[Configurare le relazioni peer]

. Verificare che le VM di storage siano create su ciascun cluster.
+
xref:../smb-config/create-svms-data-access-task.html[Creazione di una SVM]

. Verificare l'esistenza di una relazione peer tra le VM di storage su ciascun cluster.
+
xref:../peering/create-intercluster-svm-peer-relationship-93-later-task.html[Creazione di una relazione di peering SVM]

. Verificare che i volumi esistano per le LUN.
+
xref:../smb-config/create-volume-task.html[Creazione di un volume]

. Verificare che sia stata creata almeno una LIF SAN su ciascun nodo del cluster.
+
link:../san-admin/lifs-cluster-concept.html["Considerazioni per le LIF in un ambiente SAN cluster"]

+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-4B666C44-694A-48A3-B0A9-517FA7FD2502.html?cp=13_6_4_0["Creazione di una LIF"^]

. Verificare che i LUN necessari siano creati e mappati a un igroup, che viene utilizzato per mappare i LUN all'iniziatore sull'host dell'applicazione.
+
xref:../san-admin/create-luns-mapping-igroups-task.html[Creare LUN e mappare igroups]

. Eseguire nuovamente la scansione dell'host dell'applicazione per rilevare eventuali nuove LUN.




== Inizializzare il mediatore ONTAP per SM-BC

Una volta installato il mediatore ONTAP e confermata la configurazione del cluster, è necessario inizializzare il mediatore ONTAP per il monitoraggio del cluster. È possibile inizializzare il supporto ONTAP utilizzando Gestione di sistema o l'interfaccia utente di ONTAP.

[role="tabbed-block"]
====
.System Manager
--
Con Gestione di sistema, è possibile configurare il server ONTAP Mediator per il failover automatico. È inoltre possibile sostituire SSL e CA autofirmati con certificati SSL e CA validati di terze parti, se non è già stato fatto.

.Fasi
. Accedere a *protezione > Panoramica > Mediator > Configura*.
. Selezionare *Aggiungi* e immettere le seguenti informazioni sul server ONTAP Mediator:
+
** Indirizzo IPv4
** Nome utente
** Password
** Certificato




--
.CLI
--
È possibile inizializzare il mediatore ONTAP dal cluster primario o secondario utilizzando l'interfaccia CLI di ONTAP. Quando si invia il `mediator add` Su un cluster, il mediatore ONTAP viene aggiunto automaticamente sull'altro cluster.

.Fasi
. Inizializzare Mediator su uno dei cluster:
+
`snapmirror mediator add -mediator-address IP_Address -peer-cluster cluster_name -username user_name`

+
*Esempio*

+
....
cluster1::> snapmirror mediator add -mediator-address 192.168.10.1 -peer-cluster cluster2 -username mediatoradmin
Notice: Enter the mediator password.

Enter the password: ******
Enter the password again: ******
....
. Controllare lo stato della configurazione del Mediator:
+
`snapmirror mediator show`

+
....
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
192.168.10.1     cluster-2        connected         true
....
+
`Quorum Status` Indica se le relazioni del gruppo di coerenza SnapMirror sono sincronizzate con il mediatore; uno stato di `true` indica che la sincronizzazione è stata eseguita correttamente.



--
====