---
sidebar: sidebar 
permalink: smbc/smbc_admin_converting_existing_relationships_to_smbc.html 
keywords: SM-BC, SMBC, convert, Synchronous SnapMirror, zero RPO, zero recovery time objective, zero RTO, existing, snapmirror active sync 
summary: 'È possibile convertire una relazione SnapMirror sincrona con protezione zero recovery point (zero RPO) esistente in una relazione di gruppo di coerenza SnapMirror sincrona SM-BC zero RTO.' 
---
= Convertire le relazioni esistenti in relazioni SM-BC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se si dispone di una relazione SnapMirror sincrona esistente tra un cluster di origine e di destinazione, è possibile convertirla in una relazione SM-BC. Ciò consente di associare i volumi mirrorati a un gruppo di coerenza, garantendo zero RPO in un carico di lavoro multi-volume. Inoltre, è possibile conservare le snapshot SnapMirror esistenti se è necessario ripristinarle in un momento specifico prima di stabilire la relazione SM-BC.

.Prima di iniziare
* Deve esistere una relazione SnapMirror sincrona RPO zero tra il cluster primario e secondario.
* Prima di poter creare la relazione SnapMirror zero RTO, è necessario rimuovere la mappatura di tutti i LUN del volume di destinazione.
* SM-BC supporta solo i protocolli SAN (non NFS/CIFS). Assicurarsi che nessun componente del gruppo di coerenza sia montato per l'accesso NAS.


.A proposito di questa attività
* È necessario essere un amministratore di cluster e SVM sui cluster primario e secondario.
* Non è possibile convertire zero RPO in zero RTO Sync modificando il criterio SnapMirror.
* Assicurarsi che i LUN siano dismappati prima di emettere `snapmirror create` comando.
+
Se i LUN esistenti sul volume secondario sono mappati e l' `AutomatedFailover` il criterio è configurato, il `snapmirror create` genera un errore.



.Fasi
. Dal cluster secondario, eseguire un aggiornamento di SnapMirror sulla relazione esistente:
+
`destination::>snapmirror update -destination-path vs1_dst:vol1`

. Verificare che l'aggiornamento di SnapMirror sia stato completato correttamente:
+
`destination::>snapmirror show`

. Interrompere ciascuna delle relazioni sincrone RPO zero:
+
`destination::>snapmirror quiesce -destination-path vs1_dst:vol1`

+
`destination::>snapmirror quiesce -destination-path vs1_dst:vol2`

. Eliminare ciascuna delle relazioni sincrone RPO zero:
+
`destination::>snapmirror delete -destination-path vs1_dst:vol1`

+
`destination::>snapmirror delete -destination-path vs1_dst:vol2`

. Rilasciare la relazione SnapMirror di origine, conservando le copie Snapshot comuni:
+
`source::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol1`

+
`source::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol2`

. Creare una relazione SnapMirror sincrona RTO zero di gruppo:
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol1:@vol1,vol2:@vol2 -policy AutomatedFailover`

. Risincronizzare il gruppo di coerenza:
+
`destination::> snapmirror resync -destination-path vs1_dst:/cg/cg_dst`

. Eseguire nuovamente la scansione dei percorsi i/o del LUN host per ripristinare tutti i percorsi dei LUN.

