---
sidebar: sidebar 
permalink: smbc/smbc_plan_summary_of_deployment_best_practices.html 
keywords: SM-BC, SMBC, best practices, planning, SAN, Mediator, SnapMirror 
summary: 'Per pianificare un"implementazione di SnapMirror Business Continuity, è necessario prendere in considerazione diverse Best practice.' 
---
= Riepilogo delle Best practice di implementazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per pianificare un'implementazione di SnapMirror Business Continuity, è necessario prendere in considerazione diverse Best practice.



== SAN

La soluzione di Business Continuity SnapMirror supporta solo i carichi di lavoro SAN. In tutti i casi, è necessario seguire le Best practice DELLA SAN.

Inoltre:

* Le LUN replicate nel cluster secondario devono essere mappate all'host e i percorsi i/o alle LUN del cluster primario e secondario devono essere rilevati al momento della configurazione dell'host.
* Dopo un evento fuori sincronizzazione (OOS) che supera i 80 secondi o dopo un failover automatico non pianificato, è importante eseguire nuovamente la scansione del percorso i/o del LUN host per garantire che non vi sia alcuna perdita del percorso i/O. Per ulteriori informazioni, consultare la documentazione del vendor del sistema operativo host relativo alla riscan dei percorsi di i/o LUN.




== Mediatore

Per essere pienamente funzionale e per abilitare il failover automatico non pianificato, il mediatore ONTAP esterno deve essere fornito e configurato con cluster ONTAP.

Quando si installa il mediatore, è necessario sostituire il certificato autofirmato con un certificato valido firmato da una CA mainstream affidabile.



== SnapMirror

Terminare una relazione SnapMirror nel seguente ordine:

. Eseguire `snapmirror delete` nel cluster di destinazione
. Eseguire `snapmirror release` nel cluster di origine

