---
sidebar: sidebar 
permalink: smbc/smbc_troubleshoot_sm_delete_fails_in_takeover_state.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync 
summary: 'Quando ONTAP 9.9.1 viene installato in un cluster, eseguire `snapmirror delete` Il comando non riesce quando una relazione di gruppo di coerenza SM-BC è in stato di Takeover.' 
---
= L'operazione di eliminazione di SnapMirror non riesce nello stato di takover
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


.Problema:
[role="lead"]
Quando ONTAP 9.9.1 viene installato in un cluster, eseguire `snapmirror delete` Il comando non riesce quando una relazione di gruppo di coerenza SM-BC è in stato di Takeover.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.Soluzione
Quando i nodi in una relazione SM-BC sono in stato di Takeover, eseguire l'operazione di eliminazione e rilascio di SnapMirror con l'opzione "-force" impostata su true.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....