---
sidebar: sidebar 
permalink: smbc/smbc_install_creating_a_consistency_group_relationship.html 
keywords: SM-BC, SMBC, consistency group, create, constituent 
summary: È necessario creare un gruppo di coerenza SnapMirror che stabilisca anche la relazione di gruppo di coerenza sincrona. 
---
= Creare una relazione di gruppo di coerenza
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È necessario creare un gruppo di coerenza SM-BC che stabilisca anche la relazione di gruppo di coerenza sincrona.


NOTE: Questo flusso di lavoro si applica agli utenti in ONTAP 9.8 e 9.9.1. Se si utilizzano questi comandi dell'interfaccia utente di ONTAP a partire da ONTAP 9.10.1, questi continuano a funzionare per creare un gruppo di coerenza, tuttavia, si consiglia di gestire i gruppi di coerenza con Gestore di sistema o l'API REST di ONTAP.

.Prima di iniziare
Si applicano i seguenti prerequisiti e limitazioni:

* È necessario essere un amministratore di cluster o di macchine virtuali per lo storage
* È necessario disporre di una licenza SnapMirror Synchronous
* I volumi di destinazione devono essere di tipo DP
* La VM di storage primaria e secondaria deve essere in relazione peered
* Tutti i volumi costituenti di un gruppo di coerenza devono trovarsi in una singola Storage VM
* Non è possibile stabilire relazioni di gruppo di coerenza SM-BC tra cluster ASA e cluster non ASA
* Il nome del gruppo di coerenza deve essere univoco


.A proposito di questa attività
È necessario creare la relazione del gruppo di coerenza dal cluster di destinazione. È possibile mappare fino a 12 elementi utilizzando `cg-item-mappings` sul `snapmirror create` comando.

.Fasi
. Creare un gruppo di coerenza e una relazione costituente. In questo esempio vengono creati due gruppi di coerenza: cg_src con i volumi costituenti Vol1 e Vol2 e cg_dist con i volumi costituenti Vol1_dr e vol2_dr.
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`


