---
permalink: s3-audit/select-buckets-task.html 
sidebar: sidebar 
keywords: s3 audit, select, buckets 
summary: 'È necessario specificare quali bucket eseguire il controllo in una SVM abilitata per l"audit.' 
---
= Selezionare i bucket per il controllo S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario specificare quali bucket eseguire il controllo in una SVM abilitata per l'audit.

.Di cosa hai bisogno
* SVM abilitato per il controllo S3.


.A proposito di questa attività
Le configurazioni di controllo S3 sono abilitate per SVM, ma è necessario selezionare i bucket nelle SVM che sono abilitati per l'audit. Se si aggiungono bucket alla SVM e si desidera che i nuovi bucket vengano controllati, è necessario selezionarli con questa procedura. È inoltre possibile avere bucket non controllati in una SVM abilitata per il controllo S3.

Le configurazioni di controllo persistono per i bucket fino a quando non vengono rimosse da `vserver object-store-server audit object-select delete` comando.

.Procedura
Seleziona un bucket per l'audit S3:

`vserver object-store-server audit event-selector create -vserver _svm_name_ -bucket _bucket_name_ [[-access] {read-only|write-only|all}] [[-permission] {allow-only|deny-only|all}]`

* `-access` - specifica il tipo di accesso all'evento da sottoporre a verifica: `read-only`, `write-only` oppure `all` (il valore predefinito è `all`).
* `-permission` - specifica il tipo di autorizzazione all'evento da sottoporre a verifica: `allow-only`, `deny-only` oppure `all` (il valore predefinito è `all`).


.Esempio
Nell'esempio seguente viene creata una configurazione di controllo del bucket che registra solo gli eventi consentiti con accesso in sola lettura:

`cluster1::> vserver object-store-server audit event-selector create -vserver vs1 -bucket test-bucket -access read-only -permission allow-only`
