---
permalink: s3-audit/show-config-task.html 
sidebar: sidebar 
keywords: s3 audit, show, display 
summary: Questa attività spiega come mostrare le informazioni sugli audit s3 con la CLI. 
---
= Mostrare le configurazioni di controllo S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una volta completata la configurazione di controllo, è possibile verificare che il controllo sia configurato correttamente e sia attivato. È inoltre possibile visualizzare informazioni su tutte le configurazioni di controllo dell'archivio di oggetti nel cluster.

.A proposito di questa attività
È possibile visualizzare informazioni sulle configurazioni di controllo bucket e SVM.

* Bucket – utilizzare `vserver object-store-server audit event-selector show` comando
+
Senza alcun parametro, il comando visualizza le seguenti informazioni sui bucket in tutte le SVM del cluster con configurazioni di controllo degli archivi di oggetti:

+
** Nome SVM
** Nome bucket
** Valori di accesso e autorizzazione


* SVM: Utilizzare `vserver object-store-server audit show` comando
+
Senza alcun parametro, il comando visualizza le seguenti informazioni su tutte le SVM nel cluster con configurazioni di controllo degli archivi di oggetti:

+
** Nome SVM
** Stato di audit
** Directory di destinazione




È possibile specificare `-fields` parametro per specificare le informazioni di configurazione di controllo da visualizzare.

.Procedura
Mostra informazioni sulle configurazioni di controllo S3:

[cols="2,4"]
|===
| Se si desidera modificare la configurazione per... | Inserisci... 


| Bucket | `vserver object-store-server audit event-selector show [-vserver _svm_name_] [_parameters_]` 


| SVM  a| 
`vserver object-store-server audit show [-vserver _svm_name_] [_parameters_]`

|===
.Esempi
Nell'esempio riportato di seguito vengono visualizzate le informazioni relative a un singolo bucket:

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1 -bucket test-bucket
     Vserver     Bucket     Access          Permission
     ----------- ---------- --------------- ----------
     vs1         bucket1    read-only       allow-only
----
Nell'esempio riportato di seguito vengono visualizzate le informazioni relative a tutti i bucket di una SVM:

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1

     Vserver           :vs1
     Bucket            :test-bucket
     Access            :all
     Permission        :all
----
Nell'esempio riportato di seguito vengono visualizzati il nome, lo stato di controllo, i tipi di evento, il formato del registro e la directory di destinazione di tutte le SVM.

[listing]
----
cluster1::> vserver object-store-server audit show

Vserver     State  Event Types Log Format Target Directory
----------- ------ ----------- ---------- --------------------
vs1         false  data        json       /audit_log
----
Nell'esempio seguente vengono visualizzati i nomi e i dettagli SVM relativi al registro di controllo per tutte le SVM.

[listing]
----
cluster1::> vserver object-store-server audit show -log-save-details

                  Rotation                           Rotation
      Vserver     File Size Rotation Schedule        Limit
      ----------- --------- ------------------------ --------
      vs1         100MB     -                        0
----
Nell'esempio riportato di seguito vengono visualizzate tutte le informazioni di configurazione dell'audit relative a tutte le SVM.

[listing]
----
cluster1::> vserver object-store-server audit show -instance

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: data
                          Log Format: json
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 0
                  Log Retention Time: 0s
----