---
sidebar: sidebar 
permalink: s3-snapmirror/requirements-cloud-targets-concept.html 
keywords: requirements for cloud target relationships 
summary: Assicurati che gli ambienti di origine e di destinazione soddisfino i requisiti per la protezione di backup di S3 SnapMirror verso le destinazioni cloud. 
---
= Requisiti per le relazioni di destinazione del cloud
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:toc-position: content


[role="lead"]
Assicurati che gli ambienti di origine e di destinazione soddisfino i requisiti per la protezione di backup di S3 SnapMirror verso le destinazioni cloud.

Per accedere al bucket di dati, è necessario disporre di credenziali account valide con il provider dell'archivio di oggetti.

Le interfacce di rete tra cluster e un IPSpace devono essere configurati sul cluster prima che il cluster possa connettersi a un archivio di oggetti cloud. È necessario creare interfacce di rete del cluster di invio su ciascun nodo per trasferire senza problemi i dati dallo storage locale all'archivio di oggetti cloud.

Per gli obiettivi StorageGRID, è necessario conoscere le seguenti informazioni:

* Nome del server, espresso come nome di dominio completo (FQDN) o indirizzo IP
* nome bucket; il bucket deve già esistere
* tasto di accesso
* chiave segreta


Inoltre, il certificato CA utilizzato per firmare il certificato del server StorageGRID deve essere installato sulla macchina virtuale di storage amministrativa del cluster ONTAP S3 utilizzando `security certificate install command`. Per ulteriori informazioni, vedere link:../fabricpool/install-ca-certificate-storagegrid-task.html["Installazione di un certificato CA"] Se si utilizza StorageGRID.

Per i target AWS S3, è necessario conoscere le seguenti informazioni:

* Nome del server, espresso come nome di dominio completo (FQDN) o indirizzo IP
* nome bucket; il bucket deve già esistere
* tasto di accesso
* chiave segreta


Il server DNS per la VM di storage amministrativa del cluster ONTAP deve essere in grado di risolvere gli FQDN (se utilizzati) in indirizzi IP.
