---
permalink: nvme/manage-automated-discovery.html 
sidebar: sidebar 
keywords: nvme, tcp, nvme/tcp, disable, automated, discovery, controllers 
summary: A partire da ONTAP 9.13.1, il rilevamento host dei controller che utilizzano il protocollo NVMe/TCP è automatizzato per impostazione predefinita nei fabric basati su IP.  
---
= Gestire il rilevamento automatico degli host dei controller NVMe/TCP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.14.1, il rilevamento host dei controller che utilizzano il protocollo NVMe/TCP è automatizzato per impostazione predefinita nei fabric basati su IP.



== Rilevamento automatico dell'host dei controller NVMe/TCP

Se in precedenza è stato disattivato il rilevamento automatico dell'host, ma le esigenze sono state modificate, è possibile riattivarlo.

.Fasi
. Accedere alla modalità avanzata dei privilegi:
+
[source, cli]
----
set -privilege advanced
----
. Attivare il rilevamento automatico:
+
[source, cli]
----
vserver nvme modify -vserver <vserver_name> -mdns-service-discovery-enabled true
----
. Verificare che il rilevamento automatico dei controller NVMe/TCP sia attivato.
+
[source, cli]
----
vserver nvme show
----




== Disattiva il rilevamento automatico degli host dei controller NVMe/TCP

Se non è necessario che l'host rilevi automaticamente i controller NVMe/TCP e rilevi traffico multicast indesiderato sulla rete, disattivare questa funzionalità.

.Fasi
. Accedere alla modalità avanzata dei privilegi:
+
[source, cli]
----
set -privilege advanced
----
. Disattiva rilevamento automatico:
+
[source, cli]
----
vserver nvme modify -vserver <vserver_name> -mdns-service-discovery-enabled false
----
. Verificare che il rilevamento automatico dei controller NVMe/TCP sia disattivato.
+
[source, cli]
----
vserver nvme show
----

