= Considerazione di ONTAP 9.11.1RC1
:allow-uri-read: 




== Considerazione di ONTAP 9.11.1RC1

A causa di una modifica apportata alla versione 9.11.1RC1 di ONTAP, la modalità di gestione della conformità FIPS 140-2 non utilizza più il modulo software validato FIPS 140-2.

ONTAP 9.11.1RC1 ha aggiornato la versione di OpenSSL utilizzata per le connessioni dei piani di gestione e controllo per HTTPS. Questa versione di OpenSSL (OpenSSL 3.x FIPS Provider) non ha ancora completato il processo di convalida del programma di convalida del modulo crittografico FIPS 140-2 (CMVP).

Quando la modalità di compliance FIPS è attivata, gli algoritmi di crittografia utilizzati per le connessioni HTTPS sono identici agli algoritmi del provider FIPS OpenSSL Project OpenSSL 3.x emessi nel certificato A1938 del programma di convalida degli algoritmi di crittografia (CAVP). *Questa modifica riguarda solo i sistemi ONTAP configurati in modalità di conformità FIPS.*

Questo problema verrà risolto una volta che il modulo OpenSSL aggiornato presente in ONTAP 9.11.1RC1 completerà la convalida FIPS 140-2 con NIST. Se l'ambiente richiede un piano di controllo per la gestione del cluster ONTAP eseguito con un modulo validato FIPS 140-2 CMVP, si consiglia di non eseguire l'aggiornamento a 9.11.1RC1.

Ciò non influisce sulle tecnologie di crittografia NetApp a riposo come NSE, NVE e NAE, in quanto tali funzionalità utilizzano un modulo crittografico diverso da quello fornito da OpenSSL in ONTAP.

Per ulteriori informazioni, vedere link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["L'aggiornamento a ONTAP 9.11.1RC1 comporta una configurazione di gestione della conformità FIPS 140-2 non validata"^].
