= Requisiti
:allow-uri-read: 


[role="lead"]
TLS consente comunicazioni di rete crittografate con una protezione equivalente a e meno complessità rispetto a Kerberos e IPsec. In qualità di amministratore, è possibile attivare, configurare e disattivare TLS per garantire una sicurezza elevata con le connessioni NFSv3 e NFSv4.x utilizzando Gestione di sistema, l'interfaccia CLI di ONTAP o l'API REST di ONTAP.


NOTE: NFS over TLS è disponibile in ONTAP 9.15.1 come anteprima pubblica. Come offerta di anteprima, NFS su TLS non è supportato per i carichi di lavoro di produzione in ONTAP 9.15.1.

ONTAP utilizza TLS 1,3 per connessioni NFS su TLS.



== Requisiti

NFS su TLS richiede certificati X,509. È possibile creare un certificato server con firma CA nel cluster ONTAP oppure installare un certificato utilizzato direttamente dal servizio NFS. I certificati devono soddisfare le seguenti linee guida:

* Ciascun certificato deve essere configurato con il nome di dominio completo (FQDN) del server NFS (la LIF dati su cui verrà attivato/configurato TLS) come nome comune (CN).
* Ciascun certificato deve essere configurato con l'indirizzo IP o il FQDN del server NFS (o entrambi) come nome alternativo soggetto (SAN). Se sono configurati sia l'indirizzo IP che l'FQDN, i client NFS possono connettersi utilizzando l'indirizzo IP o l'FQDN.
* È possibile installare più certificati di servizio NFS per la stessa LIF, ma solo uno di essi può essere in uso alla volta come parte della configurazione NFS TLS.

