---
sidebar: sidebar 
permalink: networking/add_or_remove_ports_from_a_broadcast_domain97.html 
keywords: adding, add, create, creating, remove, removing, delete, deleting, port, broadcast, domain, reachability, repair, physical, switch, configuration, manually add or remove ports from a broadcast domain, network port broadcast-domain add-ports, network port broadcast-domain remove-ports, examples of adding and removing ports 
summary: 'L"aggiunta e la rimozione manuale delle porte dai domini di broadcast non sono richieste o consigliate' 
---
= Aggiungere o rimuovere porte da un dominio di broadcast
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiungere porte di rete durante la creazione iniziale di un dominio di trasmissione oppure aggiungere o rimuovere porte da un dominio di trasmissione già esistente. Ciò consente di utilizzare in modo efficiente tutte le porte del cluster.

.Prima di iniziare
* Le porte che si intende aggiungere a un dominio di trasmissione non devono appartenere a un altro dominio di trasmissione.
* Le porte che già appartengono a un gruppo di interfacce non possono essere aggiunte singolarmente a un dominio di trasmissione.


.A proposito di questa attività
Quando si aggiungono e rimuovono le porte di rete, si applicano le seguenti regole:

|===


| Quando si aggiungono porte... | Durante la rimozione delle porte... 


| Le porte possono essere porte di rete, VLAN o gruppi di interfacce (ifgrps). | N/A. 


| Le porte vengono aggiunte al gruppo di failover definito dal sistema del dominio di trasmissione. | Le porte vengono rimosse da tutti i gruppi di failover nel dominio di trasmissione. 


| La MTU delle porte viene aggiornata al valore MTU impostato nel dominio di trasmissione. | L'MTU delle porte non cambia. 


| L'IPSpace delle porte viene aggiornato al valore IPSpace del dominio di trasmissione. | Le porte vengono spostate in IPSpace predefinito senza attributi di dominio di trasmissione. 
|===

NOTE: Se si rimuove l'ultima porta membro di un gruppo di interfacce utilizzando `network port ifgrp remove-port` determina la rimozione della porta del gruppo di interfacce dal dominio di trasmissione, in quanto non è consentita una porta vuota del gruppo di interfacce in un dominio di trasmissione.

.Fasi
. Consente di visualizzare le porte attualmente assegnate o non assegnate a un dominio di trasmissione utilizzando `network port show` comando.
. Aggiungere o rimuovere le porte di rete dal dominio di trasmissione:
+
[cols="40,60"]
|===


| Se si desidera... | Utilizzare... 


 a| 
Aggiungere porte a un dominio di broadcast
 a| 
`network port broadcast-domain add-ports`



 a| 
Rimuovere le porte da un dominio di broadcast
 a| 
`network port broadcast-domain remove-ports`

|===


Per ulteriori informazioni su questi comandi, vedere http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^].



== Esempi di aggiunta e rimozione di porte

Il seguente comando aggiunge la porta e0g sul cluster di nodi 1-01 e la porta e0g sul cluster di nodi 1-02 al dominio di trasmissione bcast1 nell'IPSpace predefinito:

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain bcast1 -ports cluster-1-01:e0g,cluster1-02:e0g`

Il seguente comando aggiunge due porte del cluster al dominio di trasmissione Cluster nell'IPSpace del cluster:

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain Cluster -ports cluster-2-03:e0f,cluster2-04:e0f -ipspace Cluster`

Il seguente comando rimuove la porta e0e sul cluster di nod1-01 dal dominio di broadcast cast1 nell'IPSpace predefinito:

`cluster-1::> network port broadcast-domain remove-ports -broadcast-domain bcast1 -ports cluster-1-01:e0e`
