---
sidebar: sidebar 
permalink: networking/balance_network_loads_to_optimize_user_traffic_@cluster_administrators_only@_overview.html 
keywords: balance, balanced, load, utilization, usage, lif, port, cluster, performance 
summary: Configurare il cluster per soddisfare le richieste dei client da LIF caricate in modo appropriato. 
---
= Panoramica della rete Balance
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile configurare il cluster per soddisfare le richieste dei client da LIF caricate in modo appropriato. Ciò comporta un utilizzo più bilanciato di LIF e porte, che a sua volta consente migliori performance del cluster.

Il bilanciamento del carico DNS consente di selezionare una LIF di dati opportunamente caricata e di bilanciare il traffico di rete dell'utente su tutte le porte disponibili (fisiche, gruppi di interfacce e VLAN).

Con il bilanciamento del carico DNS, i LIF sono associati alla zona di bilanciamento del carico di una SVM. Un server DNS a livello di sito è configurato per inoltrare tutte le richieste DNS e restituire il LIF meno caricato in base al traffico di rete e alla disponibilità delle risorse delle porte (utilizzo della CPU, throughput, connessioni aperte e così via). Il bilanciamento del carico DNS offre i seguenti vantaggi:

* Nuove connessioni client bilanciate tra le risorse disponibili.
* Non è richiesto alcun intervento manuale per decidere quali LIF utilizzare durante il montaggio di una specifica SVM.
* Il bilanciamento del carico DNS supporta NFSv3, NFSv4, NFSv4,1, SMB 2,0, SMB 2,1, SMB 3,0 e S3.

