---
sidebar: sidebar 
permalink: networking/change_the_mtu_value_for_ports_in_a_broadcast_domain.html 
keywords: modify, modifying, mtu, mtu_value, change, changing, broadcast, domain, ports, port, change the mtu value for ports in a broadcast domain 
summary: Modificare il valore MTU per un dominio di trasmissione per modificare tale valore per tutte le porte nel dominio di trasmissione 
---
= Modificare il valore MTU per le porte in un dominio di broadcast ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile modificare il valore MTU per un dominio di broadcast per modificare il valore MTU per tutte le porte in tale dominio di broadcast. Questa operazione può essere eseguita per supportare le modifiche della topologia apportate alla rete.


NOTE: La procedura per la modifica del valore MTU per le porte del dominio di trasmissione è diversa in ONTAP 9,7 e nelle versioni precedenti. Se è necessario modificare il valore MTU per le porte del dominio di trasmissione su una rete che esegue ONTAP 9,7 e versioni precedenti, fare riferimento alla link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/change_the_mtu_value_for_ports_in_a_broadcast_domain97.html["Modifica del valore MTU per le porte in un dominio di broadcast (ONTAP 9,7 e versioni precedenti)"^].

[role="tabbed-block"]
====
.System Manager
--
A partire da ONTAP 9.12.0, puoi utilizzare System Manager per modificare il valore MTU per un dominio broadcast per cambiare il valore MTU per tutte le porte in quel dominio broadcast.

.Fasi
. Seleziona *Network > Broadcast Domains*.
. Nella sezione *Broadcast Domains*, seleziona il nome del broadcast domain per cui desideri modificare il valore MTU.
. Verrà visualizzato un messaggio che chiede di confermare la modifica del valore MTU per tutte le porte nel dominio di broadcast. Fare clic su *Yes* per procedere con la modifica.
. Modifica il valore MTU secondo necessità e salva le modifiche.
+
Il sistema applica il nuovo valore MTU a tutte le porte nel dominio di broadcast, il che causa una breve interruzione del traffico su tali porte.



--
.CLI
--
.Prima di iniziare
Il valore MTU deve corrispondere a tutti i dispositivi connessi a tale rete Layer 2, ad eccezione del traffico di gestione della porta e0M.

.A proposito di questa attività
La modifica del valore MTU provoca una breve interruzione del traffico sulle porte interessate. Il sistema visualizza un messaggio a cui è necessario rispondere con *y* per apportare la modifica al valore MTU.

.Fase
Modificare il valore MTU per tutte le porte in un dominio di broadcast:

[listing]
----
network port broadcast-domain modify -broadcast-domain <broadcast_domain_name> -mtu <mtu_value> [-ipspace <ipspace_name>]
----
Dove:

* `broadcast_domain` è il nome del dominio di trasmissione.
* `mtu` È la dimensione MTU per i pacchetti IP; 1500 e 9000 sono valori tipici.
* `ipspace` è il nome dell'IPspace in cui risiede questo dominio broadcast. L'IPspace "Default" viene utilizzato a meno che non si specifichi un valore per questa opzione.
+
Il seguente comando modifica l'MTU a 9000 per tutte le porte nel dominio broadcast bcast1:

+
[listing]
----
network port broadcast-domain modify -broadcast-domain <Default-1> -mtu < 9000 >
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: <y>
----


--
====
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-modify.html["porta di rete modifica del dominio di broadcast"^]

