---
sidebar: sidebar 
permalink: networking/commands_for_managing_failover_groups_and_policies.html 
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete 
summary: Gestire i gruppi di failover 
---
= Comandi ONTAP per la gestione di gruppi e policy di failover
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `network interface failover-groups` comandi per gestire i gruppi di failover. Si utilizza `network interface modify` Comando per gestire i gruppi di failover e le policy di failover applicate a una LIF.

|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Aggiungere porte di rete a un gruppo di failover
 a| 
`network interface failover-groups add-targets`



 a| 
Rimuovere le porte di rete da un gruppo di failover
 a| 
`network interface failover-groups remove-targets`



 a| 
Modificare le porte di rete in un gruppo di failover
 a| 
`network interface failover-groups modify`



 a| 
Visualizza i gruppi di failover correnti
 a| 
`network interface failover-groups show`



 a| 
Configurare il failover su una LIF
 a| 
`network interface modify -failover-group -failover-policy`



 a| 
Visualizzare il gruppo di failover e la policy di failover utilizzati da ciascun LIF
 a| 
`network interface show -fields failover-group, failover-policy`



 a| 
Rinominare un gruppo di failover
 a| 
`network interface failover-groups rename`



 a| 
Eliminare un gruppo di failover
 a| 
`network interface failover-groups delete`

|===

NOTE: La modifica di un gruppo di failover in modo che non fornisca una destinazione di failover valida per qualsiasi LIF nel cluster può causare un'interruzione quando un LIF tenta di eseguire il failover.

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network-interface-failover["failover-interfaccia-rete"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["modifica dell'interfaccia di rete"^]

