---
sidebar: sidebar 
permalink: networking/configure_dns_for_host-name_resolution.html 
keywords: configure, configuring, configuration, setup, set, setting, dns, local, remote, host, name, host-name, resolution, configure dns for host-name resolution, nsswitch.conf, configure an svm and data lifs for host-name resolution using an external dns server, vserver services name-service dns, vserver services name-service dns create, network interface modify -lif lifname -dns-zone, network interface create -lif lifname -dns-zone, vserver services name-service dns check, configure the name service switch table for host-name resolution 
summary: 'Utilizzare il DNS per accedere a fonti locali o remote per ottenere informazioni sull"host' 
---
= Configurare il DNS per la risoluzione del nome host
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il DNS viene utilizzato per accedere a fonti locali o remote per ottenere informazioni sull'host. È necessario configurare il DNS per accedere a una o a entrambe queste origini.

ONTAP deve essere in grado di cercare le informazioni dell'host per fornire un accesso appropriato ai client. È necessario configurare i name service per consentire a ONTAP di accedere ai servizi DNS locali o esterni per ottenere le informazioni sull'host.

ONTAP memorizza le informazioni di configurazione del name service in una tabella equivalente a `/etc/nsswitch.conf` File su sistemi UNIX.



== Configurazione di una SVM e di una LIF di dati per la risoluzione del nome host utilizzando un server DNS esterno

È possibile utilizzare `vserver services name-service dns` Per abilitare il DNS su una SVM e configurarlo per l'utilizzo del DNS per la risoluzione dei nomi host. I nomi host vengono risolti utilizzando server DNS esterni.

.Prima di iniziare
Per la ricerca dei nomi host, è necessario che sia disponibile un server DNS a livello di sito.

È necessario configurare più server DNS per evitare un singolo punto di errore. Il `vserver services name-service dns create` Viene visualizzato un messaggio di avviso se si immette un solo nome server DNS.

.A proposito di questa attività
Vedere xref:configure_dynamic_dns_services.html[Configurare i servizi DNS dinamici] Per ulteriori informazioni sulla configurazione del DNS dinamico su SVM.

.Fasi
. Abilitare il DNS sulla SVM:
+
....
vserver services name-service dns create -vserver vserver_name -domains domain_name - name-servers ip_addresses -state enabled
....
+
Il seguente comando abilita i server DNS esterni su SVM vs1:

+
....
vserver services name-service dns create -vserver <vs1.example.com> -domains <example.com> -name-servers <192.0.2.201,192.0.2.202> -state <enabled>
....
+

NOTE: Il comando di creazione dns dei servizi vserver esegue una convalida automatica della configurazione e segnala un messaggio di errore se ONTAP non è in grado di contattare il server dei nomi.



. Convalidare lo stato dei server dei nomi utilizzando `vserver services name-service dns check` comando.
+
....
vserver services name-service dns check -vserver vs1.example.com
VserverName       Server     Status    Status Details
----------------  ---------- -------   --------------------------
vs1.example.com   10.0.0.50  up        Response time (msec): 2
vs1.example.com   10.0.0.51  up        Response time (msec): 2
....


Per informazioni sulle politiche di servizio relative al DNS, vedere link:lifs_and_service_policies96.html["LIF e policy di servizio in ONTAP 9.6 e versioni successive"].



== Configurare la tabella Name Service Switch per la risoluzione dei nomi host

Per consentire a ONTAP di consultare il servizio di nomi locale o esterno per recuperare le informazioni sull'host, è necessario configurare correttamente la tabella degli switch del servizio di nomi.

.Prima di iniziare
È necessario decidere quale name service utilizzare per il mapping degli host nel proprio ambiente.

.Fasi
. Aggiungere le voci necessarie alla tabella dei name service switch:
+
....
vserver services name-service <ns-switch> create -vserver <vserver_name> -database <database_name> -source <source_names>
....
. Verificare che la tabella name service switch contenga le voci previste nell'ordine desiderato:
+
....
vserver services name-service <ns-switch> show -vserver <vserver_name>
....


.Esempio
Nell'esempio riportato di seguito viene creata una voce nella tabella name service switch per SVM vs1 in modo da utilizzare prima il file hosts locale e poi un server DNS esterno per risolvere i nomi host:

....
vserver services name-service ns-switch create -vserver vs1 -database hosts -sources files dns
....