---
sidebar: sidebar 
permalink: networking/configure_dns_services_auto.html 
keywords: dns, service, services, configuration, configure, configuring, set, up, setup, nfs, smb, cifs, active, directory, statistics, configure dns services, configure dns services for the svm before creating an nfs or smb server, vserver services name-service, configure dynamic dns on the svm, vserver-fqdn 
summary: Configurare i servizi DNS per SVM prima di creare un server NFS o SMB 
---
= Configurare i servizi DNS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario configurare i servizi DNS per SVM prima di creare un server NFS o SMB. In genere, i server dei nomi DNS sono i server DNS integrati in Active Directory per il dominio a cui si aggiungerà il server NFS o SMB.

.A proposito di questa attività
I server DNS integrati in Active Directory contengono i record di posizione del servizio (SRV) per i server LDAP e dei controller di dominio. Se SVM non riesce a trovare i server LDAP e i controller di dominio di Active Directory, la configurazione del server NFS o SMB non riesce.

Le SVM utilizzano il database ns-switch dei servizi dei nomi host per determinare i servizi dei nomi da utilizzare e in quale ordine quando si cercano informazioni sugli host. I due name service supportati per il database host sono file e dns.

Prima di creare il server SMB, è necessario assicurarsi che il dns sia una delle origini.


NOTE: Per visualizzare le statistiche per i servizi dei nomi DNS per il processo mgwd e il processo SecD, utilizzare l'interfaccia utente Statistics.

.Fasi
. Determinare la configurazione corrente per il database dei servizi di nomi host. In questo esempio, il database del servizio nomi host utilizza le impostazioni predefinite.
+
`vserver services name-service _ns-switch_ show -vserver _vs1_ -database _hosts_`

+
....
Vserver: vs1
Name Service Switch Database: hosts
Vserver: vs1 Name Service Switch Database: hosts
Name Service Source Order: files, dns
....
. Eseguire le seguenti operazioni, se necessario.
+
.. Aggiungere il servizio nome DNS al database del servizio nome host nell'ordine desiderato oppure riordinare le origini.
+
In questo esempio, il database degli host è configurato per l'utilizzo di DNS e file locali in tale ordine.

+
`vserver services name-service _ns-switch_ modify -vserver _vs1_ -database _hosts_ -sources _dns,files_`

.. Verificare che la configurazione dei name service sia corretta.
+
`vserver services name-service _ns-switch_ show -vserver _vs1_ -database _hosts_`

+
....
Vserver: vs1
Name Service Switch Database: hosts
Name Service Source Order: dns, files
....


. Configurare i servizi DNS.
+
`vserver services name-service dns create -vserver _vs1_ -domains _example.com,example2.com_ -name-servers _10.0.0.50,10.0.0.51_`

+

NOTE: Il comando di creazione dns dei servizi vserver esegue una convalida automatica della configurazione e segnala un messaggio di errore se ONTAP non è in grado di contattare il server dei nomi.

. Verificare che la configurazione DNS sia corretta e che il servizio sia attivato.
+
....
Vserver: vs1
Domains: example.com, example2.com Name Servers: 10.0.0.50, 10.0.0.51
Enable/Disable DNS: enabled Timeout (secs): 2
Maximum Attempts: 1
....
. Convalidare lo stato dei server dei nomi.
+
`vserver services name-service dns check -vserver _vs1_`



....
Vserver  Name Server  Status  Status Details
vs1      10.0.0.50    up      Response time (msec): 2
vs1      10.0.0.51    up      Response time (msec): 2
....


== Configurare il DNS dinamico sulla SVM

Se si desidera che il server DNS integrato in Active Directory registri dinamicamente i record DNS di un server NFS o SMB in DNS, è necessario configurare il DNS dinamico (DDNS) su SVM.

.Prima di iniziare
I name service DNS devono essere configurati su SVM. Se si utilizza un DDNS sicuro, è necessario utilizzare i server dei nomi DNS integrati in Active Directory e creare un server NFS o SMB o un account Active Directory per SVM.

.A proposito di questa attività
Il nome di dominio completo (FQDN) specificato deve essere univoco:

Il nome di dominio completo (FQDN) specificato deve essere univoco:

* Per NFS, il valore specificato in `-vserver-fqdn` come parte di `vserver services name-service dns dynamic-update` Command diventa il nome FQDN registrato per i LIF.
* Per SMB, i valori specificati come nome NetBIOS del server CIFS e nome di dominio completo del server CIFS diventano FQDN registrato per i LIF. Non è configurabile in ONTAP. Nel seguente scenario, l'FQDN LIF è "CIFS_VS1.EXAMPLE.COM":
+
....
cluster1::> cifs server show -vserver vs1

                                          Vserver: vs1
                         CIFS Server NetBIOS Name: CIFS_VS1
                    NetBIOS Domain/Workgroup Name: EXAMPLE
                      Fully Qualified Domain Name: EXAMPLE.COM
                              Organizational Unit: CN=Computers
Default Site Used by LIFs Without Site Membership:
                                   Workgroup Name: -
                                   Kerberos Realm: -
                             Authentication Style: domain
                CIFS Server Administrative Status: up
                          CIFS Server Description:
                          List of NetBIOS Aliases: -
....



NOTE: Per evitare un errore di configurazione di un FQDN SVM non conforme alle regole RFC per gli aggiornamenti DDNS, utilizzare un nome FQDN compatibile con RFC. Per ulteriori informazioni, vedere link:https://tools.ietf.org/html/rfc1123["RFC 1123"].

.Fasi
. Configurare DDNS su SVM:
+
`vserver services name-service dns dynamic-update modify -vserver _vserver_name_ -is- enabled _true_ [-use-secure {true|false} -vserver-fqdn _FQDN_used_for_DNS_updates_`

+
`vserver services name-service dns dynamic-update modify -vserver _vs1_ -is-enabled _true_ - use-secure _true_ -vserver-fqdn _vs1.example.com_`

+
Gli asterischi non possono essere utilizzati come parte del FQDN personalizzato. Ad esempio, `*.netapp.com` non è valido.

. Verificare che la configurazione DDNS sia corretta:
+
`vserver services name-service dns dynamic-update show`

+
....
Vserver  Is-Enabled Use-Secure Vserver FQDN      TTL
-------- ---------- ---------- ----------------- -------
vs1      true       true       vs1.example.com   24h
....

