---
sidebar: sidebar 
permalink: networking/configure_failover_groups_and_policies_for_lifs_overview.html 
keywords: lif, failover, fail, over, target, automatic, automatically, port, link, failure, group, broadcast, domain, lif failover is the automatic migration of a lif to a different network port in response to a link failure, configure failover groups and policies for lifs overview, network interface show -failover 
summary: Il failover LIF è la migrazione automatica di una LIF a una porta di rete diversa in risposta a un errore di collegamento 
---
= Ottieni informazioni sul failover LIF nelle reti ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il failover LIF si riferisce alla migrazione automatica di una LIF a una porta di rete diversa in risposta a un errore di collegamento sulla porta corrente della LIF. Si tratta di un componente chiave per fornire alta disponibilità per le connessioni alle SVM. La configurazione del failover LIF comporta la creazione di un gruppo di failover, la modifica della LIF per l'utilizzo del gruppo di failover e la specifica di una policy di failover.

Un gruppo di failover contiene un set di porte di rete (porte fisiche, VLAN e gruppi di interfacce) da uno o più nodi in un cluster. Le porte di rete presenti nel gruppo di failover definiscono le destinazioni di failover disponibili per LIF. A un gruppo di failover possono essere assegnate le LIF di gestione del cluster, dei nodi, dell'intercluster e dei dati NAS.


IMPORTANT: Quando una LIF viene configurata senza una destinazione di failover valida, si verifica un'interruzione quando la LIF tenta di eseguire il failover. È possibile utilizzare il `network interface show -failover` comando per verificare la configurazione di failover. Ulteriori informazioni su `network interface show` nella link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Riferimento al comando ONTAP"^].

Quando si crea un dominio di broadcast, viene creato automaticamente un gruppo di failover con lo stesso nome che contiene le stesse porte di rete. Questo gruppo di failover viene gestito automaticamente dal sistema, il che significa che quando le porte vengono aggiunte o rimosse dal dominio di broadcast, vengono automaticamente aggiunte o rimosse da questo gruppo di failover. Questo è un'efficienza per gli amministratori che non desiderano gestire i propri gruppi di failover.
