---
sidebar: sidebar 
permalink: networking/configure_dynamic_dns_services.html 
keywords: dns, service, services, configuration, configure, configuring, set, up, setup, nfs, smb, cifs, active, directory, statistics, configure dns services for the svm before creating an nfs or smb server, ddns, vserver services name-service dns dynamic-update modify, vserver services name-service dns dynamic-update show 
summary: Configurare i servizi DNS per SVM prima di creare un server NFS o SMB 
---
= Configurare i servizi DNS dinamici
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si desidera che il server DNS integrato in Active Directory registri dinamicamente i record DNS di un server NFS o SMB in DNS, è necessario configurare il DNS dinamico (DDNS) su SVM.

.Prima di iniziare
I name service DNS devono essere configurati su SVM. Se si utilizza un DDNS sicuro, è necessario utilizzare i server dei nomi DNS integrati in Active Directory e creare un server NFS o SMB o un account Active Directory per SVM.

.A proposito di questa attività
L'FQDN specificato deve essere univoco.


NOTE: Per evitare un errore di configurazione di un FQDN SVM non conforme alle regole RFC per gli aggiornamenti DDNS, utilizzare un nome FQDN compatibile con RFC.

.Fasi
. Configurare DDNS su SVM:
+
`vserver services name-service dns dynamic-update modify -vserver _vserver_name_ -is- enabled _true_ [-use-secure {true|false} -vserver-fqdn _FQDN_used_for_DNS_updates_`

+
`vserver services name-service dns dynamic-update modify -vserver _vs1_ -is-enabled _true_ - use-secure _true_ -vserver-fqdn _vs1.example.com_`

+
Gli asterischi non possono essere utilizzati come parte del FQDN personalizzato. Ad esempio, `*.netapp.com` non è valido.

. Verificare che la configurazione DDNS sia corretta:
+
`vserver services name-service dns dynamic-update show`

+
....
Vserver  Is-Enabled Use-Secure Vserver FQDN      TTL
-------- ---------- ---------- ----------------- -------
vs1      true       true       vs1.example.com   24h
....

