---
sidebar: sidebar 
permalink: networking/create_a_broadcast_domain_reference.html 
keywords: create, creation, creating, add, adding, broadcast, domain, create a broadcast domain, broadcast domains group network ports in the cluster that belong to the same layer 2 network, network port broadcast-domain remove-ports 
summary: I domini di broadcast raggruppano le porte di rete nel cluster che appartengono alla stessa rete Layer 2 
---
= Creare un dominio di broadcast
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Creare un dominio di broadcast per raggruppare le porte di rete nel cluster che appartengono alla stessa rete Layer 2. Le porte possono quindi essere utilizzate dalle SVM.

.Prima di iniziare
Le porte che si desidera aggiungere al dominio di trasmissione non devono appartenere a un altro dominio di trasmissione.

.A proposito di questa attività
* Tutti i nomi di dominio di trasmissione devono essere univoci all'interno di un IPSpace.
* Le porte aggiunte a un dominio di broadcast possono essere porte di rete fisiche, VLAN o gruppi di interfacce (ifgrps).
* Se le porte che si desidera utilizzare appartengono a un altro dominio di trasmissione, ma non sono utilizzate, utilizzare `network port broadcast-domain remove-ports` per rimuovere le porte dal dominio di trasmissione esistente.
* Le MTU delle porte aggiunte a un dominio di trasmissione vengono aggiornate al valore MTU impostato nel dominio di trasmissione.
* Il valore MTU deve corrispondere a tutti i dispositivi connessi a tale rete Layer 2, ad eccezione del traffico di gestione della porta e0M.
* Se non si specifica un nome IPSpace, il dominio di trasmissione viene creato nell'IPSpace "predefinito".


Per semplificare la configurazione del sistema, viene creato automaticamente un gruppo di failover con lo stesso nome che contiene le stesse porte.

.Fasi
. Visualizzare le porte non attualmente assegnate a un dominio di trasmissione:
+
`network port show`

+
Se il display è grande, utilizzare `network port show -broadcast-domain` per visualizzare solo le porte non assegnate.

. Creare un dominio di broadcast:
+
`network port broadcast-domain create -broadcast-domain _broadcast_domain_name_ -mtu _mtu_value_ [-ipspace _ipspace_name_] [-ports _ports_list_]`

+
** `_broadcast_domain_name_` è il nome del dominio di trasmissione che si desidera creare.
** `_mtu_value_` È la dimensione MTU per i pacchetti IP; 1500 e 9000 sono valori tipici.
+
Questo valore viene applicato a tutte le porte aggiunte a questo dominio di trasmissione.

** `_ipspace_name_` È il nome dell'IPSpace a cui verrà aggiunto questo dominio di trasmissione.
+
L'IPSpace predefinito viene utilizzato a meno che non si specifichi un valore per questo parametro.

** `_ports_list_` è l'elenco delle porte che verranno aggiunte al dominio di trasmissione.
+
Le porte vengono aggiunte nel formato `_node_name:port_number_`, ad esempio, `node1:e0c`.



. Verificare che il dominio di trasmissione sia stato creato come desiderato:
`network port show -instance -broadcast-domain _new_domain_`


.Esempio
Il seguente comando crea il dominio di trasmissione bcast1 nell'IPSpace predefinito, imposta la MTU su 1500 e aggiunge quattro porte:

`network port broadcast-domain create -broadcast-domain _bcast1_ -mtu _1500_ -ports _cluster1-01:e0e,cluster1-01:e0f,cluster1-02:e0e,cluster1-02:e0f_`

.Al termine
È possibile definire il pool di indirizzi IP che saranno disponibili nel dominio di trasmissione creando una subnet oppure assegnare SVM e interfacce a IPSpace in questo momento. Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["Peering di cluster e SVM"].

Se è necessario modificare il nome di un dominio di trasmissione esistente, utilizzare `network port broadcast-domain rename` comando.
