---
sidebar: sidebar 
permalink: networking/delete_a_lif.html 
keywords: 'remove a lif, destroy a lif, delete, deleting, remove, removing, logical, interface, lif, delete a lif, delete a network interface (lif) that is no longer required, network interface delete' 
summary: 'Eliminare un"interfaccia di rete (LIF) non più richiesta' 
---
= Eliminare una LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile eliminare un'interfaccia di rete (LIF) non più richiesta.

.Prima di iniziare
I LIF da eliminare non devono essere in uso.

.Fasi
. Contrassegnare i file LIF che si desidera eliminare come amministrativamente bassi utilizzando il seguente comando:
+
....
network interface modify -vserver vserver_name -lif lif_name -status-admin down
....
. Utilizzare `network interface delete` Comando per eliminare una o tutte le LIF:
+
[cols="30,70"]
|===


| Se si desidera eliminare... | Immettere il comando ... 


 a| 
Una LIF specifica
 a| 
`network interface delete -vserver vserver_name -lif lif_name`



 a| 
Tutte le LIF
 a| 
`network interface delete -vserver vserver_name -lif *`

|===
+
Il seguente comando elimina LIF mgmtlif2:

+
....
network interface delete -vserver vs1 -lif mgmtlif2
....
. Utilizzare `network interface show` Comando per confermare che la LIF è stata eliminata.

