---
sidebar: sidebar 
permalink: networking/determine_which_ports_can_be_used_for_a_broadcast_domains.html 
keywords: move, moving, broadcast, domain, ipspace, determining which ports can be used for a broadcast domain, before you can configure a broadcast domain to add to the new ipspace, you must determine what ports are available for the broadcast domain 
summary: Prima di poter configurare un dominio di trasmissione da aggiungere al nuovo IPSpace, è necessario determinare quali porte sono disponibili per il dominio di trasmissione 
---
= Determinazione delle porte che è possibile utilizzare per un dominio di broadcast
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di poter configurare un dominio di trasmissione da aggiungere al nuovo IPSpace, è necessario determinare quali porte sono disponibili per il dominio di trasmissione.


NOTE: Questa attività è pertinente per ONTAP 9.0 - 9.7, non per ONTAP 9.8.

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.A proposito di questa attività
* Le porte possono essere porte fisiche, VLAN o gruppi di interfacce (ifgroup).
* Le porte che si desidera aggiungere al nuovo dominio di trasmissione non possono essere assegnate a un dominio di trasmissione esistente.
* Se le porte che si desidera aggiungere al dominio di trasmissione si trovano già in un altro dominio di trasmissione (ad esempio, il dominio di trasmissione predefinito in IPSpace predefinito), è necessario rimuovere le porte da tale dominio di trasmissione prima di assegnarle al nuovo dominio di trasmissione.
* Le porte a cui sono assegnati LIF non possono essere rimosse da un dominio di broadcast.
* Poiché le LIF di gestione del cluster e dei nodi sono assegnate al dominio di broadcast predefinito in IPSpace predefinito, le porte assegnate a queste LIF non possono essere rimosse dal dominio di broadcast predefinito.


.Fasi
. Determinare le assegnazioni correnti delle porte.
+
`network port show`

+
[listing]
----
Node   Port IPspace  Broadcast Domain Link   MTU  Admin/Oper
------ ---- -------  ---------------- ----- ----  ------------
node1
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
node2
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
----
+
In questo esempio, l'output del comando fornisce le seguenti informazioni:

+
** Porte `e0c`, `e0d`, `e0e`, `e0f`, e. `e0g` Su ciascun nodo vengono assegnati al dominio di broadcast predefinito.
** Queste porte sono potenzialmente disponibili per l'utilizzo nel dominio di trasmissione dell'IPSpace che si desidera creare.


. Determinare quali porte nel dominio di broadcast predefinito sono assegnate alle interfacce LIF e quindi non possono essere spostate in un nuovo dominio di broadcast.
+
`network interface show`

+
[listing]
----
         Logical      Status     Network         Current   Current Is
Vserver  Interface    Admin/Oper Address/Mask    Node      Port    Home
-------  ----------   ---------- ------------   --------- -------  ----
Cluster
         node1_clus1  up/up       10.0.2.40/24   node1     e0a     true
         node1_clus2  up/up       10.0.2.41/24   node1     e0b     true
         node2_clus1  up/up       10.0.2.42/24   node2     e0a     true
         node2_clus2  up/up       10.0.2.43/24   node2     e0b     true

cluster1
         cluster_mgmt up/up       10.0.1.41/24   node1     e0c     true
         node1_mgmt   up/up       10.0.1.42/24   node1     e0c     true
         node2_mgmt   up/up       10.0.1.43/24   node2     e0c     true
----
+
Nell'esempio seguente, l'output del comando fornisce le seguenti informazioni:

+
** Le porte del nodo vengono assegnate alla porta `e0c` Su ciascun nodo e il nodo principale della LIF amministrativa del cluster è attivo `e0c` acceso `node1`.
** Porte `e0d`, `e0e`, `e0f`, e. `e0g` Su ogni nodo non sono presenti LIF e possono essere rimossi dal dominio di broadcast predefinito e quindi aggiunti a un nuovo dominio di broadcast per il nuovo IPSpace.



