---
sidebar: sidebar 
permalink: networking/display_subnets.html 
keywords: display, view, show, subnet, display subnets, view the list of ip addresses that are allocated to each subnet within an ipspace 
summary: 'Visualizzare l"elenco degli indirizzi IP allocati a ciascuna subnet all"interno di un IPSpace' 
---
= Visualizzare le subnet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile visualizzare l'elenco degli indirizzi IP allocati a ciascuna subnet all'interno di un IPSpace. L'output mostra anche il numero totale di indirizzi IP disponibili in ciascuna subnet e il numero di indirizzi attualmente utilizzati.

La procedura da seguire dipende dall'interfaccia in uso - System Manager o CLI:

[role="tabbed-block"]
====
.System Manager
--
*A partire da ONTAP 9.12.0, è possibile utilizzare Gestione sistema per visualizzare le subnet*

.Fasi
. Selezionare *rete > Panoramica > subnet*.
. Visualizzare l'elenco delle subnet.


--
.CLI
--
*Utilizzare la CLI per visualizzare le subnet*

.Fase
Visualizzare l'elenco delle subnet e gli intervalli di indirizzi IP associati utilizzati in tali subnet:

....
network subnet show
....
Il seguente comando visualizza le subnet e le proprietà della subnet:

....
network subnet show

IPspace: Default
Subnet                 Broadcast               Avail/
Name   Subnet          Domain    Gateway       Total   Ranges
-----  --------------- --------- ------------ -------- -----------------------
sub1   192.0.2.0/24     bcast1   192.0.2.1     5/9     192.0.2.92-192.0.2.100
sub3   198.51.100.0/24  bcast3   198.51.100.1   3/3     198.51.100.7,198.51.100.9
....
--
====