---
sidebar: sidebar 
permalink: networking/display_dns_domain_configurations.html 
keywords: display, view, show, dns, domain, configuration, verify, display dns domain configurations, verify dns domain configuration for one or more svms, vserver services name-service dns show 
summary: Verificare la configurazione del dominio DNS per una o più SVM 
---
= Visualizzare le informazioni di configurazione del dominio DNS ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare la configurazione del dominio DNS di una o più macchine virtuali di storage (SVM) nel cluster per verificare che sia configurata correttamente.

.Fase
Visualizzazione delle configurazioni del dominio DNS mediante `vserver services name-service dns show` comando.

Il seguente comando visualizza le configurazioni DNS per tutte le SVM nel cluster:

....
vserver services name-service dns show
                                                  Name
Vserver        State     Domains                  Servers
-------------- --------- ------------------------ -------------
cluster-1       enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
vs1            enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
vs2            enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
vs3            enabled   xyz.company.com          192.56.0.129,
                                                  192.56.0.130
....
Il seguente comando visualizza informazioni dettagliate sulla configurazione DNS per SVM vs1:

....
vserver services name-service dns show -vserver vs1
               Vserver: vs1
               Domains: xyz.company.com
          Name Servers: 192.56.0.129, 192.56.0.130
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
....