---
sidebar: sidebar 
permalink: networking/dscp_marking_for_uc_compliance.html 
keywords: enable, enabling, dscp, qos, marking, quality of service, differentiated services code point, egress, ip packet, traffic, performance, uc, compliance, unified capability, dscp marking for uc compliance, enable dscp marking on outgoing ip packet traffic 
summary: Attiva il contrassegno DSCP sul traffico dei pacchetti IP in uscita 
---
= Marcatura DSCP per la conformità UC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile attivare il contrassegno DSCP (differenziate Services code point) sul traffico dei pacchetti IP in uscita (in uscita) per un determinato protocollo con un codice DSCP predefinito o fornito dall'utente. Il contrassegno DSCP è un meccanismo per la classificazione e la gestione del traffico di rete ed è un componente della conformità UC (Unified Capability).

La marcatura DSCP (nota anche come _marcatura QoS_ o _marcatura della qualità del servizio_) viene attivata fornendo un valore IPSpace, protocollo e DSCP. I protocolli su cui è possibile applicare il contrassegno DSCP sono NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP/HTTPS, SSH, Telnet e SNMP.

Se non si fornisce un valore DSCP quando si attiva la marcatura DSCP per un determinato protocollo, viene utilizzato un valore predefinito:

* Il valore predefinito per il traffico/protocolli dati è 0x0A (10).
* Il valore predefinito per i protocolli di controllo/traffico è 0x30 (48).

