---
sidebar: sidebar 
permalink: networking/enable_multipath_routing.html 
keywords: enable, enabling, multipath, route, routing, performance, enable multipath routing, enable multipath routing to load balance and utilize all the available routes 
summary: Abilitare il routing multipath per il bilanciamento del carico e utilizzare tutti i percorsi disponibili 
---
= Abilitare il routing multipath
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se più percorsi hanno la stessa metrica per una destinazione, viene selezionato solo uno dei percorsi per il traffico in uscita. Ciò comporta la mancata utilizzo di altri percorsi per l'invio del traffico in uscita. È possibile abilitare l'instradamento multipercorso per bilanciare il carico su tutti i percorsi disponibili in proporzione alle relative metriche, rispetto all'instradamento ECMP, che bilancia il carico sui percorsi disponibili della stessa metrica.

.Fasi
. Accedere al livello di privilegio avanzato:
+
`set -privilege advanced`

. Abilita routing multipath:
+
`network options multipath-routing modify -is-enabled true`

+
Il routing multipath è abilitato per tutti i nodi nel cluster.



....
network options multipath-routing modify -is-enabled true
....