---
sidebar: sidebar 
permalink: networking/how_dns_load_balancing_works.html 
keywords: introducing, introduction, overview, dns, naming, name, service, load, balance, balancing, performance, how dns load balancing works, introducing dns load balancing 
summary: Introduzione al bilanciamento del carico DNS 
---
= Informazioni sul bilanciamento del carico DNS per la rete ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I client montano una SVM specificando un indirizzo IP (associato a una LIF) o un nome host (associato a più indirizzi IP). Per impostazione predefinita, i LIF vengono selezionati dal server DNS a livello di sito in modo round-robin, che bilancia il carico di lavoro in tutte le LIF.

Il bilanciamento del carico round-robin può comportare l'overload di alcune LIF, pertanto è possibile utilizzare una zona di bilanciamento del carico DNS che gestisce la risoluzione del nome host in una SVM. L'utilizzo di una zona di bilanciamento del carico DNS garantisce un migliore bilanciamento delle nuove connessioni client tra le risorse disponibili, migliorando le performance del cluster.

Una zona di bilanciamento del carico DNS è un server DNS all'interno del cluster che valuta dinamicamente il carico su tutte le LIF e restituisce una LIF caricata correttamente. In una zona di bilanciamento del carico, DNS assegna un peso (metrico), in base al carico, a ciascun LIF.

A ogni LIF viene assegnato un peso in base al carico della porta e all'utilizzo della CPU del nodo principale. Le LIF che si trovano su porte meno caricate hanno una maggiore probabilità di essere restituite in una query DNS. I pesi possono anche essere assegnati manualmente.
