---
sidebar: sidebar 
permalink: networking/manage_the_hosts_table_@cluster_administrators_only@.html 
keywords: 'manage, managing, snmp, monitor, monitoring, troubleshooting, error detection, traps, hosts, host, table, add, modify, change, create, delete, remove, view, show, display, manage the hosts table (cluster administrators only, manage the host name entries in the hosts table of the admin svm, commands for managing local host-name entries, vserver services name-service dns hosts' 
summary: Gestire le voci del nome host nella tabella hosts della SVM amministrativa 
---
= Gestire la tabella degli host (solo amministratori del cluster)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un amministratore del cluster può aggiungere, modificare, eliminare e visualizzare le voci del nome host nella tabella hosts della macchina virtuale di storage amministrativa (SVM). Un amministratore SVM può configurare le voci del nome host solo per la SVM assegnata.



== Comandi per la gestione delle voci dei nomi host locali

È possibile utilizzare `vserver services name-service dns hosts` Per creare, modificare o eliminare le voci della tabella host DNS.

Quando si creano o modificano le voci del nome host DNS, è possibile specificare più indirizzi alias separati da virgole.

[cols="30,70"]
|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare un nome host DNS
 a| 
`vserver services name-service dns hosts create`



 a| 
Modificare una voce del nome host DNS
 a| 
`vserver services name-service dns hosts modify`



 a| 
Eliminare una voce del nome host DNS
 a| 
`vserver services name-service dns hosts delete`

|===
Per ulteriori informazioni, consultare http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^] per `vserver services name-service dns hosts` comandi.
