---
sidebar: sidebar 
permalink: networking/merge_broadcast_domains97.html 
keywords: merge, combine, broadcast, domain, reachability, merge broadcast domains, merge the ports from one broadcast domain into an existing broadcast domain 
summary: Unire le porte da un dominio di broadcast in un dominio di broadcast esistente 
---
= Unire i domini di broadcast
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile spostare tutte le porte da un dominio di broadcast a un dominio di broadcast esistente utilizzando il comando merge.

Questa operazione riduce i passaggi necessari per rimuovere tutte le porte da un dominio di trasmissione e aggiungerle a un dominio di trasmissione esistente.

.Fase
Unire le porte da un dominio di broadcast in un dominio di broadcast esistente:

....
network port broadcast-domain merge -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -into-broadcast-domain <broadcast_domain_name>
....
* `ipspace_name` È il nome dell'IPSpace in cui risiedono i domini di trasmissione.
* `-broadcast-domain` è il nome del dominio di trasmissione che verrà unito.
* `-into-broadcast-domain` è il nome del dominio di trasmissione che riceverà porte aggiuntive.


.Esempio
Il seguente esempio unisce il dominio di trasmissione bd-data1 al dominio di trasmissione bd-data2:

`network port -ipspace Default broadcast-domain bd-data1 into-broadcast-domain bd-data2`
