---
sidebar: sidebar 
permalink: networking/modify_qos_marking_values.html 
keywords: change, changing, modify, modifying, qos, quality, service, marking, performance, modify qos marking values, change the qos marking values for different protocols, network qos-marking modify 
summary: Modificare i valori di marcatura QoS per diversi protocolli 
---
= Modificare i valori di marcatura QoS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile modificare i valori di marcatura della qualità del servizio (QoS) per diversi protocolli, per ciascun IPSpace.

.Prima di iniziare
Tutti i nodi del cluster devono eseguire la stessa versione di ONTAP.

.Fase
Modificare i valori di marcatura QoS utilizzando `network qos-marking modify` comando.

* Il `–ipspace` Parameter (parametro) specifica l'IPSpace per cui la voce di marcatura QoS deve essere modificata.
* Il `–protocol` Parametro specifica il protocollo per cui la voce di marcatura QoS deve essere modificata. Il `network qos-marking modify` la pagina man descrive i possibili valori del protocollo.
* Il `–dscp` Il parametro specifica il valore DSCP (Differentiated Services Code Point). I valori possibili vanno da 0 a 63.
* Il `-is-enabled` Il parametro viene utilizzato per attivare o disattivare il contrassegno QoS per il protocollo specificato nell'IPSpace fornito da `–ipspace` parametro.


Il seguente comando attiva il contrassegno QoS per il protocollo NFS nell'IPSpace predefinito:

....
network qos-marking modify -ipspace Default -protocol NFS -is-enabled true
....
Il seguente comando imposta il valore DSCP su 20 per il protocollo NFS nell'IPSpace predefinito:

....
network qos-marking modify -ipspace Default -protocol NFS -dscp 20
....