---
sidebar: sidebar 
permalink: networking/worksheet_for_nas_path_failover_configuration_manual.html 
keywords: ipspace configuration, broadcast domain configuration, subnet configuration, SVM configuration, LIF configuration, DNS configuration, dynamic DNS configuration, worksheet for nas path failover configuration for ontap 9.8 and later, complete all sections of the worksheet before configuring nas path failover for ontap 9.7 and earlier, ipspace configuration, broadcast domain configuration, mtu, maximum transmission unit, mtu is 1500 mtu is 9000, subnet configuration, storage virtual machine configuration, svm configuration, lif configuration, dynamic dns configuration, dns configuration 
summary: Completare tutte le sezioni del foglio di lavoro prima di configurare il failover del percorso NAS per ONTAP 9.0 - 9.7 
---
= Foglio di lavoro per la configurazione del failover del percorso NAS (ONTAP 9,7 e versioni precedenti)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Completare tutte le sezioni del foglio di lavoro prima di configurare il failover del percorso NAS.



== Configurazione di IPSpace

È possibile utilizzare un IPSpace per creare uno spazio di indirizzi IP distinto per ogni SVM in un cluster. In questo modo, i client in domini di rete separati a livello amministrativo possono accedere ai dati del cluster utilizzando indirizzi IP sovrapposti dallo stesso intervallo di subnet di indirizzi IP.

|===


| Informazioni | Necessario? | I tuoi valori 


 a| 
Nome IPSpace

* Il nome di IPSpace.
* Il nome deve essere univoco nel cluster.

| Sì |  
|===


== Configurazione del dominio di trasmissione

Un dominio di trasmissione raggruppa le porte che appartengono alla stessa rete Layer 2 e imposta la MTU per le porte del dominio di trasmissione.

I domini di broadcast vengono assegnati a un IPSpace. Un IPSpace può contenere uno o più domini di broadcast.


NOTE: La porta a cui si verifica il failover di LIF deve essere membro del gruppo di failover per LIF. Quando si crea un dominio di broadcast, ONTAP crea automaticamente un gruppo di failover con lo stesso nome. Il gruppo di failover contiene tutte le porte assegnate al dominio di trasmissione.

|===


| Informazioni | Necessario? | I tuoi valori 


 a| 
Nome IPSpace

* L'IPSpace a cui è assegnato il dominio di trasmissione.
* IPSpace deve esistere.

| Sì |  


 a| 
Nome di dominio di trasmissione

* Il nome del dominio di trasmissione.
* Questo nome deve essere univoco in IPSpace.

| Sì |  


 a| 
MTU

* MTU del dominio di trasmissione.
* Generalmente impostato su *1500* o *9000*.
* Il valore MTU viene applicato a tutte le porte nel dominio di trasmissione e a tutte le porte che vengono successivamente aggiunte al dominio di trasmissione.



NOTE: Il valore MTU deve corrispondere a tutti i dispositivi connessi a tale rete. Tenere presente che la MTU non deve superare i 1500 byte per la gestione della porta e0M e il traffico del processore di servizio.
| Sì |  


 a| 
Porte

* Le porte di rete da aggiungere al dominio di trasmissione.
* Le porte assegnate al dominio di trasmissione possono essere porte fisiche, VLAN o gruppi di interfacce (ifgroup).
* Se una porta si trova in un altro dominio di trasmissione, deve essere rimossa prima di poter essere aggiunta al dominio di trasmissione.
* Le porte vengono assegnate specificando sia il nome del nodo che la porta, ad esempio node1:e0d.

| Sì |  
|===


== Configurazione della subnet

Una subnet contiene pool di indirizzi IP e un gateway predefinito che può essere assegnato alle LIF utilizzate dalle SVM che risiedono nell'IPSpace.

* Quando si crea una LIF su una SVM, è possibile specificare il nome della subnet invece di fornire un indirizzo IP e una subnet.
* Poiché una subnet può essere configurata con un gateway predefinito, non è necessario creare il gateway predefinito in una fase separata durante la creazione di una SVM.
* Un dominio di broadcast può contenere una o più subnet. È possibile configurare le LIF SVM presenti su sottoreti diverse associando più di una subnet al dominio di trasmissione di IPSpace.
* Ogni subnet deve contenere indirizzi IP che non si sovrappongono agli indirizzi IP assegnati ad altre subnet dello stesso IPSpace.
* È possibile assegnare indirizzi IP specifici alle LIF dei dati SVM e creare un gateway predefinito per la SVM invece di utilizzare una subnet.


|===


| Informazioni | Necessario? | I tuoi valori 


 a| 
Nome IPSpace

* L'IPSpace a cui verrà assegnata la subnet.
* IPSpace deve esistere.

| Sì |  


 a| 
Nome della subnet

* Il nome della subnet.
* Il nome deve essere univoco in IPSpace.

| Sì |  


 a| 
Nome di dominio di trasmissione

* Il dominio di trasmissione a cui verrà assegnata la subnet.
* Il dominio di trasmissione deve risiedere nell'IPSpace specificato.

| Sì |  


 a| 
Subnet name e mask

* Subnet e maschera in cui risiedono gli indirizzi IP.

| Sì |  


 a| 
Gateway

* È possibile specificare un gateway predefinito per la subnet.
* Se non si assegna un gateway quando si crea la subnet, è possibile assegnarne uno in qualsiasi momento.

| No |  


 a| 
Intervalli di indirizzi IP

* È possibile specificare un intervallo di indirizzi IP o indirizzi IP specifici. Ad esempio, è possibile specificare un intervallo come:
`192.168.1.1-192.168.1.100, 192.168.1.112, 192.168.1.145`
* Se non si specifica un intervallo di indirizzi IP, l'intero intervallo di indirizzi IP nella subnet specificata sarà disponibile per l'assegnazione ai file LIF.

| No |  


 a| 
Forzare l'aggiornamento delle associazioni LIF

* Specifica se forzare l'aggiornamento delle associazioni LIF esistenti.
* Per impostazione predefinita, la creazione della subnet non riesce se le interfacce del service processor o di rete utilizzano gli indirizzi IP degli intervalli forniti.
* L'utilizzo di questo parametro consente di associare qualsiasi interfaccia indirizzata manualmente alla subnet e di eseguire correttamente il comando.

| No |  
|===


== Configurazione SVM

Utilizzate le SVM per fornire dati a client e host.

I valori registrati servono per la creazione di una SVM di dati predefinita. Se si sta creando una SVM di origine MetroCluster, consultare link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installare un MetroCluster collegato al fabric"] o il link:https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/index.html["Installare un MetroCluster stretch"].

|===


| Informazioni | Necessario? | I tuoi valori 


 a| 
Nome SVM

* Il nome della SVM.
* È necessario utilizzare un nome di dominio completo (FQDN) per garantire nomi SVM univoci nei vari campionati di cluster.

| Sì |  


 a| 
Nome del volume root

* Il nome del volume root SVM.

| Sì |  


 a| 
Nome dell'aggregato

* Il nome dell'aggregato che contiene il volume root SVM.
* Questo aggregato deve esistere.

| Sì |  


 a| 
Stile di sicurezza

* Lo stile di sicurezza per il volume root SVM.
* I valori possibili sono *ntfs*, *unix* e *misto*.

| Sì |  


 a| 
Nome IPSpace

* L'IPSpace a cui è assegnata la SVM.
* Questo IPSpace deve esistere.

| No |  


 a| 
Impostazione della lingua SVM

* La lingua predefinita da utilizzare per SVM e i relativi volumi.
* Se non si specifica una lingua predefinita, la lingua SVM predefinita viene impostata su *C.UTF-8*.
* L'impostazione della lingua SVM determina il set di caratteri utilizzato per visualizzare i nomi dei file e i dati di tutti i volumi NAS nella SVM. È possibile modificare la lingua dopo la creazione di SVM.

| No |  
|===


== Configurazione LIF

Una SVM fornisce i dati ai client e agli host attraverso una o più interfacce logiche di rete (LIF).

|===


| Informazioni | Necessario? | I tuoi valori 


 a| 
Nome SVM

* Il nome della SVM per la LIF.

| Sì |  


 a| 
Nome LIF

* Il nome del LIF.
* È possibile assegnare più LIF di dati per nodo ed è possibile assegnare LIF a qualsiasi nodo del cluster, a condizione che il nodo disponga di porte dati disponibili.
* Per garantire la ridondanza, è necessario creare almeno due LIF di dati per ciascuna subnet di dati e assegnare le LIF assegnate a una determinata subnet a porte home su nodi diversi. *Importante:* se si configura un server SMB per ospitare Hyper-V o SQL Server su SMB per soluzioni operative senza interruzioni, SVM deve disporre di almeno una LIF di dati su ogni nodo del cluster.

| Sì |  


 a| 
Ruolo LIF

* Il ruolo della LIF.
* Ai file LIF dei dati viene assegnato il ruolo dei dati.

| Sì, estratto da ONTAP 9.6 | dati 


| Politica di servizio Politica di servizio per LIF. La politica di servizio definisce quali servizi di rete possono utilizzare la LIF. I servizi integrati e le policy di servizio sono disponibili per la gestione del traffico di dati e di gestione su SVM di dati e di sistema. | Sì, a partire da ONTAP 9.6 |  


 a| 
Protocolli consentiti

* I protocolli che possono utilizzare LIF.
* Per impostazione predefinita, SMB, NFS e FlexCache sono consentiti. Il protocollo FlexCache consente di utilizzare un volume come volume di origine per un volume FlexCache su un sistema che esegue Data ONTAP in modalità 7.



NOTE: I protocolli che utilizzano la LIF non possono essere modificati dopo la creazione della LIF. Specificare tutti i protocolli quando si configura la LIF.
| No |  


 a| 
Nodo principale

* Il nodo a cui la LIF restituisce quando la LIF viene riportata alla porta home.
* È necessario registrare un nodo principale per ciascun LIF di dati.

| Sì |  


 a| 
Porta home o dominio di broadcast

* La porta a cui l'interfaccia logica ritorna quando la LIF viene riportata alla porta home.
* È necessario registrare una porta home per ciascun LIF di dati.

| Sì |  


 a| 
Nome della subnet

* Subnet da assegnare alla SVM.
* Tutti i dati LIF utilizzati per creare connessioni SMB continuamente disponibili ai server applicazioni devono trovarsi sulla stessa sottorete.

| Sì (se si utilizza una subnet) |  
|===


== Configurazione DNS

È necessario configurare il DNS sulla SVM prima di creare un server NFS o SMB.

|===


| Informazioni | Necessario? | I tuoi valori 


 a| 
Nome SVM

* Il nome della SVM su cui si desidera creare un server NFS o SMB.

| Sì |  


 a| 
Nome di dominio DNS

* Un elenco di nomi di dominio da aggiungere a un nome host quando si esegue la risoluzione dei nomi da host a IP.
* Elencare prima il dominio locale, seguito dai nomi di dominio per i quali vengono eseguite più spesso query DNS.

| Sì |  


 a| 
Indirizzi IP dei server DNS

* Elenco di indirizzi IP dei server DNS che forniscono la risoluzione dei nomi per il server NFS o SMB.
* I server DNS elencati devono contenere i record di posizione del servizio (SRV) necessari per individuare i server LDAP di Active Directory e i controller di dominio per il dominio a cui il server SMB farà parte.
Il record SRV viene utilizzato per associare il nome di un servizio al nome del computer DNS di un server che offre tale servizio. La creazione del server SMB non riesce se ONTAP non riesce a ottenere i record di posizione del servizio tramite query DNS locali.
Il modo più semplice per garantire che ONTAP possa individuare i record SRV di Active Directory consiste nel configurare i server DNS integrati come server DNS di SVM.
È possibile utilizzare server DNS non integrati in Active Directory, a condizione che l'amministratore DNS abbia aggiunto manualmente i record SRV alla zona DNS che contiene informazioni sui controller di dominio Active Directory.
* Per informazioni sui record SRV integrati in Active Directory, vedere l'argomento link:http://technet.microsoft.com/library/cc759550(WS.10).aspx["Come funziona il supporto DNS per Active Directory su Microsoft TechNet"^].

| Sì |  
|===


== Configurazione DNS dinamica

Prima di poter utilizzare il DNS dinamico per aggiungere automaticamente le voci DNS ai server DNS integrati in Active Directory, è necessario configurare il DNS dinamico (DDNS) su SVM.

I record DNS vengono creati per ogni LIF di dati sulla SVM. Creando più LIFS di dati su SVM, è possibile bilanciare il carico delle connessioni client agli indirizzi IP dei dati assegnati. Il carico DNS bilancia le connessioni effettuate utilizzando il nome host con gli indirizzi IP assegnati in modo round-robin.

|===


| Informazioni | Necessario? | I tuoi valori 


 a| 
Nome SVM

* SVM su cui si desidera creare un server NFS o SMB.

| Sì |  


 a| 
Se utilizzare DDNS

* Specifica se utilizzare DDNS.
* I server DNS configurati su SVM devono supportare DDNS. Per impostazione predefinita, il DDNS è disattivato.

| Sì |  


 a| 
Se utilizzare DDNS sicuro

* Il DDNS sicuro è supportato solo con il DNS integrato in Active Directory.
* Se il DNS integrato in Active Directory consente solo aggiornamenti DDNS sicuri, il valore di questo parametro deve essere true.
* Per impostazione predefinita, il DDNS sicuro è disattivato.
* È possibile attivare il DDNS sicuro solo dopo la creazione di un server SMB o di un account Active Directory per SVM.

| No |  


 a| 
FQDN del dominio DNS

* L'FQDN del dominio DNS.
* È necessario utilizzare lo stesso nome di dominio configurato per i servizi dei nomi DNS su SVM.

| No |  
|===