---
permalink: concepts/administrator-authentication-rbac-concept.html 
sidebar: sidebar 
keywords: administrator authentication, rbac 
summary: 'Gli amministratori utilizzano account di accesso locali o remoti per autenticarsi al cluster e alla SVM. RBAC (Role-Based Access Control) determina i comandi a cui un amministratore ha accesso.' 
---
= Autenticazione amministratore e RBAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli amministratori utilizzano account di accesso locali o remoti per autenticarsi al cluster e alla SVM. RBAC (Role-Based Access Control) determina i comandi a cui un amministratore ha accesso.



== Autenticazione

È possibile creare account di amministratore SVM e cluster locali o remoti:

* Un account locale è un account in cui le informazioni sull'account, la chiave pubblica o il certificato di protezione risiedono nel sistema di storage.
* Un account remoto è un account in cui le informazioni sull'account vengono memorizzate in un controller di dominio Active Directory, in un server LDAP o in un server NIS.


Ad eccezione del DNS, ONTAP utilizza gli stessi servizi di nome per autenticare gli account amministratore utilizzati per autenticare i client.



== RBAC

Il _ruolo_ assegnato a un amministratore determina i comandi a cui l'amministratore ha accesso. Il ruolo viene assegnato quando si crea l'account per l'amministratore. È possibile assegnare un ruolo diverso o definire ruoli personalizzati in base alle esigenze.
