---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: 'L"efficienza di archiviazione del processore di offload dedicato è abilitata per impostazione predefinita su alcune piattaforme AFF e FAS . Queste piattaforme non sfruttano l"efficienza di stoccaggio sensibile alla temperatura.  La compressione inizia senza attendere che i dati diventino freddi e viene eseguita utilizzando un processore di offload dedicato.' 
---
= Scopri l'efficienza dello storage del processore di offload dedicato ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'efficienza di archiviazione del processore di offload dedicato esegue il confezionamento sequenziale di blocchi fisici contigui e utilizza un processore di offload dedicato per la compressione dei dati a 32k.  Con la compressione a 32k, il risparmio di spazio viene realizzato a livello aggregato, a differenza delle piattaforme che utilizzano la compressione adattiva a 8k, in cui il risparmio di spazio viene realizzato a livello di volume.  Le piattaforme che utilizzano l'efficienza di archiviazione del processore di offload dedicato non utilizzano l'efficienza di archiviazione sensibile alla temperatura (TSSE), il che significa che la compressione non si basa su dati caldi o freddi.  Ciò si traduce in un risparmio immediato di spazio senza alcun impatto sulle prestazioni.

L'efficienza di archiviazione del processore di offload dedicato è abilitata per impostazione predefinita sulle seguenti piattaforme e versioni ONTAP .


NOTE: La piattaforma AFF A20 non supporta l'efficienza di archiviazione del processore di offload dedicato.  Per le piattaforme AFF A20, i dati migrati tramite la tecnologia SnapMirror vengono convertiti automaticamente in compressione in linea a 32k tramite la CPU principale.

[cols="2"]
|===
| Piattaforma | Versione di ONTAP 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 o versione successiva 


 a| 
* AFF A50
* AFF A30

| 9.16.1 o versione successiva 
|===
Per le seguenti piattaforme, l'efficienza di archiviazione è abilitata automaticamente e non richiede alcuna configurazione.  Ciò si applica a tutti i volumi thin-provisioning di nuova creazione e ai dati esistenti, compresi i volumi spostati da altre piattaforme.  La deduplicazione è abilitata indipendentemente dall'impostazione della garanzia dello spazio.  Sia la compressione che la compattazione dei dati richiedono che la garanzia di spazio sia impostata su nessuno.  I dati migrati tramite la tecnologia Volume Move o SnapMirror vengono convertiti automaticamente in compressione in linea a 32k.

* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30


Per le seguenti piattaforme, l'efficienza di archiviazione è abilitata per impostazione predefinita solo sui volumi thin-provisioning esistenti in cui l'efficienza di archiviazione era abilitata prima dell'aggiornamento a ONTAP 9.15.1 o versione successiva.  È possibile abilitare l'efficienza di archiviazione sui volumi appena creati utilizzando il metodo CLI o REST API.  I dati migrati tramite la tecnologia Volume Move o SnapMirror vengono convertiti in compressione in linea a 32k solo se la compressione era abilitata sulla piattaforma originale.

* FAS90
* FAS70


Per informazioni sull'aggiornamento di un controller a una delle piattaforme supportate, vedere https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentazione di aggiornamento hardware ONTAP"^] .
