---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: 'A partire da ONTAP 9.15.1, l"efficienza dello storage e la data compaction integrate e abilitate automaticamente sono sulle piattaforme AFF A70, AFF A90 e AFF A1K.' 
---
= Efficienza dello storage della CPU o del processore di offload dedicato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.15,1, ONTAP garantisce l'efficienza dello storage e la data compaction per le piattaforme AFF A70, AFF A90, AFF A1K, FAS70 e FAS90.

A seconda della piattaforma, si applica quanto segue quando si esegue l'aggiornamento:

* La compressione viene eseguita utilizzando la CPU principale o con un processore di offload dedicato.
* L'efficienza dello storage è abilitata per impostazione predefinita su tutti i volumi con thin provisioning o solo sui volumi esistenti.
+
Per una piattaforma FF A70, AFF A90 o AFF A1K, l'efficienza dello storage viene abilitata automaticamente e non richiede configurazione. Ciò si applica a tutti i volumi con thin provisioning appena creati e ai dati esistenti, compresi i volumi spostati da altre piattaforme su una piattaforma AFF A70, AFF A90 o AFF A1K.

+
Per una piattaforma FAS70 o FAS90, l'efficienza dello storage è abilitata per impostazione predefinita solo sui volumi con thin provisioning esistenti con efficienza dello storage abilitata prima dell'upgrade. Puoi abilitare l'efficienza dello storage sui volumi appena creati utilizzando il metodo CLI o API REST.

* I dati che vengono migrati tramite Volume Move o la tecnologia SnapMirror vengono convertiti automaticamente in compressione inline 32k:
+
Per una piattaforma AFF A70, AFF A90 o AFF A1K, i dati vengono convertiti automaticamente.

+
Per una piattaforma FAS70 o FAS90, i dati vengono convertiti solo se la compressione è stata attivata sulla piattaforma originale.



L'efficienza dello storage sensibile alla temperatura non si applica alle piattaforme AFF A70, AFF A90, AFF A1K, FAS70 e FAS90. La compressione non si basa sui dati "hot" o "cold" su queste piattaforme, pertanto la compressione inizia senza attendere che i dati diventino "cold".

L'efficienza dello storage sulle piattaforme AFF A70, AFF A90, AFF A1K, FAS70 e FAS90 utilizza il packaging sequenziale di blocchi fisici contigui per migliorare ulteriormente l'efficienza dello storage per i dati compressi.

Per informazioni sull'aggiornamento di un controller a AFF A70, AFF A90, AFF A1K, FAS70 o FAS90, vedere https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentazione di aggiornamento hardware ONTAP"^] .
