---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: 'A partire da ONTAP 9.15.1, l"efficienza dello storage e la data compaction integrate e abilitate automaticamente sono sulle piattaforme AFF A70, AFF A90 e AFF A1K.' 
---
= Efficienza dello storage della CPU o del processore di offload dedicato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'efficienza di archiviazione della CPU o del processore di offload dedicato è abilitata per impostazione predefinita su alcune piattaforme AFF e FAS .  Queste piattaforme non sfruttano l'efficienza di stoccaggio sensibile alla temperatura.  La compressione inizia senza attendere che i dati diventino freddi e viene eseguita utilizzando la CPU principale o un processore di offload dedicato.  Queste piattaforme utilizzano anche il confezionamento sequenziale di blocchi fisici contigui per migliorare ulteriormente l'efficienza di archiviazione dei dati compressi.

L'efficienza di archiviazione della CPU o del processore di offload dedicato è disponibile sulle seguenti piattaforme e versioni ONTAP :

[cols="2"]
|===
| Piattaforma | Versione di ONTAP 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 o versione successiva 


 a| 
* AFF A50
* AFF A30

| 9.16.1 o versione successiva 
|===

NOTE: I dati migrati tramite la tecnologia SnapMirror vengono convertiti automaticamente in compressione in linea a 32k sulle piattaforme AFF A20.  Tuttavia, la piattaforma AFF A20 non supporta l'efficienza di archiviazione della CPU o del processore di offload dedicato.

Per le seguenti piattaforme, l'efficienza di archiviazione è abilitata automaticamente e non richiede alcuna configurazione.  Ciò si applica a tutti i volumi thin-provisioning di nuova creazione e ai dati esistenti, compresi i volumi spostati da altre piattaforme.  La deduplicazione è abilitata indipendentemente dall'impostazione della garanzia dello spazio.  Sia la compressione che la compattazione dei dati richiedono che la garanzia di spazio sia impostata su nessuno.  I dati migrati tramite la tecnologia Volume Move o SnapMirror vengono convertiti automaticamente in compressione in linea a 32k.

* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30


Per le seguenti piattaforme, l'efficienza di archiviazione è abilitata per impostazione predefinita solo sui volumi thin-provisioning esistenti in cui l'efficienza di archiviazione era abilitata prima dell'aggiornamento a ONTAP 9.15.1 o versione successiva.  È possibile abilitare l'efficienza di archiviazione sui volumi appena creati utilizzando il metodo CLI o REST API.  I dati migrati tramite la tecnologia Volume Move o SnapMirror vengono convertiti in compressione in linea a 32k solo se la compressione era abilitata sulla piattaforma originale.

* FAS90
* FAS70


Per informazioni sull'aggiornamento di un controller a una delle piattaforme supportate, vedere https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentazione di aggiornamento hardware ONTAP"^] .
