---
permalink: concepts/client-protocols-concept.html 
sidebar: sidebar 
keywords: client protocols 
summary: 'ONTAP supporta tutti i principali protocolli client standard di settore: NFS, SMB, FC, FCoE, iSCSI, NVMe/FC e S3.' 
---
= Protocolli client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporta tutti i principali protocolli client standard di settore: NFS, SMB, FC, FCoE, iSCSI, NVMe/FC e S3.



== NFS

NFS è il protocollo di accesso ai file tradizionale per i sistemi UNIX e LINUX. I client possono accedere ai file in volumi ONTAP utilizzando i seguenti protocolli.

* NFSv3
* NFSv4
* NFSv4.2
* NFSv4.1
* PNFS


È possibile controllare l'accesso ai file utilizzando permessi di stile UNIX, permessi di stile NTFS o una combinazione di entrambi.

I client possono accedere agli stessi file utilizzando i protocolli NFS e SMB.



== PMI

SMB è il protocollo di accesso ai file tradizionale per i sistemi Windows. I client possono accedere ai file nei volumi ONTAP utilizzando i protocolli SMB 2.0, SMB 2.1, SMB 3.0 e SMB 3.1.1. Come per NFS, sono supportati diversi stili di permesso.

SMB 1.0 è disponibile ma disattivato per impostazione predefinita in ONTAP 9.3 e versioni successive.



== FC

Fibre Channel è il protocollo a blocchi di rete originale. Al posto dei file, un protocollo a blocchi presenta un intero disco virtuale a un client. Il protocollo FC tradizionale utilizza una rete FC dedicata con switch FC specializzati e richiede che il computer client disponga di interfacce di rete FC.

Un LUN rappresenta il disco virtuale e uno o più LUN vengono memorizzati in un volume ONTAP. È possibile accedere allo stesso LUN attraverso i protocolli FC, FCoE e iSCSI, ma più client possono accedere allo stesso LUN solo se fanno parte di un cluster che impedisce collisioni in scrittura.



== FCoE

FCoE è fondamentalmente lo stesso protocollo di FC, ma utilizza una rete Ethernet di livello datacenter al posto del trasporto FC tradizionale. Il client richiede ancora un'interfaccia di rete specifica per FCoE.



== ISCSI

ISCSI è un protocollo a blocchi che può essere eseguito su reti Ethernet standard. La maggior parte dei sistemi operativi client offre un iniziatore software che viene eseguito su una porta Ethernet standard. ISCSI è una buona scelta quando è necessario un protocollo a blocchi per una particolare applicazione, ma non è disponibile una rete FC dedicata.



== NVMe/FC

Il più recente protocollo a blocchi, NVMe/FC, è progettato specificamente per funzionare con lo storage basato su flash. Offre sessioni scalabili, una significativa riduzione della latenza e un aumento del parallelismo, il che lo rende ideale per applicazioni a bassa latenza e throughput elevato, come database in-memory e analytics.

A differenza di FC e iSCSI, NVMe non utilizza LUN. Utilizza invece spazi dei nomi, memorizzati in un volume ONTAP. È possibile accedere agli spazi dei nomi NVMe solo tramite il protocollo NVMe.



== S3

A partire da ONTAP 9.8, è possibile attivare un server S3 (Simple Storage Service) di ONTAP in un cluster ONTAP, consentendo di fornire i dati nello storage a oggetti utilizzando i bucket S3.

ONTAP supporta due scenari di casi d'utilizzo on-premise per il servizio dello storage a oggetti S3:

* Tier FabricPool per un bucket su cluster locale (Tier to a local bucket) o cluster remoto (Tier cloud).
* Accesso dell'applicazione client S3 a un bucket sul cluster locale o su un cluster remoto.


[NOTE]
====
ONTAP S3 è adatto per le funzionalità S3 sui cluster esistenti senza hardware e gestione aggiuntivi. Per implementazioni superiori a 300 TB, il software NetApp StorageGRID continua a essere la soluzione di punta per lo storage a oggetti. Scopri di più link:https://docs.netapp.com/sgws-114/index.jsp["StorageGRID"^].

====