---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: 'Oltre alle relazioni di protezione dei dati SnapMirror e SnapVault, che erano disk-to-disk solo per ONTAP 9,7 e versioni precedenti, oggi esistono diverse soluzioni di backup che offrono un"alternativa meno costosa per la conservazione dei dati a lungo termine.' 
---
= Backup nel cloud e supporto per backup tradizionali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oltre alle relazioni di protezione dei dati SnapMirror e SnapVault, che erano disk-to-disk solo per ONTAP 9,7 e versioni precedenti, oggi esistono diverse soluzioni di backup che offrono un'alternativa meno costosa per la conservazione dei dati a lungo termine.

Numerose applicazioni di protezione dei dati di terze parti offrono il backup tradizionale per i dati gestiti da ONTAP. Veeam, Veritas e CommVault, tra gli altri, offrono backup integrato per i sistemi ONTAP.

A partire da ONTAP 9.8, il cloud SnapMirror fornisce una replica asincrona delle copie Snapshot dalle istanze ONTAP agli endpoint di storage a oggetti. La replica cloud SnapMirror richiede un'applicazione con licenza per Orchestration e gestione dei workflow di data Protection. Le relazioni cloud di SnapMirror sono supportate dai sistemi ONTAP in determinate destinazioni di storage a oggetti di cloud pubblico e on-premise, tra cui AWS S3, Google Cloud Storage Platform o archiviazione BLOB di Microsoft Azure, il che permette di avere una maggiore efficienza con il software di backup dei vendor. Contatta il tuo rappresentante NetApp per un elenco delle applicazioni certificate supportate e dei vendor di storage a oggetti.

Se sei interessato alla protezione dei dati nativa del cloud, BlueXP può essere utilizzato per configurare le relazioni di SnapMirror o SnapVault tra volumi on-premise e istanze di Cloud Volumes ONTAP nel cloud pubblico.

BlueXP fornisce inoltre backup delle istanze di Cloud Volumes ONTAP utilizzando un modello SaaS (Software as a Service). Gli utenti possono eseguire il backup delle istanze di Cloud Volumes ONTAP su storage a oggetti cloud pubblico compatibile con S3 e S3 utilizzando il backup cloud disponibile su NetApp Cloud Central.

https://www.netapp.com/cloud-services/cloud-manager/documentation/["Risorse per la documentazione di Cloud Volumes ONTAP e BlueXP"]

https://cloud.netapp.com["NetApp Cloud Central"]
