---
permalink: concepts/compression-concept.html 
sidebar: sidebar 
keywords: compression 
summary: La compressione riduce la quantità di storage fisico richiesta per un volume combinando i blocchi di dati in gruppi di compressione, ciascuno dei quali viene memorizzato come blocco singolo. Le letture dei dati compressi sono più veloci rispetto ai metodi di compressione tradizionali, poiché ONTAP decomprime solo i gruppi di compressione che contengono i dati richiesti, non un intero file o LUN. 
---
= Compressione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_Compressione_ riduce la quantità di storage fisico richiesta per un volume combinando i blocchi di dati in _gruppi di compressione_, ciascuno dei quali viene memorizzato come un singolo blocco. Le letture dei dati compressi sono più veloci rispetto ai metodi di compressione tradizionali, poiché ONTAP decomprime solo i gruppi di compressione che contengono i dati richiesti, non un intero file o LUN.

È possibile eseguire la compressione inline o post-processo, separatamente o in combinazione:

* _Compressione inline_ comprime i dati in memoria prima che vengano scritti su disco, riducendo significativamente la quantità di i/o di scrittura su un volume, ma potenzialmente degradando le prestazioni di scrittura. Le operazioni che richiedono prestazioni elevate vengono posticipate fino alla successiva operazione di compressione post-processo, se presente.
* _Compressione post-processo_ comprime i dati dopo la scrittura su disco, secondo la stessa pianificazione della deduplica.


|===


 a| 
*_Inline data compaction_* i file di piccole dimensioni o i/o con zeri vengono memorizzati in un blocco di 4 KB, indipendentemente dal fatto che richiedano o meno 4 KB di storage fisico. _Inline data compaction_ combina blocchi di dati che normalmente consumerebbero più blocchi da 4 KB in un singolo blocco da 4 KB su disco. La compattazione avviene quando i dati sono ancora in memoria, quindi è più adatta ai controller più veloci.

|===