---
permalink: concepts/fabricpool-concept.html 
sidebar: sidebar 
keywords: storagegrid, storage grid, fabricpool, cloud tier, local tier, aggregate 
summary: Molti clienti NetApp dispongono di quantità significative di dati memorizzati a cui si accede raramente. Noi chiamiamo dati cold. I clienti hanno anche dati a cui si accede frequentemente, che chiamiamo dati hot. Idealmente, si desidera conservare i dati più caldi sullo storage più veloce per ottenere le migliori performance. I dati cold possono passare a uno storage più lento, purché sia immediatamente disponibile, se necessario. Ma come fai a sapere quali parti dei tuoi dati sono calde e quali sono fredde? 
---
= FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Molti clienti NetApp dispongono di quantità significative di dati memorizzati a cui si accede raramente. Chiamiamo i dati _cold_. I clienti hanno anche dati ai quali si accede frequentemente, che chiamiamo _hot_ data. Idealmente, si desidera conservare i dati più caldi sullo storage più veloce per ottenere le migliori performance. I dati cold possono passare a uno storage più lento, purché sia immediatamente disponibile, se necessario. Ma come fai a sapere quali parti dei tuoi dati sono calde e quali sono fredde?

FabricPool è una funzionalità ONTAP che sposta i dati in modo automatico tra un Tier locale dalle performance elevate e un Tier cloud basato su modelli di accesso. Il tiering libera lo storage locale costoso per i dati hot mantenendo i dati cold prontamente disponibili dallo storage a oggetti a basso costo nel cloud. FabricPool monitora costantemente l'accesso ai dati e sposta i dati tra i Tier per ottenere le migliori performance e il massimo risparmio.

L'utilizzo di FabricPool per il Tier dei dati cold nel cloud è uno dei modi più semplici per ottenere l'efficienza del cloud e creare una configurazione del cloud ibrido. FabricPool funziona a livello di blocchi di storage, quindi funziona sia con i dati di file che con i dati LUN.

Tuttavia, FabricPool non è solo per il tiering dei dati on-premise nel cloud, Molti clienti utilizzano FabricPool in Cloud Volumes ONTAP per eseguire il tiering dei dati cold da uno storage cloud più costoso a uno storage a oggetti a basso costo all'interno del cloud provider. A partire da ONTAP 9,8, è possibile acquisire analisi su volumi abilitati per FabricPool con link:../concept_nas_file_system_analytics_overview.html["Analisi del file system"] o link:../volumes/enable-temperature-sensitive-efficiency-concept.html["efficienza dello storage sensibile alla temperatura"].

Le applicazioni che utilizzano i dati non sono consapevoli del fatto che i dati sono a livelli, pertanto non sono necessarie modifiche alle applicazioni. Il tiering è completamente automatico, quindi non è necessaria alcuna amministrazione in corso.

È possibile memorizzare i dati cold nello storage a oggetti di uno dei principali provider di cloud. Oppure scegli NetApp StorageGRID per conservare i tuoi dati nel tuo cloud privato, per ottenere le massime performance e il controllo completo sui tuoi dati.

.Informazioni correlate
https://docs.netapp.com/us-en/ontap/concept_cloud_overview.html["Documento Gestore di sistema di FabricPool"^]

https://docs.netapp.com/us-en/data-services-cloud-tiering/index.html["NetApp Cloud Tiering"^]

https://www.youtube.com/playlist?list=PLdXI3bZJEw7mcD3RnEcdqZckqKkttoUpS["Elenco di riproduzione FabricPool su NetApp TechComm TV"^]
