---
permalink: concepts/index.html 
sidebar: sidebar 
keywords: decide, concepts, ontap, overview, data, management, cluster storage, high-availability, virtualization, protection, storage, efficiency, security 
summary: I seguenti concetti informano il software di gestione dei dati ONTAP, inclusi storage in cluster, alta disponibilità, virtualizzazione, protezione dei dati, efficienza dello storage e sicurezza. 
---
= Panoramica dei concetti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I seguenti concetti informano il software di gestione dei dati ONTAP, inclusi storage in cluster, alta disponibilità, virtualizzazione, protezione dei dati, efficienza dello storage e sicurezza. Prima di configurare la soluzione di storage, è necessario conoscere la gamma completa di funzionalità e vantaggi di ONTAP.

Per ulteriori informazioni, consultare quanto segue:

* link:../system-admin/index.html["Amministrazione di cluster e SVM"]
* link:../high-availability/index.html["Coppie ad alta disponibilità (ha)"]
* link:../networking/index.html["Gestione di rete e LIF"]
* link:../disks-aggregates/index.html["Gestione di dischi e aggregati"]
* link:../volumes/index.html["FlexVol Volumes, tecnologia FlexClone e funzionalità di efficienza dello storage"]
* link:../san-admin/provision-storage.html["Provisioning host SAN"]
* Accesso al file NAS
+
** link:../nfs-admin/index.html["Gestione NFS"]
** link:../smb-admin/index.html["Gestione delle PMI"]


* link:../data-protection/index.html["Disaster recovery e archiviazione"]

