---
permalink: concepts/manual-pages.html 
sidebar: sidebar 
keywords: CLI commands, manual pages, volume create, volume modify, volume show, volume move, snapmirror show, snapmirror create, vserver create, network interface show, storage disk show, volume delete, man pages, cli comparison tool, cli diff 
summary: Le pagine di manuale di ONTAP spiegano come utilizzare i comandi CLI di ONTAP. Trovare il riferimento al comando per la versione di ONTAP in uso. 
---
= Riferimento al comando ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ogni release principale di ONTAP, i comandi CLI comunemente disponibili (pagine di manuale di ONTAP o pagine man) sono raggruppati in un _riferimento di comando_. Questi riferimenti ai comandi spiegano come utilizzare i comandi CLI in ogni release di ONTAP. Le pagine man sono disponibili anche nella riga di comando di ONTAP con il `man` comando. Per ulteriori informazioni sui comandi descritti in questa procedura, consultare la link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].



== Riferimenti ai comandi per le versioni supportate di ONTAP

* link:https://docs.netapp.com/us-en/ontap-cli/index.html["ONTAP 9.16.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9151/index.html["ONTAP 9.15.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9141/index.html["ONTAP 9.14.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9131/index.html["ONTAP 9.13.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9121/index.html["ONTAP 9.12.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9111/index.html["ONTAP 9.11.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-9101/index.html["ONTAP 9.10.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-991/index.html["ONTAP 9.9.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli-98/index.html["ONTAP 9.8"^]
* link:https://docs.netapp.com/us-en/ontap-cli-97/index.html["ONTAP 9.7"^]
* link:https://docs.netapp.com/us-en/ontap-cli-96/index.html["ONTAP 9.6"^]
* link:https://docs.netapp.com/us-en/ontap-cli-95/index.html["ONTAP 9.5"^]
* link:https://docs.netapp.com/us-en/ontap-cli-93/index.html["ONTAP 9.3"^]




== Riferimenti ai comandi per le versioni a supporto limitato di ONTAP (solo PDF)

* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2843631["ONTAP 9.4"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2674477["ONTAP 9.2"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2573244["ONTAP 9.1"^]




== Tool di confronto CLI

È possibile ottenere informazioni sulle modifiche apportate ai comandi dell'interfaccia della riga di comando (CLI) tra le release di ONTAP utilizzando link:https://mysupport.netapp.com/site/info/cli-comparison["Tool di confronto CLI"^] Sul sito di supporto NetApp.

.Ulteriori letture
* xref:../system-admin/command-line-interface-concept.html[Utilizzare l'interfaccia della riga di comando di ONTAP]
* xref:../system-admin/methods-navigating-cli-command-directories-concept.html[Metodi per navigare nelle directory dei comandi CLI]

