---
permalink: concepts/manual-pages.html 
sidebar: sidebar 
keywords: CLI commands, manual pages, volume create, volume modify, volume show, volume move, snapmirror show, snapmirror create, vserver create, network interface show, storage disk show, volume delete, man pages, cli comparison tool, cli diff 
summary: Le pagine di manuale di ONTAP spiegano come utilizzare i comandi CLI di ONTAP. Trovare il riferimento al comando per la versione di ONTAP in uso. 
---
= Riferimento al comando ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ogni versione principale di ONTAP, i comandi CLI comunemente disponibili (pagine di manuale di ONTAP o pagine man) sono raggruppati in link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^]. Questi riferimenti ai comandi spiegano come utilizzare i comandi CLI in ogni versione ONTAP

Le pagine man sono disponibili anche sulla riga di comando ONTAP con  `man` comando. Scopri di più su  `man` nel link:https://docs.netapp.com/us-en/ontap-cli/man.html["Riferimento al comando ONTAP"^] .



== Riferimenti ai comandi per le versioni a supporto limitato di ONTAP (solo PDF)

* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2843631["ONTAP 9.4"^]




== Tool di confronto CLI

È possibile ottenere informazioni sulle modifiche apportate ai comandi dell'interfaccia della riga di comando (CLI) tra le release di ONTAP utilizzando link:https://mysupport.netapp.com/site/info/cli-comparison["Tool di confronto CLI"^] Sul sito di supporto NetApp.

.Informazioni correlate
* xref:../system-admin/command-line-interface-concept.html[Utilizzare l'interfaccia della riga di comando di ONTAP]
* xref:../system-admin/methods-navigating-cli-command-directories-concept.html[Metodi per navigare nelle directory dei comandi CLI]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["mostra disco di archiviazione"^]

