---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: 'Le offerte Remote Direct Memory Access (RDMA) di ONTAP supportano carichi di lavoro sensibili alla latenza e a elevata larghezza di banda. La funzione RDMA consente la copia dei dati direttamente tra la memoria del sistema di storage e la memoria del sistema host, aggirando le interruzioni e i costi generali della CPU' 
---
= Panoramica di RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le offerte Remote Direct Memory Access (RDMA) di ONTAP supportano carichi di lavoro sensibili alla latenza e a elevata larghezza di banda. RDMA consente di copiare i dati direttamente tra la memoria del sistema di storage e la memoria del sistema host, eludendo le interruzioni della CPU e l'overhead.



== NFS su RDMA

A partire da ONTAP 9.10.1, è possibile eseguire la configurazione link:../nfs-rdma/index.html["NFS su RDMA"] Per consentire l'utilizzo dello storage NVIDIA GPUDirect per carichi di lavoro con accelerazione GPU su host con GPU NVIDIA supportate.


NOTE: RDMA non è supportato con il protocollo SMB.



== RDMA di Cluster Interconnect

Cluster Interconnect RDMA riduce la latenza, diminuisce i tempi di failover e accelera la comunicazione tra i nodi in un cluster.

A partire da ONTAP 9.10.1, cluster Interconnect RDMA è supportato per determinati sistemi hardware, se utilizzato con le schede di rete del cluster X1151A. A partire da ONTAP 9.13.1, le schede di rete X91153A supportano anche la interconnessione in cluster RDMA. Consultare la tabella per sapere quali sistemi sono supportati nelle diverse versioni di ONTAP.

|===
| Sistemi | Versioni di ONTAP supportate 


 a| 
* AFF A50
* AFF A30
* AFF A20
* AFF C80
* AFF C60
* AFF C30
* ASA A50
* ASA A30
* ASA A20

| ONTAP 9.16.1 e versioni successive 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* ASA A1K
* ASA A90
* ASA A70
* FAS90
* FAS70

| ONTAP 9.15.1 e versioni successive 


 a| 
* AFF A900
* ASA A900
* FAS9500

| ONTAP 9.13.1 e versioni successive 


 a| 
* AFF A400
* ASA A400

| ONTAP 9.10.1 e versioni successive 
|===
Dato l'impostazione appropriata del sistema di storage, non è necessaria alcuna configurazione aggiuntiva per utilizzare l'interfaccia RDMA di cluster Interconnect.
