---
permalink: concepts/support-industry-standard-technologies-concept.html 
sidebar: sidebar 
keywords: support, industry-standard, network, technologies 
summary: ONTAP supporta tutte le principali tecnologie di rete standard di settore. Le tecnologie chiave includono IPspaces, bilanciamento del carico DNS e trap SNMP. 
---
= Supporto per tecnologie di rete standard di settore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporta tutte le principali tecnologie di rete standard di settore. Le tecnologie chiave includono IPspaces, bilanciamento del carico DNS e trap SNMP.

I domini di broadcast, i gruppi di failover e le subnet sono descritti nella xref:nas-path-failover-concept.adoc[Failover del percorso NAS].



== IPspaces

È possibile utilizzare un _IPSpace_ per creare uno spazio di indirizzi IP distinto per ciascun server di dati virtuale in un cluster. In questo modo, i client in domini di rete separati a livello amministrativo possono accedere ai dati del cluster utilizzando indirizzi IP sovrapposti dallo stesso intervallo di subnet di indirizzi IP.

Un provider di servizi, ad esempio, potrebbe configurare diversi spazi IP per i tenant utilizzando gli stessi indirizzi IP per accedere a un cluster.



== Bilanciamento del carico DNS

È possibile utilizzare _bilanciamento del carico DNS_ per distribuire il traffico di rete degli utenti tra le porte disponibili. Un server DNS seleziona dinamicamente un'interfaccia di rete per il traffico in base al numero di client montati sull'interfaccia.



== Trap SNMP

È possibile utilizzare _trap SNMP_ per controllare periodicamente la presenza di soglie operative o errori. I trap SNMP catturano le informazioni di monitoraggio del sistema inviate in modo asincrono da un agente SNMP a un gestore SNMP.



== Conformità FIPS

ONTAP è conforme agli standard federali sull'elaborazione delle informazioni (FIPS) 140-2 per tutte le connessioni SSL. È possibile attivare e disattivare la modalità SSL FIPS, impostare i protocolli SSL a livello globale e disattivare le crittografie deboli come RC4.
