---
permalink: nfs-rdma/configure-nics-task.html 
sidebar: sidebar 
keywords: networking, NICs, NFS over RDMA, NVIDIA, NFS, system manager, ports, ethernet ports 
summary: In questo articolo vengono illustrati i processi e i requisiti di configurazione delle piattaforme client-sistema e storage per le schede di rete che utilizzano NFS su RDMA in ONTAP. 
---
= Configurare le NIC per NFS su RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS su RDMA richiede la configurazione NIC sia per il sistema client che per la piattaforma di storage.



== Configurazione della piattaforma di storage

Per informazioni sul supporto RNIC di destinazione, consultare https://hwu.netapp.com/["NetApp Hardware Universe"^] .

Se si utilizza una configurazione ad alta disponibilità (ha), entrambi i nodi devono utilizzare la stessa RNIC per supportare il failover RDMA. La scheda di rete deve essere compatibile con RoCE.

* A partire da ONTAP 9.10.1, è possibile visualizzare un elenco di protocolli di offload RDMA con il comando:
+
[source, cli]
----
network port show -rdma-protocols roce
----
* A partire dal ONTAP 9.16.1, si consiglia di utilizzare il controllo del flusso di priorità (PFC). Configurare il PFC utilizzando il `network port modify` comando:
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin pfc -pfc-queues-admin 3
----
* Prima di ONTAP 9.16.1, si consiglia di utilizzare il controllo di flusso globale predefinito (GFC). Se l'impostazione del controllo di flusso è stata modificata, configurare GFC utilizzando il `network port modify` comando:
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin full
----




== Configurazione del sistema client

Per informazioni sui sistemi operativi client supportati per NFS su RDMA, fare riferimento alla https://imt.netapp.com/matrix/["Matrice di interoperabilità NetApp (IMT)"^] . Per le RNIC supportate da RoCE v2, fare riferimento alla relativa documentazione del fornitore RNIC.

Sebbene sia possibile collegare direttamente il client e il server, si consiglia di utilizzare gli switch per migliorare le prestazioni di failover.

Il client, il server, eventuali switch e tutte le porte degli switch devono essere configurati utilizzando frame jumbo. La configurazione del controllo di flusso su client e switch deve corrispondere alla configurazione del controllo di flusso di ONTAP. A partire da ONTAP 9.16.1, si consiglia di attivare e configurare il controllo di flusso prioritario su ONTAP, sugli switch e sui client. Prima di ONTAP 9.16.1, si consiglia di utilizzare il controllo di flusso globale.

Dopo la conferma di questa configurazione, è possibile montare l'esportazione NFS utilizzando RDMA.

[role="tabbed-block"]
====
.System Manager
--
È necessario utilizzare ONTAP 9.12.1 o versione successiva per configurare le interfacce di rete con NFS su RDMA utilizzando Gestione di sistema.

.Fasi
. Controllare se RDMA è supportato. Accedere a *Network > Ethernet Ports* (rete > Porte Ethernet) e selezionare il nodo appropriato nella vista del gruppo. Quando si espande il nodo, controllare il campo *protocolli RDMA* per una determinata porta: Il valore *RoCE* denota RDMA è supportato; un trattino (*-*) indica che non è supportato.
. Per aggiungere una VLAN, selezionare *+ VLAN*. Selezionare il nodo appropriato. Nel menu a discesa *porta*, le porte disponibili visualizzano il testo *RoCE abilitato* se supportano RDMA. Se non supportano RDMA, non viene visualizzato alcun testo.
. Seguire il flusso di lavoro in xref:../task_nas_enable_linux_nfs.html[Abilitare lo storage NAS per i server Linux utilizzando NFS] Per configurare un nuovo server NFS.
+
Quando si aggiungono interfacce di rete, è possibile selezionare *Usa porte RoCE*. Selezionare questa opzione per tutte le interfacce di rete che si desidera utilizzare NFS su RDMA.



--
.CLI
--
. Controllare se l'accesso RDMA è attivato sul server NFS con il comando:
+
`vserver nfs show-vserver <SVM_name>`

+
Per impostazione predefinita, `-rdma` deve essere attivato. In caso contrario, abilitare l'accesso RDMA sul server NFS:

+
`vserver nfs modify -vserver <SVM_name> -rdma enabled`

. Montare il client tramite NFSv4.0 su RDMA:
+
.. L'input per il parametro proto dipende dalla versione del protocollo IP del server. Se si tratta di IPv4, utilizzare `proto=rdma`. Se si tratta di IPv6, utilizzare `proto=rdma6`.
.. Specificare la porta di destinazione NFS come `port=20049` invece della porta standard 2049:
+
`mount -o vers=4,minorversion=0,proto=rdma,port=20049 <Server_IP_address>:/<volume_path> <mount_point>`



. *OPZIONALE*: Se è necessario smontare il client, eseguire il comando `unmount <mount_path>`


--
====
.Ulteriori informazioni
* xref:../nfs-config/create-server-task.html[Creare un server NFS]
* xref:../task_nas_enable_linux_nfs.html[Abilitare lo storage NAS per i server Linux utilizzando NFS]

