---
permalink: error-messages/configure-snmp-traphosts-event-notifications-task.html 
sidebar: sidebar 
keywords: configuring, snmp, traphosts, receive, event notifications 
summary: Per ricevere le notifiche degli eventi su un host trapSNMP, è necessario configurare un host traphost. 
---
= Configurare i traphost SNMP per ricevere le notifiche degli eventi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ricevere le notifiche degli eventi su un host trapSNMP, è necessario configurare un host traphost.

.Di cosa hai bisogno
* I trap SNMP e SNMP devono essere attivati sul cluster.
+
[NOTE]
====
I trap SNMP e SNMP sono attivati per impostazione predefinita.

====
* Il DNS deve essere configurato sul cluster per risolvere i nomi degli host trapezoidali.


.A proposito di questa attività
Se non si dispone già di un host trapSNMP configurato per ricevere notifiche di eventi (trap SNMP), è necessario aggiungerne uno.

È possibile eseguire questa attività ogni volta che il cluster è in esecuzione immettendo i comandi nella riga di comando ONTAP.

.Fase
. Se l'ambiente non dispone già di un host trapSNMP configurato per ricevere le notifiche degli eventi, aggiungerne uno:
+
`system snmp traphost add -peer-address _snmp_traphost_name_`

+
Tutte le notifiche degli eventi supportate da SNMP per impostazione predefinita vengono inoltrate all'host principale SNMP.


