---
permalink: error-messages/index.html 
sidebar: sidebar 
keywords: ems, configuration, event, management, system, events, notifications 
summary: 'È possibile configurare rapidamente ONTAP in modo che invii notifiche di eventi EMS (sistema di gestione degli eventi) importanti direttamente a un indirizzo e-mail, a un server syslog o a un traphost SNMP (Simple Management Network Protocol), in modo da ricevere immediatamente una notifica dei problemi di sistema che richiedono un"attenzione immediata.' 
---
= Panoramica della configurazione EMS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare ONTAP 9 in modo che invii notifiche di eventi EMS (sistema di gestione degli eventi) importanti direttamente a un indirizzo e-mail, a un server syslog, a un traphost SNMP (Simple Management Network Protocol) o a un'applicazione webhook, in modo da ricevere una notifica immediata dei problemi di sistema che richiedono un'attenzione immediata.

Poiché le notifiche di eventi importanti non sono attivate per impostazione predefinita, è necessario configurare EMS in modo che invii le notifiche a un indirizzo e-mail, a un server syslog, a un host trapSNMP o a un'applicazione webhook.

Esaminare le versioni specifiche della release di link:https://docs.netapp.com/us-en/ontap-ems-9131/["Riferimento EMS ONTAP 9"^].

Se la mappatura degli eventi EMS utilizza set di comandi ONTAP deprecati (come destinazione dell'evento, percorso dell'evento), si consiglia di aggiornare la mappatura. link:https://docs.netapp.com/us-en/ontap/error-messages/convert-ems-routing-to-notifications-task.html["Scopri come aggiornare la mappatura EMS da comandi ONTAP non aggiornati"^].
