---
permalink: nfs-admin/commands-manage-local-unix-groups-reference.html 
sidebar: sidebar 
keywords: command, manage, local, unix, group 
summary: Esistono comandi ONTAP specifici per la gestione dei gruppi UNIX locali. 
---
= Comandi per la gestione di gruppi UNIX locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono comandi ONTAP specifici per la gestione dei gruppi UNIX locali.

[cols="35,65"]
|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare un gruppo UNIX locale
 a| 
`vserver services name-service unix-group create`



 a| 
Aggiungere un utente a un gruppo UNIX locale
 a| 
`vserver services name-service unix-group adduser`



 a| 
Caricare i gruppi UNIX locali da un URI
 a| 
`vserver services name-service unix-group load-from-uri`



 a| 
Visualizzare i gruppi UNIX locali
 a| 
`vserver services name-service unix-group show`



 a| 
Modificare un gruppo UNIX locale
 a| 
`vserver services name-service unix-group modify`



 a| 
Eliminare un utente da un gruppo UNIX locale
 a| 
`vserver services name-service unix-group deluser`



 a| 
Eliminare un gruppo UNIX locale
 a| 
`vserver services name-service unix-group delete`

|===
Per ulteriori informazioni, consulta la pagina man relativa a ciascun comando.
