---
permalink: nfs-admin/commands-manage-name-service-switch-entries-reference.html 
sidebar: sidebar 
keywords: command, manage, name, service, switch, entry 
summary: È possibile gestire le voci di name service switch creandole, visualizzandole, modificandole ed eliminandole. 
---
= Comandi ONTAP per la gestione delle voci di commutazione del servizio nomi NAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire le voci di name service switch creandole, visualizzandole, modificandole ed eliminandole.

[cols="35,65"]
|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare una voce name service switch
 a| 
`vserver services name-service ns-switch create`



 a| 
Nome visualizzato voci switch servizio
 a| 
`vserver services name-service ns-switch show`



 a| 
Modificare una voce di name service switch
 a| 
`vserver services name-service ns-switch modify`



 a| 
Consente di eliminare una voce di switch name service
 a| 
`vserver services name-service ns-switch delete`

|===
Ulteriori informazioni su `vserver services name-service ns-switch` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+ns-switch["Riferimento al comando ONTAP"^].

.Informazioni correlate
https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Report tecnico di NetApp 4668: Guida alle Best practice per i servizi di nome"^]
