---
permalink: nfs-admin/commands-manage-local-netgroups-reference.html 
sidebar: sidebar 
keywords: command, manage, local, netgroup 
summary: È possibile gestire i netgroup locali caricandoli da un URI, verificandone lo stato tra i nodi, visualizzandoli ed eliminandoli. 
---
= Comandi per la gestione dei netgroup locali in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire i netgroup locali caricandoli da un URI, verificandone lo stato tra i nodi, visualizzandoli ed eliminandoli.

[cols="35,65"]
|===


| Se si desidera... | Utilizzare il comando... 


 a| 
Caricare i netgroup da un URI
 a| 
`vserver services name-service netgroup load`



 a| 
Verificare lo stato dei netgroup nei nodi
 a| 
`vserver services name-service netgroup status`

Disponibile a un livello di privilegio avanzato e superiore.



 a| 
Visualizzare i netgroup locali
 a| 
`vserver services name-service netgroup file show`



 a| 
Eliminare un netgroup locale
 a| 
`vserver services name-service netgroup file delete`

|===
Ulteriori informazioni su `vserver services name-service netgroup file` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+netgroup+file["Riferimento al comando ONTAP"^].
