---
permalink: nfs-admin/commands-manage-ldap-client-schema-templates-reference.html 
sidebar: sidebar 
keywords: command, manage, ldap, client, schema, template 
summary: Esistono comandi ONTAP specifici per la gestione dei modelli di schema del client LDAP. 
---
= Comandi ONTAP per la gestione dei modelli di schema del client LDAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono comandi ONTAP specifici per la gestione dei modelli di schema del client LDAP.

[NOTE]
====
Gli amministratori di SVM non possono modificare o eliminare gli schemi client LDAP creati dagli amministratori del cluster.

====
[cols="35,65"]
|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Copiare un modello di schema LDAP esistente
 a| 
`vserver services name-service ldap client schema copy` Disponibile a un livello di privilegio avanzato e superiore.



 a| 
Visualizzare i modelli di schema LDAP
 a| 
`vserver services name-service ldap client schema show`



 a| 
Modificare un modello di schema LDAP
 a| 
`vserver services name-service ldap client schema modify` Disponibile a un livello di privilegio avanzato e superiore.



 a| 
Eliminare un modello di schema LDAP
 a| 
`vserver services name-service ldap client schema delete` Disponibile a un livello di privilegio avanzato e superiore.

|===
Ulteriori informazioni su `vserver services name-service ldap client schema` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+ldap+client+schema["Riferimento al comando ONTAP"^].
