---
permalink: nfs-admin/commands-manage-ldap-client-config-reference.html 
sidebar: sidebar 
keywords: command, manage, ldap, client, configuration 
summary: Esistono comandi ONTAP specifici per la gestione delle configurazioni del client LDAP. 
---
= Comandi per la gestione delle configurazioni del client LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono comandi ONTAP specifici per la gestione delle configurazioni del client LDAP.

[NOTE]
====
Gli amministratori SVM non possono modificare o eliminare le configurazioni client LDAP create dagli amministratori del cluster.

====
[cols="35,65"]
|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare una configurazione del client LDAP
 a| 
`vserver services name-service ldap client create`



 a| 
Visualizzare le configurazioni del client LDAP
 a| 
`vserver services name-service ldap client show`



 a| 
Modificare una configurazione del client LDAP
 a| 
`vserver services name-service ldap client modify`



 a| 
Modificare la password BIND del client LDAP
 a| 
`vserver services name-service ldap client modify-bind-password`



 a| 
Eliminare una configurazione del client LDAP
 a| 
`vserver services name-service ldap client delete`

|===
Per ulteriori informazioni, consulta la pagina man relativa a ciascun comando.
