---
permalink: nfs-admin/control-root-user-access-ntfs-security-data-task.html 
sidebar: sidebar 
keywords: control, root, user, access, ntfs, security, style, data 
summary: 'È possibile configurare ONTAP per consentire ai client NFS di accedere ai dati di sicurezza NTFS e ai client NTFS per accedere ai dati di sicurezza NFS. Quando si utilizza lo stile di sicurezza NTFS su un archivio dati NFS, è necessario decidere come trattare l"accesso da parte dell"utente root e configurare di conseguenza la macchina virtuale di storage (SVM).' 
---
= Controllare l'accesso dell'utente root ai dati di sicurezza NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare ONTAP per consentire ai client NFS di accedere ai dati di sicurezza NTFS e ai client NTFS per accedere ai dati di sicurezza NFS. Quando si utilizza lo stile di sicurezza NTFS su un archivio dati NFS, è necessario decidere come trattare l'accesso da parte dell'utente root e configurare di conseguenza la macchina virtuale di storage (SVM).

.A proposito di questa attività
Quando un utente root accede ai dati di sicurezza NTFS, sono disponibili due opzioni:

* Mappare l'utente root a un utente Windows come qualsiasi altro utente NFS e gestire l'accesso in base agli ACL NTFS.
* Ignorare gli ACL NTFS e fornire l'accesso completo all'utente root.


.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

. Eseguire l'azione desiderata:
+
[cols="35,65"]
|===


| Se si desidera che l'utente root... | Immettere il comando... 


 a| 
Essere mappato a un utente Windows
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root disabled`



 a| 
Ignorare il controllo dell'ACL NT
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root enabled`

|===
+
Per impostazione predefinita, questo parametro è disattivato.

+
Se questo parametro è attivato ma non esiste alcuna mappatura dei nomi per l'utente root, ONTAP utilizza una credenziale di amministratore SMB predefinita per il controllo.

. Tornare al livello di privilegio admin:
+
`set -privilege admin`


