---
permalink: nfs-admin/create-name-mapping-task.html 
sidebar: sidebar 
keywords: create, name, mapping 
summary: È possibile utilizzare il comando vserver name-mapping create per creare una mappatura dei nomi. Si utilizzano le mappature dei nomi per consentire agli utenti Windows di accedere ai volumi di sicurezza UNIX e viceversa. 
---
= Creare mappature dei nomi per le SVM NAS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `vserver name-mapping create` per creare una mappatura dei nomi. Si utilizzano le mappature dei nomi per consentire agli utenti Windows di accedere ai volumi di sicurezza UNIX e viceversa.

.A proposito di questa attività
Per ogni SVM, ONTAP supporta fino a 12,500 mappature di nomi per ciascuna direzione.

.Fase
. Creazione di una mappatura dei nomi:
+
`vserver name-mapping create -vserver vserver_name -direction {krb-unix|win-unix|unix-win} -position integer -pattern text -replacement text`

+
[NOTE]
====
Le `-pattern` istruzioni e `-replacement` possono essere formulate come espressioni regolari. È inoltre possibile utilizzare l' `-replacement`istruzione per negare esplicitamente un mapping all'utente utilizzando la stringa di sostituzione null `" "` (il carattere di spazio). Ulteriori informazioni su `vserver name-mapping create` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-name-mapping-create.html["Riferimento al comando ONTAP"^].

====
+
Quando vengono create mappature da Windows a UNIX, tutti i client SMB che hanno connessioni aperte al sistema ONTAP al momento della creazione delle nuove mappature devono disconnettersi e riconnessi per visualizzare le nuove mappature.



.Esempi
Il seguente comando crea un mapping dei nomi sulla SVM denominata vs1. Il mapping è un mapping da UNIX a Windows nella posizione 1 nell'elenco delle priorità. Il mapping associa l'utente UNIX Johnd all'utente Windows ENG/JohnDoe.

[listing]
----
vs1::> vserver name-mapping create -vserver vs1 -direction unix-win -position 1 -pattern johnd
-replacement "ENG\\JohnDoe"
----
Il seguente comando crea un'altra mappatura dei nomi sulla SVM denominata vs1. Il mapping è un mapping da Windows a UNIX nella posizione 1 nell'elenco delle priorità. Qui il modello e la sostituzione includono espressioni regolari. Il mapping associa ogni utente CIFS nel dominio ENG agli utenti nel dominio LDAP associato alla SVM.

[listing]
----
vs1::> vserver name-mapping create -vserver vs1 -direction win-unix -position 1 -pattern "ENG\\(.+)"
-replacement "\1"
----
Il seguente comando crea un'altra mappatura dei nomi sulla SVM denominata vs1. Qui il modello include "``" come elemento nel nome utente di Windows che deve essere escapato. La mappatura mappa l'utente Windows ENG all'utente UNIX john_Ops.

[listing]
----
vs1::> vserver name-mapping create -direction win-unix -position 1 -pattern ENG\\john\$ops
-replacement john_ops
----