---
permalink: nfs-admin/decide-security-style-svm-flexvol-concept.html 
sidebar: sidebar 
keywords: decide, security, style, svm 
summary: Per aiutarti a decidere quale stile di sicurezza utilizzare su un volume, devi considerare due fattori. Il fattore principale è il tipo di amministratore che gestisce il file system. Il fattore secondario è il tipo di utente o servizio che accede ai dati sul volume. 
---
= Decidere quale stile di sicurezza utilizzare sulle SVM NAS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aiutarti a decidere quale stile di sicurezza utilizzare su un volume, devi considerare due fattori. Il fattore principale è il tipo di amministratore che gestisce il file system. Il fattore secondario è il tipo di utente o servizio che accede ai dati sul volume.

Quando si configura lo stile di protezione su un volume, è necessario considerare le esigenze dell'ambiente per assicurarsi di selezionare lo stile di protezione migliore ed evitare problemi con la gestione delle autorizzazioni. Le seguenti considerazioni possono aiutarti a decidere:

[cols="20,80"]
|===


| Stile di sicurezza | Scegliere se... 


 a| 
UNIX
 a| 
* Il file system è gestito da un amministratore UNIX.
* La maggior parte degli utenti sono client NFS.
* Un'applicazione che accede ai dati utilizza un utente UNIX come account del servizio.




 a| 
NTFS
 a| 
* Il file system è gestito da un amministratore di Windows.
* La maggior parte degli utenti è costituita da client SMB.
* Un'applicazione che accede ai dati utilizza un utente Windows come account del servizio.




 a| 
Misto
 a| 
* Il file system è gestito dagli amministratori UNIX e Windows e gli utenti sono costituiti da client NFS e SMB.


|===