---
permalink: nfs-admin/display-ldap-statistics-task.html 
sidebar: sidebar 
keywords: display, ldap, statistics 
summary: 'È possibile visualizzare le statistiche LDAP per le macchine virtuali di archiviazione (SVM) su un sistema di archiviazione per monitorare le prestazioni e diagnosticare i problemi.' 
---
= Visualizza le statistiche LDAP per gli SVM NFS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare le statistiche LDAP per le macchine virtuali di archiviazione (SVM) su un sistema di archiviazione per monitorare le prestazioni e diagnosticare i problemi.

.Prima di iniziare
* È necessario aver configurato un client LDAP su SVM.
* Gli oggetti LDAP da cui è possibile visualizzare i dati devono essere stati identificati.


.Fase
. Visualizzare i dati delle performance per gli oggetti del contatore:
+
`statistics show`



.Esempi
Nell'esempio seguente vengono visualizzate le statistiche per l'esempio denominato *smpl_1* per i contatori: avg_processor_busy e cpu_busy

[listing]
----
cluster1::*> statistics start -object system -counter avg_processor_busy|cpu_busy -sample-id smpl_1
Statistics collection is being started for Sample-id: smpl_1

cluster1::*> statistics stop -sample-id smpl_1
Statistics collection is being stopped for Sample-id: smpl_1

cluster1::*> statistics show -sample-id smpl_1
Object: system
Instance: cluster
Start-time: 8/2/2012 18:27:53
End-time: 8/2/2012 18:27:56
Cluster: cluster1
   Counter                                                     Value
   -------------------------------- --------------------------------
   avg_processor_busy                                             6%
   cpu_busy
----
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["le statistiche mostrano"^]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["inizio delle statistiche"^]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-stop.html["le statistiche si fermano"^]

