---
permalink: nfs-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, nfs, statistics 
summary: 'È possibile visualizzare le statistiche NFS per le macchine virtuali di storage (SVM) sul sistema storage per monitorare le performance e diagnosticare i problemi.' 
---
= Visualizza le statistiche per gli SVM NFS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare le statistiche NFS per le macchine virtuali di storage (SVM) sul sistema storage per monitorare le performance e diagnosticare i problemi.

.Fasi
. Utilizzare `statistics catalog object show` Per identificare gli oggetti NFS da cui è possibile visualizzare i dati.
+
`statistics catalog object show -object nfs*`

. Utilizzare `statistics start` e opzionale `statistics stop` comandi per raccogliere un campione di dati da uno o più oggetti.
. Utilizzare `statistics show` per visualizzare i dati di esempio.


.Esempio: Monitoraggio delle performance di NFSv3
L'esempio seguente mostra i dati relativi alle prestazioni per il protocollo NFSv3.

Il seguente comando avvia la raccolta dati per un nuovo campione:

[listing]
----
vs1::> statistics start -object nfsv3 -sample-id nfs_sample
----
Il comando seguente mostra i dati dell'esempio specificando i contatori che mostrano il numero di richieste di lettura e scrittura riuscite rispetto al numero totale di richieste di lettura e scrittura:

[listing]
----

vs1::> statistics show -sample-id nfs_sample -counter read_total|write_total|read_success|write_success

Object: nfsv3
Instance: vs1
Start-time: 2/11/2013 15:38:29
End-time: 2/11/2013 15:38:41
Cluster: cluster1

    Counter                                           Value
    --------------------------- ---------------------------
    read_success                                      40042
    read_total                                        40042
    write_success                                   1492052
    write_total                                     1492052
----
.Informazioni correlate
* link:../performance-config/index.html["Configurazione del monitoraggio delle performance"]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-catalog-object-show.html["catalogo statistiche oggetto mostra"^]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["le statistiche mostrano"^]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["inizio delle statistiche"^]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-stop.html["le statistiche si fermano"^]

