---
permalink: nfs-admin/display-ldap-statistics-task.html 
sidebar: sidebar 
keywords: display, ldap, statistics 
summary: 'A partire da ONTAP 9.2, è possibile visualizzare le statistiche LDAP per le macchine virtuali di storage (SVM) su un sistema storage per monitorare le performance e diagnosticare i problemi.' 
---
= Visualizzare le statistiche LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.2, è possibile visualizzare le statistiche LDAP per le macchine virtuali di storage (SVM) su un sistema storage per monitorare le performance e diagnosticare i problemi.

.Di cosa hai bisogno
* È necessario aver configurato un client LDAP su SVM.
* Gli oggetti LDAP da cui è possibile visualizzare i dati devono essere stati identificati.


.Fase
. Visualizzare i dati delle performance per gli oggetti del contatore:
+
`statistics show`



.Esempi
Nell'esempio riportato di seguito vengono illustrati i dati relativi alle prestazioni per l'oggetto `secd_external_service_op`:

[listing]
----
cluster::*> statistics show -vserver vserverName -object secd_external_service_op -instance “vserverName:LDAP (NIS & Name Mapping):GetUserInfoFromName:1.1.1.1”

Object: secd_external_service_op
Instance: vserverName:LDAP (NIS & Name Mapping):GetUserInfoFromName:1.1.1.1
Start-time: 4/13/2016 22:15:38
End-time: 4/13/2016 22:15:38
Scope: vserverName
Counter                            Value
-------------------------------- --------------------------------
instance_name                      vserverName:LDAP (NIS & Name
                                   Mapping):GetUserInfoFromName:
                                   1.1.1.1
last_modified_time                 1460610787
node_name                          nodeName
num_not_found_responses            1
num_request_failures               1
num_requests_sent                  1
num_responses_received             1
num_successful_responses           0
num_timeouts                       0
operation                          GetUserInfoFromName
process_name                       secd
request_latency                    52131us
----