---
permalink: nfs-admin/enable-disable-vmware-vstorage-over-nfs-task.html 
sidebar: sidebar 
keywords: enable, disable, vmware, vstorage, nfs 
summary: 'È possibile attivare o disattivare il supporto per VMware vStorage su NFS su macchine virtuali di storage (SVM) utilizzando il comando vserver nfs modify.' 
---
= Abilitare o disabilitare VMware vStorage su ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare o disattivare il supporto per VMware vStorage su NFS su macchine virtuali di storage (SVM) utilizzando `vserver nfs modify` comando.

.A proposito di questa attività
Per impostazione predefinita, il supporto di VMware vStorage su NFS è disattivato.

.Fasi
. Visualizzare lo stato corrente del supporto vStorage per le SVM:
+
`vserver nfs show -vserver vserver_name -instance`

. Eseguire una delle seguenti operazioni:
+
[cols="2*"]
|===
| Se si desidera... | Immettere il seguente comando... 


 a| 
Abilitare il supporto di VMware vStorage
 a| 
`vserver nfs modify -vserver vserver_name -vstorage enabled`



 a| 
Disattivare il supporto di VMware vStorage
 a| 
`vserver nfs modify -vserver vserver_name -vstorage disabled`

|===


.Al termine
Prima di utilizzare questa funzionalità, è necessario installare il plug-in NFS per VMware VAAI. Per ulteriori informazioni, consulta la sezione _Installazione del plug-in NetApp NFS per VMware VAAI_.

.Informazioni correlate
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61278["Documentazione NetApp: Plug-in NetApp NFS per VMware VAAI"^]
