---
permalink: nfs-admin/enable-disable-nfsv4-referrals-task.html 
sidebar: sidebar 
keywords:  
summary: 'Puoi abilitare i riferimenti NFSv4 sulle macchine virtuali di storage attivando le opzioni -v4-fsid-change e -v4.0-referrals o -v4.1-referrals. L"attivazione dei riferimenti NFSV4 può accelerare l"accesso ai dati per i client NFSv4 che supportano questa funzionalità.' 
---
= Abilitare o disabilitare i riferimenti NFSv4 per le SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare i riferimenti NFSv4 sulle macchine virtuali di storage (SVM) attivando le opzioni `-v4-fsid-change` e. ``-v4.0-referrals``oppure. L'attivazione dei riferimenti NFSV4 può accelerare l'accesso ai dati per i client NFSv4 che supportano questa funzionalità.

.Prima di iniziare
Se si desidera attivare i riferimenti NFS, è necessario prima disattivare Parallel NFS. Non è possibile attivare entrambi contemporaneamente.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===


| Se si desidera... | Immettere il comando... 


 a| 
Abilitare i riferimenti NFSv4
 a| 
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.0-referrals enabled`



 a| 
Disattiva i riferimenti NFSv4
 a| 
`vserver nfs modify -vserver vserver_name -v4.0-referrals disabled`



 a| 
Abilitare i riferimenti NFSv4.1
 a| 
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.1-referrals enabled`



 a| 
Disattiva i riferimenti NFSv4.1
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-referrals disabled`

|===
. Tornare al livello di privilegio admin:
+
`set -privilege admin`


