---
permalink: nfs-admin/enable-disable-pnfs-task.html 
sidebar: sidebar 
keywords: enable, disable, pnfs 
summary: 'PNFS migliora le performance consentendo ai client NFS di eseguire operazioni di lettura/scrittura direttamente e in parallelo sui dispositivi di storage, ignorando il server NFS come potenziale collo di bottiglia. Per attivare o disattivare pNFS (Parallel NFS), è possibile modificare l"opzione -v4.1-pnfs.' 
---
= Abilitare o disabilitare pNFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PNFS migliora le performance consentendo ai client NFS di eseguire operazioni di lettura/scrittura direttamente e in parallelo sui dispositivi di storage, ignorando il server NFS come potenziale collo di bottiglia. Per attivare o disattivare pNFS (Parallel NFS), è possibile modificare `-v4.1-pnfs` opzione.

[cols="50,50"]
|===
| Se la versione di ONTAP è... | Il valore predefinito di pNFS è... 


| 9.8 o versione successiva | disattivato 


| 9.7 o versioni precedenti | attivato 
|===
.Di cosa hai bisogno
Il supporto di NFSv4.1 è necessario per poter utilizzare pNFS.

Se si desidera attivare pNFS, è necessario prima disattivare i riferimenti NFS. Non è possibile abilitare entrambi contemporaneamente.

Se si utilizza pNFS con Kerberos su SVM, è necessario attivare Kerberos su ogni LIF su SVM.

.Fase
. Eseguire una delle seguenti operazioni:
+
[cols="2*"]
|===
| Se si desidera... | Immettere il comando... 


 a| 
Abilitare pNFS
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-pnfs enabled`



 a| 
Disattiva pNFS
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-pnfs disabled`

|===


.Informazioni correlate
* xref:../nfs-trunking/index.html[Panoramica del trunking NFS]

