---
permalink: nfs-admin/enable-disable-nfsv4-read-file-delegations-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, read, file, delegation 
summary: 'Per attivare o disattivare le deleghe dei file di lettura NFSv4, è possibile modificare l"opzione -v4.0-Read-delegate o -v4.1-Read-delegate. Attivando le deleghe dei file di lettura, è possibile eliminare gran parte dell"overhead dei messaggi associato all"apertura e alla chiusura dei file.' 
---
= Abilitare o disabilitare le deleghe di lettura dei file NFSv4 per le SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per attivare o disattivare le deleghe dei file di lettura NFSv4, è possibile modificare ``-v4.0-read-delegation``oppure opzione. Attivando le deleghe dei file di lettura, è possibile eliminare gran parte dell'overhead dei messaggi associato all'apertura e alla chiusura dei file.

.A proposito di questa attività
Per impostazione predefinita, le deleghe dei file di lettura sono disattivate.

Lo svantaggio dell'abilitazione delle deleghe dei file in lettura consiste nel fatto che il server e i suoi client devono ripristinare le deleghe dopo il riavvio o il riavvio del server, il riavvio o il riavvio di un client o la creazione di una partizione di rete.

.Fase
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===


| Se si desidera... | Quindi... 


 a| 
Abilitare le deleghe dei file di lettura NFSv4
 a| 
Immettere il seguente comando:

`vserver nfs modify -vserver vserver_name -v4.0-read-delegation enabled`



 a| 
Abilitare le deleghe dei file di lettura NFSv4.1
 a| 
Immettere il seguente comando:

+
`vserver nfs modify -vserver vserver_name -v4.1-read-delegation enabled`



 a| 
Disattiva le deleghe dei file di lettura NFSv4
 a| 
Immettere il seguente comando:

`vserver nfs modify -vserver vserver_name -v4.0-read-delegation disabled`



 a| 
Disattiva le deleghe dei file di lettura NFSv4.1
 a| 
Immettere il seguente comando:

`vserver nfs modify -vserver vserver_name -v4.1-read-delegation disabled`

|===


.Risultato
Le opzioni di delega dei file diventano effettive non appena vengono modificate. Non è necessario riavviare NFS.
