---
permalink: nfs-admin/enable-disable-nfsv4-write-file-delegations-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, write, file, delegation 
summary: 'Per attivare o disattivare le deleghe dei file di scrittura, è possibile modificare l"opzione -v4.0-write-delegate o -v4.1-write-delegate. Attivando le deleghe di scrittura dei file, è possibile eliminare gran parte dell"overhead dei messaggi associato al blocco di file e record, oltre all"apertura e alla chiusura dei file.' 
---
= Attivare o disattivare le deleghe dei file di scrittura NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per attivare o disattivare le deleghe dei file di scrittura, è possibile modificare ``-v4.0-write-delegation``oppure opzione. Attivando le deleghe di scrittura dei file, è possibile eliminare gran parte dell'overhead dei messaggi associato al blocco di file e record, oltre all'apertura e alla chiusura dei file.

.A proposito di questa attività
Per impostazione predefinita, le deleghe dei file di scrittura sono disattivate.

Lo svantaggio di abilitare le deleghe dei file di scrittura è che il server e i relativi client devono eseguire attività aggiuntive per ripristinare le deleghe dopo il riavvio o il riavvio del server, il riavvio o il riavvio di un client o la creazione di una partizione di rete.

.Fase
. Eseguire una delle seguenti operazioni:
+
[cols="2*"]
|===
| Se si desidera... | Quindi... 


 a| 
Abilitare le deleghe dei file di scrittura NFSv4
 a| 
Immettere il seguente comando: `vserver nfs modify -vserver vserver_name -v4.0-write-delegation enabled`



 a| 
Abilitare le deleghe dei file di scrittura NFSv4.1
 a| 
Immettere il seguente comando: `vserver nfs modify -vserver vserver_name -v4.1-write-delegation enabled`



 a| 
Disattiva le deleghe dei file di scrittura NFSv4
 a| 
Immettere il seguente comando: `vserver nfs modify -vserver vserver_name -v4.0-write-delegation disabled`



 a| 
Disattivare le deleghe dei file di scrittura NFSv4.1
 a| 
Immettere il seguente comando: `vserver nfs modify -vserver vserver_name -v4.1-write-delegation disabled`

|===


.Risultato
Le opzioni di delega dei file diventano effettive non appena vengono modificate. Non è necessario riavviare NFS.
