---
permalink: nfs-admin/enable-disable-rquota-support-task.html 
sidebar: sidebar 
keywords: enable, disable, rquota, support 
summary: 'Il protocollo rquota remoto (rquota) consente ai client NFS di ottenere informazioni sulle quote per gli utenti da un computer remoto. Il supporto per le versioni rquota varia in base alla versione di ONTAP in uso.' 
---
= Abilitare o disabilitare il supporto rquota su SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il protocollo rquota remoto (rquota) consente ai client NFS di ottenere informazioni sulle quote per gli utenti da un computer remoto. Il supporto per le versioni rquota varia in base alla versione di ONTAP in uso.

* Rquota v1 è supportato in ONTAP 9 e versioni successive.
* Rquota v2 è supportato in ONTAP 9.12.1 e versioni successive.


.A proposito di questa attività
Per impostazione predefinita, rquota è disattivato.

.Fase
. Abilitare o disabilitare rquota:
+
[cols="2*"]
|===
| Se si desidera... | Immettere il seguente comando... 


 a| 
Abilitare il supporto rquota per le SVM
 a| 
[source, cli]
----
vserver nfs modify -vserver vserver_name -rquota enable
----


 a| 
Disattiva il supporto rquota per le SVM
 a| 
[source, cli]
----
vserver nfs modify -vserver vserver_name -rquota disable
----
|===
+
Per ulteriori informazioni sulle quote, vedere link:../volumes/index.html["Gestione dello storage logico"].


