---
permalink: nfs-admin/limits-local-unix-users-groups--concept.html 
sidebar: sidebar 
keywords: limit, local, unix, user, group, member 
summary: ONTAP ha introdotto limiti per il numero massimo di utenti e gruppi UNIX nel cluster e comandi per gestire questi limiti. Questi limiti possono aiutare a evitare problemi di performance impedendo agli amministratori di creare troppi utenti e gruppi UNIX locali nel cluster. 
---
= Limiti per utenti UNIX locali, gruppi e membri del gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ha introdotto limiti per il numero massimo di utenti e gruppi UNIX nel cluster e comandi per gestire questi limiti. Questi limiti possono aiutare a evitare problemi di performance impedendo agli amministratori di creare troppi utenti e gruppi UNIX locali nel cluster.

Esiste un limite per il numero combinato di gruppi di utenti UNIX locali e di membri del gruppo. Esiste un limite separato per gli utenti UNIX locali. I limiti sono a livello di cluster. Ciascuno di questi nuovi limiti viene impostato su un valore predefinito che è possibile modificare fino a un limite massimo preassegnato.

[cols="3*"]
|===
| Database | Limite predefinito | Limite massimo 


 a| 
Utenti UNIX locali
 a| 
32,768
 a| 
65,536



 a| 
Gruppi UNIX locali e membri del gruppo
 a| 
32,768
 a| 
65,536

|===