---
permalink: nfs-admin/manage-limits-local-unix-users-groups-task.html 
sidebar: sidebar 
keywords: manage, limit, local, unix, user, group 
summary: Esistono comandi ONTAP specifici per la gestione dei limiti per utenti e gruppi UNIX locali. Gli amministratori dei cluster possono utilizzare questi comandi per risolvere i problemi di performance nel cluster che si ritiene siano correlati a un numero eccessivo di utenti e gruppi UNIX locali. 
---
= Gestire i limiti per utenti e gruppi UNIX locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono comandi ONTAP specifici per la gestione dei limiti per utenti e gruppi UNIX locali. Gli amministratori dei cluster possono utilizzare questi comandi per risolvere i problemi di performance nel cluster che si ritiene siano correlati a un numero eccessivo di utenti e gruppi UNIX locali.

.A proposito di questa attività
Questi comandi sono disponibili per l'amministratore del cluster a livello di privilegi avanzati.

.Fase
. Eseguire una delle seguenti operazioni:
+
[cols="2*"]
|===
| Se si desidera... | Utilizzare il comando... 


 a| 
Visualizza informazioni sui limiti utente UNIX locali
 a| 
`vserver services unix-user max-limit show`



 a| 
Visualizza informazioni sui limiti dei gruppi UNIX locali
 a| 
`vserver services unix-group max-limit show`



 a| 
Modificare i limiti utente UNIX locali
 a| 
`vserver services unix-user max-limit modify`



 a| 
Modificare i limiti dei gruppi UNIX locali
 a| 
`vserver services unix-group max-limit modify`

|===
+
Per ulteriori informazioni, consulta la pagina man relativa a ciascun comando.


