---
permalink: nfs-admin/modify-credential-cache-time-to-live-reference.html 
sidebar: sidebar 
keywords: reason, modify, nfs, credential, cache, time, live 
summary: 'La modifica del TTL (Time-to-live) della cache delle credenziali NFS può aiutare a risolvere i problemi in diversi scenari. È necessario comprendere quali sono questi scenari e le conseguenze di tali modifiche.' 
---
= Motivi per la modifica del time-to-live della cache delle credenziali NFS per le SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utilizza una cache delle credenziali per memorizzare le informazioni necessarie per l'autenticazione dell'utente per l'accesso all'esportazione NFS, in modo da fornire un accesso più rapido e migliorare le performance. È possibile configurare per quanto tempo le informazioni vengono memorizzate nella cache delle credenziali per personalizzarle in base all'ambiente in uso.

La modifica del TTL (Time-to-live) della cache delle credenziali NFS può aiutare a risolvere i problemi in diversi scenari. È necessario comprendere quali sono questi scenari e le conseguenze di tali modifiche.



== Motivi

Modificare il TTL predefinito nei seguenti casi:

[cols="2*"]
|===
| Problema | Azione correttiva 


 a| 
I name server nel tuo ambiente stanno riscontrando un peggioramento delle performance dovuto a un elevato carico di richieste da parte di ONTAP.
 a| 
Aumentare il TTL per le credenziali positive e negative memorizzate nella cache per ridurre il numero di richieste da ONTAP ai server dei nomi.



 a| 
L'amministratore del name server ha apportato delle modifiche per consentire l'accesso agli utenti NFS precedentemente rifiutati.
 a| 
Ridurre il TTL per le credenziali negative memorizzate nella cache per ridurre il tempo di attesa che gli utenti NFS debbano attendere che ONTAP richieda nuove credenziali ai server dei nomi esterni in modo che possano accedervi.



 a| 
L'amministratore del name server ha apportato delle modifiche per negare l'accesso agli utenti NFS precedentemente autorizzati.
 a| 
Riduci il TTL per le credenziali positive memorizzate nella cache per ridurre il tempo prima che ONTAP richieda nuove credenziali ai server dei nomi esterni, in modo che gli utenti NFS non possano accedere.

|===


== Conseguenze

È possibile modificare la durata del tempo singolarmente per il caching delle credenziali positive e negative. Tuttavia, è necessario essere consapevoli dei vantaggi e degli svantaggi di tale operazione.

[cols="3*"]
|===
| Se... | Il vantaggio è... | Lo svantaggio è... 


 a| 
Aumentare il tempo di cache delle credenziali positive
 a| 
ONTAP invia le richieste di credenziali ai server dei nomi con minore frequenza, riducendo il carico sui server dei nomi.
 a| 
Ci vuole più tempo per negare l'accesso agli utenti NFS a cui in precedenza era consentito l'accesso ma che non sono più disponibili.



 a| 
Ridurre il tempo di cache delle credenziali positive
 a| 
È necessario meno tempo per negare l'accesso agli utenti NFS a cui in precedenza era consentito l'accesso ma che non sono più disponibili.
 a| 
ONTAP invia più frequentemente richieste di credenziali ai server dei nomi, aumentando il carico sui server dei nomi.



 a| 
Aumentare il tempo di cache delle credenziali negative
 a| 
ONTAP invia le richieste di credenziali ai server dei nomi con minore frequenza, riducendo il carico sui server dei nomi.
 a| 
Occorre più tempo per concedere l'accesso agli utenti NFS che in precedenza non avevano accesso, ma che ora lo sono.



 a| 
Ridurre il tempo di cache delle credenziali negative
 a| 
Occorrono meno tempo per concedere l'accesso agli utenti NFS che in precedenza non avevano accesso, ma che ora lo sono.
 a| 
ONTAP invia più frequentemente richieste di credenziali ai server dei nomi, aumentando il carico sui server dei nomi.

|===