---
permalink: nfs-admin/modify-maximum-ace-limit-nfsv4-acls-task.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile modificare il numero massimo di ACE consentiti per ogni ACL NFSv4 modificando il parametro -v4-acl-max-aces. Per impostazione predefinita, il limite è impostato su 400 ACE per ogni ACL. L"aumento di questo limite può contribuire a garantire una migrazione corretta dei dati con ACL contenenti oltre 400 ACE nei sistemi storage che eseguono ONTAP.' 
---
= Modificare il limite massimo ACE per gli ACL NFSv4 per gli SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare il numero massimo di ACE consentiti per ogni ACL NFSv4 modificando il parametro `-v4-acl-max-aces`. Per impostazione predefinita, il limite è impostato su 400 ACE per ogni ACL. L'aumento di questo limite può contribuire a garantire una migrazione corretta dei dati con ACL contenenti oltre 400 ACE nei sistemi storage che eseguono ONTAP.

.A proposito di questa attività
L'aumento di questo limite potrebbe influire sulle performance dei client che accedono ai file con ACL NFSv4.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

. Modificare il limite massimo ACE per gli ACL NFSv4:
+
`vserver nfs modify -v4-acl-max-aces max_ace_limit`

+
L'intervallo valido di

+
`max_ace_limit` è `192` a. `1024.`

. Tornare al livello di privilegio admin:
+
`set -privilege admin`


