---
permalink: nfs-admin/nfsv3-nfsv4-performance-tcp-transfer-size-concept.html 
sidebar: sidebar 
keywords: nfsv3, nfsv4, performance, improvement, modify, tcp, transfer, size 
summary: È possibile migliorare le prestazioni dei client NFSv3 e NFSv4 che si connettono ai sistemi storage su una rete ad alta latenza modificando le dimensioni massime di trasferimento TCP. 
---
= Scopri i miglioramenti delle prestazioni NFSv3 e NFSv4 e le dimensioni del trasferimento TCP per le SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile migliorare le prestazioni dei client NFSv3 e NFSv4 che si connettono ai sistemi storage su una rete ad alta latenza modificando le dimensioni massime di trasferimento TCP.

Quando i client accedono ai sistemi storage su una rete ad alta latenza, ad esempio WAN (Wide Area Network) o MAN (Metro Area Network) con una latenza superiore a 10 millisecondi, è possibile migliorare le prestazioni di connessione modificando le dimensioni massime di trasferimento TCP. I client che accedono a sistemi storage in una rete a bassa latenza, come una LAN (Local Area Network), possono aspettarsi pochi benefici dalla modifica di questi parametri. Se il miglioramento del throughput non supera l'impatto della latenza, non utilizzare questi parametri.

Per determinare se il tuo ambiente di storage potrebbe trarre beneficio dalla modifica di questi parametri, devi prima eseguire una valutazione completa delle performance di un client NFS dalle performance scarse. Verificare se le performance ridotte sono dovute a un'eccessiva latenza di round trip e a una piccola richiesta sul client. In queste condizioni, il client e il server non possono utilizzare completamente la larghezza di banda disponibile perché trascorrono la maggior parte dei loro cicli di lavoro in attesa di piccole richieste e risposte da trasmettere sulla connessione.

Aumentando le dimensioni delle richieste NFSv3 e NFSv4, il client e il server possono utilizzare la larghezza di banda disponibile in modo più efficace per spostare più dati per unità di tempo, aumentando quindi l'efficienza complessiva della connessione.

Tenere presente che la configurazione tra il sistema storage e il client potrebbe variare. Il sistema storage e il client supportano una dimensione massima di 1 MB per le operazioni di trasferimento. Tuttavia, se si configura il sistema di storage in modo che supporti le dimensioni massime di trasferimento di 1 MB ma il client supporta solo 64 KB, la dimensione di trasferimento del mount è limitata a 64 KB o meno.

Prima di modificare questi parametri, è necessario tenere presente che questo comporta un consumo di memoria aggiuntivo nel sistema di storage per il periodo di tempo necessario per assemblare e trasmettere una risposta elevata. Maggiore è la latenza elevata delle connessioni al sistema storage, maggiore è il consumo di memoria aggiuntivo. I sistemi storage con elevata capacità di memoria potrebbero avere un effetto molto ridotto da questo cambiamento. I sistemi storage con capacità di memoria bassa potrebbero riscontrare un notevole peggioramento delle performance.

Il corretto utilizzo di questi parametri dipende dalla capacità di recuperare i dati da più nodi di un cluster. La latenza intrinseca della rete del cluster potrebbe aumentare la latenza complessiva della risposta. La latenza complessiva tende ad aumentare quando si utilizzano questi parametri. Di conseguenza, i carichi di lavoro sensibili alla latenza potrebbero avere un impatto negativo.
