---
permalink: nfs-admin/ontap-support-nfsv41-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.1 
summary: A partire da ONTAP 9.8, la funzionalità nconnect è disponibile per impostazione predefinita quando NFSv4.1 è attivato. 
---
= Supporto ONTAP per NFSv4.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.8, la funzionalità nconnect è disponibile per impostazione predefinita quando NFSv4.1 è attivato.

Le implementazioni dei client NFS precedenti utilizzano solo una singola connessione TCP con un mount. In ONTAP, una singola connessione TCP può diventare un collo di bottiglia con un aumento degli IOPS. Tuttavia, un client abilitato a nconnect può avere più connessioni TCP (fino a 16) associate a un singolo montaggio NFS. Un client NFS di questo tipo moltiplica le operazioni di file su più connessioni TCP in modo round-robin e ottiene così un throughput più elevato dalla larghezza di banda di rete disponibile. NConnect è consigliato solo per i supporti NFSv3 e NFSv4.1.

Consultare la documentazione del client NFS per verificare se nconnect è supportato nella versione del client.

NFSv4.1 è attivato per impostazione predefinita in ONTAP 9.9.1 e versioni successive. Nelle versioni precedenti, è possibile attivarlo specificando `-v4.1` e impostarlo su `enabled` Quando si crea un server NFS sulla macchina virtuale di storage (SVM).

ONTAP non supporta le deleghe a livello di file e directory NFSv4.1.
