---
permalink: nfs-admin/ontap-support-kerberos-concept.html 
sidebar: sidebar 
keywords: ontap, support, kerberos 
summary: 'Kerberos offre un"autenticazione sicura e sicura per le applicazioni client/server. L"autenticazione consente di verificare le identità di utenti e processi di un server. Nell"ambiente ONTAP, Kerberos fornisce l"autenticazione tra le macchine virtuali di storage (SVM) e i client NFS.' 
---
= Supporto ONTAP per Kerberos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Kerberos offre un'autenticazione sicura e sicura per le applicazioni client/server. L'autenticazione consente di verificare le identità di utenti e processi di un server. Nell'ambiente ONTAP, Kerberos fornisce l'autenticazione tra le macchine virtuali di storage (SVM) e i client NFS.

In ONTAP 9, sono supportate le seguenti funzionalità Kerberos:

* Autenticazione Kerberos 5 con controllo dell'integrità (krb5i)
+
Krb5i utilizza checksum per verificare l'integrità di ogni messaggio NFS trasferito tra client e server. Ciò è utile sia per motivi di sicurezza (ad esempio, per garantire che i dati non siano stati manomessi) che per motivi di integrità dei dati (ad esempio, per prevenire la corruzione dei dati quando si utilizza NFS su reti non affidabili).

* Autenticazione Kerberos 5 con controllo della privacy (krb5p)
+
Krb5p utilizza checksum per crittografare tutto il traffico tra il client e il server. Questo è più sicuro e comporta un carico maggiore.

* Crittografia AES a 128 e 256 bit
+
Advanced Encryption Standard (AES) è un algoritmo di crittografia per la protezione dei dati elettronici. ONTAP ora supporta AES con chiavi a 128 bit (AES-128) e AES con chiavi a 256 bit (AES-256) per Kerberos per una maggiore sicurezza.

* Configurazioni di area di autenticazione Kerberos a livello di SVM
+
Gli amministratori di SVM possono ora creare configurazioni di area di autenticazione Kerberos a livello di SVM. Ciò significa che gli amministratori di SVM non devono più affidarsi all'amministratore del cluster per la configurazione dell'area di autenticazione Kerberos e possono creare singole configurazioni dell'area di autenticazione Kerberos in un ambiente multi-tenancy.


