---
permalink: nfs-admin/ontap-support-nfsv42-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.2, MAC-labelled NFS, extended attributes, xattrs 
summary: 'A partire da ONTAP 9.8, il protocollo NFSv4.2 è supportato per consentire l"accesso ai client abilitati a NFSv4.2.' 
---
= Supporto ONTAP per NFSv4.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9,8, ONTAP supporta il protocollo NFSv4,2 per consentire l'accesso a client abilitati per NFSv4,2.

NFSv4,2 è attivato per impostazione predefinita in ONTAP 9.9.1 e versioni successive. In ONTAP 9,8, è necessario attivare manualmente v4,2 specificando il `-v4.1` e impostarlo su `enabled` Quando si crea un server NFS sulla macchina virtuale di storage (SVM). L'abilitazione di NFSv4.1 consente inoltre ai client di utilizzare le funzionalità di NFSv4.1 mentre sono montati come v4.2.

Le successive versioni di ONTAP ampliano il supporto per NFSv4,2 funzioni opzionali.

[cols="2*"]
|===
| A partire da... | NFSv4,2 caratteristiche opzionali includono ... 


| ONTAP 9.12.1  a| 
* Attributi estesi NFS
* File sparse
* Prenotazioni di spazio




| ONTAP 9.9.1 | Obbligatorio Access Control (MAC) con etichetta NFS 
|===


== Etichette di sicurezza NFS v4,2

A partire da ONTAP 9.9.1, è possibile attivare le etichette di sicurezza NFS. Sono disattivati per impostazione predefinita.

Con le etichette di sicurezza NFS v4.2, i server NFS ONTAP sono compatibili con il controllo di accesso obbligatorio (MAC), memorizzando e recuperando gli attributi sec_label inviati dai client.

Per ulteriori informazioni, vedere link:https://tools.ietf.org/html/rfc7204["RFC 7240"^].

A partire da ONTAP 9.12.1, le etichette di sicurezza NFS v4.2 sono supportate per le operazioni di dump NDMP. Se vengono rilevate etichette di sicurezza su file o directory nelle release precedenti, il dump non riesce.

.Fasi
. Impostare i privilegi su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
. Abilitare le etichette di sicurezza:
+
[source, cli]
----
vserver nfs modify -vserver <svm_name> -v4.2-seclabel enabled
----




== Attributi estesi NFS

A partire da ONTAP 9.12.1, gli attributi estesi NFS (xattrs) sono attivati per impostazione predefinita.

Gli attributi estesi sono attributi NFS standard definiti da https://tools.ietf.org/html/rfc8276["RFC 8276"^] E abilitato nei moderni client NFS. Possono essere utilizzate per collegare metadati definiti dall'utente a oggetti del file system e sono interessanti per implementazioni di sicurezza avanzate.

Gli attributi estesi NFS non sono attualmente supportati per le operazioni di dump NDMP. Se vengono rilevati attributi estesi su file o directory, il dump procede ma non esegue il backup degli attributi estesi su tali file o directory.

Se è necessario disattivare gli attributi estesi, utilizzare `vserver nfs modify -v4.2-xattrs disabled` comando.
