---
permalink: nfs-admin/ontap-support-nfsv41-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.1 
summary: A partire da ONTAP 9.8, la funzionalità nconnect è disponibile per impostazione predefinita quando NFSv4.1 è attivato. 
---
= Scopri di più sul supporto ONTAP per NFSv4.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.8, la funzionalità nconnect è disponibile per impostazione predefinita quando NFSv4.1 è attivato.

Le implementazioni dei client NFS precedenti utilizzano solo una singola connessione TCP con un mount. In ONTAP, una singola connessione TCP può diventare un collo di bottiglia con un aumento degli IOPS.

nconnect migliora le prestazioni del client NFS consentendo più connessioni TCP (fino a 16) per un singolo montaggio, contribuendo a superare il collo di bottiglia delle prestazioni che può verificarsi con una singola connessione TCP all'aumentare degli IOPS.

NFSv4.1 è attivato per impostazione predefinita in ONTAP 9.9.1 e versioni successive. Nelle versioni precedenti, è possibile attivarlo specificando `-v4.1` e impostarlo su `enabled` Quando si crea un server NFS sulla macchina virtuale di storage (SVM).

ONTAP non supporta le deleghe a livello di file e directory NFSv4.1.

.Informazioni correlate
link:nconnect-concept.html["Scopri di più su nconnect per le prestazioni NFS"].
