---
permalink: nfs-admin/optimize-access-cache-performance-task.html 
sidebar: sidebar 
keywords: optimize, access, cache, performance 
summary: È possibile configurare diversi parametri per ottimizzare la cache di accesso e trovare il giusto equilibrio tra le prestazioni e la corrente delle informazioni memorizzate nella cache di accesso. 
---
= Ottimizza le performance della cache di accesso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare diversi parametri per ottimizzare la cache di accesso e trovare il giusto equilibrio tra le prestazioni e la corrente delle informazioni memorizzate nella cache di accesso.

.A proposito di questa attività
Quando si configurano i periodi di aggiornamento della cache di accesso, tenere presente quanto segue:

* Valori più elevati significano che le voci rimangono più lunghe nella cache di accesso.
+
Il vantaggio è rappresentato dalle performance migliori, in quanto ONTAP spende meno risorse per il refresh delle voci della cache di accesso. Lo svantaggio è che se le regole dei criteri di esportazione cambiano e le voci della cache di accesso diventano obsolete, l'aggiornamento richiede più tempo. Di conseguenza, i client che dovrebbero ottenere l'accesso potrebbero essere rifiutati e i client che dovrebbero ottenere l'accesso potrebbero ottenere l'accesso.

* Valori più bassi significano che ONTAP aggiorna più spesso le voci della cache di accesso.
+
Il vantaggio è che le voci sono più aggiornate e i client hanno maggiori probabilità di ottenere o negare l'accesso correttamente. Lo svantaggio è una diminuzione delle performance perché ONTAP spende più risorse per aggiornare le voci della cache di accesso.



.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

. Eseguire l'azione desiderata:
+
[cols="2*"]
|===
| Per modificare... | Inserisci... 


 a| 
Periodo di refresh per voci positive
 a| 
`vserver export-policy access-cache config modify-all-vservers -refresh-period-positive timeout_value`



 a| 
Periodo di refresh per le voci negative
 a| 
`vserver export-policy access-cache config modify-all-vservers -refresh-period-negative timeout_value`



 a| 
Periodo di timeout per le voci precedenti
 a| 
`vserver export-policy access-cache config modify-all-vservers -harvest-timeout timeout_value`

|===
. Verificare le nuove impostazioni dei parametri:
+
`vserver export-policy access-cache config show-all-vservers`

. Tornare al livello di privilegio admin:
+
`set -privilege admin`


