---
permalink: nfs-admin/security-styles-their-effects-concept.html 
sidebar: sidebar 
keywords: security, style, effect, unix, ntfs, mixed, unified 
summary: 'Esistono quattro diversi stili di sicurezza: UNIX, NTFS, misto e unificato. Ogni stile di sicurezza ha un effetto diverso sul modo in cui vengono gestite le autorizzazioni per i dati. È necessario comprendere i diversi effetti per assicurarsi di selezionare lo stile di sicurezza appropriato per i propri scopi.' 
---
= Scopri gli stili di sicurezza NAS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
Esistono quattro diversi stili di sicurezza: UNIX, NTFS, misto e unificato. Ogni stile di sicurezza ha un effetto diverso sul modo in cui vengono gestite le autorizzazioni per i dati. È necessario comprendere i diversi effetti per assicurarsi di selezionare lo stile di sicurezza appropriato per i propri scopi.

È importante comprendere che gli stili di sicurezza non determinano quali tipi di client possono o non possono accedere ai dati. Gli stili di sicurezza determinano solo il tipo di autorizzazioni utilizzate da ONTAP per controllare l'accesso ai dati e il tipo di client in grado di modificare tali autorizzazioni.

Ad esempio, se un volume utilizza lo stile di sicurezza UNIX, i client SMB possono comunque accedere ai dati (purché autenticino e autorizzino correttamente) a causa della natura multiprotocollo di ONTAP. Tuttavia, ONTAP utilizza autorizzazioni UNIX che solo i client UNIX possono modificare utilizzando strumenti nativi.

[cols="5*"]
|===
| Stile di sicurezza | Client in grado di modificare le autorizzazioni | Autorizzazioni che i client possono utilizzare | Risultato di uno stile di sicurezza efficace | Client che possono accedere ai file 


.2+| UNIX .2+| NFS | Bit di modalità NFSv3 .2+| UNIX .9+| NFS e SMB 


| ACL NFSv4.x 


| NTFS | PMI | ACL NTFS | NTFS 


.3+| Misto .3+| NFS o SMB | Bit di modalità NFSv3 .2+| UNIX 


| NFSv4.ACL 


| ACL NTFS | NTFS 


.3+| Unificato (solo per volumi infiniti, in ONTAP 9.4 e versioni precedenti). .3+| NFS o SMB | Bit di modalità NFSv3 .2+| UNIX 


| ACL NFSv4.1 


| ACL NTFS | NTFS 
|===
I volumi FlexVol supportano UNIX, NTFS e stili di sicurezza misti. Quando lo stile di sicurezza è misto o unificato, le autorizzazioni effettive dipendono dal tipo di client che ha modificato le autorizzazioni per ultima, perché gli utenti impostano lo stile di sicurezza su base individuale. Se l'ultimo client che ha modificato le autorizzazioni era un client NFSv3, le autorizzazioni sono bit di modalità UNIX NFSv3. Se l'ultimo client era un client NFSv4, le autorizzazioni sono ACL NFSv4. Se l'ultimo client era un client SMB, le autorizzazioni sono ACL NTFS di Windows.

Lo stile di sicurezza unificato è disponibile solo con volumi infiniti, che non sono più supportati in ONTAP 9.5 e versioni successive. Per ulteriori informazioni, vedere xref:../flexgroup/index.html[Panoramica sulla gestione dei volumi FlexGroup].

A partire da ONTAP 9,2, il `show-effective-permissions` parametro del `vserver security file-directory` comando consente di visualizzare le autorizzazioni effettive concesse a un utente Windows o UNIX sul percorso specificato per il file o la cartella. Inoltre, il parametro opzionale `-share-name` consente di visualizzare l'autorizzazione di condivisione effettiva. Ulteriori informazioni su `vserver security file-directory show-effective-permissions` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-security-file-directory-show-effective-permissions.html["Riferimento al comando ONTAP"^].

[NOTE]
====
ONTAP imposta inizialmente alcune autorizzazioni predefinite per i file. Per impostazione predefinita, lo stile di sicurezza effettivo su tutti i dati nei volumi UNIX, misti e di sicurezza unificata è UNIX e il tipo di permessi effettivo è UNIX mode bits (0755 se non diversamente specificato) fino a quando non viene configurato da un client come consentito dallo stile di sicurezza predefinito. Per impostazione predefinita, lo stile di sicurezza effettivo su tutti i dati nei volumi di sicurezza NTFS è NTFS e dispone di un ACL che consente il controllo completo di tutti.

====
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^]

