---
permalink: nfs-admin/specify-nfsv4-locking-lease-period-task.html 
sidebar: sidebar 
keywords: specify, nfsv4, lock, lease, period 
summary: 'Per specificare il periodo di lease di blocco NFSv4 (ovvero, il periodo di tempo in cui ONTAP concede irrevocabilmente un blocco a un client), è possibile modificare l"opzione -v4-lease-seconds. I periodi di leasing più brevi accelerano il ripristino dei server, mentre i periodi di leasing più lunghi sono vantaggiosi per i server che gestiscono un numero molto elevato di client.' 
---
= Specificare il periodo di locazione del blocco NFSv4 per le SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per specificare il periodo di leasing di blocco NFSv4 (ovvero, il periodo di tempo in cui ONTAP concede irrevocabilmente un blocco a un client), è possibile modificare `-v4-lease-seconds` opzione. I periodi di leasing più brevi accelerano il ripristino dei server, mentre i periodi di leasing più lunghi sono vantaggiosi per i server che gestiscono un numero molto elevato di client.

.A proposito di questa attività
Per impostazione predefinita, questa opzione è impostata su `30`. Il valore minimo per questa opzione è `10`. Il valore massimo per questa opzione è il periodo di tolleranza di blocco, che è possibile impostare con `locking.lease_seconds` opzione.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

. Immettere il seguente comando:
+
`vserver nfs modify -vserver vserver_name -v4-lease-seconds number_of_seconds`

. Tornare al livello di privilegio admin:
+
`set -privilege admin`


