---
permalink: nfs-admin/view-nfs-exports-svms-concept.html 
sidebar: sidebar 
keywords: enable, display, nfs, export, client 
summary: I client NFS possono utilizzare il comando showmount -e per visualizzare un elenco delle esportazioni disponibili da un server NFS ONTAP. In questo modo, gli utenti possono identificare il file system che desiderano montare. 
---
= Abilitare la visualizzazione delle esportazioni NFS sui client NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I client NFS possono utilizzare `showmount -e` Per visualizzare un elenco delle esportazioni disponibili da un server NFS ONTAP. In questo modo, gli utenti possono identificare il file system che desiderano montare.

A partire da ONTAP 9.2, ONTAP consente ai client NFS di visualizzare l'elenco di esportazione per impostazione predefinita. Nelle versioni precedenti, il `showmount` opzione di `vserver nfs modify` il comando deve essere attivato in modo esplicito. Per visualizzare l'elenco di esportazione, è necessario attivare NFSv3 su SVM.

.Esempio
Il seguente comando mostra la funzione showmount sulla SVM denominata vs1:

[listing]
----
clusterl : : > vserver nfs show -vserver vs1 -fields showmount
vserver showmount
------- ---------
vs1    enabled
----
Il seguente comando eseguito su un client NFS visualizza l'elenco delle esportazioni su un server NFS con l'indirizzo IP 10.63.21.9:

[listing]
----
showmount -e 10.63.21.9
Export list for 10.63.21.9:
/unix        (everyone)
/unix/unixl  (everyone)
/unix/unix2  (everyone)
/            (everyone)
----