---
sidebar: sidebar 
permalink: anti-ransomware/enable-arp-ai-with-au.html 
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection 
summary: A partire da ONTAP 9.16.1, abilitare automaticamente ARP/AI per le installazioni FlexVol oppure abilitarlo manualmente dopo aver soddisfatto i prerequisiti. 
---
= Abilita ONTAP ARP/AI
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.16.1, ARP ha adottato la protezione autonoma contro i ransomware con intelligenza artificiale (ARP/AI) per migliorare il rilevamento e la risposta alle minacce. Dopo l'aggiornamento del cluster a ONTAP 9.17.1 per SAN o ONTAP 9.16.1 per NAS, ARP/AI verrà automaticamente abilitato per i volumi FlexVol se ARP è già abilitato per tali volumi. Se ARP o ONTAP non sono abilitati, link:../update/enable-automatic-updates-task.html["aggiornamenti automatici"] per il tuo cluster, dovresti seguire uno degli scenari descritti in questa procedura.


IMPORTANT: Prima di eseguire l'aggiornamento a una versione ONTAP con supporto ARP/AI, link:../upgrade/arp-warning-clear.html["Chiudere tutte le rilevazioni ARP esistenti"] .

.Prima di iniziare
* Per utilizzare ARP/AI, è necessario disporre di volumi FlexVol . Se si dispone di volumi FlexGroup , il modello ARP utilizzato prima di ARP/AI continua a funzionare dopo l'aggiornamento a ONTAP 9.16.1 o versioni successive.



NOTE: (Solo per ambienti NAS) Quando si esegue l'aggiornamento a ONTAP 9.16.1 o versione successiva, ARP viene abilitato e diventa automaticamente attivo per tutte le istanze ARP esistenti con volumi FlexVol . Poiché ARP/AI è addestrato su un modello di apprendimento automatico completo, non è più necessario un periodo di apprendimento. Qualsiasi periodo di apprendimento non completato prima dell'aggiornamento verrà automaticamente terminato e i volumi passeranno ad ARP/AI attivo.

.Fasi
. Seguire lo scenario specifico per la configurazione:
+
** *Solo ambienti SAN*
+
*** *Per i cluster nuovi ed esistenti che eseguono ONTAP 9.17.1 o versione successiva con volumi FlexVol *: quando esegui l'aggiornamento o l'installazione ONTAP 9.17.1 o versione successiva, dovresti link:enable-task.html["abilita ARP"] sui volumi che si intende proteggere. Quando si abilita ARP tramite System Manager o la CLI, la funzionalità ARP/AI viene abilitata automaticamente. Una volta abilitata su un volume SAN, link:respond-san-entropy-eval-period.html["ARP/AI monitora i dati in modo continuo durante un periodo di valutazione"] per determinare se i carichi di lavoro sono adatti per ARP e impostare una soglia di crittografia ottimale per il rilevamento.


** *Solo ambienti NAS*
+
*** *Per i nuovi cluster che eseguono ONTAP 9.16.1 o successivo con volumi FlexVol: link:enable-task.html["Enable ARP (attiva ARP)"]. ARP non è abilitato per impostazione predefinita. aver abilitato ARP, la funzionalità ARP/AI viene abilitata automaticamente sui volumi FlexVol che si sceglie di proteggere.
*** *Per i cluster esistenti recentemente aggiornati a ONTAP 9.16.1 e versioni successive con ARP abilitato*: non è richiesta alcuna azione. ARP/AI diventa automaticamente il nuovo metodo ARP di protezione dalle minacce sui volumi FlexVol che hai scelto di proteggere.
*** *Per i cluster esistenti aggiornati di recente a ONTAP 9.16.1 e successivi che non hanno ARP abilitato*: link:enable-task.html["Enable ARP (attiva ARP)"]. Dopo aver abilitato ARP




. Dopo aver abilitato ARP/AI, decidi se desideri che gli aggiornamenti di protezione ARP/AI vengano consegnati e installati link:arp-ai-automatic-updates.html["automaticamente o manualmente"] .


.Informazioni correlate
* link:arp-ai-automatic-updates.html["Aggiorna ARP/ai"]

