---
sidebar: sidebar 
permalink: anti-ransomware/enable-arp-ai-with-au.html 
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection 
summary: A partire da ONTAP 9.16,1, abilitare automaticamente ARP/ai per le installazioni FlexVol con ARP abilitato o attivarlo manualmente dopo aver soddisfatto i prerequisiti. 
---
= Abilita ARP/ai con aggiornamento automatico
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP 9.16,1, ARP ha adottato la protezione autonoma dal ransomware con l'intelligenza artificiale (ARP/ai) per migliorare il rilevamento e la risposta delle minacce. Dopo aver aggiornato il cluster a ONTAP 9.16,1, ARP/ai sarà automaticamente abilitato per i volumi FlexVol se ARP è già abilitato per questi volumi. Se l'ARP non è stato attivato o non sono stati attivati gli aggiornamenti automatici per il cluster, è necessario seguire uno degli scenari descritti in questa procedura.


IMPORTANT: Prima di eseguire l'aggiornamento a ONTAP 9.16,1, link:../upgrade/arp-warning-clear.html["Chiudere tutte le rilevazioni ARP esistenti"].

.Prima di iniziare
* È necessario disporre di volumi FlexVol per utilizzare ARP/ai. Se si dispone di volumi FlexGroup, il modello ARP utilizzato prima di ARP/ai continua a funzionare dopo l'aggiornamento a ONTAP 9.16,1.



NOTE: Quando si esegue l'aggiornamento a ONTAP 9.16,1, ARP viene attivato automaticamente in modalità attiva per tutte le istanze ARP esistenti con volumi FlexVol. Poiché ARP/ai è addestrato su un modello di apprendimento automatico esteso, non è più necessario un periodo di apprendimento. Tutti i periodi di apprendimento che non sono stati completati prima dell'aggiornamento verranno automaticamente terminati e i volumi passeranno alla modalità attiva.

.Fasi
. Seguire lo scenario specifico per la configurazione:
+
** *Per i nuovi cluster che eseguono ONTAP 9.16,1*:link:enable-task.html["Enable ARP (attiva ARP)"]. L'ARP non è attivato per impostazione predefinita. Dopo aver attivato ARP, la funzionalità ARP/ai viene attivata automaticamente in modalità attiva sui volumi che si sceglie di proteggere.
** *Per i cluster esistenti recentemente aggiornati a ONTAP 9.16,1 con ARP abilitato*: Nessuna azione necessaria. ARP/ai diventerà automaticamente il nuovo metodo ARP di protezione dalle minacce sui volumi FlexVol che hai scelto di proteggere.
** *Per i cluster esistenti recentemente aggiornati a ONTAP 9.16,1 che non hanno ARP abilitato*: link:enable-task.html["Enable ARP (attiva ARP)"]. ARP/ai diventerà automaticamente il nuovo metodo ARP di protezione dalle minacce dopo aver attivato ARP.


. Dopo che ARP/ai è abilitato, decidere se si desidera che gli aggiornamenti della protezione ARP/ai vengano forniti e link:arp-ai-automatic-updates.html["automaticamente o manualmente"]installati.


.Informazioni correlate
* link:arp-ai-automatic-updates.html["Aggiorna ARP/ai"]

