---
sidebar: sidebar 
permalink: anti-ransomware/index.html 
keywords: ransomware, security, autonomous protection, arp, detect, detection, threat, attack, suspect, anti-ransomware, entropy, abnormal volume activity, antiransomware, extension conformity, ransomware protection strategy 
summary: 'A partire da ONTAP 9.10.1, la funzionalità di protezione ransomware autonoma (ARP) utilizza l"analisi del carico di lavoro in ambienti NAS (NFS e SMB) per rilevare e avvisare in modo proattivo circa attività anomale che potrebbero indicare un attacco ransomware.' 
---
= Panoramica della protezione ransomware autonoma
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
A partire da ONTAP 9.10.1, la funzionalità di protezione ransomware autonoma (ARP) utilizza l'analisi del carico di lavoro in ambienti NAS (NFS e SMB) per rilevare e avvisare in modo proattivo circa attività anomale che potrebbero indicare un attacco ransomware.

Quando si sospetta un attacco, ARP crea anche nuove copie Snapshot, oltre alla protezione esistente dalle copie Snapshot pianificate.



== Licenze e abilitazione

ARP richiede una licenza diversa a seconda della versione di ONTAP in uso:

[cols="2*"]
|===
| Release di ONTAP | Licenza 


 a| 
ONTAP 9.11.1 e versioni successive
 a| 
Anti_ransomware



 a| 
ONTAP 9.10.1
 a| 
MT_EK_MGMT (Gestione delle chiavi multi-tenant)

|===
* Se si esegue l'aggiornamento a ONTAP 9.11.1 o versione successiva e ARP è già configurato nel sistema, non è necessario acquistare la nuova licenza Anti-ransomware. Per le nuove configurazioni ARP, è necessaria la nuova licenza.
* Se si esegue il ripristino da ONTAP 9.11.1 o versione successiva a ONTAP 9.10.1 e si attiva ARP con la licenza Anti-ransomware, viene visualizzato un messaggio di avviso e potrebbe essere necessario riconfigurare ARP. link:../revert/anti-ransomware-license-task.html["Scopri come ripristinare ARP"].


È possibile configurare ARP in base al volume utilizzando Gestione di sistema di ONTAP o l'interfaccia utente di ONTAP.



== Strategia di protezione ransomware di ONTAP

Una strategia efficace di rilevamento ransomware dovrebbe includere più di un singolo livello di protezione.

Un'analogia sarebbe la sicurezza di un veicolo. Non ci si affida a una singola funzione, ad esempio una cintura di sicurezza, per proteggersi completamente in caso di incidente. Gli airbag, i freni antibloccaggio e l'allarme anticollisione anteriore sono tutte funzioni di sicurezza aggiuntive che consentono di ottenere risultati migliori. La protezione ransomware deve essere visualizzata nello stesso modo.

Mentre ONTAP include funzionalità come FPolicy, Snapshot Copies, SnapLock e Active IQ Digital Advisor per la protezione dal ransomware, le seguenti informazioni si concentrano sulla funzionalità ARP on-box con funzionalità di machine learning.

Per ulteriori informazioni sulle altre funzionalità anti-ransomware di ONTAP, consulta la sezione link:https://www.netapp.com/media/7334-tr4572.pdf["TR-4572: Soluzione NetApp per ransomware."^]



== Cosa rileva ARP

Esistono due tipi di attacchi ransomware:

* Denial of service ai file crittografando i dati. L'utente malintenzionato non può accedere a questi dati a meno che non venga pagato un riscatto.
* Furto di dati proprietari sensibili. L'utente malintenzionato minaccia di rilasciare questi dati nel dominio pubblico a meno che non venga pagato un riscatto.


ARP affronta il primo tipo, con un meccanismo di rilevamento anti-ransomware basato su:

* Identificazione dei dati in entrata come crittografati o non crittografati.
* Analytics, che rileva
+
** **Entropia**: Una valutazione della casualità dei dati in un file
** **Tipi di estensione del file**: Un'estensione non conforme al normale tipo di estensione
** **IOPS del file**: Aumento dell'attività anomala del volume con crittografia dei dati (a partire da ONTAP 9.11.1)





NOTE: Nessun sistema di rilevamento ransomware o prevenzione può garantire completamente la sicurezza da un attacco ransomware. Anche se è possibile che un attacco non venga rilevato, NetApp ARP agisce come un importante livello di difesa aggiuntivo se il software antivirus non è riuscito a rilevare un'intrusione. ARP è in grado di rilevare la diffusione della maggior parte degli attacchi ransomware dopo la crittografia di un numero limitato di file, intraprendere azioni automatiche per proteggere i dati e avvisare l'utente che si sta verificando un attacco sospetto.



== Modalità di apprendimento e attive

ARP dispone di due modalità:

. Apprendimento
. Attivo


Quando si attiva ARP, questo viene eseguito in modalità di apprendimento. In modalità di apprendimento, il sistema ONTAP sviluppa un profilo di allerta basato sulle aree analitiche sopra menzionate: Entropia, tipi di estensione del file e IOPS del file. Dopo aver eseguito ARP in modalità di apprendimento per un tempo sufficiente a valutare le caratteristiche del carico di lavoro, è possibile passare alla modalità attiva e iniziare a proteggere i dati. Una volta che ARP è passato alla modalità attiva, ONTAP crea snapshot ARP per proteggere i dati in caso di rilevamento di una minaccia.

Si consiglia di lasciare ARP in modalità di apprendimento per almeno 30 giorni, anche se è possibile passare alla modalità attiva in qualsiasi momento. Il passaggio troppo anticipato potrebbe causare troppi falsi positivi. A partire da ONTAP 9.13.1, ARP determina automaticamente l'intervallo ottimale del periodo di apprendimento e automatizza lo switch, che può verificarsi prima di 30 giorni.

In modalità attiva, se un'estensione del file è contrassegnata come anomala, è necessario valutare l'avviso. Puoi agire sull'avviso per proteggere i tuoi dati o contrassegnarlo come falso positivo. Quando si contrassegna un falso positivo, ONTAP aggiorna il profilo di avviso ARP in modo che l'estensione del file non venga contrassegnata in seguito. Il comando `security anti-ransomware volume workload-behavior show` mostra le estensioni di file rilevate nel volume. (Se si esegue questo comando nelle prime fasi della modalità di apprendimento e viene visualizzata una rappresentazione accurata dei tipi di file, non utilizzare tali dati come base per passare alla modalità attiva, poiché ONTAP sta ancora raccogliendo altre metriche).

A partire da ONTAP 9.11.1, è possibile personalizzare i parametri di rilevamento per ARP. Per ulteriori informazioni, vedere xref:manage-parameters-task.html[Gestire i parametri di rilevamento degli attacchi ARP].



== Valutazione delle minacce e snapshot ARP

In modalità attiva, ARP valuta la probabilità di minaccia in base ai dati in entrata misurati in base alle analisi apprese. Viene assegnata una misurazione quando ARP rileva una minaccia:

* **Basso**: Viene assegnata la prima volta che si osserva una nuova estensione del file nel volume.
* **Moderato**: Si osservano più file con la stessa estensione mai vista prima.
+
** In ONTAP 9.10.1, la soglia per l'escalation a moderate è di 100 o più file. A partire da ONTAP 9.11.1, è possibile modificare la quantità di file; il valore predefinito è 20.




In una situazione di basso rischio, ONTAP rileva un'anomalia e crea un'istantanea del volume per creare il miglior punto di ripristino possibile. L'istantanea ARP utilizza `anti-ransomware-backup` tag ed è identificabile dal suo nome, ad esempio `Anti_ransomware_backup.2022-12-20_1248`.

Dopo che ONTAP ha eseguito un report di analytics, la minaccia passa a moderata. Ciò determina se l'anomalia corrisponde a un profilo ransomware. Le minacce che rimangono al livello basso sono registrate e visibili nella sezione **Eventi** di Gestione di sistema, ma ONTAP non invia un avviso per le minacce basse. Quando la probabilità di attacco è moderata, ONTAP genera una notifica EMS che richiede di valutare la minaccia. Per ulteriori informazioni, vedere xref:respond-abnormal-task.html[Rispondere ad attività anomale].

È possibile visualizzare informazioni su una minaccia, indipendentemente dal livello, nella sezione **Eventi** di System Manager o con `security anti-ransomware volume show -vserver _svm_name_` comando.

Gli snapshot ARP vengono conservati per un minimo di due giorni. A partire da ONTAP 9.11.1, è possibile modificare le impostazioni di conservazione. Per ulteriori informazioni, vedere xref:modify-automatic-shapshot-options-task.html[Modificare le opzioni per le copie Snapshot].



== Come ripristinare i dati in ONTAP dopo un attacco ransomware

Quando si sospetta un attacco, il sistema esegue una copia Snapshot del volume in quel momento e blocca tale copia. Se l'attacco viene confermato in un secondo momento, è possibile ripristinare il volume in questa Snapshot, riducendo al minimo la perdita di dati.

Le copie Snapshot bloccate non possono essere eliminate con mezzi normali. Tuttavia, se in seguito decidi di contrassegnare l'attacco come falso positivo, la copia bloccata verrà eliminata.

Con la conoscenza dei file interessati e del tempo di attacco, è possibile ripristinare selettivamente i file interessati da varie copie Snapshot, invece di ripristinare semplicemente l'intero volume in una delle snapshot.

ARP si basa quindi sulla comprovata tecnologia di protezione dei dati e disaster recovery di ONTAP per rispondere agli attacchi ransomware. Per ulteriori informazioni sul ripristino dei dati, consultare i seguenti argomenti.

* link:../task_dp_recover_snapshot.html["Ripristino da copie Snapshot (System Manager)"]
* link:../data-protection/restore-contents-volume-snapshot-task.html["Ripristino dei file da copie Snapshot (CLI)"]
* link:https://www.netapp.com/blog/smart-ransomware-recovery["Ripristino ransomware intelligente"^]

