---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options, autonomous ransomware protection, arp 
summary: Modifica le impostazioni delle copie Snapshot di protezione autonoma contro il ransomware generate automaticamente in risposta a sospetti attacchi ransomware. 
---
= Modificare le opzioni per le copie Snapshot automatiche
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP 9.11.1, puoi utilizzare la CLI per controllare il numero e il periodo di conservazione per le copie Snapshot di protezione autonoma dal ransomware (ARP), che sono generate automaticamente in risposta a sospetti attacchi ransomware.



== Opzioni Snapshot modificabili

È possibile modificare le seguenti opzioni per le copie Snapshot automatiche:

arw.snap.max.count:: Specifica il numero massimo di copie Snapshot ARP che possono esistere in un volume in qualsiasi momento. Le copie meno recenti vengono eliminate per garantire che il numero totale di copie Snapshot ARP rientri nel limite specificato.
arw.snap.create.interval.hours:: Specifica l'intervallo (in ore) tra le copie Snapshot ARP. Una nuova copia Snapshot viene creata quando si sospetta un attacco e la copia creata in precedenza è precedente a questo intervallo specificato.
arw.snap.normal.retain.interval.hours:: Specifica la durata (in ore) per la quale viene conservata una copia snapshot ARP. Quando una copia ARP Snapshot diventa vecchia, qualsiasi altra copia ARP Snapshot creata prima dell'ultima copia per raggiungere questa età viene eliminata. Nessuna copia snapshot ARP può essere precedente a questa durata.
arw.snap.max.retain.interval.days:: Specifica la durata massima (in giorni) per la quale è possibile conservare una copia snapshot ARP. Qualsiasi copia ARP Snapshot precedente a questa durata verrà eliminata se non viene segnalato alcun attacco sul volume.



NOTE: L'intervallo di conservazione massimo per l'istantanea ARP viene ignorato se viene rilevata una minaccia moderata. L'istantanea creata poco prima della minaccia rimarrà fino a quando la minaccia non verrà contrassegnata come un falso positivo. Una volta contrassegnati come falsi positivi, verranno eliminati anche tutti gli altri snapshot ARP presenti sul volume.

arw.snap.create.interval.hours.post.max.count:: Specifica l'intervallo (in ore) tra le copie Snapshot ARP quando il volume contiene già il numero massimo di copie Snapshot ARP. Una volta raggiunto il numero massimo di copie, una copia snapshot ARP viene eliminata per creare spazio per una nuova copia. È possibile ridurre la velocità di creazione delle nuove copie Snapshot ARP per conservare le copie meno recenti utilizzando questa opzione. Se il volume contiene già il numero massimo di copie Snapshot ARP, questo intervallo specificato in questa opzione viene utilizzato per la successiva creazione della copia Snapshot ARP, invece di arw.snap.create.interval.hours.
arw.surge.snap.interval.days:: Specifica l'intervallo (in giorni) tra le copie Snapshot di picco ARP. Una nuova copia di picco snapshot ARP viene creata quando si verifica un aumento del traffico io e l'ultima copia snapshot ARP creata è precedente a questo intervallo specificato. Questa opzione specifica anche la durata (in giorni) per la quale viene conservata una copia Snapshot di picco ARP.




== Comandi CLI

È possibile modificare solo le opzioni su un nodo SVM.


NOTE: Il `vserver options` command è un comando nascosto. Per visualizzare la pagina man, immettere `man vserver options` Nella CLI di ONTAP.

Per visualizzare tutte le impostazioni di copia correnti di ARP Snapshot, immettere:
`vserver options -vserver _svm_name_ arw*`

Per visualizzare le impostazioni di copia correnti di ARP Snapshot, immettere:
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_`

Per modificare le impostazioni di copia di ARP Snapshot, immettere:
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_ -option-value _arw_setting_value_`
