---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options, autonomous ransomware protection, arp 
summary: Modifica le impostazioni delle copie Snapshot di protezione autonoma contro il ransomware generate automaticamente in risposta a sospetti attacchi ransomware. 
---
= Modificare le opzioni per le copie Snapshot automatiche
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP 9.11.1, puoi utilizzare la CLI per controllare le impostazioni di conservazione per le copie Snapshot di protezione autonoma dal ransomware (ARP), generate automaticamente in risposta a sospetti attacchi ransomware.

.Prima di iniziare
È possibile modificare solo le opzioni di ARP Snapshot su una SVM di nodo.

.Fasi
. Per visualizzare tutte le impostazioni di copia correnti di ARP Snapshot, immettere:
`vserver options -vserver _svm_name_ arw*`
+

NOTE: Il `vserver options` command è un comando nascosto. Per visualizzare la pagina man, immettere `man vserver options` Nella CLI di ONTAP.

. Per visualizzare le impostazioni di copia correnti di ARP Snapshot, immettere:
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_`
. Per modificare le impostazioni di copia di ARP Snapshot, immettere:
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_ -option-value _arw_setting_value_`
+
È possibile modificare le seguenti impostazioni:

+
[cols="1,3"]
|===
| Impostazione ARW | Descrizione 


| *arw.snap.max.count* | Specifica il numero massimo di copie Snapshot ARP che possono esistere in un volume in qualsiasi momento. Le copie meno recenti vengono eliminate per garantire che il numero totale di copie Snapshot ARP rientri nel limite specificato. 


| *arw.snap.create.interval.hours* | Specifica l'intervallo _in ore_ tra le copie snapshot ARP. Una nuova copia Snapshot viene creata quando si sospetta un attacco e la copia creata in precedenza è precedente all'intervallo specificato. 


| *arw.snap.normal.retain.interval.hours* | Specifica la durata _in ore_ per la quale viene conservata una copia snapshot ARP. Quando una copia ARP Snapshot diventa vecchia, qualsiasi altra copia ARP Snapshot creata prima dell'ultima copia per raggiungere questa età viene eliminata. Nessuna copia snapshot ARP può essere precedente a questa durata. 


| *arw.snap.max.retain.interval.days*  a| 
Specifica la durata massima _in giorni_ per la quale è possibile conservare una copia snapshot ARP. Qualsiasi copia ARP Snapshot precedente a questa durata verrà eliminata se non viene segnalato alcun attacco sul volume.

+


NOTE: L'intervallo di conservazione massimo per l'istantanea ARP viene ignorato se viene rilevata una minaccia moderata. Lo snapshot creato in risposta alla minaccia viene conservato fino a quando non si risponde alla minaccia. Contrassegnare una minaccia come falso positivo eliminare le copie snapshot ARP sul volume.



| *arw.snap.create.interval.hours.post.max.count* | Specifica l'intervallo _in ore_ tra le copie snapshot ARP quando il volume contiene già il numero massimo di copie snapshot ARP. Una volta raggiunto il numero massimo di copie, una copia snapshot ARP viene eliminata per creare spazio per una nuova copia. È possibile ridurre la velocità di creazione delle nuove copie Snapshot ARP per conservare le copie meno recenti utilizzando questa opzione. Se il volume contiene già il numero massimo di copie Snapshot ARP, questo intervallo specificato in questa opzione viene utilizzato per la successiva creazione della copia Snapshot ARP, invece di arw.snap.create.interval.hours. 


| *arw.surge.snap.interval.days* | Specifica l'intervallo _in giorni_ tra le copie snapshot di sovracorrente ARP. ONTAP crea una copia snapshot ARP surge quando c'è un aumento del traffico io e l'ultima copia snapshot ARP creata è precedente a questo intervallo specificato. Questa opzione specifica anche il periodo di conservazione _in giorno_ per un'istantanea di sovratensione ARP. 
|===

