---
sidebar: sidebar 
permalink: anti-ransomware/respond-abnormal-task.html 
keywords: abnormal activity, data entropy, unusual file extensions, potential ransomware attack, false positive, ransomware attack, abnormal activity notification, ransomware alert, detected abnormal volume, suspected file types, attack report, anti-ransomware attack, ransomware ems 
summary: Scopri le notifiche ARP in ONTAP e determina se si sta verificando un attacco ransomware e come rispondere. 
---
= Rispondere alle attività anomale rilevate da ONTAP ARP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando la protezione ransomware autonoma (ARP) rileva attività anomale in un volume protetto, emette un avviso. È necessario valutare la notifica per determinare se l'attività è accettabile (falso positivo) o se un attacco sembra dannoso. Dopo aver categorizzato l'attacco, è possibile eliminare l'avviso e gli avvisi relativi ai file sospetti.

Quando si categorizza un attacco, gli snapshot ARP vengono conservati per un periodo di tempo abbreviato avviato dall'operazione di categorizzazione (ONTAP 9.16.1 e versioni successive) oppure eliminati immediatamente (ONTAP 9.15.1 e versioni precedenti).


NOTE: A partire da ONTAP 9.11.1, è possibile modificare link:modify-automatic-snapshot-options-task.html["impostazioni di conservazione"] per snapshot ARP.

.A proposito di questa attività
ARP visualizza un elenco di file sospetti quando rileva una qualsiasi combinazione di elevata entropia dei dati, attività anomala del volume con crittografia dei dati ed estensioni di file insolite. A partire da ONTAP 9.17.1, sia per gli ambienti NAS che SAN, i dettagli sui picchi di entropia vengono riportati anche nella pagina Anti-ransomware di System Manager.

Quando viene emessa una notifica di avviso ARP, rispondere designando l'attività in uno dei due modi:

* *Falso positivo*
+
Il tipo di file identificato o il picco di entropia sono previsti nel carico di lavoro e possono essere ignorati.

* *Potenziale attacco ransomware*
+
Il tipo di file identificato o il picco di entropia sono inattesi nel tuo carico di lavoro e devono essere trattati come un potenziale attacco.



Il monitoraggio normale riprende dopo aver aggiornato la tua decisione e aver cancellato le notifiche ARP. ARP registra la tua valutazione nel profilo di valutazione delle minacce, utilizzando la tua scelta per monitorare le attività successive sui file.

In caso di attacco sospetto, è necessario determinare se si tratta di un attacco, rispondere al caso in cui si tratti e ripristinare i dati protetti prima di cancellare le notifiche. link:index.html#how-to-recover-data-in-ontap-after-a-ransomware-attack["Scopri di più su come eseguire il ripristino da un attacco ransomware"].


NOTE: Se si ripristina un intero volume, non vi sono avvisi da cancellare.

.Prima di iniziare
ARP deve proteggere attivamente un volume e non essere in modalità di apprendimento o valutazione.

.Fasi
È possibile utilizzare System Manager o l'interfaccia CLI di ONTAP per rispondere a attività anomale.

[role="tabbed-block"]
====
.System Manager
--
. Quando ricevi una notifica di "attività anomala", segui il link. In alternativa, accedi alla scheda *Sicurezza* della panoramica *Volumi*.
+
Gli avvisi vengono visualizzati nel riquadro *Panoramica* del menu *Eventi*.

. Nella scheda *Sicurezza*, esaminare il report sui tipi di file sospetti o sui picchi di entropia.
+
** Per i file sospetti, esaminare ogni tipo di file nella finestra di dialogo *Tipi di file sospetti* e contrassegnare ciascuno di essi singolarmente.
** Per i picchi di entropia, esaminare il report sull'entropia.


. Registra la tua risposta:
+
[cols="25,75"]
|===


| Se selezioni questo valore... | Eseguire questa azione... 


 a| 
Falso positivo
 a| 
.. Effettuare una delle seguenti operazioni:
+
*** Per avvisi sui tipi di file, seleziona *Aggiorna e cancella i tipi di file sospetti*.
*** Per i picchi di entropia, seleziona *Segnala come falso positivo*.
+
Queste azioni cancellano gli avvisi relativi a file o attività sospette. ARP riprende quindi il normale monitoraggio del volume. Per ARP/AI in ONTAP 9.16.1 e versioni successive, gli snapshot ARP vengono eliminati automaticamente dopo un periodo di conservazione abbreviato attivato dall'operazione di categorizzazione. Per ONTAP 9.15.1 e versioni precedenti, gli snapshot ARP correlati vengono eliminati automaticamente dopo la cancellazione dei tipi di file sospetti.

+

NOTE: A partire da ONTAP 9.13.1, se si utilizza MAV per proteggere le impostazioni ARP, l'operazione che si sospetta venga richiesta l'approvazione di uno o più amministratori aggiuntivi. link:../multi-admin-verify/request-operation-task.html["L'approvazione deve essere ricevuta da tutti gli amministratori"] Associato al gruppo di approvazione MAV o l'operazione non riuscirà.







 a| 
Potenziale attacco ransomware
 a| 
.. Rispondere all'attacco:
+
*** Per gli avvisi sul tipo di file, contrassegna i file selezionati come *Potenziale attacco ransomware* e link:recover-data-task.html["ripristinare i dati protetti"] .
*** Per i picchi di entropia che indicano un attacco, seleziona *Segna come potenziale attacco ransomware* e link:recover-data-task.html["ripristinare i dati protetti"] .


.. Una volta completato il ripristino dei dati, registra la tua decisione e riprendi il normale monitoraggio ARP:
+
*** Per avvisi sui tipi di file, seleziona *Aggiorna e cancella i tipi di file sospetti*.
*** Per i picchi di entropia, seleziona *Segnala come potenziale attacco ransomware* e seleziona *Salva e ignora*.





NOTE: Se hai ripristinato un intero volume, non ci sono avvisi sui tipi di file sospetti da cancellare.

La registrazione della decisione cancella il report di attacco. Per ARP/AI in ONTAP 9.16.1 e versioni successive, gli snapshot ARP vengono eliminati automaticamente dopo un periodo di conservazione abbreviato attivato dall'operazione di categorizzazione. Per ONTAP 9.15.1 e versioni precedenti, dopo il ripristino di un volume, gli snapshot ARP vengono eliminati automaticamente.

|===


--
.CLI
--
. Quando ricevi una notifica di un attacco ransomware sospetto, verifica l'ora e la gravità dell'attacco:
+
[source, cli]
----
security anti-ransomware volume show -vserver <svm_name> -volume <vol_name>
----
+
Output di esempio:

+
....
Vserver Name: vs0
Volume Name: vol1
State: enabled
Attack Probability: moderate
Attack Timeline: 5/12/2025 01:03:23
Number of Attacks: 1
Attack Detected By: encryption_percentage_analysis
....
+
È inoltre possibile controllare i messaggi EMS:

+
[source, cli]
----
event log show -message-name callhome.arw.activity.seen
----
. Generare un report sugli attacchi e prendere nota della posizione di output:
+
[source, cli]
----
security anti-ransomware volume attack generate-report -vserver <svm_name> -volume <vol_name> -dest-path <[svm_name]:[junction_path/sub_dir_name]>
----
+
Esempio di comando:

+
[listing]
----
security anti-ransomware volume attack generate-report -vserver vs0 -volume vol1 -dest-path vs0:vol1
----
+
Output di esempio:

+
[listing]
----
Report "report_file_vs0_vol1_14-09-2021_01-21-08" available at path "vs0:vol1/"
----
. Visualizzare il report su un sistema client di amministrazione. Ad esempio:
+
[listing]
----
cat report_file_vs0_vol1_14-09-2021_01-21-08
----
. In base alla valutazione delle estensioni dei file o dei picchi di entropia, esegui una delle seguenti azioni:
+
** Falso positivo
+
Esegui uno dei seguenti comandi per registrare la tua decisione e riprendere il normale monitoraggio di Autonomous Ransomware Protection:

+
*** Per le estensioni dei file:
+
[source, cli]
----
anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> [<extension_identifiers>] -false-positive true
----
+
Utilizzare il seguente parametro opzionale per identificare solo estensioni specifiche come falsi positivi:

+
**** `[-extension <text>, … ]`: Estensioni di file


*** Per i picchi di entropia:
+
[source, cli]
----
security anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> -start-time <MM/DD/YYYY HH:MM:SS> -end-time <MM/DD/YYYY HH:MM:SS> -false-positive true
----


** Potenziale attacco ransomware
+
Rispondere all'attacco e link:../anti-ransomware/recover-data-task.html["Recuperare i dati dallo snapshot di backup creato da ARP"]. esegui uno dei seguenti comandi per registrare la tua decisione e riprendere il normale monitoraggio ARP:

+
*** Per le estensioni dei file:
+
[source, cli]
----
anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> [<extension identifiers>] -false-positive false
----
+
Utilizza il seguente parametro opzionale per identificare solo estensioni specifiche come potenziale ransomware:

+
**** `[-extension <text>, … ]`: Estensione file


*** Per i picchi di entropia:
+
[source, cli]
----
security anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> -start-time <MM/DD/YYYY HH:MM:SS> -end-time <MM/DD/YYYY HH:MM:SS> -false-positive false
----




+
Questo  `clear-suspect` L'operazione cancella il report di attacco. Non ci sono avvisi di tipo di file sospetto da cancellare se è stato ripristinato un intero volume. Per ARP/AI in ONTAP 9.16.1 e versioni successive, gli snapshot ARP vengono eliminati automaticamente dopo un periodo di conservazione abbreviato attivato dall'operazione di categorizzazione. Per ONTAP 9.15.1 e versioni precedenti, gli snapshot ARP vengono eliminati automaticamente dopo il ripristino di un volume o la cancellazione di un evento sospetto.

. Se si sta utilizzando MAV e un previsto `clear-suspect` L'operazione richiede ulteriori approvazioni, ogni responsabile dell'approvazione del gruppo MAV deve:
+
.. Mostra la richiesta:
+
[source, cli]
----
security multi-admin-verify request show
----
.. Approvare la richiesta di riprendere il normale monitoraggio anti-ransomware:
+
[source, cli]
----
security multi-admin-verify request approve -index[<number returned from show request>]
----
+
La risposta dell'ultimo responsabile dell'approvazione del gruppo indica che il volume è stato modificato e che viene registrato un falso positivo.



. Se si utilizza MAV e si è un responsabile dell'approvazione del gruppo MAV, è anche possibile rifiutare una richiesta con un sospetto chiaro:
+
[source, cli]
----
security multi-admin-verify request veto -index[<number returned from show request>]
----


--
====
.Informazioni correlate
* link:https://kb.netapp.com/onprem%2Fontap%2Fda%2FNAS%2FUnderstanding_Autonomous_Ransomware_Protection_attacks_and_the_Autonomous_Ransomware_Protection_snapshot#["KB: Comprendere gli attacchi di protezione ransomware autonoma e lo snapshot di protezione ransomware autonoma"^]
* link:modify-automatic-snapshot-options-task.html["Modificare le opzioni delle istantanee automatiche"]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume["volume di sicurezza anti-ransomware"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+multi-admin-verify+request["richiesta di verifica multi-amministrazione di sicurezza"^]

