---
sidebar: sidebar 
permalink: anti-ransomware/switch-learning-to-active-mode.html 
keywords: ransomware, arp, mode, switch, active, learning, autonomous ransomware protection 
summary: Per ARP 9.15.1 e versioni precedenti in ambienti NAS, commutare manualmente o automaticamente un volume abilitato per ARP dalla modalità di apprendimento alla modalità attiva. 
---
= Passare alla modalità attiva in ONTAP ARP dopo un periodo di apprendimento
:allow-uri-read: 


[role="lead"]
Per gli ambienti NAS, è possibile commutare manualmente o automaticamente un volume abilitato per ARP dalla modalità di apprendimento alla modalità attiva. È necessario cambiare modalità se si utilizza ARP con ONTAP 9.15.1 e versioni precedenti o se ARP è in esecuzione su volumi FlexGroup .

Dopo che ARP ha completato un periodo di apprendimento di almeno 30 giorni, è possibile passare manualmente alla modalità attiva. A partire da ONTAP 9.13.1, ARP determina automaticamente l'intervallo di apprendimento ottimale e automatizza il passaggio, che potrebbe avvenire anche prima dei 30 giorni.

Se si utilizza ARP su volumi FlexVol con ONTAP 9.16.1 o versione successiva, la protezione ARP/ai è attivata e diventa attiva automaticamente. Non è richiesto alcun periodo di apprendimento.


NOTE: Nei volumi esistenti, l'apprendimento e le modalità attive si applicano solo ai dati scritti di recente, non ai dati già esistenti nel volume. I dati esistenti non vengono sottoposti a scansione e analizzati, poiché le caratteristiche del traffico dati normale precedente vengono assunte in base ai nuovi dati dopo che il volume è stato abilitato per ARP.



== Passare manualmente alla modalità attiva dopo il periodo di apprendimento

Per ONTAP 9.10.1 a 9.15.1 e ARP con volumi FlexGroup , è possibile passare manualmente dalla modalità di apprendimento ARP alla modalità attiva utilizzando System Manager o ONTAP CLI una volta completato il periodo di apprendimento.

.A proposito di questa attività
La transizione manuale alla modalità attiva dopo un periodo di apprendimento descritta in questa procedura è specifica degli ambienti NAS.

.Fasi
È possibile utilizzare System Manager o ONTAP CLI per passare dalla modalità di apprendimento alla modalità attiva.

[role="tabbed-block"]
====
.System Manager
--
. Selezionare *Storage > Volumes* (archiviazione > volumi), quindi selezionare il volume pronto per la modalità attiva.
. Nella scheda *sicurezza* della panoramica *volumi*, seleziona *passa alla modalità attiva* nella casella Anti-ransomware.
. È possibile verificare lo stato ARP del volume nella casella *Anti-ransomware*.


--
.CLI
--
. Modificare il volume protetto per passare alla modalità attiva, se non è già stato fatto automaticamente:
+
[source, cli]
----
security anti-ransomware volume enable -volume <vol_name> -vserver <svm_name>
----
+
È anche possibile passare alla modalità attiva con il comando modify volume:

+
[source, cli]
----
volume modify -volume <vol_name> -vserver <svm_name> -anti-ransomware-state enabled
----
. Verificare lo stato ARP del volume.
+
[source, cli]
----
security anti-ransomware volume show
----


--
====


== Passaggio automatico dalla modalità di apprendimento alla modalità attiva

A partire da ONTAP 9.13.1, l'apprendimento adattivo è stato aggiunto all'analisi ARP e il passaggio dalla modalità di apprendimento alla modalità attiva avviene automaticamente. La decisione autonoma di ARP di passare automaticamente dalla modalità di apprendimento alla modalità attiva si basa sulle impostazioni di configurazione delle seguenti opzioni:

[listing]
----
 -anti-ransomware-auto-switch-minimum-incoming-data-percent
 -anti-ransomware-auto-switch-duration-without-new-file-extension
 -anti-ransomware-auto-switch-minimum-learning-period
 -anti-ransomware-auto-switch-minimum-file-count
 -anti-ransomware-auto-switch-minimum-file-extension
----
Se il passaggio automatico è abilitato, il volume passerà automaticamente alla modalità attiva dopo un massimo di 30 giorni, anche se non vengono soddisfatte tutte le condizioni. Questo limite di 30 giorni è fisso e non può essere modificato.

Per ulteriori informazioni sulle opzioni di configurazione ARP, compresi i valori predefiniti, consultare la link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-auto-switch-to-enable-mode-show.html["Riferimento al comando ONTAP"^].

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume["volume di sicurezza anti-ransomware"^]

