---
sidebar: sidebar 
permalink: snapmirror-active-sync/cloud-mediator-requirements-concept.html 
keywords: SM-BC, SMBC, ONTAP, Cloud Mediator, prerequisites, requirements, configuration, firewall, latency, proxy, certificate, snapmirror active sync 
summary: Prima di installare ONTAP Cloud Mediator, è necessario soddisfare determinati requisiti. 
---
= Prepararsi alla configurazione di ONTAP Cloud Mediator
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di te link:cloud-mediator-config-task.html["configurare ONTAP Cloud Mediator"] , è necessario assicurarsi che i prerequisiti siano soddisfatti.



== Requisiti del firewall

L'impostazione del firewall sul controller di dominio deve consentire il traffico HTTPS  `api.bluexp.netapp.com` da entrambi i cluster.



== Requisiti del server proxy

Se si utilizzano server proxy per SnapMirror ActiveSync, assicurarsi che i server proxy siano stati creati e di disporre delle seguenti informazioni sul server proxy:

* IP proxy HTTPS
* Porta
* Nome utente
* Password




== Latenza

La latenza ping consigliata tra il server cloud NetApp Console e i peer del cluster SnapMirror Active Sync è inferiore a 200 ms.



== Certificati CA radice

.Controllare il cluster per i certificati
ONTAP è dotato di certificati CA radice noti preinstallati, pertanto nella maggior parte dei casi non è necessario installare il certificato CA radice del server NetApp Console. Prima di iniziare la configurazione di ONTAP Cloud Mediator, è possibile controllare il cluster per verificare che i certificati esistano:

Esempio:

[listing]
----
C1_cluster% openssl s_client -showcerts -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com | egrep "s:|i:"

depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify error:num=19:self-signed certificate in certificate chain
verify return:1
depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify return:1
depth=3 C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
verify return:1
depth=2 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
verify return:1
depth=1 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
verify return:1
depth=0 C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
verify return:1
 0 s:C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
 1 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
 2 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
   i:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
 3 s:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
 4 s:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services

C1_cluster::> security certificate show -common-name Sectigo*|USERTrust*|AAA*
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
C1_sti245-vsim-ocvs024k_1775534714 42F2CCDA1B6937445F15FE752810B8F4 SectigoPublicServerAuthenticationRootE46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root E46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 758DFD8BAE7C0700FAA925A7E1C7AD14 SectigoPublicServerAuthenticationRootR46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root R46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 5C8B99C55A94C5D27156DECD8980CC26 USERTrustECCCertificationAuthority server-ca
    Certificate Authority: USERTrust ECC Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

C1_sti245-vsim-ocvs024k_1775534714 01FD6D30FCA3CA51A81BBC640E35032D USERTrustRSACertificationAuthority server-ca
    Certificate Authority: USERTrust RSA Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

----
.Controlla il server proxy per i certificati installati
Se si utilizza un proxy per connettersi al servizio ONTAP Cloud Mediator nella console NetApp , assicurarsi che i certificati CA radice del server proxy siano installati in ONTAP:

Esempio:

[listing]
----
C1_cluster% openssl s_client -showcerts -proxy <ip:port> -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com |egrep "s:|i:"
----
.Scarica il certificato CA:
Se necessario, è possibile scaricare i certificati CA radice dal sito Web dell'autorità di certificazione e installarli sui cluster.

Esempio:

[listing]
----
C1_cluster::> security certificate install -type server-ca -vserver C1_cluster

C2_cluster::> security certificate install -type server-ca -vserver C2_cluster
----