---
sidebar: sidebar 
permalink: snapmirror-active-sync/cluster-config-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP, Mediator, ONTAP Cloud Mediator, initialize, snapmirror active sync 
summary: Quando si utilizza ONTAP Mediator o ONTAP Cloud Mediator con SnapMirror ActiveSync, è necessario innanzitutto assicurarsi che il cluster sia configurato correttamente. 
---
= Configurare i cluster ONTAP per la sincronizzazione attiva SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync utilizza cluster peer per proteggere i dati in caso di failover. Prima di configurare ONTAP Mediator o ONTAP Cloud Mediator per SnapMirror Active Sync, è necessario assicurarsi che il cluster sia configurato correttamente.

.Prima di iniziare
Prima di configurare ONTAP Mediator o ONTAP Cloud Mediator, è necessario confermare quanto segue:

. Tra i cluster esiste una relazione di peering tra cluster.
+

NOTE: L'IPSpace predefinito è richiesto dalla sincronizzazione attiva di SnapMirror per le relazioni di cluster peer. Un IPSpace personalizzato non è supportato.

+
link:../peering/create-cluster-relationship-93-later-task.html["Creazione di una relazione peer del cluster"]

. Le SVM vengono create su ciascun cluster.
+
link:../smb-config/create-svms-data-access-task.html["Creazione di una SVM"]

. Tra le SVM di ciascun cluster esiste una relazione peer.
+
link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Creazione di una relazione di peering SVM"]

. I volumi esistono per i tuoi LUN.
+
link:../smb-config/create-volume-task.html["Creazione di un volume"]

. Su ogni nodo del cluster viene creato almeno un SAN LIF.
+
link:../san-admin/manage-lifs-all-san-protocols-concept.html["Considerazioni per le LIF in un ambiente SAN cluster"]

+
link:../networking/create_a_lif.html["Creazione di una LIF"]

. I LUN necessari vengono creati e mappati su un igroup, che viene utilizzato per mappare i LUN sull'iniziatore sull'host dell'applicazione.
+
link:../san-admin/provision-storage.html["Creare LUN e mappare igroups"]

. L'host dell'applicazione viene nuovamente scansionato per rilevare eventuali nuovi LUN.

