---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: Utilizza SnapMirror Active Sync per proteggere le applicazioni con le LUN, consentendo il failover delle applicazioni in modo trasparente, garantendo la business continuity in caso di disastro. 
---
= Scopri di più sulla sincronizzazione attiva ONTAP SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync, noto anche come SnapMirror Business Continuity (SM-BC), consente ai servizi aziendali di continuare a funzionare in caso di guasto completo del sito.  Questa tecnologia consente alle applicazioni di eseguire il failover senza problemi su una copia secondaria, senza interventi manuali o script personalizzati.

NetApp SnapMirror Active Sync (SM-as) è progettato per offrire una protezione a livello di applicazione più granulare, economica e facile da usare, con failover automatico.  La sincronizzazione attiva SnapMirror consente ai servizi aziendali critici di continuare a funzionare anche in caso di guasto completo del sito.  Con SnapMirror Active Sync, ora puoi replicare in modo sincrono più volumi di un'applicazione (aggiungendoli a un gruppo di coerenza) tra siti situati in posizioni geograficamente distanti.  È possibile eseguire automaticamente il failover sulla copia secondaria in caso di interruzione della copia primaria, garantendo così la continuità aziendale per le applicazioni di primo livello.

In alcuni Paesi, le normative per gli istituti finanziari impongono alle aziende di essere periodicamente raggiungibili dai loro data center secondari.  SnapMirror Active Sync, con i suoi cluster ad alta disponibilità, consente questi switchover dei data center per garantire la continuità aziendale.

Disponibile a partire da ONTAP 9.9.1, SnapMirror ActiveSync è supportato sui cluster AFF e All-Flash SAN Array (ASA).  I cluster primari e secondari devono essere dello stesso tipo: ASA, ASA r2 o AFF.  SnapMirror Active Sync protegge le applicazioni con LUN iSCSI o FCP o namespace NVMe.

SnapMirror ActiveSync supporta sia configurazioni simmetriche che asimmetriche.  Il supporto per attivo/attivo simmetrico è stato introdotto in ONTAP 9.15.1.  La configurazione attiva/attiva simmetrica consente a entrambe le copie di una LUN protetta di eseguire operazioni di I/O in lettura e scrittura con replica sincrona bidirezionale, consentendo a ciascuna copia della LUN di soddisfare le richieste di I/O locali.


NOTE: A partire da luglio 2024, il contenuto dei report tecnici precedentemente pubblicati come PDF è stato integrato nella documentazione del prodotto ONTAP. La documentazione relativa alla sincronizzazione attiva di ONTAP SnapMirror ora include il contenuto del documento _TR-4878: Sincronizzazione attiva di SnapMirror_.



== Benefici

SnapMirror Active Sync offre i seguenti benefici:

* Disponibilità continua per le applicazioni business-critical.
* Capacità di ospitare applicazioni critiche in maniera alternativa dai siti primario e secondario.
* Gestione semplificata delle applicazioni tramite gruppi di coerenza dell'ordine di scrittura dipendente.
* Possibilità di testare il failover per ogni applicazione.
* Creazione istantanea di cloni in mirroring senza influire negativamente sulla disponibilità applicativa.
* Possibilità di implementare carichi di lavoro protetti e non protetti nello stesso cluster ONTAP.
* L'identità della LUN, dello spazio dei nomi NVMe, del sottosistema NVMe o dell'unità di archiviazione rimane la stessa, quindi l'applicazione li vede come un dispositivo virtuale condiviso.
* Possibilità di riutilizzare i cluster secondari con la flessibilità per creare cloni istantanei per l'utilizzo delle applicazioni a scopo di sviluppo-test, UAT o di reporting senza influire negativamente sulla disponibilità o sulla performance applicativa.


La sincronizzazione attiva SnapMirror consente di proteggere le LUN dei dati o gli spazi dei nomi NVMe, consentendo alle applicazioni di eseguire il failover in modo trasparente per garantire la continuità aziendale in caso di emergenza. Per ulteriori informazioni, consultare link:use-cases-concept.html["Casi di utilizzo"] .



== Concetti chiave

SnapMirror ActiveSync utilizza gruppi di coerenza per garantire che i dati vengano replicati.  SnapMirror Active Sync utilizza ONTAP Mediator o, a partire da ONTAP 9.17.1, Cloud Mediator per il failover automatico, garantendo che i dati vengano forniti in caso di disastro. Quando si pianifica l'implementazione SnapMirror Active Sync, è importante comprendere i concetti essenziali di SnapMirror Active Sync e della sua architettura.

.Asimmetria e simmetria
Nelle configurazioni simmetriche attive/attive, entrambi i siti possono accedere allo storage locale per l'I/O attivo. La configurazione simmetrica attiva/attiva è ottimizzata per applicazioni in cluster, tra cui VMware vMSC, Windows Failover Cluster con SQL e Oracle RAC.

Nelle configurazioni attive/attive asimmetriche i dati sul sito secondario vengono inoltrati a una LUN, a uno spazio dei nomi o a un'unità di archiviazione.

Per ulteriori informazioni, vedere xref:architecture-concept.html[Architettura SnapMirror Active Sync].

.Gruppo di coerenza
Per i sistemi AFF e ASA a link:../consistency-groups/index.html["gruppo di coerenza"] è una raccolta di volumi FlexVol che forniscono una garanzia di coerenza per il carico di lavoro dell'applicazione che deve essere protetto per la continuità aziendale. Nei sistemi ASA r2, un gruppo di coerenza è una raccolta di unità di storage.

Lo scopo di un gruppo di coerenza è acquisire immagini snapshot simultanee di una raccolta di volumi o unità di storage, garantendo così copie della raccolta coerenti con gli arresti anomali in un determinato momento. Un gruppo di coerenza garantisce che tutti i volumi di un set di dati vengano messi in stato di quiescenza e quindi acquisiti esattamente nello stesso momento. Ciò fornisce un punto di ripristino coerente a livello di dati su tutti i volumi o le unità di storage che supportano il set di dati. Un gruppo di coerenza mantiene quindi la coerenza dell'ordine di scrittura dipendente. Se si decide di proteggere le applicazioni per la continuità operativa, il gruppo di volumi o unità di storage corrispondente a tale applicazione deve essere aggiunto a un gruppo di coerenza in modo da stabilire una relazione di protezione dei dati tra un gruppo di coerenza di origine e uno di destinazione. La coerenza di origine e di destinazione deve contenere lo stesso numero e tipo di volumi.

.Costituente
Un singolo volume, LUN o namespace NVMe (a partire da ONTAP 9.17.1) che fa parte del gruppo di coerenza protetto nella relazione di sincronizzazione attiva SnapMirror .

.Mediatore ONTAP
IL link:../mediator/index.html["Mediatore ONTAP"] Riceve informazioni sullo stato di salute dei cluster e dei nodi ONTAP peer, orchestrando i due e determinando se ciascun nodo/cluster è integro e funzionante. ONTAP Mediator fornisce informazioni sullo stato di salute relative a:

* Cluster peer ONTAP
* Nodi del cluster peer ONTAP
* Gruppi di coerenza (che definiscono le unità di failover in una relazione di sincronizzazione attiva di SnapMirror); per ogni gruppo di coerenza vengono fornite le seguenti informazioni:
+
** Stato di replica: Non inizializzato, in sincronizzazione o non sincronizzato
** Il cluster che ospita la copia primaria
** Contesto operativo (utilizzato per il failover pianificato)




Grazie a queste informazioni sullo stato di salute di ONTAP Mediator, i cluster possono differenziare i diversi tipi di guasti e determinare se eseguire un failover automatico. ONTAP Mediator è una delle tre parti nel quorum della sincronizzazione attiva di SnapMirror insieme ai cluster ONTAP (primario e secondario). Per raggiungere un consenso, almeno due parti del quorum devono concordare una certa operazione.


NOTE: A partire da ONTAP 9.15.1, System Manager visualizza lo stato della relazione di sincronizzazione attiva di SnapMirror da uno dei cluster. È inoltre possibile monitorare lo stato di ONTAP Mediator da entrambi i cluster in Gestione di sistema. Nelle release precedenti di ONTAP, System Manager visualizza lo stato delle relazioni di sincronizzazione attive di SnapMirror dal cluster di origine.

.Mediatore cloud ONTAP
ONTAP Cloud Mediator è disponibile a partire da ONTAP 9.17.1. ONTAP Cloud Mediator fornisce gli stessi servizi di ONTAP Mediator, con la differenza che è ospitato nel cloud tramite NetApp Console.

.Failover pianificato
Operazione manuale per la modifica del ruolo delle copie in una relazione di sincronizzazione attiva di SnapMirror. I siti primari diventano i secondari, mentre i siti secondari diventano quelli primari.

.Failover automatico non pianificato (AUFO)
Un'operazione automatica per eseguire un failover sulla copia mirror. L'operazione richiede l'assistenza del ONTAP Mediator per rilevare che la copia primaria non è disponibile.

.Polarizzazione primaria-prima e primaria
La sincronizzazione attiva di SnapMirror utilizza un principio primario che dà la preferenza alla copia primaria per servire l'i/o nel caso di una partizione di rete.

La polarizzazione primaria è un'implementazione speciale del quorum che migliora la disponibilità di un set di dati protetto e sincronizzati attivo di SnapMirror. Se la copia primaria è disponibile, la polarizzazione primaria entra in vigore quando il ONTAP Mediator non è raggiungibile da entrambi i cluster.

Il bias primario-primo e primario sono supportati nella sincronizzazione attiva di SnapMirror a partire da ONTAP 9.15.1. Le copie primarie sono designate in System Manager e sono prodotte con l'API REST e la CLI.

.Fuori sincronizzazione (OOS)
Quando l'i/o dell'applicazione non viene replicato nel sistema di storage secondario, viene segnalato come **fuori sincronizzazione**. Uno stato fuori sincronizzazione indica che i volumi secondari non sono sincronizzati con il primario (origine) e che la replica di SnapMirror non avviene.

Se lo stato dello specchio è `Snapmirrored` , ciò indica che è stata stabilita una relazione SnapMirror e che il trasferimento dei dati è completo, ovvero che il volume di destinazione è aggiornato con il volume di origine.

SnapMirror Active Sync supporta la risincronizzazione automatica, consentendo alle copie di tornare allo stato InSync.

A partire da ONTAP 9.15.1, supporta la sincronizzazione attiva di SnapMirror link:interoperability-reference.html#fan-out-configurations["riconfigurazione automatica nelle configurazioni fan-out"].

.Configurazione uniforme e non uniforme
* **Uniform host access** significa che gli host da entrambi i siti sono connessi a tutti i percorsi ai cluster di storage su entrambi i siti. I percorsi tra siti sono estesi su diverse distanze.
* **Accesso host non uniforme** significa che gli host in ogni sito sono collegati solo al cluster nello stesso sito. I percorsi tra siti e quelli estesi non sono connessi.



NOTE: È supportato un accesso host uniforme per qualsiasi implementazione SnapMirror Active Sync; l'accesso host non uniforme è supportato solo per le implementazioni Active/Active simmetriche.

.RPO zero
RPO è l'acronimo di Recovery Point Objective, ovvero la quantità di perdita di dati ritenuta accettabile in un determinato periodo di tempo. Zero RPO indica che non è accettabile alcuna perdita di dati.

.RTO zero
RTO è l'obiettivo del tempo di recovery, ovvero il tempo considerato accettabile per un'applicazione per ripristinare le normali operazioni senza interruzioni in seguito a un black-out, un guasto o altri eventi di perdita di dati. Zero RTO significa che non è accettabile alcun downtime.



== Supporto della configurazione di sincronizzazione attiva SnapMirror tramite la versione ONTAP

Il supporto per la sincronizzazione attiva SnapMirror varia a seconda della versione di ONTAP:

[cols="4*"]
|===


| Versione di ONTAP | Cluster supportati | Protocolli supportati | Configurazioni supportate 


| 9.17.1 e versioni successive  a| 
* AFF
* ASA
* C-Series
* ASA r2

 a| 
* ISCSI
* FC
* NVMe per carichi di lavoro VMware

 a| 
* Asimmetrico attivo/attivo



NOTE: L'attivo/attivo asimmetrico non supporta ASA r2 e NVMe Per ulteriori informazioni sul supporto NVMe, vedere link:../nvme/support-limitations.html["Configurazione, supporto e limitazioni NVMe"] .

* Attivo/attivo simmetrico




| 9.16.1 e versioni successive  a| 
* AFF
* ASA
* C-Series
* ASA r2

 a| 
* ISCSI
* FC

 a| 
* Asimmetrico attivo/attivo
* Configurazione simmetrica attiva/attiva Le configurazioni simmetriche attive/attive supportano cluster a 4 nodi in ONTAP 9.16.1 e versioni successive.  Per ASA r2 sono supportati solo cluster a 2 nodi.




| 9.15.1 e versioni successive  a| 
* AFF
* ASA
* C-Series

 a| 
* ISCSI
* FC

 a| 
* Asimmetrico attivo/attivo
* Le configurazioni simmetriche attive/attive supportano cluster a 2 nodi in ONTAP 9.15.1. I cluster a 4 nodi sono supportati in ONTAP 9.16.1 e versioni successive.




| 9.9.1 e versioni successive  a| 
* AFF
* ASA
* C-Series

 a| 
* ISCSI
* FC

 a| 
Asimmetrico attivo/attivo

|===
I cluster primari e secondari devono essere dello stesso tipo: link:../san-admin/learn-about-asa.html["ASA"] , link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^] , o AFF.
