---
sidebar: sidebar 
permalink: snapmirror-active-sync/limits-reference.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snapmirror active sync 
summary: Esistono diverse restrizioni e limitazioni aggiuntive quando si utilizza la sincronizzazione attiva di SnapMirror. 
---
= Limiti degli oggetti per ONTAP SnapMirror ActiveSync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la preparazione all'utilizzo della sincronizzazione attiva di SnapMirror, tieni presente i seguenti limiti degli oggetti.



[[consistency-groups-in-a-cluster]]
== Gruppi di coerenza in un cluster

I limiti dei gruppi di coerenza per un cluster con una configurazione SAN di sincronizzazione attiva SnapMirror vengono calcolati in base alle relazioni e dipendono dalla versione di ONTAP utilizzata. I limiti sono indipendenti dalla piattaforma.

|===
| Versione di ONTAP | Numero massimo di relazioni 


| ONTAP 9.11.1 e versioni successive | 50* 


| ONTAP 9.10.1 | 20 


| ONTAP 9.9.1 | 5 
|===
{Asterisk} a partire da ONTAP 9.16.1, SnapMirror Active Sync supporta cluster a quattro nodi in configurazioni Active/Active simmetriche. In un cluster a quattro nodi, sono supportati 100 gruppi di coerenza.



[[volumes-per-consistency-group]]
== Volumi per gruppo di coerenza

Il numero massimo di volumi per gruppo di coerenza con SnapMirror active sync per le configurazioni SAN è indipendente dalla piattaforma.

|===
| Versione di ONTAP | Numero massimo di volumi supportati in una relazione di gruppo di coerenza 


| ONTAP 9.15.1 e versioni successive | 80 


| ONTAP 9.10.1-9.14.1 | 16 


| ONTAP 9.9.1 | 12 
|===


[[volumes]]
== Volumi

I limiti di volume in SnapMirror active sync per le configurazioni SAN vengono calcolati in base al numero di endpoint, non al numero di relazioni. Un gruppo di coerenza con 12 volumi contribuisce con 12 endpoint sia sul cluster primario che su quello secondario. Sia SnapMirror active sync che le relazioni SnapMirror sincrone contribuiscono al numero totale di endpoint.


IMPORTANT: Questi limiti si applicano ai sistemi FAS, AFF e ASA . Se si dispone di un sistema ASA r2 (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30 o ASA A20), consultare link:https://docs.netapp.com/us-en/asa-r2/data-protection/manage-consistency-groups.html["Documentazione di ASA r2"^] .

Nella tabella seguente sono inclusi gli endpoint massimi per piattaforma.

|===
| Piattaforma 3+| Endpoint per ha per la sincronizzazione attiva SnapMirror 3+| Endpoint di sincronizzazione generale attivi SnapMirror e sincronizzazione sincrona per ha 


|  | ONTAP 9.11.1 e versioni successive | ONTAP 9.10.1 | ONTAP 9.9.1 | ONTAP 9.11.1 e versioni successive | ONTAP 9.10.1 | ONTAP 9.9.1 


| AFF | 400* | 200 | 60 | 400 | 200 | 80 


| ASA | 400* | 200 | 60 | 400 | 200 | 80 
|===
{Asterisk} a partire da ONTAP 9.16.1, SnapMirror Active Sync supporta cluster a quattro nodi in configurazioni Active/Active simmetriche. Il limite totale per un cluster a quattro nodi è di 800 endpoint.



[[san-object-limits]]
== Limiti degli oggetti SAN

I limiti degli oggetti SAN sono inclusi nella tabella seguente. I limiti si applicano indipendentemente dalla piattaforma.

|===
| Oggetto in una relazione di sincronizzazione attiva SnapMirror | Conta 


| LUN per volume  a| 
* 256 (ONTAP 9.9.1 - ONTAP 9.15.0)
* 512 (ONTAP 9.15.1 e versioni successive)




| Numero di LUN, namespace o unità di archiviazione univoci per soluzione di sincronizzazione attiva SnapMirror 2 x 2 | 4,096 


| Numero di LUN, namespace o unità di archiviazione univoci per soluzione di sincronizzazione attiva SnapMirror 4 x 4 (disponibile a partire da ONTAP 9.16.1) | 6,144 


| LIF per SVM (con almeno un volume in una relazione di sincronizzazione attiva SnapMirror ) | 256 


| LIF tra cluster per nodo | 4 


| LIF tra cluster per cluster | 8 
|===


[[nas-object-limits]]
== Limiti degli oggetti NAS

A partire da ONTAP 9.19.1, la sincronizzazione attiva di SnapMirror supporta i protocolli NAS. I limiti degli oggetti NAS sono inclusi nella tabella seguente.

|===
| Numero massimo di oggetti in una relazione di sincronizzazione attiva SnapMirror | Conta 


| Numero di unità di failover per coppia HA | 50 


| Numero di SVM NAS per coppia HA | 50 


| Numero di volumi per SVM | 80 


| Numero di gruppi di coerenza applicativa per coppia HA | Non supportato 


| Numero di volumi per gruppo di consistenza | Non applicabile 


| Numero di volumi per coppia HA | 400 


| Coppie di cluster gestibili da un singolo mediatore | 10 


| Numero di nodi in un cluster  a| 
2 (solo cluster AFF)

4 (solo cluster AFX)

|===


[[nvme-object-limits]]
== Limiti degli oggetti NVMe

A partire da ONTAP 9.17.1, SnapMirror ActiveSync supporta il protocollo NVMe. I limiti degli oggetti NVMe sono riportati nella tabella seguente.

|===
| Numero massimo di oggetti in una relazione di sincronizzazione attiva SnapMirror | Conta 


| Numero di mappe dello spazio dei nomi per nodo | 4K 


| Dimensione del cluster | 2 nodi 


| Numero di gruppi di coerenza per coppia HA | 50 


| Numero di volumi in un singolo gruppo di coerenza ActiveSync NVMe SnapMirror | 80 


| Numero di volumi in una coppia HA | 400 


| Sottosistemi NVMe per gruppo di coerenza | 16 


| Mappe degli spazi dei nomi per gruppo di coerenza | 256 
|===
.Informazioni correlate
* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../consistency-groups/limits.html["Limiti del gruppo di coerenza"]

