---
sidebar: sidebar 
permalink: snapmirror-active-sync/planned-failover-unsuccessful-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, failover, planned failover, common Snapshot copy, snapmirror active sync 
summary: 'Dopo aver eseguito il `snapmirror failover start` il comando, l"output per `snapmirror failover show` command visualizza un messaggio che indica che è in corso un"operazione senza interruzioni.' 
---
= Failover pianificato non riuscito
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilizzare le seguenti informazioni se l'operazione di failover pianificata non riesce.

.Problema:
Dopo aver eseguito il `snapmirror failover start` il comando, l'output per `snapmirror failover show` command visualizza un messaggio che indica che è in corso un'operazione senza interruzioni.

....
Cluster1::> snapmirror failover show
Source Destination Error
Path Path Type Status start-time end-time Reason
-------- ----------- -------- --------- ---------- ---------- ----------
vs1:/cg/cg vs0:/cg/cg planned failed 10/1/2020 10/1/2020 SnapMirror Failover cannot start because a volume move is running. Retry the command once volume move has finished.
                                                          08:35:04 08:35:04
....
.Causa:
Un failover pianificato non può iniziare quando è in corso un'operazione senza interruzioni, tra cui lo spostamento del volume, il trasferimento degli aggregati e il failover dello storage.

.Soluzione:
Attendere il completamento dell'operazione senza interruzioni e provare a eseguire nuovamente l'operazione di failover.
