---
sidebar: sidebar 
permalink: snapmirror-active-sync/prerequisites-reference.html 
keywords: SM-BC, SMBC, prerequisites, planning, software, hardware, licensing, protocols, network, snapmirror active sync 
summary: Durante la pianificazione della distribuzione di una soluzione di sincronizzazione attiva di SnapMirror è necessario considerare diversi prerequisiti. 
---
= Prerequisiti per la sincronizzazione attiva di SnapMirror in ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante il planning della distribuzione SnapMirror Active Sync, assicurati di aver soddisfatto i vari requisiti di configurazione di hardware, software e sistema.



== Hardware

Nella tabella seguente sono illustrate le configurazioni cluster NetApp supportate.

[cols="25,25,25,25"]
|===


| Tipo di cluster | Modelli supportati | Funzionalità supportate | Nodi supportati 


 a| 
AFF
 a| 
A-Series e C-Series
 a| 
Failover automatico duplex (Symmetric Active/Active), failover automatico (Asymmetric Active/Active)
 a| 
Cluster a due o quattro nodi ^1^



 a| 
Array All SAN (ASA)
 a| 
A-Series e C-Series
 a| 
Failover automatico Duplex (Symmetric AA), Automated failover (Asymmetric AA)
 a| 
Cluster a due o quattro nodi ^1^



 a| 
ASA r2
 a| 
-
 a| 
Duplex failover automatico (AA simmetrici)
 a| 
Cluster a due nodi high Availability (ha)

|===
. Il supporto per cluster a quattro nodi è disponibile a partire da ONTAP 9.16.1 e richiede Symmetric AA.


La tabella riportata di seguito illustra le funzionalità di replica tra i tipi di cluster.

[cols="33,33,33"]
|===


| Tipo di cluster 1 | Tipo di cluster 2 | Replica supportata? 


 a| 
Serie A.
 a| 
C-Series
 a| 
Sì



 a| 
AFF
 a| 
ASA
 a| 
No



 a| 
ASA ^1^
 a| 
ASA r2
 a| 
No

|===
. Per ulteriori informazioni sui tipi di cluster supportati da ASA, vedere link:../asa/support-limitations.html["Limiti di configurazione e supporto degli array SAN all-flash"].




== Software

* ONTAP 9.9.1 o versione successiva
* Mediatore ONTAP 1.2 o versione successiva
* Un server Linux o una macchina virtuale per ONTAP Mediator che esegue uno dei seguenti:


[cols="30,70"]
|===


| Versione del mediatore ONTAP | Versioni Linux supportate 


 a| 
1,9
 a| 
* Red Hat Enterprise Linux
+
** Compatibile: 8,4, 8,5, 8,6, 8,7, 8,9, 9,1 e 9,3 ^1^
** Consigliato: 8,8, 8,10, 9,0, 9,2, 9,4 e 9,5


* Rocky Linux 8 e 9




 a| 
1,8
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 8,9, 8,10, 9,0, 9,1, 9,2, 9,3 e 9,4
* Rocky Linux 8 e 9




 a| 
1,7
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 8,9, 9,0, 9,1, 9,2 e 9,3
* Rocky Linux 8 e 9




 a| 
1.6
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 e 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3, 8,4, 8,5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3, 8,4, 8,5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.0, 8.1
* CentOS: 7.6, 7.7, 7.8, 7.9


|===
. Compatibile significa che RHEL non supporta più questa versione, ma ONTAP Mediator può ancora essere installato.




== Licensing

* La licenza sincrona SnapMirror deve essere applicata su entrambi i cluster.
* La licenza SnapMirror deve essere applicata su entrambi i cluster.
+

NOTE: Se i sistemi storage ONTAP sono stati acquistati prima di giugno 2019, vedere link:https://mysupport.netapp.com/site/systems/master-license-keys["Chiavi di licenza master NetApp ONTAP"^] Per ottenere la licenza sincrona SnapMirror richiesta.





== Ambiente di rete

* Il tempo di round trip (RTT) di latenza tra cluster deve essere inferiore a 10 millisecondi.
* A partire da ONTAP 9.14.1, link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_SCSI_Reservations_and_SCSI_Persistent_Reservations["Prenotazioni persistenti SCSI-3"] Sono supportati con la sincronizzazione attiva di SnapMirror.




== Protocolli supportati

* Sono supportati solo i protocolli SAN (non NFS/SMB).
* Sono supportati solo i protocolli Fibre Channel e iSCSI.
* L'IPSpace predefinito è richiesto dalla sincronizzazione attiva di SnapMirror per le relazioni di cluster peer. IPSpace personalizzato non supportato.




== Sicurezza NTFS

Lo stile di protezione NTFS non è * supportato sui volumi di sincronizzazione attivi di SnapMirror.



== Mediatore ONTAP

* ONTAP Mediator deve essere fornito esternamente e collegato a ONTAP per un failover trasparente dell'applicazione.
* Per essere pienamente funzionale e consentire il failover automatico non pianificato, il mediatore ONTAP esterno deve essere predisposto e configurato con cluster ONTAP.
* ONTAP Mediator deve essere installato in un terzo dominio di errore, separato dai due cluster ONTAP.
* Quando si installa ONTAP Mediator, è necessario sostituire il certificato autofirmato con un certificato valido firmato da una delle principali CA affidabili.
* Per ulteriori informazioni su ONTAP Mediator, vedere link:../mediator/index.html["Prepararsi all'installazione di ONTAP Mediator"] .




== Altri prerequisiti

* Le relazioni di sincronizzazione attive di SnapMirror non sono supportate sui volumi di destinazione in lettura e scrittura. Prima di poter utilizzare un volume di lettura/scrittura, è necessario convertirlo in un volume DP creando una relazione SnapMirror a livello di volume ed eliminando la relazione. Per ulteriori informazioni, vedere link:convert-active-sync-task.html["Converti relazioni di SnapMirror esistenti in sincronizzazione attiva SnapMirror"].
* Le VM storage che utilizzano la sincronizzazione attiva SnapMirror non possono essere unite ad Active Directory quando viene calcolato un client.




== Ulteriori informazioni

* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../mediator/mediator-overview-concept.html["Panoramica del mediatore ONTAP"^]

