---
sidebar: sidebar 
permalink: snapmirror-active-sync/protect-task.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, destination, scsi, nvme 
summary: 'La configurazione della protezione per la business continuity implica la selezione delle LUN nel cluster di origine ONTAP e l"aggiunta a un gruppo di coerenza.' 
---
= Proteggi con ONTAP SnapMirror ActiveSync
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync offre una protezione asimmetrica e, a partire da ONTAP 9.15.1, protezione Active/Active simmetrica.



== Configurare la protezione asimmetrica

La configurazione di una protezione asimmetrica con SnapMirror Active Sync implica la selezione delle LUN nel cluster di origine ONTAP e l'aggiunta di queste a un gruppo di coerenza.

.Prima di iniziare
* È necessaria una licenza sincrona SnapMirror.
* È necessario essere un amministratore di cluster o di macchine virtuali per lo storage.
* Tutti i volumi costituenti di un gruppo di coerenza devono trovarsi in una singola VM di storage (SVM).
+
** Le LUN possono risiedere su volumi diversi.


* Il cluster di origine e di destinazione non può essere lo stesso.
* Non puoi stabilire relazioni di gruppo di coerenza di sincronizzazione attive SnapMirror tra cluster ASA e cluster non ASA.
* L'IPSpace predefinito è richiesto dalla sincronizzazione attiva di SnapMirror per le relazioni di cluster peer. IPSpace personalizzato non supportato.
* Il nome del gruppo di coerenza deve essere univoco.
* I volumi sul cluster secondario (di destinazione) devono essere di tipo DP.
* Le SVM primarie e secondarie devono essere in relazione peered.


.Fasi
È possibile configurare un gruppo di coerenza utilizzando l'interfaccia utente di ONTAP o Gestione sistema.

A partire da ONTAP 9.10.1, ONTAP offre un endpoint e un menu di gruppo di coerenza in System Manager, con utilità di gestione aggiuntive. Se si utilizza ONTAP 9.10.1 o versioni successive, consultare link:../consistency-groups/configure-task.html["Configurare un gruppo di coerenza"] Poi link:../consistency-groups/protect-task.html["configurare la protezione"] per creare una relazione di sincronizzazione attiva SnapMirror .


IMPORTANT: Da ONTAP 9.14.1 a 9.8, la sincronizzazione attiva SnapMirror è denominata SnapMirror Business Continuity (SM-BC).

[role="tabbed-block"]
====
.System Manager
--
. Sul cluster primario, accedere a *protezione > Panoramica > Proteggi per la business continuity > Proteggi LUN*.
. Selezionare i LUN che si desidera proteggere e aggiungerli a un gruppo di protezione.
. Selezionare il cluster di destinazione e SVM.
. Per impostazione predefinita, l'opzione *Inizializza relazione* è selezionata. Fare clic su *Save* (Salva) per iniziare la protezione.
. Accedere a *Dashboard > Performance* per verificare l'attività IOPS per le LUN.
. Nel cluster di destinazione, utilizzare System Manager per verificare che la protezione per la relazione di business continuity sia sincronizzata: *Protezione > relazioni*.


--
.CLI
--
. Creare una relazione di gruppo di coerenza dal cluster di destinazione.
`destination::> snapmirror create -source-path _source-path_ -destination-path _destination-path_ -cg-item-mappings _volume-paths_ -policy _policy-name_`
+
È possibile mappare fino a 12 volumi costitutivi utilizzando `cg-item-mappings` sul `snapmirror create` comando.

+
Nell'esempio seguente vengono creati due gruppi di coerenza: `cg_src_ on the source with `vol1` e. `vol2` e un gruppo di coerenza di destinazione mirrorato, `cg_dst`.

+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOverDuplex`

. Dal cluster di destinazione, inizializzare il gruppo di coerenza.
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. Verificare che l'operazione di inizializzazione sia stata completata correttamente. Lo stato deve essere `InSync`.
+
`snapmirror show`

. Su ciascun cluster, creare un igroup in modo da poter mappare le LUN all'iniziatore sull'host dell'applicazione.
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
+
Ulteriori informazioni su `lun igroup create` nella link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-create.html["Riferimento al comando ONTAP"^].

. Su ciascun cluster, mappare i LUN all'igroup:
+
`lun map -path _path_name_ -igroup _igroup_name_`

. Verificare che la mappatura LUN sia stata completata correttamente con `lun map` comando. Quindi, è possibile scoprire i nuovi LUN sull'host dell'applicazione.


--
====


== Configurare la protezione Active/Active simmetrica

Puoi stabilire una protezione simmetrica utilizzando System Manager o l'interfaccia a riga di comando di ONTAP. In entrambe le interfacce, esistono diversi passaggi per xref:index.html#key-concepts[configurazioni uniformi e non uniformi].

.Prima di iniziare
* Entrambi i cluster devono eseguire ONTAP 9.15.1 o versione successiva.
* Le configurazioni Active/Active simmetriche richiedono `AutomatedFailoverDuplex` policy di protezione. In alternativa, è possibile xref:../data-protection/create-custom-replication-policy-concept.html[Creazione di una policy SnapMirror personalizzata] fornito il `-type` è `automated-failover-duplex`.
* In ONTAP 9.15.1, Active/Active simmetrico è supportato solo su cluster a 2 nodi.
* A partire da ONTAP 9.16.1 GA, la SnapMirror Active Sync supporta configurazioni Active/Active simmetriche su cluster a quattro nodi.
+
** Per utilizzare la sincronizzazione attiva di SnapMirror su un cluster a quattro nodi, è necessario eseguire ONTAP 9.16.1 GA o versione successiva.
** Prima di distribuire una configurazione a quattro nodi, è necessario xref:../peering/create-cluster-relationship-93-later-task.adoc[creare una relazione peer cluster].
** Consulta la xref:limits-reference.adoc[limiti] per i cluster a quattro nodi.
** Se si torna a un cluster a due nodi, è necessario rimuovere le relazioni di sincronizzazione attive di SnapMirror dal cluster prima di eseguire il ripristino.
** Utilizzare la configurazione a quattro nodi per aggiornare storage e controller. Si tratta di un processo senza interruzioni che permette di espandere il cluster e di spostare i volumi nei nuovi nodi. Per ulteriori informazioni, vedere link:upgrade-revert-task.html#refresh-a-cluster["fare un refresh di un cluster"].


* A partire da ONTAP 9.17.1, è possibile configurare la protezione simmetrica attiva/attiva sugli spazi dei nomi NVMe solo quando entrambi i cluster eseguono ONTAP 9.17.1 o versione successiva.




== Configurare la protezione attiva/attiva simmetrica utilizzando una configurazione di sincronizzazione attiva SCSI SnapMirror

.Fasi
È possibile utilizzare System Manager o ONTAP CLI per configurare la protezione simmetrica attiva/attiva utilizzando le mappature host del protocollo SCSI.

[role="tabbed-block"]
====
.System Manager
--
.Procedura per una configurazione uniforme
. Sul sito primario, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["Creazione di un gruppo di coerenza utilizzando nuovi LUN."^]
+
.. Quando si crea il gruppo di coerenza, specificare gli iniziatori host per creare igroup.
.. Selezionare la casella di controllo **attiva SnapMirror**, quindi scegliere `AutomatedFailoverDuplex` policy.
.. Nella finestra di dialogo visualizzata, selezionare la casella di controllo **Replica gruppi iniziatori** per replicare gli igroup. In **Modifica impostazioni di prossimità**, impostare le SVM prossimali per gli host.
.. Selezionare **Salva**.




.Procedura per una configurazione non uniforme
. Sul sito primario, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["Creazione di un gruppo di coerenza utilizzando nuovi LUN."^]
+
.. Quando si crea il gruppo di coerenza, specificare gli iniziatori host per creare igroup.
.. Selezionare la casella di controllo **attiva SnapMirror**, quindi scegliere `AutomatedFailoverDuplex` policy.
.. Selezionare **Salva** per creare LUN, gruppo di coerenza, igroup, relazione SnapMirror e mappatura igroup.


. Sul sito secondario, creare un igroup e mappare i LUN.
+
.. Accedere a **host** > **gruppi iniziatori SAN**.
.. Selezionare **+Aggiungi** per creare un nuovo igroup.
.. Fornire un **Nome**, selezionare **sistema operativo host**, quindi scegliere **membri del gruppo iniziatori**.
.. Selezionare **Salva** per inizializzare la relazione.


. Mappare il nuovo igroup ai LUN di destinazione.
+
.. Passare a **archiviazione** > **LUN**.
.. Selezionare tutte le LUN da mappare all'igroup.
.. Selezionare **Altro** quindi **Mappa a gruppi iniziatori**.




--
.CLI
--
.Procedura per una configurazione uniforme
. Creare una nuova relazione SnapMirror che raggruppa tutti i volumi nell'applicazione. Assicurarsi di designare `AutomatedFailOverDuplex` criterio per stabilire la replica di sincronizzazione bidirezionale.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
Esempio: l'esempio seguente crea due gruppi di coerenza: cg_src sull'origine con vol1 e vol2 e un gruppo di coerenza speculare sulla destinazione, cg_dst.

+
[listing]
----
destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOverDuplex
----
. Inizializzare la relazione SnapMirror:
`snapmirror initialize -destination-path <destination-consistency-group>`
. Confermare che l'operazione è riuscita attendendo il `Mirrored State` mostra come `SnapMirrored` e a. `Relationship Status` come `Insync`.
+
`snapmirror show -destination-path <destination_path>`

. Sull'host, configurare la connettività host con accesso a ciascun cluster in base alle proprie esigenze.
. Stabilire la configurazione di igroup. Impostare i percorsi preferiti per gli iniziatori sul cluster locale. Specificare l'opzione per replicare la configurazione nel cluster peer per l'affinità inversa.
+
`SiteA::> igroup create -vserver <svm_name> -ostype <os_type> -igroup <igroup_name> -replication-peer <peer_svm_name> -initiator <host>`

+

NOTE: A partire da ONTAP 9.16.1, utilizzare `-proximal-vserver local` il parametro di questo comando.

+
`SiteA::> igroup add -vserver <svm_name> -igroup <igroup_name> -ostype <os_type> -initiator <host>`

+

NOTE: A partire da ONTAP 9.16.1, utilizzare `-proximal-vserver peer` il parametro di questo comando.

. Dall'host, rilevare i percorsi e verificare che gli host dispongano di un percorso attivo/ottimizzato verso la LUN di storage dal cluster preferito.
. Implementa l'applicazione e distribuisci i workload VM tra i cluster per ottenere il bilanciamento del carico richiesto.


.Procedura per una configurazione non uniforme
. Creare una nuova relazione SnapMirror che raggruppa tutti i volumi nell'applicazione. Assicurarsi di designare `AutomatedFailOverDuplex` criterio per stabilire la replica di sincronizzazione bidirezionale.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
Esempio: l'esempio seguente crea due gruppi di coerenza: cg_src sull'origine con vol1 e vol2 e un gruppo di coerenza speculare sulla destinazione, cg_dst.

+
[listing]
----
destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOverDuplex
----
. Inizializzare la relazione SnapMirror:
`snapmirror initialize -destination-path <destination-consistency-group>`
. Confermare che l'operazione è riuscita attendendo il `Mirrored State` mostra come `SnapMirrored` e a. `Relationship Status` come `Insync`.
+
`snapmirror show -destination-path <destination_path>`

. Sull'host, configurare la connettività host con accesso a ciascun cluster in base alle proprie esigenze.
. Stabilire le configurazioni igroup sui cluster di origine e di destinazione.
+
`# primary site
SiteA::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_1_name_>`

+
`# secondary site
SiteB::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_2_name>`

. Dall'host, rilevare i percorsi e verificare che gli host dispongano di un percorso attivo/ottimizzato verso la LUN di storage dal cluster preferito.
. Implementa l'applicazione e distribuisci i workload VM tra i cluster per ottenere il bilanciamento del carico richiesto.


--
====


== Configurare la protezione attiva/attiva simmetrica utilizzando una configurazione di sincronizzazione attiva NVMe SnapMirror

.Prima di iniziare
Oltre ai requisiti per la configurazione della protezione simmetrica attiva/attiva, è opportuno conoscere le configurazioni supportate e non supportate quando si utilizza il protocollo NVMe.

* I gruppi di coerenza possono avere uno o più sottosistemi.
* I volumi all'interno del gruppo di coerenza possono avere mappe di namespace da più sottosistemi.
* I sottosistemi non possono avere mappe di namespace che appartengono a più di un gruppo di coerenza.
* I sottosistemi non possono avere alcune mappe di namespace che appartengono a un gruppo di coerenza e alcune mappe di namespace che non appartengono a un gruppo di coerenza.
* I sottosistemi devono avere mappe degli spazi dei nomi che fanno parte dello stesso gruppo di coerenza.


.Fasi
A partire da ONTAP 9.17.1, è possibile utilizzare System Manager o ONTAP CLI per creare un gruppo di coerenza e configurare la protezione simmetrica attiva/attiva utilizzando le mappature host del protocollo NVMe.

[role="tabbed-block"]
====
.System Manager
--
. Nel sito primario, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["creare un gruppo di coerenza utilizzando nuovi volumi o namespace NVMe."^]
. seleziona *+Aggiungi* e scegli *Utilizzo dei nuovi namespace NVMe*.
. Immettere il nome del gruppo di coerenza.
. Seleziona *Altro*.
. Nella sezione *Protezione*, seleziona *Abilita SnapMirror* quindi scegli  `AutomatedFailoverDuplex` politica.
. Nella sezione *Mappatura host*, seleziona *Sottosistema NVMe esistente* o *Nuovo sottosistema NVMe*.
. Selezionare *In prossimità di* per modificare l'SVM prossimale. L'SVM sorgente è selezionato per impostazione predefinita.
. Se necessario, aggiungere un altro sottosistema NVMe.


--
.CLI
--
. Crea una nuova relazione SnapMirror che raggruppi tutti i volumi contenenti tutti gli spazi dei nomi NVMe utilizzati dall'applicazione. Assicurati di designare  `AutomatedFailOverDuplex` politica per stabilire la replicazione sincronica bidirezionale.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
Esempio:

+
[listing]
----
DST::> snapmirror create -source-path vs_src:/cg/cg_src_1 -destination-path vs_dst:/cg/cg_dst_1 -cg-item-mappings vs_src_vol1:@vs_dst_vol1,vs_src_vol2:@vs_dst_vol2 -policy AutomatedFailOverDuplex
----
. Inizializzare la relazione SnapMirror:
`snapmirror initialize -destination-path <destination-consistency-group>`
+
Esempio:

+
[listing]
----
DST::> snapmirror initialize -destination-path vs1:/cg/cg_dst_1
----
. Confermare che l'operazione è riuscita attendendo il `Mirrored State` mostra come `SnapMirrored` e a. `Relationship Status` come `Insync`.
+
`snapmirror show -destination-path <destination_path>`

+
I sottosistemi NVMe associati agli spazi dei nomi NVMe nei volumi primari vengono replicati automaticamente nel cluster secondario.

. Sull'host, configurare la connettività host con accesso a ciascun cluster in base alle proprie esigenze.
. Specificare l'SVM prossimale a ciascuno degli host. Questo consente all'host di accedere allo spazio dei nomi NVMe utilizzando un percorso dal cluster preferito. Potrebbe trattarsi dell'SVM nel cluster primario o dell'SVM nel cluster DR.
+
Il seguente comando indica che SVM VS_A è prossimale all'host H1 e imposta VS_A come SVM prossimale:

+
`SiteA::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H1_NQN> -proximal-vservers <VS_A>`

+
Il seguente comando indica che SVM VS_B è prossimale all'host H2 e imposta VS_B come SVM prossimale:

+
`SiteB::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H2_NQN> -proximal-vservers <VS_B>`

. Dall'host, scopri i percorsi e verifica che gli host abbiano un percorso attivo/ottimizzato verso l'archiviazione dal cluster preferito.
. Implementa l'applicazione e distribuisci i workload VM tra i cluster per ottenere il bilanciamento del carico richiesto.


--
====
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["creazione di snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["inizializzazione di snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["spettacolo snapmirror"^]

