---
sidebar: sidebar 
permalink: snapmirror-active-sync/protect-task.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, destination 
summary: 'La configurazione della protezione per la business continuity implica la selezione delle LUN nel cluster di origine ONTAP e l"aggiunta a un gruppo di coerenza.' 
---
= Proteggi con la sincronizzazione attiva di SnapMirror in ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync offre una protezione asimmetrica e, a partire da ONTAP 9.15.1, protezione Active/Active simmetrica.



== Configurare la protezione asimmetrica

La configurazione di una protezione asimmetrica con SnapMirror Active Sync implica la selezione delle LUN nel cluster di origine ONTAP e l'aggiunta di queste a un gruppo di coerenza.

.Prima di iniziare
* È necessaria una licenza sincrona SnapMirror.
* È necessario essere un amministratore di cluster o di macchine virtuali per lo storage.
* Tutti i volumi costituenti di un gruppo di coerenza devono trovarsi in una singola VM di storage (SVM).
+
** Le LUN possono risiedere su volumi diversi.


* Il cluster di origine e di destinazione non può essere lo stesso.
* Non puoi stabilire relazioni di gruppo di coerenza di sincronizzazione attive SnapMirror tra cluster ASA e cluster non ASA.
* L'IPSpace predefinito è richiesto dalla sincronizzazione attiva di SnapMirror per le relazioni di cluster peer. IPSpace personalizzato non supportato.
* Il nome del gruppo di coerenza deve essere univoco.
* I volumi sul cluster secondario (di destinazione) devono essere di tipo DP.
* Le SVM primarie e secondarie devono essere in relazione peered.


.Fasi
È possibile configurare un gruppo di coerenza utilizzando l'interfaccia utente di ONTAP o Gestione sistema.

A partire da ONTAP 9.10.1, ONTAP offre un endpoint e un menu del gruppo di coerenza in Gestione sistema, offrendo ulteriori utility di gestione. Se si utilizza ONTAP 9.10.1 o versioni successive, vedere link:../consistency-groups/configure-task.html["Configurare un gruppo di coerenza"] quindi link:../consistency-groups/protect-task.html["configurare la protezione"]creare una relazione di sincronizzazione attiva di SnapMirror.


IMPORTANT: Da ONTAP 9,8 fino al 9.14.1, la sincronizzazione attiva di SnapMirror è chiamata SnapMirror Business Continuity (SM-BC).

[role="tabbed-block"]
====
.System Manager
--
. Sul cluster primario, accedere a *protezione > Panoramica > Proteggi per la business continuity > Proteggi LUN*.
. Selezionare i LUN che si desidera proteggere e aggiungerli a un gruppo di protezione.
. Selezionare il cluster di destinazione e SVM.
. Per impostazione predefinita, l'opzione *Inizializza relazione* è selezionata. Fare clic su *Save* (Salva) per iniziare la protezione.
. Accedere a *Dashboard > Performance* per verificare l'attività IOPS per le LUN.
. Nel cluster di destinazione, utilizzare System Manager per verificare che la protezione per la relazione di business continuity sia sincronizzata: *Protezione > relazioni*.


--
.CLI
--
. Creare una relazione di gruppo di coerenza dal cluster di destinazione.
`destination::> snapmirror create -source-path _source-path_ -destination-path _destination-path_ -cg-item-mappings _volume-paths_ -policy _policy-name_`
+
È possibile mappare fino a 12 volumi costitutivi utilizzando `cg-item-mappings` sul `snapmirror create` comando.

+
Nell'esempio seguente vengono creati due gruppi di coerenza: `cg_src_ on the source with `vol1` e. `vol2` e un gruppo di coerenza di destinazione mirrorato, `cg_dst`.

+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`

. Dal cluster di destinazione, inizializzare il gruppo di coerenza.
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. Verificare che l'operazione di inizializzazione sia stata completata correttamente. Lo stato deve essere `InSync`.
+
`snapmirror show`

. Su ciascun cluster, creare un igroup in modo da poter mappare le LUN all'iniziatore sull'host dell'applicazione.
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
+
Ulteriori informazioni su `lun igroup create` nella link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-create.html["Riferimento al comando ONTAP"^].

. Su ciascun cluster, mappare i LUN all'igroup:
+
`lun map -path _path_name_ -igroup _igroup_name_`

. Verificare che la mappatura LUN sia stata completata correttamente con `lun map` comando. Quindi, è possibile scoprire i nuovi LUN sull'host dell'applicazione.


--
====


== Configurare la protezione Active/Active simmetrica

Puoi stabilire una protezione simmetrica utilizzando System Manager o l'interfaccia a riga di comando di ONTAP. In entrambe le interfacce, esistono diversi passaggi per xref:index.html#key-concepts[configurazioni uniformi e non uniformi].

.Prima di iniziare
* Entrambi i cluster devono eseguire ONTAP 9.15.1 o versione successiva.
* Le configurazioni Active/Active simmetriche richiedono `AutomatedFailoverDuplex` policy di protezione. In alternativa, è possibile xref:../data-protection/create-custom-replication-policy-concept.html[Creazione di una policy SnapMirror personalizzata] fornito il `-type` è `automated-failover-duplex`.
* In ONTAP 9.15.1, Active/Active simmetrico è supportato solo su cluster a 2 nodi.
* A partire da ONTAP 9.16.1 GA, la SnapMirror Active Sync supporta configurazioni Active/Active simmetriche su cluster a quattro nodi.
+
** Per utilizzare la sincronizzazione attiva di SnapMirror su un cluster a quattro nodi, è necessario eseguire ONTAP 9.16.1 GA o versione successiva.
** Prima di distribuire una configurazione a quattro nodi, è necessario xref:../peering/create-cluster-relationship-93-later-task.adoc[creare una relazione peer cluster].
** Consulta la xref:limits-reference.adoc[limiti] per i cluster a quattro nodi.
** Se si torna a un cluster a due nodi, è necessario rimuovere le relazioni di sincronizzazione attive di SnapMirror dal cluster prima di eseguire il ripristino.
** Utilizzare la configurazione a quattro nodi per aggiornare storage e controller. Si tratta di un processo senza interruzioni che permette di espandere il cluster e di spostare i volumi nei nuovi nodi. Per ulteriori informazioni, vedere link:upgrade-revert-task.html#refresh-a-cluster["fare un refresh di un cluster"].




.Fasi
[role="tabbed-block"]
====
.System Manager
--
.Procedura per una configurazione uniforme
. Sul sito primario, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["Creazione di un gruppo di coerenza utilizzando nuovi LUN."^]
+
.. Quando si crea il gruppo di coerenza, specificare gli iniziatori host per creare igroup.
.. Selezionare la casella di controllo **attiva SnapMirror**, quindi scegliere `AutomatedFailoverDuplex` policy.
.. Nella finestra di dialogo visualizzata, selezionare la casella di controllo **Replica gruppi iniziatori** per replicare gli igroup. In **Modifica impostazioni di prossimità**, impostare le SVM prossimali per gli host.
.. Selezionare **Salva**.




.Procedura per una configurazione non uniforme
. Sul sito primario, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["Creazione di un gruppo di coerenza utilizzando nuovi LUN."^]
+
.. Quando si crea il gruppo di coerenza, specificare gli iniziatori host per creare igroup.
.. Selezionare la casella di controllo **attiva SnapMirror**, quindi scegliere `AutomatedFailoverDuplex` policy.
.. Selezionare **Salva** per creare LUN, gruppo di coerenza, igroup, relazione SnapMirror e mappatura igroup.


. Sul sito secondario, creare un igroup e mappare i LUN.
+
.. Accedere a **host** > **gruppi iniziatori SAN**.
.. Selezionare **+Aggiungi** per creare un nuovo igroup.
.. Fornire un **Nome**, selezionare **sistema operativo host**, quindi scegliere **membri del gruppo iniziatori**.
.. Selezionare **Salva** per inizializzare la relazione.


. Mappare il nuovo igroup ai LUN di destinazione.
+
.. Passare a **archiviazione** > **LUN**.
.. Selezionare tutte le LUN da mappare all'igroup.
.. Selezionare **Altro** quindi **Mappa a gruppi iniziatori**.




--
.CLI
--
.Procedura per una configurazione uniforme
. Creare una nuova relazione SnapMirror che raggruppa tutti i volumi nell'applicazione. Assicurarsi di designare `AutomatedFailOverDuplex` criterio per stabilire la replica di sincronizzazione bidirezionale.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

. Inizializzare la relazione SnapMirror:
`snapmirror initialize -destination-path <destination-consistency-group>`
. Confermare che l'operazione è riuscita attendendo il `Mirrored State` mostra come `SnapMirrored` e a. `Relationship Status` come `Insync`.
+
`snapmirror show -destination-path <destination_path>`

. Sull'host, configurare la connettività host con accesso a ciascun cluster in base alle proprie esigenze.
. Stabilire la configurazione di igroup. Impostare i percorsi preferiti per gli iniziatori sul cluster locale. Specificare l'opzione per replicare la configurazione nel cluster peer per l'affinità inversa.
+
`SiteA::> igroup create -vserver <svm_name> -ostype <os_type> -igroup <igroup_name> -replication-peer <peer_svm_name> -initiator <host>`

+

NOTE: A partire da ONTAP 9.16.1, utilizzare `-proximal-vserver local` il parametro di questo comando.

+
`SiteA::> igroup add -vserver <svm_name> -igroup <igroup_name> -ostype <os_type> -initiator <host>`

+

NOTE: A partire da ONTAP 9.16.1, utilizzare `-proximal-vserver peer` il parametro di questo comando.

. Dall'host, rilevare i percorsi e verificare che gli host dispongano di un percorso attivo/ottimizzato verso la LUN di storage dal cluster preferito.
. Implementa l'applicazione e distribuisci i workload VM tra i cluster per ottenere il bilanciamento del carico richiesto.


.Procedura per una configurazione non uniforme
. Creare una nuova relazione SnapMirror che raggruppa tutti i volumi nell'applicazione. Assicurarsi di specificare il criterio `AutomatedFailOverDuplex'' per stabilire la replica di sincronizzazione bidirezionale.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

. Inizializzare la relazione SnapMirror:
`snapmirror initialize -destination-path <destination-consistency-group>`
. Confermare che l'operazione è riuscita attendendo il `Mirrored State` mostra come `SnapMirrored` e a. `Relationship Status` come `Insync`.
+
`snapmirror show -destination-path <destination_path>`

. Sull'host, configurare la connettività host con accesso a ciascun cluster in base alle proprie esigenze.
. Stabilire le configurazioni igroup sui cluster di origine e di destinazione.
+
`# primary site
SiteA::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_1_name_>`

+
`# secondary site
SiteB::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_2_name>`

. Dall'host, rilevare i percorsi e verificare che gli host dispongano di un percorso attivo/ottimizzato verso la LUN di storage dal cluster preferito.
. Implementa l'applicazione e distribuisci i workload VM tra i cluster per ottenere il bilanciamento del carico richiesto.


--
====