---
sidebar: sidebar 
permalink: snapmirror-active-sync/troubleshoot-site-a-mediator-task.html 
keywords: SM-BC, SMBC, troubleshooting, connectivity, consensus, snapmirror active sync 
summary: Collegamento per la risoluzione dei problemi tra il sito A e il mediatore ONTAP inattivo e il sito B inattivo. 
---
= Collegamento tra il sito A e il mediatore ONTAP inattivo e il sito B inattivo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Quando si utilizza la sincronizzazione attiva di SnapMirror, si potrebbe perdere la connettività tra ONTAP Mediator o i cluster sottoposti a peering. Puoi diagnosticare il problema controllando lo stato di connessione, disponibilità e consenso delle diverse parti della relazione di sincronizzazione attiva di SnapMirror, quindi riprendendo forzatamente la connessione.

[cols="3"]
|===
| Cosa controllare | Comando CLI | Indicatore 


| Mediatore dal sito A. | `snapmirror mediator show` | Lo stato della connessione viene visualizzato come `unreachable` 


| Connettività del sito B. | `cluster peer show` | La disponibilità viene visualizzata come `unavailable` 


| Stato di consenso del volume di sincronizzazione attivo di SnapMirror | `volume show _volume_name_ -fields smbc-consensus` | Il `sm-bc consensus` viene visualizzato il campo `Awaiting-consensus` 
|===
Per ulteriori informazioni sulla diagnosi e la risoluzione di questo problema, consultare l'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Link_between_Site_A_and_Mediator_down_and_Site_B_down_when_using_SM-BC["Collegamento tra il Sito A e il Mediator inattivo e il Sito B inattivo quando si utilizza la sincronizzazione attiva SnapMirror"^].

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-peer-show.html["spettacolo di pari del cluster"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-show.html["spettacolo di mediazione di SnapMirror"^]

