---
sidebar: sidebar 
permalink: snapmirror-active-sync/volume-move-stuck-task.html 
keywords: SM-BC, SMBC, volume move, troubleshooting, primary down, snapmirror active sync 
summary: Puoi rimuovere la protezione sincrona di SnapMirror con RTO nullo ed eliminare la configurazione della relazione di sincronizzazione attiva di SnapMirror. 
---
= Operazione di spostamento del volume bloccata quando ONTAP primario è inattivo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilizzare le seguenti informazioni se un'operazione di spostamento del volume rimane bloccata indefinitamente nello stato di cutover differito quando il sito primario è inattivo in una relazione di sincronizzazione attiva SnapMirror .

.Problema:
Un'operazione di spostamento del volume si blocca a tempo indeterminato in stato di cutover rimandato quando il sito primario viene inattivo in una relazione di sincronizzazione attiva SnapMirror.
Quando il sito primario è inattivo, il sito secondario esegue un failover automatico non pianificato (AUFO). Quando è in corso un'operazione di spostamento del volume quando viene attivato l'AUFO, lo spostamento del volume si blocca.

.Soluzione:
Interrompere l'istanza di spostamento del volume bloccata e riavviare l'operazione di spostamento del volume.
