---
sidebar: sidebar 
permalink: snapmirror-active-sync/volume-move-snapshot-task.html 
keywords: SM-BC, SMBC, volume move, troubleshooting, consistency group, Snapshot copy, snapmirror active sync 
summary: 'Dopo un"operazione di spostamento di un volume, lo snapshot di riferimento per le operazioni di spostamento del volume viene indicato come il più recente per la relazione SnapMirror.' 
---
= Lo snapshot di riferimento dello spostamento del volume viene visualizzato come il più recente per la relazione ONTAP SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilizzare le seguenti informazioni se lo snapshot di riferimento per lo spostamento del volume viene visualizzato come il più recente per la relazione SnapMirror dopo un'operazione di spostamento del volume.

.Problema:
Dopo aver eseguito un'operazione di spostamento del volume su un volume del gruppo di coerenza, lo snapshot di riferimento dello spostamento del volume potrebbe non essere visualizzato correttamente come il più recente per la relazione SnapMirror.

È possibile visualizzare l'istantanea più recente con il seguente comando:

`snapmirror show -fields newest-snapshot status -expand`

.Soluzione:
Eseguire manualmente un `snapmirror resync` oppure attendere la successiva risincronizzazione automatica al termine dell'operazione di spostamento del volume.

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["risincronizzazione snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["spettacolo snapmirror"^]

