---
permalink: smb-hyper-v-sql/configure-shares-continuous-availability-task.html 
sidebar: sidebar 
keywords: configure, shares, continuous, availability, hyper, v, sql, server, virutal, machine, database, file 
summary: È possibile modificare le condivisioni esistenti per diventare condivisioni continuamente disponibili utilizzate dai server applicativi Hyper-V e SQL Server per accedere senza interruzioni ai file di configurazione e alla macchina virtuale Hyper-V e ai file di database SQL Server. 
---
= Configurare le condivisioni esistenti per la disponibilità continua
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le condivisioni esistenti per diventare condivisioni continuamente disponibili utilizzate dai server applicativi Hyper-V e SQL Server per accedere senza interruzioni ai file di configurazione e alla macchina virtuale Hyper-V e ai file di database SQL Server.

.A proposito di questa attività
Non è possibile utilizzare una condivisione esistente come condivisione continuamente disponibile per operazioni senza interruzioni con server applicazioni su SMB se la condivisione ha le seguenti caratteristiche:

* Se il `homedirectory` la proprietà share viene impostata su tale condivisione
* Se la condivisione contiene link simbolici o widelink abilitati
* Se la condivisione contiene volumi congiundati al di sotto della radice della condivisione


Verificare che i due seguenti parametri di condivisione siano impostati correttamente:

* Il `-offline-files` il parametro è impostato su uno dei due `manual` (impostazione predefinita) o. `none`.
* I link simbolici devono essere disattivati.


È necessario configurare le seguenti proprietà di condivisione:

* `continuously-available`
* `oplocks`


Le seguenti proprietà di condivisione non devono essere impostate. Se sono presenti nell'elenco delle proprietà di condivisione correnti, devono essere rimosse dalla condivisione continuamente disponibile:

* `attributecache`
* `branchcache`


.Fasi
. Visualizza le impostazioni correnti dei parametri di condivisione e l'elenco corrente delle proprietà di condivisione configurate:
+
`*vserver cifs share show -vserver _vserver_name_ -share-name _share_name_*`

. Se necessario, modificare i parametri di condivisione per disattivare i collegamenti simbolici e impostare i file offline su manuale utilizzando `vserver cifs share properties modify` comando.
+
È possibile disattivare i collegamenti simbolici impostando il valore di `-symlink` parametro a. `""`.

+
** È possibile disattivare i collegamenti simbolici impostando il valore di `-symlink` parametro a. `""`.
** È possibile impostare `-offline-files` impostare correttamente il parametro specificando `manual`.


. Aggiungere il `continuously-available` condividere la proprietà e, se necessario, il `oplocks` proprietà di condivisione:
+
`*vserver cifs share properties add -vserver _vserver_name_ -share-name _share_name_ -share-properties continuously-available[,oplock]*`

+
Se il `oplocks` la proprietà di condivisione non è già impostata, è necessario aggiungerla con `continuously-available` condividere la proprietà.

. Rimuovere eventuali proprietà di condivisione non supportate nelle condivisioni a disponibilità continua:
+
`*vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties properties[,...]*`

+
È possibile rimuovere una o più proprietà di condivisione specificando le proprietà di condivisione con un elenco delimitato da virgole.

. Verificare che il `-symlink` e. `-offline-files` i parametri sono impostati correttamente:
+
`*vserver cifs share show -vserver _vserver_name_ -share-name _share_name_ -fields symlink-properties,offline-files*`

. Verificare che l'elenco delle proprietà di condivisione configurate sia corretto:
+
`*vserver cifs shares properties show -vserver _vserver_name_ -share-name share_name*`



.Esempi
L'esempio seguente mostra come configurare una condivisione esistente denominata "hare1 `s`" su una macchina virtuale di storage (SVM) vs1 per NDOS con un server applicativo su SMB:

* I collegamenti simbolici vengono disattivati nella condivisione impostando `-symlink` parametro su "".
* Il `-offline-file` il parametro viene modificato e impostato su `manual`.
* Il `continuously-available` la proprietà share viene aggiunta alla condivisione.
* Il `oplocks` la proprietà di condivisione è già presente nell'elenco delle proprietà di condivisione, pertanto non è necessario aggiungerla.
* Il `attributecache` la proprietà share viene rimossa dalla condivisione.
* Il `browsable` La proprietà Share è opzionale per una condivisione a disponibilità continua utilizzata per NDOS con server applicazioni su SMB e viene conservata come una delle proprietà di condivisione.


[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name share1

                      Vserver: vs1
                        Share: share1
     CIFS Server NetBIOS Name: vs1
                         Path: /data
             Share Properties: oplocks
                               browsable
                               attributecache
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: data
                Offline Files: documents
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share modify -vserver vs1 -share-name share1 -offline-file manual -symlink ""

cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties continuously-available

cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share1 -share-properties attributecache

cluster1::> vserver cifs share show -vserver vs1 -share-name share1 -fields symlink-properties,offline-files
vserver  share-name symlink-properties offline-files
-------- ---------- ------------------ -------------
vs1      share1    -                  manual

cluster1::> vserver cifs share properties show -vserver vs1 -share-name share1

         Vserver: vs1
           Share: share1
Share Properties: oplocks
                  browsable
                  continuously-available
----