---
permalink: smb-hyper-v-sql/display-nondisruptive-status-health-task.html 
sidebar: sidebar 
keywords: display, nondisruptive, operation, status, system, health, monitor, cifs, ndo, alert 
summary: È possibile utilizzare i comandi di stato del sistema per visualizzare informazioni sullo stato generale del sistema del cluster e sullo stato del sottosistema CIFS-NDO, per rispondere agli avvisi, per configurare gli avvisi futuri e per visualizzare informazioni sulla configurazione del monitoraggio dello stato di salute. 
---
= Visualizzazione dello stato delle operazioni senza interruzioni mediante il monitoraggio dello stato di salute del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `system health` Comandi per visualizzare informazioni sullo stato generale del sistema del cluster e sullo stato del sottosistema CIFS-NDO, per rispondere agli avvisi, per configurare gli avvisi futuri e per visualizzare informazioni sulla configurazione del monitoraggio dello stato di salute.

.Fasi
. Monitorare lo stato di salute eseguendo l'azione appropriata:
+
|===
| Se si desidera visualizzare... | Immettere il comando... 


 a| 
Lo stato di salute del sistema, che riflette lo stato generale dei singoli monitor di salute
 a| 
`*system health status show*`



 a| 
Informazioni sullo stato di salute del sottosistema CIFS-NDO
 a| 
`*system health subsystem show -subsystem CIFS-NDO -instance*`

|===
. Visualizzare le informazioni sulla configurazione del monitoraggio degli avvisi CIFS-NDO eseguendo le azioni appropriate:
+
|===
| Se si desidera visualizzare informazioni su... | Immettere il comando... 


 a| 
La configurazione e lo stato del monitor di stato per il sottosistema CIFS-NDO, ad esempio i nodi monitorati, lo stato di inizializzazione e lo stato
 a| 
`*system health config show -subsystem CIFS-NDO*`



 a| 
CIFS-NDO avvisa che un monitor di stato può potenzialmente generare
 a| 
`*system health alert definition show -subsystem CIFS-NDO*`



 a| 
Criteri di monitoraggio dello stato CIFS-NDO, che determinano quando vengono generati gli avvisi
 a| 
`*system health policy definition show -monitor node-connect*`

|===
+
[NOTE]
====
Utilizzare `-instance` per visualizzare informazioni dettagliate.

====


.Esempi
Il seguente output mostra informazioni sullo stato di salute generale del cluster e del sottosistema CIFS-NDO:

[listing]
----
cluster1::> system health status show
Status
---------------
ok

cluster1::> system health subsystem show -instance -subsystem CIFS-NDO

                   Subsystem: CIFS-NDO
                      Health: ok
        Initialization State: initialized
Number of Outstanding Alerts: 0
 Number of Suppressed Alerts: 0
                        Node: node2
  Subsystem Refresh Interval: 5m
----
Il seguente output mostra informazioni dettagliate sulla configurazione e lo stato del monitor di stato del sottosistema CIFS-NDO:

[listing]
----
cluster1::> system health config show -subsystem CIFS-NDO -instance

                           Node: node1
                        Monitor: node-connect
                      Subsystem: SAS-connect, HA-health, CIFS-NDO
                         Health: ok
                Monitor Version: 2.0
            Policy File Version: 1.0
                        Context: node_context
                     Aggregator: system-connect
                       Resource: SasAdapter, SasDisk, SasShelf, HaNodePair,
                                 HaICMailbox, CifsNdoNode, CifsNdoNodeVserver
Subsystem Initialization Status: initialized
    Subordinate Policy Versions: 1.0 SAS, 1.0 SAS multiple adapters, 1.0, 1.0

                           Node: node2
                        Monitor: node-connect
                      Subsystem: SAS-connect, HA-health, CIFS-NDO
                         Health: ok
                Monitor Version: 2.0
            Policy File Version: 1.0
                        Context: node_context
                     Aggregator: system-connect
                       Resource: SasAdapter, SasDisk, SasShelf, HaNodePair,
                                 HaICMailbox, CifsNdoNode, CifsNdoNodeVserver
Subsystem Initialization Status: initialized
    Subordinate Policy Versions: 1.0 SAS, 1.0 SAS multiple adapters, 1.0, 1.0
----