---
permalink: smb-hyper-v-sql/index.html 
sidebar: sidebar 
keywords: smb, cifs, configuration, microsoft, hyper-v, sql, serve 
summary: 'Le funzionalità di ONTAP consentono di eseguire operazioni senza interruzioni per due applicazioni Microsoft tramite il protocollo SMB: Microsoft Hyper-V e Microsoft SQL Server.' 
---
= Panoramica della configurazione SMB per Microsoft Hyper-V e SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le funzionalità di ONTAP consentono di eseguire operazioni senza interruzioni per due applicazioni Microsoft tramite il protocollo SMB: Microsoft Hyper-V e Microsoft SQL Server.

Utilizzare queste procedure se si desidera implementare operazioni SMB senza interruzioni nei seguenti casi:

* È stato configurato l'accesso al file del protocollo SMB di base.
* Si desidera abilitare le condivisioni di file SMB 3.0 o versioni successive che risiedono in SVM per memorizzare i seguenti oggetti:
+
** File di macchine virtuali Hyper-V.
** Database di sistema di SQL Server




.Informazioni correlate
Per ulteriori informazioni sulla tecnologia ONTAP e sull'interazione con i servizi esterni, consultare i seguenti report tecnici (TR): ** ** https://www.netapp.com/pdf.html?item=/media/16334-tr-4172pdf.pdf["Report tecnico NetApp 4172: Best practice Microsoft Hyper-V su SMB 3.0 con ONTAP"^] https://www.netapp.com/pdf.html?item=/media/19705-tr-4369.pdf["Report tecnico NetApp 4369: Best practice per Microsoft SQL Server e SnapManager 7.2 per SQL Server con Clustered Data ONTAP"^]
