---
permalink: smb-hyper-v-sql/odx-copy-offload-requirements-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, requirements, sql, server, hyper, v, smb, virtual 
summary: 'L"offload delle copie ODX deve essere attivato se si desidera migrare i file delle macchine virtuali o esportare e importare i file di database direttamente dall"origine alla posizione di storage di destinazione senza inviare dati attraverso i server applicazioni. È necessario comprendere alcuni requisiti sull"utilizzo dell"offload delle copie ODX con SQL Server e Hyper-V su soluzioni SMB.' 
---
= Requisiti di offload delle copie ODX per SQL Server e Hyper-V su SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'offload delle copie ODX deve essere attivato se si desidera migrare i file delle macchine virtuali o esportare e importare i file di database direttamente dall'origine alla posizione di storage di destinazione senza inviare dati attraverso i server applicazioni. È necessario comprendere alcuni requisiti sull'utilizzo dell'offload delle copie ODX con SQL Server e Hyper-V su soluzioni SMB.

L'utilizzo dell'offload delle copie di ODX offre un significativo vantaggio in termini di performance. Questa opzione del server CIFS è attivata per impostazione predefinita.

* SMB 3.0 deve essere abilitato per utilizzare l'offload delle copie ODX.
* I volumi di origine devono essere di almeno 1.25 GB.
* La deduplica deve essere attivata sui volumi utilizzati con l'offload delle copie.
* Se si utilizzano volumi compressi, il tipo di compressione deve essere adattivo e sono supportate solo le dimensioni del gruppo di compressione 8K.
+
Il tipo di compressione secondario non è supportato

* Per utilizzare l'offload delle copie di ODX per migrare i guest Hyper-V all'interno e tra i dischi, i server Hyper-V devono essere configurati per l'utilizzo di dischi SCSI.
+
L'impostazione predefinita prevede la configurazione dei dischi IDE, ma l'offload delle copie ODX non funziona quando i guest vengono migrati se i dischi vengono creati utilizzando dischi IDE.


