---
permalink: smb-hyper-v-sql/recommendations-config-concept.html 
sidebar: sidebar 
keywords: recommendations, sql, server, hyper, v, smb, configuration 
summary: Per essere sicuri che le configurazioni di SQL Server e Hyper-V su SMB siano solide e operative, è necessario conoscere le Best practice consigliate per la configurazione delle soluzioni. 
---
= Raccomandazioni per le configurazioni SQL Server e Hyper-V su SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per essere sicuri che le configurazioni di SQL Server e Hyper-V su SMB siano solide e operative, è necessario conoscere le Best practice consigliate per la configurazione delle soluzioni.



== Raccomandazioni generali

* Separare i file del server applicazioni dai dati generali dell'utente.
+
Se possibile, dedicare un'intera macchina virtuale di storage (SVM) e il relativo storage ai dati dell'application server.

* Per ottenere performance ottimali, non abilitare la firma SMB sulle SVM utilizzate per memorizzare i dati dell'application server.
* Per ottenere le migliori performance e una maggiore tolleranza agli errori, abilitare SMB multicanale per fornire più connessioni tra ONTAP e client in una singola sessione SMB.
* Non creare condivisioni continuamente disponibili su condivisioni diverse da quelle utilizzate nella configurazione Hyper-V o SQL Server su SMB.
* Disattiva la notifica delle modifiche sulle condivisioni utilizzate per la disponibilità continua.
* Non eseguire uno spostamento del volume contemporaneamente al trasferimento dell'aggregato (ARL) perché ARL ha fasi che interrompono alcune operazioni.
* Per le soluzioni Hyper-V su SMB, utilizzare dischi iSCSI in-guest durante la creazione di macchine virtuali in cluster. Condiviso `.VHDX` I file non sono supportati per Hyper-V su SMB nelle condivisioni SMB ONTAP.

