---
permalink: smb-hyper-v-sql/remote-vss-concepts-concept.html 
sidebar: sidebar 
keywords: remove, vss, concepts, volume, shadow, copy, service, hyper, v, smb, configuration 
summary: 'È necessario conoscere alcuni concetti necessari per comprendere in che modo i servizi di backup con configurazioni Hyper-V su SMB utilizzano il servizio Remote VSS (Volume Shadow Copy Service).' 
---
= Concetti VSS remoti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere alcuni concetti necessari per comprendere in che modo i servizi di backup con configurazioni Hyper-V su SMB utilizzano il servizio Remote VSS (Volume Shadow Copy Service).

* *VSS (Volume Shadow Copy Service)*
+
Tecnologia Microsoft utilizzata per eseguire copie di backup o snapshot di dati su un volume specifico in un determinato momento. Il sistema VSS coordina tra server di dati, applicazioni di backup e software di gestione dello storage per supportare la creazione e la gestione di backup coerenti.

* *VSS remoto (Remote Volume Shadow Copy Service)*
+
Tecnologia Microsoft utilizzata per eseguire copie di backup basate su condivisione dei dati in uno stato coerente con i dati in un momento specifico in cui si accede ai dati tramite le condivisioni SMB 3.0. Noto anche come _Volume Shadow Copy Service_.

* *Copia shadow*
+
Un insieme duplicato di dati contenuti nella condivisione in un istante di tempo ben definito. Le copie shadow vengono utilizzate per creare backup point-in-time coerenti dei dati, consentendo al sistema o alle applicazioni di continuare ad aggiornare i dati sui volumi originali.

* *Set di copie shadow*
+
Una raccolta di una o più copie shadow, con ciascuna copia shadow corrispondente a una condivisione. Le copie shadow all'interno di un set di copie shadow rappresentano tutte le condivisioni di cui è necessario eseguire il backup nella stessa operazione. Il client VSS nell'applicazione abilitata per VSS identifica le copie shadow da includere nel set.

* *Recupero automatico del set di copie shadow*
+
Parte del processo di backup per le applicazioni di backup remote abilitate per VSS in cui la directory di replica contenente le copie shadow viene resa coerente point-in-time. All'inizio del backup, il client VSS sull'applicazione attiva l'applicazione per prendere punti di controllo software sui dati pianificati per il backup (i file della macchina virtuale nel caso di Hyper-V). Il client VSS consente quindi alle applicazioni di continuare. Una volta creato il set di copie shadow, Remote VSS rende il set di copie shadow scrivibile ed espone la copia scrivibile alle applicazioni. L'applicazione prepara il set di copie shadow per il backup eseguendo un ripristino automatico utilizzando il checkpoint del software preso in precedenza. Il ripristino automatico porta le copie shadow in uno stato coerente srotolando le modifiche apportate ai file e alle directory dalla creazione del checkpoint. Il ripristino automatico è un passaggio opzionale per i backup abilitati per VSS.

* *ID copia shadow*
+
GUID che identifica in modo univoco una copia shadow.

* *ID set copia shadow*
+
GUID che identifica in modo univoco una raccolta di ID di copia shadow sullo stesso server.

* *SnapManager per Hyper-V*
+
Il software che automatizza e semplifica le operazioni di backup e ripristino per Microsoft Windows Server 2012 Hyper-V. SnapManager per Hyper-V utilizza VSS remoto con recovery automatico per eseguire il backup dei file Hyper-V sulle condivisioni SMB.



.Informazioni correlate
xref:nondisruptive-operations-glossary-concept.adoc[Concetti chiave sulle operazioni senza interruzioni per Hyper-V e SQL Server su SMB]

xref:share-based-backups-remote-vss-concept.adoc[Backup basati su condivisione con Remote VSS]
