---
permalink: smb-hyper-v-sql/witness-protocol-transparent-failover-concept.html 
sidebar: sidebar 
keywords: witness, protocol, transparent, failover, lif, ca, share, client, smb, recovery 
summary: 'Il protocollo Witness offre funzionalità di failover client avanzate per le condivisioni SMB 3.0 a disponibilità continua (condivisioni CA). La funzione Witness facilita un failover più rapido perché evita il periodo di failover di LIF. Notifica agli application server quando un nodo non è disponibile senza dover attendere il timeout della connessione SMB 3.0.' 
---
= Cosa fa il protocollo Witness per migliorare il failover trasparente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il protocollo Witness offre funzionalità di failover client avanzate per le condivisioni SMB 3.0 a disponibilità continua (condivisioni CA). La funzione Witness facilita un failover più rapido perché evita il periodo di failover di LIF. Notifica agli application server quando un nodo non è disponibile senza dover attendere il timeout della connessione SMB 3.0.

Il failover è perfetto, con le applicazioni in esecuzione sul client che non sono a conoscenza del failover. Se il server di controllo del mirroring non è disponibile, le operazioni di failover continuano a essere eseguite correttamente, ma il failover senza server di controllo del mirroring è meno efficiente.

Il failover avanzato di Witness è possibile quando vengono soddisfatti i seguenti requisiti:

* Può essere utilizzato solo con server CIFS con funzionalità SMB 3.0 e SMB 3.0 abilitati.
* Le condivisioni devono utilizzare SMB 3.0 con la proprietà di condivisione a disponibilità continua impostata.
* Il partner SFO del nodo a cui sono connessi i server applicazioni deve avere almeno una LIF di dati operativi assegnata alla macchina virtuale di storage (SVM) che ospita i dati per i server applicazioni.
+
[NOTE]
====
Il protocollo Witness opera tra coppie SFO. Poiché i LIF possono migrare a qualsiasi nodo all'interno del cluster, qualsiasi nodo potrebbe dover essere il testimone per il partner SFO. Il protocollo Witness non è in grado di fornire un failover rapido delle connessioni SMB su un dato nodo se la SVM che ospita i dati per gli application server non dispone di una LIF di dati attiva sul nodo partner. Pertanto, ogni nodo del cluster deve disporre di almeno una LIF di dati per ogni SVM che ospita una di queste configurazioni.

====
* I server applicazioni devono connettersi al server CIFS utilizzando il nome del server CIFS memorizzato in DNS invece di utilizzare singoli indirizzi IP LIF.

