---
permalink: file-system-analytics/usage-size-task.html 
sidebar: sidebar 
keywords: large directories, system manager, file system analytics, usage, top directories 
summary: Monitoraggio delle attività per visualizzare file, directory, client e utenti attivi in un volume specificato per la risoluzione dei problemi di prestazioni in tempo reale. 
---
= Abilita l'analisi dell'utilizzo di ONTAP con FSA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.12.1, è possibile abilitare l'analisi dell'utilizzo per vedere quali directory all'interno di un volume utilizzano più spazio. È possibile visualizzare il numero totale di directory in un volume o il numero totale di file in un volume. Il reporting è limitato alle 25 directory che utilizzano la maggior parte dello spazio.

Gli analytics delle directory di grandi dimensioni vengono aggiornati ogni 15 minuti. È possibile monitorare l'aggiornamento più recente selezionando l'indicatore data e ora ultimo aggiornamento nella parte superiore della pagina. È inoltre possibile fare clic sul pulsante Download per scaricare i dati in una cartella di lavoro Excel. L'operazione di download viene eseguita in background e presenta le informazioni più recenti per il volume selezionato. Se la scansione si ripresenta senza alcun risultato, assicurarsi che il volume sia online. Eventi come SnapRestore causeranno la ricostruzione dell'elenco di directory di grandi dimensioni da parte di analisi del file system.

.Fasi
. Selezionare *Storage > Volumes* (Storage > volumi). Selezionare il volume desiderato.
. Dal menu dei singoli volumi, selezionare *file System*. Quindi selezionare la scheda *Usage* (utilizzo).
. Attivare l'opzione *Analytics* per abilitare l'analisi dell'utilizzo.
. System Manager visualizza un grafico a barre che identifica le directory con le dimensioni maggiori in ordine decrescente.
+

NOTE: ONTAP potrebbe visualizzare dati parziali o non visualizzare alcun dato durante la raccolta dell'elenco delle directory principali. L'avanzamento della scansione può essere nella scheda *Usage* (utilizzo) visualizzata durante la scansione.



Per ottenere maggiori informazioni su una directory specifica, è possibile xref:../task_nas_file_system_analytics_view.html[visualizza l'attività del file system ONTAP].
