---
permalink: antivirus/commands-manage-on-access-policies-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-access, policies 
summary: È possibile modificare, disattivare o eliminare un criterio di accesso. È possibile visualizzare un riepilogo e i dettagli della policy. 
---
= Comandi per la gestione delle policy di accesso in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare, disattivare o eliminare un criterio di accesso. È possibile visualizzare un riepilogo e i dettagli della policy.

|===


| Se si desidera... | Immettere il seguente comando... 


 a| 
Creare una policy di accesso
 a| 
`vserver vscan on-access-policy create`



 a| 
Modificare un criterio di accesso
 a| 
`vserver vscan on-access-policy modify`



 a| 
Attivare un criterio di accesso
 a| 
`vserver vscan on-access-policy enable`



 a| 
Disattiva un criterio di accesso
 a| 
`vserver vscan on-access-policy disable`



 a| 
Eliminare un criterio di accesso
 a| 
`vserver vscan on-access-policy delete`



 a| 
Visualizza riepilogo e dettagli per una policy di accesso
 a| 
`vserver vscan on-access-policy show`



 a| 
Aggiungere all'elenco di percorsi da escludere
 a| 
`vserver vscan on-access-policy paths-to-exclude add`



 a| 
Eliminare dall'elenco dei percorsi da escludere
 a| 
`vserver vscan on-access-policy paths-to-exclude remove`



 a| 
Visualizzare l'elenco dei percorsi da escludere
 a| 
`vserver vscan on-access-policy paths-to-exclude show`



 a| 
Aggiungere all'elenco delle estensioni di file da escludere
 a| 
`vserver vscan on-access-policy file-ext-to-exclude add`



 a| 
Eliminare dall'elenco delle estensioni di file da escludere
 a| 
`vserver vscan on-access-policy file-ext-to-exclude remove`



 a| 
Visualizzare l'elenco delle estensioni di file da escludere
 a| 
`vserver vscan on-access-policy file-ext-to-exclude show`



 a| 
Aggiungere all'elenco delle estensioni di file da includere
 a| 
`vserver vscan on-access-policy file-ext-to-include add`



 a| 
Eliminare dall'elenco delle estensioni di file da includere
 a| 
`vserver vscan on-access-policy file-ext-to-include remove`



 a| 
Visualizzare l'elenco delle estensioni di file da includere
 a| 
`vserver vscan on-access-policy file-ext-to-include show`

|===
Per ulteriori informazioni sui comandi descritti in questa procedura, consultare la link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].
