---
permalink: antivirus/commands-manage-on-demand-tasks-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-demand, tasks 
summary: 'È possibile modificare, eliminare o annullare la pianificazione di un"attività on-demand. È possibile visualizzare un riepilogo e i dettagli dell"attività e gestire i report per l"attività.' 
---
= Comandi ONTAP Vscan per la gestione delle attività su richiesta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare, eliminare o annullare la pianificazione di un'attività on-demand. È possibile visualizzare un riepilogo e i dettagli dell'attività e gestire i report per l'attività.

|===


| Se si desidera... | Immettere il seguente comando... 


 a| 
Crea un'attività on-demand
 a| 
`vserver vscan on-demand-task create`



 a| 
Modificare un'attività on-demand
 a| 
`vserver vscan on-demand-task modify`



 a| 
Eliminare un'attività on-demand
 a| 
`vserver vscan on-demand-task delete`



 a| 
Eseguire un'attività on-demand
 a| 
`vserver vscan on-demand-task run`



 a| 
Pianificare un'attività on-demand
 a| 
`vserver vscan on-demand-task schedule`



 a| 
Annulla pianificazione di un'attività on-demand
 a| 
`vserver vscan on-demand-task unschedule`



 a| 
Visualizza riepilogo e dettagli per un'attività on-demand
 a| 
`vserver vscan on-demand-task show`



 a| 
Visualizza report on-demand
 a| 
`vserver vscan on-demand-task report show`



 a| 
Elimina i report on-demand
 a| 
`vserver vscan on-demand-task report delete`

|===
Per ulteriori informazioni sui comandi descritti in questa procedura, consultare la link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].
