---
permalink: antivirus/commands-view-vscan-server-reference.html 
sidebar: sidebar 
keywords: commands, view, vscan, server, connection, status 
summary: È possibile utilizzare i comandi vserver vscan Connection-status show per visualizzare informazioni riepilogative e dettagliate sullo stato di connessione del server Vscan. 
---
= Comandi per visualizzare lo stato di connessione del server Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `vserver vscan connection-status show` Comandi per visualizzare informazioni riepilogative e dettagliate sullo stato di connessione del server Vscan.

|===
| Se si desidera... | Immettere il seguente comando... 


 a| 
Visualizza un riepilogo delle connessioni del server Vscan
 a| 
`vserver vscan connection-status show`



 a| 
Visualizza i dettagli delle connessioni al server Vscan
 a| 
`vserver vscan connection-status show-all`



 a| 
Visualizza i dettagli dei server Vscan connessi
 a| 
`vserver vscan connection-status show-connected`



 a| 
Visualizza i dettagli dei server Vscan disponibili non connessi
 a| 
`vserver vscan connection-status show-not-connected`

|===
Per ulteriori informazioni su questi comandi, consultare la link:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["Pagine man di ONTAP"].
