---
permalink: antivirus/create-scanner-pool-single-cluster-task.html 
sidebar: sidebar 
keywords: create, scanner pool, single cluster 
summary: Un pool di scanner definisce i server Vscan e gli utenti con privilegi che possono connettersi alle SVM. È possibile creare un pool di scanner per una singola SVM o per tutte le SVM in un cluster. 
---
= Creare un pool di scanner su un singolo cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool di scanner definisce i server Vscan e gli utenti con privilegi che possono connettersi alle SVM. È possibile creare un pool di scanner per una singola SVM o per tutte le SVM in un cluster.

.Di cosa hai bisogno
* I server SVM e Vscan devono trovarsi nello stesso dominio o in domini attendibili.
* Per i pool di scanner definiti per una singola SVM, è necessario aver configurato il connettore antivirus ONTAP con la LIF di gestione SVM o la LIF dei dati SVM.
* Per i pool di scanner definiti per tutte le SVM in un cluster, è necessario aver configurato il connettore antivirus ONTAP con la LIF di gestione del cluster.


.A proposito di questa attività
L'elenco degli utenti con privilegi deve includere l'account utente di dominio utilizzato dal server Vscan per connettersi a SVM.

.Fasi
. Creazione di un pool di scanner:
+
`vserver vscan scanner-pool create -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool -hostnames Vscan_server_hostnames -privileged-users privileged_users`

+
** Specificare una SVM di dati per un pool definito per una singola SVM e specificare una SVM amministrativa del cluster per un pool definito per tutte le SVM in un cluster.
** Specificare un indirizzo IP o un FQDN per ciascun nome host del server Vscan.
** Specificare il dominio e il nome utente per ciascun utente con privilegi. Per un elenco completo delle opzioni, vedere la pagina man del comando.


+
Il seguente comando crea un pool di scanner denominato `SP` su ``vs1``SVM:

+
[listing]
----
cluster1::> vserver vscan scanner-pool create -vserver vs1 -scanner-pool SP -hostnames 1.1.1.1,vmwin204-27.fsct.nb -privileged-users cifs\u1,cifs\u2
----
. Verificare che il pool di scanner sia stato creato: `vserver vscan scanner-pool show -vserver _data_SVM|cluster_admin_SVM_ -scanner-pool _scanner_pool_`
+
Per un elenco completo delle opzioni, vedere la pagina man del comando.

+
Il seguente comando visualizza i dettagli di `SP` pool di scanner:

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver vs1 -scanner-pool SP

                                    Vserver: vs1
                               Scanner Pool: SP
                             Applied Policy: idle
                             Current Status: off
         Cluster on Which Policy Is Applied: -
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
È inoltre possibile utilizzare `vserver vscan scanner-pool show` Per visualizzare tutti i pool di scanner su una SVM. Per la sintassi completa dei comandi, vedere la pagina man del comando.


