---
permalink: antivirus/enable-virus-scan-svm-task.html 
sidebar: sidebar 
keywords: enable, virus scan, svm 
summary: È necessario attivare la scansione virus su una SVM prima di eseguire una scansione on-access o on-demand. 
---
= Abilita la scansione antivirus su SVM ONTAP Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario attivare la scansione virus su una SVM prima di eseguire una scansione on-access o on-demand.

.Fasi
. Abilitare la scansione virus su una SVM:
+
`vserver vscan enable -vserver data_SVM`

+
Ulteriori informazioni su `vserver vscan enable` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-enable.html["Riferimento al comando ONTAP"^].

+
[NOTE]
====
Se necessario, è possibile utilizzare il `vserver vscan disable` comando per disattivare la scansione antivirus. Ulteriori informazioni su `vserver vscan disable` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-disable.html["Riferimento al comando ONTAP"^].

====
+
Il seguente comando attiva la scansione virus su `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan enable -vserver vs1
----
. Verificare che la scansione virus sia attivata su SVM:
+
`vserver vscan show -vserver data_SVM`

+
Ulteriori informazioni su `vserver vscan show` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-show.html["Riferimento al comando ONTAP"^].

+
Il seguente comando visualizza lo stato Vscan di `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan show -vserver vs1

                           Vserver: vs1
                      Vscan Status: on
----

