---
permalink: antivirus/modify-vscan-file-profile-smb-share-task.html 
sidebar: sidebar 
keywords: modify, vscan, file-operations, profile, cifs share 
summary: Il profilo delle operazioni del file Vscan per una condivisione SMB definisce quali operazioni sulla condivisione possono attivare la scansione. Per impostazione predefinita, il parametro è impostato su standard. È possibile regolare il parametro in base alle necessità quando si crea o si modifica una condivisione SMB. 
---
= Modificare il profilo delle operazioni del file Vscan per una condivisione SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il profilo delle operazioni del file Vscan per una condivisione SMB definisce quali operazioni sulla condivisione possono attivare la scansione. Per impostazione predefinita, il parametro è impostato su `standard`. È possibile regolare il parametro in base alle necessità quando si crea o si modifica una condivisione SMB.

.A proposito di questa attività
Per ulteriori informazioni sui valori disponibili per un profilo delle operazioni del file Vscan, vedere "`Vscan file-operation profile`".

link:architecture-concept.html["Profilo delle operazioni del file Vscan (solo scansione on-access)"]

[NOTE]
====
La scansione antivirus non viene eseguita su una condivisione SMB per la quale `continuously-available` il parametro è impostato su `Yes`.

====
.Fase
. Modificare il valore del profilo delle operazioni del file Vscan per una condivisione SMB: `vserver cifs share modify -vserver _data_SVM_ -share-name _share_ -path _share_path_ -vscan-fileop-profile no-scan|standard|strict|writes-only`
+
Per un elenco completo delle opzioni, vedere la pagina man del comando.

+
Il seguente comando modifica il profilo delle operazioni del file Vscan per una condivisione SMB in `strict`:

+
[listing]
----
cluster1::> vserver cifs share modify -vserver vs1 -share-name SALES_SHARE -path /sales -vscan-fileop-profile strict
----

