---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: 'È possibile creare un"attività senza assegnare una pianificazione e utilizzare `vserver vscan on-demand-task schedule` comando per assegnare un programma o aggiungere un programma durante la creazione dell"attività.' 
---
= Pianifica attività su richiesta con ONTAP Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un'attività senza assegnare una pianificazione e utilizzare `vserver vscan on-demand-task schedule` comando per assegnare un programma o aggiungere un programma durante la creazione dell'attività.

.A proposito di questa attività
La pianificazione assegnata con `vserver vscan on-demand-task schedule` il comando sovrascrive un programma già assegnato con `vserver vscan on-demand-task create` comando.

.Fasi
. Pianificare un'attività on-demand:
+
`vserver vscan on-demand-task schedule -vserver _data_SVM_ -task-name _task_name_ -schedule cron_schedule`

+
Il seguente comando pianifica un'attività di accesso denominata `Task2` su `vs2` SVM:

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
Ulteriori informazioni su `vserver vscan on-demand-task schedule` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-schedule.html["Riferimento al comando ONTAP"^].

+

NOTE: Per visualizzare lo stato del lavoro, utilizzare il `job show` comando . I `job pause` comandi e `job resume`, rispettivamente, sospendono e riavviano il lavoro; `job stop` il comando termina il lavoro. Ulteriori informazioni su `job` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=job["Riferimento al comando ONTAP"^].

. Verificare che l'attività on-demand sia stata pianificata:
+
`vserver vscan on-demand-task show -instance _data_SVM_ -task-name _task_name_`

+
Ulteriori informazioni su `vserver vscan on-demand-task show` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-show.html["Riferimento al comando ONTAP"^].

+
Il seguente comando visualizza i dettagli di `Task 2` attività:

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.Al termine
Prima di pianificare l'esecuzione dell'operazione, è necessario attivare la scansione sulla SVM.
