---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: 'Se è stata creata un"attività on-demand senza assegnare una pianificazione o se si desidera assegnare una pianificazione diversa a un"attività, è possibile utilizzare il comando vserver vscan on-demand-task schedule per assegnare una pianificazione all"attività.' 
---
= Pianificare un'attività on-demand
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è stata creata un'attività on-demand senza assegnare una pianificazione o se si desidera assegnare una pianificazione diversa a un'attività, è possibile utilizzare `vserver vscan on-demand-task schedule` comando per assegnare una pianificazione all'attività.

.A proposito di questa attività
La pianificazione assegnata con `vserver vscan on-demand-task schedule` il comando sovrascrive un programma già assegnato con `vserver vscan on-demand-task create` comando.

.Fasi
. Pianificare un'attività on-demand:
+
`vserver vscan on-demand-task schedule -vserver data_SVM -task-name task_name -schedule cron_schedule`

+
Il seguente comando pianifica un'attività di accesso denominata `Task2` su ``vs2``SVM:

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
[NOTE]
====
È possibile utilizzare `job show` per visualizzare lo stato del lavoro. È possibile utilizzare `job pause` e. `job resume` comandi per mettere in pausa e riavviare il lavoro o l' `job stop` per terminare il lavoro.

====
. Verificare che l'attività on-demand sia stata pianificata: `vserver vscan on-demand-task show -instance data_SVM -task-name task_name`
+
Per un elenco completo delle opzioni, vedere la pagina man del comando.

+
Il seguente comando visualizza i dettagli di `Task 2` attività:

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.Al termine
Prima di pianificare l'esecuzione dell'operazione, è necessario attivare la scansione sulla SVM.
