---
permalink: antivirus/vscan-server-connection-concept.html 
sidebar: sidebar 
keywords: potential connectivity, issues, involve, scan-mandatory, option 
summary: 'Per impostazione predefinita, l"opzione di scansione obbligatoria per la scansione all"accesso nega l"accesso al file quando non è disponibile una connessione al server Vscan per la scansione. Sebbene questa opzione offra importanti funzioni di sicurezza, può causare problemi in alcune situazioni.' 
---
= Potenziali problemi di connettività che coinvolgono l'opzione di scansione obbligatoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `vserver vscan connection-status show` Comandi per visualizzare informazioni sulle connessioni del server Vscan che potrebbero essere utili per la risoluzione dei problemi di connettività.

Per impostazione predefinita, il `scan-mandatory` L'opzione per la scansione all'accesso nega l'accesso ai file quando non è disponibile una connessione al server Vscan per la scansione. Sebbene questa opzione offra importanti funzioni di sicurezza, può causare problemi in alcune situazioni.

* Prima di abilitare l'accesso client, è necessario assicurarsi che almeno un server Vscan sia connesso a una SVM su ciascun nodo che dispone di una LIF. Se è necessario connettere i server alle SVM dopo aver attivato l'accesso client, è necessario disattivare `scan-mandatory` Opzione su SVM per garantire che l'accesso al file non venga negato perché non è disponibile una connessione al server Vscan. È possibile riattivare l'opzione dopo aver collegato il server.
* Se una LIF di destinazione ospita tutte le connessioni del server Vscan per una SVM, la connessione tra il server e la SVM andrà persa se la LIF viene migrata. Per garantire che l'accesso al file non venga negato perché non è disponibile una connessione al server Vscan, è necessario disattivare `scan-mandatory` Prima di migrare LIF. È possibile riattivare l'opzione dopo la migrazione del LIF.


A ciascuna SVM devono essere assegnati almeno due server Vscan. Si consiglia di collegare i server Vscan al sistema storage su una rete diversa da quella utilizzata per l'accesso client.

Ulteriori informazioni su `vserver vscan connection-status show` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-connection-status-show.html["Riferimento al comando ONTAP"^].
