---
permalink: antivirus/vscan-server-install-config-concept.html 
sidebar: sidebar 
keywords: vscan, server installation, configuration 
summary: È necessario configurare uno o più server Vscan per abilitare la scansione antivirus. 
---
= Installazione e configurazione del server Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Impostare uno o più server Vscan per verificare che i file sul sistema vengano sottoposti a scansione antivirus. Seguire le istruzioni fornite dal fornitore per installare e configurare il software antivirus sul server.

Seguire le istruzioni contenute nel file README fornito da NetApp per installare e configurare il connettore antivirus ONTAP. In alternativa, seguire le istruzioni sul link:install-ontap-antivirus-connector-task.html["Pagina installare il connettore antivirus ONTAP"].

[NOTE]
====
Per le configurazioni di disaster recovery e MetroCluster, è necessario configurare server Vscan separati per i cluster ONTAP primario/locale e secondario/partner.

====


== Requisiti del software antivirus

* Per informazioni sui requisiti del software antivirus, consultare la documentazione del vendor.
* Per informazioni su vendor, software e versioni supportate da Vscan, consultare link:https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html["Soluzioni partner di Vscan"^] pagina.




== Requisiti del connettore antivirus ONTAP

* È possibile scaricare il connettore antivirus ONTAP dalla pagina *Download software* sul sito di supporto NetApp. link:http://mysupport.netapp.com/NOW/cgi-bin/software["Download NetApp: Software"^]
* Per informazioni sulle versioni di Windows supportate dal connettore antivirus ONTAP e sui requisiti di interoperabilità, vedere link:https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html["Soluzioni partner di Vscan"^].
+
[NOTE]
====
È possibile installare diverse versioni dei server Windows per diversi server Vscan in un cluster.

====
* Sul server Windows deve essere installato .NET 3.0 o versione successiva.
* SMB 2.0 deve essere attivato sul server Windows.

