---
permalink: revert/anti-ransomware-license-task.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, anti-ransomware, autonomous, protection, arp, license, licensing 
summary: Se è stata configurata la protezione anti-ransomware e si passa da ONTAP 9.11.1 o versione successiva a ONTAP 9.10.1, potrebbero essere visualizzati messaggi di avviso e funzionalità anti-ransomware limitate. 
---
= Controllare la licenza Autonomous ransomware Protection prima di eseguire il ripristino da ONTAP 9.11.1 o versione successiva
:allow-uri-read: 


[role="lead"]
Se è stata configurata la protezione ransomware autonoma (ARP) e si passa da ONTAP 9.11.1 o versione successiva a ONTAP 9.10.1 o versione precedente, potrebbero verificarsi messaggi di avviso e funzionalità ARP limitate.

In ONTAP 9.11.1, la licenza anti-ransomware ha sostituito la licenza per la gestione delle chiavi multi-tenant (MTKM). Se il sistema dispone della licenza Anti_ransomware ma non della licenza MT_EK_MGMT, durante il revert viene visualizzato un avviso che informa che ARP non può essere abilitato sui nuovi volumi al momento del revert.

I volumi con protezione esistente continueranno a funzionare normalmente dopo il ripristino e lo stato ARP può essere visualizzato utilizzando l'interfaccia CLI di ONTAP. System Manager non può visualizzare lo stato ARP senza la licenza MTKM.

Pertanto, se si desidera che ARP continui dopo aver eseguito il ripristino a ONTAP 9.10.1, assicurarsi che la licenza MTKM sia installata prima di eseguire il ripristino. link:../anti-ransomware/index.html["Scopri di più sulle licenze ARP."]
