---
permalink: revert/arp-warning-clear-revert.html 
sidebar: sidebar 
keywords: ontap, revert, ransomware, protection, security, arp 
summary: Prima di ripristinare ONTAP, rispondi a qualsiasi avviso di attività anomala in Autonomous Ransomware Protection 
---
= Risolvere gli avvisi di attività in Autonomous Ransomware Protection prima di un ripristino ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di tornare a ONTAP 9.17.1 o versioni precedenti, dovresti rispondere a qualsiasi avviso di attività anomala segnalato da Autonomous Ransomware Protection ed eliminare tutte le snapshot di Autonomous Ransomware Protection associate.

.Prima di iniziare
Per eliminare gli snapshot di Autonomous Ransomware Protection hai bisogno di privilegi "Advanced".

.Fasi
. Rispondi a qualsiasi avviso di attività anomala segnalato da link:../anti-ransomware/respond-abnormal-task.html["Protezione ransomware autonoma"] e risolvi eventuali problemi.
. Conferma la risoluzione di questi problemi prima di ripristinare selezionando *Aggiorna e cancella i tipi di file sospetti* per registrare la tua decisione e riprendere il normale monitoraggio di Autonomous Ransomware Protection.
. Elenca tutte le istantanee di Autonomous Ransomware Protection associate agli avvisi eseguendo il seguente comando:
+
[source, cli]
----
volume snapshot snapshot show -fs-version 9.18
----
. Elimina tutte le istantanee di Autonomous Ransomware Protection associate agli avvisi:
+

NOTE: Questo comando elimina tutte le istantanee che hanno il formato utilizzato dalla versione corrente di ONTAP, potenzialmente non solo le istantanee di Autonomous Ransomware Protection. Assicurati di aver intrapreso tutte le azioni necessarie per tutte le istantanee che verranno rimosse prima di eseguire questo comando.

+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----

