---
permalink: revert/arp-warning-clear-revert.html 
sidebar: sidebar 
keywords: ontap, revert, ransomware, protection, security, arp 
summary: Prima di ripristinare ONTAP, rispondere a qualsiasi avviso di attività anomala in ARP 
---
= Risolvi gli avvisi di attività in Autonomous Ransomware Protection (ARP) prima di un ripristino ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di tornare a ONTAP 9.17.1 o a una versione precedente, è necessario rispondere a qualsiasi avviso di attività anomala segnalato da Autonomous Ransomware Protection (ARP) ed eliminare tutti gli screenshot ARP associati.

.Prima di iniziare
Per eliminare gli snapshot ARP sono necessari privilegi "Avanzati".

.Fasi
. Rispondere a eventuali avvisi di attività anomala segnalati da link:../anti-ransomware/respond-abnormal-task.html["ARP"] e risolvere eventuali problemi potenziali.
. Conferma la risoluzione di questi problemi prima di tornare indietro selezionando *Aggiorna e cancella i tipi di file sospetti* per registrare la tua decisione e riprendere il normale monitoraggio ARP.
. Elencare tutti gli screenshot ARP associati agli avvisi eseguendo il seguente comando:
+
[source, cli]
----
volume snapshot snapshot show -fs-version 9.18
----
. Eliminare tutti gli screenshot ARP associati agli avvisi:
+

NOTE: Questo comando elimina tutti gli snapshot che hanno il formato utilizzato dalla versione corrente di ONTAP, potenzialmente non solo gli snapshot ARP.  Prima di eseguire questo comando, assicurarsi di aver eseguito tutte le azioni necessarie per tutti gli snapshot che verranno rimossi.

+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----

