---
permalink: revert/concept_revert_process_considerations.html 
sidebar: sidebar 
keywords: ontap, revert, limitations, issues 
summary: Prima di iniziare una reversione del ONTAP, è necessario considerare i problemi e le limitazioni di revert. 
---
= Problemi e limitazioni di ripristino di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di ripristinare un cluster ONTAP, è necessario prendere in considerazione i problemi e le limitazioni di indirizzamento.

* Il revversion è un'operazione di interruzione.
+
Durante la revisione non è possibile accedere al client. Se si sta ripristinando un cluster di produzione, assicurarsi di includere questa interruzione nella pianificazione.

* La risversione influisce su tutti i nodi del cluster.
+
La reversione interessa tutti i nodi nel cluster; tuttavia, la reversione deve essere eseguita e completata su ogni coppia ha prima che le altre coppie ha vengano ripristinate.

* La revisione è completa quando tutti i nodi eseguono la nuova release di destinazione.
+
Quando il cluster si trova in uno stato di versione mista, non inserire alcun comando che alteri l'operazione o la configurazione del cluster, a meno che non sia necessario per soddisfare i requisiti di reversione; sono consentite le operazioni di monitoraggio.

+

IMPORTANT: Se alcuni nodi sono stati ripristinati, ma non tutti, non tentare di aggiornare il cluster alla release di origine.

* Quando si ripristina un nodo, i dati memorizzati nella cache vengono cancellati in un modulo Flash cache.
+
Poiché nel modulo Flash cache non sono presenti dati memorizzati nella cache, il nodo serve le richieste di lettura iniziali dal disco, con conseguente riduzione delle prestazioni di lettura durante questo periodo. Il nodo ricompila la cache man mano che serve le richieste di lettura.

* Un LUN di cui viene eseguito il backup su nastro in esecuzione su ONTAP 9.x può essere ripristinato solo alla versione 9.x e successive e non a una versione precedente.
* Se la versione corrente di ONTAP supporta la funzionalità ACP in-band e si ripristina una versione di ONTAP che non supporta IBACP, il percorso alternativo dello shelf di dischi viene disattivato.
* Se LDAP viene utilizzato da una qualsiasi delle macchine virtuali di storage (SVM), la funzione di riferimento LDAP deve essere disattivata prima della revisione.
* Nei sistemi MetroCluster IP che utilizzano switch conformi a MetroCluster ma non validati da MetroCluster, la revisione da ONTAP 9.7 a 9.6 è un'interruzione, in quanto non è disponibile alcun supporto per i sistemi che utilizzano ONTAP 9.6 e versioni precedenti.
* Prima di ripristinare un nodo in ONTAP 9.13.1 o versione precedente, devi prima convertire un volume root SVM crittografato in un volume non crittografato
+
Se si tenta di ripristinare una versione che non supporta la crittografia del volume root della SVM, il sistema risponde con un avviso e blocca la reversione.


