---
permalink: revert/concept_consideration_for_reverting_systems_with_snapmirror_synchronous_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, considerations, snapmirror, synchronous, relationships 
summary: Prima di eseguire il ripristino da ONTAP 9.6 a ONTAP 9.5, è necessario conoscere le considerazioni relative alle relazioni sincroni di SnapMirror. 
---
= Considerazioni per il ripristino dei sistemi con le relazioni sincroni di SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire il ripristino da ONTAP 9.6 a ONTAP 9.5, è necessario conoscere le considerazioni relative alle relazioni sincroni di SnapMirror.

Prima di eseguire il ripristino, è necessario eseguire le seguenti operazioni se si dispone di relazioni sincroni di SnapMirror:

* È necessario eliminare qualsiasi relazione sincrona di SnapMirror in cui il volume di origine sta fornendo dati utilizzando NFSv4 o SMB.
+
ONTAP 9.5 non supporta NFSv4 e SMB.

* È necessario eliminare qualsiasi relazione sincrona di SnapMirror in una distribuzione a cascata con mirror.
+
Un'implementazione a cascata di mirror non è supportata per le relazioni sincroni di SnapMirror in ONTAP 9.5.

* Se le copie Snapshot comuni in ONTAP 9.5 non sono disponibili durante il ripristino, è necessario inizializzare la relazione sincrona di SnapMirror dopo il ripristino.
+
Dopo due ore di aggiornamento a ONTAP 9.6, le copie Snapshot comuni di ONTAP 9.5 vengono sostituite automaticamente dalle copie Snapshot comuni di ONTAP 9.6. Pertanto, non è possibile risincronizzare la relazione sincrona di SnapMirror dopo il ripristino se le copie Snapshot comuni da ONTAP 9.5 non sono disponibili.


