---
permalink: revert/concept_reversion_requirements_for_snapmirror_and_snapvault_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, requirements, snapmirror, snapvault, relationships 
summary: 'Il comando revert-to del nodo di sistema notifica all"utente tutte le relazioni SnapMirror e SnapVault che devono essere eliminate o riconfigurate per il completamento del processo di revert. Tuttavia, è necessario conoscere questi requisiti prima di iniziare la revisione.' 
---
= Requisiti di revert ONTAP per le relazioni SnapMirror e SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `system node revert-to` comando informa l'utente di tutte le relazioni SnapMirror e SnapVault che devono essere eliminate o riconfigurate per il completamento del processo di indirizzamento. Tuttavia, è necessario conoscere questi requisiti prima di iniziare la revisione.

* Tutte le relazioni mirror di SnapVault e data Protection devono essere interrotte e poi interrotte.
+
Una volta completata la reversione, è possibile risincronizzare e riprendere queste relazioni se esiste uno snapshot comune.

* Le relazioni di SnapVault non devono contenere i seguenti tipi di criteri di SnapMirror:
+
** mirror asincrono
+
È necessario eliminare qualsiasi relazione che utilizzi questo tipo di criterio.

** MirrorAndVault
+
Se esiste una di queste relazioni, modificare la policy di SnapMirror in mirror-vault.



* Tutte le relazioni mirror di condivisione del carico e i volumi di destinazione devono essere cancellati.
* Le relazioni di SnapMirror con i volumi di destinazione FlexClone devono essere eliminate.
* La compressione di rete deve essere disattivata per ciascun criterio SnapMirror.
* La regola all_source_snapshot deve essere rimossa da qualsiasi policy SnapMirror di tipo async-mirror.
+

NOTE: Le operazioni SFSR (Single file Snapshot Restore) e PFSR (Partial file Snapshot Restore) sono obsolete nel volume root.

* Tutte le operazioni di ripristino di snapshot e file singoli attualmente in esecuzione devono essere completate prima di poter procedere con la nuova versione.
+
È possibile attendere il completamento dell'operazione di ripristino oppure interromperla.

* Tutte le operazioni di ripristino di Snapshot e file singoli incomplete devono essere rimosse utilizzando il `snapmirror restore` comando.
+
Ulteriori informazioni su `snapmirror restore` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["Riferimento al comando ONTAP"^].


