---
permalink: revert/concept_support_of_sp_firmware_automatic_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, considerations, manual, manually, update, updating, sp, firmware 
summary: Se la funzionalità di aggiornamento automatico SP è attivata, il downgrade o il ritorno a ONTAP 8.3.x non richiede un aggiornamento manuale del firmware SP. Il firmware SP viene aggiornato automaticamente alla versione più recente compatibile supportata dalla versione di ONTAP a cui si è eseguito il ripristino o il downgrade. 
---
= Considerazioni sull'aggiornamento manuale del firmware SP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la funzionalità di aggiornamento automatico SP è attivata (impostazione predefinita), il downgrade o il ripristino a ONTAP 8.3.x non richiede un aggiornamento manuale del firmware SP. Il firmware SP viene aggiornato automaticamente alla versione più recente compatibile supportata dalla versione di ONTAP a cui si è eseguito il ripristino o il downgrade.

Se la funzionalità di aggiornamento automatico del SP è disattivata (non consigliata), una volta completato il processo di revert o downgrade del ONTAP, è necessario aggiornare manualmente il firmware del SP a una versione supportata per la versione del ONTAP a cui si è eseguito il ripristino o il downgrade.

http://mysupport.netapp.com/NOW/download/tools/serviceimage/support/["Matrice di supporto BIOS/ONTAP di NetApp"]

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Download NetApp: Firmware di sistema e diagnostica"]
