---
permalink: revert/concept_revert_paths.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: La versione di ONTAP a cui è possibile ripristinare varia in base alla versione di ONTAP attualmente in esecuzione sui nodi. 
---
= Percorsi di revert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La versione di ONTAP a cui è possibile ripristinare varia in base alla versione di ONTAP attualmente in esecuzione sui nodi. È possibile utilizzare `system image show` Per determinare la versione di ONTAP in esecuzione su ciascun nodo.

Queste linee guida si riferiscono solo alle release on-premise di ONTAP. Per informazioni sul ripristino di ONTAP nel cloud, vedere https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#reverting-or-downgrading["Ripristino o downgrade di Cloud Volumes ONTAP"^].

[cols="2*"]
|===
| Puoi ripristinare da... | Per... 


 a| 
ONTAP 9.15.1
| ONTAP 9.14.1 


 a| 
ONTAP 9.14.1
| ONTAP 9.13.1 


 a| 
ONTAP 9.13.1
| ONTAP 9.12.1 


 a| 
ONTAP 9.12.1
| ONTAP 9.11.1 


 a| 
ONTAP 9.11.1
| ONTAP 9.10.1 


 a| 
ONTAP 9.10.1
| ONTAP 9.9.1 


 a| 
ONTAP 9.9.1
| ONTAP 9.8 


 a| 
ONTAP 9.8
 a| 
ONTAP 9.7



 a| 
ONTAP 9.7
 a| 
ONTAP 9.6



 a| 
ONTAP 9.6
 a| 
ONTAP 9.5



 a| 
ONTAP 9.5
 a| 
ONTAP 9.4



 a| 
ONTAP 9.4
 a| 
ONTAP 9.3



 a| 
ONTAP 9.3
 a| 
ONTAP 9.2



 a| 
ONTAP 9.2
 a| 
ONTAP 9.1



 a| 
ONTAP 9.1 o ONTAP 9
 a| 
Data ONTAP 8.3.x

|===

NOTE: Per passare da ONTAP 9.1 a 9.0, seguire la procedura link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876873["processo di downgrade"^] documentato qui.
