---
permalink: revert/disable-extended-qtree-performance-monitoring.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, downgrade, downgrading, preparation 
summary: 'Diverse impostazioni di configurazione possono influire sulla preparazione all"aggiornamento del cluster.' 
---
= Disattivare il monitoraggio delle prestazioni Qtree esteso prima di tornare da ONTAP 9.16.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.16,1, puoi utilizzare l'API REST ONTAP per accedere alle funzionalità estese di monitoring del qtree, che comprendono metriche di latenza e statistiche cronologiche. Se su qualsiasi qtree è abilitato il monitoraggio esteso dei qtree, prima di tornare da 9.16.1, devi impostare `ext_performance_monitoring.enabled` su false.

Si lavora con l' `ext_performance_monitoring.enabled`impostazione utilizzando l' `/api/storage/qtrees`endpoint. Usa GET per recuperare il valore corrente, POST per impostarlo quando si crea un nuovo qtree e PATCH per modificarlo su un qtree esistente.

Ulteriori informazioni su link:../volumes/qtrees-partition-your-volumes-concept.html#upgrading-and-reverting["ripristino dei cluster con monitoraggio delle performance esteso del qtree"].
