---
permalink: revert/modify-qos-policy-groups.html 
sidebar: sidebar 
keywords: modify, modifying, qos, policy, groups, adaptive, non-adaptive, revert, reverting, 9.19.1 
summary: 'Se si esegue il ripristino da ONTAP 9.12.1, è necessario disattivare l"autenticazione in banda prima di eseguire l"ripristino.' 
---
= Modifica i gruppi di criteri QoS creati in ONTAP 9.19.1 o versioni successive prima di eseguire il revert da ONTAP 9.19.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I gruppi di criteri QoS adattivi e non adattivi vengono abilitati automaticamente per aumentare temporaneamente del 50% il throughput massimo di un carico di lavoro per una durata di 1 secondo, al fine di rispondere alle richieste a breve termine di prestazioni superiori per impostazione predefinita. A partire da ONTAP 9.19.1, è possibile modificare queste impostazioni predefinite. In ONTAP 9.18.1 e versioni precedenti queste impostazioni non possono essere modificate. Se sono state modificate le impostazioni predefinite di un gruppo di criteri QoS creato in ONTAP 9.19.1 o versioni successive, è necessario ripristinarle prima di poter tornare da ONTAP 9.19.1 a ONTAP 9.18.1.

.Fasi
. Verifica se hai gruppi di criteri QoS abilitati per l'aumento automatico del limite di throughput:
+
[source, cli]
----
qos policy-group show – instance
----
. Se sono configurati gruppi di criteri con `burst-percent`, `burst-iops`, e `burst-duration`, impostare queste opzioni su 0.
+
[source, cli]
----
qos policy-group modify -policy-group <policy-group> -burst-percent 0 -burst-iops 0 -burst-duration 0
----

