---
permalink: revert/remove-nas-bucket-task.html 
sidebar: sidebar 
keywords: s3, svm, bucket, object, server, filesystems, nas, directories, revert 
summary: 'Se è stato configurato l"accesso al client S3 per i dati NAS e si passa da ONTAP 9.12.1 o versione successiva a ONTAP 9.11.1 o versione precedente, è necessario rimuovere la configurazione del bucket NAS e rimuovere qualsiasi utente S3 per le mappature dei nomi utente Windows/Unix prima di eseguire il ripristino.' 
---
= Rimuovere la configurazione del bucket S3 NAS prima di tornare da ONTAP 9.12.1 o versione successiva
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è stato configurato l'accesso client S3 per i dati NAS, prima di passare da ONTAP 9.12.1 o versione successiva a ONTAP 9.11.1 o versione precedente, è necessario utilizzare l'interfaccia a riga di comando (CLI) di ONTAP per rimuovere la configurazione del bucket NAS e rimuovere eventuali mappature dei nomi (da S3 utenti a utenti Windows o Unix).

.A proposito di questa attività
Le seguenti attività vengono completate in background durante il processo di revert.

* Rimuovere tutte le creazioni di oggetti singleton parzialmente completate (ovvero tutte le voci nelle directory nascoste).
* Rimuovere tutte le directory nascoste; potrebbe esserci una per ogni volume accessibile dalla directory principale dell'esportazione mappata dal bucket S3 NAS.
* Rimuovere la tabella di caricamento.
* Eliminare tutti i valori default-unix-user e default-Windows-user per tutti i server S3 configurati.


.Fasi
. Rimuovere la configurazione della benna S3 NAS:
+
[source, cli]
----
vserver object-store-server bucket delete -vserver _svm_name_ -bucket _s3_nas_bucket_name_
----
. Rimuovi mapping dei nomi per UNIX:
+
[source, cli]
----
vserver name-mapping delete -vserver _svm_name_ -direction s3-unix
----
. Rimuovere le mappature dei nomi per Windows:
+
[source, cli]
----
vserver name-mapping delete -vserver _svm_name_ -direction s3-win
----
. Rimozione dei protocolli S3 dalla SVM:
+
[source, cli]
----
vserver remove-protocols -vserver <svm_name> -protocols s3
----

