---
permalink: revert/task_reverting_an_ontap_cluster.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, cluster 
summary: Per portare il cluster offline per tornare a una versione precedente di ONTAP, è necessario disattivare il failover dello storage e le LIF dei dati, gestire le precondizioni di reversione, ripristinare le configurazioni del cluster e del file system su un nodo, quindi ripetere il processo per ciascun nodo aggiuntivo del cluster. 
---
= Ripristinare un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ripristino di un cluster ONTAP provoca interruzioni. È necessario portare il cluster offline per tutta la durata della reversione. Non ripristinare un cluster di produzione senza l'assistenza del supporto tecnico.

Per ripristinare un cluster nuovo o di test, devi disabilitare il failover dello storage, le LIF dati e le condizioni preliminari della reversione degli indirizzi, quindi devi ripristinare la configurazione del cluster e del file system in ogni nodo del cluster.

.Prima di iniziare.
* È necessario aver completato il link:task_things_to_verify_before_revert.html["verifiche pre-indirizzamento"].
* È necessario aver completato la richiesta link:concept_pre_revert_checks.html["Controlli preliminari per la versione ONTAP specifica"].




== Passaggio 1: Preparare il cluster per la riversione

Prima di ripristinare qualsiasi nodo del cluster, occorre verificare che sia installata l'immagine ONTAP di destinazione e disabilitare tutte le LIF dati nel cluster.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
+
Inserire *y* quando viene richiesto di continuare.

. Verificare che il software ONTAP di destinazione sia installato:
+
[source, cli]
----
system image show
----
+
L'esempio seguente mostra che la versione 9.13.1 è installata come immagine alternativa su entrambi i nodi:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Disattivare tutte le LIF dei dati nel cluster:
+
[source, cli]
----
network interface modify {-role data} -status-admin down
----
. Determinare se si dispone di relazioni FlexCache tra cluster:
+
[source, cli]
----
flexcache origin show-caches -relationship-type inter-cluster
----
. Se sono presenti flexcache tra cluster, disattivare il ciclo di vita dei dati sul cluster di cache:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin down
----




== Passaggio 2: Ripristina nodi cluster

Per ripristinare il cluster, è necessario ripristinare il primo nodo in una coppia ha, quindi ripristinare il nodo partner. Ripetere questa procedura per ciascuna coppia ha del cluster fino a quando tutti i nodi non vengono ripristinati. Se si dispone di una configurazione MetroCluster, è necessario ripetere questa procedura per entrambi i cluster nella configurazione.

[role="tabbed-block"]
====
.4 o più nodi
--
.Fasi
. Accedere al nodo che si desidera ripristinare.
+
Per ripristinare un nodo, è necessario accedere al cluster attraverso la LIF di gestione dei nodi del nodo.

. Disabilitare il failover dello storage per i nodi nella coppia ha:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
È necessario disattivare il failover dello storage una sola volta per la coppia ha. Quando si disattiva il failover dello storage per un nodo, anche il failover dello storage viene disattivato sul partner del nodo.

. Impostare l'immagine software ONTAP di destinazione del nodo come immagine predefinita:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Verificare che l'immagine del software ONTAP di destinazione sia impostata come immagine predefinita per il nodo che si sta ripristinando:
+
[source, cli]
----
system image show
----
+
L'esempio seguente mostra che la versione 9.13.1 è impostata come immagine predefinita su node0:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Verificare che il nodo sia pronto per la reversione:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
Il `check-only` parametro identifica eventuali condizioni preliminari che devono essere risolte prima del ripristino, come la disattivazione del criterio snapshot o l'eliminazione degli snapshot creati dopo l'aggiornamento alla versione successiva di ONTAP.

+
L' `-version`opzione si riferisce alla versione di ONTAP a cui si sta eseguendo il ripristino. Ad esempio, se si torna da 9.14.1 a 9.13.1, il valore corretto dell' `-version`opzione è 9.13.1.

. Ripristinare la configurazione del cluster del nodo:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
La configurazione del cluster viene ripristinata e l'utente viene disconnesso dalla shell del clustershell.

. Attendere il prompt di login, quindi immettere *No* quando viene richiesto se si desidera accedere alla shell di sistema.
+
La visualizzazione della richiesta di accesso potrebbe richiedere fino a 30 minuti o più.

. Accedere alla shell del cluster con admin.
. Passare alla nodeshell:
+
[source, cli]
----
run -node <nodename>
----
+
Dopo aver effettuato nuovamente l'accesso alla shell clustershell, potrebbero essere necessari alcuni minuti prima che sia pronto ad accettare il comando nodeshell. Quindi, se il comando non riesce, attendere alcuni minuti e riprovare.

. Ripristinare la configurazione del file system del nodo:
+
[source, cli]
----
revert_to 9.x
----
+
Questo comando verifica che la configurazione del file system del nodo sia pronta per essere ripristinata, quindi la ripristina. Se vengono identificate eventuali condizioni preliminari, è necessario indirizzarle e quindi eseguire nuovamente il `revert_to` comando.

+

NOTE: L'utilizzo di una console di sistema per monitorare il processo di revert consente di visualizzare maggiori dettagli rispetto a quelli visualizzati in un nodeshell.

+
Se AUTOBOOT è true, al termine del comando, il nodo si riavvierà in ONTAP.

+
Se l'AUTOBOOT è false, al termine del comando viene visualizzato il prompt Loader. Immettere `yes` per ripristinare, quindi utilizzare `boot_ontap` per riavviare manualmente il nodo.

. Una volta riavviato il nodo, verificare che il nuovo software sia in esecuzione:
+
[source, cli]
----
system node image show
----
+
Nell'esempio seguente, image1 è la nuova versione di ONTAP ed è impostata come la versione corrente su node0:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Verificare che lo stato di indirizzamento per il nodo sia completo:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
Lo stato deve essere "completo", "non necessario" o "non sono state restituite voci di tabella".

. Ripetere questi passaggi sull'altro nodo della coppia ha, quindi ripetere questi passaggi per ogni coppia ha aggiuntiva.
+
Se si dispone di una configurazione MetroCluster, è necessario ripetere questa procedura su entrambi i cluster nella configurazione

. Dopo aver ripristinato tutti i nodi, riabilitare l'alta disponibilità per il cluster:
+
[source, cli]
----
cluster ha modify -configured true
----


--
.cluster a 2 nodi
--
. Accedere al nodo che si desidera ripristinare.
+
Per ripristinare un nodo, è necessario accedere al cluster attraverso la LIF di gestione dei nodi del nodo.

. Disattivazione dell'alta disponibilità (ha) del cluster:
+
[source, cli]
----
cluster ha modify -configured false
----
. Disattivare il failover dello storage:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
È necessario disattivare il failover dello storage una sola volta per la coppia ha. Quando si disattiva il failover dello storage per un nodo, anche il failover dello storage viene disattivato sul partner del nodo.

. Impostare l'immagine software ONTAP di destinazione del nodo come immagine predefinita:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Verificare che l'immagine del software ONTAP di destinazione sia impostata come immagine predefinita per il nodo che si sta ripristinando:
+
[source, cli]
----
system image show
----
+
Il seguente esempio mostra che la versione 9.1 è impostata come immagine predefinita su node0:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.2        MM/DD/YYYY TIME
         image2  true    false   9.1        MM/DD/YYYY TIME
node1
         image1  true    true    9.2        MM/DD/YYYY TIME
         image2  false   false   9.1        MM/DD/YYYY TIME
4 entries were displayed.
----
. Verificare se il nodo contiene attualmente epsilon:
+
[source, cli]
----
cluster show -node <nodename>
----
+
L'esempio seguente mostra che il nodo contiene epsilon:

+
[listing]
----
cluster1::*> cluster show -node node1

          Node: node1
          UUID: 026efc12-ac1a-11e0-80ed-0f7eba8fc313
       Epsilon: true
   Eligibility: true
        Health: true
----
+
.. Se il nodo contiene epsilon, contrassegnare epsilon come false sul nodo in modo che epsilon possa essere trasferito al partner del nodo:
+
[source, cli]
----
cluster modify -node <nodename> -epsilon false
----
.. Trasferire epsilon al partner del nodo contrassegnando epsilon true sul nodo partner:
+
[source, cli]
----
cluster modify -node <node_partner_name> -epsilon true
----


. Verificare che il nodo sia pronto per la reversione:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
Il `check-only` parametro identifica tutte le condizioni che devono essere risolte prima del ripristino, come la disattivazione del criterio snapshot o l'eliminazione degli snapshot creati dopo l'aggiornamento alla versione successiva di ONTAP.

. Ripristinare la configurazione del cluster del nodo:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
L' `-version`opzione si riferisce alla versione di ONTAP a cui si sta eseguendo il ripristino. Ad esempio, se si torna da 9.14.1 a 9.13.1, il valore corretto dell' `-version`opzione è 9.13.1.

+
La configurazione del cluster viene ripristinata e l'utente viene disconnesso dalla shell del clustershell.

. Attendere il prompt di login, quindi immettere `No` quando viene richiesto se si desidera accedere alla shell di sistema.
+
La visualizzazione della richiesta di accesso potrebbe richiedere fino a 30 minuti o più.

. Accedere alla shell del cluster con admin.
. Passare alla nodeshell:
+
[source, cli]
----
run -node <nodename>
----
+
Dopo aver effettuato nuovamente l'accesso alla shell clustershell, potrebbero essere necessari alcuni minuti prima che sia pronto ad accettare il comando nodeshell. Quindi, se il comando non riesce, attendere alcuni minuti e riprovare.

. Ripristinare la configurazione del file system del nodo:
+
[source, cli]
----
revert_to 9.x
----
+
Questo comando verifica che la configurazione del file system del nodo sia pronta per essere ripristinata, quindi la ripristina. Se vengono identificate eventuali condizioni preliminari, è necessario indirizzarle e quindi eseguire nuovamente il `revert_to` comando.

+

NOTE: L'utilizzo di una console di sistema per monitorare il processo di revert consente di visualizzare maggiori dettagli rispetto a quelli visualizzati in un nodeshell.

+
Se AUTOBOOT è true, al termine del comando, il nodo si riavvierà in ONTAP.

+
Se L'OPZIONE AUTOBOOT è false, al termine del comando viene visualizzato il prompt DEL CARICATORE. Invio `yes` per ripristinare, quindi utilizzare `boot_ontap` per riavviare manualmente il nodo.

. Una volta riavviato il nodo, verificare che il nuovo software sia in esecuzione:
+
[source, cli]
----
system node image show
----
+
Nell'esempio seguente, image1 è la nuova versione di ONTAP ed è impostata come la versione corrente su node0:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Verificare che lo stato di indirizzamento sia completo per il nodo:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
Lo stato deve essere "completo", "non necessario" o "non sono state restituite voci di tabella".

. Ripeti questi passaggi sull'altro nodo della coppia ha.
. Dopo aver ripristinato entrambi i nodi, riabilitare l'alta disponibilità per il cluster:
+
[source, cli]
----
cluster ha modify -configured true
----
. Riattivare il failover dello storage su entrambi i nodi:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled true
----


--
====