---
permalink: revert/task_identifying_and_moving_cifs_servers_in_workgroup_mode.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, identifying, identify, move, moving, delete, deleting, cifs, servers, workgroup, mode, SMB 
summary: Prima di eseguire un revert, è necessario eliminare tutti i server SMB in modalità gruppo di lavoro o spostarli in un dominio. La modalità Workgroup non è supportata nelle versioni di ONTAP precedenti a ONTAP 9. 
---
= Identificare e spostare i server SMB in modalità workgroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire un revert, è necessario eliminare tutti i server SMB in modalità gruppo di lavoro o spostarli in un dominio. La modalità Workgroup non è supportata nelle versioni di ONTAP precedenti a ONTAP 9.

. Identificare i server SMB con uno stile di autenticazione del gruppo di lavoro: `vserver cifs show`
. Spostare o eliminare i server identificati:
+
[cols="2*"]
|===
| Se stai andando a... | Quindi utilizzare questo comando.... 


 a| 
Spostare il server SMB dal gruppo di lavoro a un dominio Active Directory:
 a| 
`vserver cifs modify -vserver _vserver_name_ -domain _domain_name_`



 a| 
Eliminare il server SMB
 a| 
`vserver cifs delete -vserver vserver_name`

|===
. Se il server SMB è stato eliminato, immettere il nome utente del dominio, quindi la password utente.


.Informazioni correlate
link:../smb-admin/index.html["Gestione delle PMI"]
