---
permalink: revert/task_preparing_snapshot_copies_before_reverting.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, snapshot, copies, prepare, preparing, disable, delete 
summary: 'Prima di tornare a una versione precedente di ONTAP, è necessario disattivare tutti i criteri di snapshot ed eliminare gli snapshot creati dopo l"aggiornamento alla release corrente.' 
---
= Preparare le Snapshot prima di ripristinare un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di ripristinare un cluster ONTAP da qualsiasi versione di ONTAP 9, è necessario disattivare tutte le policy degli snapshot ed eliminare gli snapshot creati dopo l'aggiornamento alla release corrente.

Se si esegue il ripristino in un ambiente SnapMirror, è necessario prima eliminare le seguenti relazioni mirror:

* Tutte le relazioni mirror di condivisione del carico
* Qualsiasi relazione di mirroring della protezione dei dati creata in ONTAP 8.3.x.
* Tutte le relazioni di mirroring della protezione dei dati se il cluster è stato ricreato in ONTAP 8.3.x.


.Fasi
. Disattivare le policy di snapshot per tutte le SVM di dati:
+
[source, cli]
----
volume snapshot policy modify -vserver * -enabled false
----
. Disabilitare le policy di snapshot per gli aggregati di ogni nodo:
+
.. Identificare gli aggregati del nodo:
+
[source, cli]
----
run -node <nodename> -command aggr status
----
.. Disattiva la policy di snapshot per ogni aggregato:
+
[source, cli]
----
run -node <nodename> -command aggr options aggr_name nosnap on
----
.. Ripetere questo passaggio per ogni nodo rimanente.


. Disabilitare le policy di snapshot per il volume root di ogni nodo:
+
.. Identificare il volume root del nodo:
+
[source, cli]
----
run -node <node_name> -command vol status
----
+
Il volume root viene identificato dalla parola root nella colonna *Options* dell'output del `vol status` comando.

+
[listing]
----
vs1::> run -node node1 vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. Disattivare il criterio snapshot sul volume root:
+
[source, cli]
----
run -node <node_name> vol options root_volume_name nosnap on
----
.. Ripetere questo passaggio per ogni nodo rimanente.


. Eliminare tutti gli snapshot creati dopo l'aggiornamento alla release corrente:
+
.. Impostare il livello di privilegio su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
.. Disattivare le snapshot:
+
[source, cli]
----
snapshot policy modify -vserver * -enabled false
----
.. Elimina gli snapshot della versione più recente del nodo:
+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----
+
Questo comando elimina gli Snapshot di versione più recente in ogni volume di dati, aggregato root e volume root.

+
Se non è possibile eliminare uno snapshot, il comando non riesce e avvisa l'utente di eventuali azioni necessarie prima di poter eliminare gli snapshot. Prima di passare alla fase successiva, completare le azioni richieste e rieseguire il `volume snapshot prepare-for-revert` comando.

+
[listing]
----
cluster1::*> volume snapshot prepare-for-revert -node node1

Warning: This command will delete all snapshots that have the format used by the current version of ONTAP. It will fail if any snapshot policies are enabled, or
         if any snapshots have an owner. Continue? {y|n}: y
----
.. Verificare che gli snapshot siano stati eliminati:
+
[source, cli]
----
volume snapshot show -node nodename
----
.. Se rimangono istantanee di versione più recente, forzarne l'eliminazione:
+
[source, cli]
----
volume snapshot delete {-fs-version 9.0 -node nodename -is-constituent true} -ignore-owners -force
----
.. Ripetere questi passaggi per ogni nodo rimanente.
.. Tornare al livello di privilegio admin:
+
[source, cli]
----
set -privilege admin
----





NOTE: È necessario eseguire questi passaggi su entrambi i cluster nella configurazione MetroCluster.
