---
permalink: revert/task_reverting_systems_with_deduplicated_volumes.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, systems, deduplication, deduplicated, volumes 
summary: 'Prima di eseguire il ripristino da qualsiasi versione di ONTAP 9, è necessario assicurarsi che i volumi contengano spazio libero sufficiente per l"operazione di revert.' 
---
= Verifica dello spazio libero per i volumi deduplicati prima di ripristinare ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di ripristinare un cluster ONTAP da qualsiasi versione di ONTAP 9, è necessario verificare che i volumi contengano spazio libero sufficiente per l'operazione di indirizzamento.

Il volume deve disporre di spazio sufficiente per contenere i risparmi ottenuti attraverso il rilevamento inline di blocchi di zero. Consultare l'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_see_space_savings_from_deduplication%2C_compression%2C_and_compaction_in_ONTAP_9["Come verificare i risparmi di spazio derivanti da deduplica, compressione e compattazione in ONTAP 9"].

Se sono state attivate sia la deduplica che la compressione dei dati su un volume che si desidera ripristinare, è necessario ripristinare la compressione dei dati prima di ripristinare la deduplica.

.Fasi
. Visualizzare l'avanzamento delle operazioni di efficienza in esecuzione sui volumi:
+
[source, cli]
----
volume efficiency show -fields vserver,volume,progress
----
. Interrompere tutte le operazioni di deduplica attive e in coda:
+
[source, cli]
----
volume efficiency stop -vserver <svm_name> -volume <volume_name> -all
----
. Impostare il livello di privilegio su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
. Eseguire il downgrade dei metadati dell'efficienza di un volume alla versione di destinazione di ONTAP:
+
[source, cli]
----
volume efficiency revert-to -vserver <svm_name> -volume <volume_name> -version <version>
----
+
Nell'esempio seguente vengono ripristinati i metadati di efficienza sul volume vola in ONTAP 9.x

+
[listing]
----
volume efficiency revert-to -vserver vs1 -volume VolA -version 9.x
----
+

NOTE: Il comando revert-to per l'efficienza dei volumi ripristina i volumi presenti nel nodo su cui viene eseguito questo comando. Questo comando non ripristina i volumi tra i nodi.

. Monitorare l'avanzamento del downgrade:
+
[source, cli]
----
volume efficiency show -vserver <svm_name> -op-status Downgrading
----
. Se l'indirizzamento non riesce, visualizzare l'istanza per verificare il motivo dell'errore.
+
[source, cli]
----
volume efficiency show -vserver <svm_name> -volume <volume_name> - instance
----
. Una volta completata l'operazione di revert, tornare al livello di privilegio admin:
+
[source, cli]
----
set -privilege admin
----


Ulteriori informazioni su link:../volumes/index.html["Gestione dello storage logico"].
