---
permalink: revert/task_verifying_storage_health_before_revert.html 
sidebar: sidebar 
keywords: ontap, revert, verify, verifying, storage, health, before, revert, reverting 
summary: 'Prima e dopo l"aggiornamento, il ripristino o il downgrade di un cluster, è necessario verificare lo stato di dischi, aggregati e volumi.' 
---
= Verificare lo stato dello storage prima di eseguire il revert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima e dopo il ripristino o il downgrade di un cluster, è necessario verificare lo stato di dischi, aggregati e volumi.

. Verificare lo stato del disco:
+
[cols="2*"]
|===
| Per verificare la presenza di... | Eseguire questa operazione... 


 a| 
Dischi rotti
 a| 
.. Visualizzare eventuali dischi rotti: `storage disk show -state broken`
.. Rimuovere o sostituire eventuali dischi rotti.




 a| 
Dischi in fase di manutenzione o ricostruzione
 a| 
.. Visualizza i dischi in stato di manutenzione, in sospeso o di ricostruzione: `storage disk show -state maintenance




| in sospeso | ricostruzione` .. Prima di procedere, attendere il completamento dell'operazione di manutenzione o ricostruzione. + 
|===
. Verificare che tutti gli aggregati siano online visualizzando lo stato dello storage fisico e logico, inclusi gli aggregati di storage: `storage aggregate show -state !online`
+
Questo comando visualizza gli aggregati _non_ online. Tutti gli aggregati devono essere online prima e dopo l'esecuzione di una revisione principale.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. Verificare che tutti i volumi siano online visualizzando tutti i volumi _non_ online: `volume show -state !online`
+
Tutti i volumi devono essere online prima e dopo l'esecuzione di una revisione principale.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. Verificare che non vi siano volumi incoerenti: `volume show -is-inconsistent true`
+
Se vengono restituiti volumi incoerenti, è necessario contattare il supporto NetApp prima di procedere.



.Informazioni correlate
link:../disks-aggregates/index.html["Gestione di dischi e aggregati"]
