---
permalink: revert/task_reverting_the_physical_block_sharing_in_split_flexclone_volumes.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, reverse, reversing, physical, block sharing, split, flexclone, volumes 
summary: Se un volume FlexClone è stato diviso dal volume padre, è necessario annullare la condivisione di qualsiasi blocco fisico tra il clone e il volume padre prima di tornare da ONTAP 9.4 o versione successiva a una versione precedente di ONTAP. 
---
= Reverse physical block sharing in volumi FlexClone divisi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se un volume FlexClone è stato diviso dal volume padre, è necessario annullare la condivisione di qualsiasi blocco fisico tra il clone e il volume padre prima di tornare da ONTAP 9.4 o versione successiva a una versione precedente di ONTAP.

Questa attività è applicabile solo ai sistemi AFF quando è stato eseguito il split su uno qualsiasi dei volumi FlexClone.

. Accedere al livello di privilegio avanzato: `set -privilege advanced`
. Identificare i volumi FlexClone divisi con blocchi fisici condivisi: `volume clone sharing-by-split show`
+
[listing]
----
cluster1::> volume clone sharing-by-split show
Node            Vserver   Volume        Aggregate
--------------- --------- ------------- -------------
node1           vs1       vol_clone1    aggr1
node2           vs2       vol_clone2    aggr2
2 entries were displayed.
----
. Annullare la condivisione fisica dei blocchi in tutti i volumi FlexClone divisi nel cluster: `volume clone sharing-by-split undo start-all`
. Verificare che non vi siano volumi FlexClone divisi con blocchi fisici condivisi: `volume clone sharing-by-split show`
+
[listing]
----
cluster1::> volume clone sharing-by-split show
This table is currently empty.
----

