---
permalink: revert/task_download_and_install_ontap_software_image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing 
summary: È necessario prima scaricare il software ONTAP, quindi installarlo. 
---
= Scaricare e installare l'immagine del software ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario prima scaricare il software ONTAP dal sito del supporto NetApp, quindi installarlo.



== Scaricare l'immagine del software

Per eseguire il downgrade o il ripristino da ONTAP 9.4 e versioni successive, è possibile copiare l'immagine del software ONTAP dal sito del supporto NetApp in una cartella locale. Per eseguire il downgrade o il ripristino a ONTAP 9.3 o versioni precedenti, è necessario copiare l'immagine del software ONTAP su un server HTTP o FTP sulla rete.

Tenere presenti le seguenti importanti informazioni:

* Le immagini software sono specifiche dei modelli di piattaforma.
+
È necessario ottenere l'immagine corretta per il cluster. Le immagini software, le informazioni sulla versione del firmware e il firmware più recente per il modello di piattaforma sono disponibili sul sito del supporto NetApp.

* Le immagini software includono la versione più recente del firmware di sistema disponibile al momento del rilascio di una determinata versione di ONTAP.
* Se si esegue il downgrade di un sistema con crittografia dei volumi NetApp da ONTAP 9.5 o versioni successive, è necessario scaricare l'immagine del software ONTAP per i paesi senza restrizioni, che include crittografia dei volumi NetApp.
+
Se si utilizza l'immagine del software ONTAP per i paesi con restrizioni per eseguire il downgrade o il ripristino di un sistema con crittografia dei volumi NetApp, il sistema esegue una panoramica e si perde l'accesso ai volumi.

+
.. Individuare il software ONTAP di destinazione in link:http://mysupport.netapp.com/NOW/cgi-bin/software["Download di software"] Area del NetApp Support Site.
.. Copiare l'immagine del software.
+
*** Per ONTAP 9.3 o versioni precedenti, copiare l'immagine software (ad esempio, 93_q_image.tgz) dal sito del supporto NetApp nella directory sul server HTTP o sul server FTP da cui verrà servita l'immagine.
*** Per ONTAP 9.4 o versioni successive, copiare l'immagine software (ad esempio, 97_q_image.tgz) dal sito di supporto NetApp nella directory sul server HTTP o FTP da cui verrà servita l'immagine o in una cartella locale.








== Installare l'immagine software

È necessario installare l'immagine software di destinazione sui nodi del cluster.

* Se si esegue il downgrade o il ripristino di un sistema con crittografia dei volumi NetApp da ONTAP 9.5 o versioni successive, è necessario aver scaricato l'immagine del software ONTAP per i paesi non soggetti a restrizioni, che includono crittografia dei volumi NetApp.
+
Se si utilizza l'immagine del software ONTAP per i paesi con restrizioni per eseguire il downgrade o il ripristino di un sistema con crittografia dei volumi NetApp, il sistema esegue una panoramica e si perde l'accesso ai volumi.

+
.. Impostare il livello di privilegio su Advanced (avanzato), immettendo *y* quando viene richiesto di continuare: `set -privilege advanced`
+
Il prompt avanzato (`*>`).

.. Installare l'immagine software sui nodi.
+
Questo comando scarica e installa contemporaneamente l'immagine software su tutti i nodi. Per scaricare e installare l'immagine su ogni nodo, non specificare il parametro -background.

+
*** Se si esegue il downgrade o si ripristina una configurazione non MetroCluster o una configurazione MetroCluster a due nodi:``system node image update -node * -package location -replace-package true -setdefault true -background true``
+
Questo comando utilizza una query estesa per modificare l'immagine software di destinazione, installata come immagine alternativa, come immagine predefinita per il nodo.

*** Se si esegue il dowgrade o il ripristino di una configurazione MetroCluster a quattro o otto nodi, è necessario eseguire il seguente comando su entrambi i cluster: `system node image update -node * -package location -replace-package true true -background true -setdefault false`
+
Questo comando utilizza una query estesa per modificare l'immagine software di destinazione, che viene installata come immagine alternativa su ciascun nodo.



.. Invio `y` per continuare quando richiesto.
.. Verificare che l'immagine software sia stata scaricata e installata su ciascun nodo: `system node image show-update-progress -node *`
+
Questo comando visualizza lo stato corrente del download e dell'installazione dell'immagine software. Continuare ad eseguire questo comando fino a quando tutti i nodi non riportano uno stato di esecuzione di Exited e uno stato di uscita di Success.

+
Il comando di aggiornamento dell'immagine del nodo di sistema può non riuscire e visualizzare messaggi di errore o di avviso. Dopo aver risolto eventuali errori o avvisi, è possibile eseguire nuovamente il comando.

+
Questo esempio mostra un cluster a due nodi in cui l'immagine software viene scaricata e installata correttamente su entrambi i nodi:

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----



