---
permalink: smb-admin/add-remove-replace-trusted-domains-preferred-lists-task.html 
sidebar: sidebar 
keywords: add, remove, trust, domain, prefer, cifs, server, modify, list, configure, bidirectional, multidomain, name, mapping, search, add remove or replace trusted domains in preferred trusted domain list, replace 
summary: 'È possibile aggiungere o rimuovere domini attendibili dall"elenco dei domini attendibili preferiti per il server CIFS oppure modificare l"elenco corrente. Se si configura un elenco di domini trusted preferito, questo elenco viene utilizzato al posto dei domini trusted bidirezionali rilevati durante le ricerche di mappatura dei nomi di più domini.' 
---
= Aggiungere, rimuovere o sostituire domini SMB ONTAP attendibili negli elenchi preferiti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere o rimuovere domini attendibili dall'elenco dei domini attendibili preferiti per il server SMB oppure modificare l'elenco corrente. Se si configura un elenco di domini trusted preferito, questo elenco viene utilizzato al posto dei domini trusted bidirezionali rilevati durante le ricerche di mappatura dei nomi di più domini.

.A proposito di questa attività
* Se si aggiungono domini attendibili a un elenco esistente, il nuovo elenco viene Unito all'elenco esistente con le nuove voci alla fine I domini attendibili vengono ricercati nell'ordine in cui vengono visualizzati nell'elenco dei domini attendibili.
* Se si rimuovono domini attendibili dall'elenco esistente e non si specifica un elenco, l'intero elenco di domini attendibili per la macchina virtuale di storage (SVM) specificata viene rimosso.
* Se si modifica l'elenco esistente di domini attendibili, il nuovo elenco sovrascrive quello esistente.


[NOTE]
====
Nell'elenco Preferred trusted domain (dominio trusted preferito), inserire solo domini trusted bidirezionalmente attendibili. Anche se è possibile inserire domini trust in uscita o in entrata nell'elenco dei domini preferiti, questi non vengono utilizzati durante le ricerche di mappatura dei nomi di più domini. ONTAP ignora la voce relativa al dominio unidirezionale e passa al successivo dominio attendibile bidirezionale nell'elenco.

====
.Fase
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera eseguire le seguenti operazioni con l'elenco dei domini attendibili preferiti... | Utilizzare il comando... 


 a| 
Aggiungere domini attendibili all'elenco
 a| 
`+vserver cifs domain name-mapping-search add -vserver _vserver_name_ -trusted-domains FQDN, ...+`



 a| 
Rimuovere i domini attendibili dall'elenco
 a| 
`+vserver cifs domain name-mapping-search remove -vserver _vserver_name_ [-trusted-domains FQDN, ...]+`



 a| 
Modificare l'elenco esistente
 a| 
`+vserver cifs domain name-mapping-search modify -vserver _vserver_name_ -trusted-domains FQDN, ...+`

|===


.Esempi
Il seguente comando aggiunge due domini attendibili (cifs1.example.com e cifs2.example.com) all'elenco di domini attendibili preferito utilizzato da SVM vs1:

[listing]
----
cluster1::> vserver cifs domain name-mapping-search add -vserver vs1 -trusted-domains cifs1.example.com, cifs2.example.com
----
Il seguente comando rimuove due domini attendibili dall'elenco utilizzato da SVM vs1:

[listing]
----
cluster1::> vserver cifs domain name-mapping-search remove -vserver vs1 -trusted-domains cifs1.example.com, cifs2.example.com
----
Il seguente comando modifica l'elenco di domini attendibili utilizzato da SVM vs1. Il nuovo elenco sostituisce quello originale:

[listing]
----
cluster1::> vserver cifs domain name-mapping-search modify -vserver vs1 -trusted-domains cifs3.example.com
----
.Informazioni correlate
xref:display-preferred-trusted-domain-list-task.adoc[Visualizzare le informazioni relative all'elenco di domini attendibili preferiti]
