---
permalink: smb-admin/apply-security-policies-file-task.html 
sidebar: sidebar 
keywords: apply, file, security, policy, svm, creating, create, folder, apply security policies 
summary: 'L"applicazione di una policy di sicurezza dei file alle SVM è l"ultimo passo nella creazione e nell"applicazione di ACL NTFS a file o cartelle.' 
---
= Applicare le policy di sicurezza ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'applicazione di una policy di sicurezza dei file alle SVM è l'ultimo passo nella creazione e nell'applicazione di ACL NTFS a file o cartelle.

.A proposito di questa attività
È possibile applicare le impostazioni di protezione definite nel criterio di protezione ai file e alle cartelle NTFS che risiedono nei volumi FlexVol (NTFS o stile di protezione misto).


NOTE: Quando vengono applicati un criterio di audit e i SACL associati, tutti i DACL esistenti vengono sovrascritti. Quando vengono applicati un criterio di protezione e i DACL associati, tutti i DACL esistenti vengono sovrascritti. Prima di crearne e applicarne di nuovi, è necessario rivedere le policy di sicurezza esistenti.

.Fase
. Applicare una policy di sicurezza: `vserver security file-directory apply -vserver vserver_name ‑policy-name policy_name`
+
`vserver security file-directory apply -vserver vs1 -policy-name policy1`

+
Il processo di applicazione della policy viene pianificato e viene restituito l'ID lavoro.

+
[listing]
----
[Job 53322]Job is queued: Fsecurity Apply. Use the "Job show 53322 –id 53322" command to view the status of the operation
----

