---
permalink: smb-admin/automatic-node-referrals-client-concept.html 
sidebar: sidebar 
keywords: referral, client, perspective, windows, dfstuil, exe, utility, monitor, client-side, smb, automatic, how to monitor client-side smb automatic node referral information using a windows client 
summary: 'Per determinare quali riferimenti vengono fatti dal punto di vista del client, è possibile utilizzare l"utilità Windows dfsutil.exe.' 
---
= Monitorare le informazioni di riferimento del nodo automatico SMB lato client utilizzando un client Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per determinare quali riferimenti vengono fatti dal punto di vista del client, è possibile utilizzare Windows `dfsutil.exe` utility.

Il kit Remote Server Administration Tools (RSAT) disponibile con Windows 7 e i client successivi contiene `dfsutil.exe` utility. Utilizzando questa utility, è possibile visualizzare informazioni sul contenuto della cache di riferimento e le informazioni relative a ciascun riferimento attualmente utilizzato dal client. È inoltre possibile utilizzare l'utility per cancellare la cache di riferimento del client. Per ulteriori informazioni, consultare la Microsoft TechNet Library.

.Informazioni correlate
http://technet.microsoft.com/en-us/library/["Microsoft TechNet Library: technet.microsoft.com/en-us/library/"]
