---
permalink: smb-admin/branchcache-recommendations-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, recommendation, mind, smb, enable, caching, cache, branchcache recommendations 
summary: Prima di configurare BranchCache, è necessario tenere a mente alcuni consigli quando si decide quali condivisioni SMB si desidera attivare il caching BranchCache. 
---
= Scopri le raccomandazioni di ONTAP SMB BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di configurare BranchCache, è necessario tenere a mente alcuni consigli quando si decide quali condivisioni SMB si desidera attivare il caching BranchCache.

Quando decidi quale modalità operativa utilizzare e su quali condivisioni SMB abilitare BranchCache, devi tenere a mente i seguenti consigli:

* I vantaggi di BranchCache si riducono quando i dati da memorizzare nella cache in remoto cambiano frequentemente.
* I servizi BranchCache sono vantaggiosi per le condivisioni contenenti contenuto di file che viene riutilizzato da più client della sede remota o da contenuto di file a cui un singolo utente remoto accede ripetutamente.
* Prendi in considerazione l'abilitazione del caching per contenuti di sola lettura, come i dati in snapshot e destinazioni SnapMirror.

