---
permalink: smb-admin/break-locks-task.html 
sidebar: sidebar 
keywords: file, lock, prevent, client, access, display, information, held, break, scenario, debug, application, break locks 
summary: 'Quando i blocchi di file impediscono l"accesso dei client ai file, è possibile visualizzare le informazioni sui blocchi attualmente in attesa e quindi interrompere blocchi specifici. Esempi di scenari in cui potrebbe essere necessario interrompere i blocchi includono il debug delle applicazioni.' 
---
= Blocchi di interruzione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando i blocchi di file impediscono l'accesso dei client ai file, è possibile visualizzare le informazioni sui blocchi attualmente in attesa e quindi interrompere blocchi specifici. Esempi di scenari in cui potrebbe essere necessario interrompere i blocchi includono il debug delle applicazioni.

.A proposito di questa attività
Il `vserver locks break` il comando è disponibile solo a un livello di privilegio avanzato e superiore. La pagina man del comando contiene informazioni dettagliate.

.Fasi
. Per trovare le informazioni necessarie per interrompere un blocco, utilizzare `vserver locks show` comando.
+
La pagina man del comando contiene informazioni dettagliate.

. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera interrompere un blocco specificando... | Immettere il comando... 


 a| 
Il nome SVM, il nome del volume, il nome LIF e il percorso del file
 a| 
`vserver locks break -vserver vserver_name -volume volume_name -path path -lif lif`



 a| 
L'ID blocco
 a| 
`vserver locks break -lockid UUID`

|===
. Tornare al livello di privilegio admin: `set -privilege admin`

