---
permalink: smb-admin/choosing-hash-store-location-concept.html 
sidebar: sidebar 
keywords: configuring, configure, branchcache, store, hash, size, guideline, cids-enabled, svm, guidelines for choosing the hash store location 
summary: 'Quando configuri BranchCache, scegli dove memorizzare gli hash e le dimensioni dell"archivio hash. La comprensione delle linee guida per la scelta della posizione e delle dimensioni dell"archivio hash può aiutarti a pianificare la configurazione di BranchCache su una SVM abilitata per CIFS.' 
---
= Scopri come scegliere la posizione dell'archivio hash ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando configuri BranchCache, scegli dove memorizzare gli hash e le dimensioni dell'archivio hash. La comprensione delle linee guida per la scelta della posizione e delle dimensioni dell'archivio hash può aiutarti a pianificare la configurazione di BranchCache su una SVM abilitata per CIFS.

* È necessario individuare l'archivio hash su un volume in cui sono consentiti gli aggiornamenti atime.
+
Il tempo di accesso a un file hash viene utilizzato per conservare i file ad accesso frequente nell'archivio hash. Se gli aggiornamenti aTime sono disattivati, viene utilizzata l'ora di creazione. È preferibile utilizzare atime per tenere traccia dei file utilizzati di frequente.

* Non è possibile memorizzare gli hash su file system di sola lettura, ad esempio destinazioni SnapMirror e volumi SnapLock.
* Se viene raggiunta la dimensione massima dell'archivio hash, gli hash più vecchi vengono eliminati per fare spazio ai nuovi hash.
+
È possibile aumentare le dimensioni massime dell'archivio hash per ridurre la quantità di hash scaricati dalla cache.

* Se il volume su cui si memorizzano gli hash non è disponibile o è pieno, o se si verifica un problema di comunicazione all'interno del cluster in cui il servizio BranchCache non riesce a recuperare le informazioni sugli hash, i servizi BranchCache non sono disponibili.
+
Il volume potrebbe non essere disponibile perché non è in linea o perché l'amministratore dello storage ha specificato una nuova posizione per l'archivio hash.

+
Questo non causa problemi di accesso al file. Se l'accesso all'archivio hash viene impedito, ONTAP restituisce un errore definito da Microsoft al client, che fa in modo che il client richieda il file utilizzando la normale richiesta di lettura SMB.



.Informazioni correlate
xref:configure-branchcache-task.adoc[Configurare BranchCache sul server SMB]

xref:modify-branchcache-config-task.html[Modificare la configurazione di BranchCache]
