---
permalink: smb-admin/client-performance-traditional-lease-oplocks-concept.html 
sidebar: sidebar 
keywords: traditional, oplocks, opportunistic, locks, lease, smb, client, client-side, read-ahead, file-sharing, write-behind, information, access, reducing, reduce, network, traffic, improve client performance with traditional and lease oplocks 
summary: 'Gli oplock tradizionali (blocchi opportunistici) e gli oplock di lease consentono a un client SMB in alcuni scenari di condivisione file di eseguire il caching lato client delle informazioni di Read-ahead, write-behind e lock. Un client può quindi leggere o scrivere su un file senza ricordare regolarmente al server che ha bisogno di accedere al file in questione. Ciò migliora le performance riducendo il traffico di rete.' 
---
= Scoprite come migliorare le prestazioni dei client ONTAP per PMI con contratti di leasing e tradizionali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli oplock tradizionali (blocchi opportunistici) e gli oplock di lease consentono a un client SMB in alcuni scenari di condivisione file di eseguire il caching lato client delle informazioni di Read-ahead, write-behind e lock. Un client può quindi leggere o scrivere su un file senza ricordare regolarmente al server che ha bisogno di accedere al file in questione. Ciò migliora le performance riducendo il traffico di rete.

Gli oplock di leasing sono una forma avanzata di oplock disponibili con il protocollo SMB 2.1 e versioni successive. Gli oplock del lease consentono a un client di ottenere e preservare lo stato di caching del client in più SMB aperti che hanno origine da sé.

Gli oplock possono essere controllati in due modi:

* Da una proprietà di condivisione, utilizzando `vserver cifs share create` quando viene creata la condivisione, oppure il `vserver share properties` comando dopo la creazione.
* Da una proprietà qtree, utilizzando `volume qtree create` quando viene creato il qtree, oppure il `volume qtree oplock` comandi dopo la creazione.

