---
permalink: smb-admin/command-options-limit-client-resource-concept.html 
sidebar: sidebar 
keywords: option, vserver, cifs, modify, command, enable, control, resource, consumption, windows, client, bound, notify, request, command options to limit excessive windows client resource consumption 
summary: Le opzioni del comando vserver cifs Modify consentono di controllare il consumo di risorse per i client Windows. Questo può essere utile se i client non rientrano nei limiti normali di consumo delle risorse, ad esempio se sono presenti un numero insolitamente elevato di file aperti, sessioni aperte o richieste di notifica delle modifiche. 
---
= Opzioni di comando per limitare il consumo eccessivo di risorse client Windows in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Opzioni di `vserver cifs options modify` Il comando consente di controllare il consumo di risorse per i client Windows. Questo può essere utile se i client non rientrano nei limiti normali di consumo delle risorse, ad esempio se sono presenti un numero insolitamente elevato di file aperti, sessioni aperte o richieste di notifica delle modifiche.

Le seguenti opzioni di `vserver cifs options modify` Sono stati aggiunti comandi per controllare il consumo di risorse del client Windows. Se si supera il valore massimo di una di queste opzioni, la richiesta viene rifiutata e viene inviato un messaggio EMS. Viene inoltre inviato un messaggio di avviso EMS quando viene raggiunto il 80% del limite configurato per queste opzioni.

* `-max-opens-same-file-per-tree`
+
Numero massimo di apertura sullo stesso file per albero CIFS

* `-max-same-user-sessions-per-connection`
+
Numero massimo di sessioni aperte dallo stesso utente per connessione

* `-max-same-tree-connect-per-session`
+
Numero massimo di connessioni ad albero sulla stessa condivisione per sessione

* `-max-watches-set-per-tree`
+
Numero massimo di orologi (noto anche come _change notifes_) stabiliti per albero



Ulteriori informazioni su `vserver cifs options modify` nella link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-options-modify.html["Riferimento al comando ONTAP"^].

A partire da ONTAP 9.4, i server SMB versione 2 o successiva possono limitare il numero di richieste in sospeso (_SMB credits_) che il client può inviare al server con una connessione SMB. La gestione dei crediti SMB viene avviata dal client e controllata dal server.

Il numero massimo di richieste in sospeso che possono essere concesse su una connessione SMB è controllato da `-max-credits` opzione. Il valore predefinito per questa opzione è 128.
