---
permalink: smb-admin/commands-manage-ntfs-security-descriptors-reference.html 
sidebar: sidebar 
keywords: ontap, comand, managing, manage, security, descriptor, create, modify, delete, display, information, commands for managing ntfs security descriptors 
summary: Esistono comandi ONTAP specifici per la gestione dei descrittori di protezione. È possibile creare, modificare, eliminare e visualizzare informazioni sui descrittori di protezione. 
---
= Comandi per la gestione dei descrittori di sicurezza NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono comandi ONTAP specifici per la gestione dei descrittori di protezione. È possibile creare, modificare, eliminare e visualizzare informazioni sui descrittori di protezione.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare descrittori di protezione NTFS
 a| 
`vserver security file-directory ntfs create`



 a| 
Modificare i descrittori di protezione NTFS esistenti
 a| 
`vserver security file-directory ntfs modify`



 a| 
Visualizza informazioni sui descrittori di protezione NTFS esistenti
 a| 
`vserver security file-directory ntfs show`



 a| 
Eliminare i descrittori di protezione NTFS
 a| 
`vserver security file-directory ntfs delete`

|===
Vedere le pagine man per `vserver security file-directory ntfs` per ulteriori informazioni.
