---
permalink: smb-admin/commands-manage-security-policy-jobs-reference.html 
sidebar: sidebar 
keywords: ontap, command, pausing, pause, resuming, resume, stop, display, information, security, policy, job, commands for managing security policy jobs 
summary: Sono disponibili comandi ONTAP per mettere in pausa, riprendere, arrestare e visualizzare informazioni sui processi relativi ai criteri di protezione. 
---
= Comandi per la gestione dei processi dei criteri di protezione in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili comandi ONTAP per mettere in pausa, riprendere, arrestare e visualizzare informazioni sui processi relativi ai criteri di protezione.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Sospendere i processi di policy di sicurezza
 a| 
`vserver security file-directory job pause ‑vserver vserver_name -id integer`



 a| 
Riprendere i processi di policy di sicurezza
 a| 
`vserver security file-directory job resume ‑vserver vserver_name -id integer`



 a| 
Visualizza informazioni sui processi di policy di sicurezza
 a| 
`vserver security file-directory job show ‑vserver vserver_name` È possibile determinare l'ID lavoro di un lavoro utilizzando questo comando.



 a| 
Arrestare i processi di policy di sicurezza
 a| 
`vserver security file-directory job stop ‑vserver vserver_name -id integer`

|===
Ulteriori informazioni su `vserver security file-directory job` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+job["Riferimento al comando ONTAP"^].
