---
permalink: smb-admin/commands-manage-name-mappings-reference.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, name, mapping 
summary: Esistono comandi ONTAP specifici per la gestione delle mappature dei nomi. 
---
= Comandi per la gestione delle mappature dei nomi in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono comandi ONTAP specifici per la gestione delle mappature dei nomi.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare una mappatura dei nomi
 a| 
`vserver name-mapping create`



 a| 
Inserire una mappatura dei nomi in una posizione specifica
 a| 
`vserver name-mapping insert`



 a| 
Visualizza mappature dei nomi
 a| 
`vserver name-mapping show`



 a| 
Scambiare la posizione di due mappature dei nomi

[NOTE]
====
Lo swap non è consentito quando la mappatura dei nomi è configurata con una voce di qualificatore ip.

==== a| 
`vserver name-mapping swap`



 a| 
Modificare una mappatura dei nomi
 a| 
`vserver name-mapping modify`



 a| 
Eliminare una mappatura dei nomi
 a| 
`vserver name-mapping delete`



 a| 
Convalidare la corretta mappatura dei nomi
 a| 
`vserver security file-directory show-effective-permissions -vserver vs1 -win-user-name user1 -path / -share-name sh1`

|===
Ulteriori informazioni su `vserver name-mapping` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+name-mapping["Riferimento al comando ONTAP"^].
