---
permalink: smb-admin/commands-manage-servers-reference.html 
sidebar: sidebar 
keywords: command, creating, create, display, modify, stop, start, deleting, delete 
summary: 'È necessario conoscere i comandi per la creazione, la visualizzazione, la modifica, l"arresto, l"avvio, Ed eliminazione dei server SMB. Sono inoltre disponibili comandi per reimpostare e riscoprire i server, modificare o reimpostare le password degli account dei computer, pianificare le modifiche per le password degli account dei computer e aggiungere o rimuovere alias NetBIOS.' 
---
= Comandi ONTAP per la gestione dei server SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere i comandi per la creazione, la visualizzazione, la modifica, l'arresto, l'avvio, Ed eliminazione dei server SMB. Sono inoltre disponibili comandi per reimpostare e riscoprire i server, modificare o reimpostare le password degli account dei computer, pianificare le modifiche per le password degli account dei computer e aggiungere o rimuovere alias NetBIOS.

|===


| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare un server SMB
 a| 
`vserver cifs create`



 a| 
Visualizzare le informazioni su un server SMB
 a| 
`vserver cifs show`



 a| 
Modificare un server SMB
 a| 
`vserver cifs modify`



 a| 
Spostare un server SMB in un altro dominio
 a| 
`vserver cifs modify`



 a| 
Arrestare un server SMB
 a| 
`vserver cifs stop`



 a| 
Avviare un server SMB
 a| 
`vserver cifs start`



 a| 
Eliminare un server SMB
 a| 
`vserver cifs delete`



 a| 
Reimpostare e riscoprire i server per il server SMB
 a| 
`vserver cifs domain discovered-servers reset-servers`



 a| 
Modificare la password dell'account del computer del server SMB
 a| 
`vserver cifs domain password change`



 a| 
Reimpostare la password dell'account del computer del server SMB
 a| 
`vserver cifs domain password change`



 a| 
Pianificare le modifiche automatiche delle password per l'account del computer del server SMB
 a| 
`vserver cifs domain password schedule modify`



 a| 
Aggiungere alias NetBIOS per il server SMB
 a| 
`vserver cifs add-netbios-aliases`



 a| 
Rimuovere gli alias NetBIOS per il server SMB
 a| 
`vserver cifs remove-netbios-aliases`

|===
Ulteriori informazioni su `vserver cifs` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["Riferimento al comando ONTAP"^].

.Informazioni correlate
link:local-users-groups-when-deleting-servers-concept.html["Cosa accade agli utenti e ai gruppi locali quando si eliminano i server SMB"]
