---
permalink: smb-admin/commands-manage-ntfs-sacl-reference.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, managing, sacl, access, control, entries, aces, ntfs, exist, modify, deleting, delete, display, commands for managing ntfs sacl access control entries 
summary: 'Esistono comandi ONTAP specifici per la gestione delle voci di controllo degli accessi SACL (ACE). È possibile aggiungere ACE ai SACL NTFS in qualsiasi momento. È inoltre possibile gestire i SACL NTFS esistenti modificando, eliminando e visualizzando le informazioni relative agli ACE nei SACL.' 
---
= Comandi per la gestione delle voci di controllo degli accessi NTFS SACL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono comandi ONTAP specifici per la gestione delle voci di controllo degli accessi SACL (ACE). È possibile aggiungere ACE ai SACL NTFS in qualsiasi momento. È inoltre possibile gestire i SACL NTFS esistenti modificando, eliminando e visualizzando le informazioni relative agli ACE nei SACL.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare ACE e aggiungerli ai SACL NTFS
 a| 
`vserver security file-directory ntfs sacl add`



 a| 
Modificare gli ACE esistenti nei SACL NTFS
 a| 
`vserver security file-directory ntfs sacl modify`



 a| 
Visualizza le informazioni sugli ACE esistenti nei SACL NTFS
 a| 
`vserver security file-directory ntfs sacl show`



 a| 
Rimuovere gli ACE esistenti dai SACL NTFS
 a| 
`vserver security file-directory ntfs sacl remove`

|===
Vedere le pagine man per `vserver security file-directory ntfs sacl` per ulteriori informazioni.
