---
permalink: smb-admin/configure-folder-redirection-task.html 
sidebar: sidebar 
keywords: configure, folder, redirection, windows, properties, method, assistance, svm, administrator, configure folder redirection 
summary: 'È possibile configurare il reindirizzamento delle cartelle utilizzando la finestra Proprietà di Windows. Il vantaggio di utilizzare questo metodo consiste nel fatto che l"utente Windows può configurare il reindirizzamento delle cartelle senza l"assistenza dell"amministratore di SVM.' 
---
= Configurare il reindirizzamento delle cartelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare il reindirizzamento delle cartelle utilizzando la finestra Proprietà di Windows. Il vantaggio di utilizzare questo metodo consiste nel fatto che l'utente Windows può configurare il reindirizzamento delle cartelle senza l'assistenza dell'amministratore di SVM.

.Fasi
. In Esplora risorse, fare clic con il pulsante destro del mouse sulla cartella che si desidera reindirizzare a una condivisione di rete.
. Fare clic su *Proprietà*.
+
Vengono visualizzate le proprietà della condivisione selezionata.

. Nella scheda *scelta rapida*, fare clic su *destinazione* e specificare il percorso di rete in cui si desidera reindirizzare la cartella selezionata.
+
Ad esempio, se si desidera reindirizzare una cartella a `data` in una home directory mappata a. `Q:\`, specificare `Q:\data` come destinazione.

. Fare clic su *OK*.
+
Per ulteriori informazioni sulla configurazione delle cartelle offline, consultare la Microsoft TechNet Library.



.Informazioni correlate
http://technet.microsoft.com/en-us/library/["Microsoft TechNet Library: technet.microsoft.com/en-us/library/"]
