---
permalink: smb-admin/configure-access-restrictions-anonymous-users-task.html 
sidebar: sidebar 
keywords: anonymous, unauthenticated, user, information, network, cifs, server, option, configure, access, restriction, user, configure access restrictions for anonymous users 
summary: 'Per impostazione predefinita, un utente anonimo e non autenticato (noto anche come utente nullo) può accedere a determinate informazioni sulla rete. È possibile utilizzare un"opzione del server SMB per configurare le restrizioni di accesso per l"utente anonimo.' 
---
= Configurare le restrizioni di accesso per gli utenti anonimi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostazione predefinita, un utente anonimo e non autenticato (noto anche come _null user_) può accedere a determinate informazioni sulla rete. È possibile utilizzare un'opzione del server SMB per configurare le restrizioni di accesso per l'utente anonimo.

.A proposito di questa attività
Il `-restrict-anonymous` L'opzione del server SMB corrisponde a. `RestrictAnonymous` Voce di registro in Windows.

Gli utenti anonimi possono elencare o enumerare determinati tipi di informazioni di sistema dagli host Windows sulla rete, inclusi i nomi e i dettagli degli utenti, i criteri degli account e i nomi di condivisione. È possibile controllare l'accesso per l'utente anonimo specificando una delle tre impostazioni di restrizione dell'accesso:

|===
| Valore | Descrizione 


 a| 
`no-restriction` (impostazione predefinita)
 a| 
Non specifica restrizioni di accesso per utenti anonimi.



 a| 
`no-enumeration`
 a| 
Specifica che solo l'enumerazione è limitata per gli utenti anonimi.



 a| 
`no-access`
 a| 
Specifica che l'accesso è limitato agli utenti anonimi.

|===
.Fasi
. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Configurare l'impostazione limita anonimo: `vserver cifs options modify -vserver _vserver_name_ -restrict-anonymous {no-restriction|no-enumeration|no-access}`
. Verificare che l'opzione sia impostata sul valore desiderato: `vserver cifs options show -vserver _vserver_name_`
. Tornare al livello di privilegio admin: `set -privilege admin`


.Informazioni correlate
xref:server-options-reference.adoc[Opzioni server SMB disponibili]
