---
permalink: smb-admin/configure-security-styles-qtrees-task.html 
sidebar: sidebar 
keywords: configure, qtree, volume, security, style, permission, data, configure security styles on qtrees 
summary: Lo stile di protezione del volume qtree viene configurato per determinare il tipo di autorizzazioni utilizzate per i dati su qtree. 
---
= Configurare gli stili di sicurezza SMB sui qtree ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo stile di protezione del volume qtree viene configurato per determinare il tipo di autorizzazioni utilizzate per i dati su qtree.

.Fasi
. Eseguire una delle seguenti operazioni:
+
|===
| Se il qtree... | Utilizzare il comando... 


 a| 
Non esiste ancora
 a| 
`volume qtree create` e includono `-security-style` parametro per specificare lo stile di sicurezza.



 a| 
Esiste già
 a| 
`volume qtree modify` e includono `-security-style` parametro per specificare lo stile di sicurezza.

|===
+
Le opzioni possibili per lo stile di sicurezza qtree sono: `unix`, `ntfs`, o. `mixed`.

+
Se non si specifica uno stile di protezione durante la creazione di un qtree, lo stile di protezione predefinito è `mixed`.

+
Per ulteriori informazioni su `volume qtree create` oppure `volume qtree modify` comandi, vedere link:../volumes/index.html["Gestione dello storage logico"].

. Per visualizzare la configurazione, incluso lo stile di sicurezza del qtree creato, immettere il seguente comando: `volume qtree show -qtree qtree_name -instance`

