---
permalink: smb-admin/configure-default-user-task.html 
sidebar: sidebar 
keywords: configure, default, user, map, fail, authentication, non-mapped, fail, alternative, configure the default user 
summary: 'È possibile configurare un utente predefinito da utilizzare se tutti gli altri tentativi di mappatura non riescono per un utente o se non si desidera mappare singoli utenti tra UNIX e Windows. In alternativa, se si desidera che l"autenticazione degli utenti non mappati non venga eseguita correttamente, non è necessario configurare un utente predefinito.' 
---
= Configurare l'utente predefinito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare un utente predefinito da utilizzare se tutti gli altri tentativi di mappatura non riescono per un utente o se non si desidera mappare singoli utenti tra UNIX e Windows. In alternativa, se si desidera che l'autenticazione degli utenti non mappati non venga eseguita correttamente, non è necessario configurare un utente predefinito.

.A proposito di questa attività
Per l'autenticazione CIFS, se non si desidera associare ciascun utente Windows a un singolo utente UNIX, è possibile specificare un utente UNIX predefinito.

Per l'autenticazione NFS, se non si desidera associare ciascun utente UNIX a un singolo utente Windows, è possibile specificare un utente Windows predefinito.

.Fasi
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera... | Immettere il seguente comando... 


 a| 
Configurare l'utente UNIX predefinito
 a| 
`vserver cifs options modify -default-unix-user _user_name_`



 a| 
Configurare l'utente Windows predefinito
 a| 
`vserver nfs modify -default-win-user _user_name_`

|===

