---
permalink: smb-admin/configure-branchcache-enabled-shares-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, smb server, office, enable, smb, share, content, client, configure branchache-enabled smb shares 
summary: Dopo aver configurato BranchCache sul server SMB e nella filiale, è possibile attivare BranchCache sulle condivisioni SMB che contengono contenuti che si desidera consentire ai client delle filiali di memorizzare nella cache. 
---
= Scopri come configurare le condivisioni SMB ONTAP abilitate per BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato BranchCache sul server SMB e nella filiale, è possibile attivare BranchCache sulle condivisioni SMB che contengono contenuti che si desidera consentire ai client delle filiali di memorizzare nella cache.

Il caching BranchCache può essere attivato su tutte le condivisioni SMB sul server SMB o su base share-by-share.

* Se abiliti BranchCache su base share-by-share, puoi abilitare BranchCache durante la creazione della condivisione o modificando le condivisioni esistenti.
+
Se abiliti il caching su una condivisione SMB esistente, ONTAP inizia a calcolare gli hash e a inviare metadati ai client che richiedono contenuti non appena abiliti BranchCache su quella condivisione.

* Tutti i client che dispongono di una connessione SMB esistente a una condivisione non ricevono il supporto BranchCache se BranchCache viene successivamente abilitato su tale condivisione.
+
ONTAP annuncia il supporto di BranchCache per una condivisione al momento della configurazione della sessione SMB. I client che hanno già stabilito sessioni quando BranchCache è abilitato devono disconnettersi e riconnettersi per utilizzare il contenuto memorizzato nella cache per questa condivisione.



[NOTE]
====
Se BranchCache su una condivisione SMB viene successivamente disattivato, ONTAP interrompe l'invio dei metadati al client richiedente. Un client che necessita di dati lo recupera direttamente dal server di contenuti (server SMB).

====