---
permalink: smb-admin/configure-apply-audit-policies-ntfs-files-folders-task.html 
sidebar: sidebar 
keywords: perform, apply, policies, policy, ntfs, file, folder, ontap, cli, security, descriptor, sacl, descriptor, create, storage, virtual, machine, svm, configure and apply audit policies to ntfs files and folders using the cli 
summary: 'È necessario eseguire diversi passaggi per applicare i criteri di controllo a file e cartelle NTFS quando si utilizza l"interfaccia utente di ONTAP. Innanzitutto, si crea un descrittore di protezione NTFS e si aggiungono SACL al descrittore di protezione. Quindi, creare una policy di sicurezza e aggiungere attività di policy. Quindi, applicare il criterio di protezione a una macchina virtuale di storage (SVM).' 
---
= Configurare e applicare i criteri di controllo ai file e alle cartelle NTFS utilizzando la panoramica CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario eseguire diversi passaggi per applicare i criteri di controllo a file e cartelle NTFS quando si utilizza l'interfaccia utente di ONTAP. Innanzitutto, si crea un descrittore di protezione NTFS e si aggiungono SACL al descrittore di protezione. Quindi, creare una policy di sicurezza e aggiungere attività di policy. Quindi, applicare il criterio di protezione a una macchina virtuale di storage (SVM).

.A proposito di questa attività
Dopo aver applicato il criterio di protezione, è possibile monitorare il processo di criteri di protezione e verificare le impostazioni per il criterio di controllo applicato.


NOTE: Quando vengono applicati un criterio di audit e i SACL associati, tutti i DACL esistenti vengono sovrascritti. Prima di crearne e applicarne di nuovi, è necessario rivedere le policy di sicurezza esistenti.

.Informazioni correlate
xref:secure-file-access-storage-level-access-guard-concept.adoc[Protezione dell'accesso ai file mediante Storage-Level Access Guard]

xref:limits-when-cli-set-file-folder-security-concept.adoc[Limiti di utilizzo della CLI per impostare la sicurezza di file e cartelle]

xref:security-descriptors-apply-file-folder-security-concept.adoc[Come vengono utilizzati i descrittori di protezione per applicare la sicurezza di file e cartelle]

link:../nas-audit/index.html["Controllo SMB e NFS e tracciamento della sicurezza"]

xref:create-ntfs-security-descriptor-file-task.adoc[Configurare e applicare la protezione dei file su file e cartelle NTFS utilizzando l'interfaccia CLI]
