---
permalink: smb-admin/configure-grant-unix-group-permission-users-task.html 
sidebar: sidebar 
keywords: configure, grant, group, permission, access, file, directories, directory, incoming, cifs, ownder, configure the grant unix group permission to smb users 
summary: 'È possibile configurare questa opzione in modo da concedere ai gruppi le autorizzazioni di accesso ai file o alle directory anche se l"utente SMB in entrata non è il proprietario del file.' 
---
= Configurare l'autorizzazione Grant UNIX group per gli utenti SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare questa opzione in modo da concedere ai gruppi le autorizzazioni di accesso ai file o alle directory anche se l'utente SMB in entrata non è il proprietario del file.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Configurare l'autorizzazione Grant UNIX group come appropriato:
+
|===
| Se lo si desidera | Immettere il comando 


 a| 
Abilitare l'accesso ai file o alle directory per ottenere le autorizzazioni di gruppo anche se l'utente non è il proprietario del file
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others true`



 a| 
Disattivare l'accesso ai file o alle directory per ottenere le autorizzazioni di gruppo anche se l'utente non è il proprietario del file
 a| 
`vserver cifs options modify –grant-unix-group-perms-to-others false`

|===
. Verificare che l'opzione sia impostata sul valore desiderato: `vserver cifs options show –fields grant-unix-group-perms-to-others`
. Tornare al livello di privilegio admin: `set -privilege admin`

