---
permalink: smb-admin/configure-offline-files-computer-management-mmc-task.html 
sidebar: sidebar 
keywords: permit, user, cache, file, local, offline, configure, computer management, mmc, microsoft, management, console, configure offline files support on smb shares by using the computer management mmc 
summary: 'Se si desidera consentire agli utenti di memorizzare i file nella cache locale per l"utilizzo offline, è possibile configurare il supporto dei file offline utilizzando la console MMC Gestione computer (Microsoft Management Console).' 
---
= Configurare il supporto dei file offline sulle condivisioni SMB ONTAP utilizzando la MMC Gestione computer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera consentire agli utenti di memorizzare i file nella cache locale per l'utilizzo offline, è possibile configurare il supporto dei file offline utilizzando la console MMC Gestione computer (Microsoft Management Console).

.Fasi
. Per aprire MMC sul server Windows, in Esplora risorse fare clic con il pulsante destro del mouse sull'icona del computer locale, quindi selezionare *Gestisci*.
. Nel pannello di sinistra, selezionare *Gestione computer*.
. Selezionare *azione* > *connessione a un altro computer*.
+
Viene visualizzata la finestra di dialogo Select computer (Seleziona computer).

. Digitare il nome del server CIFS o fare clic su *Browse* (Sfoglia) per individuare il server CIFS.
+
Se il nome del server CIFS corrisponde al nome host della macchina virtuale di storage (SVM), digitare il nome SVM. Se il nome del server CIFS è diverso dal nome host SVM, digitare il nome del server CIFS.

. Fare clic su *OK*.
. Nella struttura della console, fare clic su *System Tools* > *Shared Folders*.
. Fare clic su *shares*.
. Nel riquadro dei risultati, fare clic con il pulsante destro del mouse sulla condivisione.
. Fare clic su *Proprietà*.
+
Vengono visualizzate le proprietà della condivisione selezionata.

. Nella scheda *Generale*, fare clic su *Impostazioni offline*.
+
Viene visualizzata la finestra di dialogo Offline Settings (Impostazioni offline).

. Configurare le opzioni di disponibilità offline in base alle esigenze.
. Fare clic su *OK*.

