---
permalink: smb-admin/configure-roaming-profiles-task.html 
sidebar: sidebar 
keywords: automatic, user, profile, available, log, computer, network, configure, roam, active, directory, mmc, snap-in, configuring, roam, windows, server, administration, center, configure roam profile 
summary: 'Se si desidera rendere automaticamente disponibile il profilo di un utente quando quest"ultimo effettua l"accesso a un computer della rete, è possibile configurare i profili di roaming tramite lo snap-in MMC utenti e computer di Active Directory. Se si configurano profili comuni su Windows Server, è possibile utilizzare il Centro di amministrazione di Active Directory.' 
---
= Configurare i profili di roaming
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera rendere automaticamente disponibile il profilo di un utente quando quest'ultimo effettua l'accesso a un computer della rete, è possibile configurare i profili di roaming tramite lo snap-in MMC utenti e computer di Active Directory. Se si configurano profili comuni su Windows Server, è possibile utilizzare il Centro di amministrazione di Active Directory.

.Fasi
. Sul server Windows, aprire la MMC utenti e computer di Active Directory (o Active Directory Administration Center sui server Windows).
. Individuare l'utente per cui si desidera configurare un profilo di roaming.
. Fare clic con il pulsante destro del mouse sull'utente e fare clic su *Proprietà*.
. Nella scheda *Profilo*, immettere il percorso del profilo per la condivisione in cui si desidera memorizzare il profilo di roaming dell'utente, seguito da `%username%`.
+
Ad esempio, il percorso di un profilo potrebbe essere il seguente: `\\vs1.example.com\profiles\%username%`. La prima volta che un utente effettua l'accesso, `%username%` viene sostituito con il nome dell'utente.

+
[NOTE]
====
Nel percorso `\\vs1.example.com\profiles\%username%`, `profiles` È il nome di condivisione di una condivisione su SVM (Storage Virtual Machine) vs1 con diritti di controllo completo per tutti.

====
. Fare clic su *OK*.

