---
permalink: smb-admin/control-automatic-dfs-advertisements-concept.html 
sidebar: sidebar 
keywords: cifs, server, option, control, dfs, capabilities, advertise, smb, client, connect, share, ontap, dfs, referral, access, symbol, link, how to control automatic dfs advertisements in ontap with a cifs server option 
summary: 'Un"opzione del server CIFS controlla il modo in cui le funzionalità DFS vengono pubblicizzate ai client SMB durante la connessione alle condivisioni. Poiché ONTAP utilizza i riferimenti DFS quando i client accedono a collegamenti simbolici su SMB, è necessario essere consapevoli dell"impatto della disattivazione o dell"attivazione di questa opzione.' 
---
= Controlla gli annunci DFS automatici in ONTAP con un'opzione del server CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un'opzione del server CIFS controlla il modo in cui le funzionalità DFS vengono pubblicizzate ai client SMB durante la connessione alle condivisioni. Poiché ONTAP utilizza i riferimenti DFS quando i client accedono a collegamenti simbolici su SMB, è necessario essere consapevoli dell'impatto della disattivazione o dell'attivazione di questa opzione.

Un'opzione del server CIFS determina se i server CIFS annunciano automaticamente se sono compatibili con DFS per i client SMB. Per impostazione predefinita, questa opzione è attivata e il server CIFS comunica sempre che è compatibile con DFS per i client SMB (anche quando ci si connette a condivisioni in cui l'accesso ai collegamenti simbolici è disattivato). Se si desidera che il server CIFS annunci che è compatibile con DFS solo quando si connettono a condivisioni in cui è attivato l'accesso ai collegamenti simbolici, è possibile disattivare questa opzione.

Tenere presente cosa accade quando questa opzione è disattivata:

* Le configurazioni di condivisione per i collegamenti simbolici sono invariate.
* Se il parametro share è impostato in modo da consentire l'accesso simbolico al collegamento (accesso in lettura/scrittura o accesso in sola lettura), il server CIFS comunica le funzionalità DFS ai client che si connettono a tale condivisione.
+
Le connessioni client e l'accesso ai collegamenti simbolici continuano senza interruzioni.

* Se il parametro share è impostato in modo da non consentire l'accesso tramite collegamento simbolico (disattivando l'accesso o se il valore del parametro share è nullo), il server CIFS non segnala le funzionalità DFS ai client che si connettono a tale condivisione.
+
Poiché i client hanno memorizzato nella cache le informazioni che il server CIFS è compatibile con DFS e non pubblicizzano più, i client connessi alle condivisioni in cui l'accesso al collegamento simbolico è disattivato potrebbero non essere in grado di accedere a queste condivisioni dopo la disattivazione dell'opzione del server CIFS. Una volta disattivata l'opzione, potrebbe essere necessario riavviare i client connessi a queste condivisioni, eliminando così le informazioni memorizzate nella cache.



Queste modifiche non si applicano alle connessioni SMB 1.0.
