---
permalink: smb-admin/control-domain-controller-discovery-task.html 
sidebar: sidebar 
keywords: ontap, modify, default, process, domain, controller, dc, enable, limit, site, pool, performance, improvement, environment, manage, manage domain controller discovery 
summary: 'A partire da ONTAP 9.3, è possibile modificare il processo predefinito in base al quale vengono rilevati i controller di dominio (DC). In questo modo, è possibile limitare il rilevamento al sito o a un pool di controller di dominio preferiti, con conseguente miglioramento delle performance a seconda dell"ambiente.' 
---
= Gestire il rilevamento dei controller di dominio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.3, è possibile modificare il processo predefinito in base al quale vengono rilevati i controller di dominio (DC). In questo modo, è possibile limitare il rilevamento al sito o a un pool di controller di dominio preferiti, con conseguente miglioramento delle performance a seconda dell'ambiente.

.A proposito di questa attività
Per impostazione predefinita, il processo di rilevamento dinamico rileva tutti i controller di dominio disponibili, inclusi i controller di dominio preferiti, tutti i controller di dominio nel sito locale e tutti i controller di dominio remoti. Questa configurazione può portare a latenza nell'autenticazione e nell'accesso alle condivisioni in alcuni ambienti. Se il pool di controller di dominio che si desidera utilizzare è già stato determinato o se i controller di dominio remoti sono inadeguati o inaccessibili, è possibile modificare il metodo di ricerca.

In ONTAP 9.3 e versioni successive, il `discovery-mode` del parametro `cifs domain discovered-servers` il comando consente di selezionare una delle seguenti opzioni di ricerca:

* Vengono rilevati tutti i controller di dominio del dominio.
* Vengono rilevati solo i controller di dominio nel sito locale.
+
Il `default-site` È possibile definire un parametro per il server SMB in modo da utilizzare questa modalità con le LIF non assegnate a un sito in siti e servizi.

* Il rilevamento dei server non viene eseguito, la configurazione dei server SMB dipende solo dai controller di dominio preferiti.
+
Per utilizzare questa modalità, è necessario prima definire i controller di dominio preferiti per il server SMB.



.Fase
. Specificare l'opzione di ricerca desiderata: `vserver cifs domain discovered-servers discovery-mode modify -vserver _vserver_name_ -mode {all|site|none}`
+
Opzioni per `mode` parametro:

+
** `all`
+
Rilevare tutti i controller di dominio disponibili (impostazione predefinita).

** `site`
+
Limita il rilevamento DC al tuo sito.

** `none`
+
Utilizzare solo i controller di dominio preferiti e non eseguire il rilevamento.




