---
permalink: smb-admin/create-configure-shares-concept.html 
sidebar: sidebar 
keywords: user, application, access, data, cifs, server, smb, create, configure, smb, share, name, point, volume, customize, parameter, properties, property, modify, exist, create and configure smb shares 
summary: Prima che utenti e applicazioni possano accedere ai dati sul server CIFS tramite SMB, è necessario creare e configurare le condivisioni SMB, che è un access point denominato in un volume. È possibile personalizzare le condivisioni specificando i parametri di condivisione e le proprietà di condivisione. È possibile modificare una condivisione esistente in qualsiasi momento. 
---
= Panoramica sulla creazione e la configurazione delle condivisioni SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima che utenti e applicazioni possano accedere ai dati sul server CIFS tramite SMB, è necessario creare e configurare le condivisioni SMB, che è un access point denominato in un volume. È possibile personalizzare le condivisioni specificando i parametri di condivisione e le proprietà di condivisione. È possibile modificare una condivisione esistente in qualsiasi momento.

Quando si crea una condivisione SMB, ONTAP crea un ACL predefinito per la condivisione con autorizzazioni di controllo completo per tutti.

Le condivisioni SMB sono legate al server CIFS sulla macchina virtuale di storage (SVM). Le condivisioni SMB vengono eliminate se la SVM viene eliminata o se il server CIFS a cui è associata viene cancellato dalla SVM. Se si ricrea il server CIFS su SVM, è necessario ricreare le condivisioni SMB.

.Informazioni correlate
xref:local-users-groups-concepts-concept.html[Gestire l'accesso ai file utilizzando SMB]

link:../smb-hyper-v-sql/index.html["Configurazione SMB per Microsoft Hyper-V e SQL Server"]

xref:configure-character-mappings-file-name-translation-task.adoc[Configurare la mappatura dei caratteri per la conversione dei nomi file SMB sui volumi]
