---
permalink: smb-admin/create-security-policies-file-task.html 
sidebar: sidebar 
keywords: create, creating, file, security, policy, svm, configuring, configure, apply, acl, folder, act, container, entry, applied, create security policies 
summary: 'La creazione di una policy di sicurezza dei file per le SVM è la terza fase della configurazione e dell"applicazione degli ACL a un file o a una cartella. Un criterio agisce come un contenitore per varie attività, in cui ogni attività è una singola voce che può essere applicata a file o cartelle. È possibile aggiungere attività al criterio di protezione in un secondo momento.' 
---
= Creare policy di sicurezza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La creazione di una policy di sicurezza dei file per le SVM è la terza fase della configurazione e dell'applicazione degli ACL a un file o a una cartella. Un criterio agisce come un contenitore per varie attività, in cui ogni attività è una singola voce che può essere applicata a file o cartelle. È possibile aggiungere attività al criterio di protezione in un secondo momento.

.A proposito di questa attività
Le attività aggiunte a un criterio di protezione contengono associazioni tra il descrittore di protezione NTFS e i percorsi di file o cartelle. Pertanto, è necessario associare i criteri di protezione a ogni SVM (contenente volumi di sicurezza NTFS o volumi di sicurezza misti).

.Fasi
. Creare una policy di sicurezza: `vserver security file-directory policy create -vserver vserver_name -policy-name policy_name`
+
`vserver security file-directory policy create -policy-name policy1 -vserver vs1`

. Verificare la policy di sicurezza: `vserver security file-directory policy show`
+
[listing]
----

            vserver security file-directory policy show
               Vserver          Policy Name
             ------------     --------------
                 vs1              policy1
----

