---
permalink: smb-admin/default-administrative-shares-concept.html 
sidebar: sidebar 
keywords: create, cifs, server, storage, virtual, machine, svm, default, administrative, share, automatic, what the default administrative shares are 
summary: 'Quando si crea un server CIFS sulla macchina virtuale di storage (SVM), vengono create automaticamente le condivisioni amministrative predefinite. È necessario comprendere quali sono le condivisioni predefinite e come vengono utilizzate.' 
---
= Informazioni sulle condivisioni SMB ONTAP amministrative predefinite
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si crea un server CIFS sulla macchina virtuale di storage (SVM), vengono create automaticamente le condivisioni amministrative predefinite. È necessario comprendere quali sono le condivisioni predefinite e come vengono utilizzate.

Quando si crea il server CIFS, ONTAP crea le seguenti condivisioni amministrative predefinite:


NOTE: A partire da ONTAP 9.8, la condivisione in dollari di amministrazione non viene più creata per impostazione predefinita.

* ipc
* admin (solo ONTAP 9.7 e versioni precedenti)
* €


Poiché le condivisioni che terminano con il carattere € sono condivisioni nascoste, le condivisioni amministrative predefinite non sono visibili da risorse del computer, ma è possibile visualizzarle utilizzando le cartelle condivise.



== Come vengono utilizzate le condivisioni predefinite ipc e admin

Le condivisioni ipc e admin vengono utilizzate da ONTAP e non possono essere utilizzate dagli amministratori Windows per accedere ai dati che risiedono sulla SVM.

* condivisione ipc
+
La condivisione ipc è una risorsa che condivide le named pipe che sono essenziali per la comunicazione tra i programmi. La condivisione ipc viene utilizzata durante l'amministrazione remota di un computer e durante la visualizzazione delle risorse condivise di un computer. Non è possibile modificare le impostazioni di condivisione, le proprietà di condivisione o gli ACL della condivisione ipc. Inoltre, non è possibile rinominare o eliminare la condivisione ipc.

* Quota amministrativa (solo ONTAP 9.7 e versioni precedenti)
+

NOTE: A partire da ONTAP 9.8, la condivisione in dollari di amministrazione non viene più creata per impostazione predefinita.

+
La condivisione admin viene utilizzata durante l'amministrazione remota di SVM. Il percorso di questa risorsa è sempre il percorso verso la radice SVM. Non è possibile modificare le impostazioni di condivisione, le proprietà di condivisione o gli ACL per la condivisione admin. Inoltre, non è possibile rinominare o eliminare la condivisione admin.





== Modalità di utilizzo della condivisione predefinita

La condivisione è una condivisione amministrativa che il cluster o l'amministratore SVM può utilizzare per accedere e gestire il volume root SVM.

Di seguito sono riportate le caratteristiche della quota:

* Il percorso per questa condivisione è sempre il percorso del volume root SVM e non può essere modificato.
* L'ACL predefinito per la condivisione è Amministratore/controllo completo.
+
Questo utente è il BUILTIN/amministratore. Per impostazione predefinita, il BUILTIN/amministratore può eseguire il mapping alla condivisione e visualizzare, creare, modificare o eliminare file e cartelle nella directory principale mappata. Prestare attenzione durante la gestione di file e cartelle in questa directory.

* È possibile modificare l'ACL della condivisione.
* È possibile modificare le impostazioni di condivisione e le proprietà di condivisione.
* Non è possibile eliminare la condivisione.
* L'amministratore di SVM può accedere al resto dello spazio dei nomi SVM dalla condivisione mappata incrociando le giunzioni dello spazio dei nomi.
* È possibile accedere alla condivisione utilizzando Microsoft Management Console.


.Informazioni correlate
xref:configure-ntfs-windows-security-tab-task.adoc[Configurare le autorizzazioni avanzate dei file utilizzando la scheda Sicurezza di Windows]
