---
permalink: smb-admin/delete-branchcache-config-task.html 
sidebar: sidebar 
keywords: command, deleting, delete, branchcache, service, storage, virtual, machine, svm, exist, hash, delete the branchcache configuration 
summary: Il comando da utilizzare per eliminare il servizio BranchCache sulla macchina virtuale di storage varia a seconda che si desideri eliminare o conservare gli hash esistenti. 
---
= Elimina la configurazione BranchCache sulle condivisioni SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se in precedenza è stato configurato BranchCache ma non si desidera che la macchina virtuale di storage (SVM) continui a fornire contenuto memorizzato nella cache, è possibile eliminare la configurazione BranchCache sul server CIFS. È necessario essere consapevoli di cosa accade quando si elimina la configurazione.

Quando si elimina la configurazione, ONTAP rimuove dal cluster le informazioni di configurazione relative a tale SVM e interrompe il servizio BranchCache. È possibile scegliere se ONTAP deve eliminare l'archivio hash sulla SVM.

L'eliminazione della configurazione BranchCache non interrompe l'accesso dei client abilitati a BranchCache. Successivamente, quando i client abilitati a BranchCache richiedono informazioni sui metadati sulle connessioni SMB esistenti per il contenuto già memorizzato nella cache, ONTAP risponde con un errore definito da Microsoft, che fa in modo che il client invii una seconda richiesta, richiedendo il contenuto effettivo. In risposta alla richiesta di contenuto, il server CIFS invia il contenuto effettivo memorizzato nella SVM

Una volta eliminata la configurazione di BranchCache, le condivisioni SMB non pubblicizzano le funzionalità di BranchCache. Per accedere a contenuti che non sono stati precedentemente memorizzati nella cache utilizzando nuove connessioni SMB, i client eseguono normali richieste SMB in lettura.

Il comando utilizzato per eliminare il servizio BranchCache sulla macchina virtuale di storage (SVM) varia a seconda che si desideri eliminare o mantenere gli hash esistenti.

.Fase
. Eseguire il comando appropriato:
+
|===
| Se si desidera... | Quindi, immettere quanto segue... 


 a| 
Eliminare la configurazione BranchCache ed eliminare gli hash esistenti
 a| 
`vserver cifs branchcache delete -vserver _vserver_name_ -flush-hashes true`



 a| 
Eliminare la configurazione BranchCache ma mantenere gli hash esistenti
 a| 
`vserver cifs branchcache delete -vserver _vserver_name_ -flush-hashes false`

|===


.Esempio
Nell'esempio riportato di seguito viene eliminata la configurazione BranchCache su SVM vs1 e vengono eliminati tutti gli hash esistenti:

[listing]
----
cluster1::> vserver cifs branchcache delete -vserver vs1 -flush-hashes true
----