---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: Esistono alcune linee guida importanti da comprendere quando si distribuiscono file offline sulle condivisioni home directory che hanno la proprietà share showsnapshot impostata sulle home directory. 
---
= Linee guida per la distribuzione di file SMB ONTAP offline
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono alcune importanti linee guida da comprendere quando si distribuiscono file offline nelle condivisioni home directory che dispongono di `showsnapshot` proprietà di condivisione impostata nelle home directory.

Se la `showsnapshot` proprietà Share è impostata su una condivisione della home directory in cui sono configurati file non in linea, i client Windows memorizzano nella cache tutti gli snapshot nella `~snapshot` cartella nella home directory dell'utente.

I client Windows memorizzano nella cache tutti gli snapshot nella home directory se si verifica una delle seguenti condizioni:

* L'utente rende la home directory disponibile offline dal client.
+
Il contenuto di `~snapshot` la cartella nella home directory viene inclusa e resa disponibile offline.

* L'utente configura il reindirizzamento delle cartelle per reindirizzare una cartella come `My Documents` Alla directory principale di una home directory che risiede nella condivisione del server CIFS.
+
Alcuni client Windows potrebbero rendere automaticamente disponibile la cartella reindirizzata offline. Se la cartella viene reindirizzata alla directory principale della home directory, il `~snapshot` la cartella è inclusa nel contenuto offline memorizzato nella cache.



[NOTE]
====
Evitare le distribuzioni di file offline in cui la `~snapshot` cartella è inclusa nei file offline. Gli snapshot nella `~snapshot` cartella contengono tutti i dati del volume nel punto in cui ONTAP ha creato lo snapshot. Pertanto, la creazione di una copia non in linea della `~snapshot` cartella comporta un notevole consumo di spazio di archiviazione locale sul client, consuma larghezza di banda della rete durante la sincronizzazione dei file non in linea e aumenta il tempo necessario per sincronizzare i file non in linea.

====