---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: Esistono alcune linee guida importanti da comprendere quando si distribuiscono file offline sulle condivisioni home directory che hanno la proprietà share showsnapshot impostata sulle home directory. 
---
= Linee guida per la distribuzione di file offline
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono alcune importanti linee guida da comprendere quando si distribuiscono file offline nelle condivisioni home directory che dispongono di `showsnapshot` proprietà di condivisione impostata nelle home directory.

Se il `showsnapshot` La proprietà Share viene impostata su una condivisione home directory con file offline configurati, i client Windows memorizzano nella cache tutte le copie Snapshot in `~snapshot` nella home directory dell'utente.

I client Windows memorizzano nella cache tutte le copie Snapshot nella home directory se si verifica una delle seguenti condizioni:

* L'utente rende la home directory disponibile offline dal client.
+
Il contenuto di `~snapshot` la cartella nella home directory viene inclusa e resa disponibile offline.

* L'utente configura il reindirizzamento delle cartelle per reindirizzare una cartella come `My Documents` Alla directory principale di una home directory che risiede nella condivisione del server CIFS.
+
Alcuni client Windows potrebbero rendere automaticamente disponibile la cartella reindirizzata offline. Se la cartella viene reindirizzata alla directory principale della home directory, il `~snapshot` la cartella è inclusa nel contenuto offline memorizzato nella cache.



[NOTE]
====
Implementazioni di file offline in cui `~snapshot` la cartella è inclusa nei file offline dovrebbe essere evitata. Le copie Snapshot in `~snapshot` La cartella contiene tutti i dati sul volume nel punto in cui ONTAP ha creato la copia Snapshot. Pertanto, è necessario creare una copia offline di `~snapshot` la cartella consuma un notevole storage locale sul client, consuma la larghezza di banda della rete durante la sincronizzazione dei file offline e aumenta il tempo necessario per la sincronizzazione dei file offline.

====