---
permalink: smb-admin/disable-branchcache-shares-concept.html 
sidebar: sidebar 
keywords: branchcache, caching, cache, service, smb, disable, share, share-by-share, basis, configure, temporarily, automatic, disable branchcache on smb shares 
summary: Se non si desidera fornire servizi di caching BranchCache su determinate condivisioni SMB, ma si desidera fornire servizi di caching su tali condivisioni in un secondo momento, è possibile disattivare BranchCache in base alla condivisione. Se BranchCache è configurato per offrire il caching su tutte le condivisioni, ma si desidera disattivare temporaneamente tutti i servizi di caching, è possibile modificare la configurazione di BranchCache per interrompere il caching automatico su tutte le condivisioni. 
---
= Scopri come disabilitare BranchCache sulle condivisioni SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se non si desidera fornire servizi di caching BranchCache su determinate condivisioni SMB, ma si desidera fornire servizi di caching su tali condivisioni in un secondo momento, è possibile disattivare BranchCache in base alla condivisione. Se BranchCache è configurato per offrire il caching su tutte le condivisioni, ma si desidera disattivare temporaneamente tutti i servizi di caching, è possibile modificare la configurazione di BranchCache per interrompere il caching automatico su tutte le condivisioni.

Se BranchCache su una condivisione SMB viene successivamente disattivato dopo la prima attivazione, ONTAP interrompe l'invio dei metadati al client richiedente. Un client che necessita di dati lo recupera direttamente dal server di contenuti (server CIFS sulla macchina virtuale di storage (SVM)).

.Informazioni correlate
xref:configure-branchcache-enabled-shares-concept.adoc[Configurazione delle condivisioni SMB abilitate per BranchCache]
