---
permalink: smb-admin/display-dynamic-access-control-security-task.html 
sidebar: sidebar 
keywords: display, information, dynamic, access, control, dac, security, ntfs, volume, data, effective, security, mix, security-stle, volume, conditional, ace, resource, central, access, policy, display information about dynamic access control security 
summary: 'È possibile visualizzare informazioni sulla sicurezza del controllo dinamico degli accessi (DAC) sui volumi NTFS e sui dati con protezione effettiva NTFS su volumi misti di tipo sicurezza. Ciò include informazioni su ACE condizionali, ACE di risorse e ACE di policy di accesso centrale. È possibile utilizzare i risultati per convalidare la configurazione di sicurezza o per risolvere i problemi di accesso ai file.' 
---
= Visualizza informazioni sulla sicurezza DAC per i server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sulla sicurezza del controllo dinamico degli accessi (DAC) sui volumi NTFS e sui dati con protezione effettiva NTFS su volumi misti di tipo sicurezza. Ciò include informazioni su ACE condizionali, ACE di risorse e ACE di policy di accesso centrale. È possibile utilizzare i risultati per convalidare la configurazione di sicurezza o per risolvere i problemi di accesso ai file.

.A proposito di questa attività
Specificare il nome della macchina virtuale di storage (SVM) e il percorso dei dati di cui si desidera visualizzare le informazioni di sicurezza relative al file o alla cartella. È possibile visualizzare l'output in forma di riepilogo o come elenco dettagliato.

.Fase
. Visualizzare le impostazioni di sicurezza di file e directory con il livello di dettaglio desiderato:
+
|===
| Se si desidera visualizzare le informazioni... | Immettere il seguente comando... 


 a| 
In forma riassuntiva
 a| 
`vserver security file-directory show -vserver vserver_name -path path`



 a| 
Con dettagli più dettagliati
 a| 
`vserver security file-directory show -vserver vserver_name -path path -expand-mask true`



 a| 
Dove viene visualizzato l'output con SID di gruppo e utente
 a| 
`vserver security file-directory show -vserver vserver_name -path path -lookup-names false`



 a| 
Informazioni sulla sicurezza di file e directory per file e directory in cui la bit mask esadecimale viene convertita in formato testuale
 a| 
`vserver security file-directory show -vserver vserver_name -path path -textual-mask true`

|===


.Esempi
Nell'esempio riportato di seguito vengono visualizzate le informazioni di sicurezza del controllo dinamico degli accessi relative al percorso `/vol1` In SVM vs1:

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /vol1
                           Vserver: vs1
                         File Path: /vol1
                 File Inode Number: 112
                    Security Style: mixed
                   Effective Style: ntfs
                    DOS Attributes: 10
            DOS Attributes in Text: ----D---
            Expanded Dos Attribute: -
                      Unix User Id: 0
                     Unix Group Id: 1
                    Unix Mode Bits: 777
            Unix Mode Bits in Text: rwxrwxrwx
                              ACLs: NTFS Security Descriptor
                                    Control:0xbf14
                                    Owner:CIFS1\Administrator
                                    Group:CIFS1\Domain Admins
                                    SACL - ACEs
                                       ALL-Everyone-0xf01ff-OI|CI|SA|FA
                                       RESOURCE ATTRIBUTE-Everyone-0x0
                                         ("Department_MS",TS,0x10020,"Finance")
                                       POLICY ID-All resources - No Write-0x0-OI|CI
                                    DACL - ACEs
                                       ALLOW-CIFS1\Administrator-0x1f01ff-OI|CI
                                       ALLOW-Everyone-0x1f01ff-OI|CI
                                       ALLOW CALLBACK-DAC\user1-0x1200a9-OI|CI
                                         ((@User.department==@Resource.Department_MS&&@Resource.Impact_MS>1000)&&@Device.department==@Resource.Department_MS)
----
.Informazioni correlate
xref:display-gpo-config-task.adoc[Visualizzazione delle informazioni sulle configurazioni dell'oggetto Criteri di gruppo]

xref:display-central-access-policies-task.adoc[Visualizzazione di informazioni sui criteri di accesso centrale]

xref:display-central-access-policy-rules-task.adoc[Visualizzazione delle informazioni sulle regole dei criteri di accesso centrale]
