---
permalink: smb-admin/display-preferred-trusted-domain-list-task.html 
sidebar: sidebar 
keywords: display, information, trust, domain, perfer, list, order, multidomain, name, map, search, enable, configure, alternative, display information about the preferred trusted domain list 
summary: 'È possibile visualizzare le informazioni sui domini attendibili presenti nell"elenco dei domini attendibili preferiti e l"ordine in cui vengono ricercati se sono attivate le ricerche di mappatura dei nomi multidominio. È possibile configurare un elenco di domini attendibili preferito in alternativa all"elenco di domini attendibili rilevati automaticamente.' 
---
= Consente di visualizzare le informazioni relative all'elenco di domini SMB ONTAP attendibili preferiti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare le informazioni sui domini attendibili presenti nell'elenco dei domini attendibili preferiti e l'ordine in cui vengono ricercati se sono attivate le ricerche di mappatura dei nomi multidominio. È possibile configurare un elenco di domini attendibili preferito in alternativa all'elenco di domini attendibili rilevati automaticamente.

.Fasi
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera visualizzare informazioni su... | Utilizzare il comando... 


 a| 
Tutti i domini trusted preferiti nel cluster raggruppati per SVM (Storage Virtual Machine)
 a| 
`vserver cifs domain name-mapping-search show`



 a| 
Tutti i domini trusted preferiti per una SVM specificata
 a| 
`vserver cifs domain name-mapping-search show -vserver _vserver_name_`

|===
+
Il seguente comando visualizza informazioni su tutti i domini attendibili preferiti nel cluster:

+
[listing]
----
cluster1::> vserver cifs domain name-mapping-search show
Vserver         Trusted Domains
--------------  ----------------------------------
vs1             CIFS1.EXAMPLE.COM
----


.Informazioni correlate
xref:add-remove-replace-trusted-domains-preferred-lists-task.adoc[Aggiungere, rimuovere o sostituire i domini attendibili negli elenchi preferiti]
