---
permalink: smb-admin/display-nfsv4-audit-policies-flexvol-volumes-task.html 
sidebar: sidebar 
keywords: display, information, nfsv4, audit, policies, policy, flexvol, volume, ontap, cli, security, style, permission, applied, apply, system, access, control, lists, sacl, result, validate, security, display information about nfsv4 audit policies on flexvol volumes using cli 
summary: 'È possibile visualizzare informazioni sui criteri di controllo di NFSv4 sui volumi FlexVol utilizzando l"interfaccia CLI di ONTAP, inclusi gli stili di sicurezza e gli stili di sicurezza effettivi, le autorizzazioni applicate e le informazioni sugli elenchi di controllo dell"accesso al sistema (SACL). È possibile utilizzare i risultati per convalidare la configurazione della protezione o per risolvere i problemi di controllo.' 
---
= Comandi ONTAP per visualizzare informazioni sui criteri di audit NFSv4 sui volumi SMB FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sui criteri di controllo di NFSv4 sui volumi FlexVol utilizzando l'interfaccia CLI di ONTAP, inclusi gli stili di sicurezza e gli stili di sicurezza effettivi, le autorizzazioni applicate e le informazioni sugli elenchi di controllo dell'accesso al sistema (SACL). È possibile utilizzare i risultati per convalidare la configurazione della protezione o per risolvere i problemi di controllo.

.A proposito di questa attività
Specificare il nome della macchina virtuale di storage (SVM) e il percorso dei file o delle directory di cui si desidera visualizzare le informazioni di audit. È possibile visualizzare l'output in forma di riepilogo o come elenco dettagliato.

* I volumi e i qtree UNIX di sicurezza utilizzano solo SACL NFSv4 per le policy di controllo.
* I file e le directory di un volume misto di sicurezza con stile UNIX possono applicare criteri di controllo NFSv4.
+
I volumi misti di sicurezza e le qtree possono contenere alcuni file e directory che utilizzano permessi di file UNIX, i bit di modalità o gli ACL NFSv4 e alcuni file e directory che utilizzano permessi di file NTFS.

* Il livello superiore di un volume misto di sicurezza può avere una protezione efficace UNIX o NTFS e potrebbe contenere o meno SACL NFSv4.
* L'output ACL viene visualizzato solo per file e cartelle con protezione NTFS o NFSv4.
+
Questo campo è vuoto per i file e le cartelle che utilizzano la protezione UNIX e che dispongono solo delle autorizzazioni di bit di modalità applicate (nessun ACL NFSv4).

* I campi owner e group output nell'output ACL sono validi solo nel caso di descrittori di protezione NTFS.
* Poiché la protezione di Storage-Level Access Guard può essere configurata su un volume misto di sicurezza o qtree anche se lo stile di sicurezza effettivo della root del volume o del qtree è UNIX, L'output di un volume o percorso qtree in cui Storage-Level Access Guard è configurato potrebbe visualizzare sia SACL normali di file NFSv4, directory e SACL NTFS di Storage-Level Access Guard.
* Poiché la protezione Storage-Level Access Guard è supportata su un volume o qtree UNIX se un server CIFS è configurato su SVM, l'output potrebbe contenere informazioni sulla protezione Storage-Level Access Guard applicata al volume o al qtree specificato in `-path` parametro.


.Fasi
. Visualizzare le impostazioni di sicurezza di file e directory con il livello di dettaglio desiderato:
+
|===
| Se si desidera visualizzare le informazioni... | Immettere il seguente comando... 


 a| 
In forma riassuntiva
 a| 
`vserver security file-directory show -vserver vserver_name -path path`



 a| 
Con dettagli più dettagliati
 a| 
`vserver security file-directory show -vserver vserver_name -path path -expand-mask true`

|===


.Esempi
Nell'esempio seguente vengono visualizzate le informazioni di sicurezza relative al percorso `/lab` In SVM vs1. Questo percorso di sicurezza UNIX ha un SACL NFSv4.

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /lab

                Vserver: vs1
              File Path: /lab
      File Inode Number: 288
         Security Style: unix
        Effective Style: unix
         DOS Attributes: 11
 DOS Attributes in Text: ----D--R
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 0
 Unix Mode Bits in Text: ---------
                   ACLs: NFSV4 Security Descriptor
                         Control:0x8014
                         SACL - ACEs
                           SUCCESSFUL-S-1-520-0-0xf01ff-SA
                           FAILED-S-1-520-0-0xf01ff-FA
                         DACL - ACEs
                           ALLOW-S-1-520-1-0xf01ff
----