---
permalink: smb-admin/display-discovered-trusted-domains-task.html 
sidebar: sidebar 
keywords: display, information, discover, trust, domain, cifs, server, home, contain, computer, trusted-domain, list, display information about discover trusted domains 
summary: 'È possibile visualizzare informazioni sui domini attendibili rilevati per il dominio principale del server CIFS, ovvero il dominio contenente l"account del computer del server CIFS. Ciò può essere utile quando si desidera sapere quali domini attendibili vengono rilevati e come vengono ordinati all"interno dell"elenco di domini attendibili rilevati.' 
---
= Consente di visualizzare le informazioni sui domini SMB ONTAP attendibili rilevati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sui domini attendibili rilevati per il dominio principale del server CIFS, ovvero il dominio contenente l'account del computer del server CIFS. Ciò può essere utile quando si desidera sapere quali domini attendibili vengono rilevati e come vengono ordinati all'interno dell'elenco di domini attendibili rilevati.

.A proposito di questa attività
Vengono rilevati solo i domini con trust bidirezionali con il dominio principale. Poiché il domain controller (DC) del dominio principale restituisce l'elenco dei domini attendibili in un ordine determinato dal controller di dominio, non è possibile prevedere l'ordine dei domini all'interno dell'elenco. Visualizzando l'elenco dei domini attendibili, è possibile determinare l'ordine di ricerca per le ricerche di mappatura dei nomi multidominio.

Le informazioni di dominio attendibile visualizzate sono raggruppate per nodo e SVM (Storage Virtual Machine).

.Fase
. Visualizzare le informazioni sui domini attendibili rilevati utilizzando `vserver cifs domain trusts show` comando.
+
`vserver cifs domain trusts show -vserver vs1`

+
[listing]
----
   Node: node1
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM

   Node: node2
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM
----


.Informazioni correlate
xref:reset-rediscover-trusted-domains-task.adoc[Reimpostare e riscoprire i domini attendibili]
