---
permalink: smb-admin/display-server-security-settings-task.html 
sidebar: sidebar 
keywords: display, information, smb, cifs, server, security, settings, storage, virtual, machine, svm, verify, setting, 
summary: 'È possibile visualizzare informazioni sulle impostazioni di sicurezza dei server SMB sulle macchine virtuali dello storage (SVM). È possibile utilizzare queste informazioni per verificare che le impostazioni di protezione siano corrette.' 
---
= Visualizza informazioni sulle impostazioni di sicurezza del server SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sulle impostazioni di sicurezza dei server SMB sulle macchine virtuali dello storage (SVM). È possibile utilizzare queste informazioni per verificare che le impostazioni di protezione siano corrette.

.A proposito di questa attività
Un'impostazione di protezione visualizzata può essere il valore predefinito per quell'oggetto o un valore non predefinito configurato utilizzando l'interfaccia CLI di ONTAP o gli oggetti Criteri di gruppo di Active Directory.

Non utilizzare `vserver cifs security show` Comando per i server SMB in modalità workgroup, perché alcune opzioni non sono valide.

.Fase
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera visualizzare informazioni su... | Immettere il comando... 


 a| 
Tutte le impostazioni di sicurezza su una SVM specificata
 a| 
`vserver cifs security show -vserver _vserver_name_`



 a| 
Una o più impostazioni di sicurezza specifiche sulla SVM
 a| 
`+vserver cifs security show -vserver _vserver_name_ -fields [fieldname,...]+` È possibile immettere `-fields ?` per determinare quali campi è possibile utilizzare.

|===


.Esempio
L'esempio seguente mostra tutte le impostazioni di sicurezza per SVM vs1:

[listing]
----
cluster1::> vserver cifs security show -vserver vs1

Vserver: vs1

                          Kerberos Clock Skew:        5 minutes
                          Kerberos Ticket Age:        10 hours
                         Kerberos Renewal Age:        7 days
                         Kerberos KDC Timeout:        3 seconds
                          Is Signing Required:        false
              Is Password Complexity Required:        true
         Use start_tls For AD LDAP connection:        false
                    Is AES Encryption Enabled:        false
                       LM Compatibility Level:        lm-ntlm-ntlmv2-krb
                   Is SMB Encryption Required:        false
                      Client Session Security:        none
              SMB1 Enabled for DC Connections:        false
              SMB2 Enabled for DC Connections:        system-default
LDAP Referral Enabled For AD LDAP connections:        false
             Use LDAPS for AD LDAP connection:        false
    Encryption is required for DC Connections:        false
 AES session key enabled for NetLogon channel:        false
  Try Channel Binding For AD LDAP Connections:        false
----
Le impostazioni visualizzate dipendono dalla versione di ONTAP in esecuzione.

L'esempio seguente mostra l'inclinazione del clock Kerberos per SVM vs1:

[listing]
----
cluster1::> vserver cifs security show -vserver vs1 -fields kerberos-clock-skew

            vserver kerberos-clock-skew
            ------- -------------------
            vs1     5
----
.Informazioni correlate
xref:display-gpo-config-task.adoc[Visualizzazione delle informazioni sulle configurazioni dell'oggetto Criteri di gruppo]
