---
permalink: smb-admin/display-local-groups-task.html 
sidebar: sidebar 
keywords: display, list, local, group, configure, cluster, storage, virtual, machine, svm, information, useful, troubleshoot, issue, data, user-right, privilege, display information about local groups 
summary: 'È possibile visualizzare un elenco di tutti i gruppi locali configurati sul cluster o su una specifica macchina virtuale di storage (SVM). Queste informazioni possono essere utili per la risoluzione dei problemi di accesso ai file dei dati contenuti nella SVM o dei problemi relativi ai diritti utente (privilegi) sulla SVM.' 
---
= Visualizza informazioni sui gruppi locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare un elenco di tutti i gruppi locali configurati sul cluster o su una specifica macchina virtuale di storage (SVM). Queste informazioni possono essere utili per la risoluzione dei problemi di accesso ai file dei dati contenuti nella SVM o dei problemi relativi ai diritti utente (privilegi) sulla SVM.

.Fase
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera ottenere informazioni su... | Immettere il comando... 


 a| 
Tutti i gruppi locali del cluster
 a| 
`vserver cifs users-and-groups local-group show`



 a| 
Tutti i gruppi locali sulla SVM
 a| 
`vserver cifs users-and-groups local-group show -vserver _vserver_name_`

|===
+
Quando si esegue questo comando, è possibile scegliere altri parametri opzionali. Per ulteriori informazioni, consulta la pagina man.



.Esempio
Nell'esempio seguente vengono visualizzate informazioni su tutti i gruppi locali su SVM vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver  Group Name                  Description
-------- --------------------------- ----------------------------
vs1      BUILTIN\Administrators      Built-in Administrators group
vs1      BUILTIN\Backup Operators    Backup Operators group
vs1      BUILTIN\Power Users         Restricted administrative privileges
vs1      BUILTIN\Users               All users
vs1      CIFS_SERVER\engineering
vs1      CIFS_SERVER\sales
----