---
permalink: smb-admin/display-file-security-audit-policies-concept.html 
sidebar: sidebar 
keywords: display, information, file, security, directories, directory, contain, volume, storage, virtual, machine, svm, audit, policies, policy, flexvol, configure, storage-level, access, guard, dynamic, access, control, display information about file security and audit policies 
summary: 'È possibile visualizzare informazioni sulla sicurezza dei file su file e directory contenuti nei volumi su macchine virtuali di storage (SVM). È possibile visualizzare informazioni sui criteri di controllo sui volumi FlexVol. Se configurato, è possibile visualizzare informazioni sulle impostazioni di protezione accesso a livello di storage e controllo dinamico degli accessi sui volumi FlexVol.' 
---
= Visualizza informazioni generali sulla sicurezza dei file e sui criteri di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sulla sicurezza dei file su file e directory contenuti nei volumi su macchine virtuali di storage (SVM). È possibile visualizzare informazioni sui criteri di controllo sui volumi FlexVol. Se configurato, è possibile visualizzare informazioni sulle impostazioni di protezione accesso a livello di storage e controllo dinamico degli accessi sui volumi FlexVol.



== Visualizzazione delle informazioni sulla sicurezza dei file

È possibile visualizzare le informazioni sulla sicurezza dei file applicate ai dati contenuti nei volumi e nei qtree (per i volumi FlexVol) con i seguenti stili di sicurezza:

* NTFS
* UNIX
* Misto




== Visualizzazione delle informazioni sui criteri di controllo

È possibile visualizzare informazioni sulle policy di audit per il controllo degli eventi di accesso sui volumi FlexVol sui seguenti protocolli NAS:

* SMB (tutte le versioni)
* NFSv4.x




== Visualizzazione di informazioni sulla sicurezza di Storage-Level Access Guard (SLAG)

La protezione degli accessi a livello di storage può essere applicata a volumi FlexVol e oggetti qtree con i seguenti stili di sicurezza:

* NTFS
* Misto
* UNIX (se un server CIFS è configurato sulla SVM che contiene il volume)




== Visualizzazione di informazioni sulla sicurezza del controllo dinamico degli accessi (DAC)

La protezione del controllo dinamico degli accessi può essere applicata a un oggetto all'interno di un volume FlexVol con i seguenti stili di protezione:

* NTFS
* Misto (se l'oggetto dispone di una protezione efficace NTFS)


.Informazioni correlate
xref:secure-file-access-storage-level-access-guard-concept.adoc[Protezione dell'accesso ai file mediante Storage-Level Access Guard]

xref:display-storage-level-access-guard-task.adoc[Visualizzazione di informazioni su Storage-Level Access Guard]
