---
permalink: smb-admin/dynamic-access-control-concept.html 
sidebar: sidebar 
keywords: consideration, dynamic, access, control, dac, central, policies, policy, secure, file, folder, cifs, server, consideration when using dynamic access control and central access policies with cifs servers 
summary: 'È necessario tenere presente alcune considerazioni quando si utilizza il controllo dinamico dell"accesso (DAC) e i criteri di accesso centrale per proteggere file e cartelle sui server CIFS.' 
---
= Considerazioni sull'utilizzo del controllo dinamico degli accessi e delle policy di accesso centrale con i server CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario tenere presente alcune considerazioni quando si utilizza il controllo dinamico dell'accesso (DAC) e i criteri di accesso centrale per proteggere file e cartelle sui server CIFS.



== L'accesso NFS può essere negato all'utente root se la regola dei criteri si applica all'utente di dominio/amministratore

In alcuni casi, l'accesso NFS a root potrebbe essere negato quando la sicurezza del criterio di accesso centrale viene applicata ai dati a cui l'utente root sta tentando di accedere. Il problema si verifica quando il criterio di accesso centrale contiene una regola che viene applicata al dominio/amministratore e l'account root viene mappato all'account di dominio/amministratore.

Invece di applicare una regola all'utente di dominio/amministratore, è necessario applicarla a un gruppo con privilegi amministrativi, ad esempio il gruppo dominio/amministratori. In questo modo, è possibile mappare root all'account di dominio/amministratore senza che root sia interessato da questo problema.



== Il gruppo BUILTIN/Administrators del server CIFS ha accesso alle risorse quando il criterio di accesso centrale applicato non viene trovato in Active Directory

È possibile che alle risorse contenute nel server CIFS siano applicati criteri di accesso centrale, ma quando il server CIFS utilizza il SID del criterio di accesso centrale per tentare di recuperare informazioni da Active Directory, il SID non corrisponde ai SID dei criteri di accesso centrale esistenti in Active Directory. In questi casi, il server CIFS applica il criterio di ripristino locale predefinito per tale risorsa.

Il criterio di ripristino locale predefinito consente al gruppo BUILTIN/Administrators del server CIFS di accedere a tale risorsa.
