---
permalink: smb-admin/effective-slag-matrix-reference.html 
sidebar: sidebar 
keywords: configure, slag, volume, qtree, matrix, define, configuration, applicable, scenario, list, table, effective slag matrix 
summary: È possibile configurare LO SLAG su un volume, un qtree o entrambi. La matrice DELLE SCORIE definisce su quale volume o qtree è la configurazione DELLE SCORIE applicabile in diversi scenari elencati nella tabella. 
---
= Matrice SLAG efficace sui server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare LO SLAG su un volume, un qtree o entrambi. La matrice DELLE SCORIE definisce su quale volume o qtree è la configurazione DELLE SCORIE applicabile in diversi scenari elencati nella tabella.

|===
|  | SCORIA di volume in un AFS | SCHIAVITÙ di volumi in uno snapshot | SCORIE del qtree in un AFS | SCHIAVITÙ DEI qtree in una snapshot 


 a| 
Accesso al volume in un file system di accesso (AFS)
 a| 
SÌ
 a| 
NO
 a| 
N/A.
 a| 
N/A.



 a| 
Accesso ai volumi in uno snapshot
 a| 
SÌ
 a| 
NO
 a| 
N/A.
 a| 
N/A.



 a| 
Accesso al qtree in un AFS (quando LA SCORIA è presente nel qtree)
 a| 
NO
 a| 
NO
 a| 
SÌ
 a| 
NO



 a| 
Accesso al qtree in un AFS (quando LA SCORIA non è presente in qtree)
 a| 
SÌ
 a| 
NO
 a| 
NO
 a| 
NO



 a| 
Accesso al qtree in una snapshot (quando è presente una SCORIA nel sistema AFS del qtree)
 a| 
NO
 a| 
NO
 a| 
SÌ
 a| 
NO



 a| 
Accesso al qtree in una snapshot (quando la SCORIA non è presente nell'AFS del qtree)
 a| 
SÌ
 a| 
NO
 a| 
NO
 a| 
NO

|===