---
permalink: smb-admin/enable-disable-local-user-authentication-task.html 
sidebar: sidebar 
keywords: enable, disable, local, user, authentication, smb, access, storage, virtual, machine, svm, domain, controller, domain-level, level, enable or disable local user authentication 
summary: 'È possibile attivare o disattivare l"autenticazione utente locale per l"accesso SMB sulle macchine virtuali di storage (SVM). L"impostazione predefinita prevede l"autenticazione dell"utente locale, utile quando SVM non è in grado di contattare un controller di dominio o se si sceglie di non utilizzare i controlli di accesso a livello di dominio.' 
---
= Abilitare o disabilitare l'autenticazione utente locale sui server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare o disattivare l'autenticazione utente locale per l'accesso SMB sulle macchine virtuali di storage (SVM). L'impostazione predefinita prevede l'autenticazione dell'utente locale, utile quando SVM non è in grado di contattare un controller di dominio o se si sceglie di non utilizzare i controlli di accesso a livello di dominio.

.Prima di iniziare
La funzionalità di utenti e gruppi locali deve essere attivata sul server CIFS.

.A proposito di questa attività
È possibile attivare o disattivare l'autenticazione utente locale in qualsiasi momento. Se si desidera utilizzare utenti locali per l'autenticazione durante la creazione di una connessione SMB, è necessario attivare anche l'opzione utenti e gruppi locali del server CIFS.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera che l'autenticazione locale sia... | Immettere il comando... 


 a| 
Attivato
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-local-auth-enabled true`



 a| 
Disattivato
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-local-auth-enabled false`

|===
. Tornare al livello di privilegio admin: `set -privilege admin`


.Esempio
L'esempio seguente abilita l'autenticazione dell'utente locale su SVM vs1:

[listing]
----
cluster1::>set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-auth-enabled true

cluster1::*> set -privilege admin
----
.Informazioni correlate
xref:local-user-authentication-concept.adoc[Come funziona l'autenticazione utente locale]

xref:enable-disable-local-users-groups-task.adoc[Attivazione o disattivazione di utenti e gruppi locali]
