---
permalink: smb-admin/enable-disable-local-user-accounts-task.html 
sidebar: sidebar 
keywords: enable, local, user, account, access, data, contain, storage, virtual, machine, svm, smb, connection, disable, enable or disable local user accounts 
summary: 'Attivare un account utente locale se si desidera che l"utente possa accedere ai dati contenuti nella macchina virtuale di storage (SVM) tramite una connessione SMB. È inoltre possibile disattivare un account utente locale se non si desidera che l"utente acceda ai dati SVM tramite SMB.' 
---
= Attivare o disattivare gli account utente locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Attivare un account utente locale se si desidera che l'utente possa accedere ai dati contenuti nella macchina virtuale di storage (SVM) tramite una connessione SMB. È inoltre possibile disattivare un account utente locale se non si desidera che l'utente acceda ai dati SVM tramite SMB.

.A proposito di questa attività
Per abilitare un utente locale, modificare l'account utente.

.Fase
. Eseguire l'azione appropriata:
+
|===
| Se si desidera... | Immettere il comando... 


 a| 
Attivare l'account utente
 a| 
`vserver cifs users-and-groups local-user modify ‑vserver _vserver_name_ -user-name _user_name_ -is-account-disabled false`



 a| 
Disattivare l'account utente
 a| 
`vserver cifs users-and-groups local-user modify ‑vserver _vserver_name_ -user-name _user_name_ -is-account-disabled true`

|===

