---
permalink: smb-admin/enable-disable-dynamic-access-control-task.html 
sidebar: sidebar 
keywords: option, enable, dynamic, access, control, dac, secure, object, cifs, server, disable, default, enable or disable dynamic access control 
summary: 'L"opzione che consente di utilizzare il controllo dinamico dell"accesso (DAC) per proteggere gli oggetti sul server CIFS è disattivata per impostazione predefinita. Attivare l"opzione se si desidera utilizzare Dynamic Access Control sul server CIFS. Se in seguito si decide di non utilizzare il controllo dinamico degli accessi per proteggere gli oggetti memorizzati nel server CIFS, è possibile disattivare l"opzione.' 
---
= Abilitare o disabilitare DAC per i server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'opzione che consente di utilizzare il controllo dinamico dell'accesso (DAC) per proteggere gli oggetti sul server CIFS è disattivata per impostazione predefinita. Attivare l'opzione se si desidera utilizzare Dynamic Access Control sul server CIFS. Se in seguito si decide di non utilizzare il controllo dinamico degli accessi per proteggere gli oggetti memorizzati nel server CIFS, è possibile disattivare l'opzione.

È possibile trovare informazioni su come configurare il controllo di accesso dinamico in Active Directory nella libreria Microsoft TechNet.

http://technet.microsoft.com/library/hh831717.aspx["Microsoft TechNet: Panoramica dello scenario di controllo dinamico degli accessi"^]

.A proposito di questa attività
Una volta attivato il controllo dinamico degli accessi, il file system può contenere ACL con voci correlate al controllo dinamico degli accessi. Se Dynamic Access Control è disattivato, le voci correnti di Dynamic Access Control verranno ignorate e non saranno consentite le nuove.

Questa opzione è disponibile solo al livello di privilegio avanzato.

.Fase
. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Eseguire una delle seguenti operazioni:
+
|===


| Se si desidera che Dynamic Access Control sia... | Immettere il comando... 


 a| 
Attivato
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled true`



 a| 
Disattivato
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled false`

|===
. Tornare al livello di privilegi di amministratore: `set -privilege admin`


.Informazioni correlate
xref:configure-central-access-policies-secure-data-task.adoc[Configurazione delle policy di accesso centrale per proteggere i dati sui server CIFS]
