---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: Prima che il server CIFS possa utilizzare la firma e il sealing per una comunicazione sicura con un server LDAP di Active Directory, è necessario modificare le impostazioni di sicurezza del server CIFS per abilitare la firma e il sealing LDAP. 
---
= Abilitare la firma e il sealing LDAP sul server CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima che il server CIFS possa utilizzare la firma e il sealing per una comunicazione sicura con un server LDAP di Active Directory, è necessario modificare le impostazioni di sicurezza del server CIFS per abilitare la firma e il sealing LDAP.

.Prima di iniziare
Per determinare i valori di configurazione della protezione appropriati, rivolgersi all'amministratore del server ad.

.Fasi
. Configurare l'impostazione di sicurezza del server CIFS che abilita il traffico firmato e sigillato con i server LDAP di Active Directory: `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
È possibile attivare la firma (`sign`, integrità dei dati), firma e sigillatura (`seal`, integrità dei dati e crittografia), o nessuna delle due  `none`, nessuna firma o sigillatura). Il valore predefinito è `none`.

. Verificare che l'impostazione di protezione per la firma e il sealing LDAP sia impostata correttamente: `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
Se SVM utilizza lo stesso server LDAP per eseguire query di mappatura dei nomi o altre informazioni UNIX, ad esempio utenti, gruppi e netgroup, è necessario attivare l'impostazione corrispondente con `-session-security` opzione di `vserver services name-service ldap client modify` comando.

====

