---
permalink: smb-admin/enable-encrypted-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, connection, domain, controller, encrypt, enable, enable encrypted connections to domain controllers 
summary: A partire da ONTAP 9.8, è possibile specificare che le connessioni ai controller di dominio siano crittografate. 
---
= Abilitare le connessioni crittografate ai controller di dominio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.8, è possibile specificare che le connessioni ai controller di dominio siano crittografate.

.A proposito di questa attività
ONTAP richiede la crittografia per le comunicazioni del controller di dominio (DC) quando `-encryption-required-for-dc-connection` l'opzione è impostata su `true`; il valore predefinito è `false`. Quando l'opzione è impostata, per le connessioni ONTAP-DC verrà utilizzato solo il protocollo SMB3, in quanto la crittografia è supportata solo da SMB3.

Quando sono richieste comunicazioni DC crittografate, il `-smb2-enabled-for-dc-connections` L'opzione viene ignorata, perché ONTAP negozia solo le connessioni SMB3. Se un controller di dominio non supporta SMB3 e la crittografia, ONTAP non si connetterà con esso.

.Fase
. Abilitare la comunicazione crittografata con il controller di dominio: `vserver cifs security modify -vserver _svm_name_ -encryption-required-for-dc-connection true`

