---
permalink: smb-admin/enable-disable-ntfs-acls-unix-security-task.html 
sidebar: sidebar 
keywords: enable, disable, presentation, ntfs, acl, smb, client, unix, security-style, data, volume, enable or disable the presentation of ntfs acls for unix security-style data 
summary: 'È possibile attivare o disattivare la presentazione degli ACL NTFS ai client SMB per i dati di sicurezza UNIX (volumi di sicurezza UNIX e volumi di sicurezza misti con protezione efficace UNIX).' 
---
= Abilitare o disabilitare la presentazione degli ACL NTFS per i dati di sicurezza UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare o disattivare la presentazione degli ACL NTFS ai client SMB per i dati di sicurezza UNIX (volumi di sicurezza UNIX e volumi di sicurezza misti con protezione efficace UNIX).

.A proposito di questa attività
Se si attiva questa opzione, ONTAP presenta file e cartelle su volumi con uno stile di sicurezza UNIX efficace ai client SMB come dotati di ACL NTFS. Se si disattiva questa opzione, i volumi vengono presentati come volumi FAT ai client SMB. L'impostazione predefinita prevede la presentazione degli ACL NTFS ai client SMB.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Configurare l'impostazione dell'opzione UNIX NTFS ACL: `vserver cifs options modify -vserver _vserver_name_ -is-unix-nt-acl-enabled {true|false}`
. Verificare che l'opzione sia impostata sul valore desiderato: `vserver cifs options show -vserver _vserver_name_`
. Tornare al livello di privilegio admin: `set -privilege admin`

