---
permalink: smb-admin/enable-disable-odx-task.html 
sidebar: sidebar 
keywords: enable, disable, odx, storage, virtual, machine, svm, default, support, copy, offload, smb, enable, enable or disable odx 
summary: 'È possibile attivare o disattivare ODX su macchine virtuali storage (SVM). L"impostazione predefinita prevede l"attivazione del supporto per l"offload delle copie ODX se è attivato anche SMB 3.0.' 
---
= Abilitare o disabilitare ODX sui server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare o disattivare ODX su macchine virtuali storage (SVM). L'impostazione predefinita prevede l'attivazione del supporto per l'offload delle copie ODX se è attivato anche SMB 3.0.

.Prima di iniziare
SMB 3.0 deve essere attivato.

.A proposito di questa attività
Se si disattiva SMB 3.0, ONTAP disattiva anche SMB ODX. Se si riattiva SMB 3.0, è necessario riabilitare manualmente SMB ODX.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera che l'offload delle copie ODX sia... | Immettere il comando... 


 a| 
Attivato
 a| 
`vserver cifs options modify -vserver vserver_name -copy-offload-enabled true`



 a| 
Disattivato
 a| 
`vserver cifs options modify -vserver vserver_name -copy-offload-enabled false`

|===
. Tornare al livello di privilegio admin: `set -privilege admin`


.Esempio
Il seguente esempio consente l'offload delle copie ODX su SVM vs1:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -copy-offload-enabled true

cluster1::*> set -privilege admin
----
.Informazioni correlate
xref:server-options-reference.adoc[Opzioni server SMB disponibili]
