---
permalink: smb-admin/enable-ipv6-task.html 
sidebar: sidebar 
keywords: ipv6, network, enable, cluster, setup, administrator, smb, enable ipv6 for smb, cluster administrator only 
summary: 'Le reti IPv6 non sono abilitate durante l"installazione del cluster. Per utilizzare IPv6 per SMB, un amministratore del cluster deve abilitare IPv6 al termine della configurazione del cluster. Quando l"amministratore del cluster attiva IPv6, viene attivato per l"intero cluster.' 
---
= Abilitare IPv6 per SMB (solo amministratori di cluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le reti IPv6 non sono abilitate durante l'installazione del cluster. Per utilizzare IPv6 per SMB, un amministratore del cluster deve abilitare IPv6 al termine della configurazione del cluster. Quando l'amministratore del cluster attiva IPv6, viene attivato per l'intero cluster.

.Fase
. Attiva IPv6: `network options ipv6 modify -enabled true`
+
Per ulteriori informazioni sull'attivazione di IPv6 nel cluster e sulla configurazione di LIF IPv6, consultare la _Guida alla gestione di rete_.

+
IPv6 è attivato. È possibile configurare le LIF dei dati IPv6 per l'accesso SMB.



.Informazioni correlate
xref:monitor-display-ipv6-sessions-task.adoc[Monitoraggio e visualizzazione delle informazioni sulle sessioni SMB IPv6]

link:../networking/networking_reference.html["Gestione della rete"]
