---
permalink: smb-admin/enable-disable-multidomain-name-mapping-searches-task.html 
sidebar: sidebar 
keywords: multidomain, name, mapping, search, wild, card, domain, portion, windows, configure, configuring, unix, user, bidirectional, enable, disable, enable or disable multidomain name mapping searches 
summary: 'Con le ricerche di mappatura dei nomi di più domini, è possibile utilizzare un carattere jolly (*) nella parte di dominio di un nome Windows quando si configura l"associazione di utenti UNIX con nomi utente Windows. L"utilizzo di un wild card (*) nella parte di dominio del nome consente a ONTAP di cercare tutti i domini con un trust bidirezionale con il dominio che contiene l"account del computer del server CIFS.' 
---
= Attivare o disattivare le ricerche di mapping dei nomi multidominio SMB in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con le ricerche di mappatura dei nomi di più domini, è possibile utilizzare un carattere jolly (*) nella parte di dominio di un nome Windows quando si configura l'associazione di utenti UNIX con nomi utente Windows. L'utilizzo di un wild card (*) nella parte di dominio del nome consente a ONTAP di cercare tutti i domini con un trust bidirezionale con il dominio che contiene l'account del computer del server CIFS.

.A proposito di questa attività
In alternativa alla ricerca di tutti i domini con attendenza bidirezionale, è possibile configurare un elenco di domini attendibili preferiti. Quando viene configurato un elenco di domini trusted preferiti, ONTAP utilizza l'elenco di domini trusted preferito invece dei domini trusted bidirezionalmente rilevati per eseguire ricerche di mappatura dei nomi a più domini.

* Per impostazione predefinita, le ricerche di mappatura dei nomi multidominio sono attivate.
* Questa opzione è disponibile al livello di privilegio avanzato.


.Fasi
. Impostare il livello di privilegio su Advanced (avanzato): `set -privilege advanced`
. Eseguire una delle seguenti operazioni:
+
|===
| Se si desidera che le ricerche di mappatura dei nomi di più domini siano... | Immettere il comando... 


 a| 
Attivato
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-trusted-domain-enum-search-enabled true`



 a| 
Disattivato
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-trusted-domain-enum-search-enabled false`

|===
. Tornare al livello di privilegio admin: `set -privilege admin`


.Informazioni correlate
xref:server-options-reference.adoc[Opzioni server SMB disponibili]
