---
permalink: smb-admin/export-rules-concept.html 
sidebar: sidebar 
keywords: export, rule, functional, element, policy, match, client, access, request, parameter, how export rules work 
summary: Le regole di esportazione sono gli elementi funzionali di una policy di esportazione. Le regole di esportazione consentono di associare le richieste di accesso client a un volume a parametri specifici configurati per determinare come gestire le richieste di accesso client. 
---
= Come funzionano le regole di esportazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le regole di esportazione sono gli elementi funzionali di una policy di esportazione. Le regole di esportazione consentono di associare le richieste di accesso client a un volume a parametri specifici configurati per determinare come gestire le richieste di accesso client.

Un criterio di esportazione deve contenere almeno una regola di esportazione per consentire l'accesso ai client. Se un criterio di esportazione contiene più di una regola, le regole vengono elaborate nell'ordine in cui appaiono nel criterio di esportazione. L'ordine delle regole è determinato dal numero di indice delle regole. Se una regola corrisponde a un client, vengono utilizzate le autorizzazioni di tale regola e non vengono elaborate ulteriori regole. Se nessuna regola corrisponde, al client viene negato l'accesso.

È possibile configurare le regole di esportazione per determinare le autorizzazioni di accesso del client utilizzando i seguenti criteri:

* Il protocollo di accesso al file utilizzato dal client che invia la richiesta, ad esempio NFSv4 o SMB.
* Identificatore del client, ad esempio nome host o indirizzo IP.
+
La dimensione massima di `-clientmatch` il campo è composto da 4096 caratteri.

* Il tipo di protezione utilizzato dal client per autenticare, ad esempio Kerberos v5, NTLM o AUTH_SYS.


Se una regola specifica più criteri, il client deve corrispondere a tutti i criteri affinché la regola venga applicata.

.Esempio
Il criterio di esportazione contiene una regola di esportazione con i seguenti parametri:

* `-protocol` `nfs3`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `any`
* `-rwrule` `any`


La richiesta di accesso client viene inviata utilizzando il protocollo NFSv3 e il client ha l'indirizzo IP 10.1.17.37.

Anche se il protocollo di accesso client corrisponde, l'indirizzo IP del client si trova in una subnet diversa da quella specificata nella regola di esportazione. Pertanto, la corrispondenza dei client non riesce e questa regola non si applica a questo client.

.Esempio
Il criterio di esportazione contiene una regola di esportazione con i seguenti parametri:

* `-protocol` `nfs`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `any`
* `-rwrule` `any`


La richiesta di accesso client viene inviata utilizzando il protocollo NFSv4 e il client ha l'indirizzo IP 10.1.16.54.

Il protocollo di accesso client corrisponde e l'indirizzo IP del client si trova nella subnet specificata. Pertanto, la corrispondenza dei client viene eseguita correttamente e questa regola si applica a questo client. Il client ottiene l'accesso in lettura/scrittura indipendentemente dal tipo di protezione.

.Esempio
Il criterio di esportazione contiene una regola di esportazione con i seguenti parametri:

* `-protocol` `nfs3`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `any`
* `-rwrule` `krb5,ntlm`


Il client n. 1 ha l'indirizzo IP 10.1.16.207, invia una richiesta di accesso utilizzando il protocollo NFSv3 e viene autenticato con Kerberos v5.

Il client n. 2 ha l'indirizzo IP 10.1.16.211, invia una richiesta di accesso utilizzando il protocollo NFSv3 e viene autenticato con AUTH_SYS.

Il protocollo di accesso client e l'indirizzo IP corrispondono per entrambi i client. Il parametro di sola lettura consente l'accesso in sola lettura a tutti i client, indipendentemente dal tipo di protezione con cui sono stati autenticati. Pertanto, entrambi i client ottengono l'accesso in sola lettura. Tuttavia, solo il client n. 1 ottiene l'accesso in lettura/scrittura perché per l'autenticazione è stato utilizzato il tipo di protezione approvato Kerberos v5. Il client n. 2 non ottiene l'accesso in lettura/scrittura.
