---
permalink: smb-admin/file-locking-between-protocols-concept.html 
sidebar: sidebar 
keywords: file, lock, method, use, client, application, prevent, user, access, open, ontap, protocol, about file locking between protocols 
summary: Il blocco dei file è un metodo utilizzato dalle applicazioni client per impedire a un utente di accedere a un file precedentemente aperto da un altro utente. Il modo in cui ONTAP blocca i file dipende dal protocollo del client. 
---
= Informazioni sul blocco dei file tra protocolli
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il blocco dei file è un metodo utilizzato dalle applicazioni client per impedire a un utente di accedere a un file precedentemente aperto da un altro utente. Il modo in cui ONTAP blocca i file dipende dal protocollo del client.

Se il client è un client NFS, i blocchi sono avvisi; se il client è un client SMB, i blocchi sono obbligatori.

A causa delle differenze tra i blocchi di file NFS e SMB, un client NFS potrebbe non riuscire ad accedere a un file precedentemente aperto da un'applicazione SMB.

Quando un client NFS tenta di accedere a un file bloccato da un'applicazione SMB, si verifica quanto segue:

* In volumi misti o NTFS, operazioni di manipolazione dei file come `rm`, `rmdir`, e. `mv` Può causare il malfunzionamento dell'applicazione NFS.
* Le operazioni di lettura e scrittura NFS sono negate rispettivamente dalle modalità aperta di negazione-lettura e di negazione-scrittura di SMB.
* Le operazioni di scrittura NFS non riescono quando l'intervallo scritto del file è bloccato con un esclusivo bytelock SMB.
* Scollega
+
** Per i file system NTFS, sono supportate operazioni di eliminazione SMB e CIFS.
+
Il file verrà rimosso dopo l'ultima chiusura.

** Le operazioni di scollegamento NFS non sono supportate.
+
Non è supportato perché sono necessarie semantiche NTFS e SMB e l'ultima operazione Delete-on-Close non è supportata per NFS.

** Per i filesystem UNIX, è supportata l'operazione di scollegamento.
+
È supportato perché sono richieste semantiche NFS e UNIX.



* Rinominare
+
** Per i file system NTFS, se il file di destinazione viene aperto da SMB o CIFS, il file di destinazione può essere rinominato.
** La ridenominazione NFS non è supportata.
+
Non è supportato perché sono necessarie semantiche NTFS e SMB.





Nei volumi UNIX di sicurezza, le operazioni di sconnessione e ridenominazione NFS ignorano lo stato di blocco SMB e consentono l'accesso al file. Tutte le altre operazioni NFS sui volumi UNIX di sicurezza rispettano lo stato di blocco SMB.
