---
permalink: smb-admin/folder-redirection-store-data-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, folder, redirection, enable, administrator, redirect, location, cifs, server, windows, client, store, smb, share, use folder redirection to store data on a cifs server 
summary: ONTAP supporta il reindirizzamento delle cartelle Microsoft, che consente agli utenti o agli amministratori di reindirizzare il percorso di una cartella locale a una posizione sul server CIFS. Sembra che le cartelle reindirizzate siano memorizzate sul client Windows locale, anche se i dati sono memorizzati in una condivisione SMB. 
---
= Scopri come utilizzare il reindirizzamento delle cartelle per archiviare i dati sui server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporta il reindirizzamento delle cartelle Microsoft, che consente agli utenti o agli amministratori di reindirizzare il percorso di una cartella locale a una posizione sul server CIFS. Sembra che le cartelle reindirizzate siano memorizzate sul client Windows locale, anche se i dati sono memorizzati in una condivisione SMB.

Il reindirizzamento delle cartelle è destinato principalmente alle organizzazioni che hanno già implementato le home directory e che desiderano mantenere la compatibilità con l'ambiente di home directory esistente.

* `Documents`, `Desktop`, e. `Start Menu` sono esempi di cartelle che è possibile reindirizzare.
* Gli utenti possono reindirizzare le cartelle dal client Windows.
* Gli amministratori possono configurare e gestire centralmente il reindirizzamento delle cartelle configurando gli oggetti Criteri di gruppo in Active Directory.
* Se gli amministratori hanno configurato i profili di roaming, il reindirizzamento delle cartelle consente agli amministratori di dividere i dati degli utenti dai dati del profilo.
* Gli amministratori possono utilizzare il reindirizzamento delle cartelle e i file offline insieme per reindirizzare lo storage dei dati per le cartelle locali al server CIFS, consentendo allo stesso tempo agli utenti di memorizzare il contenuto nella cache locale.


.Informazioni correlate
xref:offline-files-allow-caching-concept.adoc[Utilizzo di file offline per consentire il caching dei file per l'utilizzo offline]

xref:roaming-profiles-store-user-profiles-concept.adoc[Utilizzo di profili roaming per memorizzare i profili utente centralmente su un server CIFS associato a SVM]
