---
permalink: smb-admin/home-directory-shares-unique-user-names-concept.html 
sidebar: sidebar 
keywords: careful, assign, unique, user, name, creating, create, home, directory, share, windows, user, name, unix, variable, generate, dynamic, share, map, home directory shares require unique user names 
summary: 'Prestare attenzione a assegnare nomi utente univoci quando si creano condivisioni home directory utilizzando le variabili %w (nome utente Windows) o %u (nome utente UNIX) per generare condivisioni in modo dinamico. Il nome della condivisione viene associato al nome utente.' 
---
= Le condivisioni della home directory richiedono nomi utente univoci
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fare attenzione a assegnare nomi utente univoci quando si creano condivisioni home directory utilizzando `%w` (Nome utente Windows) o. `%u` (Nome utente UNIX) variabili per generare condivisioni in modo dinamico. Il nome della condivisione viene associato al nome utente.

Quando il nome di una condivisione statica e il nome di un utente sono identici, possono verificarsi due problemi:

* Quando l'utente elenca le condivisioni su un cluster utilizzando `net view` vengono visualizzate due condivisioni con lo stesso nome utente.
* Quando l'utente si connette a tale nome di condivisione, l'utente è sempre connesso alla condivisione statica e non può accedere alla condivisione della home directory con lo stesso nome.


Ad esempio, esiste una condivisione denominata "`Administrator`" e si dispone di un nome utente Windows "`Administrator`". Se si crea una condivisione home directory e ci si connette a tale condivisione, si viene connessi alla condivisione statica "`Administrator`" e non alla condivisione home directory "`Administrator`".

Per risolvere il problema relativo ai nomi di condivisione duplicati, procedere come segue:

* Ridenominazione della condivisione statica in modo che non sia più in conflitto con la condivisione della home directory dell'utente.
* Assegnare all'utente un nuovo nome utente in modo che non sia più in conflitto con il nome di condivisione statico.
* Creazione di una condivisione della home directory CIFS con un nome statico come "`home`" invece di utilizzare `%w` per evitare conflitti con i nomi di condivisione.

