---
permalink: smb-admin/how-ontap-creates-file-directory-names-concept.html 
sidebar: sidebar 
keywords: ontap, create, maintain, name, file, directories, directory, access, smb, format, how ontap creates file and directory names 
summary: 'ONTAP crea e mantiene due nomi per i file o le directory in qualsiasi directory che ha accesso da un client SMB: Il nome lungo originale e un nome in formato 8.3.' 
---
= Come ONTAP crea i nomi di file e directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP crea e mantiene due nomi per i file o le directory in qualsiasi directory che ha accesso da un client SMB: Il nome lungo originale e un nome in formato 8.3.

Per i nomi di file o directory che superano il nome di otto caratteri o il limite di estensione di tre caratteri (per i file), ONTAP genera un nome in formato 8.3 come segue:

* Il nome del file o della directory originale viene troncato a sei caratteri, se il nome supera i sei caratteri.
* Aggiunge una tilde (~) e un numero, da uno a cinque, ai nomi di file o directory che non sono più univoci dopo essere stati troncati.
+
Se esaurisce i numeri perché ci sono più di cinque nomi simili, crea un nome unico che non ha alcuna relazione con il nome originale.

* Nel caso dei file, l'estensione del nome del file viene troncata a tre caratteri.


Ad esempio, se un client NFS crea un file denominato `specifications.html`, Il nome del file di formato 8.3 creato da ONTAP è `specif~1.htm`. Se questo nome esiste già, ONTAP utilizza un numero diverso alla fine del nome del file. Ad esempio, se un client NFS crea un altro file denominato `specifications_new.html`, il formato 8.3 di `specifications_new.html` è `specif~2.htm`.
