---
permalink: smb-admin/index.html 
sidebar: sidebar 
keywords: smb, cifs, protocol, file, access, overview 
summary: 'Le funzionalità di accesso ai file ONTAP sono disponibili per il protocollo SMB, ad esempio l"abilitazione di un server CIFS, la creazione di condivisioni e l"abilitazione dei servizi Microsoft.' 
---
= Panoramica SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le funzioni di accesso ai file ONTAP sono disponibili per il protocollo SMB. È possibile attivare un server CIFS, creare condivisioni e abilitare i servizi Microsoft.

[NOTE]
====
_SMB_ (Server message Block) si riferisce ai dialetti moderni del protocollo CIFS (Common Internet file System). L'interfaccia della riga di comando (CLI) di ONTAP e i tool di gestione di OnCommand sono ancora visibili in _CIFS_.

====
Attenersi alle seguenti procedure nei seguenti casi:

* Vuoi comprendere la gamma di funzionalità del protocollo SMB di ONTAP.
* Si desidera eseguire attività di configurazione e manutenzione meno comuni, non la configurazione SMB di base.
* Si desidera utilizzare l'interfaccia della riga di comando (CLI), non System Manager o uno strumento di scripting automatico.

