---
permalink: smb-admin/install-self-signed-root-ca-certificate-svm-task.html 
sidebar: sidebar 
keywords: ldap, authentication, tls, bind, server, install, self-signed, root, ca, certificate, svm, install the self-signed root ca certificate on the svm 
summary: 'Se è richiesta l"autenticazione LDAP con TLS durante l"associazione ai server LDAP, è necessario installare prima il certificato della CA principale autofirmato su SVM.' 
---
= Installare certificati CA root autofirmati sulla SVM SMB di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è richiesta l'autenticazione LDAP con TLS durante l'associazione ai server LDAP, è necessario installare prima il certificato della CA principale autofirmato su SVM.

.A proposito di questa attività
Tutte le applicazioni di ONTAP che utilizzano le comunicazioni TLS possono controllare lo stato dei certificati digitali utilizzando il protocollo OCSP (Online Certificate Status Protocol). Se OCSP è abilitato per LDAP su TLS, i certificati revocati vengono rifiutati e la connessione non riesce.

.Fasi
. Installare il certificato della CA principale autofirmato:
+
.. Avviare l'installazione del certificato: `security certificate install -vserver vserver_name -type server-ca`
+
L'output della console visualizza il seguente messaggio: `Please enter Certificate: Press <Enter> when done`

.. Aprire il certificato `.pem` copiare il certificato con un editor di testo, incluse le righe che iniziano con `-----BEGIN CERTIFICATE-----` e terminando con `-----END CERTIFICATE-----`, quindi incollare il certificato dopo il prompt dei comandi.
.. Verificare che il certificato sia visualizzato correttamente.
.. Completare l'installazione premendo Invio.


. Verificare che il certificato sia installato: `security certificate show -vserver _vserver_name_`

