---
permalink: smb-admin/ldap-signing-sealing-concepts-concept.html 
sidebar: sidebar 
keywords: ontap, configure, sign, seal, enable, ldap, session, security, active, directory, ad, server, cifs, setting, storage, virtual, machine, svm, ldap signing and sealing concepts 
summary: 'A partire da ONTAP 9, è possibile configurare la firma e il sealing per abilitare la sicurezza della sessione LDAP sulle query a un server Active Directory (ad). È necessario configurare le impostazioni di sicurezza del server CIFS sulla macchina virtuale di storage (SVM) in modo che corrispondano a quelle del server LDAP.' 
---
= Ulteriori informazioni sulla firma e la crittografia LDAP SMB di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9, è possibile configurare la firma e il sealing per abilitare la sicurezza della sessione LDAP sulle query a un server Active Directory (ad). È necessario configurare le impostazioni di sicurezza del server CIFS sulla macchina virtuale di storage (SVM) in modo che corrispondano a quelle del server LDAP.

La firma conferma l'integrità dei dati del payload LDAP utilizzando la tecnologia a chiave segreta. Il sealing crittografa i dati del payload LDAP per evitare la trasmissione di informazioni sensibili in testo non crittografato. Un'opzione _LDAP Security Level_ indica se il traffico LDAP deve essere firmato, firmato e sigillato o no. L'impostazione predefinita è `none`.

La firma e il sealing LDAP sul traffico CIFS sono attivati sulla SVM con `-session-security-for-ad-ldap` al `vserver cifs security modify` comando.
