---
permalink: smb-admin/list-supported-privileges-reference.html 
sidebar: sidebar 
keywords: ontap, predefined, support, privilege, local, group, add, user, exist, domain, list of supported privileges 
summary: ONTAP dispone di un set predefinito di privilegi supportati. Per impostazione predefinita, alcuni gruppi locali predefiniti dispongono di alcuni di questi privilegi. È inoltre possibile aggiungere o rimuovere privilegi dai gruppi predefiniti o creare nuovi utenti o gruppi locali e aggiungere privilegi ai gruppi creati o a utenti e gruppi di dominio esistenti. 
---
= Elenco dei privilegi supportati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP dispone di un set predefinito di privilegi supportati. Per impostazione predefinita, alcuni gruppi locali predefiniti dispongono di alcuni di questi privilegi. È inoltre possibile aggiungere o rimuovere privilegi dai gruppi predefiniti o creare nuovi utenti o gruppi locali e aggiungere privilegi ai gruppi creati o a utenti e gruppi di dominio esistenti.

La seguente tabella elenca i privilegi supportati sulla macchina virtuale di storage (SVM) e fornisce un elenco di gruppi BUILTIN con privilegi assegnati:

|===
| Nome privilegio | Impostazione di sicurezza predefinita | Descrizione 


 a| 
`SeTcbPrivilege`
 a| 
Nessuno
 a| 
Agire come parte del sistema operativo



 a| 
`SeBackupPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Eseguire il backup di file e directory, sovrascrivendo eventuali ACL



 a| 
`SeRestorePrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Ripristinare file e directory, sovrascrivendo gli ACL, impostare qualsiasi SID utente o gruppo valido come proprietario del file



 a| 
`SeTakeOwnershipPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Assumere la proprietà di file o altri oggetti



 a| 
`SeSecurityPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Gestire l'auditingQuesto include la visualizzazione, l'eliminazione e la cancellazione del registro di sicurezza.



 a| 
`SeChangeNotifyPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`, `BUILTIN\Power Users`, `BUILTIN\Users`, `Everyone`
 a| 
Ignora controllo incrociato gli utenti con questo privilegio non devono disporre di permessi di attraversamento (x) per attraversare cartelle, collegamenti simbolici o giunzioni.

|===
.Informazioni correlate
* xref:assign-privileges-concept.adoc[Assegnare privilegi locali]
* xref:configure-bypass-traverse-checking-concept.adoc[Configurazione del controllo incrociato bypass]

