---
permalink: smb-admin/local-users-groups-concepts-concept.html 
sidebar: sidebar 
keywords: local, user, group, basic, information, determine, determining, configure, environment, local users and groups concepts 
summary: Prima di stabilire se configurare e utilizzare utenti e gruppi locali nel proprio ambiente, è necessario conoscere gli utenti e i gruppi locali e alcune informazioni di base. 
---
= Concetti relativi a utenti e gruppi locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di stabilire se configurare e utilizzare utenti e gruppi locali nel proprio ambiente, è necessario conoscere gli utenti e i gruppi locali e alcune informazioni di base.

* *Utente locale*
+
Un account utente con un identificatore di protezione univoco (SID) che ha visibilità solo sulla macchina virtuale di storage (SVM) su cui è creato. Gli account utente locali dispongono di una serie di attributi, tra cui nome utente e SID. Un account utente locale esegue l'autenticazione locale sul server CIFS utilizzando l'autenticazione NTLM.

+
Gli account utente possono essere utilizzati in diversi modi:

+
** Utilizzato per concedere privilegi di _User Rights Management_ a un utente.
** Utilizzato per controllare l'accesso a livello di condivisione e di file alle risorse di file e cartelle di proprietà della SVM.


* *Gruppo locale*
+
Un gruppo con un SID univoco ha visibilità solo sulla SVM su cui è creato. I gruppi contengono un insieme di membri. I membri possono essere utenti locali, utenti di dominio, gruppi di dominio e account di computer di dominio. I gruppi possono essere creati, modificati o cancellati.

+
I gruppi hanno diversi utilizzi:

+
** Utilizzato per concedere privilegi a _User Rights Management_ ai propri membri.
** Utilizzato per controllare l'accesso a livello di condivisione e di file alle risorse di file e cartelle di proprietà della SVM.


* *Dominio locale*
+
Dominio con ambito locale, delimitato dalla SVM. Il nome del dominio locale è il nome del server CIFS. Gli utenti e i gruppi locali sono contenuti all'interno del dominio locale.

* *Identificatore di sicurezza (SID)*
+
Un SID è un valore numerico di lunghezza variabile che identifica le entità di protezione di tipo Windows. Ad esempio, un SID tipico assume la seguente forma: S-1-5-21-3139654847-1303905135-2517279418-123456.

* *Autenticazione NTLM*
+
Metodo di protezione Microsoft Windows utilizzato per autenticare gli utenti su un server CIFS.

* *Cluster Replicated Database (RDB)*
+
Database replicato con un'istanza su ciascun nodo di un cluster. Gli oggetti utente e gruppo locali vengono memorizzati nell'RDB.


