---
permalink: smb-admin/local-users-groups-when-deleting-servers-concept.html 
sidebar: sidebar 
keywords: default, set, local, user, group, cifs, server, associate, svm, administrator, create, delete, what happens to local users and groups when deleting cifs servers 
summary: 'Il set predefinito di utenti e gruppi locali viene creato quando viene creato un server CIFS e sono associati alla macchina virtuale di storage (SVM) che ospita il server CIFS. Gli amministratori di SVM possono creare utenti e gruppi locali in qualsiasi momento. È necessario essere consapevoli di ciò che accade agli utenti e ai gruppi locali quando si elimina il server CIFS.' 
---
= Cosa accade agli utenti e ai gruppi locali quando si eliminano i server CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il set predefinito di utenti e gruppi locali viene creato quando viene creato un server CIFS e sono associati alla macchina virtuale di storage (SVM) che ospita il server CIFS. Gli amministratori di SVM possono creare utenti e gruppi locali in qualsiasi momento. È necessario essere consapevoli di ciò che accade agli utenti e ai gruppi locali quando si elimina il server CIFS.

Gli utenti e i gruppi locali sono associati alle SVM; pertanto, non vengono cancellati quando i server CIFS vengono cancellati a causa di considerazioni di sicurezza. Anche se gli utenti e i gruppi locali non vengono cancellati quando il server CIFS viene cancellato, essi sono nascosti. Non è possibile visualizzare o gestire utenti e gruppi locali fino a quando non viene ricreato un server CIFS su SVM.

[NOTE]
====
Lo stato amministrativo del server CIFS non influisce sulla visibilità degli utenti o dei gruppi locali.

====