---
permalink: smb-admin/manage-smb-level-acls-concept.html 
sidebar: sidebar 
keywords: change, share-level, acl, user, access, right, share, configure, windows, unix, group, guidelines for managing smb share-level acls 
summary: È possibile modificare gli ACL a livello di condivisione per offrire agli utenti più o meno diritti di accesso alla condivisione. È possibile configurare ACL a livello di condivisione utilizzando utenti e gruppi Windows o utenti e gruppi UNIX. 
---
= Linee guida per la gestione degli ACL a livello di condivisione SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare gli ACL a livello di condivisione per offrire agli utenti più o meno diritti di accesso alla condivisione. È possibile configurare ACL a livello di condivisione utilizzando utenti e gruppi Windows o utenti e gruppi UNIX.

Per impostazione predefinita, l'ACL a livello di condivisione fornisce il controllo completo del gruppo standard denominato Everyone. Il controllo completo nell'ACL significa che tutti gli utenti del dominio e tutti i domini trusted hanno accesso completo alla condivisione. È possibile controllare il livello di accesso per un ACL a livello di condivisione utilizzando link:../smb-admin/create-share-access-control-lists-task.html["Console di gestione Microsoft (MMC) su un client Windows o sulla riga di comando ONTAP"].

Quando si utilizza MMC, si applicano le seguenti linee guida:

* I nomi utente e gruppo specificati devono essere nomi Windows.
* È possibile specificare solo le autorizzazioni di Windows.


Quando si utilizza la riga di comando ONTAP, si applicano le seguenti linee guida:

* I nomi utente e gruppo specificati possono essere nomi Windows o UNIX.
+
Se durante la creazione o la modifica degli ACL non viene specificato un tipo di utente e gruppo, il tipo predefinito è utenti e gruppi Windows.

* È possibile specificare solo le autorizzazioni di Windows.

