---
permalink: smb-admin/manage-netbios-aliases-concept.html 
sidebar: sidebar 
keywords: netbios, alternative, name, smb, client, configuring, configure, consolidate, consolidating, data, original, file, server, manage netbios aliases for smb servers 
summary: Gli alias NetBIOS sono nomi alternativi per il server SMB che i client SMB possono utilizzare quando si connettono al server SMB. La configurazione degli alias NetBIOS per un server SMB può essere utile quando si consolidano i dati provenienti da altri file server nel server SMB e si desidera che il server SMB risponda ai nomi dei file server originali. 
---
= Informazioni sulla gestione degli alias NetBIOS per server SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli alias NetBIOS sono nomi alternativi per il server SMB che i client SMB possono utilizzare quando si connettono al server SMB. La configurazione degli alias NetBIOS per un server SMB può essere utile quando si consolidano i dati da altri file server nel server SMB e si desidera che il server SMB risponda ai nomi dei file server originali.

È possibile specificare un elenco di alias NetBIOS quando si crea il server SMB o in qualsiasi momento dopo la creazione del server SMB. È possibile aggiungere o rimuovere alias NetBIOS dall'elenco in qualsiasi momento. È possibile connettersi al server SMB utilizzando uno dei nomi presenti nell'elenco degli alias NetBIOS.

.Informazioni correlate
xref:display-netbios-over-tcp-connections-task.adoc[Visualizzazione di informazioni su connessioni NetBIOS su TCP]
