---
permalink: smb-admin/modify-local-groups-reference.html 
sidebar: sidebar 
keywords: modify, exist, local, group, description, exist, local, group, renaming, rename, modify local groups 
summary: È possibile modificare i gruppi locali esistenti modificando la descrizione di un gruppo locale esistente o rinominando il gruppo. 
---
= Modificare i gruppi SMB ONTAP locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare i gruppi locali esistenti modificando la descrizione di un gruppo locale esistente o rinominando il gruppo.

|===
| Se si desidera... | Utilizzare il comando... 


 a| 
Modificare la descrizione del gruppo locale
 a| 
`vserver cifs users-and-groups local-group modify -vserver _vserver_name_ -group-name _group_name_ -description text` Se la descrizione contiene uno spazio, deve essere racchiusa tra virgolette doppie.



 a| 
Rinominare il gruppo locale
 a| 
`vserver cifs users-and-groups local-group rename -vserver _vserver_name_ -group-name _group_name_ -new-group-name _new_group_name_`

|===
.Esempi
Nell'esempio seguente il gruppo locale "`CIFS_SERVER` Engineering`" viene rinomina in "`CIFS_SERVER Engineering_New":

[listing]
----
cluster1::> vserver cifs users-and-groups local-group rename -vserver vs1 -group-name CIFS_SERVER\engineering -new-group-name CIFS_SERVER\engineering_new
----
Nell'esempio seguente viene modificata la descrizione del gruppo locale "`CIFS_SERVER` engineering":

[listing]
----
cluster1::> vserver cifs users-and-groups local-group modify -vserver vs1 -group-name CIFS_SERVER\engineering -description "New Description"
----