---
permalink: smb-admin/modify-local-user-accounts-reference.html 
sidebar: sidebar 
keywords: modify, local, user, account, change, exist, name, description, enable, disable, rename, compromise, administrative, modify local user accounts 
summary: 'È possibile modificare un account utente locale se si desidera modificare il nome completo o la descrizione di un utente esistente e se si desidera attivare o disattivare l"account utente. È inoltre possibile rinominare un account utente locale se il nome dell"utente è compromesso o se è necessario modificare il nome per scopi amministrativi.' 
---
= Modificare gli account utente SMB ONTAP locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare un account utente locale se si desidera modificare il nome completo o la descrizione di un utente esistente e se si desidera attivare o disattivare l'account utente. È inoltre possibile rinominare un account utente locale se il nome dell'utente è compromesso o se è necessario modificare il nome per scopi amministrativi.

|===
| Se si desidera... | Immettere il comando... 


 a| 
Modificare il nome completo dell'utente locale
 a| 
`vserver cifs users-and-groups local-user modify -vserver _vserver_name_ -user-name _user_name_ ‑full-name text` Se il nome completo contiene uno spazio, deve essere racchiuso tra virgolette doppie.



 a| 
Modificare la descrizione dell'utente locale
 a| 
`vserver cifs users-and-groups local-user modify -vserver _vserver_name_ -user-name _user_name_ ‑description text` Se la descrizione contiene uno spazio, deve essere racchiusa tra virgolette doppie.



 a| 
Attivare o disattivare l'account utente locale
 a| 
`vserver cifs users-and-groups local-user modify -vserver _vserver_name_ -user-name _user_name_ -is-account-disabled {true|false}`



 a| 
Rinominare l'account utente locale
 a| 
`vserver cifs users-and-groups local-user rename -vserver _vserver_name_ -user-name _user_name_ -new-user-name _new_user_name_` Quando si rinomina un utente locale, il nuovo nome utente deve rimanere associato allo stesso server CIFS del vecchio nome utente.

|===
.Esempio
Nell'esempio seguente l'utente locale "`CIFS_SERVER` sue`" viene rinomina in "`CIFS_SERVER sue_new" sulla macchina virtuale di storage (SVM, precedentemente nota come Vserver) vs1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-user rename -user-name CIFS_SERVER\sue -new-user-name CIFS_SERVER\sue_new -vserver vs1
----