---
permalink: smb-admin/monitor-display-ipv6-sessions-task.html 
sidebar: sidebar 
keywords: monitor, display, information, smb, session, ipv6, determining, determine, monitor and display information about ipv6 smb sessions 
summary: È possibile monitorare e visualizzare le informazioni sulle sessioni SMB connesse tramite reti IPv6. Queste informazioni sono utili per determinare quali client si connettono utilizzando IPv6 e altre informazioni utili sulle sessioni SMB IPv6. 
---
= Monitorare e visualizzare informazioni sulle sessioni SMB IPv6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile monitorare e visualizzare le informazioni sulle sessioni SMB connesse tramite reti IPv6. Queste informazioni sono utili per determinare quali client si connettono utilizzando IPv6 e altre informazioni utili sulle sessioni SMB IPv6.

.Fase
. Eseguire l'azione desiderata:
+
|===
| Se si desidera determinare se... | Immettere il comando... 


 a| 
Le sessioni SMB a una macchina virtuale di storage (SVM) sono connesse tramite IPv6
 a| 
`vserver cifs session show -vserver _vserver_name_ -instance`



 a| 
IPv6 viene utilizzato per le sessioni SMB attraverso un indirizzo LIF specificato
 a| 
`vserver cifs session show -vserver _vserver_name_ -lif-address _LIF_IP_address_ -instance`

`_LIF_IP_address_` È l'indirizzo IPv6 del LIF dei dati.

|===

