---
permalink: smb-admin/monitor-security-policy-job-task.html 
sidebar: sidebar 
keywords: apply, security, policy, storage, virtual, machine, svm, monitor, progress, policy, job, ascertain, application, long-running, bulk, security, file, folder, monitor the security policy job 
summary: 'Quando si applica la policy di sicurezza alle macchine virtuali di storage (SVM), è possibile monitorare l"avanzamento dell"attività monitorando il processo di policy di sicurezza. Ciò è utile se si desidera verificare che l"applicazione del criterio di protezione sia riuscita. Questo è utile anche se si dispone di un processo a esecuzione prolungata in cui si applica la protezione in blocco a un gran numero di file e cartelle.' 
---
= Monitorare i lavori di policy di sicurezza ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si applica la policy di sicurezza alle macchine virtuali di storage (SVM), è possibile monitorare l'avanzamento dell'attività monitorando il processo di policy di sicurezza. Ciò è utile se si desidera verificare che l'applicazione del criterio di protezione sia riuscita. Questo è utile anche se si dispone di un processo a esecuzione prolungata in cui si applica la protezione in blocco a un gran numero di file e cartelle.

.A proposito di questa attività
Per visualizzare informazioni dettagliate su un processo di policy di sicurezza, utilizzare `-instance` parametro.

.Fase
. Monitorare il processo di policy di sicurezza: `vserver security file-directory job show -vserver vserver_name`
+
`vserver security file-directory job show -vserver vs1`

+
[listing]
----

Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
53322  Fsecurity Apply      vs1        node1          Success
       Description: File Directory Security Apply Job
----

