---
permalink: smb-admin/ontap-treats-read-only-bits-concept.html 
sidebar: sidebar 
keywords: read-only, bit, file-by-file, basis, reflext, file, writable, disable, enable, how ontap treats read-only bits 
summary: 'Il bit di sola lettura viene impostato file per file per indicare se un file è scrivibile (disattivato) o di sola lettura (abilitato).' 
---
= Informazioni sui bit di sola lettura ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il bit di sola lettura viene impostato file per file per indicare se un file è scrivibile (disattivato) o di sola lettura (abilitato).

I client SMB che utilizzano Windows possono impostare un bit di sola lettura per ogni file. I client NFS non impostano un bit di sola lettura per ogni file perché i client NFS non eseguono operazioni di protocollo che utilizzano un bit di sola lettura per ogni file.

ONTAP può impostare un bit di sola lettura su un file quando un client SMB che utilizza Windows crea tale file. ONTAP può anche impostare un bit di sola lettura quando un file viene condiviso tra client NFS e client SMB. Alcuni software, se utilizzati dai client NFS e dai client SMB, richiedono l'abilitazione del bit di sola lettura.

Affinché ONTAP mantenga le autorizzazioni di lettura e scrittura appropriate su un file condiviso tra client NFS e client SMB, tratta il bit di sola lettura in base alle seguenti regole:

* NFS considera qualsiasi file con il bit di sola lettura abilitato come se non abbia alcun bit di permesso di scrittura abilitato.
* Se un client NFS disattiva tutti i bit di permesso di scrittura e almeno uno di questi bit era stato precedentemente attivato, ONTAP attiva il bit di sola lettura per quel file.
* Se un client NFS attiva qualsiasi bit di autorizzazione di scrittura, ONTAP disattiva il bit di sola lettura per quel file.
* Se il bit di sola lettura per un file è attivato e un client NFS tenta di rilevare le autorizzazioni per il file, i bit di autorizzazione per il file non vengono inviati al client NFS; invece, ONTAP invia i bit di autorizzazione al client NFS con i bit di autorizzazione di scrittura mascherati.
* Se il bit di sola lettura per un file è attivato e un client SMB disattiva il bit di sola lettura, ONTAP attiva il bit di autorizzazione di scrittura del proprietario per il file.
* I file con il bit di sola lettura abilitato sono scrivibili solo da root.


Il bit di sola lettura interagisce con i bit ACL e Unix Mode nei seguenti modi:

Quando il bit di sola lettura è impostato su un file:

* Non vengono apportate modifiche all'ACL per quel file. I client NFS vedranno lo stesso ACL che avevano prima dell'impostazione del bit di sola lettura.
* Tutti i bit della modalità Unix che consentono l'accesso in scrittura al file vengono ignorati.
* Sia i client NFS che SMB possono leggere il file, ma non modificarlo.
* Le ACL e i bit di modalità UNIX vengono ignorati a favore del bit di sola lettura. Ciò significa che anche se l'ACL consente l'accesso in scrittura, il bit di sola lettura impedisce le modifiche.


Quando il bit di sola lettura non è impostato su un file:

* ONTAP determina l'accesso in base ai bit della modalità ACL e UNIX.
+
** Se l'ACL o i bit della modalità UNIX negano l'accesso in scrittura, i client NFS e SMB non possono modificare il file.
** Se né l'ACL né i bit della modalità UNIX negano l'accesso in scrittura, i client NFS e SMB possono modificare il file.




[NOTE]
====
Le modifiche alle autorizzazioni dei file hanno effetto immediato sui client SMB, ma potrebbero non avere effetto immediato sui client NFS se il client NFS attiva il caching degli attributi.

====