---
permalink: smb-admin/reasons-invalidates-branchcache-hashes-concept.html 
sidebar: sidebar 
keywords: understand, ontap, invalidate, hash, branchcache, configuration, share, reasons ontap invalidates branchcache hashes 
summary: Comprendere i motivi per cui ONTAP invalida gli hash può essere utile durante la pianificazione della configurazione di BranchCache. Può aiutarti a decidere quale modalità operativa configurare e a scegliere quali condivisioni abilitare BranchCache. 
---
= Scopri i motivi per cui ONTAP SMB invalida gli hash BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Comprendere i motivi per cui ONTAP invalida gli hash può essere utile durante la pianificazione della configurazione di BranchCache. Può aiutarti a decidere quale modalità operativa configurare e a scegliere quali condivisioni abilitare BranchCache.

ONTAP deve gestire gli hash BranchCache per garantire la validità degli hash. Se un hash non è valido, ONTAP invalida l'hash e calcola un nuovo hash alla successiva richiesta del contenuto, presupponendo che BranchCache sia ancora abilitato.

ONTAP invalida gli hash per i seguenti motivi:

* La chiave del server viene modificata.
+
Se la chiave del server viene modificata, ONTAP invalida tutti gli hash nell'archivio hash.

* Un hash viene svuotato dalla cache perché è stata raggiunta la dimensione massima dell'archivio hash BranchCache.
+
Si tratta di un parametro sintonizzabile che può essere modificato per soddisfare i requisiti di business.

* Un file viene modificato tramite accesso SMB o NFS.
* Un file per il quale sono stati calcolati gli hash viene ripristinato utilizzando `snap restore` comando.
* Un volume che contiene condivisioni SMB abilitate a BranchCache viene ripristinato utilizzando `snap restore` comando.

