---
permalink: smb-admin/recover-files-folders-previous-versions-concept.html 
sidebar: sidebar 
keywords: ability, microsoft, previous, version, applicable, file, system, support, snapshot, copies, copy, form, enable, technolofy, integral, ontap, recover, file, recover files and folders using previous versions 
summary: La possibilità di utilizzare le versioni precedenti di Microsoft è applicabile ai file system che supportano le copie Snapshot in qualche forma e le hanno attivate. La tecnologia Snapshot è parte integrante di ONTAP. Gli utenti possono ripristinare file e cartelle dalle copie Snapshot dal client Windows utilizzando la funzionalità delle versioni precedenti di Microsoft. 
---
= Panoramica sul ripristino di file e cartelle utilizzando le versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La possibilità di utilizzare le versioni precedenti di Microsoft è applicabile ai file system che supportano le copie Snapshot in qualche forma e le hanno attivate. La tecnologia Snapshot è parte integrante di ONTAP. Gli utenti possono ripristinare file e cartelle dalle copie Snapshot dal client Windows utilizzando la funzionalità delle versioni precedenti di Microsoft.

La funzionalità delle versioni precedenti offre agli utenti un metodo per sfogliare le copie Snapshot o per ripristinare i dati da una copia Snapshot senza l'intervento di un amministratore dello storage. Le versioni precedenti non sono configurabili. È sempre attivato. Se l'amministratore dello storage ha reso disponibili copie Snapshot in una condivisione, l'utente può utilizzare le versioni precedenti per eseguire le seguenti attività:

* Recuperare i file cancellati accidentalmente.
* Ripristino della sovrascrittura accidentale di un file.
* Confronta le versioni del file mentre lavori.


I dati memorizzati nelle copie Snapshot sono di sola lettura. Gli utenti devono salvare una copia di un file in un'altra posizione per apportare eventuali modifiche al file. Le copie Snapshot vengono periodicamente eliminate; pertanto, gli utenti devono creare copie dei file contenuti nelle versioni precedenti se desiderano conservare una versione precedente di un file a tempo indeterminato.
