---
permalink: smb-admin/requirements-folder-redirection-concept.html 
sidebar: sidebar 
keywords: microsoft, folder, redirection, cifs, server, version, ontap, smb, windows, client, support, feature, requirements for using folder redirection, requirement 
summary: Prima di poter utilizzare il reindirizzamento delle cartelle Microsoft con il server CIFS, è necessario sapere quali versioni di ONTAP e SMB e quali client Windows supportano la funzionalità. 
---
= Requisiti per l'utilizzo del reindirizzamento delle cartelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di poter utilizzare il reindirizzamento delle cartelle Microsoft con il server CIFS, è necessario sapere quali versioni di ONTAP e SMB e quali client Windows supportano la funzionalità.



== Requisiti di versione di ONTAP

ONTAP supporta il reindirizzamento delle cartelle Microsoft.



== Requisiti di versione del protocollo SMB

Per le macchine virtuali di storage (SVM), ONTAP supporta il reindirizzamento delle cartelle Microsoft su tutte le versioni di SMB.



== Requisiti del client Windows

Prima che un utente possa utilizzare il reindirizzamento delle cartelle di Microsoft, il client Windows deve supportare questa funzionalità.

Per informazioni aggiornate sui client Windows che supportano il reindirizzamento delle cartelle, consultare la matrice di interoperabilità.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]
