---
permalink: smb-admin/reset-rediscovering-servers-task.html 
sidebar: sidebar 
keywords: reset, discover, rediscover, server, cifs, server, discard, store, information, ldap, domain, controller, information, external, respond, reset and rediscover servers 
summary: La reimpostazione e la riscoperta dei server sul server CIFS consentono al server CIFS di eliminare le informazioni memorizzate sui server LDAP e sui controller di dominio. Dopo aver scartato le informazioni sul server, il server CIFS acquisisce nuovamente le informazioni correnti su questi server esterni. Questa operazione può essere utile quando i server connessi non rispondono in modo appropriato. 
---
= Reimpostare e riscoprire i server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La reimpostazione e la riscoperta dei server sul server CIFS consentono al server CIFS di eliminare le informazioni memorizzate sui server LDAP e sui controller di dominio. Dopo aver scartato le informazioni sul server, il server CIFS acquisisce nuovamente le informazioni correnti su questi server esterni. Questa operazione può essere utile quando i server connessi non rispondono in modo appropriato.

.Fasi
. Immettere il seguente comando: `vserver cifs domain discovered-servers reset-servers -vserver _vserver_name_`
. Visualizzare le informazioni sui server appena rilevati: `vserver cifs domain discovered-servers show -vserver _vserver_name_`


.Esempio
Nell'esempio riportato di seguito vengono ripristinati e riutilizzati i server per la macchina virtuale di storage (SVM, precedentemente nota come Vserver) vs1:

[listing]
----
cluster1::> vserver cifs domain discovered-servers reset-servers -vserver vs1

cluster1::> vserver cifs domain discovered-servers show

Node: node1
Vserver: vs1

Domain Name     Type     Preference DC-Name     DC-Address    Status
--------------- -------- ---------- ----------- ------------- -------
example.com     MS-LDAP  adequate   DC-1        1.1.3.4       OK
example.com     MS-LDAP  adequate   DC-2        1.1.3.5       OK
example.com     MS-DC    adequate   DC-1        1.1.3.4       OK
example.com     MS-DC    adequate   DC-2        1.1.3.5       OK
----
.Informazioni correlate
xref:display-discovered-servers-task.adoc[Visualizzazione delle informazioni sui server rilevati]

xref:stop-start-server-task.adoc[Interruzione o avvio del server CIFS]
