---
permalink: smb-admin/reset-rediscover-trusted-domains-task.html 
sidebar: sidebar 
keywords: force, rediscover, trust, domain, relationship, bidirectional, trust, home, cifs, server, computer, account, reset and rediscover trusted domains 
summary: 'È possibile forzare la riscoperta di tutti i domini attendibili. Ciò può risultare utile quando i server di dominio attendibili non rispondono in modo appropriato o le relazioni di trust sono cambiate. Vengono rilevati solo i domini con un trust bidirezionale con il dominio principale, ovvero il dominio contenente l"account del computer del server CIFS.' 
---
= Ripristinare e rilevare nuovamente i domini SMB ONTAP attendibili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile forzare la riscoperta di tutti i domini attendibili. Ciò può risultare utile quando i server di dominio attendibili non rispondono in modo appropriato o le relazioni di trust sono cambiate. Vengono rilevati solo i domini con un trust bidirezionale con il dominio principale, ovvero il dominio contenente l'account del computer del server CIFS.

A partire da ONTAP 9.13.1, quando ONTAP rileva nuovamente i domini attendibili, esegue anche la rilevazione del sito per tali domini. ONTAP utilizza le informazioni sul sito rilevate per le ricerche dei domain controller dei domini attendibili. Ciò contribuisce a garantire che le ricerche DNS SRV utilizzino le informazioni corrette sul sito per i domain controller dei domini attendibili. Se la rilevazione del sito per un dominio attendibile non riesce, ONTAP utilizza il sito predefinito del server SMB.

.Fase
. Reimpostare e riscoprire i domini attendibili utilizzando `vserver cifs domain trusts rediscover` comando.
+
`vserver cifs domain trusts rediscover -vserver vs1`



.Informazioni correlate
xref:display-discovered-trusted-domains-task.adoc[Visualizza informazioni sui domini attendibili rilevati]
