---
permalink: smb-admin/roaming-profiles-store-user-profiles-concept.html 
sidebar: sidebar 
keywords: ontap, support, storing, store, windows, roam, profile, cifs, server, associate, storage, virtual, machine, svm, configuring, configure, automatic, resource, availability, available, regardless, use roaming profiles to store user profiles centrally on a cifs server associated with the svm 
summary: 'ONTAP supporta la memorizzazione dei profili di roaming Windows su un server CIFS associato alla macchina virtuale di storage (SVM). La configurazione dei profili di roaming degli utenti offre vantaggi all"utente, ad esempio la disponibilità automatica delle risorse, indipendentemente dalla posizione di accesso dell"utente. I profili roaming semplificano inoltre l"amministrazione e la gestione dei profili utente.' 
---
= Utilizza i profili di roaming per memorizzare i profili utente centralmente su un server SMB associato alla panoramica SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporta la memorizzazione dei profili di roaming Windows su un server CIFS associato alla macchina virtuale di storage (SVM). La configurazione dei profili di roaming degli utenti offre vantaggi all'utente, ad esempio la disponibilità automatica delle risorse, indipendentemente dalla posizione di accesso dell'utente. I profili roaming semplificano inoltre l'amministrazione e la gestione dei profili utente.

I profili utente comuni presentano i seguenti vantaggi:

* Disponibilità automatica delle risorse
+
Il profilo univoco di un utente è automaticamente disponibile quando l'utente accede a qualsiasi computer della rete che esegue Windows 8, Windows 7, Windows 2000 o Windows XP. Gli utenti non devono creare un profilo su ciascun computer in rete.

* Sostituzione semplificata del computer
+
Poiché tutte le informazioni del profilo dell'utente vengono conservate separatamente sulla rete, è possibile scaricare facilmente il profilo dell'utente su un nuovo computer sostitutivo. Quando l'utente accede al nuovo computer per la prima volta, la copia del profilo dell'utente sul server viene copiata nel nuovo computer.



.Informazioni correlate
xref:offline-files-allow-caching-concept.adoc[Utilizzo di file offline per consentire il caching dei file per l'utilizzo offline]

xref:folder-redirection-store-data-concept.adoc[Utilizzo del reindirizzamento delle cartelle per memorizzare i dati su un server CIFS]
