---
permalink: smb-admin/server-security-settings-svm-disaster-recovery-concept.html 
sidebar: sidebar 
keywords: create, creating, svm, configure, disaster, recovery, destination, identity, preserve, snapmirror, configuration, smb, guideline, guidelines for smb server security settings in an svm disaster recovery configuration 
summary: 'Prima di creare una SVM configurata come destinazione per il disaster recovery in cui l"identità non viene preservata (l"opzione -Identity-preserve è impostata su false nella configurazione di SnapMirror), è necessario sapere come vengono gestite le impostazioni di sicurezza del server SMB sulla SVM di destinazione.' 
---
= Linee guida per le impostazioni di sicurezza del server SMB in una configurazione di disaster recovery SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di creare una SVM configurata come destinazione di disaster recovery in cui l'identità non viene preservata (la `-identity-preserve` l'opzione è impostata su `false` Nella configurazione di SnapMirror), è necessario conoscere il modo in cui le impostazioni di sicurezza del server SMB vengono gestite sulla SVM di destinazione.

* Le impostazioni di sicurezza del server SMB non predefinite non vengono replicate nella destinazione.
+
Quando si crea un server SMB sulla SVM di destinazione, tutte le impostazioni di sicurezza del server SMB vengono impostate sui valori predefiniti. Quando la destinazione di disaster recovery SVM viene inizializzata, aggiornata o risincronizzata, le impostazioni di sicurezza del server SMB sull'origine non vengono replicate nella destinazione.

* È necessario configurare manualmente le impostazioni di sicurezza del server SMB non predefinite.
+
Se sono state configurate impostazioni di sicurezza del server SMB non predefinite sulla SVM di origine, è necessario configurare manualmente queste stesse impostazioni sulla SVM di destinazione dopo che la destinazione diventa di lettura/scrittura (dopo che la relazione SnapMirror è stata interrotta).


