---
permalink: smb-admin/set-server-minimum-authentication-security-level-task.html 
sidebar: sidebar 
keywords: cifs, server, minimum, security, level, lmcompatibilitylevel, smb, token, set the cifs server minimum authentication security level 
summary: 'È possibile impostare il livello di sicurezza minimo del server SMB, noto anche come LMCompatibilityLevel, sul server SMB per soddisfare i requisiti di sicurezza aziendali per l"accesso SMB. Il livello di sicurezza minimo è il livello minimo dei token di sicurezza che il server SMB accetta dai client SMB.' 
---
= Impostare il livello di sicurezza minimo per l'autenticazione del server SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile impostare il livello di sicurezza minimo del server SMB, noto anche come _LMCompatibilityLevel_, sul server SMB per soddisfare i requisiti di sicurezza aziendali per l'accesso al client SMB. Il livello di sicurezza minimo è il livello minimo dei token di sicurezza che il server SMB accetta dai client SMB.

[NOTE]
.A proposito di questa attività
====
* I server SMB in modalità workgroup supportano solo l'autenticazione NTLM. L'autenticazione Kerberos non è supportata.
* LMCompatibilityLevel si applica solo all'autenticazione del client SMB, non all'autenticazione dell'amministratore.


====
È possibile impostare il livello di sicurezza minimo per l'autenticazione su uno dei quattro livelli di sicurezza supportati.

|===
| Valore | Descrizione 


 a| 
`lm-ntlm-ntlmv2-krb` (impostazione predefinita)
 a| 
La macchina virtuale per lo storage (SVM) accetta la protezione con autenticazione LM, NTLM, NTLMv2 e Kerberos.



 a| 
`ntlm-ntlmv2-krb`
 a| 
SVM accetta la sicurezza di autenticazione NTLM, NTLMv2 e Kerberos. SVM nega l'autenticazione LM.



 a| 
`ntlmv2-krb`
 a| 
SVM accetta la sicurezza di autenticazione NTLMv2 e Kerberos. SVM nega l'autenticazione LM e NTLM.



 a| 
`krb`
 a| 
SVM accetta solo la sicurezza con autenticazione Kerberos. SVM nega l'autenticazione LM, NTLM e NTLMv2.

|===
.Fasi
. Impostare il livello minimo di protezione per l'autenticazione: `vserver cifs security modify -vserver _vserver_name_ -lm-compatibility-level {lm-ntlm-ntlmv2-krb|ntlm-ntlmv2-krb|ntlmv2-krb|krb}`
. Verificare che il livello di protezione per l'autenticazione sia impostato sul livello desiderato: `vserver cifs security show -vserver _vserver_name_`


.Informazioni correlate
xref:enable-disable-aes-encryption-kerberos-task.adoc[Configurare la crittografia AES per la comunicazione basata su Kerberos]
