---
permalink: smb-admin/share-properties-concept.html 
sidebar: sidebar 
keywords: customize, properties, property, smb, share, how to use smb share properties 
summary: È possibile personalizzare le proprietà delle condivisioni SMB. 
---
= Utilizza la panoramica delle proprietà di condivisione SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile personalizzare le proprietà delle condivisioni SMB.

Le proprietà di condivisione disponibili sono le seguenti:

|===
| Condividere le proprietà | Descrizione 


 a| 
`oplocks`
 a| 
Questa proprietà specifica che la condivisione utilizza blocchi opportunistici, noti anche come caching lato client.



 a| 
`browsable`
 a| 
Questa proprietà consente ai client Windows di esplorare la condivisione.



 a| 
`showsnapshot`
 a| 
Questa proprietà specifica che le copie Snapshot possono essere visualizzate e attraversate dai client.



 a| 
`changenotify`
 a| 
Questa proprietà specifica che la condivisione supporta le richieste di notifica delle modifiche. Per le condivisioni su una SVM, si tratta di una proprietà iniziale predefinita.



 a| 
`attributecache`
 a| 
Questa proprietà abilita il caching degli attributi del file nella condivisione SMB per fornire un accesso più rapido agli attributi. L'impostazione predefinita prevede la disattivazione del caching degli attributi. Questa proprietà deve essere attivata solo se ci sono client che si connettono alle condivisioni su SMB 1.0. Questa proprietà di condivisione non è applicabile se i client si connettono alle condivisioni tramite SMB 2.x o SMB 3.0.



 a| 
`continuously-available`
 a| 
Questa proprietà consente ai client SMB che lo supportano di aprire i file in modo persistente. I file aperti in questo modo sono protetti da eventi di interruzione, come failover e giveback.



 a| 
`branchcache`
 a| 
Questa proprietà specifica che la condivisione consente ai client di richiedere gli hash BranchCache sui file all'interno di questa condivisione. Questa opzione è utile solo se si specifica "`per-share`" come modalità operativa nella configurazione CIFS BranchCache.



 a| 
`access-based-enumeration`
 a| 
Questa proprietà specifica che l'opzione _Access Based Enumeration_ (ABE) è attivata per questa condivisione. Le cartelle condivise con filtro ABE sono visibili a un utente in base ai diritti di accesso del singolo utente, impedendo la visualizzazione di cartelle o altre risorse condivise a cui l'utente non dispone dei diritti di accesso.



 a| 
`namespace-caching`
 a| 
Questa proprietà specifica che i client SMB che si connettono a questa condivisione possono memorizzare nella cache i risultati dell'enumerazione delle directory restituiti dai server CIFS, in modo da ottenere performance migliori. Per impostazione predefinita, i client SMB 1 non memorizzano nella cache i risultati dell'enumerazione delle directory. Poiché i client SMB 2 e SMB 3 memorizzano nella cache i risultati dell'enumerazione delle directory per impostazione predefinita, la specifica di questa proprietà di condivisione offre vantaggi in termini di prestazioni solo per le connessioni client SMB 1.



 a| 
`encrypt-data`
 a| 
Questa proprietà specifica che la crittografia SMB deve essere utilizzata quando si accede a questa condivisione. I client SMB che non supportano la crittografia durante l'accesso ai dati SMB non potranno accedere a questa condivisione.

|===