---
permalink: smb-admin/static-home-directory-share-names-upgrading-concept.html 
sidebar: sidebar 
keywords: home, directory, share, name, dynamic, variable, aware, exist, static, ontap, requirement, what happens to static home directory share names after upgrading 
summary: 'I nomi delle condivisioni della home directory devono contenere la variabile dinamica %w o %u. Dopo l"aggiornamento a una versione di ONTAP con il nuovo requisito, dovresti essere consapevole di ciò che accade ai nomi di condivisione della home directory statica esistenti.' 
---
= Cosa accade ai nomi di condivisione della home directory statica dopo l'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I nomi di condivisione della home directory devono contenere `%w` o il `%u` variabile dinamica. Dopo l'aggiornamento a una versione di ONTAP con il nuovo requisito, dovresti essere consapevole di ciò che accade ai nomi di condivisione della home directory statica esistenti.

Se la configurazione della home directory contiene nomi di condivisione statici e si esegue l'aggiornamento a ONTAP, i nomi di condivisione della home directory statica non vengono modificati e sono ancora validi. Tuttavia, non è possibile creare nuove condivisioni della home directory che non contengono `%w` oppure `%u` variabile.

La richiesta di includere una di queste variabili nel nome di condivisione della home directory dell'utente garantisce che ogni nome di condivisione sia univoco nella configurazione della home directory. Se lo si desidera, è possibile modificare i nomi di condivisione della home directory statica in nomi che contengono `%w` oppure `%u` variabile.
