---
permalink: smb-admin/stop-automatic-caching-all-shares-task.html 
sidebar: sidebar 
keywords: branchcache, configuration, automatic, enable, caching, cache, smb, share, storage, virtual, machine, svm, modify, stop automatic caching on all smb shares 
summary: 'Se la configurazione di BranchCache abilita automaticamente il caching su tutte le condivisioni SMB su ciascuna macchina virtuale di storage (SVM), puoi modificare la configurazione di BranchCache per interrompere automaticamente il caching del contenuto per tutte le condivisioni SMB.' 
---
= Arresta la memorizzazione automatica nella cache su tutte le condivisioni SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la configurazione di BranchCache abilita automaticamente il caching su tutte le condivisioni SMB su ciascuna macchina virtuale di storage (SVM), puoi modificare la configurazione di BranchCache per interrompere automaticamente il caching del contenuto per tutte le condivisioni SMB.

.A proposito di questa attività
Per interrompere il caching automatico su tutte le condivisioni SMB, si cambia la modalità operativa BranchCache in caching per-share.

.Fasi
. Configurare BranchCache per interrompere il caching automatico su tutte le condivisioni SMB: `vserver cifs branchcache modify -vserver vserver_name -operating-mode per-share`
. Verificare che la configurazione di BranchCache sia corretta: `vserver cifs branchcache show -vserver vserver_name`


.Esempio
Il seguente comando modifica la configurazione di BranchCache su storage virtual machine (SVM, precedentemente noto come Vserver) vs1 per interrompere il caching automatico su tutte le condivisioni SMB:

[listing]
----
cluster1::> vserver cifs branchcache modify -vserver vs1 -operating-mode per-share

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: per_share
----