---
permalink: smb-admin/supported-dynamic-access-control-reference.html 
sidebar: sidebar 
keywords: dynamic, access, control, dac, cifs, server, understand, ontap, support, functionality, active, directory, environment, supported dynamic access control functionality 
summary: 'Se si desidera utilizzare il controllo dinamico degli accessi (DAC) sul server CIFS, è necessario comprendere in che modo ONTAP supporta la funzionalità di controllo dinamico degli accessi negli ambienti Active Directory.' 
---
= Funzionalità DAC supportata per i server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera utilizzare il controllo dinamico degli accessi (DAC) sul server CIFS, è necessario comprendere in che modo ONTAP supporta la funzionalità di controllo dinamico degli accessi negli ambienti Active Directory.



== Supportato per Dynamic Access Control

ONTAP supporta le seguenti funzionalità quando il controllo dinamico degli accessi è attivato sul server CIFS:

|===
| Funzionalità | Commenti 


 a| 
Attestazioni nel file system
 a| 
Le affermazioni sono semplici coppie di nomi e valori che indicano una certa verità su un utente. Le credenziali utente contengono informazioni sulle attestazioni e i descrittori di protezione sui file possono eseguire controlli di accesso che includono controlli delle attestazioni. In questo modo, gli amministratori possono avere un maggiore controllo sugli utenti che possono accedere ai file.



 a| 
Espressioni condizionali per i controlli di accesso al file
 a| 
Quando si modificano i parametri di protezione di un file, gli utenti possono aggiungere espressioni condizionali arbitrariamente complesse al descrittore di protezione del file. L'espressione condizionale può includere controlli per le attestazioni.



 a| 
Controllo centralizzato dell'accesso ai file tramite policy di accesso centrali
 a| 
I criteri di accesso centrale sono un tipo di ACL memorizzato in Active Directory che può essere contrassegnato in un file. L'accesso al file viene concesso solo se i controlli di accesso del descrittore di protezione su disco e del criterio di accesso centrale con tag consentono l'accesso. In questo modo, gli amministratori possono controllare l'accesso ai file da una posizione centrale (ad) senza dover modificare il descrittore di protezione su disco.



 a| 
Staging dei criteri di accesso centrale
 a| 
Aggiunge la possibilità di provare le modifiche di sicurezza senza influire sull'accesso effettivo ai file, "eseguendo `staging`" una modifica alle policy di accesso centrale e osservando l'effetto della modifica in un report di audit.



 a| 
Supporto per la visualizzazione di informazioni sulla sicurezza dei criteri di accesso centrale mediante l'interfaccia utente di ONTAP
 a| 
Estende `vserver security file-directory show` per visualizzare le informazioni sui criteri di accesso centrale applicati.



 a| 
Analisi della sicurezza che include policy di accesso centralizzate
 a| 
Estende `vserver security trace` famiglia di comandi per visualizzare i risultati che includono informazioni sui criteri di accesso centrale applicati.

|===


== Non supportato per Dynamic Access Control

ONTAP non supporta le seguenti funzionalità quando il controllo dinamico degli accessi è attivato sul server CIFS:

|===
| Funzionalità | Commenti 


 a| 
Classificazione automatica degli oggetti del file system NTFS
 a| 
Si tratta di un'estensione dell'infrastruttura di classificazione dei file di Windows non supportata in ONTAP.



 a| 
Auditing avanzato diverso dalla gestione temporanea dei criteri di accesso centrale
 a| 
Solo lo staging dei criteri di accesso centrale è supportato per il controllo avanzato.

|===