---
permalink: smb-admin/support-ipv6-concept.html 
sidebar: sidebar 
keywords: ipv6, cifs, server, ontap, smb, network, communication, service, support for ipv6 with smb access and cifs services 
summary: 'Se si desidera utilizzare IPv6 sul server CIFS, è necessario conoscere il modo in cui ONTAP supporta IPv6 per l"accesso SMB e la comunicazione di rete per i servizi CIFS.' 
---
= Supporto per IPv6 con accesso SMB e servizi CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera utilizzare IPv6 sul server CIFS, è necessario conoscere il modo in cui ONTAP supporta IPv6 per l'accesso SMB e la comunicazione di rete per i servizi CIFS.



== Supporto di client e server Windows

ONTAP fornisce supporto per server e client Windows che supportano IPv6. Di seguito viene descritto il supporto IPv6 del client e del server Microsoft Windows:

* Windows XP e Windows 2003 supportano IPv6 per la condivisione di file SMB.
+
Queste versioni offrono un supporto limitato per IPv6.

* Windows 7, Windows 8, Windows Server 2008, Windows Server 2012 e versioni successive supportano IPv6 sia per la condivisione di file SMB che per i servizi Active Directory, inclusi i servizi DNS, LDAP, CLDAP e Kerberos.
+
Se gli indirizzi IPv6 sono configurati, Windows 7 e Windows Server 2008 e versioni successive utilizzano IPv6 per impostazione predefinita per i servizi Active Directory. Sono supportate sia l'autenticazione NTLM che Kerberos su connessioni IPv6.

+
Tutti i client Windows supportati da ONTAP possono connettersi alle condivisioni SMB utilizzando gli indirizzi IPv6.



Per informazioni aggiornate sui client Windows supportati da ONTAP, consultare la matrice di interoperabilità.

Matrice di interoperabilità

[NOTE]
====
I domini NT non sono supportati per IPv6.

====


== Supporto di servizi CIFS aggiuntivi

Oltre al supporto IPv6 per le condivisioni di file SMB e i servizi Active Directory, ONTAP fornisce il supporto IPv6 per:

* Servizi lato client, tra cui cartelle offline, profili di roaming, reindirizzamento cartelle e versioni precedenti
* Servizi lato server, tra cui home directory dinamiche (funzionalità home directory), symlink e Widelink, BranchCache, offload delle copie ODX, riferimenti automatici dei nodi, E versioni precedenti
* Servizi di gestione dell'accesso ai file, tra cui l'utilizzo di utenti e gruppi locali di Windows per il controllo degli accessi e la gestione dei diritti, l'impostazione delle autorizzazioni dei file e dei criteri di controllo mediante la CLI, il tracciamento della sicurezza, la gestione dei blocchi dei file e il monitoraggio dell'attività SMB
* Audit multiprotocollo NAS
* FPolicy
* Condivisioni continuamente disponibili, protocollo Witness e VSS remoto (utilizzato con configurazioni Hyper-V su SMB)




== Supporto del servizio di autenticazione e dei nomi

IPv6 supporta le comunicazioni con i seguenti name service:

* Controller di dominio
* Server DNS
* Server LDAP
* Server KDC
* Server NIS

