---
permalink: smb-admin/support-branchcache-group-policy-objects-concept.html 
sidebar: sidebar 
keywords: ontap, branchcache, support, group, policy, object, gpo, centralize, management, configuration, parameter, hash, publication, support for branchcache group policy objects 
summary: 'BranchCache di ONTAP fornisce il supporto per gli oggetti Criteri di gruppo BranchCache, che consentono la gestione centralizzata di alcuni parametri di configurazione BranchCache. Per BranchCache vengono utilizzati due GPO, la pubblicazione Hash per l"oggetto Criteri di gruppo BranchCache e il supporto della versione Hash per l"oggetto Criteri di gruppo BranchCache.' 
---
= Scopri di più sul supporto ONTAP SMB per gli oggetti Criteri di gruppo BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BranchCache di ONTAP fornisce il supporto per gli oggetti Criteri di gruppo BranchCache, che consentono la gestione centralizzata di alcuni parametri di configurazione BranchCache. Per BranchCache vengono utilizzati due GPO, la pubblicazione Hash per l'oggetto Criteri di gruppo BranchCache e il supporto della versione Hash per l'oggetto Criteri di gruppo BranchCache.

* *Pubblicazione Hash per l'oggetto Criteri di gruppo BranchCache*
+
La pubblicazione Hash per l'oggetto Criteri di gruppo BranchCache corrisponde a. `-operating-mode` parametro. Quando si verificano gli aggiornamenti dei GPO, questo valore viene applicato agli oggetti SVM (Storage Virtual Machine) contenuti nell'unità organizzativa (OU) a cui si applicano i criteri di gruppo.

* *Supporto della versione Hash per l'oggetto Criteri di gruppo BranchCache*
+
Il supporto della versione Hash per l'oggetto Criteri di gruppo BranchCache corrisponde a. `-versions` parametro. Quando si verificano gli aggiornamenti dei GPO, questo valore viene applicato agli oggetti SVM contenuti nell'unità organizzativa a cui si applicano i criteri di gruppo.



.Informazioni correlate
xref:applying-group-policy-objects-concept.adoc[Applicazione di oggetti Criteri di gruppo ai server CIFS]
