---
permalink: smb-admin/using-odx-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, aware, guideline, volume, intra-cluster, inter-cluster, consideration, guidelines for using odx 
summary: 'Prima di poter utilizzare ODX per l"offload delle copie, è necessario conoscere le linee guida. Ad esempio, è necessario sapere quali tipi di volumi è possibile utilizzare ODX e comprendere le considerazioni relative a ODX all"interno del cluster e tra cluster.' 
---
= Linee guida per l'utilizzo di ODX sui server ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di poter utilizzare ODX per l'offload delle copie, è necessario conoscere le linee guida. Ad esempio, è necessario sapere quali tipi di volumi è possibile utilizzare ODX e comprendere le considerazioni relative a ODX all'interno del cluster e tra cluster.



== Linee guida sui volumi

* Non è possibile utilizzare ODX per l'offload delle copie con le seguenti configurazioni di volume:
+
** Le dimensioni del volume di origine sono inferiori a 1.25 GB
+
Per utilizzare ODX, le dimensioni del volume devono essere pari o superiori a 1.25 GB.

** Volumi di sola lettura
+
ODX non viene utilizzato per file e cartelle residenti in mirror di condivisione del carico o in volumi di destinazione SnapMirror o SnapVault.

** Se il volume di origine non viene deduplicato


* Le copie ODX sono supportate solo per le copie all'interno del cluster.
+
Non è possibile utilizzare ODX per copiare file o cartelle in un volume in un altro cluster.





== Altre linee guida

* Negli ambienti SMB, per utilizzare ODX per l'offload delle copie, i file devono essere di 256 kb o superiore.
+
I file più piccoli vengono trasferiti utilizzando un'operazione di copia tradizionale.

* L'offload delle copie di ODX utilizza la deduplica come parte del processo di copia.
+
Se non si desidera che la deduplica avvenga sui volumi SVM durante la copia o lo spostamento dei dati, è necessario disattivare l'offload delle copie ODX su tale SVM.

* L'applicazione che esegue il trasferimento dei dati deve essere scritta per supportare ODX.
+
Le operazioni applicative che supportano ODX includono:

+
** Operazioni di gestione di Hyper-V, come la creazione e la conversione di hard disk virtuali (VHD), la gestione di snapshot e la copia di file tra macchine virtuali
** Operazioni di Esplora risorse
** Comandi di copia di Windows PowerShell
** Comandi di copia del prompt dei comandi di Windows
+
Robocopy al prompt dei comandi di Windows supporta ODX.

+
[NOTE]
====
Le applicazioni devono essere in esecuzione su server o client Windows che supportano ODX.

====
+
Per ulteriori informazioni sulle applicazioni ODX supportate su server e client Windows, consultare la Microsoft TechNet Library.





.Informazioni correlate
http://technet.microsoft.com/en-us/library/["Microsoft TechNet Library: technet.microsoft.com/en-us/library/"]
