---
permalink: smb-admin/view-shares-mmc-task.html 
sidebar: sidebar 
keywords: information, smb, share, svm, perform, management, task, microsoft, management, console, mmc, view, share, connect, svm, view information about smb shares using the mmc 
summary: 'È possibile visualizzare informazioni sulle condivisioni SMB sulla SVM ed eseguire alcune attività di gestione utilizzando Microsoft Management Console (MMC). Prima di poter visualizzare le condivisioni, è necessario collegare MMC a SVM.' 
---
= Consente di visualizzare le informazioni sulle condivisioni SMB di ONTAP utilizzando MMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sulle condivisioni SMB sulla SVM ed eseguire alcune attività di gestione utilizzando Microsoft Management Console (MMC). Prima di poter visualizzare le condivisioni, è necessario collegare MMC a SVM.

.A proposito di questa attività
È possibile eseguire le seguenti attività sulle condivisioni contenute in SVM utilizzando MMC:

* Visualizza condivisioni
* Visualizzare le sessioni attive
* Visualizzare i file aperti
* Enumerare l'elenco di sessioni, file e connessioni ad albero nel sistema
* Chiudere i file aperti nel sistema
* Chiudere le sessioni aperte
* Creare/gestire le condivisioni


[NOTE]
====
Le viste visualizzate dalle funzionalità precedenti sono specifiche del nodo e non del cluster. Pertanto, quando si utilizza MMC per connettersi al nome host del server SMB (cioè, cifs01.domain.local), si viene indirizzati, in base alla configurazione del DNS, a una singola LIF all'interno del cluster.

====
Le seguenti funzioni non sono supportate in MMC per ONTAP:

* Creazione di nuovi utenti/gruppi locali
* Gestione/visualizzazione di utenti/gruppi locali esistenti
* Visualizzazione di eventi o log delle performance
* Storage
* Servizi e applicazioni


Nei casi in cui l'operazione non è supportata, potrebbe verificarsi un'operazione `remote procedure call failed` errori.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/FAQ%3A_Using_Windows_MMC_with_ONTAP["Domande frequenti: Utilizzo di Windows MMC con ONTAP"]

.Fasi
. Per aprire la MMC Gestione computer su qualsiasi server Windows, nel pannello di controllo, selezionare *Strumenti di amministrazione* > *Gestione computer*.
. Selezionare *azione* > *connessione a un altro computer*.
+
Viene visualizzata la finestra di dialogo Select computer (Seleziona computer).

. Digitare il nome del sistema di storage o fare clic su *Browse* (Sfoglia) per individuare il sistema di storage.
. Fare clic su *OK*.
+
MMC si connette a SVM.

. Nel riquadro di navigazione, fare clic su *Shared Folders* > *Shares*.
+
Nel riquadro di visualizzazione di destra viene visualizzato un elenco di condivisioni su SVM.

. Per visualizzare le proprietà di una condivisione, fare doppio clic sulla condivisione per aprire la finestra di dialogo *Proprietà*.
. Se non è possibile connettersi al sistema di storage utilizzando MMC, è possibile aggiungere l'utente al gruppo BUILTIN/Administrators o al gruppo BUILTIN/Power Users utilizzando uno dei seguenti comandi sul sistema di storage:
+
[listing]
----

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name BUILTIN\Administrators -member-names <domainuser>

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name "BUILTIN\Power Users" -member-names <domainuser>
----

