---
permalink: smb-admin/write-cache-data-loss-oplocks-concept.html 
sidebar: sidebar 
keywords: circumstance, process, exclusive, oplock, file, flush, cache, data, write, lock, relinquish, network, failure, write cache data-loss considerations when using oplocks 
summary: 'In alcuni casi, se un processo ha un oplock esclusivo su un file e un secondo processo tenta di aprire il file, il primo processo deve invalidare i dati memorizzati nella cache e svuotare le scritture e i blocchi. Il client deve quindi rinunciare all"oplock e all"accesso al file. Se si verifica un errore di rete durante questo svuotamento, i dati di scrittura memorizzati nella cache potrebbero andare persi.' 
---
= Considerazioni sulla perdita di dati della cache in scrittura quando si utilizzano gli oplock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In alcuni casi, se un processo ha un oplock esclusivo su un file e un secondo processo tenta di aprire il file, il primo processo deve invalidare i dati memorizzati nella cache e svuotare le scritture e i blocchi. Il client deve quindi rinunciare all'oplock e all'accesso al file. Se si verifica un errore di rete durante questo svuotamento, i dati di scrittura memorizzati nella cache potrebbero andare persi.

* Possibilità di perdita di dati
+
Qualsiasi applicazione che dispone di dati memorizzati nella cache in scrittura può perdere tali dati nei seguenti casi:

+
** La connessione viene effettuata utilizzando SMB 1.0.
** Ha un oplock esclusivo sul file.
** Viene richiesto di interrompere l'oplock o chiudere il file.
** Durante il processo di cancellazione della cache di scrittura, il sistema di rete o di destinazione genera un errore.


* Gestione degli errori e completamento della scrittura
+
La cache stessa non ha alcun tipo di gestione degli errori, come fanno le applicazioni. Quando l'applicazione esegue una scrittura nella cache, la scrittura viene sempre completata. Se la cache, a sua volta, esegue una scrittura nel sistema di destinazione su una rete, deve presumere che la scrittura sia completata perché in caso contrario, i dati vengono persi.


