---
permalink: svm-migrate/pause-task.html 
sidebar: sidebar 
keywords: svm, migrate, pause, resume, restart 
summary: 'Potrebbe essere necessario sospendere una migrazione SVM prima dell"inizio del cutover della migrazione. È possibile sospendere una migrazione SVM utilizzando `vserver migrate pause` comando.' 
---
= Mettere in pausa e riprendere una migrazione ONTAP SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario sospendere una migrazione SVM prima dell'inizio del cutover della migrazione. È possibile sospendere una migrazione SVM utilizzando `vserver migrate pause` comando.



== Sospendere la migrazione

È possibile sospendere una migrazione SVM prima dell'avvio del cutover del client utilizzando `vserver migrate pause` comando.

Alcune modifiche alla configurazione sono limitate quando è in corso un'operazione di migrazione; tuttavia, a partire da ONTAP 9.12.1, è possibile sospendere una migrazione per correggere alcune configurazioni limitate e alcuni stati non riusciti, in modo da risolvere i problemi di configurazione che potrebbero aver causato l'errore. Alcuni degli stati di errore che è possibile correggere quando si interrompe la migrazione SVM includono:

* `setup-configuration-failed`
* `migrate-failed`


.Fasi
. Dal cluster di destinazione, sospendere la migrazione:
+
[source, cli]
----
vserver migrate pause -vserver <vserver name>
----




== Riprendere le migrazioni

Puoi utilizzare il comando per riprendere una migrazione SVM sospesa o in caso di errore della migrazione SVM `vserver migrate resume`.

.Fasi
. Dal cluster di destinazione, riprendere la migrazione SVM:
+
[source, cli]
----
vserver migrate resume
----
. Verificare che la migrazione SVM sia stata ripresa e monitorare l'avanzamento:
+
[source, cli]
----
vserver migrate show
----

