---
permalink: mediator/host-maintenance-task.html 
sidebar: sidebar 
keywords: mediator, maintain, host, maintenance, package update, kernel upgrade, change hostname, change IP, self-signed certificate, self signed certificate 
summary: Per prestazioni ottimali, eseguire regolarmente la manutenzione del sistema operativo host per ONTAP Mediator. 
---
= Gestire il sistema operativo host per ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per prestazioni ottimali, eseguire regolarmente la manutenzione del sistema operativo host per ONTAP Mediator.



== Riavviare l'host

Riavviare l'host solo quando i cluster sono integri.  I cluster non possono rispondere ai guasti mentre ONTAP Mediator è offline.  Pianificare una finestra di servizio prima del riavvio.

ONTAP Mediator riprende automaticamente durante un riavvio e ripristina le relazioni precedentemente configurate con i cluster ONTAP .



== Aggiornamenti dei pacchetti host

Aggiornare qualsiasi libreria o pacchetto yum, eccetto il kernel.  Se necessario, riavviare l'host affinché le modifiche abbiano effetto.  Pianificare una finestra di servizio prima di riavviare l'host.

Se si installa `yum-utils` utilizzare il `needs-restarting` comando per rilevare se qualsiasi modifica del pacchetto richiede un riavvio.

Riavviare dopo aver aggiornato le dipendenze di ONTAP Mediator perché le modifiche non hanno effetto immediato.



== Aggiornamenti minori del kernel per il sistema operativo host

SCST deve essere compilato per il kernel in uso. Per aggiornare il sistema operativo, è necessaria una finestra di manutenzione.

.Fasi
Per aggiornare il kernel del sistema operativo host, procedere come segue.


NOTE: Prima di aggiornare il kernel, verificare che la versione del sistema operativo e ONTAP Mediator siano compatibili.  Per le versioni supportate, vederelink:whats-new-concept.html#os-support-matrix["Matrice di supporto del sistema operativo"] .

. Arresta il mediatore ONTAP.
. Disinstallare il pacchetto SCST, vedere<<Eseguire la manutenzione dell'host>> .  (SCST non fornisce un meccanismo di aggiornamento.)
. Aggiornare il sistema operativo e riavviare.
. Reinstallare il pacchetto SCST.
. Riattivare ONTAP Mediator.




== Eseguire la manutenzione dell'host

L'aggiornamento del kernel della VM può causare problemi di compatibilità con i moduli SCST.  Disinstallare e reinstallare manualmente SCST.



=== Passaggio 1: disinstallare SCST

Per disinstallare SCST, utilizzare il pacchetto tar per la versione di ONTAP Mediator in uso.

.Fasi
. Scaricare il bundle SCST appropriato (come mostrato nella tabella seguente) ed estrarlo.
+
[cols="50,50"]
|===


| Per questa versione ... | USA questo bundle tar... 


 a| 
Mediatore ONTAP 1.10
 a| 
scst-3.9.tar.gz



 a| 
Mediatore ONTAP 1.9.1
 a| 
scst-3,8.0.tar.bz2



 a| 
ONTAP mediatore 1,9
 a| 
scst-3,8.0.tar.bz2



 a| 
ONTAP mediatore 1,8
 a| 
scst-3,8.0.tar.bz2



 a| 
ONTAP mediatore 1,7
 a| 
scst-3.7.0.tar.bz2



 a| 
Mediatore ONTAP 1.6
 a| 
scst-3.7.0.tar.bz2



 a| 
Mediatore ONTAP 1.5
 a| 
scst-3.6.0.tar.bz2



 a| 
Mediatore ONTAP 1.4
 a| 
scst-3.6.0.tar.bz2



 a| 
Mediatore ONTAP 1.3
 a| 
scst-3.5.0.tar.bz2



 a| 
Mediatore ONTAP 1.1
 a| 
scst-3.4.0.tar.bz2



 a| 
Mediatore ONTAP 1.0
 a| 
scst-3.3.0.tar.bz2

|===
+
.. Accedi al pacchetto open source dalink:https://scst.sourceforge.net/downloads.html["Download di SCST Sourceforge"^] .
.. Seleziona *Scarica le versioni rilasciate*.
.. Estrarre il bundle nella macchina virtuale.


. Eseguire i seguenti comandi di disinstallazione in `scst` elenco:
+
.. `systemctl stop mediator-scst`
.. `make scstadm_uninstall`
.. `make iscsi_uninstall`
.. `make usr_uninstall`
.. `make scst_uninstall`
.. `depmod`






=== Passaggio 2: installare SCST

Per installare manualmente SCST, è necessario il bundle tar SCST utilizzato per la versione installata di ONTAP Mediator (vedere<<scst-bundle-table,Tabella SCST>> ).


NOTE: Eseguire questo passaggio prima di installare ONTAP Mediator.  Se la versione SCST in uso è più recente della versione fornita con il programma di installazione ONTAP Mediator, il programma di installazione salta questo passaggio.

. Eseguire i seguenti comandi di installazione in `scst` elenco:
+
.. `make 2release`
.. `make scst_install`
.. `make usr_install`
.. `make iscsi_install`
.. `make scstadm_install`
.. `depmod`
+
[NOTE]
====
Se stai eseguendo una prima installazione e desideri preinstallare ONTAP Mediator, esegui il seguente comando prima di procedere con il passaggio successivo:

`mkdir -p /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys`

====
.. `cp scst/src/certs/scst_module_key.der /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/`
.. `patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch`
+

NOTE: Se si preinstalla SCST prima di ONTAP Mediator durante la prima installazione, saltare questo passaggio.  Il programma di installazione applica le patch SCST pertinenti.



. Se, in alternativa, Secure Boot è attivato, prima di riavviare il computer, procedere come segue:
+
.. Determinare ciascun nome di file per il `scst_vdisk` , `scst` , E `iscsi_scst` moduli:
+
....
[root@localhost ~]# modinfo -n scst_vdisk
[root@localhost ~]# modinfo -n scst
[root@localhost ~]# modinfo -n iscsi_scst
....
.. Determinare il rilascio del kernel:
+
....
[root@localhost ~]# uname -r
....
.. Firmare ogni file del modulo con il kernel:
+
....
[root@localhost ~]# /usr/src/kernels/<KERNEL-RELEASE>/scripts/sign-file \sha256 \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.priv \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der \
_module-filename_
....
.. Installare la chiave UEFI con il firmware.
+
Le istruzioni per l'installazione della chiave UEFI sono disponibili all'indirizzo:

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing`

+
La chiave UEFI generata si trova in:

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`



. Riavviare il sistema:
+
`reboot`





== L'host modifica il nome host o l'IP

.A proposito di questa attività
* Eseguire questa attività sull'host Linux su cui è installato ONTAP Mediator.
* Eseguire questa attività solo se i certificati autofirmati sono obsoleti perché il nome host o l'indirizzo IP sono cambiati dopo l'installazione ONTAP Mediator.
* Dopo che il certificato autofirmato temporaneo è stato sostituito da un certificato di terze parti attendibile, _non_ è possibile utilizzare questa attività per rigenerare un certificato.  Se non si dispone di un certificato autofirmato, non è possibile utilizzare questa procedura.


.Fase
Crea un certificato autofirmato temporaneo per l'host corrente:

. Riavviare ONTAP Mediator:
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

