---
permalink: mediator/host-maintenance-task.html 
sidebar: sidebar 
keywords: mediator, maintain, host, maintenance, package update, kernal upgrade, change hostname, change IP, self-signed certificate, self signed certificate 
summary: 'Per ottenere performance ottimali, è necessario mantenere regolarmente l"od host per il mediatore ONTAP.' 
---
= Gestire il sistema operativo host per ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ottenere performance ottimali, è necessario mantenere regolarmente il sistema operativo host per ONTAP Mediator.



== Riavviare l'host

Riavviare l'host quando i cluster sono integri. Mentre il mediatore ONTAP è offline, i cluster rischiano di non essere in grado di reagire correttamente ai guasti. Se è necessario riavviare il sistema, si consiglia di utilizzare una finestra di servizio.

Il mediatore ONTAP riprende automaticamente durante il riavvio e reinserisce le relazioni precedentemente configurate con i cluster ONTAP.



== Aggiornamenti dei pacchetti host

Qualsiasi libreria o pacchetto yum (ad eccezione del kernel) può essere aggiornato in modo sicuro, ma potrebbe richiedere un riavvio per avere effetto. Se è necessario riavviare il sistema, si consiglia di utilizzare una finestra di servizio.

Se si installa `yum-utils` utilizzare il `needs-restarting` comando per rilevare se qualsiasi modifica del pacchetto richiede un riavvio.

È necessario riavviare il sistema se una delle dipendenze del mediatore ONTAP viene aggiornata perché non avrà effetto immediato sui processi in esecuzione.



== Aggiornamenti minori del kernel per il sistema operativo host

SCST deve essere compilato per il kernel in uso. Per aggiornare il sistema operativo, è necessaria una finestra di manutenzione.

.Fasi
Per aggiornare il kernel del sistema operativo host, procedere come segue.

. Arrestare il mediatore ONTAP
. Disinstallare il pacchetto SCST. (SCST non fornisce un meccanismo di aggiornamento).
. Aggiornare il sistema operativo e riavviare.
. Reinstallare il pacchetto SCST.
. Riattivare i servizi del mediatore ONTAP.




== L'host modifica il nome host o l'IP

.A proposito di questa attività
* Questa attività viene eseguita sull'host Linux su cui è installato il servizio ONTAP Mediator.
* È possibile eseguire questa attività solo se i certificati autofirmati generati sono diventati obsoleti a causa di modifiche al nome host o all'indirizzo IP dell'host dopo l'installazione di ONTAP Mediator.
* Dopo che il certificato autofirmato temporaneo è stato sostituito da un certificato di terze parti attendibile, _non_ utilizzare questa attività per rigenerare un certificato.  L'assenza di un certificato autofirmato causerà l'errore di questa procedura.


.Fase
Per rigenerare un nuovo certificato autofirmato temporaneo per l'host corrente, attenersi alla seguente procedura:

. Riavviare ONTAP Mediator:
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

