---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: 'Per installare il servizio ONTAP Media, è necessario assicurarsi che tutti i prerequisiti siano soddisfatti, ottenere il pacchetto di installazione ed eseguire il programma di installazione sull"host.' 
---
= Preparazione all'installazione o all'aggiornamento del servizio ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per installare il servizio ONTAP Mediator, è necessario assicurarsi che tutti i prerequisiti siano soddisfatti, scaricare il pacchetto di installazione ed eseguire il programma di installazione sull'host. Questa procedura viene utilizzata per un'installazione o un aggiornamento di un'installazione esistente.

.A proposito di questa attività
* A partire da ONTAP 9.7, è possibile utilizzare qualsiasi versione di ONTAP Mediator per monitorare una configurazione IP MetroCluster.
* A partire da ONTAP 9.8, è possibile utilizzare qualsiasi versione di ONTAP Mediator per monitorare una relazione SM-BC.


.Prima di iniziare
È necessario soddisfare i seguenti prerequisiti.

[cols="30,70"]
|===


| Versione del mediatore ONTAP | Versioni Linux supportate 


 a| 
1,7
 a| 
* Red Hat Enterprise Linux: 8,5, 8,6, 8,7, 8,8, 8,9, 9,0, 9,1, 9,2 e 9,3
* Rocky Linux 8 e 9




 a| 
1.6
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 e 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 8.1
* CentOS: 7.6, 7.7, 7.8


|===

NOTE: La versione del kernel deve corrispondere alla versione del sistema operativo.

* installazione fisica a 64 bit o macchina virtuale
* 8 GB DI RAM
* 1 GB di spazio su disco (utilizzato per l'installazione delle applicazioni, i log dei server e il database)
* Utente: Accesso root


Tutti i pacchetti di librerie, ad eccezione del kernel, possono essere aggiornati in modo sicuro, ma potrebbero richiedere un riavvio per influire sull'applicazione ONTAP Mediator. Quando è necessario riavviare il sistema, si consiglia di utilizzare una finestra di servizio.

Se si installa `yum-utils` è possibile utilizzare `needs-restarting` comando.

Il core del kernel può essere aggiornato se viene aggiornato a una versione ancora supportata dalla matrice di versione di ONTAP Mediator. Il riavvio è obbligatorio, pertanto è necessaria una finestra di servizio.

Il modulo kernel SCST deve essere disinstallato prima del riavvio, quindi reinstallato dopo il riavvio.


NOTE: L'aggiornamento a un kernel oltre la release del sistema operativo supportata per la release specifica di ONTAP Mediator non è supportato. (Questo probabilmente indica che il modulo SCST testato non viene compilato).



== Registrare una chiave di protezione quando UEFI Secure Boot è attivato

Se l'avvio protetto UEFI è attivato, per installare ONTAP Mediator è necessario registrare una chiave di protezione prima che il servizio ONTAP Mediator possa avviarsi. Per determinare se il sistema è abilitato per UEFI e l'avvio protetto è attivato, procedere come segue:

.Fasi
. Se mokutil non è installato, eseguire il seguente comando:
+
`yum install mokutil`

. Per determinare se UEFI Secure Boot è attivato sul sistema, eseguire il comando seguente:
+
`mokutil --sb-state`

+
I risultati mostrano se l'avvio protetto UEFI è abilitato su questo sistema.

+

NOTE: ONTAP Mediator 1.2.0 e le versioni precedenti non supportano questa modalità.





== Disattivare l'avvio protetto UEFI

È inoltre possibile scegliere di disattivare l'avvio protetto UEFI prima di installare ONTAP Mediator.

.Fasi
. Nelle impostazioni del BIOS della macchina fisica, disattivare l'opzione "UEFI Secure Boot" (Avvio protetto UEFI).
. Nelle impostazioni VMware per la VM, disattivare l'opzione "Avvio sicuro" per vSphere 6.x o l'opzione "Avvio sicuro" per vSphere 7.x

