---
permalink: mediator/mediator-overview-concept.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: Il mediatore ONTAP offre diverse funzioni per le funzionalità di ONTAP. 
---
= Panoramica del mediatore ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il mediatore ONTAP offre diverse funzioni per le funzioni di ONTAP:

* Fornisce un archivio persistente e recintato per i metadati ha.
* Funge da proxy ping per la vivacità del controller.
* Fornisce una funzionalità di query sincrona sullo stato dei nodi per agevolare la determinazione del quorum.


Il mediatore ONTAP offre due servizi aggiuntivi di systemctl:

* *`ontap_mediator.service`*
+
Mantiene il server REST API per la gestione delle relazioni ONAP.

* *`mediator-scst.service`*
+
Controlla l'avvio e lo spegnimento del modulo iSCSI (SCST).





== Strumenti forniti all'amministratore di sistema

Strumenti forniti all'amministratore di sistema:

* *`/usr/local/bin/mediator_change_password`*
+
Imposta una nuova password API quando vengono forniti il nome utente e la password API correnti.

* *`/usr/local/bin/mediator_change_user`*
+
Imposta un nuovo nome utente API quando vengono forniti il nome utente e la password API correnti.

* *`/usr/local/bin/mediator_generate_support_bundle`*
+
Genera un file tgz locale contenente tutte le informazioni di supporto utili necessarie per la comunicazione con il supporto clienti NetApp. Ciò include la configurazione dell'applicazione, i registri e alcune informazioni di sistema. I bundle vengono generati sul disco locale e possono essere trasferiti manualmente, se necessario. Ubicazione dello storage: /Opt/netapp/data/support_bundle/

* *`/usr/local/bin/uninstall_ontap_mediator`*
+
Rimuove il pacchetto ONTAP Mediator e il modulo kernel SCST. Sono inclusi tutti i dati di configurazione, registri e mailbox.

* *`/usr/local/bin/mediator_unlock_user`*
+
Rilascia un blocco sull'account utente API se viene raggiunto il limite di tentativi di autenticazione. Questa funzione viene utilizzata per impedire la derivazione della password con forza bruta. Viene richiesto all'utente di inserire il nome utente e la password corretti.

* *`/usr/local/bin/mediator_add_user`*
+
(Solo supporto) utilizzato per aggiungere l'utente API al momento dell'installazione.





== Note speciali

ONTAP Mediator si affida a SCST per fornire iSCSI (vedere http://scst.sourceforge.net/index.html[]). Questo pacchetto è un modulo del kernel che viene compilato durante l'installazione specificamente per il kernel. Qualsiasi aggiornamento del kernel potrebbe richiedere la reinstallazione di SCST. In alternativa, disinstallare e reinstallare il supporto ONTAP, quindi riconfigurare la relazione ONTAP.


NOTE: Qualsiasi aggiornamento del kernel del sistema operativo del server deve essere coordinato con una finestra di manutenzione in ONTAP.
