---
sidebar: sidebar 
permalink: flexcache-hot-spot/flexcache-hotspot-remediation-overview.html 
keywords: hotspot, FlexCache, HDFA, problem, solution, ONTAP 
summary: 'Scopri come risolvere i problemi degli hotspot, un problema comune con molti carichi di lavoro di calcolo dalle performance elevate, come il rendering di animazioni o l"EDA, con FlexCache.' 
---
= Risoluzione dei problemi relativi ai carichi di lavoro di calcolo dalle performance elevate con ONTAP FlexCache Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un problema comune con molti carichi di lavoro di calcolo ad alte performance, come il rendering delle animazioni o l'EDA, è hotspot. L'Hotspotting è una situazione che si verifica quando una parte specifica del cluster o della rete subisce un carico significativamente più elevato rispetto ad altre aree, con conseguenti colli di bottiglia delle prestazioni e una minore efficienza complessiva dovuta all'eccessivo traffico di dati concentrato in tale posizione. Ad esempio, uno o più file sono molto richiesti per l'esecuzione del processo, con conseguente collo di bottiglia della CPU utilizzata per le richieste di servizio (tramite affinità di volume) di quel file. FlexCache può aiutare ad alleviare questo collo di bottiglia, ma deve essere configurato correttamente.

Questa documentazione spiega come configurare FlexCache per risolvere i problemi di hot spotting.


NOTE: A partire da luglio 2024, il contenuto dei report tecnici precedentemente pubblicati come PDF è stato integrato nella documentazione del prodotto ONTAP. Questo contenuto del report tecnico di correzione dell'hotspot ONTAP è completamente nuovo alla data di pubblicazione e non è mai stato prodotto alcun formato precedente.



== Concetti chiave

Durante la pianificazione della correzione degli hotspot, è importante comprendere questi concetti essenziali.

* *HDF (High-Density FlexCache)*: Un FlexCache condensato per coprire un numero ridotto di nodi quanto consentito dai requisiti di capacità della cache
* *HDF Array (HDFA)*: Un gruppo di HDFS che sono cache della stessa origine, distribuite in tutto il cluster
* *Inter-SVM HDFA*: Un HDF dell'HDFA per macchina virtuale server (SVM)
* *Intra-SVM HDFA*: Tutti gli HDFS nell'HDFA in una SVM
* *Traffico est-ovest*: Traffico back-end cluster generato dall'accesso indiretto ai dati


.Cosa succederà
* link:flexcache-hotspot-remediation-architecture.html["Scopri come progettare con FlexCache ad alta densità per risolvere i problemi dei punti critici"]
* link:flexcache-hotspot-remediation-hdfa-examples.html["Decidere sulla densità degli array FlexCache"]
* link:flexcache-hotspot-remediation-intra-inter-svm-hdfa.html["Determina la densità del tuo HDFS e decidi se vuoi accedere ad HDFS utilizzando NFS con HDFA inter-SVM e HDFA intra-SVM"]
* link:flexcache-hotspot-remediation-ontap-config.html["Configura HDFA e data LIF per realizzare i vantaggi dell'utilizzo del caching tra cluster con la configurazione ONTAP"]
* link:flexcache-hotspot-remediation-client-config.html["Scoprite come configurare i client per distribuire connessioni NAS ONTAP con la configurazione del client"]

