---
permalink: update/enable-automatic-updates-task.html 
sidebar: sidebar 
keywords: ontap, enable, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone 
summary: 'L"attivazione degli aggiornamenti automatici consente a ONTAP di scaricare e installare gli aggiornamenti del firmware e del database del fuso orario senza l"intervento dell"utente.' 
---
= Abilitare gli aggiornamenti automatici
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.10.1, è possibile attivare gli aggiornamenti automatici per consentire a ONTAP di scaricare e installare gli aggiornamenti del firmware senza alcun intervento.

A partire da ONTAP 9.13.1, questi aggiornamenti automatici includono anche aggiornamenti automatici del database del fuso orario.

.A proposito di questa attività
Per attivare gli aggiornamenti automatici, è necessario prima attivare AutoSupport con HTTPS. Se AutoSupport non è abilitato sul cluster o se AutoSupport è abilitato sul cluster con un altro protocollo di trasporto, durante questa procedura sarà possibile attivarlo con HTTPS.

.Fasi
. In System Manager, fare clic su *Eventi*.
. Nella sezione *Panoramica*, accanto a *attiva aggiornamento automatico*, fare clic su *azioni>attiva*.
. Se non si dispone di AutoSupport con HTTPS attivato, selezionare per attivarlo.
. Accettare i termini e le condizioni e selezionare *Salva*.

