---
permalink: data-protection/autodelete-snapshot-copies-task.html 
sidebar: sidebar 
keywords: autodelete, snapshot, copies 
summary: 'È possibile utilizzare il comando di modifica dell"eliminazione automatica dello snapshot del volume per attivare l"eliminazione automatica degli snapshot al superamento della riserva snapshot. Per impostazione predefinita, gli snapshot meno recenti vengono eliminati per primi.' 
---
= Eliminazione automatica delle snapshot con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il `volume snapshot autodelete modify` comando per attivare l'eliminazione automatica degli snapshot quando viene superata la riserva snapshot. Per impostazione predefinita, gli snapshot meno recenti vengono eliminati per primi.

.A proposito di questa attività
I cloni LUN e dei file vengono eliminati quando non sono presenti più snapshot da eliminare.

.Fase
. Eliminazione automatica degli snapshot:
+
`volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled true|false -trigger volume|snap_reserve`

+
Ulteriori informazioni su `volume snapshot autodelete modify` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["Riferimento al comando ONTAP"^].

+
Nell'esempio seguente vengono eliminati automaticamente gli snapshot per `vol1` quando la riserva snapshot è esaurita:

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0 -volume vol1 -enabled true -trigger snap_reserve
----

