---
sidebar: sidebar 
permalink: data-protection/cloud-backup-using-cbs-task.html 
keywords: cloud, data, backup, back up, storage, volume, lun, connector, secret key, access key, bluexp back and recovery service, Cloud Backup service, CBS, restore data, protect volumes, ipspace, storagegrid, storage grid, archive, archival, archiving, cost, calculator, glacier, deep archive 
summary: A partire da ONTAP 9.19.1, System Manager non supporta più il backup dei dati nel cloud tramite il servizio NetApp Backup and Recovery. È invece necessario utilizzare NetApp Console per configurare il servizio NetApp Backup and Recovery e per creare una relazione SnapMirror verso una destinazione cloud. 
---
= Eseguire il backup dei dati utilizzando NetApp Backup and Recovery
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.19.1, System Manager non supporta più il backup dei dati nel cloud tramite il servizio NetApp Backup and Recovery. È invece necessario utilizzare NetApp Console per configurare il servizio NetApp Backup and Recovery e per creare una relazione SnapMirror verso una destinazione cloud.

Backup and Recovery supporta volumi FlexVol di lettura-scrittura e volumi di protezione dati (DP).  A partire da ONTAP 9.12.1, Backup and Recovery supporta i volumi FlexGroup e SnapLock .

Scopri di più su link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Backup e ripristino NetApp"^] .

.Prima di iniziare
È necessario eseguire le seguenti procedure per creare un account nella NetApp Console. Per l'account di servizio, è necessario creare il ruolo come "Account Admin".

. link:https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Crea un account nella console NetApp"^] .
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["Creare un agente Console nella console NetApp"^]con uno dei seguenti provider cloud:
+
** Microsoft Azure
** Amazon Web Services (AWS)
** Piattaforma Google Cloud (GCP)
** StorageGRID (ONTAP 9.10.1)
+

NOTE: A partire da ONTAP 9.10.1, è possibile selezionare StorageGRID come provider di backup cloud, ma solo se NetApp Console è distribuito in locale.  L'agente Console deve essere installato in sede ed essere disponibile tramite l'applicazione software-as-a-service (SaaS) NetApp Console.



. link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Iscriviti a NetApp Backup and Recovery nella console NetApp"^](richiede la licenza appropriata).
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["Genera una chiave di accesso e una chiave segreta utilizzando NetApp Console"^] .




== Utilizzare NetApp Console e NetApp Backup and Recovery per gestire i backup ONTAP

A partire da ONTAP 9.19.1, System Manager non supporta più NetApp Backup and Recovery. Vedere link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["Gestisci i backup dei tuoi sistemi ONTAP con NetApp Backup and Recovery"^] per ulteriori informazioni sull'utilizzo di NetApp Backup and Recovery con NetApp Console.



== Ripristinare i dati dai file di backup

È possibile eseguire operazioni di gestione del backup, come il ripristino dei dati, l'aggiornamento delle relazioni e l'eliminazione delle relazioni, solo utilizzando la console NetApp . Fare riferimento a link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["Ripristino dei dati dai file di backup"^] per maggiori informazioni.
