---
permalink: data-protection/convert-type-snapmirror-task.html 
sidebar: sidebar 
keywords: convert, snapmirror, relationship, asynchronous, synchronous, baseline, convert 
summary: A partire da ONTAP 9.5, è supportato SnapMirror Synchronous. È possibile convertire una relazione asincrona di SnapMirror in una relazione sincrona SnapMirror o viceversa senza eseguire un trasferimento baseline. 
---
= Convertire il tipo di relazione SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.5, è supportato SnapMirror Synchronous. È possibile convertire una relazione asincrona di SnapMirror in una relazione sincrona SnapMirror o viceversa senza eseguire un trasferimento baseline.

.A proposito di questa attività
Non è possibile convertire una relazione asincrona di SnapMirror in una relazione sincrona SnapMirror o viceversa modificando la policy SnapMirror

.Fasi
* *Conversione di una relazione asincrona SnapMirror in una relazione sincrona SnapMirror*
+
.. Dal cluster di destinazione, eliminare la relazione asincrona di SnapMirror:
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. Dal cluster di origine, rilasciare la relazione SnapMirror senza eliminare gli snapshot comuni:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. Dal cluster di destinazione, creare una relazione sincrona SnapMirror:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM>:<destination_volume> -policy sync-mirror`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. Risincronizzazione della relazione sincrona SnapMirror:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----


* *Conversione di una relazione sincrona SnapMirror in una relazione asincrona SnapMirror*
+
.. Dal cluster di destinazione, disattivare la relazione sincrona SnapMirror esistente:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
.. Dal cluster di destinazione, eliminare la relazione asincrona di SnapMirror:
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. Dal cluster di origine, rilasciare la relazione SnapMirror senza eliminare gli snapshot comuni:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. Dal cluster di destinazione, creare una relazione asincrona SnapMirror:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM:destination_volume> -policy MirrorAllSnapshots`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. Risincronizzazione della relazione sincrona SnapMirror:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----



