---
permalink: data-protection/create-snapshot-job-schedule-task.html 
sidebar: sidebar 
keywords: create, snapshot, job, schedule 
summary: Una policy Snapshot richiede almeno una pianificazione del lavoro di copia Snapshot. È possibile utilizzare il comando cron create della pianificazione del lavoro per creare una pianificazione del lavoro. 
---
= Creare una pianificazione del lavoro Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una policy Snapshot richiede almeno una pianificazione del lavoro di copia Snapshot. È possibile utilizzare `job schedule cron create` per creare una pianificazione del processo.

.A proposito di questa attività
Per impostazione predefinita, ONTAP crea i nomi delle copie Snapshot aggiungendo un indicatore data e ora al nome della pianificazione del processo.

Se si specificano valori per il giorno del mese e il giorno della settimana, i valori vengono considerati indipendentemente. Ad esempio, un programma cron con la specifica del giorno `Friday` e il giorno del mese specificato `13` Viene eseguito ogni venerdì e il 13° giorno di ogni mese, non solo ogni venerdì 13.

.Fase
. Creare una pianificazione del processo:
+
`job schedule cron create -name _job_name_ -month month -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
Per `-month`, `-dayofweek`, e. `-hour`, è possibile specificare `all` per eseguire il processo ogni mese, giorno della settimana e ora, rispettivamente.

+
A partire da ONTAP 9.10.1, è possibile includere il server virtuale per la pianificazione del processo:

+
`job schedule cron create -name _job_name_ -vserver _Vserver_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
Nell'esempio seguente viene creata una pianificazione del processo denominata `myweekly` Il sabato alle 3:00:

+
[listing]
----
cluster1::> job schedule cron create -name myweekly -dayofweek "Saturday" -hour 3 -minute 0
----
+
Nell'esempio seguente viene creata una pianificazione denominata `myweeklymulti` che specifica più giorni, ore e minuti:

+
[listing]
----
job schedule cron create -name myweeklymulti -dayofweek "Monday,Wednesday,Sunday" -hour 3,9,12 -minute 0,20,50
----

