---
permalink: data-protection/custom-vs-default-snapshot-policy-concept.html 
sidebar: sidebar 
keywords: configure, custom, snapshot, policy 
summary: Se il criterio Snapshot predefinito non è appropriato per un volume, è possibile configurare un criterio personalizzato che modifica la frequenza, la conservazione e il nome delle copie Snapshot. La pianificazione sarà dettata principalmente dalla velocità di cambiamento del file system attivo. 
---
= Quando configurare un criterio Snapshot personalizzato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il criterio Snapshot predefinito non è appropriato per un volume, è possibile configurare un criterio personalizzato che modifica la frequenza, la conservazione e il nome delle copie Snapshot. La pianificazione sarà dettata principalmente dalla velocità di cambiamento del file system attivo.

È possibile eseguire il backup di un file system molto utilizzato come un database ogni ora, mentre si eseguono backup di file raramente utilizzati una volta al giorno. Anche per un database, in genere viene eseguito un backup completo una o due volte al giorno, eseguendo il backup dei registri delle transazioni ogni ora.

Altri fattori sono l'importanza dei file per la tua organizzazione, il tuo Service Level Agreement (SLA), il tuo Recovery Point Objective (RPO) e il tuo Recovery Time Objective (RTO). In generale, è necessario conservare solo il numero di copie Snapshot necessario.
