---
permalink: data-protection/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy, data protection 
summary: 'Per i criteri personalizzati con il tipo di criterio "vault" o "mirror-vault", è necessario definire almeno una regola che determina quali snapshot vengono trasferite durante l"inizializzazione e l"aggiornamento. È inoltre possibile definire le regole per i criteri di default con il tipo di criterio "vault" o "mirroring-vault".' 
---
= Definire una regola per un criterio con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per i criteri personalizzati con il `vault` tipo di criterio o `mirror-vault` , è necessario definire almeno una regola che determina quali snapshot vengono trasferite durante l'inizializzazione e l'aggiornamento. È inoltre possibile definire le regole per i criteri predefiniti con il `vault` tipo di criterio o. `mirror-vault`

.A proposito di questa attività
Ogni criterio con il `vault` tipo di criterio o `mirror-vault` deve avere una regola che specifica gli snapshot da replicare. La regola `bi-monthly`, ad esempio, indica che devono essere replicati solo gli snapshot assegnati all'etichetta SnapMirror `bi-monthly`. È necessario specificare l'etichetta SnapMirror quando si configura il criterio snapshot sull'origine.

Ogni tipo di policy è associato a una o più regole definite dal sistema. Queste regole vengono assegnate automaticamente a un criterio quando si specifica il relativo tipo di criterio. La tabella seguente mostra le regole definite dal sistema.

[cols="3*"]
|===


| Regola definita dal sistema | Utilizzato nei tipi di policy | Risultato 


 a| 
sm_created
 a| 
async-mirror, mirror-vault, Sync, StrictSync
 a| 
Uno snapshot creato da SnapMirror viene trasferito all'inizializzazione e all'aggiornamento.



 a| 
all_source_snapshot
 a| 
mirror asincrono
 a| 
Le nuove istantanee sulla sorgente vengono trasferite all'inizializzazione e all'aggiornamento.



 a| 
ogni giorno
 a| 
vault, vault mirror
 a| 
I nuovi snapshot sulla sorgente con l'etichetta SnapMirror `daily` vengono trasferiti all'inizializzazione e all'aggiornamento.



 a| 
settimanale
 a| 
vault, vault mirror
 a| 
I nuovi snapshot sulla sorgente con l'etichetta SnapMirror `weekly` vengono trasferiti all'inizializzazione e all'aggiornamento.



 a| 
mensile
 a| 
vault mirror
 a| 
I nuovi snapshot sulla sorgente con l'etichetta SnapMirror `monthly` vengono trasferiti all'inizializzazione e all'aggiornamento.



 a| 
coerente con l'applicazione
 a| 
Sync, StrictSync
 a| 
Gli snapshot con l'etichetta SnapMirror `app_consistent` sull'origine vengono replicati in modo sincrono sulla destinazione. Supportato a partire da ONTAP 9,7.

|===
Ad eccezione del tipo di policy "`async-mirror`", è possibile specificare regole aggiuntive in base alle esigenze, per i criteri predefiniti o personalizzati. Ad esempio:

* Per il criterio predefinito `MirrorAndVault`, è possibile creare una regola chiamata `bi-monthly` per far corrispondere gli snapshot sull'origine con l' `bi-monthly`etichetta SnapMirror.
* Per un criterio personalizzato con il `mirror-vault` tipo di criterio, è possibile creare una regola chiamata `bi-weekly` per far corrispondere gli snapshot sull'origine con l' `bi-weekly`etichetta SnapMirror.


.Fase
. Definire una regola per un criterio:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
Ulteriori informazioni su `snapmirror policy add-rule` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Riferimento al comando ONTAP"^].

+
Nell'esempio seguente viene aggiunta una regola con l'etichetta SnapMirror `bi-monthly` al valore predefinito `MirrorAndVault` policy:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
Nell'esempio seguente viene aggiunta una regola con l'etichetta SnapMirror `bi-weekly` al personalizzato `my_snapvault` policy:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
Nell'esempio seguente viene aggiunta una regola con l'etichetta SnapMirror `app_consistent` al personalizzato `Sync` policy:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
Potrai quindi replicare le snapshot dal cluster di origine che corrispondono a questa etichetta SnapMirror:

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

