---
permalink: data-protection/delete-svm-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, svm, replication, relationship 
summary: È possibile utilizzare i comandi di eliminazione di snapmirror e di rilascio di snapmirror per eliminare una relazione di replica SVM. È quindi possibile eliminare manualmente i volumi di destinazione non necessari. 
---
= Eliminare una relazione di replica SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `snapmirror delete` e. `snapmirror release` Comandi per eliminare una relazione di replica SVM. È quindi possibile eliminare manualmente i volumi di destinazione non necessari.

.A proposito di questa attività
Il `snapmirror release` Il comando elimina tutte le copie Snapshot create da SnapMirror dall'origine. È possibile utilizzare `-relationship-info-only` Opzione per conservare le copie Snapshot.

Per la sintassi completa dei comandi, vedere la pagina man.

.Fasi
. Eseguire il seguente comando dalla SVM di destinazione o dal cluster di destinazione per interrompere la relazione di replica:
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente viene spezzata la relazione tra la SVM di origine `svm1` E la SVM di destinazione `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1: -destination-path svm_backup:
----
. Eseguire il seguente comando dalla SVM di destinazione o dal cluster di destinazione per eliminare la relazione di replica:
+
`snapmirror delete -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente viene eliminata la relazione tra la SVM di origine `svm1` E la SVM di destinazione `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1: -destination-path svm_backup:
----
. Eseguire il seguente comando dal cluster di origine o dalla SVM di origine per rilasciare le informazioni sulle relazioni di replica dalla SVM di origine:
+
`snapmirror release -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio riportato di seguito vengono rilasciate informazioni per la relazione di replica specificata dalla SVM di origine `svm1`:

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1: -destination-path svm_backup:
----

