---
permalink: data-protection/destination-volume-grows-automatically-concept.html 
sidebar: sidebar 
keywords: destination, volume, grow, automatic 
summary: 'Durante il trasferimento di un mirror per la protezione dei dati, le dimensioni del volume di destinazione aumentano automaticamente se il volume di origine è cresciuto, a condizione che nell"aggregato sia presente spazio disponibile che contiene il volume.' 
---
= Quando un volume di destinazione cresce automaticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante il trasferimento di un mirror per la protezione dei dati, le dimensioni del volume di destinazione aumentano automaticamente se il volume di origine è cresciuto, a condizione che nell'aggregato sia presente spazio disponibile che contiene il volume.

Questo comportamento si verifica indipendentemente da qualsiasi impostazione di crescita automatica sulla destinazione. Non puoi limitare la crescita del volume o impedire a ONTAP di crescere.

Per impostazione predefinita, i volumi di protezione dei dati sono impostati su `grow_shrink` modalità di dimensionamento automatico, che consente al volume di crescere o ridursi in risposta alla quantità di spazio utilizzato. La dimensione automatica massima per i volumi di protezione dei dati è uguale alla dimensione massima FlexVol e dipende dalla piattaforma. Ad esempio:

* FAS6220, volume DP predefinito max-autodize = 70 TB
* FAS8200, volume DP predefinito max-autodize = 100 TB


Per ulteriori informazioni, vedere https://hwu.netapp.com/["NetApp Hardware Universe"^].
