---
permalink: data-protection/dpo-systems-feature-enhancements-reference.html 
sidebar: sidebar 
keywords: dpo, systems, feature, enhancements, snapmirror, dp optimized, optimised, backoff, back off, deduplication, deduplicate, snapshot blocks, donors, compact, flexvol, license 
summary: 'A partire da ONTAP 9.6, il numero massimo di volumi FlexVol supportati aumenta quando viene installata la licenza DP_Optimized (DPO). A partire da ONTAP 9,4, i sistemi con licenza DPO supportano il backoff SnapMirror, la deduplica in background tra volumi, l"utilizzo di blocchi snapshot come donatori e la compaction.' 
---
= Miglioramenti delle funzionalità dei sistemi ONTAP DPO
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.6, il numero massimo di volumi FlexVol supportati aumenta quando viene installata la licenza DP_Optimized (DPO). A partire da ONTAP 9,4, i sistemi con licenza DPO supportano il backoff SnapMirror, la deduplica in background tra volumi, l'utilizzo di blocchi snapshot come donatori e la compaction.

A partire da ONTAP 9.6, il numero massimo di volumi FlexVol supportati sui sistemi secondari o di protezione dei dati è aumentato, consentendo di scalare fino a 2,500 volumi FlexVol per nodo o fino a 5,000 in modalità di failover. L'aumento dei volumi FlexVol è abilitato con link:../data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["Licenza DP_Optimized (DPO)"]. È ancora necessario un link:../system-admin/manage-license-task.html#view-details-about-a-license["Licenza SnapMirror"]su entrambi i nodi di origine e destinazione.

A partire da ONTAP 9.4, ai sistemi DPO sono stati apportati i seguenti miglioramenti:

* Backoff di SnapMirror: Nei sistemi DPO, al traffico di replica viene assegnata la stessa priorità dei carichi di lavoro client.
+
Il backoff di SnapMirror è disattivato per impostazione predefinita nei sistemi DPO.

* Deduplica del volume in background e deduplica del cross-volume in background: La deduplica del volume in background e la deduplica del cross-volume in background sono abilitate nei sistemi DPO.
+
È possibile eseguire `storage aggregate efficiency cross-volume-dedupe start -aggregate _aggregate_name_ -scan-old-data true` per deduplicare i dati esistenti. La Best practice consiste nell'eseguire il comando durante le ore di lavoro fuori dalle ore di punta per ridurre l'impatto sulle performance.

+
Ulteriori informazioni su `storage aggregate efficiency cross-volume-dedupe start` nella link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-start.html["Riferimento al comando ONTAP"^].

* Maggiori risparmi utilizzando i blocchi degli snapshot come donatori: I blocchi di dati non disponibili nel file system attivo ma intrappolati negli snapshot vengono utilizzati come donatori per la deduplica dei volumi.
+
I nuovi dati possono essere deduplicati con i dati intrappolati nelle snapshot, condividendo efficacemente anche i blocchi snapshot. L'aumento dello spazio donatore offre ulteriori risparmi, soprattutto quando il volume dispone di un elevato numero di snapshot.

* Compaction (compattazione): La compattazione dei dati è attivata per impostazione predefinita sui volumi DPO.

