---
permalink: data-protection/extended-queries-many-snapmirror-relationships-task.html 
sidebar: sidebar 
keywords: extend, query, act, snapmirror, relationships 
summary: È possibile utilizzare query estese per eseguire contemporaneamente operazioni SnapMirror su molte relazioni SnapMirror. Ad esempio, potrebbero essere presenti più relazioni SnapMirror non inizializzate che si desidera inizializzare utilizzando un solo comando. 
---
= Ulteriori informazioni sulle query estese per le operazioni relative alle relazioni con ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare _query estese_ per eseguire contemporaneamente operazioni SnapMirror su molte relazioni SnapMirror. Ad esempio, potrebbero essere presenti più relazioni SnapMirror non inizializzate che si desidera inizializzare utilizzando un solo comando.

.A proposito di questa attività
È possibile applicare query estese alle seguenti operazioni SnapMirror:

* Inizializzazione delle relazioni non inizializzate
* Ripresa delle relazioni in quiescenza
* Risincronizzazione delle relazioni interrotte
* Aggiornamento delle relazioni inattive
* Interruzione dei trasferimenti di dati di relazione


.Fase
. Eseguire un'operazione SnapMirror su molte relazioni:
+
`_snapmirror command_ {-state state } *`

+
Il comando seguente inizializza le relazioni SnapMirror che si trovano in un `Uninitialized` stato:

+
[listing]
----
vs1::> snapmirror initialize {-state Uninitialized} *
----
+
Ulteriori informazioni su `snapmirror initialize` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["Riferimento al comando ONTAP"^].


