---
permalink: data-protection/limitations-mirror-relationships-concept.html 
sidebar: sidebar 
keywords: snapmirror, limitations 
summary: Prima di creare una relazione di protezione dei dati, è necessario conoscere le limitazioni di base di SnapMirror. 
---
= Limitazioni di SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di creare una relazione di protezione dei dati, è necessario conoscere le limitazioni di base di SnapMirror.

* Un volume di destinazione può avere un solo volume di origine.
+
[NOTE]
====
Un volume di origine può avere più volumi di destinazione. Il volume di destinazione può essere il volume di origine per qualsiasi tipo di relazione di replica di SnapMirror.

====
* È possibile aprire un massimo di otto volumi di destinazione da un singolo volume di origine.
* Non è possibile ripristinare i file sulla destinazione di una relazione di DR di SnapMirror.
* I volumi SnapVault di origine o di destinazione non possono essere a 32 bit.
* Il volume di origine per una relazione SnapVault non deve essere un volume FlexClone.
+
[NOTE]
====
La relazione funzionerà, ma l'efficienza offerta dai volumi FlexClone non verrà preservata.

====

