---
permalink: data-protection/long-term-retention-snapshots-concept.html 
sidebar: sidebar 
keywords: local, snapshot, retention, snapmirror, vault 
summary: È possibile creare snapshot di conservazione a lungo termine direttamente sul volume secondario di una relazione SnapMirror utilizzando il tipo di policy vault o mirror-vault.  Questi snapshot vengono conservati nella destinazione come backup. 
---
= Scopri di più sugli snapshot di conservazione a lungo termine ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le relazioni SnapMirror con un tipo di policy "vault" o "mirror-vault" consentono la creazione di snapshot direttamente sul volume secondario della relazione SnapMirror . Questi snapshot vengono conservati nella destinazione come backup. Questi snapshot vengono spesso creati per la conservazione a lungo termine e sono chiamati snapshot di conservazione a lungo termine (LTR).

È possibile creare uno snapshot di conservazione a lungo termine specificando una pianificazione della creazione dello snapshot nella regola del criterio SnapMirror , il prefisso del nome dello snapshot, l'etichetta SnapMirror e il conteggio della conservazione.  Questo snapshot viene conservato sul volume di destinazione SnapMirror indipendentemente dalle regole di conservazione sull'origine.

Gli snapshot di conservazione a lungo termine sono disponibili solo per le configurazioni FlexVol SnapMirror .  Non è possibile creare snapshot LTR per le configurazioni FlexGroup SnapMirror .

In una relazione a cascata SnapMirror , gli snapshot di conservazione a lungo termine possono essere creati solo sull'ultimo volume della cascata.



== Informazioni correlate

* link:supported-deployment-config-concept.html#how-cascade-deployments-work["Scopri come funzionano le distribuzioni a cascata"]
* link:define-schedule-create-local-copy-destination-task.html["Definire una pianificazione ONTAP SnapMirror per creare una copia locale sulla destinazione"]

