---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: 'Uno snapshot è un"immagine di sola lettura e point-in-time di un volume. L"immagine occupa uno spazio di storage minimo e comporta un overhead delle prestazioni trascurabile in quanto registra solo le modifiche apportate ai file dall"ultimo snapshot.' 
---
= Informazioni sulla gestione degli snapshot ONTAP locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un _snapshot_ è un'immagine di sola lettura e point-in-time di un volume. L'immagine occupa uno spazio di storage minimo e comporta un overhead delle prestazioni trascurabile in quanto registra solo le modifiche apportate ai file dall'ultimo snapshot.

È possibile utilizzare uno snapshot per ripristinare l'intero contenuto di un volume o singoli file o LUN, mentre gli snapshot vengono memorizzati nella directory del volume. `.snapshot`

In ONTAP 9.4 e versioni successive, un FlexVol volume può contenere fino a 1023 snapshot.  In ONTAP 9.3 e versioni precedenti, un volume può contenere fino a 255 snapshot.

[NOTE]
====
A partire da ONTAP 9,8, FlexGroup Volumes può contenere 1023 snapshot. Per ulteriori informazioni, vedere link:../flexgroup/protect-snapshot-copies-task.html["Proteggi i volumi FlexGroup utilizzando le snapshot"].

====
Esistono diversi tipi comuni di snapshot ONTAP:

* `sched_created`Snapshot generati automaticamente da una policy di snapshot ONTAP, in base a pianificazioni predefinite (ad esempio, orarie, giornaliere, settimanali o mensili).
* `sm_created`: Snapshot creati automaticamente a seguito di trasferimenti di replica SnapMirror (operazioni di aggiornamento o di inizializzazione).
* `application_created`: Snapshot generati da software di integrazione a livello host o a livello di database come SnapCenter o SnapDrive.
* `user_created`: Snapshot attivati manualmente da un amministratore utilizzando la ONTAP CLI o System Manager.
* `sv_created`: Snapshot creati automaticamente durante le operazioni del cluster, come il DR delle Storage Virtual Machine (SVM) o specifici flussi di lavoro di protezione.
* `luns_created`: Snapshot creati per eseguire il backup o acquisire lo stato di cloni di LUN o namespace NVMe.

