---
permalink: data-protection/manage-snapmirror-root-volume-replication-concept.html 
sidebar: sidebar 
keywords: manage, snapmirror, root volume , replication 
summary: 'Ogni SVM in un ambiente NAS ha un namespace univoco. Il volume root della SVM è il punto di accesso a questa gerarchia di namespace. Per i cluster composti da due o più coppie HA, è consigliabile considerare i mirror con bilanciamento del carico (LSM) del volume root della SVM per garantire che il namespace rimanga accessibile ai client nel caso in cui entrambi i nodi di una coppia HA vadano in errore.' 
---
= Leggi le informazioni sulla replica del volume root di ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni SVM in un ambiente NAS ha un namespace univoco. Il volume root della SVM è il punto di accesso a questa gerarchia di namespace. Per i cluster composti da due o più coppie HA, è consigliabile considerare i mirror con bilanciamento del carico (LSM) del volume root della SVM per garantire che il namespace rimanga accessibile ai client nel caso in cui entrambi i nodi di una coppia HA si guastino. I mirror con bilanciamento del carico non sono adatti per cluster composti da una singola coppia HA e non sono adatti per un ambiente MetroCluster.

* A partire da ONTAP 9.1, i mirror con bilanciamento del carico sono stati deprecati per i volumi di dati e sono supportati solo per i volumi root SVM.
* SnapMirror load-sharing mirrors sono in grado di supportare solo client NAS (CIFS/NFSv3). I mirror con bilanciamento del carico non supportano client NFSv4 né connessioni tramite protocollo client SAN (FC, FCoE o iSCSI). Tuttavia, NFSv4 e i mirror con bilanciamento del carico possono coesistere nello stesso ambiente.

