---
permalink: data-protection/manage-storage-efficiency-task.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, snapmirror, snap mirror, compression, compress, postporcess, update relationship, volume 
summary: 'SnapMirror preserva l"efficienza dello storage sui volumi di origine e di destinazione, con un"eccezione, quando la compressione dei dati post-elaborazione è attivata sulla destinazione. In tal caso, tutta l"efficienza dello storage viene persa sulla destinazione. Per risolvere questo problema, è necessario disattivare la compressione post-elaborazione sulla destinazione, aggiornare manualmente la relazione e riattivare l"efficienza dello storage.' 
---
= Gestire l'efficienza dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror preserva l'efficienza dello storage sui volumi di origine e di destinazione, con un'eccezione, quando la compressione dei dati post-elaborazione è attivata sulla destinazione. In tal caso, tutta l'efficienza dello storage viene persa sulla destinazione. Per risolvere questo problema, è necessario disattivare la compressione post-elaborazione sulla destinazione, aggiornare manualmente la relazione e riattivare l'efficienza dello storage.

.Di cosa hai bisogno
* I cluster di origine e di destinazione e le SVM devono essere peering.
+
https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["Peering di cluster e SVM"]

* È necessario disattivare la compressione post-elaborazione sulla destinazione.


.A proposito di questa attività
È possibile utilizzare `volume efficiency show` comando per determinare se l'efficienza è attivata su un volume. Per ulteriori informazioni, consulta le pagine man.

È possibile verificare se SnapMirror mantiene l'efficienza dello storage visualizzando i registri di controllo di SnapMirror e individuando la descrizione del trasferimento. Se viene visualizzata la descrizione del trasferimento `transfer_desc=Logical Transfer`, SnapMirror non mantiene l'efficienza dello storage. Se viene visualizzata la descrizione del trasferimento `transfer_desc=Logical Transfer with Storage Efficiency`, SnapMirror sta mantenendo l'efficienza dello storage. Ad esempio:

[listing]
----
Fri May 22 02:13:02 CDT 2020 ScheduledUpdate[May 22 02:12:00]:cc0fbc29-b665-11e5-a626-00a09860c273 Operation-Uuid=39fbcf48-550a-4282-a906-df35632c73a1 Group=none Operation-Cookie=0 action=End source=<sourcepath> destination=<destpath> status=Success bytes_transferred=117080571 network_compression_ratio=1.0:1 transfer_desc=Logical Transfer - Optimized Directory Mode
----
Trasferimento logico con storage

A partire da ONTAP 9.3, l'aggiornamento manuale non è più necessario per riattivare l'efficienza dello storage. Se SnapMirror rileva che la compressione post-processo è stata disattivata, riattiva automaticamente l'efficienza dello storage al successivo aggiornamento pianificato. Sia l'origine che la destinazione devono eseguire ONTAP 9.3.

A partire da ONTAP 9.3, i sistemi AFF gestiscono le impostazioni di efficienza dello storage in modo diverso dai sistemi FAS dopo che un volume di destinazione è reso scrivibile:

* Dopo aver impostato un volume di destinazione scrivibile utilizzando `snapmirror break` il criterio di caching sul volume viene automaticamente impostato su "`auto`" (impostazione predefinita).
+
[NOTE]
====
Questo comportamento è applicabile solo ai volumi FlexVol e non ai volumi FlexGroup.

====
* Alla risincronizzazione, il criterio di caching viene automaticamente impostato su "`none`" e deduplica e compressione inline vengono automaticamente disabilitate, indipendentemente dalle impostazioni originali. È necessario modificare le impostazioni manualmente in base alle necessità.


[NOTE]
====
Gli aggiornamenti manuali con l'efficienza dello storage abilitata possono richiedere molto tempo. Potrebbe essere necessario eseguire l'operazione in ore non di punta.

====
.Fase
. Aggiornare una relazione di replica e riattivare l'efficienza dello storage:
+
`snapmirror update -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ... -enable-storage-efficiency true`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
È necessario eseguire questo comando dalla SVM di destinazione o dal cluster di destinazione. Il comando non riesce se non esiste una copia Snapshot comune sull'origine e sulla destinazione. Utilizzare `snapmirror initialize` per reinizializzare la relazione.

====
+
Nell'esempio seguente viene aggiornata la relazione tra il volume di origine `volA` acceso `svm1` e il volume di destinazione `volA_dst` acceso `svm_backup`e riattiva l'efficienza dello storage:

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst -enable-storage-efficiency true
----

