---
permalink: data-protection/manage-snapmirror-root-volume-replication-concept.html 
sidebar: sidebar 
keywords: manage, snapmirror, root volume , replication 
summary: Ogni SVM in un ambiente NAS ha uno spazio dei nomi unico. Il volume root SVM, contenente il sistema operativo e le informazioni correlate, è il punto di ingresso della gerarchia dello spazio dei nomi. Per garantire che i dati rimangano accessibili ai client in caso di interruzione o failover di un nodo, è necessario creare una copia mirror di condivisione del carico del volume root SVM. 
---
= Leggi le informazioni sulla replica del volume root di ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni SVM in un ambiente NAS ha uno spazio dei nomi unico. Il _volume root di SVM,_ contenente il sistema operativo e le relative informazioni, è il punto di ingresso della gerarchia dello spazio dei nomi. Per garantire che i dati rimangano accessibili ai client in caso di interruzione o failover di un nodo, è necessario creare una copia mirror di condivisione del carico del volume root SVM.

Lo scopo principale dei mirror di condivisione del carico per i volumi root SVM non è più la condivisione del carico, ma il loro scopo è il disaster recovery.

* Se il volume root non è temporaneamente disponibile, il mirror di load-sharing fornisce automaticamente l'accesso in sola lettura ai dati del volume root.
* Se il volume root non è disponibile in modo permanente, è possibile promuovere uno dei volumi di load sharing per fornire l'accesso in scrittura ai dati del volume root.

