---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: 'Una copia Snapshot è un"immagine point-in-time di sola lettura di un volume. L"immagine consuma uno spazio di storage minimo e comporta un overhead delle performance trascurabile, in quanto registra solo le modifiche apportate ai file dall"ultima copia Snapshot.' 
---
= Panoramica sulla gestione delle copie Snapshot locali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una _copia Snapshot_ è un'immagine point-in-time di sola lettura di un volume. L'immagine consuma uno spazio di storage minimo e comporta un overhead delle performance trascurabile, in quanto registra solo le modifiche apportate ai file dall'ultima copia Snapshot.

È possibile utilizzare una copia Snapshot per ripristinare l'intero contenuto di un volume o per ripristinare singoli file o LUN. Le copie Snapshot vengono memorizzate nella directory `.snapshot` sul volume.

In ONTAP 9.3 e versioni precedenti, un volume può contenere fino a 255 copie Snapshot. In ONTAP 9.4 e versioni successive, un volume FlexVol può contenere fino a 1023 copie Snapshot.

[NOTE]
====
A partire da ONTAP 9.8, i volumi FlexGroup possono contenere 1023 copie Snapshot. Per ulteriori informazioni, vedere link:../flexgroup/protect-snapshot-copies-task.html["Proteggere i volumi FlexGroup utilizzando le copie Snapshot"].

====