---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: 'È possibile utilizzare il comando di creazione del proprietario dello snapshot di SnapMirror per conservare uno snapshot etichettato sul secondario in una distribuzione del vault mirror. In questo modo, si garantisce l"esistenza di uno snapshot comune per l"aggiornamento della relazione del vault.' 
---
= Assicurarsi di avere uno snapshot comune in una distribuzione del vault dei mirror di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il  `snapmirror snapshot-owner create` Comando per preservare uno snapshot etichettato sul secondario in una distribuzione mirror-vault. In questo modo si garantisce l'esistenza di uno snapshot comune per l'aggiornamento della relazione tra vault.

.A proposito di questa attività
Se si utilizza una combinazione di distribuzione fan-out del vault dei mirror o a cascata, è necessario tenere presente che gli aggiornamenti non avranno esito positivo se non esiste uno snapshot comune sui volumi di origine e destinazione.

Questo non è mai un problema per la relazione di mirroring in una distribuzione fan-out o a cascata del vault dei mirror, poiché SnapMirror crea sempre uno snapshot del volume di origine prima di eseguire l'aggiornamento.

Potrebbe essere un problema per la relazione del vault, tuttavia, perché SnapMirror non crea uno snapshot del volume di origine quando aggiorna una relazione del vault. È necessario utilizzare `snapmirror snapshot-owner create` per assicurarsi che vi sia almeno uno snapshot comune sia sull'origine che sulla destinazione della relazione del vault. link:supported-deployment-config-concept.html["Scopri di più sulle implementazioni fan-out e a cascata della data Protection"].

.Fasi
. Sul volume di origine, assegnare un proprietario allo snapshot etichettato che si desidera conservare:
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
Nell'esempio seguente viene assegnato `ApplicationA` come proprietario `snap1` dello snapshot:

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
Scopri di più su  `snapmirror snapshot-owner create` nel link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-create.html["Riferimento al comando ONTAP"^] .

. Aggiornare la relazione mirror, come descritto in link:update-replication-relationship-manual-task.html["Aggiornamento manuale di una relazione di replica"].
+
In alternativa, è possibile attendere l'aggiornamento pianificato della relazione mirror.

. Trasferire lo snapshot etichettato alla destinazione del vault:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
L'esempio seguente trasferisce lo `snap1` snapshot::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
Lo snapshot etichettato verrà conservato quando la relazione del vault viene aggiornata.

Ulteriori informazioni su `snapmirror update` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["Riferimento al comando ONTAP"^].

--


. Sul volume di origine, rimuovere il proprietario dall'istantanea etichettata:
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
Gli esempi seguenti vengono rimossi `ApplicationA` come proprietario `snap1` dello snapshot:

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
Ulteriori informazioni su `snapmirror snapshot-owner delete` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-delete.html["Riferimento al comando ONTAP"^].


