---
permalink: data-protection/reactivate-original-source-svm-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, svm, quick resync, resynchronize, reverse resync 
summary: 'È possibile ristabilire la relazione di protezione dei dati originale tra la SVM di origine e di destinazione quando non è più necessario fornire dati dalla destinazione. La procedura è in gran parte identica alla procedura per la replica del volume, con un"eccezione. È necessario arrestare la SVM di destinazione prima di riattivare la SVM di origine.' 
---
= Riattivare l'SVM di origine originale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ristabilire la relazione di protezione dei dati originale tra la SVM di origine e di destinazione quando non è più necessario fornire dati dalla destinazione. La procedura è in gran parte identica alla procedura per la replica del volume, con un'eccezione. È necessario arrestare la SVM di destinazione prima di riattivare la SVM di origine.

.Di cosa hai bisogno
Se si sono aumentate le dimensioni del volume di destinazione durante la distribuzione dei dati da esso, prima di riattivare il volume di origine, è necessario aumentare manualmente la dimensione massima automatica sul volume di origine per garantire che possa crescere in modo sufficiente.

link:destination-volume-grows-automatically-concept.html["Quando un volume di destinazione cresce automaticamente"]

.A proposito di questa attività
A partire da ONTAP 9.11.1, è possibile ridurre il tempo di risincronizzazione durante una prova di disaster recovery utilizzando `-quick-resync true` opzione di `snapmirror resync` Durante l'esecuzione di una risincronizzazione inversa di una relazione DR SVM. Una rapida risincronizzazione può ridurre il tempo necessario per tornare alla produzione ignorando le operazioni di ricostruzione e ripristino del data warehouse.


NOTE: La risincronizzazione rapida non preserva l'efficienza dello storage dei volumi di destinazione. L'attivazione della risincronizzazione rapida potrebbe aumentare lo spazio del volume utilizzato dai volumi di destinazione.

Questa procedura presuppone che la linea di base nel volume di origine originale sia intatta. Se la linea di base non è intatta, è necessario creare e inizializzare la relazione tra il volume da cui si stanno fornendo i dati e il volume di origine originale prima di eseguire la procedura.

Per la sintassi completa dei comandi, vedere la pagina man.

.Fasi
. Dalla SVM di origine originale o dal cluster di origine, creare una relazione DR SVM inversa utilizzando la stessa configurazione, policy e impostazioni di conservazione delle identità della relazione DR SVM originale:
+
`snapmirror create -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente viene creata una relazione tra la SVM da cui vengono forniti i dati, `svm_backup`E la SVM di origine originale, `svm1`:

+
[listing]
----
cluster_src::> snapmirror create -source-path svm_backup: -destination-path svm1:
----
. Dalla SVM di origine originale o dal cluster di origine, eseguire il seguente comando per invertire la relazione di protezione dei dati:
+
`snapmirror resync -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Sebbene la risincronizzazione non richieda un trasferimento di riferimento, può richiedere molto tempo. È possibile eseguire la risincronizzazione in ore non di punta.

+
[NOTE]
====
Il comando non riesce se non esiste una copia Snapshot comune sull'origine e sulla destinazione. Utilizzare `snapmirror initialize` per reinizializzare la relazione.

====
+
Nell'esempio seguente viene invertita la relazione tra la SVM di origine originale, `svm1`E la SVM da cui vengono forniti i dati, `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup: -destination-path svm1:
----
+
Esempio di utilizzo dell'opzione -quick-resync:

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup: -destination-path svm1: -quick-resync true
----
. Quando si è pronti a ristabilire l'accesso ai dati alla SVM di origine, arrestare la SVM di destinazione originale per disconnettere tutti i client attualmente connessi alla SVM di destinazione originale.
+
`vserver stop -vserver _SVM_`

+
Nell'esempio riportato di seguito viene interrotta la SVM di destinazione originale che attualmente fornisce i dati:

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. Verificare che la SVM di destinazione originale si trovi nello stato arrestato utilizzando `vserver show` comando.
+
[listing]
----
cluster_dst::> vserver show
                                  Admin      Operational Root
Vserver        Type    Subtype    State      State       Volume     Aggregate
--------       ------- ---------- ---------- ----------- ---------- ----------
svm_backup     data    default    stopped    stopped     rv         aggr1
----
. Dalla SVM di origine originale o dal cluster di origine originale, eseguire il seguente comando per eseguire l'aggiornamento finale della relazione inversa e trasferire tutte le modifiche dalla SVM di destinazione originale alla SVM di origine:
+
`snapmirror update -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio riportato di seguito viene aggiornata la relazione tra la SVM di destinazione originale da cui vengono forniti i dati,`svm_backup`E la SVM di origine originale, `svm1`:

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup: -destination-path svm1:
----
. Dalla SVM di origine originale o dal cluster di origine originale, eseguire il seguente comando per interrompere i trasferimenti pianificati per la relazione inversa:
+
`snapmirror quiesce -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente vengono interrompiti i trasferimenti pianificati tra la SVM da cui si stanno fornendo i dati, `svm_backup`E la SVM originale, `svm1`:

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup: -destination-path svm1:
----
. Quando l'aggiornamento finale è completo e la relazione indica "Quiesced" per lo stato della relazione, eseguire il seguente comando dalla SVM di origine o dal cluster di origine originale per interrompere la relazione invertita:
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente viene spezzata la relazione tra la SVM di destinazione originale da cui si stavano servendo i dati, `svm_backup`E la SVM di origine originale, `svm1`:

+
[listing]
----
cluster_src::> snapmirror break -source-path svm_backup: -destination-path svm1:
----
. Se la SVM di origine originale è stata precedentemente arrestata, dal cluster di origine, avviare la SVM di origine originale:
+
`vserver start -vserver _SVM_`

+
Nell'esempio seguente viene avviata la SVM di origine originale:

+
[listing]
----
cluster_src::> vserver start svm1
----
. Dalla SVM di destinazione originale o dal cluster di destinazione originale, ristabilire la relazione di protezione dei dati originale:
+
`snapmirror resync -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente viene ristabilita la relazione tra la SVM di origine originale, `svm1`E la SVM di destinazione originale, `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1: -destination-path svm_backup:
----
. Dalla SVM di origine originale o dal cluster di origine originale, eseguire il seguente comando per eliminare la relazione di protezione dei dati invertita:
+
`snapmirror delete -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente viene eliminata la relazione inversa tra la SVM di destinazione originale, `svm_backup`E la SVM di origine originale, `svm1`:

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup: -destination-path svm1:
----
. Dalla SVM di destinazione originale o dal cluster di destinazione originale, rilasciare la relazione di protezione dei dati invertita:
+
`snapmirror release -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
Inserire i due punti (:) dopo il nome SVM in `-source-path` e. `-destination-path` opzioni. Vedere l'esempio riportato di seguito.

====
+
Nell'esempio seguente viene rilasciata la relazione inversa tra SVM di destinazione originale, svm_backup e SVM di origine, `svm1`

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup: -destination-path svm1:
----


.Al termine
Utilizzare `snapmirror show` Per verificare che sia stata creata la relazione SnapMirror. Per la sintassi completa dei comandi, vedere la pagina man.
