---
permalink: data-protection/restore-single-file-lun-task.html 
sidebar: sidebar 
keywords: restore, single file, lun, nvme, namespace, snapmirror, destination, snapshot, copy, snap mirror, baseline, 
summary: Puoi ripristinare un singolo file, LUN, un set di file o LUN da uno snapshot o un namespace NVMe da un volume di destinazione SnapMirror. A partire da ONTAP 9.7, puoi anche ripristinare i namespace NVMe da una destinazione sincrona SnapMirror. È possibile ripristinare i file nel volume di origine originale o in un volume diverso. 
---
= Ripristino di un file, LUN o namespace NVMe da una destinazione ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi ripristinare un singolo file, LUN, un set di file o LUN da uno snapshot o un namespace NVMe da un volume di destinazione SnapMirror. A partire da ONTAP 9.7, puoi anche ripristinare i namespace NVMe da una destinazione sincrona SnapMirror. È possibile ripristinare i file nel volume di origine originale o in un volume diverso.

.Prima di iniziare
Per ripristinare un file o LUN da una destinazione sincrona SnapMirror (supportata a partire da ONTAP 9.5), occorre prima eliminare e rilasciare la relazione.

.A proposito di questa attività
Il volume su cui si ripristinano file o LUN (il volume di destinazione) deve essere un volume di lettura/scrittura:

* SnapMirror esegue un _ripristino incrementale_ se i volumi di origine e di destinazione hanno uno snapshot comune (come in genere avviene quando si esegue il ripristino del volume di origine).
* In caso contrario, SnapMirror esegue un ripristino _baseline_, in cui lo snapshot specificato e tutti i blocchi di dati a cui fa riferimento vengono trasferiti al volume di destinazione.


.Fasi
. Elencare gli snapshot nel volume di destinazione:
+
`volume snapshot show -vserver <SVM> -volume volume`

+
Ulteriori informazioni su `volume snapshot show` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["Riferimento al comando ONTAP"^].

+
L'esempio seguente mostra gli snapshot sulla `vserverB:secondary1` destinazione:

+
[listing]
----

cluster_dst::> volume snapshot show -vserver vserverB -volume secondary1

Vserver     Volume      Snapshot                State    Size  Total% Used%
-------     ------      ---------- ----------- ------   -----  ------ -----
vserverB    secondary1  hourly.2013-01-25_0005  valid   224KB     0%    0%
                        daily.2013-01-25_0010   valid   92KB      0%    0%
                        hourly.2013-01-25_0105  valid   228KB     0%    0%
                        hourly.2013-01-25_0205  valid   236KB     0%    0%
                        hourly.2013-01-25_0305  valid   244KB     0%    0%
                        hourly.2013-01-25_0405  valid   244KB     0%    0%
                        hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Ripristino di un singolo file o LUN o di un set di file o LUN da uno snapshot in un volume di destinazione SnapMirror:
+
`snapmirror restore -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot -file-list <source_file_path,@destination_file_path>`

+
Ulteriori informazioni su `snapmirror restore` nella link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["Riferimento al comando ONTAP"^].

+
[NOTE]
====
È necessario eseguire questo comando dalla SVM di destinazione o dal cluster di destinazione.

====
+
Il seguente comando ripristina i file `file1` e `file2` lo snapshot `daily.2013-01-25_0010` nel volume di destinazione originale `secondary1` , nella stessa posizione nel file system attivo del volume di origine `primary1` :

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir1/file1,/dir2/file2

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----
+
Il seguente comando ripristina i file `file1` e `file2` lo snapshot `daily.2013-01-25_0010` nel volume di destinazione originale `secondary1` , in una posizione diversa nel file system attivo del volume di origine `primary1` .

+
Il percorso del file di destinazione inizia con il simbolo @ seguito dal percorso del file dalla directory principale del volume di origine originale. In questo esempio, `file1` viene ripristinato a. `/dir1/file1.new` e il file2 viene ripristinato a. `/dir2.new/file2` acceso `primary1`:

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir/file1,@/dir1/file1.new,/dir2/file2,@/dir2.new/file2

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----
+
Il seguente comando ripristina i file `file1` e lo snapshot `daily.2013-01-25_0010` nel volume di destinazione originale `secondary1` , in diverse posizioni nel file system attivo del volume di origine e `file3` ripristina `file2` da `snap1` nella `primary1` stessa posizione nel file system attivo di `primary1`.

+
In questo esempio, il file `file1` viene ripristinato a. `/dir1/file1.new` e. `file3` viene ripristinato a. `/dir3.new/file3`:

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir/file1,@/dir1/file1.new,/dir2/file2,/dir3/file3,@/dir3.new/file3

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----

