---
permalink: data-protection/restore-single-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, single file, snapshot copy 
summary: È possibile utilizzare il comando volume snapshot restore-file per ripristinare un singolo file o LUN da una copia Snapshot. Se non si desidera sostituire un file esistente, è possibile ripristinare il file in una posizione diversa nel volume di lettura/scrittura padre. 
---
= Ripristino di un singolo file da una copia Snapshot con ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `volume snapshot restore-file` Comando per ripristinare un singolo file o LUN da una copia Snapshot. Se non si desidera sostituire un file esistente, è possibile ripristinare il file in una posizione diversa nel volume di lettura/scrittura padre.

.A proposito di questa attività
Se si sta ripristinando un LUN esistente, viene creato un clone del LUN e ne viene eseguito il backup sotto forma di copia Snapshot. Durante l'operazione di ripristino, è possibile leggere e scrivere sul LUN.

I file con flussi vengono ripristinati per impostazione predefinita.

.Fasi
. Elencare le copie Snapshot in un volume:
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Ulteriori informazioni su `volume snapshot show` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["Riferimento al comando ONTAP"^].

+
L'esempio seguente mostra le copie Snapshot in `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	    vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Ripristinare un file da una copia Snapshot:
+
`volume snapshot restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -restore-path _destination_path_`

+
Ulteriori informazioni su `volume snapshot restore-file` nella link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-restore-file.html["Riferimento al comando ONTAP"^].

+
Nell'esempio riportato di seguito viene ripristinato il file `myfile.txt`:

+
[listing]
----
cluster1::> volume snapshot restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt
----

