---
permalink: data-protection/resynchronize-relationship-task.html 
sidebar: sidebar 
keywords: resynchronize, replication, relationship 
summary: È necessario risincronizzare una relazione di replica dopo che si rende scrivibile un volume di destinazione, dopo che un aggiornamento non riesce perché non esiste una copia Snapshot comune sui volumi di origine e di destinazione o se si desidera modificare il criterio di replica per la relazione. 
---
= Risincronizzare una relazione di replica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario risincronizzare una relazione di replica dopo che si rende scrivibile un volume di destinazione, dopo che un aggiornamento non riesce perché non esiste una copia Snapshot comune sui volumi di origine e di destinazione o se si desidera modificare il criterio di replica per la relazione.

.A proposito di questa attività
* Sebbene la risincronizzazione non richieda un trasferimento di riferimento, può richiedere molto tempo. È possibile eseguire la risincronizzazione in ore non di punta.
* La risincronizzazione dei volumi che fanno parte di una configurazione fan-out o a cascata può richiedere più tempo. Non è raro che la relazione di SnapMirror riporti lo stato di "preparazione" per un periodo di tempo prolungato.


.Fase
. Risincronizzare i volumi di origine e di destinazione:
+
`snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ... -type DP|XDP -schedule _schedule_ -policy _policy_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
È necessario eseguire questo comando dalla SVM di destinazione o dal cluster di destinazione.

====
+
Nell'esempio riportato di seguito viene risincronata la relazione tra il volume di origine `volA` acceso `svm1` e il volume di destinazione `volA_dst` acceso `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----

