---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: A partire da ONTAP 9.3, le licenze sono state semplificate per la replica tra istanze di ONTAP. Nelle versioni di ONTAP 9, la licenza SnapMirror supporta le relazioni di vault e mirror. Gli utenti possono ora acquistare una licenza SnapMirror per supportare la replica ONTAP per i casi di utilizzo di backup e disaster recovery. 
---
= Panoramica sulle licenze di SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.3, le licenze sono state semplificate per la replica tra istanze di ONTAP. Nelle versioni di ONTAP 9, la licenza SnapMirror supporta le relazioni di vault e mirror. Puoi utilizzare una licenza SnapMirror per supportare la replica ONTAP per casi d'utilizzo di backup e disaster recovery.

Prima della release di ONTAP 9,3, era necessaria una licenza SnapVault separata per configurare le relazioni _vault_ tra le istanze di ONTAP, in cui l'istanza DP poteva mantenere un numero più elevato di copie Snapshot per supportare i casi d'utilizzo del backup con tempi di conservazione più lunghi, inoltre, era necessaria una licenza SnapMirror per configurare relazioni _mirror_ tra istanze di ONTAP, in cui ciascuna istanza di ONTAP conservava lo stesso numero di copie Snapshot (ovvero un'immagine _mirror_) per supportare i casi d'utilizzo di disaster recovery al fine di rendere possibili i failover dei cluster. Le licenze SnapMirror e SnapVault continuano a essere utilizzate e supportate per le release di ONTAP 8.x e 9.x.

Mentre le licenze SnapVault continuano a funzionare e sono supportate per entrambe le release di ONTAP 8.x e 9.x, la licenza SnapMirror può essere utilizzata al posto di una licenza SnapVault e può essere utilizzata sia per le configurazioni mirror che per quelle del vault.

Per la replica asincrona di ONTAP, a partire da ONTAP 9.3 viene utilizzato un singolo motore di replica unificato per configurare i criteri XDP (Extended Data Protection Mode), in cui la licenza SnapMirror può essere configurata per un criterio mirror, un criterio di vault o un criterio di vault mirror. È necessaria una licenza SnapMirror sia per i cluster di origine che per quelli di destinazione. Se è già installata una licenza SnapVault, non è necessaria alcuna licenza SnapMirror. La licenza perpetua asincrona SnapMirror è inclusa nella suite software ONTAP One installata sui nuovi sistemi AFF e FAS.

I limiti di configurazione per la protezione dei dati vengono determinati in base a diversi fattori, tra cui la versione di ONTAP, la piattaforma hardware e le licenze installate. Per ulteriori informazioni, vedere https://hwu.netapp.com/["Hardware Universe"^].



== Licenza sincrona SnapMirror

A partire da ONTAP 9.5, sono supportate le relazioni sincrone SnapMirror. Per creare una relazione sincrona SnapMirror sono necessarie le seguenti licenze:

* La licenza sincrona SnapMirror è necessaria sia sul cluster di origine che sul cluster di destinazione.
+
La licenza sincrona SnapMirror fa parte di link:../system-admin/manage-licenses-concept.html["Suite di licenze ONTAP One"].

+
Se il sistema è stato acquistato prima del 2019 giugno con un pacchetto Premium o Flash, è possibile scaricare una chiave master NetApp per ottenere la licenza sincrona SnapMirror richiesta dal sito del supporto NetApp: https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["Chiavi di licenza master"^].

* La licenza SnapMirror è richiesta sia sul cluster di origine che sul cluster di destinazione.




== Licenza cloud SnapMirror

A partire da ONTAP 9.8, la licenza cloud SnapMirror fornisce una replica asincrona delle copie Snapshot dalle istanze ONTAP agli endpoint di storage a oggetti. Le destinazioni di replica possono essere configurate utilizzando archivi di oggetti on-premise e servizi di storage a oggetti cloud pubblico compatibili con S3 e S3. Le relazioni cloud di SnapMirror sono supportate dai sistemi ONTAP fino alle destinazioni prequalificate dello storage a oggetti.

Il cloud SnapMirror non è disponibile come licenza standalone. È necessaria una sola licenza per cluster ONTAP. Oltre a una licenza cloud SnapMirror, è necessaria anche la licenza asincrona SnapMirror.

Per la creazione di una relazione cloud SnapMirror sono necessarie le seguenti licenze:

* Sia una licenza SnapMirror che una licenza cloud SnapMirror per la replica direttamente sull'endpoint dell'archivio di oggetti.
* Quando si configura un workflow di replica multi-policy (ad esempio, da disco a disco a cloud), è necessaria una licenza SnapMirror su tutte le istanze ONTAP, mentre la licenza cloud SnapMirror è necessaria solo per il cluster di origine che replica direttamente sull'endpoint dello storage a oggetti.


A partire da ONTAP 9.9,1, è possibile https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["Utilizza System Manager per la replica cloud SnapMirror"].

Un elenco delle applicazioni di terzi autorizzate per il cloud SnapMirror è pubblicato sul sito Web NetApp.



== Licenza ottimizzata per la protezione dei dati

Le licenze DPO (Data Protection Optimized) non vengono più vendute e il DPO non è supportato sulle piattaforme correnti; tuttavia, se si dispone di una licenza DPO installata su una piattaforma supportata, NetApp continua a fornire supporto fino alla fine della disponibilità di tale piattaforma.

DPO non è incluso nel pacchetto di licenze di ONTAP One e non è possibile eseguire l'aggiornamento al pacchetto di licenze di ONTAP One se la licenza DPO è installata su un sistema.

Per informazioni sulle piattaforme supportate, vedere https://hwu.netapp.com/["Hardware Universe"^].
