---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: A partire da ONTAP 9.3, le licenze sono state semplificate per la replica tra istanze di ONTAP. Nelle versioni di ONTAP 9, la licenza SnapMirror supporta le relazioni di vault e mirror. Gli utenti possono ora acquistare una licenza SnapMirror per supportare la replica ONTAP per i casi di utilizzo di backup e disaster recovery. 
---
= Panoramica sulle licenze di SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.3, le licenze sono state semplificate per la replica tra istanze di ONTAP. Nelle versioni di ONTAP 9, la licenza SnapMirror supporta le relazioni di vault e mirror. Gli utenti possono ora acquistare una licenza SnapMirror per supportare la replica ONTAP per i casi di utilizzo di backup e disaster recovery.

Prima della release di ONTAP 9.3, erano disponibili due licenze per supportare diversi casi di utilizzo della replica. Era necessaria una licenza SnapVault per configurare le relazioni _vault_ tra le istanze di ONTAP, in cui l'istanza DP poteva conservare un numero superiore di copie Snapshot per supportare i casi di utilizzo del backup in cui i tempi di conservazione sono più lunghi. Era necessaria una licenza SnapMirror per configurare le relazioni _mirror_ tra le istanze di ONTAP, in cui ogni istanza di ONTAP avrebbe mantenuto lo stesso numero di copie di snapshot (ovvero un'immagine _mirror_) per supportare i casi di utilizzo del disaster recovery in cui sarebbero possibili i failover del cluster. Le licenze SnapMirror e SnapVault possono continuare a essere utilizzate e supportate per le release ONTAP 8.x e 9.x.

Le licenze SnapVault continuano a funzionare e sono supportate sia per le versioni ONTAP 8.x che 9.x, ma non vengono più vendute. La licenza SnapMirror continua ad essere disponibile e può essere utilizzata al posto di SnapVault e può essere utilizzata per configurazioni di vault e mirror.

Per la replica asincrona di ONTAP, a partire da ONTAP 9.3 viene utilizzato un singolo motore di replica unificato per configurare i criteri XDP (Extended Data Protection Mode), in cui la licenza SnapMirror può essere configurata per un criterio mirror, un criterio di vault o un criterio di vault mirror. È necessaria una licenza SnapMirror sia per i cluster di origine che per quelli di destinazione. Se è già installata una licenza SnapVault, non è necessaria alcuna licenza SnapMirror. La licenza perpetua asincrona di SnapMirror è inclusa nel bundle di protezione dei dati che è possibile acquistare per i cluster ONTAP. Il prezzo del bundle Data Protection si basa sulla capacità raw del cluster.

I limiti di configurazione per la protezione dei dati vengono determinati in base a diversi fattori, tra cui la versione di ONTAP, la piattaforma hardware e le licenze installate. Per ulteriori informazioni, vedere https://hwu.netapp.com/["Hardware Universe"^].



== Licenza SnapMirror Synchronous

A partire da ONTAP 9.5, sono supportate le relazioni sincroni di SnapMirror. Per creare una relazione sincrona con SnapMirror sono necessarie le seguenti licenze:

* La licenza SnapMirror Synchronous è richiesta sia sul cluster di origine che sul cluster di destinazione.
+
La licenza SnapMirror Synchronous è abilitata con il bundle Premium o con il bundle Data Protection.

+
Se il sistema è stato acquistato prima di giugno 2019 con un pacchetto Premium o Flash, è possibile scaricare una chiave master NetApp per ottenere la licenza SnapMirror Synchronous richiesta dal sito di supporto NetApp: https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["Chiavi di licenza master"]

* La licenza SnapMirror è richiesta sia sul cluster di origine che sul cluster di destinazione.




== Licenza SnapMirror Cloud

A partire da ONTAP 9.8, la licenza di SnapMirror Cloud offre la replica asincrona delle copie Snapshot dalle istanze di ONTAP agli endpoint dello storage a oggetti. Le destinazioni di replica possono essere configurate utilizzando archivi di oggetti on-premise e servizi di storage a oggetti cloud pubblico compatibili con S3 e S3. Le relazioni cloud di SnapMirror sono supportate dai sistemi ONTAP alle destinazioni di storage a oggetti pre-qualificate. Gli obiettivi di storage a oggetti approvati da ONTAP 9.8 includono ONTAP S3, StorageGRID, AWS S3 Standard, S3 Standard-IA e S3 One zone-IA, Microsoft Azure Blob Premium, hot and Cool, GCP Standard e Nearline Storage.

SnapMirror Cloud non è disponibile come licenza standalone ed è disponibile solo con l'acquisto di Hybrid Cloud Bundle. Hybrid Cloud Bundle è una licenza di abbonamento a termine che ha un prezzo basato sulla capacità. È necessaria una sola licenza per cluster ONTAP. Per capacità si intende la capacità "utilizzata" (non la capacità raw) all'interno di qualsiasi volume protetto da SnapMirror Cloud. Gli utenti acquisteranno questa licenza in base alla capacità totale utilizzata dei volumi nel cluster di cui viene eseguito il backup con SnapMirror Cloud. A partire da ottobre 2021, il bundle cloud ibrido include solo una licenza SnapMirror Cloud (in precedenza, il bundle cloud ibrido includeva una licenza FabricPool, rimossa dal bundle a partire da ottobre 2021). Oltre a SnapMirror Cloud, è richiesta anche la licenza di SnapMirror asincrona, disponibile solo con l'acquisto del Data Protection Bundle.

Per creare una relazione SnapMirror Cloud sono necessarie le seguenti licenze:

* Sia una licenza SnapMirror (acquistata tramite Data Protection Bundle o Premium Bundle) che una licenza SnapMirror Cloud (acquistata tramite Hybrid Cloud Bundle) sono necessarie per la replica diretta sull'endpoint dell'archivio di oggetti.
* Quando si configura un flusso di lavoro di replica multi-policy (ad esempio, da disco a disco a cloud), è necessaria una licenza SnapMirror su tutte le istanze di ONTAP, mentre la licenza SnapMirror Cloud è richiesta solo per il cluster di origine che esegue la replica direttamente sull'endpoint dello storage a oggetti.


SnapMirror Cloud è una licenza per l'utente finale che può essere acquistata da NetApp o da un partner rivenditore NetApp approvato. La licenza di SnapMirror Cloud fornisce all'utente finale i diritti ma non abilita la replica asincrona dello storage ONTAP su oggetti. Per richiamare le API ONTAP per SnapMirror Cloud, è necessaria una chiave API univoca da un'applicazione autorizzata. Le applicazioni autorizzate e concesse in licenza utilizzate per orchestrare la replica di SnapMirror Cloud includono System Manager e sono disponibili anche presso diversi provider di applicazioni di terze parti. Queste applicazioni autorizzate incorporeranno la chiave API univoca per richiamare le API ONTAP. Per orchestrare e attivare la replica di SnapMirror Cloud è necessaria una combinazione della licenza per l'utente finale di SnapMirror Cloud e di un'applicazione di backup di terze parti autorizzata.

A partire da ONTAP 9.9.1, è possibile utilizzare Gestione di sistema per la replica cloud di SnapMirror. Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["Backup nel cloud"].

Un elenco delle applicazioni di terze parti autorizzate di SnapMirror Cloud è pubblicato sul sito Web di NetApp.



== Data Protection Optimized (DPO)

A partire da ONTAP 9.1, le nuove funzionalità di protezione dei dati di ONTAP sono state integrate con FAS8200 come parte di una soluzione chiamata bundle per la protezione dei dati. Questo nuovo bundle hardware e software includeva una nuova licenza DP_Optimized (DPO) che forniva funzionalità ONTAP esclusive per i carichi di lavoro secondari. Con l'introduzione di ONTAP 9.3, la licenza DPO ha aumentato il numero di volumi per nodo da 1,000 a 1,500. Inoltre, con ONTAP 9.3 sono state introdotte nuove configurazioni del bundle per la protezione dei dati basate sulle configurazioni di FAS2620.

La licenza DPO è stata progettata specificamente per i cluster ONTAP che dovevano essere dedicati come destinazioni secondarie per la replica di SnapMirror. Oltre ad aumentare i volumi massimi per nodo sul controller DPO, la licenza DPO ha modificato anche le impostazioni di QoS del controller per supportare un maggiore traffico di replica a scapito dell'i/o dell'applicazione Per questo motivo, la licenza DPO non deve mai essere installata su un cluster che supporti l'i/o dell'applicazione, in quanto le prestazioni dell'applicazione ne risentirebbero. In seguito, i Data Protection Bundle basati su FAS8200 e FAS2620 sono stati offerti come soluzione e includevano licenze gratuite programmatiche basate sull'ambiente del cliente. Al momento dell'acquisto dei bundle di soluzioni, verranno fornite licenze SnapMirror gratuite per alcuni cluster meno recenti replicati nel DPO secondario. Sebbene la licenza DPO sia necessaria per il cluster di soluzioni Data Protection, ai cluster primari del seguente elenco di piattaforme verranno fornite licenze SnapMirror gratuite. I cluster primari non inclusi in questo elenco richiedono l'acquisto di licenze SnapMirror. Il bundle hardware e software DPO era basato sui sistemi FAS2620 e FAS8200 che sono stati EOA e non sono più disponibili.

* Serie FAS3000
* Serie FAS6000
* Serie FAS8000




== Licenza Data Protection Optimized (DPO)

I bundle di soluzioni hardware e software per la protezione dei dati introdotti con ONTAP 9.1 e 9.3 erano basati solo su FAS8200 e FAS2620. Con la maturazione di queste piattaforme e l'introduzione di nuove piattaforme, sono aumentate le richieste di supporto delle funzionalità ONTAP per i casi di utilizzo della replica secondaria. Di conseguenza, nel novembre 2018 è stata introdotta una nuova licenza DPO standalone con la release ONTAP 9.5.

La licenza DPO standalone era supportata su entrambe le piattaforme FAS e AFF e poteva essere acquistata preconfigurata con nuovi cluster o aggiunta ai cluster implementati come aggiornamento software sul campo. Poiché queste nuove licenze DPO non facevano parte di un bundle di soluzioni hardware e software, avevano un prezzo inferiore e non venivano fornite licenze SnapMirror gratuite per i cluster primari. Anche i cluster secondari configurati con la licenza a la carte DPO devono acquistare una licenza SnapMirror, mentre tutti i cluster primari replicati nel cluster secondario DPO devono acquistare una licenza SnapMirror.

Le funzionalità ONTAP aggiuntive sono state fornite con il DPO in più versioni di ONTAP.

[cols="6*"]
|===


| Funzione | 9.3 | 9.4 | 9.5 | 9.6 | 9.7+ 


| Max vols/nodo  a| 
1500
 a| 
1500
 a| 
1500
 a| 
1500/2500
 a| 
1500/2500



 a| 
Numero massimo di sessioni di repl simultanee
 a| 
100
 a| 
200
 a| 
200
 a| 
200
 a| 
200



 a| 
Bias del carico di lavoro*
 a| 
applicazioni client
 a| 
Applicazioni/SM
 a| 
SnapMirror
 a| 
SnapMirror
 a| 
SnapMirror



 a| 
Deduplica di aggregati di volumi incrociati per HDD
 a| 
No
 a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì

|===
* Dettagli sulla priorità per la funzione di backoff di SnapMirror (bias del carico di lavoro):
* Client: La priorità i/o del cluster viene impostata sui carichi di lavoro del client (applicazioni di produzione), non sul traffico SnapMirror.
* Parità: Le richieste di replica SnapMirror hanno la stessa priorità rispetto all'i/o per le applicazioni di produzione.
* SnapMirror: Tutte le richieste di i/o SnapMirror hanno una priorità maggiore rispetto all'i/o per le applicazioni di produzione.


*Tabella 1: Max FlexVolumes per nodo nelle release di ONTAP*

[cols="7*"]
|===


|  | 9.3--9,5 senza DPO | 9.3--9,5 con DPO | 9.6 senza DPO | 9.6 con DPO | 9.7--9.9.1 senza DPO | 9.7--9..9.1 con DPO 


 a| 
FAS2620
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500



 a| 
FAS2650
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500



 a| 
FAS2720
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500



 a| 
FAS2750
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500



 a| 
R200
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500



 a| 
R220
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
1500



 a| 
FAS8200/8300
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
2500
 a| 
1000
 a| 
2500



 a| 
R300
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
R400
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
FAS8700/9000
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
2500
 a| 
1000
 a| 
2500



 a| 
R700
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
A700s
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
R800
 a| 
1000
 a| 
1500
 a| 
1000
 a| 
2500
 a| 
2500
 a| 
2500

|===
Per informazioni sul supporto più recente del volume FlexVol massimo per la configurazione, vedere https://hwu.netapp.com/["Hardware Universe"^].



== Considerazioni per tutte le nuove installazioni DPO

* Una volta attivata, la funzione di licenza DPO non può essere disattivata o annullata.
* L'installazione della licenza DPO richiede il riavvio di ONTAP o il failover per l'attivazione.
* La soluzione DPO è destinata ai carichi di lavoro dello storage secondario; le performance dei carichi di lavoro delle applicazioni sui cluster DPO potrebbero risentire
* La licenza DPO è supportata da un elenco selezionato di modelli di piattaforme di storage NetApp.
* Le funzionalità DPO variano in base alla release di ONTAP. Fare riferimento alla tabella di compatibilità.
* I nuovi sistemi FAS e AFF non sono qualificati con DPO. Le licenze DPO non possono essere acquistate per i cluster non elencati in precedenza.

