---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features 
summary: Scopri le nuove funzionalità disponibili in ONTAP 9. 
---
= Highlight sulla release ONTAP 9
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni versione del software per la gestione dei dati ONTAP 9 offre funzioni nuove e migliorate che migliorano le funzionalità, la gestibilità, le prestazioni e la sicurezza di ONTAP.

In questa pagina sono riportate le nuove funzioni evidenziate per le recenti release di ONTAP 9 oppure è possibile utilizzare la barra laterale per passare a una versione specifica di ONTAP 9 e scoprire tutti i miglioramenti delle recenti release di ONTAP.

Per informazioni dettagliate sulle versioni precedenti di ONTAP 9, sul supporto per piattaforme hardware e switch, sui problemi noti e sulle limitazioni, fare riferimento a _link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"^]_. Per accedere alle _Note sulla versione di ONTAP 9_, è necessario accedere con il proprio account NetApp o creare un account NetApp.

Per eseguire l'aggiornamento all'ultima versione di ONTAP, vedere xref:../upgrade/prepare.html[Effettuare l'aggiornamento alla versione più recente di ONTAP] e. xref:../upgrade/when-to-upgrade.html[Quando è necessario aggiornare ONTAP?]



== Highlight di ONTAP 9.14.1

ONTAP 9.14.1 offre funzionalità nuove e migliorate nelle aree offrendo FabricPool, protezione anti-ransomware, OAuth e altro ancora. Per un elenco completo delle nuove funzioni e dei miglioramenti, vedere xref:9141-reference.adoc[Novità di ONTAP 9.14.1].

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[Riduzione prenotazione WAFL]
+
ONTAP 9.14.1 introduce un aumento immediato del 5% dello spazio utilizzabile sui sistemi FAS e Cloud Volumes ONTAP, riducendo la riserva WAFL sugli aggregati con 30 TB o più.

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[Miglioramenti apportati a FabricPool]
+
FabricPool offre un aumento di xref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[performance di lettura] e permette la scrittura diretta nel cloud, riducendo il rischio di esaurire lo spazio e i costi storage grazie allo spostamento dei dati cold in un tier storage meno costoso.

* link:../authentication/oauth2-deploy-ontap.html["Supporto per OAuth 2,0"]
+
ONTAP supporta il framework OAuth 2,0, che può essere configurato tramite Gestione sistema. Con OAuth 2,0, è possibile fornire un accesso sicuro a ONTAP per framework di automazione senza creare o esporre ID utente e password a script di testo normale e runbook.

* link:../anti-ransomware/manage-parameters-task.html["Miglioramenti alla protezione autonoma dal ransomware (ARP)"]
+
ARP garantisce un maggiore controllo sulla protezione degli eventi, consentendo di regolare le condizioni che creano avvisi e riducendo la possibilità di falsi positivi.

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[Prova del disaster recovery di SnapMirror in System Manager]
+
System Manager offre un semplice flusso di lavoro per testare facilmente il disaster recovery in una posizione remota e per ripulirlo dopo il test. Questa funzione consente test più semplici e frequenti e una maggiore fiducia nei recovery time objective.

* xref::../s3-config/index.html[Supporto blocco oggetti S3]
+
ONTAP S3 supporta il comando object-lock API, consentendo di proteggere dalla cancellazione i dati scritti in ONTAP con S3
Utilizzo di comandi API S3 standard e per garantire che i dati importanti siano protetti per il tempo appropriato.

* xref:../assign-tags-cluster-task.html[Cluster] e. xref:../assign-tags-volumes-task.html[volume] etichettatura
+
Aggiungi tag di metadati a volumi e cluster per seguire le informazioni anche quando vengono spostati da on-premise a cloud e viceversa.





== Highlight di ONTAP 9.13.1

ONTAP 9.13.1 offre funzionalità nuove e migliorate nel campo della protezione anti-ransomware, dei gruppi di coerenza, della qualità del servizio, della gestione della capacità dei tenant e molto altro ancora. Per un elenco completo delle nuove funzioni e dei miglioramenti, vedere xref:9131-reference.adoc[Novità di ONTAP 9.13.1].

* Miglioramenti alla protezione autonoma dal ransomware (ARP):
+
** xref:../anti-ransomware/enable-default-task.adoc[Abilitazione automatica]
+
Con ONTAP 9.13.1, ARP passa automaticamente dalla modalità di formazione alla modalità di produzione dopo aver ricevuto dati di apprendimento sufficienti, eliminando la necessità per un amministratore di abilitarla dopo il periodo di 30 giorni.

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[Supporto per la verifica multi-admin]
+
I comandi di disattivazione ARP sono supportati dalla verifica multi-admin, garantendo che nessun amministratore singolo possa disattivare ARP per esporre i dati a potenziali attacchi ransomware.

** xref:../anti-ransomware/use-cases-restrictions-concept.html[Supporto FlexGroup]
+
ARP supporta i gruppi flessibili che iniziano con ONTAP 9.13.1. ARP può monitorare e proteggere FlexGroup che coprono più volumi e nodi nel cluster, consentendo anche di proteggere con ARP anche i set di dati più grandi.



* xref:../consistency-groups/index.html[Monitoring delle performance e della capacità per i gruppi di coerenza in System Manager]
+
Il monitoraggio della capacità e delle performance fornisce dettagli per ogni gruppo di coerenza, consentendoti di identificare e segnalare rapidamente potenziali problemi a livello di applicazione piuttosto che a livello di oggetto dati.

* xref:../volumes/manage-svm-capacity.html[Gestione della capacità del tenant]
+
I clienti multi-tenant e i service provider possono impostare un limite di capacità su ciascuna SVM, consentendo ai tenant di eseguire il provisioning self-service senza il rischio di un consumo eccessivo di capacità nel cluster da parte di un tenant.

* xref:../performance-admin/adaptive-policy-template-task.html[Qualità del servizio soffitti e pavimenti]
+
ONTAP 9.13.1 consente di raggruppare oggetti come volumi, LUN o file in gruppi e di assegnare un livello massimo di qualità del servizio (IOPS massimi) o minimo (IOPS minimi), migliorando le aspettative di performance delle applicazioni.





== Highlight di ONTAP 9.12.1

ONTAP 9.12.1 offre funzioni nuove e migliorate per quanto riguarda protezione avanzata, conservazione, prestazioni e altro ancora. Per un elenco completo delle nuove funzioni e dei miglioramenti, vedere xref:9121.adoc[Novità di ONTAP 9.12.1].

* xref:../snaplock/snapshot-lock-concept.html[Snapshot a prova di manomissione]
+
Con la tecnologia SnapLock, le copie Snapshot possono essere protette dalla cancellazione sull'origine o sulla destinazione.

+
Mantenere più punti di recovery proteggendo le snapshot sullo storage primario e secondario dalle eliminazioni da parte di hacker o amministratori fuori controllo.

* xref:../anti-ransomware/index.html[Miglioramenti alla protezione autonoma dal ransomware (ARP)]
+
Abilita immediatamente la protezione autonoma intelligente dal ransomware sullo storage secondario, in base al modello di screening già completato per lo storage primario.

+
Dopo un failover, identifica istantaneamente i potenziali attacchi ransomware sullo storage secondario. Una Snapshot viene acquisita immediatamente dei dati che iniziano a essere interessati e gli amministratori vengono avvertiti, aiutando a fermare un attacco e a migliorare il recovery.

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy]
+
Attivazione con un clic di ONTAP FPolicy per abilitare il blocco automatico dei file dannosi conosciuti l'attivazione semplificata aiuta a proteggersi dai tipici attacchi ransomware che utilizzano estensioni di file comuni e note.

* xref:../system-admin/ontap-implements-audit-logging-concept.html[Protezione avanzata: Registrazione della conservazione a prova di manomissione]
+
L'accesso alla conservazione a prova di manomissione in ONTAP che garantisce la compromissione degli account amministratore non può nascondere azioni dannose. La cronologia degli amministratori e degli utenti non può essere alterata o eliminata senza che il sistema ne sia a conoscenza.

+
Registrare e controllare tutte le azioni amministrative indipendentemente dall'origine, garantendo l'acquisizione di tutte le azioni che hanno un impatto sui dati. Un avviso viene generato ogni volta che i registri di controllo del sistema vengono manomessi in qualsiasi modo per informare gli amministratori della modifica.

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[Protezione avanzata: Autenticazione a più fattori estesa]
+
L'autenticazione a più fattori (MFA) per CLI (SSH) supporta dispositivi token hardware fisici Yubikey, garantendo che un utente malintenzionato non possa accedere al sistema ONTAP utilizzando credenziali rubate o un sistema client compromesso. Cisco DUO è supportato per MFA con System Manager.

* Dualismo degli oggetti file (accesso multiprotocollo)
+
Il dualismo degli oggetti file abilita l'accesso in lettura e scrittura nativo al protocollo S3 nella stessa origine dati che già dispone di accesso al protocollo NAS. Puoi accedere contemporaneamente allo storage come file o come oggetti dalla stessa origine dei dati, eliminando la necessità di disporre di copie duplicate dei dati da utilizzare con protocolli diversi (S3 o NAS), come per le analytics che utilizzano i dati degli oggetti.

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[Ribilanciamento FlexGroup]
+
Se i componenti di FlexGroup non sono bilanciati, è possibile ribilanciare e gestire FlexGroup senza interruzioni da
CLI, API REST e System Manager. Per ottenere prestazioni ottimali, i membri costituenti di un FlexGroup devono avere la capacità utilizzata distribuita in modo uniforme.

* Miglioramenti della capacità di storage
+
La prenotazione dello spazio WAFL è stata notevolmente ridotta, fornendo fino a 400 TiB di capacità utilizzabile per aggregato.





== Highlight di ONTAP 9.11.1

ONTAP 9.11.1 offre funzioni nuove e migliorate nel campo della sicurezza, della conservazione, delle prestazioni e altro ancora. Per un elenco completo delle nuove funzioni e dei miglioramenti, vedere xref:9111-reference.adoc[Novità di ONTAP 9.11.1].

* xref:../multi-admin-verify/index.html[Verifica multi-admin]
+
La verifica con amministratori multipli (MAV) è un approccio nativo alla verifica, che richiede approvazioni multiple per attività amministrative sensibili come l'eliminazione di una snapshot o di un volume. Le approvazioni richieste in un'implementazione MAV impediscono attacchi dannosi e modifiche accidentali ai dati.

* xref:../anti-ransomware/index.html[Miglioramenti alla protezione autonoma da ransomware]
+
La protezione autonoma dal ransomware (ARP) utilizza l'apprendimento automatico per rilevare le minacce ransomware con una maggiore granularità, consentendoti di identificare rapidamente le minacce e accelerare il recovery in caso di violazione.

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[Conformità SnapLock per FlexGroup Volumes]
+
Set di dati multi-petabyte sicuri per workload come electronic design automation e media & entertainment proteggendo i dati con blocco di file WORM in modo da non essere modificati o eliminati.

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[Eliminazione asincrona delle directory]
+
Con ONTAP 9.11.1, l'eliminazione dei file avviene in background nel sistema ONTAP, consentendo di eliminare facilmente directory di grandi dimensioni eliminando al contempo gli impatti di performance e latenza sull'i/o dell'host

* xref:../s3-config/index.html[Miglioramenti di S3]
+
Semplificare ed espandere le funzionalità di gestione dei dati a oggetti di S3 con ONTAP con endpoint API aggiuntivi e versione oggetto a livello di bucket, consentendo di memorizzare versioni multiple di un oggetto nello stesso bucket.

* Miglioramenti di System Manager
+
System Manager supporta funzionalità avanzate per ottimizzare le risorse storage e migliorare la gestione degli audit. Questi update includono funzionalità migliorate per gestire e configurare gli aggregati di storage, maggiore visibilità delle analisi del sistema e visualizzazione hardware per i sistemi FAS.





== Highlight di ONTAP 9.10.1

ONTAP 9.10.1 offre funzionalità nuove e migliorate nel campo del rafforzamento della sicurezza, dell'analisi delle performance, del supporto del protocollo NVMe e delle opzioni di backup dello storage a oggetti. Per un elenco completo delle nuove funzioni e dei miglioramenti, vedere xref:91-1-reference.adoc[Novità di ONTAP 9.10.1].

* xref:../anti-ransomware/index.html[Protezione ransomware autonoma]
+
La protezione autonoma contro il ransomware crea automaticamente una copia Snapshot del tuo volume e avvisa gli amministratori quando vengono rilevate attività anomale, permettendoti di rilevare rapidamente attacchi ransomware e ripristinare più rapidamente.

* Miglioramenti di System Manager
+
System Manager scarica automaticamente gli aggiornamenti del firmware per dischi, shelf, service processor e offre nuove integrazioni con NetApp Active IQ Digital Advisor, BlueXP e la gestione del certificato. Questi miglioramenti semplificano l'amministrazione e mantengono la business continuity.

* xref:../concept_nas_file_system_analytics_overview.html[Miglioramenti alle file-System Analytics]
+
File System Analytics offre ulteriore telemetria per identificare i principali file, directory e utenti nella vostra condivisione di file, permettendoti di identificare i problemi di performance del carico di lavoro per migliorare la pianificazione delle risorse e l'implementazione della QoS.

* xref:../nvme/support-limitations.html[Supporto NVMe over TCP (NVMe/TCP) per sistemi AFF]
+
Ottieni performance elevate e riduci il TCO per la tua SAN aziendale e i carichi di lavoro moderni sul sistema AFF utilizzando NVMe/TCP sulla rete Ethernet esistente.

* xref:../nvme/support-limitations.html[Supporto NVMe over Fibre Channel (NVMe/FC) per i sistemi NetApp FAS]
+
Utilizza il protocollo NVMe/FC sui tuoi array ibridi per consentire una migrazione uniforme su NVMe.

* xref:../s3-snapmirror/index.html[Backup cloud ibrido nativo per lo storage a oggetti]
+
Proteggi i tuoi dati di ONTAP S3 in relazione alla tua scelta di destinazioni di storage a oggetti. Utilizza la replica SnapMirror per eseguire il backup su storage on-premise con StorageGRID, nel cloud con Amazon S3 o in un altro bucket ONTAP S3 su sistemi NetApp AFF e FAS.

* xref:../flexcache/global-file-locking-task.html[Blocco globale dei file con FlexCache]
+
Garantire la coerenza dei file nelle posizioni della cache durante gli aggiornamenti dei file di origine con il blocco globale dei file utilizzando FlexCache. Questo miglioramento abilita blocchi esclusivi di lettura file in una relazione da origine a cache per i carichi di lavoro che richiedono un blocco avanzato.





== Highlight di ONTAP 9.9.1

ONTAP 9.91.1 offre funzionalità nuove e migliorate nel campo dell'efficienza dello storage, dell'autenticazione multifattore, del disaster recovery e molto altro ancora. Per un elenco completo delle nuove funzioni e dei miglioramenti, vedere xref:991-reference.adoc[Novità di ONTAP 9.9.1].

* Maggiore sicurezza per la gestione dell'accesso remoto CLI
+
Il supporto per l'hashing di password SHA512 e SSH A512 protegge le credenziali dell'account amministratore da malintenzionati che stanno tentando di ottenere l'accesso al sistema.

* link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Miglioramenti di MetroCluster IP: Supporto per cluster a 8 nodi"^]
+
Il nuovo limite è il doppio rispetto al precedente, offrendo supporto per le configurazioni MetroCluster e abilitando la disponibilità continua dei dati.

* xref:../smbc/index.html[Miglioramenti alla continuità del business di SnapMirror]
+
Offre più opzioni di replica per backup e disaster recovery per container di dati di grandi dimensioni per workload NAS.

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[Migliori performance SAN]
+
Offre performance SAN fino a quattro volte superiori per le singole applicazioni LUN come i datastore VMware, in modo da poter raggiungere performance elevate nell'ambiente SAN.

* xref:../task_cloud_backup_data_using_cbs.html[Nuova opzione di storage a oggetti per il cloud ibrido]
+
Consente l'utilizzo di StorageGRID come destinazione per NetApp Cloud Backup Service per semplificare e automatizzare il backup dei dati ONTAP on-premise.



.Passi successivi
* xref:../upgrade/prepare.html[Effettuare l'aggiornamento alla versione più recente di ONTAP]
* xref:../upgrade/when-to-upgrade.html[Quando è necessario aggiornare ONTAP?]

