---
permalink: release-notes/whats-new-9171.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.17.1' 
summary: Scopri le nuove funzionalità disponibili in ONTAP 9.17.1. 
---
= Novità di ONTAP 9.17.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità disponibili in ONTAP 9.17.1.

Per informazioni dettagliate su problemi noti, limitazioni e avvisi di aggiornamento nelle recenti versioni di ONTAP 9, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"^]. Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.

* Scopri le nuove funzionalità e le funzionalità avanzate https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Caratteristiche di ONTAP MetroCluster"^].
* Scopri di più  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["nuove e migliorate funzionalità del software ONTAP per i sistemi NetApp ASA r2"^] .
* Scopri di più  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["nuovo e migliorato supporto per i sistemi AFF, ASA e FAS e gli switch supportati"^] .
* Ulteriori informazioni sugli aggiornamenti di https://docs.netapp.com/us-en/ontap-automation/whats_new.html["API REST di ONTAP"^].


Per eseguire l'aggiornamento alla versione più recente di ONTAP, vedere link:../upgrade/create-upgrade-plan.html["Prepararsi all'aggiornamento di ONTAP"].



== Protezione dei dati

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../nvme/support-limitations.html#features[Supporto di sincronizzazione attiva SnapMirror per l'accesso host tramite NVMe]
 a| 
SnapMirror ActiveSync aggiunge il supporto per l'accesso NVMe per carichi di lavoro VMware con accesso host NVMe/TCP e NVMe/FC per cluster ONTAP a due nodi. Il supporto per NVMe/TCP nei carichi di lavoro VMware è subordinato alla risoluzione dei bug di VMware.



 a| 
xref:../snapmirror-active-sync/index.html[Supporto ONTAP Cloud Mediator con sincronizzazione attiva SnapMirror]
 a| 
ONTAP Cloud Mediator è stato introdotto in ONTAP 9.17.1 e supporta le relazioni di sincronizzazione attiva SnapMirror . Il mediatore basato su cloud, come ONTAP Mediator, funge da quorum witness per le relazioni di sincronizzazione attiva SnapMirror , garantendo un failover trasparente e riducendo al contempo la complessità operativa di manutenzione e gestione di un terzo sito.

|===


== Storage a oggetti S3

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../s3-multiprotocol/index.html[Supporto dell'azione CopyObject nei bucket NAS ONTAP S3]
 a| 
L'azione CopyObject è supportata nel bucket ONTAP S3 NAS.



 a| 
xref:../s3-multiprotocol/create-nas-bucket-task.html[Supporto per il collegamento di un bucket NAS S3 a un percorso di giunzione]
 a| 
Quando si crea un bucket NAS S3 con l'interfaccia a riga di comando ONTAP , è possibile scegliere di collegare il bucket al volume anziché al percorso di giunzione. Quando ci si collega al volume, il percorso di giunzione viene aggiornato automaticamente se il percorso cambia, ad esempio quando un volume viene smontato o montato.



 a| 
xref:../s3-multiprotocol/index.html#object-multipart-upload[Supporto multiprotocollo S3 per tagging e metadati]
 a| 
Il tagging e le coppie chiave/valore dei metadati utente sono supportati dall'azione CreateMultipartUpload negli ambienti multiprotocollo (S3 e NAS).

|===


== Sicurezza

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../system-admin/use-hsts-task.html[Supporto HTTP Strict Transport Security (HSTS)]
 a| 
ONTAP supporta HTTP Strict Transport Security per i servizi Web, consentendo l'applicazione di comunicazioni HTTPS sicure tra il browser di un utente e ONTAP.



 a| 
xref:../networking/ipsec-prepare.html[Offload hardware IPsec con gruppi di aggregazione di link]
 a| 
ONTAP supporta l'offload hardware IPsec per i gruppi di aggregazione di link, estendendo il supporto all'offload hardware introdotto nella versione 9.16.1.



 a| 
xref:../networking/ipsec-prepare.html[Supporto per chiave pre-condivisa postquantistica IPsec]
 a| 
ONTAP supporta chiavi pre-condivise postquantistiche per IPsec per proteggere da potenziali futuri attacchi ai computer quantistici.



 a| 
xref:../encryption-at-rest/manage-keys-barbican-task.html[Supporto del gestore delle chiavi OpenStack Barbican]
 a| 
ONTAP supporta il gestore delle chiavi Barbican di OpenStack per le chiavi NetApp Volume Encryption (NVE).



 a| 
xref:../authentication/configure-jit-elevation-task.html[Supporto per l'elevazione dei privilegi just in time (JIT)]
 a| 
ONTAP supporta l'elevazione dei privilegi JIT per il controllo degli accessi basato sui ruoli (RBAC). Gli utenti possono richiedere l'elevazione temporanea a un ruolo configurato, consentendo l'accesso ai comandi privilegiati su richiesta. Gli amministratori del cluster possono configurare chi può accedere all'elevazione dei privilegi JIT e quando e per quanto tempo è consentito l'accesso.



 a| 
xref:../system-admin/configure-saml-authentication-task.html[Supporto per Entra IdP e supporto del gruppo IdP per l'autenticazione SAML]
 a| 
ONTAP supporta Microsoft Entra come provider di identità SAML. Inoltre, le informazioni di gruppo fornite dall'IdP possono essere mappate ai ruoli ONTAP .



 a| 
xref:../system-admin/audit-manage-cross-cluster-requests.html[Audit delle richieste tra cluster]
 a| 
È possibile configurare ed eseguire operazioni di audit sia sul cluster di origine che su quello di destinazione (in esecuzione). Nelle versioni precedenti, solo il cluster che riceveva la richiesta del client eseguiva l'audit. Con questa funzionalità, un cluster peer che soddisfa una richiesta cross-cluster registra anche l'attività. Queste operazioni di audit possono essere abilitate ed estese a qualsiasi richiesta SET o GET avviata all'interno di ONTAP.



 a| 
xref:../anti-ransomware/index.html[Supporto per SAN con protezione autonoma da ransomware]
 a| 
ARP supporta volumi SAN con rilevamento delle anomalie basato sulla crittografia, introduce nuovi comandi per statistiche dettagliate sull'entropia e unifica la messaggistica di protezione ransomware in System Manager, precedentemente focalizzata sul NAS. Soglie di rilevamento configurabili e una conservazione degli snapshot più deterministica offrono maggiore flessibilità per carichi di lavoro diversificati.

|===


== Miglioramenti alla gestione delle risorse dello storage

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../task_nas_file_system_analytics_enable.html[FSA abilitato per impostazione predefinita per i nuovi volumi]
 a| 
I volumi creati su SVM di nuova creazione su cluster ONTAP allocati per protocolli NAS hanno la funzionalità File System Analytics (FSA) abilitata per impostazione predefinita. La funzionalità FSA viene attivata automaticamente non appena viene creato un volume, offrendo funzionalità di analisi immediate senza ulteriori configurazioni.



 a| 
xref:../flexgroup/fast-directory-delete-asynchronous-task.html[Supporto migliorato per la visualizzazione dell'avanzamento dell'eliminazione diretta sui volumi FlexGroup]
 a| 
Il comando CLI ONTAP  `volume file async-delete show` è stato migliorato per includere i processi di eliminazione asincroni emessi dai client.

|===