---
permalink: release-notes/whats-new-9191.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.19.1' 
summary: Scopri le nuove funzionalità disponibili in ONTAP 9.19.1. 
---
= Novità di ONTAP 9.19.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità disponibili in ONTAP 9.19.1.

Per informazioni dettagliate su problemi noti, limitazioni e avvisi di aggiornamento nelle recenti versioni di ONTAP 9, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"^]. Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.

* Scopri le nuove funzionalità e le funzionalità avanzate https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Caratteristiche di ONTAP MetroCluster"^].
* Scopri di più  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["nuove e migliorate funzionalità del software ONTAP per i sistemi di storage NetApp AFX"^] .
* Scopri di più  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["nuove e migliorate funzionalità del software ONTAP per i sistemi di storage NetApp ASA r2"^] .
* Scopri di più  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["nuovo e migliorato supporto per i sistemi AFF, ASA e FAS e gli switch supportati"^] .
* Ulteriori informazioni sugli aggiornamenti di https://docs.netapp.com/us-en/ontap-automation/whats_new.html["API REST di ONTAP"^].


Per eseguire l'aggiornamento alla versione più recente di ONTAP, vedere link:../upgrade/create-upgrade-plan.html["Prepararsi all'aggiornamento di ONTAP"].



== Protezione dei dati

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../snapmirror-active-sync/interoperability-reference.html[SnapMirror active sync supporta il failover trasparente delle applicazioni per AIX]
 a| 
SnapMirror active sync per configurazioni simmetriche active/active supporta il failover trasparente con RPO zero per AIX su cluster a 2 nodi.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html#restore-from-the-cloud[I limiti di supporto cloud di SnapMirror sono aumentati a 100 bucket S3]
 a| 
SnapMirror cloud aumenta il numero di bucket S3 supportati a 100.



 a| 
xref:../snaplock/snapshot-lock-concept.html[SnapMirror synchronous supporta il blocco delle snapshot antimanomissione]
 a| 
È possibile utilizzare il blocco snapshot antimanomissione con SnapMirror synchronous.



 a| 
xref:../data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html[SnapMirror synchronous supporta la replica degli snapshot pianificati sul volume di destinazione]
 a| 
È possibile replicare gli snapshot pianificati sul volume di destinazione con SnapMirror synchronous.

|===


== Networking

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
Gestisci le versioni NFS supportate dalla SVM
 a| 
Il supporto per NFSv4.2 viene gestito indipendentemente dalle impostazioni di NFSv4.1, consentendo a ciascun SVM di pubblicizzare o disabilitare le funzionalità NFSv4.2 a seconda delle necessità. Per impostazione predefinita, NFSv4.2 è abilitato quando viene creato un nuovo servizio NFS, a meno che non venga esplicitamente disabilitato dall'amministratore.

* https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv42-task.html["Abilitare o disabilitare NFSv4.2 per SVM ONTAP"]
* https://docs.netapp.com/us-en/ontap/task_nas_enable_linux_nfs.html["Abilitare l'archiviazione NAS per server Linux utilizzando NFS con ONTAP System Manager"]




 a| 
xref:../concepts/path-failover-concept.html#nas-path-failover[Miglioramento del failover LIF]
 a| 
La policy di gruppo di failover definita dal sistema ONTAP espande dinamicamente le destinazioni di failover per i LIF dati NAS, includendo potenzialmente tutte le porte disponibili nel dominio broadcast su qualsiasi nodo disponibile nel cluster. È possibile applicare la policy definita dal sistema a qualsiasi gruppo di failover. Prima di ONTAP 9.19.1, i LIF con questa policy potevano eseguire il failover solo su un altro nodo del cluster; se tale nodo non era in quorum, il LIF non eseguiva il failover, anche se erano disponibili altri nodi.

|===


== SAN

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../san-config/configure-fc-nvme-hosts-ha-pairs-reference.html[Supporto per configurazioni FC ad aggancio diretto]
 a| 
Gli switch FC non sono necessari per connettere host FC e FC-NVMe allo storage ONTAP. Gli host possono connettersi direttamente alle porte degli adattatori FC sui sistemi AFF, ASA e FAS. Questa connessione diretta è particolarmente utile nei siti remoti e negli ambienti ibridi dove la semplicità è importante.



 a| 
xref:../san-admin/multipath-automatic-lif-failover-support.html[Supporto per il multipathing attivo-attivo sui sistemi AFF]
 a| 
I sistemi AFF supportano il multipathing attivo-attivo negli ambienti SAN. Nelle configurazioni attivo-attivo, tutti i percorsi all'interno della coppia HA che possiede la LUN o il namespace sono ottimizzati in modalità attiva, in modo che in caso di failover dello storage, l'host non debba attendere la transizione ALUA o ANA dei percorsi di failover per riprendere l'I/O. Ciò riduce i tempi di failover, consentendo ai clienti SAN di eseguire carichi di lavoro mission-critical sui sistemi AFF con la stessa resilienza dei percorsi non interruttiva e bilanciamento del carico precedentemente disponibili solo sui sistemi ASA.



 a| 
xref:../san-admin/multipath-automatic-lif-failover-support.html[Supporto migliorato per il failover automatico di SAN LIF]
 a| 
Il failover automatico LIF è supportato sui sistemi AFF e ASA per i LIF del protocollo iSCSI in configurazioni multipath attivo-attivo e attivo-attivo-solo iSCSI, e per i LIF del protocollo NVMe/TCP in configurazioni multipath attivo-attivo.



 a| 
link:https://docs.netapp.com/us-en/ontap-fli/get-started/learn-about-data-migration.html["Supporto per l'importazione di LUN esterne per il protocollo iSCSI"^]
 a| 
Foreign LUN Import (FLI) supporta il protocollo iSCSI per la connettività backend.

|===


== Storage a oggetti S3

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../s3-config/create-modify-bucket-policy-task.html[Supporto ONTAP S3 per scritture ed eliminazioni condizionali con applicazione delle regole]
 a| 
È possibile utilizzare le condizioni per imporre scritture condizionali per il caricamento di oggetti ed eliminazioni condizionali per l'eliminazione di oggetti. Le scritture e le eliminazioni condizionali consentono di prevenire sovrascritture o eliminazioni involontarie di oggetti.



 a| 
xref:../s3-config/regenerate-access-keys.html[Chiavi ONTAP S3]
 a| 
Per mantenere l'accesso degli utenti alle risorse S3 se la chiave di accesso originale scade, gli amministratori del cluster ONTAP possono generare una seconda chiave di accesso per ciascun utente S3.

|===


== Sicurezza

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
Le caratteristiche del carico di lavoro ARP sono state rimosse dall'interfaccia utente di System Manager
 a| 
System Manager non visualizza più le caratteristiche del carico di lavoro di Autonomous Ransomware Protection (ARP), incluse le statistiche di baseline e di picco. Queste informazioni sono state rimosse poiché l'attività di picco veniva spesso interpretata erroneamente come un vero e proprio attacco ransomware o come qualcosa che richiedeva un intervento manuale.

Il comportamento e il rilevamento ARP rimangono invariati, e solo la presentazione di questi dettagli in System Manager è interessata. Le statistiche rimangono disponibili utilizzando le opzioni ONTAP CLI e REST API per analisi avanzate.



 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[Supporto per la protezione autonoma contro i ransomware per SnapMirror synchronous e SnapMirror active sync]
 a| 
ARP/AI supporta i volumi che partecipano a relazioni SnapMirror sincrone (NAS e SAN) e a relazioni SnapMirror active sync SAN su piattaforme supportate. ARP/AI può proteggere i volumi primari in relazioni SnapMirror sincrone su sistemi FAS, AFF e AFX, e i volumi primari in relazioni SnapMirror active sync SAN su sistemi AFF e ASA r2. ARP/AI viene eseguito sul volume primario attivo in lettura e scrittura nella relazione, creando snapshot ARP solo del volume primario e fornendo il rilevamento del ransomware basato sull'apprendimento automatico.



 a| 
xref:../networking/configure-tls-offload.html[Configurazione di offload TLS]
 a| 
È possibile configurare l'offload TLS per migliorare le prestazioni post-handshake TLS sfruttando le risorse sulle schede Ethernet supportate. Questa funzionalità esegue l'offload della crittografia e decrittografia, riducendo il sovraccarico della CPU e migliorando le performance.

|===


== Efficienza dello storage

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../flexcache/index.html[miglioramento delle performance NAS]
 a| 
ONTAP 9.19.1 consente di allocare maggiori risorse CPU per elaborare le richieste di elenco di directory NAS di piccole dimensioni. Questo miglioramento è vantaggioso per i clienti con centinaia o migliaia di client che elencano simultaneamente la stessa directory NAS di piccole dimensioni, pari o inferiore a 2 MB (circa 25.000 file).

Questo miglioramento riduce la necessità di ricorrere a soluzioni alternative, come volumi FlexCache locali, per supportare un elevato numero di client che eseguono elenchi di directory. Per un numero inferiore di client, le performance non saranno influenzate negativamente. Questo miglioramento delle performance è automatico e non richiede configurazione.

|===


== Miglioramenti alla gestione delle risorse dello storage

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../performance-admin/guarantee-throughput-qos-task.html[Supporto per la modifica delle impostazioni predefinite che controllano gli aumenti automatici del limite massimo di throughput QoS]
 a| 
È possibile modificare le impostazioni predefinite che controllano il modo in cui i gruppi di criteri QoS aumentano automaticamente il limite massimo di throughput QoS in risposta a esigenze a breve termine di prestazioni superiori. Queste impostazioni non possono essere modificate in ONTAP 9.18.1 e versioni precedenti.

|===


== System Manager

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../concept-svm-admin-dashboard-sm.html[Monitora e gestisci l'SVM utilizzando la nuova dashboard di ONTAP System Manager]
 a| 
Una nuova dashboard dedicata consente agli amministratori SVM di monitorare e gestire le proprie SVM. Ciò risulta particolarmente utile in un ambiente ONTAP multi-tenant, dove l'amministratore del cluster può fornire una dashboard SVM per ciascun tenant.

|===


== Eseguire l'upgrade

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../upgrade/automated-pre-checks.html[Reportistica migliorata per i controlli preliminari di aggiornamento automatizzati]
 a| 
Durante l'esecuzione dei controlli automatici pre-aggiornamento, gli errori e gli avvisi vengono visualizzati separatamente per consentire di identificare facilmente i problemi che devono essere risolti prima di procedere con l'aggiornamento.

|===