---
permalink: release-notes/whats-new-9161.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.16.1' 
summary: Scopri le nuove funzionalità disponibili in ONTAP 9.16.1. 
---
= Novità di ONTAP 9.16.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità disponibili in ONTAP 9.16.1.

Per informazioni dettagliate su problemi noti, limitazioni e avvisi di aggiornamento nelle recenti versioni di ONTAP 9, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"^]. Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.

Scopri le nuove funzionalità e le funzionalità avanzate https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Caratteristiche di ONTAP MetroCluster"^].

Ulteriori informazioni sul supporto nuovo e migliorato per https://docs.netapp.com/us-en/ontap-systems/whats-new.html["Piattaforme FAS, ASA e AFF e switch supportati"^].

Ulteriori informazioni sugli aggiornamenti di https://docs.netapp.com/us-en/ontap-automation/whats_new.html["API REST di ONTAP"^].

Per eseguire l'aggiornamento alla versione più recente di ONTAP, vedere link:../upgrade/create-upgrade-plan.html["Prepararsi all'aggiornamento di ONTAP"].



== Protezione dei dati

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../snapmirror-active-sync/index.html[Supporto a più nodi per la sincronizzazione attiva di SnapMirror]
 a| 
Espandendosi dal precedente limite di due nodi, la SnapMirror Active Sync supporta cluster a quattro nodi, consentendo la replica dei dati per carichi di lavoro più grandi.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[Supporto cloud di SnapMirror per la creazione di relazioni fan-out]
 a| 
Il cloud SnapMirror supporta relazioni fan-out dallo stesso volume di origine o FlexGroup in due diversi archivi di oggetti. Le fan-out possono essere due archivi di oggetti e uno o due bucket negli archivi di oggetti.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[Supporto per i backup cloud SnapMirror da un volume migrato]
 a| 
Il cloud SnapMirror supporta backup di volumi migrati nel cloud utilizzando le API REST ONTAP esistenti. La nuova funzionalità supporta i backup nel cloud SnapMirror da un volume migrato nel cloud allo stesso endpoint dell'archivio di oggetti di destinazione senza dover eseguire un'operazione di re-baseline. Sono supportati sia i volumi FlexVol che FlexGroup.

|===


== Networking

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../networking/configure_virtual_ip_vip_lifs.html#set-up-border-gateway-protocol-bgp[Supporto di autenticazione MD5 per i gruppi di peer BGP]
 a| 
ONTAP supporta l'autenticazione MD5 sui gruppi di peer BGP per proteggere le sessioni BGP. Quando MD5 è attivato, le sessioni BGP possono essere stabilite ed elaborate solo tra i peer autorizzati, impedendo attacchi come il dirottamento dei percorsi in cui un utente malintenzionato tenta di inserire false informazioni di routing nella rete mediante lo spoofing degli aggiornamenti BGP.



 a| 
xref:../networking/ipsec-prepare.html[Supporto per offload hardware IPSec]
 a| 
Protezione IP (IPsec) è un'opzione di protezione dati in movimento disponibile per proteggere tutto il traffico IP tra un client e un nodo ONTAP. Il protocollo era inizialmente disponibile con ONTAP 9.8 ed è stato implementato solo come software. A partire da ONTAP 9.16,1, è possibile ridurre il carico di alcune operazioni a elaborazione intensiva, come la crittografia e i controlli di integrità, su una scheda NIC (Network Interface Controller) supportata installata nei nodi di storage. L'utilizzo di questa opzione di offload hardware può migliorare significativamente le prestazioni e il throughput del traffico di rete protetto da IPsec.

|===


== Storage a oggetti S3

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
Supporto bucket S3 multiprotocollo per tag e metadati di oggetti S3
 a| 
A partire da ONTAP 9.16.1, il tagging degli oggetti S3 viene esteso dai bucket non-multiprotocollo ONTAP S3 a NAS e ai bucket ONTAP S3 multiprotocollo S3. I tag sono visibili solo nel protocollo S3. L'applicazione https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html["tag e metadati"^] agli oggetti S3 tramite i client S3 consente di definire cicli di vita, back-charging, categorie di dati e flussi di lavoro personalizzati sui dati archiviati come oggetti o file in ONTAP. Una volta integrato con i servizi dati di AWS come Bedrock o Athena, tagging e metadati diventano fondamentali per il Data Processing fornito da questi servizi.


NOTE: Il supporto di tag e metadati definiti dall'utente nei bucket S3 nativi è iniziato in ONTAP 9,9.1.



 a| 
xref:../s3-multiprotocol/index.html[Il bucket S3 multiprotocollo supporta il caricamento multiparte]
 a| 
Il caricamento multiparte è una funzionalità S3 di base disponibile per i bucket ONTAP S3 non multiprotocollo sin dall'inizio. A partire da ONTAP 9.16.1, questa funzionalità core viene estesa ai bucket ONTAP S3 multiprotocollo S3 e NAS.



 a| 
xref:../s3-config/cors-integration.html[Supporto di Cross-Origin Resource Sharing (CORS) per bucket ONTAP S3]
 a| 
Sfruttate tutto il potenziale delle vostre applicazioni web con Cross-Origin Resource Sharing (CORS). CORS consente una perfetta interazione tra le applicazioni client da un dominio e le risorse in un altro. Integrando il supporto CORS, è possibile potenziare le applicazioni Web basate su ONTAP S3 con accesso selettivo cross-origin alle risorse.



 a| 
xref:../s3-snapshots/index.html[ONTAP supporta l'acquisizione di snapshot di bucket ONTAP S3]
 a| 
Puoi generare snapshot point-in-time e di sola lettura dei tuoi bucket ONTAP S3. Utilizzando la funzionalità istantanee S3, è possibile creare manualmente snapshot o generarle automaticamente tramite policy snapshot. Inoltre, è possibile visualizzare, sfogliare ed eliminare snapshot S3 e ripristinare il contenuto snapshot tramite client S3.

|===


== SAN

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../san-admin/enable-space-allocation.html[Deallocazione dello spazio NVMe abilitata per impostazione predefinita]
 a| 
Per impostazione predefinita, la dislocazione dello spazio (denominata anche "hole punzoning" e "unmap") è abilitata per gli spazi dei nomi NVMe. La deallocazione dello spazio consente a un host di disallocare blocchi non utilizzati dagli spazi dei nomi per recuperare spazio. Questo migliora notevolmente l'efficienza complessiva dello storage, in particolare con file system che hanno un elevato turnover dei dati.

|===


== Sicurezza

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[Set idoneo di comandi protetti da regole esteso per la verifica multi-admin]
 a| 
Gli amministratori possono creare regole di verifica multi-admin per proteggere i gruppi di coerenza, tra cui operazioni di creazione, eliminazione e modifica, creazione ed eliminazione di snapshot di gruppi di coerenza e altri comandi.



 a| 
xref:../anti-ransomware/index.html[Protezione autonoma dal ransomware con miglioramenti ai (ARP/ai)]
 a| 
ARP è stato aggiornato con nuove funzionalità ai, che consentono al reparto IT di rilevare e rispondere agli attacchi ransomware con precisione e richiamo del 99%. Poiché l'ai è addestrato su un set di dati completo, non esiste più un periodo di apprendimento per ARP in esecuzione su volumi FlexVol e ARP/ai inizia subito in modalità attiva. ARP/ai include anche una funzionalità di aggiornamento automatico per garantire protezione e resilienza costanti contro le minacce più recenti.


NOTE: La funzione ARP/ai attualmente supporta solo NAS. Sebbene la funzionalità di aggiornamento automatico mostri la disponibilità di nuovi file di sicurezza per la distribuzione in System Manager, questi aggiornamenti sono applicabili solo per la protezione del carico di lavoro NAS.



 a| 
xref:../nvme/set-up-tls-secure-channel-nvme-task.html[NVMe/TCP su TLS 1,3]
 a| 
Proteggi NVMe/TCP "via cavo" a livello di protocollo, con una configurazione semplificata e prestazioni migliorate rispetto a IPSec.



 a| 
Supporto per TLS 1,3 per la comunicazione dell'archivio di oggetti FabricPool
 a| 
ONTAP supporta TLS 1,3 per la comunicazione dell'archivio di oggetti FabricPool.



 a| 
xref:../authentication/overview-oauth2.html[OAuth 2,0 per Microsoft Entra ID]
 a| 
Il supporto di OAuth 2,0, introdotto per la prima volta con ONTAP 9.14,1, è stato migliorato per supportare il server di autorizzazione Microsoft Entra ID (in precedenza Azure ad) con attestazioni OAuth 2,0 standard. Inoltre, le attestazioni di gruppo standard Entra ID basate sui valori di stile UUID sono supportate tramite nuove funzionalità di associazione di gruppi e ruoli. È stata inoltre introdotta una nuova funzione di mappatura dei ruoli esterna che è stata testata con Entra ID ma può essere utilizzata con qualsiasi server di autorizzazione supportato.

|===


== Efficienza dello storage

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../volumes/qtrees-partition-your-volumes-concept.html[Monitoraggio esteso delle performance dei qtree per includere metriche di latenza e statistiche cronologiche]
 a| 
Le precedenti release di ONTAP forniscono solide metriche in real-time per l'utilizzo del qtree, come ad esempio operazioni di i/o al secondo e il throughput in diverse categorie, comprese letture e scritture. A partire da ONTAP 9.16,1, è anche possibile accedere alle statistiche di latenza in tempo reale e visualizzare i dati storici archiviati. Queste nuove funzionalità offrono agli amministratori dello storage IT una maggiore comprensione delle performance di sistema e consentono l'analisi dei trend su periodi di tempo più lunghi. In questo modo potrai prendere decisioni più informate e basate sui dati in relazione al funzionamento e alla pianificazione delle risorse di cloud storage e del data center.

|===


== Miglioramenti alla gestione delle risorse dello storage

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../volumes/manage-svm-capacity.html[Supporto per volumi di data Protection in SVM con limite di storage attivato]
 a| 
Le SVM con limiti di storage abilitati possono contenere volumi di data Protection. Sono supportati i volumi FlexVol in relazioni di disaster recovery asincrone senza cascate, relazioni di disaster recovery sincrone e relazioni di ripristino.

[NOTE]
====
In ONTAP 9.15.1 e nelle release precedenti, i limiti dello storage non possono essere configurati per qualsiasi SVM che contenga volumi di data Protection, volumi in una relazione SnapMirror o in una configurazione MetroCluster.

====


 a| 
xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[Supporto per la distribuzione avanzata della capacità FlexGroup]
 a| 
Se abilitato, il bilanciamento avanzato della capacità distribuisce i dati all'interno di un file tra i volumi membri FlexGroup quando file di grandi dimensioni crescono e consumano spazio su un volume membro.



 a| 
xref:../svm-migrate/index.html[Supporto di mobilità dei dati SVM per la migrazione delle configurazioni MetroCluster]
 a| 
ONTAP supporta le seguenti migrazioni SVM di MetroCluster:

* Migrazione di una SVM tra una configurazione non MetroCluster e una configurazione IP MetroCluster
* Migrazione di una SVM tra due configurazioni IP di MetroCluster
* Migrazione di una SVM da una configurazione FC di MetroCluster e a una configurazione IP di MetroCluster


|===


== System Manager

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../authentication-access-control/webauthn-mfa-overview.html[Supporto dell'autenticazione multifattore WebAuthn resistente al phishing in System Manager]
 a| 
ONTAP 9.16,1 supporta gli accessi MFA WebAuthn, consentendo di utilizzare le chiavi di protezione hardware come secondo metodo di autenticazione quando si accede a Gestione sistema.

|===