---
permalink: release-notes/whats-new-9181.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.18.1' 
summary: Scopri le nuove funzionalità disponibili in ONTAP 9.18.1. 
---
= Novità di ONTAP 9.18.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità disponibili in ONTAP 9.18.1.

Per informazioni dettagliate su problemi noti, limitazioni e avvisi di aggiornamento nelle recenti versioni di ONTAP 9, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"^]. Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.

* Scopri le nuove funzionalità e le funzionalità avanzate https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Caratteristiche di ONTAP MetroCluster"^].
* Scopri di più  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["nuove e migliorate funzionalità del software ONTAP per i sistemi di storage NetApp AFX"^] .
* Scopri di più  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["nuove e migliorate funzionalità del software ONTAP per i sistemi di storage NetApp ASA r2"^] .
* Scopri di più  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["nuovo e migliorato supporto per i sistemi AFF, ASA e FAS e gli switch supportati"^] .
* Ulteriori informazioni sugli aggiornamenti di https://docs.netapp.com/us-en/ontap-automation/whats_new.html["API REST di ONTAP"^].


Per eseguire l'aggiornamento alla versione più recente di ONTAP, vedere link:../upgrade/create-upgrade-plan.html["Prepararsi all'aggiornamento di ONTAP"].



== Networking

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../networking/ipsec-prepare.html[Supporto IPv6 per lo scarico hardware IPsec]
 a| 
Il supporto per l'offload hardware IPsec è esteso a IPv6.



 a| 
xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[Algoritmi PQC OpenSSL]
 a| 
ONTAP supporta algoritmi crittografici di elaborazione postquantistica per SSL. Questi algoritmi forniscono una protezione aggiuntiva contro potenziali futuri attacchi al computer quantistico e sono disponibili quando la modalità SSL FIPS è disabilitata.



 a| 
xref:../networking/configure-backend-encryption.html[Crittografia di rete del cluster backend ONTAP]
 a| 
È possibile abilitare la crittografia TLS per i dati in transito sulla rete del cluster back-end ONTAP .



 a| 
xref:../high-availability/ha-pair-encryption.html[Crittografia della rete di traffico ONTAP HA]
 a| 
È possibile abilitare la crittografia per il traffico tra nodi in coppie ad alta disponibilità (HA).

|===


== SAN

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../san-admin/nvme-copy-offload.html[Scarico della copia NVMe]
 a| 
La funzione di offload della copia NVMe consente a un host NVMe di trasferire le operazioni di copia dalla propria CPU alla CPU del controller di archiviazione ONTAP . L'host può copiare i dati da uno spazio dei nomi NVMe a un altro, riservando le risorse della CPU per i carichi di lavoro delle applicazioni.

|===


== Storage a oggetti S3

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../s3-snapshots/list-restore-s3-snapshot.html[Supporto per il ripristino di snapshot S3 point-in-time]
 a| 
Offre la possibilità di ripristinare oggetti danneggiati in un bucket S3 o di ripristinare l'intero bucket su un bucket esistente.

|===


== Sicurezza

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[Supporto del volume FlexGroup per ARP/AI]
 a| 
I volumi NetApp FlexGroup supportano ARP/AI, offrendo rilevamento e protezione ransomware avanzati basati sull'apprendimento automatico.  In ONTAP 9.17.1 e nelle versioni precedenti, solo la prima generazione di ARP era disponibile per i volumi FlexGroup .  A partire da ONTAP 9.18.1, i volumi FlexGroup sono alla pari con i volumi FlexVol sia sulle piattaforme ONTAP locali (AFF e FAS) sia sulle distribuzioni ONTAP virtuali (inclusi Cloud Volumes ONTAP e ONTAP Select).  Di conseguenza, ARP/AI diventa la tecnologia ARP predefinita per i volumi FlexVol e FlexGroup .

|===


== Miglioramenti alla gestione delle risorse dello storage

[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
xref:../performance-admin/adaptive-qos-policy-groups-task.html[Supporto per gruppi di policy QoS nidificati a due livelli su SVM e volumi]
 a| 
È possibile assegnare una policy QoS a una SVM e ai volumi sotto la SVM contemporaneamente.



 a| 
xref:../flexcache/create-volume-task.html[Creare volumi SVM FlexCache di volumi di origine in una relazione SVM-DR]
 a| 
È possibile creare volumi SVM FlexCache di volumi di origine che fanno parte di una relazione SVM-DR.

|===