---
permalink: fabricpool/benefits-storage-tiers-concept.html 
sidebar: sidebar 
keywords: benefits, storage, tiers, using, fabricpool 
summary: 'La configurazione di un aggregato per l"utilizzo di FabricPool consente di utilizzare i Tier di storage. Puoi bilanciare in modo efficiente le performance e i costi del tuo sistema storage, monitorare e ottimizzare l"utilizzo dello spazio ed eseguire lo spostamento dei dati basato su policy tra i Tier di storage.' 
---
= Vantaggi dei Tier di storage grazie a FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configurazione di un aggregato per l'utilizzo di FabricPool consente di utilizzare i Tier di storage. Puoi bilanciare in modo efficiente le performance e i costi del tuo sistema storage, monitorare e ottimizzare l'utilizzo dello spazio ed eseguire lo spostamento dei dati basato su policy tra i Tier di storage.

* È possibile ottimizzare le performance dello storage e ridurre i costi dello storage memorizzando i dati in un Tier in base alla frequenza di accesso ai dati.
+
** I dati ad accesso frequente ("`hot`") vengono memorizzati nel _Tier di performance_.
+
Il Tier di performance utilizza uno storage primario dalle performance elevate, come un aggregato all flash (all SSD) del sistema storage.

** I dati ad accesso non frequente ("`cold`") vengono memorizzati nel _Tier cloud_, noto anche come _Tier di capacità_.
+
Il Tier cloud utilizza un archivio di oggetti meno costoso e che non richiede performance elevate.



* Hai la flessibilità di specificare il Tier in cui archiviare i dati.
+
È possibile specificare una delle opzioni dei criteri di tiering supportate a livello di volume. Le opzioni consentono di spostare in modo efficiente i dati tra i vari Tier man mano che i dati diventano caldi o freddi.

+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["Tipi di policy di tiering FabricPool"]

* Puoi scegliere uno degli archivi di oggetti supportati da utilizzare come Tier cloud per FabricPool.
* È possibile monitorare l'utilizzo dello spazio in un aggregato abilitato a FabricPool.
* È possibile visualizzare la quantità di dati inattivi in un volume utilizzando il reporting dei dati inattivi.
* È possibile ridurre l'impatto on-premise del sistema storage.
+
È possibile risparmiare spazio fisico quando si utilizza un archivio di oggetti basato sul cloud per il Tier cloud.


