---
permalink: fabricpool/create-mirror-task.html 
sidebar: sidebar 
keywords: creating, fabricpool, mirror 
summary: Per creare un mirror FabricPool, si allegano due archivi di oggetti a un singolo FabricPool. È possibile creare un mirror FabricPool allegando un secondo archivio di oggetti a una configurazione FabricPool esistente di un singolo archivio di oggetti oppure creare una nuova configurazione FabricPool di un singolo archivio di oggetti e quindi allegarvi un secondo archivio di oggetti. È inoltre possibile creare mirror FabricPool sulle configurazioni MetroCluster. 
---
= Creare un mirror ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per creare un mirror FabricPool, si allegano due archivi di oggetti a un singolo FabricPool. È possibile creare un mirror FabricPool allegando un secondo archivio di oggetti a una configurazione FabricPool esistente di un singolo archivio di oggetti oppure creare una nuova configurazione FabricPool di un singolo archivio di oggetti e quindi allegarvi un secondo archivio di oggetti. È inoltre possibile creare mirror FabricPool sulle configurazioni MetroCluster.

.Prima di iniziare
* È necessario aver già creato i due archivi di oggetti utilizzando `storage aggregate object-store config` comando.
* Se si creano mirror FabricPool su configurazioni MetroCluster:
+
** È necessario aver già configurato e configurato MetroCluster
** È necessario aver creato le configurazioni dell'archivio di oggetti sul cluster selezionato.
+
Se si creano mirror FabricPool su entrambi i cluster in una configurazione MetroCluster, è necessario aver creato le configurazioni dell'archivio di oggetti su entrambi i cluster.

** Se non si utilizzano archivi di oggetti on-premise per le configurazioni MetroCluster, è necessario verificare che esista uno dei seguenti scenari:
+
*** Gli archivi di oggetti si trovano in diverse zone di disponibilità
*** Gli archivi di oggetti sono configurati per conservare copie di oggetti in più zone di disponibilità
+
link:setup-object-stores-mcc-task.html["Impostazione degli archivi di oggetti per FabricPool in una configurazione MetroCluster"]







.A proposito di questa attività
L'archivio di oggetti utilizzato per il mirror FabricPool deve essere diverso dall'archivio di oggetti primario.

La procedura per la creazione di un mirror FabricPool è la stessa per le configurazioni MetroCluster e non MetroCluster.

.Fasi
. Se non si utilizza una configurazione FabricPool esistente, crearne una nuova allegando un archivio di oggetti a un livello locale utilizzando il `storage aggregate object-store attach` comando.
+
In questo esempio viene creata una nuova FabricPool allegando un archivio di oggetti a un livello locale.

+
[listing]
----
cluster1::> storage aggregate object-store attach -aggregate aggr1 -name my-store-1
----
. Collegare un secondo archivio di oggetti al livello locale utilizzando il `storage aggregate object-store mirror` comando.
+
Nell'esempio riportato di seguito viene allegato un secondo archivio di oggetti a un livello locale per creare un mirror FabricPool.

+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -name my-store-2
----


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-attach.html["aggregazione di oggetti di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+object-store+config["configurazione dell'archivio oggetti aggregati di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-mirror.html["mirror di archiviazione aggregata di oggetti"^]

