---
permalink: fabricpool/enable-disable-volume-cloud-write-task.html 
sidebar: sidebar 
keywords: creating, volume, fabricpool, cloud write, enable, disable 
summary: A partire da ONTAP 9.14.1, puoi abilitare e disabilitare la modalità di scrittura cloud su un volume nuovo o esistente in un FabricPool per consentire ai client NFS di scrivere dati direttamente nel cloud. 
---
= Attiva e disattiva i volumi da scrivere direttamente nel cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.14.1, puoi abilitare e disabilitare la scrittura direttamente nel cloud su un volume nuovo o esistente in una FabricPool, per consentire ai client NFS di scrivere dati direttamente nel cloud senza attendere le scansioni di tiering. I client SMB continuano a scrivere nel Tier di performance in un volume abilitato per la scrittura nel cloud. La modalità cloud-write è disattivata per impostazione predefinita.

Avere la possibilità di scrivere direttamente nel cloud è utile per casi come le migrazioni, ad esempio, dove grandi quantità di dati vengono trasferite in un cluster rispetto a quanto il cluster può supportare nel Tier locale. Senza la modalità cloud-write, durante la migrazione, vengono trasferite piccole quantità di dati, quindi trasferite e di nuovo in tiering, fino al completamento della migrazione. Utilizzando la modalità cloud-write, questo tipo di gestione non è più necessario, perché i dati non vengono mai trasferiti nel Tier locale.

.Prima di iniziare
* Dovresti essere un amministratore di cluster o SVM.
* È necessario essere al livello di privilegi avanzati.
* Il volume deve essere di tipo lettura-scrittura.
* Il volume deve disporre di TUTTA LA policy di tiering.




== Attiva la scrittura direttamente nel cloud durante la creazione del volume

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
. Creazione di un volume e abilitazione della modalità cloud-write:
+
[source, cli]
----
volume create -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
L'esempio seguente crea un volume denominato vol1 con Cloud Write abilitato nel Tier locale FabricPool (aggr1):

+
[listing]
----
volume create -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----




== Consenti la scrittura diretta nel cloud di un volume esistente

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
. Modifica di un volume per abilitare la modalità cloud-write:
+
[source, cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
Il seguente esempio modifica un volume chiamato vol1 con scrittura cloud abilitata nel Tier locale FabricPool (aggr1):

+
[listing]
----
volume modify -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----




== Disattivare la scrittura direttamente nel cloud su un volume

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato):
+
[source, cli]
----
set -privilege advanced
----
. Disattiva modalità cloud-write:
+
[source, cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <aggregate name>
----
+
L'esempio seguente crea un volume denominato vol1 con Cloud Write abilitato:

+
[listing]
----
volume modify -volume vol1 -is-cloud-write-enabled false -aggregate aggr1
----

