---
permalink: fabricpool/index.html 
sidebar: sidebar 
keywords: deciding, use, managing, storage tiers, fabricpool 
summary: È possibile utilizzare FabricPool per tierare automaticamente i dati in base alla frequenza di accesso. 
---
= Panoramica sulla gestione dei Tier FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare FabricPool per tierare automaticamente i dati in base alla frequenza di accesso.

FabricPool è una soluzione di storage ibrido che utilizza un aggregato all flash (all SSD) come Tier di performance e un archivio di oggetti come Tier di cloud. L'utilizzo di un FabricPool consente di ridurre i costi dello storage senza compromettere le performance, l'efficienza o la protezione.

Il livello cloud può essere localizzato su NetApp StorageGRID o ONTAP S3 (a partire da ONTAP 9.8) o su uno dei seguenti service provider:

* Cloud di Alibaba
* Amazon S3
* Amazon Commercial Cloud Services
* Google Cloud
* Cloud IBM
* Storage Blob Microsoft Azure


[NOTE]
====
A partire da ONTAP 9,7, è possibile utilizzare altri provider di archivi di oggetti che supportano API S3 generiche selezionando il provider di archivi di oggetti S3_Compatible.

====


== Video sul caso di utilizzo di dati Tier e costi inferiori

video::Vs1-WMvj9fI[youtube,width=848,height=480]
.Informazioni correlate
Vedere anche la https://docs.netapp.com/us-en/occm/concept_cloud_tiering.html["Tiering cloud di NetApp"^] documentazione.
