---
permalink: fabricpool/migration-controls-override-tiering-policy-task.html 
sidebar: sidebar 
keywords: cloud migration, controls, override, volume, default, tiering policy 
summary: 'È possibile modificare la policy di tiering predefinita di un volume per controllare il recupero dei dati utente dal Tier cloud al Tier di performance utilizzando l"opzione -cloud-retrieval-policy introdotta in ONTAP 9.8.' 
---
= Utilizza i controlli di migrazione del cloud per ignorare la policy di tiering predefinita di un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la policy di tiering predefinita di un volume per controllare il recupero dei dati utente dal livello cloud al livello di performance utilizzando `-cloud-retrieval-policy` Opzione introdotta in ONTAP 9.8.

.Di cosa hai bisogno
* Modifica di un volume mediante `-cloud-retrieval-policy` L'opzione richiede ONTAP 9.8 o versione successiva.
* Per eseguire questa operazione, è necessario disporre del livello di privilegio avanzato.
* È necessario comprendere il comportamento delle policy di tiering con `-cloud-retrieval-policy`.
+
link:tiering-policies-concept.html#how-tiering-policies-work-with-cloud-migration["Come funzionano le policy di tiering con la migrazione del cloud"]



.Fase
. Modificare il comportamento dei criteri di tiering per un volume esistente utilizzando `volume modify` con il `-cloud-retrieval-policy` opzione:
+
[listing]
----
 volume create -volume <volume_name> -vserver <vserver_name> - tiering-policy <policy_name> -cloud-retrieval-policy
----
+
[listing]
----
vol modify -volume fp_volume4 -vserver vs0 -cloud-retrieval-policy promote
----

