---
permalink: fabricpool/modify-cloud-retrieval-policy-task.html 
sidebar: sidebar 
keywords: cloud retrieval, controls, volume, default, tiering policy 
summary: 'Puoi modificare i criteri di recupero cloud di un volume utilizzando l"opzione -cloud-retrieval-policy introdotta in ONTAP 9.8.' 
---
= Modifica i criteri di recupero cloud di un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool cloud data retrieval è controllato da politiche di recupero che determinano quando i dati vengono scritti di nuovo sul tier locale. I modelli di lettura possono essere sequenziali o casuali.

Ad esempio, quando usi la policy di tiering dei volumi "Auto", se i blocchi cold vengono letti in sequenza, restano cold e rimangono sul cloud tier. Per la maggior parte delle applicazioni client questo è il comportamento desiderato e impedisce che le scansioni approfondite dei file, comuni alle applicazioni antivirus e di analytics, scrivano i dati cold di nuovo sul tier locale.

A partire da ONTAP 9.8, puoi modificare i criteri di recupero cloud di un volume per ignorare il link:tiering-policies-concept.html#how-cloud-retrieval-policies-work-with-tiering-policies["recupero cloud predefinito"] comportamento predefinito.

.Prima di iniziare
* Modifica di un volume mediante `-cloud-retrieval-policy` L'opzione richiede ONTAP 9.8 o versione successiva.
* Per eseguire questa operazione, è necessario disporre del livello di privilegio avanzato.
* È necessario comprendere il comportamento delle policy di tiering con `-cloud-retrieval-policy`.
+
link:tiering-policies-concept.html#how-cloud-retrieval-policies-work-with-tiering-policies["Come funzionano le policy di recupero cloud con le policy di tiering"]



.Fase
. Modifica i criteri di recupero cloud per un volume esistente utilizzando il  `volume modify` comando con l'opzione  `-cloud-retrieval-policy`:
+
[listing]
----
volume create -volume <volume_name> -vserver <vserver_name> - tiering-policy <policy_name> -cloud-retrieval-policy
----
+
[listing]
----
vol modify -volume fp_volume4 -vserver vs0 -cloud-retrieval-policy promote
----

