---
permalink: fabricpool/modify-existing-tag-task.html 
sidebar: sidebar 
keywords: modifying, existing tag 
summary: 'È possibile modificare il nome di un tag, sostituire tag su oggetti esistenti nell"archivio di oggetti o aggiungere un tag diverso a nuovi oggetti che si intende aggiungere in seguito.' 
---
= Modificare un tag esistente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare il nome di un tag, sostituire tag su oggetti esistenti nell'archivio di oggetti o aggiungere un tag diverso a nuovi oggetti che si intende aggiungere in seguito.

.A proposito di questa attività
Utilizzando il `volume modify` con il `-tiering-object-tags` l'opzione sostituisce i tag esistenti con il nuovo valore fornito.



== Procedura

[role="tabbed-block"]
====
.System Manager
--
. Selezionare *Storage > Tier*.
. Individuare un Tier di storage con volumi contenenti tag che si desidera modificare.
. Fare clic sulla scheda *Volumes* (volumi).
. Individuare il volume con i tag che si desidera modificare e nella colonna *Tag oggetto* fare clic sul nome del tag.
. Modificare il tag.
. Fare clic su *Apply* (Applica).


--
.CLI
--
. Utilizzare `volume modify` con il `-tiering-object-tags` opzione per modificare un tag esistente.
+
[listing]
----
volume modify [ -vserver <vserver name> ] -volume <volume_name> -tiering-object-tags <key1=value1> [ ,<key2=value2>,
<key3=value3>,<key4=value4> ]
----
+
Nell'esempio seguente viene modificato il nome del tag esistente type=abc in type=xyz.

+
[listing]
----
vol create -volume fp_volume1 -vserver vs0 -tiering-object-tags project=fabricpool,type=xyz,content=data
----


--
====