---
permalink: fabricpool/monitor-space-utilization-task.html 
sidebar: sidebar 
keywords: monitoring, space, utilization, fabricpool 
summary: Devi sapere quanti dati sono memorizzati nei livelli di performance e cloud per FabricPool. Tali informazioni consentono di determinare se è necessario modificare la policy di tiering di un volume, aumentare il limite di utilizzo della licenza FabricPool o aumentare lo spazio di storage del Tier cloud. 
---
= Monitorare l'utilizzo dello spazio per FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Devi sapere quanti dati sono memorizzati nei livelli di performance e cloud per FabricPool. Tali informazioni consentono di determinare se è necessario modificare la policy di tiering di un volume, aumentare il limite di utilizzo della licenza FabricPool o aumentare lo spazio di storage del Tier cloud.

.Fasi
. Monitorare l'utilizzo dello spazio per gli aggregati abilitati a FabricPool utilizzando uno dei seguenti comandi per visualizzare le informazioni:
+
|===


| Se si desidera visualizzare... | Quindi utilizzare questo comando: 


 a| 
La dimensione utilizzata del Tier cloud in un aggregato
 a| 
`storage aggregate show` con `-instance` parametro



 a| 
Dettagli sull'utilizzo dello spazio all'interno di un aggregato, inclusa la capacità di riferimento dell'archivio di oggetti
 a| 
`storage aggregate show-space` con `-instance` parametro



 a| 
Utilizzo dello spazio degli archivi di oggetti collegati agli aggregati, inclusa la quantità di spazio di licenza utilizzata
 a| 
`storage aggregate object-store show-space`



 a| 
Un elenco di volumi in un aggregato e le impronte dei dati e dei metadati
 a| 
`volume show-footprint`

|===
+
Oltre a utilizzare i comandi CLI, è possibile utilizzare Active IQ Unified Manager (precedentemente noto come gestore unificato di OnCommand), insieme a FabricPool Advisor, supportato su cluster ONTAP 9.4 e versioni successive, o System Manager per monitorare l'utilizzo dello spazio.

+
Nell'esempio seguente vengono illustrati i modi per visualizzare l'utilizzo dello spazio e le informazioni correlate per FabricPool:

+
[listing]
----
cluster1::> storage aggregate show-space -instance

                          Aggregate: MyFabricPool
                                                                   ...
                                               Aggregate Display Name: MyFabricPool
                                                                   ...
                          Total Object Store Logical Referenced Capacity: -
                          Object Store Logical Referenced Capacity Percentage: -
                                                                   ...
                                                       Object Store Size: -
                          Object Store Space Saved by Storage Efficiency: -
                          Object Store Space Saved by Storage Efficiency Percentage: -
                                                 Total Logical Used Size: -
                                                 Logical Used Percentage: -
                                           Logical Unreferenced Capacity: -
                                         Logical Unreferenced Percentage: -

----
+
[listing]
----
cluster1::> storage aggregate show -instance

                           Aggregate: MyFabricPool
                           ...
                           Composite: true
                           Capacity Tier Used Size:
                           ...
----
+
[listing]
----
cluster1::> volume show-footprint

Vserver : vs1
Volume : rootvol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Volume Guarantee                 MB          %
Flexible Volume Metadata         KB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %

Vserver : vs1
Volume : vol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Footprint in Performance Tier    KB          %
Footprint in Amazon01            KB          %
Flexible Volume Metadata         MB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %
...
----
. Eseguire una delle seguenti operazioni in base alle necessità:
+
|===


| Se si desidera... | Quindi... 


 a| 
Modificare la policy di tiering di un volume
 a| 
Seguire la procedura descritta in link:modify-tiering-policy-cooling-period-task.html["Gestione del tiering dello storage modificando la policy di tiering di un volume o il periodo minimo di raffreddamento del tiering"].



 a| 
Aumentare il limite di utilizzo della licenza FabricPool
 a| 
Contattare il rappresentante commerciale NetApp o del partner.

https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"^]



 a| 
Aumentare lo spazio di storage del Tier cloud
 a| 
Contattare il provider dell'archivio di oggetti utilizzato per il livello cloud.

|===

