---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: tr-4814, fabricpool, setting up, ontap s3, cloud tier, local tier, tiering, storage tiering, storage tier, lif 
summary: Se utilizzi ONTAP 9.8 o versioni successive, puoi impostare ONTAP S3 come livello cloud per FabricPool. 
---
= Configurare ONTAP S3 come Tier cloud FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se utilizzi ONTAP 9.8 o versioni successive, puoi impostare ONTAP S3 come livello cloud per FabricPool.

.Prima di iniziare
* È necessario disporre del nome del server ONTAP S3 e dell'indirizzo IP dei relativi LIF associati sul cluster remoto.
+

NOTE: Il nome del server viene utilizzato come nome di dominio completo (FQDN) dalle applicazioni client. Al di fuori di ONTAP, conferma che i record DNS puntano alle LIF dati SVM che vengono utilizzate.

* Deve essere presente <<create-lif,LIF intracluster>>nel cluster locale.
+
Se configurato per il tiering del cluster locale, un Tier locale (noto anche come aggregato di storage nella CLI ONTAP) viene collegato a un bucket locale. FabricPool utilizza le interfacce LIF del cluster per il traffico tra cluster.

+

NOTE: In caso di saturazione delle risorse di LIF del cluster, potrebbe verificarsi il peggioramento delle performance. Per evitare questo problema, NetApp consiglia di utilizzare cluster a quattro nodi o superiori in caso di tiering in un bucket locale, insieme a una coppia ha per il Tier locale e una coppia ha per il bucket locale. Il tiering nei bucket locali su una singola coppia ha non è consigliato.

* Per abilitare il tiering della capacità (cloud) FabricPool remota utilizzando ONTAP S3, è necessario link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html["Configurare intercluster LIF"] sul client FabricPool e link:../s3-config/create-data-lifs-task.html["Configurare le LIF dati"] sul server dell'archivio di oggetti.


.A proposito di questa attività
Il bilanciamento del carico è abilitato per i server ONTAP S3 in ONTAP 9.8 e versioni successive. Quando il nome host del server viene risolto in più indirizzi IP, ONTAP stabilisce connessioni client con tutti gli indirizzi IP restituiti (fino a un massimo di 16 indirizzi IP). Gli indirizzi IP vengono raccolti con un metodo round-robin quando vengono stabilite le connessioni.

.Fasi
Puoi impostare ONTAP S3 come livello cloud per FabricPool con Gestione di sistema ONTAP o l'interfaccia utente di ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. Fare clic su *Storage > Tier > Add Cloud Tier* e selezionare ONTAP S3 come provider dell'archivio di oggetti.
. Completare le informazioni richieste.
. Se si desidera creare un mirror cloud, fare clic su *Aggiungi come mirror FabricPool*.


Un mirror FabricPool offre un metodo per sostituire perfettamente un archivio di dati e garantisce che i dati siano disponibili in caso di disastro.

--
.CLI
--
. Aggiungere voci per il server S3 e i LIF al server DNS.
+
|===


| Opzione | Descrizione 


 a| 
*Se si utilizza un server DNS esterno*
 a| 
Assegnare il nome del server S3 e gli indirizzi IP all'amministratore del server DNS.



 a| 
*Se si utilizza la tabella degli host DNS del sistema locale*
 a| 
Immettere il seguente comando:

[listing]
----
dns host create -vserver <svm_name> -address ip_address -hostname <s3_server_name>
----
|===
. Specificare le informazioni di configurazione di ONTAP S3 utilizzando `storage aggregate object-store config create` con il `-provider-type` `ONTAP_S3` parametro.
+
** Il `storage aggregate object-store config create` Il comando non riesce se il sistema ONTAP locale non riesce ad accedere al server ONTAP S3 con le informazioni fornite.
** Si utilizza `-access-key` Parametro per specificare la chiave di accesso per l'autorizzazione delle richieste al server ONTAP S3.
** Si utilizza `-secret-password` Parametro per specificare la password (chiave di accesso segreta) per l'autenticazione delle richieste al server ONTAP S3.
** Se la password del server ONTAP S3 viene modificata, è necessario aggiornare immediatamente la password corrispondente memorizzata nel sistema ONTAP locale.
+
In questo modo è possibile accedere ai dati nell'archivio di oggetti di ONTAP S3 senza interruzioni.

** L'impostazione del `-is-certificate-validation-enabled` parametro su `false` disattiva il controllo dei certificati per ONTAP S3. (`-is-certificate-validation-enabled true`Si consiglia di utilizzare i certificati firmati da un'autorità di certificazione di terze parti.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. Visualizzare e verificare le informazioni di configurazione di ONTAP_S3 utilizzando `storage aggregate object-store config show` comando.
+
Il `storage aggregate object-store config modify` consente di modificare `ONTAP_S3` Informazioni di configurazione per FabricPool.



--
====
[[create-lif]]
.Informazioni correlate
* link:../smb-config/create-lif-task.html["Creazione di una LIF per SMB"]
* link:../nfs-config/create-lif-task.html["Crea LIF per NFS"]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["creazione di configurazioni di archiviazione di oggetti aggregati"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["modifica della configurazione dell'archivio oggetti aggregati di archiviazione"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["mostra configurazione archivio oggetti aggregati di archiviazione"^]

