---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting, up, alibaba cloud object, storage, cloud tier 
summary: Se utilizzi ONTAP 9.6 o versioni successive, puoi impostare Alibaba Cloud Object Storage come livello cloud per FabricPool. 
---
= Configurare lo storage a oggetti cloud Alibaba come Tier cloud ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se utilizzi ONTAP 9.6 o versioni successive, puoi impostare Alibaba Cloud Object Storage come livello cloud per FabricPool.

.Considerazioni sull'utilizzo dello storage a oggetti cloud di Alibaba con FabricPool
* È necessario un link:https://bluexp.netapp.com/cloud-tiering["Licenza di tiering BlueXP"]durante il tiering in Alibaba Cloud Object Storage.
* Nei sistemi AFF e FAS e in ONTAP Select, FabricPool supporta le seguenti classi di servizi di storage a oggetti Alibaba:
+
** Alibaba Object Storage Service Standard
** Alibaba Object Storage Service - accesso non frequente
+
https://www.alibabacloud.com/help/doc-detail/51374.htm["Alibaba Cloud: Introduzione alle classi di storage"^]





Per informazioni sulle classi di storage non elencate, contattare il rappresentante commerciale NetApp.

.Fasi
. Specificare le informazioni di configurazione di Alibaba Cloud Object Storage utilizzando `storage aggregate object-store config create` con il `-provider-type` `AliCloud` parametro.
+
** Il `storage aggregate object-store config create` Il comando non riesce se ONTAP non riesce ad accedere all'archivio di oggetti cloud Alibaba con le informazioni fornite.
** Si utilizza `-access-key` Parametro per specificare la chiave di accesso per autorizzare le richieste all'archivio di oggetti di Alibaba Cloud Object Storage.
** Se la password di Alibaba Cloud Object Storage viene modificata, è necessario aggiornare immediatamente la password corrispondente memorizzata in ONTAP.
+
In questo modo, ONTAP può accedere ai dati nello storage a oggetti cloud di Alibaba senza interruzioni.



+
[listing]
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Visualizzare e verificare le informazioni di configurazione di Alibaba Cloud Object Storage utilizzando `storage aggregate object-store config show` comando.
+
Il `storage aggregate object-store config modify` Il comando consente di modificare le informazioni di configurazione di Alibaba Cloud Object Storage per FabricPool.


