---
permalink: fabricpool/setup-aws-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, aws, s3, cloud tier 
summary: 'Se utilizzi ONTAP 9.2 o versioni successive, puoi impostare Amazon S3 come livello cloud per FabricPool. Se utilizzi ONTAP 9.5 o versioni successive, puoi configurare i servizi cloud commerciali Amazon (C2S) per FabricPool.' 
---
= Imposta Amazon S3 come Tier cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se utilizzi ONTAP 9.2 o versioni successive, puoi impostare Amazon S3 come livello cloud per FabricPool. Se utilizzi ONTAP 9.5 o versioni successive, puoi configurare i servizi cloud commerciali Amazon (C2S) per FabricPool.

.Considerazioni sull'utilizzo di Amazon S3 con FabricPool
* Potrebbe essere necessaria una licenza FabricPool.
+
** I nuovi sistemi AFF ordinati sono dotati di 10 TB di capacità libera per l'utilizzo di FabricPool.
+
Se hai bisogno di capacità aggiuntiva su un sistema AFF, se utilizzi Amazon S3 su un sistema non AFF o se esegui l'aggiornamento da un cluster esistente, devi disporre di una licenza FabricPool.

+
Se si ordina FabricPool per la prima volta per un cluster esistente, è disponibile una licenza FabricPool con 10 TB di capacità libera.



* Si consiglia di utilizzare la LIF utilizzata da ONTAP per la connessione al server a oggetti Amazon S3 su una porta a 10 Gbps.
* Nei sistemi AFF e FAS e in ONTAP Select, FabricPool supporta le seguenti classi di storage Amazon S3:
+
** Standard Amazon S3
** Amazon S3 Standard - accesso non frequente (Standard - IA)
** Amazon S3 One zone - accesso non frequente (una zona - IA)
** Amazon S3 Intelligent-Tiering
** Amazon Commercial Cloud Services
+
https://aws.amazon.com/s3/storage-classes/["Documentazione Amazon Web Services: Classi di storage Amazon S3"]



+
Per informazioni sulle classi di storage non elencate, contattare il rappresentante commerciale.

* Su Cloud Volumes ONTAP, FabricPool supporta il tiering da SSD General Purpose (gp2) e volumi HDD ottimizzati per il throughput (st1) di Amazon Elastic Block Store (EBS).


.Fasi
. Specificare le informazioni di configurazione di Amazon S3 utilizzando `storage aggregate object-store config create` con il `-provider-type` `AWS_S3` parametro.
+
** Si utilizza `-auth-type` `CAP` Parametro per ottenere le credenziali per l'accesso a C2S.
+
Quando si utilizza `-auth-type` `CAP` è necessario utilizzare il `-cap-url` Parametro per specificare l'URL completo per richiedere credenziali temporanee per l'accesso a C2S.

** Il `storage aggregate object-store config create` Il comando non riesce se ONTAP non riesce ad accedere ad Amazon S3 con le informazioni fornite.
** Si utilizza `-access-key` Parametro per specificare la chiave di accesso per autorizzare le richieste all'archivio di oggetti Amazon S3.
** Si utilizza `-secret-password` Parametro per specificare la password (chiave di accesso segreta) per l'autenticazione delle richieste all'archivio di oggetti Amazon S3.
** Se la password Amazon S3 viene modificata, devi aggiornare immediatamente la password corrispondente memorizzata in ONTAP.
+
In questo modo, ONTAP può accedere ai dati in Amazon S3 senza interruzioni.

+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name my_aws_store -provider-type AWS_S3
-server s3.amazonaws.com -container-name my-aws-bucket
-access-key DXJRXHPXHYXA9X31X3JX
----
+
[listing]
----
cluster1::> storage aggregate object-store config create -object-store-name my_c2s_store -provider-type AWS_S3 -auth-type CAP -cap-url https://123.45.67.89/api/v1/credentials?agency=XYZ&mission=TESTACCT&role=S3FULLACCESS -server my-c2s-s3server-fqdn -container my-c2s-s3-bucket
----


. Visualizzare e verificare le informazioni di configurazione di Amazon S3 utilizzando `storage aggregate object-store config show` comando.
+
Il `storage aggregate object-store config modify` Comando consente di modificare le informazioni di configurazione di Amazon S3 per FabricPool.


