---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ibm cloud, object storage, cloud tier 
summary: Se si utilizza ONTAP 9.5 o versione successiva, è possibile impostare lo storage a oggetti cloud IBM come livello cloud per FabricPool. 
---
= Configurare IBM Cloud Object Storage come Tier cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza ONTAP 9.5 o versione successiva, è possibile impostare lo storage a oggetti cloud IBM come livello cloud per FabricPool.

.Considerazioni sull'utilizzo dello storage a oggetti cloud IBM con FabricPool
* Potrebbe essere necessaria una licenza FabricPool.
+
I nuovi sistemi AFF ordinati sono dotati di 10 TB di capacità libera per l'utilizzo di FabricPool. Se si necessita di capacità aggiuntiva su un sistema AFF, se si utilizza IBM Cloud Object Storage su un sistema non AFF o se si esegue l'upgrade da un cluster esistente, è necessario un link:../fabricpool/install-license-aws-azure-ibm-task.html["Licenza FabricPool"].

+
Se si ordina FabricPool per la prima volta per un cluster esistente, è disponibile una licenza FabricPool con 10 TB di capacità libera.

* Si consiglia di utilizzare la LIF utilizzata da ONTAP per la connessione al server a oggetti cloud IBM su una porta a 10 Gbps.


.Fasi
. Specificare le informazioni di configurazione di IBM Cloud Object Storage utilizzando `storage aggregate object-store config create` con il `-provider-type` `IBM_COS` parametro.
+
** Il `storage aggregate object-store config create` Il comando non riesce se ONTAP non riesce ad accedere all'archivio di oggetti cloud IBM con le informazioni fornite.
** Si utilizza `-access-key` Parametro per specificare la chiave di accesso per autorizzare le richieste all'archivio di oggetti di IBM Cloud Object Storage.
** Si utilizza `-secret-password` Parametro per specificare la password (chiave di accesso segreta) per l'autenticazione delle richieste all'archivio di oggetti di IBM Cloud Object Storage.
** Se la password di IBM Cloud Object Storage viene modificata, è necessario aggiornare immediatamente la password corrispondente memorizzata in ONTAP.
+
In questo modo, ONTAP può accedere ai dati nello storage a oggetti cloud IBM senza interruzioni.



+
[listing]
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Visualizzare e verificare le informazioni di configurazione di IBM Cloud Object Storage utilizzando `storage aggregate object-store config show` comando.
+
Il `storage aggregate object-store config modify` Il comando consente di modificare le informazioni di configurazione di IBM Cloud Object Storage per FabricPool.


