---
permalink: fabricpool/test-object-store-performance-task.html 
sidebar: sidebar 
keywords: performance, latency, cloud, tier, aggregate, object store profiler 
summary: 'Prima di collegare un archivio di oggetti a un livello locale, è possibile verificare le prestazioni di latenza e throughput dell"archivio di oggetti utilizzando il profiler dell"archivio di oggetti.' 
---
= Verifica la latenza e le performance di throughput del Tier cloud ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di collegare un archivio di oggetti a un livello locale, è possibile verificare le prestazioni di latenza e throughput dell'archivio di oggetti utilizzando il profiler dell'archivio di oggetti.

[NOTE]
====
I risultati del profiler degli archivi di oggetti sono una misura della connettività tra ONTAP e l'archivio di oggetti del Tier cloud utilizzando 4MB put e GET a lettura casuale a intervalli di byte compresi tra 4MB e 256KB. (Solo le funzioni ONTAP interne, come SnapMirror, possono utilizzare GET di dimensioni superiori a 32KB).

Poiché non tengono conto di workload concorrenti o del comportamento esclusivo delle applicazioni client, i risultati del profiler degli archivi di oggetti non rappresentano un indicatore perfetto delle prestazioni di tiering.

====
.Prima di iniziare
* È necessario aggiungere il livello cloud a ONTAP prima di poterlo utilizzare con il profiler dell'archivio di oggetti.
* È necessario essere in modalità privilegio avanzato CLI ONTAP.


.Fasi
. Avviare il profiler dell'archivio oggetti:
+
`storage aggregate object-store profiler start -object-store-name <name> -node <name>`

. Visualizzare i risultati:
+
`storage aggregate object-store profiler show`


