---
permalink: nfs-config/add-storage-capacity-nfs-enabled-svm-concept.html 
sidebar: sidebar 
keywords: add, storage, capacity, nfs-enabled, svm 
summary: 'Per aggiungere capacità di storage a una SVM abilitata per NFS, è necessario creare un volume o un qtree per fornire un container di storage e creare o modificare un criterio di esportazione per tale container. È quindi possibile verificare l"accesso del client NFS dal cluster e verificare l"accesso dai sistemi client.' 
---
= Aggiunta di capacità di storage a una panoramica SVM abilitata per NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aggiungere capacità di storage a una SVM abilitata per NFS, è necessario creare un volume o un qtree per fornire un container di storage e creare o modificare un criterio di esportazione per tale container. È quindi possibile verificare l'accesso del client NFS dal cluster e verificare l'accesso dai sistemi client.

.Di cosa hai bisogno
* NFS deve essere completamente configurato su SVM.
* Il criterio di esportazione predefinito del volume root SVM deve contenere una regola che consenta l'accesso a tutti i client.
* Tutti gli aggiornamenti della configurazione dei name service devono essere completi.
* Eventuali aggiunte o modifiche a una configurazione Kerberos devono essere completate.

