---
permalink: nfs-config/additional-information-reference.html 
sidebar: sidebar 
keywords: additional, information, nfs, configuration, networking, san protocol, root volume, protection 
summary: 'Una volta verificato l"accesso al client NFS, è possibile eseguire una configurazione NFS aggiuntiva o aggiungere l"accesso SAN. Una volta completato l"accesso al protocollo, è necessario proteggere il volume root della SVM (Storage Virtual Machine).' 
---
= Dove trovare ulteriori informazioni su ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una volta verificato l'accesso al client NFS, è possibile eseguire una configurazione NFS aggiuntiva o aggiungere l'accesso SAN. Una volta completato l'accesso al protocollo, è necessario proteggere il volume root della SVM (Storage Virtual Machine).



== Configurazione NFS

È possibile configurare ulteriormente l'accesso NFS utilizzando le seguenti informazioni e report tecnici:

* link:../nfs-admin/index.html["Gestione NFS"]
+
Descrive come configurare e gestire l'accesso ai file utilizzando NFS.

* https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Report tecnico di NetApp 4067: Guida all'implementazione e alle Best practice di NFS"^]
+
Funge da guida operativa NFSv3 e NFSv4 e fornisce una panoramica del sistema operativo ONTAP con particolare attenzione a NFSv4.

* https://www.netapp.com/pdf.html?item=/media/19371-tr-4073.pdf["Report tecnico di NetApp 4073: Autenticazione unificata sicura"^]
+
Spiega come configurare ONTAP per l'utilizzo con server Kerberos versione 5 (krb5) basati su UNIX per l'autenticazione dello storage NFS e Active Directory (ad) come provider di identità KDC e LDAP (Lightweight Directory Access Protocol).

* https://www.netapp.com/pdf.html?item=/media/16398-tr-3580pdf.pdf["Report tecnico di NetApp 3580: Guida ai miglioramenti e alle Best practice di NFSv4 per l'implementazione di Data ONTAP"^]
+
Descrive le Best practice da seguire durante l'implementazione dei componenti NFSv4 su client AIX, Linux o Solaris collegati a sistemi che eseguono ONTAP.





== Configurazione di rete

È possibile configurare ulteriormente le funzioni di rete e i servizi di gestione dei nomi utilizzando i seguenti report tecnici e informativi:

* link:../nfs-admin/index.html["Gestione NFS"]
+
Descrive come configurare e gestire il networking ONTAP.

* https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["Report tecnico di NetApp 4182: Considerazioni sulla progettazione dello storage Ethernet e Best practice per le configurazioni di Clustered Data ONTAP"^]
+
Descrive l'implementazione delle configurazioni di rete ONTAP e fornisce scenari di implementazione di rete comuni e consigli sulle Best practice.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Report tecnico di NetApp 4668: Guida alle Best practice per i servizi di nome"^]
+
Spiega come configurare LDAP, NIS, DNS e la configurazione dei file locali per scopi di autenticazione.





== Configurazione del protocollo SAN

Se si desidera fornire o modificare l'accesso SAN alla nuova SVM, è possibile utilizzare le informazioni di configurazione FC o iSCSI, disponibili per più sistemi operativi host.



== Protezione del volume root

Dopo aver configurato i protocolli su SVM, assicurarsi che il volume root sia protetto:

* link:../data-protection/index.html["Protezione dei dati"]
+
Descrive come creare un mirror di condivisione del carico per proteggere il volume root SVM, una Best practice NetApp per le SVM abilitate per NAS. Viene inoltre descritto come eseguire rapidamente il ripristino da guasti o perdite di volume promuovendo il volume root SVM da un mirror di condivisione del carico.


