---
permalink: nfs-config/assign-export-policy-qtree-task.html 
sidebar: sidebar 
keywords: assign, export, policy, qtree 
summary: Invece di esportare un intero volume, è possibile esportare un qtree specifico su un volume per renderlo direttamente accessibile ai client. È possibile esportare un qtree assegnandogli un criterio di esportazione. È possibile assegnare il criterio di esportazione quando si crea un nuovo qtree o modificando un qtree esistente. 
---
= Assegnare un criterio di esportazione a un qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Invece di esportare un intero volume, è possibile esportare un qtree specifico su un volume per renderlo direttamente accessibile ai client. È possibile esportare un qtree assegnandogli un criterio di esportazione. È possibile assegnare il criterio di esportazione quando si crea un nuovo qtree o modificando un qtree esistente.

.Prima di iniziare
Il criterio di esportazione deve esistere.

.A proposito di questa attività
Per impostazione predefinita, i qtree ereditano il criterio di esportazione padre del volume contenente, se non diversamente specificato al momento della creazione.

È possibile associare un criterio di esportazione a un qtree quando si crea il qtree o in qualsiasi momento dopo la creazione del qtree. È possibile associare un criterio di esportazione al qtree, anche se un criterio può essere associato a molti qtree.

.Fasi
. Se non è stato specificato un criterio di esportazione al momento della creazione del qtree, assegnare un criterio di esportazione al qtree:
+
`volume qtree modify -vserver _vserver_name_ -qtree-path /vol/_volume_name/qtree_name_ -export-policy _export_policy_name_`

. Verificare che il criterio sia stato assegnato al qtree:
+
`volume qtree show -qtree _qtree_name_ -fields export-policy`



.Esempio
I seguenti comandi assegnano il criterio di esportazione nfs_policy al qtree qt1 su SVM vs1 e ne verificano l'assegnazione:

[listing]
----
cluster::> volume modify -v1server vs1 -qtree-path /vol/vol1/qt1 -policy nfs_policy

cluster::>volume qtree show -volume vol1 -fields export-policy
vserver volume qtree export-policy
------- ------ ----- -------------
vs1     data1  qt01  nfs_policy
----