---
permalink: nfs-config/configure-dns-host-name-resolution-task.html 
sidebar: sidebar 
keywords: enabling, dns, host-name, resolution, enable, host, name, resolve, automatic configuration validation 
summary: È possibile utilizzare il comando DNS name-service dei servizi vserver per abilitare il DNS su una SVM e configurarlo in modo che utilizzi il DNS per la risoluzione dei nomi host. I nomi host vengono risolti utilizzando server DNS esterni. 
---
= Abilitare il DNS per la risoluzione del nome host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `vserver services name-service dns` Per abilitare il DNS su una SVM e configurarlo per l'utilizzo del DNS per la risoluzione dei nomi host. I nomi host vengono risolti utilizzando server DNS esterni.

.Di cosa hai bisogno
Per la ricerca dei nomi host, è necessario che sia disponibile un server DNS a livello di sito.

È necessario configurare più server DNS per evitare un singolo punto di errore. Il `vserver services name-service dns create` Viene visualizzato un messaggio di avviso se si immette un solo nome server DNS.

.A proposito di questa attività
La _Guida alla gestione della rete_ contiene informazioni sulla configurazione del DNS dinamico sulla SVM.

.Fasi
. Abilitare il DNS sulla SVM:
+
`vserver services name-service dns create -vserver _vserver_name_ -domains _domain_name_ -name-servers _ip_addresses_ -state enabled`

+
Il seguente comando abilita i server DNS esterni su SVM vs1:

+
[listing]
----
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
----
+
[NOTE]
====
A partire da ONTAP 9.2, la `vserver services name-service dns create` Il comando esegue una convalida automatica della configurazione e segnala un messaggio di errore se ONTAP non riesce a contattare il server dei nomi.

====
. Visualizzare le configurazioni del dominio DNS utilizzando `vserver services name-service dns show` comando.
+
Il seguente comando visualizza le configurazioni DNS per tutte le SVM nel cluster:

+
[listing]
----
vserver services name-service dns show
                                             Name
Vserver           State     Domains             Servers
----------------- --------- ------------------- -------------
cluster1          enabled   example.com         192.0.2.201,
                                                192.0.2.202
vs1.example.com   enabled   example.com         192.0.2.201,
                                                192.0.2.202
----
+
Il seguente comando visualizza informazioni dettagliate sulla configurazione DNS per SVM vs1:

+
[listing]
----
vserver services name-service dns show -vserver vs1.example.com
               Vserver: vs1.example.com
               Domains: example.com
          Name Servers: 192.0.2.201, 192.0.2.202
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
----
. Convalidare lo stato dei server dei nomi utilizzando `vserver services name-service dns check` comando.
+
Il `vserver services name-service dns check` Il comando è disponibile a partire da ONTAP 9.2.

+
[listing]
----
vserver services name-service dns check -vserver vs1.example.com

Vserver           Name Server     Status       Status Details
----------------  -------------   ----------   --------------------------
vs1.example.com   10.0.0.50         up         Response time (msec): 2
vs1.example.com   10.0.0.51         up         Response time (msec): 2
----

