---
permalink: nfs-config/configure-svms-ldap-task.html 
sidebar: sidebar 
keywords: verify, ldap, sources, name, service, switch, table 
summary: È necessario verificare che le origini LDAP per i servizi nome siano elencate correttamente nella tabella di switch del servizio nome per SVM. 
---
= Verificare le origini LDAP per gli SVM NFS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario verificare che le origini LDAP per i servizi nome siano elencate correttamente nella tabella di switch del servizio nome per SVM.

.Fasi
. Visualizza il contenuto della tabella corrente dello switch name service:
+
`vserver services name-service ns-switch show -vserver _svm_name_`

+
Il comando seguente mostra i risultati per SVM My_SVM:

+
[listing]
----
ie3220-a::> vserver services name-service ns-switch show -vserver My_SVM
                               Source
Vserver         Database       Order
--------------- ------------   ---------
My_SVM          hosts          files,
                               dns
My_SVM          group          files,ldap
My_SVM          passwd         files,ldap
My_SVM          netgroup       files
My_SVM          namemap        files
5 entries were displayed.
----
+
`namemap` specifica le origini per la ricerca delle informazioni di mappatura dei nomi e in quale ordine. In un ambiente UNIX, questa voce non è necessaria. La mappatura dei nomi è necessaria solo in un ambiente misto che utilizza sia UNIX che Windows.

. Aggiornare `ns-switch` voce appropriata:
+
|===
| Se si desidera aggiornare la voce ns-switch per... | Immettere il comando... 


 a| 
Informazioni sull'utente
 a| 
`vserver services name-service ns-switch modify -vserver _vserver_name_ -database passwd -sources ldap,files`



 a| 
Informazioni sul gruppo
 a| 
`vserver services name-service ns-switch modify -vserver _vserver_name_ -database group -sources ldap,files`



 a| 
Informazioni sul netgroup
 a| 
`vserver services name-service ns-switch modify -vserver _vserver_name_ -database netgroup -sources ldap,files`

|===

