---
permalink: nfs-config/create-local-unix-user-task.html 
sidebar: sidebar 
keywords: create, local, unix, user 
summary: 'È possibile utilizzare il comando name-service unix-user create dei servizi vserver per creare utenti UNIX locali. Un utente UNIX locale è un utente UNIX creato sull"opzione SVM as a UNIX name service da utilizzare nell"elaborazione delle mappature dei nomi.' 
---
= Creare un utente UNIX locale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `vserver services name-service unix-user create` Per creare utenti UNIX locali. Un utente UNIX locale è un utente UNIX creato sull'opzione SVM as a UNIX name service da utilizzare nell'elaborazione delle mappature dei nomi.

.Fase
. Creare un utente UNIX locale:
+
`vserver services name-service unix-user create -vserver _vserver_name_ -user _user_name_ -id _integer_ -primary-gid _integer_ -full-name _full_name_`

+
`-user _user_name_` specifica il nome utente. La lunghezza del nome utente deve essere pari o inferiore a 64 caratteri.

+
`-id _integer_` Specifica l'ID utente assegnato.

+
`-primary-gid _integer_` Specifica l'ID del gruppo primario. In questo modo l'utente viene aggiunto al gruppo primario. Dopo aver creato l'utente, è possibile aggiungerlo manualmente a qualsiasi altro gruppo desiderato.



.Esempio
Il seguente comando crea un utente UNIX locale denominato johnm (nome completo "John Miller") sulla SVM denominata vs1. L'utente ha l'ID 123 e l'ID del gruppo primario 100.

[listing]
----
node::> vserver services name-service unix-user create -vserver vs1 -user johnm -id 123
-primary-gid 100 -full-name "John Miller"
----