---
permalink: nfs-config/export-policies-concept.html 
sidebar: sidebar 
keywords: secure, nfs, access, using, export, policies 
summary: 'È possibile utilizzare policy di esportazione per limitare l"accesso NFS a volumi o qtree a client che corrispondono a parametri specifici. Quando si effettua il provisioning di nuovo storage, è possibile utilizzare policy e regole esistenti, aggiungere regole a policy esistenti o creare nuove policy e regole. È inoltre possibile verificare la configurazione dei criteri di esportazione' 
---
= Scopri come proteggere l'accesso ONTAP NFS utilizzando i criteri di esportazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare policy di esportazione per limitare l'accesso NFS a volumi o qtree a client che corrispondono a parametri specifici. Quando si effettua il provisioning di nuovo storage, è possibile utilizzare policy e regole esistenti, aggiungere regole a policy esistenti o creare nuove policy e regole. È inoltre possibile verificare la configurazione dei criteri di esportazione

[NOTE]
====
A partire da ONTAP 9.3, è possibile attivare il controllo della configurazione dei criteri di esportazione come processo in background che registra eventuali violazioni delle regole in un elenco di regole di errore. Il `vserver export-policy config-checker` I comandi richiamano il controllo e visualizzano i risultati, che è possibile utilizzare per verificare la configurazione ed eliminare le regole errate dal criterio.i comandi convalidano solo la configurazione di esportazione per i nomi host, i netgroup e gli utenti anonimi.

====