---
permalink: system-admin/access-system-console-node-task.html 
sidebar: sidebar 
keywords: access, system, console, node, serial, ssh, sp, boot 
summary: 'Se un nodo si trova nel menu di boot o nel prompt dell"ambiente di boot, è possibile accedervi solo dalla console di sistema (chiamata anche console seriale). È possibile accedere alla console di sistema di un nodo da una connessione SSH all"SP del nodo o al cluster.' 
---
= Accedere alla console di sistema di un nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se un nodo si trova nel menu di boot o nel prompt dell'ambiente di boot, è possibile accedervi solo dalla console di sistema (chiamata anche _console seriale_). È possibile accedere alla console di sistema di un nodo da una connessione SSH all'SP del nodo o al cluster.

.A proposito di questa attività
Sia SP che ONTAP offrono comandi che consentono di accedere alla console di sistema. Tuttavia, dal provider di servizi Internet, è possibile accedere solo alla console di sistema del proprio nodo. Dal cluster, è possibile accedere alla console di sistema di qualsiasi nodo del cluster.

.Fasi
. Accedere alla console di sistema di un nodo:
+
|===
| Se si è in... | Immettere questo comando... 


 a| 
CLI SP del nodo
 a| 
`system console`



 a| 
CLI ONTAP
 a| 
`system node run-console`

|===
. Quando richiesto, accedere alla console di sistema.
. Per uscire dalla console di sistema, premere Ctrl-D.


.Esempi di accesso alla console di sistema
Nell'esempio riportato di seguito viene illustrato il risultato dell'immissione di `system console` Al prompt "`SP node2`". La console di sistema indica che node2 è in sospeso al prompt dell'ambiente di boot. Il `boot_ontap` Il comando viene immesso nella console per avviare il nodo su ONTAP. Premere Ctrl-D per uscire dalla console e tornare all'SP.

[listing]
----
SP node2> system console
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
Premere Ctrl-D per uscire dalla console di sistema.

[listing]
----

Connection to 123.12.123.12 closed.
SP node2>
----
Nell'esempio riportato di seguito viene illustrato il risultato dell'immissione di `system node run-console` Comando da ONTAP per accedere alla console di sistema di node2, che si trova al prompt dell'ambiente di boot. Il `boot_ontap` Il comando viene immesso nella console per avviare node2 in ONTAP. Premere Ctrl-D per uscire dalla console e tornare a ONTAP.

[listing]
----
cluster1::> system node run-console -node node2
Pressing Ctrl-D will end this session and any further sessions you might open on top of this session.
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
Premere Ctrl-D per uscire dalla console di sistema.

[listing]
----

Connection to 123.12.123.12 closed.
cluster1::>
----