---
permalink: system-admin/access-cluster-rsh-task.html 
sidebar: sidebar 
keywords: access, cluster, rsh, cluster, administrative, task, secure, protocol, service, policy, lif, firewall, role 
summary: È possibile inviare richieste RSH al cluster per eseguire attività amministrative. RSH non è un protocollo sicuro ed è disattivato per impostazione predefinita. 
---
= Accedere a un cluster ONTAP utilizzando le richieste RSH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile inviare richieste RSH al cluster per eseguire attività amministrative. RSH non è un protocollo sicuro ed è disattivato per impostazione predefinita.

Telnet e RSH non sono protocolli sicuri; è consigliabile utilizzare SSH per accedere al cluster. SSH offre una shell remota sicura e una sessione di rete interattiva. Per ulteriori informazioni, fare riferimento a link:./access-cluster-ssh-task.html["Accedere al cluster utilizzando SSH"].

.Prima di iniziare
Prima di poter utilizzare RSH per accedere al cluster, è necessario soddisfare le seguenti condizioni:

* È necessario disporre di un account utente locale del cluster configurato per utilizzare RSH come metodo di accesso.
+
Il `-application` parametro dei `security login` comandi specifica il metodo di accesso per un account utente. Ulteriori informazioni su `security login` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Riferimento al comando ONTAP"^].



.A proposito di questa attività
* ONTAP supporta un massimo di 50 sessioni RSH simultanee per nodo.
+
Se la LIF di gestione del cluster risiede nel nodo, condivide questo limite con la LIF di gestione del nodo.

+
Se la velocità delle connessioni in entrata è superiore a 10 al secondo, il servizio viene temporaneamente disattivato per 60 secondi.

* I comandi RSH richiedono privilegi avanzati.


[role="tabbed-block"]
====
.ONTAP 9.10.1 o versione successiva
--
.Fasi
. Verificare che il protocollo di protezione RSH sia attivato:
+
`security protocol show`

+
.. Se il protocollo di protezione RSH è attivato, passare alla fase successiva.
.. Se il protocollo di protezione RSH non è attivato, utilizzare il comando seguente per attivarlo:
+
`security protocol modify -application rsh -enabled true`



. Confermare l' `management-rsh-server` esistenza del servizio nelle LIF di gestione:
+
`network interface show -services management-rsh-server`

+
.. Se il `management-rsh-server` servizio è presente, passare alla fase successiva.
.. Se il `management-rsh-server` servizio non esiste, utilizzare il seguente comando per aggiungerlo:
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-rsh-server`





--
.ONTAP 9.9 o versioni precedenti
--
.Prima di iniziare
Prima di poter utilizzare RSH per accedere al cluster, è necessario soddisfare le seguenti condizioni:

* RSH deve essere già abilitato nella policy del firewall di gestione utilizzata dalle LIF di gestione del cluster o dei nodi, in modo che le richieste RSH possano passare attraverso il firewall.
+
Per impostazione predefinita, RSH è disattivato. Il criterio firewall dei servizi di sistema mostra il comando con il `-service rsh` parametro visualizza se RSH è stato attivato in un criterio firewall. Ulteriori informazioni su `system services firewall policy` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+firewall+policy["Riferimento al comando ONTAP"^].

* Se si utilizzano connessioni IPv6, IPv6 deve essere già configurato e abilitato sul cluster e i criteri firewall devono essere già configurati con gli indirizzi IPv6.
+
Il `network options ipv6 show` comando visualizza se IPv6 è abilitato. Il `system services firewall policy show` comando visualizza i criteri del firewall.



.Fasi
. Da un host di amministrazione, immettere il seguente comando:
+
`rsh hostname_or_IP -l username:passwordcommand`

+
`hostname_or_IP` È il nome dell'host o l'indirizzo IP della LIF di gestione cluster o di una LIF di gestione nodi. Si consiglia di utilizzare la LIF di gestione del cluster. È possibile utilizzare un indirizzo IPv4 o IPv6.

+
`command` È il comando che si desidera eseguire su RSH.



--
====
.Esempio di richiesta RSH
L'esempio seguente mostra come l'utente "`joe`", che è stato configurato con accesso RSH, può emettere una richiesta RSH per eseguire `cluster show` comando:

[listing]
----

admin_host$ rsh 10.72.137.28 -l joe:password cluster show

Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
2 entries were displayed.

admin_host$
----
Ulteriori informazioni su `cluster show` nella link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Riferimento al comando ONTAP"^].
