---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disable, default 
summary: È possibile inviare richieste Telnet al cluster per eseguire attività amministrative. Telnet è disattivato per impostazione predefinita. 
---
= Accedere a un cluster ONTAP utilizzando le richieste Telnet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile inviare richieste Telnet al cluster per eseguire attività amministrative. Telnet è disattivato per impostazione predefinita.

Telnet e RSH non sono protocolli sicuri; è consigliabile utilizzare SSH per accedere al cluster. SSH offre una shell remota sicura e una sessione di rete interattiva. Per ulteriori informazioni, fare riferimento a link:./access-cluster-ssh-task.html["Accedere al cluster utilizzando SSH"].

.Prima di iniziare
Prima di poter utilizzare Telnet per accedere al cluster, è necessario soddisfare le seguenti condizioni:

* È necessario disporre di un account utente locale del cluster configurato per utilizzare Telnet come metodo di accesso.
+
Il `-application` parametro dei `security login` comandi specifica il metodo di accesso per un account utente. Ulteriori informazioni su `security login` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Riferimento al comando ONTAP"^].



.A proposito di questa attività
* ONTAP supporta un massimo di 50 sessioni Telnet simultanee per nodo.
+
Se la LIF di gestione del cluster risiede nel nodo, condivide questo limite con la LIF di gestione del nodo.

+
Se la velocità delle connessioni in entrata è superiore a 10 al secondo, il servizio viene temporaneamente disattivato per 60 secondi.

* Se si desidera accedere all'interfaccia utente di ONTAP da un host Windows, è possibile utilizzare un'utility di terze parti, ad esempio putty.
* I comandi RSH richiedono privilegi avanzati.


[role="tabbed-block"]
====
.ONTAP 9.10.1 o versione successiva
--
.Fasi
. Verificare che il protocollo di protezione Telnet sia attivato:
+
`security protocol show`

+
.. Se il protocollo di protezione Telnet è attivato, passare alla fase successiva.
.. Se il protocollo di protezione Telnet non è attivato, utilizzare il comando seguente per attivarlo:
+
`security protocol modify -application telnet -enabled true`



. Confermare l' `management-telnet-server` esistenza del servizio nelle LIF di gestione:
+
`network interface show -services management-telnet-server`

+
.. Se il `management-telnet-server` servizio è presente, passare alla fase successiva.
.. Se il `management-telnet-server` servizio non esiste, utilizzare il seguente comando per aggiungerlo:
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`





--
.ONTAP 9.9 o versioni precedenti
--
.Prima di iniziare
Prima di poter utilizzare Telnet per accedere al cluster, è necessario soddisfare le seguenti condizioni:

* Telnet deve essere già attivato nel criterio del firewall di gestione utilizzato dalle LIF di gestione del cluster o dei nodi, in modo che le richieste Telnet possano passare attraverso il firewall.
+
Per impostazione predefinita, Telnet è disattivato. Il `system services firewall policy show` comando con il `-service telnet` parametro indica se Telnet è stato attivato in un criterio firewall. Ulteriori informazioni su `system services firewall policy` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+firewall+policy["Riferimento al comando ONTAP"^].

* Se si utilizzano connessioni IPv6, IPv6 deve essere già configurato e abilitato sul cluster e i criteri firewall devono essere già configurati con gli indirizzi IPv6.
+
Il `network options ipv6 show` comando visualizza se IPv6 è abilitato. Il `system services firewall policy show` comando visualizza i criteri del firewall.



.Fasi
. Da un host di amministrazione, immettere il seguente comando:
+
`telnet hostname_or_IP`

+
`hostname_or_IP` È il nome dell'host o l'indirizzo IP della LIF di gestione cluster o di una LIF di gestione nodi. Si consiglia di utilizzare la LIF di gestione del cluster. È possibile utilizzare un indirizzo IPv4 o IPv6.



--
====
.Esempio di richiesta Telnet
Nell'esempio seguente viene illustrato in che modo l'utente "joe", che è stato configurato con l'accesso Telnet, può inviare una richiesta Telnet per accedere a un cluster la cui LIF di gestione cluster è 10.72.137.28:

[listing]
----

admin_host$ telnet 10.72.137.28

Data ONTAP
login: joe
Password:

cluster1::>

----