---
permalink: system-admin/acces-ssp-bmc-administration-host-task.html 
sidebar: sidebar 
keywords: access, sp, bmc, administration, host, node, management 
summary: 'È possibile accedere all"SP di un nodo da un host di amministrazione per eseguire attività di gestione dei nodi in remoto.' 
---
= Accedere a SP/BMC da un host di amministrazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile accedere all'SP di un nodo da un host di amministrazione per eseguire attività di gestione dei nodi in remoto.

.Di cosa hai bisogno
Devono essere soddisfatte le seguenti condizioni:

* L'host di amministrazione utilizzato per accedere al SP deve supportare SSHv2.
* L'account utente deve essere già configurato per accedere al SP.
+
Per accedere al SP, l'account utente deve essere stato creato con `-application` del parametro `security login create` comando impostato su `service-processor` e a. `-authmethod` parametro impostato su `password`.



[NOTE]
====
Questa attività si applica sia all'SP che al BMC.

====
Se l'SP è configurato per utilizzare un indirizzo IPv4 o IPv6 e se cinque tentativi di accesso SSH da un host falliscono consecutivamente entro 10 minuti, l'SP rifiuta le richieste di accesso SSH e sospende la comunicazione con l'indirizzo IP dell'host per 15 minuti. La comunicazione riprende dopo 15 minuti ed è possibile tentare di nuovo di accedere all'SP.

ONTAP impedisce di creare o utilizzare nomi riservati al sistema (come "`root`" e "`naroot`") per accedere al cluster o al SP.

.Fasi
. Dall'host di amministrazione, accedere all'SP:
+
`*ssh username@SP_IP_address*`

. Quando richiesto, immettere la password per `username`.
+
Viene visualizzato il prompt SP, che indica che si dispone dell'accesso alla CLI SP.



.Esempi di accesso SP da un host di amministrazione
Nell'esempio seguente viene illustrato come accedere al SP con un account utente `joe`, Che è stato configurato per accedere al SP.

[listing]
----
[admin_host]$ ssh joe@192.168.123.98
joe@192.168.123.98's password:
SP>
----
Gli esempi seguenti mostrano come utilizzare l'indirizzo globale IPv6 o l'indirizzo pubblicizzato dal router IPv6 per accedere all'SP su un nodo con SSH impostato per IPv6 e l'SP configurato per IPv6.

[listing]
----
[admin_host]$ ssh joe@fd22:8b1e:b255:202::1234
joe@fd22:8b1e:b255:202::1234's password:
SP>
----
[listing]
----
[admin_host]$ ssh joe@fd22:8b1e:b255:202:2a0:98ff:fe01:7d5b
joe@fd22:8b1e:b255:202:2a0:98ff:fe01:7d5b's password:
SP>
----