---
permalink: system-admin/access-man-pages-concept.html 
sidebar: sidebar 
keywords: method, access, ontap, man, pages, command, line 
summary: 'Le pagine del manuale ONTAP (man) spiegano come utilizzare i comandi ONTAP. Sono disponibili nella riga di comando e sul sito di supporto NetApp.' 
---
= Metodi di accesso alle pagine man di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le pagine man (manual) di ONTAP spiegano come utilizzare i comandi CLI di ONTAP. Queste pagine sono disponibili nella riga di comando e sono pubblicate anche nei _riferimenti ai comandi_ specifici della release.

Nella riga di comando ONTAP, utilizzare `man _command_name_` per visualizzare la pagina manuale del comando specificato. Se non si specifica un nome di comando, viene visualizzato l'indice della pagina manuale. È possibile utilizzare `man man` per visualizzare informazioni su `man` comando stesso. È possibile uscire da una pagina man immettendo `*q*`.

Ulteriori informazioni sui comandi ONTAP a livello di amministratore e avanzato disponibili nella versione in uso nella link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].
