---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disbale, default 
summary: È possibile inviare richieste Telnet al cluster per eseguire attività amministrative. Telnet è disattivato per impostazione predefinita. 
---
= Accedere al cluster utilizzando Telnet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile inviare richieste Telnet al cluster per eseguire attività amministrative. Telnet è disattivato per impostazione predefinita.

.Di cosa hai bisogno
Prima di poter utilizzare Telnet per accedere al cluster, è necessario soddisfare le seguenti condizioni:

* È necessario disporre di un account utente locale del cluster configurato per utilizzare Telnet come metodo di accesso.
+
Il `-application` del parametro `security login` commands specifica il metodo di accesso per un account utente. Per ulteriori informazioni, consultare `security login` pagine man.



.A proposito di questa attività
* Telnet non è un protocollo sicuro.
+
Si consiglia di utilizzare SSH per accedere al cluster. SSH offre una shell remota sicura e una sessione di rete interattiva.

* ONTAP supporta un massimo di 50 sessioni Telnet simultanee per nodo.
+
Se la LIF di gestione del cluster risiede nel nodo, condivide questo limite con la LIF di gestione del nodo.

+
Se la velocità delle connessioni in entrata è superiore a 10 al secondo, il servizio viene temporaneamente disattivato per 60 secondi.

* Se si desidera accedere all'interfaccia utente di ONTAP da un host Windows, è possibile utilizzare un'utility di terze parti, ad esempio putty.
* I comandi RSH richiedono privilegi avanzati.


.Fasi
. Verificare che il protocollo di protezione Telnet sia attivato:
+
`security protocol show`

+
.. Se il protocollo di protezione Telnet è attivato, passare alla fase successiva.
.. Se il protocollo di protezione Telnet non è attivato, utilizzare il comando seguente per attivarlo:
+
`security protocol modify -application telnet -enabled true`



. Confermare l' `management-telnet-server` esistenza del servizio nelle LIF di gestione:
+
`network interface show -services management-telnet-server`

+
.. Se il `management-telnet-server` servizio è presente, passare alla fase successiva.
.. Se il `management-telnet-server` servizio non esiste, utilizzare il seguente comando per aggiungerlo:
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`





.Esempio di richiesta Telnet
L'esempio seguente mostra come l'utente "`joe`", configurato con accesso Telnet, può inviare una richiesta Telnet per accedere a un cluster la cui LIF di gestione del cluster è 10.72.137.28:

[listing]
----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----