---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: 'Quando provi ad accedere alla SP, ti viene richiesto di inserire le credenziali. Gli account utente del cluster creati con il tipo di applicazione service-processor hanno accesso alla CLI della SP su qualsiasi nodo del cluster. Gli account utente della SP sono gestiti da ONTAP e autenticati tramite password. A partire da ONTAP 9.15.1, gli account utente della SP possono opzionalmente utilizzare l"autenticazione a due fattori con una chiave pubblica come secondo metodo di autenticazione. A partire da ONTAP 9.9.1, gli account utente della SP devono avere il ruolo admin.' 
---
= Accedere al Service Processor di ONTAP utilizzando un account utente cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando provi ad accedere alla SP, ti viene richiesto di inserire le credenziali. Gli account utente del cluster creati con il tipo di applicazione  `service-processor` hanno accesso alla CLI della SP su qualsiasi nodo del cluster. Gli account utente della SP sono gestiti da ONTAP e autenticati tramite password. A partire da ONTAP 9.15.1, gli account utente della SP possono opzionalmente usare l'autenticazione a due fattori con una chiave pubblica come secondo metodo di autenticazione. A partire da ONTAP 9.9.1, gli account utente della SP devono avere il ruolo  `admin`.

Gli account utente per l'accesso allo SP vengono gestiti da ONTAP invece che dalla CLI dello SP. Un account utente del cluster può accedere allo SP se viene creato con il parametro  `-application` del comando  `security login create` impostato su  `service-processor` e il parametro  `-authmethod` impostato su  `password`. A partire da ONTAP 9.15.1, puoi configurare facoltativamente l'autenticazione a due fattori per un account SP impostando il secondo metodo di autenticazione su  `publickey` con il comando  `security login modify` e poi associando la chiave pubblica con il comando  `security login publickey create`.

Specificare `-role` Parametro durante la creazione di un account utente SP.

* In ONTAP 9.9.1 e versioni successive, è necessario specificare `admin` per `-role` e qualsiasi modifica apportata a un account richiede `admin` ruolo. Altri ruoli non sono più consentiti per motivi di sicurezza.
+
** Se si esegue l'aggiornamento a ONTAP 9.9.1 o versioni successive, vedere link:../upgrade/sp-user-accounts-change-concept.html["Modifica degli account utente che possono accedere al Service Processor"].
** Se si torna a ONTAP 9.8 o versioni precedenti, vedere link:../revert/verify-sp-user-accounts-task.html["Verificare gli account utente che possono accedere al Service Processor"].


* In ONTAP 9.8 e versioni precedenti, qualsiasi ruolo può accedere al SP, ma `admin` è consigliato.


Per impostazione predefinita, l'account utente del cluster "`admin`" include `service-processor` Tipo di applicazione e ha accesso al SP.

ONTAP impedisce di creare account utente con nomi riservati al sistema (ad esempio "`root`" e "`naroot`"). Non è possibile utilizzare un nome riservato al sistema per accedere al cluster o al SP.

È possibile visualizzare gli account utente SP correnti utilizzando `-application service-processor` del parametro `security login show` comando.

Scopri di più su link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html[`security login modify`^], link:https://docs.netapp.com/us-en/ontap-cli/security-login-publickey-create.html[`security login publickey create`^] e link:https://docs.netapp.com/us-en/ontap-cli/security-login-show.html[`security login show`^] nel riferimento ai comandi ONTAP.
