---
permalink: system-admin/autosupport-severity-types-concept.html 
sidebar: sidebar 
keywords: autosupport, severity, types, message 
summary: 'I messaggi AutoSupport presentano tipi di severità che consentono di comprendere lo scopo di ciascun messaggio, ad esempio per attirare l"attenzione immediata su un problema di emergenza o solo per fornire informazioni.' 
---
= Informazioni sui tipi di gravità di ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi AutoSupport hanno tipi di severità che aiutano a comprendere lo scopo di ciascun messaggio, ad esempio per attirare l'attenzione immediata su un problema di emergenza o solo per fornire informazioni.

I messaggi hanno una delle seguenti severità:

* *Alert*: I messaggi di avviso indicano che potrebbe verificarsi un evento di livello superiore se non si esegue alcuna azione.
+
È necessario intraprendere un'azione contro i messaggi di avviso entro 24 ore.

* *Emergenza*: I messaggi di emergenza vengono visualizzati quando si verifica un'interruzione.
+
È necessario intraprendere immediatamente un'azione contro i messaggi di emergenza.

* *Error*: Le condizioni di errore indicano cosa potrebbe accadere se si ignora.
* *Avviso*: Condizione normale ma significativa.
* *Info*: Il messaggio informativo fornisce dettagli sul problema, che è possibile ignorare.
* *Debug*: I messaggi a livello di debug forniscono le istruzioni da eseguire.


Se l'organizzazione di supporto interna riceve messaggi AutoSupport tramite e-mail, la severità viene visualizzata nella riga dell'oggetto del messaggio.
