---
permalink: system-admin/autosupport-active-iq-digital-advisor-concept.html 
sidebar: sidebar 
keywords: autosupport, active iq, digital advisor, active, iq, digital, advisor, telemetry, artificial, intelligence 
summary: 'Il componente AutoSupport di ONTAP raccoglie la telemetria e la invia per l"analisi. Digital Advisor analizza i dati di AutoSupport e offre attenzione e ottimizzazione proattive. Utilizzando l"intelligenza artificiale, il Digital Advisor può identificare i potenziali problemi e aiutarti a risolverli prima che abbiano un impatto sul tuo business.' 
---
= Informazioni su Digital Advisor e AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il componente AutoSupport di ONTAP raccoglie la telemetria e la invia per l'analisi. Digital Advisor analizza i dati di AutoSupport e offre attenzione e ottimizzazione proattive. Utilizzando l'intelligenza artificiale, il Digital Advisor può identificare i potenziali problemi e aiutarti a risolverli prima che abbiano un impatto sul tuo business.

Digital Advisor ti consente di ottimizzare la tua infrastruttura dati nel tuo cloud ibrido globale offrendo analisi predittive e supporto proattivo attraverso un portale basato sul cloud e un'app mobile. Le informazioni e i consigli basati sui dati di Digital Advisor sono disponibili per tutti i clienti NetApp con un contratto SupportEdge attivo (le funzionalità variano in base al prodotto e al Tier di supporto).

Ecco alcune cose che potete fare con Digital Advisor:

* Pianificare gli aggiornamenti. Digital Advisor identifica i problemi dell'ambiente che possono essere risolti effettuando l'aggiornamento a una versione più recente di ONTAP, mentre il componente Upgrade Advisor consente di pianificare un aggiornamento di successo.
* Visualizza lo stato di salute del sistema. Il dashboard di Digital Advisor segnala eventuali problemi relativi al funzionamento e ti aiuta a risolverli. Monitorare la capacità del sistema per assicurarsi di non esaurire mai lo spazio di storage. Visualizza i casi di supporto per il tuo sistema.
* Gestire le performance. Digital Advisor mostra le prestazioni del sistema per un periodo più lungo di quello che è possibile vedere in System Manager. Identificare i problemi di configurazione e di sistema che influiscono sulle performance.
* Massimizza l'efficienza. Visualizza le metriche di efficienza dello storage e identifica i modi per memorizzare più dati in meno spazio.
* Visualizza l'inventario e la configurazione. Digital Advisor visualizza l'inventario completo e le informazioni sulla configurazione di software e hardware. Controlla quando i contratti di servizio stanno per scadere e rinnovarli per assicurarti di rimanere supportati.


.Informazioni correlate
https://docs.netapp.com/us-en/active-iq/["Documentazione NetApp: Consulente digitale"^]

https://aiq.netapp.com/custom-dashboard/search["Avviare Digital Advisor"^]

https://www.netapp.com/us/services/support-edge.aspx["Servizi SupportEdge"^]
