---
permalink: system-admin/bmc-cli-commands-reference.html 
sidebar: sidebar 
keywords: bmc, command, cli, log, ssh 
summary: È possibile accedere al BMC utilizzando SSH. I seguenti comandi sono supportati dalla riga di comando BMC. 
---
= Comandi CLI supportati per il controller di gestione della scheda di base ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile accedere al BMC utilizzando SSH. I seguenti comandi sono supportati dalla riga di comando BMC.

|===
| Comando | Funzione 


 a| 
sistema
 a| 
Visualizza un elenco di tutti i comandi.



 a| 
console di sistema
 a| 
Connettersi alla console del sistema. Utilizzare `Ctrl+D` per uscire dalla sessione.



 a| 
core di sistema
 a| 
Eseguire il dump del core di sistema e ripristinarlo.



 a| 
spegnere e riaccendere il sistema
 a| 
Spegnere e riaccendere il sistema.



 a| 
spegnimento del sistema
 a| 
Spegnere il sistema.



 a| 
accensione del sistema
 a| 
Accendere il sistema.



 a| 
stato di alimentazione del sistema
 a| 
Stampare lo stato di alimentazione del sistema.



 a| 
ripristino del sistema
 a| 
Ripristinare il sistema.



 a| 
log di sistema
 a| 
Stampare i registri della console del sistema



 a| 
fru di sistema mostra [id]
 a| 
Scarica tutte le informazioni FRU (Field Replaceable Unit) selezionate.

|===