---
permalink: system-admin/boot-ontap-at-boot-environment-prompt-task.html 
sidebar: sidebar 
keywords: boot, ontap, environment, prompt, current, release, node 
summary: 'È possibile avviare la release corrente o la release di backup di ONTAP quando si è al prompt dell"ambiente di boot di un nodo.' 
---
= Boot ONTAP al prompt dell'ambiente di boot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile avviare la release corrente o la release di backup di ONTAP quando si è al prompt dell'ambiente di boot di un nodo.

.Fasi
. Accedere al prompt dell'ambiente di boot dal prompt del sistema di storage utilizzando `system node halt` comando.
+
La console del sistema di storage visualizza il prompt dell'ambiente di boot.

. Al prompt dell'ambiente di boot, immettere uno dei seguenti comandi:
+
|===
| Per avviare... | Inserisci... 


 a| 
L'attuale release di ONTAP
 a| 
`boot_ontap`



 a| 
L'immagine principale di ONTAP dal dispositivo di avvio
 a| 
`boot_primary`



 a| 
Immagine di backup di ONTAP dal dispositivo di avvio
 a| 
`boot_backup`

|===
+
In caso di dubbi sull'immagine da utilizzare, è necessario utilizzarla `boot_ontap` in primo luogo.


