---
permalink: system-admin/cluster-management-server-concept.html 
sidebar: sidebar 
keywords: cluster, management, server, adminsvm, svm, single, entity 
summary: 'Il server di gestione del cluster, chiamato anche adminSVM, è un"implementazione SVM (Storage Virtual Machine) specializzata che presenta il cluster come una singola entità gestibile. Oltre a fungere da dominio amministrativo di livello più elevato, il server di gestione del cluster possiede risorse che non appartengono logicamente a una SVM di dati.' 
---
= Che cos'è il server di gestione del cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il server di gestione del cluster, chiamato anche __admin__SVM, è un'implementazione SVM (Storage Virtual Machine) specializzata che presenta il cluster come una singola entità gestibile. Oltre a fungere da dominio amministrativo di livello più elevato, il server di gestione del cluster possiede risorse che non appartengono logicamente a una SVM di dati.

Il server di gestione del cluster è sempre disponibile sul cluster. È possibile accedere al server di gestione del cluster tramite la console o la LIF di gestione del cluster.

In caso di guasto della porta della rete domestica, la LIF di gestione del cluster esegue automaticamente il failover su un altro nodo del cluster. A seconda delle caratteristiche di connettività del protocollo di gestione in uso, il failover potrebbe essere notato o meno. Se si utilizza un protocollo senza connessione (ad esempio, SNMP) o si dispone di una connessione limitata (ad esempio HTTP), non si noterà il failover. Tuttavia, se si utilizza una connessione a lungo termine (ad esempio SSH), sarà necessario riconnettersi al server di gestione del cluster dopo il failover.

Quando si crea un cluster, vengono configurate tutte le caratteristiche della LIF di gestione del cluster, inclusi l'indirizzo IP, la netmask, il gateway e la porta.

A differenza di un SVM di dati o di un SVM di nodo, un server di gestione del cluster non dispone di un volume root o di volumi utente host (anche se può ospitare volumi di sistema). Inoltre, un server di gestione del cluster può avere solo LIF del tipo di gestione del cluster.

Se si esegue `vserver show` il server di gestione del cluster viene visualizzato nell'elenco di output del comando.
