---
permalink: system-admin/commands-manage-autosupport-reference.html 
sidebar: sidebar 
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information 
summary: I comandi AutoSupport del nodo di sistema consentono di modificare o visualizzare la configurazione AutoSupport, visualizzare informazioni sui messaggi AutoSupport precedenti e inviare, inviare di nuovo o annullare un messaggio AutoSupport. 
---
= Comandi per la gestione di AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utilizza `system node autosupport` Comandi per modificare o visualizzare la configurazione AutoSupport, visualizzare le informazioni sui messaggi AutoSupport precedenti e inviare, reinviare o annullare un messaggio AutoSupport.



== Configurare AutoSupport

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Controlla se vengono inviati messaggi AutoSupport
 a| 
`system node autosupport modify` con `-state` parametro



 a| 
Controlla se i messaggi AutoSupport vengono inviati al supporto tecnico
 a| 
`system node autosupport modify` con `-support` parametro



 a| 
Impostare AutoSupport o modificare la configurazione di AutoSupport
 a| 
`system node autosupport modify`



 a| 
Abilitare e disabilitare i messaggi AutoSupport per i singoli eventi di attivazione e specificare report aggiuntivi del sottosistema da includere nei messaggi inviati in risposta ai singoli eventi di attivazione
 a| 
`system node autosupport trigger modify`

|===


== Visualizza le informazioni sulla configurazione AutoSupport

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizzare la configurazione AutoSupport
 a| 
`system node autosupport show` con `-node` parametro



 a| 
Visualizza un riepilogo di tutti gli indirizzi e gli URL che ricevono messaggi AutoSupport
 a| 
`system node autosupport destinations show`



 a| 
Visualizza i messaggi AutoSupport inviati all'organizzazione di supporto interna per singoli eventi di attivazione
 a| 
`system node autosupport trigger show`



 a| 
Visualizza lo stato della configurazione AutoSupport e l'invio a varie destinazioni
 a| 
`system node autosupport check show`



 a| 
Visualizza lo stato dettagliato della configurazione AutoSupport e la consegna a varie destinazioni
 a| 
`system node autosupport check show-details`

|===


== Visualizza le informazioni sui messaggi AutoSupport precedenti

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza informazioni su uno o più dei 50 messaggi AutoSupport più recenti
 a| 
`system node autosupport history show`



 a| 
Visualizza le informazioni sui messaggi AutoSupport recenti generati per caricare i file core dump o di archivio delle performance sul sito di supporto tecnico o su un URI specificato
 a| 
`system node autosupport history show-upload-details`



 a| 
Consente di visualizzare le informazioni contenute nei messaggi AutoSupport, inclusi il nome e le dimensioni di ciascun file raccolto per il messaggio e gli eventuali errori
 a| 
`system node autosupport manifest show`

|===


== Inviare, inviare nuovamente o annullare i messaggi AutoSupport

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Ritrasmettere un messaggio AutoSupport memorizzato localmente, identificato dal numero di sequenza AutoSupport

[NOTE]
====
Se si ritrasmette un messaggio AutoSupport e se il supporto ha già ricevuto tale messaggio, il sistema di supporto non crea un caso duplicato. Se, d'altra parte, il supporto non ha ricevuto quel messaggio, il sistema AutoSupport analizzerà il messaggio e, se necessario, creerà un caso.

==== a| 
`system node autosupport history retransmit`



 a| 
Generare e inviare un messaggio AutoSupport, ad esempio a scopo di test
 a| 
`system node autosupport invoke`

[NOTE]
====
Utilizzare `-force` Parametro per inviare un messaggio anche se AutoSupport è disattivato. Utilizzare `-uri` parametro per inviare il messaggio alla destinazione specificata al posto della destinazione configurata.

====


 a| 
Consente di annullare un messaggio AutoSupport
 a| 
`system node autosupport history cancel`

|===
.Informazioni correlate
link:../concepts/manual-pages.html["Riferimento al comando ONTAP"]
