---
permalink: system-admin/commands-manage-feature-licenses-reference.html 
sidebar: sidebar 
keywords: command, manage, license, command, cluster, system, feature, usage, usage 
summary: 'I comandi di licenza di sistema consentono di gestire le licenze delle funzioni per il cluster. I comandi di utilizzo delle funzioni di sistema consentono di monitorare l"utilizzo delle funzioni.' 
---
= Comandi per la gestione delle licenze
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utilizza `system license` comandi per gestire le licenze delle funzioni per il cluster. Si utilizza `system feature-usage` comandi per monitorare l'utilizzo delle funzioni.

[cols="2,4"]
|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Aggiungere una o più licenze
 a| 
`system license add`

.Esempi
Nell'esempio seguente viene aggiunto al cluster un elenco di licenze con le chiavi AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

[]
====
Cluster1::> licenza di sistema, codice di licenza aggiuntivo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

====
Nell'esempio seguente vengono installati i file di licenza dal nodo locale "/mroot/etc/lic_file":

[]
====
cluster1::> licenza di sistema add -use-license-file true

====


 a| 
Visualizzare le informazioni sulle licenze installate, ad esempio:

* Nome e descrizione del pacchetto di licenza
* Tipo di licenza (`site`, `license`, o. `demo`)
* Data di scadenza, se applicabile
* Il cluster o i nodi per i quali viene concesso in licenza un pacchetto
* Se la licenza è stata installata prima di Data ONTAP 8.2 (`legacy`)
* ID cliente

 a| 
`system license show`

[NOTE]
====
Alcune informazioni vengono visualizzate solo quando si utilizza `–instance` parametro.

====


 a| 
Visualizzare tutti i pacchetti che richiedono licenze e il relativo stato di licenza corrente, inclusi i seguenti:

* Il nome del pacchetto
* Il metodo concesso in licenza
* La data di scadenza, se applicabile

 a| 
`system license show-status`

.Esempio
Nell'esempio seguente viene visualizzato lo stato della licenza del cluster:

[]
====
cluster1::> show-status della licenza di sistema
Licenza Status Scopo Stato dettagliato
-------- --------------------------------------- -------- ---------------------------------------------
parzialmente installato
          CIFS nodo Licenza mancante su: Node2-Cluster1.
          SnapRestore nodo Licenza mancante su: Node2-Cluster1.
valido
          FCP nodo -
          FabricPool Cluster il sistema utilizza 1 TB e può utilizzare fino a 25 TB.
non installato
          NFS - -
          ISCSI - -
          SnapMirror - -
          FlexClone - -
          SnapVault - -
          SnapLock - -
          SnapManagerSuite - -
          SnapProtectApps - -
          V_StorageAttach - -
          Insight_Balance - -
          OCShift - -
          TPM - -
          VE - -
          DP_ottimizzato - -
non applicabile
          Cloud - -
          Selezionare - -
sono state visualizzate 20 voci.

====


 a| 
Eliminare la licenza di un pacchetto dal cluster o da un nodo il cui numero seriale è stato specificato
 a| 
`system license delete`

.Esempi
Nell'esempio riportato di seguito viene eliminata una licenza denominata CIFS e il numero di serie 1-81-0000000000000000000123456 dal cluster:

[]
====
Cluster1::> system License delete -serial-number 1-81-0000000000000000000123456 -package CIFS

====
Nell'esempio riportato di seguito vengono eliminate dal cluster tutte le licenze sotto il Core Bundle con licenza installata per il numero di serie 123456789:

[]
====
Cluster1::> eliminazione della licenza di sistema { -numero di serie 123456789 -licenza installata "Core Bundle" }

====


 a| 
Visualizzare o rimuovere le licenze scadute o inutilizzate
 a| 
`system license clean-up`

.Esempi
Nell'esempio seguente vengono simulate e visualizzate le licenze che è possibile eliminare:

[]
====
cluster-1::> clean-up della licenza di sistema -expired -unused

Le seguenti licenze sono state eliminate in modo sicuro:

Numero di serie: 1-80-000011
Proprietario: Cdancluster-1
Pacchetto Motivo
--------------------------------------------------- -----------------------------------------------------------------------------------
CIFS Licenza scaduta

Numero di serie: 4067154888
Proprietario: Nessuno
Pacchetto Motivo
--------------------------------------------------- -----------------------------------------------------------------------------------
Cloud Licenza scaduta

Numero di serie: 1-81-0000000000000004067154999
Proprietario: Nessuno
Pacchetto Motivo
--------------------------------------------------- -----------------------------------------------------------------------------------
ISCSI Licenza non utilizzata da qualsiasi nodo del cluster
Le seguenti licenze sono scadute o inutilizzate ma non possono essere eliminate in modo sicuro:

Numero di serie: 4067154778
Proprietario: Node1
Pacchetto Motivo
--------------------------------------------------- -----------------------------------------------------------------------------------
Cloud La funzione potrebbe essere compromessa in seguito alla rimozione

Numero di serie: 4067154779
Proprietario: Node2
Pacchetto Motivo
--------------------------------------------------- -----------------------------------------------------------------------------------
Cloud Licenza generata dal sistema

====


 a| 
Visualizza il riepilogo dell'utilizzo delle funzionalità nel cluster in base al nodo
 a| 
`system feature-usage show-summary`



 a| 
Visualizzazione dello stato di utilizzo delle funzioni nel cluster per nodo e per settimana
 a| 
`system feature-usage show-history`



 a| 
Visualizzare lo stato del rischio di licenza per ciascun pacchetto di licenza
 a| 
`system license entitlement-risk show`

[NOTE]
====
Alcune informazioni vengono visualizzate solo quando si utilizza `-detail` e. `-instance` parametri.

====
|===
.Informazioni correlate
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^]

https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview["Articolo della Knowledge base: Panoramica sulle licenze di ONTAP 9.10.1 e versioni successive"^]

https://docs.netapp.com/us-en/ontap/task_admin_enable_new_features.html["Utilizzare Gestione sistema per installare un file di licenza NetApp"^]
