---
permalink: system-admin/commands-manage-config-backup-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, configuration, backup, schedule, settings 
summary: È possibile utilizzare i comandi delle impostazioni di backup della configurazione del sistema per gestire le pianificazioni di backup della configurazione. 
---
= Comandi per la gestione delle pianificazioni di backup della configurazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `system configuration backup settings` comandi per gestire le pianificazioni di backup della configurazione.

Questi comandi sono disponibili a livello di privilegio avanzato.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Modificare le impostazioni per una pianificazione di backup della configurazione:

* Specificare un URL remoto (HTTP, HTTPS, FTP, FTPS o TFTP ) in cui verranno caricati i file di backup della configurazione oltre alle posizioni predefinite nel cluster
* Specificare un nome utente da utilizzare per accedere all'URL remoto
* Impostare il numero di backup da conservare per ogni pianificazione di backup della configurazione

 a| 
`system configuration backup settings modify`

Quando si utilizza HTTPS nell'URL remoto, utilizzare `-validate-certification` opzione per attivare o disattivare la convalida digitale del certificato. La convalida del certificato è disattivata per impostazione predefinita.

[NOTE]
====
Il server Web su cui si sta caricando il file di backup della configurazione deve avere ATTIVATO le operazioni HTTP e POST per HTTPS. Per ulteriori informazioni, consultare la documentazione del server Web.

====


 a| 
Impostare la password da utilizzare per accedere all'URL remoto
 a| 
`system configuration backup settings set-password`



 a| 
Visualizzare le impostazioni per la pianificazione del backup della configurazione
 a| 
`system configuration backup settings show`

[NOTE]
====
Impostare `-instance` parametro per visualizzare il nome utente e il numero di backup da conservare per ciascuna pianificazione.

====
|===