---
permalink: system-admin/commands-manage-sp-from-ontap-reference.html 
sidebar: sidebar 
keywords: command, manage, sp, ontap, network, configuration, firmware, image, ssh 
summary: 'ONTAP fornisce comandi per la gestione dell"SP, tra cui la configurazione della rete SP, l"immagine del firmware SP, l"accesso SSH all"SP e l"amministrazione generale dell"SP.' 
---
= Comandi per la gestione dell'SP da ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP fornisce comandi per la gestione dell'SP, tra cui la configurazione della rete SP, l'immagine del firmware SP, l'accesso SSH all'SP e l'amministrazione generale dell'SP.



== Comandi per la gestione della configurazione di rete SP

|===
| Se si desidera... | Eseguire questo comando ONTAP... 


 a| 
Abilitare la configurazione di rete automatica SP per l'SP per utilizzare la famiglia di indirizzi IPv4 o IPv6 della subnet specificata
 a| 
`system service-processor network auto-configuration enable`



 a| 
Disattiva la configurazione di rete automatica SP per la famiglia di indirizzi IPv4 o IPv6 della subnet specificata per l'SP
 a| 
`system service-processor network auto-configuration disable`



 a| 
Visualizza la configurazione di rete automatica SP
 a| 
`system service-processor network auto-configuration show`



 a| 
Configurare manualmente la rete SP per un nodo, tra cui:

* La famiglia di indirizzi IP (IPv4 o IPv6)
* Se attivare l'interfaccia di rete della famiglia di indirizzi IP specificata
* Se si utilizza IPv4, specificare se utilizzare la configurazione di rete dal server DHCP o l'indirizzo di rete specificato
* L'indirizzo IP pubblico per l'SP
* La netmask per l'SP (se si utilizza IPv4)
* La lunghezza del prefisso di rete della subnet mask per l'SP (se si utilizza IPv6)
* L'indirizzo IP del gateway per l'SP

 a| 
`system service-processor network modify`



 a| 
Visualizzare la configurazione di rete SP, tra cui:

* La famiglia di indirizzi configurata (IPv4 o IPv6) e se è attivata
* Il tipo di dispositivo di gestione remota
* Lo stato SP corrente e lo stato del collegamento
* Configurazione di rete, ad esempio indirizzo IP, indirizzo MAC, netmask, lunghezza prefisso della subnet mask, indirizzo IP assegnato dal router, indirizzo IP locale di collegamento e indirizzo IP del gateway
* L'ora dell'ultimo aggiornamento del SP
* Il nome della subnet utilizzata per la configurazione automatica SP
* Se l'indirizzo IP assegnato dal router IPv6 è attivato
* Stato di setup della rete SP
* Motivo dell'errore di configurazione della rete SP

 a| 
`system service-processor network show`

La visualizzazione dei dettagli completi della rete SP richiede `-instance` parametro.



 a| 
Modificare la configurazione del servizio API SP, includendo quanto segue:

* Modifica della porta utilizzata dal servizio API SP
* Attivazione o disattivazione del servizio API SP

 a| 
`system service-processor api-service modify`

(livello di privilegio avanzato)



 a| 
Visualizzare la configurazione del servizio API SP
 a| 
`system service-processor api-service show`

(livello di privilegio avanzato)



 a| 
Rinnovare i certificati SSL e SSH utilizzati dal servizio API SP per la comunicazione interna
 a| 
* Per ONTAP 9.5 o versioni successive: `system service-processor api-service renew-internal-certificates`
* Per ONTAP 9.4 o versioni precedenti: `system service-processor api-service renew-certificates`
+
(livello di privilegio avanzato)



|===


== Comandi per la gestione dell'immagine del firmware SP

|===
| Se si desidera... | Eseguire questo comando ONTAP... 


 a| 
Visualizza i dettagli dell'immagine del firmware SP attualmente installata, tra cui:

* Il tipo di dispositivo di gestione remota
* L'immagine (principale o di backup) da cui viene avviato il SP, il suo stato e la versione del firmware
* Se l'aggiornamento automatico del firmware è attivato e lo stato dell'ultimo aggiornamento

 a| 
`system service-processor image show`

Il `-is-current` Parametro indica l'immagine (primaria o di backup) da cui è attualmente avviato il SP, non se la versione del firmware installata è più recente.



 a| 
Attiva o disattiva l'aggiornamento automatico del firmware SP
 a| 
`system service-processor image modify`

Per impostazione predefinita, il firmware SP viene aggiornato automaticamente con l'aggiornamento di ONTAP o quando viene scaricata manualmente una nuova versione del firmware SP. La disattivazione dell'aggiornamento automatico non è consigliata, in quanto può causare combinazioni non ottimali o non qualificate tra l'immagine ONTAP e l'immagine del firmware SP.



 a| 
Scaricare manualmente un'immagine del firmware SP su un nodo
 a| 
`system node image get`

[NOTE]
====
Prima di eseguire `system node image` è necessario impostare il livello di privilegio su advanced (avanzato) (`set -privilege advanced`), immettendo *y* quando viene richiesto di continuare.

====
L'immagine del firmware SP viene fornita con ONTAP. Non è necessario scaricare manualmente il firmware SP, a meno che non si desideri utilizzare una versione del firmware SP diversa da quella fornita con ONTAP.



 a| 
Visualizza lo stato dell'ultimo aggiornamento del firmware SP attivato da ONTAP, incluse le seguenti informazioni:

* L'ora di inizio e di fine dell'ultimo aggiornamento del firmware SP
* Se è in corso un aggiornamento e la percentuale di completamento

 a| 
`system service-processor image update-progress show`

|===


== Comandi per la gestione dell'accesso SSH al SP

|===
| Se si desidera... | Eseguire questo comando ONTAP... 


 a| 
Concedere l'accesso SP solo agli indirizzi IP specificati
 a| 
`system service-processor ssh add-allowed-addresses`



 a| 
Impedisce agli indirizzi IP specificati di accedere al SP
 a| 
`system service-processor ssh remove-allowed-addresses`



 a| 
Visualizza gli indirizzi IP che possono accedere all'SP
 a| 
`system service-processor ssh show`

|===


== Comandi per l'amministrazione SP generale

|===
| Se si desidera... | Eseguire questo comando ONTAP... 


 a| 
Visualizza informazioni generali sull'SP, tra cui:

* Il tipo di dispositivo di gestione remota
* Lo stato SP corrente
* Se la rete SP è configurata
* Informazioni di rete, ad esempio l'indirizzo IP pubblico e l'indirizzo MAC
* La versione del firmware SP e la versione dell'interfaccia di gestione della piattaforma intelligente (IPMI)
* Se l'aggiornamento automatico del firmware SP è attivato

 a| 
`system service-processor show` La visualizzazione delle informazioni SP complete richiede `-instance` parametro.



 a| 
Riavviare il SP su un nodo
 a| 
`system service-processor reboot-sp`



 a| 
Generare e inviare un messaggio AutoSupport che includa i file di log SP raccolti da un nodo specificato
 a| 
`system node autosupport invoke-splog`



 a| 
Visualizzare la mappa di allocazione dei file di log SP raccolti nel cluster, inclusi i numeri di sequenza dei file di log SP che risiedono in ciascun nodo di raccolta
 a| 
`system service-processor log show-allocations`

|===
.Informazioni correlate
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^]
