---
permalink: system-admin/commands-manage-audit-settings-reference.html 
sidebar: sidebar 
keywords: command, manage, audit, settings, management, activity 
summary: I comandi di audit della sicurezza consentono di gestire le attività di gestione registrate nel file audit.log. I comandi di inoltro dei log del cluster consentono di gestire le destinazioni a cui inoltrare il log di controllo. 
---
= Comandi per la gestione delle impostazioni di audit per le attività di gestione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utilizza `security audit` comandi per gestire le attività di gestione registrate in `audit.log` file. Si utilizza `cluster log-forwarding` comandi per gestire le destinazioni a cui inoltrare il registro di controllo.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Specificare che le richieste GET dall'interfaccia utente o dalle API ONTAP devono essere registrate nel registro di controllo (il `audit.log` file), oltre alle richieste di set predefinite
 a| 
`security audit modify`



 a| 
Visualizzare le impostazioni del registro di controllo
 a| 
`security audit show`



 a| 
Visualizza le voci di audit unite da più nodi nel cluster
 a| 
`security audit log show`



 a| 
Specificare una destinazione di inoltro per il registro di controllo e le misure di sicurezza per la trasmissione
 a| 
`cluster log-forwarding create`



 a| 
Modificare una destinazione per il registro di controllo
 a| 
`cluster log-forwarding modify`



 a| 
Eliminare una destinazione per il registro di controllo
 a| 
`cluster log-forwarding delete`



 a| 
Mostra le destinazioni configurate per il registro di controllo
 a| 
`cluster log-forwarding show`

|===
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+log-forwarding["inoltro dei log del cluster"^]

