---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: 'È possibile utilizzare i comandi di stato del sistema per visualizzare informazioni sullo stato delle risorse del sistema, rispondere agli avvisi e configurare gli avvisi futuri. L"utilizzo dei comandi CLI consente di visualizzare informazioni dettagliate sulla configurazione del monitoraggio dello stato di salute. Le pagine man dei comandi contengono ulteriori informazioni.' 
---
= Comandi per il monitoraggio dello stato di salute del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i `system health` comandi per visualizzare informazioni sullo stato delle risorse di sistema, per rispondere agli avvisi e per configurare avvisi futuri. L'utilizzo dei comandi CLI consente di visualizzare informazioni dettagliate sulla configurazione del monitoraggio dello stato di salute. Ulteriori informazioni su `system health` nella link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+health["Riferimento al comando ONTAP"^].



== Visualizza lo stato dello stato di salute del sistema

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza lo stato di salute del sistema, che riflette lo stato generale dei singoli monitor di salute
 a| 
`system health status show`



 a| 
Visualizza lo stato di salute dei sottosistemi per i quali è disponibile il monitoraggio dello stato di salute
 a| 
`system health subsystem show`

|===


== Visualizza lo stato della connettività del nodo

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza dettagli sulla connettività dal nodo allo shelf di storage, tra cui informazioni sulle porte, velocità della porta HBA, throughput i/o e velocità delle operazioni di i/o al secondo
 a| 
`storage shelf show -connectivity`

Utilizzare `-instance` parametro per visualizzare informazioni dettagliate su ogni shelf.



 a| 
Visualizza informazioni su dischi e LUN di array, inclusi lo spazio utilizzabile, i numeri di shelf e alloggiamenti e il nome del nodo proprietario
 a| 
`storage disk show`

Utilizzare `-instance` per visualizzare informazioni dettagliate su ciascun disco.



 a| 
Visualizza informazioni dettagliate sulle porte dello shelf storage, tra cui tipo di porta, velocità e stato
 a| 
`storage port show`

Utilizzare `-instance` parametro per visualizzare informazioni dettagliate su ciascun adattatore.

|===


== Gestire il rilevamento di switch di rete per cluster, storage e gestione

[cols="3*"]
|===
| Se si desidera... | Utilizzare questo comando. (ONTAP 9.8 e versioni successive) | Utilizzare questo comando. (ONTAP 9.7 e versioni precedenti) 


 a| 
Visualizza gli switch che il cluster monitora
 a| 
`system switch ethernet show`
 a| 
`system cluster-switch show`



 a| 
Visualizzare gli switch attualmente monitorati dal cluster, inclusi gli switch cancellati (visualizzati nella colonna Reason (motivo) nell'output del comando) e le informazioni di configurazione necessarie per l'accesso di rete al cluster e agli switch di rete di gestione.

Questo comando è disponibile a livello di privilegio avanzato.
 a| 
`system switch ethernet show-all`
 a| 
`system cluster-switch show-all`



 a| 
Configurare il rilevamento di uno switch non rilevato
 a| 
`system switch ethernet create`
 a| 
`system cluster-switch create`



 a| 
Modificare le informazioni relative a uno switch che il cluster monitora (ad esempio, nome del dispositivo, indirizzo IP, versione SNMP e stringa di comunità)
 a| 
`system switch ethernet modify`
 a| 
`system cluster-switch modify`



 a| 
Disattiva il monitoraggio di uno switch
 a| 
`system switch ethernet modify -disable-monitoring`
 a| 
`system cluster-switch modify -disable-monitoring`



 a| 
Disattivare il rilevamento e il monitoraggio di uno switch ed eliminare le informazioni di configurazione dello switch
 a| 
`system switch ethernet delete`
 a| 
`system cluster-switch delete`



 a| 
Rimuovere in modo permanente le informazioni di configurazione dello switch memorizzate nel database (in questo modo si riattiva il rilevamento automatico dello switch)
 a| 
`system switch ethernet delete -force`
 a| 
`system cluster-switch delete -force`



 a| 
Abilitare la registrazione automatica per l'invio con messaggi AutoSupport.
 a| 
`system switch ethernet log`
 a| 
`system cluster-switch log`

|===


== Rispondere agli avvisi generati

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza le informazioni sugli avvisi generati, ad esempio la risorsa e il nodo in cui è stato attivato l'avviso, la gravità e la probabile causa dell'avviso
 a| 
`system health alert show`



 a| 
Visualizza le informazioni relative a ciascun avviso generato
 a| 
`system health alert show -instance`



 a| 
Indica che qualcuno sta lavorando a un avviso
 a| 
`system health alert modify`



 a| 
Riconoscere un avviso
 a| 
`system health alert modify -acknowledge`



 a| 
Eliminare un avviso successivo in modo che non influisca sullo stato di salute di un sottosistema
 a| 
`system health alert modify -suppress`



 a| 
Eliminare un avviso non cancellato automaticamente
 a| 
`system health alert delete`



 a| 
Visualizza le informazioni sui messaggi AutoSupport attivati nell'ultima settimana, ad esempio per determinare se un avviso ha attivato un messaggio AutoSupport
 a| 
`system health autosupport trigger history show`

|===


== Configurare gli avvisi futuri

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Attivare o disattivare il criterio che controlla se uno stato di risorsa specifico genera un avviso specifico
 a| 
`system health policy definition modify`

|===


== Visualizza informazioni sulla configurazione del monitoraggio dello stato di salute

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizzare informazioni sui monitor di stato, ad esempio nodi, nomi, sottosistemi e stato
 a| 
`system health config show`

[NOTE]
====
Utilizzare `-instance` parametro per visualizzare informazioni dettagliate su ciascun monitor di salute.

====


 a| 
Visualizza informazioni sugli avvisi potenzialmente generati da un monitor dello stato di salute
 a| 
`system health alert definition show`

[NOTE]
====
Utilizzare `-instance` parametro per visualizzare informazioni dettagliate su ciascuna definizione di avviso.

====


 a| 
Visualizza informazioni sui criteri di monitoraggio dello stato di salute, che determinano quando vengono generati gli avvisi
 a| 
`system health policy definition show`

[NOTE]
====
Utilizzare `-instance` parametro per visualizzare informazioni dettagliate su ogni policy. Utilizzare altri parametri per filtrare l'elenco degli avvisi, ad esempio in base allo stato della policy (attivato o meno), al monitor dello stato di salute, agli avvisi e così via.

====
|===