---
permalink: system-admin/commands-manage-system-time-reference.html 
sidebar: sidebar 
keywords: command, manage, cluster, time, ntp, server, date, ntp, time, manually 
summary: 'Per gestire i server NTP del cluster, utilizzare i comandi del server ntp del servizio di gestione del tempo del cluster. I comandi di data del cluster consentono di gestire manualmente l"ora del cluster.' 
---
= Comandi per la gestione del tempo del cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utilizza `cluster time-service ntp server` Comandi per gestire i server NTP per il cluster. Si utilizza `cluster date` comandi per gestire manualmente l'ora del cluster.

A partire da ONTAP 9.5, è possibile configurare il server NTP con autenticazione simmetrica.

I seguenti comandi consentono di gestire i server NTP per il cluster:

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Associare il cluster a un server NTP esterno senza autenticazione simmetrica
 a| 
`cluster time-service ntp server create -server server_name`



 a| 
Associare il cluster a un server NTP esterno con autenticazione simmetrica disponibile in ONTAP 9.5 o versione successiva
 a| 
`cluster time-service ntp server create -server server_ip_address -key-id key_id`

[NOTE]
====
Il `key_id` deve fare riferimento a una chiave condivisa esistente configurata con '`chiave ntp cluster time-service'.

====


 a| 
Abilitare l'autenticazione simmetrica per un server NTP esistente. È possibile modificare il server NTP esistente per abilitare l'autenticazione aggiungendo l'ID chiave richiesto.

Disponibile in ONTAP 9.5 o versione successiva
 a| 
`cluster time-service ntp server modify -server server_name -key-id key_id`



 a| 
Disattiva autenticazione simmetrica
 a| 
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`



 a| 
Configurare una chiave NTP condivisa
 a| 
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`

[NOTE]
====
Le chiavi condivise sono indicate da un ID. L'ID, il tipo e il valore devono essere identici sia sul nodo che sul server NTP

====


 a| 
Visualizza le informazioni sui server NTP associati al cluster
 a| 
`cluster time-service ntp server show`



 a| 
Modificare la configurazione di un server NTP esterno associato al cluster
 a| 
`cluster time-service ntp server modify`



 a| 
Dissocare un server NTP dal cluster
 a| 
`cluster time-service ntp server delete`



 a| 
Ripristinare la configurazione annullando l'associazione di tutti i server NTP esterni al cluster
 a| 
`cluster time-service ntp server reset`

[NOTE]
====
Questo comando richiede il livello di privilegio avanzato.

====
|===
I seguenti comandi consentono di gestire manualmente l'ora del cluster:

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Impostare o modificare il fuso orario, la data e l'ora
 a| 
`cluster date modify`



 a| 
Visualizza le impostazioni relative a fuso orario, data e ora del cluster
 a| 
`cluster date show`

|===
.Informazioni correlate
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^]
