---
permalink: system-admin/commands-manage-node-remotely-reference.html 
sidebar: sidebar 
keywords: command, manage, node, remotely, sp, cli, cluster 
summary: È possibile gestire un nodo in remoto accedendo al relativo SP ed eseguendo comandi SP CLI per eseguire attività di gestione dei nodi. Per diverse attività di gestione remota dei nodi eseguite di frequente, è possibile utilizzare i comandi ONTAP da un altro nodo del cluster. Alcuni comandi SP sono specifici della piattaforma e potrebbero non essere disponibili sulla piattaforma. 
---
= Comandi ONTAP per la gestione remota dei nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire in remoto attività di gestione dei nodi accedendo al relativo SP ed eseguendo i comandi CLI SP oppure accedendo al BMC ed eseguendo i comandi CLI BMC .  Per diverse attività di gestione dei nodi remoti comunemente eseguite, è anche possibile utilizzare i comandi ONTAP da un altro nodo nel cluster.  Alcuni comandi SP e BMC sono specifici della piattaforma e potrebbero non essere disponibili sulla tua piattaforma.

Alcuni tipi di comando possono essere utilizzati sia nei set di comandi SP che BMC .  Le differenze tra loro verranno mostrate quando si accede alla riga di comando.

.Esempi
* IL `help` comando in SP: `SP> help`
* IL `help` comando in BMC: `BMC> help`


Scopri di più su `help` opzioni di comando disponibili per SP e BMC inlink:https://docs.netapp.com/us-en/ontap/system-admin/online-help-at-sp-bmc-cli-task.html["Visualizzare le informazioni della guida nell'interfaccia CLI di ONTAP SP/BMC"^] .

Scopri di più sulla corrispondente ONTAP BMC CLI inlink:https://docs.netapp.com/us-en/ontap/system-admin/bmc-cli-commands-reference.html["Comandi CLI supportati per il controller di gestione della scheda di base ONTAP"^] .

|===
| Se si desidera... | Utilizza questo comando SP... | Utilizza questo comando BMC... | Utilizzare questo comando ONTAP ... 


 a| 
Visualizza i comandi o sottocomandi disponibili di un comando specificato per SP/ BMC/ ONTAP
 a| 
`help` [`command`]
 a| 
`help` [`command`]
 a| 
N/A.



 a| 
Visualizza il livello di privilegio corrente per la CLI SP/ BMC/ ONTAP
 a| 
`priv show`
 a| 
`priv` `show`
 a| 
N/A.



 a| 
Imposta il livello di privilegio per accedere alla modalità specificata per la CLI SP/ BMC/ ONTAP
 a| 
`priv set`

{`admin`| `advanced` | `diag` }
 a| 
`priv set`

{`admin`| `advanced` | `diag` | `test` }
 a| 
N/A.



 a| 
Visualizzare la data e l'ora del sistema
 a| 
`date`
 a| 
`date`
 a| 
`date`



 a| 
Visualizza gli eventi registrati da SP/ BMC/ ONTAP
 a| 
`events`

{`all`| `info` | `newest` `number` | `oldest number` | `search keyword` }
 a| 
`events`

{`all`| `info` | `newest` | `oldest` | `search` }
 a| 
N/A.



 a| 
Visualizza lo stato SP/ BMC/ ONTAP e le informazioni sulla configurazione di rete
 a| 
`sp status`

[`-v`| `-d` ]

* IL `-v` l'opzione visualizza le statistiche SP in forma dettagliata.
* IL `-d` l'opzione aggiunge il registro di debug SP alla visualizzazione.

 a| 
`bmc status`

[`-v`| `-d` ]

* IL `-v` l'opzione visualizza le statistiche SP in forma dettagliata.
* IL `-d` l'opzione aggiunge il registro di debug SP alla visualizzazione.

 a| 
`system service-processor show`



 a| 
Visualizza la durata di attività di SP/ BMC/ ONTAP e il numero medio di processi nella coda di esecuzione negli ultimi 1, 5 e 15 minuti
 a| 
`sp uptime`
 a| 
`bmc uptime`
 a| 
N/A.



 a| 
Visualizzare i log della console di sistema
 a| 
`system log`
 a| 
`system log`

[`-a`]
 a| 
`system log`

(stampa i registri della console di sistema)



 a| 
Visualizza gli archivi di log SP/ BMC/ ONTAP o i file in un archivio
 a| 
`sp log history show`

[`-archive` {`latest`|{`all` | `archive-name` }][`-dump` {`all` | `file-name` }]
 a| 
`bmc log history show`

[`-archive` {`latest`|{`all` | `archive-name` }][`-dump` {`all` | `file-name` }]
 a| 
N/A.



 a| 
Visualizza lo stato di alimentazione del controller di un nodo
 a| 
`system power status`
 a| 
`system power status`
 a| 
`system node power show`



 a| 
Visualizza le informazioni sulla batteria
 a| 
`system battery show`
 a| 
`system battery show`
 a| 
N/A.



 a| 
Visualizza le informazioni ACP o lo stato dei sensori di espansione
 a| 
`system acp`

[`show`| `sensors show` ]
 a| 
N/A.
 a| 
N/A.



 a| 
Elencare tutte le FRU del sistema e i relativi ID
 a| 
`system fru list`
 a| 
`system fru list`
 a| 
N/A.



 a| 
Visualizzare le informazioni sul prodotto per la FRU specificata
 a| 
`system fru show` `fru_id`
 a| 
`system fru show`

[ `show <id>` ]
 a| 
N/A.



 a| 
Visualizzare il registro della cronologia dei dati FRU
 a| 
`system fru log show`

(livello di privilegio avanzato)
 a| 
`system fru log show`
 a| 
N/A.



 a| 
Visualizzare lo stato dei sensori ambientali, inclusi i relativi stati e valori correnti
 a| 
`system sensors`

oppure

`system sensors show`
 a| 
`system sensors`

{`show`| `filter <sensor_string>` }
 a| 
`system node environment sensors show`



 a| 
Visualizza lo stato e i dettagli del sensore specificato
 a| 
`system sensors get` `sensor_name`

È possibile ottenere `sensor_name` utilizzando `system sensors` o il `system sensors show` comando.
 a| 
`system sensors`

[ `get` ]
 a| 
N/A.



 a| 
Visualizza le informazioni sulla versione del firmware SP/ BMC/ ONTAP
 a| 
`version`
 a| 
`version`
 a| 
`system service-processor image show`



 a| 
Visualizza la cronologia dei comandi SP/ BMC/ ONTAP
 a| 
`sp log audit`

(livello di privilegio avanzato)
 a| 
`bmc log audit`

(livello di privilegio avanzato)
 a| 
N/A.



 a| 
Visualizza le informazioni di debug SP/ BMC/ ONTAP
 a| 
`sp log debug`

(livello di privilegio avanzato)
 a| 
`bmc log debug`

(livello di privilegio avanzato)
 a| 
N/A.



 a| 
Visualizza il file dei messaggi SP/ BMC/ ONTAP
 a| 
`sp log messages`

(livello di privilegio avanzato)
 a| 
`bmc log messages`

(livello di privilegio avanzato)
 a| 
N/A.



 a| 
Consente di visualizzare le impostazioni per la raccolta di dati forensi del sistema in un evento di ripristino del watchdog, visualizzare le informazioni forensi del sistema raccolte durante un evento di ripristino del watchdog o cancellare le informazioni forensi del sistema raccolte
 a| 
`system forensics`

[`show`| `log dump` | `log clear` ]
 a| 
N/A.
 a| 
N/A.



 a| 
Accedere alla console di sistema
 a| 
`system console`
 a| 
`system console`
 a| 
`system node run-console`



 a| 
Premere Ctrl-D per uscire dalla sessione della console di sistema.



 a| 
Accendere o spegnere il nodo oppure eseguire un ciclo di alimentazione (spegnendo e riaccendendo l'alimentazione)
 a| 
`system power` `on`
 a| 
`system power` `on`
 a| 
`system node power on`

(livello di privilegio avanzato)



 a| 
`system power` `off`
 a| 
`system power` `off`
 a| 
N/A.



 a| 
`system power` `cycle`
 a| 
`system power` `cycle`
 a| 
N/A.



 a| 
L'alimentazione in standby rimane attiva per mantenere l'SP in funzione senza interruzioni. Durante il ciclo di alimentazione, si verifica una breve pausa prima di riaccendere il prodotto.

[NOTE]
====
L'utilizzo di questi comandi per spegnere o spegnere e riaccendere il nodo potrebbe causare un arresto non corretto del nodo (chiamato anche _shutdown anomalo_) e non può sostituire un arresto corretto mediante ONTAP `system node halt` comando.

====


 a| 
Creare un core dump e ripristinare il nodo
 a| 
`system core` [`-f`]

Il `-f` l'opzione forza la creazione di un core dump e il ripristino del nodo.
 a| 
`system core`
 a| 
`system node coredump trigger`

(livello di privilegio avanzato)



 a| 
Questi comandi hanno lo stesso effetto della pressione del pulsante NMI (non-maskable Interrupt) su un nodo, causando un arresto anomalo del nodo e forzando un dump dei file core quando si arresta il nodo. Questi comandi sono utili quando ONTAP sul nodo è bloccato o non risponde a comandi come `system node shutdown`. I file core dump generati vengono visualizzati nell'output di `system node coredump show` comando. L'SP rimane operativo fino a quando l'alimentazione in ingresso al nodo non viene interrotta.



 a| 
Riavviare il nodo con un'immagine del firmware del BIOS (primaria, di backup o corrente) opzionale per eseguire il ripristino in caso di problemi come un'immagine danneggiata del dispositivo di avvio del nodo
 a| 
`system reset`

{`primary`| `backup` | `current` }
 a| 
`system reset`

{ `current` | `primary` | `backup` }
 a| 
`system node reset`con il `-firmware` {`primary` | `backup` | `current` } parametro

(livello di privilegio avanzato)



 a| 
[NOTE]
====
Questa operazione causa un arresto anomalo del nodo.

====
Se non viene specificata alcuna immagine del firmware del BIOS, l'immagine corrente viene utilizzata per il riavvio. L'SP rimane operativo fino a quando l'alimentazione in ingresso al nodo non viene interrotta.



 a| 
Confrontare l'immagine del firmware corrente della batteria con un'immagine del firmware specificata
 a| 
`system battery verify` [`image_URL`]

(livello di privilegio avanzato)

Se `image_URL` non specificato, viene utilizzata l'immagine del firmware della batteria predefinita per il confronto.
 a| 
`system battery verify` [`image_URL`]

(livello di privilegio avanzato)

Se `image_URL` non specificato, viene utilizzata l'immagine del firmware della batteria predefinita per il confronto.
 a| 
N/A.



 a| 
Aggiornare il firmware della batteria dall'immagine nella posizione specificata
 a| 
`system battery flash` [`image_URL`]

(livello di privilegio avanzato)

Utilizzare questo comando se il processo di aggiornamento automatico del firmware della batteria non è riuscito per qualche motivo.
 a| 
N/A.
 a| 
N/A.



 a| 
Aggiorna il firmware SP/ BMC/ ONTAP utilizzando l'immagine nella posizione specificata
 a| 
`sp update`

`image_URL`

`image_URL`non deve superare i 200 caratteri.
 a| 
`bmc update`

`image_URL`

`image_URL`non deve superare i 200 caratteri.
 a| 
`system service-processor image update`



 a| 
Riavviare SP/ BMC/ ONTAP
 a| 
`sp reboot`
 a| 
`bmc reboot`
 a| 
`system service-processor reboot-sp`



 a| 
Cancellare il contenuto della memoria flash NVRAM
 a| 
`system nvram flash clear`

(livello di privilegio avanzato)

Questo comando non può essere avviato quando il controller è spento (`system power off`).
 a| 
N/A.
 a| 
N/A.



 a| 
Uscire dalla CLI SP/ BMC/ ONTAP
 a| 
`exit`
 a| 
`exit`
 a| 
N/A.

|===
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^]

