---
permalink: system-admin/commands-manage-mount-points-nodes-reference.html 
sidebar: sidebar 
keywords: command, manage, mount, point, nodes, spi, web, service, root, volume, root 
summary: Il servizio Web spi crea automaticamente un punto di montaggio da un nodo al volume root di un altro nodo su richiesta di accesso ai file di log o ai file core del nodo. Sebbene non sia necessario gestire manualmente i punti di montaggio, è possibile farlo utilizzando i comandi root-mount del nodo di sistema. 
---
= Comandi per la gestione dei punti di montaggio sui nodi ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `spi` il servizio web crea automaticamente un punto di montaggio da un nodo al volume root di un altro nodo su richiesta di accesso ai file di log o ai file core del nodo. Sebbene non sia necessario gestire manualmente i punti di montaggio, è possibile farlo utilizzando `system node root-mount` comandi.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Creare manualmente un punto di montaggio da un nodo al volume root di un altro nodo
 a| 
`system node root-mount create` Può esistere un solo punto di montaggio da un nodo all'altro.



 a| 
Visualizzare i punti di montaggio esistenti sui nodi del cluster, incluso l'ora in cui è stato creato un punto di montaggio e il relativo stato corrente
 a| 
`system node root-mount show`



 a| 
Eliminare un punto di montaggio da un nodo al volume root di un altro nodo e forzare la chiusura delle connessioni al punto di montaggio
 a| 
`system node root-mount delete`

|===
.Informazioni correlate
link:../concepts/manual-pages.html["Riferimento al comando ONTAP"]
