---
permalink: system-admin/config-backup-file-concept.html 
sidebar: sidebar 
keywords: configuration, backup, files, archive, files 
summary: 'I file di backup della configurazione sono file di archivio (.7z) che contengono informazioni per tutte le opzioni configurabili necessarie per il corretto funzionamento del cluster e dei nodi al suo interno.' 
---
= Quali sono i file di backup della configurazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I file di backup della configurazione sono file di archivio (.7z) che contengono informazioni per tutte le opzioni configurabili necessarie per il corretto funzionamento del cluster e dei nodi al suo interno.

Questi file memorizzano la configurazione locale di ciascun nodo, oltre alla configurazione replicata a livello di cluster. I file di backup della configurazione vengono utilizzati per eseguire il backup e il ripristino della configurazione del cluster.

Esistono due tipi di file di backup della configurazione:

* *File di backup della configurazione del nodo*
+
Ogni nodo integro nel cluster include un file di backup della configurazione del nodo, che contiene tutte le informazioni di configurazione e i metadati necessari per il funzionamento corretto del nodo nel cluster.

* *File di backup della configurazione del cluster*
+
Questi file includono un archivio di tutti i file di backup della configurazione del nodo nel cluster, oltre alle informazioni di configurazione del cluster replicate (il database replicato o il file RDB). I file di backup della configurazione del cluster consentono di ripristinare la configurazione dell'intero cluster o di qualsiasi nodo del cluster. I programmi di backup della configurazione del cluster creano automaticamente questi file e li memorizzano su diversi nodi del cluster.



[NOTE]
====
I file di backup della configurazione contengono solo informazioni di configurazione. Non includono dati dell'utente. Per informazioni sul ripristino dei dati utente, vedere link:../data-protection/index.html["Protezione dei dati"].

====