---
permalink: system-admin/configure-saml-authentication-task.html 
sidebar: sidebar 
keywords: tdp, ldap, identity, provider, saml, security, assertion, markup, lanaguage, active, directory, disable, authentication, idp, active directory, troubleshoot, repair 
summary: 'A partire da ONTAP 9.3, è possibile configurare l"autenticazione SAML (Security Assertion Markup Language) per i servizi Web. Quando l"autenticazione SAML è configurata e abilitata, gli utenti vengono autenticati da un provider di identità esterno (IdP) invece che dai provider di servizi di directory come Active Directory e LDAP. Quando l"autenticazione SAML è disattivata, i provider di servizi di directory configurati come Active Directory e LDAP vengono utilizzati per l"autenticazione.' 
---
= Configurare l'autenticazione SAML
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.3, è possibile configurare l'autenticazione SAML (Security Assertion Markup Language) per i servizi Web. Quando l'autenticazione SAML è configurata e abilitata, gli utenti vengono autenticati da un provider di identità esterno (IdP) invece che dai provider di servizi di directory come Active Directory e LDAP.

.Di cosa hai bisogno
* È necessario aver configurato IdP per l'autenticazione SAML.
* È necessario disporre dell'URI IdP.


.A proposito di questa attività
* L'autenticazione SAML si applica solo a. `http` e. `ontapi` applicazioni.
+
Il `http` e. `ontapi` Le applicazioni vengono utilizzate dai seguenti servizi Web: Infrastruttura del processore di servizi, API ONTAP o Gestore di sistema.

* L'autenticazione SAML è applicabile solo per l'accesso alla SVM amministrativa.


I seguenti IDP sono stati convalidati con System Manager:

* Servizi di federazione di Active Directory
* Cisco DUO (compatibile con le seguenti versioni di ONTAP:)
+
** 9.7P21 e versioni successive 9,7 (fare riferimento a. https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_setting_up_saml_authentication.html["Documentazione di System Manager Classic"^])
** 9.8P17 e versioni successive 9,8
** 9,9.1P13 e versioni successive 9,9
** 9.10.1P9 e versioni successive 9,10
** 9.11.1P4 e versioni successive 9,11
** 9.12.1 e versioni successive


* Shibboleth


.Fasi
. Creare una configurazione SAML in modo che ONTAP possa accedere ai metadati IdP:
+
`*security saml-sp create -idp-uri _idp_uri_ -sp-host _ontap_host_name_*`

+
`idp_uri` È l'indirizzo FTP o HTTP dell'host IdP da cui è possibile scaricare i metadati IdP.

+
`ontap_host_name` È il nome host o l'indirizzo IP dell'host del provider di servizi SAML, che in questo caso è il sistema ONTAP. Per impostazione predefinita, viene utilizzato l'indirizzo IP della LIF di gestione del cluster.

+
È possibile fornire le informazioni sul certificato del server ONTAP. Per impostazione predefinita, vengono utilizzate le informazioni del certificato del server Web ONTAP.

+
[listing]
----
cluster_12::> security saml-sp create -idp-uri https://scspr0235321001.gdl.englab.netapp.com/idp/shibboleth -verify-metadata-server false

Warning: This restarts the web server. Any HTTP/S connections that are active
         will be disrupted.
Do you want to continue? {y|n}: y
[Job 179] Job succeeded: Access the SAML SP metadata using the URL:
https://10.63.56.150/saml-sp/Metadata

Configure the IdP and Data ONTAP users for the same directory server domain to ensure that users are the same for different authentication methods. See the "security login show" command for the Data ONTAP user configuration.
----
+
Viene visualizzato l'URL per accedere ai metadati dell'host ONTAP.

. Dall'host IdP, configurare IdP con i metadati dell'host ONTAP.
+
Per ulteriori informazioni sulla configurazione di IdP, consultare la documentazione di IdP.

. Abilitare la configurazione SAML:
+
`*security saml-sp modify -is-enabled true*`

+
Qualsiasi utente esistente che accede a. `http` oppure `ontapi` L'applicazione viene configurata automaticamente per l'autenticazione SAML.

. Se si desidera creare utenti per `http` oppure `ontapi` Applicazione dopo aver configurato SAML, specificare SAML come metodo di autenticazione per i nuovi utenti.
+
.. Creare un metodo di accesso per i nuovi utenti con autenticazione SAML: +
`*security login create -user-or-group-name _user_name_ -application [http | ontapi] -authentication-method saml -vserver _svm_name_*`
+
[listing]
----
cluster_12::> security login create -user-or-group-name admin1 -application http -authentication-method saml -vserver  cluster_12
----
.. Verificare che la voce utente sia stata creata:
+
`*security login show*`

+
[listing]
----
cluster_12::> security login show

Vserver: cluster_12
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
admin          console     password      admin            no     none
admin          http        password      admin            no     none
admin          http        saml          admin            -      none
admin          ontapi      password      admin            no     none
admin          ontapi      saml          admin            -      none
admin          service-processor
                           password      admin            no     none
admin          ssh         password      admin            no     none
admin1         http        password      backup           no     none
**admin1       http        saml          backup           -      none**
----






== Disattiva l'autenticazione SAML

È possibile disattivare l'autenticazione SAML quando si desidera interrompere l'autenticazione degli utenti Web utilizzando un provider di identità (IdP) esterno. Quando l'autenticazione SAML è disattivata, i provider di servizi di directory configurati come Active Directory e LDAP vengono utilizzati per l'autenticazione.

.Di cosa hai bisogno
È necessario effettuare l'accesso dalla console.

.Fasi
. Disattiva autenticazione SAML:
+
`*security saml-sp modify -is-enabled false*`

. Se non si desidera più utilizzare l'autenticazione SAML o se si desidera modificare IdP, eliminare la configurazione SAML:
+
`*security saml-sp delete*`





== Risolvere i problemi relativi alla configurazione SAML

Se la configurazione dell'autenticazione SAML (Security Assertion Markup Language) non riesce, è possibile riparare manualmente ogni nodo su cui la configurazione SAML ha avuto esito negativo e ripristinarlo in caso di errore. Durante il processo di riparazione, il server Web viene riavviato e tutte le connessioni HTTP o HTTPS attive vengono interrompute.

.A proposito di questa attività
Quando si configura l'autenticazione SAML, ONTAP applica la configurazione SAML per nodo. Quando si attiva l'autenticazione SAML, ONTAP tenta automaticamente di riparare ogni nodo in caso di problemi di configurazione. In caso di problemi con la configurazione SAML su qualsiasi nodo, è possibile disattivare l'autenticazione SAML e riattivarla. Possono verificarsi situazioni in cui la configurazione SAML non viene applicata a uno o più nodi anche dopo aver riattivato l'autenticazione SAML. È possibile identificare il nodo su cui si è verificato un errore nella configurazione SAML e quindi riparare manualmente tale nodo.

.Fasi
. Accedere al livello di privilegio avanzato:
+
`*set -privilege advanced*`

. Identificare il nodo su cui la configurazione SAML non ha avuto esito positivo:
+
`*security saml-sp status show -instance*`

+
[listing]
----
cluster_12::*> security saml-sp status show -instance

                         Node: node1
                Update Status: config-success
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text:
SAML Service Provider Enabled: false
        ID of SAML Config Job: 179

                         Node: node2
                Update Status: config-failed
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text: SAML job failed, Reason: Internal error. Failed to receive the SAML IDP Metadata file.
SAML Service Provider Enabled: false
        ID of SAML Config Job: 180
2 entries were displayed.
----
. Riparare la configurazione SAML sul nodo guasto:
+
`*security saml-sp repair -node _node_name_*`

+
[listing]
----
cluster_12::*> security saml-sp repair -node node2

Warning: This restarts the web server. Any HTTP/S connections that are active
         will be disrupted.
Do you want to continue? {y|n}: y
[Job 181] Job is running.
[Job 181] Job success.
----
+
Il server Web viene riavviato e tutte le connessioni HTTP o HTTPS attive vengono interrompute.

. Verificare che SAML sia configurato correttamente su tutti i nodi:
+
`*security saml-sp status show -instance*`

+
[listing]
----
cluster_12::*> security saml-sp status show -instance

                         Node: node1
                Update Status: config-success
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text:
SAML Service Provider Enabled: false
        ID of SAML Config Job: 179

                         Node: node2
                Update Status: **config-success**
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text:
SAML Service Provider Enabled: false
        ID of SAML Config Job: 180
2 entries were displayed.
----


.Informazioni correlate
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"^]
