---
permalink: system-admin/control-system-health-alerts-concept.html 
sidebar: sidebar 
keywords: system, health, alert, customization, monitor, enable, disable 
summary: È possibile controllare quali avvisi vengono generati da un monitor dello stato di salute attivando e disattivando le policy di stato del sistema che definiscono quando vengono attivati gli avvisi. Ciò consente di personalizzare il sistema di monitoraggio dello stato di salute per il proprio ambiente specifico. 
---
= Personalizzazione degli avvisi sullo stato di salute del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile controllare quali avvisi vengono generati da un monitor dello stato di salute attivando e disattivando le policy di stato del sistema che definiscono quando vengono attivati gli avvisi. Ciò consente di personalizzare il sistema di monitoraggio dello stato di salute per il proprio ambiente specifico.

È possibile conoscere il nome di un criterio visualizzando informazioni dettagliate su un avviso generato o visualizzando le definizioni dei criteri per uno specifico Health monitor, nodo o ID avviso.

La disattivazione delle policy di integrità è diversa dalla sospensione degli avvisi. La soppressione di un avviso non influisce sullo stato di salute del sottosistema, ma può comunque verificarsi.

Se si disattiva un criterio, la condizione o lo stato definito nell'espressione della regola dei criteri non attiva più un avviso.

.Esempio di avviso che si desidera disattivare
Ad esempio, supponiamo che si verifichi un avviso non utile. Si utilizza `system health alert show –instance` Per ottenere l'ID policy per l'avviso. L'ID del criterio viene utilizzato in `system health policy definition show` per visualizzare le informazioni relative al criterio. Dopo aver esaminato l'espressione della regola e altre informazioni relative al criterio, si decide di disattivarlo. Si utilizza `system health policy definition modify` per disattivare il criterio.
