---
permalink: system-admin/create-motd-task.html 
sidebar: sidebar 
keywords: create, motd, cli, user, clustershell, ssh, session, cluster, access, message, day 
summary: 'È possibile creare un messaggio del giorno (MOTD) per comunicare informazioni agli utenti CLI autenticati. Il MOTD viene visualizzato in una sessione della console (solo per l"accesso al cluster) o in una sessione SSH (per l"accesso al cluster o alla SVM) dopo l"autenticazione di un utente, ma prima della visualizzazione del prompt della shell dei cluster.' 
---
= Creare un messaggio del giorno per gli utenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un messaggio del giorno (MOTD) per comunicare informazioni agli utenti CLI autenticati. Il MOTD viene visualizzato in una sessione della console (solo per l'accesso al cluster) o in una sessione SSH (per l'accesso al cluster o alla SVM) dopo l'autenticazione di un utente, ma prima della visualizzazione del prompt della shell dei cluster.

.Fasi
. Utilizzare `security login motd modify` Comando per creare un MOTD per il cluster o SVM:
+
|===
| Se si desidera... | Quindi... 


 a| 
Specificare un messaggio che sia una singola riga
 a| 
Utilizzare `-message` "[.code]``text``" per specificare il testo.



 a| 
Includi newline (nota anche come fine delle righe)
 a| 
Utilizzare il comando senza `-message` oppure `-uri` Parametro per avviare la modalità interattiva per la modifica del MOTD.



 a| 
Caricare il contenuto da una posizione da utilizzare per il MOTD
 a| 
Utilizzare `-uri` Parametro per specificare la posizione FTP o HTTP del contenuto.

|===
+
La dimensione massima di un MOTD è di 2,048 byte, incluse le newline.

+
`Security login motd modify` Descrive le sequenze di escape che è possibile utilizzare per abilitare MOTD a visualizzare contenuti generati dinamicamente.

+
Un MOTD creato utilizzando `-uri` il parametro è statico. Non viene aggiornato automaticamente per riflettere le modifiche successive del contenuto di origine.

+
Un MOTD creato per il cluster viene visualizzato anche per tutti gli accessi SVM per impostazione predefinita, insieme a un MOTD a livello di SVM che è possibile creare separatamente per un determinato SVM. Impostazione di `-is-cluster-message-enabled` parametro a. `false` Per una SVM impedisce la visualizzazione del MOTD a livello di cluster per tale SVM.

. Verificare che il MOTD sia stato creato visualizzandolo con il `security login motd show` comando.
+
Specificando il  `-message` parametro con una stringa vuota (``) visualizza i MOTD che non sono configurati o non hanno contenuto.

+
Ulteriori informazioni su `security login motd modify` e parametri per consentire a MOTD di visualizzare contenuti generati dinamicamente in link:https://docs.netapp.com/us-en/ontap-cli/security-login-motd-modify.html["Riferimento al comando ONTAP"^].



.Esempi di creazione di MOTD
L'esempio seguente utilizza la modalità non interattiva per creare un MOTD per l'  `cluster1` grappolo:

[listing]
----
cluster1::> security login motd modify -message "Greetings!"
----
L'esempio seguente utilizza la modalità interattiva per creare un MOTD per l'  `svm1` SVM che utilizza sequenze di escape per visualizzare contenuti generati dinamicamente:

[listing]
----
cluster1::> security login motd modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.
----
Nell'esempio seguente vengono visualizzati i MOTD creati:

[listing]
----
cluster1::> security login motd show
Vserver: cluster1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Greetings!

Vserver: svm1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.

2 entries were displayed.
----
Ulteriori informazioni su `security login motd show` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-motd-show.html["Riferimento al comando ONTAP"^].
