---
permalink: system-admin/customize-show-command-output-concept.html 
sidebar: sidebar 
keywords: method, customizing, show, command, output, fields 
summary: 'Quando si utilizza il parametro –instance con un comando show per visualizzare i dettagli, l"output può essere lungo e includere più informazioni di quante ne hai bisogno. Il parametro –fields di un comando show consente di visualizzare solo le informazioni specificate.' 
---
= Metodi di personalizzazione dell'output del comando show utilizzando i campi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si utilizza `–instance` parametro con a. `show` comando per visualizzare i dettagli, l'output può essere lungo e includere più informazioni di quante ne hai bisogno. Il `–fields` parametro di a. `show` il comando consente di visualizzare solo le informazioni specificate.

Ad esempio, in esecuzione `volume show -instance` è probabile che si traducono in diverse schermate di informazioni. È possibile utilizzare `volume show –fields` `_fieldname[,fieldname...]_` per personalizzare l'output in modo che includa solo il campo o i campi specificati (oltre ai campi predefiniti sempre visualizzati). È possibile utilizzare `–fields ?` per visualizzare i campi validi per a. `show` comando.

L'esempio seguente mostra la differenza di output tra `–instance` e il `–fields` parametro:

[listing]
----
cluster1::> volume show -instance

                                   Vserver Name: cluster1-1
                                    Volume Name: vol0
                                 Aggregate Name: aggr0
                                    Volume Size: 348.3GB
                             Volume Data Set ID: -
                      Volume Master Data Set ID: -
                                   Volume State: online
                                    Volume Type: RW
                                   Volume Style: flex
                                         ...
                          Space Guarantee Style: volume
                      Space Guarantee in Effect: true
                                         ...
Press <space> to page down, <return> for next line, or 'q' to quit...
...
cluster1::>

cluster1::> volume show -fields space-guarantee,space-guarantee-enabled

vserver  volume space-guarantee space-guarantee-enabled
-------- ------ --------------- -----------------------
cluster1-1 vol0   volume          true
cluster1-2 vol0   volume          true
vs1      root_vol
                  volume          true
vs2      new_vol
                  volume          true
vs2      root_vol
                  volume          true
...
cluster1::>
----