---
permalink: system-admin/different-shells-cli-commands-concept.html 
sidebar: sidebar 
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell 
summary: Il cluster dispone di tre diverse shell per i comandi CLI, la clustershell, il nodeshell e la shell di sistema. Le shell hanno scopi diversi, ognuno dei quali ha un set di comandi diverso. 
---
= Informazioni sulle diverse shell per i comandi CLI (solo amministratori del cluster)
:allow-uri-read: 


[role="lead"]
Il cluster dispone di tre diverse shell per i comandi CLI, la _clustershell_, la _nodeshell_ e la _systemshell_. Le shell hanno scopi diversi, ognuno dei quali ha un set di comandi diverso.

* La shell clustershell è la shell nativa che viene avviata automaticamente quando si accede al cluster.
+
Fornisce tutti i comandi necessari per configurare e gestire il cluster. La guida in linea della CLI di clustershell (attivata da `?` al prompt di clustershell) visualizza i comandi di clustershell disponibili. Il `man` comando nella shell del cluster visualizza la pagina man per il comando clustershell specificato (`man <command_name>`). Ulteriori informazioni su `man` nella link:https://docs.netapp.com/us-en/ontap-cli/man.html["Riferimento al comando ONTAP"^].

* Il nodeshell è una shell speciale per i comandi che hanno effetto solo a livello di nodo.
+
La nodeshell è accessibile tramite il `system node run` comando. Ulteriori informazioni su `system node run` nella link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["Riferimento al comando ONTAP"^].

+
La guida in linea di nodeshell CLI (attivata da `?` o `help` al prompt nodeshell) visualizza i comandi nodeshell disponibili. Il `man` comando nel nodeshell visualizza la pagina man per il comando nodeshell specificato.

+
Molti comandi e opzioni nodeshell comunemente utilizzati sono tunneled o aliased nella clustershell e possono essere eseguiti anche dalla clustershell.

* Systemshell è una shell di basso livello che viene utilizzata solo per scopi di diagnostica e troubleshooting.
+
La shell di sistema e l'account associato "`diag`" sono destinati a scopi diagnostici di basso livello. Il loro accesso richiede il livello di privilegio diagnostico ed è riservato solo al supporto tecnico per eseguire le attività di risoluzione dei problemi.



Per ulteriori informazioni sui comandi descritti in questa procedura, consultare la link:https://docs.netapp.com/us-en/ontap-cli/["Riferimento al comando ONTAP"^].
