---
permalink: system-admin/display-nodeshell-commands-task.html 
sidebar: sidebar 
keywords: display, nodeshell, command, cli, list, help 
summary: 'Puoi ottenere un elenco dei comandi nodeshell disponibili usando l"aiuto CLI del nodeshell.' 
---
= Visualizza i comandi nodeshell disponibili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi ottenere un elenco dei comandi nodeshell disponibili usando l'aiuto CLI del nodeshell.

.Fasi
. Per accedere al nodeshell, immettere il seguente comando al prompt di sistema della shell:
+
`*system node run -node {_nodename_|local}*`

+
`local` è il nodo utilizzato per accedere al cluster.

+
[NOTE]
====
Il `system node run` il comando dispone di un comando alias, `run`.

====
. Immettere il seguente comando nel nodeshell per visualizzare l'elenco dei comandi nodeshell disponibili:
+
`*[_commandname_] help*`

+
 `_commandname_` è il nome del comando di cui si desidera visualizzare la disponibilità. Se non si include `_commandname_`, La CLI visualizza tutti i comandi nodeshell disponibili.

+
Viene immesso `exit` In alternativa, digitare Ctrl-d per tornare alla CLI della shell cluster.



.Esempio di visualizzazione dei comandi nodeshell disponibili
Nell'esempio seguente viene effettuato l'accesso al nodeshell di un nodo denominato node2 e vengono visualizzate le informazioni relative al comando nodeshell `environment`:

[listing]
----
cluster1::> system node run -node node2
Type 'exit' or 'Ctrl-D' to return to the CLI

node2> environment help
Usage: environment status |
     [status] [shelf [<adapter>[.<shelf-number>]]] |
     [status] [shelf_log] |
     [status] [shelf_stats] |
     [status] [shelf_power_status] |
     [status] [chassis [all | list-sensors | Temperature | PSU 1 |
     PSU 2 | Voltage | SYS FAN | NVRAM6-temperature-3 | NVRAM6-battery-3]]
----