---
permalink: system-admin/display-nodes-cluster-task.html 
sidebar: sidebar 
keywords: display, view, information, node, cluster, name, healthy, epsilon 
summary: È possibile visualizzare i nomi dei nodi, verificare che i nodi siano integri e se sono idonei a partecipare al cluster. A livello di privilegi avanzati, è anche possibile visualizzare se un nodo contiene epsilon. 
---
= Visualizza dettagli a livello di nodo in un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare i nomi dei nodi, se sono integri e se sono idonei a partecipare al cluster. A livello di privilegi avanzati, è anche possibile visualizzare se un nodo contiene epsilon.

.Fasi
. Per visualizzare le informazioni sui nodi di un cluster, utilizzare il `cluster show` comando .
+
Se si desidera che l'output mostri se un nodo contiene epsilon, eseguire il comando al livello di privilegio avanzato.

+
Ulteriori informazioni su `cluster show` nella link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Riferimento al comando ONTAP"^].



.Esempi di visualizzazione dei nodi in un cluster
Nell'esempio seguente vengono visualizzate informazioni su tutti i nodi di un cluster a quattro nodi:

[listing]
----

cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
node3                 true    true
node4                 true    true
----
Nell'esempio seguente vengono visualizzate informazioni dettagliate sul nodo denominato "`node1`" a livello di privilegi avanzati:

[listing]
----

cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> cluster show -node node1

       Node: node1
  Node UUID: a67f9f34-9d8f-11da-b484-000423b6f094
    Epsilon: false
Eligibility: true
     Health: true
----