---
permalink: system-admin/find-config-recover-cluster-task.html 
sidebar: sidebar 
keywords: cluster, configuration, recover, node, backup, file 
summary: La configurazione viene utilizzata da un nodo del cluster o da un file di backup della configurazione del cluster per ripristinare un cluster. 
---
= Individua il file di backup della configurazione del cluster ONTAP per ripristinare un cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configurazione viene utilizzata da un nodo del cluster o da un file di backup della configurazione del cluster per ripristinare un cluster.

.Fasi
. Scegliere un tipo di configurazione per ripristinare il cluster.
+
** Un nodo nel cluster
+
Se il cluster è costituito da più di un nodo e uno di essi ha una configurazione del cluster da quando il cluster si trovava nella configurazione desiderata, è possibile ripristinare il cluster utilizzando la configurazione memorizzata su tale nodo.

+
Nella maggior parte dei casi, il nodo contenente l'anello di replica con l'ID transazione più recente è il nodo migliore da utilizzare per ripristinare la configurazione del cluster. Il `cluster ring show` il comando a livello di privilegio avanzato consente di visualizzare un elenco degli anelli replicati disponibili su ciascun nodo del cluster.

** Un file di backup della configurazione del cluster
+
Se non si riesce a identificare un nodo con la corretta configurazione del cluster o se il cluster è costituito da un singolo nodo, è possibile utilizzare un file di backup della configurazione del cluster per ripristinare il cluster.

+
Se si ripristina il cluster da un file di backup della configurazione, tutte le modifiche alla configurazione apportate dopo l'esecuzione del backup andranno perse. Dopo il ripristino, è necessario risolvere eventuali discrepanze tra il file di backup della configurazione e la configurazione attuale. Vedi illink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_Configuration_Backup_Resolution_Guide["Base di conoscenza NetApp : Guida alla risoluzione del backup della configurazione ONTAP"^] per una guida alla risoluzione dei problemi.



. Se si sceglie di utilizzare un file di backup della configurazione del cluster, rendere il file disponibile per il nodo che si intende utilizzare per ripristinare il cluster.
+
|===
| Se si trova il file di backup della configurazione... | Quindi... 


 a| 
A un URL remoto
 a| 
Utilizzare `system configuration backup download` al livello di privilegio avanzato per scaricarlo nel nodo di ripristino.



 a| 
Su un nodo del cluster
 a| 
.. Utilizzare `system configuration backup show` al livello di privilegio avanzato per trovare un file di backup della configurazione del cluster creato quando il cluster si trovava nella configurazione desiderata.
.. Se il file di backup della configurazione del cluster non si trova nel nodo che si intende utilizzare per ripristinare il cluster, utilizzare `system configuration backup copy` comando per copiarlo nel nodo di ripristino.


|===


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ring-show.html["spettacolo di anelli a grappolo"^]
* link:https://docs.netapp.com/us-en/ontap-cli/system-configuration-backup-copy.html["copia di backup della configurazione del sistema"^]

