---
permalink: system-admin/generate-certificate-signing-request-cluster-task.html 
sidebar: sidebar 
keywords: generate, certificate, sign, request, cluster, csr, ca 
summary: 'È possibile utilizzare il comando generate-csr del certificato di protezione per generare una richiesta di firma del certificato (CSR). Una volta elaborata la richiesta, l"autorità di certificazione (CA) invia il certificato digitale firmato.' 
---
= Generare una richiesta di firma del certificato per il cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il certificato di protezione `generate-csr` Comando per generare una richiesta di firma del certificato (CSR). Una volta elaborata la richiesta, l'autorità di certificazione (CA) invia il certificato digitale firmato.

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster o di SVM.

.Fasi
. Generare una CSR:
+
`*security certificate generate-csr -common-name _FQDN_or_common_name_ -size 512|1024|1536|2048 -country _country_ -state _state_ -locality _locality_ -organization _organization_ -unit _unit_ -email-addr _email_of_contact_ -hash-function SHA1|SHA256|MD5*`

+
Per la sintassi completa dei comandi, vedere le pagine man.

+
Il seguente comando crea una CSR con una chiave privata a 2,048 bit generata dalla funzione di hashing SHA256 per l'utilizzo da parte del gruppo Software nel reparto IT di una società il cui nome comune personalizzato è server1.companyname.com, con sede a Sunnyvale, California, USA. L'indirizzo e-mail dell'amministratore del contatto SVM è web@example.com. Il sistema visualizza la CSR e la chiave privata nell'output.

+
[listing]
----
cluster1::>security certificate generate-csr -common-name
server1.companyname.com -size 2048 -country US -state California -
locality Sunnyvale -organization IT -unit Software -email-addr
web@example.com -hash-function SHA256
Certificate Signing Request :
-----BEGIN CERTIFICATE REQUEST-----
<certificate_value>
-----END CERTIFICATE REQUEST-----
Private Key :
24 | Administrator Authentication and RBAC
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----
Note: Please keep a copy of your certificate request and private key
for future reference.
----
. Copiare la richiesta di certificato dall'output CSR, quindi inviarla in formato elettronico (ad esempio tramite e-mail) a una CA di terze parti attendibile per la firma.
+
Una volta elaborata la richiesta, la CA invia il certificato digitale firmato. Conservare una copia della chiave privata e del certificato digitale firmato dalla CA.


