---
permalink: system-admin/health-alerts-autosupport-messages-events-concept.html 
sidebar: sidebar 
keywords: system, health, alerts, trigger, autosupport, ems, event, management, message, event 
summary: Gli avvisi sullo stato di salute del sistema attivano messaggi ed eventi AutoSupport nel sistema di gestione degli eventi, consentendo di monitorare lo stato di salute del sistema utilizzando messaggi AutoSupport e EMS, oltre a utilizzare direttamente il sistema di monitoraggio dello stato di salute. 
---
= Modalità di attivazione degli avvisi di integrità per i messaggi e gli eventi AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli avvisi sullo stato di salute del sistema attivano messaggi ed eventi AutoSupport nel sistema di gestione degli eventi, consentendo di monitorare lo stato di salute del sistema utilizzando messaggi AutoSupport e EMS, oltre a utilizzare direttamente il sistema di monitoraggio dello stato di salute.

Il sistema invia un messaggio AutoSupport entro cinque minuti da un avviso. Il messaggio AutoSupport include tutti gli avvisi generati dal precedente messaggio AutoSupport, ad eccezione degli avvisi che duplicano un avviso per la stessa risorsa e la causa probabile entro la settimana precedente.

Alcuni avvisi non attivano i messaggi AutoSupport. Un avviso non attiva un messaggio AutoSupport se la relativa policy di integrità disattiva l'invio di messaggi AutoSupport. Ad esempio, per impostazione predefinita, un criterio di integrità potrebbe disattivare i messaggi AutoSupport perché AutoSupport già genera un messaggio quando si verifica il problema. È possibile configurare i criteri per non attivare i messaggi AutoSupport utilizzando `system health policy definition modify` comando.

È possibile visualizzare un elenco di tutti i messaggi AutoSupport attivati dagli avvisi inviati la settimana precedente utilizzando `system health autosupport trigger history show` comando.

Gli avvisi attivano anche la generazione di eventi al sistema EMS. Ogni volta che viene creato un avviso e ogni volta che viene cancellato, viene generato un evento.
