---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: 'Esistono diversi monitor di stato che monitorano diverse parti di un cluster. I monitor di stato consentono di eseguire il ripristino dagli errori all"interno dei sistemi ONTAP rilevando gli eventi, inviando avvisi ed eliminando gli eventi non appena vengono eliminati.' 
---
= Scopri i monitor dello stato di salute del cluster ONTAP disponibili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono diversi monitor di stato che monitorano diverse parti di un cluster. I monitor di stato consentono di eseguire il ripristino dagli errori all'interno dei sistemi ONTAP rilevando gli eventi, inviando avvisi ed eliminando gli eventi non appena vengono eliminati.

|===
| Nome del monitor di stato (identificatore) | Nome del sottosistema (identificatore) | Scopo 


 a| 
Switch Ethernet
 a| 
Switch (stato dello switch)
 a| 
Il monitor stato switch Ethernet ONTAP (CSHM) monitora lo stato degli switch del cluster e della rete di storage durante la raccolta dei registri per l'analisi. Per impostazione predefinita, CSHM esegue il polling di ogni switch tramite SNMPv2c ogni 5 minuti per aggiornare le tabelle delle risorse con informazioni su supportabilità, monitoraggio dello stato, sensori di temperatura, utilizzo della CPU, configurazioni e connessioni dell'interfaccia, ridondanza degli switch del cluster e operazioni delle ventole e dell'alimentatore. Inoltre, se configurato, CSHM raccoglie i log tramite SSH/SCP ogni ora, che vengono inviati tramite AutoSupport per ulteriori analisi. Su richiesta, CSHM può inoltre eseguire una raccolta di log più dettagliata con il supporto tecnico utilizzando SSH/SCP.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["Monitoraggio dello stato degli switch"^] .



 a| 
Fabric MetroCluster
 a| 
Switch
 a| 
Monitora la topologia del fabric back-end di configurazione MetroCluster e rileva configurazioni errate, come cablaggio e zoning errati e errori ISL.



 a| 
Salute di MetroCluster
 a| 
Interconnessione, RAID e storage
 a| 
Monitora adattatori FC-VI, adattatori FC Initiator, aggregati e dischi sinistri e porte tra cluster



 a| 
Connettività del nodo (connessione al nodo)
 a| 
Operazioni CIFS senza interruzioni (CIFS-NDO)
 a| 
Monitora le connessioni SMB per le operazioni senza interruzioni alle applicazioni Hyper-V.



 a| 
Storage (SAS-Connect)
 a| 
Monitora shelf, dischi e adattatori a livello di nodo per verificare la presenza di percorsi e connessioni appropriati.



 a| 
Sistema
 a| 
non applicabile
 a| 
Aggrega le informazioni provenienti da altri monitor dello stato di salute.



 a| 
Connettività del sistema (connessione al sistema)
 a| 
Storage (SAS-Connect)
 a| 
Monitora gli shelf a livello di cluster per rilevare i percorsi appropriati a due nodi in cluster ha.

|===