---
permalink: system-admin/install-ca-signed-client-certificate-kmip-server-task.html 
sidebar: sidebar 
keywords: install, ca, signed, client, certificate, kmip, server, key, management, interoperability, protocol, server 
summary: 'I tipi client e server-ca specificano che il certificato viene utilizzato per l"autenticazione reciproca del cluster e di un gestore di chiavi esterno, come un server KMIP.' 
---
= Installare un certificato client firmato da CA per il server KMIP in ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tipi client e server-ca specificano che il certificato viene utilizzato per l'autenticazione reciproca del cluster e di un gestore di chiavi esterno, come un server KMIP.

.A proposito di questa attività
Installare un certificato per autenticare un server KMIP come server SSL per il cluster.

.Fasi
. Utilizzare il  `security certificate install` comando con il  `-type server-ca` parametro per installare un certificato per il server KMIP.
. Quando richiesto, immettere il certificato, quindi premere Invio.
+
ONTAP ricorda di conservare una copia del certificato per riferimenti futuri.

+
[listing]
----
cluster1::> security certificate install -type server-ca -vserver cluster1

Please enter Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----


You should keep a copy of the CA-signed digital certificate for future reference.

cluster1::>
----


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["installazione del certificato di sicurezza"^]

