---
permalink: system-admin/keyboard-shortcuts-edit-cli-commands-reference.html 
sidebar: sidebar 
keywords: keyboard, shortcuts, edit, cli, commands, unix, tcsh, shell, emacs, editor, active 
summary: 'Il comando al prompt dei comandi corrente è il comando attivo. L"utilizzo dei tasti di scelta rapida consente di modificare rapidamente il comando attivo. Questi tasti di scelta rapida sono simili a quelli della shell UNIX tcsh e dell"editor Emacs.' 
---
= Tasti di scelta rapida per la modifica dei comandi CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il comando al prompt dei comandi corrente è il comando attivo. L'utilizzo dei tasti di scelta rapida consente di modificare rapidamente il comando attivo. Questi tasti di scelta rapida sono simili a quelli della shell UNIX tcsh e dell'editor Emacs.

Nella tabella seguente sono elencati i tasti di scelta rapida per la modifica dei comandi CLI. `Ctrl-` Indica che si tiene premuto il tasto Ctrl mentre si digita il carattere specificato dopo di esso. `Esc-` Indica che si preme e si rilascia il tasto Esc, quindi si digita il carattere specificato dopo di esso.

[cols="4a,4a"]
|===
| Se si desidera... | Utilizzare uno di questi tasti di scelta rapida... 


 a| 
Spostare il cursore indietro di un carattere
 a| 
* Ctrl-B.
* Freccia indietro




 a| 
Spostare il cursore in avanti di un carattere
 a| 
* Ctrl-F.
* Freccia avanti




 a| 
Spostare il cursore indietro di una parola
 a| 
ESC-B.



 a| 
Spostare il cursore in avanti di una parola
 a| 
ESC-F.



 a| 
Spostare il cursore all'inizio della riga
 a| 
Ctrl-A.



 a| 
Spostare il cursore alla fine della riga
 a| 
Ctrl-E.



 a| 
Rimuovere il contenuto della riga di comando dall'inizio della riga al cursore e salvarlo nel buffer di taglio. Il buffer cut agisce come una memoria temporanea, simile a quella che viene chiamata _clipboard_ in alcuni programmi.
 a| 
Ctrl-U



 a| 
Rimuovere il contenuto della riga di comando dal cursore alla fine della riga e salvarlo nel buffer di taglio
 a| 
Ctrl-K.



 a| 
Rimuovere il contenuto della riga di comando dal cursore alla fine della parola seguente e salvarlo nel buffer di taglio
 a| 
ESC-D



 a| 
Rimuovere la parola prima del cursore e salvarla nel buffer di taglio
 a| 
Ctrl-W.



 a| 
Inserire il contenuto del buffer di taglio e inserirlo nella riga di comando del cursore
 a| 
Ctrl-Y



 a| 
Consente di eliminare il carattere che precede il cursore
 a| 
* Ctrl-H
* Backspace




 a| 
Consente di eliminare il carattere in cui si trova il cursore
 a| 
Ctrl-D



 a| 
Eliminare la linea
 a| 
Ctrl-C.



 a| 
Cancellare lo schermo
 a| 
Ctrl-L.



 a| 
Sostituire il contenuto corrente della riga di comando con la voce precedente nell'elenco della cronologia.

Ad ogni ripetizione del tasto di scelta rapida, il cursore della cronologia passa alla voce precedente.
 a| 
* Ctrl-P.
* ESC-P.
* Freccia su




 a| 
Sostituire il contenuto corrente della riga di comando con la voce successiva nell'elenco della cronologia. Ad ogni ripetizione del tasto di scelta rapida, il cursore della cronologia passa alla voce successiva.
 a| 
* Ctrl-N.
* ESC-N.
* Freccia giù




 a| 
Espandere un comando o un elenco di input validi inseriti parzialmente dalla posizione di modifica corrente
 a| 
* Scheda
* Ctrl-I.




 a| 
Visualizza la guida sensibile al contesto
 a| 
?



 a| 
Uscire dalla mappatura speciale per il  `?`carattere punto interrogativo ). Ad esempio, per inserire un punto interrogativo nell'argomento di un comando, premere Esc, quindi il `?` carattere.
 a| 
ESC-?



 a| 
Avviare l'output TTY
 a| 
Ctrl-Q.



 a| 
Interrompere l'output TTY
 a| 
Ctrl-S.

|===