---
permalink: system-admin/license-types-licensed-method-concept.html 
sidebar: sidebar 
keywords: license, types, method, cluster, manage, install, add, nlf 
summary: La comprensione dei tipi di licenza e del metodo concesso in licenza consente di gestire le licenze in un cluster. 
---
= Tipi di licenza e metodo concesso in licenza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La comprensione dei tipi di licenza e del metodo concesso in licenza consente di gestire le licenze in un cluster.



== Tipi di licenza

Un pacchetto può avere uno o più dei seguenti tipi di licenza installati nel cluster. Il `system license show` il comando visualizza il tipo o i tipi di licenza installati per un pacchetto.

* Licenza standard (`license`)
+
Una licenza standard è una licenza con blocco a nodo. Viene emesso per un nodo con un numero di serie di sistema specifico (noto anche come _numero di serie del controller_). Una licenza standard è valida solo per il nodo che ha il numero seriale corrispondente.

+
L'installazione di una licenza standard bloccata da nodo consente a un nodo di accedere alla funzionalità concessa in licenza. Affinché il cluster utilizzi la funzionalità concessa in licenza, è necessario che almeno un nodo sia concesso in licenza per tale funzionalità. L'utilizzo della funzionalità concessa in licenza su un nodo che non dispone di diritti per tale funzionalità potrebbe essere fuori conformità.

* Licenza del sito (`site`)
+
Una licenza di sito non è legata a un numero seriale di sistema specifico. Quando si installa una licenza di sito, tutti i nodi del cluster hanno diritto alla funzionalità concessa in licenza. Il `system license show` il comando visualizza le licenze del sito sotto il numero di serie del cluster.

+
Se il cluster dispone di una licenza di sito e si rimuove un nodo dal cluster, il nodo non dispone della licenza di sito e non ha più diritto alla funzionalità concessa in licenza. Se si aggiunge un nodo a un cluster che dispone di una licenza di sito, il nodo avrà automaticamente diritto alla funzionalità concessa dalla licenza di sito.

* Licenza di valutazione (`demo`)
+
Una licenza di valutazione è una licenza temporanea che scade dopo un determinato periodo di tempo (indicato da `system license show` comando). Consente di provare alcune funzionalità software senza acquistare alcun diritto. Si tratta di una licenza a livello di cluster e non è legata a un numero seriale specifico di un nodo.

+
Se il cluster dispone di una licenza di valutazione per un pacchetto e si rimuove un nodo dal cluster, il nodo non dispone della licenza di valutazione.





== Metodo concesso in licenza

È possibile installare sia una licenza a livello di cluster (il `site` oppure `demo` e una licenza bloccata dal nodo (il `license` digitare) per un pacchetto. Pertanto, un pacchetto installato può avere diversi tipi di licenza nel cluster. Tuttavia, per il cluster, esiste un solo _metodo concesso in licenza_ per un pacchetto. Il `licensed method` campo di `system license status show` il comando visualizza i diritti utilizzati per un pacchetto. Il comando determina il metodo concesso in licenza come segue:

* Se un pacchetto ha un solo tipo di licenza installato nel cluster, il tipo di licenza installato è il metodo concesso in licenza.
* Se un pacchetto non dispone di licenze installate nel cluster, il metodo concesso in licenza è `none`.
* Se nel cluster sono installati più tipi di licenza, il metodo concesso in licenza viene determinato nel seguente ordine di priorità del tipo di licenza.-`site`, `license`, e. `demo`.
+
Ad esempio:

+
** Se si dispone di una licenza per sito, di una licenza standard e di una licenza di valutazione per un pacchetto, il metodo concesso in licenza per il pacchetto nel cluster è `site`.
** Se si dispone di una licenza standard e di una licenza di valutazione per un pacchetto, il metodo concesso in licenza per il pacchetto nel cluster è `license`.
** Se si dispone solo di una licenza di valutazione per un pacchetto, il metodo concesso in licenza per il pacchetto nel cluster è `demo`.



