---
permalink: system-admin/log-files-sent-autosupport-messages-concept.html 
sidebar: sidebar 
keywords: log, files, autosupport, message, technical, support, staff 
summary: I messaggi AutoSupport possono contenere diversi file di log delle chiavi che consentono al personale del supporto tecnico di esaminare le recenti attività del sistema. 
---
= File di log inviati in messaggi AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi AutoSupport possono contenere diversi file di log delle chiavi che consentono al personale del supporto tecnico di esaminare le recenti attività del sistema.

Tutti i tipi di messaggi AutoSupport possono includere i seguenti file di registro quando il sottosistema file di registro è attivato:

|===
| File di log | Quantità di dati inclusi nel file 


 a| 
* File di registro da `/mroot/etc/log/mlog/` directory
* Il file di log DEI MESSAGGI

 a| 
Solo le nuove righe aggiunte ai registri dall'ultimo messaggio AutoSupport fino a un massimo specificato. Ciò garantisce che i messaggi AutoSupport abbiano dati univoci, rilevanti, non sovrapposti.

(I file di log dei partner rappresentano un'eccezione; per i partner sono inclusi i dati massimi consentiti).



 a| 
* File di registro da `/mroot/etc/log/shelflog/` directory
* File di registro da `/mroot/etc/log/acp/` directory
* Dati di log del sistema di gestione degli eventi (EMS)

 a| 
Le righe di dati più recenti fino a un massimo specificato.

|===
Il contenuto dei messaggi AutoSupport può cambiare tra una versione e l'altra di ONTAP.
