---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, ontap one, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf 
summary: 'Una licenza è un record di una o più autorizzazioni software. In ONTAP 8.2 fino a ONTAP 9.9.1, le licenze vengono fornite sotto forma di stringhe di 28 caratteri ed è disponibile una chiave per ogni funzione ONTAP. In ONTAP 9,2 è stato introdotto un nuovo formato di licenza denominato file di licenza NetApp (NLF) solo per le funzioni a livello di cluster.' 
---
= Panoramica delle licenze ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una licenza è un record di una o più autorizzazioni software. A partire da ONTAP 9.10.1, tutte le licenze vengono fornite come file di licenza NetApp (NLF), che è un singolo file che abilita più funzioni.  A partire da maggio 2023, tutti i sistemi AFF (sia serie A che serie C) e i sistemi FAS vengono venduti con la suite software ONTAP One o la suite software ONTAP base, ciascuno dei quali viene fornito come un unico NLF, sostituendo i pacchetti NLF separati introdotti per la prima volta in ONTAP 9.10.1.



== Licenze incluse con ONTAP ONE

ONTAP One contiene tutte le funzionalità disponibili con licenza. Contiene una combinazione dei contenuti del precedente bundle Core, del bundle Data Protection, del bundle Security and Compliance, del bundle Hybrid Cloud e del bundle Encryption, come mostrato nella tabella. La crittografia non è disponibile nei paesi con restrizioni.

|===


| Nome del bundle precedente | Chiavi ONTAP incluse 


.5+| Bundle principale | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVME-of 


.3+| Bundle di sicurezza e conformità | Protezione ransomware autonoma 


| MTKM 


| SnapLock 


.3+| Bundle di data Protection | SnapMirror (asincrono, sincrono, business continuity) 


| SnapCenter 


| S3 SnapMirror per destinazioni NetApp 


.2+| Bundle cloud ibrido | SnapMirror Cloud 


| S3 SnapMirror per destinazioni non NetApp 


.2+| Bundle di crittografia | Crittografia dei volumi NetApp 


| Modulo Trusted Platform 
|===


== Licenze non incluse in ONTAP ONE

ONTAP One non include i servizi erogati nel cloud di NetApp, come ad esempio:

* Tiering BlueXP
* Cloud Insights
* Backup BlueXP
* Governance dei dati




== ONTAP uno per i sistemi esistenti

Se si dispone di sistemi esistenti che sono attualmente supportati da NetApp ma non sono stati aggiornati a ONTAP One, le licenze esistenti su tali sistemi sono ancora valide e continuano a funzionare come previsto. Ad esempio, se la licenza SnapMirror è già installata su sistemi esistenti, non è necessario eseguire l'aggiornamento a ONTAP One per ottenere una nuova licenza SnapMirror. Tuttavia, se non si dispone di una licenza SnapMirror installata su un sistema esistente, l'unico modo per ottenere tale licenza è eseguire l'aggiornamento a ONTAP One a un costo aggiuntivo.

A partire da giugno 2023, è possibile utilizzare anche i sistemi ONTAP che utilizzano chiavi di licenza di 28 caratteri link:https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_28_character_keys["Eseguire l'aggiornamento al bundle di compatibilità ONTAP One o ONTAP base"].



== Licenze incluse con ONTAP base

ONTAP base è una suite software opzionale alternativa a ONTAP One per i sistemi ONTAP. È per casi d'utilizzo specifici in cui non sono richieste tecnologie di data Protection come SnapMirror e SnapCenter, nonché funzionalità di sicurezza come il ransomware autonomo, come i sistemi non di produzione per ambienti di test o sviluppo dedicati. Non è possibile aggiungere licenze aggiuntive alla ONTAP base. Per licenze aggiuntive, come SnapMirror, è necessario eseguire l'aggiornamento a ONTAP One.

|===


| Nome del bundle precedente | Chiavi ONTAP incluse 


.5+| Bundle principale | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVME-of 


.3+| Bundle di crittografia | Crittografia dei volumi NetApp 


| Modulo Trusted Platform 


| Crittografia dei dati inattivi 
|===


== Altri metodi di distribuzione delle licenze

In ONTAP 8.2 fino a ONTAP 9.9.1, le chiavi di licenza vengono fornite sotto forma di stringhe di 28 caratteri ed è disponibile una chiave per funzione ONTAP. Utilizzare l'interfaccia CLI di ONTAP per installare le chiavi di licenza se si utilizza ONTAP 8,2 tramite ONTAP 9,9.1.

[NOTE]
====
ONTAP 9.10.1 supporta l'installazione di chiavi di licenza di 28 caratteri utilizzando Gestione di sistema o CLI. Tuttavia, se è installata una licenza NLF per una funzione, non è possibile installare una chiave di licenza di 28 caratteri sul file di licenza NetApp per la stessa funzione. Per informazioni sull'installazione di NLF o chiavi di licenza con System Manager, vedere link:https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["Installare le licenze ONTAP"].

====
.Informazioni correlate
https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_NLFs_already["Come ottenere una licenza ONTAP One quando il sistema dispone già di NLF"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["Come verificare le autorizzazioni software ONTAP e le relative chiavi di licenza utilizzando il sito di assistenza"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp: Stato del rischio di licenza ONTAP"^]
