---
permalink: system-admin/manage-web-services-concept.html 
sidebar: sidebar 
keywords: manage, web, services, svm, storage, virtual, machine, cluster, controler, user 
summary: 'È possibile attivare o disattivare un servizio Web per il cluster o una macchina virtuale di storage (SVM), visualizzare le impostazioni per i servizi Web e controllare se gli utenti di un ruolo possono accedere a un servizio Web.' 
---
= Panoramica sulla gestione dei servizi Web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare o disattivare un servizio Web per il cluster o una macchina virtuale di storage (SVM), visualizzare le impostazioni per i servizi Web e controllare se gli utenti di un ruolo possono accedere a un servizio Web.

È possibile gestire i servizi Web per il cluster o una SVM nei seguenti modi:

* Attivazione o disattivazione di un servizio Web specifico
* Specifica se l'accesso a un servizio Web è limitato solo a HTTP (SSL) crittografato
* Visualizzazione della disponibilità dei servizi Web
* Consentire o negare agli utenti di un ruolo di accedere a un servizio Web
* Visualizzazione dei ruoli autorizzati ad accedere a un servizio Web


Affinché un utente possa accedere a un servizio Web, devono essere soddisfatte tutte le seguenti condizioni:

* L'utente deve essere autenticato.
+
Ad esempio, un servizio Web potrebbe richiedere un nome utente e una password. La risposta dell'utente deve corrispondere a un account valido.

* L'utente deve essere configurato con il metodo di accesso corretto.
+
L'autenticazione ha successo solo per gli utenti con il metodo di accesso corretto per il servizio Web specificato. Per il servizio Web API di ONTAP  `ontapi`), gli utenti devono disporre di `ontapi` metodo di accesso. Per tutti gli altri servizi Web, gli utenti devono disporre di `http` metodo di accesso.

+
[NOTE]
====
Si utilizza `security login` comandi per gestire i metodi di accesso e di autenticazione degli utenti`.

====
* Il servizio Web deve essere configurato in modo da consentire il ruolo di controllo degli accessi dell'utente.
+
[NOTE]
====
Si utilizza `vserver services web access` comandi per controllare l'accesso di un ruolo a un servizio web.

====


Se un firewall è attivato, il criterio firewall per l'utilizzo della LIF per i servizi Web deve essere impostato in modo da consentire HTTP o HTTPS.

Se si utilizza HTTPS per l'accesso al servizio Web, è necessario attivare anche SSL per il cluster o SVM che offre il servizio Web e fornire un certificato digitale per il cluster o SVM.
