---
permalink: system-admin/manage-jobs-schedules.html 
sidebar: sidebar 
keywords: job, categories, server, cluster, affiliated, private, commands, managing, show jobs, job schedule, stop a job, delete a job, pause a job, display private jobs, modify, cron, interval, delete, interval schedule, manage jobs and schedule, manage jobs, manage schedule 
summary: I lavori vengono inseriti in una coda di lavoro ed eseguiti in background quando le risorse sono disponibili. Se un lavoro consuma troppe risorse del cluster, è possibile interromperlo o metterlo in pausa fino a quando non si verifica una minore domanda sul cluster. È inoltre possibile monitorare e riavviare i lavori. 
---
= Gestire i lavori e pianificare
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I lavori vengono inseriti in una coda di lavoro ed eseguiti in background quando le risorse sono disponibili. Se un lavoro consuma troppe risorse del cluster, è possibile interromperlo o metterlo in pausa fino a quando non si verifica una minore domanda sul cluster. È inoltre possibile monitorare e riavviare i lavori.



== Categorie di lavoro

È possibile gestire tre categorie di lavori: Affiliati a server, affiliati a cluster e privati.

Un lavoro può essere in una delle seguenti categorie:

* *Lavori affiliati al server*
+
Questi job vengono messi in coda dal framework di gestione a un nodo specifico da eseguire.

* *Lavori affiliati a cluster*
+
Questi processi vengono messi in coda dal framework di gestione a qualsiasi nodo del cluster da eseguire.

* *Lavori privati*
+
Questi lavori sono specifici di un nodo e non utilizzano il database replicato (RDB) o altri meccanismi del cluster. I comandi che gestiscono i processi privati richiedono un livello di privilegio avanzato o superiore.





== Comandi per la gestione dei lavori

Quando si immette un comando che richiama un processo, in genere, il comando informa che il processo è stato messo in coda e ritorna al prompt dei comandi CLI. Tuttavia, alcuni comandi riportano invece l'avanzamento del processo e non ritornano al prompt dei comandi CLI fino al completamento del processo. In questi casi, è possibile premere Ctrl-C per spostare il job in background.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza informazioni su tutti i lavori
 a| 
`job show`



 a| 
Visualizza le informazioni sui job in base al nodo
 a| 
`job show bynode`



 a| 
Visualizzare le informazioni sui job affiliati al cluster
 a| 
`job show-cluster`



 a| 
Visualizza le informazioni sui lavori completati
 a| 
`job show-completed`



 a| 
Visualizza le informazioni sulla cronologia dei lavori
 a| 
`job history show`

Per ciascun nodo del cluster vengono memorizzati fino a 25,000 record di processi. Di conseguenza, il tentativo di visualizzare l'intera cronologia dei lavori potrebbe richiedere molto tempo. Per evitare tempi di attesa potenzialmente lunghi, è necessario visualizzare i lavori per nodo, SVM (Storage Virtual Machine) o ID record.



 a| 
Visualizzare l'elenco dei processi privati
 a| 
`job private show` (livello di privilegio avanzato)



 a| 
Visualizza le informazioni sui processi privati completati
 a| 
`job private show-completed` (livello di privilegio avanzato)



 a| 
Visualizza le informazioni sullo stato di inizializzazione per i job manager
 a| 
`job initstate show` (livello di privilegio avanzato)



 a| 
Monitorare l'avanzamento di un lavoro
 a| 
`job watch-progress`



 a| 
Monitorare l'avanzamento di un processo privato
 a| 
`job private watch-progress` (livello di privilegio avanzato)



 a| 
Mettere in pausa un lavoro
 a| 
`job pause`



 a| 
Mettere in pausa un processo privato
 a| 
`job private pause` (livello di privilegio avanzato)



 a| 
Riprendere un processo in pausa
 a| 
`job resume`



 a| 
Riprendere un processo privato in pausa
 a| 
`job private resume` (livello di privilegio avanzato)



 a| 
Interrompere un lavoro
 a| 
`job stop`



 a| 
Interruzione di un processo privato
 a| 
`job private stop` (livello di privilegio avanzato)



 a| 
Eliminare un lavoro
 a| 
`job delete`



 a| 
Eliminare un processo privato
 a| 
`job private delete` (livello di privilegio avanzato)



 a| 
Disassociare un lavoro affiliato al cluster a un nodo non disponibile che lo possiede, in modo che un altro nodo possa assumere la proprietà di tale lavoro
 a| 
`job unclaim` (livello di privilegio avanzato)

|===
[NOTE]
====
È possibile utilizzare `event log show` per determinare il risultato di un lavoro completato.

====
.Informazioni correlate
link:../concepts/manual-pages.html["Riferimento al comando ONTAP"]



== Comandi per la gestione delle pianificazioni dei processi

Molte attività, ad esempio le copie Snapshot dei volumi, possono essere configurate per l'esecuzione su pianificazioni specificate.le pianificazioni eseguite in orari specifici sono denominate _cron_ schedules (simili a UNIX `cron` pianificazioni). Le pianificazioni eseguite a intervalli sono denominate _interval_ schedules. Si utilizza `job schedule` comandi per gestire le pianificazioni dei processi.

Le pianificazioni dei processi non vengono regolate in base alle modifiche manuali della data e dell'ora del cluster. Questi processi vengono pianificati per essere eseguiti in base all'ora corrente del cluster in cui è stato creato il processo o quando è stato eseguito più di recente. Pertanto, se si modifica manualmente la data o l'ora del cluster, utilizzare `job show` e. `job history show` comandi per verificare che tutti i processi pianificati siano messi in coda e completati in base alle proprie esigenze.

Se il cluster fa parte di una configurazione MetroCluster, le pianificazioni dei processi su entrambi i cluster devono essere identiche. Pertanto, se si crea, modifica o elimina una pianificazione del processo, è necessario eseguire la stessa operazione sul cluster remoto.

|===
| Se si desidera... | Utilizzare questo comando... 


 a| 
Visualizza le informazioni su tutti i programmi
 a| 
`job schedule show`



 a| 
Visualizza l'elenco dei lavori in base alla pianificazione
 a| 
`job schedule show-jobs`



 a| 
Visualizza le informazioni sulle pianificazioni cron
 a| 
`job schedule cron show`



 a| 
Visualizza le informazioni sulle pianificazioni degli intervalli
 a| 
`job schedule interval show`



 a| 
Creare un calendario di cron
 a| 
`job schedule cron create`

A partire da ONTAP 9.10.1, puoi includere la SVM per la pianificazione del lavoro.



 a| 
Creare una pianificazione a intervalli
 a| 
`job schedule interval create`

Specificare almeno uno dei seguenti parametri: `-days`, `-hours`, `-minutes`, o. `-seconds`.



 a| 
Modificare una pianificazione cron
 a| 
`job schedule cron modify`



 a| 
Modificare una pianificazione di intervalli
 a| 
`job schedule interval modify`



 a| 
Eliminare un programma
 a| 
`job schedule delete`



 a| 
Eliminare una pianificazione cron
 a| 
`job schedule cron delete`



 a| 
Eliminare una pianificazione di intervalli
 a| 
`job schedule interval delete`

|===
.Informazioni correlate
link:../concepts/manual-pages.html["Riferimento al comando ONTAP"]
