---
permalink: system-admin/manage-banner-reference.html 
sidebar: sidebar 
keywords: manage, banner, svm, cluster, configure 
summary: Puoi gestire il banner a livello di cluster o SVM e modificare la modalità di visualizzazione del banner 
---
= Gestisci il banner di testo visualizzato a livello del cluster ONTAP e della SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire il banner a livello di cluster o SVM. Il banner configurato per il cluster viene utilizzato anche per tutte le SVM che non hanno un messaggio banner definito. Un banner creato successivamente per una SVM sovrascrive il banner del cluster per tale SVM.

.Scelte
* Gestire il banner a livello di cluster:
+
|===
| Se si desidera... | Quindi... 


 a| 
Creare un banner da visualizzare per tutte le sessioni di accesso
 a| 
Impostare un banner a livello di cluster:

`security login banner modify -vserver <cluster_name> { [-message "text"] | [-uri <ftp_or_http_addr>] }`



 a| 
Rimuovere il banner per tutti gli accessi (cluster e SVM)
 a| 
Impostare il banner su una stringa vuota (`""`):

`security login banner modify -vserver * -message ""`



 a| 
Eseguire l'override di un banner creato da un amministratore SVM
 a| 
Modificare il messaggio banner SVM:

`security login banner modify -vserver <svm_name> { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`

|===
* Gestire il banner a livello di SVM:
+
La specifica `-vserver <svm_name>` non è necessaria nel contesto SVM.

+
|===
| Se si desidera... | Quindi... 


 a| 
Eseguire l'override del banner fornito dall'amministratore del cluster con un banner diverso per SVM
 a| 
Creare un banner per SVM:

`security login banner modify -vserver <svm_name> { [-message "text"] | [-uri <ftp_or_http_addr>] }`



 a| 
Eliminare il banner fornito dall'amministratore del cluster in modo che non venga visualizzato alcun banner per SVM
 a| 
Impostare il banner SVM su una stringa vuota per SVM:

`security login banner modify -vserver <svm_name> -message ""`



 a| 
Utilizzare il banner a livello di cluster quando SVM utilizza attualmente un banner a livello di SVM
 a| 
Impostare il banner SVM su `"-"`:

`security login banner modify -vserver <svm_name> -message "-"`

|===

