---
permalink: system-admin/manage-banner-reference.html 
sidebar: sidebar 
keywords: manage, banner, svm, cluster, configure 
summary: È possibile gestire il banner a livello di cluster o SVM. Il banner configurato per il cluster viene utilizzato anche per tutte le SVM che non hanno un messaggio banner definito. Un banner creato successivamente per una SVM sovrascrive il banner del cluster per tale SVM. 
---
= Gestione del banner
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire il banner a livello di cluster o SVM. Il banner configurato per il cluster viene utilizzato anche per tutte le SVM che non hanno un messaggio banner definito. Un banner creato successivamente per una SVM sovrascrive il banner del cluster per tale SVM.

.Scelte
* Gestire il banner a livello di cluster:
+
|===
| Se si desidera... | Quindi... 


 a| 
Creare un banner da visualizzare per tutte le sessioni di accesso CLI
 a| 
Impostare un banner a livello di cluster:

`*security login banner modify -vserver _cluster_name_ { [-message "text"] | [_-uri ftp_or_http_addr_] }*`



 a| 
Rimuovere il banner per tutti gli accessi (cluster e SVM)
 a| 
Impostare il banner su una stringa vuota (`""`):

`*security login banner modify -vserver * -message ""*`



 a| 
Eseguire l'override di un banner creato da un amministratore SVM
 a| 
Modificare il messaggio banner SVM:

`*security login banner modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`

|===
* Gestire il banner a livello di SVM:
+
Specificare `-vserver _svm_name_` Non è richiesto nel contesto SVM.

+
|===
| Se si desidera... | Quindi... 


 a| 
Eseguire l'override del banner fornito dall'amministratore del cluster con un banner diverso per SVM
 a| 
Creare un banner per SVM:

`*security login banner modify -vserver _svm_name_ { [-message "text"] | [-uri ftp_or_http_addr] }*`



 a| 
Eliminare il banner fornito dall'amministratore del cluster in modo che non venga visualizzato alcun banner per SVM
 a| 
Impostare il banner SVM su una stringa vuota per SVM:

`*security login banner modify -vserver _svm_name_ -message ""*`



 a| 
Utilizzare il banner a livello di cluster quando SVM utilizza attualmente un banner a livello di SVM
 a| 
Impostare il banner SVM su `"-"`:

`*security login banner modify -vserver _svm_name_ -message "-"*`

|===

