---
permalink: system-admin/manage-autosupport-concept.html 
sidebar: sidebar 
keywords: manage, autosupport, support, technical, message 
summary: 'AutoSupport è un meccanismo che monitora in modo proattivo lo stato di salute del sistema e invia automaticamente messaggi al supporto tecnico NetApp, all"organizzazione di supporto interna e a un partner di supporto. Sebbene i messaggi AutoSupport per il supporto tecnico siano attivati per impostazione predefinita, è necessario impostare le opzioni corrette e disporre di un host di posta valido per l"invio dei messaggi all"organizzazione di supporto interna.' 
---
= Informazioni su AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport è un meccanismo che monitora in modo proattivo lo stato di salute del sistema e invia automaticamente messaggi al supporto tecnico NetApp, all'organizzazione di supporto interna e a un partner di supporto. Sebbene i messaggi AutoSupport per il supporto tecnico siano attivati per impostazione predefinita, è necessario impostare le opzioni corrette e disporre di un host di posta valido per l'invio dei messaggi all'organizzazione di supporto interna.

Solo l'amministratore del cluster può eseguire la gestione di AutoSupport. L'amministratore della macchina virtuale per lo storage (SVM) non ha accesso a AutoSupport.

AutoSupport è attivato per impostazione predefinita quando si configura il sistema di storage per la prima volta. AutoSupport inizia a inviare messaggi al supporto tecnico 24 ore dopo l'attivazione di AutoSupport. È possibile ridurre il periodo di 24 ore aggiornando o ripristinando il sistema, modificando la configurazione AutoSupport o modificando l'ora del sistema in modo che non sia un periodo di 24 ore.

[NOTE]
====
È possibile disattivare AutoSupport in qualsiasi momento, ma si consiglia di lasciarlo attivato. L'abilitazione di AutoSupport può contribuire a velocizzare in modo significativo la determinazione e la risoluzione dei problemi in caso di problemi nel sistema storage. Per impostazione predefinita, il sistema raccoglie le informazioni AutoSupport e le memorizza localmente, anche se si disattiva AutoSupport.

====
Per ulteriori informazioni su AutoSupport, visitare il sito del supporto NetApp.

.Informazioni correlate
* https://support.netapp.com/["Supporto NetApp"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Scopri di più sui comandi AutoSupport nella CLI di ONTAP"^]

