---
permalink: system-admin/manage-banner-motd-concept.html 
sidebar: sidebar 
keywords: manage, banner, motd, clu, user, svm, storage, virtual, machine, cluster 
summary: 'ONTAP consente di configurare un banner di accesso o un messaggio del giorno (MOTD) per comunicare le informazioni amministrative agli utenti di System Manager e CLI del cluster o della Storage Virtual Machine (SVM).' 
---
= Scopri il banner di accesso ONTAP e il testo del messaggio del giorno
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP consente di configurare un banner di accesso o un messaggio del giorno (MOTD) per comunicare le informazioni amministrative agli utenti di System Manager e CLI del cluster o della Storage Virtual Machine (SVM).

Un banner viene visualizzato in una sessione della console (solo per l'accesso al cluster) o in una sessione SSH (per l'accesso al cluster o alla SVM) prima che venga richiesto all'utente di eseguire l'autenticazione, ad esempio una password. Ad esempio, è possibile utilizzare il banner per visualizzare un messaggio di avviso come il seguente a qualcuno che tenta di accedere al sistema:

[listing]
----
$ ssh admin@cluster1-01

This system is for authorized users only. Your IP Address has been logged.

Password:

----
Un MOTD viene visualizzato in una sessione della console (solo per l'accesso al cluster) o in una sessione SSH (per l'accesso al cluster o a SVM) dopo l'autenticazione di un utente, ma prima della visualizzazione del prompt della shell dei cluster. Ad esempio, è possibile utilizzare MOTD per visualizzare un messaggio di benvenuto o informativo, ad esempio:

[listing]
----
$ ssh admin@cluster1-01

Password:

Greetings. This system is running ONTAP 9.0.
Your user name is 'admin'. Your last login was Wed Apr 08 16:46:53 2015 from 10.72.137.28.

----
È possibile creare o modificare il contenuto del banner o di MOTD utilizzando `security login banner modify` oppure `security login motd modify` di comando, rispettivamente, nei seguenti modi:

* È possibile utilizzare la CLI in modo interattivo o non interattivo per specificare il testo da utilizzare per il banner o MOTD.
+
La modalità interattiva, avviata quando si utilizza il comando senza `-message` oppure `-uri` parametro, consente di utilizzare newline (note anche come fine delle righe) nel messaggio.

+
La modalità non interattiva, che utilizza `-message` parametro per specificare la stringa del messaggio, non supporta newlines.

* È possibile caricare il contenuto da una posizione FTP o HTTP da utilizzare per il banner o MOTD.
* È possibile configurare il MOTD per visualizzare il contenuto dinamico.
+
Di seguito sono riportati alcuni esempi di elementi che è possibile configurare per la visualizzazione dinamica di MOTD:

+
** Nome del cluster, nome del nodo o nome SVM
** Data e ora del cluster
** Nome dell'utente che effettua l'accesso
** Ultimo accesso per l'utente su qualsiasi nodo del cluster
** Nome o indirizzo IP del dispositivo di accesso
** Nome del sistema operativo
** Versione del software
** Stringa della versione del cluster effettiva


+
Il banner non supporta il contenuto dinamico. Ulteriori informazioni su `security login motd modify` e sulle sequenze di escape che è possibile utilizzare per abilitare MOTD a visualizzare contenuti generati dinamicamente in link:https://docs.netapp.com/us-en/ontap-cli/security-login-motd-modify.html["Riferimento al comando ONTAP"^].



È possibile gestire il banner e il MOTD a livello di cluster o SVM:

* I seguenti fatti si applicano al banner:
+
** Il banner configurato per il cluster viene utilizzato anche per tutte le SVM che non hanno un messaggio banner definito.
** È possibile configurare un banner a livello di SVM per ogni SVM.
+
Se è stato configurato un banner a livello di cluster, questo viene ignorato dal banner a livello di SVM per la SVM indicata.



* I seguenti fatti si applicano al MOTD:
+
** Per impostazione predefinita, il MOTD configurato per il cluster è abilitato anche per tutte le SVM.
** Inoltre, è possibile configurare un MOTD a livello di SVM per ogni SVM.
+
In questo caso, gli utenti che accedono a SVM vedranno due MOTD, uno definito a livello di cluster e l'altro a livello di SVM.

** Il MOTD a livello di cluster può essere attivato o disattivato per SVM dall'amministratore del cluster.
+
Se l'amministratore del cluster disattiva il MOTD a livello di cluster per una SVM, un utente che accede a SVM non vedrà il MOTD a livello di cluster.




