---
permalink: system-admin/methods-specifying-queries-concept.html 
sidebar: sidebar 
keywords: method, use, query, operator, interface, management, unix, patterns, wildcards, command, parameter, argument 
summary: 'L"interfaccia di gestione supporta query e modelli in stile UNIX e caratteri jolly per consentire la corrispondenza di più valori negli argomenti dei parametri di comando.' 
---
= Utilizzare gli operatori di query nell'interfaccia CLI di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia di gestione supporta query e modelli in stile UNIX e caratteri jolly per consentire la corrispondenza di più valori negli argomenti dei parametri di comando.

La seguente tabella descrive gli operatori di query supportati:

[cols="10,90"]
|===
| Operatore | Descrizione 


 a| 
*
 a| 
Carattere jolly che corrisponde a tutte le voci.

Ad esempio, il comando `volume show -volume \*tmp*` visualizza un elenco di tutti i volumi i cui nomi includono la stringa `tmp`.



 a| 
!
 a| 
NON operatore.

Indica un valore che non deve essere associato; ad esempio, `*!vs0*` indica di non corrispondere al valore `vs0`.



 a| 
|
 a| 
O operatore.

Separa due valori da confrontare; ad esempio, `*vs0 | vs2*` corrisponde a vs0 o vs2. È possibile specificare più istruzioni OR, ad esempio `a | b* | \*c*` corrisponde alla voce `a`, qualsiasi voce che inizia con `b`e qualsiasi voce che includa `c`.



 a| 
..
 a| 
Operatore del raggio d'azione.

Ad esempio, `*5..10*` corrisponde a qualsiasi valore da `5` a. `10`, incluso.



 a| 
<
 a| 
Meno dell'operatore.

Ad esempio, `*<20*` corrisponde a qualsiasi valore inferiore a. `20`.



 a| 
>
 a| 
Maggiore rispetto all'operatore.

Ad esempio, `*>5*` corrisponde a qualsiasi valore maggiore di `5`.



 a| 
<=
 a| 
Minore o uguale all'operatore.

Ad esempio, `*<=5*` corrisponde a qualsiasi valore minore o uguale a. `5`.



 a| 
>=
 a| 
Maggiore o uguale all'operatore.

Ad esempio, `*>=5*` corrisponde a qualsiasi valore maggiore o uguale a. `5`.



 a| 
{`query`}
 a| 
Query estesa.

Una query estesa deve essere specificata come primo argomento dopo il nome del comando, prima di qualsiasi altro parametro.

Ad esempio, il comando `volume modify {-volume \*tmp*} -state offline` imposta offline tutti i volumi i cui nomi includono la stringa `tmp`.

|===
Se si desidera analizzare i caratteri di query come valori letterali, è necessario racchiudere i caratteri tra virgolette doppie (ad esempio, `"<10"`, `"0..100"`, `"\*abc*"`, o. `"a|b"`) per restituire i risultati corretti.

È necessario racchiudere i nomi dei file raw tra virgolette doppie per impedire l'interpretazione di caratteri speciali. Questo vale anche per i caratteri speciali utilizzati dalla shell.

È possibile utilizzare più operatori di query in un'unica riga di comando. Ad esempio, il comando `volume show -size >1GB -percent-used <50 -vserver !vs1` visualizza tutti i volumi con dimensioni superiori a 1 GB, meno del 50% utilizzati e non nella Storage Virtual Machine (SVM) denominata "`VS1'".

.Informazioni correlate
link:../system-admin/keyboard-shortcuts-edit-cli-commands-reference.html["Tasti di scelta rapida per la modifica dei comandi CLI"]
