---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: 'ONTAP include un"immagine del firmware SP chiamata immagine di riferimento. Se successivamente diventa disponibile una nuova versione del firmware SP, è possibile scaricarla e aggiornarla alla versione scaricata senza aggiornare la versione di ONTAP.' 
---
= Gestire gli aggiornamenti del firmware ONTAP SP/BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP include un'immagine del firmware SP denominata _immagine di riferimento_. Se successivamente diventa disponibile una nuova versione del firmware SP, è possibile scaricarla e aggiornarla alla versione scaricata senza aggiornare la versione di ONTAP.

[NOTE]
====
Questo argomento si applica sia all'SP che al BMC.

====
ONTAP offre i seguenti metodi per la gestione degli aggiornamenti del firmware SP:

* La funzionalità di aggiornamento automatico SP è attivata per impostazione predefinita, consentendo l'aggiornamento automatico del firmware SP nei seguenti scenari:
+
** Quando si esegue l'aggiornamento a una nuova versione di ONTAP
+
Il processo di aggiornamento di ONTAP include automaticamente l'aggiornamento del firmware SP, a condizione che la versione del firmware SP fornita con ONTAP sia più recente della versione SP in esecuzione sul nodo.

+
[NOTE]
====
ONTAP rileva un aggiornamento automatico SP guasto e attiva un'azione correttiva per riprovare l'aggiornamento automatico SP fino a tre volte. Se tutti e tre i tentativi falliscono, consultare l'articolo della Knowledge base: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Health_Monitor_SPAutoUpgradeFailedMajorAlert__SP_upgrade_fails_-_AutoSupport_Message[Health Monitor SPAutoUpgrade FailedMajorAlert SP upgrade fails - AutoSupport message].

====
** Quando si scarica una versione del firmware SP dal NetApp Support Site e la versione scaricata è più recente di quella attualmente in esecuzione sul SP
** Quando si esegue il downgrade o si torna a una versione precedente di ONTAP
+
Il firmware SP viene aggiornato automaticamente alla versione più recente compatibile supportata dalla versione di ONTAP a cui si è eseguito il ripristino o il downgrade. Non è richiesto un aggiornamento manuale del firmware SP.



+
È possibile disattivare la funzionalità di aggiornamento automatico SP utilizzando `system service-processor image modify` comando. Tuttavia, si consiglia di lasciare attivata la funzionalità. La disattivazione della funzionalità può causare combinazioni non ottimali o non qualificate tra l'immagine ONTAP e l'immagine del firmware SP.

* ONTAP consente di attivare manualmente un aggiornamento SP e di specificare la modalità di esecuzione dell'aggiornamento utilizzando `system service-processor image update` comando.
+
È possibile specificare le seguenti opzioni:

+
** Il pacchetto firmware SP da utilizzare (`-package`)
+
È possibile aggiornare il firmware SP a un pacchetto scaricato specificando il nome del file del pacchetto. Il progresso `system image package show` Comando Visualizza tutti i file di pacchetto (inclusi i file per il pacchetto firmware SP) disponibili su un nodo.

** Se utilizzare il pacchetto firmware SP di base per l'aggiornamento SP (`-baseline`)
+
È possibile aggiornare il firmware SP alla versione di base fornita con la versione attualmente in esecuzione di ONTAP.



+
[NOTE]
====
Se si utilizzano alcune opzioni o parametri di aggiornamento più avanzati, le impostazioni di configurazione del BMC potrebbero essere temporaneamente cancellate. Dopo il riavvio, ONTAP può impiegare fino a 10 minuti per ripristinare la configurazione BMC.

====
* ONTAP consente di visualizzare lo stato dell'ultimo aggiornamento del firmware SP attivato da ONTAP utilizzando `system service-processor image update-progress show` comando.


Qualsiasi connessione esistente all'SP viene interrotta quando il firmware dell'SP viene aggiornato. Questo è il caso se l'aggiornamento del firmware SP viene attivato automaticamente o manualmente.

.Informazioni correlate
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Download NetApp: Firmware di sistema e diagnostica"^]
