---
permalink: system-admin/online-help-at-sp-bmc-cli-task.html 
sidebar: sidebar 
keywords: online, help, sp, bmc, cli, command 
summary: La guida in linea visualizza i comandi e le opzioni della CLI SP/BMC. 
---
= Utilizzare la guida in linea di SP/BMC CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La guida in linea visualizza i comandi e le opzioni della CLI SP/BMC.

.A proposito di questa attività
Questa attività si applica sia all'SP che al BMC.

.Fasi
. Per visualizzare le informazioni della guida per i comandi SP/BMC, immettere quanto segue:
+
|===
| Per accedere alla guida SP... | Per accedere alla guida BMC... 


 a| 
Tipo `help` Al prompt SP.
 a| 
Tipo `system` Al prompt di BMC.

|===
+
L'esempio seguente mostra la guida in linea di SP CLI.

+
[listing]
----
SP> help
date - print date and time
exit - exit from the SP command line interface
events - print system events and event information
help - print command help
priv - show and set user mode
sp - commands to control the SP
system - commands to control the system
version - print SP version
----
+
L'esempio seguente mostra la guida in linea di BMC CLI.

+
[listing]
----
BMC> system
system acp - acp related commands
system battery - battery related commands
system console - connect to the system console
system core - dump the system core and reset
system cpld - cpld commands
system log - print system console logs
system power - commands controlling system power
system reset - reset the system using the selected firmware
system sensors - print environmental sensors status
system service-event - print service-event status
system fru - fru related commands
system watchdog - system watchdog commands

BMC>
----
. Per visualizzare le informazioni della guida relative all'opzione di un comando SP/BMC, immettere `help` Prima o dopo il comando SP/BMC.
+
L'esempio seguente mostra la guida in linea di SP CLI per SP `events` comando.

+
[listing]
----
SP> help events
events all - print all system events
events info - print system event log information
events newest - print newest system events
events oldest - print oldest system events
events search - search for and print system events
----
+
Nell'esempio seguente viene illustrata la guida in linea di BMC CLI per BMC `system power` comando.

+
[listing]
----
BMC> system power help
system power cycle - power the system off, then on
system power off - power the system off
system power on - power the system on
system power status - print system power status

BMC>
----

