---
permalink: system-admin/receive-system-health-alerts-automatic-task.html 
sidebar: sidebar 
keywords: receive, system, health, alert, automatically, system, show, command, ems, event, management, monito 
summary: 'È possibile visualizzare manualmente gli avvisi sullo stato di salute del sistema utilizzando il comando di visualizzazione degli avvisi sullo stato di salute del sistema. Tuttavia, è necessario iscriversi a specifici messaggi EMS (Event Management System) per ricevere automaticamente le notifiche quando un monitor dello stato di salute genera un avviso.' 
---
= Ricevi automaticamente avvisi sullo stato del sistema ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare manualmente gli avvisi sullo stato di salute del sistema utilizzando `system health alert show` comando. Tuttavia, è necessario iscriversi a specifici messaggi EMS (Event Management System) per ricevere automaticamente le notifiche quando un monitor dello stato di salute genera un avviso.

.A proposito di questa attività
La seguente procedura illustra come impostare le notifiche per tutti i messaggi hm.alert.Raised e per tutti i messaggi hm.alert.Cleared.

Tutti i messaggi hm.alert.Raised e tutti i messaggi hm.alert.Cleared includono una trap SNMP. I nomi dei trap SNMP sono `HealthMonitorAlertRaised` e. `HealthMonitorAlertCleared`. Per informazioni sui trap SNMP, consultare la _Network Management Guide_.

.Fasi
. Utilizzare `event destination create` Per definire la destinazione a cui si desidera inviare i messaggi EMS.
+
[listing]
----
cluster1::> event destination create -name health_alerts -mail admin@example.com
----
. Utilizzare `event route add-destinations` per instradare `hm.alert.raised` e il `hm.alert.cleared` a una destinazione.
+
[listing]
----
cluster1::> event route add-destinations -messagename hm.alert* -destinations health_alerts
----


.Informazioni correlate
link:../networking/networking_reference.html["Gestione della rete"]
