---
permalink: system-admin/respond-system-health-alerts-concept.html 
sidebar: sidebar 
keywords: respond, system, health, alerts, repair, acknowledge, prevent 
summary: Quando si verifica un avviso di stato di salute del sistema, è possibile riconoscerlo, ottenere ulteriori informazioni, riparare la condizione sottostante ed evitare che si verifichi di nuovo. 
---
= Modi per rispondere agli avvisi sullo stato di salute del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si verifica un avviso di stato di salute del sistema, è possibile riconoscerlo, ottenere ulteriori informazioni, riparare la condizione sottostante ed evitare che si verifichi di nuovo.

Quando un monitor dello stato di salute genera un avviso, è possibile rispondere in uno dei seguenti modi:

* Ottenere informazioni sull'avviso, che includono la risorsa interessata, la severità dell'avviso, la probabile causa, il possibile effetto e le azioni correttive.
* Ottenere informazioni dettagliate sull'avviso, ad esempio l'ora in cui l'avviso è stato generato e se altri hanno già confermato l'avviso.
* Ottenere informazioni sullo stato della risorsa o del sottosistema interessato, ad esempio uno shelf o un disco specifico.
* Riconoscere l'avviso per indicare che qualcuno sta lavorando al problema e identificarsi come "`Acknowledger`".
* Risolvere il problema adottando le azioni correttive fornite nell'avviso, ad esempio la risoluzione di un problema di connettività tramite il cablaggio.
* Eliminare l'avviso, se il sistema non lo ha cancellato automaticamente.
* Eliminare un avviso per evitare che influisca sullo stato di salute di un sottosistema.
+
La soppressione è utile quando si comprende un problema. Una volta eliminato un avviso, questo può comunque verificarsi, ma lo stato del sottosistema viene visualizzato come "`ok-with-suppressed`" (ok-with-suppressed). quando si verifica l'avviso sospeso.


