---
permalink: system-admin/respond-degraded-system-health-task.html 
sidebar: sidebar 
keywords: respond, degraded, system, health, status, show, alerts, corrective, probable, cause 
summary: Quando lo stato di salute del sistema è degradato, è possibile visualizzare avvisi, leggere la causa probabile e le azioni correttive, visualizzare informazioni sul sottosistema degradato e risolvere il problema. Vengono inoltre visualizzati gli avvisi soppressi, in modo da poterli modificare e verificare se sono stati riconosciuti. 
---
= Rispondere alle condizioni degradate del sistema ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando lo stato di salute del sistema è degradato, è possibile visualizzare avvisi, leggere la causa probabile e le azioni correttive, visualizzare informazioni sul sottosistema degradato e risolvere il problema. Vengono inoltre visualizzati gli avvisi soppressi, in modo da poterli modificare e verificare se sono stati riconosciuti.

.A proposito di questa attività
È possibile scoprire che è stato generato un avviso visualizzando un messaggio AutoSupport o un evento EMS oppure utilizzando `system health` comandi.

.Fasi
. Utilizzare `system health alert show` per visualizzare gli avvisi che compromettono lo stato di salute del sistema.
. Leggi la probabile causa, il possibile effetto e le azioni correttive dell'avviso per determinare se puoi risolvere il problema o se hai bisogno di ulteriori informazioni.
. Per ulteriori informazioni, utilizzare `system health alert show -instance` per visualizzare ulteriori informazioni disponibili per l'avviso.
. Utilizzare `system health alert modify` con il `-acknowledge` parametro per indicare che si sta lavorando a un avviso specifico.
. Intraprendere un'azione correttiva per risolvere il problema come descritto in `Corrective Actions` nel campo dell'avviso.
+
Le azioni correttive potrebbero includere il riavvio del sistema.

+
Una volta risolto il problema, l'avviso viene cancellato automaticamente. Se il sottosistema non dispone di altri avvisi, lo stato del sottosistema cambia in `OK`. Se lo stato di tutti i sottosistemi è corretto, lo stato generale del sistema diventa `OK`.

. Utilizzare `system health status show` per confermare che lo stato di salute del sistema è `OK`.
+
Se lo stato di salute del sistema non è `OK`, ripetere questa procedura.



.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/system-health-alert-modify.html["modifica avviso integrità sistema"^]

