---
permalink: system-admin/rules-specifying-values-concept.html 
sidebar: sidebar 
keywords: rules, specifying, values, cli, parameters, required, optional 
summary: La maggior parte dei comandi include uno o più parametri obbligatori o opzionali. Molti parametri richiedono di specificare un valore per essi. Esistono alcune regole per specificare i valori nella CLI. 
---
= Regole per specificare i valori nella CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La maggior parte dei comandi include uno o più parametri obbligatori o opzionali. Molti parametri richiedono di specificare un valore per essi. Esistono alcune regole per specificare i valori nella CLI.

* Un valore può essere un numero, un identificatore booleano, una selezione da un elenco enumerato di valori predefiniti o una stringa di testo.
+
Alcuni parametri possono accettare un elenco separato da virgole di due o più valori. Gli elenchi di valori separati da virgole non devono essere tra virgolette (" "). Ogni volta che si specifica il testo, uno spazio o un carattere di query (quando non si intende una query o un testo che inizia con un simbolo minore o maggiore di), è necessario racchiudere l'entità tra virgolette.

* L'interfaccia CLI interpreta un punto interrogativo ("`?`") come comando per visualizzare le informazioni della guida per un determinato comando.
* Alcuni testi immessi nella CLI, come i nomi dei comandi, i parametri e alcuni valori, non fanno distinzione tra maiuscole e minuscole.
+
Ad esempio, quando si immettono i valori dei parametri per `vserver cifs` comandi, le maiuscole vengono ignorate. Tuttavia, la maggior parte dei valori dei parametri, come i nomi dei nodi, le macchine virtuali di storage (SVM), gli aggregati, i volumi e le interfacce logiche, è sensibile al maiuscolo/minuscolo.

* Se si desidera cancellare il valore di un parametro che prende una stringa o un elenco, specificare un set vuoto di virgolette ("") o un trattino ("-").
* Il simbolo cancelletto ("` n.`"), noto anche come simbolo cancelletto, indica un commento per un input della riga di comando; se utilizzato, dovrebbe essere visualizzato dopo l'ultimo parametro in una riga di comando.
+
L'interfaccia CLI ignora il testo tra "` n.`" e la fine della riga.



Nell'esempio seguente, viene creata una SVM con un commento di testo. La SVM viene quindi modificata per eliminare il commento:

[listing]
----
cluster1::> vserver create -vserver vs0 -subtype default -rootvolume root_vs0
-aggregate aggr1 -rootvolume-security-style unix -language C.UTF-8 -is-repository false -ipspace ipspaceA -comment "My SVM"
cluster1::> vserver modify -vserver vs0 -comment ""
----
Nell'esempio seguente, un commento della riga di comando che utilizza il segno "` n.`" indica la funzione del comando.

[listing]
----
cluster1::> security login create -vserver vs0 -user-or-group-name new-admin
-application ssh -authmethod password #This command creates a new user account
----