---
permalink: system-admin/start-stop-storage-system-concept.html 
sidebar: sidebar 
keywords: start, stop, node, cli, ontap, troubleshoot, sp, reboot, system, boot, compactflash, shut down, shutdown,  unresponsive, shut, down, node, unresponsive, support, personnel, direct, troubleshoot 
summary: 'Potrebbe essere necessario avviare o arrestare un nodo per motivi di manutenzione o risoluzione dei problemi. È possibile eseguire questa operazione dall"interfaccia utente di ONTAP, dal prompt dell"ambiente di avvio o dall"interfaccia utente di SP.' 
---
= Avviare o interrompere un nodo ONTAP per la manutenzione o il troubleshooting
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario avviare o arrestare un nodo per motivi di manutenzione o risoluzione dei problemi. È possibile eseguire questa operazione dall'interfaccia utente di ONTAP, dal prompt dell'ambiente di avvio o dall'interfaccia utente di SP.

Utilizzando il comando SP CLI `system power off` oppure `system power cycle` Per spegnere o spegnere e riaccendere un nodo potrebbe causare un arresto non corretto del nodo (chiamato anche _shutdown anomalo_) e non sostituire un arresto corretto mediante ONTAP `system node halt` comando.



== Riavviare un nodo al prompt del sistema

È possibile riavviare un nodo in modalità normale dal prompt di sistema. Un nodo è configurato per l'avvio dal dispositivo di avvio, ad esempio una scheda PC CompactFlash.

.Fasi
. Se il cluster contiene quattro o più nodi, verificare che il nodo da riavviare non contenga epsilon:
+
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`*set -privilege advanced*`

.. Determinare quale nodo contiene epsilon:
+
`*cluster show*`

+
Il seguente esempio mostra che "`node1`" contiene epsilon:

+
[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          true
node2                true    true          false
node3                true    true          false
node4                true    true          false
4 entries were displayed.
----
.. Se il nodo da riavviare contiene epsilon, rimuovere epsilon dal nodo:
+
`*cluster modify -node _node_name_ -epsilon false*`

.. Assegnare epsilon a un nodo diverso che rimarrà attivo:
+
`*cluster modify -node _node_name_ -epsilon true*`

.. Tornare al livello di privilegio admin:
+
`*set -privilege admin*`



. Utilizzare `system node reboot` comando per riavviare il nodo.
+
Se non si specifica `-skip-lif-migration` Il comando tenta di migrare i dati e le LIF di gestione del cluster in modo sincrono su un altro nodo prima del riavvio. Se la migrazione LIF non riesce o si interrompe, il processo di riavvio viene interrotto e ONTAP visualizza un errore per indicare che la migrazione LIF non è riuscita.

+
[listing]
----
cluster1::> system node reboot -node node1 -reason "software upgrade"
----
+
Il nodo avvia il processo di riavvio. Viene visualizzato il prompt di accesso di ONTAP, che indica che il processo di riavvio è stato completato.





== Boot ONTAP al prompt dell'ambiente di boot

È possibile avviare la release corrente o la release di backup di ONTAP quando si è al prompt dell'ambiente di boot di un nodo.

.Fasi
. Accedere al prompt dell'ambiente di boot dal prompt del sistema di storage utilizzando `system node halt` comando.
+
La console del sistema di storage visualizza il prompt dell'ambiente di boot.

. Al prompt dell'ambiente di boot, immettere uno dei seguenti comandi:
+
|===
| Per avviare... | Inserisci... 


 a| 
L'attuale release di ONTAP
 a| 
`boot_ontap`



 a| 
L'immagine principale di ONTAP dal dispositivo di avvio
 a| 
`boot_primary`



 a| 
Immagine di backup di ONTAP dal dispositivo di avvio
 a| 
`boot_backup`

|===
+
In caso di dubbi sull'immagine da utilizzare, è necessario utilizzarla `boot_ontap` in primo luogo.





== Chiudere un nodo

È possibile arrestare un nodo se non risponde o se il personale di supporto lo ha indicato come parte delle attività di risoluzione dei problemi.

.Fasi
. Se il cluster contiene quattro o più nodi, verificare che il nodo da arrestare non contenga epsilon:
+
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`*set -privilege advanced*`

.. Determinare quale nodo contiene epsilon:
+
`*cluster show*`

+
Il seguente esempio mostra che "`node1`" contiene epsilon:

+
[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          true
node2                true    true          false
node3                true    true          false
node4                true    true          false
4 entries were displayed.
----
.. Se il nodo da spegnere contiene epsilon, rimuovere epsilon dal nodo:
+
`*cluster modify -node _node_name_ -epsilon false*`

.. Assegnare epsilon a un nodo diverso che rimarrà attivo:
+
`*cluster modify -node _node_name_ -epsilon true*`

.. Tornare al livello di privilegio admin:
+
`*set -privilege admin*`



. Utilizzare `system node halt` comando per arrestare il nodo.
+
Se non si specifica `-skip-lif-migration` Il comando tenta di migrare i dati e le LIF di gestione del cluster in modo sincrono su un altro nodo prima dello shutdown. Se la migrazione LIF non riesce o va in timeout, il processo di arresto viene interrotto e ONTAP visualizza un errore per indicare che la migrazione LIF non è riuscita.

+
È possibile attivare manualmente un core dump con lo shutdown utilizzando entrambi `-dump` parametro.

+
Nell'esempio seguente viene chiuso il nodo "`node1`" per la manutenzione dell'hardware:

+
[listing]
----
cluster1::> system node halt -node node1 -reason 'hardware maintenance'
----

