---
permalink: system-admin/system-volumes-concept.html 
sidebar: sidebar 
keywords: system, volume, flexvol, metadata, file, services, audit, logs, account, storage, cluster 
summary: 'I volumi di sistema sono volumi FlexVol che contengono metadati speciali, ad esempio metadati per i log di audit dei servizi file. Questi volumi sono visibili nel cluster in modo da poter tenere pienamente conto dell"utilizzo dello storage nel cluster.' 
---
= Visualizzazione dell'utilizzo della capacità di storage dei volumi di sistema in un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I volumi di sistema sono volumi FlexVol che contengono metadati speciali, ad esempio metadati per i log di audit dei servizi file. Questi volumi sono visibili nel cluster in modo da poter tenere pienamente conto dell'utilizzo dello storage nel cluster.

I volumi di sistema sono di proprietà del server di gestione del cluster (chiamato anche SVM di amministrazione) e vengono creati automaticamente quando viene attivato il controllo dei file service.

È possibile visualizzare i volumi di sistema utilizzando `volume show` ma la maggior parte delle altre operazioni del volume non è consentita. Ad esempio, non è possibile modificare un volume di sistema utilizzando `volume modify` comando.

Questo esempio mostra quattro volumi di sistema sulla SVM amministrativa, che sono stati creati automaticamente quando è stato attivato il controllo dei servizi file per una SVM di dati nel cluster:

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          2GB     1.90GB    5%
4 entries were displayed.
----