---
permalink: system-admin/troubleshoot-autosupport-subsystem-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, subsystem, node, check, show, command, issue, problem, delivery 
summary: 'È possibile utilizzare i comandi di controllo del nodo di sistema per verificare e risolvere eventuali problemi relativi alla configurazione e all"erogazione di AutoSupport.' 
---
= Eseguire la risoluzione dei problemi del sottosistema ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `system node check show` I comandi possono essere utilizzati per verificare e risolvere eventuali problemi relativi alla configurazione e all'erogazione di AutoSupport.

.Fase
. Utilizzare i seguenti comandi per visualizzare lo stato del sottosistema AutoSupport.
+
|===
| Utilizzare questo comando... | A tal fine... 


 a| 
`system node autosupport check show`
 a| 
Visualizzare lo stato generale del sottosistema AutoSupport, ad esempio lo stato della destinazione AutoSupport HTTPS, le destinazioni SMTP AutoSupport, il server AutoSupport OnDemand e la configurazione AutoSupport



 a| 
`system node autosupport check show-details`
 a| 
Visualizza lo stato dettagliato del sottosistema AutoSupport, ad esempio descrizioni dettagliate degli errori e delle azioni correttive

|===

