---
permalink: system-admin/troubleshoot-web-access-problems-concept.html 
sidebar: sidebar 
keywords: troubleshoot, web, services, access, problems, lif, firewall, policy, protocol, engin, digital, certificate, user, access, authorization 
summary: 'Gli errori di configurazione causano problemi di accesso al servizio Web. È possibile risolvere gli errori assicurandosi che LIF, policy firewall, motore del protocollo web, servizi web, certificati digitali, e l"autorizzazione all"accesso dell"utente sono tutte configurate correttamente.' 
---
= Risolvere i problemi di accesso al servizio Web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli errori di configurazione causano problemi di accesso al servizio Web. È possibile risolvere gli errori assicurandosi che LIF, policy firewall, motore del protocollo web, servizi web, certificati digitali, e l'autorizzazione all'accesso dell'utente sono tutte configurate correttamente.

La seguente tabella consente di identificare e risolvere gli errori di configurazione del servizio Web:

|===
| Questo problema di accesso... | Si verifica a causa di questo errore di configurazione... | Per risolvere l'errore... 


 a| 
Il browser Web restituisce un `unable to connect` oppure `failure to establish a connection` errore quando si tenta di accedere a un servizio web.
 a| 
La LIF potrebbe non essere configurata correttamente.
 a| 
Assicurarsi di poter eseguire il ping della LIF che fornisce il servizio Web.

[NOTE]
====
Si utilizza `network ping` Comando per eseguire il ping di una LIF. Per informazioni sulla configurazione di rete, consultare la _Guida alla gestione di rete_.

====


 a| 
Il firewall potrebbe non essere configurato correttamente.
 a| 
Assicurarsi che un criterio firewall sia impostato per supportare HTTP o HTTPS e che il criterio sia assegnato alla LIF che fornisce il servizio Web.

[NOTE]
====
Si utilizza `system services firewall policy` comandi per gestire le policy firewall. Si utilizza `network interface modify` con il `-firewall-policy` Parametro per associare un criterio a un LIF.

====


 a| 
Il motore del protocollo Web potrebbe essere disattivato.
 a| 
Assicurarsi che il motore dei protocolli Web sia abilitato in modo da poter accedere ai servizi Web.

[NOTE]
====
Si utilizza `system services web` comandi per gestire il motore del protocollo web per il cluster.

====


 a| 
Il browser Web restituisce un `not found` errore quando si tenta di accedere a un servizio web.
 a| 
Il servizio Web potrebbe essere disattivato.
 a| 
Assicurarsi che ogni servizio Web a cui si desidera consentire l'accesso sia attivato singolarmente.

[NOTE]
====
Si utilizza `vserver services web modify` per abilitare un servizio web per l'accesso.

====


 a| 
Il browser Web non riesce ad accedere a un servizio Web con il nome account e la password dell'utente.
 a| 
L'utente non può essere autenticato, il metodo di accesso non è corretto o non è autorizzato ad accedere al servizio Web.
 a| 
Assicurarsi che l'account utente esista e sia configurato con il metodo di accesso e di autenticazione corretti. Inoltre, assicurarsi che il ruolo dell'utente sia autorizzato ad accedere al servizio Web.

[NOTE]
====
Si utilizza `security login` comandi per gestire gli account utente, i relativi metodi di accesso e i metodi di autenticazione. L'accesso al servizio Web API di ONTAP richiede `ontapi` metodo di accesso. L'accesso a tutti gli altri servizi Web richiede `http` metodo di accesso. Si utilizza `vserver services web access` comandi per gestire l'accesso di un ruolo a un servizio web.

====


 a| 
Si effettua la connessione al servizio Web con HTTPS e il browser Web indica che la connessione è stata interrotta.
 a| 
È possibile che SSL non sia abilitato sul cluster o sulla SVM (Storage Virtual Machine) che fornisce il servizio Web.
 a| 
Assicurarsi che il cluster o la SVM abbia abilitato SSL e che il certificato digitale sia valido.

[NOTE]
====
Si utilizza `security ssl` Comandi per gestire la configurazione SSL per i server HTTP e il `security certificate show` per visualizzare le informazioni del certificato digitale.

====


 a| 
La connessione al servizio Web viene stabilita con HTTPS e il browser Web indica che la connessione non è attendibile.
 a| 
È possibile che si stia utilizzando un certificato digitale autofirmato.
 a| 
Assicurarsi che il certificato digitale associato al cluster o alla SVM sia firmato da una CA attendibile.

[NOTE]
====
Si utilizza `security certificate generate-csr` per generare una richiesta di firma digitale del certificato e il `security certificate install` Comando per installare un certificato digitale firmato dalla CA. Si utilizza `security ssl` Comandi per gestire la configurazione SSL per il cluster o SVM che fornisce il servizio Web.

====
|===
.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["ping di rete"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["modifica dell'interfaccia di rete"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-generate-csr.html["certificato di sicurezza generate-csr"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["installazione del certificato di sicurezza"^]

