---
permalink: system-admin/types-autosupport-messages-reference.html 
sidebar: sidebar 
keywords: active, iq, active iq, digital advisor, autosupport, messages, content, support, subsystems 
summary: I messaggi AutoSupport contengono informazioni sullo stato dei sottosistemi supportati. Imparare cosa contengono i messaggi AutoSupport può aiutare a interpretare o rispondere ai messaggi ricevuti tramite e-mail o visualizzati sul sito Web di Digital Advisor. 
---
= Tipi di messaggi ONTAP AutoSupport e relativo contenuto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi AutoSupport contengono informazioni sullo stato dei sottosistemi supportati. Imparare cosa contengono i messaggi AutoSupport può aiutare a interpretare o rispondere ai messaggi ricevuti tramite e-mail o visualizzati sul sito Web di Digital Advisor.

|===
| Tipo di messaggio | Tipo di dati contenuti nel messaggio 


 a| 
Attivato da eventi
 a| 
File contenenti dati sensibili al contesto relativi al sottosistema specifico in cui si è verificato l'evento



 a| 
Ogni giorno
 a| 
File di log



 a| 
Performance
 a| 
Dati sulle performance campionati durante le 24 ore precedenti



 a| 
Settimanale
 a| 
Dati di configurazione e stato



 a| 
Attivato da `system node autosupport invoke` comando
 a| 
Dipende dal valore specificato in `-type` parametro:

* `test` invia un messaggio attivato dall'utente con alcuni dati di base.
+
Questo messaggio attiva anche una risposta email automatica dal supporto tecnico a qualsiasi indirizzo email specificato, utilizzando `-to` Per confermare la ricezione dei messaggi AutoSupport.

* `performance` invia i dati delle performance.
* `all` invia un messaggio attivato dall'utente con una serie completa di dati simili al messaggio settimanale, inclusi i dati di risoluzione dei problemi di ciascun sottosistema.
+
Il supporto tecnico in genere richiede questo messaggio.





 a| 
Attivato da `system node autosupport invoke-core-upload` comando
 a| 
File core dump per un nodo



 a| 
Attivato da `system node autosupport invoke-performance-archive` comando
 a| 
File di archiviazione delle performance per un periodo di tempo specificato



 a| 
Attivato da AutoSupport OnDemand
 a| 
AutoSupport OnDemand può richiedere nuovi messaggi o messaggi precedenti:

* I nuovi messaggi, a seconda del tipo di raccolta AutoSupport, possono essere `test`, `all`, o. `performance`.
* I messaggi passati dipendono dal tipo di messaggio che viene inviato nuovamente.


AutoSupport OnDemand può richiedere nuovi messaggi che caricano i seguenti file sul sito di supporto NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^]:

* Core dump
* Archivio delle performance


|===