---
permalink: system-admin/view-default-certificates-tls-based-applications-task.html 
sidebar: sidebar 
keywords: view, default, certificates, tls, applications, transport 
summary: 'A partire da ONTAP 9.2, ONTAP fornisce un set predefinito di certificati root attendibili per le applicazioni ONTAP che utilizzano TLS (Transport Layer Security).' 
---
= Visualizza i certificati predefiniti per le applicazioni basate su TLS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.2, ONTAP fornisce un set predefinito di certificati root attendibili per le applicazioni ONTAP che utilizzano TLS (Transport Layer Security).

.Di cosa hai bisogno
I certificati predefiniti vengono installati solo sulla SVM amministrativa durante la creazione o durante un aggiornamento a ONTAP 9.2.

.A proposito di questa attività
Le applicazioni correnti che agiscono come client e richiedono la convalida dei certificati sono AutoSupport, EMS, LDAP, registrazione degli audit, FabricPool, E KMIP.

Quando i certificati scadono, viene richiamato un messaggio EMS che richiede all'utente di eliminarli. I certificati predefiniti possono essere eliminati solo al livello di privilegio avanzato.

[NOTE]
====
L'eliminazione dei certificati predefiniti potrebbe causare il mancato funzionamento di alcune applicazioni ONTAP (ad esempio, AutoSupport e registrazione audit).

====
.Fase
. È possibile visualizzare i certificati predefiniti installati sulla SVM amministrativa utilizzando il comando show del certificato di protezione:
+
`*security certificate show -vserver –type server-ca*`

+
[listing]
----

fas2552-2n-abc-3::*> security certificate show -vserver fas2552-2n-abc-3 -type server-ca
Vserver    Serial Number   Common Name                            Type
---------- --------------- -------------------------------------- ------------
fas2552-2n-abc-3
           01              AAACertificateServices                 server-ca
    Certificate Authority: AAA Certificate Services
          Expiration Date: Sun Dec 31 18:59:59 2028
----

