---
permalink: system-admin/view-default-certificates-tls-based-applications-task.html 
sidebar: sidebar 
keywords: view, default, certificates, tls, applications, transport 
summary: 'ONTAP fornisce un set predefinito di certificati radice attendibili per le applicazioni ONTAP che utilizzano Transport Layer Security (TLS).' 
---
= Visualizza i certificati predefiniti per le applicazioni basate su TLS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP fornisce un set predefinito di certificati radice attendibili per le applicazioni ONTAP che utilizzano Transport Layer Security (TLS).

.Prima di iniziare
I certificati predefiniti vengono installati solo sull'SVM di amministrazione durante la sua creazione o durante un aggiornamento.

.A proposito di questa attività
Le applicazioni correnti che agiscono come client e richiedono la convalida dei certificati sono AutoSupport, EMS, LDAP, registrazione degli audit, FabricPool, E KMIP.

Quando i certificati scadono, viene richiamato un messaggio EMS che richiede all'utente di eliminarli. I certificati predefiniti possono essere eliminati solo al livello di privilegio avanzato.

[NOTE]
====
L'eliminazione dei certificati predefiniti potrebbe causare il mancato funzionamento di alcune applicazioni ONTAP (ad esempio, AutoSupport e registrazione audit).

====
.Fase
. È possibile visualizzare i certificati predefiniti installati sulla SVM amministrativa utilizzando il comando show del certificato di protezione:
+
`*security certificate show -vserver –type server-ca*`

+
[listing]
----
cluster1::> security certificate show

Vserver    Serial Number   Certificate Name                          Type
---------- --------------- ----------------------------------------- ---------
vs0        4F4E4D7B         www.example.com                            server
    Certificate Authority:  www.example.com
          Expiration Date: Thu Feb 28 16:08:28 2013
----
+
Ulteriori informazioni su `security certificate show` nella link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html?q=show["Riferimento al comando ONTAP"^].


