---
permalink: authentication/configure-nis-server-access-task.html 
sidebar: sidebar 
keywords: configure, nis server, access 
summary: 'È necessario configurare l"accesso del server NIS a una SVM prima che gli account NIS possano accedere alla SVM. È possibile utilizzare il comando name-service nis-domain create dei servizi vserver per creare una configurazione di dominio NIS su una SVM.' 
---
= Configurare l'accesso al server NIS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare l'accesso del server NIS a una SVM prima che gli account NIS possano accedere alla SVM. È possibile utilizzare `vserver services name-service nis-domain create` Per creare una configurazione di dominio NIS su una SVM.

.Di cosa hai bisogno
* Tutti i server configurati devono essere disponibili e accessibili prima di configurare il dominio NIS sulla SVM.
* Per eseguire questa attività, è necessario essere un amministratore del cluster o di SVM.


.A proposito di questa attività
È possibile creare più domini NIS. È possibile impostare un solo dominio NIS su `active` alla volta.

.Fase
. Creare una configurazione di dominio NIS su una SVM: `vserver services name-service nis-domain create -vserver SVM_name -domain client_configuration -active true|false -nis-servers NIS_server_IPs`
+
Per la sintassi completa dei comandi, vedere link:config-worksheets-reference.html["foglio di lavoro"].

+
[NOTE]
====
A partire da ONTAP 9.2, il campo `-nis-servers` sostituisce il campo `-servers`. Questo nuovo campo può includere un nome host o un indirizzo IP per il server NIS.

====
+
Il seguente comando crea una configurazione di dominio NIS su SVM ``engData``. Il dominio NIS `nisdomain` È attivo al momento della creazione e comunica con un server NIS con l'indirizzo IP `192.0.2.180`.

+
[listing]
----
cluster1::>vserver services name-service nis-domain create
-vserver engData -domain nisdomain -active true -nis-servers 192.0.2.180
----

