---
permalink: authentication/create-svm-computer-account-domain-task.html 
sidebar: sidebar 
keywords: create, svm, computer, account, domain, cifs server 
summary: Se non è stato configurato un server SMB per una SVM di dati, è possibile utilizzare il comando vserver Active-directory create per creare un account di computer per la SVM nel dominio. 
---
= Creare un account di computer SVM sul dominio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se non è stato configurato un server SMB per una SVM dati, è possibile utilizzare `vserver active-directory create` Per creare un account di computer per la SVM nel dominio.

.Di cosa hai bisogno
Per eseguire questa attività, è necessario essere un amministratore del cluster o di SVM.

.A proposito di questa attività
Dopo aver inserito `vserver active-directory create` Viene richiesto di fornire le credenziali per un account utente ad con privilegi sufficienti per aggiungere computer all'unità organizzativa specificata nel dominio. La password dell'account non può essere vuota.

.Fase
. Creare un account di computer per una SVM nel dominio ad:
+
`vserver active-directory create -vserver _SVM_name_ -account-name _NetBIOS_account_name_ -domain _domain_ -ou _organizational_unit_`

+
Per la sintassi completa dei comandi, vedere link:config-worksheets-reference.html["foglio di lavoro"].

+
Il seguente comando crea un account di computer denominato `ADSERVER1` sul dominio `example.com` Per SVM `engData`. Dopo aver immesso il comando, viene richiesto di immettere le credenziali dell'account utente ad.

+
[listing]
----
cluster1::>vserver active-directory create -vserver engData -account-name ADSERVER1 -domain example.com

In order to create an Active Directory machine account, you must supply the name and password of a Windows account with sufficient privileges to add computers to the "CN=Computers" container within the "example.com" domain.

Enter the user name: Administrator

Enter the password:
----

