---
permalink: authentication/dynamic-authorization-overview.html 
sidebar: sidebar 
keywords: dynamic, authorization, framework, security, login, ssh 
summary: 'Configurare il framework di autorizzazione dinamica per aumentare la sicurezza degli accessi SSH e limitare l"esecuzione di determinati comandi in circostanze sospette.' 
---
= Ulteriori informazioni sull'autorizzazione dinamica di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.15.1, gli amministratori possono configurare e abilitare l'autorizzazione dinamica per aumentare la sicurezza dell'accesso remoto a ONTAP, riducendo al contempo i potenziali danni che potrebbero essere causati da un soggetto malintenzionato. Con ONTAP 9.15.1, l'autorizzazione dinamica fornisce un framework iniziale per assegnare un punteggio di sicurezza agli utenti e, se la loro attività sembra sospetta, sfidarli con ulteriori controlli di autorizzazione o negare completamente un'operazione. Gli amministratori possono creare regole, assegnare punteggi di attendibilità e limitare comandi per determinare quando determinate attività sono consentite o negate per un utente. Gli amministratori possono abilitare l'autorizzazione dinamica per tutto il cluster o per singole macchine virtuali storage.



== Come funziona l'autorizzazione dinamica

L'autorizzazione dinamica utilizza un sistema di punteggio di attendibilità per assegnare agli utenti un livello di attendibilità diverso a seconda dei criteri di autorizzazione. In base al livello di attendibilità dell'utente, è possibile consentire o negare un'attività da eseguire oppure richiedere un'ulteriore autenticazione.

Per link:configure-dynamic-authorization.html["Personalizzare l'autorizzazione dinamica"]ulteriori informazioni su come configurare i pesi dei punteggi dei criteri e altri attributi di autorizzazione dinamici, consultare la sezione.



=== Periferiche di fiducia

Quando si utilizza l'autorizzazione dinamica, la definizione di una periferica attendibile è una periferica utilizzata da un utente per accedere a ONTAP utilizzando l'autenticazione a chiave pubblica come uno dei metodi di autenticazione. Il dispositivo è attendibile perché solo quell'utente dispone della chiave privata corrispondente.



=== Esempio di autorizzazione dinamica

Prendiamo ad esempio tre utenti che tentano di eliminare un volume. Quando tentano di eseguire l'operazione, viene esaminato il livello di rischio per ciascun utente:

* Il primo utente accede da un dispositivo attendibile con pochissimi errori di autenticazione precedenti, il che rende basso il livello di rischio; l'operazione è consentita senza autenticazione aggiuntiva.
* Il secondo utente accede da un dispositivo attendibile con una percentuale moderata di errori di autenticazione precedenti, il che rende moderato il livello di rischio; viene richiesta un'autenticazione aggiuntiva prima che l'operazione venga consentita.
* Il terzo utente accede da un dispositivo non attendibile con un'alta percentuale di errori di autenticazione precedenti, il che rende il livello di rischio elevato; l'operazione non è consentita.


.Cosa succederà
* link:enable-disable-dynamic-authorization.html["Attiva o disattiva l'autorizzazione dinamica"]
* link:configure-dynamic-authorization.html["Personalizzare l'autorizzazione dinamica"]

