---
permalink: authentication/enable-password-account-access-task.html 
sidebar: sidebar 
keywords: enable, password, account, access 
summary: È possibile utilizzare il comando Security login create per consentire agli account amministratore di accedere a un amministratore o a una SVM dati con una password. La password viene richiesta dopo aver immesso il comando. 
---
= Attiva l'accesso alla password dell'account ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi utilizzare `security login create` il comando per abilitare gli account amministratore per l'accesso a una SVM di amministrazione o dati con una password. La password viene richiesta dopo aver immesso il comando. Ulteriori informazioni su `security login create` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["Riferimento al comando ONTAP"^].

.A proposito di questa attività
Se non si è certi del ruolo di controllo dell'accesso che si desidera assegnare all'account di accesso, è possibile utilizzare il `security login modify` comando per aggiungere il ruolo in un secondo momento. Ulteriori informazioni su `security login modify` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["Riferimento al comando ONTAP"^].

.Prima di iniziare
Per eseguire questa attività, è necessario essere un amministratore del cluster.

.Fase
. Abilitare gli account dell'amministratore locale per accedere a una SVM utilizzando una password:
+
`security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_`

+
Il seguente comando attiva l'account amministratore del cluster `admin1` con il predefinito `backup` Ruolo di accesso alla SVM amministrativa``engCluster`` utilizzo di una password. La password viene richiesta dopo aver immesso il comando.

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name admin1 -application ssh -authmethod password -role backup
----

