---
permalink: authentication/lock-unlock-user-account-task.html 
sidebar: sidebar 
keywords: lock, unlock, administrator account 
summary: 'È possibile utilizzare il comando di blocco dell"accesso di sicurezza per bloccare un account amministratore e il comando di sblocco dell"accesso di sicurezza per sbloccare l"account.' 
---
= Bloccare e sbloccare un account amministratore di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `security login lock` per bloccare un account amministratore e il `security login unlock` per sbloccare l'account.

.Prima di iniziare
Per eseguire queste attività, è necessario essere un amministratore del cluster.

.Fasi
. Blocco di un account amministratore:
+
`security login lock -vserver SVM_name -username user_name`

+
Il seguente comando blocca l'account amministratore `admin1` Per SVM ``vs1.example.com``:

+
[listing]
----
cluster1::>security login lock -vserver engData -username admin1
----
+
Ulteriori informazioni su `security login lock` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-lock.html["Riferimento al comando ONTAP"^].

. Sbloccare un account amministratore:
+
`security login unlock -vserver SVM_name -username user_name`

+
Il seguente comando sblocca l'account amministratore `admin1` Per SVM ``vs1.example.com``:

+
[listing]
----
cluster1::>security login unlock -vserver engData -username admin1
----
+
Ulteriori informazioni su `security login unlock` nella link:https://docs.netapp.com/us-en/ontap-cli/security-login-unlock.html["Riferimento al comando ONTAP"^].



.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["accesso di sicurezza"^]

