---
permalink: authentication/predefined-roles-cluster-administrators-concept.html 
sidebar: sidebar 
keywords: predefined roles, cluster administrators 
summary: I ruoli predefiniti per gli amministratori dei cluster devono soddisfare la maggior parte delle esigenze. È possibile creare ruoli personalizzati in base alle necessità. Per impostazione predefinita, a un amministratore del cluster viene assegnato il ruolo di amministratore predefinito. 
---
= Ruoli predefiniti per gli amministratori del cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I ruoli predefiniti per gli amministratori dei cluster devono soddisfare la maggior parte delle esigenze. È possibile creare ruoli personalizzati in base alle necessità. Per impostazione predefinita, a un amministratore del cluster viene assegnato il valore predefinito `admin` ruolo.

La seguente tabella elenca i ruoli predefiniti per gli amministratori del cluster:

|===


| Questo ruolo... | Dispone di questo livello di accesso... | Alle seguenti directory di comandi o comandi 


 a| 
amministratore
 a| 
tutto
 a| 
Tutte le directory dei comandi (`DEFAULT`)



 a| 
admin-no-fsa (disponibile a partire da ONTAP 9.12.1)
 a| 
Lettura/scrittura
 a| 
* Tutte le directory dei comandi (`DEFAULT`)
* `security login rest-role`
* `security login role`




 a| 
Di sola lettura
 a| 
* `security login rest-role create`
* `security login rest-role delete`
* `security login rest-role modify`
* `security login rest-role show`
* `security login role create`
* `security login role create`
* `security login role delete`
* `security login role modify`
* `security login role show`
* `volume activity-tracking`
* `volume analytics`




 a| 
Nessuno
 a| 
`volume file show-disk-usage`



 a| 
AutoSupport
 a| 
tutto
 a| 
* `set`
* `system node autosupport`




 a| 
nessuno
 a| 
Tutte le altre directory di comando (`DEFAULT`)



 a| 
backup
 a| 
tutto
 a| 
`vserver services ndmp`



 a| 
readonly
 a| 
`volume`



 a| 
nessuno
 a| 
Tutte le altre directory di comando (`DEFAULT`)



 a| 
readonly
 a| 
tutto
 a| 
* `security login password`
+
Solo per la gestione della password locale del proprio account utente e delle informazioni sulle chiavi

* `set`




 a| 
* A partire da ONTAP 9,8, sola lettura
* Prima di ONTAP 9,8, nessuno

 a| 
`security`



 a| 
readonly
 a| 
Tutte le altre directory di comando (`DEFAULT`)



 a| 
SnapLock
 a| 
tutto
 a| 
* `set`
* `volume create`
* `volume modify`
* `volume move`
* `volume show`




 a| 
nessuno
 a| 
* `volume move governor`
* `volume move recommend`




 a| 
nessuno
 a| 
Tutte le altre directory di comando (`DEFAULT`)



 a| 
nessuno
 a| 
nessuno
 a| 
Tutte le directory dei comandi (`DEFAULT`)

|===

NOTE: Il `autosupport` il ruolo viene assegnato al predefinito `autosupport` Account, utilizzato da AutoSupport OnDemand. ONTAP impedisce di modificare o eliminare `autosupport` account. ONTAP impedisce inoltre l'assegnazione di `autosupport` ruolo per altri account utente.

.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["accesso di sicurezza"^]
* link:https://docs.netapp.com/us-en/ontap-cli/set.html["partenza"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume["volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+ndmp["servizi vserver ndmp"^]

