---
permalink: authentication/reset-totp-configuration-task.html 
sidebar: sidebar 
keywords: enable, ssh, multifactor authentication, mfa, hardware authentication device 
summary: Per proteggere la sicurezza del tuo account, se la tua chiave segreta TOTP viene compromessa o persa, devi disattivarla e crearne una nuova. 
---
= Reimpostare la chiave segreta TOTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per proteggere la sicurezza del tuo account, se la tua chiave segreta TOTP viene compromessa o persa, devi disattivarla e crearne una nuova.



== Reimpostare il TOTP se la chiave viene compromessa

Se la chiave segreta TOTP è compromessa, ma si dispone ancora dell'accesso, è possibile rimuovere la chiave compromessa e crearne una nuova.

. Accedere all'account utente con la password utente o la chiave pubblica SSH e la chiave segreta TOTP compromessa.
. Rimuovere la chiave segreta TOTP compromessa:
+
[source, cli]
----
security login totp delete -vserver <svm_name> -username <account_username>
----
. Creare una nuova chiave segreta TOTP:
+
[source, cli]
----
security login totp create -vserver <svm_name> -username <account_username>
----
. Verificare che la configurazione TOTP sia attivata sull'account:
+
[source, cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----




== Ripristinare il TOTP se la chiave viene persa

Se la chiave segreta TOTP viene persa, contattare l'amministratore dello storage per link:disable-totp-secret-key-task.html["disattivare la chiave"]. Una volta disattivata la chiave, è possibile utilizzare il primo metodo di autenticazione per accedere e configurare un nuovo TOTP.

.Prima di iniziare
La chiave segreta TOTP deve essere disattivata da un amministratore dello storage. Se non si dispone di un account amministratore dello storage, contattare l'amministratore dello storage per disattivare la chiave.

.Fasi
. Una volta disattivato il segreto TOTP da un amministratore dello storage, utilizzare il metodo di autenticazione principale per accedere all'account locale.
. Creare una nuova chiave segreta TOTP:
+
[source, cli]
----
security login totp create -vserver <svm_name> -username <account_username >
----
. Verificare che la configurazione TOTP sia attivata sull'account:
+
[source, cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----

